const fs = require('fs');

const OUTPUT_BATCH_FILE = 'jobs/output_batch.json';
let outputs = JSON.parse(fs.readFileSync(OUTPUT_BATCH_FILE, 'utf8'));

outputs.push({
  "id": "00397",
  "group": "dialog",
  "strings": [
    { "source": "But they want some kinda 'neutral observer' or whatever the fuck. Job figured maybe you'd put their minds at ease.", "translation": "Họ muốn 'người giám sát độc lập' chó đẻ gì đó. Job nghĩ bạn sẽ khiến họ an tâm." },
    { "source": "What do you say? You'll get a cut of the deal, of course - provided it all goes according to plan.", "translation": "Sao nào? Bạn sẽ có phần nếu mọi việc êm xuôi." },
    { "source": "Great. Here's the address. You pick up the folks at the ranch, make sure they get there okay.", "translation": "Tuyệt. Địa chỉ đây. Đón người ở nông trại." },
    { "source": "Mickey and Job will meet you there.", "translation": "Mickey và Job sẽ gặp bạn ở đó." },
    { "source": "Fair enough. If you change your mind, though, here's the address.", "translation": "Công bằng. Nếu đổi ý thì địa chỉ đây." },
    { "source": "Dammit, boy, what the hell are you thinking? What you think Pa would say about this? Huh? What about Eli?", "translation": "Chết tiệt, nghĩ gì vậy? Cha sẽ nói gì? Còn Eli nữa?" },
    { "source": "They're not here. We are. And we gotta think about what comes next.", "translation": "Họ chết rồi. Chúng ta phải lo cho tương lai." },
    { "source": "I don't give a shit! I ain't never had to pay for it, and I ain't never had to take it that way neither!", "translation": "Đéo quan tâm! Tao chưa từng trả tiền cho chuyện đó, và tao sẽ đéo bao giờ lấy nó kiểu đó!" },
    { "source": "Sure as shit ain't about to start now.", "translation": "Chắc chắn là không phải lúc này." },
    { "source": "Yeah, and I'm sure Romulus' followers felt the same way, but we all know what happened to the Sabines.", "translation": "Chắc bọn Romulus cũng nghĩ thế, nhưng biết điều gì xảy ra với Sabines rồi đấy." },
    { "source": "The fuck is a 'Sabine?'", "translation": "'Sabine' cái đéo gì?" },
    { "source": "Livy? Titus Livius Patavinus? Ab Urbe fucking Condita?", "translation": "Livy? Titus Livius Patavinus? Ab Urbe fucking Condita?" },
    { "source": "Never mind.", "translation": "Đừng bận tâm." },
    { "source": "(muttering) Yeah, damn right never mind. We're done, that's the final word.", "translation": "(Lẩm bẩm) Bỏ qua. Thế là xong." },
    { "source": "(radio) I think the Wilkersons are still waiting for you down at that trade meet.", "translation": "(radio) Gia đình Wilkersons đang đợi ở chỗ giao dịch." },
    { "source": "(radio) So we're brokering deals for the Wilkersons now, huh? Super. What next? Ooh, do you think I could join the Mafia?", "translation": "(radio) Giờ làm môi giới cho Wilkersons hả? Ngon. Mình xin vào Mafia được không?" },
    { "source": "(radio) I just don't think we should be so friendly with them, you know? I mean, yeah, not many people left, stupid to burn bridges, yadda yadda yadda, I get that.", "translation": "(radio) Đừng quá thân với họ. Ít người nên không nên gây thù, tôi hiểu." },
    { "source": "(radio) But these are bad people. The only reason they haven't turned on us yet is because they're getting what they want from us.", "translation": "(radio) Nhưng đó là người xấu. Họ không cắn là vì họ đang cần ta." },
    { "source": "(radio) For now, that's a good enough reason. It's bad enough fighting zombies, I don't want to fight the Wilkersons, too.", "translation": "(radio) Tạm thời vậy. Tôi chả muốn chiến với Wilkersons đâu." },
    { "source": "(radio) Okay, it's your call. But for the record? If this turns out to be a trap, I'm totally claiming 'I told you so' rights for a week.", "translation": "(radio) Ok tùy bạn. Nếu đây là bẫy thì ráng mà chịu nha." },
    { "source": "(radio) Also, you're on kitchen duty. Have fun!", "translation": "(radio) Bạn trực bếp nhé. Vui vẻ!" },
    { "source": "You the one the Wilkersons sent?", "translation": "Người của Wilkersons phái tới hả?" },
    { "source": "That's right. ", "translation": "Phải." },
    { "source": "Follow me.", "translation": "Theo tôi." },
    { "source": "Huh. Didn't figure you for Job's cronies. Always heard you folks were decent sorts.", "translation": "Không nghĩ bạn là lính Job. Tưởng bạn tốt cơ." },
    { "source": "I'm just here to make sure the trade goes nice and smooth.", "translation": "Tôi tới đây để giám sát giao dịch thôi." },
    { "source": "Then you'd best watch the Wilkersons. I trust them about as far as a two-headed snake.", "translation": "Cẩn thận Wilkersons. Đừng có tin bọn rắn hai đầu này." },
    { "source": "Shit, got me good with that one.", "translation": "Mẹ, ăn đòn đau đấy." },
    { "source": "He's dead.", "translation": "Hắn chết rồi." },
    { "source": "Think I don't know that?", "translation": "Tưởng tôi không biết chắc?" },
    { "source": "That sounds bad.", "translation": "Có vẻ tệ." },
    { "source": "Maybe to you. Little killin' sounds just fine right about now.", "translation": "Chắc với bạn. Tôi thì khoái chém giết." },
    { "source": "Shit' got me good with that one.", "translation": "Mẹ, ăn đòn đau đấy." },
    { "source": "This feel a little familiar to you?", "translation": "Có quen thuộc không?" },
    { "source": "Little bit.", "translation": "Một chút." },
    { "source": "You stickin' around?", "translation": "Bạn ở đây hả?" },
    { "source": "You got what we asked for?", "translation": "Có đồ tôi cần chưa?" },
    { "source": "It's all right here.", "translation": "Tất cả ở đây." },
    { "source": "Hope you brought something worthwhile.", "translation": "Mong là đồ xịn." },
    { "source": " It ain't wise to cross me.", "translation": " Gây sự với tao là ngu đấy." }
  ]
});

outputs.push({
  "id": "00398",
  "group": "dialog",
  "strings": [
    { "source": "Here you go. As promised. ", "translation": "Đây. Như đã hứa." },
    { "source": "Appreciate you taking care of this for us.", "translation": "Cám ơn đã giúp đỡ." },
    { "source": "Now why don't you run along... you hear me?", "translation": "Giờ thì lượn đi... nghe không?" },
    { "source": "Unh... I ain't gonna last long leaking like a busted radiator.", "translation": "Hừ... máu chảy vầy chắc tao chết sớm." },
    { "source": "Reckon I better go patch this up. After that, think I'll get my sorry ass blind stinking drunk for a month of Sundays.", "translation": "Băng lại đã. Rồi đi nhậu tẹt ga luôn." },
    { "source": "But you still give a holler if you want me to shoot some corpsified motherfuckers for you. My aim's better when I drink.", "translation": "Nhưng khi nào cần bắn xác sống thì cứ gọi. Tao say bắn chuẩn hơn." },
    { "source": "You hear about the Wilkersons?", "translation": "Nghe nói về Wilkersons chưa?" },
    { "source": "Some kind of deal went bad or something. I've heard, like, five versions of the story, but the long and the short of it is they ended up shooting each other or something.", "translation": "Phi vụ thất bại gì đó. Nghe phong phanh là họ bắn nhau." },
    { "source": "<GenericResponse_BadNews_Vindictive>", "translation": "<GenericResponse_BadNews_Vindictive>" },
    { "source": "I tell you the other night I busted into my bitch ex-wife's house?", "translation": "Kể nghe vụ phá nhà con vợ cũ chưa?" },
    { "source": "Yep. Kicked in the door, smashed up the place, pissed on her bed. Felt good, even if she is already a zombie.", "translation": "Phá cửa, đập đồ, đái lên giường. Sướng, dù nó đã hóa zombie." },
    { "source": "Best part, though? No piece of shit local cops showing up blabbing about 'drunk and disorderly' and 'restraining order' bullshit.", "translation": "Khoái nhất là đéo có cảnh sát tới bắt vì lệnh cấm." },
    { "source": "Yeah, well, just keep your asses clear of Marshall. Way I hear it, the pigs have some kind of base down there, and they ain't handing out traffic tickets, if you know what I mean.", "translation": "Cứ tránh xa Marshall ra. Bọn cớm có căn cứ dưới đó, và chúng đéo có hiền đâu." },
    { "source": "I was damn sorry to hear about your brother, boys. Real shame.", "translation": "Chia buồn vụ thằng em của mấy anh nha." },
    { "source": "(drunk) You here to trade, or get punched in the fuckin' mouth?", "translation": "(say) Tới giao dịch hay tới ăn đấm?" },
    { "source": "Fair enough. I got a couple cases of ammo and some canned goods here--how's your moonshine stock?", "translation": "Công bằng. Tôi có đạn và đồ hộp--còn rượu lậu không?" },
    { "source": "(drunk) We got plenty. What I'm wondering though... is what's to stop me from caving your skull in and just taking that shit?", "translation": "(say) Nhiều. Cớ gì tao không đập móp sọ mày rồi cướp mẹ nó đi?" },
    { "source": "Well, nothing, Mickey... but then who's gonna bring you more?", "translation": "Không gì, Mickey... nhưng rồi ai mang đồ tới nữa?" },
    { "source": "<Laughter>", "translation": "<Cười lớn>" },
    { "source": "You got some stones on you!", "translation": "Cứng cựa đấy!" },
    { "source": "<Nervous laughter>", "translation": "<Cười gượng>" },
    { "source": "Boys! Get your lazy asses out here and bring this stuff inside!", "translation": "Lũ lười! Ra đây mang đồ vào!" },
    { "source": "(foreshadowing the fact that Job is moving into human trafficking) All right, here's the deal. You work for us, you get a cut of whatever we bring in. Food, ammo, gas... well. Whatever.", "translation": "Được rồi, làm cho bọn tao, chia phần trăm đồ hộp, đạn, xăng... gì cũng được." },
    { "source": "Plus you get to crack some skulls when folks get uppity.", "translation": "Và được đập nứt sọ những đứa láo xược." },
    { "source": "Sure. Anyways, you decide that doesn't sit right with you, the door's right there. Just remember what's on the other side of it.", "translation": "Được. Nếu mày không thích thì cửa đó. Cứ nhớ bên kia cửa là gì." },
    { "source": "Hell with that! We ain't got time for half-asses and lollygaggers. We need boys we can rely on.", "translation": "Đéo rảnh! Đéo cần bọn vớ vẩn. Bọn tao cần người đáng tin cậy." },
    { "source": "We'll treat you right long as you do as you're told. But you don't toe the line, and I'll personally stomp you into paste.", "translation": "Mày nghe lời thì tao đối xử tốt. Láo thì tao đập nát óc." },
    { "source": "(Trying to play it off as a joke) Let's not scare our friends off already, Mickey. Everybody's here because they want to be.", "translation": "(Cố đùa) Đừng dọa bạn bè thế, Mickey. Mọi người tự nguyện mà." },
    { "source": "Everybody's here 'cause I went out and found them, little brother! So they--", "translation": "Họ ở đây vì em đã đi tìm họ! Thế nên họ--" },
    { "source": "So you can all just shut up and do what I say.", "translation": "Thế nên hãy ngậm mồm vào và làm theo." },
    { "source": "Any questions, you come see me first.", "translation": "Có câu hỏi gì thì tới gặp tao." },
    { "source": "(Scared) I told you, this is all we have!", "translation": "(Sợ hãi) Đã nói rồi, bọn tao chỉ có thế này thôi!" },
    { "source": " I know you did. I know that. But see, here's where I have a problem I also know what I told you last time.", "translation": " Biết rồi. Tao biết. Nhưng vấn đề là tao nhớ đã nói gì lần trước." },
    { "source": "Where the hell am I supposed to get a whole case of ammunition?!", "translation": "Lấy đâu ra nguyên thùng đạn bây giờ?!" },
    { "source": "Maybe you shoulda thought about that before you bought our merchandise! You know what we do to deadbeats?", "translation": "Lẽ ra phải nghĩ đến chuyện đó trước! Mày biết tao làm gì bọn nợ nần không?" },
    { "source": "Oh, God, please! We gave you our food, our gas... you said that would square us!", "translation": "Trời ơi! Bọn tao đã đưa đồ ăn, xăng... anh bảo thế là xong mà!" },
    { "source": "No. No. What I said was 'this will cover the interest.' You still owe us the principal, right?", "translation": "Không. Không. Tao bảo là 'trả lãi thôi'. Mày vẫn nợ gốc, hiểu chưa?" },
    { "source": "No buts. We had a deal, and you don't want people thinking you're the sort that breaks his deals, do we?", "translation": "Không nhưng nhị. Thỏa thuận là thỏa thuận, đừng làm người thất tín." },
    { "source": "You just run along and get us what you owe, and we won't have a problem. You hear me?", "translation": "Mang đồ tới đây, và mọi chuyện sẽ êm xuôi. Nghe không?" },
    { "source": "(Muttering) Next time we mail his head home in a box to show we ain't fucking around.", "translation": "(Lẩm bẩm) Lần tới chặt đầu nó gửi về cho chúng nó biết mặt." }
  ]
});

outputs.push({
  "id": "00399",
  "group": "dialog",
  "strings": [
    { "source": "Maybe when the post office gets working again.", "translation": "Chắc đợi lúc bưu điện hoạt động lại." },
    { "source": "You seen Job around?", "translation": "Thấy Job không?" },
    { "source": "Good. Guy sets my teeth on edge whenever he's around. Were you here for that whole thing with the Halloran gang?", "translation": "May. Hắn ta làm tôi ngứa mắt. Có mặt ở đây lúc băng Halloran tới không?" },
    { "source": "Man, that was fucked up. So, these guys get it into their head they can start selling crank on the Wilkersons' turf, right?", "translation": "Hơi tệ. Bọn đó nghĩ có thể bán hàng trên địa bàn nhà Wilkersons." },
    { "source": "So after Mickey beats the hell out of them and drags them out to the farmhouse, Job decides to 'teach them a lesson.'", "translation": "Mickey tẩn bọn nó rồi đưa về nông trại, Job muốn 'dạy một bài học'." },
    { "source": "I guess maybe one of them survived. Whole time though, Job? He never looks up from his fuckin' book. Kept reading out loud from it. I dunno, something by Julius Caesar or somebody.", "translation": "Chắc có đứa còn sống. Mà Job cứ đọc sách suốt. Đọc to cái gì đó của Julius Caesar." },
    { "source": "Well, that's just about it for your physical. Now, has there been any reduction in the burning sensation when you urinate?", "translation": "Khám xong. Giờ, đi tiểu còn rát không?" },
    { "source": "Jesus, Doc! Not in front of everybody!", "translation": "Trời ạ, Doc! Đừng hỏi ở đây chứ!" },
    { "source": "I ain't here to spare your delicate sensibilities, I'm here to see to your medical well-being!", "translation": "Tôi không phải ở đây để giữ thể diện, tôi khám bệnh!" },
    { "source": "If you was so embarrassed about the condition, maybe you shouldn't have been fraternizing with women of low moral character.", "translation": "Nếu thấy xấu hổ thì bớt giao du với bọn đàn bà hư hỏng đi." },
    { "source": "Now, does it still burn when you piss?", "translation": "Đi tiểu còn rát không?" },
    { "source": "No. It's gotten better.", "translation": "Không. Đỡ rồi." },
    { "source": "Good. Nothing serious then.", "translation": "Tốt. Không có gì nghiêm trọng." },
    { "source": "No, goddammit, I said I was gonna do it, I'm gonna do it!", "translation": "Không, mẹ kiếp, bảo làm thì làm!" },
    { "source": "(Losing his temper for once) Will you use your head for once in your fool life?", "translation": "(Nổi cáu) Có dùng não không vậy?" },
    { "source": "Them bridges have been empty for days now! The Army ain't even watching them, we get over the barricades and we can get all the guns we want!", "translation": "Cầu trống mấy ngày rồi! Bọn lính không canh đâu, vượt rào là có súng!" },
    { "source": "And suppose they're watching it closer than you think? Suppose they got snipers up there, just waiting for some dumbass to try getting over?", "translation": "Nhỡ chúng canh sát hơn thì sao? Có lính bắn tỉa chờ thằng ngu nào đó thì sao?" },
    { "source": "I'll take care of it!", "translation": "Tự lo được!" },
    { "source": "Like you took care of Eli?", "translation": "Lo được như Eli à?" },
    { "source": "Best watch that mouth, boy. Can't hide behind momma's skirts no more.", "translation": "Cẩn thận mồm miệng. Không nấp sau váy mẹ được đâu." },
    { "source": "Patrols are back in. No casualties today, but no food, either.", "translation": "Tuần tra về rồi. Không ai chết, cũng không có thức ăn." },
    { "source": "Again? We're going to have food riots at this rate.", "translation": "Nữa à? Kiểu này thì sẽ bạo động vì thức ăn mất." },
    { "source": "We've pretty much picked downtown clean. Maybe if you let the scouts range out farther....", "translation": "Trung tâm dọn sạch rồi. Nếu cho trinh sát đi xa hơn..." },
    { "source": "I'm not willing to risk that. We're barely holding this block; we don't try to expand until we've consolidated.", "translation": "Tôi không muốn mạo hiểm. Vừa giữ nổi chỗ này; chưa nên mở rộng vội." },
    { "source": "Well, we've got to do something. We can't keep relying on Ray and his swap meets to keep us in food.", "translation": "Phải làm gì đó. Không thể dựa mãi vào Ray và chợ đồ cũ của ổng." },
    { "source": "Ray's not the only one with a longer reach than us; spread the word, Sheriff. We'll trade ammunition for food to anyone willing to bring it.", "translation": "Không chỉ mình Ray; báo đi, Cảnh sát. Đổi đạn lấy thức ăn cho ai mang tới." },
    { "source": "Ray Santos", "translation": "Ray Santos" },
    { "source": "(radio) You get around the valley a fair bit. Feel like making a delivery for me? I'll pay, of course.", "translation": "(radio) Bạn hay đi loanh quanh đúng không. Giao hàng giúp tôi nhé? Có trả công đàng hoàng." },
    { "source": "(radio) I've got a little care package here that needs to make its way home. I can make it worth your while.", "translation": "(radio) Có gói quà cần giao nè. Sẽ trả công hậu hĩnh." },
    { "source": "(radio) Feel like making a delivery? I've got some stuff I could give you in exchange. You'll like it.", "translation": "(radio) Giao đồ không? Có đồ đổi nè, cậu sẽ thích." },
    { "source": "I appreciate you doing this. It's good to see people with a good head for business making their way in the world. Reminds me of myself.", "translation": "Rất cảm ơn. Rất tốt khi thấy người kinh doanh giỏi như cậu. Giống tôi lúc trước." },
    { "source": "You're going to make somebody very happy with this. Turning a profit is all well and good, but knowing that you helped keep someone from going hungry or cold? That's the real treasure.", "translation": "Sẽ có người vui lắm. Có lãi cũng tốt, nhưng giúp được người khác không đói khổ mới là kho báu thật sự." },
    { "source": "You've been a good friend to me, and to the people of this valley. When we start to rebuild on a larger scale, you're exactly the kind of person I'm going to want on my side.", "translation": "Cậu là người bạn tốt với mọi người ở thung lũng này. Khi tái thiết, tôi rất cần một người như cậu." },
    { "source": "Judge Lawton", "translation": "Judge Lawton" },
    { "source": "(radio) This is Judge Lawton. Earlier today, our scouts informed me that they have identified multiple infestations in the downtown Marshall area.", "translation": "(radio) Tôi là Judge Lawton. Trinh sát vừa báo có ổ nhiễm bệnh ở trung tâm Marshall." },
    { "source": "(radio) Based on this information, and for your own safety, I'm declaring a lockdown, effective immediately and until further notice.", "translation": "(radio) Dựa vào đó, và vì an toàn, tôi tuyên bố phong tỏa, có hiệu lực tức thì." },
    { "source": "(radio) This is a matter for the police, and they will deal with it.", "translation": "(radio) Cảnh sát sẽ giải quyết." },
    { "source": "(radio) Might want to head down to the courthouse and see what's going on.", "translation": "(radio) Lên tòa án xem sao đi." },
    { "source": "All due respect, Your Honor, we're stretched too thin as it is. You've got half my guys guarding the dispensary instead of out there pushing these things back!", "translation": "Thưa ngài, chúng ta mỏng lực lượng quá. Ngài bắt nửa số lính gác trạm y tế thay vì đi đánh lùi bọn chúng!" },
    { "source": "I understand the difficulty, Sheriff, but I don't know what you expect me to do about it.", "translation": "Tôi hiểu, Cảnh sát trưởng, nhưng cô muốn tôi làm gì chứ." }
  ]
});

fs.writeFileSync(OUTPUT_BATCH_FILE, JSON.stringify(outputs, null, 2));
console.log("Added 00397, 00398, 00399.");
