const fs = require('fs');

const OUTPUT_BATCH_FILE = 'jobs/output_batch.json';
let outputs = JSON.parse(fs.readFileSync(OUTPUT_BATCH_FILE, 'utf8'));

outputs.push({
  "id": "00400",
  "group": "dialog",
  "strings": [
    { "source": "We only have so many trained officers left, and I'm not comfortable with the prospect with arming civilians for this kind of work.", "translation": "Số cảnh sát có hạn, và tôi không an tâm khi để dân thường mang vũ khí làm việc này." },
    { "source": "If you'd let me start training-", "translation": "Nếu cho phép tôi huấn luyện-" },
    { "source": "We'll discuss this later, Sheriff. We have a visitor.", "translation": "Bàn sau đi, Cảnh sát trưởng. Có khách." },
    { "source": "Welcome. I suppose you've heard our broadcasts? Well, it's all true.", "translation": "Chào mừng. Nghe đài rồi chứ? Sự thật đấy." },
    { "source": "We have a safe, secure society here, governed by the rule of law.", "translation": "Chúng tôi có cộng đồng an toàn, quản lý bằng pháp luật." },
    { "source": "Walk with me. I", "translation": "Đi cùng tôi. Tôi" },
    { "source": "You have a society? I'm sorry, what exactly happened to the United States while I wasn't looking?", "translation": "Cộng đồng á? Nước Mỹ bị gì trong lúc tôi không để ý vậy?" },
    { "source": "Look around. We're facing a disaster of unprecedented scale. We have no way of knowing how widespread it is or how long it will take federal authorities to respond.", "translation": "Nhìn đi. Đây là thảm họa chưa từng có. Không biết nó rộng tới đâu và khi nào chính phủ mới phản ứng." },
    { "source": "Until they do, we have to look out for ourselves. It may not be the most Constitutionally traditional succession, but it's all we have.", "translation": "Tới lúc đó, phải tự lo. Có thể không đúng Hiến pháp, nhưng đó là cách duy nhất." },
    { "source": "All we have? The Army's camped just across the river.", "translation": "Duy nhất? Quân đội cắm trại ngay bờ sông kìa." },
    { "source": "Yes, and other than vaguely-threatening radio broadcasts, they've made no attempt to contact us or provide relief efforts to the civilian government.", "translation": "Đúng, nhưng ngoài mấy đe dọa qua radio, họ chả thèm liên lạc hay giúp chính quyền dân sự." },
    { "source": "Meanwhile, ordinary citizens like yourselves are living in fear. Fear of the dead, fear of the criminal element that sees this as an opportunity to prey on their fellow man, fear of the uncertain future of our nation.", "translation": "Trong khi dân đen đang sợ hãi. Sợ xác chết, sợ tội phạm nhân cơ hội cướp bóc, sợ tương lai mịt mờ." },
    { "source": "But it doesn't have to be that way.", "translation": "Nhưng đâu cần thiết phải vậy." },
    { "source": "So what exactly are these laws?", "translation": "Vậy các luật đó là gì?" },
    { "source": "Nothing too onerous. You'll keep to the curfew, put any supplies you gather toward the community pool, and respect the rights and property of the others in the community.", "translation": "Đơn giản thôi. Tuân thủ giờ giới nghiêm, nộp mọi nhu yếu phẩm kiếm được, và tôn trọng quyền lợi, tài sản của mọi người." },
    { "source": "And, of course, all firearms will be surrendered. Only duly appointed law enforcement officers are allowed to go armed.", "translation": "Và, nộp mọi vũ khí. Chỉ cảnh sát thi hành công vụ mới được mang súng." },
    { "source": "Right. Well, thanks for the offer, but we're doing just fine on our own, and I'm damn sure not surrendering my guns when the streets are full of flesh-eating dead people.", "translation": "À vâng. Cám ơn, bọn tôi tự lo được, và dĩ nhiên đéo có chuyện giao súng khi đầy zombie ăn thịt ngoài đường." },
    { "source": "I'm very sorry to hear that. We'd certainly prefer it if people joined us freely, before the issue has to be forced.", "translation": "Rất tiếc. Thà mọi người tự nguyện tham gia còn hơn là bị bắt ép." },
    { "source": "Is that a threat?", "translation": "Bà đang đe dọa à?" },
    { "source": "Just a reminder that the Wild West doesn't last forever. The law always catches up.", "translation": "Nhắc nhở thôi. Luật pháp luôn đến kịp lúc." },
    { "source": "(thoughtful, to player) Don't take it personal. She's under a lot of strain; we're penned in pretty good by these things, and like you might have heard we're shorthanded.", "translation": "(suy ngẫm) Đừng để bụng. Căng thẳng thôi; chúng ta đang bị vây hãm, và đang rất thiếu nhân lực." },
    { "source": "Tell you what. Help me clear some of these problem areas out and I'll vouch for you. Put in a good word, maybe set up some kind of trade arrangement.", "translation": "Vầy đi. Giúp dọn dẹp mấy khu phức tạp, tôi bảo lãnh cho. Nói giúp vài tiếng, rồi thiết lập giao dịch." },
    { "source": "(radio) I could still use a hand with these infestations if you're willing.", "translation": "(radio) Vẫn cần người dọn dẹp ổ bệnh nếu bạn rảnh." },
    { "source": "(radio) Just got word from Sheriff Parsons. I guess those people didn't make it. Thought you should know.", "translation": "(radio) Vừa nhận tin từ Cảnh sát trưởng. Đám người đó chết rồi. Cần báo cho bạn." },
    { "source": "Feel like lending a hand?", "translation": "Muốn giúp một tay không?" },
    { "source": "Hope you're geared up; we've got a few infestations to deal with.", "translation": "Chuẩn bị sẵn đi; có vài ổ bệnh cần dọn." },
    { "source": "I hate to see the old girl like this.", "translation": "Tôi ghét nhìn thấy nơi này như vầy." },
    { "source": "The town. It's been on rough times for a while now, but it used to be a damn fine place to live. Raise a family.", "translation": "Thị trấn này. Gần đây khó khăn quá, nhưng nó từng là nơi tuyệt vời để sống. Để nuôi nấng gia đình." },
    { "source": "Course, my wife didn't agree, but never you mind.", "translation": "Vợ tôi không nghĩ vậy, nhưng bỏ đi." },
    { "source": "She married a machinist; didn't like it when I became a cop instead.", "translation": "Bà ấy lấy một thợ máy; nên không thích tôi làm cảnh sát." },
    { "source": "She finally had enough a few years back; took our son to live in the city. Said it would be a more enriching environment for him.", "translation": "Vài năm trước, bà ấy mang con lên thành phố. Nói đó là môi trường tốt hơn cho nó." },
    { "source": "Not your fault. I just hope things there aren't as bad as things here.", "translation": "Không phải lỗi của ông. Mong trên đó không tệ như ở đây." },
    { "source": "Hell. Guess we're staying put till one of you changes your mind, then.", "translation": "Chết tiệt. Chắc cứ ở đây tới khi có người đổi ý." },
    { "source": "You think it's bad now? You should have seen Marshall in the first couple of days.", "translation": "Giờ tệ á? Vài ngày đầu Marshall kinh dị hơn nhiều." },
    { "source": "Seemed like half the town was already dead or dying, and the other half was trying to cram into the courthouse for protection.", "translation": "Nửa số người đã chết hoặc hấp hối, nửa còn lại cố chui vào tòa án trốn." },
    { "source": "Mayer Carson had got himself shot trying to cross the bridges, the City Council was locked in a conference room and refused to come out, the police station was overrun... it was chaos.", "translation": "Thị trưởng Carson bị bắn ở cầu, Hội đồng nhốt mình ở phòng họp, sở cảnh sát thất thủ... cực kì hỗn loạn." },
    { "source": "Judge Lawton stepped up. Got us all organized, kept people from each other's throats...", "translation": "Judge Lawton đứng ra. Tổ chức lại, ngăn người ta cắn xé nhau..." },
    { "source": "So maybe she's not technically the law of the land... but damn sure we'd all be dead without her.", "translation": "Nên về lý bà ta không phải là pháp luật... nhưng thiếu bà ấy thì tất cả tiêu hết rồi." },
    { "source": "Course, some folks can never see how good they got it until it's all gone.", "translation": "Đúng là có người không bao giờ biết trân trọng cho đến khi mất đi." },
    { "source": "You know how it is. Some people, you ask them to go without for a little bit and suddenly they're on the cross.", "translation": "Cậu biết mà. Vài người hễ cứ bắt họ chịu cực tí là họ làm ầm lên như tử vì đạo vậy." }
  ]
});

outputs.push({
  "id": "00401",
  "group": "dialog",
  "strings": [
    { "source": "It's nothing new--you never heard more whining than from the back seat of a patrol car.", "translation": "Thường thôi--bọn ngồi sau xe cảnh sát là bọn than vãn nhiều nhất." },
    { "source": "(radio) Mayday, mayday! Is anyone reading?", "translation": "(radio) Mayday, mayday! Ai nghe không?" },
    { "source": "(radio) We're trapped! Lots of zombies outside, and we're out of ammo. Don't know how long we can hold out!", "translation": "(radio) Mắc kẹt rồi! Rất nhiều zombie ngoài này, hết đạn rồi. Sắp không trụ nổi nữa!" },
    { "source": "Sit tight--help's on the way.", "translation": "Ráng nha--đang tới cứu." },
    { "source": "(to player) Come on--we can deal with the rest of these infestations later. We gotta help those people first.", "translation": "(với người chơi) Dọn ổ nhiễm bệnh sau đi. Cứu người đã." },
    { "source": "Thanks. We owe you big-time.", "translation": "Cảm ơn. Nợ mọi người nhiều lắm." },
    { "source": "Don't you worry about it. We're happy to help.", "translation": "Đừng lo. Rất vui vì giúp được." },
    { "source": "(to player) I think we'll call it a day there. The rest of those infestations can wait a while. I appreciate the help, though.", "translation": "(với người chơi) Hôm nay vậy đủ rồi. Mấy ổ nhiễm đó dọn sau cũng được. Dù sao thì cám ơn nha." },
    { "source": "(radio) Sounds like they're having some trouble with infestations in Marshall.", "translation": "(radio) Có vẻ Marshall đang dính dịch nặng." },
    { "source": "All right; if I get a chance, I'll look into it.", "translation": "Được rồi; rảnh tôi sẽ qua xem." },
    { "source": "(radio) Word around town is you're making quite a splash for yourself, my friend.", "translation": "(radio) Nghe nói cậu đang nổi tiếng lắm đấy bạn." },
    { "source": "(radio) You might not know me yet, but I think the two of us could do each other a lot of good.", "translation": "(radio) Có thể cậu chưa biết tôi, nhưng ta có thể giúp đỡ nhau." },
    { "source": "(radio) Why don't you come down to Marshall so we can have a little face to face chat?", "translation": "(radio) Sao cậu không ghé Marshall để nói chuyện trực tiếp nhỉ?" },
    { "source": "(radio) Hey, it's okay, I'm a patient man, and you're busy, but I really would like to talk to you.", "translation": "(radio) Ổn thôi, tôi kiên nhẫn, cậu thì bận, nhưng tôi rất muốn nói chuyện với cậu." },
    { "source": "You know anything about this Ray guy?", "translation": "Biết gì về người tên Ray này không?" },
    { "source": "(radio) Yeah, he's kind of a local big shot. Owned a bunch of businesses in Marshall, served on the county commission, that kind of thing.", "translation": "(radio) Ông ta là tai to mặt lớn. Làm chủ nhiều chỗ ở Marshall, làm cả ủy ban quận, đại khái thế." },
    { "source": "(radio) A lot of people used to say he was crooked, but nobody ever proved anything.", "translation": "(radio) Nhiều người nói ổng là lừa đảo, nhưng không có bằng chứng." },
    { "source": "(radio) All I know is when my dad's insurance wouldn't cover my treatment? Ray shows up at our place one night with an envelope full of cash.", "translation": "(radio) Tôi chỉ biết khi bảo hiểm của bố không trả tiền chữa bệnh? Ray đến vào một đêm mang theo cái phong bì đầy tiền." },
    { "source": "(radio) Tells my dad not to worry so much. 'Just remember me in November.' It was $10,000.", "translation": "(radio) Kêu bố tôi đừng lo. 'Hãy nhớ đến tôi vào tháng 11'. 10.000 đô lận đó." },
    { "source": "Lot of money for a county commissioner.", "translation": "Rất nhiều tiền với một ủy viên hội đồng quận." },
    { "source": "(radio) Yeah, well... I don't know where he got it, and I don't really care. Ray's a good guy in my book.", "translation": "(radio) Tôi không biết ông ta lấy đâu ra tiền, cũng không quan tâm. Trong mắt tôi ông ta là người tốt." },
    { "source": "(radio) What do you suppose Ray wants?", "translation": "(radio) Bạn nghĩ Ray cần gì?" },
    { "source": "I dunno, but I'm not sure I trust him. You remember that corruption scandal a few years back?", "translation": "Không rõ, nhưng không chắc là tin ổng được không. Nhớ vụ tham nhũng vài năm trước không?" },
    { "source": "(radio) I remember that the charges were dismissed. Nobody could prove anything.", "translation": "(radio) Nhớ là bị bác bỏ cáo trạng rồi. Không ai chứng minh được." },
    { "source": "Hey! Come on up--just enjoying the view.", "translation": "Này! Lên đây--tận hưởng phong cảnh." },
    { "source": "Glad you made it. Hope this wasn't too far out of your way; I like to come up here sometimes to think.", "translation": "Mừng là cậu tới. Chắc không xa lắm đâu; tôi thích đến đây suy nghĩ." },
    { "source": "Really gives you a sense of the big picture, you know? Go ahead, have a look. Take it in.", "translation": "Cho ta góc nhìn bao quát hơn, hiểu không? Cứ tới xem đi. Cảm nhận thử xem." },
    { "source": "My family's got deep roots in this town. My grandpa started with nothing but the deed to a few dozen acres of empty wilderness and spun it into a lumber empire that put all four of his kids through college.", "translation": "Nhà tôi ở đây lâu rồi. Từ mẫu đất hoang dã, ông nội xây dựng đế chế gỗ, nuôi bốn đứa con ăn học." },
    { "source": "My father took that education and gave back to this town. Miguel Santos was the first Latino mayor Marshall ever had, did you know that?", "translation": "Cha tôi dùng kiến thức đó cống hiến. Miguel Santos là thị trưởng người Latin đầu tiên của Marshall đấy." },
    { "source": "Community, you see. That's what matters--now more than ever. All of us together, doing our own thing but helping our neighbors when they need it.", "translation": "Cộng đồng. Đó là cái quan trọng nhất. Cùng nhau, làm việc của mình, giúp đỡ người bên cạnh." },
    { "source": "Marshall's seen some bad times and some good, but my family's always done our part to help her through the bad and make the good even better.", "translation": "Marshall có lúc thăng lúc trầm, nhưng gia đình tôi luôn giúp đỡ để vượt qua lúc khó và làm lúc thịnh càng tốt hơn." },
    { "source": "The way I see it, this whole thing is just another bad time, and I just know my daddy and granddaddy are looking down at me right now, saying 'Raymundo, you've got to do the right thing.'", "translation": "Theo tôi, chuyện này chỉ là một khoảng thời gian xấu, và cha, ông tôi đang nhìn xuống và nói: 'Raymundo, hãy làm điều đúng đắn'." },
    { "source": "So that's what I'm doing. Just helping out, any way I can. You need supplies, I can arrange a trade. You need a car, I can hook you up.", "translation": "Nên tôi đang làm vậy. Giúp đỡ bất kỳ ai. Cần hàng hóa? Có liền. Cần xe? Tìm giùm luôn." },
    { "source": "Anyways, I've taken up enough of your time. You've probably got a lot on your mind, you don't need old Ray talking your ear off.", "translation": "Tôi chiếm nhiều thời gian của cậu rồi. Cậu còn nhiều thứ phải lo, lão Ray này không nên nói quá nhiều." },
    { "source": " Tell you what, though give me a little while to put something together. A sort of 'welcome to the neighborhood present. I'll give you a call when it's ready. See you then?", "translation": " Nói cho nghe, để tôi chuẩn bị một chút. Một món quà 'chào mừng người mới'. Lúc nào xong tôi gọi. Gặp sau nhé?" },
    { "source": "Perfect. You stay safe out there.", "translation": "Tuyệt. Cẩn thận nhé." },
    { "source": "(radio) Got that little present ready for you. Come on out and meet me when you've got the time.", "translation": "(radio) Chuẩn bị xong quà rồi. Rảnh thì qua lấy nhé." },
    { "source": "(radio) Still waiting for you whenever you're free.", "translation": "(radio) Vẫn chờ cậu đến lấy quà đây." },
    { "source": "Well? Whaddya think?", "translation": "Thấy sao?" },
    { "source": "It's a car. It's for me?", "translation": "Xe. Tặng tôi à?" }
  ]
});

outputs.push({
  "id": "00402",
  "group": "dialog",
  "strings": [
    { "source": "Sure, why not? I've amassed a fair little collection since this business went down. I can spare one for a new friend. It's all about people pulling together, after all.", "translation": "Chắc rồi. Thu thập được một bộ sưu tập kha khá. Cho bạn mới một chiếc cũng chẳng sao. Chung tay vì mọi người thôi." },
    { "source": "Speaking of pulling together... I wonder if you wouldn't be able to do me a favor?", "translation": "Nhắc vụ chung tay... Cậu có thể giúp tôi một việc không?" },
    { "source": "The folks out at the old Ballard homestead have been having trouble with one of their trucks. I happen to have some parts to spare, so I was figuring on running them out there.", "translation": "Mọi người ở nông trang Ballard đang gặp rắc rối với xe tải. Tôi tình cờ có đồ phụ tùng, nên định mang qua." },
    { "source": "Don't suppose you'd be interested in taking this little beauty for a test drive?", "translation": "Chắc cậu có hứng lái thử chiếc xế hộp này đúng không?" },
    { "source": "I knew I could rely on you. By all means, you drive. It's not too far.", "translation": "Biết là nhờ được mà. Cậu lái nhé. Không xa lắm đâu." },
    { "source": "So, how about it?", "translation": "Sao hả?" },
    { "source": "Well, that's your prerogative. Guess I'll just have to walk it out there myself. You can keep the car, of course.", "translation": "Tùy cậu. Để tự đi bộ đến đó vậy. Giữ chiếc xe đi nhé." },
    { "source": "Handles like a dream, doesn't she? I had one just like her as a younger man.", "translation": "Lái đã đúng không? Thời trẻ cũng có chiếc thế này." },
    { "source": "Ah, yeah, this takes me back. The open road, wind in your hair... of course, when I was younger I usually had a stacked blonde sitting next to me, but hey.", "translation": "Ah, làm nhớ lại hồi đó quá. Đường trải dài, gió vờn tóc... Dĩ nhiên lúc trước kế bên tui luôn là mấy em tóc vàng hoe rực lửa." },
    { "source": "Say, you want to try something really cathartic? Head up this way, I want to show you something.", "translation": "Nè, muốn xả stress không? Đi đường này, tôi chỉ cho xem." },
    { "source": "Ah, yeah, this takes me back. The open road, wind in your hair, a pretty girl sitting next to me....", "translation": "Làm nhớ hồi đó quá. Đường trải dài, gió vờn tóc, em gái xinh ngồi kế bên..." },
    { "source": "All that's missing is classic rock on the radio.", "translation": "Chỉ thiếu mỗi bài nhạc rock cổ điển trên đài." },
    { "source": "There we go. See those zombies?", "translation": "Tới rồi. Thấy lũ zombie không?" },
    { "source": "Let's run the bastards over.", "translation": "Cán qua bọn chó đẻ đó." },
    { "source": "Come on, it'll be fun! Take out some of your aggression. Blow off steam. Trust me, this baby can take it.", "translation": "Sẽ vui lắm! Xả stress đi. Tin tôi, con này chịu được." },
    { "source": "Ha ha! That never gets old, does it?", "translation": "Ha ha! Không bao giờ chán!" },
    { "source": "Okay, come on, let's get back to it.", "translation": "Thôi, đi lo việc chính." },
    { "source": "Okay, okay... that was fun, but I suppose we'd better take care of this delivery now. Let's go.", "translation": "Ok... vui đó, nhưng thôi giao hàng cái. Đi lẹ." },
    { "source": "Looks like another trouble spot up ahead. Let's be neighborly and clear these things out, shall we?", "translation": "Phía trước có ổ kìa.Làm hàng xóm tốt, dọn sạch nó luôn nhé?" },
    { "source": "Lay on the horn, there--that'll draw them out into the road.", "translation": "Bóp kèn--cho chúng ra đường." },
    { "source": "Yeah. That's right.", "translation": "Tuyệt vời." },
    { "source": "Ever done a donut on a zombie's head? Try it!", "translation": "Thử xoay vòng trên đầu zombie chưa? Làm thử đi!" },
    { "source": "Let's get these bastards!", "translation": "Đập bọn khốn này!" },
    { "source": "Might as well take care of this batch, too.", "translation": "Dọn luôn tụi này đi." },
    { "source": "More of them? I'll be damned. We're gonna ding the fender at this rate.", "translation": "Còn nữa à? Thật vãi đạn. Kiểu này móp xe cản trước mất." },
    { "source": "Now I know you're not gonna leave this beauty sitting on the side of the road.", "translation": "Biết là cậu không bỏ xe này ở ven đường đâu." },
    { "source": "Let's stick to driving--no sense working harder than we have to.", "translation": "Cứ ngồi xe--không cần làm lố." },
    { "source": "Let's get back in the car.", "translation": "Vào lại xe đi." },
    { "source": "You just like hearing this baby purr, don't you?", "translation": "Thích tiếng động cơ rầm rú lắm hả?" },
    { "source": "Knew you couldn't resist this beauty.", "translation": "Biết là không thể cưỡng lại mà." },
    { "source": "And here we are. Thanks for driving.", "translation": "Tới nơi. Cám ơn đã lái nhé." },
    { "source": "Hey, Ray! Good to see you!", "translation": "Hey Ray! Rất vui được gặp!" },
    { "source": "Howdy folks! Heard you were having some engine troubles. Figured I'd drop by with some spare parts and see if we can't get the old girl back on her feet.", "translation": "Chào bà con! Nghe bảo gặp vấn đề máy móc. Ghé mang theo phụ tùng xem có giúp được gì không." },
    { "source": "Don't even worry about it. I'm happy to help.", "translation": "Đừng lo. Rất sẵn lòng giúp đỡ." },
    { "source": "Say, you got any spare lumber in your barn there? I know some folks who are running a little short.", "translation": "Trong kho còn ván gỗ nào không? Có người đang thiếu." },
    { "source": "Oh, yeah, sure! Help yourself!", "translation": "Oh, có chứ! Cứ lấy tự nhiên." },
    { "source": "Don't mind if I do, thanks.", "translation": "Tuyệt vời, cám ơn nhiều." },
    { "source": "As for you, you take care out there. And enjoy the ride. I'm sure I'll see you around.", "translation": "Cậu thì đi bảo trọng nhé. Lái vui vẻ. Chắc chắn sẽ còn gặp lại." },
    { "source": "Frank Johnson", "translation": "Frank Johnson" },
    { "source": "(radio) The Judge wants to talk to you. Get your ass down to the courthouse.", "translation": "(radio) Thẩm phán muốn gặp cậu. Tới tòa án lẹ đi." }
  ]
});

outputs.push({
  "id": "00403",
  "group": "dialog",
  "strings": [
    { "source": "I hear Ray's got you doing favors for him now.", "translation": "Nghe nói cậu đang sai vặt cho lão Ray hả." },
    { "source": "That a problem?", "translation": "Có vấn đề gì à?" },
    { "source": "Don't know that I'd call it a problem, exactly. I'd just advise you to keep your eyes open.", "translation": "Không hẳn. Tôi chỉ khuyên cậu nên sáng mắt ra." },
    { "source": "I really don't have time for this.", "translation": "Không rảnh cho ba cái chuyện này." },
    { "source": " Then a quick word of advice Pick your friends carefully. While you still have the luxury.", "translation": " Vậy nghe cho kĩ Chọn bạn mà chơi. Khi cậu còn có thể." },
    { "source": "Oh, Ray talks a big game about everybody pulling together and helping out like some big happy family, but we've seen where that gets us. You've seen where it gets us.", "translation": "Oh, Ray cứ hay ba hoa về gia đình hạnh phúc, đoàn kết giúp đỡ nhau, nhưng ta đều thấy rồi đó. Cậu cũng thấy rồi đó." },
    { "source": "We are vastly outnumbered, facing an enemy that knows neither respite nor pity. Alone, we don't stand a chance.", "translation": "Số lượng ta quá chênh lệch, kẻ thù thì không biết mệt không biết thương xót. Chỉ có một mình thì ta không có cơ hội." },
    { "source": "They will pick us off one by one, and we will ultimately be overwhelmed by a tide of soulless, ravenous husks of what were once our brothers and sisters.", "translation": "Chúng sẽ giết từng người một, rồi ta cũng sẽ bị áp đảo bởi đàn ác quỷ khát máu từng là anh chị em ta thôi." },
    { "source": "Our only hope is to band together, stand strong, and do whatever is necessary for the survival of the human race.", "translation": "Hi vọng duy nhất là liên kết lại, mạnh mẽ, làm mọi thứ vì giống nòi con người." },
    { "source": "So what's wrong with helping people?", "translation": "Giúp người thì có gì sai?" },
    { "source": "Nothing. But Ray and his 'grand vision' lacks the kind of focused leadership that will see us through this crisis.", "translation": "Không có. Nhưng Ray và 'tầm nhìn to lớn' của hắn thiếu khả năng lãnh đạo thiết yếu để đưa ta qua cơn khủng hoảng này." },
    { "source": "You'd do well to remember that.", "translation": "Nhớ kỹ vào." },
    { "source": "Virginia Dalhgren", "translation": "Virginia Dalhgren" },
    { "source": "(radio) Hey, anybody home at the courthouse?", "translation": "(radio) Hey, có ai ở tòa án không?" },
    { "source": "(radio) Our scouts are reporting a lot of zombies closing in on your location. Might want to tell your sentries to wake the hell up.", "translation": "(radio) Trinh sát báo có rất nhiều zombie đang tiến tới. Đánh thức lính gác dậy đi." },
    { "source": "(radio) Hello? Hello?", "translation": "(radio) Alo? Alo?" },
    { "source": "Hey, Carl, how are things?", "translation": "Hey Carl, sao rồi?" },
    { "source": "Same as usual.", "translation": "Vẫn thế." },
    { "source": "My God, I got here just in time.", "translation": "Lạy chúa, đến kịp lúc." },
    { "source": "What've you got for us today, Ray?", "translation": "Hôm nay mang cho tụi này cái gì vây, Ray?" },
    { "source": "The usual. Couple crates of food, some gas for your cruisers, and a little something extra.", "translation": "Như cũ thôi. Vài thùng thức ăn, chút xăng cho xe, và một phần nho nhỏ nữa." },
    { "source": "Is that Scotch?", "translation": "Rượu Scotch hả?" },
    { "source": "Single-malt, my friend. Your favorite, if I remember right.", "translation": "Single-malt. Đúng gu nếu không nhầm." },
    { "source": "You do indeed. I'll, uh, get the rest of this stuff stowed.", "translation": "Chuẩn đấy. Tui... đi cất mấy thứ này cái đã." },
    { "source": "You take it easy now!", "translation": "Đi thong thả!" }
  ]
});

fs.writeFileSync(OUTPUT_BATCH_FILE, JSON.stringify(outputs, null, 2));
console.log("Added 00400, 00401, 00402, 00403.");
