import fs from "node:fs";
import { replaceXmlStrings } from "../tools/lib/strings.js";

const translations = new Map([
  ["TIP: Hold [xi_use] to search for supplies or useful items.", "MẸO: Giữ [xi_use] để lục soát nhu yếu phẩm hoặc đồ dùng hữu ích."],
  ["TIP: Hold [sprint] + [xi_use] to search FASTER but make more NOISE.", "MẸO: Giữ [sprint] + [xi_use] để lục soát NHANH HƠN nhưng gây ra nhiều TIẾNG ỒN hơn."],
  ["TIP: Press [xi_use] to enter or exit a car.", "MẸO: Nhấn [xi_use] để vào hoặc ra khỏi xe."],
  ["TIP: Press [drop] to drop rucksacks.", "MẸO: Nhấn [drop] để thả ba lô xuống."],
  ["TIP: Hold [emote_hold] and tap [item] to drop rucksacks.", "MẸO: Giữ [emote_hold] và nhấn [item] để thả ba lô xuống."],
  ["TIP: The green icons represent mission opportunities.", "MẸO: Biểu tượng màu xanh lá cây đại diện cho cơ hội làm nhiệm vụ."],
  ["TIP: The blue ring shows your mission objective.", "MẸO: Vòng tròn màu xanh lam hiển thị mục tiêu nhiệm vụ của bạn."],
  ["TIP: Taking emergency supplies requires INFLUENCE.", "MẸO: Lấy nhu yếu phẩm khẩn cấp yêu cầu phải có ẢNH HƯỞNG."],
  ["Earn INFLUENCE by completing missions, gathering supplies, and defending your home.", "Kiếm ẢNH HƯỞNG bằng cách hoàn thành nhiệm vụ, thu thập nhu yếu phẩm và bảo vệ cứ điểm."],
  ["TIP: Use [ui_lb] and [ui_rb] to view other item types.", "MẸO: Dùng [ui_lb] và [ui_rb] để xem các loại vật phẩm khác."],
  ["You have new Events in your Journal! Press [ul_journal_menu] to open your Journal and review things that have happened to you on the Events page.", "Có sự kiện mới trong Sổ Tay! Nhấn [ul_journal_menu] mở Sổ Tay và xem lại các sự kiện đã diễn ra trong trang Sự Kiện."],
  ["You have new Events in your Journal! Press D-pad [xi_dpad_up] to open your Journal and review things that have happened to you on the Events page.", "Có sự kiện mới trong Sổ Tay! Nhấn D-pad [xi_dpad_up] mở Sổ Tay và xem lại các sự kiện đã diễn ra trong trang Sự Kiện."],
  ["The Events page keeps a log of things that happen to you as you play, including new mission opportunities, results of previous missions, community events, skill upgrades, and global events that impact you and your fellow survivors in Trumbull Valley.\r\nUse the mouse to select an event to show more details such as the people involved, and the associated rewards and bonuses.", "Trang Sự Kiện ghi lại nhật ký những gì xảy ra với bạn, bao gồm nhiệm vụ mới, kết quả nhiệm vụ cũ, sự kiện cộng đồng, nâng cấp kỹ năng, và các sự kiện ảnh hưởng tới những người sống sót ở thung lũng Trumbull.\r\nDùng chuột chọn sự kiện để xem chi tiết như người liên quan, phần thưởng và lợi ích kèm theo."],
  ["The Events page keeps a log of things that happen to you as you play, including new mission opportunities, results of previous missions, community events, skill upgrades, and global events that impact you and your fellow survivors in Trumbull Valley.\r\nUse the D-pad to select an event and press [xi_a] to show more details such as the people involved, and the associated rewards and bonuses.", "Trang Sự Kiện ghi lại nhật ký những gì xảy ra với bạn, bao gồm nhiệm vụ mới, kết quả nhiệm vụ cũ, sự kiện cộng đồng, nâng cấp kỹ năng, và các sự kiện ảnh hưởng tới những người sống sót ở thung lũng Trumbull.\r\nDùng D-pad chọn sự kiện và nhấn [xi_a] để xem chi tiết như người liên quan, phần thưởng và lợi ích kèm theo."],
  ["You've leveled up a Skill! Press [ul_journal_menu] to open your Journal and view your Skills and Abilities on the Survivor page.", "Kỹ năng vừa thăng cấp! Nhấn [ul_journal_menu] mở Sổ Tay và xem Kỹ Năng cũng như Năng Lực trên trang Người Sống Sót."],
  ["You've leveled up a Skill! Press D-pad [xi_dpad_up] to open your Journal and view your Skills and Abilities on the Survivor page.", "Kỹ năng vừa thăng cấp! Nhấn D-pad [xi_dpad_up] mở Sổ Tay và xem Kỹ Năng cũng như Năng Lực trên trang Người Sống Sót."],
  ["The Survivor page is where you view your progress in various Skills.  Everyone you encounter will have a different set of skills at their disposal.\r\nTo learn more about a Skill such as how to train it up, how it helps you, and what new abilities it unlocks; select a Skill with the mouse. Some skills, such as Fighting, will allow you to further specialize and learn new techniques.", "Trang Người Sống Sót là nơi xem tiến trình Kỹ Năng. Mỗi người sẽ có một bộ kỹ năng riêng biệt.\r\nĐể tìm hiểu thêm về cách huấn luyện một Kỹ Năng, lợi ích của nó, và những Năng Lực mà nó mở khóa; hãy dùng chuột chọn Kỹ Năng đó. Vài kỹ năng như Chiến Đấu cho phép bạn chuyên môn hóa và học chiêu thức mới."],
  ["The Survivor page is where you view your progress in various Skills.  Everyone you encounter will have a different set of skills at their disposal.\r\nTo learn more about a Skill such as how to train it up, how it helps you, and what new abilities it unlocks; select a Skill with the D-Pad and press [xi_a].  Some skills, such as Fighting, will allow you to further specialize and learn new techniques.", "Trang Người Sống Sót là nơi xem tiến trình Kỹ Năng. Mỗi người sẽ có một bộ kỹ năng riêng biệt.\r\nĐể tìm hiểu thêm về cách huấn luyện một Kỹ Năng, lợi ích của nó, và những Năng Lực mà nó mở khóa; dùng D-Pad chọn Kỹ Năng và nhấn [xi_a]. Vài kỹ năng như Chiến Đấu cho phép chuyên môn hóa và học chiêu thức mới."],
  ["Press [ul_journal_menu] to open your Journal and manage your Inventory on the Survivor page.", "Nhấn [ul_journal_menu] mở Sổ Tay và quản lý Túi Đồ ở trang Người Sống Sót."],
  ["Press D-pad [xi_dpad_up] to open your Journal and manage your Inventory on the Survivor page.", "Nhấn D-pad [xi_dpad_up] mở Sổ Tay và quản lý Túi Đồ ở trang Người Sống Sót."],
  ["The Survivor page shows information on your character, such as Name, Equipment, Traits, Skills, and Status. Use the mouse to highlight specific items to see more information.\r\nYou can also use the mouse to manage items in your inventory. This is where you will Equip and Unequip weapons, Reload guns, Use consumables, and Destroy unwanted items.", "Trang Người Sống Sót hiển thị Tên, Trang Bị, Đặc Điểm, Kỹ Năng và Trạng Thái. Dùng chuột trỏ vào vật phẩm để xem chi tiết.\r\nBạn cũng có thể dùng chuột quản lý túi đồ. Đây là nơi bạn Trang bị, Tháo vũ khí, Nạp đạn, Dùng vật phẩm và Phá hủy đồ vật không cần thiết."],
  ["The Survivor page shows information on your character, such as Name, Equipment, Traits, Skills, and Status.  Use the D-pad to highlight specific items to see more information.\r\nYou can also use D-pad [xi_dpad_left] to manage items in your inventory.  This is where you will Equip and Unequip weapons, Reload guns, Use consumables, and Destroy unwanted items.", "Trang Người Sống Sót hiển thị Tên, Trang Bị, Đặc Điểm, Kỹ Năng và Trạng Thái. Dùng D-pad trỏ vào vật phẩm để xem chi tiết.\r\nBạn cũng có thể dùng D-pad [xi_dpad_left] quản lý túi đồ. Đây là nơi bạn Trang bị, Tháo vũ khí, Nạp đạn, Dùng vật phẩm và Phá hủy đồ vật không cần thiết."],
  ["You've joined a Community! Press [ul_journal_menu] to open your Journal and learn more about your fellow survivors on the Community page.", "Bạn vừa gia nhập Cộng Đồng! Nhấn [ul_journal_menu] mở Sổ Tay và tìm hiểu những người sống sót khác ở trang Cộng Đồng."],
  ["You've joined a Community! Press D-pad [xi_dpad_up] to open your Journal and learn more about your fellow survivors on the Community page.", "Bạn vừa gia nhập Cộng Đồng! Nhấn D-pad [xi_dpad_up] mở Sổ Tay và tìm hiểu những người sống sót khác ở trang Cộng Đồng."],
  ["The Community page shows information on characters in your community.  Character portraits may be shaded to indicate conditions such as Hurt, Sick, or Tired.\r\nUse the mouse to highlight a character and view Name, Equipment, Traits, Skills, and Status. Select the character to highlight specific items to see more information.", "Trang Cộng Đồng hiển thị thông tin các thành viên. Ảnh đại diện có thể bị làm tối để báo hiệu tình trạng như Bị Thương, Ốm, hoặc Mệt Mỏi.\r\nDùng chuột chọn nhân vật để xem chi tiết Tên, Trang Bị, Đặc Điểm, Kỹ Năng và Trạng Thái. Chọn nhân vật để làm nổi bật các trang bị tương ứng."],
  ["The Community page shows information on characters in your community.  Character portraits may be shaded to indicate conditions such as Hurt, Sick, or Tired.\r\nUse the D-pad to highlight a character and view Name, Equipment, Traits, Skills, and Status.  Press [xi_a] and use the D-pad to highlight specific items to see more information.", "Trang Cộng Đồng hiển thị thông tin các thành viên. Ảnh đại diện có thể bị làm tối để báo hiệu tình trạng Bị Thương, Ốm, hoặc Mệt Mỏi.\r\nDùng D-pad chọn nhân vật để xem Tên, Trang Bị, Đặc Điểm, Kỹ Năng và Trạng Thái. Nhấn [xi_a] và dùng D-pad chọn trang bị tương ứng để xem thông tin chi tiết."],
  ["You have a new Home! Press [ul_journal_menu] to open your Journal and view your Stockpiles and Possessions on the Assets page.", "Bạn đã có Cứ Điểm mới! Nhấn [ul_journal_menu] mở Sổ Tay để xem Kho Dự Trữ và Tài Sản ở trang Tài Sản."],
  ["You have a new Home! Press D-pad [xi_dpad_up] to open your Journal and view your Stockpiles and Possessions on the Assets page.", "Bạn đã có Cứ Điểm mới! Nhấn D-pad [xi_dpad_up] mở Sổ Tay để xem Kho Dự Trữ và Tài Sản ở trang Tài Sản."],
  ["The Assets page is where you can get an overview of your Community's Assets. Use the mouse to highlight specific items to get more information.\r\nStatus and Possessions show statistical information about your Community.\r\nStockpiles are the resources you'll need to keep your Community alive, safe, and healthy.", "Trang Tài Sản là nơi bạn có cái nhìn tổng quan về Tài Sản của Cộng Đồng. Dùng chuột chọn vật phẩm để xem thêm thông tin.\r\nTrạng Thái và Tài Sản hiển thị dữ liệu thống kê về Cộng Đồng.\r\nKho Dự Trữ là nguồn lực bạn cần để giữ cho Cộng Đồng tồn tại, an toàn và khỏe mạnh."],
  ["The Assets page is where you can get an overview of your Community's Assets. Use the D-Pad to highlight specific items to get more information.\r\nStatus and Possessions show statistical information about your Community.\r\nStockpiles are the resources you'll need to keep your Community alive, safe, and healthy.", "Trang Tài Sản là nơi bạn có cái nhìn tổng quan về Tài Sản của Cộng Đồng. Dùng D-Pad chọn vật phẩm để xem thêm thông tin.\r\nTrạng Thái và Tài Sản hiển thị dữ liệu thống kê về Cộng Đồng.\r\nKho Dự Trữ là nguồn lực bạn cần để giữ cho Cộng Đồng tồn tại, an toàn và khỏe mạnh."]
]);

const OUTPUT_FILE = "output/gamedata/libs/class3/contentmanager/hints.xml";
const INPUT_FILE = "input/gamedata/libs/class3/contentmanager/hints.xml";

const sourceXml = fs.existsSync(OUTPUT_FILE) ? fs.readFileSync(OUTPUT_FILE, "utf8") : fs.readFileSync(INPUT_FILE, "utf8");
const translatedXml = replaceXmlStrings(sourceXml, translations);

if (!fs.existsSync("output/gamedata/libs/class3/contentmanager")) {
  fs.mkdirSync("output/gamedata/libs/class3/contentmanager", { recursive: true });
}
fs.writeFileSync(OUTPUT_FILE, translatedXml);

console.log(`Translated 30 strings in ${OUTPUT_FILE}`);
