const fs = require('fs');
const chunk108 = {
  "We've got zeds on the west gate!": "Có zeds ở cổng phía tây!",
  "Ah, who am I kidding, before too long some motherfucker with an instant camera and a permanent marker's gonna drag us back down.": "À, tôi đùa ai chứ, chẳng mấy chốc sẽ có một thằng khốn nào đó với cái máy ảnh chụp lấy ngay và một cây bút lông sẽ kéo chúng ta xuống mồ.",
  "Goddammit, Doc! All I want to know is how Eli's doing?": "Mẹ kiếp, Bác sĩ! Tôi chỉ muốn biết Eli đang thế nào thôi?",
  "So I guess we're walking, then?": "Vậy tôi đoán là chúng ta phải cuốc bộ rồi?",
  "We Kick Ass": "Chúng Ta Cân Tất",
  "No idea, sir. Have the scientists learned anything from his samples?": "Không biết nữa, thưa ngài. Các nhà khoa học đã tìm ra gì từ các mẫu vật của hắn ta chưa?",
  "Lindsey": "Lindsey",
  "Quentin, wait!": "Quentin, đợi đã!",
  "Raises shooting skill for the whole community.": "Tăng cường kỹ năng bắn súng cho toàn bộ cộng đồng.",
  "Distraction Progress": "Tiến Độ Đánh Lạc Hướng",
  "Della": "Della",
  "Do you know what it's like out there? No, uh-uh, no we'd get killed in a second! I'll stay here.": "Cậu có biết ngoài kia thế nào không? Không, không đời nào, chúng ta sẽ chết ngay tắp lự! Tôi sẽ ở lại đây.",
  "I bench press more than my body weight, if that's what you mean.": "Tôi có thể đẩy tạ nằm nhiều hơn trọng lượng cơ thể mình, nếu đó là điều cậu muốn hỏi.",
  "Nicely done. Nicely done.": "Làm tốt lắm. Làm tốt lắm.",
  "Aw man, I was stupid. I was searching this garage for some gas for the generators, when some of those cops from the courthouse start coming up the street.": "Trời ạ, tôi ngu quá. Tôi đang lục lọi cái ga ra này để tìm chút xăng cho máy phát điện, thì vài tên cảnh sát từ tòa án bắt đầu tiến tới trên đường.",
  "Well, if it ain't everybody's favorite. What you after?": "Chà, đây chẳng phải là cục cưng của mọi người sao. Cậu đang tìm kiếm thứ gì?",
  "Losing patience with this nonsense.": "Mất kiên nhẫn với trò nhảm nhí này rồi.",
  "Did he say Eli?": "Anh ta vừa nói Eli sao?",
  "Black Friday, this is Doghouse.": "Black Friday, đây là Doghouse.",
  "Not happening.": "Không có chuyện đó đâu.",
  "No, you can't-": "Không, cậu không thể-",
  "Clear the infestations with Sheriff Carl.": "Dọn dẹp các Ổ Dịch (Infestation) cùng với Cảnh sát trưởng Carl.",
  "Cochran": "Cochran",
  "Every time you kill an enemy, you regain a small amount of Stamina.": "Mỗi khi giết một kẻ thù, bạn sẽ hồi lại một lượng nhỏ Thể lực (Stamina).",
  "I'm on bed rest till this thing gets better.": "Tôi phải nằm bất động trên giường cho đến khi chuyện này khá hơn.",
  "Looks like the moment has passed.": "Có vẻ như cơ hội đã trôi qua rồi.",
  "Alright, here's the situation. This pass is the only way out of the valley, and the Army clearly doesn't want us leaving anytime soon.": "Được rồi, tình hình là thế này. Con đèo này là lối thoát duy nhất khỏi thung lũng, và Quân đội rõ ràng không muốn chúng ta rời đi sớm đâu.",
  "Hold still, motherfucker...": "Đứng yên, thằng khốn...",
  "I really gotta get a suppressor!": "Tôi thực sự phải kiếm một cái nòng giảm thanh!",
  "SMG: P9 Forge": "Tiểu liên (SMG): P9 Forge",
  "Holy shit. I think we're in the clear.": "Vãi thật. Tôi nghĩ chúng ta an toàn rồi.",
  "If they hit us again any time soon, we're in trouble.": "Nếu chúng tấn công chúng ta lần nữa trong thời gian ngắn, chúng ta sẽ gặp rắc rối to đấy.",
  "Delete Saved Game": "Xóa File Lưu Game",
  "We set 'em up, you knock 'em down.": "Chúng tôi gom chúng lại, cậu hạ gục chúng.",
  "AFTERMATH: The Vet Clinic": "HẬU QUẢ: Phòng Khám Thú Y",
  "Posit one one tango mike papa two five foxtrot zero five oscar. [message end tone]": "Vị trí một một tango mike papa hai năm foxtrot không năm oscar. [âm báo kết thúc tin nhắn]",
  "Snyder Machine Shop": "Xưởng Cơ Khí Snyder",
  "Power Supply": "Nguồn Điện",
  "Anyone else want some?": "Còn ai muốn ăn đòn nữa không?",
  "Thanks to that, we're almost out of building materials.": "Vì chuyện đó, chúng ta gần như cạn kiệt vật liệu xây dựng rồi.",
  "That bought us a little time. Let's resupply and get ready for the next wave.": "Việc đó đã câu thêm cho chúng ta một chút thời gian. Hãy tiếp tế và chuẩn bị sẵn sàng cho đợt tấn công tiếp theo.",
  "Check your map.": "Kiểm tra bản đồ của cậu đi.",
  "Fernandez": "Fernandez",
  "I'll sleep easier now.": "Giờ thì tôi sẽ dễ ngủ hơn rồi.",
  "Unwelcome Guest": "Vị Khách Không Mời",
  "It's not overrun with murderous walking dead guys, right? I mean, it's pretty safe there?": "Nơi đó không bị tràn ngập bởi bọn xác chết biết đi khát máu chứ, phải không? Ý tôi là, ở đó khá an toàn chứ?",
  "Listen to me! I don't have long, I can feel the change coming.": "Nghe tôi này! Tôi không còn nhiều thời gian, tôi có thể cảm nhận được sự biến đổi đang đến.",
  "Let's dance!": "Quẩy lên nào!",
  "For all I know, this is all their fault!": "Theo những gì tôi biết, tất cả chuyện này đều là lỗi của chúng!",
  "Numbs the pain, but won't help serious wounds. Serious stuff. Feels pretty damn good, though.": "Làm tê liệt cơn đau, nhưng không có tác dụng với các vết thương nghiêm trọng. Một thứ thuốc nặng đô. Dù sao thì, cảm giác cũng khá là tuyệt đấy.",
  "Make Incendiary Rounds": "Chế Tạo Đạn Cháy (Incendiary Rounds)",
  "Col": "Đại tá",
  "Hoarded Stuff": "Đồ Tích Trữ",
  "There it is.": "Nó kia rồi.",
  "Can I uh, can help you?": "Tôi có thể... ừm, có thể giúp gì cho cậu không?",
  "Quentin's in shock.": "Quentin đang bị sốc.",
  "Electricity": "Điện",
  "I'll have another name for you soon. Try to keep somebody alive till then.": "Tôi sẽ sớm gửi cho các anh một cái tên khác. Cố gắng giữ mạng cho người nào đó cho đến lúc ấy nhé.",
  "Y'know, it seems like you've been really tense lately.": "Cậu biết không, dạo này trông cậu có vẻ rất căng thẳng đấy.",
  "Hope people aren't accusing me of not pulling my own weight because of this injury.": "Hy vọng mọi người không chỉ trích tôi là kẻ vô dụng ăn bám chỉ vì vết thương này.",
  "Useful ITEMS that we've found or made. Gotta plan carefully while loading up a backpack.": "Các VẬT PHẨM (ITEMS) hữu ích mà chúng ta đã tìm thấy hoặc tự chế. Phải lên kế hoạch cẩn thận khi chất đồ vào ba lô.",
  "We got your cyclophophosphamide, Lily. I didn't see any of that metho-whatever.": "Chúng tôi đã lấy được thuốc cyclophosphamide cho cô, Lily. Tôi không thấy cái loại metho-gì-gì đó đâu cả.",
  "I just want to be able to get my damn paper without having a twenty minute conversation about Aunt Mabel and her bunion troubles, you know?": "Tôi chỉ muốn có thể ra lấy tờ báo chết tiệt của mình mà không phải chịu đựng cuộc nói chuyện dài 20 phút về dì Mabel và rắc rối với cái mụn ở chân của bà ấy, cậu hiểu không?",
  "Make 7.62mm Ammo": "Chế Tạo Đạn 7.62mm",
  "Eli? What? What happened to him?": "Eli? Cái gì? Có chuyện gì xảy ra với anh ấy?",
  "MEDICINE is needed for a chance at recovery.": "THUỐC MEN (MEDICINE) là cần thiết để có cơ hội phục hồi.",
  "That's it. I'm out of here.": "Thế là quá đủ rồi. Tôi chuồn khỏi đây thôi.",
  "Here come da boom!": "Bùm chéo đây!",
  "Even the best needs some help sometimes!": "Ngay cả người giỏi nhất đôi khi cũng cần sự giúp đỡ!",
  "Dude, I've never seen anybody kill as many zeds as %2$s! It was freaking unreal! Totally worth all the ammo we used. - %1$s": "Này, tôi chưa bao giờ thấy ai giết nhiều zeds như %2$s! Thật không thể tin nổi! Hoàn toàn xứng đáng với số lượng đạn mà chúng ta đã tiêu tốn. - %1$s",
  "Vaccarini": "Vaccarini",
  "I don't think \"ambush\" is these guys' MO. More like \"run at you screaming and try to eat your face.\"": "Tôi không nghĩ \"phục kích\" là phương thức hoạt động của bọn này. Giống kiểu \"hét toáng lên chạy về phía cậu và cố gắng ăn thịt khuôn mặt cậu\" thì đúng hơn.",
  "You've leveled up a Skill! Press [ul_journal_menu] to open your Journal and view your Skills and Abilities on the Survivor page.": "Bạn vừa thăng cấp một Kỹ năng! Nhấn [ul_journal_menu] để mở Nhật ký (Journal) và xem các Kỹ năng cũng như Khả năng của bạn ở trang Người Sống Sót (Survivor).",
  "That sounds bad.": "Nghe có vẻ tệ đấy.",
  "Alvarado": "Alvarado",
  "With results like this, don't expect to be out there for long. Highroad out.": "Với kết quả như thế này, đừng hy vọng có thể ở ngoài đó được lâu. Highroad, hết.",
  "OPPORTUNITY: Train Outsiders": "CƠ HỘI: Huấn luyện Người Ngoài",
  "I tell you about the zed I wasted the other day?": "Tôi đã kể cho cậu nghe về con zed mà tôi tiêu diệt hôm nọ chưa?",
  "Springs": "Lò Xo",
  "BUILT: Training Area": "ĐÃ XÂY: Khu Huấn Luyện",
  "Tate": "Tate",
  "I ... can't discuss this with you.": "Tôi... không thể thảo luận chuyện này với cậu.",
  "When you're ready to contact Highroad for new orders, just give us the word.": "Khi các anh đã sẵn sàng liên lạc với Highroad để nhận mệnh lệnh mới, chỉ cần báo một tiếng.",
  "Make Mild Stims": "Chế Tạo Thuốc Kích Thích Nhẹ (Mild Stims)",
  "%2$s knows what he did. - %1$s": "%2$s thừa hiểu những gì hắn đã làm. - %1$s",
  "Problem solved.": "Vấn đề đã được giải quyết.",
  "You know what's sad? I'm already starting to forget what it felt like to be worried about normal shit.": "Cậu biết điều gì đáng buồn không? Tôi đã bắt đầu quên mất cảm giác lo lắng về những thứ bình thường là như thế nào rồi.",
  "Time to run this back to base.": "Đến lúc mang thứ này chạy về căn cứ rồi.",
  "If you've got the means, get over there and help out!": "Nếu cậu có khả năng, hãy đến đó và giúp một tay!",
  "Sergeant Eldridge got tired of waiting around for orders. It's like he's never been in the Army before. In any case, he gone now. Hope he doesn't do too much damage out there on his own.": "Trung sĩ Eldridge đã mệt mỏi với việc chờ đợi mệnh lệnh. Cứ như thể anh ta chưa từng ở trong Quân đội trước đây vậy. Dù sao thì, anh ta cũng đã đi rồi. Hy vọng anh ta không tự mình gây ra quá nhiều thiệt hại ngoài đó.",
  "SET UP: Workshop": "THIẾT LẬP: Xưởng (Workshop)",
  "Max. Stamina": "Thể Lực Tối Đa",
  "Vehicles": "Phương Tiện",
  "Grey": "Màu Xám",
  "Well, that was a total disaster. %1$s and the team got their butts kicked by that infestation. - %2$s": "Chà, đúng là một thảm họa tồi tệ. %1$s và nhóm đã bị cái Ổ dịch đó đánh cho tơi bời. - %2$s",
  "Automatically repair Body and Tire damage for vehicles parked overnight.": "Tự động sửa chữa hư hỏng cho Thân vỏ và Lốp của các phương tiện được đậu qua đêm.",
  "Dramatically decreases construction and upgrade times for facilities.": "Giảm đáng kể thời gian xây dựng và nâng cấp cho các cơ sở vật chất.",
  "Curl Bar": "Thanh Tạ Đòn (Curl Bar)",
  "Well, I should hope so.": "Chà, tôi cũng hy vọng thế.",
  "Potassium": "Kali"
};

const file = 'output/languages/chunks/btxt_chunk_108.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_108.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk108[r.sourceText]) {
    r.translatedText = chunk108[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 108 successfully!');
