const fs = require('fs');
const chunk158 = {
  "Tell me a little about your dad.": "Kể cho tôi nghe một chút về bố cậu đi.",
  "You saved my ass.": "Cậu đã cứu mạng tôi đấy.",
  "They don't care who dies, as long as they solve their little problem. Well, I care. So I'm bringing the news to you.": "Họ đéo quan tâm ai chết, miễn là họ giải quyết được vấn đề cỏn con của họ. Chà, tôi quan tâm. Vì vậy, tôi mang tin tức này đến cho cậu.",
  "But I guess they know where to find us.": "Nhưng tôi đoán họ biết tìm chúng ta ở đâu.",
  "I think we can try that again.": "Tôi nghĩ chúng ta có thể thử lại việc đó.",
  "SCRAPPED: Lily's Brother": "ĐÃ HỦY: Anh trai của Lily",
  "On second thought. Hold off. This place isn't safe.": "Nghĩ lại thì. Dừng lại đã. Nơi này đéo an toàn.",
  "%s : %s": "%s : %s",
  "Your friend needs antibiotics, I need medicine, so I kinda... sent you to a place you might find both.": "Bạn của cậu cần thuốc kháng sinh, tôi cần thuốc, nên tôi kiểu như... đã gửi cậu đến một nơi mà cậu có thể tìm thấy cả hai thứ đó.",
  "Damn good thing the zombies tore this place up. We gotta fix this before people start getting sick.": "May quá là bọn zombie đã phá nát chỗ này. Chúng ta phải sửa chữa nơi này trước khi mọi người bắt đầu đổ bệnh.",
  "Sure, take your time. Not like we're all slowly dying of dead guy plague or anything.": "Chắc chắn rồi, cứ từ từ. Đéo phải kiểu như tất cả chúng ta đều đang chết dần chết mòn vì bệnh dịch xác sống hay gì đó đâu.",
  "PERSONAL SKILL. \"No white after Labor Day\" is just the beginning.": "KỸ NĂNG CÁ NHÂN. \"Đéo mặc màu trắng sau Ngày Lễ Lao Động (Labor Day)\" chỉ là sự khởi đầu.",
  "Conner": "Conner",
  "Better shut that screamer up first.": "Tốt hơn là nên bịt mõm con screamer đó lại trước đi.",
  "DECLINED: Special Delivery": "ĐÃ TỪ CHỐI: Giao Hàng Đặc Biệt (Special Delivery)",
  "Hatchet": "Rìu Nhỏ (Hatchet)",
  "When they figure out who's responsible for this epidemic, there's going to be one hell of a lawsuit filed against them. (Jurisprudence expertise.)": "Khi họ tìm ra ai phải chịu trách nhiệm cho dịch bệnh này, sẽ có một vụ kiện tụng ra trò nhằm vào chúng. (Chuyên môn Luật học - Jurisprudence expertise.)",
  "Marissa": "Marissa",
  "So next time you piss somebody off, make sure they're not armed.": "Nên lần tới khi cậu chọc giận ai đó, hãy chắc chắn rằng họ đéo có vũ trang.",
  "Carson": "Carson",
  "Horde attacking home!": "Một bầy horde đang tấn công nhà!",
  "Yeah? Huh. Maybe Quentin's right after all.": "Vậy sao? Hả. Rốt cuộc có lẽ Quentin đã đúng.",
  "%+d Friendship with Everyone at Home": "%+d Tình Bạn với Mọi người ở Nhà",
  "It's like high school all over again, except the glee club wants to eat me. - %1$s": "Nó giống hệt như thời trung học lặp lại vậy, ngoại trừ việc câu lạc bộ hợp xướng muốn ăn thịt tôi. - %1$s",
  "Why go into one of the most dangerous parts of the city, just to get one Screamer? There must be something else.": "Tại sao lại đi vào một trong những nơi nguy hiểm nhất của thành phố, chỉ để tóm một con Screamer chứ? Chắc chắn phải có chuyện gì đó khác.",
  "I could see forever from up there!": "Tôi có thể nhìn thấy mọi thứ từ trên đó!",
  "I understand. These things are monsters. But that doesn't give us an excuse to be monsters, too.": "Tôi hiểu. Những thứ này là quái vật. Nhưng điều đó đéo cho chúng ta cái cớ để cũng trở thành quái vật.",
  "… Dad?": "… Bố?",
  "TRUST LOST (Ally in Blast Radius)": "MẤT NIỀM TIN (Đồng Minh trong Vùng Nổ)",
  "Trade our Ammo for some Food?": "Đổi Đạn của chúng ta lấy một ít Thức Ăn chứ?",
  "Greyhound One Alpha to Bravo, what's your status? Bravo, come in!": "Greyhound Một Alpha gọi Bravo, tình hình của các anh sao rồi? Bravo, nghe rõ trả lời!",
  "Let's do this fast. Grab the shit and get the hell out of here.": "Hãy làm việc này thật nhanh. Lấy đồ rồi cút thẳng khỏi đây thôi.",
  "Sounds nice.": "Nghe tuyệt đấy.",
  "Doghouse, this is Black Friday. We've got a helo inbound. Refugees onboard.": "Nhà Chó (Doghouse), đây là Black Friday. Chúng tôi có một chiếc trực thăng đang bay đến. Có người tị nạn trên khoang.",
  "Clayton": "Clayton",
  "START MISSION. Seems like a harmless way to earn a little goodwill.": "BẮT ĐẦU NHIỆM VỤ. Có vẻ như đây là một cách vô hại để kiếm chút thiện chí.",
  "Advice: Build a Training Area": "Lời Khuyên: Xây Dựng Một Khu Vực Huấn Luyện (Training Area)",
  "Our friend here would be happy to take you home. Wouldn't you, friend?": "Bạn của chúng tôi ở đây sẽ rất vui được đưa cậu về nhà. Đúng đéo, anh bạn?",
  "That should give us a better sense of where we stand. -%1$s": "Điều đó sẽ cho chúng ta biết rõ hơn về tình thế của mình hiện tại. -%1$s",
  "+300% research speed. REQUIRES GOOD RESEARCHER.": "+300% tốc độ nghiên cứu. YÊU CẦU NGƯỜI NGHIÊN CỨU TỐT.",
  "Hector": "Hector",
  "Copper Wire": "Dây Đồng",
  "Colton?": "Colton?",
  "Got Doc Hanson out of a jam at the cemetery. He's offered to provide medical advice to me and my friends. - %1$s": "Đã cứu Doc Hanson thoát khỏi cảnh kẹt cứng ở nghĩa trang. Ông ấy đề nghị cung cấp lời khuyên y tế cho tôi và bạn bè của tôi. - %1$s",
  "Sleeping quarters. Hope you don't mind sharing, we're pretty tight on space here.": "Khu vực ngủ nghỉ. Hy vọng cậu đéo phiền khi phải ngủ chung, không gian ở đây của chúng ta khá chật hẹp.",
  "I did. Carl said that Alex is her real name. She, ahh... she worked at the truck depot, you could say.": "Tôi đã làm. Carl nói rằng Alex là tên thật của cô ấy. Cô ấy, ahh... cậu có thể nói là cô ấy làm việc ở bến xe tải.",
  "Upgrading to Sat-Comms makes it easier to maintain more Outposts in the field. (Max Outposts raised to 8)": "Nâng cấp lên Vệ Tinh Viễn Thông (Sat-Comms) giúp duy trì nhiều Tiền đồn (Outpost) trên thực địa dễ dàng hơn. (Giới hạn Tiền đồn tối đa tăng lên 8)",
  "Was there something else?": "Còn chuyện gì nữa đéo?",
  "Yeah. We're on our way.": "Ừ. Chúng tôi đang trên đường đến đây.",
  "I gathered resources and brought them home. - %1$s.": "Tôi đã thu thập các tài nguyên và mang chúng về nhà. - %1$s.",
  "Here's your meds, no thanks to dumbass over there.": "Thuốc của cậu đây, đéo nhờ gì thằng ngu bên kia đâu.",
  "Sounds like a plan.": "Nghe có vẻ là một kế hoạch đấy.",
  "I can't keep going out there if I never get any rest when I'm here. It's gonna get me killed. - %1$s": "Tôi đéo thể tiếp tục ra ngoài đó nếu tôi đéo bao giờ được nghỉ ngơi khi ở đây. Chuyện đó sẽ giết chết tôi mất. - %1$s",
  "Controller Invert Y-Axis": "Đảo Ngược Trục Y Trên Tay Cầm (Controller Invert Y-Axis)",
  "Jamie": "Jamie",
  "Galugau": "Galugau",
  "Gen": "Gen",
  "Thanks to some solid tactical planning, we've managed to recover some food from the surrounding area.": "Nhờ một số kế hoạch chiến thuật vững chắc, chúng ta đã có thể thu hồi được một ít thức ăn từ khu vực xung quanh.",
  "Never thought we'd have to worry so much about a case of salmonella.": "Chưa bao giờ nghĩ rằng chúng ta lại phải lo lắng đến thế về một ca nhiễm khuẩn salmonella.",
  "DECLINED: Accusations": "ĐÃ TỪ CHỐI: Những Lời Buộc Tội (Accusations)",
  "Supplies Delivered": "Đã Giao Nhu Yếu Phẩm",
  "Those things are disgusting.": "Những thứ đó thật tởm lợm.",
  "12 GENERIC Grant Marshall": "12 CHUNG (GENERIC) Grant Marshall",
  "SitRep: India": "Báo Cáo Tình Hình (SitRep): India",
  "Gamma": "Gamma",
  "Holy Rolling": "Cuộn Thảo Dược Thần Thánh (Holy Rolling)",
  "Soliz": "Soliz",
  "To provide Electricity.": "Để cung cấp Điện.",
  "When soldiers come back from the battlefield, sometimes they have injuries that a few painkillers won't fix. The Surgery allows us to fix them up properly.": "Khi binh lính trở về từ chiến trường, đôi khi họ mang theo những vết thương mà vài viên thuốc giảm đau đéo thể chữa khỏi được. Phòng Phẫu Thuật (Surgery) cho phép chúng ta chữa trị cho họ một cách tử tế.",
  "This space used to be a restaurant. Fix it up, and we could use it as a mess for the soldiers.": "Không gian này từng là một nhà hàng. Hãy sửa sang lại nó, và chúng ta có thể sử dụng nó làm nhà ăn (mess) cho những người lính.",
  "Lower your voice. It's all we can do right now. Your family wouldn't want you to die.": "Nhỏ giọng lại đi. Đó là tất cả những gì chúng ta có thể làm lúc này. Gia đình cô đéo muốn cô chết đâu.",
  "Hey, you seem to have brains you're not using. Maybe I should just take a sample out of YOUR head.": "Này, anh có vẻ có não mà đéo dùng tới. Có lẽ tôi nên lấy mẫu thẳng từ trong đầu ANH luôn đi.",
  "Watch your ammo and reload when it's safe.": "Hãy chú ý đến lượng đạn và nạp lại khi an toàn.",
  "Otto": "Otto",
  "Help destroy a feral zed.": "Giúp tiêu diệt một con zed feral.",
  "Sweet Jesus, it's about time we finished.": "Chúa ơi, đã đến lúc chúng ta hoàn thành xong chuyện này.",
  "Wait, are you serious? We're fighting a Juggernaut with sticks and knives?": "Khoan đã, cậu nghiêm túc chứ? Chúng ta đang đánh nhau với một con Juggernaut bằng gậy gộc và dao dóc sao?",
  "Weight Belts": "Đai Tập Tạ (Weight Belts)",
  "Hey Lily, tell me I still got time to get to our friends.": "Này Lily, nói với tôi là tôi vẫn còn thời gian để đến chỗ những người bạn của chúng ta đi.",
  "Nothing here.": "Đéo có gì ở đây cả.",
  "Survivor Activity": "Hoạt Động Của Người Sống Sót",
  "Williamson": "Williamson",
  "Decent Tools": "Công Cụ Tương Đối Ổn (Decent Tools)",
  "Make Box Mine": "Chế Tạo Mìn Hộp (Box Mine)",
  "Delete Error": "Lỗi Xóa",
  "Rifle: T21 Carbine 9mm": "Súng Trường: Súng T21 Carbine 9mm",
  "Looking for me?": "Tìm tôi sao?",
  "Earn a skill specialization for one of your community members.": "Kiếm một chuyên môn kỹ năng (skill specialization) cho một trong những thành viên cộng đồng của bạn.",
  "Embedded Shrapnel": "Mảnh Đạn Ghăm Vào Người (Embedded Shrapnel)",
  "Dammit! Help!": "Chết tiệt! Cứu với!",
  "ASSET PROFILE: Dr. Julene Horn": "HỒ SƠ TÀI SẢN (ASSET PROFILE): Tiến sĩ Julene Horn",
  "Pistol: P.08": "Súng Lục (Pistol): Súng P.08",
  "A wealthy museum curator from Danforth.": "Một người quản lý bảo tàng giàu có đến từ Danforth.",
  "Erlenmeyer Flask": "Bình Nón Erlenmeyer",
  "Probably kill you last....": "Chắc sẽ giết cậu cuối cùng....",
  "Hey, you think you could talk to Jacob the next time you stop by?": "Này, cậu có nghĩ cậu có thể nói chuyện với Jacob trong lần tới khi cậu ghé qua đéo?",
  "Ugh...": "Ugh...",
  "88 GENERIC Billy Bob Hicks": "88 CHUNG (GENERIC) Billy Bob Hicks",
  "Hazmat": "Đồ Bảo Hộ (Hazmat)",
  "Settle Home Base": "Thiết Lập Căn Cứ Chính (Home Base)"
};

const file = 'output/languages/chunks/btxt_chunk_158.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_158.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk158[r.sourceText]) {
    r.translatedText = chunk158[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 158 successfully!');
