const fs = require('fs');
const path = require('path');

const chunk101 = {
  "Citizens of Trumbull Valley I know it's difficult, but we must insist that you do not bury any of your re-animated loved ones, even after they've been destroyed.": "Cư dân Thung lũng Trumbull, tôi biết điều này rất khó khăn, nhưng chúng tôi buộc phải yêu cầu các vị không chôn cất những người thân đã bị biến đổi, ngay cả khi họ đã bị tiêu diệt.",
  "I must have been delirious with fever. Kept dreaming that people were murmuring about putting one in the back of my skull. Crazy, right? - %1$s": "Chắc là tôi đã nói sảng vì sốt. Cứ mơ thấy người ta đang thì thầm về việc găm một viên đạn vào sau đầu tôi. Điên rồ thật, đúng không? - %1$s",
  "SitRep: Russia": "Báo Cáo Tình Hình: Nga",
  "Alright, lady, that's enough. Off the radio.": "Được rồi thưa cô, thế là đủ rồi. Tắt bộ đàm đi.",
  "The Zombie Apocalypse": "Tận Thế Zombie",
  "We should do some experiments with food preservation. Pickling, salting, smoking, canning. So many things to try. REQUIRES SOME EXPERIMENTATION.": "Chúng ta nên thử nghiệm một số cách bảo quản thực phẩm. Ngâm chua, ướp muối, xông khói, đóng hộp. Có quá nhiều thứ để thử nghiệm. YÊU CẦU PHẢI THỬ NGHIỆM THỰC TẾ.",
  "Doctor Horn is alive. He looks like he's been through hell out here on his own, but I'll be damned if we're gonna let anything else happen to him.": "Bác sĩ Horn vẫn còn sống. Trông ông ấy như vừa trải qua địa ngục khi phải tự mình sống sót ngoài này, nhưng cứ chặt đầu tôi đi nếu chúng ta để chuyện tồi tệ nào khác xảy ra với ông ấy.",
  "Kessing": "Kessing",
  "Crude, effective movie replica.": "Một bản sao thô sơ nhưng hiệu quả bước ra từ phim ảnh.",
  "I've gotten us out of worse spots than this, right? Just stick with me.": "Tôi từng đưa chúng ta thoát khỏi những tình huống còn tồi tệ hơn thế này, đúng không? Cứ theo sát tôi.",
  "Need Medicine": "Cần Thuốc Men",
  "Boles": "Boles",
  "You stickin' around?": "Cậu tính nán lại đây à?",
  "Got a grip on him, don't he?": "Nắm thóp được anh ta rồi, đúng không?",
  "Dailey": "Dailey",
  "Group therapy.": "Trị liệu nhóm.",
  "Ain't no fuckin' way, buddy.": "Đéo có chuyện đó đâu, anh bạn.",
  "We've completed the requested upgrade, sir.": "Chúng tôi đã hoàn tất đợt nâng cấp theo yêu cầu, thưa ngài.",
  "Nobody's been able to raise %1$s on the radio. Supply runs shouldn't take this long... right? - %2$s.": "Không ai có thể liên lạc với %1$s qua bộ đàm. Các chuyến đi tìm nhu yếu phẩm không thể kéo dài như thế... đúng không? - %2$s.",
  "It sounds like something's gone wrong on her end. Well, it was fun while it lasted.": "Nghe có vẻ như bên cô ấy đã xảy ra chuyện không hay. Chà, dù sao thì cũng đã rất vui khi mọi thứ còn yên bình.",
  "Perfect. Our friends and neighbors. What should we do?": "Tuyệt hảo. Bạn bè và hàng xóm của chúng ta đấy. Chúng ta nên làm gì đây?",
  "Alexia": "Alexia",
  "This isn't a fucking vacation. I sent you in there for a reason.": "Đây đéo phải một kỳ nghỉ. Tôi cử cậu vào đó là có lý do.",
  "Mayday, mayday, mayday, we need assistance!": "Cấp cứu, cấp cứu, cấp cứu, chúng tôi cần hỗ trợ!",
  "Fuck! That wasn't half bad.": "Mẹ kiếp! Mọi chuyện cũng không đến nỗi tệ.",
  "ATTITUDE: Ambitious": "THÁI ĐỘ: Tham Vọng",
  "Power Tools": "Dụng Cụ Cầm Tay",
  "Here, I'll put it on your map.": "Đây, tôi sẽ đánh dấu nó trên bản đồ của cậu.",
  "I'm still feeling pretty energized. I should save this.": "Tôi vẫn còn cảm thấy khá sung sức. Tôi nên giữ lại cái này.",
  "SleepingPad": "Tấm Trải Ngủ",
  "Goddamn, where'd you learn to shoot like that?": "Chết tiệt, cậu học cách bắn như thế ở đâu vậy?",
  "They must be using seriously old-school equipment, 'cause I was able to crack their encryption.": "Bọn họ chắc chắn đang sử dụng những thiết bị cực kỳ lỗi thời, vì tôi đã có thể bẻ khóa lớp mã hóa của chúng.",
  "My stepdad was miserable son of a bitch. Treated me like shit, treated my mom even worse. Not really a new story, I know.": "Bố dượng tôi là một thằng khốn nạn thảm hại. Đối xử với tôi như rác rưởi, đối xử với mẹ tôi còn tệ hơn thế. Tôi biết, đó chẳng phải là một câu chuyện mới mẻ gì.",
  "May make it home on his own.": "Có thể sẽ tự mình tìm đường về nhà.",
  "EXPIRED: Dr. Dan Bogatz": "ĐÃ TỪ TRẦN: Bác sĩ Dan Bogatz",
  "Lustre": "Lustre",
  "Diehl": "Diehl",
  "Don't open the door!": "Đừng mở cửa!",
  "Sorry, we just don't have the room for you right now.": "Xin lỗi, hiện tại chúng tôi không còn chỗ cho cậu.",
  "Scientist": "Nhà Khoa Học",
  "I'm going to grab every classic I can...Dickens, Shakespeare, Frost. Losing them would be a tragedy. (Knowledge of Literature.)": "Tôi sẽ lấy mọi cuốn sách kinh điển mà tôi có thể... Dickens, Shakespeare, Frost. Đánh mất chúng sẽ là một bi kịch thực sự. (Kiến thức về Văn Học.)",
  "We just lost another group of survivors.": "Chúng ta vừa mất thêm một nhóm người sống sót khác.",
  "%d infestations discovered.": "Phát hiện %d Ổ Dịch.",
  "Grocer": "Người Bán Tạp Hóa",
  "It’s no wonder somebody abandoned that RV. Its fuel tank is totally dry.": "Chẳng trách có người lại vứt bỏ chiếc xe RV đó. Bình xăng của nó đã cạn sạch.",
  "Amber": "Amber",
  "That's what your momma said.": "Đó là những gì mẹ của mày đã nói đấy.",
  "Any joint pain? Fatigue?": "Có đau khớp không? Mệt mỏi không?",
  "I'm up. Time to look around.": "Tôi dậy rồi. Đã đến lúc xem xét xung quanh.",
  "We're almost done here.": "Chúng ta gần xong ở đây rồi.",
  "Area Clear": "Khu Vực An Toàn",
  "I've found some supplies.": "Tôi đã tìm thấy vài nhu yếu phẩm.",
  "Eckener": "Eckener",
  "Horse Trainer": "Người Huấn Luyện Ngựa",
  "Anything out there I should be aware of?": "Ngoài đó có gì mà tôi cần phải lưu ý không?",
  "Before you ask, no...I don't have sweet nunchuck skills. (Improved Cardio and Fighting.)": "Trước khi cậu hỏi, không... tôi đéo có tuyệt kỹ múa côn nhị khúc nào đâu. (Tăng Cường Thể Lực và Chiến Đấu.)",
  "Start New Game": "Bắt Đầu Trò Chơi Mới",
  "Bugged out. Well, the ones that weren't sick or hurt, at least. You saw what they did with them.": "Bỏ trốn hết rồi. Chà, ít nhất là những người không bị ốm hay bị thương. Cậu đã thấy những gì chúng làm với họ rồi đấy.",
  "Spartan Sword": "Thanh Kiếm Spartan",
  "Good for you.": "Tốt cho cậu.",
  "To those of you who are left ... get out of the city and make for the capital. We'll be waiting.": "Gửi tới những ai còn sống sót... hãy thoát khỏi thành phố và tiến thẳng đến thủ đô. Chúng tôi sẽ chờ.",
  "Hamburger Buns": "Bánh Mì Kẹp Thịt",
  "Intel said they were dug in pretty good, but they weren't well-armed. We figured it'd be a piece of cake.": "Tin tình báo cho biết họ cố thủ khá kỹ, nhưng lại không được trang bị vũ khí tốt. Bọn tôi cứ tưởng đó sẽ là một miếng bánh ngon.",
  "%s Known": "Đã Biết %s",
  "Gagnon": "Gagnon",
  "START MISSION. Help defend the survivors.": "BẮT ĐẦU NHIỆM VỤ. Giúp bảo vệ những người sống sót.",
  "Ally Hurt": "Đồng Minh Bị Thương",
  "New neighbors.": "Những người hàng xóm mới.",
  "Duck and dodge, soldier!": "Cúi đầu và né tránh đi, người lính!",
  "- %1$s": "- %1$s",
  "Angelina": "Angelina",
  "Any word on the medivac?": "Có tin tức gì về đội sơ tán y tế chưa?",
  "Now, doesn't that just give you a warm fuzzy feeling?": "Giờ thì điều đó chẳng phải mang lại cho cậu một cảm giác ấm áp và lâng lâng sao?",
  "Artillery, now!": "Pháo binh, bắn ngay!",
  "AY-firm.": "Đã rõ.",
  "So what kind of samples do you get from a Juggernaut?": "Vậy anh lấy được loại mẫu vật gì từ một con Juggernaut?",
  "Wow, this place looks secure. I still can't believe you found me.": "Chà, nơi này trông có vẻ an toàn đấy. Tôi vẫn không thể tin được là cậu đã tìm thấy tôi.",
  "Well, I'm guessing they heard the car.": "Chà, tôi đoán là chúng đã nghe thấy tiếng động cơ xe.",
  "Let's set up camp here.": "Hãy lập trại ở đây.",
  "Fight in the Community": "Đánh Nhau Trong Cộng Đồng",
  "Look like that infestation was worse than we thought. %1$s couldn't even make a dent. - %2$s": "Có vẻ như cái Ổ Dịch đó còn tồi tệ hơn chúng ta tưởng. %1$s thậm chí còn không làm sứt mẻ được một mống nào. - %2$s",
  "Could probably kill everyone in the community without a weapon. Has trouble respecting others because of it.": "Có thể giết tất cả mọi người trong cộng đồng bằng tay không. Vì vậy nên rất khó để tôn trọng người khác.",
  "I haven't earned this.": "Tôi chưa xứng đáng với điều này.",
  "Yeah, we're coming in.": "Đúng vậy, chúng tôi đang vào đây.",
  "Army Engineer": "Kỹ Sư Quân Đội",
  "We've got to be quieter.": "Chúng ta phải giữ im lặng hơn nữa.",
  "Huh?": "Hả?",
  "Raises Vitality and improves Recovery Chance.": "Tăng Sinh Lực và cải thiện Cơ Hội Phục Hồi.",
  "ABORTED: Artillery Site": "ĐÃ HỦY: Trạm Pháo Binh",
  "Bonus XP from Dojo!": "Nhận XP Thưởng từ Võ Đường!",
  "+250%": "+250%",
  "What kind of lesson?": "Một bài học về cái gì cơ?",
  "You hear that?": "Cậu có nghe thấy tiếng đó không?",
  "Harper": "Harper",
  "Welcome to the Church of the Ascension": "Chào mừng đến với Nhà Thờ Thăng Thiên",
  "You got it from here?": "Cậu tự lo được từ đây chứ?",
  "Looks like they're walking a predictable route.": "Có vẻ như chúng đang đi theo một lộ trình rất dễ đoán.",
  "This character should be given the BADASS context tag whenever the player's health is below 40% and there are more than 2 zombies around.": "Nhân vật này sẽ được gắn thẻ ngữ cảnh BADASS bất cứ khi nào máu của người chơi dưới 40% và có hơn 2 con zombie xung quanh.",
  "-%d Day(s)": "-%d Ngày",
  "Don't suppose you'd be interested in taking this little beauty for a test drive?": "Không nghĩ là cậu sẽ hứng thú với việc đưa người đẹp bé nhỏ này đi chạy thử một vòng đâu nhỉ?"
};

const file = 'output/languages/chunks/btxt_chunk_101.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_101.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk101[r.sourceText]) {
    r.translatedText = chunk101[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 101 successfully!');
