const fs = require('fs');
const chunk124 = {
  "So ... your name is Sasquatch?": "Vậy ... tên của anh là Sasquatch à?",
  "Reload Gun": "Nạp Đạn Súng",
  "Is now missing.": "Bây giờ đang mất tích.",
  "16 GENERIC Devon Wall": "16 GENERIC Devon Wall",
  "Ammo, Fuel, and Pipe Bombs": "Đạn Dược, Nhiên Liệu, và Bom Ống",
  "Pike": "Pike",
  "Now we need a backup plan.": "Giờ thì chúng ta cần một kế hoạch dự phòng.",
  "Jesus, ain't there an end to these bastards?": "Chúa ơi, đéo có hồi kết cho lũ khốn này sao?",
  "Doesn't anybody check the dates on these bottles? All this goes in the trash now. -%1$s": "Không ai kiểm tra hạn sử dụng trên mấy cái chai này à? Giờ tất cả đống này phải vứt vào thùng rác rồi. -%1$s",
  "You know what we need? A workshop. You know? Something that will show people that we can actually build on this place, ok? We don't just have to scrape by.": "Cậu biết chúng ta cần gì không? Một xưởng chế tạo (workshop). Hiểu chứ? Một thứ gì đó sẽ cho mọi người thấy rằng chúng ta thực sự có thể xây dựng nơi này, ok? Chúng ta không chỉ phải sống lay lắt qua ngày.",
  "Better wrap up quick before they come to investigate.": "Tốt nhất là giải quyết nhanh gọn đi trước khi chúng đến điều tra.",
  "Bloodstains on the carpet again?": "Lại có vết máu trên thảm nữa à?",
  "I'm getting kinda worried about him. He's barely eating, he hardly says two words to anybody....": "Tôi đang khá lo lắng cho anh ấy. Anh ấy hầu như đéo ăn gì, cũng đéo nói với ai được hai từ....",
  "There's our target.": "Mục tiêu của chúng ta kia rồi.",
  "It takes hordes a while to congregate. If we clear some of them out, it'll make things easier for us. For a while, anyways.": "Lũ horde sẽ mất một thời gian để tụ tập lại. Nếu chúng ta dọn dẹp bớt vài bọn chúng, mọi chuyện sẽ dễ thở hơn cho chúng ta. Dù sao thì cũng được một thời gian.",
  "That's not good.": "Thế là không ổn rồi.",
  "So... %1$s decided to try and make that trade run on their own, and I haven't heard from them since. I'm getting worried. - %2$s": "Vậy... %1$s quyết định tự mình thực hiện chuyến đi giao thương đó, và tôi đã không nghe tin tức gì từ họ kể từ đó. Tôi đang bắt đầu lo rồi đấy. - %2$s",
  "Do you have everything?": "Cậu có lấy đủ mọi thứ chưa?",
  "Wrong Kill Type - Continue!": "Sai Loại Đòn Kết Liễu - Tiếp Tục Nào!",
  "Player Match": "Trận Đấu Ghép Người Chơi (Player Match)",
  "AMMO RESOURCE. A hodgepodge of ammunition.": "TÀI NGUYÊN ĐẠN. Một mớ hỗn độn các loại đạn.",
  "We have a new CO in the Ops Center.": "Chúng ta có Sĩ Quan Chỉ Huy (CO) mới tại Trung Tâm Điều Hành (Ops Center).",
  "Credits": "Đội Ngũ Thực Hiện (Credits)",
  "Repairs the vehicle's engine. REQUIRES TOOLS EXPERT.": "Sửa chữa động cơ xe. YÊU CẦU CHUYÊN GIA VỀ CÔNG CỤ (TOOLS EXPERT).",
  "How about that? I might be an angel!": "Thế thì sao? Có thể tôi là một thiên thần đấy!",
  "Incoming! Right side!": "Đang đến kìa! Bên phải!",
  "Well, nothing, Mickey... but then who's gonna bring you more?": "Chà, đéo có gì cả, Mickey... nhưng sau đó ai sẽ là người mang thêm đồ cho anh?",
  "Yeah! That is how you slay a zombie!": "Yeah! Đó mới là cách tàn sát một con zombie chứ!",
  "Vince had a good idea!": "Vince có một ý tưởng hay đấy!",
  "Counseling": "Tư Vấn Tâm Lý (Counseling)",
  "Yeah, come by if you're not too damn busy.": "Phải, ghé qua đây đi nếu cậu không quá mẹ nó bận rộn.",
  "Stopping Power": "Lực Cản Đạn",
  "Those barricades won't last long!": "Mấy cái rào chắn đó sẽ đéo trụ được lâu đâu!",
  "Delay your decision.": "Trì hoãn quyết định của bạn.",
  "They're gonna bust through any second!": "Chúng sẽ phá cửa xông vào bất cứ lúc nào!",
  "Trade 15 Daily Rations of Food for 3 Cases of Ammunition.": "Trao đổi 15 Khẩu phần Thức ăn Hàng ngày để lấy 3 Thùng Đạn dược.",
  "Y'know, if we don't help out soon, it may be too late.": "Biết không, nếu chúng ta không giúp một tay sớm, có thể sẽ quá muộn đấy.",
  "Roger that, Highroad. We'll get to that location and report back on what we find.": "Rõ rồi, Highroad. Chúng tôi sẽ đến vị trí đó và báo cáo lại những gì chúng tôi tìm thấy.",
  "Anybody hungry?": "Có ai đói không?",
  "Schulz": "Schulz",
  "Assault Rifle: G36": "Súng trường tấn công: G36",
  "%1$s is the leader of Greyhound Two, serving under my command.": "%1$s là đội trưởng của Greyhound Two, phục vụ dưới quyền chỉ huy của tôi.",
  "EXPIRED: Seek and Destroy": "HẾT HẠN: Tìm và Diệt",
  "62 GENERIC Ryan Simpson": "62 GENERIC Ryan Simpson",
  "46 GENERIC Tom Cassavettes": "46 GENERIC Tom Cassavettes",
  "Stop making so much noise, you're drawing zeds!": "Đừng có làm ồn nữa, cậu đang thu hút lũ zed đấy!",
  "Outpost Setup": "Thiết Lập Tiền Đồn (Outpost)",
  "Let's consider that done.": "Hãy coi như chuyện đó đã xong.",
  "Good luck out there.": "Chúc may mắn ngoài kia.",
  "You can choose one of two special attacks.": "Bạn có thể chọn một trong hai đòn tấn công đặc biệt.",
  "Pistol: G21": "Súng lục: G21",
  "Can I suggest using some painkillers?": "Tôi có thể gợi ý việc sử dụng vài viên thuốc giảm đau không?",
  "That was so close. I was about to put a bullet in my head.": "Suýt chút nữa thì. Tôi đã định cho một viên đạn vào đầu mình rồi.",
  "14 MIL Sgt Wade Moore": "14 MIL Trung sĩ Wade Moore",
  "Sure, I've got a lot of shit stashed. Always knew it would come in handy someday. (Hoarding tendencies.)": "Chắc chắn rồi, tôi có giấu một đống đồ cất giữ. Luôn biết rằng một ngày nào đó nó sẽ có ích mà. (Có xu hướng tích trữ.)",
  "Hey. She doesn't exactly have a good reason to trust us right now.": "Này. Cô ấy cũng đéo có lý do chính đáng nào để tin tưởng chúng ta lúc này cả.",
  "Hammerhead": "Hammerhead",
  "+71%": "+71%",
  "Nice work! You saved a lot of people.": "Làm tốt lắm! Cậu đã cứu được rất nhiều người.",
  "May God have mercy on your soul.": "Cầu Chúa thương xót cho linh hồn cậu.",
  "Basic Maintenance Tools": "Bộ Dụng Cụ Bảo Trì Cơ Bản",
  "The Sheriff in Marshall asked me for some help, and I refused. I wonder if that was a mistake. - %1$s": "Cảnh sát trưởng ở Marshall đã nhờ tôi giúp đỡ, và tôi đã từ chối. Tôi tự hỏi liệu đó có phải là một sai lầm hay không. - %1$s",
  "I've located a zed infestation.": "Tôi đã định vị được một ổ dịch zed.",
  "A SUPPLY RUN is already in progress here.": "Một cuộc ĐI LẤY VẬT TƯ đang được tiến hành tại đây.",
  "Rifle: M110 SASS": "Súng trường: M110 SASS",
  "Okay, bag's full, so we're done here.": "Được rồi, túi đầy rồi, vậy là chúng ta xong việc ở đây.",
  "They'll be on their way soon.": "Họ sẽ lên đường sớm thôi.",
  "Outlaw": "Kẻ Ngoài Vòng Pháp Luật",
  "We could use some help getting out of here.": "Chúng tôi rất cần được giúp đỡ để thoát khỏi đây.",
  "Not the sharpest tool in the shed. (Improves wits s-l-o-w-l-y.)": "Không phải là người sáng dạ nhất. (Tăng Trí Tuệ (Wits) cực-kỳ-chậm.)",
  "No. We're not opening up until the zombies are gone.": "Không. Chúng tôi đéo mở cửa cho đến khi lũ zombie biến đi hết.",
  "Illness Recovery Failed": "Phục Hồi Bệnh Tật Thất Bại",
  "Gaining respect for Vince (Royell Vincent).": "Đang dần tôn trọng Vince (Royell Vincent).",
  "Like, I never knew Bill Mahoney's backyard had an unobstructed view right into Katie St. John's bedroom window.": "Kiểu như, tôi chưa bao giờ biết sân sau của Bill Mahoney lại có một tầm nhìn đéo bị che khuất nhìn thẳng vào cửa sổ phòng ngủ của Katie St. John.",
  "Get lost.": "Cút đi.",
  "PERSONAL SKILL. Do you have a minute to discuss the use of symbolism in Anna Karenina?": "KỸ NĂNG CÁ NHÂN. Cậu có một phút để thảo luận về việc sử dụng tính biểu tượng trong tác phẩm Anna Karenina không?",
  "Fuck! They're inside! They're inside!": "Đéo mẹ! Chúng nó vào trong rồi! Chúng nó vào trong rồi!",
  "%1$dm; %2$ds": "%1$d phút; %2$d giây",
  "Micro-brewer who left the big city to open a small pub in town.": "Một người thợ nấu bia thủ công đã rời thành phố lớn để mở một quán rượu nhỏ trong thị trấn.",
  "SMG: MPS 90B": "Súng tiểu liên: MPS 90B",
  "BONUS XP (Slaughter)": "XP THƯỞNG (Tàn Sát)",
  "All right, this ain't the Hilton. Secure your trash and see Ops for your duty assignments.": "Được rồi, đây đéo phải là khách sạn Hilton. Tự dọn dẹp rác của mình và gặp phòng Điều Hành (Ops) để nhận nhiệm vụ được giao.",
  "I'm going to have to ask you to move along. This area is under quarantine. No civilians allowed.": "Tôi sẽ phải yêu cầu các người rời đi. Khu vực này đang bị cách ly. Không cho phép dân thường vào đây.",
  "On second thought, I'm an idiot. Hold off.": "Nghĩ lại thì, tôi đúng là một thằng ngu. Chờ đã.",
  "There are supposed to be a lot of painless ways to do this. Course, all of them end with me turning, so I guess it's bullet in the head time. Fuck you, zombies. - %1$s": "Đáng lẽ phải có rất nhiều cách không đau đớn để làm việc này. Tất nhiên, tất cả những cách đó đều kết thúc bằng việc tôi bị biến đổi, nên tôi đoán đến lúc tặng một viên kẹo đồng vào đầu rồi. Đm bọn mày, zombie. - %1$s",
  "The Surgery facility allows you to perform advanced medical procedures in the field and recover maximum vitality.": "Cơ sở Phẫu Thuật (Surgery) cho phép bạn thực hiện các thủ thuật y tế phức tạp ngay trên chiến trường và phục hồi sinh lực (vitality) ở mức tối đa.",
  "Don't count on a car surviving an encounter with one of these guys.": "Đừng có mong chiếc xe nào còn nguyên vẹn sau khi đụng độ một trong những gã này.",
  "This was a total bust. There's nothing useful out here.": "Đúng là một thất bại thảm hại. Đéo có gì hữu ích ở ngoài này cả.",
  "Restock All": "Bổ sung Toàn bộ",
  "Safe Zone": "Vùng An Toàn (Safe Zone)",
  "SitRep: Local Update #3": "Báo Cáo Tình Hình (SitRep): Cập nhật Địa phương số 3",
  "Sally Jo": "Sally Jo",
  "Albin": "Albin",
  "Just don't expect me to be running around town dodging zombies till then.": "Chỉ là đừng có mong tôi chạy quanh thị trấn để né lũ zombie cho đến lúc đó.",
  "LMG: M249 SAW": "Súng máy hạng nhẹ: M249 SAW",
  "So... that didn't suck.": "Vậy... nó không đến nỗi quá tệ.",
  "Stay away! Just… Just stay away!": "Tránh xa ra! Cứ… Cứ tránh xa ra!",
  "Asshole!": "Đồ khốn!",
  "Civilians can't just roll up on a horde and clear it out for these people. It's us or nobody!": "Dân thường đéo thể cứ thế xông vào một bầy horde và dọn dẹp nó cho những người này. Là chúng ta hoặc đéo ai cả!",
  "70 GENERIC Hannah Nolan": "70 GENERIC Hannah Nolan"
};

const file = 'output/languages/chunks/btxt_chunk_124.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_124.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk124[r.sourceText]) {
    r.translatedText = chunk124[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 124 successfully!');
