const fs = require('fs');
const chunk184 = {
  "12 GENERIC Timothy Ebberts": "12 CHUNG (GENERIC) Timothy Ebberts",
  "Looks like a whole lot more coming in.": "Trông có vẻ như đang có nhiều tên tiến vào đây hơn rồi đấy.",
  "Yeah. Afghanistan first, then Iraq. Me and Strand mustered out after our last tour, but Colton's--Colton was a lifer. We do one of these hunting trips every year.": "Đúng vậy. Đầu tiên là chiến trường Afghanistan, sau đó là Iraq. Tôi và Strand đã xuất ngũ sau chuyến phục vụ cuối cùng của chúng tôi, nhưng Colton thì--Colton là một quân nhân chuyên nghiệp. Chúng tôi thường tổ chức một chuyến đi săn bắn như thế này vào mỗi năm.",
  "Heads up. We got zombies coming in.": "Chú ý nào. Bọn zombies đang tiến đến đây đấy.",
  "Tarver": "Tarver",
  "Rucksack's full, so I'm headed back.": "Ba lô (Rucksack) đã đầy cmnr, nên tôi sẽ quay trở về.",
  "Can't believe the zeds didn't hear that.": "Đéo thể tin được là bọn zeds lại đéo nghe thấy tiếng động đó đấy.",
  "Yeah. That place is gonna be lousy with zombies.": "Ừ. Nơi đó sẽ nhung nhúc đẫm đặc bọn zombies cho xem.",
  "That's it. I can't raise them anymore. I hope they got out alive.": "Thế là hết. Tôi đéo thể liên lạc với bọn họ được nữa rồi. Hy vọng là bọn họ đã thoát ra ngoài sống sót.",
  "58 GENERIC Tim White": "58 CHUNG (GENERIC) Tim White",
  "BOASTFUL people may rub others the wrong way.": "Những kẻ KHOE KHOANG (BOASTFUL) có thể sẽ khiến cho người khác cảm thấy khó chịu.",
  "We're friends, right?": "Chúng ta là bạn bè mà, đúng đéo?",
  "Yeah, he's kind of a local big shot. Owned a bunch of businesses in Marshall, served on the county commission, that kind of thing.": "Ừ, ông ta kiểu như là một nhân vật tai to mặt lớn ở địa phương này. Sở hữu một loạt các cơ sở kinh doanh thương mại ở thành phố Marshall, phục vụ trong ủy ban quận (county commission), đại loại là như vậy.",
  "We gotta try to spot the hordes before they see us.": "Chúng ta phải cố gắng phát hiện ra lũ zombie (hordes) trước khi bọn chúng kịp nhìn thấy chúng ta.",
  "You're batting a thousand lately!": "Dạo gần đây cậu đang làm việc cực kỳ xuất sắc đấy (batting a thousand)!",
  "Make .357 Ammo": "Chế Tạo Đạn Dược (Ammo) .357",
  "Sure, sure, could be. Or we're about to gatecrash a redneck wedding. Just saying.": "Chắc chắn rồi, chắc chắn rồi, có thể là vậy. Hoặc là chúng ta chuẩn bị phá bĩnh một đám cưới của lũ nhà quê (redneck). Tôi chỉ đang nói đùa vậy thôi.",
  "You're going for the record, Alex!": "Cậu đang tiến tới việc phá kỷ lục luôn đấy, Alex!",
  "Look for the \"COMMERCE: Library Access\" action at the Library.": "Hãy tìm kiếm hành động \"GIAO THƯƠNG (COMMERCE): Quyền Truy Cập Thư Viện\" tại cơ sở Thư Viện (Library).",
  "Dude, I think these guys want to eat us!": "Anh bạn, tôi nghĩ những gã này đang muốn ăn tươi nuốt sống chúng ta đấy!",
  "Problem? What problem? I don't remember a problem.": "Vấn đề á? Vấn đề đéo gì cơ? Tôi đéo nhớ là có cái vấn đề gì cả.",
  "I've lost contact with my last caller. I hope whatever you were doing was worth it.": "Tôi đã mất liên lạc với người gọi cuối cùng của mình rồi. Tôi hy vọng bất cứ việc gì mà cậu đang làm là hoàn toàn xứng đáng.",
  "I'm begging you. Put me out of my misery. It'll be worse for everybody if you don't.": "Tôi đang cầu xin cậu đấy. Hãy giúp tôi chấm dứt sự đau đớn này đi. Mọi chuyện sẽ trở nên tồi tệ hơn đối với tất cả mọi người nếu cậu đéo làm vậy.",
  "Make Love to the Camera": "Tạo Dáng Thật Quyến Rũ Trước Ống Kính Máy Ảnh",
  "Pistol: Mk. 3 Target": "Súng Lục (Pistol): Mk. 3 Target",
  "Walter": "Walter",
  "Words of Inspiration": "Những Lời Truyền Cảm Hứng",
  "Next time you get orders to bring someone in, I want them alive. Highroad out.": "Lần tới nếu nhận được mệnh lệnh phải bắt giữ một người nào đó về đây, tôi muốn bọn họ phải còn sống. Highroad hết (out).",
  "Caitlin": "Caitlin",
  "130 STORY Mickey Wilkerson": "130 CỐT TRUYỆN (STORY) Mickey Wilkerson",
  "Feels like I got run over by a bus full of angry nuns.": "Cảm giác cứ như thể tôi vừa mới bị một chiếc xe buýt chở đầy những bà sơ đang tức giận cán qua người vậy.",
  "Sure, no problem. We'll be along shortly.": "Chắc chắn rồi, đéo vấn đề gì đâu. Chúng tôi sẽ đến đó nhanh thôi.",
  "Requires Blunt Weapons Level 4": "Yêu cầu có Vũ Khí Cùn (Blunt Weapons) Cấp 4",
  "Breathing HURTS with this cracked rib. I can't really run or exert myself too much. (Stamina and Cardio XP penalty)": "Việc hít thở ĐANG GÂY ĐAU ĐỚN với cái xương sườn bị rạn nứt này. Tôi thực sự đéo thể chạy hoặc vắt kiệt sức lực của bản thân mình quá nhiều được. (Phạt điểm XP của Thể Lực và Cardio)",
  "Thanks I learned a lot.": "Cảm ơn nhé tôi đã học hỏi được rất nhiều điều.",
  "Doctor Horn isn't at the crash site, though we had to fight most of his security detail. We're going to search the nearby buildings and try to locate him before the zeds do.": "Bác sĩ Horn đéo có mặt tại hiện trường vụ rơi máy bay, mặc dù chúng tôi đã phải chiến đấu với hầu hết các thành viên trong đội bảo vệ an ninh của ông ta. Chúng tôi sẽ tiến hành tìm kiếm ở các tòa nhà gần đó và cố gắng xác định vị trí của ông ta trước khi bọn zeds kịp tìm thấy.",
  "Intro": "Giới thiệu (Intro)",
  "Finished scouting. Nothing major to report.": "Đã hoàn thành việc trinh sát (scouting). Đéo có chuyện gì lớn để báo cáo cả.",
  "How about if we go together? I'll make sure nobody bothers you.": "Hay là chúng ta đi cùng nhau thì sao? Tôi sẽ đảm bảo đéo có bất kỳ ai làm phiền đến cậu đâu.",
  "A U.S. competitor to the \"G\" line of pistols.": "Một đối thủ cạnh tranh của Hoa Kỳ đối với dòng súng lục \"G\".",
  "Hoo doggie!": "Hoo doggie!",
  "A tough SUV, built to last through ANY type of apocalypse. Just so happened to be here for the zombie kind.": "Một chiếc xe SUV cứng cáp, được chế tạo để có thể tồn tại được qua BẤT KỲ loại hình tận thế nào. Thật tình cờ là nó lại xuất hiện ở đây để đối phó với loại tận thế zombie này.",
  "Army Zeds": "Bọn Zeds Của Quân Đội (Army Zeds)",
  "Loves Spicy Food": "Rất Thích Ăn Đồ Ăn Cay (Spicy Food)",
  "Well, then let's take a look inside.": "Chà, vậy thì hãy cùng đi vào bên trong xem thử một chút nào.",
  "You did good. I know things look pretty bleak to you, but just try and remember, everybody's here for you.": "Cậu đã làm rất tốt. Tôi biết mọi chuyện đang có vẻ khá là ảm đạm đối với cậu, nhưng hãy cố gắng nhớ rằng, mọi người đều ở đây vì cậu.",
  "And who's Andy Pimms?": "Và Andy Pimms là kẻ đéo nào vậy?",
  "Karen": "Karen",
  "Butcher": "Người Làm Nghề Bán Thịt (Butcher)",
  "Gabriel": "Gabriel",
  "We just lost a barricade!": "Chúng ta vừa mất đi một tấm rào chắn phòng thủ (barricade)!",
  "Seth": "Seth",
  "Allows the creation of explosives.": "Cho phép chế tạo các loại vật liệu nổ (explosives).",
  "%d dB": "%d dB",
  "We might want to hurry a bit.": "Chúng ta có lẽ cần phải nhanh lên một chút đấy.",
  "So help me, %1$s, if you say one more thing about how Foghat sucks, I will kick your ass! - %2$s": "Có Chúa chứng giám cho tôi (So help me), %1$s, nếu cậu còn nói thêm một lời nào nữa về việc ban nhạc Foghat tệ hại đến mức nào, thì tôi sẽ đá đít cậu đấy! - %2$s",
  "Good. Guy sets my teeth on edge whenever he's around. Were you here for that whole thing with the Halloran gang?": "Tốt. Gã đó luôn làm cho tôi cảm thấy lo lắng bồn chồn (sets my teeth on edge) bất cứ khi nào hắn lảng vảng ở quanh đây. Cậu có ở đây khi toàn bộ chuyện đó xảy ra với băng đảng Halloran đéo?",
  "Lamar": "Lamar",
  "Seems pretty shell-shocked. Hope she doesn't do something crazy.": "Trông có vẻ khá là chấn động tâm lý (shell-shocked) đấy. Hy vọng là cô ta đéo làm ra điều gì điên rồ.",
  "Rifle: 700 Huntsman Camo": "Súng Trường (Rifle): 700 Huntsman Camo",
  "Use [xi_thumblx] to move.": "Sử dụng phím [xi_thumblx] để di chuyển.",
  "Pointing out that we need a medicine stockpile.": "Chỉ ra rằng chúng ta đang cần có một kho dự trữ thuốc men (medicine stockpile).",
  "Gotta keep up with it.": "Cần phải theo kịp chuyện đó thôi.",
  "Hope you're keeping your nose clean, Alex.": "Hy vọng cậu sẽ tránh xa khỏi những rắc rối (keeping your nose clean), Alex.",
  "Your orders are to stay on mission, assuming you still have the personnel.": "Mệnh lệnh của anh là tiếp tục thực hiện nhiệm vụ (stay on mission), giả định như anh vẫn còn đủ nhân sự để thực hiện việc đó.",
  "NOTE: Good Neighbors": "LƯU Ý (NOTE): Những Người Hàng Xóm Tốt Bụng",
  "Incoming!": "Coi chừng!",
  "Fuel it up and flip the switch for thirty minutes of electric power.": "Đổ đầy nhiên liệu (Fuel) vào và bật công tắc để có được ba mươi phút sử dụng năng lượng điện (electric power).",
  "I'm sorry, Doctor Horn. Your husband is dead.": "Tôi rất tiếc, Bác sĩ Horn. Chồng của cô đã chết cmnr.",
  "Former Cheerleader": "Cựu Đội Trưởng Đội Cổ Vũ (Cheerleader)",
  "Well... I think that's the most exhaustive survey of Trumbull County ever. I don't think we left any stone unturned. So, what do you think?": "Chà... Tôi nghĩ đó là cuộc khảo sát toàn diện nhất về Quận Trumbull từ trước đến nay. Tôi đéo nghĩ là chúng ta đã bỏ sót bất kỳ ngóc ngách nào đâu (left any stone unturned). Vậy, cậu nghĩ sao?",
  "Are you the extraction team?": "Các anh có phải là đội chiết xuất giải cứu (extraction team) đéo?",
  "What happened to the badass motherfucker?": "Chuyện đéo gì đã xảy ra với cái tên khốn kiếp ngầu lòi (badass motherfucker) kia vậy?",
  "Complete all Sasquatch hunting missions.": "Hoàn thành tất cả các nhiệm vụ săn bắn theo chỉ dẫn của Sasquatch.",
  "The next thing that breaks won't get fixed unless we find some building materials.": "Thứ tiếp theo bị hỏng sẽ đéo được sửa chữa trừ phi chúng ta tìm được thêm một ít vật liệu xây dựng (building materials).",
  "High quality antique, they don't make them like this anymore.": "Đồ cổ chất lượng cao, người ta đéo còn sản xuất ra những thứ giống như thế này nữa đâu.",
  "Now we can cook up some things.": "Bây giờ thì chúng ta đã có thể chế tạo ra (cook up) được vài món đồ rồi đấy.",
  "Pedersen": "Pedersen",
  "Woah, watch your back!": "Woah, hãy cẩn thận coi chừng cái lưng của cậu đấy!",
  "Cardio Improved!": "Kỹ Năng Cardio Đã Được Cải Thiện!",
  "Chelsea": "Chelsea",
  "You think it's an evacuation route?": "Cô nghĩ đó là một tuyến đường sơ tán (evacuation route) sao?",
  "Tire Iron": "Cờ Lê Tháo Lốp (Tire Iron)",
  "154 HERO Sgt Kelly Eldridge": "154 NGƯỜI HÙNG (HERO) Trung Sĩ Kelly Eldridge",
  "Now!": "Ngay bây giờ!",
  "We've got more people than we have guns. That's going to make it easier for the zombies to overwhelm us - %1$s": "Chúng ta có nhiều người hơn số súng mà chúng ta đang có. Điều đó sẽ khiến cho bọn zombies dễ dàng áp đảo được chúng ta hơn - %1$s",
  "Mickey and Job are in mourning for their brother Eli. Best to give them some space. - %1$s": "Mickey và Job đang chìm trong đau buồn vì cái chết của em trai Eli của họ. Tốt nhất là nên để cho bọn họ có một chút không gian riêng tư. - %1$s",
  "Flugtag": "Flugtag",
  "Time to clear the hell out.": "Đã đến lúc phải dọn dẹp sạch sẽ đống rác rưởi này rồi.",
  "S-Mine": "Mìn S-Mine",
  "The bad boys back at base want to know how we end up with so many of these \"Ferals\".": "Những gã tồi tệ đang ở lại căn cứ (base) muốn biết làm thế nào mà chúng ta lại đụng độ phải quá nhiều con \"Ferals\" như thế này.",
  "SitRep: Chicago": "Báo Cáo Tình Hình (SitRep): Chicago",
  "Level 3": "Cấp Độ 3",
  "Excuse me?": "Xin lỗi, cái gì cơ?",
  "Solar Power": "Năng Lượng Mặt Trời (Solar Power)",
  "Shit yeah, let's do it!": "Chết tiệt thật chứ, hãy làm tới luôn đi!",
  "Wooden Spoons": "Những Chiếc Thìa Gỗ (Wooden Spoons)",
  "Time to move out.": "Đã đến lúc phải lên đường di chuyển (move out) rồi.",
  "Relocated your home base.": "Đã di dời căn cứ (home base) của bạn sang địa điểm khác.",
  "Help hunt the Feral Zombie?": "Cùng giúp sức săn lùng con Feral Zombie chứ?"
};

const file = 'output/languages/chunks/btxt_chunk_184.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_184.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk184[r.sourceText]) {
    r.translatedText = chunk184[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 184 successfully!');
