const fs = require('fs');
const chunk177 = {
  "SMG: UMP Pro": "Súng Tiểu Liên (SMG): UMP Pro",
  "Hold [sprint] + hold [xi_use] for a more powerful shove that always knocks enemies down.": "Giữ [sprint] + giữ [xi_use] để có một cú xô ngã (shove) mạnh mẽ hơn, luôn luôn đánh gục được kẻ thù.",
  "Get Outta My Dreams": "Biến Khỏi Những Giấc Mơ Của Tôi (Get Outta My Dreams)",
  "You wanna try NOT letting the horde see us first?": "Cậu có muốn thử ĐÉO để bầy (horde) zombie nhìn thấy chúng ta trước đéo?",
  "We all run into trouble sometimes. There's nothing more important than going out and finding one of our people. - %1$s.": "Tất cả chúng ta đôi khi đều gặp phải rắc rối. Đéo có gì quan trọng hơn việc ra ngoài đó và tìm kiếm một trong những người của chúng ta. - %1$s.",
  "Has gained trust.": "Đã nhận được sự tin tưởng (trust).",
  "Get to her last known location, track her down, and bring her in. Doghouse out.": "Hãy đến địa điểm cuối cùng mà người ta còn nhìn thấy cô ấy, truy tìm dấu vết của cô ấy, và đưa cô ấy về đây. Doghouse hết (out).",
  "Every 24 hours, we restock the Supply Locker. The better our Stockpiles, the more items we distribute. - %1$s": "Cứ mỗi 24 giờ, chúng ta lại bổ sung thêm hàng vào Tủ Chứa Nhu Yếu Phẩm (Supply Locker). Kho Dự Trữ (Stockpiles) của chúng ta càng tốt, chúng ta càng có thể phân phối nhiều đồ đạc hơn. - %1$s",
  "Incendiary Rounds": "Đạn Gây Cháy (Incendiary Rounds)",
  "Automatically repair stored weapons each day ... or do it manually at the Supply Locker for 30 Influence.": "Tự động sửa chữa những vũ khí được lưu trữ mỗi ngày ... hoặc tự thực hiện thủ công tại Tủ Chứa Nhu Yếu Phẩm với giá 30 Điểm Ảnh Hưởng (Influence).",
  "Then we'll ditch these backwoods crazies, get back to town, and find out what the hell happened up here.": "Sau đó chúng ta sẽ vứt bỏ đám người điên rồ nơi rừng rú này, quay trở lại thị trấn, và tìm hiểu xem chuyện quái quỷ gì đã xảy ra ở trên này.",
  "FOOD RESOURCE. A bunch of vending machine treats.": "TÀI NGUYÊN THỨC ĂN (FOOD). Một đống đồ ăn vặt từ máy bán hàng tự động.",
  "Even if we get back to town, we tell anybody about this and we spend the next 25-to-life trying not to drop the soap!": "Ngay cả khi chúng ta có quay trở lại được thị trấn, chúng ta kể cho bất kỳ ai về chuyện này và chúng ta sẽ phải dành 25 năm tiếp theo cho đến cuối đời cố gắng để đéo bị rớt cục xà phòng trong tù đấy!",
  "Noland": "Noland",
  "You really came through for us. Nice job.": "Cậu thực sự đã vượt qua thử thách để giúp đỡ chúng tôi. Làm tốt lắm.",
  "We need to get people trained up on proper trigger discipline, or else this is gonna keep happening.": "Chúng ta cần phải huấn luyện mọi người về kỷ luật bóp cò đúng đắn, nếu đéo chuyện này sẽ còn tiếp diễn hoài.",
  "Zoey": "Zoey",
  "Untrained caregiver.": "Một người chăm sóc (caregiver) đéo được đào tạo bài bản.",
  "A classic scoped hunting rifle.": "Một khẩu súng trường săn bắn có trang bị ống ngắm cổ điển.",
  "Officer": "Sĩ Quan (Officer)",
  "Area attack that has a high chance to trip targets.": "Đòn tấn công diện rộng có tỷ lệ cao làm vấp ngã các mục tiêu.",
  "Leave me alone, asshole. Somebody remind me why %1$s is here. Other than to annoy the shit out of me. - %2$s.": "Để tôi yên đi, thằng khốn. Ai đó làm ơn nhắc tôi nhớ tại sao %1$s lại ở đây với. Ngoài mục đích làm tôi bực mình muốn chết ra. - %2$s.",
  "I got a ways to go. Wouldn't mind a car.": "Tôi còn một quãng đường dài để đi đấy. Tôi sẽ đéo phiền nếu có một chiếc xe đâu.",
  "When are you coming home to let that heal?": "Khi nào cậu mới chịu về nhà để chữa trị cho vết thương đó lành lại vậy?",
  "Used to getting by without state of the art equipment.": "Đã quen với việc phải xoay sở sống qua ngày mà đéo có những trang thiết bị hiện đại tối tân (state of the art).",
  "So much to do, so little time. Right?": "Có quá nhiều việc phải làm, mà lại có quá ít thời gian. Đúng đéo?",
  "Tara": "Tara",
  "I need you to be done.": "Tôi cần cậu phải làm xong việc này.",
  "Unlocks the ability to create Pipe Bombs. REQUIRES A MUNITIONS SHOP.": "Mở khóa khả năng chế tạo Bom Ống (Pipe Bombs). YÊU CẦU PHẢI CÓ MỘT XƯỞNG SẢN XUẤT ĐẠN DƯỢC (MUNITIONS SHOP).",
  "NEW PLAN": "KẾ HOẠCH (PLAN) MỚI",
  "Calabresi": "Calabresi",
  "+20 Max Vitality for everyone.": "+20 Sinh Lực (Vitality) Tối Đa cho tất cả mọi người.",
  "Your brother's an asshole.": "Anh trai cậu đúng là một thằng khốn.",
  "The Prodigal": "Kẻ Phung Phí Đứa Con Hoang Đàng (The Prodigal)",
  "Do I get a lollipop now?": "Bây giờ tôi có được nhận một cây kẹo mút đéo?",
  "Let's get you out of that funk. C'mere, follow me.": "Hãy đưa cậu ra khỏi cái trạng thái ủ rũ (funk) đó nào. Lại đây, đi theo tôi.",
  "What? Oh my god....": "Cái gì? Ôi Chúa ơi....",
  "CONTACT: Vehicle Delivery": "LIÊN LẠC (CONTACT): Giao Nhận Phương Tiện (Vehicle Delivery)",
  "%1$s is starting to annoy people.": "%1$s đang bắt đầu làm mọi người cảm thấy khó chịu.",
  "Ayden": "Ayden",
  "Medivac is ready to go, if Greyhound Two would make me a fucking LZ.": "Trực thăng Tải Thương (Medivac) đã sẵn sàng cất cánh, nếu Greyhound Two chịu dọn cho tôi một cái Bãi Đáp (LZ) chết tiệt.",
  "Dude, we just killed a bunch of people! You know what that means?": "Anh bạn, chúng ta vừa mới giết chết một đống người đấy! Cậu có biết điều đó có ý nghĩa gì đéo?",
  "Until they do, we have to look out for ourselves. It may not be the most Constitutionally traditional succession, but it's all we have.": "Cho đến khi họ làm điều đó, chúng ta phải tự lo cho bản thân mình thôi. Đó có thể đéo phải là sự kế thừa truyền thống nhất theo Hiến pháp, nhưng đó là tất cả những gì chúng ta có.",
  "So tell me again why we care about this dead guy's crazy ideas?": "Vậy hãy nói lại cho tôi nghe xem tại sao chúng ta lại phải quan tâm đến những ý tưởng điên rồ của gã đã chết này nào?",
  "Wants to join us.": "Muốn gia nhập cùng với chúng ta.",
  "Adios, motherfuckers!": "Adios (Tạm biệt), những thằng khốn nạn!",
  "Let me go find some more.": "Để tôi đi tìm kiếm thêm một ít nữa.",
  "The Old Farmhouse": "Ngôi Nhà Trang Trại Cũ (The Old Farmhouse)",
  "Shotgun: Model 870 X": "Súng Shotgun: Model 870 X",
  "So if you're wondering why the army hasn't come to your door with an armored truck to escort you to safety ...": "Vậy nếu cậu đang tự hỏi tại sao quân đội vẫn chưa gõ cửa nhà cậu bằng một chiếc xe bọc thép để hộ tống cậu đến nơi an toàn ...",
  "Don't come after me.": "Đừng có đuổi theo tôi.",
  "Seriously, do you have some moral objection to just cutting its damn head off? Now we gotta keep hunting.": "Nghiêm túc đấy, cậu có sự phản đối nào về mặt đạo đức đối với việc chỉ cần chặt cmn cái đầu chết tiệt của nó đi đéo? Bây giờ chúng ta lại phải tiếp tục săn lùng.",
  "Now that's what I like to see. People sticking together, instead of turning on each other like a pack of hyenas.": "Chà, đó mới chính là những gì mà tôi muốn thấy. Mọi người gắn kết lại với nhau, thay vì quay sang cắn xé lẫn nhau như một bầy linh cẩu.",
  "Get to the Horn house": "Đi đến nhà của Horn",
  "Heard on the grapevine you might need a hand.": "Tôi nghe phong thanh được rằng cậu có thể đang cần được giúp một tay đấy.",
  "Just some thug. He doesn't even know how to describe himself.": "Chỉ là một tên côn đồ nào đó. Hắn ta thậm chí còn đéo biết cách mô tả bản thân mình nữa.",
  "Got any tips on how to make this construction go faster?": "Có mẹo (tips) nào về cách để làm cho công trình xây dựng này tiến triển nhanh hơn đéo?",
  "INCIDENT: Feral Encounter": "SỰ CỐ (INCIDENT): Đụng Độ Feral",
  "Well what the hell do you expect, with all the goddamn infestations out there?": "Chà, cậu mong đợi cái quái gì cơ chứ, với tất cả những ổ dịch chết tiệt ở ngoài kia?",
  "They're on the move again.": "Bọn chúng lại đang di chuyển rồi.",
  "After weeks among the infected, he's decided he's never taking that suit off again. Ever. He sleeps in it. No one knows how he uses the bathroom. (Immune to Bloater Gas and Screamer Cries.)": "Sau nhiều tuần sống giữa những kẻ bị lây nhiễm, anh ta đã quyết định sẽ đéo bao giờ cởi bộ đồ đó ra nữa. Đéo bao giờ. Anh ta ngủ trong đó luôn. Đéo ai biết anh ta đi vệ sinh bằng cách nào nữa. (Miễn nhiễm với Khí Độc Của Bloater và Tiếng Hét Của Screamer.)",
  "Another time.": "Để khi khác đi (Another time).",
  "\\\\": "\\\\",
  "I'm small. You won't even notice I'm here.": "Tôi nhỏ bé lắm. Cậu thậm chí sẽ đéo chú ý đến việc tôi đang ở đây đâu.",
  "You'll need to go meet with them.": "Cậu sẽ cần phải đi gặp bọn họ.",
  "That's how you fuckin' do it.": "Đó chính là cách mà cậu nên làm khốn kiếp như vậy đấy.",
  "This is good.": "Chuyện này tốt đấy.",
  "Weapons Training": "Luyện Tập Kỹ Năng Vũ Khí (Weapons)",
  "I know what I'm doing.": "Tôi biết mình đang làm gì mà.",
  "Check out the Fairgrounds": "Kiểm tra tìm kiếm khu Hội Chợ (Fairgrounds)",
  "Angela": "Angela",
  "+10 Stamina for everyone.": "+10 Thể Lực (Stamina) cho tất cả mọi người.",
  "Cram a noisemaker into a homemade mine, and it lures the zombies in before it explodes. Nice.": "Nhét một thiết bị tạo tiếng ồn (noisemaker) vào một quả mìn tự chế, và nó sẽ thu hút lũ zombies lao tới trước khi phát nổ. Tuyệt.",
  "You! You've been out there, right? Have you seen my daughter? She wasn't here at muster this morning, I don't know where she went!": "Cậu! Cậu đã ở ngoài đó, đúng đéo? Cậu có nhìn thấy con gái tôi đéo? Con bé đéo có mặt ở đây lúc tập trung điểm danh sáng nay, tôi đéo biết con bé đã đi đâu nữa!",
  "Claim Home Site?": "Chiếm Lấy (Claim) Vị Trí Căn Cứ (Home Site)?",
  "Let's see what we can find.": "Hãy xem chúng ta có thể tìm thấy được những gì nào.",
  "Revolver: Safari": "Súng Lục Ổ Quay (Revolver): Safari",
  "Seems like we can help each out, now and again. - Your neighbor, %1$s": "Có vẻ như chúng ta có thể giúp đỡ lẫn nhau, đôi khi là vậy. - Người hàng xóm của cậu, %1$s",
  "Chronic Fatigue": "Hội Chứng Mệt Mỏi Mãn Tính (Chronic Fatigue)",
  "Don't let them surround you!": "Đừng để cho bọn chúng bao vây lấy cậu!",
  "Our agreement still stands. For now.": "Thỏa thuận của chúng ta vẫn còn hiệu lực. Cho đến lúc này.",
  "Resents Police": "Phẫn Nộ Oán Giận Với Cảnh Sát",
  "Attitudes matter.": "Thái độ (Attitudes) rất quan trọng.",
  "No, no, I understand. Playing with fire seems dangerous when you're three fucking years old.": "Không, đéo, tôi hiểu mà. Việc chơi đùa với lửa có vẻ nguy hiểm khi cậu mới được có ba tuổi chết tiệt.",
  "Intercept Zombie Horde": "Đánh Chặn (Intercept) Bầy Đàn (Horde) Zombie",
  "Jamal": "Jamal",
  "Refills some brass to generate several magazines' worth of ammunition.": "Đổ đầy lại một vài vỏ đạn (brass) để tạo ra đủ số đạn dược (ammunition) cho vài băng đạn.",
  "Aw, this reminds me of that one episode... (TV Trivia.)": "Ồ, điều này nhắc tôi nhớ đến cái tập phim đó... (Kiến Thức Vặt Về Phim Truyền Hình - TV Trivia.)",
  "Tell you what. I've got some pull with the artillery pukes attached to my unit.": "Nói cho cậu nghe chuyện này nhé. Tôi có chút quen biết với mấy tên pháo binh chết tiệt được điều động đến đơn vị của tôi.",
  "Artillery Barrage Ready (Use Artillery Marker)": "Đợt Pháo Kích (Artillery Barrage) Đã Sẵn Sàng (Sử dụng Điểm Đánh Dấu Tọa Độ Pháo Binh - Artillery Marker)",
  "%+d Construction Materials": "%+d Vật Liệu Xây Dựng (Construction Materials)",
  "OPPORTUNITY: Food Preservation": "CƠ HỘI (OPPORTUNITY): Bảo Quản Thức Ăn (Food Preservation)",
  "Degrasse": "Degrasse",
  "LILY'S BROTHER": "ANH TRAI CỦA LILY",
  "A little help back here?": "Có thể giúp một tay ở phía sau này được đéo?",
  "I dunno... there hasn't been anything on the radio.": "Tôi đéo biết nữa... đéo có bất kỳ thông tin nào được phát trên radio cả.",
  "Pick Sam Up": "Đón Sam (Pick Up)",
  "My pleasure.": "Niềm vinh hạnh của tôi (My pleasure).",
  "Mike": "Mike",
  "Goddamn, you're unstoppable!": "Mẹ kiếp, cậu đúng là đéo thể cản bước (unstoppable) được mà!"
};

const file = 'output/languages/chunks/btxt_chunk_177.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_177.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk177[r.sourceText]) {
    r.translatedText = chunk177[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 177 successfully!');
