const fs = require('fs');
const chunk129 = {
  "Help hunt the Juggernaut?": "Giúp đi săn con Juggernaut chứ?",
  "Yeah! C'mon, you shit-eatin' sonsabitches!": "Yeah! Lên đi, mấy thằng chó đẻ ăn cứt!",
  "Just takin' inventory while you decide when you're ready to load up.": "Tôi chỉ đang kiểm kê đồ đạc trong khi chờ cậu quyết định xem khi nào thì sẵn sàng nạp đạn.",
  "Scanning.": "Đang quét.",
  "Let's hole up here, let' em run right past.": "Hãy ẩn nấp ở đây đi, cứ để bọn chúng chạy lướt qua.",
  "Well, I suppose I owe you one.": "Chà, tôi đoán là tôi nợ cậu một ân tình.",
  "%1$s is sick now too.": "%1$s bây giờ cũng bị bệnh rồi.",
  "Target spotted.": "Đã phát hiện mục tiêu.",
  "Refrigerated Supply": "Nguồn Cung Cấp Đông Lạnh",
  "Madison Grant is safe": "Madison Grant đã an toàn",
  "Remote enough we'd have to drive to get anywhere, but I see your point.": "Đủ hẻo lánh để chúng ta phải lái xe nếu muốn đi đến bất cứ đâu, nhưng tôi hiểu ý cậu.",
  "Gross": "Kinh Tởm",
  "Gunpowder": "Thuốc Súng",
  "That's not important. Is it true?": "Điều đó đéo quan trọng. Nó có đúng sự thật không?",
  "Choose a specialization": "Chọn một chuyên môn",
  "We saved Dan Bogatz": "Chúng ta đã cứu Dan Bogatz",
  "Hey. Thank you again. I owe you my life.": "Này. Cảm ơn cậu lần nữa. Tôi nợ cậu mạng sống này.",
  "Get Doc Hanson.": "Đi tìm Bác sĩ Hanson đi.",
  "Wait!": "Đợi đã!",
  "I'm just worn out. Food isn't going to change that.": "Tôi chỉ đang kiệt sức thôi. Thức ăn sẽ đéo thể thay đổi được điều đó đâu.",
  "Those folks need someone to help them get down here. -%2$s": "Những người đó cần ai đó giúp họ xuống đây. -%2$s",
  "Ex-wife. Oh, like it matters. Yes, please get us out of here!": "Vợ cũ. Ồ, làm như điều đó quan trọng lắm vậy. Đúng, làm ơn đưa chúng tôi ra khỏi đây đi!",
  "Honestly, a little town like this? It's not like the stores here had the greatest selection to begin with.": "Thành thật mà nói, một thị trấn nhỏ như thế này á? Các cửa hàng ở đây vốn dĩ cũng đéo có nhiều sự lựa chọn ngay từ đầu rồi.",
  "Fortunately, I have faith in you.": "May mắn thay, tôi có niềm tin ở cậu.",
  "Anybody got a car I could use?": "Có ai có chiếc xe nào tôi có thể dùng được không?",
  "He needed a doctor.": "Ông ấy cần một bác sĩ.",
  "So now we got zeds wearin' body armor. What's next, drivin' cars?": "Vậy là bây giờ chúng ta có bọn zed mặc áo giáp chống đạn. Điều gì tiếp theo đây, chúng nó lái xe luôn chắc?",
  "Huh. I expected the universe to shit on us.": "Hừm. Tôi đã đinh ninh là vũ trụ lại chuẩn bị giáng thêm một đống cứt lên đầu chúng ta cơ.",
  "Just got word that a whole bunch more zombies are headed your way.": "Vừa nhận được tin báo rằng có thêm một đám đông zombie đang tiến về phía các người.",
  "Artillery is operational, ma'am. We can start lighting up the zeds any time you want.": "Pháo binh đã sẵn sàng hoạt động, thưa cô. Chúng ta có thể nã pháo vào bọn zed bất cứ lúc nào cô muốn.",
  "Sgt": "Trung Sĩ",
  "%1$s made the ultimate sacrifice.": "%1$s đã thực hiện sự hy sinh cao cả nhất.",
  "Yeah, didn't think so.": "Ừ, tôi cũng đéo nghĩ thế đâu.",
  "Trujillo": "Trujillo",
  "Hunter": "Thợ Săn",
  "Come on now, don't y'all be a bunch of pussies! We still need somebody with a ride down here at the farm!": "Thôi nào, đừng có hành xử như một lũ chết nhát! Chúng tôi vẫn cần ai đó có xe ở trang trại dưới này!",
  "I see something ahead of us.": "Tôi thấy cái gì đó ở phía trước chúng ta kìa.",
  "Sudden noises are great for grabbing attention. (Best to toss these and then run or hide.)": "Những tiếng ồn bất ngờ rất tuyệt để thu hút sự chú ý. (Tốt nhất là ném những thứ này rồi chạy hoặc trốn.)",
  "BUILDING TENSION": "GIA TĂNG SỰ CĂNG THẲNG",
  "Engaging!": "Giao chiến!",
  "Look for Alan Gunderson": "Tìm Alan Gunderson",
  "-60% Max Stamina": "-60% Thể Lực Tối Đa",
  "No user signed in": "Chưa có người dùng đăng nhập",
  "These leave an impression.": "Những thứ này để lại ấn tượng đấy.",
  "Hey, hey! Low stamina makes it easier for the zeds to drag you down.": "Này, này! Thể lực thấp sẽ khiến bọn zed dễ dàng kéo cậu ngã xuống hơn đấy.",
  "You gonna be okay on your own?": "Cậu tự lo một mình được không đấy?",
  "I know you're scared, but I know a trick to help. Follow me.": "Tôi biết cậu đang sợ hãi, nhưng tôi biết một mẹo có thể giúp ích. Theo tôi.",
  "Doghouse - Vehicle Delivery": "Doghouse - Giao Phương Tiện",
  "Shit, they're around back!": "Chết tiệt, chúng vòng ra đằng sau rồi!",
  "You are still ENCUMBERED. Stamina will drain rapidly while sprinting.": "Bạn vẫn đang bị QUÁ TẢI (ENCUMBERED). Thể lực sẽ giảm nhanh chóng khi chạy nước rút.",
  "Gamer Rating": "Xếp Hạng Người Chơi",
  "EXPIRED: Zed Hunt": "HẾT HẠN: Săn Zed",
  "Fear Itself": "Bản Thân Nỗi Sợ Hãi",
  "Uppercut": "Cú đấm móc (Uppercut)",
  "Listen, I'm a generous guy, but at some point you're just taking advantage of me.": "Nghe này, tôi là một người hào phóng, nhưng đến một lúc nào đó thì cậu chỉ đang lợi dụng tôi thôi.",
  "I need some damn backup!": "Tôi cần chó chết một chút viện trợ!",
  "You build up some excellent interpersonal skills when you work all day with people on the edge of dementia.": "Cậu sẽ xây dựng được những kỹ năng giao tiếp tuyệt vời khi làm việc cả ngày với những người đang trên bờ vực mất trí nhớ.",
  "Desperately Need Medicine": "Tuyệt Vọng Cần Thuốc Men",
  "Wonder what's gonna go wrong today.": "Tự hỏi hôm nay sẽ có chuyện tồi tệ gì xảy ra đây.",
  "XP penalty from Two Left Feet.": "Hình phạt XP từ Lóng Ngóng (Two Left Feet).",
  "We ain't done yet!": "Chúng ta vẫn chưa xong đâu!",
  "Retrieved Thomas Ritter's watch for Lily. Something to remember him by.": "Đã lấy lại được chiếc đồng hồ của Thomas Ritter cho Lily. Một thứ gì đó để tưởng nhớ về anh ấy.",
  "Looks like we have an issue in the Kitchen.": "Có vẻ như chúng ta đang gặp vấn đề trong Nhà Bếp.",
  "I don't know what your problem is, and I don't care. But you're making it everybody's problem, and that's not gonna fly.": "Tôi đéo biết vấn đề của cậu là gì, và tôi cũng đéo quan tâm. Nhưng cậu đang biến nó thành vấn đề của mọi người, và chuyện đó sẽ đéo được chấp nhận đâu.",
  "Not many people feel like dancing right now. Things are just too goddamn depressing. (Improved Cardio)": "Bây giờ đéo có mấy ai có tâm trạng để nhảy múa đâu. Mọi thứ đang quá sức tuyệt vọng mẹ nó rồi. (Cải Thiện Tim Mạch)",
  "Reduced Wound Recovery chance.": "Giảm cơ hội Phục Hồi Vết Thương (Wound Recovery).",
  "98 GENERIC Jackson Hollis": "98 GENERIC Jackson Hollis",
  "Sight Adjustment Tools": "Bộ Dụng Cụ Điều Chỉnh Ống Ngắm",
  "Yes. This is definitely where we should be.": "Vâng. Đây chắc chắn là nơi chúng ta nên ở lại.",
  "I got all the way to the edge of town just to get trapped in a building!": "Tôi đã lặn lội đến tận rìa thị trấn chỉ để bị mắc kẹt trong một tòa nhà!",
  "A powerful slam from a zombie caused massive contusions and internal bleeding. (Health and Stamina penalty)": "Một cú đập mạnh từ một con zombie đã gây ra những vết bầm tím lớn và chảy máu trong. (Hình phạt về Máu và Thể Lực)",
  "Gathered medicine.": "Đã thu thập thuốc men.",
  "94 GENERIC Frank Fitzgerald": "94 GENERIC Frank Fitzgerald",
  "Mickey, can you watch my ass?": "Mickey, cậu có thể bọc hậu cho tôi được không?",
  "I managed to find %3$s and get them home safe and sound.": "Tôi đã tìm được %3$s và đưa họ về nhà an toàn.",
  "Talk to %1$s %2$s": "Nói chuyện với %1$s %2$s",
  "You're giving away our goddamn position with this Rambo shit.": "Cậu đang để lộ vị trí chết tiệt của chúng ta bằng cái trò Rambo chó má này đấy.",
  "Nobody knows what it is. But it sure as shit ain't a virus. We'd have seen it by now.": "Đéo ai biết nó là cái gì. Nhưng chắc chắn như ban ngày rằng đéo phải là một loại virus. Nếu thế thì chúng ta đã phát hiện ra nó rồi.",
  "Left": "Bên trái",
  "Okoro": "Okoro",
  "Madelyn": "Madelyn",
  "Anybody tell you you can be a real meanie-weenie?": "Đã có ai nói với cậu rằng cậu có thể là một kẻ thực sự xấu tính chưa?",
  "Whitlock": "Whitlock",
  "Search and Rescue": "Tìm Kiếm và Cứu Hộ",
  "Lorenz": "Lorenz",
  "Fish Stunner": "Dụng Cụ Chích Điện Cá (Fish Stunner)",
  "Round up your people and get them on that bird.": "Tập hợp người của cậu lại và đưa họ lên chiếc trực thăng đó đi.",
  "Scientific Principles": "Các Nguyên Lý Khoa Học",
  "105 STORY Philip Manfred": "105 STORY Philip Manfred",
  "Great. Out of food.": "Tuyệt. Đéo còn thức ăn nữa.",
  "You sure about this?": "Cậu chắc chắn về điều này chứ?",
  "Get clear! I got these assholes!": "Tránh ra! Để lũ khốn này cho tôi!",
  "Black Friday, we're picking up a strange broadcast here that none of my folks can make any sense of.": "Black Friday, chúng tôi đang bắt được một chương trình phát thanh kỳ lạ ở đây mà đéo ai trong số người của tôi có thể hiểu được.",
  "Yeah, well, excuse me for not being team cheerleader.": "Vâng, chà, xin thứ lỗi cho việc tôi đéo phải là đội trưởng đội cổ vũ.",
  "Helped %3$s with a supply run. They were glad for the help, so they cut us in. -%1$s": "Đã giúp %3$s thực hiện một chuyến đi thu thập vật tư. Họ rất vui vì được giúp đỡ, nên họ đã chia phần cho chúng ta. -%1$s",
  "Almost out of that.": "Gần như đã cạn kiệt thứ đó rồi.",
  "On the right side, you seein' this?": "Bên cánh phải, cậu có thấy không?",
  "He's a whiz with a gun, and the dozens of taxidermied animals on his wall prove it.": "Anh ta là một chuyên gia sử dụng súng, và hàng tá động vật nhồi bông trên tường của anh ta đã chứng minh điều đó.",
  "RIP Andy": "Yên nghỉ nhé Andy",
  "Resolution 2160p": "Độ phân giải 2160p"
};

const file = 'output/languages/chunks/btxt_chunk_129.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_129.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk129[r.sourceText]) {
    r.translatedText = chunk129[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 129 successfully!');
