const fs = require('fs');
const chunk146 = {
  "Okay, time to see what we see.": "Được rồi, đến lúc xem xem chúng ta có gì nào.",
  "That one doesn't look so good.": "Kẻ đó trông đéo ổn chút nào.",
  "We're not out of the woods yet.": "Chúng ta vẫn chưa thoát khỏi nguy hiểm đâu.",
  "We've got an opening. Let's get out of here while we can.": "Chúng ta có một lối thoát. Hãy cút khỏi đây khi còn có thể.",
  "Yeah, well, trust me... you don't want those two in a room together right now.": "Phải, ừ thì, tin tôi đi... cậu đéo muốn hai người đó ở chung một phòng ngay lúc này đâu.",
  "Mom and Dad were both in the armed services. The house was run like a military unit ... or perhaps a military prison.": "Cả Bố và Mẹ đều phục vụ trong quân đội. Ngôi nhà được vận hành giống như một đơn vị quân đội ... hay có lẽ là một nhà tù quân sự.",
  "Rifle: Micro Dynamic Rifle": "Súng Trường (Rifle): Súng Trường Micro Dynamic",
  "Anything you want to tell me?": "Cậu có điều gì muốn nói với tôi đéo?",
  "Take The Survivors Home": "Đưa Những Người Sống Sót Về Nhà",
  "Yeah, I got that impression. Come on. Follow me.": "Phải, tôi cũng có cảm giác đó. Thôi nào. Theo tôi.",
  "Hold [ul_aim] to aim. Press [ul_shoot] to shoot.": "Giữ [ul_aim] để ngắm. Nhấn [ul_shoot] để bắn.",
  "Gathered by %1$s.": "Được thu thập bởi %1$s.",
  "Alan just shot Pastor Will.": "Alan vừa mới bắn Mục sư Will.",
  "I've got a few other leads, though, if you'd cover me while I go look.": "Dù vậy, tôi có một vài manh mối khác, nếu cậu yểm trợ cho tôi trong lúc tôi đi tìm.",
  "Charley": "Charley",
  "Give the man a ride?": "Cho anh bạn này đi nhờ một chuyến đéo?",
  "Now don't get all riled up, it ain't as bad as all that. I'm reliably informed the ancient Egyptians did it with fair regularity.": "Nào, đừng có nổi cáu lên thế, chuyện đéo đến mức tồi tệ thế đâu. Tôi được thông báo một cách đáng tin cậy rằng người Ai Cập cổ đại đã làm điều đó với mức độ khá thường xuyên đấy.",
  "Spotted something. Should be some useful stuff there.": "Phát hiện ra thứ gì đó. Chắc hẳn phải có một vài món đồ hữu ích ở đó.",
  "Needs Tattoo Artist": "Cần Thợ Xăm",
  "MEDICINE RESOURCE. Medication for animals.": "NGUỒN THUỐC MEN. Thuốc dùng cho động vật.",
  "Hey, what's up?": "Này, có chuyện gì vậy?",
  "Dude, what the hell? I saw you like ten minutes ago. Also? Kinda busy here.": "Anh bạn, cái quái gì vậy? Tôi vừa gặp cậu tầm mười phút trước mà. Hơn nữa? Đang hơi bận ở đây đấy.",
  "Garza": "Garza",
  "Reckon I better go patch this up. After that, think I'll get my sorry ass blind stinking drunk for a month of Sundays.": "Chắc tôi nên đi băng bó lại vết thương này thôi. Sau đó, tôi nghĩ tôi sẽ vác cái mông thảm hại của mình đi uống cho say bí tỉ, say đéo biết trời đất gì trong suốt một thời gian dài cho xem.",
  "Search for Sasquatch": "Tìm kiếm Sasquatch",
  "Excellent.": "Xuất sắc.",
  "Continuing to monitor the situation.": "Tiếp tục theo dõi tình hình.",
  "Team Player": "Đồng Đội Tốt",
  "MISSION: The Voice On the Radio": "NHIỆM VỤ: Giọng Nói Trên Radio",
  "Enjoyed Sailing": "Từng Đam Mê Đua Thuyền",
  "Sure, why not? I've amassed a fair little collection since this business went down. I can spare one for a new friend. It's all about people pulling together, after all.": "Chắc chắn rồi, tại sao đéo chứ? Tôi đã tích cóp được một bộ sưu tập kha khá kể từ khi mớ hỗn độn này nổ ra. Tôi có thể dành ra một cái cho người bạn mới. Rốt cuộc thì, đây là lúc mọi người phải đoàn kết lại với nhau mà.",
  "You been sleeping okay?": "Cậu dạo này ngủ ổn đéo?",
  "You keep making that much noise, I may have to shoot you myself.": "Cậu mà cứ gây ra nhiều tiếng ồn như thế, có khi chính tôi sẽ phải bắn cậu đấy.",
  "Handbrake": "Phanh Tay",
  "Shannon": "Shannon",
  "Anyway, I don't think Lily's quite forgiven me yet.": "Dù sao thì, tôi đéo nghĩ Lily đã hoàn toàn tha thứ cho tôi đâu.",
  "These things aren't your regular shambling corpses.": "Những thứ này đéo phải là lũ xác chết lê lết thông thường đâu.",
  "Thalia": "Thalia",
  "I think she grew up somewhere around here, she might have holed up in one of these buildings.": "Tôi nghĩ cô ấy lớn lên ở đâu đó quanh đây, cô ấy có thể đang trốn trong một trong những tòa nhà này.",
  "Stand by!": "Chuẩn bị sẵn sàng!",
  "Gomez": "Gomez",
  "Doctor Horn is dead, by his own hand. He was my responsibility, but I didn't see this coming. He seemed convinced that he was going to turn, and that putting a bullet in his head was the only way out.\r\nNow we'll never know what would have happened. How many lives he might have saved. I hope the brass has a backup plan.": "Bác sĩ Horn đã chết, do chính tay ông ấy tự sát. Ông ấy là trách nhiệm của tôi, nhưng tôi đã đéo lường trước được chuyện này. Ông ấy có vẻ tin chắc rằng mình sẽ biến đổi, và việc găm một viên đạn vào đầu là lối thoát duy nhất.\r\nBây giờ chúng ta sẽ đéo bao giờ biết được điều gì sẽ xảy ra. Ông ấy có thể đã cứu sống bao nhiêu mạng người. Tôi hy vọng đám sĩ quan cấp cao có một kế hoạch dự phòng.",
  "Oh. Okay, yeah. No, sure. I understand.": "Ồ. Được rồi, phải. Đéo, chắc chắn rồi. Tôi hiểu.",
  "Loved Dancing": "Từng Yêu Thích Khiêu Vũ",
  "Managed to get what we wanted, on my way back.": "Đã lấy được thứ chúng ta cần, đang trên đường quay lại.",
  "I'm headed back to base. Tell me when you're ready to get serious.": "Tôi sẽ quay về căn cứ. Nói cho tôi biết khi nào cậu sẵn sàng nghiêm túc nhé.",
  "Local carpenter, one of the first to help organize survivors.": "Thợ mộc địa phương, một trong những người đầu tiên giúp đỡ tổ chức lại những người sống sót.",
  "JOURNAL: Broken Up": "NHẬT KÝ: Đã Chia Tay",
  "Hey, we could use some help here!": "Này, chúng tôi cần được giúp đỡ ở đây!",
  "Option 2": "Tùy chọn 2",
  "Rosa": "Rosa",
  "This isn't over yet.": "Chuyện này vẫn chưa kết thúc đâu.",
  "I'll look into it.": "Tôi sẽ xem xét việc đó.",
  "Milo added 4 Ammo, 4 Fuel, and more pipe bombs than we know what to do with.": "Milo vừa thêm vào 4 Đạn (Ammo), 4 Nhiên Liệu (Fuel), và nhiều bom ống tới mức chúng ta đéo biết phải làm gì với chúng.",
  "Max": "Max",
  "Aspect Ratio - 4:3": "Tỷ Lệ Khung Hình - 4:3",
  "Sure it's a workout, but crushing zombies with large, heavy objects is the only way to master Heavy Weapon Specialization.": "Chắc chắn đây là một bài tập thể lực rồi, nhưng đập nát bọn zombie bằng những vật thể to và nặng là cách duy nhất để thành thạo Chuyên Môn Vũ Khí Hạng Nặng (Heavy Weapon Specialization).",
  "REFUSE HERO. Let them know they're on their own.": "TỪ CHỐI ANH HÙNG (HERO). Cho họ biết rằng họ phải tự lo thân đi.",
  "That was an impressive stroke of good fortune.": "Đó quả là một sự may mắn vô cùng ấn tượng đấy.",
  "Anything you need to get off your chest?": "Cậu có điều gì cần phải xả ra cho nhẹ lòng đéo?",
  "MISSION: Escort": "NHIỆM VỤ: Hộ Tống",
  "Emote 1": "Biểu Cảm 1",
  "Play Lifeline": "Chơi Lifeline",
  "So maybe she's not technically the law of the land... but damn sure we'd all be dead without her.": "Nên có thể về mặt lý thuyết cô ấy đéo phải là luật lệ của vùng đất này... nhưng chắc chắn một điều rằng tất cả chúng ta đều sẽ chết ngóm nếu đéo có cô ấy.",
  "Civilian CasEvac isn't the mission. Isolate, contain, identify. Until the squints figure out what's causing this little chucklefuck, you're all potential carriers.": "Sơ tán y tế dân sự (Civilian CasEvac) đéo phải là nhiệm vụ. Cách ly, ngăn chặn, nhận dạng. Cho đến khi đám mọt sách tìm ra nguyên nhân gây ra cái mớ hỗn độn chết tiệt này, tất cả các người đều là những vật mang mầm bệnh tiềm ẩn.",
  "Your RV eventually breaks down in an area with refreshed supplies where you can start to rebuild. It will serve as a temporary home site for you until you can find a new place to live.": "Cuối cùng thì chiếc xe RV của bạn sẽ bị hỏng ở một khu vực có các nguồn cung cấp được làm mới, nơi bạn có thể bắt đầu xây dựng lại. Nó sẽ đóng vai trò như một địa điểm đóng quân tạm thời cho bạn cho đến khi bạn có thể tìm thấy một nơi ở mới.",
  "I think she grew up somewhere around here, she might have holed up in one of those buildings.": "Tôi nghĩ cô ấy lớn lên ở đâu đó quanh đây, cô ấy có thể đang trốn trong một trong những tòa nhà đó.",
  "We're safe as long as we have ammo and a guard tower.": "Chúng ta sẽ an toàn chừng nào chúng ta còn đạn dược và tháp canh (guard tower).",
  "Nah, I'm fine for now.": "Đéo, hiện tại thì tôi ổn.",
  "Took karate to get revenge on everybody who made fun of him in high school.": "Đã học karate để trả thù tất cả những kẻ đã từng chế giễu anh ta ở trường trung học.",
  "Special counter that lets you jump over an enemy and knock it to its knees.": "Đòn phản công đặc biệt cho phép bạn nhảy qua kẻ thù và quật ngã hắn quỳ xuống đất.",
  "Gotta walk for this one.": "Phải đi bộ cho vụ này rồi.",
  "That'll draw some attention.": "Thứ đó sẽ thu hút sự chú ý đây.",
  "All this medicine just went bad. Don't any of you people check the expiration date?": "Tất cả đống thuốc này đều hỏng hết rồi. Đéo có ai trong số mấy người chịu kiểm tra hạn sử dụng à?",
  "Julius": "Julius",
  "Might want to consider it for some of our surplus.": "Có thể sẽ muốn cân nhắc điều đó đối với một số vật dụng dư thừa của chúng ta.",
  "The apocalyptic handyman's best friend.": "Người bạn thân thiết nhất của những gã thợ đụng thời tận thế.",
  "Stamina will gradually recover while resting at home. It should take about 1 hour and 30 minutes to get back to full Stamina.": "Thể lực (Stamina) sẽ dần dần phục hồi trong khi nghỉ ngơi tại căn cứ. Sẽ mất khoảng 1 giờ 30 phút để phục hồi lại toàn bộ Thể lực.",
  "Vitality will gradually recover while resting at home. It should take about 10 hours to get back to full Vitality.": "Sinh lực (Vitality) sẽ dần dần phục hồi trong khi nghỉ ngơi tại căn cứ. Sẽ mất khoảng 10 giờ để phục hồi lại toàn bộ Sinh lực.",
  "Freak": "Quái Nhân (Freak)",
  "Oh, fuck you and your \"noble martyr\" bullshit! You don't go shooting people without at least consulting the fucking rest of us!": "Ồ, kệ mẹ cậu và cái thứ vớ vẩn \"liệt sĩ cao cả\" của cậu đi! Cậu đéo thể đi bắn người mà đéo thèm bàn bạc với phần còn lại chết tiệt của chúng tôi một tiếng được đâu!",
  "I'll start taking inventory.": "Tôi sẽ bắt đầu kiểm kê hàng hóa.",
  "Use the \"Train Outsiders\" action at the Shooting Platform to accept.": "Sử dụng hành động \"Huấn luyện Người ngoài (Train Outsiders)\" tại Sân Bắn (Shooting Platform) để chấp nhận.",
  "You were untouchable out there, man.": "Cậu quả là đéo thể cản bước ở ngoài đó đấy, anh bạn.",
  "She always had a good head on her shoulders. If she was in trouble, she would've tried to get inside, and fortify someplace till we came looking.": "Cô ấy luôn là người rất tỉnh táo. Nếu cô ấy đang gặp rắc rối, cô ấy hẳn sẽ cố gắng vào trong, và cố thủ ở một nơi nào đó cho đến khi chúng ta đi tìm.",
  "I can't leave yet. It's my fault our food stores went bad. I've got to make it right.": "Tôi vẫn chưa thể rời đi được. Việc kho thức ăn của chúng ta bị hỏng là lỗi của tôi. Tôi phải sửa sai mới được.",
  "The Killer": "Kẻ Giết Người",
  "Rescue Op": "Chiến Dịch Giải Cứu (Rescue Op)",
  "Make Firecracker": "Chế Tạo Pháo Thăng Thiên (Firecracker)",
  "Perform 50 Stealth Kills. (Breakdown Level 5 or Higher)": "Thực hiện 50 Pha Hạ Gục Lén Lút. (Breakdown Cấp 5 trở lên)",
  "Ibuprofen": "Ibuprofen",
  "Need ammo here!": "Cần đạn ở đây!",
  "Who do you think should staff the place?": "Cậu nghĩ ai nên túc trực ở nơi này?",
  "That's nothing. I caught him earlier, staring at his pistol like it was his long-lost friend.": "Thế chưa là gì đâu. Trước đó tôi còn bắt gặp anh ta, đang nhìn chằm chằm vào khẩu súng lục của mình như thể nó là một người bạn thất lạc từ lâu vậy.",
  "I'm sorry, listeners. It's time for me to get off this channel, and make my own way out of the city.": "Tôi xin lỗi các thính giả. Đã đến lúc tôi phải rời khỏi kênh này, và tự tìm đường thoát khỏi thành phố rồi.",
  "Hey, cheer up, boss. Can't be all bad.": "Này, vui lên đi, sếp. Mọi chuyện đéo thể tồi tệ mãi được đâu.",
  "Arnold": "Arnold",
  "Nice Person": "Người Tốt",
  "I've been saying it forever, we need a kitchen. I'm sick and tired of eating cold processed meat all the time.": "Tôi đã nói cái điều này cả tỷ lần rồi, chúng ta cần một nhà bếp. Tôi phát ốm và mệt mỏi với việc lúc đéo nào cũng phải ăn thịt hộp lạnh ngắt rồi.",
  "Small caliber rounds for pistols, revolvers, rifles, and SMGs.": "Đạn cỡ nhỏ dùng cho súng lục, súng côn, súng trường, và tiểu liên."
};

const file = 'output/languages/chunks/btxt_chunk_146.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_146.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk146[r.sourceText]) {
    r.translatedText = chunk146[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 146 successfully!');
