const fs = require('fs');
const chunk103 = {
  "Velazquez": "Velazquez",
  "Mulroney": "Mulroney",
  "If you're listening, I'm here to help you survive.": "Nếu bạn đang nghe, tôi ở đây để giúp bạn sống sót.",
  "You gotta wrap it real tight. If you can still feel the limb afterwards, it ain't tight enough.": "Cậu phải băng nó lại thật chặt. Nếu cậu vẫn còn cảm thấy cái chân (hoặc tay) sau đó, tức là nó chưa đủ chặt đâu.",
  "Hang tight, still got half this place to fortify.": "Cố bám trụ nhé, vẫn còn một nửa khu này cần phải gia cố.",
  "Well? What are you waiting for?": "Sao hả? Cậu còn chờ gì nữa?",
  "I could use some food.": "Tôi cần một chút thức ăn.",
  "Anyways, even if we didn't know him that well, we'll miss him. So long, Ed.": "Dù sao đi nữa, ngay cả khi chúng ta không biết rõ về anh ấy, chúng ta sẽ rất nhớ anh ấy. Tạm biệt, Ed.",
  "Creates a couple of homemade suppressors.": "Chế tạo một vài ống giảm thanh tự chế.",
  "One of our guys has gone missing. We could use some help finding him.": "Một người của chúng tôi đã mất tích. Chúng tôi cần sự giúp đỡ để tìm anh ta.",
  "Set Up Barracks": "Dựng Trại Lính",
  "Anything I need to take care of?": "Có chuyện gì cần tôi giải quyết không?",
  "Here in the valley for a hunting trip with some old Army buddies. A veteran sharpshooter.": "Đến thung lũng này cho một chuyến đi săn với vài chiến hữu cũ trong Quân đội. Một tay thiện xạ kỳ cựu.",
  "Some things (like a Garden) can't be built indoors.": "Một số công trình (như Khu Vườn) không thể xây trong nhà.",
  "Targets Neutralized": "Đã Vô Hiệu Hóa Mục Tiêu",
  "Civilians Rescued (Lifeline)": "Thường Dân Được Cứu (Chiến dịch Lifeline)",
  "I'd be surprised if you had. They never got much national press. Just a small, quiet bunch of crazies who thought the Reds were going to rain nuclear hellfire down on us any day.": "Tôi sẽ rất ngạc nhiên nếu cậu biết. Họ chưa bao giờ được báo chí quốc gia chú ý nhiều. Chỉ là một đám cuồng tín nhỏ bé, im lìm, những kẻ luôn nghĩ rằng bọn Cộng sản sẽ trút cơn mưa hạt nhân xuống đầu chúng ta bất cứ lúc nào.",
  "%1$s got home with the supplies, but it was a close call. - %2$s": "%1$s đã mang được nhu yếu phẩm về nhà, nhưng suýt nữa thì mất mạng. - %2$s",
  "It was bad. The zombies got in somehow and just swarmed them.": "Rất tệ. Lũ zombie bằng cách nào đó đã lọt vào và tràn ngập bọn họ.",
  "Maybe they just look dead. To us. Maybe this whole thing is really just some ... new kind of life.": "Có lẽ chúng chỉ trông như đã chết. Đối với chúng ta. Có lẽ toàn bộ chuyện này thực sự chỉ là một... hình thái sự sống mới.",
  "Hell, when that horde started swarming the walls, I thought we were all done for.": "Khốn kiếp, khi cái bầy đó bắt đầu tràn qua tường, tôi đã nghĩ tất cả chúng ta xong đời rồi.",
  "Community, you see. That's what matters--now more than ever. All of us together, doing our own thing but helping our neighbors when they need it.": "Cộng đồng, cậu thấy đấy. Đó mới là điều quan trọng--bây giờ hơn bao giờ hết. Tất cả chúng ta cùng nhau, làm việc của mình nhưng vẫn giúp đỡ những người hàng xóm khi họ cần.",
  "Ms. Grant, I'm sorry ... Thomas Horn is dead. We need your help with his notes. Were you involved with his research?": "Cô Grant, tôi rất tiếc... Thomas Horn đã chết. Chúng tôi cần cô giúp đỡ giải mã các ghi chép của ông ấy. Cô có tham gia vào nghiên cứu của ông ấy không?",
  "Bell": "Bell",
  "I'm ready.": "Tôi sẵn sàng rồi.",
  "I can't keep this up if every time I ask for help, the army just swoops in and gets everybody killed.": "Tôi không thể tiếp tục chuyện này nếu mỗi lần tôi yêu cầu giúp đỡ, quân đội lại ập đến và khiến mọi người bỏ mạng.",
  "specialization": "chuyên môn",
  "If I don't get the medicine I need soon, I'm in the same boat as your friend.": "Nếu tôi không sớm có được loại thuốc tôi cần, tôi cũng sẽ chịu chung số phận như bạn của cậu thôi.",
  "Oh honey, that's wonderful!": "Ôi con yêu, điều đó thật tuyệt vời!",
  "These freaks are a fuckin' nightmare. Help us out?": "Những con quái vật này là một cơn ác mộng chết tiệt. Cậu giúp chúng tôi một tay được không?",
  "Thanks. For everything.": "Cảm ơn. Vì tất cả.",
  "Stranger in Trouble": "Người Lạ Gặp Nạn",
  "18 MIL Sgt Ashley Bronson": "18 MIL Trung sĩ Ashley Bronson",
  "Nah, this place is too small.": "Không đâu, chỗ này quá chật chội.",
  "I used to crunch numbers, but now I'm crunching skulls. Never saw that coming.": "Tôi từng nghiền ngẫm những con số, nhưng bây giờ tôi đang nghiền nát những hộp sọ. Chưa bao giờ tôi ngờ tới điều đó.",
  "Eli": "Eli",
  "Shit. Is he still alive?": "Chết tiệt. Anh ta còn sống không?",
  "7 GENERIC Hank Rassle": "7 GENERIC Hank Rassle",
  "Abigail": "Abigail",
  "Just checked our stockpiles.": "Tôi vừa kiểm tra lại kho dự trữ của chúng ta.",
  "Yeah! Let's do this!": "Yeah! Làm tới bến luôn nào!",
  "Delivered 6 rucksacks to your base in the back of a single vehicle.": "Đã giao 6 túi đồ về căn cứ trong cốp của một chiếc xe.",
  "Took your own sweet time finding me, didn't ya?": "Mất khá nhiều thời gian vàng bạc để tìm ra tôi, phải không?",
  "Losses": "Tổn Thất",
  "Swinging for the fences, metal style.": "Vung gậy hết cỡ, phong cách hạng nặng.",
  "Everybody signed her yearbook \"Have a great summer.\"": "Mọi người đều ký vào kỷ yếu của cô ấy dòng chữ \"Chúc một mùa hè tuyệt vời.\"",
  "We should get on this ASAP. A life is at stake.": "Chúng ta nên xử lý việc này CÀNG SỚM CÀNG TỐT. Một mạng người đang bị đe dọa.",
  "Adrenaline Junkie": "Kẻ Ghiền Adrenaline",
  "COMPLETED: Quentin Barnes?": "ĐÃ HOÀN THÀNH: Quentin Barnes?",
  "Woods": "Woods",
  "You risked yourself to find me? Thanks.": "Cậu liều mạng để tìm tôi sao? Cảm ơn nhé.",
  "A little busy here.": "Tôi đang hơi bận ở đây.",
  "Do you still have any more samples?": "Anh có còn mẫu vật nào khác không?",
  "Intense concentration makes the world around you slow to a crawl as you line up the perfect shot.": "Sự tập trung cao độ khiến thế giới xung quanh chậm lại đến mức bò trườn trong khi cậu ngắm một phát súng hoàn hảo.",
  "Special Delivery": "Giao Hàng Đặc Biệt",
  "So many priceless pieces of art destroyed. It breaks my heart. (Sales experience.)": "Biết bao nhiêu tác phẩm nghệ thuật vô giá bị phá hủy. Chuyện đó làm trái tim tôi tan nát. (Kinh nghiệm Bán hàng.)",
  "Autumn": "Autumn",
  "Never mind. Forget I said anything.": "Đừng bận tâm. Cứ quên những gì tôi vừa nói đi.",
  "I know you did. I know that. But see, here's where I have a problem. I also know what I told you last time.": "Tao biết là mày đã làm vậy. Tao biết. Nhưng nhìn xem, đây là chỗ tao có vấn đề. Tao cũng biết tao đã dặn mày cái gì vào lần trước.",
  "Created 3 Pipe Bombs.": "Đã chế tạo 3 Bom Ống (Pipe Bomb).",
  "Come on, I saw a truck just up the road. I don't think you should be walking right now.": "Lại đây, tôi thấy một chiếc xe tải ở ngay khúc trên kia. Tôi không nghĩ cậu nên đi bộ lúc này đâu.",
  "Anthony": "Anthony",
  "Hey Lily, let folks know I'll be home soon.": "Này Lily, báo cho mọi người biết là tôi sẽ về nhà sớm thôi.",
  "I'd probably be dead, if not for you.": "Tôi có lẽ đã chết, nếu không có cậu.",
  "Deal with it.": "Chấp nhận đi.",
  "Our mom died when I was thirteen. Lily was nine.": "Mẹ chúng tôi qua đời khi tôi mười ba tuổi. Lily lên chín.",
  "Exercise caution while we look into this. Highroad out.": "Hãy cẩn trọng trong lúc chúng tôi điều tra chuyện này. Highroad, hết.",
  "Yeah. It might be time I had a little talk with the Wilkersons.": "Ừ. Có lẽ đã đến lúc tôi nên có một cuộc trò chuyện nhỏ với anh em nhà Wilkerson.",
  "Heads up! Coming in with supplies now.": "Cẩn thận! Đang mang nhu yếu phẩm về.",
  "There's a good infirmary here. Just need to stock it and clean up a little... Okay, a lot.": "Có một bệnh xá tốt ở đây. Chỉ cần tích trữ thuốc men và dọn dẹp một chút... Được rồi, là dọn dẹp rất nhiều.",
  "Thomas Horn's former research partner. Became one of his staunchest critics after they had some kind of falling out.": "Đồng nghiệp nghiên cứu cũ của Thomas Horn. Trở thành một trong những nhà phê bình gay gắt nhất của ông ta sau khi hai người có xích mích.",
  "Make .40 Ammo": "Chế tạo đạn cỡ .40",
  "Patrick": "Patrick",
  "Designating a location for a drone strike.": "Đang chỉ định một vị trí để không kích bằng Drone.",
  "I'm headed home.": "Tôi đang về nhà đây.",
  "One nasty son of a bitch.": "Một thằng khốn nạn tởm lợm.",
  "Do I have to? Okay, okay. Fine.": "Tôi có bắt buộc không? Được rồi, được rồi. Ổn thôi.",
  "I'm writing all this down, just in case.": "Tôi đang ghi chép lại tất cả những thứ này, phòng hờ.",
  "I'm trying to avoid combat, but it's hard.": "Tôi đang cố gắng tránh giao chiến, nhưng thật sự rất khó.",
  "Losing that outpost leaves us vulnerable to the zeds.": "Mất đi tiền đồn đó khiến chúng ta trở nên dễ bị lũ Zed tấn công.",
  "Do you want to sign in? If you don't you will be unable to save progress.": "Bạn có muốn đăng nhập không? Nếu không bạn sẽ không thể lưu lại tiến trình chơi.",
  "Guess you guys like loud noises.": "Tôi đoán là mấy người thích những tiếng ồn lớn.",
  "Forget it. We're not interested in \"signing up\" with your little society.": "Quên đi. Chúng tôi không hứng thú với việc \"đăng ký\" gia nhập cái xã hội bé nhỏ của các người đâu.",
  "Another big boy! I call dibs!": "Thêm một gã to xác nữa kìa! Tôi xí con này nha!",
  "We've had a few suspicious sightings. Might be people afraid to ask for help. Might be something to worry about. How are things over there? - %1$s": "Chúng tôi phát hiện vài điểm đáng ngờ. Có thể là những người sợ phải lên tiếng nhờ giúp đỡ. Cũng có thể là điều gì đó đáng lo ngại. Tình hình bên đó sao rồi? - %1$s",
  "Guess this arm gives me time to brush up on my domestic skills.": "Tôi đoán là cái tay bị thương này cho tôi thời gian để trau dồi các kỹ năng nội trợ của mình.",
  "If you can hear me, this is Pastor William at the Spencer's Mill Church.": "Nếu các bạn có thể nghe thấy tôi, tôi là Mục sư William ở Nhà thờ Spencer's Mill.",
  "Hey, are you gonna go look into those survivors I mentioned?": "Này, cậu có định đi xem xét nhóm người sống sót mà tôi đã nhắc tới không?",
  "As long as he doesn't get cocky.": "Miễn là anh ta đừng quá kiêu ngạo.",
  "WEAPON DELIVERED": "VŨ KHÍ ĐÃ ĐƯỢC GIAO",
  "142 STORY Jacob Ritter": "142 STORY Jacob Ritter",
  "HADLEY WESTEN": "HADLEY WESTEN",
  "You know what I mean. We all count on each other, and in return we stick together no matter what.": "Cậu biết ý tôi mà. Tất cả chúng ta đều nương tựa vào nhau, và đổi lại chúng ta phải sát cánh bên nhau bất kể chuyện gì.",
  "I'm surrounded!": "Tôi bị bao vây rồi!",
  "Bonus Survivor": "Người Sống Sót Thưởng",
  "We'll gather up our stuff and head over in a bit.": "Chúng tôi sẽ thu dọn đồ đạc và đi sang đó trong chốc lát.",
  "Really take care of people, you know?": "Cậu thực sự quan tâm đến mọi người, cậu biết không?",
  "Here. A little something for the next batch.": "Đây. Một chút quà cho mẻ hàng tiếp theo.",
  "Rifle: Mk. 15": "Súng trường: Mk. 15",
  "Seems like the only way to stop them for good is with a shot to the head. Anything else, they just keep coming.": "Có vẻ như cách duy nhất để cản chúng vĩnh viễn là một phát súng vào đầu. Còn nếu làm bất cứ điều gì khác, chúng vẫn sẽ tiếp tục lao tới."
};

const file = 'output/languages/chunks/btxt_chunk_103.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_103.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk103[r.sourceText]) {
    r.translatedText = chunk103[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 103 successfully!');
