const fs = require('fs');
const chunk202 = {
  "Take %d": "Mang Theo %d",
  "This is THE black SUV the conspiracy theorists talk about. Your tax dollars put in a great engine and made it very tough. Seats four agents (sunglasses optional).": "Đây chính là LÀ một chiếc SUV màu đen vô cùng bí ẩn mà các nhà lý thuyết học âm mưu (conspiracy theorists) vẫn hay thường xuyên bàn tán đến. Những đồng tiền thuế (tax dollars) của bạn đã được đầu tư để lắp đặt một khối động cơ cực kỳ tuyệt vời và khiến cho nó trở nên vô cùng cứng cáp và cực kỳ trâu bò (tough). Có đủ chỗ ngồi (Seats) dành cho bốn người đặc vụ agents (kính râm sunglasses là một tùy chọn tùy ý optional).",
  "Blackburn": "Blackburn",
  "The Events page keeps a log of things that happen to you as you play, including new mission opportunities, results of previous missions, community events, skill upgrades, and global events that impact you and your fellow survivors in Trumbull Valley.\r\nUse the D-pad to select an event and press [xi_a] to show more details such as the people involved, and the associated rewards and bonuses.": "Trang Sự Kiện (Events) sẽ lưu giữ lại một bản nhật ký (log) về tất cả những thứ đang xảy ra đối với bạn trong quá trình bạn chơi game, bao gồm cả những cơ hội thực hiện các nhiệm vụ (mission opportunities) mới, kết quả (results) của những nhiệm vụ trước đó, các sự kiện của cộng đồng (community events), nâng cấp kỹ năng (skill upgrades), và những sự kiện trên quy mô toàn cầu (global events) có tác động (impact) trực tiếp đến bản thân bạn cũng như là những người bạn đồng hành sống sót (fellow survivors) của bạn ở khu vực Thung Lũng Trumbull Valley.\r\nHãy sử dụng cụm phím điều hướng (D-pad) để có thể tiến hành lựa chọn một sự kiện bất kỳ và sau đó nhấn [xi_a] để có thể xem thêm thông tin chi tiết (details) chẳng hạn như là những con người đang có liên quan (involved) đến sự kiện đó, và những phần thưởng (rewards) cũng như các khoản tiền thưởng bổ sung (bonuses) có liên quan (associated).",
  "Hold your position and wait for the next name on the list.": "Hãy tiếp tục giữ vững vị trí (position) của mình đi và chờ đợi cho đến khi cái tên tiếp theo xuất hiện ở trên danh sách.",
  "Hey there, listeners. This is Vienna Cho, surviving the apocalypse for another day.": "Xin chào tất cả mọi người, những vị thính giả (listeners) vô cùng quý mến. Đây là Vienna Cho, đang cố gắng để có thể sống sót (surviving) vượt qua được thảm họa tận thế (apocalypse) thêm một ngày nữa.",
  "Jacob? Come on, let's get you and your friend out of here.": "Jacob ư? Thôi nào, chúng ta hãy cùng nhau mau chóng đưa cậu và cả người bạn của cậu trốn thoát ra khỏi cái nơi này thôi.",
  "Huh. That place takes me back.": "Huh. Cái nơi đó thực sự đã gợi lại cho tôi rất nhiều những kỷ niệm (takes me back) đáng nhớ đấy.",
  "9mm SMG for Federal police.": "Loại súng tiểu liên 9mm SMG chuyên được sử dụng dành cho lực lượng cảnh sát Liên Bang (Federal police).",
  "TIP: Hold [sprint] + [xi_use] to search FASTER but make more NOISE.": "MẸO (TIP): Nhấn và Giữ nút [sprint] + [xi_use] để có thể tiến hành tìm kiếm đồ đạc NHANH HƠN RẤT NHIỀU (FASTER) nhưng đồng thời cũng sẽ tạo ra nhiều TIẾNG ỒN (NOISE) hơn.",
  "Out on patrol.": "Đang ra ngoài để đi tuần tra (patrol).",
  "Just a little under the weather. I should be fine, right? Right? (REDUCED STAMINA.)": "Chỉ là do cảm thấy hơi khó ở trong người (under the weather) một chút đéo thôi. Tôi chắc chắn sẽ đéo sao đâu, có đúng đéo? Đúng chứ? (ĐÃ BỊ GIẢM ĐI THỂ LỰC STAMINA.)",
  "Jacobsen": "Jacobsen",
  "And here we are!": "Và chúng ta hiện đã đến nơi rồi đây!",
  "Let me ask you something: has anybody else done half as much to pull shit together as we have?": "Hãy để tôi hỏi cậu một câu này: liệu có bất kỳ một người nào khác đã từng làm được dù chỉ là một nửa so với những nỗ lực cố gắng thu dọn mọi cái đống cứt hỗn độn (pull shit together) như những gì mà chúng ta đã và đang làm hay đéo?",
  "Test Tubes": "Những Chiếc Ống Nghiệm (Test Tubes)",
  "Mata": "Mata",
  "Do you want to use your original saved game, or delete it and continue normally?": "Bạn có muốn tiếp tục sử dụng lại file lưu trữ dữ liệu (saved game) ban đầu (original) của mình, hay là muốn xóa bỏ (delete) hoàn toàn nó đi và tiếp tục tiến hành quá trình khởi động bình thường (normally)?",
  "There's another.": "Đang có thêm một con nữa kìa.",
  "You might want to come home and lend a hand.": "Cậu có thể sẽ muốn quay trở về nhà (home) và giúp đỡ mọi người một tay đấy.",
  "TIP: [ul_radio_menu] to talk to Pastor William again.": "MẸO (TIP): Nhấn phím [ul_radio_menu] để có thể tiến hành nói chuyện lại một lần nữa với Mục Sư Pastor William.",
  "No, no. Of course not.": "Đéo, đéo. Đương nhiên là đéo rồi.",
  "Zeds in Southern Europe": "Zeds đã xuất hiện ở khu vực Nam Âu (Southern Europe)",
  "49 VIP Hadley Westen": "49 NHÂN VẬT QUAN TRỌNG (VIP) Hadley Westen",
  "Use this after your MAXIMUM STAMINA has been reduced.": "Hãy sử dụng loại vật phẩm này ngay sau khi lượng THỂ LỰC TỐI ĐA (MAXIMUM STAMINA) của bạn đã bị sụt giảm (reduced) một cách nghiêm trọng.",
  "Well, yeah I guess, but you couldn't really have known that.": "Chà, yeah tôi đoán là như vậy, nhưng cậu vốn dĩ đéo thể nào có thể biết trước được điều đó mà.",
  "Unlocks a Special Technique based on your Core Skills.": "Tiến hành Mở Khóa (Unlocks) một loại Kỹ Năng Kỹ Thuật Chiến Đấu Đặc Biệt (Special Technique) hoàn toàn mới dựa trên các loại Kỹ Năng Cốt Lõi (Core Skills) của bạn.",
  "New Commanding Officer: %1$s": "Sĩ Quan Chỉ Huy (Commanding Officer) Mới Được Bổ Nhiệm: %1$s",
  "You have already added Milo to this community once.": "Bạn đã từng thêm Milo vào trong cộng đồng (community) này một lần rồi.",
  "They are fucking murdering us out here!": "Bọn chúng đang tàn sát chết tiệt (fucking murdering) tất cả chúng tôi ở ngoài này!",
  "ATTITUDE: Grim": "THÁI ĐỘ (ATTITUDE): Cực Kỳ Tồi Tệ Khắc Nghiệt (Grim)",
  "Help": "Sự Trợ Giúp (Help)",
  "There’s a broken-down RV just outside of town. Looks like somebody just left it there. It’s in way better shape than most of the other big vehicles that are lying around.": "Có một chiếc xe RV đã bị hỏng hóc (broken-down) nằm ở ngay bên ngoài khu vực thị trấn. Trông có vẻ như ai đó đã bỏ lại nó ở đó. Tình trạng hiện tại của nó vẫn còn tốt hơn rất nhiều so với phần lớn các loại phương tiện (vehicles) cỡ lớn khác đang nằm rải rác ở khắp mọi nơi xung quanh đây.",
  "111 HERO Lyanna Carter": "111 ANH HÙNG (HERO) Lyanna Carter",
  "Whoever did it emptied their rucksacks and just took off.": "Bất cứ kẻ đéo nào đã làm ra cái chuyện này cũng đều đã dốc cạn toàn bộ đồ đạc (emptied) có ở bên trong những chiếc balo (rucksacks) của bọn họ và sau đó thì chỉ việc cao chạy xa bay (took off) đéo.",
  "Look at 'em go!": "Hãy nhìn bọn chúng bỏ chạy kìa!",
  "Hayden": "Hayden",
  "Christ no, I want to live. But, well since that's not looking too likely, I might as well be the guy you tell your grandkids about.": "Chúa ơi đéo, tôi hoàn toàn muốn được sống sót. Nhưng, chà, vì có vẻ như điều đó hiện tại sẽ đéo có khả năng (likely) xảy ra nữa rồi, vậy nên tôi có thể sẽ trở thành một gã mà cậu sẽ phải kể lại với những đứa cháu chắt (grandkids) của mình về tôi đấy.",
  "Pile of Vending Machine Snacks": "Cả Một Đống Đồ Ăn Vặt (Snacks) Được Lấy Ra Từ Một Chiếc Máy Bán Hàng Tự Động (Vending Machine)",
  "Only slightly damaged.": "Chỉ bị hư hại một chút đéo đáng kể (slightly damaged).",
  "95 GENERIC Aaron Felder": "95 CHUNG (GENERIC) Aaron Felder",
  "All right, we've got a strong signal. I think it's another beacon.": "Được rồi, chúng tôi hiện đang bắt được một tín hiệu (signal) cực kỳ mạnh mẽ. Tôi nghĩ rằng đó là một thiết bị tín hiệu đèn hiệu (beacon) khác.",
  "Bet I can jimmy this bad boy.": "Cá là tôi hoàn toàn có thể dễ dàng cạy mở (jimmy) được thứ tồi tệ (bad boy) này.",
  "STFU PLZ4ME KTHXBAI.": "STFU PLZ4ME KTHXBAI.",
  "And we had all these nice empty bottles just sitting here, waiting to be turned into firebombs.": "Và chúng ta hiện đang có tất cả những chiếc vỏ chai (bottles) rỗng tuyệt đẹp này nằm la liệt ở đây, đang chờ đợi để được biến thành những quả bom lửa (firebombs).",
  "Andie": "Andie",
  "Shit! We just lost a barricade!": "Chết tiệt thật (Shit)! Chúng ta vừa mới bị mất đi một cái rào chắn (barricade) cmnr!",
  "Too many people around here don't know how to use a gun. We gotta fix that.": "Đang có quá nhiều người ở quanh khu vực này đéo hề biết cách làm thế nào để sử dụng một khẩu súng (gun). Chúng ta cần phải nhanh chóng khắc phục (fix) được cái vấn đề đó.",
  "Allergies? Do I look like the pharmaceutical aisle at Drug Barn?": "Các triệu chứng dị ứng (Allergies) ư? Trông tôi có giống hệt như một cái quầy (aisle) bán dược phẩm (pharmaceutical) tại một cửa hàng thuốc Drug Barn đéo?",
  "It's a possibility.": "Đó cũng là một khả năng (possibility) hoàn toàn có thể xảy ra đấy.",
  "Cracked ribs. This should heal up in a while. (Health penalty.)": "Bị rạn nứt xương sườn (Cracked ribs). Thứ này sẽ phải mất một khoảng thời gian khá lâu mới có thể hoàn toàn bình phục (heal up) trở lại được. (Hình phạt bị trừ đi Máu Health penalty.)",
  "SFX Volume": "Âm Lượng (Volume) Các Hiệu Ứng Âm Thanh (SFX)",
  "Anybody in here?": "Có ai đang ở trong này đéo?",
  "Research priorities are also set at the Ops Center, opening up advanced options at the other Facilities.": "Các ưu tiên dành cho công việc Nghiên Cứu (Research priorities) cũng có thể được thiết lập ngay tại Trung Tâm Điều Hành (Ops Center), qua đó sẽ giúp mở khóa (opening up) thêm được rất nhiều những tùy chọn nâng cao (advanced options) cực kỳ đắt giá tại các Cơ Sở (Facilities) khác.",
  "That's all for now.": "Đó là tất cả những gì mà chúng ta cần phải làm vào lúc này.",
  "You're wearing yourself out!": "Cậu đang tự khiến cho bản thân mình trở nên vô cùng kiệt sức (wearing yourself out) đấy!",
  "No, but with this dead man's switch in my hand, you don't want me getting up close and personal with any zeds.": "Đéo, nhưng với cái nút công tắc của một tên tử tù (dead man's switch) đang nằm ở trong tay của tôi, thì cậu sẽ đéo muốn để tôi tiến lại quá gần (up close) và chạm trán trực tiếp (personal) với bất kỳ một con zeds nào đâu.",
  "Haggling always succeeds when you invoke your boss.": "Việc mặc cả trả giá (Haggling) sẽ luôn luôn thành công mỹ mãn mỗi khi bạn nhắc đến (invoke) người sếp (boss) của mình.",
  "Kill a Juggernaut with a melee weapon.": "Tiêu diệt một con Juggernaut bằng một loại vũ khí cận chiến (melee weapon).",
  "44 VIP Madison Grant": "44 NHÂN VẬT QUAN TRỌNG (VIP) Madison Grant",
  "We're fighting for survival here. If you can't stay on point, then I can't support your operation.": "Chúng ta hiện đang phải chiến đấu một cách điên cuồng chỉ để được sống sót (survival) ở cái nơi này. Nếu như cậu đéo thể nào giữ được sự tập trung cao độ (stay on point) vào công việc, vậy thì tôi sẽ đéo thể nào tiếp tục hỗ trợ cho chiến dịch (operation) của cậu được nữa.",
  "Check your nine o'clock!": "Hãy mau kiểm tra ngay hướng chín giờ (nine o'clock) của cậu kìa!",
  "It's always hard to lose someone. - %1$s": "Luôn luôn là một điều vô cùng khó khăn (hard) mỗi khi phải đánh mất đi một ai đó (lose someone). - %1$s",
  "You keep shooting like that, there's gonna be a hundred zombies on our ass.": "Nếu cậu cứ tiếp tục xả súng (shooting) bừa bãi như thế, thì chẳng mấy chốc sẽ có cả hàng trăm con zombies chạy đến và cắn thẳng vào mông (ass) của chúng ta mất.",
  "I like the looks of that.": "Tôi rất thích cái vẻ bề ngoài của cái thứ đó đấy.",
  "I'm at Bogatz's vehicle. Looks like he got swarmed. Can't tell if he got out alive, or ... otherwise.": "Tôi hiện đang có mặt ở vị trí chiếc xe của Bogatz. Trông có vẻ như anh ta đã bị lũ zombie bao vây tấn công (swarmed) tơi bời. Đéo thể nào biết chắc được liệu anh ta đã có thể trốn thoát ra ngoài khi vẫn còn sống sót (alive) đéo, hay là... đã có một kết cục vô cùng tồi tệ nào đó khác (otherwise).",
  "Hey hey!": "Này này (Hey hey)!",
  "And now I'm out.": "Và bây giờ thì tôi đã hoàn toàn cạn kiệt đạn dược mất rồi (out).",
  "I'm heading out now.": "Hiện tại tôi đang chuẩn bị lên đường đi ra ngoài (heading out) đây.",
  "This was a total bust. There's nothing useful here.": "Thực sự là một sự lãng phí công sức (bust) hoàn toàn. Đéo hề có bất kỳ một thứ đéo gì hữu ích (useful) ở cái nơi này cả.",
  "Hello? Hello? Is anybody hearing me? If you're receiving this, I need some help!": "Xin chào? Xin chào? Có bất cứ ai có thể nghe thấy tôi nói đéo? Nếu như các người có thể nhận được đoạn tín hiệu (receiving) vô tuyến này, tôi đang thực sự cần phải có được một vài sự giúp đỡ!",
  "Doghouse - Drone Strike": "Doghouse - Cuộc Không Kích Bằng Máy Bay Không Người Lái (Drone Strike)",
  "Gotta get out of here!": "Phải nhanh chóng trốn thoát (get out) ra khỏi cái nơi này thôi!",
  "Ashby": "Ashby",
  "Get these things off me!": "Hãy mau ném những cái thứ chết tiệt này ra khỏi người tôi đi (Get these things off)!",
  "Hey! Are you here for us?": "Này! Cậu đến đây là để cứu vớt chúng tôi có phải đéo?",
  "Hang on, I've got a transmission coming in... I think.": "Khoan đã nào, tôi vừa mới nhận được một đoạn tín hiệu truyền tải (transmission) truyền tới đây... Tôi nghĩ là vậy.",
  "Shit, we lost somebody.": "Chết tiệt thật (Shit), chúng ta vừa mới bị mất đi một người cmnr.",
  "Uh, I find you to be against regulation and I would appreciate it if you left.": "Uh, tôi nhận thấy rằng cậu đang cố tình làm trái với các quy định (regulation) của chúng tôi và tôi sẽ cực kỳ đánh giá cao (appreciate) điều đó nếu như cậu chịu rời khỏi (left) đây ngay lập tức.",
  "Hey, I'm really sorry about your people.": "Này, tôi thực sự rất lấy làm tiếc (sorry) về những chuyện đã xảy ra đối với những người đồng đội (people) của cậu.",
  "In my experience, most of 'em kinda suck at the whole \"serve and protect\" thing.": "Theo như kinh nghiệm (experience) cá nhân của tôi thì, phần lớn bọn chúng đều làm cực kỳ tệ hại (suck) ở cái khoảng \"phục vụ (serve) và bảo vệ (protect)\" mà bọn chúng vẫn luôn mồm tự hào.",
  "I don't know about you, but I know a good night's sleep in a real bed always gives my energy level a boost.": "Tôi đéo biết cậu thì sẽ như thế nào, nhưng tôi biết rất rõ rằng một giấc ngủ (sleep) ngon lành vào ban đêm trên một chiếc giường (bed) thực thụ sẽ luôn luôn giúp cho mức năng lượng (energy) của tôi được gia tăng (boost) lên một cách đáng kể.",
  "I'll get you the location.": "Tôi sẽ nhanh chóng gửi cho cậu tọa độ vị trí (location) của cái nơi đó.",
  "It's a good thing that ended when it did.": "Thật là một điều vô cùng tốt đẹp (good thing) khi mà mọi chuyện đã hoàn toàn kết thúc (ended) đúng như cái lúc mà nó đã từng xảy ra.",
  "0%": "0%",
  "Not my fault everybody else screwed up.": "Đó đéo phải là lỗi (fault) của tôi khi mà tất cả mọi người khác đều đã làm hỏng bét (screwed up) mọi chuyện.",
  "Of course, an army mistake gets people fucking killed. So how about you turn it around, soldier boys?": "Đương nhiên rồi, một sai lầm (mistake) ngu ngốc của quân đội (army) sẽ trực tiếp khiến cho mọi người phải mất đi mạng sống chết tiệt (fucking killed). Vậy thì tại sao các người lại đéo chịu quay trở lại (turn it around) đi hả, những chàng trai binh lính (soldier boys) dũng cảm?",
  "Your equipped gun is fully loaded.": "Khẩu súng (gun) mà bạn đang trang bị (equipped) hiện đã được nạp đầy đủ đạn (fully loaded).",
  "Slow and steady gets us not eaten. Take your time.": "Chậm rãi (Slow) và cực kỳ chắc chắn (steady) sẽ có thể giúp cho chúng ta đéo bị bọn chúng ăn thịt (eaten). Cứ thong thả (Take your time) mà làm đi nhé.",
  "Control Configuration": "Cấu Hình (Configuration) Điều Khiển (Control)",
  "HELP REFUGEE. Gather supplies and return to base.": "GIÚP ĐỠ CHO NHỮNG NGƯỜI TỊ NẠN (HELP REFUGEE). Thu thập (Gather) các loại vật tư hàng hóa tiếp tế (supplies) và nhanh chóng quay trở lại căn cứ (base).",
  "SitRep: Atlanta": "Báo Cáo Tình Hình (SitRep): Atlanta",
  "Okay, I'm here now.": "Được rồi, hiện tại tôi đã có mặt ở đây cmnr.",
  "Miranda": "Miranda",
  "Carry Painkillers with you.": "Nên mang theo người Thuốc Giảm Đau (Painkillers) cùng với bạn.",
  "Come on, let's go make some noise.": "Thôi nào, chúng ta hãy cùng nhau đi tạo ra một vài tiếng ồn (noise) nào.",
  "The kid you're after, Hadley Westen ... his family owns the biggest food shipping network in the region.": "Cái thằng nhóc (kid) mà cậu đang cố gắng đi săn lùng (after), Hadley Westen... gia đình của nó hiện đang sở hữu một trong những mạng lưới vận chuyển (shipping network) lương thực (food) lớn nhất ở trong toàn bộ khu vực (region) này đấy.",
  "God, that fucking thing reeks!": "Chúa ơi, cái thứ chết tiệt (fucking) đó bốc mùi hôi thối kinh tởm quá (reeks)!",
  "No trouble like family trouble, is there?": "Đéo có bất kỳ một loại rắc rối (trouble) đéo nào có thể so sánh được với những rắc rối ở trong gia đình (family), có đúng đéo?",
  "Experimental close assault weapon from CLEO.": "Một loại vũ khí tiến công cận chiến (close assault) đang trong giai đoạn thử nghiệm (Experimental) được gửi đến từ CLEO."
};

const file = 'output/languages/chunks/btxt_chunk_202.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_202.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk202[r.sourceText]) {
    r.translatedText = chunk202[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 202 successfully!');
