const fs = require('fs');
const chunk168 = {
  "Alright, sounds good. We'll meet at a neutral location.": "Được rồi, nghe hay đấy. Chúng开展ta sẽ gặp nhau ở một địa điểm trung lập.",
  "I understand the difficulty, Sheriff, but I don't know what you expect me to do about it.": "Tôi hiểu sự khó khăn này, Cảnh sát trưởng (Sheriff), nhưng tôi đéo biết anh muốn tôi phải làm gì về chuyện đó nữa.",
  "Please forgive me!": "Xin hãy tha thứ cho tôi!",
  "Nimble": "Nhanh Nhẹn (Nimble)",
  "Glad we got away from that.": "Mừng là chúng ta đã thoát khỏi chuyện đó.",
  "Nice of you to see things my way.": "Thật tốt khi cậu có thể nhìn nhận mọi việc theo cách của tôi.",
  "Almost out.": "Gần ra ngoài rồi.",
  "Juggernauts shouldn't even exist.": "Bọn Juggernauts thậm chí đéo nên tồn tại trên đời này.",
  "The Wilkersons won't be happy.": "Gia đình Wilkersons sẽ đéo vui đâu.",
  "Could be they ran out of gas. If you don't see any reserve tanks around, you might have to siphon some vehicles to get enough.": "Có thể là chúng đã hết xăng. Nếu cậu đéo thấy bất kỳ bình xăng dự phòng nào xung quanh, cậu có thể phải hút xăng từ một vài chiếc xe để có đủ số lượng cần thiết.",
  "%1$s and Co. barely made it though that last attack. - %2$s": "%1$s và những người khác vừa mới vượt qua được cuộc tấn công cuối cùng đó. - %2$s",
  "Ehrenburg": "Ehrenburg",
  "You can take a few things from the emergency locker over there. We try to ration out supplies every day.": "Cậu có thể lấy một vài thứ từ tủ đồ khẩn cấp đằng kia. Chúng tôi cố gắng phân phát khẩu phần nhu yếu phẩm mỗi ngày.",
  "Had to get out there and find something to eat, but it's too hard trying to survive solo.": "Đã phải ra ngoài đó và tìm thứ gì đó để ăn, nhưng việc cố gắng sinh tồn một mình là quá khó khăn.",
  "Edwin": "Edwin",
  "Good shit right there.": "Hàng ngon ngay đây rồi.",
  "Materials": "Vật Liệu (Materials)",
  "Courtney": "Courtney",
  "There's a lot of ground to cover, though. Somebody ought to put a bell on that boy.": "Tuy nhiên, còn rất nhiều khu vực phải lùng sục. Ai đó nên đeo một cái chuông cho cậu bé đó đi.",
  "No zombies over there.": "Đéo có con zombies nào ở đằng kia cả.",
  "A chance to make a difference.": "Một cơ hội để tạo nên sự khác biệt.",
  "Some people have all the luck.": "Một số người có được mọi sự may mắn trên đời.",
  "You looking for some food?": "Cậu đang tìm chút thức ăn hả?",
  "Trait Discovered: TMI": "Đã Khám Phá Được Đặc Điểm (Trait): TMI (Nói Quá Nhiều)",
  "No, goddammit! Cars are too dangerous, just leave it!": "Đéo, mẹ kiếp! Những chiếc xe đó quá nguy hiểm, cứ mặc kệ nó đi!",
  "Hot Dogs": "Xúc Xích (Hot Dogs)",
  "We found a backpack containing the belongings of a fallen ally and brought them home. - %1$s.": "Chúng tôi đã tìm thấy một chiếc balo chứa đồ đạc của một người đồng đội đã ngã xuống và mang chúng về nhà. - %1$s.",
  "Offer Shelter to Survivors": "Cung Cấp Nơi Trú Ẩn (Shelter) cho Những Người Sống Sót",
  "I really don't want to do this....": "Tôi thực sự đéo muốn làm điều này chút nào....",
  "We need to build up our food stockpile, A-S-A-P.": "Chúng ta cần phải xây dựng lại kho dự trữ thức ăn của mình, C-À-N-G-S-Ớ-M-C-À-N-G-T-Ố-T (A-S-A-P).",
  "I hate to see the old girl like this.": "Tôi ghét phải nhìn thấy cô gái già này trong tình trạng thế này.",
  "Natalie": "Natalie",
  "Search the Location Thoroughly": "Tìm Kiếm Địa Điểm Này Một Cách Kỹ Lưỡng",
  "A hero has been sighted!": "Đã nhìn thấy một vị anh hùng!",
  "Cots and Futons": "Giường Xếp và Đệm Futon (Cots and Futons)",
  "No thanks to you, now we've got to go and do it all over again.": "Đéo có cậu giúp, bây giờ chúng ta lại phải đi và làm lại toàn bộ mọi thứ.",
  "I think I've seen just about enough of this valley. Let's get the hell out of here.": "Tôi nghĩ tôi đã nhìn thấy quá đủ về cái thung lũng này rồi. Hãy cút khỏi nơi quỷ quái này thôi.",
  "Chapman": "Chapman",
  "Mary": "Mary",
  "%s Level Up": "%s Lên Cấp (Level Up)",
  "Resources Lost": "Đã Mất Tài Nguyên (Resources Lost)",
  "Gained +3 Ammo.": "Đã thu được +3 Đạn Dược (Ammo).",
  "My hands are greased lightning. I'm faster while aiming, I reload quicker, and I can lock in on a zombie's head from even farther away. (Special Technique: Focus Aim)": "Đôi tay tôi nhanh như chớp. Tôi ngắm bắn nhanh hơn, nạp đạn nhanh hơn, và tôi có thể khóa mục tiêu vào đầu một con zombie từ khoảng cách xa hơn nữa. (Kỹ Năng Đặc Biệt: Ngắm Bắn Tập Trung - Focus Aim)",
  "We've got some construction problems.": "Chúng ta đang gặp một số vấn đề về việc xây dựng.",
  "SMG: 93 Raffica": "Súng Tiểu Liên (SMG): 93 Raffica",
  "I know I might not make it.": "Tôi biết tôi có thể sẽ đéo qua khỏi.",
  "The house isn't too far from here. I'll show you where to go.": "Ngôi nhà đéo quá xa nơi này đâu. Tôi sẽ chỉ cho cậu đường đi.",
  "Command Center: No Survivors Found": "Trung Tâm Chỉ Huy (Command Center): Đéo Tìm Thấy Người Sống Sót Nào",
  "Whatever. I can't have you beating it to death, or blowing its head off.": "Sao cũng được. Tôi đéo thể để cậu đánh nó đến chết, hoặc bắn bay đầu nó được.",
  "Jones": "Jones",
  "Lincoln": "Lincoln",
  "SURVIVAL TACTICS: Rucksack": "CHIẾN THUẬT SINH TỒN (SURVIVAL TACTICS): Balo Chứa Đồ (Rucksack)",
  "Yeah, this place is a ghost town.": "Ừ, nơi này đúng là một thị trấn ma (ghost town).",
  "Sometimes you have to appreciate the small victories.": "Đôi khi cậu phải biết trân trọng những chiến thắng nhỏ bé.",
  "Looks like we might have a situation on our hands.": "Có vẻ như chúng ta có thể đang gặp một tình huống rắc rối đây.",
  "Who should I send?": "Tôi nên cử ai đi đây?",
  "We can't just let the zombies infest these buildings.": "Chúng ta đéo thể cứ để bọn zombies lây nhiễm (infest) vào những tòa nhà này được.",
  "How's it looking back there?": "Tình hình phía sau đó trông thế nào rồi?",
  "We'll see you soon.": "Chúng tôi sẽ sớm gặp lại cậu.",
  "Resupply at Home": "Tiếp Tế (Resupply) tại Căn Cứ (Home)",
  "So, you used me.": "Vậy là, cậu đã lợi dụng tôi.",
  "Leave me behind, sir. I'll hold 'em off.": "Cứ bỏ tôi lại đi, thưa sếp. Tôi sẽ cầm chân chúng.",
  "We have a medivac down the road. We're looking for Doctor Julene Horn. Thomas Horn's wife?": "Chúng tôi có một máy bay sơ tán y tế (medivac) đang ở dưới đường. Chúng tôi đang tìm Bác sĩ Julene Horn. Vợ của Thomas Horn?",
  "Barroom Brawler": "Kẻ Hay Gây Gổ Quán Rượu (Barroom Brawler)",
  "Hey, I'm not greedy. You help me out and half of anything we get is yours.": "Này, tôi đéo tham lam đâu. Cậu giúp tôi và một nửa số đồ chúng ta kiếm được sẽ là của cậu.",
  "There's nobody up there buddy....": "Đéo có ai ở trên đó đâu anh bạn....",
  "I lost contact with a friend of mine.": "Tôi đã mất liên lạc với một người bạn của mình.",
  "You see them? Over there on the left?": "Cậu có thấy chúng đéo? Ở đằng kia bên trái kìa?",
  "This just gets better and better.": "Mọi chuyện ngày càng trở nên tồi tệ hơn đấy.",
  "Go scout for a larger place to call home.": "Đi trinh sát tìm một nơi rộng rãi hơn để gọi là nhà đi.",
  "No, no we should have it covered.": "Đéo, đéo chúng ta nên kiểm soát được tình hình.",
  "Ray says he's got something for me. Wonder what it is. - %1$s": "Ray nói ông ấy có thứ gì đó cho tôi. Tự hỏi đéo biết nó là cái gì. - %1$s",
  "I dunno, I figured if he had a radio, there must be somebody on the other end.": "Tôi đéo biết nữa, tôi đã nghĩ rằng nếu anh ta có radio, chắc chắn phải có ai đó ở đầu dây bên kia.",
  "+28%": "+28%",
  "Ain't no time like the present!": "Đéo có lúc nào thích hợp bằng hiện tại đâu!",
  "Uh, this is so corporate.": "Ờ, nghe đậm chất công ty (corporate) thật.",
  "That means cars? Bad, unless you're getting the hell out of there in a hurry.": "Điều đó có nghĩa là xe cộ ư? Tồi tệ đấy, trừ khi cậu đang định vội vã cút khỏi nơi đó.",
  "Sergeant. I gave you an order!": "Trung sĩ. Tôi đã ra lệnh cho cậu rồi cơ mà!",
  "No matter how fucked up things get, we have to plan for the coming season. (Good with plants.)": "Dù mọi chuyện có tồi tệ đến mức nào đi chăng nữa, chúng ta vẫn phải lên kế hoạch cho mùa vụ sắp tới. (Giỏi việc trồng cây.)",
  "XP BOOST: Leadership": "TĂNG XP: Kỹ năng Lãnh đạo (Leadership)",
  "Fully Explore this Location": "Khám Phá Toàn Bộ (Fully Explore) Địa Điểm Này",
  "Roger that, sir.": "Đã rõ, thưa sếp.",
  "%2$s knows what she did. - %1$s": "%2$s biết rõ những gì cô ta đã làm. - %1$s",
  "Available Facilities:": "Các Cơ Sở (Facilities) Đã Có Sẵn:",
  "Scouts said they found them with grass stuffed in their mouths. Starved. Bad way to go.": "Những người lính trinh sát nói rằng họ tìm thấy chúng với cỏ nhét đầy trong miệng. Bị chết đói. Thật là một cái kết tồi tệ.",
  "The hummus is for everybody.": "Hũ hummus là dành cho tất cả mọi người.",
  "Isaac": "Isaac",
  "Dedicated Work Area": "Khu Vực Làm Việc Chuyên Dụng",
  "Now that Ed is dead, we no longer have a reason to fetch the Doc.": "Bây giờ Ed đã chết rồi, chúng ta đéo còn lý do gì để phải rước Doc về nữa.",
  "And time's not exactly on our side, if you know what I mean.": "Và thời gian đéo thực sự đứng về phía chúng ta, nếu cậu hiểu ý tôi.",
  "68 GENERIC Dick Calvert": "68 CHUNG (GENERIC) Dick Calvert",
  "If it doesn't come in the form of a folksy saying, Janet doesn't trust it.": "Nếu nó đéo xuất hiện dưới dạng một câu tục ngữ dân gian, Janet sẽ đéo tin đâu.",
  "Everybody's here 'cause I went out and found them, little brother! So they--": "Mọi người có mặt ở đây là do tao đã ra ngoài kia và tìm thấy họ đấy, thằng em trai à! Vì vậy họ--",
  "Rucksack's full, so I'm headin' back.": "Balo (Rucksack) đầy rồi, nên tôi đang quay về đây.",
  "Thought he was gonna pop me one right there.": "Đã nghĩ là hắn sẽ bắn tôi một phát ngay tại đó cơ đấy.",
  "Requires CLASS OF FRESHMAN ENGLISH STUDENTS.": "Yêu cầu phải có LỚP HỌC SINH VIÊN TIẾNG ANH NĂM NHẤT (CLASS OF FRESHMAN ENGLISH STUDENTS).",
  "Generators would be pretty straightforward, or we could try to find a place with solar panels.": "Máy phát điện (Generators) sẽ khá dễ tìm, hoặc chúng ta có thể cố gắng tìm một nơi nào đó có các tấm pin năng lượng mặt trời.",
  "Larwin": "Larwin",
  "Appreciates a good gun.": "Biết đánh giá cao một khẩu súng tốt.",
  "So you're saying those things are zombies?": "Vậy ý cậu là những thứ đó là bọn zombies hả?"
};

const file = 'output/languages/chunks/btxt_chunk_168.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_168.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk168[r.sourceText]) {
    r.translatedText = chunk168[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 168 successfully!');
