const fs = require('fs');
const chunk112 = {
  "How're they doing?": "Họ sao rồi?",
  "Just try not to fuck up the next one, all right? Doghouse out.": "Cố gắng đừng làm hỏng cái tiếp theo, rõ chưa? Doghouse kết thúc liên lạc.",
  "You're right. I'm not going to destroy an entire city on the word of a crazy person. I'll take you there now.": "Cậu nói đúng. Tôi sẽ không phá hủy cả một thành phố chỉ vì lời nói của một kẻ điên. Tôi sẽ đưa cậu đến đó ngay.",
  "This room is in disarray. We'll need to fix it up before we can use it.": "Căn phòng này thật lộn xộn. Chúng ta sẽ cần phải dọn dẹp và sửa chữa nó trước khi có thể sử dụng.",
  "A Powerhouse wades into the middle of 'em and mixes it up hand-to-hand.": "Một Chiến Binh Cận Chiến (Powerhouse) sẽ xông thẳng vào giữa bọn chúng và tả xung hữu đột bằng tay không.",
  "Looks like a horde of zeds.": "Trông giống như một bầy zombie (horde) vậy.",
  "You probably ought to lock me up somewhere, right? I don't want to turn in the middle of the base and then start eating people.": "Có lẽ anh nên nhốt tôi lại đâu đó đi, phải không? Tôi không muốn bị biến đổi giữa căn cứ rồi bắt đầu ăn thịt mọi người đâu.",
  "Oh, man, this is bad. I think I pissed off a horde or something.": "Ôi, chết tiệt, tệ rồi đây. Tôi nghĩ tôi đã chọc giận một bầy horde hay gì đó rồi.",
  "Shot Eli": "Đã bắn Eli",
  "Right. End of the world, you just blew into town and could somebody point you to a place to stay?": "Phải rồi. Tận thế tới nơi, cậu vừa dạt vào thị trấn và muốn ai đó chỉ cho cậu chỗ nào đó để ở sao?",
  "Marshall Municipal Courthouse is a safe place. We have food, security, and shelter.": "Tòa án Thành phố Marshall là một nơi an toàn. Chúng tôi có thức ăn, an ninh và nơi trú ẩn.",
  "Assault Rifle: L85A1": "Súng trường tấn công: L85A1",
  "Marchenko": "Marchenko",
  "Oh man, if you weren't here, we'd have been fucked. Royally.": "Ôi bạn ơi, nếu không có cậu ở đây, chúng tôi tiêu đời rồi. Chắc chắn luôn.",
  "Made it.": "Đến nơi rồi.",
  "Yeah, okay, maybe leave that part out.": "Ừ, được rồi, có lẽ nên bỏ qua phần đó đi.",
  "Hope we aren't planning any big construction projects.": "Hy vọng chúng ta không đang lên kế hoạch cho bất kỳ dự án xây dựng lớn nào.",
  "Dietrich": "Dietrich",
  "We found a backpack containing gathered resources and brought them home. - %1$s.": "Chúng tôi đã tìm thấy một chiếc ba lô chứa tài nguyên thu thập được và mang chúng về nhà. - %1$s.",
  "Ain't got the room.": "Không còn chỗ trống.",
  "Larson": "Larson",
  "Quentin wants me to find out about Becca's past. Sheriff Parsons seemed to know something; maybe I should start with him. - %1$s": "Quentin muốn tôi tìm hiểu về quá khứ của Becca. Cảnh sát trưởng Parsons có vẻ biết gì đó; có lẽ tôi nên bắt đầu với ông ấy. - %1$s",
  "Mulligan": "Mulligan",
  "Maher": "Maher",
  "I've done what I could to raise spirits.": "Tôi đã làm những gì có thể để vực dậy tinh thần mọi người.",
  "I knew this day would come for a long time. It's in the Bible, people!": "Tôi đã biết ngày này sẽ đến từ lâu rồi. Có chép trong Kinh thánh đó, mọi người!",
  "Pat": "Pat",
  "Maybe if we weren't down to an expired bottle of baby aspirin and a case of cough syrup, we wouldn't have so many sick people.": "Có lẽ nếu chúng ta không chỉ còn lại một lọ aspirin cho trẻ em đã hết hạn và một hộp siro ho, thì chúng ta đã không có nhiều người ốm đến vậy.",
  "74 GENERIC Omar Magnusson": "74 GENERIC Omar Magnusson",
  "I'm glad.": "Tôi rất vui.",
  "PERSONAL SKILL. Come on, let's make a deal.": "KỸ NĂNG CÁ NHÂN. Thôi nào, hãy cùng thỏa thuận nhé.",
  "TIP: Radio home using [xi_dpad_down] (D-pad) to relocate your home base.": "MẸO: Gọi radio về nhà bằng cách dùng [xi_dpad_down] (D-pad) để dời Căn cứ của bạn.",
  "Increased space for resources.": "Tăng thêm không gian chứa tài nguyên.",
  "Lock and load, boys! Company's here!": "Lên đạn đi các chàng trai! Có khách tới rồi đây!",
  "One of ours has wandered off. I could use a hand finding them.": "Một người của chúng ta đã đi lạc. Tôi cần người phụ một tay tìm họ.",
  "Sounds like the Army is stepping things up.... -%1$s": "Có vẻ như Quân đội đang đẩy mạnh mọi việc.... -%1$s",
  "All set.": "Mọi thứ đã sẵn sàng.",
  "96 STORY Karen Tolbert": "96 STORY Karen Tolbert",
  "Waypoint (%s)": "Điểm Đánh Dấu (Waypoint) (%s)",
  "I'm just here to make sure the trade goes nice and smooth.": "Tôi chỉ ở đây để đảm bảo cuộc giao dịch diễn ra êm đẹp và suôn sẻ thôi.",
  "Completed a survey activity.": "Đã hoàn thành một hoạt động khảo sát.",
  "Alright, we're all stressed, but we can't afford to be at each other's throats, okay? So you start playing nice, or you're out on your ass.": "Được rồi, tất cả chúng ta đều đang căng thẳng, nhưng chúng ta không thể cứ cấu xé lẫn nhau mãi được, hiểu không? Cho nên hãy bắt đầu cư xử tử tế đi, nếu không cậu sẽ bị tống cổ ra ngoài.",
  "Delay your decision. An attempt might be made without you.": "Trì hoãn quyết định của bạn. Một nỗ lực có thể được thực hiện mà không cần bạn.",
  "You got something more important to do? Okay then.": "Cậu có việc gì quan trọng hơn để làm sao? Vậy cũng được.",
  "Hey, this is Sasquatch again, in case you were wondering.": "Này, lại là Sasquatch đây, phòng trường hợp cậu đang thắc mắc.",
  "You just invited the neighbors over.": "Cậu vừa mới mời lũ hàng xóm sang chơi đấy.",
  "Supplies must be brought HOME for distribution.": "Nhu yếu phẩm phải được mang VỀ NHÀ để phân phát.",
  "Do you want to load this save, overwrite the save, or choose another storage device?": "Bạn muốn tải bản lưu (save) này, ghi đè lên bản lưu, hay chọn một thiết bị lưu trữ khác?",
  "Timothy Hall is dead": "Timothy Hall đã chết",
  "The one that's completely full of zeds. Perfect.": "Cái nơi mà ngập tràn lũ zed ấy. Hoàn hảo thật.",
  "We lost somebody back there. We could use your help finding them.": "Chúng tôi đã lạc mất một người ở đó. Chúng tôi cần cậu giúp tìm người đó.",
  "That's the last of the food.": "Đó là số thức ăn cuối cùng.",
  "Yeah. Seems like we just can't catch a break.": "Đúng vậy. Có vẻ như chúng ta không thể nghỉ ngơi được chút nào.",
  "Hard at work, or hardly working": "Làm việc chăm chỉ, hay là chả làm gì cả",
  "The pinnacle of precision M14 evolution to date. this version is custom to the Red Talon group.": "Đỉnh cao của sự tiến hóa về độ chính xác của súng M14 cho đến nay. Phiên bản này được thiết kế riêng cho nhóm Red Talon.",
  "Warren": "Warren",
  "We've added a weapons-training course to keep our proficiency with firearms up to par.": "Chúng ta đã thêm một khóa huấn luyện sử dụng vũ khí để giữ cho kỹ năng dùng súng luôn ở mức tốt.",
  "You can blame that on everybody being at each others' throats. Not all those injuries are from zombies.": "Cậu có thể đổ lỗi điều đó cho việc mọi người cứ cắn xé lẫn nhau. Không phải tất cả những vết thương đó đều do zombie gây ra đâu.",
  "You've leveled up a Skill! Press D-pad [xi_dpad_up] to open your Journal and view your Skills and Abilities on the Survivor page.": "Bạn vừa tăng cấp một Kỹ Năng! Nhấn D-pad [xi_dpad_up] để mở Nhật ký (Journal) và xem Kỹ Năng cũng như Khả Năng của bạn trên trang Người Sống Sót.",
  "Soterios": "Soterios",
  "A greenhouse will improve our crop yields.": "Một nhà kính (greenhouse) sẽ giúp cải thiện năng suất cây trồng của chúng ta.",
  "Hey, check your map again.": "Này, kiểm tra lại bản đồ của cậu đi.",
  "Hey, hey. Guess what I had for breakfast today? Fucking tree bark.": "Này, này. Đoán xem hôm nay tôi ăn gì cho bữa sáng nào? Vỏ cây chết tiệt đấy.",
  "So you'd rather have him running around unsupervised?": "Vậy là cô thà để ông ta chạy rông mà không có ai giám sát sao?",
  "If you're hearing this, we could use some help.": "Nếu cậu nghe thấy tin này, chúng tôi cần được giúp đỡ.",
  "I can't go home. I can't! That last supply run I... I got bit.": "Tôi không thể về nhà. Tôi không thể! Lần đi tìm đồ tiếp tế vừa rồi tôi... tôi đã bị cắn.",
  "Could you grab a car or something?": "Cậu có thể lấy một chiếc xe hay gì đó được không?",
  "How are you doing? Getting enough to eat?": "Mọi chuyện sao rồi? Có đủ đồ ăn không?",
  "You want to confess that we killed her father and stole his radio before they patch you up?": "Cậu muốn thú nhận rằng chúng ta đã giết cha cô ấy và đánh cắp bộ đàm của ông ta trước khi họ băng bó cho cậu sao?",
  "Parking Space": "Chỗ Đậu Xe",
  "Somebody out there has to have some food. I'm going to find them. - %1$s": "Chắc chắn ai đó ngoài kia phải có chút thức ăn. Tôi sẽ đi tìm họ. - %1$s",
  "Aw shit. Zombies heard the car, better move quick.": "Ôi khỉ thật. Bọn zombie đã nghe thấy tiếng xe rồi, tốt nhất là nên di chuyển nhanh lên.",
  "Small extra damage. No map indicators.": "Thêm sát thương nhỏ. Không có chỉ báo trên bản đồ.",
  "%1$s has lost track of the Juggernaut. We missed a chance to bring down the zombie population and delay the next siege.": "%1$s đã mất dấu con Juggernaut. Chúng ta đã bỏ lỡ cơ hội làm giảm số lượng zombie và trì hoãn cuộc bao vây tiếp theo.",
  "Close Map": "Đóng Bản Đồ",
  "Keep your weapon ready. This is going down any second.": "Giữ sẵn vũ khí của cậu đi. Chuyện này sẽ kết thúc trong tích tắc.",
  "I'd say this place is clear.": "Tôi có thể nói là nơi này đã an toàn.",
  "Start Game": "Bắt Đầu Trò Chơi",
  "Jesse": "Jesse",
  "Use [ui_scroll_down] to cycle between Mission Opportunities.": "Sử dụng [ui_scroll_down] để chuyển đổi giữa các Nhiệm vụ Có sẵn.",
  "It's not exactly a core survival skill, but I am pretty good with a ukulele.": "Đó không hẳn là một kỹ năng sinh tồn cốt lõi, nhưng tôi chơi đàn ukulele khá giỏi đấy.",
  "We need to sort out our shit, ASAP.": "Chúng ta cần phải giải quyết đống lộn xộn của mình, NGAY LẬP TỨC.",
  "Andrew": "Andrew",
  "Heeeeere little zombie. Come on. Uncle Mickey wants to blow your fucking brains out.": "Đếếếến đây nào zombie nhỏ. Thôi nào. Chú Mickey muốn thổi bay cái bộ脑 khốn kiếp của cưng đấy.",
  "137 NPC Mercenary": "137 Lính Đánh Thuê NPC",
  "We've had a sighting of one of our missing people.": "Chúng tôi vừa nhìn thấy một trong những người mất tích của mình.",
  "No, I'm feeling good already.": "Không, tôi đã cảm thấy tốt rồi.",
  "Let's just get the samples and go.": "Cứ lấy mẫu vật rồi đi thôi.",
  "Hilda": "Hilda",
  "If you have to fight them, try to isolate them and kill them quickly.": "Nếu cậu phải chiến đấu với chúng, hãy cố gắng cô lập chúng và tiêu diệt thật nhanh.",
  "Open the Journal [ul_journal_menu] and use the Radio facility to make contact with HQ.": "Mở Nhật ký (Journal) [ul_journal_menu] và sử dụng thiết bị Radio để liên lạc với Trụ sở (HQ).",
  "You did good. I know things are looking pretty bleak, but just try and remember, everybody's here for you.": "Cô làm tốt lắm. Tôi biết mọi thứ đang rất ảm đạm, nhưng hãy cố gắng và nhớ rằng, mọi người luôn ở đây vì cô.",
  "SURVIVAL TACTICS: Headshot Streak": "CHIẾN THUẬT SINH TỒN: Chuỗi Headshot",
  "I guess what I'm trying to say is thanks.": "Tôi đoán những gì tôi đang cố nói là cảm ơn cậu.",
  "Oh yeah, we are WAY up in the air.": "Ồ yeah, chúng ta đang ở TRÊN CAO lắm đấy.",
  "Looks like somebody's ammo cache.": "Có vẻ như đây là kho đạn của ai đó.",
  "Yeah, I've been saying we can't just leave shit lying around on shelves. We need some way to refrigerate our food.": "Ừ, tôi đã nói là chúng ta không thể cứ để thức ăn vứt lăn lóc trên kệ được. Chúng ta cần một cách nào đó để làm lạnh thực phẩm.",
  "Garrison": "Garrison",
  "Individual rounds loaded into magazines for use in the field.": "Từng viên đạn đơn lẻ được nạp vào băng đạn để sử dụng trên chiến trường.",
  "The Latrine is Filthy!": "Khu Nhà Vệ Sinh (Latrine) Đang Bẩn Thỉu!"
};

const file = 'output/languages/chunks/btxt_chunk_112.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_112.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk112[r.sourceText]) {
    r.translatedText = chunk112[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 112 successfully!');
