const fs = require('fs');
const chunk180 = {
  "You don't sing, do you? (TV Trivia.)": "Cậu đéo biết hát, phải đéo? (Kiến Thức Truyền Hình.)",
  "Bailey": "Bailey",
  "\"Let's roll.\" Buncha goddamn cowboys here.": "\"Lên đường thôi.\" Một lũ cao bồi chết tiệt ở đây.",
  "Look, I know there's some more food here somewhere, I just... I gotta find it. Please. It's for my brother.": "Nghe này, tôi biết vẫn còn một ít thức ăn ở đâu đó quanh đây, tôi chỉ... tôi phải tìm ra nó. Làm ơn đi. Nó là dành cho em trai của tôi.",
  "The fuck? How can you just ignore this?": "Cái đéo gì vậy? Làm sao cậu có thể cứ thế phớt lờ chuyện này được chứ?",
  "Well, that wraps up another one of those. Thanks for the assist.": "Chà, thế là giải quyết xong thêm một vụ như vậy nữa. Cảm ơn vì đã hỗ trợ.",
  "Don't you think that's something you should ask her?": "Cậu đéo nghĩ đó là chuyện mà cậu nên tự mình đi hỏi cô ấy sao?",
  "DOC HANSON. Restores your Maximum Vitality.": "DOC HANSON. Phục hồi Sinh Lực Tối Đa (Maximum Vitality) cho bạn.",
  "Guess there are no celebrities left to gossip about. Your FAME is the long-term recognition you've earned with other survivors. Your INFLUENCE will continually tick towards this value, making it a sort of a baseline.": "Đoán là đéo còn người nổi tiếng nào sót lại để mà bàn tán xôn xao nữa đâu. DANH TIẾNG (FAME) của bạn là sự công nhận lâu dài mà bạn đã giành được từ những người sống sót khác. ẢNH HƯỞNG (INFLUENCE) của bạn sẽ liên tục tăng dần theo giá trị này, khiến nó trở thành một loại mức cơ sở.",
  "Okay, that was it.": "Được rồi, xong chuyện rồi đó.",
  "Large Backpack": "Ba Lô Lớn (Large Backpack)",
  "%1$s is safe and sound.": "%1$s đang bình an vô sự.",
  "Plenty of restaurants around here if you're looking to beef up our food supply. Or you could go house to house and check kitchens, I guess.": "Có rất nhiều nhà hàng quanh đây nếu cậu đang muốn tăng cường nguồn cung cấp thức ăn cho chúng ta. Hoặc cậu cũng có thể đi từng nhà và kiểm tra nhà bếp của họ, tôi đoán vậy.",
  "Great. The hordes have found us again.": "Tuyệt thật. Lũ zombie (hordes) lại tìm thấy chúng ta rồi.",
  "I'll tell you when it gets to zero.": "Tôi sẽ nói cho cậu biết khi nào nó trở về số không.",
  "Move it, people! Now now now!": "Di chuyển đi, mọi người! Ngay bây giờ ngay lúc này!",
  "Rolling Pin": "Cây Lăn Bột (Rolling Pin)",
  "Like somebody took a weed whacker to my fucking neck.": "Cứ như thể ai đó vừa lấy máy cắt cỏ xén ngang qua cái cổ chết tiệt của tôi vậy.",
  "We may have a problem on our six.": "Chúng ta có thể đang gặp rắc rối ở hướng sáu giờ đấy.",
  "I like Quentin, but I'm not going to snoop for him.": "Tôi thích Quentin, nhưng tôi sẽ đéo đi rình mò theo dõi vì lợi ích của anh ta đâu.",
  "Negative, negative. We need time to resupply before we can head out again.": "Từ chối, từ chối. Chúng tôi cần thêm thời gian để tiếp tế (resupply) trước khi chúng tôi có thể lên đường ra ngoài đó một lần nữa.",
  "C. C. Garcia": "C. C. Garcia",
  "Your orders are to continue evaluation and collect relevant intelligence.": "Mệnh lệnh của anh là tiếp tục đánh giá và thu thập các thông tin tình báo có liên quan.",
  "Get yourself clear!": "Hãy tự giải thoát cho chính mình đi!",
  "Book on Gardening": "Sách Hướng Dẫn Trồng Trọt (Book on Gardening)",
  "Jacob was... growing up, he was my hero. It killed me when he left home, and just when I thought I'd gotten him back....": "Jacob từng là... lúc lớn lên, anh ấy là một người anh hùng trong lòng tôi. Nó đã giết chết tôi khi anh ấy rời khỏi nhà, và ngay khi tôi những tưởng mình đã tìm lại được anh ấy....",
  "Nathan": "Nathan",
  "Any time.": "Bất cứ lúc nào.",
  "Good to hear.": "Thật tốt khi nghe điều đó.",
  "Switch to": "Chuyển sang",
  "Lynn": "Lynn",
  "Supply Locker": "Tủ Đựng Đồ Tiếp Tế (Supply Locker)",
  "You see how fast we're going through our fuel stocks?": "Cậu có thấy chúng ta đang tiêu thụ lượng nhiên liệu (fuel) dự trữ nhanh đến mức nào đéo?",
  "Should be supplies there.": "Chắc hẳn là có đồ tiếp tế (supplies) ở đó.",
  "Had a few words of wisdom to share.": "Có một vài lời khuyên khôn ngoan muốn chia sẻ.",
  "Ooh, you're right. Wouldn't want to push a scary psycho like you.": "Ooh, cậu nói đúng đấy. Tôi sẽ đéo muốn chọc giận một tên tâm thần đáng sợ như cậu đâu.",
  "Look, truth is we're stretched pretty thin. You think you could help us out on this thing?": "Nghe này, sự thật là lực lượng của chúng tôi đang bị kéo giãn ra khá mỏng rồi. Cậu có nghĩ rằng cậu có thể giúp đỡ chúng tôi giải quyết chuyện này đéo?",
  "We'll follow you.": "Chúng tôi sẽ đi theo cậu.",
  "Yeehaw, let's do it!": "Yeehaw, làm thôi nào!",
  "Thought you'd want to know, one of the Wilkersons' goons just dropped off a \"care package.\"": "Nghĩ là cậu sẽ muốn biết chuyện này, một trong những tên tay sai của nhà Wilkerson vừa mới mang đến bỏ lại một \"gói hàng cứu trợ (care package).\"",
  "Supply Room": "Phòng Tiếp Tế (Supply Room)",
  "God help us all.": "Xin Chúa hãy cứu giúp tất cả chúng con.",
  "Lots of weird noises last night. Sounded like people setting off fireworks or something. Ed says it's Spencer's Mill's 75th Annual Bored Teenager Days. - %1$s": "Có rất nhiều tiếng ồn kỳ lạ vào đêm qua. Nghe giống như có người đang đốt pháo hoa hay cái gì đó đại loại vậy. Ed nói rằng đó là Ngày Hội Thường Niên Lần Thứ 75 Của Những Thanh Thiếu Niên Chán Đời ở Spencer's Mill. - %1$s",
  "And I gotta admit, knowing we're not the only ones that made it feels pretty good.": "Và tôi phải thừa nhận rằng, việc biết được chúng ta đéo phải là những người duy nhất sống sót qua khỏi chuyện này mang lại cảm giác khá là tốt.",
  "Y'know, I might need that later.": "Cậu biết đấy, tôi có thể sẽ cần đến thứ đó sau này.",
  "Ops Center": "Trung Tâm Tác Chiến (Ops Center)",
  "You ready to light the fires?": "Cậu đã sẵn sàng để châm lửa đốt cháy chưa?",
  "We need a goddamn infirmary!": "Chúng ta cần một cái bệnh xá (infirmary) chết tiệt!",
  "Set Up Field Workshop": "Xây Dựng Xưởng Chế Tạo Dã Chiến (Field Workshop)",
  "Nicknamed the \"Hammer of Justice\"": "Được mệnh danh là \"Chiếc Búa Công Lý\"",
  "Manslaughter": "Ngộ Sát (Manslaughter)",
  "U.S. Intelligence has confirmed outbreaks in Osaka, Kyoto, Manila, Brisbane, Sydney, and Wellington. \r\nZed presence has gone worldwide in barely over a week.": "Cơ Quan Tình Báo Hoa Kỳ đã xác nhận có bùng phát dịch bệnh ở Osaka, Kyoto, Manila, Brisbane, Sydney, và Wellington. \r\nSự hiện diện của bọn Zed đã lan rộng ra toàn cầu chỉ trong vòng hơn một tuần.",
  "%3$s learned a few things.": "%3$s đã học hỏi thêm được một vài điều.",
  "DANGER: Armored Zed Sighting": "NGUY HIỂM: Phát Hiện Zed Bọc Giáp (Armored Zed)",
  "What, like a dispatcher?": "Cái gì, giống như một người điều phối (dispatcher) á?",
  "Search for the Feral Zombie": "Tìm kiếm con Feral Zombie",
  "WILCO, sir. Black Friday out.": "Sẽ tuân lệnh (WILCO), thưa ngài. Black Friday hết (out).",
  "Carl comes across as a quiet, patient, introspective sort. He's a long-time veteran of the force, and though he never rose above patrolman rank, he was always a dependable cop, and the department frequently partnered him up with rookies, trusting him to show them the ropes.": "Carl có vẻ ngoài là một người trầm tính, kiên nhẫn và sống nội tâm. Ông ấy là một cựu binh lâu năm của lực lượng cảnh sát, và mặc dù ông ấy đéo bao giờ thăng tiến quá cấp bậc cảnh sát tuần tra, ông luôn là một viên cảnh sát đáng tin cậy, và sở cảnh sát thường xuyên phân công ông làm việc cùng với những người lính mới, tin tưởng giao phó cho ông việc chỉ dẫn cho họ những quy tắc cơ bản.",
  "Got lucky there.": "Đã ăn may ở chỗ đó đấy.",
  "Set Up Training Area": "Xây Dựng Khu Vực Huấn Luyện (Training Area)",
  "Typical....": "Điển hình....",
  "Died of Black Fever.": "Đã chết vì căn bệnh Black Fever.",
  "Survivors who cannot reach the Marshall Municipal Courthouse should contact us on this frequency.": "Những người sống sót đéo thể đến được Tòa Án Thành Phố Marshall vui lòng liên hệ với chúng tôi qua tần số này.",
  "Yeah, I need a suppressor on this gun.": "Đúng vậy, tôi cần lắp một ống giảm thanh (suppressor) lên khẩu súng này.",
  "RUMORS: Flu Epidemic": "TIN ĐỒN: Dịch Cúm (Flu Epidemic)",
  "Hearst": "Hearst",
  "An entry level collector's sword.": "Một thanh kiếm cấp độ nhập môn dành cho những người sưu tầm.",
  "FRIENDSHIP EARNED: Jacob Ritter": "ĐÃ NHẬN ĐƯỢC TÌNH BẠN: Jacob Ritter",
  "Suck it up! We gotta move!": "Cố gắng chịu đựng đi! Chúng ta phải di chuyển thôi!",
  "Can't say I'm surprised.": "Đéo thể nói rằng tôi cảm thấy ngạc nhiên được.",
  "How is anybody supposed to trust you if you can't even keep them safe?": "Làm sao mọi người có thể tin tưởng cậu khi mà cậu thậm chí còn đéo thể giữ an toàn cho họ được chứ?",
  "Did you look inside the RV? It’s … it’s just awful. All that blood. And … maybe worse.": "Cậu đã nhìn vào bên trong chiếc xe RV chưa? Nó... nó thật tồi tệ. Toàn là máu. Và... có thể còn tệ hơn thế nữa.",
  "Think we have enough building materials to make it secure?": "Nghĩ rằng chúng ta có đủ vật liệu xây dựng (building materials) để gia cố cho nó được an toàn đéo?",
  "Aw man, this car's gonna get us way more attention than we want.": "Trời ạ, chiếc xe ô tô này sẽ thu hút thêm nhiều sự chú ý về phía chúng ta hơn những gì mà chúng ta muốn đấy.",
  "Uncle Sam would seem to disagree with you there. Our orders are to evict squatters, with lethal force if they resist. You resisted, so....": "Uncle Sam (Chính phủ Hoa Kỳ) có vẻ sẽ đéo đồng ý với cô về chuyện đó đâu. Mệnh lệnh của chúng tôi là trục xuất những người đang chiếm dụng đất trái phép, sử dụng vũ lực sát thương nếu họ chống cự. Cô đã chống cự, vì thế nên....",
  "But you gotta snap outta that if you wanna live through this.": "Nhưng cậu phải thoát khỏi tình trạng đó nếu như cậu muốn sống sót vượt qua chuyện này.",
  "138 STORY Carl Parsons": "138 CỐT TRUYỆN (STORY) Carl Parsons",
  "Good work!": "Làm tốt lắm!",
  "Doctor Horn found a weapon easily enough.": "Bác sĩ Horn đã tìm thấy một món vũ khí khá dễ dàng.",
  "Climb up and survey the area.": "Hãy leo lên cao và quan sát khu vực này.",
  "AMMO DELIVERED": "ĐÃ GIAO ĐẠN DƯỢC",
  "They're inside the LZ!": "Bọn chúng đang ở bên trong khu vực bãi đáp (LZ)!",
  "What do you want?": "Cậu muốn cái đéo gì hả?",
  "To check his ID, for Christ's sake!": "Để kiểm tra cái thẻ ID của ông ấy, vì Chúa!",
  "NM+": "NM+",
  "Bob": "Bob",
  "Here's a good spot for an outpost.": "Đây là một vị trí tốt để lập một tiền đồn (outpost) đấy.",
  "We've got a lot of work ahead of us if we're going to survive another attack.": "Chúng ta còn rất nhiều việc ở phía trước nếu muốn sống sót qua một cuộc tấn công khác.",
  "We have a safe, secure society here, governed by the rule of law.": "Chúng ta có một xã hội an toàn, an ninh ở đây, được cai trị bởi những quy định của pháp luật.",
  "That got their attention!": "Làm như vậy đã thu hút sự chú ý của bọn chúng rồi đấy!",
  "At least I'd be able to keep the food I found.": "Ít nhất thì tôi cũng sẽ có thể giữ lại được số thức ăn mà tôi đã tìm thấy.",
  "Okay, it's your call. But for the record? If this turns out to be a trap, I'm totally claiming \"I told you so\" rights for a week.": "Được rồi, tùy cậu quyết định thôi. Nhưng nói trước để cậu biết nhé? Nếu chuyện này hóa ra lại là một cái bẫy, tôi chắc chắn sẽ sử dụng cái quyền được nói câu \"Tôi đã bảo cậu rồi mà\" trong suốt cả một tuần liền đấy.",
  "Set up and ready.": "Đã thiết lập xong và sẵn sàng hoạt động.",
  "You seem like you're about ready to give up.": "Cậu có vẻ như là cậu đã sắp sửa sẵn sàng để bỏ cuộc rồi thì phải.",
  "%d Missions Completed": "Đã Hoàn Thành %d Nhiệm Vụ",
  "If she left that radio station, who would we have to yell at us?": "Nếu cô ấy rời khỏi đài phát thanh đó, chúng ta sẽ có ai để mà hét vào mặt chúng ta nữa đây?",
  "Provides a chance of doubled output from your Garden.": "Cung cấp một tỷ lệ để nhân đôi sản lượng thu hoạch từ Khu Vườn (Garden) của bạn.",
  "Det Cord": "Dây Cháy Chậm (Det Cord)",
  "All T21 rifles are made to easily convert between 9mm and 5.56mm.": "Tất cả các loại súng trường T21 đều được chế tạo để dễ dàng chuyển đổi qua lại giữa cỡ đạn 9mm và 5.56mm.",
  "Weird stuff on the news, and today Job Wilkerson pays me a call and says I can pay him off in bullets and food instead of cash. What the hell's going on?": "Toàn những chuyện kỳ lạ trên bản tin thời sự, và hôm nay Job Wilkerson đã gọi điện cho tôi và nói rằng tôi có thể trả nợ cho hắn ta bằng đạn dược và thức ăn thay vì tiền mặt. Chuyện quái quỷ gì đang diễn ra vậy chứ?"
};

const file = 'output/languages/chunks/btxt_chunk_180.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_180.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk180[r.sourceText]) {
    r.translatedText = chunk180[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 180 successfully!');
