const fs = require('fs');
const chunk119 = {
  "The save game appears to be damaged and cannot be loaded. You can choose another storage device or continue without saving losing any progress made.": "Tệp lưu game có vẻ đã bị hỏng và không thể tải được. Bạn có thể chọn một thiết bị lưu trữ khác hoặc tiếp tục chơi mà không lưu lại những tiến trình đã đạt được.",
  "In case you didn't notice, the army pulled out of the city hours ago.": "Trong trường hợp cậu chưa nhận ra, thì quân đội đã rút khỏi thành phố nhiều giờ trước rồi.",
  "Ronald": "Ronald",
  "If you ain't ready to burn a zed, then let's turn around and get ready.": "Nếu cậu chưa sẵn sàng để thiêu rụi bọn zed, thì chúng ta hãy quay lại và chuẩn bị đi.",
  "NOTE: Come check this out!": "GHI CHÚ: Đến xem cái này đi!",
  "%1$s is no longer in the community.": "%1$s không còn ở trong cộng đồng nữa.",
  "Adewale": "Adewale",
  "Awesome.": "Tuyệt vời.",
  ".22-caliber Ammunition": "Đạn cỡ .22",
  "You might not know me yet, but I think the two of us could do each other a lot of good.": "Có thể cậu chưa biết tôi, nhưng tôi nghĩ hai chúng ta có thể mang lại nhiều lợi ích cho nhau đấy.",
  "Motherfucking zombie assholes!": "Lũ zombie khốn khiếp chó đẻ!",
  "All versions of State of Decay have now been upgraded with Vehicle Storage. Approach the rear of any driveable vehicle, and press [xi_use] to access the inventory for that vehicle. You may load conventional inventory items (weapons, ammunition, consumables, etc) or rucksack resources (Food, Ammo, Materials, Medicine, Fuel) into a vehicle. When you drive a vehicle into your Parking facility, any rucksack resources it contains are automatically delivered into your base.": "Mọi phiên bản của State of Decay hiện đã được nâng cấp thêm tính năng Lưu trữ trên xe. Hãy tiếp cận phía sau của bất kỳ chiếc xe nào có thể lái được, và nhấn [xi_use] để mở kho đồ của xe đó. Bạn có thể chất các vật phẩm thông thường (vũ khí, đạn dược, đồ tiêu hao, v.v.) hoặc tài nguyên dạng Ba lô (Thức ăn, Đạn, Vật liệu, Thuốc, Nhiên liệu) lên xe. Khi bạn lái xe vào bãi đậu xe của căn cứ, mọi tài nguyên dạng Ba lô chứa trên xe sẽ được tự động chuyển vào kho của bạn.",
  "Zeds up ahead.": "Có zed ở phía trước.",
  "Novak": "Novak",
  "Owes Child Support": "Nợ Tiền Cấp Dưỡng Nuôi Con",
  "Pistol: Hi-Power": "Súng lục: Hi-Power",
  "Zombie Kill Points (Weekly)": "Điểm Tiêu Diệt Zombie (Hàng tuần)",
  "We need to make some armor. (Handy with Arts and Crafts.)": "Chúng ta cần chế tạo vài bộ giáp. (Khéo Tay Hay Làm / Arts and Crafts.)",
  "You need to chill out before somebody decides to put you in the ground. Get the picture?": "Mày cần phải bình tĩnh lại trước khi có ai đó quyết định chôn sống mày xuống đất. Hiểu chưa?",
  "I guess we're moving on, huh?": "Tôi đoán là chúng ta phải tiếp tục lên đường thôi, nhỉ?",
  "So much for doing it the quiet way.": "Thế là xong cái kế hoạch hành động trong im lặng.",
  "Jesus, who pissed in your cereal? C'mon, walk with me.": "Chúa ơi, ai vừa đái vào bát ngũ cốc của cậu vậy? Thôi nào, đi dạo với tôi.",
  "Not too bright, are they?": "Bọn nó không được sáng dạ cho lắm, nhỉ?",
  "This is Vienna Cho, signing off. For good.": "Đây là Vienna Cho, kết thúc phiên phát sóng. Mãi mãi.",
  "She's a civilian. We can't expect her to understand.": "Cô ấy là dân thường. Chúng ta không thể trông mong cô ấy hiểu được.",
  "Hey, we're all angry at the hand we've been dealt.": "Này, tất cả chúng ta đều đang giận dữ với cái hoàn cảnh mà chúng ta phải gánh chịu.",
  "Don't suppose you've decided on whether we can join you or not?": "Không biết là cậu đã quyết định xem chúng tôi có thể tham gia cùng các cậu hay chưa?",
  "Matt": "Matt",
  "April": "April",
  "There's only one way we're going to make it.": "Chỉ có một cách duy nhất để chúng ta sống sót qua chuyện này.",
  "Steer": "Lái xe",
  "Eshiet": "Eshiet",
  "55 REF Shark Hoodie Guy": "55 REF Anh Chàng Mặc Áo Hoodie Cá Mập",
  "Hold still, dammit! I know it hurts!": "Ở yên đó, chết tiệt! Tôi biết là đau mà!",
  "73 REF Carlton Weathers": "73 REF Carlton Weathers",
  "This here's about to go pear-shaped.": "Chuyện này sắp bung bét hết cả rồi.",
  "People! We are LEAVING!": "Mọi người! Chúng ta RÚT THÔI!",
  "Pistol: X-Lock Tactical": "Súng lục: X-Lock Tactical",
  "You ain't welcome round these parts, pardner.": "Các người không được hoan nghênh ở khu vực này đâu, anh bạn.",
  "Things have gone from bad to worse up here.": "Mọi chuyện trên này đang từ tồi tệ chuyển sang tồi tệ hơn rồi.",
  "Mal": "Mal",
  "Stay sharp!": "Tập trung vào!",
  "Fellow survivors, this is my final broadcast. I'll leave it on a loop, for however long that lasts.": "Hỡi những người sống sót, đây là buổi phát sóng cuối cùng của tôi. Tôi sẽ để nó phát lặp đi lặp lại, được bao lâu hay bấy nhiêu.",
  "Doesn't seem to trust anyone.": "Có vẻ như không tin tưởng bất cứ ai.",
  "Yeah, get that sumbitch!": "Phải, bắt lấy thằng chó đẻ đó đi!",
  "Sledgehammer": "Búa Tạ (Sledgehammer)",
  "You got ammo, we got hooch. Interested?": "Các cậu có đạn, chúng tôi có rượu. Có hứng thú không?",
  "Cannot help with missions or provide labor until the wound heals.": "Không thể giúp làm nhiệm vụ hoặc cung cấp nhân công cho đến khi vết thương lành.",
  "HOME: Binge Eating": "NHÀ: Cuồng Ăn (Binge Eating)",
  "You're that hurt and still fighting? What're you trying to prove?": "Cậu bị thương nặng thế mà vẫn chiến đấu sao? Cậu đang cố chứng tỏ điều gì chứ?",
  "Laws": "Laws",
  "If you want to keep your guns and keep your own scavenge, you're on you're own.": "Nếu các người muốn giữ súng và giữ chiến lợi phẩm cho riêng mình, thì các người phải tự lo thân thôi.",
  "It doesn't take much to set you off once you've got a couple shots in you. (Bonus Melee)": "Chẳng cần nhiều lắm để kích động cậu một khi cậu đã nốc vài ly. (Thưởng Kỹ năng Cận chiến)",
  "Shira Bogatz is safe and sound": "Shira Bogatz đã bình an vô sự",
  "The folks out at the old Ballard homestead have been having trouble with one of their trucks. I happen to have some parts to spare, so I was figuring on running them out there.": "Những người ở nông trang Ballard cũ đang gặp rắc rối với một trong những chiếc xe tải của họ. Tôi tình cờ có dư vài phụ tùng, nên định đem ra đó cho họ.",
  "Okay, what joker tied my intestines into bowlines? - %1$s": "Được rồi, tên ngốc nào đã thắt ruột tôi thành những nút thắt thế này? - %1$s",
  "Hey, what the fuck are you doing? Get your ass back here!": "Này, cậu đang làm cái quái gì vậy? Vác cái mông về đây ngay!",
  "COMPLETED: Ask the Sheriff": "ĐÃ HOÀN THÀNH: Hỏi Cảnh sát trưởng",
  "137 STORY Ray Santos": "137 STORY Ray Santos",
  "Thank God we've got plenty of medicine.": "Tạ ơn Chúa là chúng ta có đủ thuốc men.",
  "That won't work.": "Sẽ không hiệu quả đâu.",
  "Escort the Assets to Base": "Hộ tống các Mục tiêu (Assets) về Căn cứ",
  "Having some trouble.": "Đang gặp chút rắc rối.",
  "Mugs": "Cốc (Mugs)",
  "I cannot believe you! You want to run away! Again!": "Tôi không thể tin được anh! Anh muốn chạy trốn! Một lần nữa!",
  "Aspect Ratio - 16:10": "Tỷ Lệ Khung Hình - 16:10",
  "SitRep: Toronto": "Báo Cáo Tình Hình (SitRep): Toronto",
  "The law still reigns in Marshall.": "Luật pháp vẫn ngự trị ở Marshall.",
  "Gonna be a hell of a time keeping stuff working around here without electricity.": "Sẽ là một khoảng thời gian khó khăn như địa ngục để giữ cho mọi thứ hoạt động quanh đây mà không có điện.",
  "Woohoo! %1$s and some other folks fought off that siege. - %2$s": "Woohoo! %1$s và vài người khác đã đánh lùi cuộc vây hãm đó. - %2$s",
  "Ours? Ours are still pretty much bottles of booze with rags in them.": "Của chúng ta á? Của chúng ta phần lớn vẫn chỉ là những chai rượu nhét giẻ vào thôi.",
  "How about you help us take down a freak?": "Hay là cậu giúp chúng tôi hạ gục một con quái thai (freak) nhé?",
  "[message looping tone] One one lima november nine nine charlie six one romeo.": "[tiếng bíp vòng lặp tin nhắn] Một một lima november chín chín charlie sáu một romeo.",
  "Make Pipe Bomb": "Chế Tạo Bom Ống (Pipe Bomb)",
  "I'll carry the stuff and do the talking. I just want to have an extra gun on hand in case things get bad.": "Tôi sẽ mang đồ và làm người đứng ra nói chuyện. Tôi chỉ muốn có thêm một tay súng phòng trường hợp mọi chuyện tồi tệ đi.",
  "Looks like we get to sit around with our thumbs up our asses a little longer.": "Có vẻ như chúng ta sẽ phải tiếp tục ngồi không và cắm ngón tay vào đít thêm một lúc nữa.",
  "EXTRACTED: Michele Martin": "ĐÃ RÚT LUI: Michele Martin",
  "Did nobody see my name on the fucking hot dogs? Seriously? I had plans for those! Special plans. Assholes. - %1$s": "Không ai nhìn thấy tên tôi trên mấy cái xúc xích chết tiệt đó sao? Thật sự luôn? Tôi đã có kế hoạch cho chúng! Những kế hoạch đặc biệt. Lũ khốn. - %1$s",
  "Looks like we have troops in contact. Hang back, doctor. Let us check this out.": "Có vẻ như quân ta đang giao tranh. Lùi lại đi, bác sĩ. Để chúng tôi kiểm tra.",
  "How about I come along and watch your back?": "Hay là tôi đi theo và yểm trợ cho cậu nhé?",
  "Thanks for the company.": "Cảm ơn vì đã đồng hành.",
  "While you see the save icon please do not turn off your console.": "Trong khi bạn thấy biểu tượng lưu, vui lòng không tắt máy (console).",
  "Have raids like this been a problem before?": "Những cuộc tập kích thế này có từng là vấn đề trước đây chưa?",
  "Resolution 640x480": "Độ phân giải 640x480",
  "That should thin the zombies out for a while. Makes things safer for all of us. -%1$s": "Điều đó sẽ làm giảm bớt lượng zombie trong một thời gian. Giúp mọi thứ an toàn hơn cho tất cả chúng ta. -%1$s",
  "Reflexes Improved!": "Phản Xạ (Reflexes) Đã Được Cải Thiện!",
  "I'll say my goodbyes then. And if you gentlemen decide you'd rather be in a different line of work, well, you just let me know.": "Vậy tôi xin phép chào tạm biệt. Và nếu các quý ông quyết định mình muốn làm một công việc khác, chà, cứ cho tôi biết nhé.",
  "We've got a problem at the Workshop.": "Chúng ta có vấn đề ở Xưởng (Workshop).",
  "My dad used to say when the going gets tough, the tough get going.": "Bố tôi từng nói khi mọi thứ trở nên khó khăn, những người mạnh mẽ sẽ bắt đầu hành động.",
  "The Moustache": "Bộ Râu Mép",
  "Desperately Need Guns": "Vô Cùng Cần Súng",
  "We've got some more rounds of .22 ammunition.": "Chúng ta vừa có thêm vài viên đạn .22.",
  "Just one big slaughterhouse": "Chỉ là một lò mổ khổng lồ thôi",
  "Zeds ahead, lock and load.": "Có zed ở phía trước, lên đạn sẵn sàng.",
  "Martinez": "Martinez",
  "Items added to the supply locker!": "Các vật phẩm đã được thêm vào tủ đồ (Supply Locker)!",
  "Safe only goes so far. Hordes can still wander through and noise can always draw zeds in.": "Sự an toàn cũng chỉ đến mức đó thôi. Các bầy horde vẫn có thể đi ngang qua và tiếng ồn thì luôn thu hút bọn zed đến.",
  "Mason": "Mason",
  "Hold up, I think we're safe now.": "Đợi đã, tôi nghĩ giờ chúng ta an toàn rồi.",
  "Perfect. You stay safe out there.": "Hoàn hảo. Cậu hãy giữ an toàn ngoài đó nhé."
};

const file = 'output/languages/chunks/btxt_chunk_119.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_119.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk119[r.sourceText]) {
    r.translatedText = chunk119[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 119 successfully!');
