const fs = require('fs');
const chunk160 = {
  "Has an anti-authoritarian streak that stems from being in trouble with the law.": "Có tư tưởng chống đối chính quyền bắt nguồn từ việc gặp rắc rối với pháp luật.",
  "We missed a catastrophic case of the shits by THAT much. We gotta be more careful with our food.": "Suýt chút nữa thì chúng ta dính một thảm họa tiêu chảy nặng cmnr. Chúng ta phải cẩn thận hơn với thức ăn của mình.",
  "Take me to the nuke. I can take apart Eldridge's switch.": "Đưa tôi đến chỗ quả bom hạt nhân. Tôi có thể tháo rời công tắc của Eldridge.",
  "Well, fuck.": "Chà, đụ má.",
  "+25%": "+25%",
  "Experimental support weapon from CLEO.": "Vũ khí hỗ trợ thử nghiệm từ CLEO.",
  "Maybe you oughta stand somewhere else right now.": "Có lẽ cậu nên đứng ở chỗ khác ngay bây giờ đi.",
  "Immelman": "Immelman",
  "Maybe a few decades from now, we'll have domesticated dead people.": "Biết đâu vài thập kỷ nữa, chúng ta sẽ có người chết được thuần hóa.",
  "Rifle: M1 Carbine": "Súng Trường: M1 Carbine",
  "Just taking care of some business.": "Chỉ đang giải quyết một số công việc thôi.",
  "Enclave in trouble!": "Khu Tự Trị (Enclave) đang gặp rắc rối!",
  "Jesus... like he was a damn toy....": "Chúa ơi... cứ như anh ta là một món đồ chơi chết tiệt vậy....",
  "Huh. Might be some people there.": "Hả. Có thể có vài người ở đó.",
  "Will never ask \"You want fries with that?\" again.": "Sẽ đéo bao giờ hỏi \"Cậu có muốn dùng thêm khoai tây chiên đéo?\" một lần nào nữa.",
  "Sometimes it's like we're re-inventing civilization one discovery at a time.": "Đôi khi có cảm giác như chúng ta đang tái thiết lại nền văn minh qua từng khám phá vậy.",
  "It is therefore the decision of this court that you serve a term of not less than two weeks in the county detention facility.": "Do đó, quyết định của tòa án này là anh sẽ phải phục vụ một án phạt đéo dưới hai tuần tại trại giam của quận.",
  "He's a shithead, but look on the bright side. He's only about half as stupid as he looks.": "Hắn ta là một thằng khốn nạn, nhưng hãy nhìn vào mặt tích cực xem. Hắn chỉ ngu bằng khoảng một nửa vẻ bề ngoài của hắn thôi.",
  "Single-malt, my friend. Your favorite, if I remember right.": "Mạch nha đơn cất (Single-malt), anh bạn. Loại cậu thích nhất, nếu tôi nhớ đéo nhầm.",
  "You may be gripped with doubt, exhausted and afraid. You may think this is all futile, and that we won't see another dawn.": "Có thể các bạn đang bị bủa vây bởi sự nghi ngờ, kiệt sức và sợ hãi. Có thể các bạn nghĩ rằng tất cả những điều này đều vô ích, và rằng chúng ta sẽ đéo thể nhìn thấy bình minh thêm một lần nào nữa.",
  "Created - .22 Ammunition": "Đã tạo - Đạn .22",
  "You've added survivors to your Community! Press [ul_journal_menu] to open your Journal and learn about making Friends on the Community page.": "Bạn đã thêm những người sống sót vào Cộng Đồng của mình! Nhấn [ul_journal_menu] để mở Nhật Ký (Journal) và tìm hiểu về cách kết Bạn (Friends) trên trang Cộng Đồng (Community).",
  "Edged Weapon Specialization Improved!": "Kỹ năng chuyên môn Vũ Khí Có Lưỡi (Edged Weapon Specialization) đã được cải thiện!",
  "UPGRADED: Ammunition Shop": "ĐÃ NÂNG CẤP: Cửa Hàng Đạn Dược (Ammunition Shop)",
  "Because the LategameCheat flag is set, all of these have been unlocked: Library, Generator, Storage, Dining Area, Garden, and Kitchen": "Bởi vì cờ LategameCheat đã được bật, tất cả những thứ này đã được mở khóa: Thư Viện (Library), Máy Phát Điện (Generator), Kho Chứa (Storage), Khu Vực Ăn Uống (Dining Area), Khu Vườn (Garden), và Nhà Bếp (Kitchen)",
  "Oh man, oh man...I'm losing my shit!": "Ôi bạn ơi, ôi bạn ơi... tôi đang mất bình tĩnh cmnr!",
  "31 MIL Pfc Anthony Hartsock": "31 QUÂN ĐỘI (MIL) Binh Nhất (Pfc) Anthony Hartsock",
  "Influence Costs Decreased": "Giảm Chi Phí Ảnh Hưởng (Influence Costs)",
  "Damn, you're a pretty good shot!": "Chết tiệt, cậu bắn khá tốt đấy chứ!",
  "22 GENERIC Edgar Reynolds": "22 CHUNG (GENERIC) Edgar Reynolds",
  "Our target won't last much longer.": "Mục tiêu của chúng ta sẽ đéo trụ được lâu nữa đâu.",
  "Smythe": "Smythe",
  "Take that, assholes!": "Nhận lấy này, lũ khốn!",
  "Can't resist the urge to crack a joke, even at the least appropriate times. Can be a lot of fun ... but can also annoy the shit out of people.": "Đéo thể cưỡng lại cảm giác thèm muốn được kể một câu chuyện cười, ngay cả vào những thời điểm đéo thích hợp nhất. Có thể rất vui ... nhưng cũng có thể làm người khác khó chịu phát điên.",
  "We've located a group of soldiers holed up in the outskirts of the city. We should consider bringing them on as reinforcents.": "Chúng tôi đã tìm ra vị trí một nhóm lính đang cố thủ ở ngoại ô thành phố. Chúng ta nên cân nhắc việc đưa họ về làm viện binh.",
  "79 REF Tyler Goff": "79 NGƯỜI TỊ NẠN (REF) Tyler Goff",
  "Sneaking through here is harder than I thought.": "Lẻn qua đây khó hơn tôi nghĩ đấy.",
  "You shouldn't be running around hurt like that.": "Cậu đéo nên chạy nhảy loanh quanh khi đang bị thương như thế.",
  "Just don't take shit you haven't earned.": "Chỉ là đừng có lấy đi cái thứ chết tiệt đéo phải do cậu kiếm được.",
  "Need an infirmary to keep sick people away from everyone else.": "Cần một bệnh xá (infirmary) để cách ly những người bị bệnh ra xa khỏi những người khác.",
  "Save Game Not Found": "Đéo tìm thấy file Lưu Game (Save Game)",
  "Reminds me of when the whole family got together for a good barn-raising when I was a kid. Nah, I'm just fucking with ya! Nice work, though.": "Làm tôi nhớ đến hồi nhỏ, khi cả nhà cùng nhau dựng một cái nhà kho thật bự. Đéo đâu, tôi chỉ trêu cậu thôi! Tuy nhiên, làm tốt lắm.",
  "I knew all those hours I spent breaking into my neighbors' houses would pay off someday! (Expert scavenger.)": "Tôi biết ngay là tất cả những giờ tôi dành ra để đột nhập vào nhà hàng xóm sẽ được đền đáp vào một ngày nào đó mà! (Chuyên gia nhặt rác - Expert scavenger.)",
  "SitRep: Venezuela": "Báo Cáo Tình Hình (SitRep): Venezuela",
  "That's taken care of.": "Chuyện đó đã được lo liệu xong.",
  "+300%": "+300%",
  "We made our own MREs! All it took was some plastic bags and bits of random food.": "Chúng ta đã tự làm Khẩu phần ăn dã chiến (MREs)! Tất cả những gì cần thiết chỉ là một vài cái túi ni lông và một ít thức ăn linh tinh.",
  "We copy, Highroad. What do you have for us?": "Chúng tôi nghe rõ, Highroad. Anh có thông tin gì cho chúng tôi?",
  "Returning to base now.": "Đang trở về căn cứ ngay bây giờ.",
  "After witnessing the death of his rescuer, Doctor Bogatz attempted to flee on his own, but soon fell prey to the zombies himself.": "Sau khi chứng kiến cái chết của người giải cứu mình, Bác sĩ Bogatz đã cố gắng tự bỏ trốn, nhưng ngay sau đó bản thân ông cũng trở thành con mồi cho bọn zombie.",
  "Beer pong opponents get drunk 20% faster.": "Đối thủ chơi trò beer pong sẽ bị say nhanh hơn 20%.",
  "Doesn't suspect the truth.": "Đéo nghi ngờ gì về sự thật.",
  "Barrera": "Barrera",
  "Created 3 Mild Stims.": "Đã chế tạo 3 Chất Kích Thích Nhẹ (Mild Stims).",
  "We'll get payback, but right now we have to keep moving.": "Chúng ta sẽ trả thù, nhưng hiện tại chúng ta phải tiếp tục di chuyển.",
  "Looks like that's all there is to see.": "Có vẻ như đó là tất cả những gì có thể thấy.",
  "Powder and Primer": "Thuốc Súng và Kíp Nổ (Powder and Primer)",
  "Local administrator of the HFF. Worked out of a nearly-abandoned building in the bad part of town. Hard to avoid the impression that something shady was going on over there.": "Quản trị viên địa phương của HFF. Làm việc tại một tòa nhà gần như bị bỏ hoang ở khu vực tồi tàn của thị trấn. Thật khó để tránh khỏi ấn tượng rằng có chuyện gì đó mờ ám đang diễn ra ở đó.",
  "Eldridge agreed to trigger the nuke after our unit is clear of the city. I hope this was the right decision ... it's not the kind of thing you can take back.": "Eldridge đã đồng ý kích hoạt quả bom hạt nhân sau khi đơn vị của chúng ta rời khỏi thành phố. Tôi hy vọng đây là một quyết định đúng đắn ... nó đéo phải là loại chuyện mà cậu có thể rút lại được.",
  "Lange": "Lange",
  "Get \"Sasquatch\" back to Black Friday": "Đưa \"Sasquatch\" trở lại Black Friday",
  "Just like Thanksgiving.": "Cứ như là Lễ Tạ Ơn vậy.",
  "You gotta be smart to survive. There are no second chances. (Bad at FIGHTING)": "Cậu phải thông minh thì mới sống sót được. Đéo có cơ hội thứ hai đâu. (Tệ khoản CHIẾN ĐẤU)",
  "C'mon, asshole. Get in the truck.": "Thôi nào, thằng khốn. Lên xe tải đi.",
  "Where the hell did you learn to fight like that?": "Cậu học kiểu đánh nhau đó ở cái xó xỉnh nào vậy?",
  "You are now FATIGUED and have LOWER STAMINA.": "Bạn hiện đang bị MỆT MỎI (FATIGUED) và bị GIẢM THỂ LỰC (LOWER STAMINA).",
  "We have the highest possible illness prevention chance.": "Chúng ta có cơ hội phòng ngừa bệnh tật cao nhất có thể.",
  "I think I'll just leave that.": "Tôi nghĩ tôi sẽ để thứ đó lại thôi.",
  "Creeping Death. Extra Screamers. Extra Bloaters. Moderate extra damage. Lethal Juggernauts. No map indicators.": "Cái Chết Bò Trườn (Creeping Death). Thêm Screamers. Thêm Bloaters. Sát thương gây ra thêm ở mức vừa phải. Juggernauts Gây Chết Người. Không có chỉ báo trên bản đồ.",
  "Mind the rear flank.": "Chú ý phía sườn sau.",
  "UNLOCKED!": "ĐÃ MỞ KHÓA!",
  "Bullets are bullets. Don't much care where they came from. You can tell your sweethearts their debt's settled.": "Đạn là đạn. Đéo quan tâm lắm việc chúng đến từ đâu. Cậu có thể nói với những người yêu dấu của cậu rằng món nợ của họ đã được giải quyết.",
  "Oh ... well ... yeah, we were involved. I mean, we were working together.": "Ồ ... ừm ... vâng, chúng tôi có tham gia. Ý tôi là, chúng tôi đã làm việc cùng nhau.",
  "Watch out!": "Cẩn thận đấy!",
  "But...": "Nhưng...",
  "Purnell": "Purnell",
  "That's odd.": "Thật kỳ lạ.",
  "Did not make it.": "Đã đéo làm được.",
  "This is your base?": "Đây là căn cứ của các cậu sao?",
  "Meet up with Vince": "Hẹn gặp Vince",
  "Outpost - Drone Recon": "Tiền Đồn (Outpost) - Do Thám Bằng Drone (Drone Recon)",
  "We could use more hands.": "Chúng tôi cần thêm người phụ giúp.",
  "Hey, it's okay, I'm a patient man and you're busy, but I really would like to talk to you.": "Này, đéo sao đâu, tôi là một người kiên nhẫn và cậu đang bận, nhưng tôi thực sự muốn nói chuyện với cậu.",
  "Drone Trailer": "Rơ-moóc Điều Khiển Drone (Drone Trailer)",
  "I've had to live with that decision for ten years, Your Honor. Not a day goes by that I don't wonder if I made the right one.": "Tôi đã phải sống với quyết định đó suốt mười năm qua, thưa Quý tòa. Đéo có một ngày nào trôi qua mà tôi đéo tự hỏi liệu mình có làm đúng đéo.",
  "Found a bunch of shit folks might want.": "Tìm thấy một đống thứ chết tiệt mà mọi người có thể cần.",
  "Mitchell": "Mitchell",
  "Not yet. Someone made a cell phone call from this location.": "Vẫn chưa. Có ai đó đã thực hiện một cuộc gọi điện thoại di động từ vị trí này.",
  "Ritalin": "Thuốc Ritalin",
  "Hold [sprint] and press [ul_melee_attack] to launch an attack guaranteed to knock the target down.": "Giữ [sprint] và nhấn [ul_melee_attack] để tung ra một đòn tấn công đảm bảo sẽ hạ gục mục tiêu.",
  "This heroic survivor wanted to be a part of your community because of your legendary accomplishments.": "Người sống sót anh hùng này muốn trở thành một phần của cộng đồng bạn vì những thành tựu huyền thoại của bạn.",
  "Next person might not be as lucky as me.": "Người tiếp theo có thể đéo may mắn được như tôi đâu.",
  "Yeah, boy, let's do this.": "Đúng thế, chàng trai, hãy làm chuyện này thôi.",
  "Are you gonna just leave us hangin' here?": "Các anh định bỏ mặc chúng tôi lơ lửng ở đây luôn hả?",
  "Three more down with black fever.": "Thêm ba người nữa gục ngã vì sốt đen.",
  "Band Nerd": "Đứa Mọt Sách Ban Nhạc (Band Nerd)",
  "How about these?": "Mấy thứ này thì sao?",
  "%3$s seems to have cheered up a lot. -%1$s": "%3$s có vẻ đã vui lên rất nhiều. -%1$s",
  "Don't forget we still need those explosives if we're gonna break through.": "Đừng quên là chúng ta vẫn cần số thuốc nổ đó nếu muốn đột phá.",
  "You look like hell. You should take some painkillers.": "Trông cậu tàn tạ vãi cức. Cậu nên uống chút thuốc giảm đau đi."
};

const file = 'output/languages/chunks/btxt_chunk_160.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_160.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk160[r.sourceText]) {
    r.translatedText = chunk160[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 160 successfully!');
