const fs = require('fs');
const chunk147 = {
  "Zeds are coming over the wall!": "Lũ Zed đang trèo qua tường!",
  "Looks like we might have a fight on our hands.": "Có vẻ như chúng ta sắp phải động tay động chân rồi.",
  "Unlocks the ability to create Box Mines. REQUIRES A MUNITIONS SHOP.": "Mở khóa khả năng chế tạo Mìn Hộp (Box Mines). YÊU CẦU MỘT XƯỞNG ĐẠN DƯỢC (MUNITIONS SHOP).",
  "The town. It's been on rough times for a while now, but it used to be a damn fine place to live. Raise a family.": "Thị trấn này. Nó đã trải qua một khoảng thời gian khó khăn, nhưng nó từng là một nơi chết tiệt đáng để sống. Để nuôi dưỡng một gia đình.",
  "You got him!": "Cậu tóm được hắn rồi!",
  "Civilian version of the MP 90. Optic included.": "Phiên bản dân sự của khẩu MP 90. Có trang bị sẵn ống ngắm.",
  "Frizzini": "Frizzini",
  "Mm-mm.": "Ừm-hửm.",
  "Can't seem to engage with other people on a human level. Might be a sociopath. Or just an introvert.": "Có vẻ như đéo thể giao tiếp với người khác ở một mức độ bình thường của con người. Có thể là một kẻ thái nhân cách. Hoặc chỉ là một người hướng nội.",
  "Posit one one lima november nine nine kilo six one quebec. [message end tone]": "Tọa độ một một lima november chín chín kilo sáu một quebec. [âm báo kết thúc tin nhắn]",
  "Need a pinch hitter here!": "Cần một người thay thế ở đây!",
  "SURVIVAL TACTICS: Recruiting survivors": "CHIẾN THUẬT SINH TỒN: Chiêu mộ những người sống sót",
  "Hell, yeah.": "Chết tiệt, chuẩn rồi đấy.",
  "We won't let you down.": "Chúng tôi sẽ đéo làm anh thất vọng đâu.",
  "Kill 100 Zombies with Heavy Weapons. (Breakdown Level 4 or Higher)": "Tiêu diệt 100 Zombie bằng Vũ Khí Hạng Nặng. (Breakdown Cấp 4 trở lên)",
  "You got yourself a deal.": "Cậu có một thỏa thuận rồi đấy.",
  "Yeah yeah, quit begging already. I'll help ya find 'em.": "Rồi rồi, bớt van xin đi. Tôi sẽ giúp cậu tìm bọn chúng.",
  "%1$s went out on a supply run and found a really nice stash of resources. They'd like some help getting it back to base.": "%1$s đã ra ngoài tìm kiếm nhu yếu phẩm và tìm thấy một kho tài nguyên rất ngon nghẻ. Họ muốn một chút giúp đỡ để mang nó về căn cứ.",
  "Infirmary's no damn good if we don't have somebody to run it.": "Bệnh xá (Infirmary) đéo có cái tác dụng mẹ gì nếu chúng ta đéo có ai điều hành nó cả.",
  "This is Judge Lawton. Earlier today, our scouts informed me that they have identified multiple infestations in the downtown Marshall area.": "Đây là Thẩm phán Lawton. Đầu ngày hôm nay, các trinh sát của chúng tôi đã báo cáo rằng họ đã xác định được nhiều ổ dịch (infestations) ở khu vực trung tâm thị trấn Marshall.",
  "Look, you're not alone. Everybody's scared. Just don't do anything stupid, okay?": "Nghe này, cậu đéo đơn độc đâu. Ai cũng sợ hãi cả. Chỉ là đừng làm trò gì ngu ngốc, được đéo?",
  "Caroline": "Caroline",
  "Glad you came by. Fact is, we're never gonna last on our own. Not like you folks have.": "Rất vui vì các cậu đã ghé qua. Sự thật là, chúng tôi sẽ đéo bao giờ có thể tự mình trụ lại được. Đéo giống như các cậu.",
  "And on your left, we have hungry zombies.": "Và ở bên trái của các bạn, chúng ta có những con zombie đói khát.",
  "Do you want a pack of these things on your ass?": "Mày có muốn một bầy những thứ này đuổi theo đít mày đéo?",
  "Sign In": "Đăng Nhập",
  "That didn't go so well.": "Chuyện đó đã diễn ra đéo suôn sẻ cho lắm.",
  "Jars": "Lọ Giai Đoạn (Jars)",
  "Anything I can do to make you feel better?": "Tôi có thể làm gì để cậu cảm thấy khá hơn đéo?",
  "We are clear!": "Chúng ta an toàn rồi!",
  "[%s] is not allowed for this action.": "[%s] đéo được phép cho hành động này.",
  "Sir, what's the plan now?": "Thưa ngài, kế hoạch bây giờ là gì?",
  "Shot in his sleep by Alan Gunderson.": "Bị bắn chết trong lúc đang ngủ bởi Alan Gunderson.",
  "ATTITUDE: Sulking": "THÁI ĐỘ: Hờn dỗi",
  "Up front!": "Ở phía trước!",
  "But they want some kinda \"neutral observer\" or whatever the fuck. Job figured maybe you'd put their minds at ease.": "Nhưng chúng muốn một kiểu \"người quan sát trung lập\" hay bất cứ cái thứ quái quỷ gì đó. Job nghĩ có lẽ cậu sẽ giúp chúng cảm thấy yên tâm.",
  "The Army's been pretty quiet since that last incident. Let's hope it stays that way. -%1$s": "Quân Đội khá im hơi lặng tiếng kể từ vụ việc lần trước. Hãy hy vọng mọi chuyện vẫn tiếp tục như vậy. -%1$s",
  "SitRep: Milwaukee": "Báo Cáo Tình Hình (SitRep): Milwaukee",
  "Feels like a bunch of tiny goblins are doing a clog dance through my bowels. This is what we get for not having someone who knows how to cook worth a damn. - %1$s": "Cảm giác cứ như có một lũ yêu tinh tí hon đang nhảy múa ầm ĩ trong ruột tôi vậy. Đây là hậu quả của việc đéo có một ai biết nấu ăn cho tử tế cả. - %1$s",
  "Oh, son, you just asking for a whooping!": "Ồ, con trai, cậu đang tự chuốc lấy một trận đòn đấy!",
  "I think we just started a parade.": "Tôi nghĩ chúng ta vừa bắt đầu một cuộc diễu hành đấy.",
  "Dude is now missing.": "Gã đó hiện đang mất tích.",
  "Hey look, I didn't come out here to talk about my feelings, alright?": "Này nghe đây, tôi đéo ra đây để nói về cảm xúc của mình đâu, được đéo?",
  "Roger that, sir. You can count on us.": "Rõ rồi, thưa ngài. Ngài có thể trông cậy vào chúng tôi.",
  "Dad? Dad, are you there?": "Bố? Bố có ở đó đéo?",
  "You have new Events in your Journal! Press D-pad [xi_dpad_up] to open your Journal and review things that have happened to you on the Events page.": "Bạn có Sự kiện (Events) mới trong Nhật ký (Journal)! Nhấn D-pad [xi_dpad_up] để mở Nhật ký của bạn và xem lại những gì đã xảy ra trên trang Sự kiện.",
  "Good. You made it.": "Tốt. Cậu đã đến kịp.",
  "Rugged exterior, measured precision.": "Vẻ ngoài thô kệch, nhưng độ chính xác được đo lường kỹ càng.",
  "I remember that the charges were dismissed. Nobody could prove anything.": "Tôi nhớ là các cáo buộc đã bị bãi bỏ. Đéo ai có thể chứng minh được điều gì cả.",
  "Suturing Needles": "Kim Khâu Phẫu Thuật",
  "Walk with Job": "Đi bộ với Job",
  "This place looks ... secure.": "Nơi này trông có vẻ ... an toàn đấy.",
  "Hey! Listen ... I picked something up over the radio.": "Này! Nghe này ... Tôi vừa bắt được tín hiệu gì đó qua radio.",
  "True Believer": "Kẻ Cuồng Tín",
  "Signed Out": "Đã Đăng Xuất",
  "Escort the Survivor": "Hộ Tống Người Sống Sót",
  "We're really short on guns.": "Chúng ta thực sự đang rất thiếu súng.",
  "Blunt Weapon Specialization Improved!": "Chuyên Môn Vũ Khí Cùn (Blunt Weapon Specialization) Đã Được Cải Thiện!",
  "Let's execute this plan.": "Hãy tiến hành kế hoạch này thôi.",
  "Let me know if you want to run back together.": "Hãy cho tôi biết nếu cậu muốn cùng chạy về.",
  "Barrels of Fuel": "Vài Thùng Nhiên Liệu (Fuel)",
  "Adita": "Adita",
  "Defensive Skill": "Kỹ Năng Phòng Thủ",
  "Yeah, well, we're gonna get through them whether they're crazy or not.": "Phải, ừ thì, chúng ta sẽ vượt qua bọn chúng dù cho chúng có điên cuồng hay đéo.",
  "Piece together a few portable snacks from general food supplies.": "Gộp vài món đồ ăn vặt có thể mang theo từ nguồn cung cấp thức ăn chung.",
  "No pain, no gain, right?": "Đéo chịu đựng thì đéo có thành quả, đúng đéo?",
  "House hunting.": "Đi săn nhà.",
  "You know I never once broke curfew growing up? Never snuck out of the house, never dated anybody my parents didn't approve of, never took a road trip to Mexico and forgot most of the details in a tequila-soaked haze.": "Cậu biết đéo, hồi còn nhỏ tôi chưa từng một lần phá lệnh giới nghiêm cơ? Chưa từng lẻn ra khỏi nhà, chưa từng hẹn hò với ai mà bố mẹ tôi đéo chấp thuận, chưa từng có một chuyến đi phượt tới Mexico và quên sạch hầu hết các chi tiết trong cơn say tequila bí tỉ.",
  "Short of sitting in our bunks jerking off, all we were allowed to do with our free time was come up here, swim a few laps, and try to pretend MREs were suitable barbecue fodder.": "Ngoại trừ việc ngồi trên giường và sục cặc, thì tất cả những gì chúng tôi được phép làm trong thời gian rảnh là lên đây, bơi vài vòng, và cố gắng giả vờ rằng đống MRE (Khẩu phần ăn sẵn) là đồ nướng BBQ hảo hạng.",
  "Sure. So long, Alan.": "Chắc chắn rồi. Tạm biệt, Alan.",
  "Potent Stims": "Thuốc Kích Thích Cực Mạnh",
  "Look, somewhere to hide!": "Nhìn kìa, có chỗ để trốn!",
  "Well that's just fucked!": "Chà thế thì đúng là khốn nạn thật!",
  "Grow 10 Food in the Garden. (Breakdown Level 3 or Higher)": "Trồng 10 Thức Ăn (Food) trong Vườn. (Breakdown Cấp 3 trở lên)",
  "Comms": "Liên Lạc",
  "Disaster": "Thảm Họa",
  "We're pretty under-supplied for DIY projects. Keep an eye out for building materials.": "Chúng ta đang khá thiếu thốn nguồn cung cho các dự án tự làm (DIY). Hãy để mắt tìm kiếm vật liệu xây dựng (building materials) nhé.",
  "Eat another fuckin' steak.": "Ăn thêm một miếng bít tết chết tiệt nữa đi.",
  "100% faster construction. +10 Material storage capacity.": "Tốc độ xây dựng nhanh hơn 100%. +10 dung lượng lưu trữ Vật liệu (Material).",
  "Jimena": "Jimena",
  "The Sheriff? Yeah, he went out about an hour ago. Said he was gonna hunt down this feral bastard that's been stalking our patrols.": "Cảnh sát trưởng á? Vâng, ông ấy đã ra ngoài khoảng một giờ trước rồi. Nói rằng ông ấy sẽ đi săn cái con feral khốn kiếp luôn rình rập các cuộc tuần tra của chúng ta.",
  "Building materials and fuel.": "Vật liệu xây dựng (Building materials) và nhiên liệu (fuel).",
  "CONTACT: Construction Advice": "LIÊN HỆ: Lời Khuyên Xây Dựng",
  "A single powerful strike from an overhead UAV. An infrared beacon attracts zombies to the target zone just before the strike.": "Một đòn oanh tạc mạnh mẽ duy nhất từ UAV trên không. Một bộ phát tín hiệu hồng ngoại sẽ thu hút bọn zombie vào khu vực mục tiêu ngay trước khi nổ.",
  "Beck": "Beck",
  "Isabella": "Isabella",
  "What did I say? No cars!": "Tôi đã nói gì nào? Đéo dùng ô tô!",
  "Sweet, warm, and full of love.": "Ngọt ngào, ấm áp, và tràn đầy tình yêu thương.",
  "Sounds like we have at least one horde inbound.": "Nghe như thể chúng ta có ít nhất một bầy horde đang kéo tới.",
  "Contacted a new group of survivors.": "Đã liên lạc với một nhóm người sống sót mới.",
  "Danforth standard police cruiser. They have great speed and handling. Seats four (two uncomfortably).": "Xe cảnh sát tiêu chuẩn của Danforth. Chúng có tốc độ và khả năng xử lý tuyệt vời. 4 chỗ ngồi (hai chỗ hơi chật chội).",
  "Westmoreland": "Westmoreland",
  "If anything survived that, you've got bigger problems.": "Nếu có thứ gì đó có thể sống sót sau cú đó, cậu sẽ gặp phải những rắc rối lớn hơn đấy.",
  "Stop! Hammer Time!": "Dừng Lại! Đến Giờ Búa Tạ Rồi!",
  "New Survey Point Discovered!": "Phát Hiện Điểm Quan Sát (Survey Point) Mới!",
  "Spends more time at the gym than at home, and could teach half the classes there. (Fitness Expert)": "Dành nhiều thời gian ở phòng tập gym hơn là ở nhà, và có thể dạy được một nửa số lớp học ở đó. (Chuyên Gia Thể Hình)",
  "Funny how differently you see the place when you're avoiding zombies.": "Thật buồn cười khi cậu nhìn thấy nơi này theo một cách khác hẳn lúc cậu đang trốn tránh bọn zombie.",
  "Vitality will gradually recover while resting at home. It should take about 20 hours to get back to full Vitality.": "Sinh lực (Vitality) sẽ dần dần phục hồi trong khi nghỉ ngơi tại căn cứ. Sẽ mất khoảng 20 giờ để phục hồi lại toàn bộ Sinh lực.",
  "COMMUNITY: Concern": "CỘNG ĐỒNG: Nỗi lo ngại",
  "Comin' up empty here.": "Trắng tay ở đây rồi."
};

const file = 'output/languages/chunks/btxt_chunk_147.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_147.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk147[r.sourceText]) {
    r.translatedText = chunk147[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 147 successfully!');
