const fs = require('fs');

const map = {
  "It's a WHOLE bunch of explosives stuffed into a pipe. Extra shrapnel means more dead zombies.": "Cả ĐỐNG thuốc nổ được nhét chung vào một cái ống nước. Thêm miểng văng thì thêm lũ thây ma nát bét.",
  "Lights an area up. Good for night-time zombie spotting, or night-time zombie luring.": "Thắp sáng cả một khu vực. Dùng để soi xác sống hoặc dụ chúng nó vào ban đêm đều ngon.",
  "Box Mine": "Mìn Hộp",
  "So what if it's a bunch of nuts and bolts in an old paint can? It still explodes.": "Nhét đầy đai ốc với bu lông vô lon sơn cũ thì đã sao? Nó vẫn nổ tung xác như thường.",
  "Flame Fougasse": "Mìn Lửa Fougasse",
  "Like a Molotov, but this one's pressure sensitive.": "Giống bom xăng Molotov, nhưng quả này được kích nổ bằng áp suất.",
  "Whistling Box Mine": "Mìn Hộp Phát Âm",
  "Cram a noisemaker into an improvised mine, and it lures the zombies in before it explodes. Nice.": "Nhét đồ phát tiếng ồn vào quả mìn tự chế để dụ tụi thây ma lại gần trước khi nổ bùm. Hay đấy.",
  "S-Mine": "Mìn S-Mine",
  "Pops up to head height for optimal zombie killing.": "Nảy lên ngang đầu để thổi bay sọ lũ thây ma cho chuẩn.",
  "Stockpiled since 1974, this example came out of an EOD training container.": "Nằm trong kho từ năm 1974, đồ chơi này tuồn ra từ một thùng đạn huấn luyện tháo gỡ bom mìn.",
  "Artillery Marker": "Pháo Hiệu Gọi Pháo Binh",
  "Toss this to target an area for artillery.": "Ném cái này để đánh dấu mục tiêu nã pháo.",
  "Sudden noises are great for grabbing attention. (Best to toss these and then run or hide.)": "Mấy tiếng động bất thình lình rất dễ hút sự chú ý. (Ném xong thì lo mà chạy trốn cho lẹ.)",
  "Wind-Up Alarm Clock": "Đồng Hồ Báo Thức Dây Cót",
  "Even dead, people still hate this sound. Brings the zombies running.": "Dù chết rồi người ta vẫn ghét cay ghét đắng cái tiếng này. Nó gọi lũ thây ma tới ầm ầm.",
  "Kitchen Timer": "Đồng Hồ Hẹn Giờ Nấu Ăn",
  "Set the timer and run like hell. Zombies'll come running like it's Sunday dinner.": "Vặn giờ rồi cắm đầu mà chạy. Lũ thây ma sẽ mò tới cứ như đang có tiệc tối Chủ Nhật vậy.",
  "Talking Doll": "Búp Bê Biết Nói",
  "This one's just plain creepy. Seems to attract the zombies, though.": "Con búp bê này rùng rợn vãi. Nhìn chung là dụ được đám thây ma.",
  "Improvised Suppressor": "Ống Giảm Thanh Tự Chế",
  "Cuts down gunshot noise. Made this one out of an oil can, figure it's only good for 10 shots or so.": "Giảm bớt tiếng súng. Cái này được làm từ lon dầu, tao đoán chắc bắn được cỡ 10 phát là nát.",
  "Handcrafted Suppressor": "Ống Giảm Thanh Thủ Công",
  "Cuts down gunshot noise. Decent construction; this one should last 30 shots, give or take.": "Giảm tiếng ồn của súng. Cấu tạo cũng tàm tạm; chắc xài được cỡ 30 phát.",
  "Machined Suppressor": "Ống Giảm Thanh Máy Tiện",
  "Cuts down gunshot noise. Not quite professional quality, but might last for a good 50 shots.": "Giảm âm tốt. Dù chưa đạt chuẩn chuyên nghiệp, nhưng chắc trụ được tầm 50 phát bắn.",
  "What a piece of crap. Guess I could use it to break a window.": "Đúng là một đống rác rưởi. Chắc dùng để đập vỡ cửa sổ thì được.",
  "I never meant to... hell, I never thought I was even capable of something like that. I guess you never really know what you're capable of until you're three days out from your last meal and some kid grabs the last can of tuna fish out from under you, huh? Learned a lot of things that day. Like how it feels to crush the life out of somebody's throat. I don't even know who I'm writing this note to. God? Myself? That kid? Hell, whoever you are, I'm sorry.": "Tôi chưa bao giờ cố ý... mẹ kiếp, tôi chưa bao giờ nghĩ mình có thể làm ra chuyện như vậy. Chắc là bạn sẽ không bao giờ thực sự biết mình có khả năng làm gì cho đến khi bạn đói lả ba ngày và bị một thằng nhóc nẫng mất hộp cá ngừ cuối cùng ngay trước mắt, đúng không? Tôi đã học được nhiều điều vào ngày hôm đó. Kiểu như cảm giác nghiền nát yết hầu của một người là như thế nào. Tôi cũng đéo biết mình đang viết cái mảnh giấy này cho ai. Cho Chúa? Cho chính mình? Cho thằng nhóc đó? Khốn kiếp, dù mày là ai, tao xin lỗi.",
  "Hasty scribblings in pencil on the back of an office envelope.": "Những nét chữ viết vội bằng bút chì trên lưng một phong bì văn phòng.",
  "Day 9. The attacks are getting more frequent now. They know we're here. Ammo's running low, but it's the stress that's really getting to us. Can't sleep with all those screamers out there. Vasquez is taking it the worst--if you find this note, and you find us dead from gunshot wounds, look at Vasquez.": "Ngày thứ 9. Các cuộc tấn công dạo này ngày càng dồn dập. Bọn chúng biết chúng tôi đang ở đây. Đạn dược sắp cạn, nhưng sự căng thẳng mới là thứ thực sự giết chết chúng tôi. Không ai ngủ được với mấy con quái vật hay gào thét ngoài kia. Vasquez là người hoảng loạn nhất--nếu có ai tìm thấy mảnh giấy này, và thấy chúng tôi chết vì vết thương do đạn bắn, thì hãy nhìn Vasquez.",
  "Diary Page": "Trang Nhật Ký",
  "Black pen on a yellow legal notepad, there is a bloody thumbprint in the corner.": "Bút mực đen viết trên sổ tay pháp lý màu vàng, có một dấu vân tay đầy máu ở góc.",
  "Never realized how much food three people can go through in a week. When we found that Tartan Mart nobody had hit yet, we thought we'd taken enough for a month, but now it's a week later and the food's all gone and that Tartan Mart has been totally picked over... and now I don't know what to do.": "Chưa bao giờ tôi nhận ra ba người có thể ngốn hết bao nhiêu thức ăn trong một tuần. Khi chúng tôi tìm thấy cửa hàng Tartan Mart chưa bị ai hôi của, chúng tôi tưởng đã lấy đủ phần ăn cho cả tháng. Nhưng giờ mới được một tuần mà đồ ăn đã hết nhẵn, cái siêu thị đó thì đã bị vét sạch bách... và giờ tôi không biết phải làm cái mẹ gì nữa.",
  "Blue ballpoint pen on the back of a Tartan Mart inventory order form.": "Chữ bút bi xanh viết trên lưng một tờ đơn đặt hàng của Tartan Mart.",
  "I'm leaving this note for my family and friends. If that's not you, put this note down before the poison in the ink seeps into your skin and kills you. If it is you, don't worry, the poison thing was a bluff. I'm going across the river to find out what those Army pigs know. If I'm not back by Thursday, assume I've been compromised by government mind-lasers and you should shoot me on sight.": "Tao để lại tờ giấy này cho gia đình và bạn bè. Nếu mày không phải là họ, bỏ tờ giấy xuống ngay trước khi chất độc trong mực ngấm vào da chết mẹ mày đi. Còn nếu là các cậu, đừng lo, vụ chất độc tao xạo l*n thôi. Tao sẽ qua sông để xem lũ lợn Quân Đội biết được những gì. Nếu tới Thứ Năm mà tao chưa về, hãy coi như tao đã bị tia laser tẩy não của chính phủ bắn trúng và cứ thế mà bắn vỡ sọ tao nếu gặp nhé.",
  "Black felt-tip pen on a cardboard box top.": "Bút lông đen viết trên nắp một hộp carton.",
  "This note is for John. And for Sara. It's for Lisa and Geraldo and Mahz and all of them. I'm the only one left. Guys, I'm sorry this is the best memorial I can give you. I'm gonna leave this note someplace I hope people will find it. I'm gonna leave it with some pictures from that Vegas weekend last year. Hopefully it finds its way to your people. Love all you guys.": "Mảnh giấy này dành cho John. Cho Sara. Cho Lisa, Geraldo, Mahz và tất cả mọi người. Tôi là người duy nhất còn sống sót. Xin lỗi các bạn vì đây là món đồ tưởng niệm duy nhất tôi có thể để lại. Tôi sẽ đặt nó ở một nơi mà tôi hi vọng có ai đó tìm thấy. Tôi sẽ kẹp nó cùng với vài bức ảnh chụp chuyến đi Vegas năm ngoái. Hi vọng nó sẽ về được tay người nhà các bạn. Yêu tất cả mọi người.",
  "Blue ballpoint pen on pink flowery stationery, sealed in a plastic sandwich bag.": "Viết bằng bút bi xanh trên một tờ giấy in hoa màu hồng, được bọc trong một túi nilon đựng sandwich.",
  "Dear Anthony, We waited as long as we could. Your father isn't willing to stay any longer. I suppose he's right. We can't risk everyone else. I hope you find this note and that you come find us. We didn't want to leave without you. We love you. Be safe.": "Anthony thân yêu, nhà mình đã đợi lâu nhất có thể rồi. Bố con không muốn nán lại thêm nữa. Mẹ nghĩ ông ấy đúng. Chúng ta không thể đặt tính mạng của những người khác vào vòng nguy hiểm. Mẹ hi vọng con sẽ tìm thấy mảnh giấy này và đến tìm bố mẹ. Bố mẹ không hề muốn phải rời đi mà không có con. Yêu con. Hãy giữ an toàn nhé.",
  "Red pen in an envelope with the name, \"Anthony\" on the front.": "Chữ viết mực đỏ trong một phong bì có đề tên \"Anthony\" ở mặt trước.",
  "Carly, if you get this note, STAY HERE. I heard a rumor you were in Danforth, so I went to check it out, but just in case it's wrong, I want you to wait for me here. Lock the doors, there's food and ammo in the house, and don't let anyone in who isn't me. Okay? I'll see you soon.": "Carly, nếu em đọc được dòng này, HÃY Ở YÊN ĐÂY. Anh nghe đồn em đang ở Danforth, nên anh tới đó để kiếm, nhưng phòng khi tin vịt, anh muốn em hãy chờ anh ở đây. Khóa kín cửa, trong nhà có đồ ăn và đạn, đừng cho bất cứ ai vào nếu đó không phải là anh. Rõ chưa? Anh sẽ gặp em sớm thôi.",
  "Black pen on a yellow sticky-note.": "Chữ viết mực đen trên tờ giấy ghi chú màu vàng.",
  "Dear Colin, I'm leaving you. I can't take the lies, or the paranoia, or the constant harping about government conspiracy. I'm going to stay with my mother up north. Don't try to find me. - Elsa. P.S. I took all your guns, your ammo, and your ridiculous MREs and I threw them in the river. Serves you right, you pig.": "Colin à, tôi bỏ anh. Tôi không thể chịu đựng thêm những lời nói dối, sự hoang tưởng, hay những điệp khúc nhảm nhí về thuyết âm mưu chính phủ nữa. Tôi sẽ lên miền Bắc sống với mẹ. Đừng có cố tìm tôi. - Elsa. Tái bút: Tôi đã ném hết súng đạn và mấy khẩu phần ăn MRE lố lăng của anh xuống sông rồi. Đáng đời nhà anh, đồ con lợn.",
  "Blue pen on crumpled notepaper.": "Bút mực xanh viết trên một tờ giấy nhớ nhàu nát.",
  "Dear Diary, HOLY SHIT IT WORKED! When Skyler said he found a ritual that could bend the dead to our black wills and finally take revenge on assholes like Ricky Valdez I kinda thought he was full of shit, but IT WORKED! It's all over the news, the dead are rising from the grave to eat the flesh of the living! BRB, I'm going to try out my sweet zombie-controlling powers!": "Nhật ký thân mến, ĐỆCH MẸ NÓ HIỆU NGHIỆM RỒI! Khi thằng Skyler bảo nó tìm ra một nghi thức có thể khiến lũ người chết phục tùng bóng tối của tụi này để đi trả thù bọn khốn như Ricky Valdez, tao đã nghĩ nó xạo l*n, nhưng MÀ NÓ THÀNH CÔNG RỒI! Báo đài đưa tin ầm ầm, người chết đội mồ sống dậy ăn thịt người sống kìa! Chờ xíu tao quay lại ngay, tao phải đi test thử siêu năng lực điều khiển zombie ngọt ngào này mới được!",
  "Red ballpoint in a small, leather bound diary.": "Chữ viết bút bi đỏ trong một cuốn sổ nhật ký bọc da nhỏ.",
  "Dear whatever prick came in here to loot my house: one can of food in this kitchen is poisoned. Good luck, asshole.": "Gửi thằng khốn nạn nào dám lẻn vào hôi của nhà tao: có một lon đồ ăn trong bếp đã bị tẩm thuốc độc đấy. Chúc may mắn nhé, đồ chó.",
  "Red felt-tip pen on construction paper, large lettering.": "Chữ in hoa lớn, viết bằng bút dạ đỏ trên giấy thủ công.",
  "Project: PALLAS Phase 1 complete. Evaluation: Vastly exceeded expected parameters. Phase 2 pending reestablishment of proper chain of command.": "Dự án: PALLAS Giai đoạn 1 hoàn tất. Đánh giá: Vượt xa mọi thông số kỳ vọng. Giai đoạn 2 đang chờ việc tái thiết lập chuỗi chỉ huy.",
  "Black pen on a military form 469, labeled \"Duty Limiting Condition Report\". Signed by Lt Col Schwalier.": "Chữ viết mực đen trên biểu mẫu quân sự 469, với tựa đề \"Báo cáo Hạn chế Thi hành Nhiệm vụ\". Có chữ ký của Trung tá Schwalier.",
  "If you think this thing \"just happened,\" you're fooling yourself. Someone knows what caused this, someone is BEHIND this. Don't believe me? Then riddle me this: why did the Army start ferrying people in two days BEFORE the first confirmed attacks?": "Nếu mày nghĩ vụ này \"tự nhiên mà có\", thì mày đang tự huyễn hoặc bản thân rồi. Ai đó biết nguyên nhân gây ra dịch bệnh, ai đó ĐỨNG SAU chuyện này. Không tin tao à? Thế thì giải thích coi: tại sao Quân Đội lại bắt đầu chuyển người vào tận hai ngày TRƯỚC KHI các vụ tấn công đầu tiên được xác nhận?",
  "Typewriter (yes, an actual typewriter) on typing paper.": "Được đánh bằng máy chữ (đúng, là một cái máy đánh chữ thật) trên giấy in.",
  "Weird stuff on the news, and today Job Wilkerson pays me a call and says I can pay him off in bullets and food instead of cash. What the hell's going on?": "Tin tức trên TV có mấy thứ kỳ quặc, và hôm nay thằng Job Wilkerson gọi điện cho tôi bảo tôi có thể trả nợ cho nó bằng đạn và đồ ăn thay vì tiền mặt. Cái quái gì đang diễn ra vậy?",
  "Blue felt-tip pen on white notepad. Three extra question marks.": "Bút dạ xanh viết trên sổ tay trắng. Kèm theo ba dấu chấm hỏi nhấn mạnh.",
  "Aunt Helen: Took me ten years, but I finally found it. Proof that the sheriff buried evidence in my cousin's case so he and that damned judge could keep their conviction rate intact. I was supposed to show it to Councilman Santos' friend at the Marshall Gazette today, but he had to reschedule. Something about a major story breaking at the hospital.": "Dì Helen: Mất đến mười năm, nhưng cuối cùng cháu cũng đã tìm ra. Bằng chứng cho thấy tay cảnh sát trưởng đã ém nhẹm chứng cứ trong vụ án của em họ cháu, để hắn và lão thẩm phán khốn khiếp kia có thể giữ nguyên tỷ lệ phá án. Cháu định cho bạn của Ủy viên Santos ở toà soạn báo Marshall Gazette xem vào hôm nay, nhưng ông ấy phải dời lịch. Có vẻ như có vụ gì động trời vừa nổ ra ở bệnh viện.",
  "Computer printout on personal letterhead, mailed two weeks ago.": "Được in từ máy tính trên một tờ giấy cá nhân, bưu điện đóng dấu gửi từ hai tuần trước.",
  "Strain 854b shows a remarkable resistance to traditional antibiotic countermeasures. Estimated probability of successful containment: 13.48%": "Chủng vi khuẩn 854b đang cho thấy khả năng kháng kháng sinh truyền thống một cách kinh khủng. Tỷ lệ kiềm chế dịch bệnh thành công ước tính: 13,48%",
  "Black pen on a heavily redacted CDC NORS (WDT) form.": "Bút mực đen viết trên mẫu đơn CDC NORS (WDT) bị gạch xóa chi chít.",
  "I've waited my whole life for this moment. My katana is sharp, my .50 caliber is fully loaded, and my trench coat is freshly dry-cleaned. Time to kill some zombies.": "Tao đã chờ đợi khoảnh khắc này suốt cả cuộc đời. Thanh Katana đã mài sắc, khẩu .50 cal đã nạp đầy đạn, áo khoác măng-tô cũng vừa mới sấy khô. Tới giờ đi gặt thây ma rồi.",
  "White paint pen on black construction paper.": "Bút sơn trắng viết trên nền giấy thủ công đen.",
  "MISSING GIRL: Have you seen me? Alex Collins, 5'6\" 113 lbs., brown eyes, purple-dyed hair. REWARD OFFERED, NO QUESTIONS ASKED. We just want our little girl home.": "TÌM BÉ GÁI ĐI LẠC: Bạn có thấy tôi không? Alex Collins, 5'6\" 113 lbs, mắt nâu, tóc nhuộm tím. CÓ HẬU TẠ, KHÔNG HỎI LÝ DO. Chúng tôi chỉ cần con gái mình được về nhà.",
  "Color photocopy, with several pictures.": "Bản in màu, đính kèm vài tấm ảnh.",
  "Harlan, can you pick up a carton of milk at the Tartan Mart next time you're out? I want to bake a cake for Lucy's birthday. Thanks! - Sandy xoxoxo": "Harlan, lần tới anh ra ngoài có thể mua giúp em một hộp sữa ở Tartan Mart được không? Em muốn nướng một cái bánh kem cho sinh nhật của Lucy. Cảm ơn anh! - Sandy xoxoxo",
  "Blue pen on a sticky note that reads, \"To do list\".": "Mực xanh viết trên tờ giấy nhớ có dòng chữ \"Những việc cần làm\".",
  "Hi Ma. Dunno why I keep writing these notes to you--I'm a little too old to believe you're reading them up in Heaven. Habit, I guess. Well, anyways, Joanie had the baby, but it was a pretty tough labor. She's staying with her folks out west for a little while, but I've got to stay here and keep working. It's hard, knowing she and little Max are so far away, but that's what men do for their families, right? That's what you and dad taught me, anyway. Okay, Ma, I gotta go--something's on the TV about an emergency evacuation order or something. I better go see what it is. Love to Grandma and Grandpa. - Eugene": "Chào Mẹ. Chẳng hiểu sao con cứ liên tục viết mấy mảnh giấy này cho mẹ--Con đã quá già để tin rằng mẹ có thể đọc được chúng từ trên Thiên đường. Chắc là thói quen thôi. Dù sao thì, Joanie cũng đã sinh em bé, nhưng cô ấy đã có một ca chuyển dạ khá khó khăn. Cô ấy đang ở với nhà đẻ ở miền Tây một thời gian, nhưng con thì phải ở lại đây cày cuốc. Thật khó khăn khi biết cô ấy và bé Max đang ở xa như vậy, nhưng đó là điều mà một người đàn ông phải làm cho gia đình, đúng không mẹ? Đó là điều mà mẹ và bố đã dạy con mà. Được rồi, Mẹ, con phải đi đây--trên TV đang chiếu gì đó về lệnh sơ tán khẩn cấp. Con ra xem thử coi có chuyện gì. Gửi tình yêu đến Ông và Bà nội. - Eugene",
  "Blue ballpoint pen in a small, well-worn notebook.": "Bút bi xanh viết trong một cuốn sổ tay nhỏ, sờn cũ.",
  "Kate - Your dad's still not back from the commissary at the ranger station. I'm going to go see what's keeping him. If I'm not back before you wake up, stay in the cabin and have a granola bar for breakfast. No using the camp stove unsupervised. - Mom": "Kate - Bố con vẫn chưa về từ trạm kiểm lâm. Mẹ sẽ đi xem có chuyện gì giữ chân ông ấy. Nếu mẹ không về trước lúc con thức dậy, hãy ở yên trong cabin và ăn sáng bằng một thanh ngũ cốc. Không được dùng bếp dã ngoại khi không có người lớn. - Mẹ",
  "Black pen on the back of a granola bar box.": "Bút đen viết trên mặt sau của hộp ngũ cốc.",
  "This cell phone has a cracked screen and almost no battery life left, but the camera function shows a series of images of shambling figures lurking into the light of a campfire while some college kids look on. The last image shows one of the figures grabbing a young man by the shoulders. The call log shows seven dropped calls to 911.": "Chiếc điện thoại này đã bị vỡ nát màn hình và gần như cạn kiệt pin, nhưng bên trong mục thư viện ảnh vẫn hiển thị một loạt những bóng người dặt dẹo đang lảng vảng vào ánh lửa trại trong khi mấy đứa sinh viên đại học đang ngồi nhìn. Bức ảnh cuối cùng là cảnh một trong những sinh vật đó đang chộp lấy vai một thanh niên. Nhật ký cuộc gọi cho thấy bảy cuộc gọi thất bại tới số 911.",
  "Damaged cellphone, stuck on the \"My Photos\" folder.": "Chiếc điện thoại vỡ nát, màn hình đang bị đơ ở mục \"Hình ảnh của tôi\".",
  "Saw some creepy dude hanging out by the public restrooms. He looked drunk. Maybe stoned. Stank too. Gross. I decided to hold it.": "Thấy một gã rùng rợn nào đó đang lảng vảng quanh nhà vệ sinh công cộng. Hắn trông như bị say rượu. Hoặc là phê cần. Thúi hoắc nữa. Tởm vãi. Tao quyết định nín đái luôn.",
  "Silver felt-tip pen, cursive, on cream-colored diary paper, the \"O\" in gross has a smiley face in it.": "Bút dạ màu bạc, viết tay cách điệu trên giấy nhật ký màu kem, chữ \"O\" trong từ tởm được vẽ thêm một biểu tượng mặt cười.",
  "Ranger Gunderson - We apologize, but despite your repeated requests we cannot authorize the purchase of any .50 caliber hunting rifles for the ranger station. We would like to remind you that bears have not been seen on Mt. Tanner in over forty years, and moreover large-caliber rifles are not a recommended means of dealing with rogue bears.": "Ranger Gunderson - Chúng tôi rất lấy làm tiếc, nhưng bất chấp những yêu cầu liên tục của anh, chúng tôi không thể cấp phép mua bất kỳ loại súng săn .50 caliber nào cho trạm kiểm lâm. Chúng tôi muốn nhắc anh rằng chưa ai thấy gấu trên Núi Tanner trong hơn bốn mươi năm nay, và hơn nữa súng trường cỡ nòng lớn không phải là phương tiện được khuyên dùng để đối phó với những con gấu nổi điên.",
  "Compter printout on official County Parks Administration letterhead.": "Bản in máy tính trên văn bản hành chính của Cơ quan Quản lý Công viên Quận.",
  "Mortar Marker": "Pháo Hiệu Gọi Súng Cối",
  "Toss this to target an area for mortar.": "Ném cái này để đánh dấu mục tiêu nã súng cối.",
  "Drone Strike Marker": "Đèn Cầy Đánh Dấu Không Kích",
  "Toss this to target an area for a Drone Strike.": "Ném cái này để đánh dấu mục tiêu Không Kích bằng máy bay không người lái.",
  
  "Pistol: G 17C": "Súng Lục (Pistol) G 17C",
  "Very popular \"G\" line of firearms. Polymer frame.": "Dòng súng \"G\" cực kỳ phổ biến. Khung bọc polyme.",
  "Pistol: Bz 75": "Súng Lục (Pistol) Bz 75",
  "A favorite of police forces the world over.": "Vũ khí ưa thích của lực lượng cảnh sát trên toàn thế giới.",
  "Pistol: D 1911": "Súng Lục (Pistol) D 1911",
  ".45 caliber royalty.": "Bậc thầy đạn .45 caliber.",
  "Pistol: G 19": "Súng Lục (Pistol) G 19",
  "Compact, little brother of the G17C": "Nhỏ gọn, đàn em của con G17C.",
  "Pistol: G 26": "Súng Lục (Pistol) G 26",
  "Ultra compact and  mean, just like your little sister.": "Siêu nhỏ nhưng khó chịu chết mẹ, y chang con em gái mày vậy.",
  "Pistol: M9": "Súng Lục (Pistol) M9",
  "The standard in most U.S. military branches since 1985.": "Trang bị chuẩn của phần lớn các nhánh quân đội Hoa Kỳ từ năm 1985.",
  "Pistol: P 226": "Súng Lục (Pistol) P 226",
  "European precision used by police and militaries worldwide.": "Thiết kế chuẩn xác của Châu Âu, được cảnh sát và quân đội toàn thế giới tin dùng.",
  "Pistol: 1911A1 Officer": "Súng Lục (Pistol) 1911A1 Officer",
  "Historic collectible, still in good condition.": "Một món đồ sưu tầm mang tính lịch sử, vẫn còn tốt chán.",
  "Pistol: Condor": "Súng Lục (Pistol) Condor",
  "Uses the .50 AE pistol round, a show stopper.": "Xài đạn lục .50 AE, bắn phát chết luôn.",
  "Pistol: G 20 ": "Súng Lục (Pistol) G 20",
  "Retooled from 10mm to .45 cal. Scope included.": "Được chỉnh sửa từ đạn 10mm sang .45 cal. Có gắn sẵn ống ngắm.",
  "Pistol: G21": "Súng Lục (Pistol) G 21",
  "Another entry from the \"G\" line, in .45 caliber.": "Một thành viên khác của dòng súng \"G\", xài đạn .45 caliber.",
  "Pistol: G22": "Súng Lục (Pistol) G 22",
  "Beloved by police units, light and powerful.": "Được các đơn vị cảnh sát mê mẩn, nhẹ và cực mạnh.",
  "Pistol: M11": "Súng Lục (Pistol) M 11",
  "A P226 used by select U.S. military units.": "Là biến thể P226 được dùng bởi một số đơn vị tinh nhuệ Hoa Kỳ.",
  "Pistol: Mi.Le": "Súng Lục (Pistol) Mi.Le",
  "Designed for police and military uses.": "Được thiết kế riêng cho cảnh sát và mục đích quân sự.",
  "Pistol: Mk. 3 Target": "Súng Lục (Pistol) Mk. 3 Target",
  "A favorite of target shooters and small game hunters.": "Món hàng khoái khẩu của dân bắn bia và thợ săn thú nhỏ.",
  "Pistol: OHWS 40": "Súng Lục (Pistol) OHWS 40",
  "Used by special operations forces.": "Thường được trang bị cho các lực lượng tác chiến đặc biệt.",
  "Pistol: P 229": "Súng Lục (Pistol) P 229",
  "Compact relative of the P226.": "Phiên bản thu gọn của P226.",
  "Pistol: Tac Master 1911": "Súng Lục (Pistol) Tac Master 1911",
  "1911 frame, upgraded for precision shooting.": "Khung 1911, nhưng được nâng cấp để bắn chính xác hơn.",
  "Pistol: X-Lock": "Súng Lục (Pistol) X-Lock",
  "A U.S. competitor to the \"G\" line of pistols.": "Đối thủ cạnh tranh tại Mỹ của dòng súng lục \"G\".",
  "Pistol: X-Lock Tactical": "Súng Lục (Pistol) X-Lock Tactical",
  "Lighter, shorter version of the X-Lock.": "Bản thu gọn và nhẹ hơn của X-Lock.",
  "Pistol: Bz75 ST": "Súng Lục (Pistol) Bz75 ST",
  "Popular compact version of the Bz75.": "Bản thu gọn phổ biến của Bz75.",
  "Pistol: Carrier 1911": "Súng Lục (Pistol) Carrier 1911",
  "Short, self-defense version of the 1911.": "Bản tự vệ siêu nhỏ của 1911.",
  "Revolver: Snub Special 22": "Súng Rulo (Revolver) Snub Special 22",
  "Reliable and inexpensive, a classic.": "Rẻ và uy tín, một tuyệt tác kinh điển.",
  "Revolver: Viper P357": "Súng Rulo (Revolver) Viper P357",
  "A revolver with a long history of police use.": "Dòng súng rulo gắn liền với lịch sử của ngành cảnh sát.",
  "Revolver: M 1917": "Súng Rulo (Revolver) M 1917",
  "Aging classic from the last days of WWI.": "Hàng cổ từ những ngày cuối của Đệ nhất Thế chiến.",
  "Revolver: Model 29": "Súng Rulo (Revolver) Model 29",
  "Powerful gun, made legendary in the movies.": "Khẩu súng uy lực, đã đi vào huyền thoại qua các bộ phim.",
  "Revolver: Toro Bravo": "Súng Rulo (Revolver) Toro Bravo",
  "An angry bull, this packs a big punch.": "Một con bò tót đang nổi điên, thổi bay mọi kẻ ngáng đường.",
  "Revolver: Anvil ": "Súng Rulo (Revolver) Anvil",
  "The .500 S&W round, used for shock and awe.": "Sức mạnh từ viên đạn .500 S&W, gây sốc và đầy oai vệ.",
  "Revolver: Blackbird": "Súng Rulo (Revolver) Blackbird",
  "Modern manufacture, wild west inspiration.": "Chế tác hiện đại, nhưng lấy cảm hứng từ miền Tây hoang dã.",
  "Revolver: Diplomat": "Súng Rulo (Revolver) Diplomat",
  "Short, powerful and reliable.": "Ngắn gọn, mạnh mẽ và ổn định.",
  "Revolver: River Snake": "Súng Rulo (Revolver) River Snake",
  "Powerful. Scoped for precision.": "Đầy quyền lực. Gắn sẵn ống ngắm bắn.",
  "Revolver: Safari": "Súng Rulo (Revolver) Safari",
  "Fires out of the bottom of the cylinder.": "Hỏa lực khai hỏa từ đáy của ổ xoay đạn.",
  "SMG: MP 90": "Súng Tiểu Liên (SMG) MP 90",
  "Compact SMG, normally 5.7mm, adapted for 9mm.": "Súng tiểu liên nhỏ gọn, nguyên bản 5.7mm, được chế lại để bắn đạn 9mm.",
  "SMG: MPS 90B": "Súng Tiểu Liên (SMG) MPS 90B",
  "Civilian version of the MP 90.  Optic included.": "Phiên bản dân sự của MP 90. Gắn sẵn phụ kiện ngắm.",
  "SMG: MP5A3": "Súng Tiểu Liên (SMG) MP5A3",
  "Iconic SMG, popular worldwide.": "Dòng tiểu liên mang tính biểu tượng, phủ sóng toàn thế giới.",
  "SMG: M1A1": "Súng Tiểu Liên (SMG) M1A1",
  "Famous design, in the WWII configuration. (replica)": "Thiết kế nổi tiếng, cấu hình từ Thế chiến II. (Bản sao chép)",
  "SMG: Super Z": "Súng Tiểu Liên (SMG) Super Z",
  "New steps in engineering, pistol configuration.": "Bước ngoặt mới trong kỹ thuật chế tạo, thiết kế theo cấu hình súng lục.",
  "SMG: M-10": "Súng Tiểu Liên (SMG) M-10",
  "A favorite of movie badguys.": "Món yêu thích của bọn phản diện trên phim.",
  "SMG: Mini Uzi 22": "Súng Tiểu Liên (SMG) Mini Uzi 22",
  "Economical, .22 caliber version of the Uzi.": "Bản kinh tế .22 caliber của dòng Uzi.",
  "SMG: MP7A1": "Súng Tiểu Liên (SMG) MP7A1",
  "A 4.6mm converted to 9mm. Optic included. ": "Khẩu 4.6mm được đôn lên nòng 9mm. Có sẵn phụ kiện ngắm.",
  "SMG: P9 Forge": "Súng Tiểu Liên (SMG) P9 Forge",
  "Sometimes called an \"improved\" Uzi.": "Nhiều lúc được gọi là bản Uzi \"nâng cấp\".",
  "SMG: PDS": "Súng Tiểu Liên (SMG) PDS",
  "Full-size rifle round, SMG-size package.": "Xài đạn súng trường xịn, trong hình dáng nhỏ gọn của súng tiểu liên.",
  "SMG: Samurai PDW": "Súng Tiểu Liên (SMG) Samurai PDW",
  "9mm SMG for Federal police.": "Dòng tiểu liên 9mm dành cho Cảnh sát Liên bang.",
  "SMG: UMP40": "Súng Tiểu Liên (SMG) UMP40",
  "Hard hitting SMG, meant to replace the MP5.": "Tiểu liên sát thương cao, được tạo ra để thay thế MP5.",
  "SMG: Uzi": "Súng Tiểu Liên (SMG) Uzi",
  "This sixty year-old is nowhere near retirement. ": "Ông già 60 tuổi này vẫn chưa muốn nghỉ hưu đâu.",
  "SMG: MP5K": "Súng Tiểu Liên (SMG) MP5K",
  "Compact MP5, great for tight spaces.": "Phiên bản MP5 thu gọn, cực ngon trong không gian hẹp.",
  "SMG: TMP9": "Súng Tiểu Liên (SMG) TMP9",
  "Swiss SMG, a relative of the P9 Forge.": "Hàng Thụy Sĩ, họ hàng gần với con P9 Forge.",
  "Assault Rifle: Mk.16 Mod.0": "Súng Trường Tấn Công: Mk.16 Mod.0",
  "Special Forces combat rifle. Has a pairing of optics.": "Súng chiến đấu của Lực lượng Đặc nhiệm. Trang bị kèm cặp phụ kiện ngắm.",
  "Assault Rifle: AR 15": "Súng Trường Tấn Công: AR 15",
  "Civilian version of the M4.": "Phiên bản dân sự của M4.",
  "Assault Rifle: AKMS": "Súng Trường Tấn Công: AKMS",
  "Paratrooper version of the AK frame.": "Phiên bản lính dù dùng khung súng AK.",
  "Assault Rifle: AR 15 Custom": "Súng Trường Tấn Công: AR 15 Custom",
  "An AR15 with some new furniture.": "Một khẩu AR15 vừa được tuốt lại đồ chơi mới.",
  "Assault Rifle: AK47": "Súng Trường Tấn Công: AK 47",
  "Legendary battle rifle. ": "Khẩu súng trường chiến đấu huyền thoại.",
  "Assault Rifle: 416D": "Súng Trường Tấn Công: 416D",
  "Short-stroke piston reliability. Scoped.": "Công nghệ Pít-tông siêu uy tín. Có sẵn ống ngắm.",
  "Assault Rifle: ACR": "Súng Trường Tấn Công: ACR",
  "A versatile, multi-role rifle in the field.": "Dòng súng trường linh hoạt, đa dụng trên chiến trường.",
  "Assault Rifle: AK47 Custom": "Súng Trường Tấn Công: AK47 Custom",
  "Customized with aftermarket additions, scoped.": "Được độ thêm phụ kiện xịn từ thị trường chợ đen, đi kèm ống ngắm.",
  "Assault Rifle: M14": "Súng Trường Tấn Công: M14",
  "50+ years of combat ops and counting. ": "Hơn 50 năm lăn lộn trên chiến trường và vẫn đang tăng.",
  "Assault Rifle: M16A4": "Súng Trường Tấn Công: M16A4",
  "USMC issue rifle. Badass attitude included.": "Vũ khí tiêu chuẩn của lính thủy đánh bộ Mỹ. Có sẵn một đống phong thái bất cần.",
  "Assault Rifle: M4A1": "Súng Trường Tấn Công: M4A1",
  "The standard U.S. military rifle.": "Súng trường tiêu chuẩn của Quân đội Mỹ.",
  "Assault Rifle: M6 SBR": "Súng Trường Tấn Công: M6 SBR",
  "Short Barreled Rifle.": "Súng trường nòng ngắn.",
  "Assault Rifle: 416 CQB": "Súng Trường Tấn Công: 416 CQB",
  "CQB - Close Quarters Battle.": "Súng Cận Chiến - Close Quarters Battle.",
  "Assault Rifle: AUG A3": "Súng Trường Tấn Công: AUG A3",
  "An iconic Austrian bullpup design.": "Thiết kế súng bullpup huyền thoại đến từ Áo."
};

function applyTranslations(chunkPath, mapData) {
  if (!fs.existsSync(chunkPath)) return;
  const chunk = JSON.parse(fs.readFileSync(chunkPath, 'utf8'));
  for (const r of chunk.replacements) {
    if (mapData[r.sourceText]) {
      r.translatedText = mapData[r.sourceText];
    }
  }
  fs.mkdirSync('output/languages/bmd_chunks', { recursive: true });
  fs.writeFileSync(chunkPath.replace('input/languages/', 'output/languages/'), JSON.stringify(chunk, null, 2), 'utf8');
}

applyTranslations('input/languages/bmd_chunks/bmd_chunk_5.json', map);
applyTranslations('input/languages/bmd_chunks/bmd_chunk_6.json', map);

console.log('Translated BMD Chunk 5 and 6 successfully!');
