const fs = require('fs');
const chunk190 = {
  "Look, I'll think about what you said, okay?": "Nghe này, tôi sẽ suy nghĩ về những gì cậu đã nói, okay?",
  "Peace, love, and happiness went into the custom paint job of this flower-powered four seater.": "Sự bình yên, tình yêu, và niềm hạnh phúc đã được thể hiện ở bên trong công việc sơn tùy chỉnh của chiếc xe bốn chỗ chạy bằng hoa này.",
  "That's where you've been? Jesus, Quentin, you took half the crew out to find one guy? Do you have any idea how worried I've been.": "Đó là nơi mà cậu đã đi à? Chúa ơi, Quentin, cậu đã dẫn theo một nửa số người trong đội đi ra ngoài chỉ để tìm kiếm một người thôi sao? Cậu có biết là tôi đã phải lo lắng đến mức như thế nào đéo.",
  "You want me to wait here?": "Cậu muốn tôi phải đợi ở đây sao?",
  "Don't know what I was thinking, going out there without backup. Guess I've always bitten off more than I could chew.": "Đéo hiểu lúc đó tôi đang nghĩ cái đéo gì nữa, khi lại dám đi ra ngoài đó mà đéo thèm có ai yểm trợ (backup). Chắc hẳn là lúc đéo nào tôi cũng tự rước lấy nhiều rắc rối hơn mức bản thân có thể giải quyết được.",
  "Climb the Cell Tower": "Trèo Lên Tháp Viễn Thông (Cell Tower)",
  "Arts and Crafts": "Nghệ Thuật và Thủ Công (Arts and Crafts)",
  "That was some quick thinking. I owe you.": "Cách suy nghĩ và giải quyết vấn đề nhanh nhạy lắm. Lần này tôi nợ cậu một mạng đấy.",
  "Who's Andy Pimms?": "Andy Pimms là ai thế?",
  "Don't be reckless.": "Đừng có tỏ ra quá khinh suất (reckless) đấy nhé.",
  "Out of here. I mean, does it really matter?": "Ra khỏi đây. Ý tôi là, chuyện đó có thực sự quan trọng đến vậy đéo?",
  "I can barely even walk right now, let alone do that.": "Bây giờ tôi thậm chí còn hầu như đéo thể tự bước đi được nữa là, nói gì đến việc đó cơ chứ.",
  "We don't have enough people to man the walls. If a horde attacks us, we're going to have gaps in our defenses. - %1$s": "Chúng ta đéo có đủ số lượng người để túc trực phòng thủ ở trên các bức tường. Nếu như có một bầy zombie horde tấn công chúng ta, chắc chắn chúng ta sẽ để lộ ra những sơ hở trong tuyến phòng ngự của mình mất. - %1$s",
  "David": "David",
  "What we need is an infirmary. We can't keep cramming sick people in here with the rest of us.": "Thứ mà chúng ta đang thực sự rất cần ngay lúc này đó là một cái bệnh xá (infirmary). Chúng ta đéo thể nào cứ tiếp tục nhồi nhét những người đang bị bệnh tật ở lại đây cùng với những người còn lại trong nhóm của chúng ta được.",
  "ATTITUDE: Boastful": "THÁI ĐỘ (ATTITUDE): Hay Khoe Khoang Boastful",
  "I see some trouble on our six!": "Tôi đang nhìn thấy có một vài rắc rối ở vị trí 6 giờ của chúng ta kìa!",
  "Ninja": "Ninja",
  "Lucas": "Lucas",
  "Maybe they've gone rogue. Or maybe this was the plan all along. Either way ... thank you guys.": "Có thể bọn họ đã trở thành những kẻ nổi loạn (rogue). Hoặc có lẽ đây vốn dĩ đã là một phần của kế hoạch ngay từ ban đầu. Dù cho sự thật có là gì đi chăng nữa thì... xin cảm ơn các cậu.",
  "Start looking around for hordes. We'll do the rest.": "Hãy bắt đầu tìm kiếm xung quanh về vị trí của những bầy zombie hordes. Chúng tôi sẽ lo nốt những phần việc còn lại.",
  "6 Daily Rations of Food per day": "Tiêu thụ 6 Khẩu Phần Ăn (Food) mỗi ngày",
  "Gardner": "Gardner",
  "Handyman": "Thợ Đụng Handyman (Đụng đâu sửa đó)",
  "Park": "Park",
  "Come on--we can deal with the rest of these infestations later. We gotta help those people first.": "Thôi nào--chúng ta có thể quay trở lại và giải quyết nốt những khu vực Ổ Dịch (infestations) này sau cũng được mà. Trước tiên chúng ta cần phải giúp đỡ cho những người đó đã.",
  "It's one thing to be an asshole like me, but you've been steppin' over the line, pal.": "Trở thành một thằng khốn nạn như tôi lại là một chuyện khác, nhưng cậu đang đi quá giới hạn rồi đấy, người anh em à.",
  "Black Friday, this is Doghouse Actual. I need the ranking officer on site.": "Black Friday, đây là Doghouse Actual. Tôi cần được nói chuyện với sĩ quan chỉ huy tại hiện trường.",
  "Kilohana had the strongest heart of anyone I've known. I hate these zombies for taking him away from us.": "Kilohana là người có một trái tim mạnh mẽ nhất so với tất cả những người mà tôi từng quen biết. Tôi thực sự rất căm hận lũ zombies chết tiệt này vì chúng đã cướp mất anh ấy khỏi vòng tay của chúng tôi.",
  "DECLINE MISSION. Let them handle their own problems.": "TỪ CHỐI NHIỆM VỤ (DECLINE MISSION). Cứ để cho bọn họ tự giải quyết những rắc rối của chính bản thân họ đi.",
  "Didn't figure on them things following me this time. Anyways, I appreciate the help. You find your people in need of doctoring, you give me a call.": "Lần này tôi đéo thể lường trước được việc những thứ đó lại bám theo mình. Dù sao thì, tôi cũng rất biết ơn về sự giúp đỡ của cậu. Nếu cậu thấy người của mình cần được điều trị y tế (doctoring), thì hãy gọi cho tôi nhé.",
  "Family Restaurant": "Nhà Hàng Gia Đình (Family Restaurant)",
  "Welcome to Snyder Trucking": "Chào mừng bạn đến với Khu Vận Tải Snyder",
  "EXPIRED: Michele Martin": "ĐÃ HẾT HẠN (EXPIRED): Michele Martin",
  "Need SWAT support.": "Cần có sự hỗ trợ của lực lượng SWAT.",
  "TRADE RUN": "CỬ NGƯỒI ĐI GIAO DỊCH (TRADE RUN)",
  "So... you gonna go talk to Job Wilkerson?": "Vậy... cậu định sẽ đến nói chuyện với Job Wilkerson à?",
  "Slice! (Weapon Specializations: Low Slice, Behead)": "Chém Bằng Kiếm! (Chuyên Môn Vũ Khí: Chém Thấp Low Slice, Chặt Đầu Behead)",
  "So if these soldiers have been locked in the warehouse, and you can't open the warehouse door without power, and the power's been out for days....": "Vậy nếu như những người lính (soldiers) này đã bị nhốt ở trong nhà kho, và các người thì lại đéo thể mở được cánh cửa của nhà kho ra nếu như đéo có nguồn điện (power), và nguồn điện thì lại đã bị cắt mất từ mấy ngày hôm trước rồi....",
  "Pesticides": "Thuốc Trừ Sâu (Pesticides)",
  "Hey. I don't want to panic you, but we may have a problem.": "Này. Tôi đéo muốn làm cho cậu phải hoảng sợ đâu, nhưng chúng ta có lẽ đang gặp phải một vấn đề khá lớn đấy.",
  "EXPIRED: Supply Run with Kilo": "ĐÃ HẾT HẠN (EXPIRED): Chạy Đi Thu Thập Tiếp Tế (Supply Run) Cùng Với Kilo",
  "Night": "Ban Đêm (Night)",
  "Well, I hear Sheriff Parsons has been running his mouth again.": "Chà, tôi nghe nói là Cảnh sát trưởng (Sheriff) Parsons lại bắt đầu nói nhảm nữa rồi.",
  "Let me think on that.": "Hãy để tôi suy nghĩ thêm về chuyện đó đã nhé.",
  "Why don't you come down to Marshall so we can have a little face to face chat?": "Tại sao các người đéo xuống Marshall để chúng ta có thể có một cuộc trò chuyện nhỏ trực tiếp với nhau nhỉ?",
  "You just stay right there. You make me look good by comparison.": "Cậu cứ đứng yên ở đó đi. Cậu làm cho tôi trông có vẻ giỏi giang hơn bằng cách so sánh đấy.",
  "We are leaving now.": "Chúng tôi sẽ rời đi ngay bây giờ.",
  "I'm sorry to hear that.": "Tôi rất tiếc khi phải nghe điều đó.",
  "Get Matching Tattoos": "Xăm Những Hình Xăm Có Cặp Có Đôi Mảnh Khớp Nhau (Matching Tattoos)",
  "Handles like a dream, doesn't she? I had one just like her as a younger man.": "Con xe này xử lý tình huống mượt mà giống hệt như một giấc mơ vậy, có đúng đéo? Tôi cũng đã từng có một chiếc xe giống y hệt như cô nàng này khi tôi còn là một thanh niên trẻ tuổi đấy.",
  "Angelica": "Angelica",
  "I told you, this is all we have!": "Tôi đã nói với các người rồi, đây là tất cả những gì mà chúng tôi hiện đang có!",
  "I guess they just hit their breaking point. Decided a quick, clean end was better than trying to scrape by for one more day.": "Tôi đoán là bọn họ đã đạt đến điểm giới hạn tột cùng (breaking point) của sức chịu đựng cmnr. Quyết định lựa chọn một cái kết nhanh gọn, sạch sẽ vẫn tốt hơn là cứ phải cố gắng sống lay lắt thêm được một ngày nào đó nữa.",
  "Drop Rucksack": "Vứt Bỏ Chiếc Balo (Rucksack)",
  "This building is TOO SMALL to fortify.": "Tòa nhà này thực sự QUÁ NHỎ (TOO SMALL) để có thể củng cố và biến nó trở thành một căn cứ.",
  "Inherited lots of land, but his love of bourbon bankrupted him...and makes sure he stays that way.": "Được thừa kế lại rất nhiều đất đai, nhưng niềm đam mê bất diệt dành cho rượu bourbon đã khiến anh ta bị phá sản...và điều đó chắc chắn rằng anh ta vẫn sẽ phải tiếp tục sống theo cái cách khốn nạn đó thôi.",
  "Special technique that allows you to instantly counter incoming attacks.": "Một kỹ thuật đặc biệt (Special technique) cho phép bạn có thể ngay lập tức thực hiện các đòn phản công (counter) lại các đòn tấn công đang lao tới.",
  "Even if nobody knows what it means but us... they deserve to be remembered.": "Ngay cả khi đéo có ai ngoài chúng ta biết được những biểu tượng này có ý nghĩa gì đi chăng nữa... thì bọn họ vẫn xứng đáng để được chúng ta nhớ tới.",
  "There's a horde.": "Có một bầy zombie horde ở kia kìa.",
  "Over on the right.": "Ở ngay phía bên tay phải kìa.",
  "Baking Ingredients": "Các Nguyên Liệu Làm Bánh",
  "REWARD. Several rucksacks' worth of Medicine, delivered directly into your stockpile.": "PHẦN THƯỞNG (REWARD). Bạn sẽ nhận được vài chiếc balo (rucksacks) chứa đầy Thuốc Men (Medicine), được gửi thẳng trực tiếp vào kho dự trữ của bạn.",
  "KILLED: Dr. Dan Bogatz": "ĐÃ BỊ GIẾT CHẾT (KILLED): Bác sĩ Dan Bogatz",
  "Strand?": "Strand à?",
  "Good work, soldier. Highroad out.": "Làm tốt lắm, người lính à. Highroad hết.",
  "Hey, Mickey! You got a sightline on these assholes?": "Này, Mickey! Cậu đã đưa những tên khốn này vào trong tầm ngắm đéo?",
  "Sonner": "Sonner",
  "I found some construction materials.": "Tôi đã tìm thấy được một số vật liệu xây dựng (construction materials).",
  "%d added to Supply Locker. (Good medicine supply.)": "%d đã được thêm vào Tủ Khóa Tiếp Tế (Supply Locker). (Nguồn cung cấp thuốc men medicine đang ở mức rất tốt.)",
  "Ok": "Ok",
  "Good job holding the line back there.": "Làm tốt lắm khi cậu đã có thể giữ vững được phòng tuyến ở ngoài đó.",
  "Holy crap, it's like a spooky ghost town, but full of zombies and bombs.": "Vãi cả cứt, cái nơi khốn khiếp này cứ giống như là một thị trấn ma quái vậy, nhưng lại chứa đầy những bọn zombies và cả bom mìn.",
  "Build 8 outposts.": "Xây dựng 8 tiền đồn (outposts).",
  "Now this is interesting... I found this old article in a science magazine about making biodiesel out of food byproducts.": "Bây giờ thì chuyện này đã bắt đầu trở nên thú vị rồi đây... Tôi vừa mới tìm thấy được bài viết cũ này trên một cuốn tạp chí khoa học nói về việc làm thế nào để có thể chế tạo ra loại nhiên liệu sinh học biodiesel từ các chế phẩm phụ thuộc nguồn thực phẩm.",
  "COMPLETED: Seek and Destroy": "ĐÃ HOÀN THÀNH (COMPLETED): Truy Tìm và Tiêu Diệt (Seek and Destroy)",
  "Someone died for this.": "Một ai đó đã phải hy sinh tính mạng của mình chỉ vì thứ này đấy.",
  "Field Surgery": "Phẫu Thuật Dã Chiến (Field Surgery)",
  "They're here! Somebody!": "Bọn chúng đang ở đây! Có ai đéo!",
  "Belongings (%1$s %2$s)": "Đồ Đạc Thuộc Về Cá Nhân (%1$s %2$s)",
  "Dick": "Dick",
  "Is it true? Is Eli...?": "Đó có phải là sự thật đéo? Có phải Eli đã...?",
  "Lily's immune system's already weak - if she catches this bug....": "Hệ miễn dịch của Lily vốn dĩ đã rất yếu rồi - nếu như cô ấy mà lại mắc phải căn bệnh này thì....",
  "Looks pretty clear to me.": "Đối với tôi thì có vẻ khá là rõ ràng rồi đấy.",
  "Follow my lead and we'll get there just fine.": "Hãy đi theo sự dẫn dắt của tôi và chúng ta sẽ có thể đến được đó một cách bình yên vô sự.",
  "Beijing vows to protect borders from foreign refugees \"at all costs.\"": "Bắc Kinh đã tuyên bố sẽ phải bảo vệ nghiêm ngặt các khu vực biên giới lãnh thổ khỏi những người dân tị nạn (refugees) nước ngoài \"bằng bất cứ giá nào.\"",
  "Reduces discord. Protects against vermin.": "Làm giảm thiểu đi sự bất hòa (discord). Bảo vệ chống lại những loài sâu bọ và động vật gây hại (vermin).",
  "Now that's some fine work.": "Đó quả thực là một màn trình diễn xuất sắc đấy.",
  "+0%": "+0%",
  "So, I'm picturing this warehouse full of supplies, and a woman named Cleo who sits at a radio all day, surrounded by her cats.": "Vậy ra, tôi đang hình dung về một cái nhà kho chứa đầy những nguồn hàng tiếp tế này, cùng với một người phụ nữ có tên là Cleo đang ngồi trực bên đài phát thanh (radio) suốt cả ngày, xung quanh cô ta là lũ mèo.",
  "Let's move.": "Chúng ta hãy di chuyển thôi nào.",
  "We need to clear this infestation out.": "Chúng ta cần phải dọn dẹp sạch sẽ khu vực Ổ Dịch (infestation) này.",
  "I'm picking up a lot of weird signals lately. I think they're encrypted radio chatter.": "Gần đây tôi đang bắt được rất nhiều những tín hiệu kỳ lạ. Tôi nghĩ đó là những cuộc nói chuyện qua bộ đàm đã được mã hóa bí mật (encrypted).",
  "Ever since we lost that outpost, shit's been seven kinds of messed up.": "Kể từ cái ngày mà chúng ta để đánh mất cái tiền đồn (outpost) đó, mọi thứ chết tiệt đều đã trở nên rối tung rối mù cả lên cmnr.",
  "After witnessing the death of his rescuer, Hadley Westen totally freaked out and got himself killed.": "Sau khi phải chứng kiến cái chết của chính ân nhân cứu mạng của mình, Hadley Westen đã trở nên hoàn toàn hoảng loạn tột độ và tự rước lấy cái chết cho bản thân anh ta.",
  "I know it's tough out there for everybody, but we've got sick people here and no medical supplies to speak of. Anyone out there know where our runners might find some?": "Tôi biết rằng ở ngoài kia mọi chuyện đang diễn ra rất khó khăn với tất cả mọi người, nhưng hiện tại ở đây chúng tôi đang có rất nhiều người bị bệnh và đéo còn chút thuốc men (medical supplies) nào có thể sử dụng được nữa. Có ai ở ngoài kia biết được nơi nào mà những người chạy bộ thu thập (runners) của chúng tôi có thể tìm thấy được một ít thuốc men đéo?",
  "Falling back!": "Rút lui (Falling back)!",
  "Scavenge 150 Resources. (Breakdown Level 4 or Higher)": "Thu thập (Scavenge) được 150 Nguồn Tài Nguyên. (Cấp Độ Breakdown 4 Hoặc Cao Hơn)",
  "Let me look around just a little bit more.": "Hãy để tôi xem xét xung quanh thêm một chút nữa nhé.",
  "76 GENERIC Jackson Palaver": "76 CHUNG (GENERIC) Jackson Palaver"
};

const file = 'output/languages/chunks/btxt_chunk_190.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_190.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk190[r.sourceText]) {
    r.translatedText = chunk190[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 190 successfully!');
