const fs = require('fs');
const chunk171 = {
  "Gas Generator": "Máy Phát Điện Chạy Xăng (Gas Generator)",
  "Switch to %1$s and let %2$s rest. %2$s will regain maximum Vitality and Stamina while resting.": "Chuyển sang %1$s và để %2$s nghỉ ngơi. %2$s sẽ phục hồi Sinh Lực (Vitality) và Thể Lực (Stamina) tối đa trong khi nghỉ ngơi.",
  "We're too late. The zeds got to them first.": "Chúng ta đến quá muộn rồi. Bọn zeds đã tóm được họ trước.",
  "Get some, brah!": "Nhận lấy này, người anh em!",
  "Okay, I see Spencer's Mill up ahead.": "Được rồi, tôi thấy Spencer's Mill ở phía trước rồi.",
  "Hey Lily? Let folks know I'll be home soon.": "Này Lily? Báo cho mọi người biết là tôi sẽ về nhà sớm nhé.",
  "74 GENERIC Dick Calvert": "74 CHUNG (GENERIC) Dick Calvert",
  "Where is he?": "Anh ta đâu rồi?",
  "We cut that one a little too close, I think.": "Tôi nghĩ là chúng ta vừa thoát chết trong gang tấc đấy.",
  "Get some fucking zeds off my back!": "Hất vài con zeds chết tiệt khỏi lưng tôi cái coi!",
  "Nicholas": "Nicholas",
  "Somebody place an order for delivery?": "Có ai vừa đặt hàng giao tận nơi đéo?",
  "Did you ever hear of the Montana People's Front?": "Cậu đã bao giờ nghe nói về Mặt Trận Nhân Dân Montana (Montana People's Front) chưa?",
  "You have a society? I'm sorry, what exactly happened to the United States while I wasn't looking?": "Cậu có một xã hội sao? Xin lỗi, chính xác thì chuyện gì đã xảy ra với nước Mỹ trong lúc tôi đéo để ý vậy?",
  "We'll keep trying.": "Chúng ta sẽ tiếp tục cố gắng.",
  "Auto Repair": "Sửa Chữa Ô Tô (Auto Repair)",
  "Hanna": "Hanna",
  "Duckworth": "Duckworth",
  "ADVICE: Build a Cooking Area": "LỜI KHUYÊN (ADVICE): Hãy Xây Dựng Một Khu Vực Nấu Ăn (Cooking Area)",
  "Fairgrounds Lockers": "Các Tủ Đồ (Lockers) Ở Khu Hội Chợ (Fairgrounds)",
  "Hey, you doing okay?": "Này, cậu vẫn ổn chứ?",
  "Yo dawg, that's straight-up cold, man.": "Này anh bạn, chuyện đó đúng là lạnh lùng tàn nhẫn đấy.",
  "My mom, she's got this medical marijuana prescription, right?": "Mẹ tôi, bà ấy có cái đơn thuốc cần sa y tế này, cậu biết đéo?",
  "HOME: Not Enough Beds": "CĂN CỨ (HOME): Đéo Đủ Giường",
  "Are we sure he didn't just get a charge out of cutting up dead bodies?": "Chúng ta có chắc là hắn đéo chỉ cảm thấy phấn khích khi được cắt xẻo những xác chết đéo?",
  "Now, I've drawn up some basic plans, but we'll want to get on this in a hurry.": "Bây giờ, tôi đã vạch ra một vài kế hoạch cơ bản, nhưng chúng ta sẽ muốn bắt tay vào việc này một cách nhanh chóng đấy.",
  "Feral Zed": "Zed Hoang Dại (Feral Zed)",
  "105 HERO Shark Hoodie Guy": "105 ANH HÙNG (HERO) Chàng Trai Mặc Áo Hoodie Cá Mập",
  "I can carry the stuff and handle the negotiating, but some extra muscle never hurt.": "Tôi có thể mang vác đồ đạc và lo liệu việc đàm phán, nhưng có thêm vài tay cơ bắp cũng đéo thừa đâu.",
  "We're there.": "Chúng ta đến nơi rồi.",
  "Created 2 Suppressors.": "Đã chế tạo 2 Ống Giảm Thanh (Suppressors).",
  "Phoebe": "Phoebe",
  "Can't we deal with this later?": "Chúng ta đéo thể giải quyết chuyện này sau được sao?",
  "That place is worth a scavenging run.": "Nơi đó rất đáng để thực hiện một chuyến thu lượm đồ (scavenging run) đấy.",
  "Ezekiel": "Ezekiel",
  "TIP: Taking emergency supplies requires INFLUENCE.": "MẸO (TIP): Việc lấy các nhu yếu phẩm khẩn cấp yêu cầu phải có ẢNH HƯỞNG (INFLUENCE).",
  "Miller": "Miller",
  "COMPLETED: The Voice On the Radio": "ĐÃ HOÀN THÀNH: Giọng Nói Trên Radio",
  "Has trouble sleeping without his favorite Dakimakura. (Reduced Stamina)": "Gặp khó khăn khi ngủ mà đéo có chiếc gối ôm (Dakimakura) yêu thích của mình. (Bị Giảm Thể Lực - Reduced Stamina)",
  "They're trying to get in the front!": "Chúng đang cố gắng đột nhập vào từ phía trước!",
  "Protect Ed": "Bảo Vệ Ed",
  "ATTITUDE: Relaxed": "THÁI ĐỘ (ATTITUDE): Thoải Mái (Relaxed)",
  "You could have prevented this. It's not like I exactly kept it to myself. All somebody had to do was say something, but I guess your \"supply runs\" are more important. Fuck you. - %1$s": "Cậu đã có thể ngăn chặn chuyện này. Đéo phải là tôi đã giữ kín chuyện đó cho riêng mình. Tất cả những gì ai đó phải làm là lên tiếng, nhưng tôi đoán những \"chuyến đi tìm nhu yếu phẩm\" của các người còn quan trọng hơn. Khốn nạn. - %1$s",
  "Guess we're making progress.": "Đoán là chúng ta đang có tiến triển đấy.",
  "Field Workshop": "Xưởng Làm Việc (Workshop) Dã Chiến",
  "Brooklyn": "Brooklyn",
  "Priming Tool": "Dụng Cụ Nạp Mồi Lửa (Priming Tool)",
  "Incendiary ammo for compatible shotguns.": "Đạn cháy dành cho các loại súng shotgun tương thích.",
  "I don't have a firearm for that.": "Tôi đéo có khẩu súng nào cho loại đạn đó.",
  "We're all that's left of our unit. We could use some orders, ma'am.": "Chúng tôi là tất cả những gì còn sót lại của đơn vị mình. Chúng tôi cần một vài mệnh lệnh, thưa cô.",
  "Scavenged a resource": "Đã thu lượm (Scavenged) được một tài nguyên",
  "Change of plans.": "Thay đổi kế hoạch.",
  "Don't you get it? More of us didn't make it than did. We can't be soft-hearted about this. Not any more.": "Cậu đéo hiểu sao? Số người đéo qua khỏi còn nhiều hơn số người sống sót. Chúng ta đéo thể mềm lòng về chuyện này được nữa. Đéo thể nữa.",
  "Isis": "Isis",
  "Swiss SMG, a relative of the P9 Forge.": "Súng tiểu liên SMG của Thụy Sĩ, có họ hàng với khẩu P9 Forge.",
  "I wouldn't worry about it. I'm sure they're just advance scouts. The main force will be here any day, and they'll take care of us.": "Tôi sẽ đéo lo lắng về chuyện đó đâu. Tôi chắc chắn chúng chỉ là những đội trinh sát tiên phong. Lực lượng chính sẽ có mặt ở đây vào một ngày nào đó, và họ sẽ chăm lo cho chúng ta.",
  "Clear out this space to use it as a Supply Room.": "Dọn dẹp sạch sẽ đéo gian này để sử dụng nó làm Phòng Cung Cấp Nhu Yếu Phẩm (Supply Room).",
  "I know it's probably not something you want to think about, but... we've got a decision to make.": "Tôi biết đó có lẽ đéo phải là điều cậu muốn nghĩ tới, nhưng... chúng ta có một quyết định phải đưa ra.",
  "Take Care of Eli": "Chăm Sóc cho Eli",
  "Stealth Drunk": "Kẻ Uống Rượu Vụt Trộm (Stealth Drunk)",
  "Let's take care of him and go the fuck home.": "Hãy lo liệu cho anh ta và về cái nhà chết tiệt thôi.",
  "Is the LZ secure?": "Khu vực hạ cánh (LZ) đã an toàn chưa?",
  "Requires trained medic!": "Yêu cầu phải có nhân viên y tế (medic) đã qua đào tạo!",
  "I don't think I can carry any more. Let's just go.": "Tôi đéo nghĩ là tôi có thể mang thêm được gì nữa. Cứ đi thôi.",
  "Taxidermy's a way to take something living and preserve it forever. It's not about dead things; it's about making them immortal. (Chemistry and Arts and Crafts. Interesting combo.)": "Thuật nhồi bông (Taxidermy) là một cách để lấy đi sự sống của một thứ gì đó và bảo tồn nó mãi mãi. Nó đéo phải là về những thứ đã chết; nó là về việc làm cho chúng trở nên bất tử. (Hóa Học và Thủ Công Mỹ Nghệ. Sự kết hợp thú vị đấy.)",
  "How about some artillery support?": "Một chút hỏa lực pháo binh hỗ trợ thì sao?",
  "Are you high? No way I'm going out there!": "Cậu phê cần à? Đéo đời nào tôi lại đi ra ngoài đó đâu!",
  "We could use your help in this area.": "Chúng tôi cần sự giúp đỡ của cậu ở khu vực này.",
  "Tensions are running pretty high these days, huh?": "Căng thẳng đang leo thang khá cao trong những ngày này, huh?",
  "You had a chance to talk to Carl yet?": "Cậu đã có cơ hội nói chuyện với Carl chưa?",
  "Doug": "Doug",
  "I hit something with my car. Those things were ... all over the place.": "Tôi đã tông phải thứ gì đó bằng xe của mình. Những thứ đó đã ... ở khắp mọi nơi.",
  "All done, heading back.": "Xong việc rồi, quay về thôi.",
  "Yeah. Tell the gang we're building an outpost here.": "Ừ. Nói với cả nhóm là chúng ta đang xây dựng một tiền đồn (outpost) ở đây nhé.",
  "Maximum trust!": "Độ Tin Tưởng (Trust) Tối Đa!",
  "Now, it's your call whether you want to help or be a pain in my ass...": "Bây giờ, quyền quyết định là ở cậu, muốn giúp đỡ hay muốn trở thành một cái gai trong mắt tôi...",
  "Hey, have you seen Dad recently?": "Này, dạo này cậu có thấy Bố đâu đéo?",
  "Ow! Dammit!": "Á! Mẹ kiếp!",
  "There's another horde.": "Có một bầy (horde) khác kìa.",
  "Knows a little something about tools and construction.": "Biết đôi chút về công cụ và xây dựng.",
  "Find out what Mickey wants.": "Tìm hiểu xem Mickey muốn gì.",
  "Vienna Cho": "Vienna Cho",
  "Better stock up on Medicine.": "Tốt hơn là nên dự trữ thêm Thuốc Men (Medicine).",
  "Oh God oh God!": "Ôi Chúa ơi ôi Chúa ơi!",
  "Anyway, thanks for the- oh, what the fuck?": "Dù sao thì, cảm ơn vì- ôi, cái đéo gì thế này?",
  "You may want to come home.": "Có lẽ cậu sẽ muốn trở về nhà đấy.",
  "Really? Yeah, no, that's awesome.": "Thật sao? Ừ, đéo, điều đó thật tuyệt vời.",
  "Hamilton": "Hamilton",
  "Use a car door to kill a zombie.": "Sử dụng cửa xe ô tô để giết một con zombie.",
  "Watch yourselves. It's slippery over here.": "Cẩn thận đấy. Bọn nó rất trơn trượt (slippery) khi ở bên này.",
  "Well you can thank our friend here for that. We would have been in real trouble otherwise.": "Chà, các người có thể cảm ơn người bạn này của chúng ta vì điều đó. Nếu đéo thì chúng ta đã thực sự gặp rắc rối to rồi.",
  "Probably would have drowned, except some fella picnicking on the bank saw me. Dove right in and hauled me out.": "Có lẽ tôi đã bị chết đuối rồi, nếu như đéo có một anh chàng đang đi dã ngoại trên bờ nhìn thấy tôi. Lao thẳng xuống và kéo tôi lên.",
  "No. It's gotten better.": "Đéo. Nó đã trở nên tốt hơn rồi.",
  "Lead the survivor to the LZ": "Dẫn Người Sống Sót tới Khu Vực Hạ Cánh (LZ)",
  "The lumber room's looking pretty empty. Might want to look for some building materials out there.": "Phòng chứa gỗ trông khá trống trải. Có lẽ muốn tìm kiếm một số vật liệu xây dựng ngoài đó.",
  "Holden": "Holden",
  "Christ, just ring the dinner bell while you're at it.": "Chúa ơi, hãy rung chuông gọi ăn tối luôn đi trong lúc cậu đang làm việc đó.",
  "Community member found.": "Đã tìm thấy một thành viên cộng đồng.",
  "Yeah. Few of their goons hit up the gas station outside town, found a couple survivors holed up there.": "Ừ. Vài tên tay sai của chúng đã tấn công vào trạm xăng ngoài thị trấn, phát hiện ra một vài người sống sót đang ẩn nấp ở đó.",
  "Elliott": "Elliott"
};

const file = 'output/languages/chunks/btxt_chunk_171.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_171.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk171[r.sourceText]) {
    r.translatedText = chunk171[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 171 successfully!');
