const fs = require('fs');
const chunk189 = {
  "Okay… looks like the hordes keep going that way.": "Okay… có vẻ như bầy horde (hordes) vẫn đang tiếp tục di chuyển về hướng đó.",
  "Looks like you're slowing down. Food will help some, but you need rest.": "Trông có vẻ như cậu đang chậm lại rồi đấy. Thức ăn (Food) sẽ có thể giúp ích được đôi chút, nhưng cậu cần phải được nghỉ ngơi.",
  "Caller, you're on the air. Tell us your situation.": "Người gọi đến, bạn đang được lên sóng đấy. Hãy kể cho chúng tôi nghe về tình hình hiện tại của bạn xem nào.",
  "I think we've turned a corner here.": "Tôi nghĩ là chúng ta vừa mới rẽ qua một góc cua ở đây.",
  "Do me a favor and don't come driving up like a dumbass.": "Hãy làm cho tôi một việc và đừng có lái xe lao đến giống như một thằng ngu nữa.",
  "But I believe that we--that you--have been chosen for greater things. We won't just survive, we will rise and be the birth of a new civilization.": "Nhưng tôi luôn tin tưởng rằng chúng ta--rằng các bạn--đã được lựa chọn để thực hiện những điều tuyệt vời hơn thế. Chúng ta sẽ đéo chỉ dừng lại ở việc cố gắng sống sót (survive), chúng ta sẽ vươn lên và trở thành nơi khai sinh ra một nền văn minh mới.",
  "This doesn't seem very stealthy.": "Cách này có vẻ đéo được lén lút (stealthy) cho lắm đâu.",
  "A place to grow fresh food. Coming along nicely.": "Một nơi để trồng trọt các loại thực phẩm tươi sạch (fresh food). Mọi chuyện đang tiến triển rất tốt đấy.",
  "Still. I buried her in that dress. She... she always loved it.": "Vẫn vậy thôi. Tôi đã chôn cất con bé trong bộ váy đó. Nó... nó luôn luôn yêu thích bộ váy đó mà.",
  "Better shut up that screamer first.": "Tốt hơn hết là nên khóa mồm con screamer đó lại trước đi.",
  "Good for repairing stuff.": "Rất thích hợp dùng để sửa chữa (repairing) đồ đạc.",
  "At first, they told us just to stay home, lock our doors, and wait for the all-clear.": "Vào lúc đầu, bọn họ chỉ bảo chúng tôi hãy ở yên trong nhà, khóa chặt các cửa lại, và chờ đợi cho đến khi có thông báo an toàn (all-clear).",
  "Just don't be too close when you do.": "Chỉ là đừng đứng quá gần khi cậu làm điều đó.",
  "Outta fuel? How'd we let that happen?": "Đã Hết Sạch Nhiên Liệu (Outta fuel) cmnr à? Tại sao chúng ta lại có thể để cho chuyện đó xảy ra cơ chứ?",
  "You're right. Start putting out calls to everyone we know. Tell them to get ready to move. We're all getting the hell out of here.": "Cậu nói đúng đấy. Hãy bắt đầu gọi điện thông báo cho tất cả những người mà chúng ta biết đi. Bảo bọn họ chuẩn bị sẵn sàng để di chuyển. Tất cả chúng ta sẽ thoát khỏi cái nơi chết tiệt này.",
  "Tank Mechanic": "Thợ Sửa Chữa Xe Tăng (Tank Mechanic)",
  "DECLINED: Home Sweet Home": "ĐÃ TỪ CHỐI (DECLINED): Ngôi Nhà Thân Yêu (Home Sweet Home)",
  "Fighting zombies hand to hand is bad enough, but some of our people don't even have a weapon. We're in trouble if a horde gets past our defenses. - %1$s": "Phải chiến đấu với bọn zombies bằng tay không đã là một chuyện quá tồi tệ rồi, nhưng một vài người trong số chúng ta thậm chí còn đéo có nổi một món vũ khí cơ. Chúng ta sẽ gặp rắc rối to nếu như có một bầy zombie horde lọt qua được lớp hàng rào phòng thủ của chúng ta đấy. - %1$s",
  "Success! Your save from the original State of Decay has been imported.": "Thành Công! File save từ phiên bản State of Decay gốc của bạn đã được nhập liệu thành công cmnr.",
  "Make yourself useful and get over here.": "Hãy làm cho bản thân trở nên có ích một chút và qua đây đi.",
  "I can't believe it. I mean, that place was like a fortress.": "Tôi đéo thể nào tin được chuyện này lại xảy ra. Ý tôi là, cái nơi đó vốn dĩ giống như một pháo đài bất khả xâm phạm vậy.",
  "Hey, that was badass!": "Này, cái đó thật là bá đạo (badass) đấy!",
  "At least then I'd be able to keep the food I found.": "Ít nhất thì khi đó tôi sẽ có thể giữ lại được chỗ thức ăn (food) mà tôi đã tìm thấy.",
  "Rifle: CLEO DMR": "Súng Trường (Rifle): CLEO DMR",
  "Koskinen": "Koskinen",
  "72 GENERIC Liz Winard": "72 CHUNG (GENERIC) Liz Winard",
  "Do you think we should have left a note or something back at the church?": "Cậu có nghĩ là chúng ta nên để lại một mảnh giấy nhắn hay một thứ đéo gì đó ở nhà thờ (church) đéo?",
  "Too many HORDES out there.": "Đang có quá nhiều những BẦY ZOMBIE HORDE (HORDES) ở ngoài kia đấy.",
  "I'm serious, I think I'm getting a fever! Oh man, this is bad, we're already low on medicine.": "Tôi nói nghiêm túc đấy, tôi nghĩ là tôi đang bị lên cơn sốt (fever) cmnr! Oh trời ạ, chuyện này thật tồi tệ, chúng ta vốn dĩ đã sắp cạn kiệt thuốc men (medicine) rồi mà.",
  "Did Aeschylus say that too?": "Aeschylus cũng đã từng nói như vậy sao?",
  "START MISSION. Trade 1 Case of Ammunition for 5 Cases of Medicine.": "BẮT ĐẦU NHIỆM VỤ (START MISSION). Trao đổi 1 Thùng Đạn Dược (Ammunition) để lấy 5 Thùng Thuốc Men (Medicine).",
  "Got you now.": "Bắt được mày rồi nhé.",
  "I haven't even heard a car engine all day. Just moaning. Ugh.": "Tôi thậm chí còn đéo nghe thấy tiếng động cơ xe hơi nào suốt cả một ngày trời rồi. Chỉ toàn là những tiếng rên rỉ mà thôi. Ugh.",
  "Please hurry!": "Làm ơn hãy nhanh lên!",
  "Ask around about an area that has MATERIALS.": "Hỏi thăm thông tin xung quanh về một khu vực có chứa VẬT LIỆU XÂY DỰNG (MATERIALS).",
  "If you're lucky enough to get your hands on military-grade hardware, using it's the only way to keep up your Assault Rifle Specialization.": "Nếu như bạn đủ may mắn để có thể chạm tay vào các loại trang thiết bị phần cứng cấp độ quân sự (military-grade hardware), thì việc sử dụng nó chính là cách duy nhất để có thể duy trì được Chuyên Môn Súng Trường Tấn Công (Assault Rifle Specialization) của bạn.",
  "Quit farting around with the ones on the lawn and get in the house!": "Thôi ngay cái trò đánh rắm đi lảng vảng xung quanh với những thứ đang ở trên bãi cỏ đi và hãy đi vào trong nhà ngay!",
  "Wait. You're alive? You're the army! I thought you guys had cleared out.": "Khoan đã. Cậu vẫn còn sống sót sao? Cậu là người của quân đội (army)! Tôi cứ tưởng là các cậu đã rút lui khỏi đây hết rồi chứ.",
  "Restore Max Stamina once a day.": "Hồi phục lại mức Thể Lực Tối Đa (Max Stamina) mỗi ngày một lần.",
  "LMG: CLEO LSW": "Súng Máy Hạng Nhẹ (LMG): CLEO LSW",
  "Physician's Assistant": "Trợ Lý Bác Sĩ (Physician's Assistant)",
  "Next time, use a headshot to kill the Bloater.": "Lần tới, hãy ngắm bắn thẳng vào đầu (headshot) để tiêu diệt con Bloater nhé.",
  "Need more than a shoulder to bust this one open.": "Sẽ cần nhiều hơn là chỉ một bờ vai để có thể phá tung được cái này đấy.",
  "I'm not giving up yet!": "Tôi vẫn chưa chịu bỏ cuộc đâu!",
  "You're an 18-karat bringdown.": "Cậu đúng là một kẻ luôn mang lại sự thất vọng tột độ đấy.",
  "I can't attach a suppressor to this gun.": "Tôi đéo thể nào gắn được ống giảm thanh (suppressor) vào khẩu súng này.",
  "Scoring": "Đang Ghi Điểm (Scoring)",
  "You holding up okay?": "Cậu vẫn có thể trụ vững được chứ hả?",
  "There's no time! Get in the vehicle now!": "Đéo còn thời gian nữa đâu! Hãy lên xe (vehicle) đi, ngay bây giờ!",
  "Ruben": "Ruben",
  "Nothing. But Ray and his \"grand vision\" lacks the kind of focused leadership that will see us through this crisis.": "Đéo có đéo gì cả. Nhưng Ray và cái \"tầm nhìn vĩ đại\" của anh ta lại đang bị thiếu đi sự tập trung vào vai trò lãnh đạo cần thiết để có thể giúp chúng ta vượt qua được cuộc khủng hoảng này.",
  "Let me look around a little bit more.": "Hãy để tôi xem xét xung quanh thêm một chút nữa nhé.",
  "You're on your own, soldier.": "Cậu sẽ phải tự lực cánh sinh thôi, người lính à.",
  "Contact West!": "Đã phát hiện thấy kẻ thù ở Khu Vực Phía Tây (West)!",
  "I made it to the Ranger Station, and I'm starting to wonder if this was a good idea. It looks like things have gotten worse since last time anyone came here.": "Tôi đã đến được Trạm Kiểm Lâm (Ranger Station) cmnr, và tôi đang bắt đầu tự hỏi xem liệu đây có phải là một ý tưởng hay đéo. Có vẻ như mọi thứ đã trở nên tồi tệ hơn rất nhiều kể từ lần cuối cùng có một người nào đó đặt chân đến nơi này.",
  "Radio Post": "Trạm Phát Sóng Radio",
  "You tell 'em, Mickey.": "Cậu nói đúng đấy, Mickey.",
  "Get that one off you!": "Hãy gạt cái con đó ra khỏi người của cậu đi!",
  "Outweighed everyone in school, in every grade. Wears it well, and is in top physical form. (Powerhouse)": "Vượt trội hơn tất cả mọi người ở trong trường, ở mọi khối lớp. Sở hữu một thân hình lực lưỡng, và luôn ở trong trạng thái thể lực sung mãn nhất. (Kỹ Năng Nền Tảng Powerhouse)",
  "I mean, shit... leaving those folks to die like that? Cold.": "Ý tôi là, khốn khiếp thật... bỏ mặc cho những người đó phải chết như vậy sao? Thật máu lạnh (Cold).",
  "Advice: Establish An Outpost": "Lời Khuyên (Advice): Thiết Lập Một Tiền Đồn (Outpost)",
  "Prepares our people for combat.": "Chuẩn bị sẵn sàng các trang thiết bị chiến đấu (combat) cho người của chúng ta.",
  "Hey, how come you never just stomp a zombie when it's down? Do you got anger issues?": "Này, tại sao cậu đéo bao giờ chịu giẫm đạp (stomp) lên một con zombie khi mà nó đã bị ngã gục xuống rồi vậy? Cậu có vấn đề về việc kiểm soát sự tức giận của bản thân đéo?",
  "%d added to Supply Locker. (Passable fuel supply.)": "%d đã được thêm vào Tủ Khóa Tiếp Tế (Supply Locker). (Nguồn cung cấp nhiên liệu fuel tạm chấp nhận được.)",
  "Affirmative.": "Đã rõ (Affirmative).",
  "What the fuck are you waiting for?": "Cậu còn đang chờ đợi cái đéo gì nữa vậy?",
  "Milwaukee is now the first major metropolitan area to be officially abandoned by the U.S. Army.": "Milwaukee hiện đã trở thành khu vực đô thị lớn đầu tiên chính thức bị Quân đội Hoa Kỳ (U.S. Army) bỏ rơi hoàn toàn.",
  "All right. We're Oscar-Mike.": "Được rồi. Chúng ta là Oscar-Mike.",
  "YES. We may be here for the long haul.": "VÂNG. Chúng ta có lẽ sẽ phải ở lại đây trong một khoảng thời gian dài đấy.",
  "Come on, man. You can't ask me to do this!": "Thôi nào, anh bạn. Cậu đéo thể nào yêu cầu tôi làm cái chuyện này được đâu!",
  "MISSION: Lone Soldier": "NHIỆM VỤ (MISSION): Người Lính Đơn Độc",
  "A major supply drop called in from a more distant location. Requires sat-comms and a boosted signal.": "Một đợt thả dù tiếp tế (supply drop) lớn vừa mới được yêu cầu hỗ trợ từ một khu vực xa xôi hơn. Cần phải có các thiết bị liên lạc vệ tinh (sat-comms) và một tín hiệu truyền dẫn đã được khuếch đại (boosted signal).",
  "Trumbull Local": "Cư Dân Địa Phương Thung Lũng Trumbull",
  "ADVICE: Build More Outposts": "LỜI KHUYÊN (ADVICE): Hãy Xây Dựng Thêm Nhiều Tiền Đồn (Outposts) Hơn Nữa",
  "Reverse": "Đảo Ngược (Reverse)",
  "Change of plan. Hold off for now.": "Thay đổi kế hoạch cmnr. Hãy tạm dừng lại mọi thứ (Hold off) ngay lúc này.",
  "Well, we can't just stay out here in the open, that's for damn sure.": "Chà, chúng ta đéo thể cứ đứng tơ hơ ở ngoài khu vực trống trải này mãi được, đó là điều chắc chắn.",
  "Rachel": "Rachel",
  "Assault Rifle: M16A4": "Súng Trường Tấn Công (Assault Rifle): M16A4",
  "Disciplined": "Kỷ Luật (Disciplined)",
  "Granderson": "Granderson",
  "Just let me know who to send.": "Chỉ cần cho tôi biết là phải cử ai đi là được.",
  "One of the Wilkersons' flunkies.": "Một trong những tên tay sai của nhà Wilkerson.",
  "Alan has been a forest ranger with the Department of Fish and Wildlife since he graduated from community college.": "Alan đã từng là một nhân viên kiểm lâm trực thuộc Cục Bảo Vệ Cá và Động Vật Hoang Dã kể từ khi anh ấy tốt nghiệp trường cao đẳng cộng đồng.",
  "Standard military hand grenade. This one fell off a truck, a big green truck.": "Loại lựu đạn cầm tay tiêu chuẩn của quân đội. Quả lựu đạn này đã bị rơi ra từ một chiếc xe tải, một chiếc xe tải lớn có màu xanh lá cây.",
  "Not right now, I need a breather.": "Đéo phải ngay lúc này đâu, tôi cần phải có thời gian để nghỉ ngơi lấy lại sức đã.",
  "We don't take kindly to unexpected guests, so you can kindly fuck right off.": "Chúng tôi đéo bao giờ tiếp đón những vị khách đéo mời mà tới một cách tử tế đâu, vì vậy cậu có thể vui lòng cút xéo ngay cho khuất mắt tao.",
  "Leave the rest. We need to go now.": "Hãy bỏ lại phần còn lại đi. Chúng ta cần phải đi ngay bây giờ.",
  "Garden Limb Saw": "Cưa Cành Cây (Garden Limb Saw)",
  "Okay, I think that's it for now.": "Okay, tôi nghĩ hiện tại như vậy là đủ rồi.",
  "Get outta there, now!": "Hãy ra khỏi đó đi, ngay lập tức!",
  "I'm just not used to it, okay?": "Tôi chỉ là vẫn chưa quen với chuyện đó thôi, okay?",
  "That's one less infestation we've got to worry about. -%1$s": "Đó là một Ổ Dịch (infestation) nữa đã được giải quyết để chúng ta bớt phải bận tâm suy nghĩ hơn rồi đấy. -%1$s",
  "30 GENERIC Grant Fitzwallace": "30 CHUNG (GENERIC) Grant Fitzwallace",
  "Affirmative, sir. Shira is his daughter. The doctor is KIA.": "Đã rõ thưa ngài. Shira chính là con gái của ông ấy. Vị Bác sĩ đó đã Tử Trận KIA cmnr.",
  "Work fast. I doubt we'll be alone for long.": "Hãy làm việc cho nhanh lên nào. Tôi đéo nghĩ là chúng ta sẽ được an toàn ở đây trong khoảng thời gian dài đâu.",
  "Lawton": "Lawton",
  "Knew I should have spent more time at the gym!": "Biết ngay là mình lẽ ra nên dành nhiều thời gian hơn ở phòng tập gym mà!",
  "Limited by Fame.": "Bị giới hạn bởi Danh Tiếng (Fame).",
  "Ramirez": "Ramirez"
};

const file = 'output/languages/chunks/btxt_chunk_189.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_189.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk189[r.sourceText]) {
    r.translatedText = chunk189[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 189 successfully!');
