const fs = require('fs');
const chunk139 = {
  "Left high school early to pursue a mechanical career. (Tools Expert)": "Đã bỏ học trung học sớm để theo đuổi nghề cơ khí. (Chuyên Gia Máy Móc)",
  "No-No Picture": "Bức Ảnh Cấm Kỵ",
  "MISSION: Ask the Sheriff": "NHIỆM VỤ: Hỏi Thăm Cảnh Sát Trưởng",
  "Sandra": "Sandra",
  "Watch my back while I gather up some supplies. I think we're going to need them.": "Bọc hậu cho tôi trong lúc tôi thu gom một ít nhu yếu phẩm. Tôi nghĩ chúng ta sẽ cần đến chúng.",
  "People, we need to pull together right fucking now.": "Mọi người, chúng ta cần phải đoàn kết lại ngay lúc chết tiệt này.",
  "Let's do this thing, brah!": "Triển thôi, người anh em!",
  "I used to be a survivor like you. Then I took a zombie to the knee. (Crouching Stamina penalty)": "Tôi từng là một người sống sót như bạn, rồi tôi bị zombie táp trúng đầu gối. (Trừ Thể lực khi ngồi xổm)",
  "Ferguson": "Ferguson",
  "But this bomb is on a dead man's switch. If I die, or if I even start having sad thoughts, Danforth is gone. You hear me?": "Nhưng quả bom này được gắn với công tắc sinh tử (dead man's switch). Nếu tao chết, hay thậm chí nếu tao bắt đầu có những suy nghĩ buồn bã, Danforth sẽ bốc hơi. Mày nghe rõ đéo?",
  "Vipperman": "Vipperman",
  "Note to self: punch Alan right in his goddamn face. - %1$s": "Tự nhắc nhở bản thân: đấm thẳng vào cái mặt chó đẻ của Alan. - %1$s",
  "You don't mess around, do you?": "Cậu đéo phải dạng vừa đâu, nhỉ?",
  "That's all I can ask.": "Đó là tất cả những gì tôi có thể yêu cầu.",
  "Here to make a deal?": "Đến đây để thỏa thuận à?",
  "That's more like it.": "Thế có phải tốt hơn đéo.",
  "So take me to that nuke. I'll disable Eldridge's switch at the source.": "Vậy nên hãy đưa tôi đến chỗ quả bom hạt nhân đó. Tôi sẽ vô hiệu hóa công tắc của Eldridge tận gốc.",
  "Defend the Perimeter": "Bảo Vệ Vành Đai",
  "A quality blade, lightly used.": "Một thanh kiếm chất lượng, ít được sử dụng.",
  "Hood": "Hood",
  "Look, I appreciate your concern. Really, it means a lot.": "Nghe này, tôi rất trân trọng sự quan tâm của cậu. Thực sự đấy, nó có ý nghĩa rất lớn.",
  "I'll need that later.": "Tôi sẽ cần cái đó sau.",
  "When you get it done, things get better. Simple as that.": "Khi cậu hoàn thành công việc, mọi thứ sẽ trở nên tốt đẹp hơn. Đơn giản vậy thôi.",
  "We need a clean place where our medics can do their work.": "Chúng ta cần một nơi sạch sẽ để các bác sĩ có thể làm việc.",
  "What, again? Didn't you just fix it?": "Gì cơ, lại nữa hả? Chẳng phải cậu vừa mới sửa nó sao?",
  "SWAT deployment not available at this time, over.": "Đội SWAT hiện đéo khả dụng để triển khai, hết.",
  "Shaun": "Shaun",
  "Sir?": "Thưa sếp?",
  "Made it to the ranger station, but it looks like we're not out of the woods yet. Heh. Ed will be sad he missed making that pun. - %1$s": "Đã đến được trạm kiểm lâm, nhưng có vẻ như chúng ta vẫn chưa thoát khỏi nguy hiểm (out of the woods). Hờ. Ed sẽ rất buồn vì anh ấy đã bỏ lỡ việc chơi chữ câu này. - %1$s",
  "I don't trust her, but she may be useful": "Tôi đéo tin cô ta, nhưng cô ta có thể hữu dụng",
  "I mean, hell, I hate going out there just to get food.": "Ý tôi là, chết tiệt, tôi ghét việc phải ra ngoài đó chỉ để kiếm thức ăn.",
  "Return to Base": "Trở Về Căn Cứ",
  "Remove Generator": "Tháo Dỡ Máy Phát Điện",
  "Pack it up and move it out.": "Đóng gói đồ đạc và di chuyển thôi.",
  "You're not.": "Đéo phải cậu.",
  "Our best bet is immobilizing them with explosives.": "Cách tốt nhất của chúng ta là làm bất động chúng bằng thuốc nổ.",
  "Look, I don't mean to be rude, but... can you just leave me alone for a little while?": "Nghe này, tôi đéo có ý thô lỗ đâu, nhưng... cậu có thể để tôi yên một lát đéo?",
  "I can't believe it. Lily's dad was actually wearing that watch that she gave him as a kid. Maybe this trip to the Ranger Station was worth it after all.": "Tôi đéo thể tin được. Bố của Lily thực sự đã đeo chiếc đồng hồ mà cô ấy tặng ông khi còn nhỏ. Có lẽ chuyến đi đến Trạm Kiểm Lâm này rốt cuộc cũng đéo uổng phí.",
  "That's a hell of a thing for anybody to see.": "Đó quả là một cảnh tượng kinh khủng đối với bất kỳ ai.",
  "Hall": "Hall",
  "Resolution 1366x768": "Độ phân giải 1366x768",
  "So when we run outta ammo, we supposed to just ask the zeds nicely to leave us alone?": "Vậy khi hết đạn, chúng ta chỉ cần lịch sự yêu cầu lũ zed để chúng ta yên là được à?",
  "He's gonna get swarmed if we don't draw some of them off. Come on, help me look for something to distract them.": "Anh ấy sẽ bị bủa vây nếu chúng ta đéo dụ bớt một vài con đi. Nào, giúp tôi tìm thứ gì đó để đánh lạc hướng chúng.",
  "You got your head, your shoulders, your knees, and your toes. Need me to sing it to you?": "Mày có đầu, vai, đầu gối và ngón chân. Cần tao hát cho mày nghe đéo?",
  "Goddamn right.": "Chuẩn con mẹ nó rồi.",
  "I can handle this.": "Tôi có thể lo vụ này.",
  "Groomed for combat and comes with a threaded barrel.": "Được tinh chỉnh cho chiến đấu và đi kèm với một nòng có ren (threaded barrel).",
  "The AK 47's older sister. Bayonet removed.": "Bà chị gái của AK 47. Đã tháo lưỡi lê.",
  "Are you hearing this?": "Cậu có nghe thấy gì đéo?",
  "All this waiting around is driving me crazy!": "Việc cứ phải chờ đợi quanh quẩn thế này đang làm tôi phát điên!",
  "The rest is up to you.": "Phần còn lại là tùy thuộc vào cậu.",
  "Black Friday, this is Highroad Actual. We've come to the end of the line here.": "Black Friday, đây là Highroad Actual. Chúng ta đã đến đường cùng rồi.",
  "RUMORS: We Are Famous": "TIN ĐỒN: Chúng Ta Đã Nổi Tiếng",
  "Well, at least I won't have to worry about paying off my school loans.": "Chà, ít nhất thì tôi sẽ đéo phải lo lắng về việc trả nợ khoản vay sinh viên nữa.",
  "A ruthless zombie killing tool.": "Một công cụ giết zombie tàn nhẫn.",
  "Rebar": "Thép vằn (Rebar)",
  "I'm getting worried about him. He's barely eating, he hardly says two words to anybody....": "Tôi bắt đầu thấy lo cho anh ấy. Anh ấy gần như đéo ăn uống gì, và cũng hiếm khi nói chuyện với ai....",
  "Right flank, zeds inbound.": "Cánh phải, lũ zed đang kéo đến.",
  "Set up a proper Landing Zone, so we can call in supplies and equipment from the outside.": "Thiết lập một Khu Vực Hạ Cánh (Landing Zone) tử tế, để chúng ta có thể gọi tiếp tế nhu yếu phẩm và trang thiết bị từ bên ngoài.",
  "Svenson": "Svenson",
  "Never say no to extra muscle.": "Đéo bao giờ được nói đéo với sức mạnh cơ bắp bổ sung.",
  "They may not survive without your help.": "Họ có thể đéo sống sót được nếu đéo có sự giúp đỡ của bạn.",
  "I almost feel sorry for the stupid fuckers.": "Tôi gần như thấy thương hại cho mấy thằng ngu khốn kiếp đó.",
  "LOG: Leave is cancelled": "NHẬT KÝ: Việc Rời Đi Đã Bị Hủy Bỏ",
  "Unlocks the ability to create Steel Pipe Bombs. REQUIRES A MUNITIONS SHOP.": "Mở khóa khả năng chế tạo Bom Ống Thép. YÊU CẦU PHẢI CÓ XƯỞNG ĐẠN DƯỢC (MUNITIONS SHOP).",
  "We do have supplies for you. If you need them.": "Chúng tôi có nhu yếu phẩm cho cậu. Nếu cậu cần.",
  "Food won't help, gotta get some rest.": "Thức ăn đéo giúp ích gì đâu, phải nghỉ ngơi thôi.",
  "I think it's time we pulled up stakes.": "Tôi nghĩ đã đến lúc chúng ta nhổ trại rời đi rồi.",
  "HOME: Counseling": "CĂN CỨ: Tư Vấn",
  "SitRep: Local Update #2": "Báo cáo tình hình: Cập nhật địa phương #2",
  "43 STORY Dennis Cross": "43 STORY Dennis Cross",
  "44 GENERIC Becky Silverstone": "44 GENERIC Becky Silverstone",
  "Maybe we need a refresher course on what \"kill it with fire\" means? Better gear up, 'cause we ain't done yet.": "Có lẽ chúng ta cần một khóa bồi dưỡng về ý nghĩa của cụm từ \"giết nó bằng lửa\" chăng? Tốt hơn hết là hãy chuẩn bị đồ đạc đi, vì chúng ta vẫn chưa xong việc đâu.",
  "Cuts down gunshot noise. Made this one out of an oil can, figure it's only good for 10 shots or so.": "Giảm tiếng ồn của súng. Cái này được làm từ một cái lon dầu, dự là chỉ xài được khoảng 10 phát thôi.",
  "Outstanding. We've got this.": "Tuyệt vời. Chúng ta nắm chắc phần thắng rồi.",
  "Only problem is, loading it up will make a lot of noise.": "Vấn đề duy nhất là, việc chất đồ lên xe sẽ tạo ra rất nhiều tiếng ồn.",
  "We need to spot hordes before they spot us.": "Chúng ta cần phát hiện lũ bầy đàn trước khi chúng nhìn thấy chúng ta.",
  "I was laughing so hard I almost couldn't bring myself to brain it.": "Tôi đã cười quá trời đất đến mức gần như đéo nỡ nện vào đầu nó.",
  "So, what did you want to say?": "Vậy, cậu muốn nói gì nào?",
  "The Joker": "Kẻ Thích Đùa (The Joker)",
  "Keep an eye out for construction sites, garages, repair shops... anything like that. They're basically arsenals now.": "Hãy để mắt đến các công trường xây dựng, nhà để xe, xưởng sửa chữa... bất cứ thứ gì đại loại như vậy. Chúng cơ bản là những kho vũ khí vào lúc này đấy.",
  "Remind me to never piss you off.": "Nhớ nhắc tôi đừng bao giờ làm cậu điên tiết nhé.",
  "Choose Your Hero": "Chọn Anh Hùng Của Bạn",
  "Think we've just about wrung this town dry.": "Nghĩ lại thì chúng ta gần như đã vắt kiệt cái thị trấn này rồi.",
  "Back with supplies.": "Đã mang nhu yếu phẩm trở về.",
  "91 GENERIC Ariel Long": "91 GENERIC Ariel Long",
  "Thanks for listening.": "Cảm ơn vì đã lắng nghe.",
  "(Colonel Gregory Peel)": "(Đại tá Gregory Peel)",
  "I'm afraid our little flock may have outgrown its pasture.": "Tôi e rằng bầy cừu nhỏ của chúng ta đã phát triển vượt quá sức chứa của đồng cỏ mất rồi.",
  "Hi ... um, I'm sorry, I don't know what to say. I'm in a building. I think they know I'm here.": "Xin chào... ừm, tôi xin lỗi, tôi đéo biết phải nói gì. Tôi đang ở trong một tòa nhà. Tôi nghĩ chúng biết tôi đang ở đây.",
  "We've found a place to stay.": "Chúng tôi đã tìm được một nơi để tá túc.",
  "And another bust. Freaking great. I told you this was a stupid idea.": "Và lại thêm một cú xôi hỏng bỏng đéo. Thật tuyệt vời làm sao. Tôi đã bảo cậu đây là một ý tưởng ngu xuẩn mà.",
  "Bum Knee": "Đầu Gối Tồi Tàn",
  "Trying to keep Ed out of trouble. Mostly failing.": "Cố gắng giữ cho Ed tránh khỏi rắc rối. Mà phần lớn là thất bại.",
  "WITHDRAWAL: Nicotine": "HỘI CHỨNG CAI NGHIỆN: Nicotine",
  "A package of military construction materials, with a few other supplies to keep our base strong.": "Một gói vật liệu xây dựng quân sự, cùng với vài nhu yếu phẩm khác để giữ cho căn cứ của chúng ta luôn vững chắc.",
  "Yeah some, uh… some folks are kind of worried about you. You okay?": "Phải, một vài... ừm, một vài người có vẻ hơi lo lắng cho cậu. Cậu ổn chứ?",
  "Advice: Upgrade to Shooting Platform": "Lời Khuyên: Nâng Cấp Lên Bục Bắn Súng (Shooting Platform)",
  "Here. Everything we found at the lakeside cabins. Nobody made it out of there.": "Đây. Tất cả những gì chúng tôi tìm thấy ở mấy căn nhà gỗ ven hồ. Đéo một ai sống sót thoát khỏi đó cả.",
  "Ready to have our backs.": "Luôn sẵn sàng bọc hậu cho chúng ta."
};

const file = 'output/languages/chunks/btxt_chunk_139.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_139.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk139[r.sourceText]) {
    r.translatedText = chunk139[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 139 successfully!');
