const fs = require('fs');
const chunk173 = {
  "Diversion Request": "Yêu Cầu Đánh Lạc Hướng (Diversion Request)",
  "Galvin": "Galvin",
  "Pack": "Balo (Pack)",
  "Reminds me of Christmas when I was six. My folks stayed up all night putting together this tree fort in the backyard. Told me it was from Santa.": "Nhắc tôi nhớ đến lễ Giáng sinh năm tôi sáu tuổi. Bố mẹ tôi đã thức trắng đêm để dựng cái pháo đài trên cây này ở sân sau. Rồi bảo với tôi là quà của ông già Noel.",
  "Our Sat-Comms allow us to maintain more Outposts in the field. (Max Outposts raised to 8)": "Hệ thống liên lạc vệ tinh (Sat-Comms) cho phép chúng ta duy trì nhiều Tiền Đồn (Outposts) hơn trên thực địa. (Số lượng Tiền Đồn tối đa tăng lên 8)",
  "Exercise caution. Highroad out.": "Hãy cẩn trọng. Highroad hết (out).",
  "Experimental, .40 caliber pistol from CLEO.": "Súng lục cỡ nòng .40 thử nghiệm từ CLEO.",
  "Trait Discovered: Online Shopper": "Đã Khám Phá Đặc Điểm (Trait): Người Mua Sắm Trực Tuyến (Online Shopper)",
  "I recommend we move to another location immediately.": "Tôi đề nghị chúng ta nên di chuyển đến một địa điểm khác ngay lập tức.",
  "Profile 2": "Hồ Sơ 2",
  "What the hell is Alan up to? - %1$s": "Alan đang định giở cái trò khốn kiếp gì vậy? - %1$s",
  "NEW INFESTATION": "Ổ DỊCH MỚI (NEW INFESTATION)",
  "Tragedy.": "Bi Kịch.",
  "Master the use of Assault Weapons. (Rifles and SMGs)": "Thông thạo việc sử dụng Vũ Khí Đột Kích. (Súng trường và súng tiểu liên SMG)",
  "Figures. Can't risk somebody turning behind your back, right?": "Đoán thế nào cũng vậy. Đéo thể mạo hiểm để ai đó biến đổi thành xác sống ngay sau lưng mình được, phải đéo?",
  "Relax. We got those too.": "Thư giãn đi. Chúng ta cũng có những thứ đó.",
  "I appreciate your concern. It means a lot to me.": "Tôi rất cảm kích sự quan tâm của cậu. Điều đó có ý nghĩa rất lớn đối với tôi.",
  "If the Army isn't here to get us out, what the hell are they doing here? -%1$s": "Nếu Quân Đội đéo ở đây để đưa chúng ta ra ngoài, thì bọn họ đang làm cái quái gì ở đây vậy? -%1$s",
  "Slicing up zombies might dull your blade, but it'll sharpen your Edged Weapon Specialization.": "Chém lũ zombies có thể làm cùn lưỡi kiếm của cậu, nhưng nó sẽ mài sắc Chuyên Môn Vũ Khí Sắc Bén (Edged Weapon Specialization) của cậu.",
  "Hold up. Trouble ahead.": "Khoan đã. Phía trước có rắc rối đấy.",
  "I need some artillery support.": "Tôi cần một chút hỗ trợ pháo binh.",
  "Still plenty of radio chatter, but there've been no new sightings of the Army near us. -%1$s": "Vẫn còn rất nhiều cuộc trao đổi trên radio, nhưng đéo có thêm dấu vết nào mới của Quân Đội ở gần chúng ta cả. -%1$s",
  "Sounds like the Army's \"non-interference\" policy is coming from higher up. -%1$s": "Có vẻ như chính sách \"đéo can thiệp\" của Quân Đội là đến từ cấp trên cao hơn rồi. -%1$s",
  "Well that doesn't suck.": "Chà, điều đó đéo tệ chút nào.",
  "Why am I not surprised?": "Tại sao tôi lại đéo hề cảm thấy ngạc nhiên nhỉ?",
  "Zhang": "Zhang",
  "Yeah I'm bummed too, that asshole owed me twenty bucks.": "Ừ tôi cũng thấy buồn chán, thằng khốn đó còn nợ tôi hai chục đô đấy.",
  "You can switch to any of your FRIENDS.": "Cậu có thể chuyển đổi sang bất kỳ BẠN BÈ (FRIENDS) nào của mình.",
  "Can't believe that noise didn't bring any zombies.": "Đéo thể tin được là cái tiếng ồn đó lại đéo thu hút một con zombie nào kéo đến.",
  "That was too fucking close. Thanks for the help.": "Chết tiệt vừa rồi suýt chút nữa thì xong đời rồi. Cảm ơn vì đã giúp đỡ.",
  "Fox": "Fox",
  "Hold on a minute ...": "Đợi một chút ...",
  "Well, I'm not exactly seeing the light at the end of the tunnel.": "Chà, tôi cũng đéo hẳn là đang nhìn thấy ánh sáng le lói cuối đường hầm đâu.",
  "Success": "Thành Công",
  "Well goddamn, look who's droppin' zeds like flies!": "Chà mẹ kiếp, nhìn xem ai đang hạ gục lũ zeds dễ như đập ruồi kìa!",
  "Head to the Reservoir": "Đi tới Hồ Chứa Nước (Reservoir)",
  "Heavily Tattooed": "Xăm Trổ Đầy Mình (Heavily Tattooed)",
  "I don't know what for, but I figure if anybody can track 'em down, it'd be you.": "Tôi đéo biết để làm gì, nhưng tôi cho rằng nếu có ai đó có thể lùng sục truy dấu bọn chúng, thì đó sẽ là cậu.",
  "Any chance you've made up your mind on whether we could join you?": "Có khả năng nào cậu đã quyết định được việc liệu chúng tôi có thể gia nhập cùng cậu hay đéo chưa?",
  "Prepare for Extraction": "Chuẩn Bị Để Sơ Tán Lộ Trình (Extraction)",
  "Emilio": "Emilio",
  "Connor": "Connor",
  "Everyone gets a weird vibe from this guy. He's treats zombie-killing like it's a game, and talks too much about the \"feeling\" of taking a life. No one knows how he made it through his last psych evaluation.": "Mọi người đều cảm thấy có dự cảm kỳ lạ về gã này. Hắn coi việc giết zombie như một trò chơi, và nói quá nhiều về \"cảm giác\" khi tước đoạt đi một sinh mạng. Đéo ai biết làm thế nào hắn có thể vượt qua được bài kiểm tra tâm lý cuối cùng của mình.",
  "People got hurt, and they couldn't do what had to be done. In the end, somebody turned... and that was all it took.": "Mọi người bị thương, và họ đéo thể làm những gì cần phải làm. Cuối cùng, có ai đó đã biến đổi... và tất cả chỉ có thế.",
  "Well, so much for the annual fishing trip.": "Chà, đến đây là quá đủ cho chuyến đi câu cá hàng năm rồi đấy.",
  "MISSION: The Law": "NHIỆM VỤ: Luật Lệ (The Law)",
  "I'm such a fuck up. Why do you even keep me around?": "Tôi đúng là một kẻ phá hoại tồi tệ. Tại sao mấy người vẫn còn giữ tôi ở lại đây chứ?",
  "Hell yeah!": "Tuyệt vời ông mặt trời!",
  "I know you're out there. I know you're listening.": "Tôi biết cậu đang ở ngoài đó. Tôi biết cậu đang lắng nghe.",
  "They lost nearly their entire unit, but we managed to bring %1$s back alive.": "Bọn họ đã mất gần như toàn bộ đơn vị của mình, nhưng chúng ta đã xoay sở đưa được %1$s trở về sống sót.",
  "Bring %s Home": "Đưa %s Trở Về Nhà",
  "God, I'm so sick of being crammed in here like sardines.": "Chúa ơi, tôi chán ngấy cái cảnh bị nhồi nhét ở đây như cá mòi đóng hộp lắm rồi.",
  "We're gettin' kinda hammered out here on our own. Any room for us to join you?": "Bọn tôi đang bị dần tơi bời ở ngoài này khi phải tự mình xoay sở đây. Có chỗ nào cho bọn tôi gia nhập cùng cậu đéo?",
  "God bless.": "Chúa phù hộ.",
  "We're down to NCO's leading this operation.": "Chúng tôi đéo còn các Hạ Sĩ Quan (NCO) để lãnh đạo chiến dịch này nữa.",
  "Jake wouldn't be much of a loss, but Thomas is pretty good with that revolver.": "Jake sẽ đéo phải là một sự mất mát quá lớn, nhưng Thomas khá là cừ khôi với khẩu súng lục ổ quay đó.",
  "Something about a favor. I dunno, just hurry home, okay? I don't like the way he's looking at me.": "Chuyện gì đó về một đặc ân thì phải. Tôi đéo rõ nữa, cứ nhanh chóng về nhà đi, được đéo? Tôi đéo thích cái cách mà hắn ta đang nhìn tôi chút nào.",
  "Ivan": "Ivan",
  "This cell phone has a cracked screen and almost no battery life left, but the camera function shows a series of images of shambling figures lurking into the light of a campfire while some college kids look on. The last image shows one of the figures grabbing a young man by the shoulders. The call log shows seven dropped calls to 911.": "Chiếc điện thoại di động này có một màn hình bị nứt và hầu như đéo còn chút pin nào, nhưng chức năng camera lại hiển thị một loạt hình ảnh về những bóng dáng lảo đảo đang rình rập tiến vào ánh sáng của một đống lửa trại trong khi một vài sinh viên đại học đang đứng nhìn. Bức ảnh cuối cùng cho thấy một trong số những bóng người đó đang tóm lấy vai một chàng trai trẻ. Nhật ký cuộc gọi cho thấy có bảy cuộc gọi bị rớt đến số 911.",
  "Disturbance at the bridges.": "Sự nhiễu loạn ở khu vực những cây cầu.",
  "Build an Infirmary to reduce the chances of getting sick.": "Xây dựng một Bệnh Xá (Infirmary) để làm giảm thiểu khả năng bị đổ bệnh.",
  "I guess that's one way to get out some aggression.": "Tôi đoán đó là một cách để giải tỏa bớt sự giận dữ căng thẳng.",
  "Requires FANTASY FOOTBALL LEAGUE.": "Yêu cầu GIẢI ĐẤU BÓNG BẦU DỤC ẢO (FANTASY FOOTBALL LEAGUE).",
  "- Empty -": "- Trống -",
  "So what's the story here? Lots of people in this valley need a CasEvac, why aren't you pulling us out?": "Vậy câu chuyện ở đây là sao? Có rất nhiều người trong thung lũng này cần Sơ Tán Y Tế (CasEvac), tại sao các người đéo đưa chúng tôi ra ngoài?",
  "TIP: Press [ul_melee_attack] to attack. Press [cover] to defend.": "MẸO (TIP): Nhấn [ul_melee_attack] để tấn công. Nhấn [cover] để phòng thủ.",
  "Well, that's that then. Now, what'd you want to ask?": "Chà, mọi chuyện là như vậy đó. Bây giờ, cậu muốn hỏi điều gì nào?",
  "Load the RV": "Chất Đồ Lên Xe RV",
  "ATTITUDE: Paralyzed": "THÁI ĐỘ (ATTITUDE): Bị Tê Liệt (Paralyzed)",
  "I've done what I could to smooth things over.": "Tôi đã làm những gì có thể để làm dịu tình hình bớt căng thẳng đi rồi.",
  "I don't need that now.": "Lúc này tôi đéo cần đến thứ đó.",
  "SitRep: Senegal": "Báo Cáo Tình Hình (SitRep): Senegal",
  "Requires Wits Level 4": "Yêu cầu Sự Sắc Bén (Wits) Cấp Độ 4",
  "Remove Refrigerated Storage": "Gỡ Bỏ Kho Lưu Trữ Lạnh (Refrigerated Storage)",
  "A way to bring resources home.": "Một cách để mang các loại tài nguyên về nhà.",
  "You've unlocked an Extra! Press [xi_dpad_left] and [xi_dpad_right] to switch between the Radio channel and the Extras channel.": "Cậu vừa mở khóa được một Tùy Chọn Thêm (Extra)! Nhấn [xi_dpad_left] và [xi_dpad_right] để chuyển đổi qua lại giữa Kênh Radio và Kênh Các Tùy Chọn Thêm.",
  "Is anyone hearing this? I don't want to die!": "Có ai nghe thấy tôi đéo? Tôi đéo muốn chết!",
  "Pistol: OHWS 40": "Súng Lục: OHWS 40",
  "After fully searching a building, I can radio home and have the guys set up an outpost.": "Sau khi tìm kiếm lục soát toàn bộ một tòa nhà, tôi có thể gọi bộ đàm về nhà và nhờ mọi người thiết lập một tiền đồn.",
  "Eagle-Eyed": "Đôi Mắt Tinh Tường (Eagle-Eyed)",
  "A real cheery dearie.": "Đúng là một cưng vui vẻ.",
  "Don't... please, I'm begging you… don't.": "Đừng... làm ơn, tôi cầu xin cậu… đừng.",
  "Axe": "Chiếc Rìu (Axe)",
  "Already your Base.": "Đây Đã Là Căn Cứ (Base) Của Cậu Rồi.",
  "This is what you get when all those self-esteem-building activities in school actually work. It isn't pretty.": "Đây là những gì cậu nhận được khi tất cả những hoạt động xây dựng lòng tự trọng đó ở trường học thực sự có hiệu quả. Trông nó chẳng hay ho tốt đẹp gì đâu.",
  "This is a good location.": "Đây là một địa điểm tốt đấy.",
  "Marathon": "Marathon",
  "The RV's gas tank is empty.": "Bình xăng của chiếc RV đã cạn sạch rồi.",
  "But I decided to come home instead. I had an early morning the next day.": "Nhưng thay vào đó tôi đã quyết định trở về nhà. Ngày hôm sau tôi có việc phải dậy sớm từ sáng.",
  "I don't need any of this.": "Tôi đéo cần bất cứ thứ gì trong đống này cả.",
  "%1$d Barrels of Fuel": "%1$d Thùng Nhiên Liệu (Fuel)",
  "DEFENSE: Outpost Destroyed Horde": "PHÒNG THỦ: Tiền Đồn Đã Tiêu Diệt Một Bầy Xác Sống",
  "AN ACT OF GENEROSITY": "MỘT HÀNH ĐỘNG HÀO PHÓNG (AN ACT OF GENEROSITY)",
  "Cassandra": "Cassandra",
  "SMG: MP 90": "Súng Tiểu Liên (SMG): MP 90",
  "Beefcake!": "Đồ cơ bắp thịt bò (Beefcake)!",
  "Thinks this whole thing is kind of fascinating, if you think about it.": "Nghĩ rằng toàn bộ chuyện này có phần hơi hấp dẫn lôi cuốn, nếu cậu thử nghĩ kỹ về nó.",
  "Be careful. There are a lot of infestations out there.": "Hãy cẩn thận. Ở ngoài kia có rất nhiều những ổ dịch (infestations) đấy.",
  "Choose Whom to Bring on the RV": "Hãy Chọn Những Người Nào Sẽ Được Đưa Lên Chuyến Xe RV",
  "Max out a community member's Wits skill.": "Nâng Tối đa kỹ năng Sự Sắc Bén (Wits) của một thành viên trong cộng đồng."
};

const file = 'output/languages/chunks/btxt_chunk_173.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_173.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk173[r.sourceText]) {
    r.translatedText = chunk173[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 173 successfully!');
