const fs = require('fs');
const chunk156 = {
  "At least you can get around now without the constant risk of getting plowed into by some jackass in an SUV. (Improved cardio.)": "Ít nhất thì bây giờ cậu có thể đi loanh quanh mà đéo phải thường xuyên nơm nớp lo sợ bị tông phải bởi một thằng khốn nào đó lái chiếc SUV. (Cải thiện thể lực - cardio.)",
  "Well, at least we won't have to worry about our ammo supply.": "Chà, ít nhất chúng ta sẽ đéo phải lo lắng về nguồn cung cấp đạn dược nữa.",
  "Yeah, hurry up and wait.": "Ừ, nhanh lên rồi chờ đợi.",
  "That's it! We're done! Game over, man, game over!": "Thế đấy! Chúng ta xong đời rồi! Trò chơi kết thúc rồi, anh bạn, trò chơi kết thúc rồi!",
  "All right, let's see what you've got. Better not be wasting our time.": "Được rồi, để xem cậu có gì nào. Tốt nhất là đừng làm lãng phí thời gian của chúng tôi.",
  "Top scores for handling and acceleration in its class. Someone put a lot of their rent money into this. Four seater.": "Đạt điểm tuyệt đối về khả năng xử lý và tăng tốc trong phân khúc. Ai đó đã đổ rất nhiều tiền thuê nhà của họ vào thứ này. Xe bốn chỗ.",
  "God, I hate this shit.": "Chúa ơi, tôi ghét cái thứ rác rưởi này.",
  "UPGRADED: Weapons Lab": "ĐÃ NÂNG CẤP: Phòng Thí Nghiệm Vũ Khí (Weapons Lab)",
  "Hell with that, Becca's in there!": "Mặc xác chuyện đó đi, Becca đang ở trong đó!",
  "Okay, I know, I know, it was stupid to come out here alone, I just thought... I dunno, if I could find something really useful, maybe Lindsey'd finally like me. You know?": "Được rồi, tôi biết, tôi biết, thật ngu ngốc khi ra ngoài này một mình, tôi chỉ nghĩ... tôi đéo biết nữa, nếu tôi có thể tìm thấy thứ gì đó thực sự hữu ích, có lẽ Lindsey cuối cùng sẽ thích tôi. Cậu biết đéo?",
  "Kill Zone Size": "Kích Thước Vùng Sát Thương (Kill Zone)",
  "Thanks, %1$s. I appreciate what you said. I've been blaming myself for things that aren't under my control. - %2$s": "Cảm ơn, %1$s. Tôi rất trân trọng những gì cậu nói. Tôi đã luôn tự trách bản thân về những thứ đéo nằm trong tầm kiểm soát của mình. - %2$s",
  "Not zombies. Dead people. These folks never turned. No injuries on any of them except a single gunshot, right in the head.": "Đéo phải zombie. Những người chết. Những người này chưa từng bị biến đổi. Không có vết thương nào trên bất kỳ ai trong số họ ngoại trừ một phát súng duy nhất, ngay vào đầu.",
  "Assault Rifle: Tar 21": "Súng Trường Tấn Công: Súng Tar 21",
  "Kramer": "Kramer",
  "Kennedy": "Kennedy",
  "Used exclusively to monitor traffic and communicate with HQ. Recruiting is handled at the Ops Center. Supplies can be ordered from the Landing Zone.": "Được sử dụng độc quyền để theo dõi giao thông và liên lạc với Trụ Sở Chính (HQ). Việc chiêu mộ được xử lý tại Trung Tâm Vận Hành (Ops Center). Nhu yếu phẩm có thể được đặt hàng từ Khu Vực Hạ Cánh (Landing Zone).",
  "For God's sake, I just kept a couple cans of tuna so my wife could eat!": "Vì Chúa, tôi chỉ giữ lại vài hộp cá ngừ để vợ tôi có thể ăn thôi mà!",
  "SitRep: Local Update #5": "Báo Cáo Tình Hình (SitRep): Cập Nhật Địa Phương #5",
  "The Challenge Tab in your Journal displays a list of Challenges, each of which is tied to a particular Hero. Complete a challenge, and its Hero will shortly appear as a recruitable character, and will begin to show up randomly in the world in all your future Breakdown games. You may also select that Hero as your starting character when beginning a new game from scratch. Heroes usually begin with upgraded skills, unique abilities, and special weapons.": "Thẻ Thử Thách (Challenge Tab) trong Nhật ký (Journal) của bạn hiển thị danh sách các Thử Thách, mỗi Thử Thách gắn liền với một Anh Hùng (Hero) cụ thể. Hoàn thành một thử thách, và Anh Hùng đó sẽ sớm xuất hiện dưới dạng một nhân vật có thể chiêu mộ, đồng thời sẽ bắt đầu xuất hiện ngẫu nhiên trong thế giới ở tất cả các màn chơi Breakdown trong tương lai của bạn. Bạn cũng có thể chọn Anh Hùng đó làm nhân vật khởi đầu khi bắt đầu một trò chơi mới từ đầu. Các Anh Hùng thường bắt đầu với các kỹ năng đã được nâng cấp, những khả năng độc đáo, và các loại vũ khí đặc biệt.",
  "Let it be known that we will not tolerate raiders in Marshall. Attacks on fellow survivors will be answered harshly.": "Xin thông báo rằng chúng tôi sẽ đéo dung thứ cho những kẻ cướp bóc ở Marshall. Những cuộc tấn công nhắm vào những người sống sót khác sẽ bị đáp trả một cách tàn nhẫn.",
  "Sarah was the worst.": "Sarah là tồi tệ nhất.",
  "Trust me.": "Tin tôi đi.",
  "Really, army guys? I bring these people in, you keep them alive. That's the deal.": "Thật sự đấy, mấy anh lính? Tôi đưa những người này vào, các anh giữ cho họ sống sót. Thỏa thuận là như vậy.",
  "Salazar": "Salazar",
  "Sheets": "Khăn Trải Giường (Sheets)",
  "Kind of regretting that now.": "Giờ thì tôi hơi hối hận vì chuyện đó rồi.",
  "Those civilians weren't kidding. We've got a major zed situation here.": "Những người dân thường đó đéo hề nói đùa. Chúng ta đang có một tình huống nghiêm trọng với bọn zed ở đây.",
  "Let's do this quietly, folks.": "Hãy làm việc này một cách lặng lẽ nào, các bạn.",
  "Samaritan": "Người Tốt Bụng (Samaritan)",
  "Select Profile": "Chọn Hồ Sơ (Profile)",
  "Before too much longer, we're gonna have to shut the generators off.": "Chẳng bao lâu nữa, chúng ta sẽ phải tắt các máy phát điện đi.",
  "Zombie": "Zombie",
  "It's-- no, never mind, it's stupid.": "Đó là-- đéo, thôi bỏ đi, thật ngu ngốc.",
  "EOD Training Texts": "Giáo Trình Huấn Luyện Tháo Gỡ Bom Mìn (EOD Training Texts)",
  "We went out to try and rescue %1$s, but when we started taking casualties, they fled. We haven't been able to locate them.": "Chúng tôi đã ra ngoài để cố gắng giải cứu %1$s, nhưng khi chúng tôi bắt đầu có thương vong, họ đã bỏ trốn. Chúng tôi vẫn chưa thể xác định được vị trí của họ.",
  "They're coming in the front.": "Chúng đang tràn vào từ phía trước.",
  "36 GENERIC Sam Wenderly": "36 CHUNG (GENERIC) Sam Wenderly",
  "I guess we’ve all been a bit tense lately, wouldn’t you say?": "Tôi đoán dạo gần đây tất cả chúng ta đều hơi căng thẳng, cậu có nghĩ vậy đéo?",
  "Before you ask, no... I don't have sweet nunchuck skills. (Improved Cardio and Fighting.)": "Trước khi cậu hỏi, thì đéo... tôi đéo có kỹ năng múa côn nhị khúc điệu nghệ đâu. (Cải thiện Thể lực và Chiến đấu.)",
  "How bad you think it's getting outside the valley?": "Cậu nghĩ tình hình bên ngoài thung lũng đang tệ đến mức nào?",
  "I'm sorry. I'm so sorry.": "Tôi xin lỗi. Tôi thực sự xin lỗi.",
  "New Waypoint": "Tọa Độ Đánh Dấu (Waypoint) Mới",
  "DEATH: %1$s": "TỬ VONG: %1$s",
  "Seems like you could use some fresh air. Follow me.": "Có vẻ như cậu cần chút không khí trong lành đấy. Theo tôi.",
  "Petersen": "Petersen",
  "Neel": "Neel",
  "Okay, I see the generators, but... they're crawling with zombies.": "Được rồi, tôi thấy các máy phát điện rồi, nhưng... chúng đang bò lổm ngổm toàn zombie.",
  "See how I did that?": "Thấy cách tôi làm điều đó đéo?",
  "I've seen, like, three guys get bit by zeds, and none of 'em dead.": "Tôi đã thấy, kiểu như, ba gã bị bọn zed cắn, và đéo có ai trong số họ chết cả.",
  "%3$s has been really depressed lately. Better do something about that. -%2$s": "%3$s dạo này có vẻ rất suy sụp. Tốt nhất là nên làm gì đó đi. -%2$s",
  "What did you-?": "Cậu đã làm gì-?",
  "Blue pen on crumpled notepaper.": "Bút mực xanh viết trên giấy ghi chú nhàu nát.",
  "A typical garden store blade.": "Một lưỡi dao thường thấy ở cửa hàng dụng cụ làm vườn.",
  "We can leave at any time.": "Chúng ta có thể rời đi bất cứ lúc nào.",
  "Come on, we're moving!": "Thôi nào, chúng ta di chuyển thôi!",
  "That looks like trouble.": "Trông có vẻ như rắc rối rồi đấy.",
  "Assigning someone to staff your kitchen reduces the risk of food poisoning.": "Việc phân công ai đó phụ trách nhà bếp của bạn sẽ giúp làm giảm nguy cơ ngộ độc thực phẩm.",
  "Strict Leader": "Thủ Lĩnh Nghiêm Khắc",
  "Avery": "Avery",
  "Aw, hell!": "Ôi, chết tiệt!",
  "They got inside! They got inside!": "Chúng lọt vào trong rồi! Chúng lọt vào trong rồi!",
  "We can keep flying medivacs to your location, but I'd rather have you back at base than have you sacrifice yourself for a city that can't be saved.": "Chúng tôi có thể tiếp tục cho máy bay sơ tán y tế (medivac) bay đến vị trí của anh, nhưng tôi thà để anh quay lại căn cứ còn hơn là nhìn anh hy sinh bản thân vì một thành phố đéo thể cứu vãn được nữa.",
  "Because I've listened to you talk.": "Bởi vì tôi đã nghe cậu nói chuyện.",
  "KILLED: Sasquatch": "ĐÃ GIẾT: Sasquatch",
  "My guns don't wear out nearly as quick, and when they do jam I clear them faster.": "Súng của tôi đéo bị hao mòn nhanh như vậy đâu, và khi chúng bị kẹt đạn, tôi cũng xử lý nhanh hơn.",
  "Forget about it. You'd have done the same for us.": "Quên chuyện đó đi. Cậu cũng sẽ làm điều tương tự cho chúng tôi thôi.",
  "Almost done!": "Sắp xong rồi!",
  "North gate is down, zeds are inside!": "Cổng Bắc đã sập, bọn zed đang ở bên trong!",
  "Those fuckin' Screamers are a bunch of chumps.": "Đám Screamer khốn khiếp đó chỉ là một lũ thiểu năng.",
  "This doctor … this doctor is supposed to be the expert on zeds, and he killed himself over some monster movie stuff.": "Vị bác sĩ này... vị bác sĩ này được cho là chuyên gia về zed, và ông ta đã tự sát vì mấy thứ vớ vẩn trên phim về quái vật.",
  "All she's seen is the movies. She doesn't know what we do.": "Tất cả những gì cô ta thấy chỉ là qua phim ảnh. Cô ta đéo biết chúng ta phải làm những gì đâu.",
  "Establishing Outpost": "Đang Thiết Lập Tiền Đồn (Outpost)",
  "Any more targets?": "Còn mục tiêu nào nữa đéo?",
  "Quentin says I can RADIO him for advice that'll speed up construction projects. - %1$s": "Quentin nói rằng tôi có thể GỌI BỘ ĐÀM (RADIO) cho anh ấy để xin lời khuyên giúp đẩy nhanh các dự án xây dựng. - %1$s",
  "ATTITUDE: Quiet": "THÁI ĐỘ: Trầm Lặng (Quiet)",
  "REWARD. Delivers a crateload of Pie to your supply locker, and unlocks a new Facility Action in the Kitchen.": "PHẦN THƯỞNG. Giao một thùng bánh Bánh Nướng (Pie) đến tủ đựng đồ của bạn, và mở khóa một Hành Động Cơ Sở (Facility Action) mới trong Nhà Bếp.",
  "Revolver: Toro Bravo": "Súng Lục Ổ Quay (Revolver): Súng Toro Bravo",
  "You saved me.": "Cậu đã cứu tôi.",
  "I don't know what you're looking for.": "Tôi đéo biết cậu đang tìm kiếm cái gì.",
  "As far as Sam is concerned, Trumbull Valley and just about everyone in it can suck her dick.": "Theo như Sam quan tâm, Thung lũng Trumbull và gần như tất cả mọi người trong đó đều có thể bú cu cô ta.",
  "Heine": "Heine",
  "A full-fledged workshop would give us the ability to repair cars.": "Một xưởng (workshop) đầy đủ tiện nghi sẽ cho phép chúng ta sửa chữa xe hơi.",
  "Haha! Did you see that?": "Haha! Cậu có thấy cảnh đó đéo?",
  "Can you please go away? I'm not a big fan of yours right now.": "Cậu có thể vui lòng đi đi được đéo? Bây giờ tôi đéo phải là fan bự của cậu đâu.",
  "That's pretty good.": "Cái đó khá tuyệt đấy.",
  "Timothy Hall is on the way to the capital.": "Timothy Hall đang trên đường đến thủ phủ.",
  "The voice on the radio.": "Giọng nói trên radio.",
  "Professor of microbiology. Family man. Former research partner of Thomas Horn.": "Giáo sư vi sinh vật học. Người đàn ông của gia đình. Cựu đối tác nghiên cứu của Thomas Horn.",
  "I was born ready.": "Tôi sinh ra là để sẵn sàng.",
  "What part of \"hand to hand\" do you not get? You ruined half the samples I need!": "Anh đéo hiểu chỗ nào trong từ \"cận chiến\" hả? Anh đã phá hỏng một nửa số mẫu vật tôi cần rồi đấy!",
  "Let's just find some transportation and get the hell out of here. I don't like being this exposed.": "Hãy tìm một phương tiện di chuyển nào đó và cút khỏi đây thôi. Tôi đéo thích bị phơi mình ra thế này đâu.",
  "Use caution when exploring.": "Hãy thận trọng khi đi khám phá.",
  "Kim Jong-zed?": "Kim Jong-zed sao?",
  "That is that.": "Thế là xong.",
  "Ly": "Ly",
  "If we hide here, we can catch our breath.": "Nếu chúng ta trốn ở đây, chúng ta có thể lấy lại sức.",
  "Avid Surfer": "Người Đam Mê Lướt Sóng",
  "That was pretty crazy.": "Chuyện đó khá là điên rồ đấy.",
  "A dedicated ammunition shop will let us refill our brass, and manufacture the ammunition we need from the random stuff we scavenge in the field.": "Một cửa hàng đạn dược chuyên dụng sẽ cho phép chúng ta nạp lại vỏ đạn, và chế tạo lượng đạn dược cần thiết từ những món đồ ngẫu nhiên mà chúng ta nhặt nhạnh được trên thực địa."
};

const file = 'output/languages/chunks/btxt_chunk_156.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_156.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk156[r.sourceText]) {
    r.translatedText = chunk156[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 156 successfully!');
