const fs = require('fs');
const chunk162 = {
  "Fine, you hold her hand.": "Được thôi, cậu đi mà nắm tay cô ấy.",
  "Let's move out, then.": "Vậy thì, đi thôi.",
  "Hey, I can't bail your sorry ass out all the time. Got all these other shitheads to look out for.": "Này, tôi đéo thể lúc nào cũng cứu cái mạng quèn của cậu được đâu. Còn cả đống lũ khốn khác cần phải để mắt tới đây này.",
  "Don't push yourself too hard. You need to give yourself time to heal at home.": "Đừng có cố quá. Cậu cần phải cho bản thân thời gian để hồi phục ở nhà.",
  "Learned how to make backyard bombs on the internet. Posted slow motion videos of friends walking away from explosions. (Chemistry Expert)": "Học cách chế tạo bom tự chế trên internet. Đăng các video quay chậm cảnh bạn bè bước đi khỏi những vụ nổ. (Chuyên gia Hóa học - Chemistry Expert)",
  "SUV Bubbles!": "Chiếc SUV Bubbles!",
  "That's just disturbing on so many levels.": "Chuyện đó thật đáng lo ngại trên rất nhiều phương diện.",
  "Dead Man's Party! Extra hordes. Extra infestations. Moderate extra damage. Lethal Juggernauts. No map indicator.": "Bữa Tiệc Của Kẻ Chết (Dead Man's Party)! Thêm hordes. Thêm Ổ dịch (infestations). Sát thương gây ra thêm ở mức vừa phải. Juggernauts Gây Chết Người. Không có chỉ báo trên bản đồ.",
  "%+d Community Fame (Flawless)": "%+d Danh Tiếng Cộng Đồng (Community Fame) (Hoàn Hảo)",
  "Dylan": "Dylan",
  "We're getting too many refugees in here as it is. We can't afford to feed a bunch of globe-trotting scam artists.": "Chúng ta đã nhận quá nhiều người tị nạn vào đây rồi. Chúng ta đéo thể cáng đáng nổi việc nuôi một lũ lừa đảo đi chu du khắp thế giới đâu.",
  "Quentin Barnes? From the grange?": "Quentin Barnes? Đến từ trang trại (grange) à?",
  "Hey, congratulations!": "Này, chúc mừng nhé!",
  "Bad Blood Turned to Bloodshed": "Mối Thù Hằn Biến Thành Cuộc Tắm Máu",
  "COMPLETED: Not Alone": "ĐÃ HOÀN THÀNH: Không Hề Đơn Độc (Not Alone)",
  "Should I come back and help?": "Tôi có nên quay lại và giúp một tay đéo?",
  "%2$s is doing better.": "%2$s đang làm tốt hơn rồi.",
  "I'll point it out on your map.": "Tôi sẽ chỉ nó ra trên bản đồ của cậu.",
  "Let's hoof it, people. Stay low and stay quiet.": "Đi thôi mọi người. Đi khom người và giữ im lặng nhé.",
  "Almost there!": "Sắp tới rồi!",
  "One of our scouts encountered a Feral while out on patrol. We took it down to buyt ourselves some time before the next siege ... but we suffered a loss in the process.": "Một trong những trinh sát của chúng tôi đã chạm trán với một con Feral khi đang đi tuần tra. Chúng tôi đã hạ gục nó để câu giờ cho bản thân trước cuộc vây hãm tiếp theo... nhưng chúng tôi đã phải gánh chịu tổn thất trong quá trình đó.",
  "Whitaker": "Whitaker",
  "We're moving out. Be there soon!": "Chúng tôi đang di chuyển. Sẽ đến đó sớm thôi!",
  "You've been a good friend to me, and to the people of this valley. When we start to rebuild on a larger scale, you're exactly the kind of person I'm going to want on my side.": "Cậu đã là một người bạn tốt đối với tôi, và với người dân ở thung lũng này. Khi chúng ta bắt đầu xây dựng lại ở quy mô lớn hơn, cậu chính xác là kiểu người mà tôi muốn có ở bên cạnh mình.",
  "He don't get better soon, you know what I gotta-": "Anh ta mà đéo khá hơn sớm, cậu biết tôi phải làm gì rồ-",
  "We got a big trade going down with them folks over at the ranch house.": "Chúng ta có một vụ giao dịch lớn đang diễn ra với những người ở ngôi nhà trang trại đó.",
  "Use [moveforward], [moveleft], [moveback], [moveright] to move.": "Sử dụng [moveforward], [moveleft], [moveback], [moveright] để di chuyển.",
  "Event: Ally Hurt": "Sự kiện: Đồng minh Bị thương",
  "Collects notes on survival techniques, giving everyone a boost to Wits XP for the week.": "Thu thập các ghi chú về kỹ năng sinh tồn, giúp tăng cường Kinh Nghiệm Trí Tuệ (Wits XP) cho mọi người trong tuần.",
  "Instead of moping around, how about you help me out?": "Thay vì ủ rũ lảng vảng quanh đây, hay là cậu giúp tôi một tay đéo?",
  "Larry": "Larry",
  "Yeah. It's time for a change of scenery.": "Ừ. Đã đến lúc phải thay đổi môi trường sống (change of scenery) rồi.",
  "Welcome to the Savini Residence": "Chào mừng đến với Dinh Thự Savini (Savini Residence)",
  "A replica of the famous Ulfberht swords.": "Một bản sao của những thanh kiếm Ulfberht nổi tiếng.",
  "They might not be as bad as hordes, but even having a few zombies wandering around here is a risk.": "Chúng có thể đéo tồi tệ như bọn hordes, nhưng ngay cả việc có một vài con zombie lang thang quanh đây cũng là một mối rủi ro.",
  "SET UP: Warehouse Storage Area": "THIẾT LẬP: Khu Vực Kho Chứa (Warehouse Storage Area)",
  "Grace": "Grace",
  "Do you see that?": "Cậu có nhìn thấy đéo?",
  "NOTE: Chopper Sightings": "GHI CHÚ (NOTE): Những Lần Nhìn Thấy Trực Thăng (Chopper Sightings)",
  "Fell victim to the Pastor.": "Đã trở thành nạn nhân của Mục sư (Pastor).",
  "Hey, dipshit. We're trying to be sneaky here.": "Này, đồ ngu. Chúng ta đang cố gắng hành động lén lút ở đây đấy.",
  "Goddammit. Come on, then, we better go bail them out.": "Chết tiệt. Đi thôi, chúng ta tốt hơn hết là nên đi giải cứu họ.",
  "Well, I ... heard you on the radio.": "À thì, tôi... đã nghe thấy cậu trên đài radio.",
  "Roger that, Greyhound One. Might want to hurry back. We're seeing a lot of movement around here.": "Đã rõ, Greyhound Một. Tốt nhất các anh nên vội vã quay lại đi. Chúng tôi đang thấy có rất nhiều chuyển động quanh đây.",
  "NO. He needs to complete this on his own.": "ĐÉO. Cậu ta cần phải tự mình hoàn thành việc này.",
  "A hiding spot.": "Một chỗ trốn.",
  "Val": "Val",
  "Kill 50 Zombies with Explosives. (Breakdown Level 4 or Higher)": "Giết 50 con Zombie bằng Thuốc nổ (Explosives). (Chế độ Breakdown Cấp độ 4 trở lên)",
  "SURVIVAL TACTICS: Safe Areas": "CHIẾN THUẬT SINH TỒN (SURVIVAL TACTICS): Các Khu Vực An Toàn (Safe Areas)",
  "Gimme a few more minutes.": "Cho tôi thêm vài phút nữa.",
  "I hoped for better from you.": "Tôi đã hy vọng cậu làm tốt hơn thế này.",
  "Let's get back in the car.": "Quay lại xe thôi.",
  "Tactics: Thin the Herd": "Chiến thuật: Tỉa Bớt Bầy Đàn (Thin the Herd)",
  "Affirmative, Doghouse is no longer active... but ... before we lost contact he sent us a burst transmission with plenty of intel.": "Xác nhận, Nhà Chó (Doghouse) đéo còn hoạt động nữa... nhưng... trước khi mất liên lạc, anh ấy đã gửi cho chúng ta một đường truyền dữ liệu chớp nhoáng (burst transmission) với rất nhiều thông tin tình báo.",
  "Cram a noisemaker into an improvised mine, and it lures the zombies in before it explodes. Nice.": "Nhét một thiết bị tạo tiếng ồn vào một quả mìn tự chế, và nó sẽ dụ lũ zombie lại gần trước khi phát nổ. Tuyệt đấy.",
  "It's funny how the world ending makes some folks better people.": "Thật nực cười làm sao khi ngày tận thế lại khiến một số người trở thành người tốt hơn.",
  "I'd like to see more of that!": "Tôi muốn nhìn thấy nhiều pha như thế nữa!",
  "Chinedu": "Chinedu",
  "Guess we bit off a little more than we could chew. Don't suppose you'd be willing to give us a hand?": "Đoán là chúng tôi đã làm chuyện đéo lượng sức mình rồi. Chắc cậu đéo sẵn lòng giúp chúng tôi một tay đâu nhỉ?",
  "Nothing useful here.": "Đéo có gì hữu ích ở đây cả.",
  "Rescued": "Đã Giải Cứu",
  "We've got to do something soon, it's getting way too dangerous out there.": "Chúng ta phải làm gì đó sớm thôi, ngoài kia đang trở nên quá đỗi nguy hiểm rồi.",
  "Forbes": "Forbes",
  "Whatever. Just... whatever.": "Sao cũng được. Chỉ là... sao cũng được.",
  "Greatly reduced Vitality and Stamina. Bed rest is advised. Moderate chance of recovery every 24 hours.": "Bị giảm đáng kể Sinh Lực (Vitality) và Thể Lực (Stamina). Khuyên dùng nghỉ ngơi trên giường. Có cơ hội phục hồi ở mức vừa phải sau mỗi 24 giờ.",
  "Here's the coordinates.": "Tọa độ đây.",
  "That did it. Thanks, Doc.": "Xong rồi đấy. Cảm ơn nhé, Doc.",
  "Everybody here's occupied. Sorry.": "Mọi người ở đây đều đang bận việc rồi. Xin lỗi nhé.",
  "HUNGRY: Weak from Hunger": "ĐÓI (HUNGRY): Suy yếu do Đói",
  "Lemme kill some zeds before I answer that.": "Để tôi giết vài con zeds trước khi trả lời câu đó đã.",
  "%d Cases of Medicine": "%d Thùng Thuốc Men (Cases of Medicine)",
  "Aaron": "Aaron",
  "Mauser": "Mauser",
  "Wendy": "Wendy",
  "Please restart the game to switch to this game mode.": "Vui lòng khởi động lại trò chơi để chuyển sang chế độ chơi này.",
  "Listen, asshole, we don't want any trouble!": "Nghe này, thằng khốn, bọn tao đéo muốn gặp bất cứ rắc rối nào đâu!",
  "Powerful round primarily for revolvers and some rifles.": "Loại đạn mạnh mẽ chủ yếu dùng cho súng lục ổ quay và một số súng trường.",
  "Oh, Christ... It's... Has everybody gone nuts?": "Ôi, Chúa ơi... Chuyện này... Mọi người phát điên hết cả rồi sao?",
  "Jesus, that one looks vicious.": "Chúa ơi, con đó trông có vẻ hung tợn đấy.",
  "What the hell's wrong with you?": "Cậu bị cái quái gì vậy hả?",
  "The Threat Level Indicator below the mini-map warns you when a zombie attack is imminent at your base.": "Chỉ báo Mức Độ Nguy Hiểm (Threat Level Indicator) bên dưới bản đồ nhỏ cảnh báo cho bạn khi có một cuộc tấn công của zombie sắp xảy ra tại căn cứ của bạn.",
  "I’m not saying we should leave right NOW, necessarily. We’ve all gotten pretty attached to this place.": "Tôi đéo nói là chúng ta nên rời đi NGAY BÂY GIỜ đâu. Tất cả chúng ta đều đã khá gắn bó với nơi này rồi.",
  "Come on, up you get. We need to get you out of your funk.": "Thôi nào, đứng lên đi. Chúng ta cần kéo cậu ra khỏi tình trạng ủ rũ này.",
  "You get allergies, you blow your nose like an adult and get back to work!": "Cậu bị dị ứng, cậu hỉ mũi như một người lớn rồi quay trở lại làm việc đi!",
  "155 HERO Gurubani Kaur": "155 ANH HÙNG (HERO) Gurubani Kaur",
  "You've joined a Community! Press [ul_journal_menu] to open your Journal and learn more about your fellow survivors on the Community page.": "Bạn đã tham gia vào một Cộng Đồng (Community)! Nhấn [ul_journal_menu] để mở Nhật Ký (Journal) và tìm hiểu thêm về những người sống sót cùng bạn trên trang Cộng Đồng.",
  "19 GENERIC Ben Greene": "19 CHUNG (GENERIC) Ben Greene",
  "Remove Barracks": "Dỡ bỏ Doanh Trại (Barracks)",
  "Hey. Thanks, by the way. You really busted your ass for us back there. We won't forget that.": "Này. Nhân tiện, cảm ơn nhé. Cậu đã thực sự liều mạng vì chúng tôi ở đằng kia. Chúng tôi sẽ đéo bao giờ quên điều đó đâu.",
  "C'mon. This has gotta be making you feel better, right?": "Thôi nào. Chuyện này hẳn phải làm cho cậu cảm thấy tốt hơn chứ, phải đéo?",
  "Edmond": "Edmond",
  "Oh God, help me! I don't want to die like this!": "Ôi Chúa ơi, cứu tôi với! Tôi đéo muốn chết như thế này đâu!",
  "Sounds good to me.": "Nghe có vẻ ổn đối với tôi đấy.",
  "Book on Car Maintenance": "Sách Về Bảo Dưỡng Ô tô",
  "So you robbed a dead guy. And you expect his friends to help us out?": "Vậy là cậu đã cướp đồ của một gã chết tiệt. Và cậu hy vọng bạn bè của hắn ta sẽ giúp chúng ta sao?",
  "Let's find some asshole to shoot.": "Hãy đi tìm vài thằng khốn để bắn nào.",
  "Research has kinda slowed to a crawl.": "Quá trình nghiên cứu (Research) có vẻ như đang chậm như rùa bò.",
  "Guys, guys, guys. Don't you think we've got enough ways to get messed up without fighting amongst ourselves?": "Mọi người, mọi người, mọi người à. Mọi người đéo nghĩ là chúng ta đã có đủ cách để bị ăn hành mà đéo cần phải đánh nhau trong nội bộ sao?",
  "25 MIL Cpl Hank Green": "25 QUÂN ĐỘI (MIL) Hạ Sĩ (Cpl) Hank Green",
  "Sorry, Becks. Figured you'd yell at me if I told you.": "Xin lỗi nhé, Becks. Tớ nghĩ là cậu sẽ la mắng tớ nếu tớ nói cho cậu biết."
};

const file = 'output/languages/chunks/btxt_chunk_162.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_162.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk162[r.sourceText]) {
    r.translatedText = chunk162[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 162 successfully!');
