const fs = require('fs');
const chunk161 = {
  "What good are samples without the doctor?": "Mấy cái mẫu vật có ích lợi mẹ gì nếu đéo có bác sĩ chứ?",
  "Lily heard a rumor over the radio that there's a broken-down RV in the valley. Apparently, it's in good enough shape to get us out of here with just a few minor repairs. I should go check it out, in case we need it one day.": "Lily nghe được một tin đồn qua radio rằng có một chiếc RV bị hỏng nằm trong thung lũng. Rõ ràng, nó vẫn còn đủ tốt để đưa chúng ta ra khỏi đây chỉ với một vài sửa chữa nhỏ. Tôi nên đến kiểm tra thử xem sao, phòng khi chúng ta cần dùng đến nó vào một ngày nào đó.",
  "Got some zombies for you to shoot here, Mickey.": "Có vài con zombie cho cậu bắn đây, Mickey.",
  "You're giving away our goddamn position with this Rambo routine.": "Anh đang làm lộ vị trí chết tiệt của chúng ta bằng cái trò Rambo này đấy.",
  "Nearly done here.": "Sắp xong ở đây rồi.",
  "Set Up Dining Area": "Thiết Lập Khu Vực Ăn Uống (Dining Area)",
  "Dammit, horde spotted us!": "Chết tiệt, bọn horde đã phát hiện ra chúng ta rồi!",
  "Well, they do say misery loves company....": "Chà, người ta thường nói đồng bệnh tương lân mờ....",
  "Let's head back to my enclave.": "Hãy quay lại khu tự trị (enclave) của tôi thôi.",
  "2 Outposts - PMC Reinforcements": "2 Tiền Đồn (Outpost) - Lính Đánh Thuê (PMC) Viện Trợ",
  "We sure could use your help around here.": "Chúng tôi chắc chắn rất cần sự giúp đỡ của cậu quanh đây.",
  "I could use a bit of help!": "Tôi cần một chút giúp đỡ!",
  "These attacks gradually wear down morale.": "Những cuộc tấn công này dần dần làm suy giảm tinh thần.",
  "Damn, it feels good to be alive!": "Chết tiệt, cảm giác được sống thật là tốt!",
  "No Nonsense": "Đéo Nói Nhảm (No Nonsense)",
  "Evan": "Evan",
  "I can't stop thinking about how those zombies nearly killed me. I'm not sleeping, I'm having flashbacks ... I'm sorry, what were we talking about? (Overall XP and Health penalty)": "Tôi đéo thể ngừng suy nghĩ về việc lũ zombie đó suýt giết chết tôi như thế nào. Tôi đéo ngủ được, tôi cứ bị ảo giác (flashbacks) ... Tôi xin lỗi, chúng ta đang nói về chuyện gì vậy? (Bị phạt Kinh Nghiệm - XP và Máu - Health tổng thể)",
  "Let me think a little bit more on this.": "Để tôi suy nghĩ thêm một chút về chuyện này.",
  "The remains are cross-contaminated all to hell. We're not going to get anything useful here.": "Những tàn tích này đã bị ô nhiễm chéo cmnr. Chúng ta sẽ đéo thu thập được bất cứ thứ gì hữu ích ở đây đâu.",
  "I've got a few ideas on where we could look.": "Tôi có một vài ý tưởng về nơi chúng ta có thể tìm kiếm.",
  "Disapproves.": "Phản đối.",
  "KIA, sir. All officers are down.": "Hy sinh rồi, thưa ngài. Tất cả các sĩ quan đều đã gục ngã.",
  "Soldiers, ma'am.": "Những người lính, thưa cô.",
  "Tyler": "Tyler",
  "Something's going on with the Generators.": "Có chuyện gì đó đang xảy ra với các Máy Phát Điện (Generator).",
  "Can't we just shoot it, set it off that way?": "Chúng ta đéo thể cứ thế bắn nó, kích nổ nó theo cách đó sao?",
  "Now that's some weird shit right there.": "Chuyện này đúng là quá kỳ lạ.",
  "Resolution 3840x2160": "Độ phân giải 3840x2160",
  "152 HERO Sgt Kilohana Young": "152 ANH HÙNG (HERO) Trung Sĩ (Sgt) Kilohana Young",
  "Play State of Decay": "Chơi State of Decay",
  "Raffone": "Raffone",
  "Safely in the air ... but alone.": "Đang an toàn trên không trung ... nhưng chỉ có một mình.",
  "Hmm. Maybe not.": "Hmm. Có lẽ là đéo.",
  "Witness Protection": "Chương Trình Bảo Vệ Nhân Chứng (Witness Protection)",
  "That's a big fuck you to zed.": "Đó là một câu chửi thề cực lớn ném thẳng vào mặt bọn zed.",
  "Feel like talking about it?": "Cậu có muốn nói về nó đéo?",
  "Keep your eye on our right, we've got zombies incoming.": "Hãy để mắt tới phía bên phải, có bọn zombie đang kéo tới.",
  "Infestation destroyed": "Đã tiêu diệt Ổ dịch (Infestation)",
  "Gamertag": "Gamertag",
  "Okay, show me the ropes.": "Được rồi, chỉ cho tôi cách làm đi.",
  "Lott": "Lott",
  "Bring %s home": "Đưa %s về nhà",
  "40%": "40%",
  "Hey, does anyone know what's happening over in the Valley? I haven't heard anything from the folks in Marshall.": "Này, có ai biết chuyện gì đang xảy ra bên Thung Lũng đéo? Tôi đéo nghe được tin tức gì từ những người ở Marshall cả.",
  "Fratres Carmeli navigant in a bothe apud Eli,\r\nNon sunt in coeli quia fuccant uuiuys of heli.": "Fratres Carmeli navigant in a bothe apud Eli,\r\nNon sunt in coeli quia fuccant uuiuys of heli.",
  "I'm sorry. That doesn't seem very fair.": "Tôi rất tiếc. Điều đó có vẻ đéo công bằng cho lắm.",
  "Just do this quietly.": "Cứ làm việc này một cách lặng lẽ.",
  "Under Siege": "Đang Bị Vây Hãm",
  "Those zeds didn't stand a chance, huh?": "Bọn zed đó đéo có cửa nào luôn, hả?",
  "I'm sorry, but I'm going to have to ask you to move on. The Captain gets cranky when people contaminate her scene.": "Tôi xin lỗi, nhưng tôi sẽ phải yêu cầu cậu di chuyển đi. Đội trưởng sẽ cáu kỉnh nếu có người làm ô nhiễm hiện trường của cô ấy.",
  "Cleo is sending us magic air strike grenades now?": "Bây giờ Cleo đang gửi cho chúng ta lựu đạn không kích ma thuật đấy à?",
  "The Colleague": "Đồng Nghiệp",
  "So um, what happened to the guy the Wilkersons beat up?": "Vậy ừm, chuyện gì đã xảy ra với gã bị nhà Wilkerson đánh đập vậy?",
  "Probably should have brought somebody more useful than me.": "Lẽ ra nên mang theo ai đó hữu ích hơn tôi.",
  "Listen, I'm not leaving you here and I'm damn sure not carrying you, so pull yourself together and follow me!": "Nghe này, tôi sẽ đéo bỏ cậu lại đây và tôi đéo đời nào vác cậu trên vai đâu, nên hãy xốc lại tinh thần và theo tôi ngay!",
  "We've got a horde sighting.": "Chúng ta đã phát hiện ra một bầy horde.",
  "Set the timer and run like hell. Zombies'll come running like it's Sunday dinner.": "Hẹn giờ và cắm đầu cắm cổ mà chạy. Lũ zombie sẽ lao đến như thể đây là bữa tối Chủ nhật vậy.",
  "Suicide Hotline": "Đường Dây Nóng Ngừa Tự Tử (Suicide Hotline)",
  "Sounds like somebody lost one of their people. - %1$s": "Có vẻ như ai đó đã mất đi người thân của họ rồi. - %1$s",
  "I'll mark survey locations on my map with BINOCULARS.": "Tôi sẽ đánh dấu các vị trí khảo sát trên bản đồ của mình bằng ỐNG NHÒM (BINOCULARS).",
  "Invert X-Axis": "Đảo Ngược Trục X (Invert X-Axis)",
  "A group of survivors is interested in joining our community. - %2$s": "Một nhóm người sống sót đang quan tâm đến việc gia nhập cộng đồng của chúng ta. - %2$s",
  "Priorities": "Những Ưu Tiên (Priorities)",
  "We'll pack this away for a rainy day.": "Chúng ta sẽ cất thứ này đi để dành cho những ngày giông bão.",
  "Sam and Alan are waiting at the clinic. I'll put up with Alan if it means getting the meds. -%1$s": "Sam và Alan đang đợi ở phòng khám. Tôi sẽ chịu đựng Alan nếu điều đó có nghĩa là lấy được số thuốc. -%1$s",
  "Find out where you stand.": "Tìm hiểu xem vị thế của cậu đang ở đâu.",
  "So that's what I'm doing. Just helping out, any way I can. You need supplies, I can arrange a trade. You need a car, I can hook you up.": "Vậy nên đó là những gì tôi đang làm. Chỉ là giúp đỡ bằng bất cứ cách nào tôi có thể. Nếu cậu cần nhu yếu phẩm, tôi có thể sắp xếp một cuộc trao đổi. Nếu cậu cần một chiếc xe, tôi có thể móc nối cho cậu.",
  "Quentin Contacted": "Đã Liên Hệ Với Quentin",
  "Enemy targets acquired.": "Đã xác định được mục tiêu của kẻ thù.",
  "You ain't got the clearance.": "Anh đéo có quyền truy cập đâu.",
  "Could use our help.": "Có thể cần sự giúp đỡ của chúng ta.",
  "Who's... can't see... help me...": "Ai đó... đéo nhìn thấy... giúp tôi với...",
  "All right, people, I want samples of everything in here. Food, medicine, toothbrushes, dirty underpants, bag it, tag it, and get it back to the lab!": "Được rồi, mọi người, tôi muốn lấy mẫu của mọi thứ ở đây. Thức ăn, thuốc men, bàn chải đánh răng, quần lót bẩn, đóng gói, gắn thẻ và mang nó trở lại phòng thí nghiệm!",
  "Escape: Find a Large Vehicle": "Trốn Thoát: Tìm Một Chiếc Xe Lớn (Find a Large Vehicle)",
  "46 VIP Timothy Hall": "46 KHÁCH VIP Timothy Hall",
  "Shit, here we go!": "Chết tiệt, chúng ta tới đây!",
  "Storage Device Removed": "Đã Gỡ Bỏ Thiết Bị Lưu Trữ",
  "Total Fame Earned": "Tổng Số Danh Tiếng (Fame) Đã Kiếm Được",
  "+32%": "+32%",
  "Was that too much? I was kinda going for a Doc Hanson thing there.": "Như vậy có quá đáng đéo? Tôi chỉ đang cố bắt chước phong cách của Doc Hanson thôi.",
  "Boyle": "Boyle",
  "We don't have enough soldiers left to go on risky zombie hunts.": "Chúng ta đéo còn đủ lính để thực hiện những cuộc đi săn zombie đầy rủi ro đâu.",
  "Either way, we should look into it. Having electricity will open a lot of doors for us.": "Dù sao đi nữa, chúng ta cũng nên xem xét chuyện đó. Có điện sẽ mở ra rất nhiều cơ hội cho chúng ta.",
  "Roger that, Doghouse. Greyhound out.": "Đã rõ, Nhà Chó (Doghouse). Greyhound xin ngừng kết nối.",
  "So this is about Tom?": "Vậy chuyện này là về Tom à?",
  "Not that I should go to jail or anything.": "Đéo phải là tôi nên vào tù hay gì cả đâu.",
  "Adrian": "Adrian",
  "Kill one of each freak zombie type.": "Giết một con trong mỗi loại zombie dị dạng (freak).",
  "Guess we can't quit now, huh?": "Đoán là chúng ta đéo thể bỏ cuộc bây giờ được rồi, hả?",
  "Vitality drops whenever you get hurt. Taking serious damage lowers your Maximum Vitality.": "Sinh Lực (Vitality) giảm xuống bất cứ khi nào bạn bị tổn thương. Chịu sát thương nghiêm trọng sẽ làm giảm Sinh Lực Tối Đa (Maximum Vitality) của bạn.",
  "Kiara": "Kiara",
  "Heroic Multikill": "Pha Tiêu Diệt Hàng Loạt Khó Tin (Heroic Multikill)",
  "Bag's full, I say we head out.": "Balo đã đầy, tôi nghĩ chúng ta nên đi thôi.",
  "This right here is why giving everybody a gun is a bad idea. - %2$s": "Chính vì điều này mà việc phát súng cho mọi người là một ý tưởng tồi. - %2$s",
  "Fucking shit-fuck!": "Mẹ kiếp khốn nạn vãi lồn!",
  "We can't keep this up forever.": "Chúng ta đéo thể tiếp tục như thế này mãi được.",
  "Now I know you're not gonna leave this beauty sitting on the side of the road.": "Giờ thì tôi biết cậu sẽ đéo để người đẹp này nằm chình ình bên lề đường đâu.",
  "Peel's ordered us into Danforth tomorrow to exfil some VIP.\r\nI'm looking forward to being useful again rather than just getting yelled at by the Colonel. \r\nHere's hoping the city isn't lost yet.": "Peel đã ra lệnh cho chúng tôi tiến vào Danforth vào ngày mai để giải cứu một số VIP.\r\nTôi rất mong chờ được trở nên hữu ích thêm một lần nữa thay vì chỉ bị Đại tá la mắng. \r\nHy vọng là thành phố vẫn chưa thất thủ.",
  "What's going on is there's more of them up here than I expected. We need to sweep the rest of the cabins for survivors, but I've got injured people here I have to tend to.": "Chuyện gì đang xảy ra là có nhiều bọn chúng ở trên này hơn tôi dự tính. Chúng ta cần dọn dẹp các túp lều còn lại để tìm người sống sót, nhưng tôi có những người bị thương ở đây cần phải chăm sóc.",
  "Dunno about you, but killin' these things makes me feel...more alive, I guess.": "Đéo biết cậu thấy sao, nhưng giết những thứ này làm tôi cảm thấy... giống như mình đang thực sự sống hơn, tôi đoán vậy."
};

const file = 'output/languages/chunks/btxt_chunk_161.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_161.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk161[r.sourceText]) {
    r.translatedText = chunk161[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 161 successfully!');
