const fs = require('fs');
const chunk169 = {
  "Then we're done here.": "Vậy là chúng ta xong việc ở đây rồi.",
  "Thought you'd want to know I made it. I met up with some good people. I have a new home now. - %1$s": "Nghĩ rằng cậu sẽ muốn biết là tôi đã làm được. Tôi đã gặp gỡ được một vài người tốt. Bây giờ tôi đã có một mái nhà mới rồi. - %1$s",
  "Creates a few improvised Potent Stims.": "Chế tạo một vài ống thuốc kích thích cực mạnh (Potent Stims) dã chiến.",
  "Hero Sighted": "Đã Nhìn Thấy Vị Anh Hùng (Hero Sighted)",
  "We've lost too many people already.": "Chúng ta đã mất quá nhiều người rồi.",
  "Mayday, mayday!": "Cấp cứu, cấp cứu!",
  "Actions like this improve your reputation.": "Những hành động như thế này sẽ cải thiện danh tiếng của cậu.",
  "This making you feel any better?": "Chuyện này có làm cậu cảm thấy khá hơn chút nào đéo?",
  "The Judge is going too far...Somebody oughta do something.": "Thẩm phán đang đi quá xa rồi... Ai đó phải làm điều gì đó đi chứ.",
  "You got some extra stash of ammo I don't know about?": "Cậu có kho đạn dự trữ bí mật nào mà tôi đéo biết đéo?",
  "Powerful spinning kick that knocks down a target.": "Cú đá xoay uy lực có khả năng đánh gục một mục tiêu.",
  "Oh. You know. Some stuff.": "Ồ. Cậu biết đấy. Vài thứ linh tinh.",
  "That's all the financial stuff, spreadsheets, account statements ... you don't need these lab reports, do you?": "Đó là tất cả những thứ liên quan đến tài chính, bảng tính, sao kê tài khoản... cậu đéo cần mấy bản báo cáo phòng thí nghiệm này, phải đéo?",
  "Stand in front of a broken gate and hold [xi_use] to repair it!": "Đứng trước một cánh cổng bị hỏng và giữ [xi_use] để sửa chữa nó!",
  "They've sent someone to talk it over.": "Họ đã cử người đến để thảo luận về việc này.",
  "Replaces the vehicle's tires.": "Thay lốp cho xe.",
  "How is this so hard? Get something sharp, and stick it in the bad thing. Let's see if you can do better next time.": "Tại sao việc này lại khó đến vậy? Lấy một thứ gì đó sắc nhọn, và đâm nó vào thứ tồi tệ kia. Để xem lần tới cậu có thể làm tốt hơn đéo nhé.",
  "You can say that again.": "Cậu nói đéo sai đâu.",
  "Mandy": "Mandy",
  "Sasquatch to boss. Are you coming along, or do I have to take care of this mission my own damn self?": "Sasquatch gọi sếp. Anh có đi cùng đéo, hay là tôi phải tự mình xử lý cái nhiệm vụ chết tiệt này đây?",
  "Could go at any time.": "Có thể xảy ra bất cứ lúc nào.",
  "Going up close and personal with these things is a recipe for disaster. We need more guns.": "Cận chiến mặt đối mặt với những thứ này là một công thức dẫn đến thảm họa đấy. Chúng ta cần thêm súng.",
  "Well, I'm not running a marathon any time soon.": "Chà, trong thời gian tới tôi sẽ đéo chạy marathon đâu.",
  "Donald": "Donald",
  "Don't worry, I'll be back out there as soon as I can. Fucking chest wounds aren't gonna slow me down.": "Đéo phải lo, tôi sẽ quay trở lại ngoài đó sớm nhất có thể. Ba cái vết thương chết tiệt ở ngực này đéo thể cản bước tôi được đâu.",
  "Aidan": "Aidan",
  "Eli knew it, too. It wasn't your fault.": "Eli cũng biết điều đó mà. Đó đéo phải lỗi của cậu.",
  "You just take your sweet time, and I'll poke around a bit.": "Cậu cứ từ từ mà làm, còn tôi sẽ đi dạo quanh đây một chút.",
  "Yeah, I'll take any help I can get.": "Ừ, tôi sẽ nhận bất kỳ sự giúp đỡ nào mà tôi có thể.",
  "The Ninja": "Nhẫn Giả (The Ninja)",
  "Here. Resupply.": "Đây. Tiếp tế (Resupply) đây.",
  "I'm not here to decide who's a waste of time. I'm here to get you out.": "Tôi đéo ở đây để phán xét ai là kẻ vô dụng lãng phí thời gian. Tôi ở đây để đưa cậu ra ngoài.",
  "Allows Workshop to be upgraded to Machine Shop.": "Cho phép Xưởng làm việc (Workshop) được nâng cấp thành Xưởng Cơ Khí (Machine Shop).",
  "I'm not going outside with all these zombies around.": "Tôi sẽ đéo ra ngoài với lũ zombies lảng vảng xung quanh đây đâu.",
  "It's time to clear this infestation out.": "Đến lúc dọn dẹp sạch ổ dịch (infestation) này rồi.",
  "The whole world's burning, and we're sitting here guarding the Valley That Modernization Forgot. Go Army.": "Cả thế giới đang bốc cháy, và chúng ta lại ngồi đây canh gác cái Thung lũng Bị Sự Hiện Đại Hóa Bỏ Quên này. Hoan hô Quân đội.",
  "We're not quite ready yet.": "Chúng ta vẫn chưa thực sự sẵn sàng đâu.",
  "Maybe, but as soon as I switch them on, those things are going to swarm.": "Có thể, nhưng ngay khi tôi bật chúng lên, những thứ đó sẽ kéo đến thành bầy.",
  "Reinforcements Found": "Đã Tìm Thấy Quân Viện Trợ (Reinforcements)",
  "Cleared that bunch out pretty good.": "Đã dọn dẹp sạch sẽ đám đó khá tốt rồi đấy.",
  "Jesus, what's the point any more? We're never gonna survive this.": "Chúa ơi, còn có ích lợi gì nữa chứ? Chúng ta sẽ đéo bao giờ sống sót qua nổi chuyện này đâu.",
  "Search and Rescue: Success": "Tìm Kiếm và Cứu Hộ (Search and Rescue): Thành Công",
  "So, what, we're on our own?": "Vậy là, sao cơ, chúng ta phải tự lo cho thân mình ư?",
  "Can you get around them?": "Cậu có thể đi vòng qua chúng đéo?",
  "Everything depends on the fundamentals. The right daily program for sleep, food, and exercise is what really defines a good soldier. (Fitness Expert)": "Mọi thứ đều phụ thuộc vào những điều cơ bản. Một chế độ sinh hoạt hợp lý về giấc ngủ, thức ăn và tập luyện là những gì thực sự định hình nên một người lính giỏi. (Chuyên Gia Thể Hình - Fitness Expert)",
  "Oh God... I don't believe it.": "Ôi Chúa ơi... Tôi đéo tin được chuyện này.",
  "If you're trying to cheer me up, this is a piss-poor job of it.": "Nếu cậu đang cố làm tôi vui lên, thì đây đúng là một nỗ lực thảm hại đấy.",
  "Just perfect.": "Thật hoàn hảo.",
  "Drinking Glasses": "Ly Uống Nước",
  "You wouldn't believe how fast rats get into things otherwise. We learned that one the hard way.": "Cậu sẽ đéo thể tin được bọn chuột có thể chui rúc vào đồ đạc nhanh đến mức nào đâu. Chúng tôi đã phải học bài học đó một cách đắt giá đấy.",
  "Jeff": "Jeff",
  "Do you got everything?": "Cậu đã lấy đủ mọi thứ chưa?",
  "You are not connected to Xbox Live. Your scores will not be recorded to the leaderboards while disconnected.": "Bạn đéo kết nối với Xbox Live. Điểm số của bạn sẽ đéo được ghi lại trên bảng xếp hạng (leaderboards) trong khi mất kết nối.",
  "You gonna make a big deal about that, or are we okay?": "Cậu định làm ầm lên chuyện đó, hay là chúng ta vẫn ổn?",
  "(at home)": "(tại căn cứ)",
  "COMPLETED: Melancholy": "ĐÃ HOÀN THÀNH: U Sầu (Melancholy)",
  "Hold up, let's take care of this first.": "Khoan đã, hãy giải quyết chuyện này trước đã.",
  "Amanda": "Amanda",
  "Gathered 11 Daily Rations of Food": "Đã Thu Thập Được 11 Khẩu Phần Thức Ăn Hàng Ngày",
  "What's your billet, soldier?": "Vị trí đóng quân của cậu ở đâu, binh nhì?",
  "Put this one in the win column.": "Ghi nhận cái này vào cột chiến thắng đi.",
  "Walk with me. I'll explain.": "Đi dạo với tôi nào. Tôi sẽ giải thích.",
  "Look for New Home Sites": "Tìm Kiếm Các Vị Trí Làm Căn Cứ Mới (New Home Sites)",
  "Refills some brass to generate several magazines' worth of .40-caliber ammunition.": "Nạp lại một ít vỏ đạn (brass) để tạo ra vài băng đạn cỡ .40.",
  "Bunks": "Giường Tầng (Bunks)",
  "SURVIVAL TACTICS: Personalities": "CHIẾN THUẬT SINH TỒN (SURVIVAL TACTICS): Tính Cách (Personalities)",
  "Billy Bob": "Billy Bob",
  "Chicken-fried steak?": "Bò bít tết chiên xù?",
  "If you're interested, there's a little recovery operation we could do.": "Nếu cậu có hứng thú, có một nhiệm vụ thu hồi (recovery operation) nho nhỏ mà chúng ta có thể làm.",
  "Son of a bitch... I knew I shouldn't have gone out there without somebody watching my back.": "Chết tiệt... Tôi biết là tôi đéo nên ra ngoài đó mà đéo có ai hỗ trợ yểm trợ phía sau mà.",
  "Cases of Medicine": "Những Thùng Thuốc Men (Medicine)",
  "Bunn": "Bunn",
  "Not as racist as he seems.": "Đéo phân biệt chủng tộc như vẻ bề ngoài của hắn đâu.",
  "Not so tough without your cronies, are you %2$s? - %1$s": "Đéo có lũ bạn bè của mình thì mày cũng đéo cứng cựa lắm đâu, phải đéo %2$s? - %1$s",
  "Was someone looking for a little survival training?": "Có ai đang tìm kiếm một khóa huấn luyện sinh tồn nho nhỏ đéo?",
  "Keller": "Keller",
  "Yeah, this should work.": "Ừ, cái này chắc chắn sẽ hiệu quả đấy.",
  "Area of effect items like petrol bombs are good when taking on groups.": "Các vật phẩm có sát thương diện rộng như bom xăng (petrol bombs) rất hữu ích khi đối đầu với đám đông.",
  "Lots of zombies right behind me.": "Có rất nhiều zombies ngay phía sau tôi đấy.",
  "xi_triggerr": "xi_triggerr",
  "Affirmative. En route now.": "Xác nhận. Đang trên đường tới.",
  "So, is there anything you want to tell me?": "Vậy, cậu có điều gì muốn nói với tôi đéo?",
  "We made rations for the road! All it took was some plastic bags and bits of random food.": "Chúng ta đã làm được những khẩu phần ăn đi đường rồi! Tất cả những gì cần thiết chỉ là vài chiếc túi nilon và một ít thức ăn linh tinh.",
  "MORALE MISSION": "NHIỆM VỤ TINH THẦN (MORALE MISSION)",
  "Dude, check it out! They've got a gun!": "Anh bạn, nhìn này! Chúng có một khẩu súng!",
  "You do indeed. I'll, uh, get the rest of this stuff stowed.": "Đúng vậy. Tôi sẽ, ừm, đem số đồ còn lại này đi cất.",
  "Aw shit, bulletproof zombies!": "Ôi chết tiệt, bọn zombies chống đạn kìa!",
  "We're here to protect you, Hadley. You don't need a weapon.": "Chúng tôi ở đây để bảo vệ cậu, Hadley. Cậu đéo cần đến vũ khí đâu.",
  "C'mon! Anybody hungry?": "Thôi nào! Có ai đói đéo?",
  "All right, made it to the top. Gonna take a look around.": "Được rồi, đã lên đến đỉnh. Sẽ quan sát xung quanh một chút.",
  "What's going on here?": "Chuyện gì đang xảy ra ở đây vậy?",
  "Sharpen your Wits by searching and scavenging.": "Trau dồi Trí Tuệ (Wits) của bạn bằng cách tìm kiếm và thu lượm đồ đạc (scavenging).",
  "Place Propane Tanks": "Đặt Bình Khí Propane",
  "You're in rough shape. Try some painkillers.": "Tình trạng của cậu khá tệ đấy. Hãy thử dùng chút thuốc giảm đau xem.",
  "Black Friday, are you picking this up?": "Black Friday, các anh có nghe thấy đéo?",
  "Ford": "Ford",
  "Let %1$s down.": "Làm %1$s thất vọng.",
  "We're not the only survivors around, you know. There's a few other groups scattered around the valley.": "Cậu biết đấy, chúng ta đéo phải là những người sống sót duy nhất ở quanh đây đâu. Còn có một vài nhóm khác rải rác khắp thung lũng này.",
  "Looks like it's harvest time again.": "Có vẻ như lại đến mùa thu hoạch rồi.",
  "Food Drop": "Đợt Thả Thức Ăn (Food Drop)"
};

const file = 'output/languages/chunks/btxt_chunk_169.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_169.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk169[r.sourceText]) {
    r.translatedText = chunk169[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 169 successfully!');
