const fs = require('fs');
const chunk131 = {
  "I think I managed to listen in on some pretty heavy-duty stuff. Want to hear?": "Tôi nghĩ tôi vừa nghe lén được một số chuyện khá là quan trọng đấy. Muốn nghe không?",
  "Earn and spend this every day. Use it or lose it.": "Kiếm và tiêu thứ này mỗi ngày. Không dùng thì mất.",
  "Medicine Cache": "Kho Chứa Thuốc Men",
  "Assault Rifle Specialization Improved!": "Chuyên Môn Súng Trường Tấn Công Đã Cải Thiện!",
  "%s < %d": "%s < %d",
  "Gotta be honest, I have no idea what to do now.": "Thành thật mà nói, tôi đéo biết phải làm gì bây giờ.",
  "He usually goes to ground here when things get bad. Maybe that's where he holed up.": "Ông ấy thường hay trốn ở đây khi mọi chuyện trở nên tồi tệ. Có lẽ đó là nơi ông ấy đang lẩn trốn.",
  "SKS Rifle and Folding Axe": "Súng trường SKS và Rìu Gập",
  "Mars": "Mars",
  "Food, Medicine, and Ammunition all play key survival roles.": "Thức Ăn, Thuốc Men, và Đạn Dược đều đóng vai trò then chốt cho sự sinh tồn.",
  "So I noticed you got a bit of a temper on you.": "Thế nên tôi mới nhận ra là cậu có chút nóng nảy đấy.",
  "Yo yo yo!": "Yo yo yo!",
  "Somebody put the antihistamines where the pseudoephedrine is supposed to go. Good thing I noticed, or I'd have killed myself trying to treat sniffles. We need a goddamn infirmary. - %1$s": "Ai đó đã đặt thuốc kháng histamine vào chỗ đáng lẽ phải để pseudoephedrine. May mà tôi để ý, nếu đéo thì tôi đã tự giết chết chính mình khi cố gắng điều trị chứng sụt sịt rồi. Chúng ta cần một cái bệnh xá chết tiệt. - %1$s",
  "Target acquired.": "Đã xác định mục tiêu.",
  "%s Supply Run: On The Move": "Đợt Tiếp Tế %s: Đang Di Chuyển",
  "Where is he? Quick!": "Cậu ta đâu rồi? Nhanh lên!",
  "Sachs": "Sachs",
  "Storage Room": "Phòng Kho",
  "No Commanding Officer": "Không Có Sĩ Quan Chỉ Huy",
  "You lousy artillery pukes better not miss!": "Mấy tên pháo binh khốn nạn các người tốt nhất là đừng có bắn trượt đấy!",
  "Ohhhhh, shiiiiiiiiit!": "Ohhhhh, chết tiệttttt!",
  "Taking this one on foot.": "Vụ này phải đi bộ rồi.",
  "Used to track characters that have become hurt in order to allow them to recover during gameplay": "Được sử dụng để theo dõi các nhân vật đã bị thương nhằm cho phép họ phục hồi trong quá trình chơi",
  "Store of Knowledge": "Kho Tàng Kiến Thức",
  "Back again, huh?": "Lại trở về rồi sao?",
  "Hey there, sports fan.": "Này, anh bạn người hâm mộ thể thao.",
  "What? How can you just ignore this?": "Cái gì? Làm sao anh có thể cứ thế phớt lờ chuyện này được chứ?",
  "Exactly. Grab a sword for yourself before we head back. I can give you some pointers.": "Chính xác. Hãy lấy cho mình một thanh kiếm trước khi chúng ta quay về. Tôi có thể chỉ cho cậu vài chiêu.",
  "Sports Trivia": "Kiến Thức Thể Thao",
  "This'll be a piece of cake.": "Chuyện này sẽ dễ như ăn bánh thôi.",
  "Hold [ul_aim] to aim your gun.": "Giữ [ul_aim] để ngắm bắn bằng súng của bạn.",
  "Yeah. I'm in.": "Phải. Tôi tham gia.",
  "START MISSION. Earn Trust and Influence.": "BẮT ĐẦU NHIỆM VỤ. Kiếm Niềm Tin (Trust) và Ảnh Hưởng (Influence).",
  "Hey, shut it. That's a Screamer.": "Này, im đi. Đó là một con Screamer.",
  "Collin": "Collin",
  "Dining Area": "Khu Vực Ăn Uống",
  "Nuclear strikes in Belarus and Ukraine confirmed. \r\nMoscow claims self-defense.": "Đã xác nhận các cuộc tấn công hạt nhân ở Belarus và Ukraine. \r\nMoscow tuyên bố đây là hành động tự vệ.",
  "Well, we've got to do something. We can't keep relying on Ray and his swap meets to keep us in food.": "Chà, chúng ta phải làm gì đó. Chúng ta đéo thể cứ mãi dựa vào Ray và những buổi trao đổi hàng hóa của gã để có cái ăn được.",
  "Desperate People": "Những Kẻ Tuyệt Vọng",
  "It's okay. I know you tried your best.": "Đéo sao đâu. Tôi biết cậu đã cố gắng hết sức rồi.",
  "Hey! How's it going?": "Này! Mọi chuyện thế nào rồi?",
  "Zeds dislike fire. This one comes fresh out of our workshop, so go us!": "Bọn zed đéo thích lửa đâu. Quả này mới ra lò từ xưởng của chúng ta đấy, tuyệt vời!",
  "Looks like you need a little something for the pain.": "Có vẻ như cậu cần một chút gì đó để giảm đau đấy.",
  "COMPLETED: Army Sighting": "HOÀN THÀNH: Nhìn Thấy Quân Đội",
  "Lost faith. Abandoned the community.": "Đã mất niềm tin. Rời bỏ cộng đồng.",
  "Madison Grant is on the way to the capital. So is Brock.": "Madison Grant đang trên đường đến thủ đô. Brock cũng vậy.",
  "Hope you're about done there, because it's about to get messy.": "Hy vọng cậu đã làm xong việc ở đó, vì mọi chuyện sắp trở nên lộn xộn rồi đấy.",
  "Quint": "Quint",
  "We can't stay here. Come on, let's grab what we can and get moving.": "Chúng ta đéo thể ở lại đây được. Nào, hãy nhặt những gì có thể và di chuyển thôi.",
  "Stay frosty.": "Hãy giữ cái đầu lạnh.",
  "I don't wanna die!": "Tôi đéo muốn chết!",
  "Fat lot of good that did anybody else.": "Điều đó thì đéo có lợi ích đéo gì cho bất kỳ ai khác cả.",
  "Steve": "Steve",
  "Lily's been going through her dad's things, and I think she's starting to realize just how much she's really lost. I know I can't bring him back, but ... maybe if she had something to remember him by?": "Lily đang xem lại những món đồ của bố cô ấy, và tôi nghĩ cô ấy đang bắt đầu nhận ra mình thực sự đã mất đi bao nhiêu. Tôi biết tôi đéo thể mang ông ấy trở lại, nhưng... có lẽ nếu cô ấy có thứ gì đó để tưởng nhớ về ông ấy thì sao?",
  "Schultz": "Schultz",
  "Assault Rifle: AKMS": "Súng trường tấn công: AKMS",
  "Thanks for the company. I'll make sure this gets to the right place.": "Cảm ơn vì đã đi cùng. Tôi sẽ đảm bảo thứ này được đưa đến đúng nơi.",
  "Juarez": "Juarez",
  "Myra": "Myra",
  "Melanie": "Melanie",
  "This is a total mess.": "Đây đúng là một mớ hỗn độn chết tiệt.",
  "So now everybody's pissin' themselves over one little feral? Fuck that shit.": "Vậy là bây giờ tất cả mọi người đều đái ra quần vì một con feral nhỏ bé sao? Địt mẹ cái đống rác rưởi đó.",
  "Might want to see what we can do to beef up our rep.": "Có lẽ chúng ta nên xem xét có thể làm gì để tăng cường danh tiếng của mình.",
  "This surgery facility allows us to immediately treat serious injuries while in the field.": "Cơ sở phẫu thuật này cho phép chúng ta điều trị ngay lập tức các vết thương nghiêm trọng khi đang ở ngoài chiến trường.",
  "I thought we were goners back there. I mean, I've seen some bad shit in my time, but that was... damn.": "Tôi tưởng chúng ta đã tiêu tùng ở đó rồi chứ. Ý tôi là, tôi đã từng chứng kiến nhiều chuyện tồi tệ trong đời, nhưng cái đó... mẹ kiếp.",
  "61 GENERIC Lance Sykes": "61 GENERIC Lance Sykes",
  "Can I just go on the record and say that that really sucked?": "Tôi có thể nói thẳng ra là chuyện đó thực sự rất tồi tệ đéo?",
  "Holy crap!": "Trời đất ơi!",
  "Piece together a few new MREs from general food supplies.": "Gom góp một vài suất MRE mới từ các nguồn cung cấp thức ăn chung.",
  "Family Business": "Chuyện Gia Đình",
  "The Kirkman Residence is a bit bigger than the church, and has a built-in workshop. - %1$s": "Khu dân cư Kirkman lớn hơn nhà thờ một chút, và có sẵn một xưởng chế tạo (workshop) bên trong. - %1$s",
  "I got a sample from his gut ... which is hard to do without piercing the outer flesh and making him go boom.": "Tôi đã lấy được một mẫu vật từ ruột của nó... điều đéo hề dễ dàng nếu không đâm thủng lớp da bên ngoài và khiến nó phát nổ.",
  "Might hold the key to curing the zombie plague.": "Có thể nắm giữ chìa khóa để chữa khỏi đại dịch zombie.",
  "Attempt to make contact with a new group of survivors": "Cố gắng liên lạc với một nhóm người sống sót mới",
  "This sixty year-old is nowhere near retirement.": "Ông lão 60 tuổi này vẫn chưa có ý định nghỉ hưu đâu.",
  "BOASTFUL people have their drawbacks.": "Những người KHOÁC LÁC (BOASTFUL) luôn có những nhược điểm của họ.",
  "%3$s seems to have gotten it together. -%1$s": "%3$s có vẻ như đã ổn định lại rồi. -%1$s",
  "But if we had reference material, we could do a whole lot more.": "Nhưng nếu chúng ta có tài liệu tham khảo, chúng ta có thể làm được nhiều hơn thế.",
  "Varney": "Varney",
  "Help. It's called… it's called help. I know you probably haven't heard of it, whatever. Just… oh God.": "Giúp đỡ. Nó được gọi là… nó được gọi là sự giúp đỡ. Tôi biết có lẽ cậu chưa từng nghe nói về nó, sao cũng được. Chỉ là… ôi Chúa ơi.",
  "Julie": "Julie",
  "You know expired meds are worse than nothing, right? Ugh, throw all these out! -%1$s": "Cậu có biết thuốc hết hạn còn tệ hơn là đéo có gì không? Ugh, vứt hết đống này đi! -%1$s",
  "Have you looked at the streets lately? It's like every day is Zombie Pride Day.": "Gần đây cậu có nhìn ra ngoài đường đéo? Cứ như thể ngày nào cũng là Ngày Hội Tự Hào Của Zombie vậy.",
  "Dammit! Back me up!": "Chết tiệt! Bọc hậu cho tôi!",
  "Door-to-fuckin'-door service.": "Dịch vụ giao hàng tận cửa con mẹ nó luôn.",
  "Asshole": "Thằng khốn",
  "All those zeds down and you're barely breathing hard!": "Ngần ấy bọn zed gục ngã mà cậu vẫn thở đéo dốc chút nào!",
  "Are you sure? I mean, the church has been home since this started. I hate to leave it.": "Cậu chắc chứ? Ý tôi là, nhà thờ đã là nhà kể từ khi chuyện này bắt đầu. Tôi rất ghét phải rời bỏ nó.",
  "Why haven't you kicked him out, then?": "Vậy tại sao các người chưa đuổi cổ anh ta đi?",
  "TIP: [ul_prev_consumable] or [ul_next_consumable] to select an item. Press [item] to use the selected item.": "MẸO: Sử dụng [ul_prev_consumable] hoặc [ul_next_consumable] để chọn một vật phẩm. Nhấn [item] để sử dụng vật phẩm đã chọn.",
  "Head to the Grange": "Đi đến Nông trang",
  "Community Morale is Very Low": "Tinh Thần Cộng Đồng Đang Rất Thấp",
  "Survivor": "Người Sống Sót",
  "The outbreak condition in Caracas has worsened to CRITICAL.\r\nNational Guard action in Plaza Venezuela resulted in massive military casualties.": "Tình trạng bùng phát dịch bệnh ở Caracas đã tồi tệ đến mức NGUY KỊCH.\r\nHành động của Vệ Binh Quốc Gia tại Quảng trường Venezuela đã dẫn đến thương vong quân sự khổng lồ.",
  "Hate those things.": "Ghét cay ghét đắng mấy thứ đó.",
  "Be sure you're using a bladed weapon. That is the only way to succeed at this hunt.": "Hãy chắc chắn rằng bạn đang sử dụng vũ khí có lưỡi. Đó là cách duy nhất để thành công trong cuộc săn lùng này.",
  "Huh. So that's what they mean by \"no such thing as an unloaded gun.\" Sorry %2$s. - %1$s": "Hừm. Vậy ra đó là ý của họ khi nói \"đéo có cái gọi là một khẩu súng chưa nạp đạn.\" Xin lỗi %2$s. - %1$s",
  "Help's on the way!": "Sự trợ giúp đang trên đường đến!",
  "You're a bunch of law-breaking delinquents, but you're tough. I might have a use for you. I'll be in touch. - %1$s": "Các người là một lũ tội phạm vi phạm pháp luật, nhưng các người rất cứng rắn. Có thể tôi sẽ cần dùng đến các người. Tôi sẽ liên lạc sau. - %1$s",
  "It's good to know folks here have got my back.": "Thật tốt khi biết mọi người ở đây sẽ luôn bảo vệ tôi."
};

const file = 'output/languages/chunks/btxt_chunk_131.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_131.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk131[r.sourceText]) {
    r.translatedText = chunk131[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 131 successfully!');
