const fs = require('fs');
const chunk194 = {
  "Hey... I'm young, quick, and I got a big-ass wrench. What could go wrong?": "Này... Tôi còn trẻ, cực kỳ nhanh nhẹn, và tôi đang có một cái cờ lê to tổ chảng ở đây. Còn có chuyện đéo gì có thể diễn ra tồi tệ được nữa cơ chứ?",
  "COMMUNITY: Chill Pill": "CỘNG ĐỒNG (COMMUNITY): Viên Thuốc Thư Giãn (Chill Pill)",
  "You're a big reason we're not dead already. Any chance of us joining your group full-time?": "Cậu chính là một lý do rất lớn khiến cho chúng tôi vẫn chưa chết. Liệu có cơ hội nào để cho chúng tôi có thể gia nhập vào nhóm của cậu một cách chính thức đéo?",
  "This is it.": "Chính là nó đây rồi.",
  "PERSONAL SKILL. I made you this friendship bracelet!": "KỸ NĂNG CÁ NHÂN (PERSONAL SKILL). Tớ đã làm tặng cho cậu chiếc vòng tay tình bạn này đấy!",
  "FOOD DELIVERED": "THỨC ĂN (FOOD) ĐÃ ĐƯỢC GIAO TỚI NƠI",
  "The pilot dropped off a stack of construction materials that he scavenged from HQ. Should help us hold out for a bit longer.": "Người phi công đó đã thả xuống một đống vật liệu xây dựng (construction materials) mà anh ta đã thu thập được từ Trụ sở chính (HQ). Chắc chắn nó sẽ giúp ích cho chúng ta có thể cầm cự được thêm một khoảng thời gian dài nữa.",
  "Here we are.": "Chúng ta đến nơi rồi.",
  "Be careful, all right?": "Hãy cẩn thận đấy, được đéo?",
  "Power's back!": "Nguồn điện (Power) đã được khôi phục trở lại!",
  "I'm outta gas!": "Tôi đã hết sạch nhiên liệu (gas) cmnr!",
  "I got these assholes!": "Tôi đã tóm được những tên khốn này cmnr!",
  "Drive Sam Home": "Lái Xe Đưa Sam Về Nhà",
  "Eldridge may have been rude, crude, and kind of a jerkface, but I'm still gonna miss him. G'bye, Sasquatch.": "Eldridge có thể là một kẻ thô lỗ, cục cằn, và hơi khốn nạn một chút, nhưng tôi vẫn sẽ nhớ tới anh ta. Tạm biệt nhé, Sasquatch.",
  "Jigsaw": "Chiếc Cưa Lọng Jigsaw",
  "I'm really starting to worry about %1$s. Nobody can get them to come out, or even talk to anybody. - %2$s": "Tôi thực sự đang bắt đầu cảm thấy lo lắng cho %1$s. Đéo một ai có thể thuyết phục được cậu ấy ra ngoài, hoặc thậm chí là nói chuyện với bất kỳ một ai cả. - %2$s",
  "That's a lot of money for a county commissioner.": "Đó quả thực là một số tiền rất lớn đối với một ủy viên hội đồng quận.",
  "Oh, shit.": "Oh, chết tiệt.",
  "Out of ammo, fuck!": "Hết đạn cmnr, đệch!",
  "KILLED: Dr. Timothy Hall": "ĐÃ BỊ GIẾT CHẾT (KILLED): Bác sĩ Timothy Hall",
  "You're really here? I was about to give up.": "Cậu thực sự đã đến đây ư? Tôi đã gần như sắp sửa từ bỏ cmnr.",
  "Owner of a funky art gallery just outside of town.": "Chủ sở hữu của một phòng trưng bày nghệ thuật sôi động nằm ở ngay khu vực ngoại ô của thị trấn.",
  "There's some trouble we might want to look into.": "Đang có một số rắc rối mà chúng ta có lẽ sẽ cần phải xem xét kỹ lưỡng đấy.",
  "%s Spotted!": "Đã Nhìn Thấy %s!",
  "So I'm guessing Eli's brothers didn't approve?": "Vậy tôi đoán là những người anh em của Eli đã đéo hề tán thành về chuyện này ư?",
  "Do you still have any samples?": "Cậu có còn giữ bất cứ một mẫu vật (samples) nào đéo?",
  "Aw Jesus, fat zombies are the worst.": "Aw Chúa ơi, bọn zombies béo ịch luôn là những thứ tồi tệ nhất.",
  "We've got a ton of notes over here, and no one who can use them.": "Chúng ta hiện đang có cả tấn những tờ giấy ghi chú ở đây, và đéo một ai trong chúng ta có thể sử dụng được chúng cả.",
  "MISSION: Quentin Barnes?": "NHIỆM VỤ (MISSION): Quentin Barnes?",
  "We've found some troops in need of assistance.": "Chúng tôi đã tìm thấy một số binh lính (troops) đang cần được hỗ trợ.",
  "The Vet Clinic": "Phòng Khám Thú Y (Vet Clinic)",
  "Allergies. Un-goddamn-believable.": "Dị ứng. Thật đéo thể nào tin nổi.",
  "Spent hours blowing into a brass instrument every day ... possibly at the expense of a social life. (Bonus Stamina)": "Dành hàng giờ đồng hồ mỗi ngày chỉ để thổi vào một loại nhạc cụ bằng đồng (brass instrument) ... có lẽ là đã phải đánh đổi bằng cả một cuộc sống giao tiếp xã hội bình thường. (Thưởng Thêm Điểm Thể Lực Stamina)",
  "Bishop": "Bishop",
  "You ready to see some serious shit?": "Cậu đã sẵn sàng để chứng kiến những thứ rắc rối thực sự nghiêm trọng đéo?",
  "TIP: Hold [sprint] to sprint.": "MẸO (TIP): Giữ [sprint] để tiến hành chạy nước rút (sprint).",
  "Importing Xbox 360 Save ...": "Đang tiến hành nhập tệp tin lưu trữ trò chơi Save trên Xbox 360 ...",
  "Rifle: 983 Squirrel": "Súng Trường (Rifle): 983 Squirrel",
  "How'd you get to be so cool?": "Làm thế đéo nào mà cậu lại có thể trở nên ngầu đến như vậy được nhỉ?",
  "Computer Skills": "Các Kỹ Năng Về Máy Tính (Computer Skills)",
  "You want me to sit around and rot like the rest of these pogues?": "Các người muốn tôi ngồi yên một chỗ và thối rữa từ từ giống hệt như những tên lính quèn chết tiệt ở đằng kia sao?",
  "How'd you find me?": "Làm thế đéo nào mà cậu có thể tìm thấy được tôi ở đây?",
  "Trait Discovered: Private Life": "Đã Khám Phá Ra Đặc Điểm (Trait): Cuộc Sống Riêng Tư Bí Mật (Private Life)",
  "We're having a bad season.": "Chúng ta đang trải qua một mùa vụ vô cùng tồi tệ.",
  "Creuzfeldt": "Creuzfeldt",
  "All right, survivors, we have our first caller!": "Được rồi, những người còn sống sót (survivors) thân mến, chúng ta đã có được một vị thính giả gọi điện đến đầu tiên rồi đây!",
  "Nah, that's it. Just wanted to get you out of your shell. Get some perspective, maybe.": "Đéo, chỉ có vậy thôi. Chỉ là tôi muốn giúp cậu chui ra khỏi cái vỏ bọc an toàn của chính mình. Có thể là cậu sẽ có được một cái nhìn đa chiều hơn về mọi chuyện.",
  "Church Kitchen": "Nhà Bếp Của Nhà Thờ (Church Kitchen)",
  "Car's dropped off for you.": "Chiếc xe ô tô đã được thả xuống cho cậu cmnr.",
  "That's a fucking juggernaut!": "Đó là một con quái vật juggernaut chết tiệt!",
  "Damn, I'm good.": "Chết tiệt thật, tôi giỏi vãi cả cứt.",
  "Delacruz": "Delacruz",
  "Probably not, no.": "Chắc là đéo đâu, đéo.",
  "Darryl": "Darryl",
  "Probably a couple screamers in there.": "Có lẽ là đang có một vài con screamers ở trong đó đấy.",
  "Maybe before you start yelling at somebody, you should think about how you need those folks to back you up next time the zeds roll around.": "Có lẽ trước khi cậu bắt đầu lớn tiếng quát tháo một ai đó, cậu nên suy nghĩ đến việc mình sẽ cần những con người đó hỗ trợ giúp đỡ cho mình như thế nào trong những lần đụng độ với lũ zeds tiếp theo.",
  "We're making a difference.": "Chúng ta đang tạo ra được sự khác biệt.",
  "Shit... I'm freaking out here!": "Chết tiệt thật... Tôi đang sợ vãi lồn ra đây!",
  "We have unconfirmed reports of a bloater not far from here.": "Chúng tôi hiện đang nhận được một số những báo cáo chưa được xác nhận về sự xuất hiện của một con bloater ở cách khu vực này không xa.",
  "Rosario": "Rosario",
  "Short pump, not legal. Don't try this at home.": "Súng pump action phiên bản nòng ngắn, đéo hề hợp pháp một chút nào cả. Đừng bao giờ cố gắng thử làm điều này ở nhà nhé.",
  "Is anybody out there? This is Becca at the grange--we're under attack!": "Có ai ở ngoài đó đéo? Đây là Becca hiện đang ở nông trang (grange)--chúng tôi đang bị tấn công!",
  "Roger that, Black Friday. Better than we hoped for.": "Đã rõ, thưa ngài Black Friday. Kết quả này còn tốt đẹp hơn rất nhiều so với những gì mà chúng tôi đã hy vọng.",
  "Survivor Activity Discovered!": "Vừa Mới Phát Hiện Ra Được Một Hoạt Động (Activity) Của Người Sống Sót!",
  "Safely in the air.": "Đang an toàn ở trên không trung.",
  "NEW ZOMBIE TYPE: Feral": "LOẠI ZOMBIE MỚI: Feral",
  "Oil": "Dầu Nhớt (Oil)",
  "Yeah. About a year ago, I go to take some trash out after the dinner shift, and there's this dog in the alley behind the restaurant, right?": "Yeah. Khoảng một năm trước, tôi đi đổ rác ở phía bên ngoài sau khi vừa mới kết thúc xong ca làm việc buổi tối, và có một con chó đi lạc ở trong một con hẻm nhỏ nằm ngay phía sau nhà hàng, đúng đéo?",
  "Reminds me of camping with my Uncle John as a kid.": "Thứ này làm tôi nhớ lại những chuyến đi cắm trại cùng với chú John khi tôi vẫn còn là một đứa trẻ.",
  "I'm out of here.": "Tôi sẽ rời khỏi nơi này.",
  "We're loaded up.": "Chúng ta đã chất đầy đồ lên xe rồi.",
  "Knight": "Knight",
  "Refuses": "Từ Chối (Refuses)",
  "Schuster": "Schuster",
  "Hit it, my position!": "Hãy bắn thẳng vào vị trí của tôi!",
  "Hurts like hell. Think I twisted my ankle or something.": "Đau vãi cả linh hồn. Tôi nghĩ là tôi đã bị bong gân mắt cá chân hoặc một cái đéo gì đó đại loại như vậy.",
  "Jose": "Jose",
  "It'll keep your shots from drawing every zombie in town.": "Nó sẽ giúp cho những phát súng (shots) của cậu đéo thu hút sự chú ý của mọi con zombie đang lảng vảng ở trong thị trấn.",
  "Patterson": "Patterson",
  "When you've unlocked a new Hero, look on your Map for a new Escort Mission to find that Hero.": "Khi bạn đã mở khóa được một Anh Hùng (Hero) mới, hãy xem trên Bản Đồ (Map) của mình để tìm kiếm một Nhiệm Vụ Hộ Tống (Escort Mission) mới giúp bạn có thể tìm thấy được vị Anh Hùng đó.",
  "Where the hell do these big bastards keep coming from?": "Mấy cái thằng khốn to xác này cứ liên tục chui ra từ cái xó xỉnh chết tiệt nào vậy hả?",
  "Be sure you're carrying a fire-based weapon. That is the only way to succeed at this hunt.": "Hãy chắc chắn rằng cậu đang mang theo một loại vũ khí có khả năng tạo ra lửa (fire-based). Đó là cách duy nhất để có thể thành công trong cuộc đi săn lần này.",
  "Cracked Pipe": "Ống Nước Bị Nứt Vỡ (Cracked Pipe)",
  "Mel": "Mel",
  "Here we go.": "Chúng ta đi thôi nào.",
  "Provides research options.": "Cung cấp cho bạn các tùy chọn nghiên cứu (research).",
  "This'll work.": "Thứ này chắc chắn sẽ hoạt động tốt đây.",
  "Yeah, and I'm sure Romulus' followers felt the same way, but we all know what happened to the Sabines.": "Yeah, và tôi chắc chắn rằng những kẻ đi theo phục tùng cho Romulus cũng đã có cảm giác giống hệt như vậy, nhưng tất cả chúng ta đều đã biết chính xác những gì đã xảy ra với tộc người Sabines rồi đấy.",
  "I owe you one. Let me know if you or your people need any Medical Advice. - Doc Hanson": "Tôi nợ cậu một mạng đấy nhé. Hãy cho tôi biết nếu như cậu hoặc người của cậu có cần đến bất kỳ một Lời Khuyên Y Tế (Medical Advice) nào đéo. - Doc Hanson",
  "Increased XP from shooting.": "Gia tăng thêm lượng điểm kinh nghiệm (XP) nhận được từ việc sử dụng súng (shooting).",
  "MISSION: Unwelcome Guest": "NHIỆM VỤ (MISSION): Những Vị Khách Đéo Mời Mà Tới (Unwelcome Guest)",
  "You keep shooting like that, there's gonna be a hundred zombies here.": "Nếu cậu cứ tiếp tục bắn súng như vậy, sẽ có hàng trăm con zombies kéo đến đây mất.",
  "The Captain": "Ngài Thuyền Trưởng (The Captain)",
  "Mickey": "Mickey",
  "Break its goddamn head!": "Hãy đập nát cái đầu chết tiệt của nó đi!",
  "TIP: Press [ul_journal_menu] to open your journal and view inventory, skills, and community info.": "MẸO (TIP): Nhấn [ul_journal_menu] để mở cuốn sổ nhật ký (journal) của bạn lên và tiến hành xem xét các thông tin về hành trang (inventory), kỹ năng (skills), cũng như là các thông tin về cộng đồng (community info).",
  "Ain't so bad working for the Wilkersons. Well, so long as you don't get on Mickey's bad side.": "Làm việc cho nhà Wilkersons cũng đéo đến nỗi quá tệ. Chà, miễn là cậu đừng chọc tức Mickey.",
  "So how about we check this place next?": "Vậy tiếp theo chúng ta sẽ đi kiểm tra cái địa điểm này thì sao nhỉ?",
  "Let's kill these fuckers.": "Hãy cùng nhau giết chết những tên khốn này đi.",
  "ATTITUDE: Moral Objections": "THÁI ĐỘ (ATTITUDE): Luôn Phản Đối Về Mặt Đạo Đức (Moral Objections)"
};

const file = 'output/languages/chunks/btxt_chunk_194.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_194.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk194[r.sourceText]) {
    r.translatedText = chunk194[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 194 successfully!');
