const fs = require('fs');
const chunk141 = {
  "Man, my life just flashed before my eyes. It was like a really boring art film. I need to get out more.": "Trời ạ, cuộc đời vừa lóe lên trước mắt tôi. Nó giống như một bộ phim nghệ thuật chán ngắt vậy. Tôi cần phải ra ngoài nhiều hơn mới được.",
  "You look like hell. Got any painkillers?": "Trông cậu tàn tạ vãi. Có thuốc giảm đau đéo?",
  "Who says there's no such thing as karma?": "Ai nói là đéo có nghiệp chướng (karma) chứ?",
  "We should set up some traps.": "Chúng ta nên cài vài cái bẫy.",
  "Medical Professional": "Chuyên Gia Y Tế",
  "Harvey": "Harvey",
  "Gunfire, explosions, firecrackers, and alarm clocks are just some of the ways to create a DISTRACTION.": "Tiếng súng, tiếng nổ, pháo thăng thiên và đồng hồ báo thức chỉ là một vài trong số các cách để tạo ra SỰ ĐÁNH LẠC HƯỚNG (DISTRACTION).",
  "When we picked him up, he was hunting a Screamer in there. But Screamers are everywhere.": "Lúc chúng tôi đón anh ấy, anh ấy đang săn một con Screamer ở trong đó. Nhưng Screamers thì ở khắp mọi nơi.",
  "I hope it's not my fault....": "Tôi hy vọng đó đéo phải là lỗi của tôi....",
  "Black Friday, aerial recon confirms those drop coordinates from Cleo. If you're short on supplies, you should head on out there. Highroad out.": "Black Friday, trinh sát trên không xác nhận tọa độ thả dù từ Cleo. Nếu các anh đang thiếu nhu yếu phẩm, các anh nên tiến ra đó. Highroad hết.",
  "Watch out for the big one!": "Coi chừng con bự chảng đó!",
  "I'll just stay out of your way and let you work.": "Tôi sẽ tránh đường và để cậu làm việc.",
  "HOME: Epidemic Contained": "CĂN CỨ: Dịch Bệnh Đã Được Kiểm Soát",
  "Helps keep our people healthy.": "Giúp giữ cho mọi người của chúng ta khỏe mạnh.",
  "Naw, this place is a disaster waitin' to happen.": "Đéo, nơi này là một thảm họa đang chờ chực xảy ra đấy.",
  "Time to Leave": "Đến Lúc Rời Đi",
  "Attach": "Lắp đặt",
  "Fatalities Averted": "Ngăn Chặn Được Tử Vong",
  "Worked with Major Hawkes for the past five years, and has been her most trusted colleague and advisor. Has three daughters back in Hawaii.": "Đã làm việc cùng Thiếu tá Hawkes trong năm năm qua, và là đồng nghiệp kiêm cố vấn đáng tin cậy nhất của cô ấy. Có ba cô con gái ở quê nhà Hawaii.",
  "So, anybody fuckin' stuff up at home?": "Vậy, có ai làm hỏng chuyện gì chết tiệt ở nhà đéo?",
  "MISSION: Army Sighting": "NHIỆM VỤ: Phát Hiện Quân Đội",
  "More mouths to feed? Sure, whatever.": "Thêm miệng ăn á? Chắc rồi, sao cũng được.",
  "Take a walk with me, will you? Let me see if I can't explain how things are.": "Đi dạo với tôi một lát nhé? Để tôi xem liệu mình có thể giải thích tình hình mọi thứ được đéo.",
  "One more soldier now has the thousand-yard stare of a veteran. A veteran of latrine-cleaning duty.": "Lại thêm một người lính giờ đây có ánh nhìn xa xăm của một cựu binh. Một cựu binh của nhiệm vụ cọ rửa nhà xí.",
  "Munitions Shop": "Xưởng Đạn Dược (Munitions Shop)",
  "Set Traps for Passing Hordes": "Cài Bẫy Cho Các Bầy Đàn Đi Ngang Qua",
  "Goin' out there, bringin' stuff back...makes me wanna work even harder.": "Ra ngoài đó, mang đồ về... làm tôi muốn làm việc chăm chỉ hơn nữa.",
  "Check the right!": "Kiểm tra cánh phải!",
  "A revolver with a long history of police use.": "Một khẩu súng lục ổ xoay với lịch sử sử dụng lâu đời trong lực lượng cảnh sát.",
  "What do you think is going to happen to me? Am I getting arrested?": "Cậu nghĩ chuyện gì sẽ xảy ra với tôi? Tôi có bị bắt đéo?",
  "I say we head to a neutral location. We'll do the exchange there.": "Tôi nói là chúng ta nên đến một địa điểm trung lập. Chúng ta sẽ thực hiện trao đổi ở đó.",
  "Cpl": "Hạ sĩ (Cpl)",
  "Doesn't put up with wasted time. Anyone who isn't pulling their weight is bringing everyone else down.": "Đéo chịu đựng việc lãng phí thời gian. Bất cứ ai đéo hoàn thành trách nhiệm của mình đều đang kéo tất cả những người khác xuống.",
  "That should do it.": "Như thế là ổn rồi.",
  "Vercesi": "Vercesi",
  "Hope you enjoy the ride.": "Hy vọng cậu tận hưởng chuyến đi.",
  "All clear.": "Trắng màn rồi (All clear).",
  "No sweat. I'll help run interference while your people work.": "Đéo vấn đề gì. Tôi sẽ giúp đánh lạc hướng trong lúc người của cậu làm việc.",
  "I like you! You can come over to my house and fuck my sister!": "Tao thích mày! Mày có thể đến nhà tao và chơi em gái tao!",
  "Sorry to hear that. I wish I could do more, but I've just about burned through all my medical stocks. Everybody's got this thing, seems like.": "Rất tiếc khi nghe điều đó. Tôi ước mình có thể làm được nhiều hơn, nhưng tôi gần như đã đốt sạch kho dự trữ y tế của mình rồi. Có vẻ như ai cũng bị dính cái bệnh này.",
  "Oh yeah!": "Ồ de!",
  "Survivors at the Church": "Những Người Sống Sót Ở Nhà Thờ",
  "Outpost - PMC Snipers": "Tiền Đồn - Lính Bắn Tỉa PMC",
  "Unresolved issues.": "Những vấn đề chưa được giải quyết.",
  "I'm not saying anyone's a thief, but some things have walked off.": "Tôi đéo nói ai là kẻ trộm, nhưng một số thứ đã đéo cánh mà bay.",
  "Lori": "Lori",
  "I'm confused.": "Tôi đang thấy bối rối.",
  "Hey, I'm a college student!": "Này, tôi là một sinh viên đại học đấy!",
  "Headhunter": "Thợ Săn Đầu Người (Headhunter)",
  "Book on Firearm Maintenance": "Sách Hướng Dẫn Bảo Dưỡng Súng Cầm Tay",
  "PERSONAL SKILL. Yeah, yeah, I've heard all the jokes about sadistic gym teachers and sleazy personal trainers. See if you're laughing when I leave you in the dust with the dead.": "KỸ NĂNG CÁ NHÂN. Phải, phải, tôi đã nghe đủ các trò đùa về mấy ông thầy thể dục tàn bạo và mấy gã huấn luyện viên cá nhân lươn lẹo rồi. Xem cậu có còn cười nổi đéo khi tôi bỏ cậu lại hít bụi cùng bọn người chết nhé.",
  "Appreciate it. Wasn't sure I'd make it home otherwise.": "Rất cảm kích. Đéo chắc là tôi có thể về nhà an toàn nếu đéo có chuyện đó.",
  "Too many fucking newbies around here. Gotta get us a training facility.": "Có quá nhiều lính mới chết tiệt quanh đây. Phải kiếm cho chúng ta một cơ sở huấn luyện (training facility) thôi.",
  "Well, we can't have that now, can we? We got to get you back to your people.": "Chà, chúng ta đéo thể để chuyện đó xảy ra bây giờ được, đúng đéo? Chúng tôi phải đưa cậu trở về với người của mình.",
  "Hey, I need some help. Come with me, okay?": "Này, tôi cần giúp đỡ. Đi cùng tôi, được đéo?",
  "Nah, that's it. You just seemed like you needed to get out of your shell a little bit. Get some perspective, maybe.": "Đéo, thế thôi. Cậu chỉ có vẻ như cần thoát ra khỏi cái vỏ ốc của mình một chút. Biết đâu lại có cái nhìn khác về mọi thứ.",
  "SWEET RIDE": "CHIẾC XE NGỌT NGÀO",
  "Hunt down an Armored zombie.": "Săn lùng một con zombie mặc giáp (Armored).",
  "My fever's spiking. I can't do anything right now.": "Cơn sốt của tôi đang tăng vọt. Tôi đéo thể làm bất cứ việc gì ngay lúc này.",
  "Repair all": "Sửa chữa tất cả",
  "Alexander": "Alexander",
  "You won't be sorry.": "Cậu sẽ đéo phải hối tiếc đâu.",
  "Just about there.": "Sắp đến nơi rồi.",
  "Shit. You think we'll make a run on one of those construction sites soon?": "Chết tiệt. Cậu nghĩ chúng ta sẽ sớm thực hiện một chuyến càng quét vào một trong những công trường xây dựng đó đéo?",
  "Smoker": "Người Hút Thuốc",
  "More freaking patrols, man... bullshit.": "Lại thêm mấy cuộc tuần tra chó đẻ, bạn ạ... nhảm nhí thật.",
  "<Disgusted sigh> This is sooo lame…": "<Thở dài ngao ngán> Thật là quá nhảm nhí…",
  "COMBAT TRAINING": "HUẤN LUYỆN CHIẾN ĐẤU",
  "I guess I understand.": "Tôi đoán là mình hiểu.",
  "Escort a refugee back to base.": "Hộ tống một người tị nạn về căn cứ.",
  "Garden": "Khu Vườn",
  "HOME: Morale Qualms": "CĂN CỨ: Lo Lắng Về Tinh Thần",
  "Make Whistling Box Mine": "Chế Tạo Mìn Hộp Có Tiếng Hú (Whistling Box Mine)",
  "Gotcha!": "Bắt được mày rồi!",
  "Don't take this the wrong way, but it's a really interesting problem to solve, if you think about it. (Handy with tools.)": "Đừng hiểu lầm nhé, nhưng đó thực sự là một vấn đề thú vị để giải quyết đấy, nếu cậu nghĩ về nó. (Khéo tay với các công cụ.)",
  "What?! Are you literally insane?": "Cái gì?! Cậu thực sự điên rồi sao?",
  "Choice is final for each character. Hold [ui_x] to choose.": "Lựa chọn này là cuối cùng cho mỗi nhân vật. Giữ phím [ui_x] để chọn.",
  "Sorry, dudes. Didn't mean to eat all that grub, I just found the last stash of Acapulco Gold maybe in the world, and I figured \"hey, it'd suck to die with this righteous bud unsmoked,\" and, well, you can kinda see what happened from there. - %1$s": "Xin lỗi các anh bạn. Tôi đéo cố ý ăn sạch đống thức ăn đó đâu, chỉ là tôi vừa tìm thấy có lẽ là lô cần sa Acapulco Gold cuối cùng trên thế giới, và tôi tự nhủ \"này, sẽ thật tồi tệ nếu chết mà đéo hút nốt chỗ hàng cực phẩm này\", và, ừ thì, các cậu có thể hình dung ra chuyện gì đã xảy ra sau đó rồi đấy. - %1$s",
  "Good thing my tape recorder was running. You're gonna want to hear this.": "May mà máy ghi âm của tôi đang chạy. Ngài sẽ muốn nghe đoạn này đấy.",
  "Fitzwallace": "Fitzwallace",
  "Delay. Sgt. Tan will wait for you.": "Trì hoãn. Trung sĩ Tan sẽ đợi cậu.",
  "Made for Police to use the same .40 cal round as a sidearm.": "Được chế tạo để Cảnh sát sử dụng cùng loại đạn .40 cal như một vũ khí phụ (sidearm).",
  "That's our load blown. You folks take care, now.": "Bọn tôi thả hết hàng rồi. Mọi người bảo trọng nhé.",
  "We got zeds on our six.": "Chúng ta có zed bám theo đuôi kìa (on our six).",
  "Anyway, she asks me to bring her some of \"the product.\" So I have to drive instead.": "Dù sao thì, cô ấy bảo tôi mang cho cô ấy một ít \"hàng\". Vì vậy tôi phải lái xe thay.",
  "With food supplies scarce, everyone's on edge, but %1$s and %2$s really crossed the line. -%3$s": "Với nguồn cung cấp thức ăn khan hiếm, mọi người đều đang căng thẳng, nhưng %1$s và %2$s thực sự đã đi quá giới hạn. -%3$s",
  "You can choose one of two utility skills.": "Bạn có thể chọn một trong hai kỹ năng tiện ích (utility skills).",
  "I think we oughta search that place.": "Tôi nghĩ chúng ta nên lục soát nơi đó.",
  "Flirt": "Tán tỉnh",
  "Feels good to be building something, even if it's mostly scrap lumber and sheet metal. Gotta start somewhere.": "Cảm giác thật tốt khi xây dựng một thứ gì đó, ngay cả khi nó chủ yếu là gỗ vụn và các tấm kim loại. Phải bắt đầu từ đâu đó chứ.",
  "Jung": "Jung",
  "Nobody is ranked on this leaderboard.": "Đéo có ai được xếp hạng trên bảng xếp hạng này.",
  "Yeah, assuming they haven't switched to a steady diet of long pork, too.": "Phải, giả sử họ cũng đéo chuyển sang chế độ ăn thịt đồng loại (long pork) đều đặn nữa.",
  "101 HERO Sam Hoffman": "101 HERO Sam Hoffman",
  "Doghouse": "Doghouse",
  "Makayla": "Makayla",
  "One sec.": "Đợi một giây.",
  "I already took my fair share.": "Tôi đã lấy phần chia công bằng của mình rồi.",
  "Right.": "Đúng thế.",
  "We should load up quickly.": "Chúng ta nên chất đồ lên xe thật nhanh."
};

const file = 'output/languages/chunks/btxt_chunk_141.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_141.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk141[r.sourceText]) {
    r.translatedText = chunk141[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 141 successfully!');
