const fs = require('fs');
const chunk121 = {
  "Resolution 1440x900": "Độ phân giải 1440x900",
  "SET UP: Supply Room": "THIẾT LẬP: Phòng Tiếp Tế (Supply Room)",
  "RESCUED: Dr. Timothy Hall": "ĐÃ GIẢI CỨU: Tiến sĩ Timothy Hall",
  "Will you use your head for once in your fool life?": "Ông có chịu dùng cái đầu của mình một lần trong cái cuộc đời ngu ngốc này không?",
  "LMG: M1918A2": "Súng máy hạng nhẹ: M1918A2",
  "Paid a debt for a perfect stranger.": "Đã trả nợ cho một người hoàn toàn xa lạ.",
  "Must be nice to be a squirrel.": "Làm một con sóc chắc tuyệt lắm nhỉ.",
  "\"Mercy\" killing.": "Cái chết \"Nhân đạo\".",
  "FREAK HUNT: Bloater": "SĂN QUÁI THAI: Bloater",
  "Yeah I wouldn't say faith is my strong suit.": "Phải, tôi sẽ không nói niềm tin là điểm mạnh của mình đâu.",
  "Pvt": "Binh nhì (Pvt)",
  "It's been a pleasure doing business.": "Rất hân hạnh được hợp tác làm ăn.",
  "Folks are probably worried about me. Let's go.": "Mọi người chắc đang lo cho tôi lắm. Chúng ta đi thôi.",
  "Jenna": "Jenna",
  "Looks like trouble headed our way.": "Có vẻ như rắc rối đang hướng về phía chúng ta.",
  "Yo, that's my dawg right there, son!": "Yo, đó là chiến hữu của tao đấy, nhóc!",
  "Shit, I gotta get outta here!": "Chết tiệt, mình phải thoát khỏi đây!",
  "Army Medic": "Quân Y (Army Medic)",
  "Executed 50 Stealth Kills at Breakdown Level 5 or Higher.": "Thực hiện 50 Pha Ám Sát Lén Lút (Stealth Kills) ở Cấp độ Breakdown 5 trở lên.",
  "His dad pressured him into joining the military, hoping it would toughen him up.": "Bố anh ấy đã ép anh gia nhập quân đội, với hy vọng nó sẽ giúp anh trở nên cứng rắn hơn.",
  "This isn't how we make friends.": "Đây không phải là cách chúng ta kết bạn.",
  "ITEMS UNLOCKED": "ĐÃ MỞ KHÓA VẬT PHẨM",
  "You know who I am, right? I should be supervising you!": "Các người biết tôi là ai chứ? Đáng ra tôi phải là người giám sát các người mới phải!",
  "Coming up the road now! Better get ready!": "Đang đi lên đường lớn kìa! Tốt nhất là nên chuẩn bị sẵn sàng đi!",
  "Can't wait till this shit gets better. I'm going stir crazy on nothing but rest.": "Đéo thể đợi đến khi cái tình cảnh chết tiệt này khá hơn được. Tôi phát điên vì chẳng làm gì ngoài việc nghỉ ngơi rồi.",
  "What is your decision?": "Quyết định của cậu là gì?",
  "Myles": "Myles",
  "Clearing infestations is rough work. Just ask %1$s. - %2$s": "Dọn dẹp các ổ dịch (infestations) là một công việc khó nhằn. Cứ hỏi %1$s mà xem. - %2$s",
  "Leaderboards are not available while not connected to Xbox Live.": "Bảng xếp hạng không khả dụng khi chưa kết nối với Xbox Live.",
  "Destroy 5 Juggernauts (Breakdown Level 5 or Higher).": "Tiêu diệt 5 con Juggernaut (Cấp độ Breakdown 5 trở lên).",
  "Let's do some business.": "Cùng hợp tác làm ăn nào.",
  "Destroyed 5 Juggernauts at Breakdown Level 5 or Higher.": "Đã tiêu diệt 5 con Juggernaut ở Cấp độ Breakdown 5 trở lên.",
  "The \"Trench Gun\" or M97. Still fires, but showing some wear.": "Khẩu \"Trench Gun\" hay M97. Vẫn bắn được, nhưng đã có dấu hiệu hao mòn.",
  "The outbreak condition in Kansas City has worsened to CRITICAL. \r\nRiverfront Park refugee camp is overrun.": "Tình trạng bùng phát dịch bệnh ở Kansas City đã trở nên NGUY KỊCH. \r\nTrại tị nạn Riverfront Park đã thất thủ.",
  "What are you doing here? I thought the city was abandoned.": "Các người đang làm gì ở đây? Tôi tưởng thành phố đã bị bỏ hoang rồi chứ.",
  "%d added to Supply Locker. (Good fuel supply.)": "%d đã được thêm vào Tủ Đồ. (Nguồn cung cấp nhiên liệu tốt.)",
  "Wes": "Wes",
  "Retooled from 10mm to .45 cal. Scope included.": "Được cải tiến từ đạn 10mm sang cỡ nòng .45. Có kèm ống ngắm.",
  "Look, I don't know what you're asking for, but if you want my advice... some things ought to stay in the past. Anybody deserves a clean slate, it's that girl.": "Nghe này, tôi không biết ông đang yêu cầu điều gì, nhưng nếu ông muốn lời khuyên của tôi... một số chuyện nên để lại trong quá khứ đi. Nếu có ai đó xứng đáng được làm lại từ đầu, thì chính là cô gái đó.",
  "You can choose one of two defensive skills.": "Bạn có thể chọn một trong hai kỹ năng phòng thủ.",
  "+20": "+20",
  "No, no, no no no no.... it can't be gone! I left it right here! Agh, where is it!": "Không, không, không không không không.... nó không thể biến mất được! Tôi đã để nó ngay đây mà! Agh, nó đâu rồi!",
  "Safe? No, but I can fix that.": "An toàn à? Không, nhưng tôi có thể sửa lại chuyện đó.",
  "About as big-hearted and generous as they come. If it were up to him, he'd hand out all his food to anybody who needed it; that's just what people do in a crisis, right?": "Thuộc dạng người có tấm lòng nhân hậu và hào phóng nhất mà cậu từng gặp. Nếu là ông ấy, ông ấy sẽ phân phát toàn bộ thức ăn của mình cho bất cứ ai cần; đó là điều mà con người nên làm trong một cuộc khủng hoảng, phải không?",
  "Talk to Alan?": "Nói chuyện với Alan?",
  "That should protect us for a little while at least.": "Ít nhất thì thứ đó sẽ bảo vệ chúng ta được một thời gian.",
  "Screw that, they need my help!": "Mặc kệ đi, họ cần tôi giúp!",
  "Kills": "Số mạng tiêu diệt (Kills)",
  "Negative, Black Friday. That place was getting hairy last time I took off.": "Không được, Black Friday. Lần trước tôi cất cánh, khu vực đó đang trở nên cực kỳ hỗn loạn.",
  "Created some .50 BMG ammunition.": "Đã tạo ra vài viên đạn .50 BMG.",
  "We could use your advice on some construction.": "Chúng tôi rất cần lời khuyên của cậu về việc xây dựng.",
  "No.": "Không.",
  "Sounds like a real old time country doctor.": "Nghe đúng chuẩn một bác sĩ nông thôn thời xưa.",
  "They're coming up behind us.": "Chúng đang tiến đến sau lưng chúng ta.",
  "I know it sounds crazy. But after leaving us to the horde, and getting a ton of people killed, I think they may have actually saved somebody.": "Tôi biết nghe có vẻ điên rồ. Nhưng sau khi bỏ mặc chúng ta cho lũ horde, và khiến cả đống người phải chết, tôi nghĩ thực ra họ đã cứu được vài người đấy.",
  "97 GENERIC Sam Haney": "97 GENERIC Sam Haney",
  "Keep moving. They're behind us.": "Tiếp tục di chuyển. Chúng ở ngay phía sau chúng ta kìa.",
  "DISTANT GUNSHOTS": "TIẾNG SÚNG VỌNG LẠI TỪ XA",
  "Hot Meal": "Bữa Ăn Nóng Hỏi",
  "Crap.": "Chết tiệt.",
  "Faafao": "Faafao",
  "Tomba": "Tomba",
  "You wouldn't be looking for a hired gun by any chance, would you?": "Tình cờ là cậu không có đang tìm kiếm một tay súng đánh thuê, đúng không?",
  "Virginia Dalhgren": "Virginia Dalhgren",
  "Research Potent Homemade Stims": "Nghiên Cứu Các Loại Thuốc Kích Thích Tự Chế Mạnh",
  "So are you leaning yes or no?": "Vậy cậu nghiêng về hướng đồng ý hay từ chối?",
  "New Facility! Use your Ops Center to assign specific Tactics to inactive soldiers.": "Cơ Sở Mới! Sử dụng Trung Tâm Điều Hành (Ops Center) của bạn để chỉ định các Chiến Thuật (Tactics) cụ thể cho những người lính đang không làm nhiệm vụ.",
  "Lot of zed activity over here.": "Có rất nhiều dấu vết hoạt động của lũ zed ở quanh đây.",
  "Stash %d": "Kho đồ ẩn giấu %d",
  "Seems like we're done for now.": "Có vẻ như chúng ta đã xong việc tạm thời rồi.",
  "Swear to God! Kept trying to eat me, but that big stupid foam dog head kept getting in its way.": "Thề có Chúa! Nó cứ cố ăn thịt tôi, nhưng cái đầu chó bằng xốp ngu ngốc to đùng đó cứ vướng víu vào nó.",
  "Target Snap Distance Increased!": "Khoảng Cách Khóa Mục Tiêu (Snap Distance) Đã Tăng Lên!",
  "Got tired of wading in other people's shit.": "Đã quá mệt mỏi với việc phải lội trong đống phân của người khác rồi.",
  "See if you can make contact.": "Thử xem cậu có thể liên lạc được không.",
  "Green items active during Driving.": "Các vật phẩm màu xanh lá sẽ kích hoạt khi đang Lái Xe (Driving).",
  "THE OLD FARMHOUSE": "NGÔI NHÀ TRANG TRẠI CŨ",
  "He always had a good head on his shoulders. If he was in trouble, he would've tried to get inside, and fortify someplace till we came looking.": "Anh ấy luôn là một người sáng suốt. Nếu gặp rắc rối, anh ấy sẽ cố tìm cách trốn vào trong, và gia cố phòng thủ ở một nơi nào đó cho đến khi chúng ta đến tìm.",
  "While this order is active, soldiers will hunt zombies around the perimeter to keep the Threat Level low, and make attacks less frequent.": "Khi mệnh lệnh này được kích hoạt, những người lính sẽ đi săn lũ zombie xung quanh vành đai để giữ Mức Độ Mối Đe Dọa (Threat Level) ở mức thấp, đồng thời giảm thiểu tần suất các cuộc tấn công.",
  "Good think Pastor Will played the electric guitar at Sunday School.": "Thật tốt khi Mục sư Will đã chơi guitar điện ở Trường Chúa Nhật.",
  "Tiara": "Tiara",
  "Janiyah": "Janiyah",
  "Dan Bogatz is on the way to the capital with his daughter Shira.": "Dan Bogatz đang trên đường tới thủ đô cùng với cô con gái Shira của ông.",
  "We'll discuss this later, Sheriff. We have a visitor.": "Chúng ta sẽ bàn chuyện này sau, Cảnh sát trưởng. Chúng ta có khách.",
  "SET UP: Landing Zone": "THIẾT LẬP: Điểm Đáp (Landing Zone)",
  "Let's go for a walk.": "Đi dạo chút thôi.",
  "Civilian version of the M4.": "Phiên bản dân sự của khẩu M4.",
  "16 MIL Sgt Joe Mueller": "16 MIL Trung sĩ Joe Mueller",
  "Toss this to target an area for mortar.": "Ném vật này để đánh dấu tọa độ cho pháo kích.",
  "Can you please show these fuckups how to build something?": "Cậu làm ơn chỉ cho mấy con lợn vô dụng này cách xây dựng thứ gì đó được không?",
  "No no, thank you. I don't get many opportunities to practice my sermons any more.": "Không không, cảm ơn ông. Giờ tôi chẳng còn nhiều cơ hội để thực hành các bài thuyết giáo của mình nữa đâu.",
  "A small-town hero and people pleaser. Missed out on a football scholarship at his favorite college ... so the Army is his safety school.": "Một anh hùng thị trấn nhỏ và là người luôn muốn làm vui lòng mọi người. Đã bỏ lỡ một suất học bổng bóng bầu dục tại trường đại học yêu thích... thế nên Quân đội là lối thoát an toàn của anh ấy.",
  "Fast, deadly, and nearly immune to gunfire.": "Nhanh nhẹn, chết chóc, và gần như miễn nhiễm với súng đạn.",
  "64 GENERIC Harrison Biggs": "64 GENERIC Harrison Biggs",
  "[message looping tone] One one lima november nine nine india six one tango.": "[tiếng bíp vòng lặp tin nhắn] Một một lima november chín chín india sáu một tango.",
  "Box Mine": "Mìn Hộp",
  "What's the situation?": "Tình hình thế nào rồi?",
  "Irma": "Irma",
  "Cadimo": "Cadimo",
  "Dammit dammit dammit!": "Chết tiệt chết tiệt mẹ kiếp!",
  "Still supporting Judge Lawton.": "Vẫn đang ủng hộ Thẩm phán Lawton."
};

const file = 'output/languages/chunks/btxt_chunk_121.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_121.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk121[r.sourceText]) {
    r.translatedText = chunk121[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 121 successfully!');
