const fs = require('fs');
const chunk176 = {
  "+33%": "+33%",
  "Yeah, but it's right in the middle of Marshall. Plenty of supply options. Plus it looks like we could build on the roof if we had to.": "Ừ, nhưng nó lại nằm ngay ở giữa trung tâm thị trấn Marshall. Có rất nhiều nguồn cung cấp nhu yếu phẩm. Thêm vào đó, có vẻ như chúng ta có thể xây dựng trên mái nhà nếu bắt buộc phải làm vậy.",
  "Holy shit man! Holy shit!": "Vãi cứt thật anh bạn! Vãi cả cứt!",
  "Fixes leaks, or creates them!": "Sửa chữa chỗ rò rỉ, hoặc tạo ra chúng!",
  "Political Activist": "Nhà Hoạt Động Chính Trị (Political Activist)",
  "Headshots still work, but it may take more than one.": "Những phát bắn vào đầu (Headshots) vẫn có tác dụng, nhưng có thể sẽ cần nhiều hơn một phát đạn.",
  "We got %3$s out of there. Could have gone a lot worse. -%1$s": "Chúng ta đã đưa được %3$s ra khỏi đó an toàn. Mọi chuyện đã có thể tồi tệ hơn rất nhiều. -%1$s",
  "Probably not. We better fix that problem.": "Có lẽ là đéo. Tốt hơn hết là chúng ta nên giải quyết dứt điểm vấn đề đó đi.",
  "That ain't gonna work.": "Cách đó đéo có tác dụng đâu.",
  "Emote 3": "Biểu Cảm 3 (Emote 3)",
  "Killed a zombie horde": "Đã tiêu diệt một bầy (horde) zombie",
  "Yeah, we can do some trading if you want.": "Ừ, chúng ta có thể thực hiện vài giao dịch trao đổi nếu cậu muốn.",
  "EXPIRED: Exterminate a Juggernaut": "ĐÃ HẾT HẠN: Tiêu Diệt Một Con Juggernaut",
  "How about you stay down here and I'll head up top?": "Thế cậu ở lại dưới này còn tôi sẽ đi lên trên đó thì sao?",
  "Big Meal": "Bữa Ăn Lớn (Big Meal)",
  "Merc Melee": "Vũ Khí Cận Chiến Của Lính Đánh Thuê (Merc Melee)",
  "Feel like making a delivery? I've got some stuff I could give you in exchange. You'll like it.": "Có muốn thực hiện một chuyến giao hàng đéo? Tôi có một vài thứ có thể đưa cho cậu để trao đổi. Cậu sẽ thích nó đấy.",
  "Time's up. We need to get moving.": "Hết thời gian rồi. Chúng ta cần phải di chuyển thôi.",
  "Great for fast getaways, transporting a lotta salvage, and running over zombies a whole horde at a time... few things are more valuable than a motor vehicle.": "Tuyệt vời cho những pha tẩu thoát nhanh chóng, vận chuyển được rất nhiều vật tư thu thập (salvage), và có thể cán nát cả một bầy zombie cùng lúc... có rất ít thứ giá trị hơn là một chiếc xe cơ giới (motor vehicle).",
  "Gimme your best shot.": "Hãy cho tôi xem cú ra đòn tốt nhất của cậu đi.",
  "Get over there and secure that extraction point. We're not going to be rescuing anybody if we can't even land a damn helo. Doghouse out.": "Hãy đến đó và bảo vệ an toàn cho điểm sơ tán (extraction point) đó. Chúng ta sẽ đéo thể giải cứu bất kỳ ai nếu chúng ta thậm chí còn đéo thể hạ cánh một chiếc trực thăng chết tiệt xuống được. Doghouse hết (out).",
  "Asset Name Goes Here": "Tên Tài Sản (Asset) Được Điền Ở Đây",
  "Shooting Practice": "Luyện Tập Bắn Súng (Shooting Practice)",
  "Generator": "Máy Phát Điện (Generator)",
  "%s is set.": "%s đã được thiết lập xong.",
  "A bunkhouse for laborers.": "Một khu nhà tập thể (bunkhouse) dành cho những người lao động.",
  "Yeah, just gimme a minute.": "Ừ, cho tôi một phút.",
  "Bad news. We let our crops sit too long, and now everything's rotted on the vine.": "Tin xấu đây. Chúng ta đã để cây trồng quá lâu, và bây giờ mọi thứ đều đã thối rữa hết trên cành rồi.",
  "Folding Hatchet": "Rìu Gấp (Folding Hatchet)",
  "The brass have given %1$s more operational discretion.": "Cấp trên (brass) đã trao cho %1$s nhiều quyền tự quyết hơn trong chiến dịch (operational discretion).",
  "None, sir. Black Friday out.": "Đéo có ai cả, thưa ngài. Black Friday hết (out).",
  "Trained as a tank mechanic in the Reserves; now runs a small auto repair business just outside Danforth.": "Được huấn luyện làm thợ sửa xe tăng trong Lực Lượng Dự Bị; hiện tại đang điều hành một tiệm sửa xe ô tô nhỏ ngay ngoại ô Danforth.",
  "Next up's the kitchen. Sam's our unofficial in-house chef, but... well, there's only so much anybody can do with canned soup and pork rinds.": "Tiếp theo là nhà bếp. Sam là đầu bếp nội bộ đéo chính thức của chúng ta, nhưng... chà, ai cũng chỉ có thể làm được ngần ấy thứ với món súp đóng hộp và tóp mỡ lợn (pork rinds) mà thôi.",
  "No, no no no no, here's good, here's safe, out there's bad!": "Không, đéo đéo đéo đéo, ở đây rất tốt, ở đây an toàn, ngoài kia rất tồi tệ!",
  "We failed to bring Dr. Horn back to base in one piece. I can't overstate how critical that man was to our survival. If the brass doesn't find us a backup plan ... we're fucked.": "Chúng ta đã thất bại trong việc đưa Bác sĩ Horn trở về căn cứ nguyên vẹn. Tôi đéo thể nói hết được tầm quan trọng sống còn của người đàn ông đó đối với sự sống sót của chúng ta. Nếu cấp trên (brass) đéo tìm cho chúng ta một kế hoạch dự phòng nào khác... chúng ta tiêu cmnr.",
  "Everybody'd love to have Doc as a full-time resident, but he's refused all of us.": "Tất cả mọi người đều muốn Doc trở thành một cư dân chính thức toàn thời gian, nhưng ông ấy đã từ chối tất cả chúng tôi.",
  "I think he grew up somewhere around here, he might be holed up in one of those buildings.": "Tôi nghĩ anh ta đã lớn lên ở quanh khu vực này, anh ta có thể đang trốn chui trốn nhủi trong một trong những tòa nhà đó.",
  "Dropped out of college after missing a bunch of exams for a MOBA tournament.": "Đã bỏ học đại học sau khi bỏ lỡ một loạt các bài kiểm tra chỉ vì tham gia một giải đấu MOBA.",
  "A British Army mainstay for most of the last century.": "Một trụ cột của Quân Đội Anh trong phần lớn thế kỷ trước.",
  "I'm continuing to hear stories of flu outbreaks. We'd better stock up on medicine. -%1$s.": "Tôi liên tục nghe được những câu chuyện về các đợt bùng phát dịch cúm (flu outbreaks). Tốt hơn hết là chúng ta nên dự trữ thêm thuốc men. -%1$s.",
  "Looks like before the main force pulled out, a bunch of soldiers got sick. Sounds like the same thing Alan and Pastor Will had.": "Có vẻ như trước khi lực lượng chủ lực rút đi, một nhóm binh lính đã bị ốm. Nghe có vẻ giống hệt căn bệnh mà Alan và Mục sư Will mắc phải.",
  "REFUSE SURVIVORS. Let them know they're on their own.": "TỪ CHỐI (REFUSE) NHỮNG NGƯỜI SỐNG SÓT. Hãy cho họ biết rằng họ phải tự mình lo liệu thôi.",
  "Well, let's start looking.": "Chà, hãy bắt đầu tìm kiếm thôi.",
  "Goddamn, that's a lot of them.": "Mẹ kiếp, chúng đông đéo tả nổi.",
  "Well, good luck. Hope you find him.": "Chà, chúc may mắn nhé. Hy vọng cậu sẽ tìm thấy anh ta.",
  "Hankins": "Hankins",
  "Probably a good thing I didn't bring Ed then.": "Vậy thì có lẽ việc tôi đéo mang theo Ed đi cùng là một quyết định đúng đắn đấy.",
  "Restores classic cars.": "Chuyên gia phục chế những chiếc xe ô tô cổ điển.",
  "Then you'd best watch the Wilkersons. I trust them about as far as a two-headed snake.": "Vậy thì tốt nhất là cậu nên để mắt đến nhà Wilkersons. Sự tin tưởng của tôi dành cho họ cũng ngang bằng với một con rắn hai đầu mà thôi.",
  "ASSET PROFILE: Hadley Westen": "HỒ SƠ TÀI SẢN (ASSET PROFILE): Hadley Westen",
  "Coronado": "Coronado",
  "<0.01 lbs": "<0.01 lbs",
  "Um ... I'm not sure that I--": "Ờm ... Tôi đéo chắc là tôi--",
  "Watch yourself - there's a feral out there.": "Hãy cẩn thận đấy - có một con Feral đang lảng vảng ở ngoài đó.",
  "Okay, moving too fast.": "Được rồi, di chuyển quá nhanh rồi.",
  "Asia": "Asia",
  "Reply All": "Trả Lời Tất Cả (Reply All)",
  "We'd need enough people to defend the walls.": "Chúng ta sẽ cần đủ người để có thể bảo vệ được các bức tường rào chắn.",
  "Maya": "Maya",
  "Hang on, I'm coming!": "Cố bám trụ nhé, tôi đến đây!",
  "You don't stop talking shit behind my back, %2$s, and I will cut you like a prison bitch. Sweet dreams, motherfucker. - %1$s": "Nếu mày đéo ngừng nói những lời chó má sau lưng tao đi, %2$s, thì tao sẽ rạch mặt mày như một con chó cái trong tù đấy. Chúc ngủ ngon, thằng khốn nạn. - %1$s",
  "Buy Breakdown": "Mua Bản Mở Rộng Breakdown",
  "I came face to face with a screamer today and nearly shit myself. -%1$s.": "Hôm nay tôi đã đụng độ trực diện với một con screamer và suýt nữa thì vãi cả ra quần. -%1$s.",
  "Did you see me out there today?": "Hôm nay cậu có nhìn thấy tôi biểu diễn ngoài đó đéo?",
  "TIP: Press [sprint] + [xi_use] to shove an enemy away.": "MẸO (TIP): Nhấn [sprint] + [xi_use] để xô ngã hất văng (shove) một kẻ thù ra xa.",
  "Stop running around like an idiot! Hold still and aim!": "Đừng có chạy lăng xăng xung quanh như một thằng ngu nữa! Đứng yên và ngắm bắn (aim) đi!",
  "Julene Horn is on the way to the capital with her husband's notes.": "Julene Horn đang trên đường đến thủ đô cùng với những cuốn sổ ghi chép (notes) của chồng cô ấy.",
  "We've received a small delivery of supplies.": "Chúng ta đã nhận được một đợt giao hàng nhỏ chứa một ít nhu yếu phẩm (supplies).",
  "TIP: Press [crouch] to turn your flashlight on or off.": "MẸO (TIP): Nhấn [crouch] để bật hoặc tắt đèn pin (flashlight) của cậu.",
  "A. D. Young": "A. D. Young",
  "Dammit!": "Mẹ kiếp!",
  "PERSONAL SKILL. American, British, Mexican, Korean--I don't care, I watch them all.": "KỸ NĂNG CÁ NHÂN (PERSONAL SKILL). Mỹ, Anh, Mexico, Hàn Quốc--tôi đéo quan tâm, tôi xem tất.",
  "We could have used your help, though.": "Mặc dù vậy, chúng tôi đã có thể cần đến sự giúp đỡ của cậu đấy.",
  "We're on our way.": "Chúng tôi đang trên đường đến đây.",
  "Charlie": "Charlie",
  "Please tell me that's a sack full of building materials. We're down to our last nails.": "Làm ơn hãy nói với tôi rằng đó là một bao tải chứa đầy vật liệu xây dựng (building materials) đi. Chúng ta đã cạn kiệt đến những chiếc đinh cuối cùng rồi.",
  "Um ... not in a while.": "Ờm ... cũng đã một khoảng thời gian rồi đéo thấy.",
  "Start gathering your things. I'll watch your back.": "Bắt đầu thu dọn đồ đạc của cậu đi. Tôi sẽ yểm trợ phía sau cho cậu.",
  "So yeah. I'm not gonna pry. But if you do ever want to talk about it....": "Thế đấy. Tôi sẽ đéo soi mói tọc mạch đâu. Nhưng nếu có bao giờ cậu muốn nói về chuyện đó....",
  "Hey, you weren't listening when I called you all grunts and killers, right?": "Này, lúc nãy cậu đéo nghe thấy tôi gọi tất cả các người là những tên lính quèn (grunts) và những kẻ giết người đấy chứ, phải đéo?",
  "Don't worry about it. I'll be patched up soon enough.": "Đừng bận tâm về chuyện đó. Tôi sẽ sớm được băng bó chữa trị ổn thỏa thôi.",
  "Better wrap this up fast.": "Tốt hơn hết là nên giải quyết dứt điểm nhanh gọn chuyện này đi.",
  "Requires Fighting Level 3": "Yêu cầu Kỹ Năng Chiến Đấu (Fighting) Cấp Độ 3",
  "You got zeds on your tail!": "Có bọn zeds đang bám theo đuôi cậu kìa!",
  "Go to hell.": "Xuống địa ngục cmn đi.",
  "I left my father with those monsters. I just ran as far and as fast as I could, and I tried to tell myself he wasn't really my dad any more, that everything that made him him was long gone.": "Tôi đã bỏ lại cha mình cùng với những con quái vật đó. Tôi chỉ biết cắm đầu chạy càng xa và càng nhanh càng tốt, và tôi đã cố tự nhủ với bản thân rằng ông ấy đéo còn thực sự là cha tôi nữa, rằng mọi thứ từng làm nên con người ông đã biến mất từ lâu rồi.",
  "Eating together can help reduce discord in the community and maintain cleanliness.": "Việc ăn uống cùng nhau có thể giúp làm giảm sự bất hòa (discord) trong cộng đồng và duy trì vệ sinh sạch sẽ.",
  "MISSION: Accusations": "NHIỆM VỤ: Những Lời Buộc Tội (Accusations)",
  "Break In": "Đột Nhập (Break In)",
  "Been better.": "Từng có lúc tốt hơn thế này.",
  "Situation seems normal--so, y'know, we're only kinda totally screwed.": "Tình hình có vẻ như vẫn bình thường--vì vậy, cậu biết đấy, chúng ta chỉ đang ở trong tình thế hoàn toàn bế tắc khốn nạn mà thôi.",
  "He still owns all the comics your mom threw out.": "Cậu ta vẫn còn giữ tất cả những cuốn truyện tranh mà mẹ cậu đã vứt đi đấy.",
  "Splints": "Thanh Nẹp Xương (Splints)",
  "-%d Seconds": "-%d Giây (Seconds)",
  "[exhausted from combat] I need a rest!": "[kiệt sức vì chiến đấu] Tôi cần phải nghỉ ngơi!",
  "Enthusiasm": "Sự Nhiệt Tình (Enthusiasm)",
  "Huh... which one...?": "Hả... con nào cơ...?",
  "Ammunition Refill Station": "Trạm Tiếp Tế Đạn Dược (Ammunition Refill Station)",
  "Not like we're going anywhere till we do.": "Giống như thể chúng ta sẽ đéo đi đến đâu cả cho đến khi chúng ta làm được điều đó vậy.",
  "38 MIL Wo Philip Tulafoni": "38 QUÂN ĐỘI (MIL) Wo Philip Tulafoni"
};

const file = 'output/languages/chunks/btxt_chunk_176.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_176.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk176[r.sourceText]) {
    r.translatedText = chunk176[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 176 successfully!');
