const fs = require('fs');
const chunk210 = {
  "Michele Martin seems to believe that she should be prosecuted for ... something. Perhaps she is one of the few people whose lives will benefit from the fall of civilization. We have better things to do than to go after people like her.": "Michele Martin dường như (seems) vẫn luôn luôn tin tưởng (believe) rằng bản thân cô ấy thực sự rất đáng bị pháp luật trừng phạt truy tố (prosecuted) vì một cái tội lỗi tồi tệ ... nào đó (something). Có lẽ (Perhaps) cô ấy chính là một (one) trong số những người vô cùng hiếm hoi (few) mà phần cuộc sống (lives) tẻ nhạt của họ sẽ nhận được nhiều sự giải thoát lợi ích (benefit) nhất từ sự kiện sụp đổ của nền văn minh nhân loại (fall of civilization). Chúng ta hiện tại còn có rất nhiều những việc cực kỳ quan trọng (better things) cần phải thực hiện (do) thay vì phải liên tục rượt đuổi đi theo sau bảo vệ (go after) cho một người (people) có tính cách kỳ quặc như (like) cô ấy.",
  "Quit dancin' and start fightin'!": "Hãy mau lập tức từ bỏ (Quit) ngay cái việc đi nhảy múa lượn lờ (dancin') chết tiệt đó đi và bắt đầu (start) lao vào chiến đấu thực sự (fightin') đi nào!",
  "DISCOVERED: Confident Survivors": "ĐÃ PHÁT HIỆN RA (DISCOVERED): Một Nhóm Người Sống Sót (Survivors) Trông Có Vẻ Vô Cùng Tự Tin Và Lạc Quan (Confident)",
  "Screw that, they need help!": "Mặc xác (Screw) chuyện đó đi, hiện tại thì bọn họ đang vô cùng cần (need) có người đến để hỗ trợ giúp đỡ (help)!",
  "Okay. Looks like there were no zombies around.": "Được rồi (Okay). Trông có vẻ như (Looks like) là hoàn toàn đéo hề có (were no) sự xuất hiện của bất kỳ một con zombies tởm lợm đéo nào ở quanh khu vực này (around) cả.",
  "Duane": "Duane",
  "Molly angels forty, ten mikes.": "Molly đang tiếp cận đến điểm đánh dấu forty (angels forty), chỉ còn cách đích khoảng chừng mười phút di chuyển nữa thôi (ten mikes).",
  "151 HERO Maj Alicia Hawkes": "151 VỊ ANH HÙNG (HERO) Thiếu Tá (Maj) Alicia Hawkes",
  "Stay back! I'm smashing heads in here!": "Hãy mau lùi lại tránh xa ra (Stay back)! Hiện tại thì tao đang đập nát (smashing) vụn một vài cái đầu (heads) ở ngay trong này (here) đấy!",
  "Lawal": "Lawal",
  "You are DROWNING. Get out of the water.": "Bạn hiện ĐANG BỊ ĐUỐI NƯỚC (DROWNING). Hãy mau chóng tìm cách bơi vào bờ và leo lên ngay khỏi (Get out) khu vực mặt nước (water) đi.",
  "Best zombie kills": "Màn trình diễn chém giết tàn sát (kills) bọn zombie vô cùng tuyệt vời đỉnh cao nhất (Best)",
  "Garlic": "Củ Tỏi (Garlic)",
  "DISCOVERED: Uncertain Survivors": "ĐÃ PHÁT HIỆN RA (DISCOVERED): Một Nhóm Người Sống Sót (Survivors) Trông Có Vẻ Cực Kỳ Lo Lắng Hoang Mang Đéo Biết Phải Làm Gì Cả (Uncertain)",
  "You know, I always really appreciate these little talks we have.": "Cậu biết đấy (You know), tôi luôn luôn (always) thực sự (really) vô cùng đánh giá cao và cực kỳ trân trọng (appreciate) những cái buổi trò chuyện tâm sự (talks) tuy vô cùng ngắn ngủi (little) nhỏ bé này nhưng lại cực kỳ quý giá mà chúng ta đã cùng nhau trải qua (have).",
  "Creates a few homemade Mild Stims.": "Có Thể Tự Mình Chế Tạo Sản Xuất (Creates) ra được một vài (few) loại Thuốc Trị Thương Phục Hồi Thể Lực Giảm Đau Nhẹ (Mild Stims) thủ công (homemade).",
  "Hell, anything that gives us a fighting chance out there.": "Chết tiệt thật (Hell), chỉ cần là bất cứ một cái thứ vũ khí nào (anything) mà có thể cung cấp mang lại (gives) cho chúng ta thêm được một cái cơ hội (chance) cực kỳ mỏng manh dùng để chống trả chiến đấu lại (fighting) cái lũ quái vật tởm lợm ở bên ngoài đó (out there) thì cũng đã là quá đủ rồi.",
  "Combat!": "Chiến đấu (Combat) nào!",
  "She did. And I should have. We've seen guys skulking around casing the joint before. Must have been waiting for the right time.": "Cô ấy thực sự đã làm (did) như vậy đấy. Và đáng lẽ ra tôi cũng nên (should) phải hành động quyết liệt (have) như thế. Trước đây (before), chúng ta đã từng nhìn thấy (seen) vô số những gã khốn kiếp (guys) có những hành vi vô cùng mờ ám cứ liên tục lén lút rình rập đi dạo lượn lờ xung quanh (skulking around) để quan sát do thám theo dõi (casing) cái khu vực căn cứ tồi tàn (joint) này. Bọn chúng chắc hẳn (Must have been) là hiện vẫn đang tiếp tục kiên nhẫn chờ đợi (waiting) cho đến đúng lúc thời cơ (right time) thực sự chín muồi để ra tay hành động.",
  "Trade 1 Case of Ammunition for 5 Cases of Medicine.": "Dùng 1 Thùng Hàng Cung Cấp Đạn Dược (Case of Ammunition) để tiến hành Trao Đổi Giao Dịch (Trade) Đổi Lấy 5 Thùng Hàng Cung Cấp Thuốc Men Y Tế (Cases of Medicine).",
  "Dammit. The caller isn't here. They're probably one of the bodies on the ground.": "Mẹ kiếp (Dammit). Cái người đã phát ra lời kêu gọi cầu cứu (caller) hiện đéo có mặt (isn't) ở đây (here). Rất có thể (probably) bọn họ chính là một (one) trong số những cái xác chết vô hồn (bodies) đang nằm rải rác la liệt ở ngay trên mặt đất (ground) này cũng nên.",
  "SWAT Officer": "Sĩ Quan Đặc Nhiệm Cảnh Sát Vũ Trang (SWAT Officer)",
  "Escort needed.": "Hiện Đang Vô Cùng Cần Phải (needed) Có Người Hộ Tống Đi Theo Trợ Giúp Bảo Vệ (Escort).",
  "Hey, do you need any help?": "Này, cậu có thực sự cần (need) bất cứ (any) một sự hỗ trợ giúp đỡ (help) đéo nào hay đéo?",
  "Yeah, I can tell you're impressed.": "Yeah, tôi hoàn toàn có thể tự đưa ra lời khẳng định (tell) đanh thép được rằng hiện tại cậu đang cảm thấy vô cùng ngưỡng mộ và vô cùng ấn tượng (impressed) với toàn bộ những gì mà tôi đã làm được đấy.",
  "Nikola": "Nikola",
  "-60% Max Vitality": "Bị Trừ Giảm Ngay Trực Tiếp -60% Vào Chỉ Số Sinh Lực Thể Lực Tối Đa (Max Vitality)",
  "Sweep": "Quét Trụ",
  "Have you thought about us joining up with you?": "Liệu (Have) cậu đã từng bao giờ suy nghĩ (thought) một cách cực kỳ nghiêm túc về cái việc cho phép chúng tôi (us) được quyền sáp nhập gia nhập tham gia (joining up) vào chung phe với (with) các cậu hay chưa?",
  "Not yet. Hold on to that trigger. I'll let you know.": "Vẫn chưa (Not yet) đâu. Hãy cứ giữ chặt (Hold on) ngón tay của cậu ở ngay trên cái bộ phận cò súng (trigger) đó đi. Tôi chắc chắn sẽ lên tiếng thông báo phát tín hiệu (let) cho cậu biết (know) ngay khi nào mà cậu cần phải siết cò hành động.",
  "This is straight from the Commander in Chief.": "Toàn bộ những cái lời mệnh lệnh chết tiệt này (This) đều được đưa ra và truyền đạt một cách vô cùng trực tiếp (straight) từ phía Tổng Tư Lệnh Vị Chỉ Huy Trưởng Lãnh Đạo Tối Cao Nhất (Commander in Chief) đấy.",
  "Keep it up.": "Hãy cứ tiếp tục duy trì và cố gắng phát huy (Keep it up) thật tốt đi nhé.",
  "You ought to pop some painkillers.": "Cậu đáng lẽ ra (ought to) đã nên phải nuốt trọn (pop) một vài viên thuốc giảm đau (painkillers) khốn khiếp vào mồm ngay rồi đấy.",
  "Payne": "Payne",
  "The CO needs a designated space for research and planning.": "Vị Sĩ Quan Chỉ Huy (CO) hiện đang rất cần (needs) phải có một khu vực không gian khoảng trống (space) đã được lựa chọn thiết kế dành riêng (designated) cho các mục đích nhằm phục vụ cho việc nghiên cứu (research) tìm tòi và đồng thời lên những kế hoạch chiến lược tác chiến cụ thể (planning).",
  "Quentin! Oh, thank God!": "Quentin! Oh, tạ ơn lạy chúa (thank God)!",
  "Player Inventory": "Túi Đồ Trang Bị Hòm Đồ Hành Trang Lưu Trữ Vật Phẩm (Inventory) Cá Nhân Của Người Chơi (Player)",
  "Supply Drop": "Đợt Thả (Drop) Hàng Hóa Tiếp Tế Nguồn Cung Ứng Vật Tư (Supply) Chết Tiệt Xuống Khu Vực Mặt Đất Bằng Đường Hàng Không",
  "Sorry to waste your time. I'm not going back.": "Thực sự vô cùng xin lỗi (Sorry) vì đã làm lãng phí (waste) rất nhiều thời gian (time) quý báu của cậu nhé. Nhưng mà tôi chắc chắn sẽ đéo bao giờ chịu quay trở về cái nơi tồi tệ đó (going back) đéo đâu.",
  "79 GENERIC Jack Trant": "79 CHUNG (GENERIC) Jack Trant",
  "Didn't make a dent.": "Hoàn toàn đéo thể nào (Didn't) tạo ra được (make) bất cứ một sự tác động ảnh hưởng vết trầy xước sứt mẻ (dent) đéo nào cả.",
  "Yeah! Kicked their sorry asses!": "Yeah! Cuối cùng thì cũng đã thành công đập nát tươm sút tung (Kicked) được cái lũ chó đẻ khốn nạn (sorry asses) đó đi rồi!",
  "Get 'er done!": "Hãy mau nhanh chóng hoàn thành (done) dứt điểm trọn vẹn toàn bộ công việc tồi tệ này ('er) đi nào!",
  "Unlock Full Game": "Tiến Hành Mở Khóa (Unlock) Trọn Vẹn Toàn Bộ Nội Dung Đầy Đủ Của Trò Chơi (Full Game)",
  "Speakers - Dolby 7.1": "Dàn Loa (Speakers) Hệ Thống Âm Thanh Đa Chiều Vòm - Dolby 7.1",
  "Another drop secure. Nice work.": "Thêm (Another) một kiện hàng viện trợ (drop) chết tiệt nữa hiện đã được thu hồi bảo vệ an toàn (secure) thành công. Một công việc hoàn thành rất xuất sắc tuyệt vời (Nice work) đấy.",
  "107 HERO Walter Degrasse": "107 VỊ ANH HÙNG (HERO) Walter Degrasse",
  "Upgrade to Sat-Comms": "Tiến Hành Nâng Cấp Tái Thiết Lại (Upgrade) Lên Thành Trạm Thu Phát Tín Hiệu Liên Lạc Qua Vệ Tinh (Sat-Comms)",
  "If you can find one, you're more than welcome.": "Nếu như cậu thực sự có khả năng (can) tìm thấy (find) được một người (one) phù hợp đéo nào đó, thì cậu sẽ luôn luôn được bọn tôi nhiệt tình vui vẻ chào đón (welcome) nồng nhiệt hơn bao giờ hết (more than).",
  "Come on. You and me are going to go out there and kick some ass. You'll feel better.": "Thôi nào (Come on). Cậu và tôi cả hai chúng ta (You and me) chắc chắn sẽ (going to) cùng nhau tiến ra bên ngoài đó (go out there) và sẽ đập nát tươm sút tung (kick) đít một vài cái con chó đẻ khốn nạn (ass) chết tiệt đó đi. Chắc chắn là cậu sẽ (You'll) mau chóng cảm thấy (feel) nhẹ nhõm tốt hơn (better) rất nhiều mà thôi.",
  "Grew up on a cattle ranch. Spent an entire summer literally shoveling shit. First in the family to attend college.": "Đã từng có một quãng thời gian sinh sống và lớn lên (Grew up) ở bên trong một khu vực trang trại (ranch) chăn nuôi gia súc (cattle). Đã phải tiêu tốn (Spent) trọn vẹn toàn bộ cả một kỳ nghỉ hè (entire summer) chết tiệt chỉ để đi làm cái công việc hót dọn (shoveling) phân cứt đái tồi tệ (shit) theo đúng nghĩa đen (literally). Là một người cực kỳ xuất sắc vô cùng tài giỏi được coi là cá nhân đầu tiên (First) ở trong dòng họ gia đình (family) đã vô cùng xuất sắc đạt đủ điều kiện để có thể theo học (attend) tại một ngôi trường cao đẳng đại học (college) danh tiếng đéo nào đó.",
  "Fashion Forward": "Người Đi Tiên Phong (Forward) Khởi Xướng Cho Các Trào Lưu Xu Hướng Gu Thẩm Mỹ Thời Trang (Fashion)",
  "All right. We'll get everything organized here and then we'll head your way.": "Được rồi (All right). Chúng tôi chắc chắn sẽ nhanh chóng tiến hành dọn dẹp sắp xếp ngăn nắp tổ chức (organized) lại toàn bộ tất cả mọi thứ (everything) ở tại cái khu vực này (here) ổn thỏa và rồi sau đó (then) chúng tôi sẽ ngay lập tức di chuyển (head) thẳng về phía bên cậu (your way).",
  "Not Alone": "Hoàn Toàn Đéo Hề Phải Chịu Cảnh Bị Bỏ Rơi Lại Cô Đơn Trơ Trọi Một Thân Một Mình (Not Alone)",
  "Oh, military-grade explosives. Is there any problem you can't solve?": "Oh, toàn là các loại thuốc nổ hỏa tiễn đạn pháo bom mìn (explosives) đạt tiêu chuẩn chất lượng cấp độ dành riêng cho quân đội (military-grade) đéo. Rốt cuộc thì liệu (Is there) còn có bất kỳ (any) một cái vấn đề rắc rối (problem) tồi tệ đéo nào mà cậu đéo thể nào (can't) có thể giải quyết xử lý được (solve) đéo?",
  "You're building the ultimate tree fort, aren't you?": "Có phải (aren't you) hiện tại cậu đang cố gắng chế tạo ra (building) một cái pháo đài (fort) ở trên ngọn cây (tree) ở mức độ tối thượng và đỉnh cao (ultimate) nhất, đúng đéo?",
  "From Russia with...great regard.": "Gửi đến từ (From) nước Nga (Russia) cùng với... rất nhiều những lời chúc những sự kính trọng yêu quý tốt đẹp nhất (great regard).",
  "I think I'm okay right now.": "Tôi nghĩ (think) rằng hiện tại (right now) bản thân tôi vẫn hoàn toàn ổn (okay) đéo hề hấn đéo gì cả.",
  "No, I should really go home and rest.": "Đéo (No), tôi thực sự (really) rất nên (should) đi về nhà (go home) ngay và đi nghỉ ngơi tĩnh dưỡng (rest) đôi chút.",
  "Royal Igorot Axe": "Cây Rìu Bổ Củi Chết Tiệt Mang Tên Royal Igorot (Royal Igorot Axe)",
  "We've been losing people right and left. I think we've got one of those eyeless freaks in the area.": "Chúng tôi hiện đang liên tục phải chứng kiến sự bỏ mạng tồi tệ hi sinh (losing) của vô số những người đồng đội (people) của mình ở khắp mọi nơi (right and left). Tôi nghĩ (think) rằng rất có khả năng hiện chúng tôi đang phải đối mặt (got) với một trong số (one) những cái con quái vật gớm ghiếc (freaks) hoàn toàn đéo có mắt (eyeless) đang lảng vảng đi lại lượn lờ ở quanh khu vực (area) này.",
  "Ray Santos tried to bribe me with a car. Screw him. - %1$s": "Tên chó đẻ khốn nạn Ray Santos đó đã cả gan dám thử (tried) giở trò mua chuộc hối lộ (bribe) tôi chỉ bằng một cái chiếc xe hơi (car) phế liệu tồi tàn rác rưởi. Mặc xác (Screw) thằng khốn kiếp đó (him) đi đéo thèm quan tâm. - %1$s",
  "We might live through this yet.": "Tuy vậy (yet) chúng ta có lẽ (might) là sẽ có khả năng cố gắng sống sót vượt qua (live through) được toàn bộ cái cơn ác mộng thảm kịch (this) tồi tệ này.",
  "Daily Rations of Food": "Các Khẩu Phần Ăn Tiêu Chuẩn (Rations) Dùng Để Cung Cấp Lương Thực Thực Phẩm (Food) Dành Cho Từng Ngày (Daily)",
  "%+d Community Fame (Slaughter)": "%+d Điểm Danh Tiếng Uy Tín (Fame) Của Cộng Đồng (Community) Dành Cho Những Kẻ Chuyên Đi Tàn Sát Đâm Chém Máu Lạnh (Slaughter)",
  "Over here! Come and get it!": "Hãy mau đi tới bên này (Over here) đi! Nào hãy mau đến đây (Come) và bắt đầu thử tiến hành xơi tái tao xem nào (get it) cái lũ chó đẻ tởm lợm này!",
  "Look, I appreciate you coming to get me, but I really need to find this. Do you think you can come with me while I look for it?": "Nghe này (Look), tôi thực sự vô cùng trân trọng đánh giá cao (appreciate) cái việc cậu đã cất công lặn lội đi đến tận đây (coming) chỉ để tìm đón (get) tôi đi, thế nhưng (but) tôi hiện đang thực sự rất cần (really need) phải tìm lại (find) cho bằng được cái món đồ vật tồi tệ này (this) cái đã. Cậu có nghĩ (think) rằng cậu có thể (can) nán lại một chút để đi theo hỗ trợ (come with) tôi trong lúc (while) tôi đi cố gắng lục lọi tìm kiếm (look for) lại nó đéo?",
  "That's not necessary.": "Chuyện đó (That's) hoàn toàn đéo hề (not) có một chút đéo nào là thực sự cần thiết (necessary) đâu.",
  "Blue ballpoint pen on pink flowery stationery, sealed in a plastic sandwich bag.": "Bút bi (ballpoint pen) với mực màu xanh (Blue) nằm ở trên nền giấy viết thư (stationery) điểm xuyết những hình hoa văn họa tiết (flowery) màu hồng nhạt (pink), được niêm phong đóng gói dán kín (sealed) vô cùng cẩn thận ở bên trong một chiếc túi nhựa (plastic) bọc sandwich.",
  "William": "William",
  "Deadeye": "Kỹ Năng Ngắm Bắn Điểm Yếu Chết Người Sắc Sảo Tuyệt Đối Deadeye",
  "Eldridge brought up the fact that this toxic gas isn't normal. Dead bodies stink, but they don't asphyxiate. There's something more to these Bloaters than just rot.": "Eldridge vừa mới đưa ra mổ xẻ phân tích (brought up) một cái sự thật (fact) vô cùng quan trọng cho rằng cái thứ chất khí hơi (gas) vô cùng độc hại (toxic) tồi tệ này hoàn toàn đéo hề (isn't) được bình thường (normal) một chút đéo nào. Mùi hương phát ra từ những cái xác chết (Dead bodies) thối rữa đúng là vô cùng bốc mùi kinh tởm (stink), thế nhưng (but) chắc chắn là chúng đéo (don't) thể nào có thể khiến cho một con người bình thường rơi vào trạng thái ngạt thở tắt thở (asphyxiate) một cách tàn nhẫn được. Chắc chắn là đang có một cái bí ẩn chết tiệt đéo nào đó (something) đáng sợ ẩn chứa nhiều thứ tồi tệ khủng khiếp hơn (more) ở bên trong cơ thể của mấy cái con Bloaters gớm ghiếc này chứ đéo phải chỉ đơn thuần (just) là mùi hôi thối mục rữa (rot).",
  "Adeyemi": "Adeyemi",
  "I have an idea. Why don't you give me a hand for a bit?": "Tôi hiện đang có (have) một ý tưởng (idea) này. Tại sao cậu đéo (Why don't) chịu tự chủ động chìa ra một bàn tay của cậu (give me a hand) để giúp đỡ hỗ trợ cho tôi một chút (for a bit) đi nhỉ?",
  "Hey, we're all dealing with the same bullshit.": "Này, tất cả mọi người (all) trong số chúng ta hiện đều đang phải cùng nhau chịu đựng giải quyết đối mặt (dealing with) với chung (same) một cái đống cứt đái rác rưởi khốn nạn (bullshit) tồi tệ chết tiệt này thôi.",
  "Yeah, at least then I'd be able to keep the food I found.": "Yeah, chí ít (at least) là sau đó (then) tôi chắc chắn sẽ có khả năng (able) được phép giữ lại (keep) toàn bộ mọi nguồn cung cấp lương thực thực phẩm (food) tồi tệ mà tôi đã thu thập tìm thấy (found) được.",
  "It's nothing new--you never heard more whining than from the back seat of a patrol car.": "Cũng đéo có gì (nothing) thực sự là quá mới mẻ lạ lẫm (new)--cậu sẽ đéo bao giờ (never) phải nghe thấy (heard) vô vàn (more) những lời kêu ca phàn nàn rên rỉ (whining) thảm thiết từ bất cứ một nơi đéo nào khác ngoại trừ là từ khu vực ghế băng phía sau (back seat) của một chiếc xe tuần tra (patrol car) cảnh sát đéo.",
  "Use the Radio Menu to add GURUBANI KAUR to your community after you've established a base.": "Sử dụng Bảng Trình Đơn Menu Bộ Đàm Radio (Radio Menu) để có thể tiến hành kêu gọi kêu gọi bổ sung thêm (add) nhân vật GURUBANI KAUR gia nhập vào khu vực cộng đồng (community) những người sống sót của bạn ngay sau khi (after) bạn đã thành công tiến hành xây dựng thiết lập (established) xong xuôi một khu vực nền móng căn cứ (base) an toàn.",
  "You interested in joining forces? We'd be useful, I promise.": "Cậu có thực sự cảm thấy hứng thú quan tâm (interested) đến việc cùng nhau tạo lập thành một liên minh hợp nhất hai lực lượng (joining forces) này lại thành một hay đéo? Chúng tôi chắc chắn sẽ trở nên (be) cực kỳ hữu dụng có ích (useful), tôi xin hứa (promise) danh dự với cậu đấy.",
  "I appreciate it. Wasn't sure I'd make it home otherwise.": "Tôi thực sự vô cùng trân trọng đánh giá cao (appreciate) về điều tồi tệ này. Tôi hoàn toàn đéo (Wasn't) dám chắc chắn (sure) được rằng liệu tôi có còn có khả năng có thể quay trở về đến căn cứ ngôi nhà (home) một cách an toàn sống sót (make it) được hay đéo nếu như hoàn cảnh rẽ sang một hướng khác (otherwise).",
  "Yeah, I got you a pony. Then it tried to eat me, so I shot it in the head.": "Yeah, tôi đã tóm được (got) riêng cho cậu một con ngựa con (pony) vô cùng xinh xắn và đáng yêu đây. Nhưng sau đó (Then) cái con súc vật chết tiệt đó lại cố gắng (tried) cắn xé muốn xơi tái nhai nuốt (eat) tôi, thế nên (so) tôi đã đành phải cho nó một viên kẹo đồng (shot) găm thẳng tắp vào giữa cái đầu chết tiệt (head) của nó rồi.",
  "The city can't contain them anymore.": "Khu vực thành phố (city) này hoàn toàn đéo thể nào (can't) có thể tiếp tục kìm hãm giam giữ (contain) được bọn chúng thêm được nữa (anymore) đéo đâu.",
  "Morales": "Morales",
  "I dunno, but I'm not sure I trust him. You remember that corruption scandal a few years back?": "Tôi cũng đéo rõ (dunno), thế nhưng (but) tôi hoàn toàn đéo (not) dám chắc chắn (sure) được rằng liệu tôi có nên tin tưởng (trust) đặt trọn niềm tin vào cái tên đó (him) hay đéo nữa. Cậu có còn nhớ (remember) được cái vụ bê bối scandal tham nhũng hối lộ (corruption) kinh hoàng đã từng bị phanh phui xảy ra vào một vài (few) năm (years) trước (back) đéo?",
  "Menus": "Menu Điều Hướng",
  "Play Breakdown": "Bắt Đầu Chơi (Play) Phiên Bản Breakdown",
  "Catherine": "Catherine",
  "Trant": "Trant",
  "Lily": "Lily",
  "Held off a seige in Lifeline": "Đã Vô Cùng Xuất Sắc Thành Công Chống Trả Ngăn Chặn Đẩy Lùi (Held off) Lại Một Cuộc Tấn Công Bạo Lực Vây Hãm Khốc Liệt Tàn Bạo (seige) Ở Trong Chế Độ Phiên Bản Lifeline Chết Tiệt",
  "If you pass out from exhaustion, I ain't carryin' you home.": "Nếu như (If) cậu bị ngất xỉu (pass out) do việc kiệt sức (exhaustion), tôi chắc chắn sẽ đéo (ain't) thể nào có thể tự mình khuân vác vác (carryin') cậu quay trở về căn cứ (home) được đéo đâu.",
  "We've got a real problem with infestations around here. Think you can help us out?": "Chúng tôi hiện đang gặp phải một vấn đề vô cùng rắc rối (problem) thực sự nghiêm trọng (real) với việc dọn dẹp các loại khu vực ổ dịch (infestations) đang nằm rải rác lân cận ở xung quanh khu vực (around) nơi này. Cậu có nghĩ (Think) là cậu có thể (can) hỗ trợ giúp đỡ (help) giải thoát cho chúng tôi (us out) thoát khỏi mớ bòng bong này được đéo?",
  "I didn't realize the Department of Fish and Wildlife counted as a \"beat.\"": "Tôi hoàn toàn đéo thể nào (didn't) có thể sớm nhận ra (realize) được rằng khu vực làm việc trực thuộc Sở Quản Lý Hành Chính Về Các Loài Cá (Fish) Và Các Động Vật Hoang Dã (Wildlife) lại được đánh giá tính xem (counted) như (as) là một \"tuyến khu vực địa bàn dùng để phân chia lịch đi tuần tra (beat)\" đéo.",
  "1 Outpost - Artillery Barrage": "1 Khu Vực Tiền Đồn (Outpost) - Lực Lượng Pháo Binh Bắn Phá Chặn Hậu Xé Nát Bét Đội Hình (Artillery Barrage)",
  "Each Outpost creates a safe area around it.": "Mỗi một (Each) Khu Vực Tiền Đồn (Outpost) sẽ có khả năng tự động tạo dựng thiết lập (creates) nên một mạng lưới vòng an toàn (safe area) cực kỳ kiên cố bao bọc vững chãi ở mọi bề xung quanh quanh (around) khu vực đó (it).",
  "Delay your decision. Ignoring the problem will make it go away, won't it?": "Tiến hành Trì Hoãn Bỏ Lỡ Việc Đưa Ra (Delay) quyết định xử lý (decision) của bạn. Việc liên tục làm ngơ cố tình lờ đi (Ignoring) một vấn đề rắc rối (problem) tồi tệ chắc chắn sẽ (will) làm cho (make) nó tự động tan biến đi mất (go away), liệu có đúng đéo (won't it)?",
  "Kraus": "Kraus",
  "Hey man, we could use your advice on some construction.": "Này người anh em (man), chúng tôi hiện tại đang thực sự rất cần (could use) những lời đề nghị lời khuyên tư vấn (advice) từ cậu liên quan đến một vài (some) dự án công trình xây dựng (construction) đéo nào đó.",
  "Anyway, I wanted you to know that I understand your frustration.": "Dù sao đi chăng nữa (Anyway), tôi thực sự chỉ muốn (wanted) cậu biết (know) một sự thật đó là (that) tôi hoàn toàn vô cùng thấu hiểu (understand) cho sự thất vọng vô cùng não nề và nỗi bực tức tức giận điên cuồng (frustration) của bản thân cậu.",
  "Gimme a minute?": "Có thể phiền xin phép vui lòng tự động dành ra nán lại (Gimme) cho tôi thêm được một phút đồng hồ (minute) nữa đéo?"
};

const file = 'output/languages/chunks/btxt_chunk_210.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_210.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk210[r.sourceText]) {
    r.translatedText = chunk210[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 210 successfully!');
