const fs = require('fs');
const chunk123 = {
  "Hey Doc, what do I do about this injury?": "Này Bác sĩ, tôi phải làm gì với vết thương này đây?",
  "Nothing this organized, though.": "Dù vậy thì cũng không có gì được tổ chức bài bản như thế này đâu.",
  ".357 caliber": "Cỡ nòng .357",
  "Okay... you say so. Maybe grab some meds from the communal supply though, huh?": "Được rồi... cậu nói sao thì nghe vậy. Dù sao thì, có lẽ nên lấy ít thuốc men từ kho dự trữ chung, nhỉ?",
  "Shit, I knew we should have picked Montana this year.": "Chết tiệt, tôi biết đáng ra năm nay chúng ta nên chọn đi Montana mà.",
  "Biohazard! Extra Bloaters. Moderate extra damage. Lethal Juggernauts. No map indicators.": "Thảm họa sinh học! Thêm Bloaters. Tăng thêm sát thương ở mức vừa. Juggernauts Chí Mạng. Không có chỉ báo trên bản đồ.",
  "I've been looking for you.": "Tôi đang tìm cậu đấy.",
  "Gonna need a bigger wall": "Sẽ cần một bức tường lớn hơn đấy",
  "Victor": "Victor",
  "Wait here. Looks like trouble ahead.": "Đợi ở đây. Phía trước có vẻ như có rắc rối.",
  "Help Dr. Horn collect the notes": "Giúp Tiến sĩ Horn thu thập các ghi chép",
  "Scratches from zombies are no joke. They can get very deep, and the risk of infection is high. (Health and Stamina penalties)": "Vết cào từ zombie đéo phải chuyện đùa đâu. Chúng có thể rất sâu, và nguy cơ nhiễm trùng là rất cao. (Giảm Máu và Thể lực)",
  "That's it! Charges set! Go go go!": "Xong rồi! Đã cài thuốc nổ! Đi đi đi!",
  "ATTITUDE: Insensitive": "THÁI ĐỘ: Vô cảm",
  "Willing to share.": "Sẵn sàng chia sẻ.",
  "I just want you to know, you're doing great. Thanks.": "Tôi chỉ muốn cậu biết là cậu đang làm rất tốt. Cảm ơn nhé.",
  "Staffing:": "Nhân sự:",
  "Try not to break everything in here, okay?": "Cố gắng đừng có phá nát mọi thứ trong này nhé, được không?",
  "You can scratch that supply run out of your day planner... and expect some harsh words from %1$s. Something about being hung out to dry? - %2$s": "Cậu có thể gạch cái chuyến đi lấy vật tư đó khỏi lịch trình trong ngày rồi đấy... và chuẩn bị tinh thần nghe %1$s chửi thề đi. Cái gì mà bị đem con bỏ chợ ấy? - %2$s",
  "Who's interested in a little hunting practice?": "Có ai hứng thú với việc thực hành săn bắn một chút không?",
  "The zeds have breached the north gate!": "Lũ zed đã chọc thủng cổng phía bắc rồi!",
  "I'm getting on the helicopter, too, right?": "Tôi cũng được lên trực thăng phải không?",
  "Recoil Reduction": "Giảm Độ Giật",
  "Give me a minute, all right?": "Cho tôi một phút, được chứ?",
  "ACCEPT. You will leave on the next helo, and destroy the city.": "CHẤP NHẬN. Bạn sẽ rời đi trên chiếc trực thăng tiếp theo và phá hủy thành phố.",
  "MISSION: Special Delivery": "NHIỆM VỤ: Giao hàng Đặc biệt",
  "Hey, if that floats your boat, I'm not turning down free help.": "Này, nếu điều đó làm cậu vui, thì tôi cũng không đời nào từ chối sự giúp đỡ miễn phí đâu.",
  "Expelled Member": "Thành Viên Bị Trục Xuất",
  "I’m all packed up. Just let me know when you find a good place to settle down. I’ll come and meet you there.": "Tôi đã thu dọn đồ đạc xong xuôi cả rồi. Chỉ cần báo cho tôi khi cậu tìm được chỗ nào ngon lành để định cư. Tôi sẽ đến gặp cậu ở đó.",
  "Is that a threat?": "Đó là một lời đe dọa à?",
  "Paint Cans": "Các Thùng Sơn",
  "Actor Will flee if Hungry": "Nhân vật sẽ bỏ chạy nếu Bị Đói",
  "TRUST GAINED (Emotional Support)": "ĐẠT ĐƯỢC SỰ TIN TƯỞNG (Hỗ trợ Tinh thần)",
  "Rescued.": "Đã Giải cứu.",
  "The new facility looks like shit, but I guess it'll do.": "Cơ sở mới trông như cức, nhưng tôi đoán nó cũng tạm ổn.",
  "Feel like lending a hand?": "Có muốn giúp một tay không?",
  "Well for now, that's a good enough reason. It's bad enough fighting zombies, I don't want to fight the Wilkersons, too.": "Chà, ít ra thì bây giờ, đó là một lý do đủ tốt. Đánh nhau với zombie đã đủ tệ rồi, tôi đéo muốn phải đánh nhau với nhà Wilkerson nữa đâu.",
  "Time to get my ass back on the ground.": "Đến lúc vác xác trở lại mặt đất rồi.",
  "HOME: Food Contamination": "NHÀ: Thức Ăn Bị Ô Nhiễm",
  "Kill that rotter!": "Giết con thây ma đang thối rữa đó đi!",
  "The zed ain't been made that can fuck with me!": "Con zed đéo nào có thể chơi lại tao đâu!",
  "Izquierdo": "Izquierdo",
  "Increased XP from melee combat.": "Tăng XP nhận được từ cận chiến.",
  "You learn a lot about human nature doing people's hair. My number one takeaway? We're doomed. (Counseling experience.)": "Bạn sẽ học được rất nhiều về bản chất con người khi làm tóc cho họ. Bài học lớn nhất tôi rút ra được ư? Chúng ta tiêu đời rồi. (Kinh nghiệm tư vấn tâm lý.)",
  "Golf Club": "Gậy Đánh Golf",
  "In the old days they'd fill shotguns with nails, bits of glass, rocks, whatever they could get their hands on. Bet that'd ruin a zombie's day.": "Ngày xưa, người ta thường nhồi vào súng shotgun đinh, mảnh thủy tinh, sỏi đá, bất cứ thứ gì họ có thể tìm được. Cá là thứ đó sẽ khiến bọn zombie tơi bời hoa lá.",
  "Not cool, brah. Not cool.": "Đéo ngầu đâu, ông bạn. Đéo ngầu chút nào.",
  "What's with the toxic gas?": "Khí độc này là sao đây?",
  "Once you get on the road, you'll face terrors you can't imagine, and there's a good chance you'll die.": "Một khi đã lên đường, cậu sẽ phải đối mặt với những nỗi kinh hoàng không thể tưởng tượng nổi, và rất có khả năng cậu sẽ chết.",
  "Kensenth": "Kensenth",
  "Come on over and take a fucking bite!": "Lại đây và cắn mẹ tao một miếng đi!",
  "No sweat. I'll run interference while your people work.": "Đéo thành vấn đề. Tôi sẽ đánh lạc hướng trong lúc người của cậu làm việc.",
  "START MISSION. Roll out and hunt some freaks.": "BẮT ĐẦU NHIỆM VỤ. Xuất phát và đi săn vài con quái thai thôi.",
  "That's not a good idea.": "Đó đéo phải là một ý kiến hay đâu.",
  "Okay, I'm headed your way.": "Được rồi, tôi đang tiến về phía cậu đây.",
  "Better wrap things up quick.": "Tốt nhất là giải quyết mọi chuyện nhanh gọn đi.",
  "Talcum Powder": "Phấn rôm",
  "Well, the infestation's dealt with, but %1$s had a pretty nasty time of it. - %2$s": "Chà, ổ dịch đã được giải quyết, nhưng %1$s đã có một khoảng thời gian khá tồi tệ với nó. - %2$s",
  "Anybody out there's got a set of wheels and the inclination to play good Samaritan, swing on by the farm.": "Nếu có ai ngoài kia có xe và có nhã ý làm người tốt việc tốt, hãy tạt qua trang trại nhé.",
  "<Laughs>": "<Cười>",
  "Johanson": "Johanson",
  "63 PMC Mercenary": "63 Lính Đánh Thuê PMC",
  "Gather Progress": "Tiến Độ Thu Thập",
  "Tell Quentin?": "Nói với Quentin?",
  "Hold tight. I'm on my way.": "Cố bám trụ nhé. Tôi đang đến đây.",
  "Gamer Sigma": "Gamer Sigma",
  "Here comes another horde.": "Thêm một bầy horde nữa đang đến.",
  "The general isn't happy": "Tướng quân đang không hài lòng đâu",
  "I know we don't know each other that well, but it seems like you're having a pretty rough time.": "Tôi biết chúng ta không quá thân thiết, nhưng có vẻ như cậu đang trải qua một khoảng thời gian khá khó khăn.",
  "Watch your back!": "Cẩn thận sau lưng!",
  "I have other patients to see, but I will come visit the church and check on this friend of yours soon as I can. - %1$s": "Tôi còn những bệnh nhân khác phải lo, nhưng tôi sẽ đến nhà thờ và kiểm tra người bạn này của cậu ngay khi có thể. - %1$s",
  "You the one the Wilkersons sent?": "Ông là người mà nhà Wilkerson cử đến à?",
  "Suck it up. You survived that horde attack, you can survive this.": "Cam chịu đi. Cậu đã sống sót sau cuộc tấn công của bầy horde đó, cậu cũng sẽ vượt qua được chuyện này thôi.",
  "Black Friday to Doghouse, we have Julene Horn in the air with a stack of her husband's notes.": "Black Friday gọi Doghouse, chúng tôi đang đưa Julene Horn lên không trung cùng với một xấp ghi chép của chồng cô ấy.",
  "Cam": "Cam",
  "The Community page shows information on characters in your community. Character portraits may be shaded to indicate conditions such as Hurt, Sick, or Tired.\r\nUse the mouse to highlight a character and view Name, Equipment, Traits, Skills, and Status. Select the character to highlight specific items to see more information.": "Trang Cộng Đồng (Community) hiển thị thông tin về các nhân vật trong cộng đồng của bạn. Chân dung nhân vật có thể bị làm mờ để chỉ các tình trạng như Bị Thương, Bệnh Tật, hoặc Mệt Mỏi.\r\nSử dụng chuột để trỏ vào một nhân vật và xem Tên, Trang bị, Đặc điểm, Kỹ năng, và Trạng thái. Chọn nhân vật để làm nổi bật các mục cụ thể và xem thêm thông tin.",
  "If we work together, we can clear this infestation and make our lives easier.": "Nếu chúng ta hợp tác cùng nhau, chúng ta có thể dọn dẹp cái ổ dịch này và khiến cuộc sống của chúng ta dễ thở hơn.",
  "An unplanned death is a danger to everyone.": "Một cái chết không được lường trước là mối nguy hiểm đối với tất cả mọi người.",
  "Job denied it, but I'm pretty sure they know something about it, at least.": "Job đã phủ nhận, nhưng tôi khá chắc ít nhất là họ biết điều gì đó về chuyện này.",
  "Ask %s to join your home?": "Mời %s tham gia nhóm của bạn?",
  "Almost home.": "Sắp về đến nhà rồi.",
  "We've relocated to the Alamo BBQ and Burrito Hacienda. The food here wasn't very authentic, but the wall's surprisingly legit. - %1$s": "Chúng tôi đã chuyển đến quán Alamo BBQ and Burrito Hacienda. Đồ ăn ở đây không chuẩn vị lắm, nhưng bức tường phòng thủ thì tốt đến bất ngờ đấy. - %1$s",
  "Spotted a vet clinic that looks fairly untouched. We're going to go see what we can find. - %1$s": "Phát hiện một phòng khám thú y trông có vẻ như chưa bị ai động tới. Chúng tôi sẽ đến đó xem có thể tìm thấy gì. - %1$s",
  "Just wondering if you've been having the same problem.": "Chỉ đang thắc mắc liệu cậu có gặp phải vấn đề tương tự không.",
  "Destroyed 10 hordes in one day.": "Đã tiêu diệt 10 bầy horde trong một ngày.",
  "Get ‘em off the barricades!": "Đẩy lũ chúng nó ra khỏi các rào chắn đi!",
  "Need a Generator!": "Cần Một Máy Phát Điện!",
  "<Coughing> In retrospect, I'm not sure which I regret more.": "<Ho> Nghĩ lại thì, tôi cũng đéo chắc mình hối hận vì chuyện gì hơn nữa.",
  "Research at Ops Center": "Nghiên cứu tại Trung Tâm Điều Hành (Ops Center)",
  "Civic Duty": "Nghĩa Vụ Công Dân",
  "Inexpensive, full auto only WWII SMG.": "Loại súng tiểu liên rẻ tiền, chỉ có chế độ bắn tự động hoàn toàn từ thời Thế chiến II.",
  "HIGH-VALUE ASSET": "TÀI SẢN CÓ GIÁ TRỊ CAO",
  "Transferred to the Military Police stateside after being cleared of a friendly-fire incident. Never wanted to hold the lives of her fellow soldiers in her hands again. Now all bets are off.": "Đã chuyển sang lực lượng Quân cảnh trong nước sau khi được minh oan trong một sự cố bắn nhầm đồng đội. Không bao giờ muốn nắm giữ mạng sống của đồng đội trong tay mình nữa. Nhưng giờ thì mọi thứ đã thay đổi rồi.",
  "Hey, just hang in there, okay?": "Này, cứ cố bám trụ đi, được chứ?",
  "4 TANNER Sheila Brookstone": "4 TANNER Sheila Brookstone",
  "SET UP: Alamo Cold Storage": "THIẾT LẬP: Kho Lạnh Alamo",
  "A garden would let us grow some of our own food instead of always having to scavenge.": "Một khu vườn sẽ cho phép chúng ta tự trồng một chút thức ăn thay vì lúc nào cũng phải đi nhặt mót.",
  "Upgrade to Weapons Training": "Nâng Cấp lên Khu Huấn Luyện Vũ Khí (Weapons Training)",
  "Yeah... looking back on it, I should've gotten that dog.": "Phải... nghĩ lại thì, đáng lẽ ra tôi nên nuôi con chó đó.",
  "Hey, listen, sometimes stuff breaks. It's nobody's fault, it just is what it is.": "Này, nghe đây, đôi khi đồ đạc cứ thế mà hỏng thôi. Đéo phải lỗi của ai cả, nó vốn dĩ là thế rồi."
};

const file = 'output/languages/chunks/btxt_chunk_123.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_123.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk123[r.sourceText]) {
    r.translatedText = chunk123[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 123 successfully!');
