const fs = require('fs');
const path = require('path');

const chunk100 = {
  "Your inventory is FULL. There's no room for an ARTILLERY MARKER.": "Túi đồ của bạn đã ĐẦY. Không còn chỗ chứa ĐIỂM ĐÁNH DẤU PHÁO BINH.",
  "I'll handle the grunt work, I just don't want to go out there alone. Buddy system, right?": "Tôi sẽ lo mấy việc nặng nhọc, tôi chỉ không muốn ra ngoài đó một mình. Phải có đồng đội đi cùng chứ, đúng không?",
  "That's gonna keep happening until we clear out some infestations.": "Chuyện đó sẽ còn tiếp diễn cho đến khi chúng ta dọn dẹp xong mấy cái Ổ Dịch.",
  "54 GENERIC Clarice Washburn": "54 GENERIC Clarice Washburn",
  "Did that help at all?": "Điều đó có giúp ích được gì không?",
  "%+d Morale!": "%+d Nhuệ khí!",
  "I'll wait right here.": "Tôi sẽ đợi ngay đây.",
  "I'll lay it out. The other people back at base deserve better from you than what they're getting.": "Tôi nói thẳng nhé. Những người khác ở căn cứ xứng đáng nhận được nhiều hơn từ cậu thay vì những gì họ đang phải chịu đựng.",
  "That wasn't too close for you, was it?": "Như vậy là không quá sát sao với cậu chứ hả?",
  "MISSION: Friend In Danger": "NHIỆM VỤ: Bạn Bè Gặp Nạn",
  "Construction Experience": "Kinh nghiệm Xây dựng",
  "Restores classic cars. Don't ask about his first name.": "Thợ phục chế xe cổ. Đừng hỏi tên thật của anh ấy.",
  "Strong background in research and analysis.": "Có nền tảng vững chắc về nghiên cứu và phân tích.",
  "Lost target, I say again, lost target.": "Đã mất dấu mục tiêu, tôi nhắc lại, đã mất dấu mục tiêu.",
  "Help hunt the Bloated Zed?": "Giúp săn lùng con Zed Bụng Phệ chứ?",
  "Dude, bro... talk about a buzzkill.": "Trời ơi, ông bạn... đúng là kẻ phá đám.",
  "Clear the Blast Radius": "Dọn dẹp Bán Kính Vụ Nổ",
  "This is where we store the basic Supplies that we rely on in the field.": "Đây là nơi chúng ta cất giữ Nhu yếu phẩm cơ bản để dùng ngoài chiến trường.",
  "As promised, payment for your help the other day. Rumor has it those poor folks got killed by zombies not 10 minutes after you left. Real shame. - %1$s": "Như đã hứa, đây là thù lao cho sự giúp đỡ của cậu hôm nọ. Nghe đồn những người tội nghiệp đó đã bị zombie xé xác chỉ 10 phút sau khi cậu rời đi. Thật đáng tiếc. - %1$s",
  "Make Shotgun Shells": "Chế Tạo Đạn Shotgun",
  "Barracks": "Trại Lính",
  "Have %s accompany you and fight with you. (%d Influence)": "Yêu cầu %s đi cùng và chiến đấu cùng bạn. (%d Ảnh Hưởng)",
  "Delete": "Xóa",
  "We'll take care of the rest of the repairs.": "Chúng tôi sẽ lo phần sửa chữa còn lại.",
  "Modular and versatile, this rifle enjoys worldwide popularity.": "Thiết kế mô-đun và đa dụng, khẩu súng trường này cực kỳ phổ biến trên toàn thế giới.",
  "At least it wasn't a TPK.": "Ít nhất thì không phải là quét sạch toàn đội (TPK).",
  "Jenkins": "Jenkins",
  "Jessie": "Jessie",
  "It was a way to see the world even when I was stuck in the house.": "Đó là cách để ngắm nhìn thế giới ngay cả khi tôi bị mắc kẹt trong nhà.",
  "Kruger": "Kruger",
  "Hydrochloric Acid": "Axit Clohidric",
  "Hoo-ee! You keep on with what you're doing!": "Ái chà! Cứ tiếp tục phát huy nhé!",
  "Come on.": "Thôi nào.",
  "Last time anybody saw him, he was hanging out here. Probably the best place to start looking.": "Lần cuối cùng có người thấy anh ta là quanh quẩn ở đây. Có lẽ đây là nơi tốt nhất để bắt đầu tìm kiếm.",
  "Tanner": "Tanner",
  "Almost ready. Just got to take care of this one thing first.": "Gần xong rồi. Chỉ cần giải quyết nốt chuyện này trước đã.",
  "Payton": "Payton",
  "Kyra": "Kyra",
  "Yeah, that feels a lot better.": "Ừ, cảm giác khá hơn nhiều rồi đấy.",
  "Gabrielle": "Gabrielle",
  "You're like a fuckin' champ with that thing!": "Cậu dùng cái thứ đó như một nhà vô địch chết tiệt vậy!",
  "I think something might have been chewing on them. Ugh.": "Tôi nghĩ có thứ gì đó đã gặm nhấm đống này. Ọe.",
  "%1$s isn't allowed to go on sentry duty without somebody checking their breath for tequila. How many mags did they blow through and not hit a single damn thing? - %2$s": "%1$s không được phép gác đêm nếu không có ai kiểm tra xem có mùi tequila hay không. Cậu ta đã xả bao nhiêu băng đạn mà không trúng lấy một mục tiêu khốn khiếp nào chứ? - %2$s",
  "Kill a Bloater with a headshot.": "Giết một con Bloater bằng một phát bắn headshot.",
  "Resolution 1280x800": "Độ phân giải 1280x800",
  "Juggling Baton": "Gậy Tung Hứng",
  "Thank you for purchasing the original edition of State of Decay! Select this option, and an exclusive character will be added directly to your community.": "Cảm ơn bạn đã mua phiên bản gốc của State of Decay! Chọn tùy chọn này, và một nhân vật độc quyền sẽ tham gia trực tiếp vào cộng đồng của bạn.",
  "Oh shit. Zombie Horde.": "Ôi chết tiệt. Một bầy Zombie.",
  "Mishandled Gun": "Xử lý Súng Sai Cách",
  "116 HERO Zeika Rivera": "116 HERO Zeika Rivera",
  "2 Outposts - Drone Strike": "2 Tiền Đồn - Không Kích Bằng Drone",
  "God be praised.": "Tạ ơn Chúa.",
  "Strange Signal": "Tín Hiệu Lạ",
  "Let's hole up here a little longer. There's some stuff I want to do before we go.": "Hãy ẩn nấp ở đây thêm một chút nữa. Tôi còn vài việc muốn làm trước khi đi.",
  "You don't have to like orders to follow them.": "Cậu không cần phải thích những mệnh lệnh để tuân theo chúng.",
  "Mackenzie": "Mackenzie",
  "DECLINE MISSION. Leave the stranger to fend for himself.": "TỪ CHỐI NHIỆM VỤ. Bỏ mặc kẻ lạ mặt tự sinh tự diệt.",
  "Super Glue": "Keo Siêu Dính",
  "SNACKS aren't enough to combat long-standing HUNGER.": "ĐỒ ĂN VẶT không đủ để chống lại cơn ĐÓI kéo dài.",
  "Go easy, you're no good if you pass out.": "Từ từ thôi, cậu sẽ trở nên vô dụng nếu ngất xỉu đấy.",
  "Beat to shit, signals don't work and it smells like anchovies. Papa Fulci spared every expense on this sweet ride. Space for four, or twenty pizzas.": "Nát bét, đèn xi nhan hỏng và có mùi như cá cơm. Papa Fulci đã tiết kiệm từng xu cho chiếc xe ngọt ngào này. Chỗ cho 4 người, hoặc 20 chiếc pizza.",
  "Not the sharpest tool in the shed. (Improves wits SLOWLY.)": "Không phải là người thông minh nhất. (Tăng Trí Tuệ CHẬM.)",
  "Who's that there on the road? Huh?": "Ai đang ở trên đường thế kia? Hả?",
  "I think I could cobble together a signal booster out of these old guitar amps. Maybe pick up broadcasts from farther away.": "Tôi nghĩ mình có thể chắp vá một bộ khuếch đại tín hiệu từ những chiếc amply guitar cũ này. Có thể bắt được đài từ xa hơn.",
  "One of our neighbors radioed in a special request.": "Một trong những người hàng xóm của chúng ta vừa gọi vô tuyến yêu cầu một trợ giúp đặc biệt.",
  "Spent all day at work in a room full of brothers, sisters, parents, and cousins. Learned to navigate stressful social situations like a pro.": "Dành cả ngày làm việc trong một căn phòng chật ních anh chị em, cha mẹ và họ hàng. Học được cách giải quyết các tình huống xã hội căng thẳng như một chuyên gia.",
  "That's no damn good to anybody.": "Chuyện đó chẳng tốt đẹp chết tiệt gì cho ai cả.",
  "How many people, sir?": "Có bao nhiêu người thưa ngài?",
  "Hell, if I'm being honest, some days I don't even want to get out of bed in the morning, you know?": "Chết tiệt, nếu tôi nói thật, có những ngày tôi thậm chí không muốn bước ra khỏi giường vào buổi sáng, cậu biết không?",
  "Sure. I'll give you a little time to wrap up your business.": "Chắc chắn rồi. Tôi sẽ cho cậu một chút thời gian để giải quyết công việc của mình.",
  "An aggressive bullpup carbine, perfect for CQB.": "Một khẩu carbine bullpup hầm hố, hoàn hảo cho Cận chiến (CQB).",
  "Trophy Hunter": "Thợ Săn Tiền Thưởng",
  "I see you been takin' fightin' lessons from me!": "Tôi thấy cậu đã học được vài chiêu chiến đấu từ tôi đấy!",
  "Zombies? How the hell is that possible?": "Zombies sao? Làm thế quái nào lại có chuyện đó?",
  "This Is How You Died": "Đây Là Cách Cậu Chết",
  "120 STORY SWAT Officer": "120 STORY Sĩ quan SWAT",
  "Use the RV icon on the Home Tab of your Journal to prepare the RV for evacuation.": "Sử dụng biểu tượng Xe RV trên Tab Nhà (Home) trong Nhật ký của bạn để chuẩn bị Xe RV cho việc sơ tán.",
  "Research Potent Improvised Stims": "Nghiên cứu Thuốc kích thích Tự chế Cực mạnh",
  "I'll be back with a car.": "Tôi sẽ quay lại với một chiếc xe.",
  "Modern manufacture of the classic 1887, made popular by movies and video games.": "Phiên bản sản xuất hiện đại của dòng shotgun 1887 cổ điển, nổi tiếng qua phim ảnh và trò chơi điện tử.",
  "Lab Work": "Công Việc Phòng Thí Nghiệm",
  "Look, I don't know what you're trying to accomplish, but I've had enough.": "Nghe này, tôi không biết cậu đang cố gắng đạt được điều gì, nhưng tôi chịu đựng đủ rồi.",
  "The Fighter": "Chiến Binh",
  "Gained +5 Food.": "Nhận được +5 Thức ăn.",
  "Marley": "Marley",
  "Press [roll] to leapfrog over an enemy and knock them to their knees.": "Nhấn phím [Lăn] để nhảy qua một kẻ thù và vật ngã chúng.",
  "Okay, we've got some more materials headed your way.": "Được rồi, chúng tôi có thêm một số vật liệu đang được chuyển tới chỗ bạn.",
  "Requires Fighting Level 7": "Yêu cầu Cấp độ Chiến đấu 7",
  "Pills can't help right now.": "Thuốc men không thể giúp ích lúc này.",
  "Okay... well....": "Được rồi... chà....",
  "Light em' up! Redneck's special blend. Pretty sure it's pure wood-grain alcohol.": "Đốt cháy chúng! Hỗn hợp đặc biệt của bọn nhà quê. Cực kỳ chắc chắn đây là cồn nguyên chất.",
  "Juggernaut": "Juggernaut",
  "Bag of Fertilizer": "Bao Phân Bón",
  "Well?": "Sao?",
  "We've gotten word that another group of survivors wants to trade some of their Building Materials for some of our Ammunition. -%2$s": "Chúng ta nhận được tin báo rằng có một nhóm người sống sót khác muốn trao đổi một số Vật Liệu Xây Dựng của họ lấy Đạn Dược của chúng ta. -%2$s",
  "We could use some help.": "Chúng tôi cần một chút giúp đỡ.",
  "PERSONAL SKILL. God, I love money.": "KỸ NĂNG CÁ NHÂN. Chúa ơi, tôi yêu tiền.",
  "No, no. It makes perfect sense.": "Không, không. Nghe hoàn toàn có lý.",
  "35 GENERIC Martin Tarney": "35 GENERIC Martin Tarney",
  "Return Eldridge to Base": "Đưa Eldridge Trở Về Căn Cứ"
};

const file = 'output/languages/chunks/btxt_chunk_100.json';
const c = JSON.parse(fs.readFileSync(file, 'utf8'));
for(const r of c.replacements) {
  if(chunk100[r.sourceText]) {
    r.translatedText = chunk100[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 100 successfully!');
