const fs = require('fs');
const chunk197 = {
  "Harrison": "Harrison",
  "That's all I ask.": "Đó là tất cả những gì mà tôi yêu cầu.",
  "Maintains medic training by providing medication to the clients at a retirement home. Works at the hospital part-time.": "Thường xuyên duy trì việc đào tạo chuyên môn y tế của mình thông qua việc cung cấp các loại thuốc men cho những bệnh nhân tại một viện dưỡng lão. Đồng thời làm việc bán thời gian tại bệnh viện.",
  "Married right out of high school, accomplishing step seven in his nineteen-step plan for lifetime success.": "Kết hôn ngay sau khi vừa mới tốt nghiệp trường trung học, hoàn thành xuất sắc bước thứ 7 trong kế hoạch 19 bước để đạt được những sự thành công ở trong cuộc đời của anh ấy.",
  "Well, then, I guess we better go find some pills for you two, huh?": "Chà, nếu vậy thì, tôi đoán là tốt hơn hết chúng ta nên đi tìm một vài viên thuốc (pills) cho hai người, hả?",
  "Not gonna be able to do this in a car.": "Đéo thể nào làm được cái việc này khi mà đang ngồi ở bên trong một chiếc xe ô tô (car) đâu.",
  "Everything okay?": "Mọi chuyện đều ổn cả chứ?",
  "Kimberly": "Kimberly",
  "Delivered to the Wilkersons.": "Đã giao hàng thành công tới tay của nhà Wilkersons.",
  "Seems like they're done causing trouble for the day. -%1$s": "Có vẻ như bọn họ đã hoàn tất cái việc gây ra thêm hàng tá những rắc rối cho ngày hôm nay cmnr. -%1$s",
  "Okay, I'm ready. Man, this is gonna hurt.": "Okay, tôi đã sẵn sàng cmnr. Trời ạ, việc này chắc chắn sẽ rất là đau đây.",
  "This place is starting to fall apart. We really need more materials.": "Cái nơi này đang dần bắt đầu rơi vào tình trạng đổ nát cmnr. Chúng ta thực sự đang rất cần có thêm nhiều loại vật liệu (materials) hơn nữa.",
  "Our defenses okay?": "Hệ thống phòng thủ (defenses) của chúng ta vẫn đang hoạt động ổn định cả chứ?",
  "A military and police oriented version of the F45, match barrel and optic.": "Một phiên bản súng F45 được thiết kế đặc biệt dành riêng cho quân đội và lực lượng cảnh sát, đi kèm với đó là một nòng súng chuẩn thi đấu (match barrel) và các loại ống ngắm quang học (optic).",
  "Man, this is gonna suck....": "Trời ạ, chuyện này chắc chắn sẽ cực kỳ tệ hại đây....",
  "Evelyn": "Evelyn",
  "Investigate the Signal": "Tiến Hành Điều Tra Nguồn Gốc Của Tín Hiệu (Signal)",
  "+0": "+0",
  "YOU ARE NO LONGER ENCUMBERED": "BẠN ĐÉO CÒN BỊ CẢN TRỞ BỞI SỨC NẶNG NỮA CÓ THỂ DI CHUYỂN BÌNH THƯỜNG",
  "Black Friday, we have a location on that supply drop. Sending it to you now.": "Black Friday, hiện tại chúng tôi đã xác định được vị trí của đợt thả đồ tiếp tế (supply drop) đó cmnr. Đang tiến hành gửi nó cho ngài ngay đây.",
  "%1$s has fallen into an actual depression.": "%1$s đã rơi vào trạng thái trầm cảm (depression) một cách vô cùng nghiêm trọng.",
  "Major, we had two more men with us. They went out looking for a vehicle.": "Thiếu tá (Major), chúng tôi đáng lẽ ra phải có thêm hai người đàn ông nữa đi cùng. Bọn họ đã đi ra ngoài đó để tìm kiếm một chiếc xe di chuyển (vehicle) cmnr.",
  "We got another one of them big 'uns comin'!": "Chúng ta lại có thêm một trong số mấy thằng to xác đó đang đi tới kìa!",
  "ZOMBIE INFESTATION": "CÓ MỘT Ổ DỊCH ZOMBIE (ZOMBIE INFESTATION)",
  "Has a new home.": "Đã có được một mái ấm (home) mới.",
  "MEDICINE RESOURCE. Most of this stuff is illegal.": "NGUỒN THUỐC MEN (MEDICINE RESOURCE). Hầu hết tất cả những thứ này đều là những loại thuốc bất hợp pháp.",
  "Brought %3$s home.": "Đã đưa được %3$s trở về nhà an toàn.",
  "[message looping tone] One one tango lima november nine nine foxtrot six one quebec.": "[âm báo tin nhắn lặp lại liên tục] One one tango lima november nine nine foxtrot six one quebec.",
  "Get on the RV and leave the valley in our dust.": "Hãy leo lên chiếc xe RV và rời khỏi cái thung lũng này trong làn khói bụi mù mịt được tạo ra ở phía sau lưng của chúng ta.",
  "Come on, up you get. We need to get you out of this funk.": "Thôi nào, hãy mau đứng dậy đi. Chúng tôi cần phải giúp cho cậu thoát ra khỏi cái trạng thái hoảng loạn (funk) tồi tệ này.",
  "Manufacture Items": "Chế Tạo Ra Các Món Vật Phẩm (Manufacture Items)",
  "Can she help us with her husband's work?": "Liệu cô ấy có thể giúp đỡ chúng ta tiếp tục các công việc dang dở của chồng mình được đéo?",
  "%d Infestations Cleared": "%d Ổ Dịch (Infestations) Đã Được Dọn Dẹp Sạch Sẽ",
  "Delilah": "Delilah",
  "You folks seem to know what you're doing. Mind takin' us in so we could learn from you?": "Những người như các cậu dường như biết rất rõ những gì mà mình đang làm. Cậu có phiền đéo nếu như thu nhận chúng tôi vào nhóm để chúng tôi có thể học hỏi thêm được nhiều kinh nghiệm sinh tồn từ phía cậu?",
  "Search For %s": "Tìm Kiếm (Search) %s",
  "Build up your Cardio the old fashioned way: run. A lot.": "Hãy tăng cường chỉ số Sức Khỏe Tim Mạch (Cardio) của bản thân theo một cách cực kỳ truyền thống cổ điển: Chạy bộ (run). Chạy thật là nhiều vào.",
  "Camera / Zoom": "Camera / Thu Phóng (Zoom)",
  "We might need an extra hand on this one.": "Có lẽ chúng ta sẽ cần phải nhờ đến sự trợ giúp của một số người khác ở trong việc này đấy.",
  "If you're still alive, then you're in my prayers. Get out if you can.": "Nếu như bạn vẫn còn sống sót, vậy thì bạn đang nằm ở trong những lời cầu nguyện của tôi đấy. Hãy nhanh chóng trốn thoát khỏi nơi đó nếu như bạn có thể.",
  "DANGER: Infestations": "SỰ NGUY HIỂM (DANGER): Các Ổ Dịch (Infestations)",
  "See, that's good old-fashioned craftsmanship right there. None of that particle board, pine-veneer Swedish crap you put together with an allen wrench.": "Nhìn xem, đó chính là một trong những sản phẩm mang đậm tính chất thủ công mỹ nghệ cổ điển tuyệt vời đấy. Đéo có bất kỳ một miếng gỗ công nghiệp (particle board) hay là mấy cái đống rác rưởi phủ lớp veneer gỗ thông (pine-veneer) chết tiệt nào của Thụy Điển mà cậu có thể dễ dàng lắp ráp lại với nhau bằng một cái cờ lê lục giác (allen wrench) ở đây đâu.",
  "Just... Look, when the time comes, make it quick, okay? One in the head. Don't let me suffer.": "Chỉ là... Nghe đây, khi thời điểm đó thực sự đến, hãy làm nó một cách thật nhanh gọn, được chứ? Hãy bắn một viên đạn thẳng vào đầu tôi. Đừng để cho tôi phải chịu thêm bất cứ một sự đau đớn nào cả.",
  "These opportunities are only available if we have a strong reputation.": "Những cơ hội (opportunities) này sẽ chỉ có sẵn khi và chỉ khi chúng ta sở hữu được một mức độ danh tiếng (reputation) đủ mạnh.",
  "Knock down burning stuff.": "Có thể đánh ngã được những thứ đang bị bốc cháy.",
  "Should be on your map.": "Nó đáng lẽ ra phải xuất hiện ở trên tấm bản đồ (map) của cậu rồi chứ.",
  "Why don't people like me as much as you?": "Tại sao mọi người lại đéo hề thích tôi nhiều giống như cách mà bọn họ thích cậu nhỉ?",
  "We've got zeds at nine o'clock.": "Chúng ta đang có lũ zeds tiếp cận từ hướng 9 giờ.",
  "We can track it down or find another way, but it'd be faster if you did a little scavenger hunt.": "Chúng ta có thể tự mình truy tìm dấu vết của nó hoặc là tìm kiếm một cách giải quyết khác, nhưng mọi việc sẽ có thể diễn ra nhanh hơn rất nhiều nếu như cậu chịu thực hiện một cuộc đi săn nhặt phế liệu (scavenger hunt) nho nhỏ.",
  "But you poke them once in the brain and SPLAT! Dead.": "Nhưng cậu chỉ cần đâm bọn chúng một nhát xuyên qua não và SPLAT! Chết ngay lập tức.",
  "%1$s isn't originally from our unit, but they're ready and willing to fight.": "%1$s vốn đéo phải là người xuất thân từ đơn vị của chúng ta, nhưng cậu ấy đã sẵn sàng và rất sẵn lòng tham gia chiến đấu cùng với chúng ta.",
  "Roger that. We have a helo en route to your position.": "Đã rõ. Hiện tại chúng tôi đang có một chiếc trực thăng (helo) đang trên đường (en route) bay tới vị trí đóng quân của các người.",
  "TIP: Press [xi_dpad_up] (D-pad) and then [xi_shoulderl] to view your HOME BASE.": "MẸO (TIP): Nhấn phím [xi_dpad_up] (D-pad) và sau đó nhấn [xi_shoulderl] để xem CĂN CỨ (HOME BASE) của bạn.",
  "I'm not playing errand boy for the Wilkersons. - %1$s": "Tôi sẽ đéo bao giờ chịu đóng vai trò như là một tên nhóc chạy vặt (errand boy) ngu ngốc cho nhà Wilkersons đâu. - %1$s",
  "Hey, careful with the moaning. We've got itchy trigger fingers around here.": "Này, hãy cẩn thận với tiếng rên rỉ (moaning) đó đấy. Có rất nhiều kẻ đang cảm thấy vô cùng ngứa ngáy ngón tay đặt trên cò súng ở quanh đây đấy nhé.",
  "I don't think this place is big enough.": "Tôi đéo nghĩ rằng cái nơi này đủ rộng lớn để chứa chấp thêm người đéo đâu.",
  "Lily, how much time have I got to take care of this?": "Lily, tôi sẽ có khoảng bao nhiêu thời gian rảnh rỗi để có thể giải quyết được chuyện này đây?",
  "Jarrell": "Jarrell",
  "The zeds are inside the west gate!": "Lũ zeds đã lọt được vào bên trong khu vực cổng phía tây rồi!",
  "You're a lifesaver, Ray. Uhh, what did we agree on for the price?": "Ông đúng là một ân nhân cứu mạng (lifesaver) đấy, Ray. Uhh, vậy chúng ta đã thỏa thuận với nhau về mức giá cả như thế nào nhỉ?",
  "Not looking so good.": "Trông đéo có vẻ tốt đẹp cho lắm.",
  "Even in defeat, we can fight back. %1$s understood that. - %2$s": "Ngay cả khi phải đối mặt với sự thất bại cay đắng, chúng ta vẫn có thể phản công (fight back) trở lại. %1$s đã hiểu được điều đó. - %2$s",
  "We can't get discouraged by every setback.": "Chúng ta đéo thể nào trở nên nản lòng (discouraged) chỉ vì một vài thất bại nhỏ được.",
  "Vehicle Ops Breached": "Khu Vực Bảo Trì Phương Tiện Di Chuyển (Vehicle Ops) Đã Bị Xâm Nhập Phá Vỡ (Breached)",
  "I encountered a new group of survivors. So far they seem friendly. - %1$s": "Tôi vừa mới tình cờ bắt gặp được một nhóm những người sống sót (survivors) mới. Cho đến hiện tại thì có vẻ như bọn họ đều rất thân thiện. - %1$s",
  "Stay strong, people!": "Mọi người hãy cố gắng giữ vững tinh thần (Stay strong) nhé!",
  "Sorry, can't really talk right now.": "Thực sự rất xin lỗi cậu, hiện tại tôi đéo thể nói chuyện được.",
  "Meiss": "Meiss",
  "Yes ma'am!": "Tuân lệnh quý cô!",
  "We've lost too many to this godforsaken operation. Highroad out.": "Chúng ta đã đánh mất đi quá nhiều người vào trong cái chiến dịch khốn nạn bị Chúa bỏ rơi này cmnr. Highroad xin hết.",
  "Requires POWER TIE.": "Yêu Cầu (Requires) Phải Có SỰ KẾT NỐI VỚI NGUỒN ĐIỆN (POWER TIE).",
  "Daydreamer": "Kẻ Hay Mơ Mộng Hão Huyền (Daydreamer)",
  "Breakdown Level 4.": "Chế Độ Breakdown Cấp Độ (Level) 4.",
  "Right. Because normally gun-running moonshiners are such upstanding citizens?": "Đúng thế. Bởi vì thông thường thì những kẻ buôn lậu súng ống (gun-running) cũng đồng thời là những tên chuyên nấu rượu lậu (moonshiners) đều là những công dân cực kỳ gương mẫu hay sao?",
  "Alright, found it.": "Tuyệt vời, tôi đã tìm thấy nó rồi.",
  "I think I'm gettin' the short end of the stick here, but what the fuck.": "Tôi nghĩ là tôi đang phải chịu nhận lấy cái phần thiệt thòi (short end) lớn nhất ở trong cái thỏa thuận chết tiệt này, nhưng kệ mẹ nó đi.",
  "MATERIALS RESOURCE. Commercial construction materials.": "NGUỒN VẬT LIỆU (MATERIALS RESOURCE). Các loại vật liệu xây dựng (construction materials) được sử dụng trong thương mại.",
  "Sweet movie prop replica.": "Một món đồ phục chế làm đạo cụ trong phim ảnh (movie prop replica) cực kỳ tuyệt vời.",
  "61 GENERIC Larry Roach": "61 CHUNG (GENERIC) Larry Roach",
  "Rescue Dan Bogatz": "Giải Cứu Dan Bogatz",
  "ATTITUDE: Helpful": "THÁI ĐỘ (ATTITUDE): Luôn Sẵn Sàng Giúp Đỡ (Helpful)",
  "Chopper": "Chiếc Máy Bay Trực Thăng (Chopper)",
  "Daisy": "Daisy",
  "[message looping tone] One one lima november nine nine juliett six one oscar.": "[âm báo tin nhắn lặp lại liên tục] One one lima november nine nine juliett six one oscar.",
  "Hey, you're here! Let me grab what I can, and we'll head out.": "Này, cậu đã đến đây rồi! Hãy để cho tôi mang theo tất cả những thứ đéo mà tôi có thể, và sau đó chúng ta sẽ rời khỏi nơi này.",
  "Trait Discovered: Body Dump": "Đã Khám Phá Ra Đặc Điểm (Trait): Bãi Vứt Bỏ Xác Chết (Body Dump)",
  "Overachieving Student": "Một Sinh Viên Cực Kỳ Xuất Sắc (Overachieving Student)",
  "Robinson": "Robinson",
  "Nobody": "Đéo một ai cả",
  "I mean, plasma TVs and sports cars I get--some people are just dumbasses and think \"hey, free stuff.\"": "Ý tôi là, những chiếc tivi plasma và những chiếc xe thể thao (sports cars), tôi hoàn toàn có thể hiểu được điều đó--bởi vì một số kẻ chỉ là những lũ ngu ngốc và nghĩ rằng \"này, toàn là đồ miễn phí (free stuff) đéo thôi.\"",
  "Follow Lily": "Hãy Đi Theo Lily",
  "They're loaded down pretty good, though; an escort would be helpful.": "Mặc dù vậy, bọn họ đã mang vác theo khá là nhiều những loại vật tư hàng hóa nặng nề ở trên người; một sự hộ tống (escort) lúc này sẽ vô cùng hữu ích đấy.",
  "Glad that gun's on our side.": "Thật vui vì khẩu súng đó hiện đang nằm ở cùng phe với chúng ta.",
  "Rescue": "Nhiệm Vụ Giải Cứu (Rescue)",
  "We're too late.": "Chúng ta đã đến quá muộn cmnr.",
  "Reardon": "Reardon",
  "Listeners, you know I'm not one to judge.": "Các vị thính giả (Listeners) thân mến, các bạn đều biết rất rõ rằng tôi đéo phải là loại người thích đi phán xét (judge) một ai đó mà.",
  "Wagner": "Wagner",
  "Raab": "Raab",
  "Here comes the judge....": "Vị thẩm phán (judge) đã đến rồi đây...."
};

const file = 'output/languages/chunks/btxt_chunk_197.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_197.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk197[r.sourceText]) {
    r.translatedText = chunk197[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 197 successfully!');
