const fs = require('fs');
const chunk170 = {
  "Double Kill": "Hạ Gục Kép (Double Kill)",
  "Actually, um ... should I talk to a lawyer?": "Thực ra thì, ừm ... tôi có nên nói chuyện với một luật sư đéo?",
  "The RV's gas tank is empty. We're going to have to fill her up if we want to make it out of here. (RV FACILITY)": "Bình xăng của chiếc RV đã cạn kiệt. Chúng ta sẽ phải đổ đầy nó nếu muốn thoát khỏi đây. (CƠ SỞ RV - RV FACILITY)",
  "Okay, I'm clear. Say again?": "Được rồi, tôi nghe rõ. Cậu có thể nói lại đéo?",
  "Where's my damn shooter?!": "Tay súng chết tiệt của tôi đâu rồi?!",
  "Well, once the itis wears off.": "Chà, một khi cơn buồn ngủ (itis) qua đi.",
  "Well, if you see one, you let me know.": "Chà, nếu cậu thấy một cái, hãy cho tôi biết nhé.",
  "I've been listening to you pogues yammering on the radio for a couple of days now, doing your best to fuck up the apocalypse.": "Tôi đã nghe lũ lính quèn (pogues) bọn mày lải nhải trên radio được vài ngày nay rồi, đang cố gắng hết sức để làm cho cái ngày tận thế này trở nên tồi tệ hơn à.",
  "Dantron": "Dantron",
  "Colony": "Thuộc Địa (Colony)",
  "You got something against stompin' a zed when it's down?": "Cậu có vấn đề gì với việc dẫm đạp một con zed khi nó đã gục ngã à?",
  "No, I am not leaving empty-handed. You need to do what you can.": "Đéo, tôi sẽ đéo rời đi với hai bàn tay trắng đâu. Cậu cần phải làm những gì cậu có thể đi.",
  "Rule #18": "Quy Tắc Số 18",
  "Got to get out of here! I... I can't stay....": "Phải cút khỏi đây thôi! Tôi... tôi đéo thể ở lại được....",
  "Aura": "Aura",
  "Shotgun: Model 1100 Malone": "Súng Shotgun: Model 1100 Malone",
  "Thanks to some solid tactical planning, we've managed to recover some construction materials from the surrounding area.": "Nhờ có một kế hoạch chiến thuật vững chắc, chúng tôi đã xoay sở để thu hồi được một số vật liệu xây dựng từ khu vực xung quanh.",
  "XP penalty from Drunk.": "Bị trừ XP do Say Xỉn (Drunk).",
  "Spotted something interesting. We should check it out later.": "Vừa phát hiện ra thứ gì đó thú vị. Chúng ta nên kiểm tra nó sau.",
  "Heads up. We've got a visitor.": "Cẩn thận. Chúng ta có khách viếng thăm đấy.",
  "Guess we better get looking then, huh?": "Đoán là chúng ta tốt hơn nên bắt đầu tìm kiếm thôi, hả?",
  "Weapons Lab": "Phòng Thí Nghiệm Vũ Khí (Weapons Lab)",
  "We got a double dose.": "Chúng ta nhận được một liều lượng gấp đôi.",
  "Shit... way too exposed out here, gotta get moving.": "Chết tiệt... ngoài này trống trải quá, phải di chuyển thôi.",
  "You folks got this one?": "Mấy người có xử lý được tên này đéo?",
  "Where's my daughter? You told me you'd rescue her! You have to find her!": "Con gái tôi đâu? Các người đã nói với tôi là sẽ giải cứu con bé mà! Các người phải tìm ra con bé!",
  "We really better get moving.": "Chúng ta thực sự tốt hơn nên di chuyển thôi.",
  "I'm realizing more and more that stamina is the key to survival. And the more stuff I carry, the less stamina I have.": "Tôi ngày càng nhận ra rằng thể lực (stamina) là chìa khóa để sống sót. Và tôi càng mang vác nhiều đồ, tôi càng có ít thể lực hơn.",
  "Quentin has a question.": "Quentin có một câu hỏi.",
  "This is weird. I hope we're not ... stealing from someone.": "Thật là kỳ lạ. Tôi hy vọng chúng ta đéo đang ... ăn cắp đồ của ai đó.",
  "If he lives through the night, he'll probably pull through.": "Nếu anh ta sống qua đêm nay, có lẽ anh ta sẽ qua khỏi thôi.",
  "You see the zeds on our right?": "Cậu có thấy bọn zeds ở bên phải chúng ta đéo?",
  "Organized exercise program: An additional +10 Stamina for everyone.": "Chương trình tập luyện bài bản: Thêm +10 Thể Lực (Stamina) cho tất cả mọi người.",
  "We need to do something to turn this around or we're going to lose everyone. -%1$s.": "Chúng ta cần phải làm điều gì đó để xoay chuyển tình thế này nếu đéo chúng ta sẽ mất tất cả mọi người. -%1$s.",
  "Survive detonating a nuclear device in Danforth.": "Sống sót sau khi kích nổ một thiết bị hạt nhân ở Danforth.",
  "Give me a sitrep, Lily.": "Báo cáo tình hình (sitrep) cho tôi đi, Lily.",
  "Aspect Ratio - 16:9": "Tỷ Lệ Khung Hình - 16:9",
  "Vehicle Storage": "Bãi Đỗ Xe (Vehicle Storage)",
  "Booster": "Người Thúc Đẩy (Booster)",
  "Pickup Artist": "Nghệ Sĩ Tán Gái (Pickup Artist)",
  "Sounds like a good offer.": "Nghe có vẻ là một lời đề nghị hấp dẫn đấy.",
  "Friedl": "Friedl",
  "The world is apparently designed for people who see these imaginary colors called \"green\" and \"red\". (Difficulty Scavenging)": "Thế giới này dường như được thiết kế dành cho những người có thể nhìn thấy những màu sắc tưởng tượng được gọi là \"màu xanh\" và \"màu đỏ\". (Gặp Khó Khăn Khi Scavenging - Tìm kiếm đồ vật)",
  "We should be more quiet.": "Chúng ta nên giữ im lặng hơn.",
  "DOC HANSON": "BÁC SĨ HANSON",
  "You know, you shouldn't run around wounded like this.": "Cậu biết đấy, cậu đéo nên chạy nhảy xung quanh với những vết thương như thế này.",
  "Truth is, Ed's not the only one who needs medications.": "Sự thật là, Ed đéo phải là người duy nhất cần đến thuốc men.",
  "33 GENERIC Steve Scott": "33 CHUNG (GENERIC) Steve Scott",
  "We're getting pretty famous around here.": "Chúng ta đang trở nên khá nổi tiếng ở quanh đây rồi đấy.",
  "\"The United States of Trumbull.\" Got kind of a nice ring to it, huh?": "\"Hợp Chủng Quốc Trumbull.\" Nghe có vẻ cũng hay ho đấy chứ, hả?",
  "Oh shit, wait, he's coming over here. Act natural.": "Ôi chết tiệt, đợi đã, hắn đang đi tới đây. Cứ tỏ ra tự nhiên đi.",
  "The ME's office is on lockdown, so there's a good chance of survivors.": "Văn phòng Giám định Y khoa (ME) đang bị phong tỏa (lockdown), nên có khả năng cao là sẽ có những người sống sót.",
  "Beakers": "Cốc Mỏ (Beakers)",
  "MISSION: Trade Opportunity (Medicine)": "NHIỆM VỤ: Cơ Hội Giao Thương (Thuốc Men)",
  "Woah, on second thought. Hold off. This place isn't safe.": "Ồ, nghĩ lại thì. Khoan đã. Nơi này đéo an toàn đâu.",
  "Now we're making progress.": "Bây giờ chúng ta đang có tiến triển rồi đấy.",
  "Crook": "Kẻ Lừa Đảo (Crook)",
  "Shooting": "Khả năng Bắn Súng (Shooting)",
  "RUMOR: Neighbor Missing": "TIN ĐỒN (RUMOR): Hàng Xóm Bị Mất Tích",
  "I could be out on the ocean right now. The whole world could go to hell in handbasket, but I'd just have the waves and the wind, you know?": "Lẽ ra bây giờ tôi đã có thể lênh đênh trên biển khơi rồi. Cả thế giới có thể tan thành mây khói, nhưng tôi sẽ chỉ có những con sóng và những cơn gió, cậu biết đéo?",
  "This has been all over the radio lately.": "Dạo này chuyện này được phát ầm ĩ trên radio.",
  "Roger that, Defender. When you get there, find someone in charge, and tell them we're here.": "Đã rõ, Defender. Khi anh đến đó, hãy tìm người phụ trách và nói với họ là chúng ta đang ở đây.",
  "Cool. Not done yet.": "Tuyệt. Vẫn chưa xong đâu.",
  "But if you keep that shit inside, it'll eat away at you. You gotta let go.": "Nhưng nếu cậu cứ giữ cái đống tồi tệ đó trong lòng, nó sẽ ăn mòn cậu mất. Cậu phải buông bỏ đi.",
  "Kill Stragglers": "Tiêu Diệt Những Kẻ Tụt Hậu (Stragglers)",
  "Looking for somebody.": "Đang tìm ai đó.",
  "Hoarding": "Tích Trữ Đồ Đạc (Hoarding)",
  "Winter": "Winter",
  "I did. But I think you should ask her yourself if you really want to know.": "Tôi đã hỏi rồi. Nhưng tôi nghĩ cậu nên tự mình hỏi cô ấy nếu cậu thực sự muốn biết.",
  "The RV's engine is shot. It looks like something was chewing on it. We're going to have to fix it, or this trip is over before it starts.": "Động cơ của chiếc RV đã hỏng nặng rồi. Trông như thể có thứ gì đó đã nhai nát nó vậy. Chúng ta sẽ phải sửa nó, nếu đéo chuyến đi này sẽ kết thúc trước khi nó kịp bắt đầu đấy.",
  "%1$+d Trust with %2$s": "%1$+d Độ Tin Tưởng (Trust) với %2$s",
  "SMG: M3": "Súng Tiểu Liên (SMG): M3",
  "Mohammed": "Mohammed",
  "Slacker": "Kẻ Lười Biếng (Slacker)",
  "Dawn": "Dawn",
  "No, I think we're good. Look, you know that if it gets this bad again, you can find me, we can talk about it.": "Đéo, tôi nghĩ chúng ta ổn rồi. Nghe này, cậu biết là nếu mọi chuyện lại tồi tệ thế này nữa, cậu có thể tìm tôi, chúng ta có thể nói chuyện.",
  "Listen, man, we need some help here! A bunch of us are crammed into the church, and we-": "Nghe này anh bạn, chúng tôi cần được giúp đỡ! Một đám người chúng tôi đang bị dồn nhét vào nhà thờ, và chúng tôi-",
  "Might want to head down to the courthouse and see what's going on.": "Có lẽ cậu sẽ muốn đi tới tòa án để xem có chuyện gì đang xảy ra đấy.",
  "I hear you've got Dan Bogatz en route. What do you make of him? Is he our man?": "Tôi nghe nói cậu đã cho Dan Bogatz lên đường rồi. Cậu đánh giá anh ta thế nào? Anh ta có phải là người của chúng ta đéo?",
  "Listen to this. I recorded it a little while ago.": "Nghe đoạn này đi. Tôi đã ghi âm lại nó cách đây một lúc.",
  "You know something, you're all right. You ain't kin, but you're all right.": "Cậu biết đéo, cậu cũng được đấy chứ. Cậu đéo phải người nhà của tôi, nhưng cậu khá ổn đấy.",
  "Sneak to the Next Location": "Lén Lút Đi Tới Địa Điểm Tiếp Theo",
  "Cervantes": "Cervantes",
  "\"The United States of Trumbull.\" Got kind of a ring to it, huh?": "\"Hợp Chủng Quốc Trumbull.\" Nghe cũng xuôi tai đấy chứ, hả?",
  "Return to the Runner": "Quay Trở Về với Người Chạy Bộ (Runner)",
  "Locked.": "Đã khóa.",
  "Very good at coordinating large groups of people and multiple interlocking schemes. Always a step ahead of every problem.": "Rất giỏi trong việc điều phối các nhóm người lớn và nhiều kế hoạch đan xen nhau. Luôn đi trước mọi vấn đề một bước.",
  "Can't sit still in the base when there might be cigarettes out there. (Reduced Stamina)": "Đéo thể ngồi yên trong căn cứ khi có thể có thuốc lá ở ngoài kia. (Bị Giảm Thể Lực - Reduced Stamina)",
  "Barth": "Barth",
  "Ammunition and explosives.": "Đạn Dược và chất nổ.",
  "Zombies ain't smart, but they never quit. They'll find their way in if there's an opening, and if you give them enough time they'll make one.": "Bọn Zombies đéo thông minh gì, nhưng chúng đéo bao giờ bỏ cuộc. Chúng sẽ tìm đường vào nếu có kẽ hở, và nếu cậu cho chúng đủ thời gian, chúng sẽ tự tạo ra một đường vào.",
  "Thomson": "Thomson",
  "Wang": "Wang",
  "About fuckin' time.": "Cũng đến cmn lúc rồi đấy.",
  "'I'm glad you're here.'": "'Tôi rất vui vì cậu đang ở đây.'",
  "Yeah. Me too.": "Ừ. Tôi cũng thế.",
  "I remember all my kids.": "Tôi nhớ tất cả những đứa con của mình.",
  "%1$s wants us to help other survivors.": "%1$s muốn chúng ta giúp đỡ những người sống sót khác.",
  "Coming in with a full pack.": "Quay trở về với một chiếc balo đầy ắp.",
  "That's nothing. I caught her earlier, staring at her pistol like it was her long-lost friend.": "Chuyện đó đéo nhằm nhò gì đâu. Lúc nãy tôi vừa bắt gặp cô ta, đang chằm chằm nhìn vào khẩu súng lục của mình như thể nó là một người bạn mất tích từ lâu vậy."
};

const file = 'output/languages/chunks/btxt_chunk_170.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_170.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk170[r.sourceText]) {
    r.translatedText = chunk170[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 170 successfully!');
