const fs = require('fs');
const chunk191 = {
  "Brandon": "Brandon",
  "One of my callers wants to know if anyone has seen her friend Karen...Karen Tolbert.": "Một trong những thính giả gọi điện đến đài phát thanh của tôi muốn biết xem liệu có ai đã từng nhìn thấy bạn của cô ấy tên là Karen... Karen Tolbert đéo.",
  "No! You find my daughter. I'm not going anywhere unless we get Shira.": "Đéo! Các người phải tìm kiếm con gái tôi. Tôi sẽ đéo đi đâu cả trừ khi chúng ta tìm thấy Shira.",
  "Thanks! I thought I was dead.": "Cảm ơn nhé! Tôi cứ tưởng là mình đã chết chắc cmnr.",
  "%1$s encountered a Feral while out on patrol. We took it down together and bought ourselves some time before the next siege.": "%1$s đã đụng độ với một con Feral trong lúc đang đi tuần tra ở ngoài đó. Chúng tôi đã cùng nhau hạ gục được nó và câu thêm được một chút thời gian chuẩn bị cho bản thân trước khi cuộc bao vây (siege) tiếp theo bắt đầu diễn ra.",
  "Time for some scorched fuckin' earth.": "Đã đến lúc để thiêu rụi mảnh đất chết tiệt này cmnr.",
  "I'm showing that you're near the freeway tunnel. You looking for Sasquatch?": "Tín hiệu của tôi đang hiển thị rằng các cậu hiện đang ở rất gần khu vực đường hầm đường cao tốc (freeway tunnel). Có phải các cậu đang tìm kiếm Sasquatch đéo?",
  "Erikson": "Erikson",
  "Played it cool.": "Đã chơi rất ngầu.",
  "23 MIL Cpl Michael Hastings": "23 QUÂN ĐỘI (MIL) Hạ Sĩ (Cpl) Michael Hastings",
  "Blueprints": "Các Bản Thiết Kế Blueprints",
  "The rest of the family went one way ... and I went the other. I'm accustomed to being alone and self-sufficient.": "Những người còn lại trong gia đình đã đi theo một hướng ... còn tôi thì lại đi theo một hướng khác. Tôi đã quá quen thuộc với cuộc sống độc thân và luôn phải tự cung tự cấp (self-sufficient) rồi.",
  "Guess you fuckers like loud noises.": "Đoán chừng bọn khốn các người rất thích những tiếng ồn lớn.",
  "Better clear out before the zeds find me.": "Tốt hơn hết là nên dọn dẹp sạch sẽ khu vực này đi trước khi bọn zeds tìm thấy tôi ở đây.",
  "+80%": "+80%",
  "MISSION: Civic Duty": "NHIỆM VỤ (MISSION): Nghĩa Vụ Công Dân",
  "Copy that, Sarge. Let's pop some heads!": "Đã rõ, thưa Trung Sĩ (Sarge). Hãy cùng nhau làm nổ tung vài cái đầu thôi nào!",
  "This isn't on anyone. Just be careful. We can't lose track of anything in a scenario like this. Least of all weapons.": "Chuyện này đéo phải là lỗi của bất kỳ ai cả. Chỉ là hãy cẩn thận hơn một chút thôi. Chúng ta đéo thể để đánh mất bất cứ thứ gì trong một tình huống khó khăn như thế này được. Đặc biệt nhất là vũ khí.",
  "Some kind of deal went bad or something. I've heard, like, five versions of the story, but the long and the short of it is they ended up shooting each other or something.": "Có một cuộc giao dịch đéo nào đó đã diễn ra rất tồi tệ hoặc đại loại như thế. Tôi đã nghe được, giống như là, khoảng năm phiên bản khác nhau của câu chuyện này, nhưng tóm lại thì có vẻ như bọn họ đã kết thúc bằng việc nổ súng bắn vào nhau hoặc một thứ đéo gì đó tương tự.",
  "That's the idea.": "Đó chính là ý tưởng tuyệt vời đấy.",
  "Just hold on, Becca! I'm coming home!": "Cố gắng chịu đựng thêm một chút nữa thôi, Becca! Anh đang trên đường về nhà đây!",
  "Everything I see, I like.": "Tất cả những thứ gì lọt vào mắt của tôi, tôi đều rất thích.",
  "Escape: Repair Tires on the RV": "Trốn Thoát (Escape): Sửa Chữa Những Chiếc Lốp Cho Chiếc Xe RV",
  "Nguyen": "Nguyen",
  "I've been looking over our medical stocks. It looks like we could break some of this stuff down and brew up some stimulants.": "Tôi đang xem xét lại kho dự trữ vật tư y tế của chúng ta. Có vẻ như chúng ta có thể tiến hành phân tách một số thành phần ra và sử dụng để bào chế thành những loại thuốc kích thích (stimulants).",
  "Full-auto paired with the usual Bz 75 excellence. Spare mag is fitted as a foregrip.": "Phiên bản bắn hoàn toàn tự động (Full-auto) được kết hợp cùng với sự xuất sắc tuyệt đối của dòng súng Bz 75 thông thường. Băng đạn dự phòng (Spare mag) được thiết kế gắn liền như là một cái tay cầm phụ (foregrip).",
  "Requires CELL PHONE DATA PLAN.": "Yêu cầu phải có GÓI DỮ LIỆU MẠNG DI ĐỘNG (CELL PHONE DATA PLAN).",
  "Son of a bitch! Can't trust anybody to know their shit around here these days.": "Đồ chó đẻ! Chẳng thể nào tin tưởng giao việc cho bất cứ kẻ đéo nào ở cái nơi này trong những ngày tháng này được.",
  "Guest": "Khách (Guest)",
  "You feel like helping us clear an infestation?": "Cậu có muốn giúp đỡ cho chúng tôi dọn dẹp sạch sẽ một khu vực Ổ Dịch (infestation) đéo?",
  "Almost done. I'm so glad you're here.": "Gần xong cmnr. Tôi rất mừng vì cậu đang có mặt ở đây đấy.",
  "Hadley Westen died while we were trying to rescue him. We really did all we could, but ... it wasn't enough. I'm glad I'm not the one who has to explain this to his parents, and still ask for their help.": "Hadley Westen đã chết trong lúc chúng tôi đang cố gắng để giải cứu anh ta. Chúng tôi đã thực sự cố gắng làm mọi thứ trong khả năng của mình, nhưng ... điều đó là chưa đủ. Thật may mắn khi tôi đéo phải là người đứng ra giải thích chuyện này cho bố mẹ của anh ta hiểu, để rồi sau đó vẫn tiếp tục mặt dày yêu cầu sự giúp đỡ từ bọn họ.",
  "That ain't necessary.": "Chuyện đó là đéo cần thiết đâu.",
  "Can't carry that much.": "Đéo thể nào mang theo được nhiều đến như vậy.",
  "Red pen in an envelope with the name, \"Anthony\" on the front.": "Chiếc bút mực đỏ nằm gọn ở trong một phong bì có ghi tên, \"Anthony\" ở ngay mặt trước.",
  "Are things going to get better? I doubt it.": "Liệu rồi mọi chuyện có thể trở nên tốt đẹp hơn đéo? Tôi thực sự rất nghi ngờ về điều đó đấy.",
  "TIP: Hold [emote_hold] and tap [item] to drop rucksacks.": "MẸO (TIP): Giữ [emote_hold] và nhấn [item] để vứt bỏ các balo chứa đồ (rucksacks).",
  "Pull pin, toss, wait for boom. Repeat as necessary.": "Rút chốt, ném, chờ đợi để cho nó phát nổ (boom). Lặp lại nếu như cảm thấy cần thiết.",
  "Might want to swing wide, we got zombies off to the right there.": "Có lẽ chúng ta nên lùi lại giữ khoảng cách với chúng một chút đấy, đang có một vài con zombies vừa xuất hiện ở phía bên phải đằng kia kìa.",
  "Y'know, those painkillers work better when you actually USE 'em.": "Cậu biết đấy, những viên thuốc giảm đau (painkillers) đó sẽ chỉ có thể phát huy tác dụng tốt nhất khi cậu thực sự SỬ DỤNG chúng.",
  "And so help me, if you so much as sneeze on these, you will spend the rest of your very short life on zombie-baiting duty. Do I make myself clear?": "Và hãy giúp tôi một tay, nếu như cậu lỡ xì mũi vào những thứ này, cậu sẽ phải dành toàn bộ phần đời còn lại rất ngắn ngủi của mình để làm nhiệm vụ mồi nhử zombies (zombie-baiting) đấy. Tôi nói như vậy đã đủ rõ ràng để cho cậu hiểu hay chưa hả?",
  "Doc, I'm kinda messed up. What should I do?": "Doc, tôi đang cảm thấy hơi rối rắm một chút. Tôi nên làm cái đéo gì bây giờ?",
  "This looks like the place.": "Trông có vẻ như đây chính là nơi đó.",
  "Whatever's out there, it's got to be better than this... right?": "Bất kể thứ đéo gì đang ở ngoài kia đi chăng nữa, thì nó chắc chắn sẽ phải tốt đẹp hơn thế này rất nhiều... có đúng đéo?",
  "Guess this arm gives me some time to brush up on my domestic skills.": "Tôi đoán là cánh tay này sẽ giúp cho tôi có thêm một chút thời gian để có thể trau dồi lại các kỹ năng quản lý công việc nội trợ của bản thân mình đấy.",
  "Could you keep an eye out for a large vehicle of some kind? Like an RV or a bus ... something we could pack everybody into and head out if things got bad?": "Cậu có thể để ý tìm kiếm giúp cho tôi một phương tiện di chuyển có kích thước lớn nào đó được đéo? Giống như là một chiếc xe RV hoặc một chiếc xe buýt chẳng hạn ... một thứ đéo gì đó đủ sức chứa để chúng ta có thể nhét được tất cả mọi người vào trong và ngay lập tức rời đi nếu như mọi chuyện dần trở nên tồi tệ hơn?",
  "Naturally good shot. (Improves at SHOOTING faster)": "Sở hữu khả năng bắn súng cực kỳ tốt bẩm sinh. (Cải thiện tốc độ BẮN SÚNG SHOOTING được nhanh hơn)",
  "I guess I'll just wait here then?": "Tôi đoán là tôi sẽ tiếp tục chờ đợi ở đây?",
  "You heard your sister.": "Cậu đã nghe chị gái của mình nói gì rồi đấy.",
  "You gained renown": "Bạn đã nhận được điểm Danh Tiếng (renown)",
  "Can you blame her?": "Cậu có thể đổ lỗi cho cô ấy được đéo?",
  "Carl": "Carl",
  "Guess I'll follow you.": "Đoán chừng tôi sẽ đi theo các người.",
  "45 GENERIC Terrence Halverson": "45 CHUNG (GENERIC) Terrence Halverson",
  "28 GENERIC Shana Tarver": "28 CHUNG (GENERIC) Shana Tarver",
  "Having a good source of food helps too.": "Việc có được một nguồn cung cấp thức ăn (food) dồi dào cũng sẽ giúp ích được rất nhiều.",
  "Otherwise, I'm going to go ahead and take an inventory of what's here.": "Mặt khác, tôi sẽ tiếp tục đi lên phía trước và tiến hành kiểm kê lại toàn bộ những gì hiện đang có ở nơi này.",
  "Come with me, son. We'll see to those wounds.": "Hãy đi theo tôi nào, con trai. Chúng ta sẽ xem xét để chữa trị cho những vết thương đó.",
  "No time for grieving now, keep it together!": "Đéo có thời gian để mà đau buồn nữa đâu, hãy cố gắng giữ bình tĩnh đi!",
  "Give away 5 FOOD to help your neighbors survive.": "Trao tặng 5 THỨC ĂN (FOOD) để có thể giúp đỡ những người hàng xóm của bạn sống sót.",
  "I'll get you there.": "Tôi sẽ đưa cậu đến đó.",
  "There's a freak over there.": "Có một con quái vật đột biến freak ở đằng kia kìa.",
  "Command Center: Food Located": "Trung Tâm Chỉ Huy (Command Center): Đã Xác Định Được Vị Trí Của Thức Ăn (Food)",
  "75 GENERIC Mona Adkins": "75 CHUNG (GENERIC) Mona Adkins",
  "I'm almost there.": "Tôi sắp đến được nơi đó rồi.",
  "I've been building and repairing bikes since I was twelve years old. (Tools Expert)": "Tôi đã tự mình chế tạo và tiến hành sửa chữa những chiếc xe đạp kể từ khi tôi chỉ mới mười hai tuổi. (Chuyên Gia Công Cụ Tools Expert)",
  "Now I'm thinking we ought to check it out.": "Bây giờ tôi nghĩ là chúng ta nên đi đến đó để kiểm tra thử xem sao.",
  "So... we gonna get a bigger place soon? Sam snores. A lot.": "Vậy... liệu chúng ta có thể sớm chuyển đến một nơi rộng rãi hơn đéo? Sam ngáy to vãi đái. Rất là to luôn.",
  "Destroying hordes helps everyone.": "Việc tiêu diệt những bầy zombie hordes sẽ giúp ích cho tất cả mọi người.",
  "And he wanted to steal the slushy drink machine, and somehow he convinced me to help him carry it home.": "Và anh ta đã muốn đánh cắp luôn cả cái máy pha chế đồ uống đá tuyết (slushy), và đéo hiểu bằng cách nào mà anh ta đã thuyết phục được tôi giúp anh ta vác nó về nhà.",
  "Assault Rifle: 556 Grenade Launcher": "Súng Trường Tấn Công (Assault Rifle): Súng Phóng Lựu 556",
  "Bonk! (Weapon Specializations: Uppercut, Spinning Backhand)": "Bonk! (Chuyên Môn Vũ Khí: Tung Đòn Đánh Móc Uppercut, Xoay Người Vung Tay Đánh Trả Spinning Backhand)",
  "Refrigeration": "Thiết Bị Điện Lạnh (Refrigeration)",
  "This fever... I know what it means. I just don't have the guts to do it myself.": "Cơn sốt (fever) này... tôi biết chính xác nó có ý nghĩa gì. Tôi chỉ là đéo có đủ can đảm (guts) để tự mình ra tay kết liễu bản thân mà thôi.",
  "Pistol: G 26": "Súng Lục (Pistol): G 26",
  "Good thing we got a decent food stockpile.": "Một tin tốt đó là hiện tại chúng ta đang có một kho dự trữ thức ăn (food) khá ổn định.",
  "Crasman": "Crasman",
  "Iconic SMG, popular worldwide.": "Khẩu súng tiểu liên SMG mang tính biểu tượng, cực kỳ phổ biến trên toàn thế giới.",
  "Find yourself a good, high vantage point. You're gonna be doing some spotting for us.": "Hãy tìm cho mình một vị trí thuận lợi ở trên cao. Cậu sẽ phải tiến hành do thám một số mục tiêu cho chúng tôi đấy.",
  "Come with me. We'll dig 'em up.": "Hãy đi theo tôi nào. Chúng ta sẽ đào bới chúng lên.",
  "Matthews": "Matthews",
  "Pots": "Nồi Chảo (Pots)",
  "Load Up RV": "Chất Đồ Lên Xe RV",
  "Deliver the Ammo": "Tiến Hành Giao Số Đạn Dược (Ammo)",
  "I'm done here, let's roll out.": "Tôi đã hoàn thành xong mọi chuyện ở đây cmnr, chúng ta hãy rời khỏi đây thôi nào.",
  "These army guys have done what they could. I get that now.": "Những người lính quân đội (army) này đã cố gắng làm những gì mà bọn họ có thể. Bây giờ thì tôi đã hiểu được điều đó cmnr.",
  "Shit buddy, you're lookin' pretty fucked!": "Chết tiệt thật anh bạn à, trông cậu có vẻ tồi tệ vãi cả cứt!",
  "Firemode": "Chế Độ Bắn (Firemode)",
  "Crusty like how?": "Thô lỗ như thế đéo nào cơ?",
  "Rage": "Cơn Tức Giận (Rage)",
  "Thanks for the pep talk. It helped.": "Cảm ơn vì những lời khuyên chân thành. Nó thực sự đã giúp ích được rất nhiều.",
  "You think it's bad now? You should have seen Marshall in the first couple of days.": "Cậu nghĩ hiện tại như thế này là đã đủ tồi tệ lắm rồi sao? Cậu đáng lẽ ra nên nhìn thấy tình cảnh ở Marshall trong một vài ngày đầu tiên.",
  "To properly dispose of the re-animated, wrap the corpses in heavy duty plastic trash bags and leave them on the street.": "Để có thể tiêu hủy đúng cách những thi thể đã được tái sinh (re-animated), hãy bọc những cái xác đó lại bằng những chiếc túi ni lông đựng rác dày, dai và có độ bền cao sau đó hãy ném chúng ra ngoài đường.",
  "Artillery Support": "Hỗ Trợ Pháo Binh (Artillery Support)",
  "Keep your apolcalypse garden trim!": "Hãy luôn giữ cho khu vườn sinh thái apolcalypse của bạn được cắt tỉa một cách gọn gàng!",
  "If you really need me, I'll be, um...around somewhere. (Hates exercise.)": "Nếu như các người thực sự rất cần tôi, tôi sẽ, um...ở quanh quẩn đâu đó. (Căm ghét việc phải tập thể dục.)",
  "Better break out the big guns!": "Tốt hơn hết là hãy lấy mấy khẩu súng lớn (big guns) ra đi!",
  "Command Center: Ammo Located": "Trung Tâm Chỉ Huy (Command Center): Đã Xác Định Được Vị Trí Của Đạn Dược (Ammo)",
  "Sounds like %3$s is in danger. Maybe we should help. -%2$s": "Nghe có vẻ như %3$s đang gặp nguy hiểm thì phải. Có lẽ chúng ta nên đến đó để giúp đỡ. -%2$s",
  "Pliers": "Kìm Pliers"
};

const file = 'output/languages/chunks/btxt_chunk_191.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_191.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk191[r.sourceText]) {
    r.translatedText = chunk191[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 191 successfully!');
