const fs = require('fs');
const chunk111 = {
  "Doesn't take crap from anybody. Knows what's right and goes for it.": "Không để ai bắt nạt mình. Biết điều gì là đúng và theo đuổi nó.",
  "What can I say, I was in my punk rock \"fuck the man\" phase. I thought it made me cool.": "Biết nói sao đây, tôi từng có một thời kỳ nổi loạn theo phong cách punk rock kiểu \"kệ mẹ bọn có quyền\" (fuck the man). Tôi cứ tưởng thế là ngầu.",
  "%2$s is stuck in the middle of an infestation. Without help, I don't like the odds. -%2$s": "%2$s đang bị mắc kẹt giữa một Ổ dịch (Infestation). Nếu không có sự trợ giúp, tôi không thấy có nhiều hy vọng đâu. -%2$s",
  "Just hang in there!": "Cố gắng cầm cự nhé!",
  "Organized Leader": "Lãnh Đạo Có Tổ Chức",
  "The pilot dropped off a box of ammo that he scavenged from HQ. Should help us hold out for a bit longer.": "Viên phi công vừa thả xuống một thùng đạn mà anh ta kiếm được từ Trụ sở. Chắc sẽ giúp chúng ta cầm cự thêm một thời gian nữa.",
  "I think everybody's going to be sleeping with one eye open from now on. - %1$s": "Tôi nghĩ từ giờ trở đi mọi người sẽ phải ngủ với một con mắt mở to đấy. - %1$s",
  "Dude! Help! Now! Please?": "Này! Cứu với! Ngay bây giờ! Làm ơn?",
  "Escape": "Trốn Thoát",
  "Those barricades won't last!": "Những rào chắn đó sẽ không trụ được lâu đâu!",
  "Kelsey": "Kelsey",
  "I love it when they come right up the front like that!": "Tao thích cái cách bọn chúng xông thẳng tới phía trước như vậy!",
  "What does she think we are, miracle workers?": "Cô ta nghĩ chúng ta là ai chứ, những kẻ tạo ra phép màu chắc?",
  "Fish": "Cá",
  "I have a target.": "Tôi đã có mục tiêu.",
  "Whoa--easy there, Alex. It's me, Sheriff Carl. We don't want any trouble, we're just here to talk.": "Whoa--bình tĩnh nào, Alex. Là tôi đây, Cảnh sát trưởng Carl. Chúng tôi không muốn gây rắc rối, chúng tôi chỉ đến để nói chuyện thôi.",
  "Malia": "Malia",
  "Ya think? What's next, razor wire and guard towers?": "Cậu nghĩ vậy sao? Tiếp theo là gì, dây kẽm gai và tháp canh à?",
  "Dave": "Dave",
  "What do you want to do here?": "Cậu muốn làm gì ở đây?",
  "Found a bunch of dead people when we were out patrolling yesterday.": "Tìm thấy một đống xác người khi chúng tôi đi tuần tra hôm qua.",
  "The RV can run now, but we don't know how long it's going to last. Better get on the road soon, before our luck runs out.": "Chiếc RV đã chạy được rồi, nhưng chúng ta không biết nó sẽ trụ được bao lâu. Tốt nhất là lên đường sớm đi, trước khi vận may của chúng ta cạn kiệt.",
  "Business as usual at the Courthouse. Still confiscating guns and pretending they've got things under control. - %1$s": "Mọi chuyện vẫn như thường lệ ở Tòa án. Bọn họ vẫn tịch thu súng và giả vờ như đang kiểm soát được tình hình. - %1$s",
  "You better clear that infestation before they get there.": "Tốt hơn là cậu nên dọn sạch cái Ổ dịch đó trước khi họ đến đó.",
  "%1$s committed suicide.": "%1$s đã tự sát.",
  "In my defense, I was drunk at the time. - %1$s": "Biện hộ cho bản thân một chút, lúc đó tôi đang say xỉn. - %1$s",
  "That was a nice ride. Way to go, dipshit.": "Một chuyến đi tuyệt vời đấy. Khá lắm, đồ ngu.",
  "That oughta have some good stuff.": "Chỗ đó hẳn phải có vài thứ hay ho.",
  "Jesus, this hurts like hell. I hate feeling this useless.": "Chúa ơi, đau chết mất. Tôi ghét cảm giác vô dụng như thế này.",
  "Denial": "Chối Bỏ",
  "Your guess is as good as mine.": "Tôi cũng mù tịt như cậu thôi.",
  "Sorry about your people.": "Rất tiếc về những người của cậu.",
  "Experimental magazine-fed grenade launcher form CLEO.": "Súng phóng lựu nạp đạn bằng băng thử nghiệm từ CLEO.",
  "The east gate is compromised!": "Cổng phía đông đã bị chọc thủng!",
  "FUEL DELIVERED": "NHIÊN LIỆU ĐÃ ĐƯỢC GIAO",
  "Well, now we know where the black fever came from. -%1$s": "Chà, giờ thì chúng ta đã biết cơn Sốt Đen bắt nguồn từ đâu rồi. -%1$s",
  "Okaaay then, got it.": "Được rôồôi, hiểu rồi.",
  "All's quiet with the Wilkersons.": "Mọi thứ vẫn yên ắng với nhà Wilkerson.",
  "Hold [sprint] to sprint. Press [jump] to climb or vault objects. Sprint into doors to smash them open.": "Giữ [sprint] để chạy nước rút (sprint). Nhấn [jump] để leo hoặc nhảy qua các chướng ngại vật. Chạy nước rút lao vào cửa để tông tung chúng.",
  "Survey Point": "Điểm Khảo Sát (Survey Point)",
  "Tested out of high school to work at the family business. (Bonus to Wits)": "Nghỉ học trung học để làm việc cho doanh nghiệp gia đình. (Tăng điểm Mưu trí - Wits)",
  "I got what we came for. Time to go.": "Tôi lấy được thứ chúng ta cần tìm rồi. Đến lúc đi thôi.",
  "What kind of person turns a gun on someone they live with?": "Loại người gì lại chĩa súng vào người sống chung với mình chứ?",
  "It was that, or let him stay here and keep grumbling about kicking you and Ed out.": "Một là làm vậy, hai là để ông ta ở lại đây và tiếp tục càu nhàu về việc đuổi cậu và Ed đi.",
  "Pistol: G22": "Súng lục: G22",
  "Fiery Pickup": "Chiếc Xe Bán Tải Bốc Cháy",
  "Right. Guess I'm not surprised you're out here ignoring the quarantine orders.": "Được rồi. Chắc tôi không ngạc nhiên khi thấy cậu ở ngoài này và phớt lờ lệnh cách ly đâu.",
  "Your comms are fine. Nobody can raise Doghouse.": "Đường truyền liên lạc của cậu vẫn ổn. Không ai có thể liên lạc được với Doghouse cả.",
  "The general's furious that we couldn't retrieve our asset, Dan Bogatz. I'll take some comfort that we brought at least one more person out of Danforth alive.": "Tướng quân đang rất tức giận vì chúng ta không thể giải cứu nhân sự quan trọng, Dan Bogatz. Tôi sẽ tự an ủi phần nào khi ít nhất chúng ta đã đưa được một người nữa sống sót thoát khỏi Danforth.",
  "Fix Up Lockers": "Sửa Chữa Tủ Đồ",
  "They seem to like noise. They'll come check out any loud noise they hear.": "Bọn chúng có vẻ thích tiếng ồn. Chúng sẽ mò đến kiểm tra bất cứ tiếng động lớn nào nghe được.",
  "Hold [sprint] to search faster!": "Giữ [sprint] để tìm kiếm nhanh hơn!",
  "Jude": "Jude",
  "Fitness Magazine": "Tạp Chí Thể Hình",
  "A favorite in north-central Florida.": "Một món ăn yêu thích ở vùng Bắc-Trung tâm Florida.",
  "Navigation": "Điều hướng",
  "Hoffman": "Hoffman",
  "Striking Pads": "Đệm Tập Đánh (Striking Pads)",
  "Truck Stop": "Trạm Dừng Xe Tải",
  "Nothing worth my time here.": "Chẳng có gì đáng tốn thời gian ở đây cả.",
  "NOTE: I've Got An Idea": "GHI CHÚ: Tôi Có Một Ý Tưởng",
  "Apparently you're too important to leave behind.": "Rõ ràng là cậu quá quan trọng để bị bỏ lại phía sau.",
  "Eldridge": "Eldridge",
  "Can you help me gather these supplies before we go?": "Cậu có thể giúp tôi thu thập những nhu yếu phẩm này trước khi đi được không?",
  "Maybe COMBAT TRAINING at a DOJO would help.": "Có lẽ HUẤN LUYỆN CHIẾN ĐẤU (COMBAT TRAINING) tại môt VÕ ĐƯỜNG (DOJO) sẽ giúp ích.",
  "%1$s ran into some trouble on the way home from a scavenging run. Probably could have used our help. - %2$s.": "%1$s đã gặp rắc rối trên đường đi thu thập đồ tiếp tế về. Lẽ ra có thể cần đến sự giúp đỡ của chúng ta. - %2$s.",
  "Winters": "Winters",
  "Thank you for showing up. This stuff was just sitting here. If you watch my back, I'll load it up.": "Cảm ơn vì đã đến. Mớ đồ này cứ nằm tơ hơ ở đây. Nếu cậu canh chừng phía sau, tôi sẽ chất chúng lên.",
  "Pistol: Bz75 ST": "Súng lục: Bz75 ST",
  "COMMERCE: Train Outsiders": "THƯƠNG MẠI: Huấn luyện Người ngoài",
  "I'm barely keepin' it together right now.": "Lúc này tôi gần như không thể giữ nổi bình tĩnh nữa rồi.",
  "This here's too much.": "Thế này là quá mức chịu đựng rồi.",
  "Master the use of Edged Weapons.": "Bậc thầy sử dụng Vũ Khí Sắc Nhọn.",
  "With these guys running the show, are we better off with the zombies?": "Với những kẻ này nắm quyền điều hành, liệu chúng ta có tốt hơn khi ở cùng lũ zombie không?",
  "Somebody's been attacking survivors, stealing their stuff, and generally being assholes. Time to talk to the Wilkersons. - %1$s": "Có kẻ đang tấn công những người sống sót, cướp đồ của họ và hành xử như những thằng khốn nạn thực sự. Đã đến lúc phải nói chuyện với nhà Wilkerson. - %1$s",
  "Next time, use a blade to kill the Feral.": "Lần tới, hãy dùng một món vũ khí sắc nhọn để giết con Feral.",
  "Shit, you're always a rush!": "Chết tiệt, lúc nào cậu cũng hấp tấp!",
  "Santos": "Santos",
  "You want %2$s, you've got to go through me. - %3$s": "Nếu các người muốn có %2$s, thì phải bước qua xác tôi đã. - %3$s",
  "Anything at home I should be worried about?": "Ở nhà có chuyện gì mà tôi cần lo lắng không?",
  "Over here.": "Bên này.",
  "Controller disconnected.": "Tay cầm đã bị ngắt kết nối.",
  "Hey! Come get me, you dead bastards!": "Này! Đến bắt tao đi, lũ khốn chết tiệt kia!",
  "Will you just calm down? Just calm down. We'll find him.": "Cậu có thể bình tĩnh lại được không? Hãy bình tĩnh lại. Chúng ta sẽ tìm thấy anh ấy.",
  "Let's be honest, if you don't take us in, we're pretty much fucked.": "Thành thật mà nói, nếu các người không thu nhận chúng tôi, thì chúng tôi coi như ăn cứt.",
  "I need some time to think about this. I'm going out.": "Tôi cần chút thời gian suy nghĩ về chuyện này. Tôi đi ra ngoài đây.",
  "Combat Score": "Điểm Chiến Đấu",
  "Relax, it's just a little food poisoning.": "Thư giãn đi, chỉ là ngộ độc thực phẩm nhẹ thôi.",
  "What, did I stutter? Let's do this.": "Gì chứ, tôi có nói lắp đâu? Làm tới đi.",
  "Zombies are pretty thick on the ground right now. Could be trouble down the road.": "Lũ zombie đang tập trung khá đông dưới kia. Có thể sẽ có rắc rối trên đường đấy.",
  "Shit, you really got some issues!": "Mẹ kiếp, đầu óc mày thực sự có vấn đề rồi đấy!",
  "We don't have enough food for everyone.": "Chúng ta không có đủ thức ăn cho tất cả mọi người.",
  "Let's get these bastards!": "Cùng tóm cổ lũ khốn này nào!",
  "Low Morale puts your community at greater risk of depression, violence, and despair.": "Tinh thần thấp sẽ khiến cộng đồng của bạn có nguy cơ cao rơi vào trầm cảm, bạo lực và tuyệt vọng.",
  "Family Meals": "Bữa Ăn Gia Đình",
  "Nice fighting back there.": "Màn chiến đấu đẹp mắt đấy.",
  "A military solution to your problems.": "Một giải pháp quân sự cho những vấn đề của bạn.",
  "I hope that medivac is inbound, because it's our only way out.": "Tôi hy vọng chuyến trực thăng y tế đang đến, bởi vì đó là lối thoát duy nhất của chúng ta.",
  "Escort the Survivors": "Hộ Tống Người Sống Sót",
  "But I think I want to find out.": "Nhưng tôi nghĩ tôi muốn tìm hiểu chuyện gì đã xảy ra."
};

const file = 'output/languages/chunks/btxt_chunk_111.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_111.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk111[r.sourceText]) {
    r.translatedText = chunk111[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 111 successfully!');
