const fs = require('fs');
const chunk120 = {
  "This car's gonna get us too much attention.": "Chiếc xe này sẽ gây quá nhiều sự chú ý cho chúng ta.",
  "Glad you came by--I was trying to get to this place with good salvage, but I ran into a whole bunch of zeds.": "Rất vui vì cậu đã ghé qua--Tôi đang cố đến nơi này để thu thập phế liệu, nhưng lại chạm trán một đống zed.",
  "That is not good.": "Thế là không ổn rồi.",
  "Surveying": "Trinh Sát (Surveying)",
  "Slow attack that automatically decapitates a single target.": "Đòn tấn công chậm, tự động chặt đầu một mục tiêu đơn lẻ.",
  "Let's go find our missing person, shall we?": "Chúng ta đi tìm người mất tích thôi, được chứ?",
  "Assault Rifle: 416 CQB": "Súng trường tấn công: 416 CQB",
  "Young": "Young",
  "Game Over, Man!": "Trò Chơi Kết Thúc Rồi, Anh Bạn!",
  "Pretty smug right about now.": "Bây giờ đang khá tự mãn đấy.",
  "Pistol: Mi.Le": "Súng lục: Mi.Le",
  "Load Rucksack (Hold)": "Chất Ba lô lên xe (Giữ)",
  "Sorry I asked....": "Xin lỗi vì tôi đã hỏi....",
  "Woodrow": "Woodrow",
  "SMG: CLEO PDW": "Súng tiểu liên: CLEO PDW",
  "I was hoping you'd say that. Come on, I'll show you what we need.": "Tôi đã hy vọng cậu sẽ nói thế. Thôi nào, tôi sẽ cho cậu thấy những gì chúng ta cần.",
  "Prison Ink": "Hình Xăm Nhà Tù",
  "DANGER: Food Shortage": "NGUY HIỂM: Thiếu Hụt Thức Ăn",
  "BUILT: Outpost": "ĐÃ XÂY: Tiền Đồn (Outpost)",
  "So now what?": "Vậy giờ sao?",
  "Juggernauts! Extra Juggernauts. Lethal Juggernauts (grabs kill, regardless of health). Small extra damage. No map indicators.": "Juggernauts! Thêm Juggernauts. Juggernauts Chí Mạng (tóm là chết, bất chấp máu). Thêm một chút sát thương. Không có chỉ báo trên bản đồ.",
  "Exploration": "Khám Phá",
  "Privacy Screens": "Màn Che Riêng Tư",
  "Community Morale is Good": "Tinh thần của Cộng đồng đang Tốt",
  "Not zombies--they've got guns. They- <Gunshots>": "Không phải zombies--chúng có súng. Chúng- <Tiếng súng>",
  "We're doomed.": "Chúng ta tiêu đời rồi.",
  "You're with the Army! Do you have a way out of here?": "Các anh đi cùng Quân đội! Các anh có cách nào ra khỏi đây không?",
  "Kill 50 Zombies with Assault Rifles. (Breakdown Level 4 or Higher)": "Tiêu diệt 50 con Zombie bằng Súng trường tấn công. (Cấp độ Breakdown 4 trở lên)",
  "MISSION: Trouble at the Courthouse": "NHIỆM VỤ: Rắc rối tại Tòa án",
  ".45 caliber": "Cỡ nòng .45",
  "You seen what's left of our meds? It's not lookin' good.": "Cậu thấy những gì còn lại của kho thuốc chưa? Tình hình không khả quan lắm đâu.",
  "Search for the source of the signal.": "Tìm kiếm nguồn phát của tín hiệu.",
  "New report from our scouts.": "Báo cáo mới từ các trinh sát của chúng ta.",
  "26 GENERIC Frank Johnson": "26 GENERIC Frank Johnson",
  "Weiss": "Weiss",
  "Solar upgrade available for Generator": "Có thể nâng cấp Năng lượng Mặt trời (Solar) cho Máy Phát Điện (Generator)",
  "%s Fully Searched": "%s Đã Lục Soát Hoàn Toàn",
  "Just takin' out a few zeds.": "Chỉ là giải quyết vài con zed thôi.",
  "Cardio": "Thể Lực (Cardio)",
  "Trowel": "Cái Bay",
  "There a good kitchen here. Just need to clear out all the chaos and we can start using it.": "Ở đây có một nhà bếp tốt. Chỉ cần dọn dẹp mớ hỗn độn này và chúng ta có thể bắt đầu sử dụng nó.",
  "Population": "Dân Số",
  "Graphics - Min Spec": "Đồ họa - Cấu hình tối thiểu",
  "We're lucky we aren't dead already--and we owe a lot of that to you. Any chance you'd have some space for us?": "Chúng tôi thật may mắn vì chưa chết--và chúng tôi nợ cậu rất nhiều vì điều đó. Liệu cậu có chỗ nào cho chúng tôi không?",
  "Let's get going.": "Chúng ta đi thôi.",
  "What did you take?": "Cậu đã lấy cái gì?",
  "I mean it. We gotta stick together, right? Alone I would have been vulnerable--we need people to watch our backs.": "Tôi nói thật đấy. Chúng ta phải gắn kết với nhau, đúng không? Một mình tôi sẽ rất dễ bị tổn thương--chúng ta cần người bảo vệ sau lưng.",
  "You're straying from the righteous path, my child.": "Con đang đi chệch khỏi con đường chính đạo rồi, con của ta.",
  "39 GENERIC Martin Tarney": "39 GENERIC Martin Tarney",
  "Show you when I get there.": "Sẽ cho cậu thấy khi tôi đến đó.",
  "Parker": "Parker",
  "Hope you brought something worthwhile.": "Hy vọng là cậu mang đến thứ gì đó đáng giá.",
  "Doctor Horn may still be alive.": "Tiến sĩ Horn có thể vẫn còn sống.",
  "Okay, but I ain't waitin' forever.": "Được thôi, nhưng tôi đéo đợi mãi đâu.",
  "Survive 2 minutes within a Danger Zone.": "Sống sót 2 phút trong Khu Vực Nguy Hiểm (Danger Zone).",
  "We got issues on the left side!": "Chúng ta có vấn đề ở bên trái kìa!",
  "Our people are getting chewed up out there.": "Người của chúng ta đang bị xé xác ngoài kia kìa.",
  "Spotted something interesting. Should be some useful stuff there.": "Phát hiện một thứ thú vị. Chắc là có vài món đồ hữu ích ở đó.",
  "[message looping tone] One one tango lima-": "[tiếng bíp vòng lặp tin nhắn] Một một tango lima-",
  "You need to watch your stamina.": "Cậu cần phải chú ý đến Thể lực (stamina) của mình.",
  "Hill": "Hill",
  "Need an escort.": "Cần một người hộ tống.",
  "We don't have enough weapons for everybody.": "Chúng ta không có đủ vũ khí cho tất cả mọi người.",
  "I'll lead the way.": "Tôi sẽ dẫn đường.",
  "If there's people down there, they might need help.": "Nếu có người ở dưới đó, họ có thể cần sự giúp đỡ.",
  "Killing Blow Chance Increased!": "Tỷ Lệ Đòn Kết Liễu Đã Tăng!",
  "If Doc hadn't been in the neighborhood... well. I've told him and told him, \"Don't you go out alone.\"": "Nếu Bác sĩ (Doc) không ở quanh đây... chà. Tôi đã bảo đi bảo lại rồi, \"Ông đừng có ra ngoài một mình.\"",
  "We've located some medical personnel stranded just outside the city.": "Chúng tôi đã định vị được một số nhân viên y tế đang mắc kẹt ngay bên ngoài thành phố.",
  "Gotta love sneaking up on the bastards.": "Đúng là rất khoái cái trò lẻn ra sau mấy thằng khốn đó.",
  "Might want to check here.": "Có lẽ nên kiểm tra chỗ này.",
  "Attention survivors Only those who abide by the laws posted outside the courthouse are eligible for the protection of the Sheriff's Department.": "Chú ý hỡi những người sống sót Chỉ những ai tuân thủ các luật lệ được dán bên ngoài tòa án mới đủ điều kiện được bảo vệ bởi Sở Cảnh sát.",
  "You've been effective enough that I'm allocating some assets to back you up.": "Cậu đã làm việc đủ hiệu quả nên tôi sẽ phân bổ vài nguồn lực để yểm trợ cho cậu.",
  "In times like these, I often take comfort in those around me.": "Vào những lúc như thế này, tôi thường tìm sự an ủi từ những người xung quanh mình.",
  "Done and done.": "Xong xuôi hết rồi.",
  "%+d Community Fame (Savior)": "%+d Danh Tiếng Cộng Đồng (Vị Cứu Tinh)",
  "Pistol: P 229": "Súng lục: P 229",
  "I don't know what your problem is, and I don't care. But you're making it everybody's problem, and that's not okay.": "Tôi không biết vấn đề của cậu là gì, và tôi cũng cóc quan tâm. Nhưng cậu đang biến nó thành vấn đề của mọi người, và chuyện đó đéo ổn chút nào.",
  "I don't know. I guess we just head to town, try to find... somebody.": "Tôi không biết. Tôi đoán chúng ta cứ tiến vào thị trấn, cố gắng tìm... ai đó.",
  "Great news! This last crop came up even better than we hoped!": "Tin tuyệt vời đây! Vụ mùa vừa rồi thu hoạch còn tốt hơn cả chúng ta mong đợi!",
  "So how about we argue call signs later, after you fucking come out here and reinforce my ass!": "Thế để tranh cãi về danh hiệu sau đi, sau khi anh đéo mẹ nó vác xác ra đây và yểm trợ cho tôi!",
  "60 REF Charley Marshall": "60 REF Charley Marshall",
  "Lights": "Đèn",
  "Major ...": "Thiếu tá ...",
  "It's all so wrong. I don't know if it's the lying or the whoring that bothers me more. - %1$s": "Tất cả đều sai trái. Tôi không biết là việc nói dối hay trò lăng nhăng đó làm tôi khó chịu hơn nữa. - %1$s",
  "We need good people. If you want, you can crash with us.": "Chúng tôi cần những người tốt. Nếu muốn, cậu có thể tá túc cùng chúng tôi.",
  "Claims to have things under control.": "Tuyên bố là đã kiểm soát được tình hình.",
  "Wonderful, now we have a real food problem.": "Tuyệt vời, giờ thì chúng ta có một vấn đề thực sự về thức ăn.",
  "Javier": "Javier",
  "Scavenger?": "Đi nhặt mót (Scavenger) hả?",
  "(Can't work.)": "(Không thể làm việc.)",
  "Move Left": "Di Chuyển Sang Trái",
  "Search nearby areas to obtain resources to resupply your base. That ammo won't last forever!": "Tìm kiếm khu vực xung quanh để thu thập tài nguyên và tiếp tế cho căn cứ của bạn. Đống đạn đó không dùng được mãi đâu!",
  "Spotted a Juggernaut on its way toward us. We were able to use explosives to take it out. - %1$s.": "Phát hiện một con Juggernaut đang hướng về phía chúng ta. Chúng tôi đã dùng thuốc nổ để hạ gục nó. - %1$s.",
  "He was alive when you found him?": "Ông ấy vẫn còn sống khi cậu tìm thấy ông ấy à?",
  "We're gonna have to tear down all of this and rebuild it. Unless you want the place to fall down around our ears.": "Chúng ta sẽ phải phá bỏ toàn bộ thứ này và xây lại. Trừ phi cậu muốn nơi này sập xuống ngay trên đầu chúng ta.",
  "Morgan": "Morgan",
  "SET UP: Warehouse Lockers": "THIẾT LẬP: Tủ Đồ Nhà Kho",
  "How you holding up, Carl?": "Anh chống chọi sao rồi, Carl?",
  "Cool. That'll go a long way toward securing the area.": "Tuyệt. Chuyện đó sẽ giúp ích rất nhiều trong việc đảm bảo an toàn cho khu vực này.",
  "NOTE: Still Searching": "GHI CHÚ: Vẫn Đang Lục Soát"
};

const file = 'output/languages/chunks/btxt_chunk_120.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_120.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk120[r.sourceText]) {
    r.translatedText = chunk120[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 120 successfully!');
