const fs = require('fs');
const chunk205 = {
  "33 GENERIC Robert Albin": "33 CHUNG (GENERIC) Robert Albin",
  "Things look okay now, but don't worry, we're still fucked.": "Hiện tại thì mọi chuyện có vẻ như vẫn đang hoàn toàn ổn (okay), thế nhưng cậu đéo cần phải lo lắng (don't worry) đéo đâu, vì tất cả chúng ta chắc chắn vẫn sẽ đều bị ăn cứt (fucked) mà thôi.",
  "If I'm going to keep doing this, I'm going to need some more ammo.": "Nếu như tôi vẫn còn muốn có thể tiếp tục thực hiện cái công việc chết tiệt (keep doing this) này, thì chắc chắn tôi sẽ cần phải có thêm được một lượng lớn đạn dược (ammo) nữa.",
  "Olive Oil": "Dầu Ô Liu (Olive Oil)",
  "Ask me, it's about time to start making our own laws....": "Nếu như cậu muốn hỏi ý kiến (Ask me) của tôi, thì có lẽ hiện tại đã đến lúc chúng ta cần phải bắt đầu (start) tự tạo ra cho riêng mình những thứ luật lệ (laws) mới rồi đấy....",
  "%1$s never did take down that freak.... - Lily": "%1$s chưa từng bao giờ (never) có thể thực sự hạ gục (take down) thành công cái con quái vật gớm ghiếc (freak) đó cả.... - Lily",
  "Grants immunity to foul odors.": "Ban cho (Grants) một khả năng miễn nhiễm (immunity) hoàn toàn với mọi thứ mùi hôi thối kinh tởm (foul odors).",
  "That's some nice work, people.": "Đó thực sự là một màn trình diễn (work) cực kỳ tuyệt vời (nice) đấy, mọi người ạ.",
  "Requires KEG STAND.": "Yêu cầu (Requires) cần phải có KỸ NĂNG ĐỨNG UỐNG RƯỢU BẰNG HAI TAY (KEG STAND).",
  "Just lucky, I guess. It was pretty chaotic up at the lake.": "Chỉ là do may mắn (lucky) mà thôi, tôi đoán là như vậy. Bầu không khí ở khu vực trên hồ (up at the lake) lúc nãy thực sự cực kỳ hỗn loạn (chaotic).",
  "A typical Army field barracks, rich with that memorable FAN aroma.": "Một khu nhà doanh trại dã chiến (field barracks) vô cùng đặc trưng (typical) của Quân Đội (Army), có mùi hương thoang thoảng nồng nặc cái thứ mùi hôi thối kinh tởm vô cùng đáng nhớ (memorable) của bọn FAN.",
  "What the hell do you expect, with all the goddamn infestations out there?": "Cậu còn đang mong đợi (expect) cái đéo gì nữa đây hả, với toàn bộ tất cả mọi cái ổ dịch (infestations) khốn khiếp chết tiệt (goddamn) hiện đang tràn ngập ở ngoài kia cơ chứ?",
  "Off the Wagon": "Đã Bắt Đầu Uống Rượu Lại Đéo Kiểm Soát Được Nữa Rồi (Off the Wagon)",
  "Hey, c'mon! Anybody hungry?": "Này, thôi nào (c'mon)! Có bất cứ ai hiện đang cảm thấy đói bụng (hungry) đéo?",
  "PERSONAL SKILL. Just don't ask me to help you move furniture, okay?": "KỸ NĂNG CÁ NHÂN (PERSONAL SKILL). Chỉ là xin đừng bao giờ nhờ vả (ask) tôi đến để giúp đỡ cho cậu khuân vác di chuyển (move) đống đồ đạc nội thất (furniture) chết tiệt của cậu đi là được, okay?",
  "DECLINE MISSION. Skip out this.": "TỪ CHỐI (DECLINE) LÀM NHIỆM VỤ (MISSION). Bỏ qua hoàn toàn (Skip out) nhiệm vụ này.",
  "Help them out before it's too late.": "Hãy nhanh chóng đến để giúp đỡ (Help) cho bọn họ đi trước khi (before) mọi thứ trở nên quá đỗi muộn màng (too late).",
  "Let's go track 'em down.": "Chúng ta hãy cùng nhau đi truy lùng (track 'em down) bọn chúng thôi nào.",
  "Moving on will reset your Challenge progress. You're REALLY starting over. Are you sure you want to leave now?": "Việc Lựa Chọn Tiếp Tục Tiến Lên Phía Trước (Moving on) sẽ trực tiếp thiết lập lại (reset) toàn bộ các thanh tiến trình Thử Thách (Challenge progress) của bạn. Bạn sẽ THỰC SỰ (REALLY) phải tiến hành bắt đầu lại mọi thứ ngay từ con số đéo (starting over). Bạn có thực sự chắc chắn (sure) rằng bản thân mình đang muốn rời đi (leave) ngay bây giờ hay đéo?",
  "Well, nothing better break any time soon. You seen the state of our material stocks?": "Chà, tốt nhất là đéo nên có bất cứ một cái thứ đéo gì có thể dễ dàng bị phá hủy đổ vỡ (break) trong bất kỳ một khoảng thời gian sớm (any time soon) nào. Cậu đã tự mình chứng kiến được cái tình trạng hiện tại (state) của toàn bộ các kho dự trữ nguyên vật liệu (material stocks) của chúng ta rồi đéo?",
  "Recon is telling us that our high-value asset is dead, and the mission to rescue them is scrapped. Hopefully, the brass will be forgiving, and will give us another chance.": "Lực lượng Trinh Sát (Recon) hiện đang báo cáo lại với chúng tôi rằng toàn bộ khối tài sản sở hữu trị giá vô cùng to lớn (high-value asset) của chúng ta hiện đã hoàn toàn bị phá hủy (dead), và cái nhiệm vụ (mission) được tiến hành tổ chức nhằm mục đích đi giải cứu (rescue) cho bọn họ cũng đã hoàn toàn bị hủy bỏ (scrapped) cmnr. Rất hy vọng (Hopefully) rằng, đám quan chức cấp cao (brass) sẽ chịu bỏ qua (forgiving) cho cái sự việc tồi tệ này, và sẽ cho chúng ta thêm được một cơ hội khác (another chance).",
  "MISSION SCRAPPED: Nervous Survivor": "NHIỆM VỤ ĐÃ BỊ HỦY BỎ (MISSION SCRAPPED): Một Người Sống Sót (Survivor) Nào Đó Đang Cảm Thấy Vô Cùng Căng Thẳng (Nervous)",
  "Hey.": "Này (Hey).",
  "Ask around about an area that has FUEL.": "Dò hỏi (Ask around) khắp mọi nơi xung quanh để có thể tìm kiếm được một khu vực (area) đang có dự trữ rất nhiều NHIÊN LIỆU (FUEL).",
  "Can't fit a suppressor on this gun.": "Tuyệt đối đéo thể nào (Can't) có thể lắp đặt vừa vặn (fit) được một cái ống giảm thanh (suppressor) vào cái khẩu súng này đéo đâu.",
  "I've got some really bad news about %1$s and that last attack... - Lily": "Tôi hiện đang có một vài tin tức (news) vô cùng tồi tệ (bad) nói về %1$s và cả cái cuộc tấn công đẫm máu cuối cùng đó (last attack)... - Lily",
  "Might have even shot somebody, I'm not sure.": "Có thể là đã nổ súng bắn trúng (shot) phải một người đéo nào đó (somebody), tôi cũng đéo dám chắc chắn (not sure) lắm.",
  "COMPLETED: Lone Soldier": "ĐÃ HOÀN THÀNH (COMPLETED): Người Lính (Soldier) Hoàn Toàn Cô Độc (Lone)",
  "%+d Trust.": "%+d Sự Tin Tưởng (Trust).",
  "Jackass.": "Đồ Ngu Ngốc Nửa Mùa (Jackass).",
  "Hey, you feeling patriotic? We could use your eyes to help us clear out some zeds.": "Này, cậu có đang cảm thấy được một chút tinh thần yêu nước nồng nàn (patriotic) nào đéo? Chúng tôi hiện đang rất cần phải được sử dụng đôi mắt (eyes) của cậu để có thể hỗ trợ (help) cho chúng tôi trong việc càn quét dọn dẹp sạch sẽ (clear out) một vài con zeds.",
  "Her parents hated her boyfriend... until the zombies got them.": "Bố mẹ (parents) của cô ấy vốn dĩ luôn cực kỳ căm ghét (hated) gã bạn trai (boyfriend) của cô ấy... mãi cho đến khi (until) bọn zombies chạy đến và xé xác nhai nuốt (got them) toàn bộ bọn họ.",
  "Powerful gun, made legendary in the movies.": "Một khẩu súng vô cùng mạnh mẽ (Powerful gun), đã từng làm nên rất nhiều tên tuổi huyền thoại (legendary) ở trên những bộ phim truyền hình (movies).",
  "Yo, c'mon, a little ay-you-da-may here!": "Yo, thôi nào (c'mon), cần phải có thêm một chút ay-you-da-may ở ngay chỗ này nữa!",
  "You have your orders. Highroad out.": "Cậu hiện tại đã nhận được các mệnh lệnh (orders) của mình rồi đấy. Căn cứ Highroad kết thúc truyền tin (out).",
  "A dirty rotten scoundrel.": "Một tên cặn bã (scoundrel) cực kỳ thối nát (rotten) và vô cùng bẩn thỉu (dirty).",
  "Smoked Oysters": "Món Hàu Hun Khói (Smoked Oysters)",
  "Just a reminder that the Wild West doesn't last forever.": "Chỉ là một lời nhắc nhở (reminder) nhỏ dành cho mọi người rằng cái kỷ nguyên Miền Tây Hoang Dã (Wild West) chết tiệt này sẽ đéo bao giờ có thể tồn tại được mãi mãi (forever) đâu.",
  "That's great news!": "Đó thực sự là một cái tin tức (news) vô cùng tuyệt vời (great) đấy!",
  "Good point.": "Đó quả thực là một quan điểm cực kỳ xuất sắc (Good point).",
  "I encountered a new group of survivors. They're worried. Aren't we all, though? - %1$s": "Tôi vừa mới tình cờ đụng độ (encountered) phải một nhóm người sống sót (survivors) hoàn toàn mới. Bọn họ hiện đang tỏ ra cực kỳ lo lắng (worried). Thế nhưng, chẳng lẽ tất cả chúng ta lại đéo giống như vậy ư? - %1$s",
  "Kirk": "Kirk",
  "It's a car. It's for me?": "Đó là một chiếc xe hơi (car). Nó được dành cho tôi ư?",
  "OPPORTUNITY: Biodiesel": "CƠ HỘI BẤT NGỜ (OPPORTUNITY): Dầu Diesel Sinh Học (Biodiesel)",
  "Madilyn": "Madilyn",
  "Aw, don't let it get you down, champ.": "Aw, đừng bao giờ để cho cái thứ đó có thể dễ dàng đánh gục (get you down) được cậu nhé, anh bạn nhà vô địch (champ).",
  "Eye Protection": "Kính Bảo Vệ Mắt (Eye Protection)",
  "TIP: Once you fully SEARCH this building, you can set up an OUTPOST here.": "MẸO (TIP): Ngay sau khi bạn đã hoàn thành việc TÌM KIẾM (SEARCH) toàn bộ tất cả mọi thứ có ở bên trong khu vực tòa nhà (building) này, bạn sẽ hoàn toàn có thể thiết lập (set up) nên được một cái TIỀN ĐỒN (OUTPOST) ở ngay tại đây.",
  "You want me to carry WHAT? (Doesn't handle encumbrance well.)": "Cậu đang muốn tôi phải mang vác (carry) cái THỨ CHẾT TIỆT (WHAT) gì cơ chứ? (Đéo thể nào có thể tự mình xử lý giải quyết handle được tình trạng mang vác quá nặng encumbrance một cách tốt nhất well.)",
  "We've detected a transferred save from the original State of Decay.": "Hệ thống của chúng tôi vừa mới tiến hành phát hiện (detected) ra được một bản lưu trữ dữ liệu save đã được chuyển sang (transferred) từ phiên bản tựa game State of Decay bản gốc (original).",
  "A lot of Doctor Horn's funding seems to have come from a little NGO called the Human Future Fund.": "Có vẻ như phần lớn (A lot of) những nguồn tài trợ ngân sách (funding) của Tiến Sĩ Horn đều được xuất phát (come from) từ một tổ chức phi chính phủ NGO quy mô cực kỳ nhỏ nhặt bé xíu có tên gọi là cái Quỹ Tài Trợ Tương Lai Của Nhân Loại (Human Future Fund).",
  "Lost %1$s. Might be able to find them again, though.": "Vừa mới bị lạc mất (Lost) %1$s cmnr. Thế nhưng, có lẽ là chúng ta vẫn sẽ có thể may mắn tìm thấy lại (find them again) được bọn họ đấy.",
  "Check it out. Building supplies.": "Hãy xem thử (Check it out) cái thứ này đi. Các loại vật tư vật liệu dùng để xây dựng công trình (Building supplies).",
  "Brought in some supplies with %1$s.": "Đã mang (Brought) về được một lượng lớn hàng hóa tiếp tế (supplies) cùng với %1$s.",
  "A young woman showed up at our gate today with a rucksack full of supplies. She said she was here to help, so we welcomed her in. It's not easy to trust people these days, but she has an honest face, and what seems to be a genuine desire to do good.": "Ngày hôm nay đã có một người phụ nữ trẻ tuổi xuất hiện (showed up) ở ngay trước cổng căn cứ (gate) của chúng tôi mang theo một cái rucksack nhét đầy ắp các loại vật tư hàng hóa tiếp tế (supplies). Cô ấy nói rằng cô ấy đến đây là để giúp đỡ (help), vì vậy nên chúng tôi đã vui vẻ chào đón (welcomed) cô ấy vào trong nhà. Ở trong những cái ngày tháng tồi tệ thảm khốc (these days) như hiện tại, cái việc dễ dàng đặt niềm tin (trust) vào người khác hoàn toàn đéo phải là một cái điều dễ dàng (easy) đéo nào, thế nhưng cô ấy thực sự có một khuôn mặt cực kỳ trung thực (honest), và dường như là có một mong muốn khát khao (desire) cực kỳ chân thành (genuine) để có thể làm được một vài điều gì đó tốt đẹp (good).",
  "Vegan": "Người Ăn Chay Trường (Vegan)",
  "That's good news. We'd've been pretty fucked out here on our own.": "Đó quả thực là một tin tức vô cùng tốt lành (good news) đấy. Nếu đéo thì chúngáng chắc chắn sẽ bị ăn một đống những trận đòn tơi tả nát bét thối tha (pretty fucked) ở ngoài này khi chỉ có một thân một mình (on our own) đấy.",
  "+20% Recovery Chance. REQUIRES TRAINED HEALER.": "+20% Tỷ Lệ (Chance) Hồi Phục Bình Phục (Recovery). YÊU CẦU CẦN PHẢI SỞ HỮU MỘT NGƯỜI LÀM NGHỀ CHỮA BỆNH (HEALER) ĐÃ ĐƯỢC ĐÀO TẠO QUA TRƯỜNG LỚP BÀI BẢN CHUYÊN NGHIỆP (TRAINED).",
  "We'll hold out as long as we can, but if we're not making a difference, we're bugging out.": "Chúng tôi chắc chắn sẽ cố gắng chống cự bám trụ (hold out) lâu nhất ở trong cái khả năng mà chúng tôi có thể (can), nhưng nếu như chúng tôi đéo thể nào tạo ra (making) được một sự thay đổi khác biệt (difference) đéo nào cả, thì chúng tôi sẽ tự động rút lui bỏ chạy đi khỏi (bugging out) đây.",
  "A workshop will let us build the stuff that we can't requisition, and maintain the stuff that we can.": "Một khu vực xưởng làm việc (workshop) sẽ giúp cho chúng ta có thể tự mình tiến hành xây dựng và chế tạo (build) ra được những món vật phẩm mà chúng ta đéo thể nào có thể tự tiện tiến hành trưng dụng (requisition) được, và đồng thời cũng có thể bảo trì bảo dưỡng (maintain) được những món vật phẩm mà chúng ta hoàn toàn có khả năng.",
  "Let's move!": "Hãy mau di chuyển (move) thôi nào!",
  "The Grange survivors are kinda pissed.": "Cái nhóm người sống sót (survivors) ở khu vực The Grange hiện tại đang cảm thấy có đôi chút vô cùng tức giận (pissed) đấy.",
  "Carr": "Carr",
  "Repair (Hold)": "Tiến Hành Sửa Chữa (Repair) (Nhấn và Giữ phím)",
  "Private Vincent had a good idea. We may have lost contact with Doghouse, along with our air and artillery support ... but there's no reason we can't set up our own additional assets by capturing them in the field.": "Binh Nhì Vincent vừa mới nảy ra được một ý tưởng (idea) cực kỳ xuất sắc. Chúng ta hiện tại có thể đã hoàn toàn đánh mất đi sự liên lạc (lost contact) với căn cứ Doghouse, cùng với đó là toàn bộ tất cả sự hỗ trợ chi viện từ trên không (air) cũng như là pháo binh (artillery support)... nhưng hoàn toàn đéo hề có bất kỳ một lý do (reason) nào để biện minh cho cái việc rằng chúng ta lại đéo thể tự mình tiến hành thiết lập (set up) nên được những cơ sở tài sản (assets) bổ sung (additional) của riêng chúng ta bằng cách tự đi chiếm đóng (capturing) lấy toàn bộ bọn chúng ở ngoài thực địa (field).",
  "Eyes up!": "Hãy mau mở to đôi mắt (Eyes up) của cậu ra đi kìa!",
  "Yeah. I'm peachy.": "Yeah. Tình trạng của tôi hiện đang vô cùng tuyệt vời và vô cùng hoàn hảo (peachy).",
  "Freak Hunt": "Đi Săn Lùng (Hunt) Những Con Quái Vật Gớm Ghiếc (Freak)",
  "Say again, Black Friday. You're sending Shira Bogatz?": "Nói lại lần nữa (Say again) xem nào, căn cứ Black Friday. Các người hiện đang cử (sending) Shira Bogatz đến chỗ này đéo đấy hả?",
  "The standard U.S. military rifle.": "Mẫu súng trường (rifle) chuyên dụng tiêu chuẩn (standard) của Quân Đội Hoa Kỳ (U.S. military).",
  "Let's run the bastards over.": "Chúng ta hãy mau lái xe cán nát bét (run over) cái đám khốn nạn (bastards) này thôi nào.",
  "Different people have different skills.": "Mỗi một con người khác nhau (Different) sẽ đều có những bộ kỹ năng (skills) hoàn toàn riêng biệt khác nhau.",
  "Oh, shit, she's coming over here. Act natural.": "Oh, chết tiệt thật (shit), cô ấy hiện đang tiến về phía này (coming over) kìa. Hãy cố gắng tỏ ra tự nhiên (Act natural) nhất có thể nhé.",
  "Hannah": "Hannah",
  "Paper Cutter Arm": "Phần Lưỡi Dao Cắt (Arm) Lấy Ra Từ Một Chiếc Máy Xén Cắt Giấy (Paper Cutter)",
  "I'm running low on ammo! Anybody wanna help me out?": "Tôi hiện tại đã gần như cạn kiệt (running low) toàn bộ số lượng đạn dược (ammo) mất rồi! Có bất cứ ai (Anybody) muốn đến để giúp đỡ (help) cho tôi một tay đéo?",
  "Yeah, that's right. You fuckfaces love the sound of cars, don't you?": "Yeah, hoàn toàn chính xác đấy (that's right). Cái đám mang khuôn mặt như cái lồn chó khốn khiếp chết tiệt (fuckfaces) nhà chúng mày cực kỳ yêu thích (love) tiếng ồn phát ra từ những chiếc xe hơi (cars), có đúng đéo?",
  "So many zombies in the area, I don't think circling around's any better.": "Đang có quá nhiều zombies xuất hiện ở trong cái khu vực này, tôi đéo nghĩ (don't think) rằng cái việc cứ liên tục đi chạy vòng quanh (circling around) thì sẽ giúp cho mọi việc có thể trở nên khá khẩm hơn (better) được một chút đéo nào đâu.",
  "This should help keep us going.": "Thứ này chắc chắn sẽ có thể giúp (help) duy trì cho sự sống sót (going) của chúng ta.",
  "Any combat sounds draw attention, but gunfire is extremely loud. Use caution when firing a gun without a suppressor.": "Bất kỳ một âm thanh (sounds) phát ra trong quá trình chiến đấu (combat) đéo nào cũng đều sẽ rất dễ dàng thu hút được sự chú ý (draw attention) của lũ quái vật, thế nhưng riêng đối với tiếng súng nổ (gunfire) thì nó lại cực kỳ to (loud) và vô cùng vang dội. Hãy luôn thật sự cẩn trọng (Use caution) mỗi khi bạn muốn tiến hành nổ súng (firing) một khẩu súng đéo được trang bị bất kỳ một loại ống giảm thanh (suppressor) nào.",
  "All right! Diplomacy's over, motherfuckers!": "Được rồi (All right)! Trò chơi ngoại giao (Diplomacy) kết thúc (over) cmnr, hỡi những thằng khốn nạn chó đẻ (motherfuckers)!",
  "I think we've got a fight on our hands.": "Tôi đang nghĩ rằng chúng ta sắp sửa (we've got) phải đối mặt với một trận chiến sống còn vô cùng ác liệt (fight) đấy.",
  "Ever notice how the people who suck the most at doing shit also have zero sense of humor? I mean, damn, if you're not a good shot, you could at least try to be good company. -%1$s.": "Cậu đã bao giờ từng thử chú ý (notice) đến cái việc rằng có một vài những kẻ luôn tỏ ra cực kỳ ngu dốt và tồi tệ (suck) nhất ở trong việc làm ra những cái thứ cứt đái chết tiệt (shit) đồng thời cũng là những kẻ đéo có một chút xíu (zero) khiếu hài hước (sense of humor) đéo nào đéo? Ý của tôi là, mẹ kiếp (damn), nếu như cậu vốn dĩ đéo phải là một tay súng bắn tỉa cự phách cừ khôi xuất sắc (good shot), thì ít ra cậu cũng nên cố gắng (try) trở thành một người bạn đồng hành thực sự tốt bụng (good company) đéo được sao. -%1$s.",
  "VIP: Dr. Thomas Horn, PhD": "NHÂN VẬT QUAN TRỌNG (VIP): Tiến Sĩ Thomas Horn, PhD",
  "We'd need someplace a little bigger.": "Chúng ta chắc chắn sẽ rất cần phải có được một cái nơi đéo nào đó (someplace) có kích thước rộng lớn hơn (bigger) một chút đéo.",
  "Yup, we're building here.": "Yup, chúng ta hiện đang tiến hành xây dựng (building) ở ngay tại đây.",
  "Hurry up, zeds are inbound.": "Hãy mau nhanh lên (Hurry up) nào, lũ zeds hiện đang ập tới (inbound) rồi đấy.",
  "MADISON GRANT": "MADISON GRANT",
  "I appreciate you coming to get me, but I really need to find this. Come with me while I look for it?": "Tôi thực sự vô cùng cảm kích (appreciate) trước cái việc mà cậu đã lặn lội chạy đến đây để giải cứu (get me) cho tôi, nhưng tôi hiện đang rất cần phải đi tìm lại (find) cái món đồ này. Hãy đi cùng (Come with) với tôi trong lúc mà tôi đang cố gắng đi tìm kiếm (look for) nó nhé?",
  "I don't know. I... I need some time to think about things. I'm gonna go out for a while, okay?": "Tôi hoàn toàn đéo biết (don't know) nữa. Tôi... Tôi hiện tại chỉ cần có thêm một chút thời gian (time) để có thể suy nghĩ (think) thông suốt lại mọi chuyện (things). Tôi sẽ đi ra ngoài (go out) dạo bộ một lát đéo, okay?",
  "I think he grew up somewhere around here, he might have holed up in one of those buildings.": "Tôi nghĩ rằng anh ấy đã từng lớn lên (grew up) ở một cái khu vực đéo nào đó loanh quanh ở quanh đây (around here), anh ấy rất có thể (might) hiện tại đang lẩn trốn (holed up) ở bên trong một trong số những cái tòa nhà (buildings) đó.",
  "Can't think of one distinctive thing about this guy.": "Hoàn toàn đéo thể nào (Can't) có thể nghĩ ra (think) được một đặc điểm nhận dạng đặc trưng nổi bật (distinctive thing) đéo nào về cái gã này (this guy) cả.",
  "Yeah, well, just keep your asses clear of Marshall. Way I hear it, the pigs have some kind of base down there, and they ain't handing out traffic tickets, if you know what I mean.": "Yeah, chà, chỉ việc cố gắng bảo vệ (keep) cho cái mông (asses) chết tiệt của cậu tránh xa (clear) khỏi cái khu vực thị trấn Marshall ra là được. Theo như những gì mà tôi đã được nghe ngóng (hear it) lại, cái đám cớm lợn chết tiệt (pigs) dường như đang có một cái căn cứ (base) bí mật đéo nào đó nằm ở ngay phía dưới đó, và chắc chắn là bọn chúng sẽ đéo đời nào chịu nhẹ nhàng đến mức đi phân phát (handing out) những tờ vé phạt vi phạm giao thông (traffic tickets) đéo đâu, nếu như cậu có thể hiểu (know) được những cái gì mà tôi đang muốn ám chỉ.",
  "Apple": "Trái Táo (Apple)",
  "Indy's in trouble": "Indy hiện tại đang gặp phải rắc rối (trouble) lớn cmnr",
  "DANGER: Juggernaut Sighting": "CẢNH BÁO NGUY HIỂM (DANGER): Phát Hiện Sự Xuất Hiện (Sighting) Của Một Con Juggernaut",
  "Who needs a gun? Clubs don't run out of ammo.": "Còn có ai (Who) lại đi cần đến một khẩu súng (gun) nữa cơ chứ? Những cây gậy đánh golf (Clubs) sẽ đéo bao giờ (don't) có thể bị rơi vào tình trạng hết sạch đạn dược (run out of ammo) cả.",
  "This thing's gonna draw zombies like flies to honey.": "Cái thứ này chắc chắn sẽ cực kỳ dễ dàng thu hút (draw) toàn bộ lũ zombies kéo đến giống hệt như lũ ruồi nhặng (flies) bu vào bãi cứt tẩm mật ong (honey) vậy.",
  "Vise": "Một Cái Ê Tô Kẹp Phôi Lớn Bằng Kim Loại (Vise)",
  "Drone Strike Marker": "Pháo Sáng Ra Hiệu Đánh Dấu Cột Khói (Marker) Của Cuộc Không Kích Bằng Máy Bay Không Người Lái (Drone Strike)"
};

const file = 'output/languages/chunks/btxt_chunk_205.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_205.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk205[r.sourceText]) {
    r.translatedText = chunk205[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 205 successfully!');
