const fs = require('fs');
const chunk203 = {
  "I've got stuff scattered all over the place. Give me a second to pull it together?": "Hiện tại tôi đang có một vài món đồ đạc (stuff) bị vương vãi nằm rải rác (scattered) ở khắp mọi nơi. Cho tôi xin một vài giây để có thể thu dọn và tập hợp (pull it together) toàn bộ bọn chúng lại được đéo?",
  "We're gonna lose these barricades if you don't do something!": "Chúng ta chắc chắn sẽ đánh mất đi toàn bộ những cái rào chắn (barricades) này nếu như cậu đéo chịu nhanh chóng làm một thứ đéo gì đó đi!",
  "Creates a few homemade firetraps.": "Chế tạo (Creates) ra một vài cái bẫy lửa tự chế (homemade firetraps).",
  "TIP: Radio home using [ul_radio_menu] to create an OUTPOST here.": "MẸO (TIP): Sử dụng Bộ Đàm (Radio) để liên lạc quay trở về căn cứ (home) bằng cách sử dụng phím [ul_radio_menu] để có thể thiết lập (create) nên một TIỀN ĐỒN (OUTPOST) ở ngay tại khu vực này.",
  "Yeah... I… I guess so.": "Yeah... Tôi... Tôi đoán là như vậy.",
  "Stay out of the Blast Radius": "Hãy Nhanh Chóng Tránh Xa (Stay out) Khỏi Bán Kính (Radius) Của Vụ Nổ Bơm (Blast)",
  "I feel like we just got settled. You sure about this?": "Tôi cảm thấy giống như thể là chúng ta chỉ vừa mới ổn định được chỗ ở (settled) xong. Cậu có thực sự chắc chắn về cái quyết định này đéo vậy?",
  "Bermudez": "Bermudez",
  "The precision of it... I don't think it was some random thug. This looked professional.": "Sự vô cùng chính xác (precision) của nó... Tôi đéo nghĩ rằng nó lại được thực hiện bởi một tên côn đồ (thug) rác rưởi ngẫu nhiên (random) nào đó đéo đâu. Chuyện này trông có vẻ cực kỳ chuyên nghiệp (professional).",
  "Pistol: CLEO Striker 40": "Súng Lục (Pistol): CLEO Striker 40",
  "Ismael": "Ismael",
  "Lights an area up. Good for night-time zombie spotting, or night-time zombie luring.": "Sẽ thắp sáng (Lights up) rực rỡ cho toàn bộ khu vực. Cực kỳ hữu ích trong việc phát hiện (spotting) ra lũ zombie vào ban đêm, hoặc là dùng để đi dụ dỗ (luring) lũ zombie vào ban đêm.",
  "Revolver: SP 101": "Súng Lục Ổ Quay (Revolver): SP 101",
  "Sergeant Eldridge has taken off to who-knows-where. Part of me is like, \"good riddance\" ... but the rest of me wants to know what he's doing out there.": "Trung Sĩ Eldridge vừa mới âm thầm rời đi (taken off) đến một cái nơi đéo nào đó mà đéo một ai biết (who-knows-where) cmnr. Một phần trong tôi thì lại cảm thấy kiểu như là, \"đi luôn cho khuất mắt (good riddance)\"... thế nhưng phần còn lại thì vẫn luôn muốn được biết xem rốt cuộc thì anh ta hiện đang làm cái đéo gì ở ngoài đó cơ chứ.",
  "Ivonne": "Ivonne",
  "Guess we're not the only ones having a bad day.": "Đoán chừng chúng ta đéo phải là những người duy nhất hiện đang phải trải qua một ngày vô cùng tồi tệ (bad day) rồi.",
  "Do what you can.": "Hãy làm tất cả những gì mà cậu có thể (can) làm đi.",
  "Okay, that was too close.": "Okay, vừa rồi thực sự là quá suýt soát nguy hiểm (close) đấy.",
  "Grady": "Grady",
  "Headlights": "Đèn Pha (Headlights) Xe Ô Tô",
  "Naomi": "Naomi",
  "Just call me \"Skullcrusher.\" ... Please?": "Cứ gọi tôi với cái biệt danh là \"Kẻ Nghiền Nát Đầu Lâu (Skullcrusher)\" là được... Được chứ (Please)?",
  "Yeah, but we've got antibiotics.": "Yeah, thế nhưng chúng ta hiện đang có sẵn trong tay thuốc kháng sinh (antibiotics) mà.",
  "The selected storage device does not have enough space": "Thiết bị lưu trữ (storage device) mà bạn vừa mới lựa chọn hiện đéo có đủ khoảng trống (space)",
  "Max Stamina Increased!": "Chỉ Số Thể Lực Tối Đa (Max Stamina) Đã Được Tăng Lên (Increased)!",
  "Search for a vehicle large enough to get you and your closest friends out of the valley.": "Hãy mau chóng đi tìm kiếm (Search) một chiếc phương tiện (vehicle) có kích thước đủ lớn để có thể chở được cậu và cả những người bạn bè thân thiết (closest) nhất của cậu trốn thoát ra khỏi cái khu vực thung lũng (valley) này.",
  "We could use an escort.": "Chúng tôi rất cần phải có được một sự hộ tống bảo vệ (escort).",
  "We'll hear more from him later, I'm sure.": "Chúng ta chắc chắn sẽ được nghe thêm tin tức (hear more) từ anh ấy sau, tôi hoàn toàn dám chắc chắn (sure) về điều đó.",
  "Civilians Rescued": "Cứu Sống Những Người Dân Thường (Civilians)",
  "We've got a live one, people.": "Chúng ta vừa mới có thêm một người mới tới vẫn còn sống sót (live one) đấy, mọi người ạ.",
  "Thanks for the help out here. I know it's not easy.": "Rất cảm ơn vì tất cả những sự giúp đỡ (help) ở ngoài này. Tôi biết rõ nó hoàn toàn đéo hề dễ dàng (easy) một chút đéo nào.",
  "Swat Zombie": "Con Zombie Đặc Nhiệm Swat",
  "I'm not waiting around, so you need to put on your big kid pants and move!": "Tôi sẽ đéo đời nào chịu tiếp tục đứng ở đây để chờ đợi (waiting around) đéo đâu, vì vậy nên cậu cần phải mặc vào chiếc quần dành cho những cậu bé to lớn (big kid) của mình đi và tiếp tục di chuyển (move)!",
  "I told Shira to run. To leave me. But she made a bunch of noise to lead the zombies away. I was alone.": "Tôi đã từng bảo Shira hãy mau chạy đi (run). Hãy bỏ mặc (leave) tôi lại đi. Nhưng cô ấy đã quyết định gây ra một đống những tiếng ồn chết tiệt nhằm mục đích dụ dỗ (lead) lũ zombies đuổi theo tránh xa khỏi tôi. Và sau đó thì tôi chỉ còn lại có một mình.",
  "You led them right to us!": "Cậu đã trực tiếp dẫn đường (led) cho bọn chúng đến thẳng chỗ của chúng tôi đấy!",
  "It's only a shame you can't mount a zombie head on account of blasting it all to hell to bag the sumbitch. (Improved Shooting, Cardio, and Wits)": "Thật sự vô cùng đáng tiếc (shame) khi mà cậu đã đéo thể nào có thể thu thập được một cái đầu (head) của bọn zombie bởi vì cái lý do là cậu đã nổ súng bắn nát bét (blasting) tươm toàn bộ bọn chúng để tiêu diệt cái lũ khốn nạn chó đẻ (sumbitch) đó. (Giúp Cải Thiện Đáng Kể Improved Kỹ Năng Bắn Súng Shooting, Khả Năng Vận Động Cardio, và Sự Khôn Ngoan Sáng Suốt Wits)",
  "59 REF Heather LaRue": "59 NGƯỜI TỊ NẠN (REF) Heather LaRue",
  "Sorry. Faith's not exactly my strong suit.": "Thành thật xin lỗi. Sự trung thành (Faith) đéo hẳn (exactly) là thế mạnh lớn nhất (strong suit) của tôi.",
  "I can do this all day.": "Tôi hoàn toàn có thể làm cái việc nhàm chán này trong suốt cả ngày (all day).",
  "Artillery site has over a dozen hostiles. Nothing a couple of army-trained badasses can't handle.": "Khu vực căn cứ pháo binh (Artillery site) hiện đang có đến hơn một tá những kẻ thù địch (hostiles). Chẳng có một điều đéo gì mà một cặp đôi siêu chiến binh cực kỳ thiện chiến (badasses) đã được quân đội huấn luyện bài bản (army-trained) lại đéo thể nào xử lý (handle) được cả.",
  "Medicine Drop": "Chuyến Hàng Tiếp Tế Chứa Đầy Thuốc Men (Medicine Drop)",
  "Movin' On Up!": "Tiếp Tục Tiến Lên (Movin' On Up) Nào!",
  "I get why you're in bad shape. Everybody's in bad shape.": "Tôi hoàn toàn có thể hiểu được lý do tại sao tình trạng (shape) hiện tại của cậu lại trở nên tồi tệ (bad) đến như vậy. Tình trạng của tất cả mọi người cũng đều tồi tệ y hệt như cậu vậy.",
  "This would improve yields from our gardens. REQUIRES A GARDEN.": "Thứ này chắc chắn sẽ có thể giúp cải thiện (improve) đáng kể sản lượng (yields) được thu hoạch từ những khu vườn (gardens) của chúng ta. YÊU CẦU CẦN PHẢI SỞ HỮU MỘT KHU VƯỜN (GARDEN).",
  "I could use an update on our friends.": "Tôi hiện đang rất cần phải được nghe một bài cập nhật (update) tình hình về những người bạn (friends) của chúng ta.",
  "But I still left him there. I never told that to anyone before now.": "Nhưng cuối cùng thì tôi vẫn quyết định bỏ mặc (left) anh ấy ở lại đó. Trước đó tôi chưa bao giờ (never) từng tiết lộ (told) cái điều đó với bất kỳ một người đéo nào cả cho đến tận bây giờ.",
  "62 PMC Mercenary": "62 TẬP ĐOÀN QUÂN SỰ TƯ NHÂN (PMC) Lính Đánh Thuê (Mercenary)",
  "Set Up Ops Center": "Thiết Lập Xây Dựng (Set Up) Trung Tâm Điều Hành (Ops Center)",
  "Zeds marching to the sea": "Bọn Zeds hiện đang ồ ạt diễu hành (marching) tiến thẳng về phía biển (sea)",
  "Fuck, how you been?": "Địt mẹ (Fuck), dạo này cậu thế đéo nào rồi (how you been)?",
  "Without it, we won't be able to make real firebombs. We'll be stuck scavenging for liquor bottles.": "Nếu như đéo có nó, thì chúng ta sẽ đéo thể nào có thể tự tay chế tạo ra được những quả bom lửa (firebombs) thực sự. Chúng ta sẽ mãi bị mắc kẹt (stuck) ở trong cái vòng luẩn quẩn phải đi nhặt nhạnh (scavenging) tìm kiếm những cái vỏ chai rượu (liquor bottles).",
  "Hey, whoa!": "Này (Hey), whoa!",
  "Don't mind if I do, thanks.": "Sẽ đéo bận tâm (mind) một chút đéo nào nếu như tôi thực sự phải làm việc đó đâu, cảm ơn nhé.",
  "Yes, and other than vaguely-threatening radio broadcasts, they've made no attempt to contact us or provide relief efforts to the civilian government.": "Đúng vậy, và ngoài những cái bản tin phát thanh (broadcasts) trên radio mang tính chất đe dọa cực kỳ mơ hồ (vaguely-threatening) ra, bọn họ vẫn chưa hề thực hiện bất kỳ một nỗ lực (attempt) đéo nào để cố gắng liên lạc (contact) với chúng ta hoặc là cung cấp (provide) các nỗ lực hỗ trợ cứu trợ (relief efforts) dành cho chính quyền dân sự (civilian government).",
  "Trouble in paradise, huh?": "Gặp Rắc rối (Trouble) ở nơi thiên đường (paradise), huh?",
  "You're on your own, soldiers.": "Kể từ giờ phút này các người sẽ phải tự lực cánh sinh bảo vệ cho chính bản thân mình (on your own) đấy, những người lính (soldiers) dũng cảm ạ.",
  "Racz": "Racz",
  "1 Case of Ammunition for 5 Daily Rations of Food.": "1 Rương (Case) Chứa Đầy Đạn Dược (Ammunition) Để Đổi Lấy 5 Khẩu Phần Thức Ăn Hàng Ngày (Daily Rations of Food).",
  "It looks like we don't have everything we need to build this facility. - %1$s": "Trông có vẻ như chúng ta đéo hề có đầy đủ tất cả mọi thứ (everything) mà chúng ta cần để có thể tiến hành xây dựng (build) nên được cái cơ sở (facility) này. - %1$s",
  "Jade": "Jade",
  "Let's go somewhere else. No point in drawing more of them here.": "Chúng ta hãy nhanh chóng đi đến một cái nơi đéo nào đó khác (somewhere else) thôi. Sẽ đéo có bất cứ một lợi ích (point) đéo gì trong cái việc cứ liên tục thu hút (drawing) thêm rất nhiều bọn chúng tới chỗ này cả.",
  "We are in a bit of trouble here...can anyone help?": "Chúng tôi hiện đang gặp phải một chút rắc rối (trouble) ở chỗ này... liệu có ai có thể giúp đỡ (help) được đéo?",
  "Twelve o'clock.": "Hướng Mười hai giờ (Twelve o'clock).",
  "Especially in times like these.": "Đặc biệt (Especially) là vào những cái thời điểm thảm khốc giống như lúc này (times like these).",
  "INCIDENT: Juggernaut Encounter": "BIẾN CỐ BẤT NGỜ (INCIDENT): Đụng Độ Trạm Trán (Encounter) Phải Một Con Juggernaut",
  "Requires UNLIMITED DATA PLAN.": "Yêu cầu (Requires) cần phải có ĐĂNG KÝ GÓI DỮ LIỆU KHÔNG GIỚI HẠN (UNLIMITED DATA PLAN).",
  "I lost my virginity back there. Me and Lucy Cormoran, junior year. She had this thing where...": "Tôi đã đánh mất đi sự trong trắng (virginity) của mình ngay tại cái khu vực đó. Tôi và Lucy Cormoran, vào năm học cấp ba (junior year). Cô ấy đã có cái thứ này ở cái nơi mà...",
  "Julene": "Julene",
  "Mickey Wilkerson": "Mickey Wilkerson",
  "I think this covers what we owe you.": "Tôi nghĩ là cái đống này chắc hẳn đã hoàn toàn trang trải (covers) đủ để trả hết toàn bộ số nợ (owe) mà chúng tôi đã vay mượn của các người rồi đấy.",
  "This base could be in better shape. \r\nAccess the base menu in your Journal to fix it up.": "Khu vực căn cứ (base) này đáng lẽ ra đã có thể ở trong một tình trạng tốt đẹp (better shape) hơn rất nhiều. \r\nHãy truy cập trực tiếp vào mục menu căn cứ (base) ở trong Cuốn Nhật Ký Hành Trình (Journal) của bạn để có thể tiến hành nâng cấp sửa chữa (fix it up) lại toàn bộ.",
  "SET UP: Sleeping Area": "TIẾN HÀNH THIẾT LẬP (SET UP): Khu Vực Ngủ Nghỉ (Sleeping Area)",
  "Help with the fortifications.": "Hỗ trợ (Help) gia cố thêm cho các công trình phòng thủ kiên cố (fortifications).",
  "He's alive ... for now.": "Anh ấy hiện tại vẫn còn sống (alive)... chỉ là ở trong thời điểm hiện tại (for now).",
  "RECRUIT SURVIVORS. Escort this entire group home to join your community.": "CHIÊU MỘ (RECRUIT) NHỮNG NGƯỜI SỐNG SÓT. Hộ tống (Escort) toàn bộ cả cái nhóm (group) người này quay trở về nhà (home) một cách an toàn nhất để bọn họ có thể chính thức gia nhập (join) vào cộng đồng (community) của bạn.",
  "Hey survivors, how about a call to break up the silence? Anyone?": "Này hỡi những con người đang cố gắng sống sót (survivors) ở ngoài kia, có ai muốn thực hiện một cuộc gọi (call) để có thể phá vỡ đi cái sự im lặng (silence) cực kỳ chết chóc này đéo? Có bất cứ một ai đéo?",
  "Sounds like there's a rotter around.": "Nghe giống như là đang có một con rotter (kẻ thối rữa) đi loanh quanh (around) ở gần đây đấy.",
  "If it ain't one thing, it's a-fuckin-other.": "Nếu như đéo phải là do cái chuyện chết tiệt (thing) này, thì chắc chắn là sẽ do một cái lý do chết tiệt nào đó khác (a-fuckin-other).",
  "Zombies inbound.": "Bọn Zombies đang ập tới (inbound) rồi.",
  "Moore": "Moore",
  "Leadership Improved!": "Kỹ Năng Lãnh Đạo (Leadership) Đã Được Cải Thiện (Improved)!",
  "Not too bad.": "Hoàn toàn đéo quá tệ (bad) một chút đéo nào.",
  "Requires Reflexes Level 6": "Yêu Cầu (Requires) Cần Phải Có Kỹ Năng Phản Xạ (Reflexes) Ở Cấp Độ (Level) 6",
  "Who is this?": "Kẻ đéo nào đang nói đấy hả (Who is this)?",
  "Gilchrist": "Gilchrist",
  "We found him on some kind of weird black ops mission, and he doesn't seem to like us all that much. That's fine, the feeling's mutual.": "Chúng tôi đã vô tình bắt gặp (found) được anh ta khi đang đi thực hiện một loại nhiệm vụ đặc nhiệm ngầm (black ops) vô cùng kỳ lạ đéo nào đó, và anh ta dường như cũng đéo hề tỏ ra là có thiện cảm (like) đối với chúng tôi cho lắm. Thế cũng đéo sao cả (fine), cái cảm giác đó đến từ cả hai phía (mutual).",
  "No more of that.": "Sẽ đéo bao giờ có thêm bất kỳ một cái thứ chết tiệt đéo nào giống như thế (No more of that) diễn ra nữa đâu.",
  "Feel like checking this out?": "Cậu có cảm thấy hứng thú (Feel like) đối với việc đi kiểm tra thử (checking) cái thứ này xem sao đéo?",
  "Abilities": "Các Khả Năng (Abilities) Đặc Biệt",
  "Edger": "Edger",
  "We've got some more shotgun shells.": "Chúng ta vừa mới kiếm được thêm một vài viên đạn dành cho súng shotgun (shotgun shells).",
  "Bree": "Bree",
  "Some more for the stockpile.": "Mang thêm được một ít vật tư (Some more) đóng góp vào trong kho hàng dự trữ (stockpile).",
  "Triplett": "Triplett",
  "Antisocial": "Lối Sống Kỳ Dị Hoàn Toàn Xa Lánh Lẩn Tránh Tiếp Xúc Với Xã Hội (Antisocial)",
  "Elena": "Elena",
  "2 MIL Pvt Royell Vincent": "2 QUÂN ĐỘI (MIL) Binh Nhì (Pvt) Royell Vincent",
  "Accept": "Chấp Nhận (Accept)",
  "Just need a little more time to heal up, that's all.": "Tôi hiện tại chỉ cần có thêm một chút thời gian (time) để có thể chữa lành (heal up) toàn bộ các vết thương mà thôi, mọi chuyện chỉ đơn giản có thế thôi (that's all).",
  "Damn, this bag's gettin' heavy!": "Mẹ kiếp (Damn), cái chiếc túi chết tiệt này đang ngày càng trở nên nặng nề (heavy) hơn rất nhiều rồi đấy!"
};

const file = 'output/languages/chunks/btxt_chunk_203.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_203.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk203[r.sourceText]) {
    r.translatedText = chunk203[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 203 successfully!');
