const fs = require('fs');
const chunk209 = {
  "A scoped revolver-rifle hybrid in .45 caliber.": "Một sự kết hợp pha trộn (hybrid) cực kỳ hoàn hảo giữa dòng súng lục ổ quay (revolver) và súng trường (rifle) có trang bị sẵn ống ngắm (scoped) sử dụng loại đạn nòng cỡ .45 caliber.",
  "Sounds fair to me.": "Nghe có vẻ (Sounds) cực kỳ hợp lý công bằng (fair) đối với tôi (to me) đấy.",
  "Take that one out!": "Mau tiến hành tiêu diệt hạ gục (Take out) cái con chó đẻ chết tiệt (that one) đó ngay đi!",
  "Get off this frequency, buddy. This is for grown-up army work, not whatever it is you're doing.": "Hãy mau cút xéo (Get off) ra khỏi cái kênh tần số tín hiệu (frequency) này ngay đi, anh bạn (buddy). Nơi này hiện đang được sử dụng để dành riêng cho những công việc (work) vô cùng quan trọng của những người lính quân đội (army) thực thụ (grown-up), chứ đéo (not) phải là chỗ để dành cho bất cứ cái thứ nhảm nhí đéo nào (whatever it is) mà cậu hiện đang cố gắng thực hiện (doing).",
  "Watchtower": "Khu Vực Tháp Canh (Watchtower)",
  "No. I'm sorry.": "Đéo (No). Tôi thực sự vô cùng xin lỗi (sorry).",
  "Working the angles.": "Tính toán điều chỉnh tỉ mỉ từng góc độ (Working the angles).",
  "At least we're okay for ammo.": "Chí ít (At least) thì hiện tại chúng ta vẫn còn đang có đủ (okay) một lượng đạn dược (ammo) cần thiết.",
  "Oh... oh Lord forgive me. I apologize...": "Oh... oh lạy Chúa (Lord) xin hãy tha thứ (forgive) cho con. Con vô cùng thành tâm xin lỗi (apologize)...",
  "I told you those pork chops looked under done. Nice going, Emeril. - %1$s": "Tôi đã nói thẳng (told) với cậu rồi cái đống sườn heo (pork chops) đó trông có vẻ như (looked) là vẫn chưa hề được nấu chín (under done) đéo đâu. Làm tốt (Nice going) lắm, Emeril. - %1$s",
  "Come on. Quit moping around, I need your help.": "Thôi nào (Come on). Hãy mau chấm dứt ngay (Quit) cái việc cứ liên tục lượn lờ ủ rũ rên rỉ (moping around) đi, tôi hiện đang rất cần (need) có sự hỗ trợ giúp đỡ (help) của cậu đây.",
  "Nice noise discipline, Boot.": "Giữ gìn kỷ luật (discipline) hạn chế tiếng ồn (noise) tốt (Nice) lắm, Binh Nhì (Boot).",
  "For shotguns.": "Sử dụng chuyên biệt dành riêng Cho (For) các loại súng shotguns.",
  "Wall": "Bức Tường (Wall)",
  "Shots fired in North Atlantic": "Tiếng súng nổ (Shots fired) đã vang lên ở khu vực North Atlantic",
  "Standing by for coordinates.": "Hiện đang chờ đợi (Standing by) để có thể nhận được tọa độ (coordinates) mục tiêu.",
  "That refugee is on the way to the capital.": "Người tị nạn (refugee) đó hiện tại đang ở trên đường (on the way) đi di chuyển tiến đến khu vực thủ đô (capital) rồi.",
  "Weaver": "Weaver",
  "Okay, look. I've got this condition. Lupus? It's chronic. No cure. Without medication...": "Được rồi (Okay), nghe này (look). Tôi hiện đang mắc phải một căn bệnh (condition) tồi tệ này. Lupus ban đỏ ư? Nó là một dạng mãn tính (chronic). Hoàn toàn đéo thể nào có thể chữa trị (No cure) được. Nếu như đéo có (Without) thuốc men (medication) điều trị...",
  "The Dealer": "Kẻ Chuyên Đi Phân Phối Buôn Bán Giao Dịch Hàng Hóa Cấm (Dealer)",
  "Highroad, this is Black Friday. Please let the Special Activities Division know that Sergeant Eldridge is officially KIA.": "Căn cứ tổng bộ chỉ huy Highroad, đây là (this is) trạm gác Black Friday. Xin vui lòng (Please) hãy nhanh chóng thông báo (let) cho phía Cục Đơn Vị Phụ Trách Về Các Hoạt Động Cứu Trợ Đặc Biệt (Special Activities Division) biết (know) rằng Thượng Sĩ Trung Sĩ (Sergeant) Eldridge hiện tại đã chính thức (officially) Tử Trận Bỏ Mạng Hoàn Toàn (KIA).",
  "You're on your own.": "Cậu hiện tại sẽ phải tự lực cánh sinh xoay sở đi nhé (on your own).",
  "I am super-impressed by what you've accomplished.": "Tôi thực sự cảm thấy vô cùng kinh ngạc và vô cùng ấn tượng (super-impressed) với toàn bộ những gì (what) mà cậu đã xuất sắc đạt được (accomplished).",
  "Hey, let me give you something.": "Này, hãy để cho tôi (let me) gửi tặng cho cậu (give) một cái thứ đồ vật gì đó (something).",
  "Bedroom": "Khu Vực Phòng Ngủ (Bedroom)",
  "I'm on the move.": "Tôi hiện tại đang bắt đầu tiến hành di chuyển (on the move).",
  "Detonator": "Công Tắc Kích Nổ (Detonator)",
  "Internet junkie who just wants to make the world a better place.": "Một con nghiện cắm mặt vào mạng Internet (Internet junkie) kẻ luôn (who) chỉ (just) có một khao khát mong muốn (wants) rằng có thể khiến (make) cho cái thế giới (world) tồi tệ này trở thành một nơi (place) tốt đẹp hơn (better).",
  "%s Collected!": "Hiện Tại Đã Thu Thập Lấy Được (Collected) %s!",
  "Not bad, not bad at all!": "Đéo hề tồi (Not bad) một chút nào, hoàn toàn đéo hề tồi một chút đéo nào cả (at all)!",
  "Yeah we're building here.": "Yeah hiện tại chúng tôi vẫn đang tiếp tục tiến hành xây dựng (building) mọi thứ ở quanh đây (here).",
  "Think I'll just leave that.": "Tôi nghĩ (Think) là tôi sẽ chỉ việc (just) bỏ lại (leave) cái món đồ chết tiệt đó (that) mà thôi.",
  "Pharmaceutical sales executive who suffers from bad luck with the ladies.": "Một vị giám đốc đại diện chuyên phụ trách về mảng bán hàng (sales executive) dược phẩm (Pharmaceutical) kẻ luôn (who) phải hứng chịu đau khổ (suffers) từ những sự xui xẻo rủi ro (bad luck) trong những vấn đề có liên quan đến chuyện tình cảm với hội chị em phụ nữ (ladies).",
  "With the right person tending the garden, we'll have a chance of higher yields.": "Chỉ Cần có được sự hỗ trợ đắc lực từ đúng một người (right person) thực sự am hiểu về việc chăm sóc (tending) khu vực vườn tược (garden), chúng ta chắc chắn sẽ có được một cơ hội (chance) thu hoạch được một sản lượng năng suất (yields) cao hơn (higher) rất nhiều.",
  "Say your piece and get the hell out. I ain't got time for this shit.": "Hãy mau nói thẳng (Say) ra cái phần mục đích (piece) của nhà cậu đi rồi mau cút xéo (get the hell out) ngay. Tôi hoàn toàn đéo (ain't) có nhiều thời gian rảnh rỗi (time) để dành cho cái thứ cứt đái tồi tệ (shit) này đéo.",
  "Sure, ready when you are.": "Chắc chắn (Sure) rồi, tôi luôn luôn ở trong một tư thế sẵn sàng (ready) bất cứ khi nào (when) mà cậu yêu cầu.",
  "Could use some help getting out of here.": "Hiện đang rất cần (Could use) một sự hỗ trợ giúp đỡ (help) nào đó để có thể đi thoát ra (getting out) được khỏi cái nơi chốn khốn khiếp chết tiệt này (here).",
  "Elijah": "Elijah",
  "If I'd known this was coming, I'd have designed the school with a moat. (Handy with tools.)": "Nếu như tôi mà đã biết trước (known) được rằng cái thảm họa tồi tệ này rồi sẽ xảy ra (coming), thì tôi chắc chắn đã đích thân tự tay thiết kế (designed) bao bọc xung quanh cái ngôi trường (school) này là một con hào (moat) cực lớn rồi. (Vô Cùng Tháo Vát Khéo Tay Rất Giỏi Handy trong việc sử dụng đa dạng các loại công cụ dụng cụ tools.)",
  "Haven't seen much of her yet.": "Tôi vẫn chưa (Haven't) từng được nhìn thấy (seen) cô ta quá nhiều (much) đéo đâu.",
  "Fix Up Bedroom": "Tiến Hành Sửa Chữa (Fix Up) Cải Tạo Lại Khu Vực Phòng Ngủ (Bedroom)",
  "Warehouse Storage": "Nhà Kho (Warehouse) Lưu Trữ Trữ Hàng (Storage)",
  "I don't think this is over.": "Tôi đéo nghĩ (don't think) rằng mọi chuyện ở đây đã thực sự kết thúc (over) đéo đâu.",
  "You take it easy now!": "Bây giờ (now) cậu hãy cứ bình tĩnh thư giãn (take it easy) đi!",
  "Zombies are hitting our runners pretty hard!": "Lũ Zombies tởm lợm hiện đang liên tục tấn công đâm chém (hitting) những người chạy bộ (runners) làm nhiệm vụ giao hàng của chúng ta một cách vô cùng thảm khốc ác liệt (pretty hard) kìa!",
  "I feel like we're going in circles trying to avoid these fucking zeds.": "Tôi có cảm giác (feel) dường như (like) là chúng ta hiện đang cứ liên tục đi chạy vòng quanh thành một vòng tròn khép kín (circles) trong lúc đang cố gắng (trying) tìm cách để có thể né tránh (avoid) cái lũ zeds khốn khiếp chết tiệt (fucking) này vậy.",
  "Ain't no zeds here.": "Tuyệt đối đéo hề (Ain't no) có bất cứ một con zeds đéo nào ở quanh đây (here) cả.",
  "Can't remember the last time I had a good night's sleep. (REDUCED STAMINA.)": "Hoàn toàn đéo thể nào (Can't) có thể nhớ nổi (remember) được xem cái lần cuối cùng (last time) mà tôi có thể đánh được một giấc ngủ (sleep) cực kỳ ngon lành (good night's) là từ khi đéo nào nữa. (THỂ LỰC SINH LỰC STAMINA ĐÃ BỊ SUY GIẢM GIẢM SÚT REDUCED CHẾT TIỆT.)",
  "Now, if we're lucky, when the troops pulled out they left behind anything too heavy to carry. Maybe including artillery shells.": "Giờ thì (Now), nếu như (if) chúng thực sự đủ may mắn (lucky), một khi (when) quân đội (troops) bắt đầu tiến hành rút lui (pulled out) chắc chắn là bọn họ sẽ đành phải bỏ lại phía sau (left behind) bất cứ một cái thứ gì đó (anything) quá sức nặng nề (heavy) đéo thể nào có thể tự mang vác theo (carry) được. Có thể (Maybe) là sẽ bao gồm (including) luôn cả các loại vỏ đạn pháo (artillery shells).",
  "Soldier, I can't risk you being KIA. I need your team here at the capital where you can still do some good.": "Người lính (Soldier), tôi hoàn toàn đéo thể nào có thể dám (can't) đánh cược mạo hiểm (risk) chịu đựng cái việc cậu sẽ bị KIA (Tử trận). Tôi hiện đang rất cần (need) đội (team) của cậu phải túc trực ở ngay tại đây (here) khu vực thủ đô (capital) nơi (where) mà cậu vẫn hoàn toàn có thể tiếp tục tự mình làm (do) được một vài thứ gì đó hữu ích (good).",
  "The Grange needs fortifications.": "Khu vực trang trại The Grange hiện đang rất cần (needs) phải được gia cố xây dựng thêm các công trình hệ thống phòng thủ (fortifications).",
  "No reason for that now.": "Hoàn toàn đéo có (No) bất kỳ một lý do (reason) chết tiệt đéo nào để phải tiến hành làm cái việc đó (for that) ngay lúc này (now) đéo.",
  "Diary Page": "Trang Giấy Xé Ra Từ Cuốn Sổ Nhật Ký (Diary Page)",
  "Destroy the Feral Zombies": "Tiến Hành Phá Hủy Tiêu Diệt Hạ Gục (Destroy) Bọn Feral Zombies Khát Máu Bạo Lực Chết Tiệt",
  "Here.": "Ở ngay tại đây (Here).",
  "The zombies broke through their defenses. I heard the whole thing on the radio. It was... awful.": "Bọn zombies đã dễ dàng chọc thủng phá vỡ (broke through) được toàn bộ mọi hệ thống phòng thủ (defenses) của bọn họ. Tôi đã tận tai lắng nghe (heard) được toàn bộ mọi sự việc tồi tệ đó (whole thing) thông qua sóng phát thanh radio. Nó thực sự vô cùng... khủng khiếp (awful).",
  "I'm coming home alive after this. I don't really care how many zeds get in my way.": "Tôi chắc chắn sẽ quay trở về căn cứ (coming home) một cách an toàn sống sót (alive) ngay sau khi kết thúc xong xuôi cái vụ (after this) này. Tôi hoàn toàn đéo (don't) thực sự (really) quan tâm bận tâm (care) đến việc liệu sẽ có thêm bao nhiêu (how many) con zeds khốn kiếp dám ngang nhiên nhảy ra ngáng đường (get in my way) của tôi đéo đâu.",
  "Doctor -- no!": "Bác sĩ (Doctor) -- đéo (no) đừng làm như vậy!",
  "Got word of an area that is rumored to have FUEL. Let's check it out.": "Vừa mới nhận được một thông tin mật báo (Got word) nói về một khu vực (area) nơi (that) mà có tin đồn (rumored) là hiện vẫn còn đang lưu trữ một lượng lớn NHIÊN LIỆU XĂNG DẦU KHÍ ĐỐT (FUEL). Nào chúng ta hãy cùng nhau tiến đến đó để đi kiểm tra (check it out) ngay thôi.",
  "Here they come!": "Bọn chúng bắt đầu kéo đến rồi kìa (Here they come)!",
  "Way too close that time.": "Vừa mới ở một khoảng cách quá (too) gần (close) vào cái lúc đó (that time).",
  "Better deal with this first.": "Tốt hơn hết (Better) là nên giải quyết xử lý dứt điểm (deal with) cái thứ chết tiệt này (this) trước đã (first).",
  "We're lucky we have plenty of food.": "Chúng ta thực sự rất là vô cùng may mắn (lucky) vì hiện tại chúng ta vẫn còn đang có rất nhiều dư dả (plenty) các loại nguồn cung ứng lương thực thực phẩm (food).",
  "Thanks for getting me home again.": "Vô cùng cảm ơn (Thanks) vì đã hỗ trợ đưa dẫn (getting) tôi quay trở về căn cứ ngôi nhà (home) an toàn thêm một lần nữa (again).",
  "Trotter": "Trotter",
  "We're pinned down and need extraction.": "Chúng tôi hiện đang bị kìm chân ghim chặt (pinned down) khốn khiếp và vô cùng cần (need) phải có người đến để hỗ trợ rút lui giải cứu (extraction).",
  "Do that. And don't get killed.": "Hãy tiến hành làm như vậy đi (Do that). Và tuyệt đối đừng (don't) có để bản thân bị bọn chúng giết chết (killed) đấy.",
  "Heh. Guess that's why they always say \"don't drink the water.\"": "Heh. Có lẽ (Guess) đó chính là lý do tại sao (why) mà bọn họ luôn luôn liên tục cảnh báo (say) rằng \"tuyệt đối đừng (don't) bao giờ được uống (drink) cái nguồn nước (water) bẩn thỉu đó.\"",
  "Lend a fuckin' hand?": "Sẵn lòng chìa ra (Lend) một bàn tay (hand) để đi hỗ trợ giúp đỡ khốn khiếp chết tiệt (fuckin') chứ hả?",
  "But the Wilkersons? Really? Have you seen their rap sheets?": "Thế nhưng (But) lại là cái gia đình Wilkersons chết dẫm đó ư? Cậu thực sự (Really) nghiêm túc đấy đéo? Cậu đã từng được tận mắt nhìn thấy (seen) cái đống hồ sơ tiền án tiền sự (rap sheets) dài dằng dặc của bọn chúng chưa hả?",
  "I still see you in ten seconds and I'll crack your skull open so the zombies don't have to work so hard.": "Nếu như tôi mà vẫn còn nhìn thấy (see) cái bản mặt của cậu ở đây trong vòng mười giây (ten seconds) tới thì tôi chắc chắn sẽ tự tay đập vỡ (crack) toang cái hộp sọ (skull) của cậu ra ngay lập tức để cho bọn zombies đéo (don't) cần phải cố gắng làm việc (work) một cách cực nhọc (so hard) khốn khiếp đến như vậy nữa.",
  "The RV is prepped and ready to go. Now it's up to us ... how long do we want to stay here before shipping out? Everyone is ready to drop what they're doing and run if we give the order.": "Chiếc xe RV hiện tại đã được chuẩn bị (prepped) sửa chữa xong xuôi và hoàn toàn sẵn sàng (ready) để có thể lăn bánh khởi hành rời đi (go). Giờ đây (Now) mọi thứ sẽ phụ thuộc hoàn toàn vào quyết định của chính chúng ta (up to us) ... rốt cuộc thì chúng ta sẽ còn muốn (want) tiếp tục ở lại (stay) cái chốn chết tiệt này (here) thêm bao lâu nữa (how long) trước khi (before) thực sự bắt đầu chuyến hành trình di tản (shipping out)? Tất cả mọi người (Everyone) hiện đều đã sẵn sàng vứt bỏ (drop) lại toàn bộ tất cả mọi thứ (what) mà bọn họ hiện đang cố gắng làm (doing) và sẽ ngay lập tức bỏ chạy (run) đi ngay nếu như (if) chúng ta chịu ban phát đưa ra (give) một lời mệnh lệnh (order) chết tiệt.",
  "Continue": "Tiếp Tục (Continue)",
  "Arriving at the target now.": "Hiện tại đang tiến hành di chuyển tiếp cận đến (Arriving) khu vực mục tiêu (target) ngay bây giờ (now).",
  "LOG: Rumors are flying": "NHẬT KÝ THEO DÕI (LOG): Những Lời Đồn Đại (Rumors) Hiện Đang Bắt Đầu Bay Múa Lan Truyền Khắp Nơi (flying)",
  "Food supplies are looking a little tight.": "Nguồn dự trữ tiếp tế lương thực (Food supplies) dạo gần đây trông có vẻ như (looking) đang trở nên khá là cạn kiệt thiếu hụt (a little tight) cmnr.",
  "I really missed an opportunity here, but life goes on.": "Tôi thực sự (really) đã vô tình bỏ lỡ (missed) mất một cơ hội (opportunity) vô cùng đáng giá ở đây (here), thế nhưng (but) cuộc sống (life) thì vẫn luôn luôn phải tiếp diễn (goes on) mà thôi.",
  "I Can See My House From Here": "Tôi Hoàn Toàn Có Thể (Can) Dễ Dàng Nhìn Thấy (See) Ngôi Nhà Căn Cứ (House) Của Tôi Từ Ngay Tại Vị Trí Chỗ Này (From Here)",
  "Sense of Superiority": "Cảm Giác Rằng Bản Thân Mình Vượt Trội Và Siêu Việt Hơn (Sense of Superiority) Tất Cả Những Người Khác",
  "START MISSION. It might be useful to earn the respect of the local Sheriff.": "BẮT ĐẦU (START) TIẾN HÀNH THỰC HIỆN NHIỆM VỤ (MISSION). Có lẽ (might be) nó sẽ trở nên cực kỳ hữu ích (useful) để có thể dễ dàng kiếm được (earn) một sự tôn trọng (respect) nhất định từ một vị Cảnh Sát Trưởng (Sheriff) của khu vực địa phương (local) này.",
  "We've had a sighting of one of our missing persons. We might have a line on %1$s's whereabouts.": "Chúng tôi vừa mới có được một thông tin thông báo phát hiện (sighting) vô cùng quan trọng về một (one) trong số những người hiện đang bị mất tích (missing) của chúng ta. Chúng tôi có lẽ (might) hiện đã có được một vài manh mối liên kết (line) có liên quan đến tung tích (whereabouts) của %1$s.",
  "Becca Collins": "Becca Collins",
  "DECLINE MISSION. Sam isn't the type to hold a grudge, is she?": "TỪ CHỐI BỎ QUA (DECLINE) ĐÉO LÀM CÁI NHIỆM VỤ NÀY (MISSION). Sam đéo phải (isn't) là một cái loại người (type) có tính cách chuyên đi ôm hận thù dai dẳng (hold a grudge) đéo đâu, có đúng đéo (is she)?",
  "Could be trouble on the left.": "Có lẽ (Could be) là đang có rắc rối (trouble) ở ngay bên phía cánh trái (left) kìa.",
  "I can still hear something.": "Tôi vẫn (still) còn có thể nghe thấy (hear) được một cái thứ âm thanh (something) chết tiệt đéo nào đó.",
  "Our memories are the only legacies they can leave behind. We owe them that much.": "Những ký ức kỷ niệm (memories) đẹp đẽ của chúng ta chính là những di sản vô giá (legacies) duy nhất (only) mà bọn họ có thể bỏ lại ở phía sau (leave behind). Chúng ta thực sự đã nợ (owe) bọn họ quá nhiều (that much).",
  "Uh… uh… aaaah!": "Uh… uh… aaaah!",
  "Damien": "Damien",
  "Faith's not exactly my strong suit.": "Lòng tin đức tin (Faith's) hoàn toàn đéo hề (not exactly) phải là một trong những điểm vô cùng mạnh mẽ (strong suit) nổi trội của tôi đéo đâu.",
  "Oh, shit, he's coming over here. Act natural.": "Oh, cứt thật (shit), gã ta hiện đang tiến đến (coming) ngay tại vị trí bên này (over here) kìa. Hãy cố gắng tỏ ra (Act) hành động cư xử một cách hoàn toàn tự nhiên (natural) đi.",
  "Well, our fuel's basically dead.": "Chà (Well), nguồn dự trữ nhiên liệu khí đốt xăng dầu (fuel's) của chúng ta về cơ bản (basically) là đã hoàn toàn cạn kiệt đéo còn (dead) một giọt.",
  "Provides +8 beds.": "Cung Cấp Hỗ Trợ (Provides) +8 chiếc giường ngủ (beds).",
  "Gallons of Fuel": "Những Thùng Gallons Chứa Đầy Nhiên Liệu Xăng Dầu Khí Đốt (Fuel)",
  "Now don't judge me, all right? I've got a lot of useful stuff here... and I'll share it with you if you can get me out of here.": "Bây giờ (Now) thì xin hãy đừng (don't) có vội vã đánh giá (judge) gì tôi cả, hiểu đéo (all right)? Tôi hiện đang sở hữu (got) được vô vàn (a lot) những món đồ đạc (stuff) cực kỳ hữu ích (useful) ở ngay tại đây (here)... và tôi chắc chắn sẽ phân chia sẻ lại (share) nó cho cậu nếu như (if) cậu thực sự có thể giúp tôi thoát ra (get me out) khỏi được cái chốn chết tiệt này (here).",
  "Did she say they have guns?": "Có đúng là cô ta vừa mới lên tiếng khẳng định (say) nói rằng bọn chúng hiện đang sở hữu (have) súng ống (guns) đấy đéo?",
  "Scouted by %1$s.": "Đã được tiến hành theo dõi do thám đi trinh sát (Scouted) kỹ càng bởi %1$s.",
  "Roger that, Black Friday. If those guys even exist anymore.": "Rõ rồi (Roger that), trạm gác Black Friday. Nếu như (If) cái lũ khốn kiếp (guys) chết tiệt đó thậm chí (even) vẫn còn đang tồn tại sống sót (exist) trên cõi đời này đéo (anymore).",
  "Let's make this happen.": "Nào chúng ta hãy cùng nhau làm (make) cho cái sự việc tồi tệ này (this) thực sự biến thành hiện thực (happen) đi nào.",
  "You just call us every time you see a zombie? Take care of it yourself.": "Có phải là cứ mỗi lần (every time) cậu tình cờ bắt gặp (see) một con zombie chết tiệt đéo nào đó thì cậu sẽ ngay lập tức (just) gọi réo tên (call) chúng tôi lên hay đéo? Hãy mau tự mình (yourself) tự đi mà giải quyết xử lý dọn dẹp (Take care) cái con chó đẻ đó đi.",
  "Expulsion always lowers your community reputation.": "Hành vi Trục Xuất (Expulsion) một ai đó sẽ luôn luôn (always) làm cho điểm danh tiếng uy tín (reputation) của cộng đồng (community) căn cứ của bạn bị sụt giảm (lowers) nghiêm trọng."
};

const file = 'output/languages/chunks/btxt_chunk_209.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_209.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk209[r.sourceText]) {
    r.translatedText = chunk209[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 209 successfully!');
