const fs = require('fs');
const chunk174 = {
  "Gain increased XP from melee combat.": "Nhận thêm XP từ các trận cận chiến (melee combat).",
  "I got the key to fixing this whole mess right here in my pack.": "Tôi có chìa khóa để giải quyết toàn bộ mớ hỗn độn này ngay trong balo của mình.",
  "I was more concerned as to whether the infection's cleared up.": "Tôi lo lắng nhiều hơn về việc liệu tình trạng lây nhiễm (infection) đã được giải quyết triệt để hay chưa.",
  "Lily, we don't have the time!": "Lily, chúng ta đéo có thời gian đâu!",
  "From the era of big American road muscle. Lots of guts but handles like a brick and is short on seats.": "Đến từ kỷ nguyên của những chiếc xe cơ bắp đường phố (road muscle) Mỹ. Động cơ rất bốc (guts) nhưng việc điều khiển thì cứng nhắc như một viên gạch và lại còn thiếu chỗ ngồi.",
  "Train another enclave at your dojo.": "Huấn luyện cho một nhóm sinh tồn (enclave) khác tại võ đường (dojo) của cậu.",
  "Indoor": "Trong Nhà (Indoor)",
  "Ms. Grant. I just need to know that I'm rescuing someone who knows the science, and not just Doctor Horn's girlfriend.": "Cô Grant. Tôi chỉ cần biết rằng tôi đang giải cứu một người am hiểu về khoa học (science), chứ đéo phải chỉ là bạn gái của Bác sĩ Horn.",
  "Assault Rifle: AK 74": "Súng Trường Đột Kích (Assault Rifle): AK 74",
  "Anyway, I found this necklace of his. Would you... could you come with me? I want to leave it someplace he would have liked.": "Dù sao thì, tôi đã tìm thấy sợi dây chuyền này của anh ấy. Cậu sẽ... cậu có thể đi cùng tôi đéo? Tôi muốn để nó ở một nơi nào đó mà anh ấy từng yêu thích.",
  "Too early to tell. He may have been crazy, but I hope we didn't let this soldier die for nothing. Highroad out.": "Còn quá sớm để nói. Anh ta có thể đã điên rồi, nhưng tôi hy vọng chúng ta đã đéo để người lính này phải hy sinh một cách vô ích. Highroad hết (out).",
  "Sent an energy drink flying.": "Vừa ném bay một lon nước tăng lực.",
  "Toggle Waypoint": "Bật/Tắt Điểm Đánh Dấu (Waypoint)",
  "Happy to help.": "Rất vui được giúp đỡ.",
  "Nobody has any idea where %3$s is. If we don't find them soon, we might not find them at all. -%2$s": "Đéo ai biết %3$s đang ở đâu cả. Nếu chúng ta đéo nhanh chóng tìm thấy bọn họ, có lẽ chúng ta sẽ đéo bao giờ tìm thấy họ nữa. -%2$s",
  "It took some persuading, but we all agreed to get matching tattoos to show our mutual trust and solidarity. It helps to have a visual reminder that we're all on the same side.": "Phải mất chút công sức thuyết phục, nhưng tất cả chúng tôi đã đồng ý xăm những hình xăm (tattoos) giống hệt nhau để thể hiện sự tin tưởng và tình đoàn kết lẫn nhau. Nó giúp có một lời nhắc nhở trực quan rằng tất cả chúng ta đều đang cùng chung một chiến tuyến.",
  "Kent": "Kent",
  "This feel a little familiar to you?": "Cậu có cảm thấy chuyện này hơi quen thuộc đéo?",
  "That's gonna have to wait.": "Chuyện đó sẽ phải chờ thôi.",
  "But let's try finding this guy before he sees US, okay?": "Nhưng hãy cố gắng tìm gã này trước khi hắn nhìn thấy CHÚNG TA, được chứ?",
  "Carter": "Carter",
  "Target's gone.": "Mục tiêu đã biến mất.",
  "Press [aim.reload] to reload.": "Nhấn [aim.reload] để nạp đạn (reload).",
  "You must be Doctor Thomas Horn. We're here to get you out.": "Ông chắc hẳn là Bác sĩ Thomas Horn. Chúng tôi ở đây để đưa ông ra ngoài.",
  "Brack": "Brack",
  "Next time let's not hit ALL the zeds?": "Lần tới chúng ta đừng có đánh ĐỘNG tất cả bọn zeds, có được đéo?",
  "Fairgrounds Storage": "Kho Chứa Đồ (Storage) Ở Khu Hội Chợ (Fairgrounds)",
  "Damn, I'm good!": "Mẹ kiếp, tôi đúng là quá đỉnh!",
  "ATTITUDE: Overbearing": "THÁI ĐỘ (ATTITUDE): Hống Hách, Độc Đoán (Overbearing)",
  "Will you...? I mean, it's not technically suicide if you do it. Right?": "Cậu sẽ giúp chứ...? Ý tôi là, về mặt kỹ thuật thì nó đéo phải là tự sát (suicide) nếu cậu làm điều đó. Đúng đéo?",
  "Loss to the Community": "Một Sự Mất Mát Đối Với Cộng Đồng (Community)",
  "Shotgun: 1187 Chop": "Súng Shotgun: 1187 Chop",
  "Danica": "Danica",
  "Upgrade to Weapons Lab": "Nâng cấp lên Phòng Thí Nghiệm Vũ Khí (Weapons Lab)",
  "This is tough!": "Điều này thật là khó khăn (tough)!",
  "Damn. That area's totally infested.": "Chết tiệt. Khu vực đó đã hoàn toàn bị lây nhiễm (infested) rồi.",
  "Radio": "Bộ Đàm (Radio)",
  "Feels like a bunch of tiny goblins are doing a clog dance through my bowels. This is what we get for not having a proper place to prepare our food.": "Cảm giác giống như có một bầy yêu tinh tí hon đang nhảy múa ầm ĩ (clog dance) xuyên qua ruột gan tôi vậy. Đây là những gì chúng ta nhận được vì đéo có một nơi tử tế để chuẩn bị thức ăn.",
  "Barricade the Windows": "Gia Cố Chắn Kín Các Cửa Sổ (Windows)",
  "%1$s survived.": "%1$s đã sống sót.",
  "Need a Medical Lab": "Cần có một Phòng Thí Nghiệm Y Tế (Medical Lab)",
  "Stay strong out there.": "Hãy giữ vững tinh thần mạnh mẽ (Stay strong) khi ở ngoài đó nhé.",
  "MATERIALS RESOURCE. A messy heap of old building materials.": "TÀI NGUYÊN VẬT LIỆU (MATERIALS). Một đống lộn xộn các loại vật liệu xây dựng cũ.",
  "UPGRADED: Shooting Platform": "ĐÃ NÂNG CẤP: Bệ Đứng Bắn (Shooting Platform)",
  "These things are looking pretty active. I think they're gonna spread to another building soon.": "Bọn này trông có vẻ khá là hiếu động (active) đấy. Tôi nghĩ chúng sẽ sớm lây lan sang một tòa nhà khác mất thôi.",
  "Madison Grant insists that she knows Dr. Horn's research well enough to reconstruct it on her own. If we can keep her alive until the helo gets here, we may actually make a difference.": "Madison Grant khăng khăng rằng cô ấy biết đủ rõ về nghiên cứu của Bác sĩ Horn để có thể tự mình tái tạo lại nó. Nếu chúng ta có thể giữ cho cô ấy sống sót cho đến khi máy bay trực thăng đến đây, có lẽ chúng ta sẽ thực sự làm nên chuyện.",
  "START MISSION. Earn Trust for helping clear the infestation.": "BẮT ĐẦU NHIỆM VỤ. Nhận được Độ Tin Tưởng (Trust) nhờ vào việc giúp dọn dẹp sạch sẽ ổ dịch (infestation).",
  "For God's sake keep it sterile. You don't want that thing getting infected.": "Vì Chúa hãy giữ cho nó được vô trùng. Cậu đéo muốn thứ đó bị nhiễm trùng đâu.",
  "Fucking- shit- FUCK!": "Khốn- chết tiệt- ĐỤ MÁ!",
  "I hear you, loud and clear.": "Tôi nghe thấy cậu rồi, rất to và rõ ràng.",
  "Gunshots, yeah.": "Tiếng súng, ừ.",
  "It's on now.": "Bắt đầu rồi đây (It's on now).",
  "Honey": "Honey",
  "Spotted a weird one.": "Vừa phát hiện ra một con rất kỳ lạ (weird).",
  "Gracie": "Gracie",
  "UPGRADING our INFIRMARY will increase our chances of recovery in the future.": "Việc NÂNG CẤP BỆNH XÁ (INFIRMARY) của chúng ta sẽ làm tăng cơ hội phục hồi trong tương lai.",
  "Hang tight, we're coming!": "Ráng bám trụ (Hang tight) nhé, chúng tôi đến đây!",
  "Dr. Dan": "Bác sĩ Dan",
  "EXPIRED: Madison Grant": "ĐÃ HẾT HẠN (EXPIRED): Madison Grant",
  "Never hurts to have some extra.": "Có dư ra một chút cũng đéo bao giờ thừa.",
  "Heartrate Monitor": "Máy Đo Nhịp Tim (Heartrate Monitor)",
  "We need to be better about harvesting our crops. We just lost a whole planting.": "Chúng ta cần phải làm tốt hơn trong việc thu hoạch mùa màng của mình. Chúng ta vừa mới mất trắng cả một vụ mùa (planting) xong.",
  "If we ignore them, they'll just spread, and next thing you know we're neck-deep in zombies.": "Nếu chúng ta phớt lờ chúng đi, chúng sẽ chỉ lây lan ra thêm, và điều tiếp theo mà cậu biết là chúng ta sẽ ngập ngụa tới tận cổ trong lũ zombies cho xem.",
  "I'm so proud of you!": "Tôi rất tự hào về cậu!",
  "Alara": "Alara",
  "I'm not going down like this!": "Tôi sẽ đéo gục ngã (going down) như thế này đâu!",
  "Vegard": "Vegard",
  "There's a lot of firepower here, but it looks like they're barely holding on. Same as the rest of us. - %1$s": "Có rất nhiều hỏa lực (firepower) ở đây, nhưng có vẻ như bọn họ chỉ đang cố gắng cầm cự một cách chật vật. Giống hệt như những người còn lại trong chúng ta vậy. - %1$s",
  "Have raids like these been a problem before?": "Những cuộc đột kích (raids) như thế này đã từng là một vấn đề trước đây hay chưa?",
  "Watson": "Watson",
  "Green Thumb": "Có Khiếu Trồng Trọt (Green Thumb)",
  "Bunsen Burner": "Đèn Khò Bunsen (Bunsen Burner)",
  "Tom": "Tom",
  "Dakimakura": "Gối Ôm Hình Nhân Vật Hoạt Hình (Dakimakura)",
  "So the brain's the thing, right? But why is that?": "Vậy thì bộ não là mấu chốt, đúng đéo? Nhưng tại sao lại như vậy chứ?",
  "Too bad we won't be doing another one of those for a while.": "Thật tệ là chúng ta sẽ đéo thể làm thêm một chuyện nào giống như thế này nữa trong một thời gian dài đấy.",
  "In trouble.": "Đang gặp rắc rối (In trouble).",
  "Hart": "Hart",
  "We've got some more rounds of 40mm grenade ammunition.": "Chúng ta đã có thêm một số đạn súng lựu đạn 40mm.",
  "I'll check to see what's here.": "Tôi sẽ đi kiểm tra xem có những gì ở đây.",
  "Nothing you wear looks ridiculous.": "Đéo có bộ đồ nào cậu mặc mà trông lại có vẻ lố bịch (ridiculous) cả.",
  "I never realized how important my faith was to me until everything else was taken away.": "Tôi chưa bao giờ nhận ra đức tin của mình lại quan trọng đối với tôi đến nhường nào cho đến khi mọi thứ khác đều bị tước đoạt mất.",
  "What the hell, man? We're gone two weeks and - and what? Everybody takes up cannibalism?": "Cái quái gì vậy, anh bạn? Chúng tôi mới rời đi có hai tuần mà - và chuyện gì thế này? Mọi người đều bắt đầu ăn thịt lẫn nhau (cannibalism) sao?",
  "I'll see who's free and send them your way.": "Tôi sẽ xem có ai đang rảnh rỗi và cử họ đến chỗ cậu.",
  "Well well well. You done good.": "Chà chà chà. Cậu làm tốt lắm.",
  "3 Daily Rations of Food per day": "3 Khẩu Phần (Rations) Thức Ăn Hàng Ngày mỗi ngày",
  "Look, I don't like this any better than you, but we gotta keep it together so we can hold each other up. That's all.": "Nghe này, tôi cũng đéo thích chuyện này hơn cậu chút nào đâu, nhưng chúng ta phải sát cánh cùng nhau để có thể tương trợ nâng đỡ lẫn nhau. Chỉ vậy thôi.",
  "The RV's as clean as we can get it.": "Chiếc RV đã sạch sẽ nhất trong khả năng mà chúng ta có thể dọn dẹp nó rồi.",
  "And that should do it. Hope it helps.": "Và thế là xong. Hy vọng nó có ích.",
  "Man, I wish I could be as awesome as you.": "Trời ạ, tôi ước gì mình có thể tuyệt vời (awesome) được như cậu.",
  "Pokorny": "Pokorny",
  "Pistol: G 17C": "Súng Lục: G 17C",
  "Compact, little brother of the G17C": "Gọn nhẹ, là người em trai nhỏ của khẩu G17C",
  "Man, can anybody tell me what the hell is going on?": "Anh bạn, có ai có thể cho tôi biết chuyện quái gì đang xảy ra đéo?",
  "Armor!": "Mặc Giáp (Armor)!",
  "Oh...my...gosh. I totally shouldn't tell you this, but I know you can keep a secret. Right? (Gossip. Idealistic.)": "Ôi... Chúa... ơi. Lẽ ra tôi hoàn toàn đéo nên kể cho cậu chuyện này, nhưng tôi biết cậu có thể giữ bí mật mà. Đúng đéo? (Hay Buôn Chuyện - Gossip. Mộng Tưởng Lý Tưởng Hóa - Idealistic.)",
  "I want to know what these people are dropping in our AO. Get there. Highroad out.": "Tôi muốn biết những người này đang thả cái đéo gì xuống Khu Vực Tác Chiến (AO) của chúng ta. Tới đó đi. Highroad hết (out).",
  "Good Lord, she's got a temper on her.": "Lạy Chúa Lòng Lành, cô ấy đúng là có một sự nóng nảy (temper) rất đáng gờm đấy.",
  "How can I help?": "Tôi có thể giúp gì đéo?",
  "Greene": "Greene"
};

const file = 'output/languages/chunks/btxt_chunk_174.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_174.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk174[r.sourceText]) {
    r.translatedText = chunk174[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 174 successfully!');
