const fs = require('fs');
const chunk152 = {
  "It’s not just that it’s horrible. A place like that could make us sick. We’ve got to disinfect it, or it’s a deathtrap.": "Đéo chỉ là kinh tởm thôi đâu. Một nơi như thế có thể khiến chúng ta đổ bệnh đấy. Chúng ta phải khử trùng nó, nếu đéo thì nó sẽ là một cái bẫy tử thần.",
  "Found some food.": "Tìm thấy một ít thức ăn rồi.",
  "Oh shit! Oh shit! Oh shit! Oh shit!": "Ôi cứt! Ôi cứt! Ôi cứt! Ôi cứt!",
  "I'd feel more comfortable having you along in case things go bad.": "Tôi sẽ cảm thấy an tâm hơn nếu có cậu đi cùng trong trường hợp mọi chuyện trở nên tồi tệ.",
  "You gonna keep us waiting out here 'til we get killed or what?": "Cậu định để chúng tôi đợi ngoài này cho đến khi bị giết hay sao?",
  "Got a rucksack full of useful resources.": "Đã lấy được một chiếc ba lô chứa đầy những tài nguyên hữu ích.",
  "Any tips on making this construction go faster?": "Có mẹo nào để tiến trình xây dựng này diễn ra nhanh hơn đéo?",
  "Okay, just about done. How we looking?": "Được rồi, gần xong rồi. Trông thế nào?",
  "We really need to get moving.": "Chúng ta thực sự cần phải di chuyển thôi.",
  "We need to do something about our lack of beds. People aren't getting enough rest. - %1$s": "Chúng ta cần phải làm gì đó với việc thiếu giường ngủ. Mọi người đang đéo được nghỉ ngơi đầy đủ. - %1$s",
  "DISCOVERED: Friendly Survivors": "ĐÃ PHÁT HIỆN: Những Người Sống Sót Thân Thiện",
  "Annabelle": "Annabelle",
  "We got a horde that needs clearing out.": "Chúng ta có một bầy horde cần phải dọn dẹp.",
  "We're taking you to HQ. Apparently, your research is our best hope for curing this thing.": "Chúng tôi sẽ đưa ông đến Trụ sở chính (HQ). Có vẻ như nghiên cứu của ông là hy vọng tốt nhất để chúng tôi chữa khỏi thứ dịch bệnh này.",
  "JOURNAL: Memento": "NHẬT KÝ: Kỷ Vật (Memento)",
  "Bam, crush that skull.": "Bùm, đập nát cái sọ đó đi.",
  "Posit one one tango mike papa two five kilo zero five mike. [message end tone]": "Tọa độ một một tango mike papa hai năm kilo không năm mike. [tiếng bíp kết thúc tin nhắn]",
  "Card Games": "Các Trò Chơi Bài (Card Games)",
  "Lizbeth": "Lizbeth",
  "Aubrey": "Aubrey",
  "LILY RITTER. Restores your Maximum Stamina.": "LILY RITTER. Phục hồi Mức Thể Lực Tối Đa (Maximum Stamina) của bạn.",
  "Vehicle Sounds": "Âm Thanh Xe Cộ",
  "Uhh, isn't that suicide?": "Uhh, đéo phải thế là tự sát sao?",
  "Harman": "Harman",
  "Hold [ul_aim] to Survey": "Giữ [ul_aim] để Khảo Sát (Survey)",
  "The hell's going on there?": "Cái quái gì đang diễn ra ở đó vậy?",
  "Aspiring Rapper": "Rapper Đầy Tham Vọng",
  "Welcome Back": "Chào Mừng Trở Lại",
  "Christmas dinner comes early this year, folks.": "Bữa tối Giáng sinh đến sớm vào năm nay rồi, bà con ơi.",
  "Quiet Search": "Tìm Kiếm Im Lặng",
  "Rowley": "Rowley",
  "Alan was MIA for a while, but he has returned. - %1$s": "Alan đã mất tích (MIA) một thời gian, nhưng anh ấy đã trở lại rồi. - %1$s",
  "That's nice of you to say...": "Cậu thật tốt khi nói vậy...",
  "Damian": "Damian",
  "So I was going to ask if you'd go up to where he died and bring me something of his.": "Vậy nên tôi định hỏi xem cậu có thể lên chỗ anh ấy chết và mang về cho tôi thứ gì đó của anh ấy được đéo.",
  "We could avoid a few fights if we stayed quiet.": "Chúng ta có thể tránh được vài cuộc chạm trán nếu chúng ta giữ im lặng.",
  "Would be dead without our help.": "Đã chết chắc nếu đéo có sự giúp đỡ của chúng ta.",
  "Getting close.": "Đang đến gần rồi.",
  "Requires WEEKLY PINOCHLE GAME.": "Yêu cầu TRÒ CHƠI BÀI PINOCHLE HÀNG TUẦN.",
  "The Operator": "Tay Điều Hành (The Operator)",
  "Maybe their battery died. Maybe their body did. But they're lost to us now.": "Có thể đài của họ hết pin. Có thể cơ thể họ đã bỏ mạng. Nhưng giờ thì họ đã rời xa chúng ta rồi.",
  "A place to grow fresh food. Just getting started.": "Một nơi để trồng thực phẩm tươi sạch. Chỉ mới bắt đầu thôi.",
  "I'm a medic. I think I can make a bigger difference here than I could at some refugee camp.": "Tôi là một nhân viên y tế (medic). Tôi nghĩ tôi có thể tạo ra sự khác biệt lớn ở đây hơn là ở một trại tị nạn nào đó.",
  "The Believer": "Kẻ Cuồng Tín",
  "Carlton": "Carlton",
  "Delay your decision. They may find another ride for him in the meantime.": "Trì hoãn quyết định của bạn. Họ có thể tìm thấy một phương tiện khác cho anh ta trong lúc đó.",
  "Lots of people seem pretty keen to join us.": "Có vẻ như rất nhiều người đang khá háo hức muốn gia nhập với chúng ta đấy.",
  "We're gonna tell everybody else about this, right? I mean, we're not just gonna leave?": "Chúng ta sẽ nói cho mọi người biết về chuyện này, đúng đéo? Ý tôi là, chúng ta đéo thể cứ thế rời đi đúng đéo?",
  "Event: Emergency Repairs": "Sự kiện: Sửa Chữa Khẩn Cấp",
  "Callsign Sasquatch. High speed, low drag. Likes to cut things open.": "Tên gọi Sasquatch. Tốc độ cao, lực cản thấp. Có sở thích mổ xẻ mọi thứ.",
  "Let's get that firing discipline back, okay?": "Hãy lấy lại kỷ luật nổ súng đó, được đéo?",
  "Whatever you do, don't tell him wrestling is staged.": "Dù cậu có làm gì đi nữa, đừng nói với anh ta rằng môn đấu vật là diễn kịch đấy.",
  "Oh my God!": "Ôi Chúa ơi!",
  "Yeah, I know you gotta do your hair and makeup before we go out.": "Phải rồi, tôi biết cậu còn phải làm tóc và trang điểm trước khi chúng ta ra ngoài cơ mà.",
  "RIDGE CABINS": "CÁC CHÒI TRÊN ĐỈNH ĐỒI (RIDGE CABINS)",
  "Melee Specialization": "Đặc Năng Cận Chiến (Melee Specialization)",
  "All right. We'll get everything organized here and then head your way.": "Được rồi. Chúng tôi sẽ sắp xếp mọi thứ ổn thỏa ở đây rồi sẽ đến chỗ cậu.",
  "Travis": "Travis",
  "Buck up. You survived that horde attack, you can survive this.": "Phấn chấn lên nào. Cậu đã sống sót sau cuộc tấn công của bầy horde đó, cậu cũng có thể vượt qua chuyện này thôi.",
  "No more than usual. I usually just lay down for a little while until it passes.": "Đéo nhiều hơn bình thường đâu. Tôi thường chỉ nằm xuống nghỉ một lúc cho đến khi cơn đau trôi qua.",
  "Ma'am, I ain't joking. If your bullshit keeps me from my mission, I'm taking it on the road as a one-man show.": "Thưa cô, tôi đéo nói đùa đâu. Nếu mấy chuyện nhảm nhí của cô cản trở nhiệm vụ của tôi, tôi sẽ tự mình giải quyết nó như một chuyến lưu diễn solo đấy.",
  "You happy now, shit-for-brains? Try a suppressor next time!": "Mày vui chưa hả thằng não chó? Lần sau hãy thử dùng nòng giảm thanh đi!",
  "Shit.": "Chết tiệt.",
  "Airdrops a vehicle near your location.": "Thả dù một chiếc xe xuống gần vị trí của bạn.",
  "Can't do that anymore.": "Đéo thể làm thế được nữa.",
  "Pistol: X-Lock": "Súng Lục (Pistol): Súng Lục X-Lock",
  "%d added to Supply Locker. (Passable medicine supply.)": "Đã thêm %d vào Tủ Đồ Tiếp Tế. (Nguồn cung cấp thuốc men ở mức chấp nhận được.)",
  "+10 Pouting.": "+10 Dỗi hờn.",
  "Guess you're not perfect, huh?": "Có vẻ cậu đéo hoàn hảo như cậu nghĩ nhỉ?",
  "Just a little one....": "Chỉ là một chút thôi....",
  "We don't need to clear out the whole area, just take out the freak.": "Chúng ta đéo cần phải dọn sạch toàn bộ khu vực đâu, chỉ cần khử con quái nhân (freak) đó là được.",
  "Shake it off!": "Tỉnh táo lại đi!",
  "We could use your help. Again.": "Chúng tôi có thể cần đến sự giúp đỡ của cậu. Lần nữa.",
  "That's just about it for our fuel.": "Nhiên liệu của chúng ta chỉ còn chừng đó thôi.",
  "Xbox Gamertag": "Thẻ người chơi (Gamertag) Xbox",
  "+20 Food, Ammo, Medicine, Fuel, and Materials capacity.": "Tăng 20 sức chứa cho Thức Ăn, Đạn Dược, Thuốc Men, Nhiên Liệu và Vật Liệu.",
  "Grenade Launcher: GL M32": "Súng Phóng Lựu: Súng Phóng Lựu GL M32",
  "I'm on this like stink on a bloater.": "Tôi sẽ dính lấy chuyện này như cái mùi hôi thối dính trên người một con bloater vậy.",
  "You're right. I'll take you there now.": "Cậu nói đúng. Tôi sẽ đưa cậu đến đó ngay bây giờ.",
  "Thanks for the assist. I found a freak, and I could use a hand taking it down.": "Cảm ơn vì đã hỗ trợ. Tôi đã tìm thấy một con quái nhân (freak), và tôi cần một người giúp một tay để hạ gục nó.",
  "So, zombies aren't covered by the Geneva Convention, right?": "Vậy, lũ zombie đéo được bảo hộ bởi Công ước Geneva, đúng đéo?",
  "Another Supply Drop?": "Thêm một đợt thả tiếp tế nữa sao?",
  "Gotta give this thing time to run its course.": "Phải cho thứ này thời gian để nó phát huy tác dụng.",
  "Racks": "Giá Đỡ (Racks)",
  "Computer printout on personal letterhead, mailed two weeks ago.": "Bản in máy tính trên giấy có tiêu đề cá nhân, được gửi từ hai tuần trước.",
  "Zombies weren't enough, now we gotta deal with super flu?": "Lũ zombie vẫn chưa đủ hay sao, bây giờ chúng ta lại phải đối phó với cái thứ siêu cảm cúm này nữa à?",
  "Oh! The army. Um ... technically, this is your shit, I guess.": "Ồ! Quân đội. Um ... về mặt kỹ thuật, cái này là đồ của các anh, tôi đoán vậy.",
  "Asset Located": "Đã Định Vị Được Mục Tiêu",
  "Completed all hunting missions with Sasquatch.": "Đã hoàn thành tất cả các nhiệm vụ đi săn cùng Sasquatch.",
  "What can I say? I'm a people person. (Sexting aficionado.)": "Tôi có thể nói gì đây? Tôi là một người hòa đồng mà. (Người đam mê nhắn tin gạ tình.)",
  "No problem. I'll call your guys and walk them through it.": "Đéo có gì. Tôi sẽ gọi cho người của cô và hướng dẫn họ cách làm.",
  "YOUR NEW HOME": "NGÔI NHÀ MỚI CỦA BẠN",
  "Just the six of you?": "Chỉ sáu người các cậu thôi sao?",
  "So this is my life now? Whatever, let's go.": "Vậy đây là cuộc sống của tôi bây giờ sao? Sao cũng được, đi thôi.",
  "For medical treatment.": "Để điều trị y tế.",
  "What you gonna do when I run wild on you?": "Cậu định làm gì khi tôi nổi cơn thịnh nộ với cậu đây?",
  "Now what are we going to do?": "Giờ thì chúng ta sẽ làm gì đây?",
  "We're clear.": "Khu vực đã an toàn.",
  "You should join us.": "Cậu nên gia nhập với chúng tôi.",
  "FOOD RESOURCE. A few of these might be stale, but they should still be edible.": "NGUỒN THỰC PHẨM (FOOD RESOURCE). Một số thứ trong này có thể đã bị thiu, nhưng có lẽ chúng vẫn có thể ăn được."
};

const file = 'output/languages/chunks/btxt_chunk_152.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_152.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk152[r.sourceText]) {
    r.translatedText = chunk152[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 152 successfully!');
