const fs = require('fs');
const chunk106 = {
  "121 STORY Soldier": "121 STORY Người lính",
  "Durable with reliable bolt action.": "Bền bỉ với cơ chế nạp đạn (bolt action) đáng tin cậy.",
  "20%": "20%",
  "Virginia": "Virginia",
  "Well, when you get drunk you do kinda stumble around like a zombie. Can't blame somebody for taking a shot at you.": "Chà, khi say rượu thì cậu đi loạng choạng chẳng khác gì một con zombie. Không thể trách người ta lỡ tay bắn cậu được.",
  "Lily, we don't have time!": "Lily, chúng ta không có thời gian đâu!",
  "Jaiden": "Jaiden",
  "Survive the Zombie Siege": "Sống sót qua đợt Cuộc vây hãm của Zombie",
  "%s Acquired!": "Đã Nhận Được %s!",
  "And to think, I actually had hope for this generation.": "Và thử nghĩ xem, tôi đã từng thực sự kỳ vọng vào thế hệ này.",
  "It's sort of an odd couple thing to see the two of them spending so much time together, but I'm glad to see it. Seems like %1$s is a good influence on %2$s. - %3$s": "Thật hơi kỳ lạ khi thấy hai người họ dành quá nhiều thời gian ở bên nhau, nhưng tôi rất vui khi thấy điều đó. Có vẻ như %1$s có ảnh hưởng tốt đến %2$s. - %3$s",
  "Macklin": "Macklin",
  "That's why you wanted this little bit of quality time?": "Đó là lý do cậu muốn có chút thời gian riêng tư chất lượng này sao?",
  "What about lesions? Have you developed any lesions?": "Thế còn các vết thương lở loét? Cậu có bị nổi bất kỳ vết loét nào chưa?",
  "%d Facilities Built": "Đã Xây Dựng %d Cơ sở",
  "Appreciate you taking care of this for us. Mickey's right, he's not likely to make it himself.": "Cảm ơn cậu đã giải quyết chuyện này giúp chúng tôi. Mickey nói đúng, anh ta không thể tự mình vượt qua được đâu.",
  "Showed those motherfuckers what's what, didn't we?": "Đã cho bọn khốn đó nếm mùi rồi, phải không?",
  "Perez": "Perez",
  "They're preliminary, we'll have to do a full work-up back at base, but... yes ma'am, they appear to be.": "Đó mới chỉ là bước đầu, chúng ta sẽ phải kiểm tra toàn diện khi về căn cứ, nhưng... vâng thưa cô, có vẻ là chúng.",
  "More of 'em coming.": "Thêm một đám nữa đang đến.",
  "Doesn't take everybody. Just one.": "Không cần tất cả mọi người. Chỉ cần một người thôi.",
  "Could be trouble up ahead.": "Có thể có rắc rối ở phía trước đấy.",
  "XP bonus from Reading Lights!": "Thưởng XP nhờ Đèn Đọc Sách!",
  "Something's Missing": "Thiếu Thứ Gì Đó",
  "Upgrade the Radio": "Nâng cấp Bộ đàm (Radio)",
  "You seem awfully excited about this place.": "Cậu có vẻ vô cùng phấn khích về nơi này nhỉ.",
  "Come on. We'll go see to your friend.": "Đi nào. Chúng ta sẽ đi thăm bạn cậu.",
  "I've had just about enough of this shit.": "Tôi đã chịu đựng đủ cái thứ rác rưởi này rồi.",
  "Plug your ears!": "Bịt tai lại!",
  "Here's the thing. People can't take the constant yelling and abuse.": "Vấn đề là thế này. Mọi người không thể chịu đựng được những lời la mắng và lăng mạ triền miên đâu.",
  "So I've been thinking about stuff we could do to improve this place, but we just don't have enough materials to do much.": "Nên tôi đang nghĩ về những việc chúng ta có thể làm để cải thiện nơi này, nhưng chúng ta lại không có đủ vật liệu để làm gì nhiều.",
  "Well, I think I've seen enough for now.": "Chà, tôi nghĩ tôi đã xem đủ cho lúc này rồi.",
  "We just got lucky.": "Chúng ta chỉ là ăn may thôi.",
  "5 GENERIC B.W. Wilson": "5 GENERIC B.W. Wilson",
  "The Defender": "Người Phòng Thủ",
  "I'll take whatever help we can get, but ... listeners, keep your eyes open. It doesn't take much for an army to turn into a mob.": "Tôi sẽ nhận bất cứ sự trợ giúp nào có thể, nhưng... quý thính giả, hãy luôn mở to mắt. Từ một đội quân biến thành một lũ cướp bóc chẳng mất nhiều thời gian đâu.",
  "Not enough soldiers to spare.": "Không có đủ lính để cử đi đâu.",
  "Got it!": "Hiểu rồi!",
  "I saw the army pull out of Danforth. I know they left this town to die.": "Tôi đã thấy quân đội rút khỏi Danforth. Tôi biết họ bỏ mặc thị trấn này cho chết.",
  "Lead the Runners Home": "Dẫn đường cho đội Vận chuyển về nhà",
  "We still have people out there.": "Chúng ta vẫn còn người ở ngoài đó.",
  "What is that?": "Cái gì thế?",
  "Doghouse to Greyhound One, we're showing that the asset is ... not at your position.": "Doghouse gọi Greyhound One, chúng tôi thấy mục tiêu... không nằm ở vị trí của các anh.",
  "Tactical version of the 870.": "Phiên bản chiến thuật của khẩu 870.",
  "Took a beating for late payments to the Wilkersons.": "Bị ăn một trận đòn vì thanh toán muộn cho nhà Wilkerson.",
  "That’s it. We’re full up, unless someone wants to ride on the roof.": "Vậy đó. Chúng ta đã kín chỗ, trừ phi có ai muốn ngồi trên nóc xe.",
  "Hey. There's something weird coming over the radio. It's really strong, like it's super close-by.": "Này. Có thứ gì đó kỳ lạ phát qua bộ đàm. Tín hiệu rất mạnh, giống như nó ở ngay gần đây.",
  "Painkillers": "Thuốc Giảm Đau",
  "Morale Issue: Anger": "Vấn đề Nhuệ Khí: Tức Giận",
  "Hang on, we got you covered.": "Khoan đã, chúng tôi yểm trợ cho cậu.",
  "I used to shop at all the organic food places, farmer's markets, shit like that. If it wasn't holistic, pesticide-free and lovingly hand-picked by hippies on a commune somewhere, I wouldn't eat it.": "Tôi từng mua sắm ở mọi cửa hàng thực phẩm hữu cơ, chợ nông sản, mấy cái thứ đại loại thế. Nếu đó không phải là thực phẩm toàn phần, không thuốc trừ sâu và được mấy gã hippie ở một công xã nào đó tự tay hái một cách cẩn thận, thì tôi sẽ không ăn.",
  "King": "King",
  "Excellent!": "Tuyệt vời!",
  "Locate Thomas Horn": "Xác định vị trí Thomas Horn",
  "Reveals nearby zombies, vehicles, and buildings.": "Phát hiện vị trí của zombie, phương tiện và các tòa nhà lân cận.",
  "Pseudoephedrine": "Pseudoephedrine (Thuốc cảm)",
  "This will get you where you need to go, slowly, and for a price. Four seats of unregulated fares await.": "Chiếc xe này sẽ đưa cậu đến nơi cậu muốn, một cách chậm chạp, và cậu phải trả giá cho nó. Bốn chỗ ngồi với giá vé vô định đang chờ.",
  "Abandon Outpost": "Bỏ Tiền Đồn",
  "Black Friday, this is Highroad Actual. I thought you should know this.": "Black Friday, đây là Highroad Actual. Tôi nghĩ anh nên biết điều này.",
  "I have seen things that you cannot possibly imagine.": "Tôi đã chứng kiến những thứ mà cậu không thể nào tưởng tượng nổi đâu.",
  "Demolitions Training": "Huấn Luyện Phá Dỡ",
  "Liu": "Liu",
  "Coming in behind us!": "Đang đến từ phía sau chúng ta!",
  "We all feel that pain, but we also take joy in the memories they left us.": "Tất cả chúng ta đều cảm nhận được nỗi đau đó, nhưng chúng ta cũng tìm thấy niềm vui trong những ký ức mà họ để lại.",
  "That's almost too easy!": "Thế thì gần như là quá dễ dàng!",
  "Navigate the World: Press [jump] to interact with a range of environmental objects, from climbing fences, hurdling barriers, to crashing through windows. Stealth: Hold [cover] to crouch and enter stealth mode. Use [moveforward], [moveleft], [moveback], [moveright] to move while crouched. . Tap [cover] again to exit crouch. Crouching while in bushes provides additional stealth. Sneak up on wandering zombies to deliver an instantaneous killing blow. Discovery: Use [xi_use] to interact with objects in the world such as opening doors, searching containers, and barricading windows. Express Yourself: Experiment with the effects of the different emotes your character can display. Press [emote1], [emote4], [emote3], or [emote2] to emote.": "Khám Phá Thế Giới: Nhấn [jump] để tương tác với các vật thể xung quanh, từ leo rào, nhảy rào chắn, cho đến lao qua cửa sổ. Hành Động Lén Lút: Giữ [cover] để ngồi xổm và vào chế độ lén lút. Dùng [moveforward], [moveleft], [moveback], [moveright] để di chuyển khi đang ngồi xổm. Nhấn [cover] lần nữa để đứng lên. Ngồi xổm trong các bụi rậm sẽ tăng độ ẩn nấp. Lẻn ra sau những con zombie đang đi lang thang để thực hiện đòn kết liễu tức thì. Khám Phá: Dùng [xi_use] để tương tác với các vật thể trong thế giới như mở cửa, lục lọi rương chứa, và gia cố cửa sổ. Thể Hiện Cảm Xúc: Thử các hiệu ứng biểu cảm khác nhau của nhân vật. Nhấn [emote1], [emote4], [emote3], hoặc [emote2] để hiển thị biểu cảm.",
  "You've taken a lot of damage, reducing your MAXIMUM VITALITY.": "Bạn đã chịu nhiều sát thương, làm giảm SINH LỰC TỐI ĐA của bạn.",
  "Sweep Kick": "Cú Đá Quét",
  "Close call for those two, looks like the Army isn't here to protect and serve. -%1$s": "Thật nguy hiểm cho hai người đó, có vẻ như Quân Đội ở đây không phải để bảo vệ và phục vụ nhân dân đâu. -%1$s",
  "You especially.": "Đặc biệt là cậu.",
  "Aim": "Ngắm Bắn",
  "Judge Lawton stepped up. Got us all organized, kept people from each other's throats...": "Thẩm Phán Lawton đã đứng ra. Tổ chức lại tất cả, ngăn mọi người cắn xé lẫn nhau...",
  "Our supplies are packed tighter and smarter now. We can store a lot more now, and it lasts significantly longer ... though it can be hard to find what you need in a pinch.": "Nguồn dự trữ của chúng ta nay được đóng gói chặt chẽ và thông minh hơn. Bây giờ chúng ta có thể chứa được nhiều hơn, và bảo quản lâu hơn đáng kể... mặc dù lúc nguy cấp thì hơi khó để tìm ra thứ cần thiết.",
  "There's a good kitchen here. Just need to clear out all the chaos and we can start using it.": "Có một nhà bếp tốt ở đây. Chỉ cần dọn dẹp mớ hỗn độn này là chúng ta có thể bắt đầu sử dụng.",
  "Let's hole up here a while longer. There's still some stuff I want to do before we go.": "Hãy nương náu ở đây thêm một lát. Vẫn còn vài việc tôi muốn làm trước khi đi.",
  "Stay sharp. This ain't over.": "Giữ tỉnh táo nhé. Vẫn chưa xong đâu.",
  "Keyah": "Keyah",
  "My time is up. Use your helicopter to save somebody else.": "Thời gian của tôi đã hết. Hãy dùng trực thăng cứu người khác đi.",
  "That's not a normal zed.": "Đó không phải là một con Zed bình thường đâu.",
  "What can I do?": "Tôi có thể làm gì?",
  "Could use some help to get out of here.": "Tôi cần một chút trợ giúp để rời khỏi đây.",
  "We should check on Eli.": "Chúng ta nên đi kiểm tra Eli.",
  "Waiting for you.": "Đang đợi cậu.",
  "Break its fucking skull!": "Đập nát cái sọ chết tiệt của nó đi!",
  "132 STORY Job Wilkerson": "132 STORY Job Wilkerson",
  "Nobody dies on our watch!": "Không một ai được phép chết trong ca gác của chúng ta!",
  "Come with me. You need to get out of your own head for a little while.": "Đi theo tôi. Cậu cần phải thoát khỏi những suy nghĩ trong đầu một lát.",
  "Welcome to State of Decay! Join your fellow survivors at forums.undeadlabs.com for game tips and news!": "Chào mừng đến với State of Decay! Hãy tham gia cùng những người sống sót khác tại forums.undeadlabs.com để biết thêm các mẹo và tin tức về game!",
  "Public Restroom": "Nhà Vệ Sinh Công Cộng",
  "Please. You try to help people, and you just get taken advantage of. Way of the world.": "Thôi đi. Cậu cố gắng giúp người, và cậu chỉ bị lợi dụng thôi. Thói đời là thế.",
  "Drew": "Drew",
  "Ed's hitting on the girl at the bait shop. Again. God help us all. - %1$s": "Ed lại đang tán tỉnh cô gái ở cửa hàng mồi câu. Lại nữa. Chúa cứu rỗi chúng ta. - %1$s",
  "I want to be angry at Westen's father for using political leverage to save his son ... but in his shoes, I imagine I'd do the same.": "Tôi muốn tức giận cha của Westen vì đã sử dụng đòn bẩy chính trị để cứu con trai mình... nhưng nếu ở vào vị trí của ông ấy, tôi nghĩ tôi cũng sẽ làm y như vậy.",
  "BUILT: Watchtower": "ĐÃ XÂY: Tháp Canh",
  "What were you thinking? You know nobody's supposed to go out there alone.": "Cậu đang nghĩ gì vậy? Cậu biết là không một ai được phép ra ngoài đó một mình mà.",
  "Hey, what's that? Looks like a vet's office or something.": "Này, gì kia? Có vẻ như là một phòng khám thú y hay gì đó.",
  "A great idea ... should still give it a try.": "Một ý tưởng tuyệt vời... vẫn nên thử một lần xem sao.",
  "I'm having second thoughts. Hold off for now.": "Tôi đang xem xét lại. Tạm hoãn đã.",
  "DECLINE MISSION. Let them know the futility of their actions.": "TỪ CHỐI NHIỆM VỤ. Hãy cho họ biết những hành động đó đều là vô ích.",
  "REMAINING USES:": "SỐ LẦN SỬ DỤNG CÒN LẠI:"
};

const file = 'output/languages/chunks/btxt_chunk_106.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_106.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk106[r.sourceText]) {
    r.translatedText = chunk106[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 106 successfully!');
