const fs = require('fs');
const chunk199 = {
  "I already told you, I haven't seen-": "Tôi đã nói với anh rồi cơ mà, tôi đéo hề nhìn thấy-",
  "Anybody up for it?": "Có ai muốn tham gia đéo?",
  "I want you to know the only reason %2$s isn't dead yet is because I respect %3$s. But this isn't over. - %1$s": "Tôi muốn cậu biết rằng lý do duy nhất khiến cho %2$s vẫn chưa bị giết chết là bởi vì tôi rất tôn trọng %3$s. Nhưng chuyện này chắc chắn sẽ đéo kết thúc dễ dàng như vậy đâu. - %1$s",
  "%3$s might not make it.": "%3$s có thể sẽ đéo qua khỏi đâu.",
  "UPGRADED: Surgery": "ĐÃ NÂNG CẤP XONG (UPGRADED): Phòng Phẫu Thuật (Surgery)",
  "Uh, hi.": "Uh, chào.",
  "I'm not sure this is the right place.": "Tôi đéo chắc rằng đây có phải là một địa điểm thích hợp hay đéo nữa.",
  "%3$s seems to have calmed down a lot. -%1$s": "Dường như %3$s đã có thể bình tĩnh lại được phần nào rồi. -%1$s",
  "+42%": "+42%",
  "Trusty Fire Axe": "Chiếc Rìu Cứu Hỏa Đáng Tin Cậy (Trusty Fire Axe)",
  "Tool Knowledge": "Kiến Thức Về Cách Sử Dụng Các Loại Công Cụ (Tool Knowledge)",
  "Yeah! Kicked your sorry asses!": "Yeah! Đá đít (Kicked) lũ khốn nạn thảm hại các người!",
  "Just once I'd like to have a showdown at high noon....": "Chỉ một lần duy nhất thôi, tôi thực sự rất muốn có được một cuộc đối đầu (showdown) quyết liệt vào đúng buổi trưa....",
  "Mercy Victim": "Nạn Nhân Của Lòng Thương Xót (Mercy Victim)",
  "It looks like somebody was ripped to pieces inside the RV. Probably several somebodies. It smells like the inside of a Bloater. It can't be safe to ride in a mess like that. We're going to have to clean and disinfect the whole thing. (RV FACILITY)": "Trông có vẻ như một kẻ nào đó đã bị xé xác thành từng mảnh vụn ngay bên trong chiếc xe RV cmnr. Có lẽ là vài ba kẻ nào đó. Nơi này hiện đang bốc mùi thối rữa hệt như phần nội tạng bên trong của một con Bloater vậy. Chắc chắn sẽ đéo thể nào an toàn nếu như cứ lái một chiếc xe mang theo cả một đống hỗn độn (mess) bẩn thỉu như thế này được. Chúng ta sẽ cần phải dọn dẹp và tiến hành khử trùng (disinfect) lại toàn bộ mọi thứ. (CƠ SỞ VẬT CHẤT TRÊN XE RV RV FACILITY)",
  "Yeah, that's definitely a horde.": "Yeah, đó chắc chắn là một bầy horde.",
  "Zombie Horde Alerted!": "Bầy Zombie Horde Đã Bị Báo Động (Alerted)!",
  "This is where we'll store the bulk of our supplies once we've cleared it out.": "Đây sẽ là nơi mà chúng ta dự định dùng để cất trữ (store) phần lớn các loại vật tư đồ tiếp tế (supplies) của mình một khi chúng ta đã dọn dẹp sạch sẽ được nó.",
  "She was being ground evac'd on the other side of town ... but the way the highways are jammed up, we think she's stranded.": "Cô ấy đang được di tản (evac'd) bằng đường bộ ở phía bên kia của thị trấn... nhưng với cái tình trạng mà các đường cao tốc (highways) hiện đang bị tắc nghẽn vô cùng nghiêm trọng như thế này, chúng tôi e rằng rất có thể cô ấy đã bị mắc kẹt lại cmnr.",
  "No sir. We'll get the next one, sir. Black Friday out.": "Đéo có chuyện đó đâu thưa ngài. Chúng tôi sẽ nhanh chóng tóm được nó ở mục tiêu tiếp theo, thưa ngài. Black Friday xin hết.",
  "CONTACT: Sharpshooting": "LIÊN HỆ (CONTACT): Huấn Luyện Kỹ Năng Bắn Tỉa (Sharpshooting)",
  "Modafinil": "Modafinil",
  "A common gas generator, salvaged from a civilian shop. It burns through fuel like a mofo, but it keeps the equipment running.": "Một chiếc máy phát điện (generator) chạy bằng khí đốt thông thường, được trục vớt từ một cửa hàng dân dụng. Nó ngốn nhiên liệu (fuel) khát máu hệt như một thằng khốn nạn, nhưng bù lại nó có thể giúp cho các thiết bị luôn được duy trì trạng thái hoạt động.",
  "Upgrade to Greenhouse": "Tiến Hành Nâng Cấp Lên Thành Nhà Kính Trồng Cây (Greenhouse)",
  "I never thought I'd be living in a glorified shack, eating beans out of a can. You country people may be used to that, but I'm sure not.": "Tôi đéo bao giờ có thể nghĩ rằng sẽ có một ngày mình phải sống trong một cái túp lều (shack) tồi tàn, và ăn những hạt đậu (beans) trực tiếp từ một cái hộp thiết. Những người dân quê mùa (country people) như các người có lẽ đã quá quen thuộc với lối sống đó rồi, nhưng chắc chắn là tôi thì đéo bao giờ.",
  "97 STORY Darryl White": "97 CỐT TRUYỆN (STORY) Darryl White",
  "A lot of people have been noticing that the Army broadcasts have stopped. I'm not sure what it means, but it can't be good. - %1$s": "Rất nhiều người đã nhận ra được rằng những chương trình phát sóng (broadcasts) của lực lượng Quân đội đã hoàn toàn bị ngừng lại. Tôi đéo dám chắc chắn rằng điều này có ý nghĩa gì đéo, nhưng nó có thể đéo phải là một điềm báo tốt lành đéo đâu. - %1$s",
  "Small-caliber version of the famous spy's gun.": "Phiên bản sử dụng đạn cỡ nòng nhỏ hơn của một loại súng cực kỳ nổi tiếng dành riêng cho những tên điệp viên.",
  "The hell? Do we have any food left in this place?": "Cái đéo gì thế này? Liệu chúng ta có còn sót lại bất kỳ một chút thức ăn (food) nào ở trong cái nơi này đéo?",
  "I've always felt like I was specially blessed.": "Tôi vẫn luôn cảm thấy như thể bản thân mình đã nhận được một sự ban phước (blessed) cực kỳ đặc biệt vậy.",
  "Lived on a diet of nachos, cookies, and anime throughout high school. Has had trouble sleeping since he left home.": "Sống dựa vào một chế độ ăn kiêng (diet) bao gồm nachos, bánh quy (cookies), và cày anime (anime) trong suốt quãng thời gian học trung học. Đã luôn gặp phải rắc rối với giấc ngủ (sleeping) kể từ khi anh ấy rời khỏi nhà.",
  "We're lucky that HVT has lasted as long as they have. If we don't get there ASAP, we'll be sending them home in a bag.": "Chúng ta thực sự đã rất may mắn khi mà cái Mục Tiêu Có Giá Trị Cao (HVT) đó vẫn có thể kéo dài mạng sống của bọn họ được lâu đến như vậy. Nếu như chúng ta đéo thể có mặt ở đó CÀNG SỚM CÀNG TỐT (ASAP), chúng ta chắc chắn sẽ phải gửi trả bọn họ về nhà ở bên trong một cái túi đựng xác mất thôi.",
  "Skull SUV": "Chiếc Xe SUV Đầu Lâu (Skull SUV)",
  "You have 30 minutes remaining in your trial. Press [xi_start] to unlock the full game.": "Bạn chỉ còn lại 30 phút ở trong phiên bản dùng thử (trial) của mình. Hãy nhấn [xi_start] để mở khóa toàn bộ trò chơi (full game).",
  "A little help over here?": "Có ai đó tới đây giúp đỡ tôi một chút được đéo?",
  "I won't lie to you...our fate's in your hands.": "Tôi sẽ đéo nói dối cậu đâu... số phận (fate) của tất cả chúng tôi hiện tại đều đang được đặt trọn ở trong lòng bàn tay của cậu.",
  "Weaponry": "Chuyên Về Các Loại Vũ Khí (Weaponry)",
  "I get the feeling that you’re a bit more tense than the others.": "Tôi có một cảm giác rằng cậu dường như đang trở nên căng thẳng (tense) hơn một chút so với những người khác.",
  "Best watch that mouth, boy. Can't hide behind momma's skirts no more.": "Tốt nhất là hãy cẩn thận với cái miệng của mình đấy, nhóc con à. Mày sẽ đéo thể nào trốn núp mãi ở phía sau cái váy của mẹ mày được nữa đâu.",
  "Multiple zeds, clustered and moving.": "Phát hiện ra có rất nhiều con zeds, đang tụ tập thành từng nhóm (clustered) và đang di chuyển.",
  "All this Stamina and I didn't even have to dope! (Special Techniques: Marathon, Combat Endurance)": "Có được toàn bộ lượng Thể Lực (Stamina) dồi dào này mà đéo hề cần phải sử dụng doping! (Các Kỹ Thuật Đặc Biệt Special Techniques: Luyện Tập Chạy Marathon, Sức Bền Trong Chiến Đấu Combat Endurance)",
  "That was a mistake.": "Đó quả thực là một sai lầm.",
  "xi_triggerl": "xi_triggerl",
  "Will you two shut up and get moving? I'm not getting paid to babysit.": "Hai người các cậu có thể câm miệng lại và tiếp tục di chuyển được đéo? Tôi đéo hề được trả tiền (paid) để đi làm cái công việc của một bảo mẫu giữ trẻ (babysit) đéo đâu nhé.",
  "Fuck you!": "Địt mẹ mày!",
  "Look, we're stretched pretty thin. Any help you could give us would be appreciated.": "Nghe đây, lực lượng của chúng tôi hiện đang bị kéo căng đến mức gần như là kiệt sức cmnr. Bất kỳ một sự trợ giúp đéo nào mà cậu có thể cung cấp cho chúng tôi đều sẽ được chúng tôi vô cùng trân trọng và cảm kích.",
  "Waypoint (Search)": "Điểm Đánh Dấu Tọa Độ Waypoint (Nhằm Mục Đích Tìm Kiếm Search)",
  "Black Friday to ... who is this again?": "Black Friday gọi cho... lại là ai đây?",
  "Turner": "Turner",
  "ATTITUDE: Sullen": "THÁI ĐỘ (ATTITUDE): Vô Cùng Ủ Rũ Buồn Bã (Sullen)",
  "1911 frame, upgraded for precision shooting.": "Khung súng 1911, đã được nâng cấp (upgraded) để có thể thực hiện những cú bắn với độ chuẩn xác cực cao.",
  "SitRep: Dallas": "Báo Cáo Tình Hình (SitRep): Dallas",
  "Portillo": "Portillo",
  "I know they'd been sick for a while... I guess one of them succumbed and turned. They were dead before they knew what hit them.": "Tôi biết là bọn họ đã bị ốm được một thời gian rồi... Tôi đoán là một trong số bọn họ đã đéo thể nào qua khỏi và bắt đầu biến đổi (turned). Bọn họ đã chết trước khi bọn họ kịp nhận ra được thứ gì đã tấn công mình.",
  "We're here to follow orders, remember? And Hadley may be an idiot, but he's still a human being.": "Chúng ta ở đây là để tuân theo các mệnh lệnh (orders), có nhớ đéo? Và Hadley có thể là một thằng ngu ngốc, nhưng anh ấy dù sao cũng vẫn là một con người (human being) mà.",
  "RECRUIT SOLDIER. Escort this soldier home to join your unit.": "CHIÊU MỘ NGƯỜI LÍNH (RECRUIT SOLDIER). Hộ tống người lính (soldier) này quay trở về nhà một cách an toàn để bọn họ có thể gia nhập vào đơn vị (unit) của bạn.",
  "Created 3 MREs": "Đã Chế Tạo (Created) Thành Công 3 Khẩu Phần Ăn Dành Cho Quân Đội (MREs)",
  "TIP: The blue ring shows your mission objective.": "MẸO (TIP): Vòng tròn màu xanh lam sẽ hiển thị trực tiếp cho mục tiêu nhiệm vụ (mission objective) của bạn.",
  "That's what your mom said.": "Đó chính là những gì mà mẹ cậu đã nói.",
  "Yeah. Just doesn't seem like we can catch a break.": "Yeah. Dường như chúng ta sẽ đéo thể nào có được một phút nghỉ ngơi (break) đéo nào cả.",
  "Come on, come on, don’t be dead. Answer me! Don’t be dead!": "Thôi nào, thôi nào, đừng có chết mà. Hãy mau trả lời tôi đi! Đừng có chết!",
  "If you're gonna keep going, you better try some painkillers.": "Nếu như cậu vẫn muốn tiếp tục tiến về phía trước, tốt hơn hết là cậu nên thử uống một vài viên thuốc giảm đau (painkillers) đi.",
  "Gabby": "Gabby",
  "Weber": "Weber",
  "Sleeping Area": "Khu Vực Ngủ Nghỉ (Sleeping Area)",
  "32 MIL Pfc Rennie Arellano": "32 QUÂN ĐỘI (MIL) Binh Nhất (Pfc) Rennie Arellano",
  "I've been talking to some of the other survivors.": "Tôi vừa mới nói chuyện với một số những người sống sót (survivors) khác.",
  "He really cared, not just about surviving, but about doing the right thing.": "Anh ấy thực sự rất quan tâm, đéo chỉ đơn thuần là việc cố gắng để sống sót (surviving), mà là về việc thực hiện những điều đúng đắn.",
  "Shotgun: Warrior": "Súng Shotgun: Warrior",
  "FUEL RESOURCE. Great for making petrol bombs.": "NGUỒN NHIÊN LIỆU (FUEL RESOURCE). Vô cùng tuyệt vời để có thể sử dụng chế tạo ra các quả bom xăng (petrol bombs).",
  "So she fucked me instead. I don't want to be one of them. I need you to do the right thing.": "Cho nên thay vào đó cô ấy đã quyết định chơi khăm (fucked) tôi. Tôi đéo muốn phải trở thành một trong số bọn chúng đâu. Tôi cần cậu hãy thực hiện những điều đúng đắn.",
  "Alan? Gee, thanks.": "Alan ư? Trời ạ, cảm ơn nhé.",
  "Replaces the vehicle's doors.": "Cho phép tiến hành thay thế (Replaces) lại các cánh cửa (doors) của chiếc xe di chuyển.",
  "Reid": "Reid",
  "Very popular \"G\" line of firearms. Polymer frame.": "Một trong những dòng súng cầm tay mang mã \"G\" cực kỳ phổ biến. Sở hữu phần khung súng được làm bằng vật liệu polymer.",
  "I didn't come out here to talk about my feelings, alright?": "Tôi đéo ra ngoài này để nói chuyện với cậu về những cảm xúc (feelings) của bản thân mình, được chứ?",
  "I saw that Lily's brother was in trouble, but couldn't help. - %1$s": "Tôi đã nhìn thấy anh trai của Lily đang gặp rắc rối, nhưng đéo thể nào ra tay cứu giúp được anh ấy. - %1$s",
  "And secure that perimeter for God's sake! We may have shit the bed on containing this thing from day one, but that's no excuse not to not do this right.": "Và hãy mau chóng thắt chặt kiểm soát ở khu vực vành đai (perimeter) đó vì Chúa đi! Có thể chúng ta đã phá hỏng hoàn toàn cái việc cố gắng ngăn chặn thứ dịch bệnh này ngay từ ngày đầu tiên cmnr, nhưng đó đéo phải là lý do để chúng ta đéo cố gắng thực hiện nó một cách đúng đắn.",
  "... but they'll be back before long.": "... nhưng bọn họ chắc chắn sẽ nhanh chóng quay trở lại ngay thôi.",
  "Ward": "Ward",
  "You think you got what it takes to go toe to toe with me? Think again!": "Mày nghĩ rằng mày có đủ khả năng để có thể đối đầu trực diện một chọi một (toe to toe) với tao ư? Hãy suy nghĩ lại đi nhé!",
  "Let's just get this over with.": "Hãy nhanh chóng giải quyết xong cái việc chết tiệt này đi.",
  "Well, let's get it finished, quick. Last thing I want to see is you get bored.": "Chà, vậy thì hãy nhanh chóng hoàn thành dứt điểm nó đi. Việc cuối cùng mà tôi muốn được nhìn thấy chính là việc cậu bắt đầu cảm thấy buồn chán (bored).",
  "Equip": "Trang Bị (Equip)",
  "69 GENERIC Mona Adkins": "69 CHUNG (GENERIC) Mona Adkins",
  "Look, the medicine situation here is critical. We need to get more, and we need to get it soon.": "Nghe đây, tình trạng khan hiếm thuốc men (medicine) ở đây hiện đang rơi vào mức cực kỳ nguy hiểm. Chúng ta đang rất cần phải thu thập được nhiều thuốc hơn nữa, và chúng ta cần phải có được nó càng sớm càng tốt.",
  "%+d Barrels of Fuel": "%+d Thùng Nhiên Liệu (Fuel)",
  "Let me go find more.": "Hãy để cho tôi đi ra ngoài để tìm kiếm thêm nhiều hơn nữa.",
  "Books Completed": "Số Lượng Sách Đã Được Đọc Xong (Books Completed)",
  "Not to complain…but it was kinda nice having a car.": "Đéo phải là tôi muốn phàn nàn đéo đâu... nhưng việc sở hữu được một chiếc xe ô tô (car) cũng khá là tuyệt vời đấy chứ.",
  "Advice: Upgrade to Munitions Shop": "Lời Khuyên (Advice): Hãy Nâng Cấp (Upgrade) Lên Thành Cửa Hàng Đạn Dược (Munitions Shop)",
  "Research Steel Pipe Bomb": "Tiến Hành Nghiên Cứu Chế Tạo Bom Ống Thép (Steel Pipe Bomb)",
  "My sympathies.": "Xin gửi lời chia buồn (sympathies) sâu sắc nhất của tôi.",
  "Come on, up you go. We need to get you out of your funk.": "Thôi nào, hãy mau đứng dậy đi. Chúng tôi cần phải giúp cho cậu thoát ra khỏi cái trạng thái hoảng loạn (funk) tồi tệ này.",
  "Hold [sprint] and press [ul_melee_attack] to cut off an enemy's leg.": "Nhấn giữ nút [sprint] và sau đó bấm phím [ul_melee_attack] để có thể chém đứt chân của kẻ địch.",
  "I mean, zombies were inside. We were all freaked. So, we raided the liquor department afterwards, just to take the edge off, you know?": "Ý tôi là, lũ zombies đang ở ngay bên trong. Tất cả chúng tôi đều đang cảm thấy vô cùng sợ hãi (freaked). Do đó, chúng tôi đã quyết định đột kích vào cửa hàng bán rượu ngay sau đó, chỉ để tìm cách xoa dịu đi sự căng thẳng, cậu biết mà?",
  "Josue": "Josue",
  "They could use your help.": "Bọn họ có thể sẽ cần đến sự giúp đỡ của cậu đấy.",
  "How about you and I go find something to hit?": "Cậu nghĩ sao nếu như cậu và tôi cùng nhau đi tìm kiếm một thứ đéo gì đó để đập phá (hit) cho xả stress nhỉ?",
  "Located an area that has FOOD.": "Đã xác định được (Located) một khu vực tiềm năng có chứa THỨC ĂN (FOOD)."
};

const file = 'output/languages/chunks/btxt_chunk_199.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_199.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk199[r.sourceText]) {
    r.translatedText = chunk199[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 199 successfully!');
