const fs = require('fs');
const chunk164 = {
  "Self-Sufficient": "Tự Cung Tự Cấp (Self-Sufficient)",
  "Haha. Nicely done.": "Haha. Làm tốt lắm.",
  "Journal": "Nhật Ký (Journal)",
  "LOG: Entering Danforth": "NHẬT KÝ (LOG): Đang tiến vào Danforth",
  "Adebayo": "Adebayo",
  "One of our loyal listeners just got a visit from the army, and they're being airlifted out as we speak.": "Một trong những thính giả trung thành của chúng ta vừa được quân đội ghé thăm, và họ đang được không vận rời đi ngay lúc chúng ta đang nói chuyện đây.",
  "Welcome. I suppose you've heard our broadcasts? Well, it's all true.": "Chào mừng. Tôi đoán là cậu đã nghe các chương trình phát sóng của chúng tôi rồi đéo? Chà, tất cả đều là sự thật.",
  "Firecrackers, Alarm Clocks, Etc.": "Pháo tép, Đồng hồ báo thức, v.v.",
  "If we didn't have a good stash of building materials, we'd be in trouble.": "Nếu chúng ta đéo có một kho dự trữ Vật Liệu Xây Dựng (Building Materials) tốt, chúng ta sẽ gặp rắc rối to đấy.",
  "Grant": "Grant",
  "I'm kinda blown away by how awesome you are.": "Tôi có hơi bị kinh ngạc trước việc cậu quá đỗi tuyệt vời đấy.",
  "Holy crap, that was loud! Did you guys know that was gonna be so loud? - %1$s": "Vãi cức, to vãi! Các cậu có biết là nó sẽ kêu to như vậy đéo? - %1$s",
  "Now I'm sharing a room with four other people, and if I want any privacy, I've got to brave the zombie-infested streets.": "Bây giờ tôi đang phải ở chung phòng với bốn người khác, và nếu muốn có chút riêng tư, tôi phải dũng cảm đối mặt với những con phố đầy rẫy zombie.",
  "Roger that, Black Friday. Hope you got what we need. Highroad out.": "Đã rõ, Black Friday. Hy vọng các anh có những gì chúng tôi cần. Highroad xin ngừng liên lạc.",
  "TIP: Hold [sprint] to ascend or descend a ladder faster.": "MẸO (TIP): Giữ [sprint] để leo lên hoặc leo xuống thang nhanh hơn.",
  "I wish I could shoot like you. I've gotta practice more.": "Tôi ước gì mình có thể bắn giỏi như cậu. Tôi phải luyện tập nhiều hơn nữa mới được.",
  "Couldn't get a lot out of them, but they sounded scared. Might be worth checking out.": "Đéo khai thác được nhiều thông tin từ họ, nhưng nghe giọng họ có vẻ rất sợ hãi. Có lẽ đáng để đi kiểm tra xem sao.",
  "Safe... for now.": "An toàn... tạm thời là vậy.",
  "Hey, I appreciate it. Too bad I'm, uh, fresh out of ammo, or I'd totally come with you. Totally.": "Này, tôi rất cảm kích. Tiếc là tôi, ờ, vừa mới hết đạn xong, đéo thì tôi hoàn toàn sẽ đi cùng cậu. Hoàn toàn đấy.",
  "Too bad we don't have anybody to staff it.": "Tệ thật, chúng ta đéo có ai để vận hành nó cả.",
  "Beds": "Giường Ngủ",
  "Defend the Workers": "Bảo Vệ Những Người Công Nhân",
  "Everyone got matching tattoos.": "Mọi người đều có hình xăm giống nhau.",
  "If we don't find more meds, the next sick person may not get any better.": "Nếu chúng ta đéo tìm thêm thuốc men, người bệnh tiếp theo có thể sẽ đéo khá hơn được đâu.",
  "Should do a lot to cut back on the spoilage problem.": "Hẳn sẽ làm được nhiều điều để cắt giảm vấn đề hư hỏng thực phẩm đây.",
  "There's a freak.": "Có một con dị dạng (freak) kìa.",
  "Well, antibiotics for dogs aren't any different than antibiotics for people. And it looks like no one's broken in.": "Chà, thuốc kháng sinh cho chó đéo khác gì thuốc kháng sinh cho người đâu. Và có vẻ như đéo có ai đột nhập vào đây cả.",
  "Could we not do this right now? Please?": "Chúng ta có thể đéo làm chuyện này lúc này được đéo? Làm ơn đi?",
  "Better fighters make better survivors.": "Những chiến binh giỏi hơn sẽ là những người sống sót tốt hơn.",
  "Shira Bogatz is on the way to the capital. We weren't able to save her father.": "Shira Bogatz đang trên đường đến thủ đô. Chúng tôi đã đéo thể cứu được cha cô ấy.",
  "Wait, what's the point?": "Khoan đã, mục đích là cái quái gì vậy?",
  "Might be some good stuff in there.": "Có thể có vài món đồ tốt ở trong đó.",
  "Is it that hard to put them on?": "Việc mặc chúng vào khó đến thế sao?",
  "Look, I'm all for sharing freely, but whoever keeps eating my soy cheese could you please stop? I'm lactose intolerant, I can't eat the other kinds. Just a little pretend cheese, that's all I ask! - %1$s": "Nghe này, tôi hoàn toàn ủng hộ việc chia sẻ một cách thoải mái, nhưng bất cứ ai cứ ăn phô mai đậu nành của tôi, làm ơn dừng lại được đéo? Tôi bị chứng đéo dung nạp lactose, tôi đéo thể ăn các loại khác được. Chỉ là một chút phô mai giả thôi mà, đó là tất cả những gì tôi yêu cầu! - %1$s",
  "We're about to head out scavenging. Come along?": "Chúng tôi chuẩn bị ra ngoài để đi nhặt rác (scavenging). Đi cùng đéo?",
  "They all had the same weird pathology, even though they came from completely different sources.": "Tất cả chúng đều có cùng một bệnh lý kỳ lạ giống nhau, mặc dù chúng đến từ những nguồn hoàn toàn khác biệt.",
  "Precisely what the chef requested.": "Chính xác là những gì đầu bếp đã yêu cầu.",
  "Hey, alright! That's mighty fine!": "Này, được đấy! Thế là tuyệt quá rồi!",
  "Orlando": "Orlando",
  "He didn't make it. I'm sorry.": "Anh ấy đã đéo qua khỏi. Tôi xin lỗi.",
  "Well, excuse me for being a little stressed out over the end of the fucking world!": "Chà, xin lỗi vì tôi có hơi căng thẳng một chút trước ngày cmn tận thế của thế giới này!",
  "Maybe it was an unforeseen interaction with--": "Có thể đó là một phản ứng ngoài ý muốn với--",
  "Carlson": "Carlson",
  "Ipina": "Ipina",
  "Gus": "Gus",
  "Orchard": "Vườn Cây Ăn Quả (Orchard)",
  "Const. Materials Cache": "Kho Vật Liệu Xây Dựng (Const. Materials)",
  "You want to learn the ropes, you need on-the-job training or a good trade school. Neither's really around any more.": "Cậu muốn học cách làm việc, cậu cần phải được đào tạo thực tế hoặc học tại một trường dạy nghề tốt. Cả hai thứ đó giờ đéo còn tồn tại nữa đâu.",
  "Just so you know... we all appreciate what you're doing out there.": "Nói cho cậu biết... tất cả chúng tôi đều trân trọng những gì cậu đang làm ở ngoài kia.",
  "Alright, let's track 'em down.": "Được rồi, đi lùng sục chúng thôi.",
  "Set/Clear Waypoint": "Đặt/Xóa Điểm Đến (Waypoint)",
  "Hugo": "Hugo",
  "Kilo": "Kilo",
  "CQB - Close Quarters Battle.": "CQB - Chiến Đấu Cận Chiến (Close Quarters Battle).",
  "You look like shit. Go home and get some rest!": "Trông cậu tàn tạ như cứt vậy. Về nhà và nghỉ ngơi đi!",
  "So long.": "Tạm biệt.",
  "Sets zeds on fire. They don't seem to like it much. This one's made with gasoline.": "Thiêu rụi bọn zeds. Có vẻ như chúng đéo thích điều đó cho lắm. Quả này được làm bằng xăng.",
  "Hey, look. Eli knew it, too, ok? It wasn't your fault.": "Này, nhìn đi. Eli cũng biết điều đó mà, ok? Đó đéo phải lỗi của cậu.",
  "I'll take my chances.": "Tôi sẽ nắm lấy cơ hội của mình.",
  "Or not. She's crazy. - %1$s": "Hoặc đéo. Cô ta bị điên rồi. - %1$s",
  "Well, it's too fucking late now, isn't it? Why don't you just hand your rifles over to the zeds, save us all some trouble?": "Chà, bây giờ đã cmn quá muộn rồi, phải đéo? Tại sao các cậu đéo giao nộp súng trường cho bọn zeds luôn đi, để đỡ rắc rối cho tất cả chúng ta?",
  "JOURNAL: Can we even do this?": "NHẬT KÝ (JOURNAL): Liệu chúng ta có thể làm được chuyện này đéo?",
  "Storyteller": "Người Kể Chuyện (Storyteller)",
  "Troubled by this situation.": "Cảm thấy bối rối trước tình huống này.",
  "Not all that hard to kill, but they're highly infectious.": "Đéo khó giết lắm, nhưng chúng có khả năng lây nhiễm rất cao.",
  "26 MIL Cpl Dexter Flagg": "26 QUÂN ĐỘI (MIL) Hạ Sĩ (Cpl) Dexter Flagg",
  "It's amazing how much a simple \"thank you\" now and again can smooth things over. - %1$s": "Thật đáng kinh ngạc khi một lời \"cảm ơn\" đơn giản thỉnh thoảng lại có thể xoa dịu mọi thứ. - %1$s",
  "Skillful feats like a one-shot multikill provide a big XP boost.": "Những kỹ năng điêu luyện như hạ gục nhiều mục tiêu chỉ bằng một phát súng (one-shot multikill) sẽ mang lại một lượng lớn Kinh Nghiệm (XP).",
  "Dojo": "Võ Đường (Dojo)",
  "That could be useful.": "Thứ đó có thể hữu ích đấy.",
  "Julienne!": "Julienne!",
  "Yeah, sure. Let's go.": "Ừ, chắc chắn rồi. Đi thôi.",
  "When I shove somebody, they move. (Class Specializations: Power Push, Power Kick)": "Khi tôi xô ai đó, họ sẽ phải bật ngửa. (Kỹ Năng Chuyên Môn Của Lớp - Class Specializations: Đẩy Xô Uy Lực - Power Push, Cú Đá Uy Lực - Power Kick)",
  "Feral Exterminated": "Đã Tiêu Diệt Feral",
  "Worried about community morale.": "Lo lắng về tinh thần của cộng đồng.",
  "Sure. The more the merrier.": "Chắc chắn rồi. Càng đông càng vui.",
  "Isn't it a virus?": "Đó đéo phải là một loại virus sao?",
  "New community members.": "Những thành viên mới của cộng đồng.",
  "Two Left Feet": "Hậu Đậu (Two Left Feet)",
  "Confirmed, sir. No one here matches the ID. Alive or dead.": "Đã xác nhận, thưa ngài. Đéo có ai ở đây trùng khớp với giấy tờ tùy thân cả. Dù còn sống hay đã chết.",
  "Attractive": "Hấp Dẫn",
  "Deleting a saved game will destroy all progress in this save slot. The slot will be available for a new game. Are you sure?": "Xóa file lưu game sẽ phá hủy mọi tiến trình trong ô lưu (save slot) này. Ô lưu đó sẽ có sẵn cho một lượt chơi mới. Bạn có chắc đéo?",
  "People are getting fed up with canned food and beef jerky.": "Mọi người đang ngày càng phát ngán với đồ hộp và thịt bò khô rồi.",
  "Subtitles": "Phụ Đề (Subtitles)",
  "Okay, come on, let's get back to it.": "Được rồi, thôi nào, hãy quay lại làm việc đi.",
  "Jacobs": "Jacobs",
  "Screamers": "Screamers",
  "Got some supplies here.": "Có một ít nhu yếu phẩm (supplies) ở đây.",
  "That feral just became our target.": "Con feral đó vừa trở thành mục tiêu của chúng ta.",
  "Yeah, okay, I ditched my search buddy. But see, I know this place, not too far from here. Guy had like a hundred grand stuffed into a mattress.": "Ừ, được rồi, tôi đã bỏ rơi đồng đội tìm kiếm của mình. Nhưng nghe này, tôi biết một chỗ, đéo xa đây lắm. Có gã giấu cả trăm ngàn đô nhét vào nệm cơ đấy.",
  "Jayden": "Jayden",
  "One of our folks wandered off last night. I think it was cabin fever finally setting in.": "Một người của chúng ta đã đi lang thang vào tối qua. Tôi nghĩ rốt cuộc thì chứng bức bối vì bị nhốt (cabin fever) cũng đã phát tác rồi.",
  "That was the last of my food.": "Đó là chút thức ăn cuối cùng của tôi đấy.",
  "I'm there. Gonna take a look around.": "Tôi đến nơi rồi. Sẽ xem xét xung quanh một chút.",
  "Zombies. On the other side of the river.": "Zombies. Ở phía bên kia sông.",
  "Barefoot in the snow, uphill both ways, etc. etc.": "Đi chân trần trên tuyết, leo dốc cả hai chiều, v.v. và v.v.",
  "Right. Right, sorry. Stupid....": "Đúng. Đúng, xin lỗi. Ngu ngốc quá....",
  "Madeline": "Madeline",
  "Safety First": "An Toàn Là Trên Hết (Safety First)",
  "Watched Cooking Shows": "Thích Xem Các Chương Trình Nấu Ăn (Watched Cooking Shows)"
};

const file = 'output/languages/chunks/btxt_chunk_164.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_164.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk164[r.sourceText]) {
    r.translatedText = chunk164[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 164 successfully!');
