const fs = require('fs');
const chunk172 = {
  "Black Friday, Doghouse here.": "Black Friday, Doghouse nghe đây.",
  "A souped-up promotional vehicle for the Qwik Clean Cleaning Service.": "Một chiếc xe quảng cáo được độ lại của Dịch Vụ Vệ Sinh Qwik Clean.",
  "Anyone out there? Please!": "Có ai ngoài đó đéo? Làm ơn!",
  "MISSION: Sgt. Erik Tan": "NHIỆM VỤ: Trung sĩ Erik Tan",
  "Event: Mishandled Gun": "Sự kiện: Bất Cẩn Chơi Súng (Mishandled Gun)",
  "First Aid Kit": "Hộp Sơ Cứu (First Aid Kit)",
  "A brand new bullpup rifle with a unique forward ejection system. Stock sights.": "Một khẩu súng trường bullpup hoàn toàn mới với hệ thống hất vỏ đạn về phía trước độc đáo. Ống ngắm nguyên bản (Stock sights).",
  "So just... scrape them into some bags and incinerate them.": "Vậy nên cứ... cạo chúng cho vào mấy cái túi rồi đem thiêu rụi hết đi.",
  "Bonus Character": "Nhân Vật Thưởng Thêm (Bonus Character)",
  "Surrender this location to the zeds.": "Đầu hàng nhường lại địa điểm này cho bọn zeds.",
  "Kilo brought the supplies back to base on his own. He's been really withdrawn lately, worrying about his family. He snaps at Vince more than usual. I wish I'd been there to support him.": "Kilo đã tự mình mang số nhu yếu phẩm về căn cứ. Dạo này anh ấy trở nên rất khép kín, lo lắng cho gia đình của mình. Anh ấy gắt gỏng với Vince nhiều hơn bình thường. Tôi ước gì mình đã ở đó để hỗ trợ anh ấy.",
  "Really, people? We can't get off our asses to save a single caller?": "Thật sao, mọi người? Chúng ta đéo thể nhấc mông lên để đi cứu một người gọi cầu cứu hay sao?",
  "Shame about Maybeline's boy.": "Thật đáng tiếc cho cậu con trai của Maybeline.",
  "Long story.": "Chuyện dài lắm.",
  "Returning Home": "Đang Trở Về Nhà (Returning Home)",
  "Staying on foot's a better idea anyways.": "Dù sao thì việc đi bộ vẫn là một ý kiến hay hơn.",
  "This is Sasquatch, calling Black Friday. Requesting additional forces at my position inside the Highway Nine tunnel.": "Đây là Sasquatch, gọi Black Friday. Yêu cầu tăng viện thêm lực lượng đến vị trí của tôi bên trong đường hầm Quốc lộ 9 (Highway Nine).",
  "I'm hearing that our latest caller has been picked up ... by the military again.": "Tôi đang nghe tin là người gọi cầu cứu mới nhất của chúng ta đã được đón đi ... lại bởi phía quân đội.",
  "+25 Demagoguery when discussing literature.": "+25 Kỹ năng Mị dân (Demagoguery) khi thảo luận về văn học.",
  "Nothing we can use here.": "Đéo có thứ gì chúng ta có thể dùng được ở đây cả.",
  "Right. Well, thanks for the offer, but we're doing just fine on our own, and I'm damn sure not surrendering my guns when the streets are full of flesh-eating dead people.": "Phải rồi. Chà, cảm ơn vì lời đề nghị, nhưng chúng tôi đang tự xoay sở rất tốt, và tôi đéo chắc chắn một điều là tôi sẽ đéo giao nộp súng của mình khi ngoài đường đầy rẫy những xác chết thèm khát ăn thịt người đâu.",
  "That's not a normal zombie.": "Đó đéo phải là một con zombie bình thường đâu.",
  "Full Auto": "Tự Động Hoàn Toàn (Full Auto)",
  "Anything I need to worry about with this doctor?": "Có điều gì tôi cần phải lo lắng về vị bác sĩ này đéo?",
  "DECLINE MISSION. This might not go over so well.": "TỪ CHỐI NHIỆM VỤ. Chuyện này có thể sẽ đéo suôn sẻ cho lắm đâu.",
  "Almost. Just one more second.": "Gần xong rồi. Chỉ một giây nữa thôi.",
  "Could use help to get out of here.": "Cần được giúp đỡ để thoát khỏi đây.",
  "Whistling Box Mine": "Mìn Hộp Hú Còi (Whistling Box Mine)",
  "Just trying to be helpful, ma'am.": "Chỉ đang cố gắng giúp ích thôi, thưa cô.",
  "Maybe I jumped the gun a little bit. Let's stay where we are.": "Có lẽ tôi đã hơi hấp tấp vội vàng một chút. Hãy cứ ở yên vị trí của chúng ta đi.",
  "I sure could use a vehicle out here.": "Tôi chắc chắn có thể dùng một chiếc xe ở ngoài này đấy.",
  "Helmerichs": "Helmerichs",
  "Oh, god, I don't want to die!": "Ôi, Chúa ơi, tôi đéo muốn chết!",
  "Sorry. I'm too banged up.": "Xin lỗi. Tôi bị thương quá nặng (banged up) rồi.",
  "One solution. One number per square. It's a rare dose of logic in this illogical world. (Sudoku expertise.)": "Một giải pháp. Một con số cho mỗi ô vuông. Đó là một liều lượng logic hiếm hoi trong cái thế giới phi logic này. (Chuyên gia giải đố Sudoku.)",
  "Pump you up!": "Bơm tinh thần cho cậu lên nào!",
  "PERSONAL SKILL. Babe Ruth's batting average? .342. Ask me a tough one.": "KỸ NĂNG CÁ NHÂN. Tỷ lệ đánh bóng trung bình của Babe Ruth á? .342. Hãy hỏi tôi một câu nào khó hơn đi.",
  "Come on, then. I'll help you track 'em down.": "Vậy thì đi thôi. Tôi sẽ giúp cậu lùng sục truy dấu bọn chúng.",
  "Radio Operator: %s": "Người Vận Hành Radio: %s",
  "The good news is we're still well-stocked with ammo.": "Tin tốt là chúng ta vẫn còn dự trữ rất nhiều đạn dược.",
  "Works Out Constantly": "Liên Tục Luyện Tập (Works Out Constantly)",
  "Brush Axe": "Rựa Phát Cây (Brush Axe)",
  "Looks like it's party time.": "Có vẻ như đã đến giờ quẩy (party time) rồi.",
  "He's got a point. I'd feel better with something sturdier than a tree branch. We might want to think about scrounging up some long-term supplies too. Just in case.": "Cậu ta nói có lý đấy. Tôi sẽ cảm thấy yên tâm hơn nếu có thứ gì đó chắc chắn hơn là một cành cây. Chúng ta có lẽ cũng nên nghĩ đến việc vơ vét thu lượm (scrounging up) thêm một vài nhu yếu phẩm dài hạn nữa. Chỉ là để đề phòng bất trắc thôi.",
  "Shotgun: Super 90 KIWF": "Súng Shotgun: Super 90 KIWF",
  "Instead of bein' useless, how about fuckin' helpin' me!": "Thay vì đứng đó làm kẻ vô dụng lãng phí đéo gian, sao đéo giúp tao một tay đi hả thằng chết tiệt!",
  "Holy Mother of God....": "Lạy Chúa Lòng Lành....",
  "Hammer": "Cây Búa (Hammer)",
  "Hope he's not looking for new patients up there.": "Hy vọng anh ta đéo đang đi tìm kiếm những bệnh nhân mới ở trên đó.",
  "TANNER LAKE": "HỒ TANNER (TANNER LAKE)",
  "Low profile, slim but brutal. INCENDIARY.": "Cấu hình thấp, nhỏ gọn nhưng tàn bạo. ĐẠN CHÁY (INCENDIARY).",
  "What is that dude eating?": "Gã đó đang ăn cái đéo gì vậy?",
  "DECLINE MISSION. Tell the strangers to fend for themselves. This isn't how we make friends.": "TỪ CHỐI NHIỆM VỤ. Bảo những kẻ xa lạ kia hãy tự mà lo liệu lo cho thân mình đi. Đây đéo phải là cách chúng ta kết bạn đâu.",
  "What I'm doing? Sheriff Parsons, what we're doing here is nothing less than maintaining the continuity of American government in the face of an unprecedented crisis.": "Tôi đang làm gì ư? Cảnh sát trưởng Parsons, những gì chúng tôi đang làm ở đây đéo có gì khác ngoài việc duy trì sự liền mạch của chính phủ Hoa Kỳ khi phải đối mặt với một cuộc khủng hoảng chưa từng có tiền lệ thế này.",
  "Thought you were hot shit kicking me out, right? Well, it turns out I don't need you assholes. - %1$s": "Tưởng mấy người tống cổ tôi đi là oai lắm đúng đéo? Chà, hóa ra tôi cũng đéo cần đám khốn nạn các người. - %1$s",
  "I guess we owe someone a thank-you, huh?": "Tôi đoán là chúng ta nợ ai đó một lời cảm ơn, nhỉ?",
  "Reminds me of when built our house, but with fewer arguments. God, I hope I see that place again someday.": "Nhắc tôi nhớ đến lúc chúng ta xây nhà, nhưng ít tranh cãi cãi vã hơn. Chúa ơi, tôi hy vọng một ngày nào đó tôi sẽ lại được nhìn thấy nơi ấy.",
  "Need:": "Cần:",
  "Just a college student.": "Chỉ là một sinh viên đại học thôi.",
  "Another survivor group approached us after hearing that we'd learned to cure and pickle food to extend its longevity. We traded our expertise for a share of their stockpiles. - %1$s.": "Một nhóm người sống sót khác đã tiếp cận chúng tôi sau khi nghe nói rằng chúng tôi đã học được cách tẩm ướp và muối chua thực phẩm để kéo dài thời hạn bảo quản. Chúng tôi đã đánh đổi chuyên môn của mình để lấy một phần kho dự trữ của họ. - %1$s.",
  "Or you're going to have to answer to me.": "Nếu đéo, cậu sẽ phải trả lời nói chuyện với tôi đấy.",
  "Alice": "Alice",
  "If you ignore the rampant destruction and flesh-eating dead people, this place is kinda quaint.": "Nếu cậu phớt lờ đi sự tàn phá tràn lan và những xác chết ăn thịt người, thì nơi này cũng khá là cổ kính đấy.",
  "THE FINAL COUNTDOWN": "NHỮNG GIÂY PHÚT CUỐI CÙNG (THE FINAL COUNTDOWN)",
  "Can we hurry? We should hurry.": "Chúng ta có thể nhanh lên đéo? Chúng ta nên nhanh lên.",
  "Helped %3$s find one of their missing people. Got a nice little bonus out of it, too. -%1$s": "Đã giúp %3$s tìm thấy một trong những người bị mất tích của họ. Cũng kiếm được một khoản tiền thưởng nhỏ khá hời từ việc đó. -%1$s",
  "Don't let it get up!": "Đéo để nó đứng dậy!",
  "Doc, you can't ask me to do this. I promised ma I'd take care of him.": "Doc, anh đéo thể bắt tôi làm chuyện này được. Tôi đã hứa với mẹ là tôi sẽ chăm sóc cho anh ấy.",
  "Time to light 'em up!": "Đến lúc thiêu rụi chúng rồi!",
  "I'm actually getting to the point where thinking about food makes me nauseous. I didn't think that was possible.": "Thực sự thì tôi đang đạt đến cái mức độ mà chỉ cần nghĩ về đồ ăn thôi cũng khiến tôi buồn nôn rồi. Tôi đéo từng nghĩ điều đó là có thể xảy ra cơ đấy.",
  "I got a horde over here.": "Tôi phát hiện một bầy (horde) ở bên này.",
  "Resolution 1920x1080": "Độ Phân Giải 1920x1080",
  "Went out in a Blaze of Glory at Breakdown Level 1 or Higher.": "Đã ngã xuống trong một Ánh Hào Quang Rực Rỡ (Blaze of Glory) ở Breakdown Cấp Độ 1 (Level 1) hoặc Cao Hơn.",
  "We've found a place to stay that seems sturdy enough ... for the moment.": "Chúng tôi đã tìm thấy một nơi để trú chân có vẻ đủ kiên cố ... cho tới thời điểm hiện tại.",
  "Sometimes you gotta go your own way.": "Đôi khi cậu phải đi theo con đường của riêng mình.",
  "This outbreak is an punishment for the wicked, and only the truly righteous will survive.": "Trận đại dịch bùng phát này là một sự trừng phạt dành cho những kẻ độc ác, và chỉ những người thực sự công chính mới có thể sống sót.",
  "OUTPOSTS could take him out before he reaches us.": "Các TIỀN ĐỒN (OUTPOSTS) có thể sẽ hạ gục hắn trước khi hắn tiếp cận được chúng ta.",
  "All that got me was a pissed off zombie and a busted uke.": "Tất cả những gì tôi nhận được chỉ là một con zombie đang điên tiết và một cây đàn ukulele (uke) bị hỏng bét.",
  "We're here. Stay near the landing zone until the helicopter gets here. As long as you don't do anything stupid, we'll keep you alive.": "Chúng tôi ở đây rồi. Hãy ở gần khu vực hạ cánh (landing zone) cho đến khi máy bay trực thăng đến đây. Miễn là cậu đéo làm điều gì ngu ngốc, chúng tôi sẽ giữ cho cậu sống sót.",
  "Hell with this. Y'all want to risk your asses for her dumb fuck pal, knock yourselves out.": "Khốn kiếp với chuyện này. Tất cả bọn mày muốn mạo hiểm cái mạng quèn của mình vì thằng bạn ngu xuẩn của cô ta thì cứ tự nhiên mà đi.",
  "What is the point of even trying against something like that?": "Có ý nghĩa gì đâu khi cố gắng chống lại một thứ gì đó như thế chứ?",
  "That's good news! See you soon.": "Thật là một tin tốt! Hẹn sớm gặp lại cậu.",
  "You know there aren't any civilians who can roll up on a horde and just clear it out for these people! It's us or nobody!": "Cậu biết thừa là đéo có bất kỳ dân thường nào có thể lao vào một bầy xác sống và chỉ đơn giản là dọn dẹp sạch sẽ chúng vì những người này đâu! Chỉ có chúng ta hoặc là đéo có ai cả!",
  "Please don't let me die like this.": "Xin đừng để tôi phải chết như thế này.",
  "Would rather work alone than in a group ... and would rather die than be told what to do.": "Thà làm việc một mình còn hơn là theo nhóm ... và thà chết còn hơn là bị sai khiến việc phải làm.",
  "Suicide": "Tự Sát (Suicide)",
  "We might want to get somebody to get up in the watchtower and pick them off.": "Có lẽ chúng ta nên đưa một ai đó lên đài quan sát (watchtower) và bắn tỉa từng tên một.",
  "Let's roll.": "Lên đường thôi (Let's roll).",
  "This one was really bad. Two people down, and it's just dumb luck it wasn't more.": "Chuyện này thực sự rất tồi tệ. Hai người gục xuống, và thật là một sự may mắn ngu xuẩn khi con số đó đéo nhiều hơn.",
  "Hope you're ready.": "Hy vọng cậu đã sẵn sàng.",
  "I was just thinking about a few of my buddies who were on leave when this all hit.": "Tôi chỉ đang nghĩ về một vài người bạn của mình, những người đang trong kỳ nghỉ phép khi tất cả những chuyện này ập đến.",
  "We've got sightings of one of those zombies with body armor. Better take it out quick. -%2$s": "Chúng ta đã phát hiện ra một trong số những con zombies mặc áo giáp chống đạn (body armor) đó. Tốt hơn là nên tiêu diệt nó nhanh chóng. -%2$s",
  "If you're looking for any more hands, we'd be happy to join you.": "Nếu cậu đang tìm kiếm thêm nhân lực, chúng tôi sẽ rất vui lòng được gia nhập cùng cậu.",
  "Come on, we gotta clear these things out before we open the gate!": "Cố lên, chúng ta phải dọn dẹp sạch sẽ những thứ này trước khi mở cổng!",
  "Main Menu": "Menu Chính (Main Menu)",
  "No cell reception up at the lake. Guess you could say we've been out of the loop.": "Đéo có sóng điện thoại ở trên hồ. Chắc cậu cũng có thể nói rằng chúng tôi đã bị mất hoàn toàn liên lạc với thế giới bên ngoài rồi.",
  "Not much of a direct threat, but if you let a SCREAMER keep making noise, it'll bring a lot of zeds to the area.": "Đéo phải là một mối đe dọa trực tiếp quá lớn, nhưng nếu cậu để cho một con SCREAMER tiếp tục gây ra tiếng ồn, nó sẽ thu hút rất nhiều bọn zeds kéo đến khu vực này.",
  "That's a building, dumbass. We're not putting any rounds through there.": "Đó là một tòa nhà, đồ ngu. Chúng ta sẽ đéo bắn bất kỳ viên đạn nào qua đó đâu.",
  "Kill 5 Bloaters (Breakdown Level 2 or Higher).": "Tiêu diệt 5 con Bloaters (Breakdown Cấp Độ 2 hoặc Cao Hơn).",
  "Father Figure": "Hình Mẫu Người Cha (Father Figure)"
};

const file = 'output/languages/chunks/btxt_chunk_172.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_172.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk172[r.sourceText]) {
    r.translatedText = chunk172[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 172 successfully!');
