const fs = require('fs');
const chunk138 = {
  "Juggernaut Exterminated": "Juggernaut Đã Bị Tiêu Diệt",
  "I'm gonna see if I can get a high-level view of things.": "Tôi sẽ xem liệu mình có thể quan sát mọi thứ từ trên cao đéo.",
  "Weapon Specialization": "Chuyên Môn Vũ Khí",
  "Spivey": "Spivey",
  "RECOVER: Belongings": "THU HỒI: Đồ Đạc Cá Nhân",
  "Tyrone": "Tyrone",
  "We already didn't have enough food to go around, and now this?": "Chúng ta đã đéo có đủ thức ăn để chia nhau rồi, và giờ thì thêm chuyện này nữa sao?",
  "Fix Up Library": "Sửa Chữa Thư Viện",
  "Shit, I'm dry!": "Chết tiệt, tôi cạn đạn rồi!",
  "Pirate Cutlass": "Kiếm Hải Tặc (Cutlass)",
  "Community Has %s": "Cộng Đồng Có %s",
  "Listen, I understand where you're coming from. We've all lost a lot.": "Nghe này, tôi hiểu cảm giác của cậu. Tất cả chúng ta đều đã mất mát rất nhiều.",
  "Fellow survivors, there is hope.": "Hỡi những người sống sót, vẫn còn hy vọng.",
  "The supply run will complete on its own. Or you could provide an escort.": "Chuyến chạy tiếp tế sẽ tự động hoàn thành. Hoặc bạn có thể cung cấp người hộ tống.",
  "Alivia": "Alivia",
  "The zeds may have the numbers, but as long as we keep rebuilding, we got a fighting chance.": "Lũ zed có thể đông đảo về số lượng, nhưng chừng nào chúng ta còn tiếp tục xây dựng lại, chúng ta vẫn còn cơ hội chiến đấu.",
  "1 GENERIC Wendell Higgins": "1 GENERIC Wendell Higgins",
  "Just like that.": "Chỉ đơn giản vậy thôi.",
  "Solid copy.": "Nghe rõ (Solid copy).",
  "Norville": "Norville",
  "Tell Quentin... or not.": "Kể cho Quentin... hoặc đéo.",
  "Horn, MD": "Bác sĩ Horn",
  "Hey! Hello? Can you hear me? Report in, we can’t lose you! Please come back … [sigh]": "Này! Alo? Cậu có nghe tôi nói đéo? Báo cáo đi, chúng tôi đéo thể mất cậu được! Làm ơn quay lại đi … [thở dài]",
  "It's a good thing I was here, but we need to deal with %1$s. Next time I might not be around. - %3$s": "Thật tốt là tôi đã có mặt ở đây, nhưng chúng ta cần phải giải quyết vụ %1$s. Lần sau có thể tôi sẽ đéo có ở quanh đây đâu. - %3$s",
  "Training": "Huấn Luyện",
  "Has Seen Things": "Đã Từng Trải",
  "As a reminder to all citizens of Marshall, until the current crisis is over, possession of firearms by civilians has been declared unlawful.": "Xin nhắc nhở toàn thể công dân Marshall, cho đến khi cuộc khủng hoảng hiện tại kết thúc, việc dân thường sở hữu súng đạn bị coi là bất hợp pháp.",
  "Sir, you may want to hear this. I picked it up over the radio.": "Thưa sếp, ngài có thể muốn nghe cái này. Tôi đã bắt được nó qua radio.",
  "Help destroy a feral zombie?": "Giúp tiêu diệt một con feral zombie?",
  "Camp Site": "Khu Cắm Trại",
  "Well, that's just about it for your physical. Now, has there been any reduction in the burning sensation when you urinate?": "Chà, phần kiểm tra thể chất của cậu đến đây là xong. Bây giờ, cảm giác buốt rát khi đi đái đã thuyên giảm chút nào chưa?",
  "+10 Food, Ammo, Medicine, Fuel, and Materials capacity.": "+10 Sức chứa Thức Ăn, Đạn Dược, Thuốc Men, Nhiên Liệu và Vật Liệu.",
  "I ain't your personal bodyguard. Tend to your own shit for once.": "Tôi đéo phải vệ sĩ riêng của cậu. Lần này tự lo cái đống cứt của mình đi.",
  "Nuts and Bolts": "Bu-lông và Ốc-vít",
  "Wrong Kill Type - Aborting!": "Sai Loại Hạ Gục - Đang Hủy!",
  "Woah. There might be some people there.": "Chà. Có thể có vài người ở đó.",
  "DELAY. I need a moment to think!": "TRÌ HOÃN. Tôi cần một chút thời gian để suy nghĩ!",
  "We're getting low on medicine.": "Chúng ta đang cạn kiệt thuốc men.",
  "DECLINE MISSION. Quentin probably won't appreciate that.": "TỪ CHỐI NHIỆM VỤ. Quentin có lẽ sẽ đéo thích điều đó đâu.",
  "Word on the wireless is %1$s made it home with those supplies. Seemed kinda miffed about not getting any help, though. - %2$s": "Tin đồn qua bộ đàm là %1$s đã về đến nhà với những nhu yếu phẩm đó. Dù vậy, có vẻ hơi bực bội vì đéo nhận được bất kỳ sự giúp đỡ nào. - %2$s",
  "Bastards never stood a chance!": "Lũ khốn đó đéo bao giờ có cơ hội nào đâu!",
  "We could've used shooting like that back when...well, before I got here.": "Chúng ta đã có thể sử dụng khả năng bắn súng như vậy hồi mà... chà, trước khi tôi đến đây.",
  "We gotta start loading up on gas, or these cars aren't going to be worth squat.": "Chúng ta phải bắt đầu tích trữ xăng thôi, nếu đéo mấy chiếc xe này sẽ đéo đáng một xu cắc nào.",
  "There's a reason we're seeing so many hordes out there. Seems like half the valley's infested.": "Có lý do khiến chúng ta thấy quá nhiều bầy đàn ngoài đó. Có vẻ như một nửa thung lũng đã bị lây nhiễm rồi.",
  "Oviedo": "Oviedo",
  "Weapons Delivered": "Vũ Khí Đã Được Giao",
  "But it's been hours since I had a new caller, and as far as I know, I'm talking to an empty town.": "Nhưng đã nhiều giờ trôi qua kể từ lúc tôi có một cuộc gọi mới, và theo như tôi biết, tôi đang độc thoại với một thị trấn ma.",
  "This list of assets won't go on forever. You keep losing people, and we'll have to pull you out.": "Danh sách tài sản này sẽ đéo kéo dài mãi mãi đâu. Các anh cứ tiếp tục để mất người, và chúng tôi sẽ phải rút các anh ra.",
  "What are you waiting for? You. Me. Truck. Now.": "Cậu còn chờ gì nữa? Cậu. Tôi. Xe tải. Ngay bây giờ.",
  "Problem Solver": "Kẻ Giải Quyết Vấn Đề",
  "The perimeter's breached!": "Vành đai phòng thủ đã bị chọc thủng!",
  "It wasn't easy, but I managed to find this.": "Đéo dễ dàng gì, nhưng tôi đã xoay sở tìm được cái này.",
  "Well, then we need to get people out there looking for more building materials. Lumber, nails, tools, you know, that kind of shit.": "Chà, vậy thì chúng ta cần cử người ra ngoài đó tìm thêm vật liệu xây dựng. Gỗ ván, đinh, dụng cụ, cậu biết đấy, những thứ chó đẻ đại loại thế.",
  "A survivor came bearing gifts.": "Một người sống sót đã đến và mang theo những món quà.",
  "%s Unlocked": "%s Đã Được Mở Khóa",
  "What's wrong?": "Có chuyện gì vậy?",
  "Running sucks. (Improves cardio slowly.)": "Chạy bộ thật tệ hại. (Cải thiện thể lực từ từ.)",
  "Support local business my ass, once you can order a toilet that's a replica of Henry VIII's throne at two in the morning, you don't go back.": "Ủng hộ doanh nghiệp địa phương cái mông tao ấy, một khi cậu đã có thể đặt mua một cái bồn cầu sao chép y chang ngai vàng của vua Henry VIII lúc hai giờ sáng, cậu sẽ đéo bao giờ quay lại mua đồ địa phương nữa đâu.",
  "Shit, no more ammo!": "Chết tiệt, hết đạn rồi!",
  "We fended off yet another zombie horde. It's really starting to wear on everyone. - %1$s.": "Chúng ta lại vừa đánh đuổi thêm một bầy zombie nữa. Điều này thực sự đang bắt đầu vắt kiệt sức mọi người rồi. - %1$s.",
  "Fuck. People always crying about how awful the army is ... 'til you need us for something, right?": "Chết tiệt. Mọi người luôn khóc lóc về việc quân đội tồi tệ như thế nào ... cho đến khi mấy người cần chúng tôi cho việc gì đó, đúng đéo?",
  "Light indirect fire over a broad area that sets zombies on fire.": "Hỏa lực gián tiếp hạng nhẹ bao phủ một khu vực rộng lớn, có khả năng thiêu cháy lũ zombie.",
  "Restaurant": "Nhà Hàng",
  "Theo": "Theo",
  "Comes across as a quiet, patient, introspective sort. He's a long-time veteran of the force, and the department frequently partnered him up with rookies, trusting him to show them the ropes.": "Luôn tỏ ra là một người trầm lặng, kiên nhẫn và sống nội tâm. Anh ấy là một cựu binh lâu năm của lực lượng cảnh sát, và sở thường xuyên bắt cặp anh với những lính mới, tin tưởng giao cho anh nhiệm vụ chỉ bảo họ.",
  "Found some medicine.": "Tìm thấy chút thuốc men.",
  "Will look around for any survivors.": "Sẽ đi quanh tìm kiếm bất kỳ người sống sót nào.",
  "Lawyer": "Luật Sư",
  "Neutral Observer": "Người Quan Sát Trung Lập",
  "Oh God oh God oh God!": "Ôi Chúa ơi ôi Chúa ơi ôi Chúa ơi!",
  "Need More %s": "Cần Thêm %s",
  "It's...not a good thing.": "Đó... đéo phải là một điều tốt.",
  "Help Kilo bring in a big haul of supplies.": "Giúp Kilo mang về một lượng lớn nhu yếu phẩm.",
  "Repair engine": "Sửa chữa động cơ",
  "Survived 2 minutes within a Danger Zone.": "Đã sống sót 2 phút trong Khu Vực Nguy Hiểm.",
  "Schupman": "Schupman",
  "Shelly": "Shelly",
  "Who knows? Maybe he's right. Maybe Horn was a crackpot. But I want to bring him in to find out.": "Ai mà biết được? Có thể ông ấy đúng. Có thể Horn là một gã lập dị. Nhưng tôi muốn đưa ông ấy về để tìm hiểu xem sao.",
  "I think we'll call it a day there. The rest of those infestations can wait a while. I appreciate the help, though.": "Tôi nghĩ hôm nay chúng ta sẽ dừng ở đây thôi. Phần còn lại của mấy cái ổ dịch đó có thể đợi thêm một thời gian nữa. Dù sao thì cũng cảm ơn cậu đã giúp.",
  "Don't take this the wrong way, but you seem a bit fried.": "Đừng hiểu lầm nhé, nhưng cậu trông có vẻ hơi đuối sức (fried) rồi đấy.",
  "Graphics - Medium Spec": "Đồ họa - Cấu Hình Trung Bình",
  "Vienna Cho is planning to use our comms to track down more civilian refugees. For now, I won't stand in her way. If there are people we can rescue, I do want to know about it. But I can't say I'm totally comfortable with a civilian sitting in that chair.": "Vienna Cho đang định dùng hệ thống thông tin liên lạc của chúng ta để theo dõi thêm những người dân tị nạn. Tạm thời, tôi sẽ đéo ngáng đường cô ấy. Nếu có những người mà chúng ta có thể giải cứu, tôi thực sự muốn biết về điều đó. Nhưng tôi đéo thể nói là mình hoàn toàn thoải mái với việc một người dân thường ngồi vào vị trí đó đâu.",
  "Hey, come get some!": "Này, đến mà nếm mùi đi!",
  "Greatly reduced Vitality and Stamina. Bed rest is advised. Very small chance of recovery every 24 hours.": "Sinh lực (Vitality) và Thể lực (Stamina) bị giảm đáng kể. Khuyên bạn nên nằm nghỉ ngơi. Có một cơ hội phục hồi rất nhỏ mỗi 24 giờ.",
  "Suit yourself. I suppose you'll just have to take your chances. Good luck.": "Tùy cậu thôi. Tôi cho là cậu sẽ phải tự thử vận may của mình vậy. Chúc may mắn.",
  "You will see me later.": "Chúng ta sẽ gặp lại nhau sau.",
  "We found a run-down RV on the outskirts of town. It might just be what we need to carry a few people and enough supplies to make it to safety.": "Chúng tôi đã tìm thấy một chiếc xe RV tồi tàn ở ngoại ô thị trấn. Nó có thể chính là thứ chúng ta cần để chở một vài người và đủ nhu yếu phẩm để đến nơi an toàn.",
  "Short Wakizashi": "Kiếm Ngắn Wakizashi",
  "Shit, I thought there was a lot of you!": "Chết tiệt, tao tưởng phe bọn mày đông lắm cơ mà!",
  "DELAY. Maybe later.": "TRÌ HOÃN. Có thể để sau.",
  "Okay, let's go find 'em.": "Được rồi, đi tìm họ thôi.",
  "The RV's tires are good to go.": "Lốp của chiếc RV đã sẵn sàng để lăn bánh.",
  "A well crafted movie replica sword.": "Một thanh kiếm đạo cụ điện ảnh được chế tác tinh xảo.",
  "Turns food into fuel.": "Chuyển hóa thức ăn thành nhiên liệu.",
  "Pistol: M9": "Súng lục: M9",
  "Pressure Triggers": "Cò Ép Lực (Pressure Triggers)",
  "Duncan": "Duncan",
  "That was too close.": "Suýt chút nữa thì toi mạng.",
  "Unfriendly attitude.": "Thái độ đéo thân thiện.",
  "Storage": "Nhà Kho"
};

const file = 'output/languages/chunks/btxt_chunk_138.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_138.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk138[r.sourceText]) {
    r.translatedText = chunk138[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 138 successfully!');
