const fs = require('fs');
const chunk117 = {
  "Alexis": "Alexis",
  "Gradually gain Fame with special achievements.": "Dần dần nhận được Danh tiếng (Fame) qua những thành tựu đặc biệt.",
  "119 STORY SWAT Officer": "119 STORY Lính Đặc Nhiệm SWAT",
  "I got a zed for you over here.": "Tôi có một con zed cho cậu ở đây này.",
  "TIP: Hold [cover] to crouch down and make yourself harder to spot.": "MẸO: Giữ [cover] để ngồi xổm xuống và khiến bản thân khó bị phát hiện hơn.",
  "Like that time when I hit on Richie Peters' girlfriend. Man, that was a mistake.": "Giống như cái lần tôi tán tỉnh bạn gái của Richie Peters ấy. Anh bạn à, đó đúng là một sai lầm.",
  "Rosenberg": "Rosenberg",
  "Planning a new construction project?": "Đang lên kế hoạch cho một dự án xây dựng mới à?",
  "Weapons and suppressors": "Vũ khí và ống giảm thanh",
  "Assault Rifle: M6 SBR": "Súng trường tấn công: M6 SBR",
  "Check this out. This came over the radio a little while ago. I managed to record most of it.": "Xem này. Tin này vừa phát trên radio lúc nãy. Tôi đã thu âm được phần lớn.",
  "We're not going very far.": "Chúng ta sẽ không đi xa đâu.",
  "Trait Discovered: Frugal Gourmet": "Đặc Điểm Được Khám Phá: Người Sành Ăn Tiết Kiệm",
  "Modern materials made with classic Italian charm.": "Vật liệu hiện đại kết hợp với vẻ quyến rũ cổ điển của Ý.",
  "Seems like there's a bug going around. It's only a matter of time before it hits us. - %1$s": "Có vẻ như đang có dịch bệnh lây lan. Chỉ là vấn đề thời gian trước khi nó đánh gục chúng ta thôi. - %1$s",
  "It will take a while for the plants to mature.": "Sẽ mất một thời gian để cây trồng trưởng thành.",
  "Dead ahead!": "Ngay phía trước!",
  "Experimental precision rifle from CLEO.": "Súng trường bắn tỉa thử nghiệm từ CLEO.",
  "Upgraded police shotgun.": "Súng shotgun cảnh sát đã được nâng cấp.",
  "Whenever you're ready to move on, you can tell your people to load up the RV from the Radio Room at your home.": "Bất cứ khi nào bạn sẵn sàng rời đi, bạn có thể bảo người của mình chất đồ lên xe RV từ Phòng Radio (Radio Room) tại nhà bạn.",
  "Single-stage Press": "Máy Ép Một Giai Đoạn (Single-stage Press)",
  "It was Black Fever. They never stood a chance.": "Đó là Cơn Sốt Đen (Black Fever). Họ không bao giờ có cơ hội sống sót.",
  "Carl, hey. Wanted to talk to you for a sec.": "Này Carl. Muốn nói chuyện với anh một lát.",
  "Select": "Chọn",
  "We've got some more rounds of .357 ammunition.": "Chúng ta vừa có thêm vài viên đạn .357.",
  "65 GENERIC Mary O'Leary": "65 GENERIC Mary O'Leary",
  "I'll come with you. I owe him that much.": "Tôi sẽ đi cùng cô. Tôi nợ anh ấy chừng đó.",
  "We've completed the requested upgrade, ma'am.": "Chúng tôi đã hoàn thành việc nâng cấp theo yêu cầu, thưa cô.",
  "Runner should be getting close soon.": "Người chạy việc (Runner) chắc sắp tới nơi rồi.",
  "Caldwell": "Caldwell",
  "%s%d %s": "%s%d %s",
  "It'd boost morale, and I bet people would feel more energized after a big, healthy meal.": "Nó sẽ thúc đẩy tinh thần, và tôi cá là mọi người sẽ cảm thấy tràn trề năng lượng hơn sau một bữa ăn lớn, đủ dinh dưỡng.",
  "Taking a moral stand.": "Giữ vững lập trường đạo đức.",
  "Brant": "Brant",
  "Careful on the right.": "Cẩn thận bên phải.",
  "Come to mama.": "Đến với mẹ nào.",
  "Nobody better get sick any time soon, because I got some bad news.": "Tốt nhất là đừng ai bị ốm trong thời gian tới, vì tôi có vài tin xấu đây.",
  "Anything you guys need?": "Các cậu có cần gì không?",
  "Maurice": "Maurice",
  "Toggle Map Legend": "Bật/Tắt Chú Giải Bản Đồ",
  "Nope! You're on your own!": "Không! Cậu phải tự lo thân thôi!",
  "Thanks. You just saved our lives.": "Cảm ơn. Cậu vừa cứu mạng chúng tôi đấy.",
  "Let's go tear down that wall! Man, I've been waiting to say that my whole life.": "Hãy đi phá sập bức tường đó nào! Anh bạn, cả đời tôi chỉ chờ được nói câu đó thôi đấy.",
  "Paramedic": "Nhân Viên Y Tế (Paramedic)",
  "Shopping": "Đi Mua Sắm",
  "Pham": "Phạm",
  "Why go into one of the most dangerous parts of the city, just to get one Screamer? There…there must be something else.": "Tại sao lại đi vào một trong những khu vực nguy hiểm nhất của thành phố, chỉ để bắt một con Screamer chứ? Chắc chắn… chắc chắn phải có thứ gì đó khác.",
  "I'm getting plenty of callers who say they're in trouble ... but nobody's coming to save them.": "Tôi nhận được rất nhiều cuộc gọi của những người nói rằng họ đang gặp rắc rối... nhưng chẳng có ai đến cứu họ cả.",
  "A save game cannot be found on this storage device. You can create a save on this storage device, choose another storage device, or continue without saving losing any progress made.": "Không tìm thấy tệp lưu game nào trên thiết bị lưu trữ này. Bạn có thể tạo một bản lưu mới trên thiết bị này, chọn một thiết bị lưu trữ khác, hoặc tiếp tục chơi mà không lưu tiến trình.",
  "I mean, you spend your whole life in a place, but until you're climbing fences and running through backyards, you don't really see how it all fits together.": "Ý tôi là, cậu dành cả đời ở một nơi, nhưng cho đến khi cậu phải leo rào và chạy qua những cái sân sau, cậu mới thực sự thấy mọi thứ liên kết với nhau như thế nào.",
  "SUV Skull": "Chiếc SUV Skull",
  "I've got their pattern down now.": "Bây giờ tôi đã nắm thóp được cách di chuyển của chúng rồi.",
  "Bonus XP for Shooting": "Thưởng XP cho Kỹ năng Bắn súng (Shooting)",
  "Allows us to contact regimental HQ.": "Cho phép chúng ta liên lạc với Trụ sở Trung đoàn.",
  "This is Vienna Cho signing off...at least for now. Goodbye.": "Đây là Vienna Cho kết thúc phiên phát sóng... ít nhất là vào lúc này. Tạm biệt.",
  "Okay, I know I screwed up, and I'm sorry, but at least nobody got hurt... right? - %1$s": "Được rồi, tôi biết tôi đã phá hỏng mọi thứ, và tôi xin lỗi, nhưng ít ra thì không có ai bị thương... đúng không? - %1$s",
  "We're heavily engaged, cannot support you at this time.": "Chúng tôi đang giao tranh ác liệt, không thể hỗ trợ các người vào lúc này.",
  "Secure the LZ": "Bảo vệ an toàn cho Điểm Đáp (LZ)",
  "The Prepper SUV has been delivered to a location near the base.": "Chiếc Prepper SUV đã được chuyển đến một địa điểm gần căn cứ.",
  "About the calmest guy ever to pilot a bird. Says that his unflappable attitude comes from a clean conscience.": "Có lẽ là người điềm tĩnh nhất từng lái máy bay. Anh ta nói rằng thái độ không hề nao núng của mình đến từ một lương tâm trong sạch.",
  "And wouldn't you know it, Hadley's rich dad was the biggest contributor to the governor's last campaign!": "Và cậu biết không, ông bố giàu có của Hadley chính là người đóng góp lớn nhất cho chiến dịch tranh cử vừa rồi của thống đốc đấy!",
  "Almost done.": "Sắp xong rồi.",
  "Keep an eye out for the zombies--I'll be as quiet as I can, but... well I mean... I'm using a fucking hammer.": "Để mắt đến lũ zombie giùm--Tôi sẽ cố gắng giữ im lặng nhất có thể, nhưng... ừ thì ý tôi là... tôi đang dùng một cái búa khốn khiếp cơ mà.",
  "COMPLETED: Combat Training": "ĐÃ HOÀN THÀNH: Huấn Luyện Chiến Đấu",
  "Clear the Infestation": "Dọn dẹp Ổ dịch (Infestation)",
  "Kilo went out on a supply run and found a really nice stash of resources. He'd like some help getting it back to base.": "Kilo đã ra ngoài tìm đồ tiếp tế và tìm thấy một kho tài nguyên thực sự ngon lành. Anh ấy muốn có người phụ mang nó về căn cứ.",
  "I'm not 100% sure it's spoiled, but better safe than sorry.": "Tôi không dám chắc 100% là nó đã hỏng, nhưng cẩn tắc vô ưu.",
  "Just turn me loose in a room and I'll strip it to the copper in the walls.": "Cứ thả tôi vào một căn phòng và tôi sẽ lột sạch mọi thứ cho đến tận mấy sợi dây đồng trong tường.",
  "A greenhouse provides higher yield crops than a garden.": "Một nhà kính (greenhouse) mang lại năng suất cây trồng cao hơn so với một khu vườn (garden).",
  "I've got a visual.": "Tôi đã nhìn thấy mục tiêu.",
  "We've killed plenty of those already, if you want to go through the pile.": "Chúng tôi đã giết rất nhiều đứa như thế rồi, nếu cậu muốn đi lục lọi trong đống xác đó.",
  "Skills like these you gotta acquire by attending a fancy culinary school--or burning a lot of food. Either way, it's not happening now.": "Những kỹ năng kiểu này cậu chỉ có thể có được bằng cách theo học một trường ẩm thực danh giá--hoặc làm cháy rất nhiều đồ ăn. Dù sao thì, chuyện đó không xảy ra bây giờ đâu.",
  "Richey": "Richey",
  "I'd appreciate a little covering fire.": "Tôi sẽ rất cảm kích nếu được bắn yểm trợ một chút.",
  "We've got an injured man here. If anybody knows where we can find Doctor Hanson, please let us know on this frequency.": "Chúng tôi có một người bị thương ở đây. Nếu ai biết có thể tìm Bác sĩ Hanson ở đâu, xin hãy thông báo cho chúng tôi trên tần số này.",
  "Comforter": "Người An Ủi",
  "Dora": "Dora",
  "Free and clear, we'll be there shortly.": "Đường đã quang đãng, chúng tôi sẽ đến đó ngay.",
  "Just stay out of my way and let me work.": "Cứ tránh đường và để tôi làm việc đi.",
  "Ricky": "Ricky",
  "That was some real hero shit.": "Đó quả là một hành động anh hùng chết tiệt thật sự đấy.",
  "Toothbrush": "Bàn chải đánh răng",
  "Can they help us?": "Liệu họ có thể giúp chúng ta không?",
  "Now remember, what I need is a single round to the snot locker.": "Bây giờ nhớ kỹ nhé, những gì tôi cần là một phát đạn duy nhất vào ngay giữa mặt.",
  "I mean, I got mugged once in Danforth. Freaked me out so bad I didn't leave my apartment for a month.": "Ý tôi là, tôi từng bị cướp một lần ở Danforth. Nó làm tôi sợ phát khiếp đến mức không dám ra khỏi căn hộ của mình suốt một tháng liền.",
  "Refills some brass to generate a few magazines' worth of 9mm ammunition.": "Đúc lại vài vỏ đạn bằng đồng để tạo ra lượng đạn 9mm đủ cho vài băng.",
  "Additives": "Chất phụ gia",
  "Yes! Humans 1, flesh-eating freak monsters 0!": "Đúng vậy! Con người 1, lũ quái vật ăn thịt người quái thai 0!",
  "We need to stay close to home!": "Chúng ta cần phải ở gần nhà!",
  "Looks like we're gonna have to crack open the armory.": "Có vẻ như chúng ta sẽ phải phá cửa kho vũ khí (armory) thôi.",
  "A guard tower would help.": "Một tháp canh (guard tower) sẽ giúp ích đấy.",
  "Cycle Missions": "Chuyển Đổi Các Nhiệm Vụ",
  "CLEO Cra-B": "Súng CLEO Cra-B",
  "Those guys are in real trouble.": "Mấy người đó đang gặp rắc rối thực sự đấy.",
  "Any idea who's behind it?": "Có ý tưởng gì về việc ai đứng đằng sau chuyện này không?",
  "Mission accomplished.": "Nhiệm vụ hoàn thành.",
  "Montano": "Montano",
  "The Sniper": "Kẻ Bắn Tỉa (The Sniper)",
  "And, y'know, no offense, but there are people here I do not want to share a bed with. Even if it is in shifts.": "Và, cậu biết đấy, không có ý xúc phạm đâu, nhưng có những người ở đây mà tôi không muốn ngủ chung giường đâu. Ngay cả khi có chia ca đi chăng nữa.",
  "Just like target practice.": "Cứ như đang luyện tập bắn bia vậy."
};

const file = 'output/languages/chunks/btxt_chunk_117.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_117.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk117[r.sourceText]) {
    r.translatedText = chunk117[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 117 successfully!');
