const fs = require('fs');
const chunk155 = {
  "Affirmative, sir. He died during a zed attack.": "Rõ, thưa ngài. Anh ấy đã hy sinh trong một cuộc tấn công của zed.",
  "TIP: Press [sprint] + [cover] to roll.": "MẸO: Nhấn [sprint] + [cover] để lộn nhào (roll).",
  "The latest update from Capt. Montressor in Trumbull Valley is overdue. \r\nThe success of Operation: Washout may be jeopardized.": "Bản cập nhật mới nhất từ Đại úy Montressor ở Thung lũng Trumbull đã quá hạn.\r\nSự thành công của Chiến dịch Washout có thể đang bị đe dọa.",
  "Nicole": "Nicole",
  "Blades": "Vũ Khí Sắc Nhọn (Blades)",
  "You better sleep lightly. Because I'm coming for you.": "Mày tốt nhất là nên ngủ một mắt đi. Vì tao sẽ đến tìm mày đấy.",
  "A place to make the things we don't have, and maintain the things we do.": "Một nơi để chế tạo những thứ chúng ta đéo có, và bảo trì những thứ chúng ta đang có.",
  "I'll follow your lead.": "Tôi sẽ nghe theo chỉ dẫn của cậu.",
  "Gets hit on constantly. Really sick of every guy thinking he'll be the \"last man on earth\".": "Liên tục bị tán tỉnh. Thực sự phát ốm vì mọi gã đàn ông đều nghĩ hắn sẽ là \"người đàn ông cuối cùng trên trái đất\".",
  "Okay. Looks like no zombies were close by.": "Được rồi. Có vẻ như đéo có zombie nào ở gần đây.",
  "That kinda shit's gonna get us all dead.": "Cái loại chết tiệt đó sẽ khiến tất cả chúng ta mất mạng đấy.",
  "Looks like an infestation.": "Trông giống như một ổ dịch (infestation).",
  "Speakers - QSound": "Loa - QSound",
  "The middle Wilkerson brother. A cold-blooded schemer.": "Người anh thứ nhà Wilkerson. Một kẻ mưu mô máu lạnh.",
  "Liv": "Liv",
  "I heard from a buddy of mine down in Marshall the Army rolled up on them and seized all their guns.": "Tôi nghe một người bạn của tôi ở Marshall nói rằng Quân đội đã ập đến chỗ họ và tịch thu toàn bộ súng ống của họ.",
  "Digging a latrine sounds like a shit job, but everyone will thank me later.": "Đào một cái nhà xí (latrine) nghe có vẻ như một công việc chó má, nhưng mọi người sẽ cảm ơn tôi sau.",
  "Don't worry, I'll make sure you look good too.": "Đừng lo, tôi sẽ đảm bảo cậu trông cũng bảnh tỏn luôn.",
  "Practiced Photography": "Từng Luyện Tập Nhiếp Ảnh",
  "Gianna": "Gianna",
  "We all enjoy killin' zeds, but maybe bein' quiet is a better idea?": "Tất cả chúng ta đều thích giết bọn zed, nhưng có lẽ giữ im lặng là một ý kiến hay hơn chăng?",
  "An outpost here could keep the hordes back.": "Một tiền đồn (outpost) ở đây có thể kìm chân bầy horde.",
  "Former county commissioner. Slick bastard. Good at procuring whatever you need ... especially if it's a car.": "Cựu ủy viên quận. Thằng khốn láu cá. Rất giỏi trong việc kiếm chác bất cứ thứ gì bạn cần ... đặc biệt nếu đó là một chiếc xe hơi.",
  "Okay. I'll follow your lead.": "Được rồi. Tôi sẽ nghe theo chỉ dẫn của cậu.",
  "Liked Tailgating": "Thích Tham Gia Các Buổi Tiệc Tùng Tại Cốp Xe (Tailgating)",
  "Micah": "Micah",
  "Any time I can do you a favor, just say the word.": "Bất cứ lúc nào tôi có thể giúp cậu, chỉ cần nói một lời thôi.",
  "Better do it quick then. Before it starts to move.": "Tốt hơn hết là làm nhanh lên. Trước khi nó bắt đầu di chuyển.",
  "Be careful in there.": "Cẩn thận đấy.",
  "+30% to flirt, but 15% chance of lawsuit or impeachment.": "Tăng 30% khả năng tán tỉnh, nhưng có 15% nguy cơ bị kiện tụng hoặc luận tội.",
  "The longer this goes on, the more I think the ones who got turned were the lucky ones. -%1$s": "Chuyện này càng kéo dài, tôi càng nghĩ rằng những người bị biến đổi lại là những kẻ may mắn. -%1$s",
  "We have time to do this right.": "Chúng ta có thời gian để làm việc này cho đúng đắn.",
  "You gonna sit around with your thumb up your ass or help out?": "Cậu định ngồi lì đó đút ngón tay cái vào lỗ đít hay ra tay giúp một tay vậy?",
  "Search Sounds": "Âm Thanh Tìm Kiếm",
  "Tells my dad not to worry so much. \"Just remember me in November.\" It was $10,000.": "Nói với bố tôi đừng quá lo lắng. \"Chỉ cần nhớ đến cháu vào tháng Mười Một.\" Nó trị giá 10.000 đô la.",
  "League Champion": "Nhà Vô Địch Giải Đấu",
  "Swing Training Bat": "Gậy Tập Đánh Bóng (Swing Training Bat)",
  "Get a tour of the church.": "Đi một vòng tham quan nhà thờ.",
  "So what are you guys doing here? All the info I have says you pulled out days ago.": "Vậy các anh đang làm gì ở đây? Tất cả thông tin tôi có đều nói rằng các anh đã rút lui vài ngày trước rồi cơ mà.",
  "2 Outposts - Incendiary Barrage": "2 Tiền Đồn (Outposts) - Loạt Đạn Cháy (Incendiary Barrage)",
  "We get out of this, I oughta take you hunting!": "Khi chúng ta thoát khỏi chuyện này, tôi phải dẫn cậu đi săn mới được!",
  "Uh-huh.... And were you \"scouting\" with Eli Wilkerson?": "Uh-huh.... Và cô đang đi \"trinh sát\" cùng với Eli Wilkerson à?",
  "I've got a couple of leads I can check out. Meantime, your people ought to start stockpiling supplies.": "Tôi có vài manh mối có thể kiểm tra. Trong thời gian đó, người của cậu nên bắt đầu dự trữ nguồn cung cấp đi.",
  "Time's a-wasting.": "Thời gian đang cạn dần.",
  "118 HERO Jacob Ritter": "118 ANH HÙNG (HERO) Jacob Ritter",
  "We can always use a little more help.": "Chúng ta luôn cần thêm một chút giúp đỡ.",
  "Edged Weapon": "Vũ Khí Sắc Nhọn (Edged Weapon)",
  "You Gotta Believe": "Bạn Phải Tin Tưởng (You Gotta Believe)",
  "We've lost our target.": "Chúng ta đã mất dấu mục tiêu.",
  "We've noticed some new survivor activity.": "Chúng tôi nhận thấy có một số hoạt động mới của những người sống sót.",
  "Target identified. We're zeroed in, contact in 3... 2... 1...": "Đã xác định mục tiêu. Chúng tôi đã nhắm chuẩn, tiếp xúc trong 3... 2... 1...",
  "Master the use of Rifles.": "Làm chủ việc sử dụng Súng Trường (Rifles).",
  "You've got to think about defense too. You can't just wade in like that.": "Cậu cũng phải nghĩ đến phòng thủ nữa chứ. Cậu đéo thể cứ thế lao vào như vậy được.",
  "<Sharp inhale>": "<Hít một hơi thật sâu>",
  "How can you pass that up? Make the call. You know you want to.": "Làm sao cậu có thể bỏ lỡ chuyện đó được? Hãy đưa ra quyết định đi. Cậu biết là cậu muốn thế mà.",
  "We're out.": "Chúng ta hết rồi.",
  "You can radio home for SCAVENGERS instead and let someone else do the heavy lifting.": "Thay vào đó, bạn có thể gọi bộ đàm về nhà cho NHỮNG NGƯỜI NHẶT MÓT (SCAVENGERS) và để người khác làm công việc nặng nhọc này.",
  "Reinforcements": "Viện Binh (Reinforcements)",
  "We need to thin the ranks a little. Take out this horde before it gets any bigger.": "Chúng ta cần làm mỏng đội hình một chút. Tiêu diệt bầy horde này trước khi nó trở nên lớn hơn.",
  "Suppressor won't work on this one.": "Nòng giảm thanh sẽ đéo có tác dụng với khẩu này đâu.",
  "Zeds incoming on your right!": "Bọn zed đang lao tới từ bên phải của cậu!",
  "What a piece of crap. Guess I could use it to break a window.": "Thật là một đống rác rưởi. Đoán là tôi có thể dùng nó để đập vỡ một cái cửa sổ.",
  "Whoa, hold up!": "Chà, đợi đã!",
  "This is a rescue mission, Vince. What do you think?": "Đây là một nhiệm vụ giải cứu, Vince. Cậu nghĩ sao?",
  "This place is nice and isolated. That's a big plus except when we need to make a supply run. - %1$s": "Nơi này khá tuyệt và hẻo lánh. Đó là một điểm cộng lớn ngoại trừ lúc chúng ta cần phải thực hiện một chuyến đi tìm nhu yếu phẩm. - %1$s",
  "We'll have the necessary tools, and the necessary hygiene, to perform more serious medical procedures.": "Chúng ta sẽ có đủ các dụng cụ cần thiết, và đảm bảo điều kiện vệ sinh cần thiết, để thực hiện các quy trình y tế nghiêm trọng hơn.",
  "Ten-four, I'm ready.": "Đã nhận rõ (Ten-four), tôi đã sẵn sàng.",
  "Now we gotta throw out all this food because vermin got to it!": "Giờ thì chúng ta phải vứt hết đống thức ăn này đi vì bọn sâu bọ đã đánh hơi thấy rồi!",
  "I could keep this up all day!": "Tôi có thể duy trì phong độ này cả ngày!",
  "I was saving that!": "Tôi đang để dành thứ đó mà!",
  "Gun Oil": "Dầu Lau Súng (Gun Oil)",
  "He's the kind of guy you know will have your back, even if you've treated him like shit. Logged hundreds of hours at the shooting range.": "Anh ấy là kiểu người mà bạn biết sẽ luôn yểm trợ phía sau bạn, ngay cả khi bạn đối xử với anh ấy như rác rưởi. Đã có hàng trăm giờ kinh nghiệm tại trường bắn.",
  "Is that all you got left?": "Đó là tất cả những gì cậu còn lại sao?",
  "Alamo Kitchen": "Nhà Bếp Alamo",
  "Olson": "Olson",
  "Black pen on a yellow legal notepad, there is a bloody thumbprint in the corner.": "Bút mực đen viết trên cuốn sổ tay pháp lý màu vàng, có một dấu vân tay đẫm máu ở góc.",
  "You got a knack for this, you know that?": "Cậu có năng khiếu trong việc này đấy, cậu biết đéo?",
  "SitRep: World Update": "Báo Cáo Tình Hình (SitRep): Cập Nhật Thế Giới",
  "Athletic Tape": "Băng Dính Thể Thao",
  "Landing Zone": "Khu Vực Hạ Cánh (Landing Zone)",
  "You're not fine. You need to go to the infirmary.": "Cậu đéo ổn đâu. Cậu cần phải đến bệnh xá.",
  "Progress Score": "Điểm Tiến Độ",
  "Gardening Magazines": "Tạp Chí Làm Vườn",
  "Get me on that helicopter, and I'll show you what I can do.": "Đưa tôi lên chiếc trực thăng đó, và tôi sẽ cho anh thấy tôi có thể làm được gì.",
  "Explosives acquired.": "Thu được chất nổ.",
  "%1$s called in - said the guy who was willing to trade with us backed out. Guess we shoulda been a little quicker on the draw, - %2$s": "%1$s đã gọi đến - nói rằng cái gã sẵn sàng giao dịch với chúng ta đã rút lui rồi. Có lẽ chúng ta đáng nhẽ ra nên hành động nhanh hơn một chút, - %2$s",
  "Goddamn zombies overran everything we built. Feel like coming back and trying again?": "Bọn zombie chết tiệt đã càn quét mọi thứ mà chúng ta cất công xây dựng. Có muốn quay lại và thử lại đéo?",
  "I just, I feel terrible. They were always asking for help... I guess this time they really needed it.": "Tôi chỉ, tôi cảm thấy tồi tệ quá. Họ đã luôn cầu cứu... Tôi đoán lần này họ thực sự cần sự giúp đỡ.",
  "It's way too easy for zombies to ambush us. We need to put up a watchtower and curb that shit.": "Quá dễ dàng để bọn zombie phục kích chúng ta. Chúng ta cần phải dựng một tháp canh và chấm dứt cái thứ chó đẻ đó.",
  "A good kid, but a little flaky.": "Một đứa trẻ ngoan, nhưng hơi lập dị.",
  "Anyway, she wants to call herself Becca now, that's her business.": "Dù sao thì, bây giờ cô ấy muốn tự gọi mình là Becca, đó là chuyện của cô ấy.",
  "<Groaning, coughing>": "<Tiếng rên rỉ, ho khan>",
  "Ronnie": "Ronnie",
  "Shotgun: 590 SP": "Súng Săn (Shotgun): Súng 590 SP",
  "The most direct and simplest way to put an end to a zombie is in hand-to-hand combat. Every weapon is a little different, but it always comes down to the same thing: remove the head or destroy the brain.": "Cách trực tiếp và đơn giản nhất để kết liễu một con zombie là bằng chiến đấu giáp lá cà (hand-to-hand combat). Mỗi loại vũ khí đều có một chút khác biệt, nhưng nó luôn tuân theo một nguyên lý chung: loại bỏ cái đầu hoặc phá hủy não bộ.",
  "Rumors spread 20% faster.": "Tin đồn lan truyền nhanh hơn 20%.",
  "I guess they were trying to keep it quiet, but that didn't last too long. People figured it out pretty quick.": "Tôi đoán họ đã cố gắng giữ kín chuyện này, nhưng điều đó đéo kéo dài được lâu. Mọi người đã phát hiện ra chuyện đó khá nhanh.",
  "Corporal Torres.": "Hạ sĩ Torres.",
  "Let's do this.": "Làm thôi nào.",
  "Amado": "Amado"
};

const file = 'output/languages/chunks/btxt_chunk_155.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_155.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk155[r.sourceText]) {
    r.translatedText = chunk155[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 155 successfully!');
