const fs = require('fs');
const chunk104 = {
  "Joyce": "Joyce",
  "Complete challenges listed in the Challenges Tab of your Journal to unlock new Heroes.": "Hoàn thành các thử thách được liệt kê trong Tab Thử Thách (Challenges) của Nhật ký để mở khóa các Anh Hùng mới.",
  "Would you like to load the existing save game?": "Bạn có muốn tải bản lưu game hiện tại không?",
  "Boys! Get your lazy asses out here and bring this stuff inside!": "Các chàng trai! Nhấc mấy cái mông lười biếng của các cậu ra đây và mang đống đồ này vào trong đi!",
  "Are you hearing this shit?": "Cậu có nghe thấy cái thứ khốn kiếp này không?",
  "Destroy hordes to slow the spread of infestations.": "Tiêu diệt các bầy zombie để làm chậm sự lây lan của các Ổ Dịch.",
  "%d Daily Rations of Food": "%d Khẩu phần Thức ăn Hàng ngày",
  "Ain't safe to keep runnin' in the red like that!": "Cứ chạy thục mạng khi thể lực báo đỏ thế kia thì không an toàn chút nào đâu!",
  "Install Now": "Cài Đặt Ngay",
  "You see them up ahead there?": "Cậu có thấy chúng ở phía trước không?",
  "Cross": "Cross",
  "36 GENERIC Winona Hesse": "36 GENERIC Winona Hesse",
  "Or you're going to answer to me.": "Hoặc cậu sẽ phải ăn nói với tôi.",
  "Maybe they can get us out of here. -%1$s": "Biết đâu họ có thể đưa chúng ta rời khỏi đây. -%1$s",
  "Can't be too careful.": "Cẩn thận không bao giờ thừa.",
  "Jump Rope": "Dây Nhảy",
  "Ahhhh!": "Áááá!",
  "Dammit, here they come again!": "Chết tiệt, chúng lại đến nữa rồi!",
  "I skipped the tour, but Lily still had something to say: I need to score some antibiotics for Ed or he's going to die. - %1$s": "Tôi đã bỏ qua chuyến đi dạo, nhưng Lily vẫn có điều muốn nói: Tôi cần tìm thuốc kháng sinh cho Ed nếu không anh ấy sẽ chết. - %1$s",
  "Meantime, just sit tight.": "Trong lúc đó, hãy cứ ngồi yên chờ đợi.",
  "Zeds. 9 o'clock.": "Zeds. Hướng 9 giờ.",
  "93 GENERIC Rick Ford": "93 GENERIC Rick Ford",
  "Dead": "Đã Chết",
  "You can choose a special technique related to this skill if you haven't already chosen a special technique.": "Bạn có thể chọn một tuyệt kỹ liên quan đến kỹ năng này nếu bạn chưa chọn tuyệt kỹ nào.",
  "Woah, woah. Give that noisemaker a little more room next time!": "Khoan, khoan đã. Lần sau hãy nhường chỗ cho cái thứ gây ồn ào đó một chút nhé!",
  "What's the word?": "Có tin tức gì không?",
  "The best selling shotgun in history.": "Khẩu shotgun bán chạy nhất trong lịch sử.",
  "No big thing.": "Chẳng có gì to tát cả.",
  "You're pretty banged up. Painkillers won't be enough.": "Cậu bị bầm dập khá nặng đấy. Thuốc giảm đau sẽ không đủ đâu.",
  "Hurry up and wait.": "Nhanh lên và chờ đợi.",
  "Runs a conspiracy theory blog.": "Điều hành một trang blog chuyên về thuyết âm mưu.",
  "The fuck is her problem?": "Cô ta bị cái đéo gì vậy?",
  "Ready to roll in a minute.": "Sẵn sàng lên đường trong một phút nữa.",
  "Nicolas": "Nicolas",
  "I don't like the fact that we're not hearing any transmissions from outside the valley.": "Tôi không thích việc chúng ta không bắt được bất kỳ tín hiệu nào từ bên ngoài thung lũng.",
  "Somebody's got to take care of them.": "Phải có ai đó lo liệu cho họ chứ.",
  "Grassi": "Grassi",
  "Tell you what, though. Give me a little while to put something together. A sort of \"welcome to the neighborhood\" present. I'll give you a call when it's ready. See you then?": "Nói cậu nghe này. Cho tôi chút thời gian để chuẩn bị vài thứ. Một kiểu quà \"chào mừng đến với khu phố\". Tôi sẽ gọi cho cậu khi làm xong. Hẹn gặp lại nhé?",
  "DECLINE MISSION. Are you willing to turn a blind eye to what's happening?": "TỪ CHỐI NHIỆM VỤ. Bạn có sẵn sàng nhắm mắt làm ngơ trước những gì đang diễn ra không?",
  "Let me guess. Hordes of shrieking, ravenous undead?": "Để tôi đoán xem. Những bầy xác sống đang la hét và đói khát?",
  "I like a fight as much as the next gal, but maybe we should be quieter.": "Tôi cũng thích đánh nhau như bất kỳ cô gái nào khác, nhưng có lẽ chúng ta nên giữ im lặng hơn.",
  "No, son, it's not just one. It's a horde smorgasbord.": "Không đâu chàng trai, không chỉ có một bầy. Đó là cả một bàn tiệc buffet zombie.",
  "135 NPC SWAT Officer": "135 NPC Sĩ quan SWAT",
  "You might just be almost as badass as me!": "Cậu có lẽ cũng gần ngầu bằng tôi đấy!",
  "We can work faster if we search together. Let's go.": "Chúng ta có thể làm việc nhanh hơn nếu cùng nhau tìm kiếm. Đi thôi.",
  "I couldn't be a part of this community anymore. I'm sorry.": "Tôi không thể là một phần của cộng đồng này được nữa. Tôi xin lỗi.",
  "I'll Be There For You": "Tôi Sẽ Ở Đó Vì Cậu",
  "I'll tell the others to get moving. And...thank you.": "Tôi sẽ bảo những người khác di chuyển. Và... cảm ơn.",
  "Sam": "Sam",
  "Advice: Upgrade to Dojo": "Lời khuyên: Nâng cấp lên Võ Đường (Dojo)",
  "Jeremy": "Jeremy",
  "We are vastly outnumbered, facing an enemy that knows neither respite nor pity. Alone, we don't stand a chance.": "Chúng ta đang bị áp đảo hoàn toàn về quân số, phải đối mặt với một kẻ thù không biết mệt mỏi cũng chẳng có sự thương xót. Đơn độc, chúng ta không có lấy một cơ hội.",
  "I'm right here, dumbass. Can't be in two places at once.": "Tao đang ở ngay đây, đồ ngu. Không thể phân thân ở hai nơi cùng lúc được.",
  "MORALE ISSUE: Insensitive Personality": "VẤN ĐỀ NHUỆ KHÍ: Tính Cách Vô Tâm",
  "It's hard to stay focused. I need food. (REDUCED STAMINA.)": "Rất khó để giữ tập trung. Tôi cần thức ăn. (GIẢM THỂ LỰC TỐI ĐA.)",
  "The good news is we're still well-stocked for ammo.": "Tin tốt là chúng ta vẫn còn dự trữ khá nhiều đạn dược.",
  "Naw, fuck that. Stay put for now.": "Đéo, bỏ mẹ chuyện đó đi. Tạm thời cứ đứng yên đấy.",
  "How about it?": "Thế thì sao?",
  "Sword": "Kiếm",
  "This space is devoted to physical training. It can be upgraded to sharpen our skills using melee weapons and firearms.": "Không gian này dành riêng cho việc huấn luyện thể chất. Nó có thể được nâng cấp để rèn luyện kỹ năng sử dụng vũ khí cận chiến và súng đạn.",
  "Stockton": "Stockton",
  "NEW TRAIT: Sick": "ĐẶC ĐIỂM MỚI: Đổ Bệnh",
  "Vitality will gradually recover while resting at home. It should take about 15 hours to get back to full Vitality.": "Sinh lực sẽ dần phục hồi khi nghỉ ngơi tại nhà. Sẽ mất khoảng 15 giờ để phục hồi hoàn toàn.",
  "She does have a point.": "Cô ấy nói cũng có lý.",
  "%s: %s": "%s: %s",
  "Rifle: Sidekick": "Súng trường: Sidekick",
  "Talk to the boys if you're looking to trade; I'm busy here.": "Nói chuyện với bọn con trai nếu cậu muốn giao dịch; tôi đang bận ở đây.",
  "I know, right? Like that asshole'd have duct tape.": "Tôi biết mà, phải không? Làm như tên khốn đó có băng keo không bằng.",
  "Dancer": "Vũ Công",
  "Try not to lose hope. Another opportunity will present itself.": "Cố gắng đừng tuyệt vọng. Một cơ hội khác sẽ tự xuất hiện thôi.",
  "We are now facing an entirely different kind of crisis. Sergeant Eldridge believes he has orders to nuke the city before the zombies get out. I've spoken with him, and bought us some time, but I don't know how much. Who knows ... maybe he's right.": "Chúng ta hiện đang phải đối mặt với một loại khủng hoảng hoàn toàn khác. Trung sĩ Eldridge tin rằng anh ta có lệnh ném bom hạt nhân vào thành phố trước khi lũ zombie thoát ra. Tôi đã nói chuyện với anh ta, và câu giờ cho chúng ta được một chút, nhưng tôi không biết là bao lâu. Ai mà biết được... có thể anh ta đúng.",
  "Good thing nobody took any of these yet. God knows what weird side effects they'd have after all this time. -%1$s": "May mà chưa có ai dùng mấy thứ này. Có Chúa mới biết chúng sẽ gây ra những tác dụng phụ kỳ quái gì sau ngần ấy thời gian. -%1$s",
  "It's too late to run. We'll have to stand and fight.": "Đã quá muộn để bỏ chạy. Chúng bản sẽ phải ở lại và chiến đấu.",
  "I want you to know how much I appreciate all your efforts.": "Tôi muốn cậu biết rằng tôi trân trọng mọi nỗ lực của cậu đến nhường nào.",
  "Artillery barrage on my mark!": "Trận địa pháo khai hỏa theo hiệu lệnh của tôi!",
  "This fuckin' sucks.": "Chuyện này tồi tệ vãi cứt.",
  "SCAVENGING: Medicine": "THU THẬP: Thuốc Men",
  "That new outpost could make a big difference.": "Tiền đồn mới đó có thể tạo ra một sự khác biệt lớn.",
  "CHARITY: Soup Kitchen": "TỪ THIỆN: Bếp ĂN Tình Thương",
  "Hey!": "Này!",
  "Infirmary's going to fill up fast at this rate.": "Bệnh xá sẽ chật kín chỗ rất nhanh với cái đà này.",
  "Hey, we were counting on you!": "Này, chúng tôi đã trông cậy vào cậu đấy!",
  "AN ELEVATED PERSPECTIVE": "MỘT GÓC NHÌN TỪ TRÊN CAO",
  "Snipe Zombies": "Bắn Tỉa Zombie",
  "I wish I'd gotten to know him better.": "Ước gì tôi đã có cơ hội biết anh ấy rõ hơn.",
  "Dim Bulb": "Bóng Đèn Mờ",
  "Hadley Westen is on the way to the capital.": "Hadley Westen đang trên đường đến thủ đô.",
  "Good to know the folks here have got my back.": "Thật tốt khi biết mọi người ở đây luôn hậu thuẫn cho tôi.",
  "Now they're tellin' us a feral's lurkin' out there. Fuck, I'm stayin' home.": "Giờ thì họ bảo chúng ta có một con Feral đang rình rập ngoài kia. Khốn kiếp, tôi thà ở nhà còn hơn.",
  "Ball Bearings": "Vòng Bi (Bạc Đạn)",
  "SHERIFF PARSONS. Brings in a SWAT team to help you for a couple of minutes.": "CẢNH SÁT TRƯỞNG PARSONS. Gọi một đội SWAT đến hỗ trợ bạn trong vài phút.",
  "Seriously? We failed her, and we failed this town. Forgive me for not agreeing with you.": "Thật sao? Chúng ta đã bỏ rơi cô ấy, và chúng ta đã làm thị trấn này thất vọng. Thứ lỗi cho tôi vì không thể đồng tình với cậu.",
  "Commemorative Hockey Stick": "Gậy Khúc Côn Cầu Kỷ Niệm",
  "Building a fresh Barracks to house our newest reinforcements.": "Đang xây dựng một Trại lính mới để làm chỗ ở cho những tân binh của chúng ta.",
  "The Survivor": "Kẻ Sống Sót",
  "I've been trying for half an hour. We've got nothing.": "Tôi đã cố gắng suốt nửa giờ đồng hồ. Vẫn không có kết quả gì.",
  "That looks fuckin' useful.": "Thứ đó trông có vẻ cực kỳ hữu ích đấy.",
  "I found %3$s, but it was too late. I did what I had to. -%1$s": "Tôi đã tìm thấy %3$s, nhưng quá muộn rồi. Tôi đã làm những gì phải làm. -%1$s",
  "Talk": "Nói chuyện",
  "Calliope": "Calliope"
};

const file = 'output/languages/chunks/btxt_chunk_104.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_104.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk104[r.sourceText]) {
    r.translatedText = chunk104[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 104 successfully!');
