const fs = require('fs');
const chunk196 = {
  "Got 'em! We're good.": "Tóm được bọn chúng rồi! Chúng ta đã an toàn.",
  "Shit. We got an infestation to deal with.": "Chết tiệt thật. Chúng ta đang có một cái ổ dịch (infestation) cần phải giải quyết đây.",
  "What, you looking for food?": "Sao cơ, cậu đang muốn tìm kiếm thức ăn (food) à?",
  "Get clear! I got these assholes.": "Tránh ra đi! Tôi đã tóm được những tên khốn này cmnr.",
  "Good work.": "Làm tốt lắm.",
  "Move": "Di Chuyển Nhanh (Move)",
  "Yeah, I think I can make it from here.": "Yeah, tôi nghĩ là tôi có thể tự mình xoay sở được từ đây.",
  "We're done. Good luck out here.": "Chúng tôi đã xong việc ở đây rồi. Chúc cậu gặp nhiều may mắn ở ngoài này nhé.",
  "Spotted a Feral on its way toward us and took it out before it became a threat. - %1$s.": "Vừa mới phát hiện ra một con Feral đang lao thẳng về phía của chúng ta và đã tiêu diệt nó thành công trước khi nó có thể trở thành một mối đe dọa thực sự. - %1$s.",
  "Mission\rOpportunity": "Cơ Hội Nhận\rNhiệm Vụ (Mission)",
  "Time for a break!": "Đã đến lúc cần phải nghỉ ngơi một chút rồi!",
  "Jack": "Jack",
  "Hell of a fight.": "Đúng là một trận chiến vãi cả đái.",
  "SMG: G 18 (Compensated)": "Súng Tiểu Liên (SMG): G 18 (Đã Gắn Ống Bù Giật Compensated)",
  "Adriana": "Adriana",
  "Food Supply": "Nguồn Cung Cấp Thức Ăn (Food Supply)",
  "We depend on our comms to maintain contact with the brass, and with each other. We can also use them to reach out to other units stranded in the city.": "Chúng ta phải phụ thuộc vào các thiết bị liên lạc (comms) để có thể duy trì việc kết nối với các cấp chỉ huy (brass), và với những người khác. Chúng ta cũng có thể sử dụng chúng để tìm cách liên lạc với các đơn vị đang bị mắc kẹt khác ở trong thành phố.",
  "%1$s is gone. Nobody seems to know where or why. Guess the fear finally got to 'em. At least it doesn't look like they swiped too much food on the way out. - %2$s": "%1$s đã rời đi cmnr. Dường như đéo có một ai biết được là cậu ấy đã đi đâu hay tại sao lại làm như vậy. Tôi đoán là có lẽ nỗi sợ hãi cuối cùng cũng đã đánh gục được cậu ấy. Ít nhất thì có vẻ như cậu ấy đã đéo lấy cắp đi quá nhiều lượng thức ăn (food) trước khi rời khỏi nơi này. - %2$s",
  "Need Good Researcher": "Đang Cần Một Chuyên Gia Nghiên Cứu (Researcher) Giỏi",
  "All this medicine just expired. Any of you people check the expiration date?": "Tất cả những loại thuốc (medicine) này đều đã hết hạn sử dụng (expired) cmnr. Có ai trong số các người từng chịu kiểm tra cái ngày hết hạn (expiration date) đéo vậy hả?",
  "Traded supplies.": "Vừa mới trao đổi các vật tư đồ tiếp tế (supplies).",
  "Don't you let 'em bust through!": "Đừng để cho bọn chúng có cơ hội đột phá vượt qua hàng rào phòng ngự!",
  "Invited a community member to follow you.": "Đã mời (Invited) một thành viên ở trong cộng đồng đi theo bạn.",
  "Well, the freak's dead, but sounds like %1$s bit off more than they could chew. - %2$s": "Chà, con quái vật đó đã chết cmnr, nhưng có vẻ như %1$s đã tự rước lấy quá nhiều rắc rối hơn mức mà cậu ấy có thể giải quyết được. - %2$s",
  "Unhappy.": "Đang Cảm Thấy Đéo Vui (Unhappy).",
  "There's a zombie horde in the way.": "Đang có một bầy zombie horde ở trên đường đi.",
  "Man, that freak is beyond just being a freak.": "Trời ạ, con quái vật đó đéo chỉ đơn thuần là một con quái vật bình thường đéo đâu.",
  "Car's on its way.": "Chiếc xe ô tô đang trên đường đi tới chỗ của cậu rồi.",
  "SET UP: Alamo Kitchen": "THIẾT LẬP (SET UP): Nhà Bếp Ở Khu Nhà Hàng Alamo (Alamo Kitchen)",
  "Nobody minds if you're getting shit done and you need extra stuff.": "Sẽ đéo có một ai để bụng nếu như cậu hoàn thành tốt các công việc và cần đến một vài thứ đồ đạc khác để sử dụng đâu.",
  "Diane": "Diane",
  "Spotted a freak.": "Vừa phát hiện ra một con quái vật (freak).",
  "Sounds like we're all quiet.": "Có vẻ như tất cả chúng ta đã có thể yên tĩnh trở lại rồi.",
  "Try to keep out of their line of sight. Zeds'll come check out just about anything louder than a solid smack on the head, but their eyesight's for shit.": "Hãy cố gắng tránh xa khỏi tầm nhìn của bọn chúng. Lũ zeds sẽ tìm đến để kiểm tra bất kỳ một thứ đéo gì có âm thanh phát ra lớn hơn một cú đánh thật mạnh vào đầu, nhưng thị lực của bọn chúng thì lại tồi tệ như cứt vậy.",
  "Activate": "Kích Hoạt (Activate)",
  "Hunt a Screamer": "Đi Săn Một Con Screamer",
  "45 GENERIC Eddie Francis": "45 CHUNG (GENERIC) Eddie Francis",
  "So what? Can't we just tear them down like the barricades on the bridge?": "Vậy thì sao chứ? Chẳng lẽ chúng ta đéo thể nào phá hủy bọn chúng giống hệt như những chướng ngại vật ở trên cây cầu đó ư?",
  "I'm starting to think they're more dangerous than the zombies. We're better off on our own, right?": "Tôi đang bắt đầu nghĩ rằng bọn chúng thậm chí còn trở nên nguy hiểm hơn cả lũ zombies ngoài kia nữa đấy. Chúng ta tốt hơn hết là nên tự mình xoay sở một mình, có đúng đéo?",
  "Joe": "Joe",
  "Shouldn't we be out there doing something?": "Chẳng phải là chúng ta nên đi ra ngoài đó và làm một việc đéo gì đó hay sao?",
  "Where are you taking me?": "Các người đang đưa tôi đi đâu thế này?",
  "You won't regret this, I promise.": "Cậu sẽ đéo bao giờ phải cảm thấy hối hận vì quyết định này đâu, tôi hứa đấy.",
  "You are now friends with %1$s.": "Hiện tại bạn đã trở thành bạn bè (friends) với %1$s.",
  "Hey, I have some supplies lying around that might be useful. I assume you want them?": "Này, tôi đang có một vài vật tư đồ tiếp tế (supplies) nằm vứt chỏng chơ ở xung quanh đây có vẻ như sẽ rất hữu ích. Tôi đoán là cậu đang muốn có được chúng phải đéo?",
  "Oh my god!": "Ôi Chúa ơi!",
  "We need some thunder down here.": "Chúng tôi đang rất cần phải có một chút sấm sét (thunder) giáng xuống nơi này.",
  "Feels like a goddamn earthquake!": "Cảm giác giống hệt như đang có một trận động đất chết tiệt vậy!",
  "START MISSION. Get a quick tour and earn a little Trust with Lily.": "BẮT ĐẦU NHIỆM VỤ (START MISSION). Tham gia vào một chuyến tham quan ngắn và kiếm thêm được một chút sự Tin Tưởng (Trust) từ Lily.",
  "Now, which of these do I want...?": "Bây giờ, tôi đang muốn lấy cái đéo nào trong số những thứ này đây...?",
  "It's not time you should be worried about. Searching around for some girl with a wounded man in tow? Sounds like suicide.": "Thời gian đéo phải là thứ mà cậu nên cảm thấy lo lắng vào lúc này đâu. Cậu định đi loanh quanh để tìm kiếm một cô gái nào đó với một gã đàn ông đang bị thương đi cùng ư? Nghe có vẻ giống như là tự sát vậy.",
  "He said no.": "Anh ấy đã nói đéo.",
  "I'm fine, alright?": "Tôi vẫn hoàn toàn ổn, được chứ?",
  "Hmm... I dunno. Could be the old lady that volunteers at the cat rescue. Or, ooh, the Meals on Wheels guy! He's got a van and everything!": "Hmm... Tôi đéo biết nữa. Rất có thể đó là người phụ nữ lớn tuổi từng làm tình nguyện viên tại trung tâm cứu hộ mèo. Hoặc là, ooh, cái gã làm việc cho tổ chức từ thiện Bữa Ăn Trên Những Bánh Xe (Meals on Wheels)! Ông ấy đang sở hữu một chiếc xe tải thùng và tất cả mọi thứ cần thiết khác!",
  "Hey, how's it going?": "Này, mọi chuyện dạo này vẫn diễn ra ổn cả chứ?",
  "A lot of time and money went in to restoring and customizing this old classic. Room for two in front and two in the bed.": "Rất nhiều thời gian và tiền bạc đã được đầu tư để phục chế và độ lại chiếc xe mang phong cách cổ điển này. Nó có đủ chỗ trống dành cho hai người ngồi ở khoang phía trước và hai người ở khoang phía sau xe.",
  "The other inmates used to come to me for all their work. (Tattoo Artist)": "Những người bạn tù khác thường tìm đến tôi để nhờ tôi thực hiện mọi tác phẩm của bọn họ. (Thợ Xăm Hình Tattoo Artist)",
  "Okay, no celebrating. Catch your breath, then get back to the fight.": "Okay, hiện tại đéo phải là lúc để ăn mừng đâu. Hãy lấy lại nhịp thở đi, và sau đó quay trở lại với cuộc chiến.",
  "That's what I thought. It's just a simple radio receiver. Give me a couple minutes, and it'll be toast.": "Đó chính xác là những gì mà tôi đã nghĩ. Nó chỉ là một chiếc máy thu sóng radio (radio receiver) đơn giản mà thôi. Chỉ cần cho tôi một vài phút, và nó sẽ trở thành một đống phế liệu ngay lập tức.",
  "Powerful round used the world over, includes the entirety of the thirty caliber family of rifle ammunition. Used by battle rifles and long range rifles.": "Loại đạn mạnh mẽ được sử dụng phổ biến trên toàn thế giới, bao gồm toàn bộ các loại đạn súng trường thuộc dòng cỡ nòng 30. Thường được sử dụng cho các loại súng trường chiến đấu và súng trường tầm xa.",
  "Zombie kills, feats of fighting skill, completed missions, Home upgrades, and a range of other accomplishments all contribute to the Score that you earn at the end of a Breakdown scenario. Whenever you leave the map (or die), your Score will be displayed, and that same Score will be tracked and recorded on the Breakdown leaderboards. Playing at a higher difficulty has a major positive impact on your Score.": "Tiêu diệt lũ Zombie, thực hiện những kỹ năng chiến đấu siêu phàm (feats of fighting skill), hoàn thành xuất sắc các nhiệm vụ, nâng cấp Căn Cứ (Home), và một loạt những thành tựu khác, tất cả sẽ cùng nhau đóng góp vào Tổng Số Điểm (Score) mà bạn có thể kiếm được sau khi kết thúc một màn chơi Breakdown. Bất cứ khi nào bạn rời khỏi bản đồ (hoặc là chết), Số Điểm (Score) của bạn sẽ được hiển thị ra, và số điểm đó cũng sẽ được hệ thống theo dõi cũng như ghi lại ở trên bảng xếp hạng (leaderboards) của chế độ Breakdown. Việc tham gia vào trò chơi với một cấp độ khó (difficulty) cao hơn sẽ mang lại một tác động cực kỳ to lớn đối với Số Điểm của bạn.",
  "Vienna Cho, radio host, civilian advocate, vocal critic of the military ... bomb disarming expert?": "Vienna Cho, một người dẫn chương trình radio (radio host), người bênh vực cho các quyền lợi của dân thường (civilian advocate), một người chuyên lên tiếng chỉ trích quân đội ... lại là một chuyên gia gỡ bom (bomb disarming expert) ư?",
  "So, what? We need to tear it down? What?": "Vậy thì, sao chứ? Chúng ta cần phải phá hủy nó ư? Cái đéo gì cơ?",
  "We waited too long to make contact with Michele Martin and the HFF. Our scouts report that the building is cleaned out. Looks like someone got out of there in a hurry, burning any documents they couldn't carry.": "Chúng ta đã phải chờ đợi quá lâu để có thể liên lạc được với Michele Martin và tổ chức HFF. Những lính do thám (scouts) của chúng tôi báo cáo lại rằng cái tòa nhà đó hiện đã trống trơn cmnr. Trông có vẻ như một người nào đó đã rời khỏi nơi đó một cách cực kỳ vội vã, thiêu rụi tất cả mọi tài liệu (documents) mà họ đéo thể nào mang theo được.",
  "Meanwhile, enjoy your view of scenic Spencer's Mill, renowned for having the friendliest, flesh-eatingest residents in the valley.": "Trong khoảng thời gian chờ đợi này, hãy tận hưởng cái khung cảnh tuyệt đẹp của Spencer's Mill, nơi vô cùng nổi tiếng vì sở hữu những người dân ăn thịt người thân thiện nhất ở trong vùng thung lũng.",
  "What was he even doing down there?": "Hắn ta đã làm cái trò đéo gì ở dưới đó vậy?",
  "Zombie Horde.": "Bầy Zombie Horde.",
  "I got a feeling we ain't done yet.": "Tôi có một dự cảm rất tồi tệ là chúng ta vẫn chưa thể giải quyết xong chuyện này đâu.",
  "Enthusiastically modified with cheap aftermarket parts. Good top end once it gets going. Seats four high school kids.": "Được sửa đổi độ lại một cách vô cùng nhiệt tình bằng những món phụ tùng hậu mãi cực kỳ rẻ tiền. Tốc độ tối đa rất tốt một khi đã bắt đầu đạt được đà di chuyển. Có thể chứa được 4 đứa học sinh trung học.",
  "I know the way. Just stick close.": "Tôi biết rõ đường đi. Hãy đi sát vào tôi nhé.",
  "LOSING HEARTS": "ĐANG DẦN BỊ ĐÁNH MẤT ĐI TRÁI TIM",
  "If anybody's in the neighborhood, can you please go get my idiot brother?": "Nếu như có bất kỳ một ai đang ở gần khu vực này, các người có thể làm ơn đi tìm thằng anh trai ngu ngốc của tôi được đéo?",
  "DECLINE MISSION. They might have something else for you tomorrow.": "TỪ CHỐI NHIỆM VỤ (DECLINE MISSION). Rất có thể bọn họ sẽ giao cho bạn một việc gì đó khác vào ngày mai.",
  "Believes in you.": "Đang đặt niềm tin (Believes) vào bạn.",
  "All right. I'll let everybody know. You watch yourself out there, too.": "Được rồi. Tôi sẽ báo lại chuyện này cho tất cả mọi người được biết. Cậu cũng phải tự mình cẩn thận khi ở ngoài đó đấy.",
  "Watch the right flank.": "Hãy chú ý quan sát cẩn thận bên sườn phải (right flank).",
  "I'm glad you were able to help me out.": "Tôi rất vui vì cậu đã có thể giúp đỡ tôi giải quyết chuyện này.",
  "Whenever you're ready, we can try that again.": "Bất cứ khi nào cậu đã chuẩn bị sẵn sàng, chúng ta có thể thử làm lại chuyện đó một lần nữa.",
  "Keep clear of the DZ for now. We don't know if this is a supply drop, or something more ... aggressive.": "Hãy tránh xa khu vực thả dù (DZ) ngay lúc này. Chúng ta đéo thể biết chắc chắn được liệu đây có phải là một đợt thả đồ tiếp tế (supply drop) hay đéo, hoặc là một thứ gì đó... hung hãn (aggressive) hơn rất nhiều.",
  "Going in on foot.": "Tôi sẽ đi vào bằng đường bộ.",
  "Great rugged sport utility vehicle. Seats four.": "Chiếc xe thể thao đa dụng với vẻ ngoài cực kỳ mạnh mẽ. Sở hữu 4 chỗ ngồi.",
  "Just gotta keep doing this.": "Chỉ là cần phải tiếp tục thực hiện công việc này.",
  "Shit… That's a zombie horde.": "Chết tiệt thật... Đó là một bầy zombie horde.",
  "Shotgun: 870 Aggressor AD": "Súng Shotgun: 870 Aggressor AD",
  "Thanks, we've got it from here.": "Cảm ơn nhé, chúng tôi có thể tự mình xoay sở được từ đây.",
  "Let's check in here.": "Hãy cùng nhau kiểm tra ở trong này xem sao.",
  "Well... this is my stop. I appreciate you looking after me.": "Chà... đây là điểm dừng chân của tôi cmnr. Tôi thực sự rất cảm kích vì cậu đã luôn chăm sóc và bảo vệ cho tôi.",
  "Shore up your position, soldier! Long as you don't fuck it up any worse, we can keep you supplied by air.": "Hãy mau củng cố lại vị trí đóng quân của mình đi, người lính (soldier)! Chừng nào cậu đéo làm cho mọi chuyện trở nên tồi tệ hơn, chúng tôi sẽ tiếp tục cung cấp nhu yếu phẩm cho cậu bằng đường hàng không.",
  "I intercepted and destroyed an incoming horde before it could do much damage. - %1$s.": "Tôi đã đánh chặn và tiêu diệt thành công một bầy horde đang lao tới trước khi bọn chúng có thể kịp gây ra quá nhiều thiệt hại cho nơi này. - %1$s.",
  "So, what, we're trapped?": "Vậy thì, cái đéo gì, chúng ta đã bị mắc kẹt lại cmnr ư?",
  "Herzog": "Herzog",
  "Tell Quentin everything you heard.": "Hãy kể lại cho Quentin tất cả những gì mà cậu đã được nghe.",
  "We've received a generous package of Army-issue ammunition and explosive ordnance.": "Chúng ta vừa mới nhận được một gói hàng vô cùng hào phóng bao gồm đạn dược (ammunition) do Quân đội cấp và một số loại vật liệu nổ (explosive ordnance).",
  "Some new survivors have thrown their lot in with us. -%1$s": "Một số những người sống sót (survivors) mới đã quyết định gia nhập và liên minh với chúng ta. -%1$s",
  "Sounds good.": "Nghe có vẻ rất tốt đấy.",
  "They fucked with the wrong person.": "Bọn chúng đã dám đụng chạm với nhầm người rồi đấy.",
  "START MISSION. Destroy a few zeds and chat a bit.": "BẮT ĐẦU NHIỆM VỤ (START MISSION). Tiêu diệt một vài con zeds và trò chuyện một chút.",
  "[message looping tone] One one lima november nine nine bravo six one papa.": "[âm báo tin nhắn lặp lại liên tục] One one lima november nine nine bravo six one papa.",
  "Gugler": "Gugler",
  "I think I'll check this out next.": "Tôi nghĩ là tiếp theo tôi sẽ đi kiểm tra thử chỗ này xem sao."
};

const file = 'output/languages/chunks/btxt_chunk_196.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_196.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk196[r.sourceText]) {
    r.translatedText = chunk196[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 196 successfully!');
