const fs = require('fs');
const chunk165 = {
  "Watch your right!": "Cẩn thận bên phải!",
  "We have to face facts. Pastor Will has that black fever. He isn't gonna make it. - %1$s": "Chúng ta phải đối mặt với sự thật thôi. Mục sư Will đã bị sốt đen rồi. Ông ấy sẽ đéo qua khỏi đâu. - %1$s",
  "Coming up on an infestation.": "Đang tiến đến gần một ổ dịch (infestation).",
  "Unarmed attacks replaced by a spinning kick that knocks the target down.": "Các đòn tấn công tay không được thay thế bằng một cú đá xoay vòng giúp đánh ngã mục tiêu.",
  "That's too much noise, take your time.": "Thế là quá nhiều tiếng ồn rồi, cứ từ từ thôi.",
  "I need you to drive me.": "Tôi cần cậu lái xe chở tôi đi.",
  "SET UP: Mess": "THIẾT LẬP: Nhà Ăn (Mess)",
  "41 CIV Vienna Cho": "41 DÂN SỰ (CIV) Vienna Cho",
  "FixUp_AltChurch": "SửaChữa_NhàThờThayThế (FixUp_AltChurch)",
  "Builds houses for the poor.": "Xây nhà cho người nghèo.",
  "Nice takedown.": "Hạ gục đẹp đấy.",
  "So that's it, huh? \"Nice to meet you, would you prefer to be shot in the face or kicked out on your asses?\"": "Vậy là xong rồi hả? \"Rất vui được gặp các người, các người muốn bị bắn vào mặt hay muốn bị đá đít ra khỏi đây?\"",
  "Assault Rifle: 556S": "Súng Trường Tấn Công: 556S",
  "How'd you meet Eli, anyway?": "Mà này, làm thế nào cậu quen Eli vậy?",
  "Goddammit, Will, why'd you have to go do this on me?": "Chết tiệt, Will, tại sao cậu lại phải làm thế này với tôi cơ chứ?",
  "I know this sucks, but we gotta keep going anyway.": "Tôi biết chuyện này thật tồi tệ, nhưng dù sao đi nữa thì chúng ta cũng phải tiếp tục tiến lên.",
  "Leila": "Leila",
  "I'm not surprised. There's so many infestations around here it's a miracle you didn't die when you stepped out the front door.": "Tôi đéo ngạc nhiên đâu. Có quá nhiều ổ dịch quanh đây nên việc cậu đéo chết khi bước ra khỏi cửa trước đã là một phép màu rồi.",
  "Sounds like I've got company.": "Có vẻ như tôi có khách rồi.",
  "[message looping tone] One one lima november nine nine charlie six one tango.": "[âm báo tin nhắn lặp lại] Một một lima november chín chín charlie sáu một tango.",
  "Nothing": "Đéo có gì cả",
  "If you keep jumping into fights like that, you better learn how to dodge.": "Nếu cậu cứ thích lao vào những cuộc đánh lộn như thế, tốt hơn hết là cậu nên học cách né đòn đi.",
  "How about some help?!": "Sao đéo giúp một tay đi?!",
  "A requirement for any Day-Walker.": "Điều kiện bắt buộc đối với bất kỳ kẻ đi ngày (Day-Walker) nào.",
  "Stump": "Gốc Cây (Stump)",
  "Maybe you shoulda thought about that before you bought our merchandise! You know what we do to deadbeats?": "Có lẽ mày nên nghĩ về điều đó trước khi mua hàng của bọn tao! Mày biết bọn tao làm gì với những kẻ quỵt nợ đéo?",
  "%1$s encountered a Juggernaut while out on patrol. They've called in reinforcements to help them take it down.": "%1$s đã chạm trán với một con Juggernaut khi đang đi tuần tra. Họ đã gọi viện binh đến để giúp họ hạ gục nó.",
  "... just in case you're taking requests.": "... chỉ phòng trường hợp cậu đang nhận yêu cầu thôi.",
  "She's just a civilian. We can't expect her to understand.": "Cô ấy chỉ là một thường dân. Chúng ta đéo thể mong đợi cô ấy hiểu được.",
  "The Workshop and the Medical Lab unlock additional items.": "Xưởng Cơ Khí (Workshop) và Phòng Thí Nghiệm Y Tế (Medical Lab) sẽ mở khóa thêm các vật phẩm mới.",
  "Doc, what's the good word?": "Doc, có tin gì tốt đéo?",
  "Heads up, big boy coming.": "Coi chừng, thằng bự con đang đến kìa.",
  "Better look around some more.": "Tốt hơn là nên nhìn xung quanh thêm chút nữa.",
  "What do you think they'll get out of this sample?": "Cậu nghĩ họ sẽ thu được gì từ mẫu vật này?",
  "You mind helping me out?": "Cậu có phiền giúp tôi một tay đéo?",
  "%1$s made the find.": "%1$s đã phát hiện ra.",
  "Ridge Cabins": "Khu nhà lều Ridge Cabins",
  "It has an office in Danforth, run by a woman named Michele Martin.": "Nó có một văn phòng ở Danforth, do một người phụ nữ tên là Michele Martin điều hành.",
  "Built a facility.": "Đã xây dựng xong một cơ sở (facility).",
  "Hey folks, that's the second time the army has swept in and rescued one of our callers.": "Này mọi người, đó là lần thứ hai quân đội càn quét tới và giải cứu một trong những người gọi điện cho chúng ta.",
  "<Death scream>": "<Tiếng thét chết chóc>",
  "+10%": "+10%",
  "I'll see to him. You got what you came for, so just take Doc and get the hell out.": "Tôi sẽ lo cho anh ấy. Các người đã lấy được thứ mình cần rồi, vậy nên hãy dẫn Doc theo và biến mẹ đi.",
  "I've fought my last squabble over a stale heel of bread. If you get the food situation sorted out, call me. - %1$s": "Tôi đã đánh trận cãi vã cuối cùng vì một mẩu bánh mì thiu rồi. Nếu cậu giải quyết xong tình hình lương thực, hãy gọi cho tôi. - %1$s",
  "+120%": "+120%",
  "Assault Rifle: AK47": "Súng Trường Tấn Công: AK47",
  "That's a start.": "Thế là bắt đầu được rồi đấy.",
  "Look, you're not going to take those documents without me, right? I mean ... I can probably help you read them.": "Nghe này, cậu sẽ đéo lấy những tài liệu đó mà đéo có tôi đi cùng đâu, phải đéo? Ý tôi là... tôi có thể giúp cậu đọc chúng đấy.",
  "Bilingual": "Song Ngữ (Bilingual)",
  "Graham": "Graham",
  "I know things seem bad, but we're going to make it. And you're going to help. Let's go.": "Tôi biết mọi chuyện có vẻ tồi tệ, nhưng chúng ta sẽ vượt qua được thôi. Và cậu sẽ giúp một tay. Đi nào.",
  "Don't rack the slide when there's a shell in the chamber. It makes you look like a jackass.": "Đừng có lên đạn khi đã có sẵn đạn trong buồng nòng. Việc đó làm cậu trông giống như một thằng ngốc vậy.",
  "My broadcast. I'm not leaving on any helicopter, soldier.": "Buổi phát sóng của tôi. Tôi sẽ đéo rời đi trên bất kỳ chiếc trực thăng nào đâu, người lính à.",
  "If you've got one, attach a suppressor to muffle the sound.": "Nếu bạn có, hãy gắn thêm nòng giảm thanh để giảm bớt tiếng ồn.",
  "We're comparing them to our comms transcripts, to see if there's some pattern to what we're being sent. Highroad out.": "Chúng tôi đang so sánh chúng với các bản ghi âm liên lạc của mình, để xem liệu có khuôn mẫu nào trong những gì chúng tôi nhận được đéo. Highroad xin ngừng liên lạc.",
  "Destroy a Juggernaut with Melee": "Tiêu diệt một con Juggernaut bằng Cận Chiến (Melee)",
  "NEW TRAIT: Depression": "ĐẶC ĐIỂM MỚI (NEW TRAIT): Trầm Cảm (Depression)",
  "Speed Bag": "Túi Tốc Độ (Speed Bag)",
  "Let me think a bit more on this.": "Để tôi suy nghĩ thêm chút nữa về việc này.",
  "I was wondering what you could tell me about that girl at the grange. Becca?": "Tôi đang tự hỏi cậu có thể cho tôi biết gì về cô gái ở trang trại (grange). Becca?",
  "Gotta keep going!": "Phải tiếp tục tiến lên thôi!",
  "Aging classic from the last days of WWI.": "Món đồ cổ kỹ thuật lâu năm từ những ngày cuối cùng của Thế Chiến thứ nhất (WWI).",
  "Or--and this is totally speculation, here--it could be the known felons who live just outside of town.": "Hoặc--và đây hoàn toàn là suy đoán thôi nhé--có thể đó là những tên trọng phạm khét tiếng sống ở ngay bên ngoài thị trấn.",
  "Izabella": "Izabella",
  "I've run eighty yard touchdowns without even breaking a sweat. (Sports trivia whiz.)": "Tôi đã chạy những cú chạm đất tám mươi dặm mà thậm chí đéo hề đổ một giọt mồ hôi. (Thần đồng kiến thức thể thao.)",
  "Knows how to cover his tracks.": "Biết cách xóa dấu vết.",
  "\"And I heard a great voice out of the throne saying, \"Behold, the tabernacle of God is with men, and he shall dwell with them, and they shall be his peoples, and God himself shall be with them, and be their God\"": "\"Và tôi nghe thấy một giọng nói lớn vang lên từ ngai vàng, \"Kìa, đền tạm của Thượng Đế ở giữa loài người, Ngài sẽ ở cùng họ, họ sẽ là dân của Ngài, và chính Thượng Đế sẽ ở cùng họ, và là Thượng Đế của họ\"",
  "Medical Advisor: %s": "Cố Vấn Y Tế: %s",
  "Orders are orders, ma'am. We're not the only people left. Find a group of refugees and make some friends.": "Lệnh là lệnh, thưa cô. Chúng ta đéo phải là những người duy nhất còn sống sót. Hãy tìm một nhóm người tị nạn và kết bạn đi.",
  "Wits": "Trí Tuệ (Wits)",
  "Come with me. I've got an idea.": "Đi theo tôi. Tôi có một ý tưởng.",
  "%1$s encountered a Bloater while out on patrol. They've called in reinforcements to help them take it down safely.": "%1$s đã chạm trán với một con Bloater khi đang đi tuần tra. Họ đã gọi viện binh đến để giúp họ hạ gục nó một cách an toàn.",
  "COMPLETED: Scene of the Crime": "ĐÃ HOÀN THÀNH: Hiện Trường Vụ Án (Scene of the Crime)",
  "Wacker": "Wacker",
  "+5": "+5",
  "Regain Vitality by numbing the pain.": "Phục hồi Sinh Lực (Vitality) bằng cách làm dịu cơn đau.",
  "Why aren't we better organized?": "Tại sao chúng ta lại đéo có tổ chức tốt hơn chứ?",
  "Jonah": "Jonah",
  "Shotgun: A-Series Mod. 1": "Súng Shotgun: A-Series Mod. 1",
  "The warehouse I'm headed to right now?": "Cái nhà kho mà tôi đang hướng tới ngay bây giờ ấy hả?",
  "Vince had to give up on the artillery site without outside support. He had the right idea, though. If we can track down assets like artillery and drones in the field, we can set up outposts there, and access those resources on our own.": "Vince đã phải từ bỏ địa điểm pháo binh vì đéo có sự hỗ trợ từ bên ngoài. Dù sao thì cậu ta cũng có ý tưởng đúng. Nếu chúng ta có thể theo dõi các tài sản như pháo binh và drone trên thực địa, chúng ta có thể thiết lập tiền đồn (outpost) ở đó và tự mình truy cập vào những nguồn tài nguyên này.",
  "21 GENERIC Ben Greene": "21 CHUNG (GENERIC) Ben Greene",
  "We've gotten reports of a zombie wearing body armor, if you can believe it. Won't be easy to take it down.": "Chúng tôi đã nhận được báo cáo về một con zombie mặc áo giáp, nếu cậu có thể tin được chuyện đó. Sẽ đéo dễ dàng để hạ gục nó đâu.",
  "You don't miss much, do you?": "Cậu đéo bỏ sót thứ gì nhiều, phải đéo?",
  "Almost screwed the pooch on that one.": "Suýt nữa thì làm hỏng bét chuyện đó rồi.",
  "Relax, I ain't gonna hit you ‘less I want to.": "Bình tĩnh đi, tao sẽ đéo đánh mày trừ khi tao muốn thế.",
  "A workshop focused on making explosives and incendiaries.": "Một xưởng (workshop) tập trung vào việc chế tạo thuốc nổ và chất gây cháy.",
  "I don't even know what to say. \"Thank you\" doesn't really cover it, does it?": "Tôi thậm chí đéo biết phải nói gì nữa. \"Cảm ơn\" thì thực sự đéo đủ, đúng đéo?",
  "Anyone interested in creating a little distraction?": "Có ai hứng thú với việc tạo ra một chút sự đánh lạc hướng đéo?",
  "Somebody better get some food, 'cause I AIN'T eatin' no tree bark.": "Ai đó tốt hơn là nên đi lấy ít thức ăn đi, vì tao ĐÉO CÓ định ăn vỏ cây đâu.",
  "Refills some brass to generate several magazines' worth of .44-caliber ammunition.": "Nạp lại một ít vỏ đạn (brass) để tạo ra vài băng đạn cỡ .44.",
  "I think we're clear!": "Tôi nghĩ chúng ta an toàn rồi!",
  "You sure about that?": "Cậu chắc về điều đó chứ?",
  "Follow me, let's take a walk.": "Đi theo tôi, chúng ta đi dạo một lát.",
  "MISSION: Home Sweet Home": "NHIỆM VỤ (MISSION): Ngôi Nhà Thân Yêu (Home Sweet Home)",
  "Called in a favor from his artillery buddies.": "Đã gọi một đặc ân từ những người bạn pháo binh của anh ta.",
  "Breakfast Foods": "Thức Ăn Sáng (Breakfast Foods)",
  "Next stop, Spencer's Mill. - %1$s": "Điểm dừng tiếp theo, Spencer's Mill. - %1$s",
  "Create a Garden": "Tạo một Khu Vườn (Garden)",
  "Family Back Home": "Gia Đình Ở Quê Nhà"
};

const file = 'output/languages/chunks/btxt_chunk_165.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_165.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk165[r.sourceText]) {
    r.translatedText = chunk165[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 165 successfully!');
