const fs = require('fs');
const chunk134 = {
  "Saving": "Đang Lưu",
  "Target down!": "Mục tiêu đã gục!",
  "Goldman": "Goldman",
  "Where's it going?": "Nó đi đâu vậy?",
  "Here. Just like we agreed on.": "Đây. Đúng như chúng ta đã thỏa thuận.",
  "I started wondering if I was the only one out here!": "Tôi đã bắt đầu tự hỏi liệu có phải mình là người duy nhất ở ngoài này đéo!",
  "%3$s has been on edge lately. Better do something about that before it gets out of hand -%2$s": "%3$s dạo này có vẻ căng thẳng. Tốt hơn là nên làm gì đó với chuyện này trước khi nó vượt tầm kiểm soát -%2$s",
  "This one's locked.": "Cái này bị khóa rồi.",
  "Like hell I'm going outside with this leg. Even one of those fatass zombies could catch me right now.": "Còn lâu tao mới ra ngoài với cái chân này. Giờ đến cả một trong mấy con zombie mập địt đó cũng có thể bắt được tao.",
  "Two. Afghanistan.": "Hai lần. Afghanistan.",
  "Ready to go?": "Sẵn sàng đi chưa?",
  "I could use an update, Lily.": "Tôi cần một bản cập nhật tình hình đấy, Lily.",
  "%1$s is losing faith.": "%1$s đang mất dần niềm tin.",
  "Doc Hanson's with the Wilkersons. From everything I've heard, these people are dangerous. - %1$s": "Bác sĩ Hanson đang ở cùng nhà Wilkerson. Từ những gì tôi nghe được, những người này rất nguy hiểm. - %1$s",
  "Some people have moral objections to our choices.": "Một số người có những phản đối về mặt đạo đức đối với các lựa chọn của chúng ta.",
  "Oh man, he blew up. We had a huge fight, didn't talk for years after that.": "Trời ạ, ông ấy đã nổi trận lôi đình. Chúng tôi đã cãi nhau một trận to, đéo thèm nói chuyện trong suốt nhiều năm sau đó.",
  "Got killed by zombies.": "Bị zombie giết.",
  "So I'm supposed to ask you to come along on this trade run.": "Vậy nên tôi có nhiệm vụ rủ cậu đi cùng trong chuyến đi giao dịch này.",
  "We're not talking razor wire and Jersey barriers here. These are serious walls, the kind they use to stop car bombers from driving onto Army bases.": "Chúng ta đéo đang nói về dây thép gai và rào chắn bê tông (Jersey barriers) đâu. Đây là những bức tường thực sự kiên cố, loại mà họ dùng để ngăn chặn xe đánh bom lao vào các căn cứ quân sự đấy.",
  "Ray": "Ray",
  "Ease down, line up good shots.": "Bình tĩnh, ngắm bắn cho chuẩn vào.",
  "I thought I saw somebody come in here. Guess they ran out the back.": "Tôi tưởng mình vừa thấy ai đó vào đây. Đoán là họ đã chạy ra bằng cửa sau rồi.",
  "Vic": "Vic",
  "Are you trying to get people killed? Do you want the world to end?": "Cậu đang cố làm người ta bỏ mạng sao? Cậu muốn thế giới này tận thế à?",
  "Sounds like things are mostly quiet out there.": "Nghe có vẻ như mọi thứ ngoài đó hầu như đều yên tĩnh.",
  "Not too bad!": "Đéo quá tệ!",
  "If they can't see you, they can't eat you.": "Nếu chúng đéo thể nhìn thấy cậu, chúng đéo thể ăn thịt cậu.",
  "Assault Rifle: CLEO HCQB": "Súng trường tấn công: CLEO HCQB",
  "You'll find GURUBANI KAUR on the Hero Menu in Breakdown. Or use the Radio Menu to add her after you've established a base.": "Bạn sẽ tìm thấy GURUBANI KAUR trên Menu Anh hùng (Hero Menu) trong chế độ Breakdown. Hoặc sử dụng Menu Radio để gọi cô ấy đến sau khi bạn đã thiết lập xong căn cứ.",
  "That'll do it for now.": "Bấy nhiêu đó là đủ cho lúc này.",
  "You see the zeds up there?": "Cậu có thấy lũ zed trên đó đéo?",
  "TIP: Use an EXPLOSIVE or INCENDIARY to go out in a Blaze of Glory.": "MẸO: Sử dụng THUỐC NỔ (EXPLOSIVE) hoặc VŨ KHÍ CHÁY (INCENDIARY) để ra đi trong một vụ nổ hào nhoáng (Blaze of Glory).",
  "Any idea how we can get this built faster?": "Có ý kiến gì để chúng ta xây cái này nhanh hơn không?",
  "Fuck this walking shit, where's my ride?": "Địt mẹ cái việc đi bộ chó đẻ này, xe của tao đâu rồi?",
  "Construction": "Xây dựng",
  "Debug3": "Debug3",
  "This is an open message to any survivors in Trumbull Valley.": "Đây là một tin nhắn mở gửi đến bất kỳ người sống sót nào ở Thung lũng Trumbull.",
  "Looks like trouble.": "Có vẻ như có rắc rối rồi.",
  "Help %1$s get some supplies back to base.": "Giúp %1$s mang một số nhu yếu phẩm về căn cứ.",
  "Community": "Cộng đồng",
  "What is it?": "Chuyện gì vậy?",
  "Requires 23 CATS.": "Yêu cầu 23 CON MÈO.",
  "Are you trying to draw attention?": "Mày đang cố thu hút sự chú ý hả?",
  "Tell me you weren't with Eli Wilkerson again.": "Nói với tôi là cậu đéo đi cùng Eli Wilkerson nữa đi.",
  "Don't be a stranger.": "Đừng có xa lạ thế chứ.",
  "I already told you, we don't have any ammo! Christ, we're down to killing zombies with two-by-fours!": "Tôi đã bảo cậu rồi, chúng ta đéo còn đạn nữa! Lạy Chúa, chúng ta đã đến bước đường cùng phải giết zombie bằng mấy thanh gỗ 2x4 rồi đấy!",
  "We need to upgrade our Radio Post if we want to reach Highroad.": "Chúng ta cần nâng cấp Trạm Radio nếu muốn liên lạc được với Highroad.",
  "Sanchez": "Sanchez",
  "Seems like a fair trade.": "Có vẻ là một cuộc trao đổi công bằng.",
  "Okay, guess I made it.": "Được rồi, đoán là tôi đã sống sót.",
  "Paxton": "Paxton",
  "A zed's not really down until you finish it off.": "Một con zed thực sự chưa bị hạ gục cho đến khi bạn kết liễu nó.",
  "What? Oh, Jesus, just... word of advice? Job Wilkerson offers you anything on credit, you run for the hills like your ass is on fire.": "Cái gì? Ôi, Chúa ơi, chỉ là... một lời khuyên thôi đéo? Nếu Job Wilkerson đề nghị cho cậu nợ bất cứ thứ gì, hãy cắm đầu mà chạy như thể đít cậu đang bốc cháy ấy.",
  "Follow me and try to learn something.": "Đi theo tao và cố gắng học hỏi chút gì đó đi.",
  "Chef's Knife": "Dao Bếp",
  "One of those big bastards has been tromping around. We've avoided it so far, but we need to take it out.": "Một trong những thằng khổng lồ chao chát đó đang lảng vảng quanh đây. Cho đến giờ chúng ta vẫn tránh được nó, nhưng chúng ta cần phải hạ gục nó.",
  "Fashion": "Thời trang",
  "WITHDRAWAL: Caffeine": "HỘI CHỨNG CAI NGHIỆN: Caffeine",
  "I guess....": "Tôi đoán vậy....",
  "Some folks are kind of worried about you. You okay?": "Một vài người có vẻ hơi lo lắng cho cậu. Cậu ổn chứ?",
  "124 HERO Doc Hanson": "124 HERO Doc Hanson",
  "Lost Loved One": "Mất Người Thân",
  "That's your problem": "Đó là vấn đề của cậu",
  "I don't like either choice. Give me some time.": "Tôi đéo thích lựa chọn nào cả. Cho tôi thêm thời gian.",
  "I'm about wrapped up here.": "Tôi sắp xong việc ở đây rồi.",
  "MISSION COMPLETE: Help Doc Hanson": "HOÀN THÀNH NHIỆM VỤ: Giúp Đỡ Bác sĩ Hanson",
  "I guess the zeds weren't listening.": "Tôi đoán lũ zed đéo có nghe thấy.",
  "Whitt": "Whitt",
  "55 GENERIC Aidan Murray": "55 GENERIC Aidan Murray",
  "We can't let our guard down with illness. We can't afford folks getting sick around here.": "Chúng ta đéo thể mất cảnh giác với bệnh tật được. Chúng ta đéo thể gánh nổi hậu quả nếu mọi người đổ bệnh ở quanh đây đâu.",
  "Maybe I'll go out to the infirmary. And just lie there by myself, since nobody's working it.": "Có lẽ tôi sẽ ra bệnh xá. Và cứ nằm một mình ở đó, vì làm chó có ai làm việc ở đó đâu.",
  "Feels responsible for maintaining some semblance of order in Trumbull County.": "Cảm thấy có trách nhiệm duy trì một chút trật tự ở Hạt Trumbull.",
  "How are those friends of ours holding up?": "Những người bạn của chúng ta chống chịu sao rồi?",
  "Now she lives with us.": "Bây giờ cô ấy sống với chúng ta.",
  "Distracted zombies to complete an objective.": "Đã đánh lạc hướng zombie để hoàn thành mục tiêu.",
  "Americans? I think we canceled their passports when they joined the living dead.": "Người Mỹ à? Tôi nghĩ chúng ta đã hủy hộ chiếu của họ kể từ khi họ gia nhập đội ngũ xác sống rồi.",
  "So ... the zombies really liked that beacon, huh?": "Vậy... lũ zombie thực sự thích cái đèn hiệu đó nhỉ?",
  "Posit one one lima november nine nine charlie six one tango. [message end tone]": "Tọa độ một một lima november chín chín charlie sáu một tango. [âm thanh kết thúc tin nhắn]",
  "You don't have to do this, Alan. We can figure something out, buddy.": "Cậu đéo cần phải làm thế này đâu, Alan. Chúng ta có thể tìm ra cách khác mà, anh bạn.",
  "Good thing we had an infirmary.": "Thật tốt là chúng ta đã có một bệnh xá.",
  "Honestly, I don't know which prospect scares me more.": "Thành thật mà nói, tôi đéo biết viễn cảnh nào làm tôi sợ hơn nữa.",
  "Hold [sprint] + [cover] while standing still to kill two enemies at once.": "Giữ phím [Chạy nước rút] (sprint) + [Nấp] (cover) trong khi đứng yên để kết liễu hai kẻ thù cùng một lúc.",
  "Okay, so, guess you didn't think that was worthwhile. Fair enough. - %1$s": "Được rồi, đoán là cậu đéo cho rằng điều đó đáng giá. Cũng công bằng thôi. - %1$s",
  "Hold on. I don't think we're clear.": "Đợi đã. Tôi đéo nghĩ là chúng ta đã an toàn đâu.",
  "Stay calm, I'm on my way.": "Bình tĩnh đi, tôi đang tới đây.",
  "Grenade, Landmine, Firebomb, Suppressor": "Lựu Đạn, Mìn, Bom Lửa, Ống Giảm Thanh",
  "PERSONAL SKILL. Plants aren't so different from us. Each one has its own needs, and if you don't tend to those needs they'll end up choking each other to death.": "KỸ NĂNG CÁ NHÂN. Cây cối đéo khác biệt với chúng ta là mấy. Mỗi loại đều có những nhu cầu riêng, và nếu cậu đéo chăm sóc những nhu cầu đó, chúng sẽ tự bóp nghẹt lẫn nhau cho đến chết.",
  "Gunsmith's Manual": "Sổ Tay Thợ Súng",
  "Their numbers make them dangerous.": "Số lượng đông đảo mới khiến chúng trở nên nguy hiểm.",
  "Acquired TRUCK KEYS and RADIO.": "Đã lấy được CHÌA KHÓA XE TẢI và BỘ ĐÀM (RADIO).",
  "Mistakenly thought the World Stroganoff Cookoff was in town.": "Đã nhầm tưởng Cuộc Thi Nấu Stroganoff Thế giới được tổ chức trong thị trấn.",
  "Yeah, you know what, I'll just take that.": "Phải, mày biết gì đéo, tao sẽ lấy cái đó.",
  "Values people over orders.": "Coi trọng con người hơn cả mệnh lệnh.",
  "Yeah, well... better stock up on meds. Pastor Will's not looking so great.": "Ừ thì, chà... tốt hơn là nên tích trữ thêm thuốc men đi. Mục sư Will trông đéo khá khẩm lắm đâu.",
  "Sgt. Erik Tan": "Trung sĩ Erik Tan",
  "Preacher": "Mục sư",
  "Seay": "Seay",
  "That's all I can carry. Ready to go?": "Đó là tất cả những gì tôi có thể mang theo. Sẵn sàng đi chưa?",
  "Hi, Becca.": "Chào, Becca.",
  "It takes some real hand-to-hand combat skill to take these on. - %1$s": "Phải cần một chút kỹ năng cận chiến thực sự để đối phó với bọn này. - %1$s"
};

const file = 'output/languages/chunks/btxt_chunk_134.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_134.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk134[r.sourceText]) {
    r.translatedText = chunk134[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 134 successfully!');
