const fs = require('fs');
const chunk200 = {
  "Execute": "Tiến Hành Xử Tử (Execute)",
  "Madison Grant? We've got a helicopter inbound to pick you up.": "Madison Grant ư? Chúng tôi hiện đang có một chiếc máy bay trực thăng đang trên đường tiến vào (inbound) để có thể giải cứu cậu đấy.",
  "Upgrade complete, ma'am!": "Quá trình nâng cấp (Upgrade) đã hoàn tất, thưa cô!",
  "Looks like we're getting more loot from Cleo. Hopefully she got Lily that pony she's been wanting.": "Trông có vẻ như chúng ta đang nhận được thêm rất nhiều chiến lợi phẩm (loot) từ Cleo. Hy vọng rằng cô ấy đã thực sự tìm thấy được cho Lily con ngựa con (pony) mà con bé vẫn luôn hằng mong ước.",
  "Martin": "Martin",
  "Maybe there's another treatment we can try.": "Có lẽ vẫn còn có một phương pháp điều trị (treatment) nào đó khác mà chúng ta có thể thử áp dụng.",
  "125 STORY Pfc. Winters": "125 CỐT TRUYỆN (STORY) Binh Nhất (Pfc.) Winters",
  "I thought you said you had survivors holed up here!": "Tôi đã tưởng rằng cậu nói là cậu đang có những người sống sót (survivors) đang trú ẩn (holed up) ở trong cái nơi này chứ!",
  "You got that one!": "Cậu vừa mới tóm được con khốn đó rồi!",
  "Overqualified": "Trình Độ Vượt Quá Yêu Cầu (Overqualified)",
  "Automatically repair body and tire damage for vehicles parked overnight.": "Sẽ tự động tiến hành sửa chữa (repair) lại toàn bộ những hư hỏng (damage) ở phần thân vỏ cũng như là phần lốp xe dành cho các loại phương tiện (vehicles) được đậu lại qua đêm.",
  "Highroad - Vehicle Delivery": "Highroad - Bàn Giao Phương Tiện (Vehicle Delivery)",
  "Escape Trumbull County.": "Nhanh Chóng Trốn Thoát (Escape) Khỏi Hạt Trumbull.",
  "Get in there and bring them back. Highroad out.": "Hãy nhanh chóng đi vào trong đó và đưa bọn họ trở về đây một cách an toàn. Highroad xin phép được ngừng liên lạc (out).",
  "How are we different? We can live through most of that, at least for a while, but shoot us in the brain and we're just as gone as a zed.": "Vậy rốt cuộc thì chúng ta khác biệt ở chỗ đéo nào cơ chứ? Chúng ta có thể sống sót vượt qua được hầu hết những thứ đó, hoặc ít nhất là trong một khoảng thời gian ngắn, thế nhưng nếu như bắn một viên đạn thẳng vào não của chúng ta thì chúng ta cũng sẽ chết ngay lập tức y hệt như một con zed vậy.",
  "Everybody just calm down and think about this, okay? - %3$s": "Tất cả mọi người hãy mau bình tĩnh lại và suy nghĩ thật kỹ về chuyện này đi, có được đéo? - %3$s",
  "Dude, assist, assist!": "Này anh bạn, hãy đến đây hỗ trợ cho tôi đi (assist)!",
  "Ranger station. Maybe we can find some help there.": "Trạm kiểm lâm (Ranger station). Biết đâu chúng ta có thể tìm kiếm được một vài sự trợ giúp ở đó.",
  "Each personality is unique.": "Mỗi một đặc điểm tính cách (personality) đều là sự khác biệt hoàn toàn độc nhất vô nhị (unique).",
  "Hello? Anybody here still alive?": "Xin chào? Có còn ai ở đây vẫn còn sống đéo vậy?",
  "You know I went past my old place the other day?": "Cậu có biết là vào ngày hôm nọ tôi đã đi ngang qua cái nơi ở cũ của mình đéo?",
  "Sure. Let's go.": "Chắc chắn rồi. Chúng ta hãy đi thôi.",
  "%s is not set.": "%s vẫn chưa được thiết lập.",
  "Our ammo supply is basically tapped. Not good.": "Nguồn dự trữ đạn dược (ammo) của chúng ta về cơ bản là đã hoàn toàn cạn kiệt (tapped) cmnr. Thật đéo ổn một chút đéo nào.",
  "Ain't got the space for it.": "Tôi đéo còn đủ khoảng trống nào dành cho cái thứ này nữa đâu.",
  "Demands nothing but the best from herself and those around her. Her subordinates privately call her the Monster for her mercilessly high standards.": "Luôn yêu cầu đéo có gì khác ngoài việc mọi thứ đều phải là tốt nhất (best) từ chính bản thân mình và cả những người xung quanh. Những người thuộc cấp (subordinates) của cô ấy thường hay bí mật gọi cô ấy với cái biệt danh là Con Quái Vật (Monster) bởi vì những tiêu chuẩn cao (high standards) một cách vô cùng tàn nhẫn (mercilessly) của cô ấy.",
  "DECLINED: Bad Tidings": "ĐÃ TỪ CHỐI (DECLINED): Những Tin Tức Tồi Tệ (Bad Tidings)",
  "Still feeling pretty energized, I better save this.": "Tôi hiện tại vẫn đang cảm thấy khá là tràn đầy năng lượng (energized), tốt hơn hết là tôi nên tiết kiệm cái thứ này lại thì hơn.",
  "What? No!": "Cái đéo gì cơ? Đéo thể nào!",
  "After the real estate bubble burst, construction pretty much stopped on a lot of buildings around here. Probably plenty of building material to scavenge at places like that.": "Sau khi bong bóng bất động sản (real estate bubble) chính thức bị nổ tung, các công trình xây dựng (construction) ở phần lớn các tòa nhà quanh đây gần như là đã hoàn toàn bị đình trệ. Có lẽ sẽ có rất nhiều các loại vật liệu xây dựng (building material) để có thể đi nhặt nhạnh (scavenge) ở những cái nơi giống như thế này đấy.",
  "Sweet, sweet fortune!": "Thật là một sự may mắn (fortune) vô cùng ngọt ngào!",
  "You might need this.": "Cậu có thể sẽ rất cần đến cái thứ này đấy.",
  "A lighter variant of the venerable heavy hitter.": "Một biến thể (variant) sở hữu trọng lượng nhẹ hơn (lighter) rất nhiều của khẩu súng cực kỳ uy lực (heavy hitter) và cũng vô cùng đáng kính (venerable).",
  "%s Found!": "Đã Tìm Thấy (Found) Được %s!",
  "Of course not.": "Đương nhiên là đéo rồi.",
  "No way does that gun get any quieter.": "Đéo có chuyện khẩu súng chết tiệt đó có thể trở nên im lặng hơn được một chút đéo nào đâu.",
  "We all saw it coming. %1$s has been more and more nervous lately. Some people just can't take the pressure, and I can't say that there aren't reasons to be scared. Anyway, %1$s is gone now. Ran away. Somehow I doubt we'll be seeing them again. - %2$s": "Tất cả chúng ta đều đã dự đoán trước được việc này rồi. %1$s dạo gần đây ngày càng trở nên lo lắng hoảng loạn vô cùng dữ dội. Một số người đơn giản là đéo thể nào chịu đựng nổi cái thứ áp lực (pressure) đó, và tôi cũng đéo thể nói rằng là đéo hề có một lý do đéo nào để mà phải cảm thấy sợ hãi được. Dù sao thì, %1$s cũng đã rời đi cmnr. Đã chạy trốn rồi. Bằng một cách nào đó tôi thực sự nghi ngờ cái việc liệu chúng ta có thể được nhìn thấy bọn họ thêm một lần đéo nào nữa hay đéo. - %2$s",
  "IOU some medicine. Don't worry, I'll be fine. - %1$s": "Tôi Vẫn Còn Nợ Cậu (IOU) một ít thuốc men (medicine) đấy nhé. Nhưng cũng đừng quá lo lắng, tôi rồi sẽ đéo sao đâu. - %1$s",
  "Dodge/Crouch": "Né Tránh (Dodge)/Cúi Người (Crouch)",
  "Come on, son. No use causing a scene.": "Thôi nào, chàng trai. Việc cố tình tạo ra một vụ ẩu đả (scene) cũng sẽ đéo có bất kỳ một tác dụng đéo gì đâu.",
  "We don't have anybody here qualified to treat this.": "Chúng ta đéo có bất kỳ một người đéo nào ở đây có đủ trình độ chuyên môn (qualified) để có thể điều trị (treat) được cái thứ dịch bệnh thảm khốc này đâu.",
  "Why don't you go take down a horde? I'd do it, but I ain't got nothin' to prove to you.": "Tại sao cậu lại đéo chịu tự mình đi tiêu diệt (take down) một bầy horde đi nhỉ? Tôi hoàn toàn có thể làm được điều đó, thế nhưng tôi lại đéo hề có bất cứ một lý do đéo gì cần phải chứng minh (prove) với cậu cả.",
  "NOTE: Like a Good Neighbor": "TỜ GHI CHÚ (NOTE): Giống Như Là Một Người Hàng Xóm Tốt Bụng (Good Neighbor)",
  "Damn good thing we stocked up on fuel.": "Thật may mắn chết đi được khi mà chúng ta đã kịp thời dự trữ thêm được rất nhiều nhiên liệu (fuel).",
  "THE COURTHOUSE": "TÒA ÁN (THE COURTHOUSE)",
  "Greyhound Two. I thought we'd lost you.": "Greyhound Two. Tôi đã tưởng là chúng tôi đã đánh mất (lost) các người cmnr chứ.",
  "We don't know squat.": "Chúng tôi đéo biết một cái đéo gì cả (squat).",
  "Bloated Zed": "Con Zed Mập Địch Bụng Bự (Bloated)",
  "Desperate Survivors": "Những Người Sống Sót Hiện Đang Vô Cùng Tuyệt Vọng (Desperate)",
  "I woulda made a break for it, but I couldn't just leave all my tools behind. (Handy with tools.)": "Đáng lẽ ra thì tôi đã có thể dễ dàng bỏ trốn cmnr, thế nhưng tôi lại đéo thể nào đành lòng bỏ lại toàn bộ các loại công cụ (tools) của mình ở phía sau được. (Rất Khéo Tay Handy khi sử dụng với các loại công cụ tools.)",
  "KILLED: Hadley Westen": "BỊ GIẾT CHẾT (KILLED): Hadley Westen",
  "Feral": "Feral",
  "HOME: Ed's Getting Sicker": "CĂN CỨ (HOME): Tình Trạng Của Ed Đang Ngày Càng Trở Nên Tồi Tệ Hơn Rất Nhiều (Sicker)",
  "Improvised. Does not hold an edge well.": "Một loại vũ khí tự chế (Improvised) thô sơ. Nó đéo thể nào giữ được độ sắc bén (edge) ở phần lưỡi cắt một cách tốt nhất.",
  "I dunno, just some people have been having trouble sleeping. You know, the stress and all.": "Tôi đéo biết nữa (dunno), chỉ là một số người dạo gần đây đã bắt đầu gặp phải những rắc rối cực kỳ nghiêm trọng với giấc ngủ (sleeping). Cậu biết đấy, sự căng thẳng (stress) áp lực tột độ và tất cả những thứ tương tự như vậy.",
  "Keep moving, zeds on our tail.": "Hãy tiếp tục di chuyển đi, lũ zeds đang bám đuôi ngay sát phía sau chúng ta rồi đấy.",
  "Don't think they'll listen to me.": "Tôi đéo nghĩ rằng bọn họ sẽ chịu lắng nghe tôi đâu.",
  "Listen to this. I think I've figured out a pretty easy way to get some refrigerated storage working.": "Hãy thử lắng nghe cái này xem. Tôi nghĩ rằng mình đã phát hiện ra (figured out) một cái cách khá là dễ dàng để có thể giúp cho hệ thống kho lạnh bảo quản (refrigerated storage) hoạt động trở lại.",
  "Checking in!": "Tiến hành thủ tục nhận phòng (Checking in) nào!",
  "%d Rucksacks Delivered": "%d Chiếc Balo Chứa Đồ (Rucksacks) Đã Được Bàn Giao (Delivered) Thành Công",
  "Plus, they don't exactly grow on trees, and we only got so much fuel to keep them running. So we gotta be careful about when we use 'em.": "Thêm vào đó, bọn chúng đéo hề tự động mọc ra ở trên những cái cây, và chúng ta cũng chỉ có được một lượng nhiên liệu (fuel) nhất định để có thể giúp duy trì hoạt động cho bọn chúng. Vì vậy nên chúng ta cần phải cực kỳ cẩn thận về cái thời điểm mà chúng ta quyết định sử dụng bọn chúng.",
  "Determines when someone gets sick due to poor sanitation.": "Đóng vai trò quyết định (Determines) xem khi nào thì một người nào đó sẽ bị ốm (sick) do các điều kiện cơ sở vệ sinh (sanitation) quá tồi tàn.",
  "Every life is worth saving, right?": "Mỗi một mạng sống (life) thì đều hoàn toàn xứng đáng để được giải cứu (saving), có đúng đéo?",
  "Keeping out of trouble?": "Đang cố gắng để tránh xa khỏi những rắc rối (trouble) sao?",
  "Wounded": "Đã Bị Thương (Wounded)",
  "I'm not hurt yet.": "Hiện tại tôi vẫn chưa bị thương (hurt) một chút đéo nào đâu.",
  "I'll say this about the folks here--you know they've got your back.": "Tôi sẽ phải thốt lên cái điều này về những con người ở đây--cậu biết rất rõ là bọn họ sẽ luôn sẵn sàng bảo vệ cậu ở phía sau (back) mà.",
  "Miles": "Miles",
  "Yeah, I like that plan.": "Yeah, tôi rất thích cái kế hoạch đó đấy.",
  "Gain +5 FOOD in exchange for pickling and curing food for another survivor group.": "Sẽ thu được (Gain) +5 THỨC ĂN (FOOD) để đổi lấy việc tiến hành muối chua (pickling) và sấy khô (curing) các loại thức ăn dành cho một nhóm những người sống sót khác.",
  "Surgical Facility": "Cơ Sở Phẫu Thuật (Surgical Facility)",
  "We're sitting tight. Ready when you are.": "Chúng tôi vẫn đang bám trụ (sitting tight) ở đây. Đã chuẩn bị sẵn sàng bất cứ khi nào cậu muốn.",
  "Zeds are everywhere": "Bọn Zeds hiện đang có mặt ở khắp mọi nơi",
  "88 GENERIC Anson Hearst": "88 CHUNG (GENERIC) Anson Hearst",
  "You can't reach your map right now.": "Hiện tại bạn đéo thể nào truy cập được vào tấm bản đồ (map) của mình.",
  "We're in luck, it's a small one.": "Chúng ta thực sự rất may mắn (luck), đó chỉ là một nhóm nhỏ mà thôi.",
  "You put that one down hard.": "Cậu vừa mới hạ gục con quái vật đó một cách vô cùng tàn nhẫn đấy.",
  "Has a background in health and fitness.": "Sở hữu một nền tảng kiến thức (background) cực kỳ vững chắc về các lĩnh vực chăm sóc sức khỏe (health) cũng như thể hình (fitness).",
  "Sure.": "Chắc chắn rồi.",
  "You ain't looking good.": "Trông cậu có vẻ đéo được ổn cho lắm đâu đấy.",
  "Come on! Just push through the undergrowth, it's not gonna kill you!": "Thôi nào! Hãy cứ mạnh dạn đẩy thẳng về phía trước đi qua những bụi rậm (undergrowth) đó đi, nó sẽ đéo thể nào giết chết được cậu đâu!",
  "Along with a pack full of samples.": "Cùng với một gói chứa đầy những mẫu thử nghiệm (samples).",
  "Giant wrench, made by the Big Ass Wrench Company, McMillanville. USA.": "Một chiếc cờ lê khổng lồ (Giant wrench), được sản xuất bởi Big Ass Wrench Company, McMillanville. Nước Mỹ.",
  "Ross": "Ross",
  "We're trapped! Lots of zombies outside, and we're out of ammo. Don't know how long we can hold out!": "Chúng tôi đã bị mắc kẹt lại cmnr! Có rất nhiều zombies đang xuất hiện ở bên ngoài kia, và chúng tôi thì đã cạn kiệt đạn dược (ammo) mất rồi. Chúng tôi đéo biết là mình sẽ còn có thể tiếp tục cầm cự (hold out) được thêm bao lâu nữa đâu!",
  "SWAT Zombies": "Những Con Zombies Đặc Nhiệm SWAT",
  "Played the Drums": "Từng Chơi Trống (Drums)",
  "71 GENERIC Edgar Carew": "71 CHUNG (GENERIC) Edgar Carew",
  "LOG: Crash Site Located": "BẢN GHI NHẬT KÝ (LOG): Đã Xác Định Được (Located) Vị Trí Hiện Tại Của Khu Vực Hiện Trường Vụ Tai Nạn (Crash Site)",
  "Zombie Kill Score": "Điểm Số Giết (Kill Score) Zombies",
  "You, my friend? You rock. There, I said it.": "Cậu, bạn của tôi ơi? Cậu thực sự rất tuyệt vời (rock). Đấy, tôi đã nói ra nó rồi đấy.",
  "Hammerstein": "Hammerstein",
  "27 MIL Pfc Tyler Goss": "27 QUÂN ĐỘI (MIL) Binh Nhất (Pfc) Tyler Goss",
  "12 MIL Sgt Naomi Monson": "12 QUÂN ĐỘI (MIL) Trung Sĩ (Sgt) Naomi Monson",
  "Stay calm, I'm on the way.": "Hãy cứ giữ bình tĩnh nhé, tôi hiện đang trên đường tới đó đây.",
  "COMPLETED: Trouble at the Courthouse": "ĐÃ HOÀN THÀNH XUẤT SẮC (COMPLETED): Những Rắc Rối (Trouble) Xảy Ra Tại Tòa Án (Courthouse)",
  "Ugh... can't seem to shake this fever.": "Ugh... dường như tôi đéo thể nào xua tan (shake) đi được cái cơn sốt (fever) thảm khốc này.",
  "MISSION: Combat Training": "NHIỆM VỤ (MISSION): Huấn Luyện Kỹ Năng Chiến Đấu (Combat Training)",
  "That area looks open.": "Cái khu vực đó trông có vẻ khá là thoáng đãng trống rỗng (open) đấy.",
  "EXTRACTED: Brock": "ĐÃ ĐƯỢC GIẢI CỨU THÀNH CÔNG (EXTRACTED): Brock"
};

const file = 'output/languages/chunks/btxt_chunk_200.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_200.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk200[r.sourceText]) {
    r.translatedText = chunk200[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 200 successfully!');
