const fs = require('fs');
const chunk201 = {
  "You ready to go?": "Cậu đã chuẩn bị sẵn sàng để lên đường chưa?",
  "You all think it's funny? Huh? The \"pranks,\" the stolen food, the blanket parties when nobody's looking? Fuck all of you. Especially you, %2$s. - %1$s": "Tất cả các người đều nghĩ rằng chuyện đó rất vui đùa (funny) ư? Hả? Những \"trò đùa ngu ngốc (pranks)\", những phần thức ăn bị đánh cắp, những bữa tiệc trùm chăn (blanket parties) diễn ra mỗi khi đéo có một ai để ý giám sát? Địt mẹ tất cả các người. Đặc biệt là cậu đấy, %2$s. - %1$s",
  "Come on, the more the merrier!": "Thôi nào, càng đông người thì lại càng vui chứ sao!",
  "I mean it, dammit. You don't do what I say, it'll get gangrenous and you'll lose the entire leg.": "Tôi đang nói hoàn toàn nghiêm túc đấy, chết tiệt thật. Nếu như cậu đéo chịu làm theo những gì mà tôi đã căn dặn, nó sẽ dần chuyển sang giai đoạn hoại tử (gangrenous) và cậu sẽ bị mất đi toàn bộ cái chân đó vĩnh viễn.",
  "Learned electrical work from her mom. Learned medical work from Uncle Sam.": "Cô ấy đã được học cách làm các công việc liên quan đến đồ điện (electrical) từ mẹ của mình. Và được học về những kiến thức y tế (medical) từ Chú Sam.",
  "So many zeds in the area, I don't think circling around's any better.": "Đang có quá nhiều bọn zeds tụ tập ở trong khu vực này, tôi đéo nghĩ rằng cái việc cố gắng đi đường vòng (circling) sẽ có thể giải quyết được bất kỳ một vấn đề đéo nào cả.",
  "Hey, I don't look at your ass when YOU bend over. (Handy with tools.)": "Này, tôi thề là tôi đéo hề nhìn trộm vào mông của cậu mỗi khi CẬU cúi người xuống đâu đấy nhé. (Rất Khéo Tay Handy khi sử dụng với các loại công cụ tools.)",
  "Prepare a Feast": "Nấu Một Bữa Tiệc Thịnh Soạn (Prepare a Feast)",
  "That doesn't look so good.": "Thứ đó trông có vẻ đéo được ổn cho lắm đâu.",
  "Just a little longer ... there are a lot of fucking wires in here!": "Chỉ một lúc nữa thôi... đang có cả một đống những sợi dây điện (wires) chết tiệt nằm rải rác ở ngay bên trong này!",
  "Add %1$s as a FRIEND. Friends share Fame and Influence. You can switch between friends when you aren't on a mission.": "Thêm %1$s vào trong danh sách BẠN BÈ (FRIEND) của bạn. Những người bạn bè sẽ chia sẻ (share) chung số lượng Danh Tiếng (Fame) và tầm Ảnh Hưởng (Influence) với nhau. Bạn hoàn toàn có thể tự do chuyển đổi (switch) quyền điều khiển giữa những người bạn với nhau mỗi khi bạn đéo phải làm một nhiệm vụ nào đó.",
  "Vicious and deadly.": "Vô cùng tàn bạo (Vicious) và cực kỳ nguy hiểm có thể dễ dàng gây ra những cái chết chóc (deadly) thương tâm.",
  "Met Eli": "Đã Gặp Gỡ (Met) Eli",
  "That a problem?": "Đó có phải là một vấn đề rắc rối (problem) đéo?",
  "We're going to need more building materials.": "Chúng ta sẽ cần phải thu thập được nhiều vật liệu xây dựng (building materials) hơn nữa.",
  "I don't know if it's anxiety or bad food, but what I just did in the latrine might have killed a lesser soldier. I am so glad we're paying attention to sanitation around here ... I hate to think how rancid this place would be if people were doing shit like that all over the base.": "Tôi đéo biết đó là do sự lo lắng (anxiety) tột độ hay là vì đám thức ăn ôi thiu (bad food) nữa, thế nhưng những gì mà tôi vừa mới tống ra ở trong nhà vệ sinh (latrine) có thể sẽ trực tiếp giết chết được một người lính cấp dưới. Tôi thực sự rất cảm thấy vui mừng khi mà chúng ta vẫn đang chú ý cực kỳ sát sao đến các vấn đề liên quan đến vệ sinh môi trường (sanitation) ở quanh đây... Tôi vô cùng ghét cái việc phải nghĩ xem cái nơi thối nát này sẽ có thể trở nên tồi tệ (rancid) đến cái mức đéo nào nếu như tất cả mọi người đều ỉa đái (shit) bừa bãi ở khắp mọi nơi xung quanh cái căn cứ này.",
  "\"Finding\" Supplies": "\"Tìm Kiếm (Finding)\" Các Loại Vật Tư Đồ Tiếp Tế (Supplies)",
  "HOME: Shouting Match": "CĂN CỨ (HOME): Cuộc Tranh Cãi Nảy Lửa (Shouting Match)",
  "Vehicle relocated.": "Chiếc xe đã được di dời (relocated) thành công.",
  "I won't be a part of this.": "Tôi sẽ đéo bao giờ tham gia vào cái chuyện ngu ngốc này đâu.",
  "Value": "Giá Trị (Value)",
  "Good news, I'm loaded up and heading home.": "Tin tốt đây, tôi đã thu gom đầy đủ đồ đạc rồi và hiện đang trên đường quay trở về nhà (home).",
  "KILLED: Timothy Hall": "BỊ GIẾT CHẾT (KILLED): Timothy Hall",
  "Excess resources won't last through the night.": "Các nguồn tài nguyên dư thừa (Excess resources) sẽ đéo thể nào tồn tại kéo dài qua được đến sáng ngày hôm sau đâu.",
  "Ready to take out an Infestation.": "Đã chuẩn bị sẵn sàng để có thể tiến hành dọn dẹp sạch sẽ một cái ổ dịch (Infestation).",
  "I was hoping I'd see something like that.": "Tôi vẫn luôn hy vọng rằng mình sẽ có cơ hội được nhìn thấy một thứ đéo gì đó tương tự như vậy.",
  "156 GENERIC Milo Eldridge": "156 CHUNG (GENERIC) Milo Eldridge",
  "The folks at the Grange needed more help than I could give them. - %1$s": "Những người khốn khổ ở khu vực Grange đã cần đến rất nhiều sự trợ giúp (help) hơn so với những gì mà cá nhân tôi có thể cung cấp được cho bọn họ. - %1$s",
  "We're clear in here.": "Chúng tôi đã dọn dẹp an toàn sạch sẽ (clear) mọi thứ ở trong này rồi.",
  "Klein": "Klein",
  "Good luck making it back. I don't even know if we'll be here by then.": "Chúc may mắn ở trong chuyến đi quay trở về. Tôi thậm chí còn đéo thể biết được liệu lúc đó chúng tôi có còn sống sót để tiếp tục trụ lại ở đây đéo.",
  "All the benefits of an Infirmary, plus the ability to create painkillers and stimulants.": "Toàn bộ những lợi ích của một Bệnh Xá (Infirmary), cộng thêm với khả năng để có thể chế tạo (create) ra các loại thuốc giảm đau (painkillers) cũng như là chất kích thích (stimulants).",
  "You'll see a dirt path on the left - follow that all the way to the Barrett place. You can't miss it.": "Cậu sẽ nhanh chóng nhìn thấy một con đường đất (dirt path) nằm ở phía bên trái - hãy tiếp tục đi men theo con đường đó cho đến khi cậu đến được khu vực nhà của Barrett. Cậu sẽ đéo thể nào bỏ lỡ được nó đâu.",
  "Medicine and medical facilities help.": "Các cơ sở vật chất chuyên lưu trữ Thuốc Men (Medicine) và dùng trong y tế (medical) sẽ là một công cụ hỗ trợ (help) đắc lực.",
  "Good to go.": "Đã sẵn sàng để có thể lên đường cmnr.",
  "Fires the .50 BMG. For anti-materiel missions.": "Sử dụng loại đạn .50 BMG. Được tạo ra nhằm mục đích phục vụ chuyên dụng cho những nhiệm vụ tiêu diệt các phương tiện cơ giới hạng nặng (anti-materiel missions).",
  "Doak": "Doak",
  "Color Blind": "Mắc Hội Chứng Bị Mù Màu (Color Blind)",
  "Advice: Build a Sleeping Area": "Lời Khuyên (Advice): Hãy Xây Dựng (Build) Lên Một Khu Vực Ngủ Nghỉ (Sleeping Area)",
  "Safe and sound now.": "Hiện tại thì mọi thứ đều đã cực kỳ an toàn (Safe) và vô cùng tốt đẹp (sound) cmnr.",
  "No signs of Doc Hanson today.": "Ngày hôm nay đéo hề có bất cứ một dấu hiệu (signs) nhận biết đéo nào của Bác Sĩ Hanson cả.",
  "I'm fine, I'm fine. Had worse the day after I learned to say \"red-light district\" in German.": "Tôi hoàn toàn ổn, tôi vẫn ổn. Mọi thứ thậm chí còn diễn ra tồi tệ hơn rất nhiều vào cái ngày đầu tiên sau khi tôi học được cái cách để có thể nói ra từ \"khu đèn đỏ red-light district\" bằng tiếng Đức.",
  "Soldier, you've managed to bring in more critical intel and assets than anyone could have expected.": "Người lính à, cậu đã xoay xở vô cùng xuất sắc mang về cho chúng ta được nhiều thông tin tình báo (intel) cũng như các tài sản (assets) mang tính chất cực kỳ quan trọng hơn bất kỳ một sự mong đợi nào của mọi người ở đây.",
  "Event: Suicide": "Sự Kiện Bất Ngờ (Event): Hành Động Tự Sát (Suicide)",
  "I guess you know your shit.": "Tôi đoán là cậu hiểu rất rõ về cái công việc chết tiệt (shit) của mình.",
  "Thanks, Doc.": "Cảm ơn nhé, Bác Sĩ.",
  "Hey, I just want to let you know, you're doing great. Thank you.": "Này, tôi chỉ muốn để cho cậu biết một điều rằng, cậu hiện đang làm việc rất tốt. Cảm ơn cậu.",
  "0 MIL Maj Alicia Hawkes": "0 QUÂN ĐỘI (MIL) Thiếu Tá (Maj) Alicia Hawkes",
  "HOME: Flu-like Symptoms": "CĂN CỨ (HOME): Có Dấu Hiệu Tương Tự Như Triệu Chứng Bị Cúm (Flu-like)",
  "Lifesaving Supplies": "Những Nguồn Vật Tư Cứu Mạng Chữa Bệnh Khẩn Cấp (Lifesaving Supplies)",
  "You really know what you're doing.": "Cậu thực sự biết rất rõ những gì mà mình đang làm.",
  "Stephanie": "Stephanie",
  "We're burning through meds at an alarming rate. I think everyone's a little paranoid about getting sick. - %1$s": "Chúng ta đang tiêu thụ lượng thuốc men (meds) một cách quá mức với một tốc độ vô cùng đáng báo động (alarming). Tôi nghĩ rằng tất cả mọi người đều đang cảm thấy có đôi chút hoang tưởng (paranoid) về cái việc sẽ có thể bị nhiễm bệnh (sick). - %1$s",
  "Get it together, or you're gonna wear out your welcome. Got it?": "Tập trung tinh thần lại đi, nếu đéo cậu chắc chắn sẽ tự mình làm hỏng đi cái sự chào đón nồng nhiệt (welcome) của mọi người dành cho cậu ở nơi này đấy. Hiểu rõ rồi chứ?",
  "I knew that milk tasted a little too much like cheese.... - %1$s": "Tôi đã biết tỏng rằng mùi vị của cái món sữa (milk) đó dường như hơi có một chút tương tự giống như phô mai (cheese) cmnr mà.... - %1$s",
  "Just don't leave me to die.": "Chỉ cần đừng có bỏ mặc tôi lại một mình để phải chịu đựng cái chết thảm khốc là được.",
  "You know how it is. Some people, you ask them to go without for a little bit and suddenly they're on the cross.": "Cậu biết rõ nó tồi tệ đến mức đéo nào rồi đấy. Một vài người, cậu chỉ yêu cầu bọn họ hãy tạm thời cố gắng nhịn đói vượt qua hoàn cảnh vô cùng khó khăn này một chút thôi và rồi ngay lập tức bọn họ bắt đầu tỏ ra thái độ y hệt như thể bản thân bọn họ đang bị đem đi đóng đinh trên cây thánh giá (cross) vậy.",
  "Are you up for helping with a trade run?": "Cậu có sẵn sàng để giúp đỡ thực hiện một chuyến giao dịch trao đổi hàng hóa (trade) đéo?",
  "133 STORY Sgt. Erik Tan": "133 CỐT TRUYỆN (STORY) Trung Sĩ (Sgt.) Erik Tan",
  "TRAINING MISSION": "NHIỆM VỤ HUẤN LUYỆN (TRAINING MISSION)",
  "Looks like a zed hoedown.": "Trông giống hệt như là một buổi tiệc khiêu vũ (hoedown) vô cùng cuồng nhiệt của một lũ zed vậy.",
  "Universal water-transporting tech.": "Hệ thống công nghệ (tech) cung cấp nước (water) vô cùng phổ biến.",
  "One man's trash is another man's treasure. I can find a way to make a buck off just about anything. (Advanced wits.)": "Đống rác thải (trash) của kẻ này rất có thể lại chính là một kho báu (treasure) quý giá đối với những kẻ khác. Tôi hoàn toàn có thể tự mình tìm ra được cách để kiếm tiền (buck) từ hầu như bất cứ một thứ đéo gì. (Sự Khôn Ngoan Sáng Suốt Tiên Tiến Advanced wits.)",
  "Woah, woah. You sure?": "Woah, woah. Cậu có thực sự chắc chắn về điều đó đéo vậy?",
  "I don't think I can do that.": "Tôi đéo nghĩ rằng mình có thể làm được cái điều đó đéo đâu.",
  "Hello? Can anybody hear me? If you're receiving this, I need some help!": "Xin chào? Có bất cứ ai có thể nghe thấy tôi nói đéo? Nếu như các người có thể nhận được đoạn tín hiệu (receiving) vô tuyến này, tôi đang thực sự cần phải có được một vài sự giúp đỡ!",
  "Canvas": "Loại Vải Bạt Dày Dặn (Canvas)",
  "Taking things from their SUPPLY LOCKER will cost more INFLUENCE now.": "Việc lấy đi bất kỳ thứ đéo gì từ trong những TỦ ĐỒ TIẾP TẾ (SUPPLY LOCKER) của bọn họ giờ đây sẽ khiến cho bạn phải tiêu tốn nhiều điểm ẢNH HƯỞNG (INFLUENCE) hơn.",
  "These things are homemade, so they don't last forever.": "Những thứ đồ chết tiệt này đều là các sản phẩm tự chế (homemade), vì vậy nên bọn chúng chắc chắn sẽ đéo thể nào tồn tại được mãi mãi đâu.",
  "I'm already loaded down.": "Tôi đã mang vác theo quá đủ những thứ đồ cồng kềnh (loaded down) rồi.",
  "Absent-Minded": "Cực Kỳ Lơ Đãng Và Thiếu Tập Trung (Absent-Minded)",
  "Might be worth it to do a little surveying.": "Rất có thể sẽ vô cùng đáng giá (worth) để dành ra chút thời gian để có thể đi khảo sát dò xét (surveying) đôi chút quanh khu vực này đấy.",
  "And that's that.": "Và mọi thứ chỉ đơn giản có vậy thôi.",
  "Assault Rifle: AUG A3": "Súng Trường Tấn Công (Assault Rifle): AUG A3",
  "I understand how you feel. I've often grappled with my own worthiness to lead, to serve as an example to my flock.": "Tôi hoàn toàn có thể thấu hiểu được cậu đang cảm thấy tồi tệ đến như thế nào. Tôi vẫn thường xuyên phải tự mình vật lộn (grappled) với chính sự kém cỏi vô dụng của bản thân trong việc cố gắng dẫn dắt, cũng như là việc phục vụ (serve) như một tấm gương vô cùng sáng chói dành cho những con chiên (flock) ở trong bầy đàn của mình.",
  "Aagh! Get 'em off! Eugh!": "Aagh! Hãy mau lôi bọn chúng ra khỏi người tôi đi (Get 'em off)! Eugh!",
  "LMG: M27 IAR": "Súng Máy Hạng Nhẹ (LMG): M27 IAR",
  "That's how I like it! Medium rare.": "Đó chính xác là những gì mà tôi rất thích ở nó! Được làm chín tái (Medium rare) vô cùng tuyệt vời.",
  "Hey, you want something more interesting, you find it your damn self.": "Này, nếu như cậu muốn tìm kiếm được một thứ đéo gì đó vô cùng thú vị (interesting) hơn nữa, thì tốt hơn hết là cậu nên tự mình vác cái xác chết tiệt (damn self) đi mà tìm kiếm nó đi nhé.",
  "Tommy": "Tommy",
  "Deeber": "Deeber",
  "Canned Tomatoes": "Cà Chua Đóng Hộp (Canned Tomatoes)",
  "16 GENERIC Zheng Chu": "16 CHUNG (GENERIC) Zheng Chu",
  "So, umm, what are we doing out here, exactly?": "Vậy, umm, chúng trên hiện đang làm cái đéo gì ở ngoài này, nói chính xác xem nào?",
  "That's none of your--": "Đó đéo phải là chuyện của cậu--",
  "Um ... Cleo? Are you listening?": "Um... Cleo? Cô có đang lắng nghe đéo đấy?",
  "It just went off! I swear I wasn't screwing around. I definitely wasn't trying to shoot anybody! - %1$s": "Khẩu súng chết tiệt đó bỗng nhiên phát nổ (went off)! Tôi xin thề với cậu là tôi đéo hề cố tình đi nghịch ngợm lung tung (screwing around) vào nó đéo đâu. Tôi chắc chắn là đéo bao giờ có ý định cố gắng để bắn trúng (shoot) vào bất kỳ một ai cả! - %1$s",
  "Negative. R.O.E. prohibits engaging civilian structures. Sorry.": "Hoàn toàn đéo thể nào (Negative). Quy Tắc Giao Chiến (R.O.E.) đã cực kỳ nghiêm cấm (prohibits) cái việc tấn công vào các cấu trúc công trình của dân thường (civilian). Tôi thành thật xin lỗi.",
  "Joined the military after a couple semesters of college. Hasn't quite figured out what direction to go. (Research Experience)": "Gia nhập vào trong lực lượng quân đội (military) sau một vài học kỳ diễn ra ở trường cao đẳng. Vẫn chưa thể nào có thể định hướng rõ ràng được những việc mà bản thân cần phải làm trong khoảng thời gian sắp tới. (Có Rất Nhiều Những Kinh Nghiệm Nghiên Cứu Chuyên Sâu Research Experience)",
  "They should be close.": "Bọn họ chắc chắn phải ở rất gần đây thôi.",
  "I'll try to keep up.": "Tôi sẽ luôn cố gắng hết sức để có thể bắt kịp tốc độ di chuyển.",
  "Macias": "Macias",
  "They would like to come join us.": "Bọn họ dường như đang rất muốn đến để xin được gia nhập (join) vào trong nhóm của chúng ta.",
  "So this dumbshit wandered off, and now we gotta go find 'em.": "Cho nên cái thằng ngu ngốc (dumbshit) này đã cố tình đi lang thang vớ vẩn ở một cái xó xỉnh chết tiệt nào đó cmnr, và hiện tại chúng ta lại sẽ phải cất công đi tìm kiếm bọn họ.",
  "Rescue: %s": "Giải Cứu (Rescue): %s",
  "Found some remaining items.": "Đã tìm thấy (Found) được một vài vật phẩm vẫn còn sót lại (remaining).",
  "Feel the burn! And the squish.": "Hãy cảm nhận những sự bỏng rát (burn)! Và cả sự nát bét (squish) đầy thảm khốc đi.",
  "You did what you could. Things can always go wrong.": "Cậu cũng đã cố gắng làm tất cả mọi thứ để cứu vãn lại tình thế trong khả năng có thể rồi. Mọi chuyện vẫn luôn có thể rẽ sang một hướng vô cùng tồi tệ mà.",
  "Please?": "Làm ơn (Please) đi?",
  "Our head count's coming up short. Could you help us look?": "Lực lượng nhân sự của chúng tôi hiện đang bị thiếu hụt đi rất nhiều người. Cậu có thể giúp đỡ chúng tôi cùng đi tìm kiếm (look) được đéo?"
};

const file = 'output/languages/chunks/btxt_chunk_201.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_201.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk201[r.sourceText]) {
    r.translatedText = chunk201[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 201 successfully!');
