const fs = require('fs');
const chunk128 = {
  "%+d Cases of Medicine": "%+d Thùng Thuốc Men",
  "Highroad Actual to Black Friday, prepare to copy new S-2 on an asset.": "Highroad Actual gọi Black Friday, chuẩn bị nhận báo cáo S-2 mới về một nhân sự.",
  "Rodeo Bleachers": "Khán Đài Đấu Bò (Rodeo)",
  "Nothing they didn't deserve.": "Không có gì mà bọn họ đéo đáng phải nhận cả.",
  "Clear Out the Zombies": "Dọn Dẹp Đám Zombie",
  "Quit dicking around and get back inside!": "Đừng có lảng vảng nữa và quay vào trong ngay!",
  "I'm out.": "Tôi hết đạn rồi.",
  "19 GENERIC Simon Sayers": "19 GENERIC Simon Sayers",
  "Lost Brother": "Người Anh Em Thất Lạc",
  "All in a day's work.": "Cũng chỉ là một ngày làm việc bình thường thôi.",
  "About time you showed up. Let's get my high-speed, low-drag ass back to your base.": "Đến lúc cậu xuất hiện rồi đấy. Hãy đưa cái mông nhanh nhẹn, gọn gàng này của tôi trở lại căn cứ của cậu đi.",
  "Event: Food poisoning": "Sự kiện: Ngộ độc thức ăn",
  "You get my back, I'll get yours!": "Cậu bảo vệ tôi, tôi sẽ bảo vệ cậu!",
  "Callie": "Callie",
  "Got any inspiration for me?": "Có nguồn cảm hứng nào cho tôi không?",
  "Phillips": "Phillips",
  "Woo! That one'll wake you up in the morning, huh? Damn near had a heart attack. - %1$s": "Woo! Quả đó đủ để đánh thức cậu vào buổi sáng luôn nhỉ? Gần như làm tôi đau tim chết mẹ. - %1$s",
  "CHEAT CHEAT CHEAT": "ĂN GIAN ĂN GIAN ĂN GIAN",
  "Fell in the initial attack.": "Đã gục ngã trong cuộc tấn công ban đầu.",
  "Start a Scenario at Breakdown Level 4.": "Bắt đầu một Kịch Bản ở Breakdown Cấp 4.",
  "Siege in Progress!": "Đang Bị Bao Vây!",
  "He's hurt, and... look.": "Anh ấy bị thương, và... nhìn kìa.",
  "SURVIVAL TACTICS: Collect Guns": "CHIẾN THUẬT SINH TỒN: Thu Thập Súng",
  "While the power is on, we can cook hot meals and run our more advanced facilities.": "Trong khi có điện, chúng ta có thể nấu những bữa ăn nóng và vận hành các cơ sở tiên tiến hơn của mình.",
  "So, Colton and Strand? Did you serve with them?": "Vậy, Colton và Strand? Cậu có phục vụ cùng họ không?",
  "Signed, sealed, and delivered. Now we'll see if Ray comes through with payment. - %1$s": "Đã ký kết, đóng dấu và giao hàng. Bây giờ chúng ta sẽ xem liệu Ray có thanh toán sòng phẳng hay không. - %1$s",
  "They weren't that impressed.": "Họ không mấy ấn tượng cho lắm.",
  "Liked to Tinker": "Thích Sửa Chữa Chế Tạo (Tinker)",
  "In case you haven't noticed, we're not exactly overburdened with strong leadership types. Alan's the only bastard cold enough to support a plan like that, and, well...": "Trong trường hợp cậu chưa để ý, chúng ta đéo hề có nhiều những kiểu người lãnh đạo mạnh mẽ đâu. Alan là tên khốn duy nhất đủ lạnh lùng để ủng hộ một kế hoạch như vậy, và, chà...",
  "Right. Let's get the hell back to the ranger station and get out of here.": "Phải rồi. Hãy quay lại trạm kiểm lâm và biến khỏi đây thôi.",
  "If they couldn't survive on their own, what chance has anybody got?": "Nếu họ không thể tự mình sống sót, thì ai có thể có cơ hội nào cơ chứ?",
  "Okay, just about done. We clear?": "Được rồi, gần xong rồi. Chúng ta an toàn chứ?",
  "My handler said this biopsy was worth me risking my funky ass, so do you people want it or not?": "Người quản lý của tôi nói rằng mẫu sinh thiết này đáng để tôi mạo hiểm cái mạng quèn của mình, vậy các người có muốn nó hay không?",
  "I really like this girl. I just want to make sure I'm not making a mistake.": "Tôi thực sự thích cô gái này. Tôi chỉ muốn chắc chắn rằng mình không phạm sai lầm.",
  "We're hitting the road.": "Chúng ta lên đường thôi.",
  "We've been searching the area near the base for additional supplies, but we're coming up empty. It's too early to give up, though.": "Chúng tôi đã tìm kiếm các nguồn cung cấp bổ sung ở khu vực gần căn cứ, nhưng đéo thu hoạch được gì. Dù vậy, vẫn còn quá sớm để bỏ cuộc.",
  "I'll help you search.": "Tôi sẽ giúp cậu tìm kiếm.",
  "Mickey, I could use some covering fire!": "Mickey, tôi cần anh bắn yểm trợ!",
  "Sorry. Not interested.": "Xin lỗi. Không hứng thú.",
  "Liliana": "Liliana",
  "A huge band nerd in high school. His sister joked that he joined the military mostly for the marching.": "Một tên mọt sách to xác trong ban nhạc ở trường trung học. Em gái cậu ta nói đùa rằng cậu ta gia nhập quân đội chủ yếu là để được diễu hành.",
  "It's not too late to seek redemption.": "Vẫn chưa quá muộn để tìm kiếm sự chuộc lỗi đâu.",
  "Great. Let's keep it that way.": "Tuyệt. Cứ giữ vững phong độ như vậy nhé.",
  "Cooperation is the key. We have to learn to live together. We have to learn to work together. (Idealistic.)": "Hợp tác là chìa khóa. Chúng ta phải học cách sống cùng nhau. Chúng ta phải học cách làm việc cùng nhau. (Lý tưởng hóa.)",
  "Sorry, kid. If we're going by \"who's dying first,\" I got you beat by at least a few months.": "Xin lỗi nhé, nhóc. Nếu chúng ta tính xem \"ai sẽ chết trước,\" thì tôi đã đánh bại cậu ít nhất vài tháng rồi đấy.",
  "Now how can I slack off when folks are pitchin' in like that?": "Giờ thì làm sao tôi có thể lười biếng khi mọi người đang chung tay giúp đỡ như vậy chứ?",
  "Nah, let's wait on this one.": "Thôi, hãy đợi thêm chút nữa với việc này.",
  "Face, meet bat.": "Mặt, chạm gậy nào.",
  "Has left the community.": "Đã rời khỏi cộng đồng.",
  "\"Fanny angels\"? Now they're just messing with us.": "\"Fanny angels\"? Giờ thì bọn chúng chỉ đang đùa giỡn với chúng ta thôi.",
  "Oh yeah, you all want some of this!": "Oh yeah, tất cả bọn mày đều muốn nếm thử cái này phải không!",
  "Almost. Just give me a second.": "Sắp xong rồi. Cho tôi một giây thôi.",
  "Higgins": "Higgins",
  "We rescued some lab reports from the Human Future Fund, which had been funding Thomas Horn's research.\r\nUnfortunately, in the process we lost the HFF administrator to the zeds.": "Chúng tôi đã giải cứu một số báo cáo phòng thí nghiệm từ Quỹ Tương Lai Nhân Loại (Human Future Fund), tổ chức đã tài trợ cho nghiên cứu của Thomas Horn.\r\nĐáng tiếc là trong quá trình đó, chúng tôi đã mất một quản trị viên của HFF vào tay lũ zed.",
  "Events": "Sự kiện",
  "Foster": "Foster",
  "Updated second-cousin of the M10, semi-automatic.": "Phiên bản nâng cấp được xem như người anh em họ xa của M10, bán tự động.",
  "Hey, we've run into some trouble.": "Này, chúng tôi đang gặp phải một số rắc rối.",
  "Rifle: Lenfield No.4 MkI": "Súng trường: Lenfield No.4 MkI",
  "Moderate extra damage. Lethal Juggernauts. No map indicators.": "Tăng thêm sát thương ở mức vừa. Juggernauts Chí Mạng. Không có chỉ báo trên bản đồ.",
  "Alright. Hope the return trip goes well.": "Được rồi. Hy vọng chuyến trở về sẽ suôn sẻ.",
  "I confess that particular intelligence has eluded me until now.": "Tôi thú nhận rằng tôi đã đéo nắm được thông tin tình báo cụ thể đó cho đến tận bây giờ.",
  "A word of warning about the Wilkersons, though....": "Dù vậy, xin có một lời cảnh báo về bọn nhà Wilkerson....",
  "Sentencing severity reduced by 33%.": "Mức độ nghiêm trọng của bản án giảm 33%.",
  "No ma'am.": "Không, thưa cô.",
  "The Sacrifice": "Sự Hy Sinh",
  "There's a horde right behind us. Move your asses!": "Có một bầy horde ngay phía sau chúng ta. Vác cái xác lên và chạy đi!",
  "Guess that's two I owe you. I'll meet you out front.": "Đoán là tôi nợ cậu hai lần rồi đấy. Tôi sẽ gặp cậu ở phía trước.",
  "It's always hard to lose one of our own. Seems like we've lost so many people....": "Việc mất đi một người của chính mình luôn luôn khó khăn. Có vẻ như chúng ta đã mất đi quá nhiều người rồi....",
  "Look, I know there's some food here somewhere, I just... gotta find it. Please. It's for my brother.": "Nghe này, tôi biết có một ít thức ăn ở đâu đó quanh đây, tôi chỉ... phải tìm thấy nó. Làm ơn. Nó dành cho anh trai tôi.",
  "Next time, kill the Screamer with fire.": "Lần sau, hãy dùng lửa để giết bọn Screamer.",
  "It's not that easy. I need them in good condition.": "Nó đéo dễ như vậy đâu. Tôi cần chúng ở tình trạng tốt.",
  "Farmhouse Food Storage": "Kho Thức Ăn Nông Trại",
  "Survival Handbook": "Sổ Tay Sinh Tồn",
  "Claire": "Claire",
  "This is going from bad to worse, fast.": "Chuyện này đang từ tồi tệ chuyển sang tồi tệ hơn, và rất nhanh.",
  "If there is, we'll have to make an incision through the skull to drain off the excess fluid.": "Nếu có, chúng ta sẽ phải rạch một đường qua hộp sọ để dẫn lưu lượng dịch thừa ra ngoài.",
  "Community Reputation Worsened": "Danh Tiếng Cộng Đồng Giảm Sút",
  "I managed to get clear, but they were right on my ass and I was low on ammo.": "Tôi đã cố gắng thoát thân, nhưng chúng bám sát ngay đằng sau và tôi thì sắp hết đạn.",
  "Resources Gained": "Tài Nguyên Thu Được",
  "Eesh. That place is crawling with zombies.": "Eo ôi. Nơi đó đang nhung nhúc bọn zombie.",
  "Check it out. I managed to decrypt this signal.": "Xem này. Tôi đã giải mã được tín hiệu này rồi.",
  "Your momma's so dumb zombies call her \"appetizer.\"": "Mẹ mày ngu đến mức bọn zombie còn gọi bà ấy là \"món khai vị\" đấy.",
  "Could he have the cure?": "Liệu ông ấy có thuốc giải không?",
  "[message looping tone] One one tango mike papa two five delta zero five papa.": "[âm thanh thông báo lặp lại] One one tango mike papa two five delta zero five papa.",
  "Rescue Thomas Horn": "Giải Cứu Thomas Horn",
  "Critical failure!": "Thất bại chí mạng!",
  "Allows weapon repair and item creation.": "Cho phép sửa chữa vũ khí và chế tạo vật phẩm.",
  "Not enough space here for what we need.": "Đéo đủ không gian ở đây cho những gì chúng ta cần.",
  "%.2f lbs": "%.2f lbs",
  "This bag's really fucking heavy, so how about a thank you?": "Cái túi này nặng vãi lồn, vậy nên sao đéo nói một lời cảm ơn đi?",
  "Yeah, I understand. Deciding whether to murder thousands of people is a big decision. You take whatever time you need.": "Vâng, tôi hiểu. Việc quyết định xem có nên giết hàng nghìn người hay không là một quyết định lớn. Cô cứ lấy bao nhiêu thời gian tùy thích.",
  "Madaleno": "Madaleno",
  "Follow Jacob": "Theo Chân Jacob",
  "It's about time! I need to get out of here!": "Đến lúc rồi! Tôi cần phải rời khỏi đây!",
  "Nobody's really sure why you're even here.": "Đéo ai thực sự chắc chắn tại sao cậu lại ở đây cả.",
  "It's one thing to know how to roll with the punches. It's better if you can avoid 'em all together. (Great reflexes.)": "Biết cách chống đỡ những cú đấm là một chuyện. Sẽ tốt hơn nếu cậu có thể hoàn toàn né tránh được chúng. (Phản xạ tuyệt vời.)",
  "Ally Fled (Food Shortage)": "Đồng Minh Đã Bỏ Trốn (Thiếu Thức Ăn)",
  "I'm not in charge.": "Tôi đéo phải là người phụ trách.",
  "Available": "Có Sẵn",
  "Help hunt the Juggernaut?": "Giúp săn lùng con Juggernaut chứ?",
  "Yeah! C'mon, you shit-eatin' sonsabitches!": "Yeah! Lên đi, mấy thằng chó đẻ ăn cứt!",
  "Just takin' inventory while you decide when you're ready to load up.": "Tôi chỉ đang kiểm kê đồ đạc trong khi chờ cậu quyết định xem khi nào thì cậu sẵn sàng nạp đạn.",
  "Scanning.": "Đang quét.",
  "Let's hole up here, let' em run right past.": "Hãy ẩn nấp ở đây đi, cứ để bọn chúng chạy lướt qua.",
  "Well, I suppose I owe you one.": "Chà, tôi đoán là tôi nợ cậu một ân tình.",
  "%1$s is sick now too.": "%1$s bây giờ cũng bị bệnh rồi.",
  "Target spotted.": "Đã phát hiện mục tiêu.",
  "Refrigerated Supply": "Nguồn Cung Cấp Đông Lạnh",
  "Madison Grant is safe": "Madison Grant đã an toàn",
  "Remote enough we'd have to drive to get anywhere, but I see your point.": "Đủ hẻo lánh để chúng ta phải lái xe nếu muốn đi đến bất cứ đâu, nhưng tôi hiểu ý cậu.",
  "Gross": "Kinh Tởm",
  "Gunpowder": "Thuốc Súng",
  "That's not important. Is it true?": "Điều đó đéo quan trọng. Nó có đúng sự thật không?",
  "Choose a specialization": "Chọn một chuyên môn",
  "We saved Dan Bogatz": "Chúng ta đã cứu Dan Bogatz",
  "Hey. Thank you again. I owe you my life.": "Này. Cảm ơn cậu lần nữa. Tôi nợ cậu mạng sống này.",
  "Get Doc Hanson.": "Đi tìm Bác sĩ Hanson đi.",
  "Wait!": "Đợi đã!",
  "I'm just worn out. Food isn't going to change that.": "Tôi chỉ đang kiệt sức thôi. Thức ăn sẽ đéo thể thay đổi được điều đó đâu.",
  "Those folks need someone to help them get down here. -%2$s": "Những người đó cần ai đó giúp họ xuống đây. -%2$s",
  "Ex-wife. Oh, like it matters. Yes, please get us out of here!": "Vợ cũ. Ồ, làm như điều đó quan trọng lắm vậy. Đúng, làm ơn đưa chúng tôi ra khỏi đây đi!",
  "Honestly, a little town like this? It's not like the stores here had the greatest selection to begin with.": "Thành thật mà nói, một thị trấn nhỏ như thế này á? Các cửa hàng ở đây vốn dĩ cũng đéo có nhiều sự lựa chọn ngay từ đầu rồi.",
  "Fortunately, I have faith in you.": "May mắn thay, tôi có niềm tin ở cậu.",
  "Anybody got a car I could use?": "Có ai có chiếc xe nào tôi có thể dùng được không?",
  "He needed a doctor.": "Ông ấy cần một bác sĩ.",
  "So now we got zeds wearin' body armor. What's next, drivin' cars?": "Vậy là bây giờ chúng ta có bọn zed mặc áo giáp chống đạn. Điều gì tiếp theo đây, chúng nó lái xe luôn chắc?",
  "Huh. I expected the universe to shit on us.": "Hừm. Tôi đã đinh ninh là vũ trụ lại chuẩn bị giáng thêm một đống cứt lên đầu chúng ta cơ.",
  "Just got word that a whole bunch more zombies are headed your way.": "Vừa nhận được tin báo rằng có thêm một đám đông zombie đang tiến về phía các người.",
  "Artillery is operational, ma'am. We can start lighting up the zeds any time you want.": "Pháo binh đã sẵn sàng hoạt động, thưa cô. Chúng ta có thể nã pháo vào bọn zed bất cứ lúc nào cô muốn.",
  "Sgt": "Trung Sĩ",
  "%1$s made the ultimate sacrifice.": "%1$s đã thực hiện sự hy sinh cao cả nhất.",
  "Yeah, didn't think so.": "Ừ, đéo nghĩ thế đâu.",
  "Trujillo": "Trujillo",
  "Hunter": "Thợ Săn",
  "Come on now, don't y'all be a bunch of pussies! We still need somebody with a ride down here at the farm!": "Thôi nào, đừng có hành xử như một lũ chết nhát! Chúng tôi vẫn cần ai đó có xe ở trang trại dưới này!",
  "I see something ahead of us.": "Tôi thấy cái gì đó ở phía trước chúng ta kìa.",
  "Sudden noises are great for grabbing attention. (Best to toss these and then run or hide.)": "Những tiếng ồn bất ngờ rất tuyệt để thu hút sự chú ý. (Tốt nhất là ném những thứ này rồi chạy hoặc trốn.)",
  "BUILDING TENSION": "GIA TĂNG SỰ CĂNG THẲNG",
  "Engaging!": "Giao chiến!",
  "Look for Alan Gunderson": "Tìm Alan Gunderson",
  "-60% Max Stamina": "-60% Thể Lực Tối Đa",
  "No user signed in": "Chưa có người dùng đăng nhập",
  "These leave an impression.": "Những thứ này để lại ấn tượng đấy.",
  "Hey, hey! Low stamina makes it easier for the zeds to drag you down.": "Này, này! Thể lực thấp sẽ khiến bọn zed dễ dàng kéo bạn ngã xuống hơn đấy.",
  "You gonna be okay on your own?": "Cậu tự lo một mình được không đấy?",
  "I know you're scared, but I know a trick to help. Follow me.": "Tôi biết cậu đang sợ hãi, nhưng tôi biết một mẹo có thể giúp ích. Theo tôi.",
  "Doghouse - Vehicle Delivery": "Doghouse - Giao Phương Tiện",
  "Shit, they're around back!": "Chết tiệt, chúng vòng ra đằng sau rồi!",
  "You are still ENCUMBERED. Stamina will drain rapidly while sprinting.": "Bạn vẫn đang bị QUÁ TẢI (ENCUMBERED). Thể lực sẽ giảm nhanh chóng khi chạy nước rút.",
  "Gamer Rating": "Xếp Hạng Người Chơi",
  "EXPIRED: Zed Hunt": "HẾT HẠN: Săn Zed",
  "Fear Itself": "Bản Thân Nỗi Sợ Hãi",
  "Uppercut": "Cú đấm móc (Uppercut)",
  "Listen, I'm a generous guy, but at some point you're just taking advantage of me.": "Nghe này, tôi là một người hào phóng, nhưng đến một lúc nào đó thì cậu chỉ đang lợi dụng tôi thôi.",
  "I need some damn backup!": "Tôi cần chó chết một chút viện trợ!",
  "You build up some excellent interpersonal skills when you work all day with people on the edge of dementia.": "Cậu sẽ xây dựng được những kỹ năng giao tiếp tuyệt vời khi làm việc cả ngày với những người đang trên bờ vực mất trí nhớ.",
  "Desperately Need Medicine": "Tuyệt Vọng Cần Thuốc Men",
  "Wonder what's gonna go wrong today.": "Tự hỏi hôm nay sẽ có chuyện tồi tệ gì xảy ra đây.",
  "XP penalty from Two Left Feet.": "Hình phạt XP từ Lóng Ngóng (Two Left Feet).",
  "We ain't done yet!": "Chúng ta vẫn chưa xong đâu!",
  "Retrieved Thomas Ritter's watch for Lily. Something to remember him by.": "Đã lấy lại được chiếc đồng hồ của Thomas Ritter cho Lily. Một thứ gì đó để tưởng nhớ về anh ấy.",
  "Looks like we have an issue in the Kitchen.": "Có vẻ như chúng ta đang gặp vấn đề trong Nhà Bếp.",
  "I don't know what your problem is, and I don't care. But you're making it everybody's problem, and that's not gonna fly.": "Tôi đéo biết vấn đề của cậu là gì, và tôi cũng đéo quan tâm. Nhưng cậu đang biến nó thành vấn đề của mọi người, và chuyện đó sẽ đéo được chấp nhận đâu.",
  "Not many people feel like dancing right now. Things are just too goddamn depressing. (Improved Cardio)": "Bây giờ đéo có mấy ai có tâm trạng để nhảy múa đâu. Mọi thứ đang quá sức tuyệt vọng mẹ nó rồi. (Cải Thiện Tim Mạch)",
  "Reduced Wound Recovery chance.": "Giảm cơ hội Phục Hồi Vết Thương (Wound Recovery).",
  "98 GENERIC Jackson Hollis": "98 GENERIC Jackson Hollis",
  "Sight Adjustment Tools": "Bộ Dụng Cụ Điều Chỉnh Ống Ngắm",
  "Yes. This is definitely where we should be.": "Vâng. Đây chắc chắn là nơi chúng ta nên ở lại.",
  "I got all the way to the edge of town just to get trapped in a building!": "Tôi đã lặn lội đến tận rìa thị trấn chỉ để bị mắc kẹt trong một tòa nhà!",
  "A powerful slam from a zombie caused massive contusions and internal bleeding. (Health and Stamina penalty)": "Một cú đập mạnh từ một con zombie đã gây ra những vết bầm tím lớn và chảy máu trong. (Hình phạt về Máu và Thể Lực)",
  "Gathered medicine.": "Đã thu thập thuốc men.",
  "94 GENERIC Frank Fitzgerald": "94 GENERIC Frank Fitzgerald",
  "Mickey, can you watch my ass?": "Mickey, cậu có thể bọc hậu cho tôi được không?",
  "I managed to find %3$s and get them home safe and sound.": "Tôi đã tìm được %3$s và đưa họ về nhà an toàn.",
  "Talk to %1$s %2$s": "Nói chuyện với %1$s %2$s",
  "You're giving away our goddamn position with this Rambo shit.": "Cậu đang để lộ vị trí chết tiệt của chúng ta bằng cái trò Rambo chó má này đấy.",
  "Nobody knows what it is. But it sure as shit ain't a virus. We'd have seen it by now.": "Đéo ai biết nó là cái gì. Nhưng chắc chắn như ban ngày rằng đéo phải là một loại virus. Nếu thế thì chúng ta đã phát hiện ra nó rồi.",
  "Left": "Bên trái",
  "Okoro": "Okoro",
  "Madelyn": "Madelyn",
  "Anybody tell you you can be a real meanie-weenie?": "Đã có ai nói với cậu rằng cậu có thể là một kẻ thực sự xấu tính chưa?",
  "Whitlock": "Whitlock",
  "Search and Rescue": "Tìm Kiếm và Cứu Hộ",
  "Lorenz": "Lorenz",
  "Fish Stunner": "Dụng Cụ Chích Điện Cá (Fish Stunner)",
  "Round up your people and get them on that bird.": "Tập hợp người của cậu lại và đưa họ lên chiếc trực thăng đó đi.",
  "Scientific Principles": "Các Nguyên Lý Khoa Học",
  "105 STORY Philip Manfred": "105 STORY Philip Manfred",
  "Great. Out of food.": "Tuyệt. Đéo còn thức ăn nữa.",
  "You sure about this?": "Cậu chắc chắn về điều này chứ?",
  "Get clear! I got these assholes!": "Tránh ra! Để lũ khốn này cho tôi!",
  "Black Friday, we're picking up a strange broadcast here that none of my folks can make any sense of.": "Black Friday, chúng tôi đang bắt được một chương trình phát thanh kỳ lạ ở đây mà đéo ai trong số người của tôi có thể hiểu được.",
  "Yeah, well, excuse me for not being team cheerleader.": "Vâng, chà, xin thứ lỗi cho việc tôi đéo phải là đội trưởng đội cổ vũ.",
  "Helped %3$s with a supply run. They were glad for the help, so they cut us in. -%1$s": "Đã giúp %3$s thực hiện một chuyến đi thu thập vật tư. Họ rất vui vì được giúp đỡ, nên họ đã chia phần cho chúng ta. -%1$s",
  "Almost out of that.": "Gần như đã cạn kiệt thứ đó rồi.",
  "On the right side, you seein' this?": "Bên cánh phải, cậu có thấy không?",
  "He's a whiz with a gun, and the dozens of taxidermied animals on his wall prove it.": "Anh ta là một chuyên gia sử dụng súng, và hàng tá động vật nhồi bông trên tường của anh ta đã chứng minh điều đó.",
  "RIP Andy": "Yên nghỉ nhé Andy",
  "Resolution 2160p": "Độ phân giải 2160p"
};

const file = 'output/languages/chunks/btxt_chunk_128.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_128.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk128[r.sourceText]) {
    r.translatedText = chunk128[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 128 successfully!');
