const fs = require('fs');
const chunk105 = {
  "For now, that's a good enough reason. It's bad enough fighting zombies, I don't want to have to fight the Wilkersons, too.": "Tạm thời thì đó là một lý do đủ tốt. Đánh nhau với zombie đã đủ mệt rồi, tôi không muốn phải đánh nhau với cả gia đình Wilkerson nữa đâu.",
  "I've been saying we can't just leave our shit lying around on shelves. We need some way to refrigerate our food.": "Tôi đã nói rồi, chúng ta không thể cứ vứt đồ đạc bừa bãi trên kệ được. Chúng ta cần một cách nào đó để bảo quản lạnh thức ăn.",
  "You ready?": "Sẵn sàng chưa?",
  "But on the plus side, at least you're not in Montana.": "Nhưng điểm cộng là, ít ra cậu không ở Montana.",
  "Stopping Power Increased!": "Đã Tăng Lực Cản (Stopping Power)!",
  "Look, we're all scared. None of us knows what's gonna happen next.": "Nghe này, tất cả chúng ta đều sợ hãi. Không ai trong chúng ta biết điều gì sẽ xảy ra tiếp theo.",
  "We've got Bogatz. He's wounded.": "Chúng ta đã tìm thấy Bogatz. Anh ta bị thương rồi.",
  "Pistol: Bz 75": "Súng lục: Bz 75",
  "Like loud noises, don't ya?": "Thích tiếng ồn lớn lắm phải không?",
  "Well, you can cancel that missing persons report. %3$s just made it home, courtesy of %1$s. - %2$s": "À, cậu có thể hủy báo cáo người mất tích đó đi. %3$s vừa về đến nhà, nhờ công của %1$s. - %2$s",
  "Alana": "Alana",
  "We're pretty shorthanded right now. We'd love to have you.": "Hiện tại chúng tôi đang khá thiếu nhân lực. Rất vui nếu cậu gia nhập.",
  "No, we should have it covered.": "Không, chúng tôi lo liệu được.",
  "17 GENERIC Simon Sayers": "17 GENERIC Simon Sayers",
  "RESOURCES keep our community going.": "TÀI NGUYÊN (RESOURCES) giúp cộng đồng của chúng ta duy trì hoạt động.",
  "Never mind. I'm just here to trade.": "Đừng bận tâm. Tôi chỉ đến đây để giao dịch.",
  "People will start to flee.": "Mọi người sẽ bắt đầu bỏ chạy.",
  "Looks like some zeds are followin' us.": "Có vẻ như vài con Zed đang bám theo chúng ta.",
  "Greyhound One, this is Black Friday. We have a visual on you now.": "Greyhound One, đây là Black Friday. Chúng tôi đã thấy các anh.",
  "I got a visual.": "Tôi đã nhìn thấy mục tiêu.",
  "DEFENSE: Incoming Horde Destroyed": "PHÒNG THỦ: Đã Tiêu Diệt Bầy Zombie Đang Tới",
  "Then I promptly told them all to get fucked as soon as I turned 18. Moved out here and did my damnedest to forget everything they taught me.": "Rồi tao thẳng thừng bảo bọn họ cút đi ngay khi tao vừa tròn 18 tuổi. Chuyển ra đây và cố gắng hết sức để quên sạch những gì họ đã dạy tao.",
  "Tasked with maintaining some semblance of order in Trumbull County.": "Được giao nhiệm vụ duy trì một chút trật tự còn sót lại ở Hạt Trumbull.",
  "Gamer Mu": "Gamer Mu",
  "Just uh, don't tell the Judge, okay?": "Chỉ là... đừng nói với Thẩm Phán nhé, được không?",
  "%2$s isn't happy.": "%2$s không vui đâu.",
  "And I was having such a good time out here.": "Và tôi đang có một khoảng thời gian tuyệt vời ở ngoài này cơ mà.",
  "Seems like an asshole.": "Có vẻ là một tên khốn.",
  "Eldridge has a point. These freak mutations can't be random, or we wouldn't see the same ones again and again.": "Eldridge nói có lý. Những đột biến quái dị này không thể là ngẫu nhiên, nếu không chúng ta đã chẳng thấy những dạng y hệt lặp đi lặp lại.",
  "Survive the Zombie Attack": "Sống Sót Qua Đợt Tấn Công Của Zombie",
  "I'm not stealing it, I'm just... borrowing it. Honest. That's all. Look, I need it, okay? - %1$s": "Tôi không ăn cắp nó, tôi chỉ... mượn tạm thôi. Thật đấy. Chỉ vậy thôi. Nghe này, tôi cần nó, được chưa? - %1$s",
  "[message looping tone] This is Cleo. Order at DZ.": "[âm báo lặp lại] Đây là Cleo. Hàng đã đến Khu Vực Thả (Drop Zone).",
  "I wish I'd gotten to know her better.": "Ước gì tôi đã có cơ hội biết cô ấy rõ hơn.",
  "Preserve Food": "Bảo Quản Thức Ăn",
  "We could use your help.": "Chúng tôi cần sự giúp đỡ của cậu.",
  "Oh, interesting.": "Ồ, thú vị đấy.",
  "INFLUENCE GAINED (Rapid Completion)": "ĐIỂM ẢNH HƯỞNG ĐƯỢC TĂNG (Hoàn Thành Nhanh Chóng)",
  "Good news. We figured out how to make homemade grenades.": "Tin tốt đây. Chúng ta đã tìm ra cách chế tạo lựu đạn tự chế.",
  "SET UP: Medical Area": "THIẾT LẬP: Khu Vực Y Tế",
  "Gabriela": "Gabriela",
  "Easy soldier. What happened to you?": "Bình tĩnh nào người lính. Có chuyện gì xảy ra với cậu vậy?",
  "Emphasis on \"were.\"": "Nhấn mạnh vào từ \"đã từng.\"",
  "No problem.": "Không vấn đề gì.",
  "Shotgun: Model 1887": "Shotgun: Model 1887",
  "Need 10 Materials": "Cần 10 Vật liệu",
  "Trade our Ammo for some Medicine?": "Đổi Đạn của chúng ta lấy Thuốc Men nhé?",
  "Low Backpack": "Ba Lô Sức Chứa Nhỏ",
  "This could work. Nice size, remote enough there's not too many zeds....": "Chỗ này có vẻ ổn. Rộng rãi, đủ hẻo lánh nên không có quá nhiều zeds...",
  "Here you go. As promised.": "Của cậu đây. Như đã hứa.",
  "After a childhood of first-class luxury, she shocked her parents by enlisting in the Army. She wants to have a \"real life\" ... whatever that means.": "Sau một tuổi thơ sống trong nhung lụa, cô đã làm cha mẹ sốc nặng khi nhập ngũ. Cô ấy muốn có một \"cuộc sống thực sự\"... dù điều đó có nghĩa là gì đi nữa.",
  "Hey, hey. I'm just here to make sure the trade goes nice and smooth.": "Này, này. Tôi chỉ ở đây để đảm bảo cuộc giao dịch diễn ra tốt đẹp và suôn sẻ thôi.",
  "Daniel": "Daniel",
  "Supply Lines: Materials Found": "Tuyến Tiếp Tế: Đã Tìm Thấy Vật Liệu",
  "State of Decay": "State of Decay",
  "A handy, short notice weapon.": "Một vũ khí tiện dụng, ứng phó nhanh.",
  "We need to stock up on medicine.": "Chúng ta cần tích trữ thuốc men.",
  "Can he match Dr. Horn's expertise?": "Ông ta có thể sánh với chuyên môn của Tiến sĩ Horn không?",
  "%s Clear": "%s Đã Dọn Sạch",
  "Fucking zombies keep picking our people off.": "Bọn zombie chết tiệt cứ liên tục sát hại người của chúng ta.",
  "On the right, on the right!": "Bên phải, bên phải!",
  "126 HERO Calliope Morris": "126 HERO Calliope Morris",
  "I'm never going to know love again. - %1$s": "Tôi sẽ không bao giờ biết đến tình yêu nữa. - %1$s",
  "Liam": "Liam",
  "I'm sorry, son. I did all I could.": "Ta xin lỗi, chàng trai. Ta đã làm tất cả những gì có thể.",
  "Meimberg": "Meimberg",
  "This is something else. Something much worse.": "Đây là một thứ khác. Một thứ gì đó tồi tệ hơn nhiều.",
  "SitRep: Worldwide Outbreaks": "Báo Cáo Tình Hình: Bùng Phát Toàn Cầu",
  "That's everything. Let's get out of here.": "Đó là tất cả mọi thứ. Cùng ra khỏi đây thôi.",
  "It's not exactly a core survival skill, but I am pretty good with a ukelele.": "Đó không hẳn là một kỹ năng sinh tồn cốt lõi, nhưng tôi chơi đàn ukulele khá giỏi đấy.",
  "Can I help you?": "Tôi có thể giúp gì cho cậu không?",
  "It's a long shot, but I want you to go in and see if they're still alive. Highroad out.": "Hy vọng rất mong manh, nhưng tôi muốn các anh vào trong đó xem họ có còn sống hay không. Highroad, hết.",
  "Created 2 Box Mines.": "Đã chế tạo 2 Mìn Hộp (Box Mine).",
  "Heads up. We've got zombie activity at three o'clock..": "Cẩn thận. Có dấu hiệu của zombie ở hướng ba giờ..",
  "Food, medicine, ammo? That all makes sense. Immediate survival and yadda yadda.": "Thức ăn, thuốc men, đạn dược? Tất cả đều hợp lý. Sinh tồn trước mắt và vân vân, mây mây.",
  "Come on. We're getting out of here.": "Đi thôi. Chúng ta phải rời khỏi đây.",
  "Apparently the agency has been watching Bogatz lately, and even put a tracker in his car.": "Rõ ràng là cơ quan tình báo đã theo dõi Bogatz dạo gần đây, thậm chí còn đặt máy theo dõi trong xe của anh ta.",
  "Nerdfighter": "Mọt Sách Chiến Binh",
  "We should check these out.": "Chúng ta nên kiểm tra những thứ này.",
  "%2$s is stabilized, at least. Could have just as easily gone the other way, though. - %3$s": "%2$s ít nhất đã ổn định lại. Tuy nhiên, mọi chuyện cũng có thể dễ dàng đi theo chiều hướng xấu hơn. - %3$s",
  "Not that I'm planning to break bad on you, but a little energy boost while you're out there might save your butt.": "Không phải là tôi muốn làm trò gì mờ ám với cậu đâu, nhưng một chút thuốc tăng lực khi cậu ở ngoài đó có thể cứu mạng cậu đấy.",
  "They've sorted it out themselves. They're moving again.": "Họ tự giải quyết xong rồi. Họ đang di chuyển tiếp.",
  "State of Decay is an open sandbox world that develops in real time, dynamically responding to your actions, the choices you make, and the ever-increasing zombie threat. Decide where you'd like to set up a fortified safe haven for you and other survivors you've rescued, then scout for critical supplies and call runners to gather resources and create supply chains. Use the materials you've gathered to build and upgrade your home base, but be careful! Resources will deplete as you pillage areas, and zombies are attracted to noise and activity. Take up the offensive by assaulting hordes before they reach your home, or focus on improving your defenses against the massed zombie attacks. Every choice and every action matter in this fully simulated, evolving world.": "State of Decay là một thế giới mở hộp cát phát triển theo thời gian thực, phản ứng linh hoạt với các hành động, lựa chọn của bạn và cả mối đe dọa từ zombie ngày càng gia tăng. Hãy quyết định nơi bạn muốn thiết lập một nơi trú ẩn an toàn cho mình và những người sống sót khác mà bạn đã cứu, sau đó trinh sát để tìm kiếm nguồn nhu yếu phẩm thiết yếu, đồng thời gọi các \"người vận chuyển\" (runners) thu thập tài nguyên và tạo chuỗi cung ứng. Sử dụng vật liệu bạn thu thập được để xây dựng và nâng cấp căn cứ của mình, nhưng hãy cẩn thận! Tài nguyên sẽ cạn kiệt khi bạn cướp bóc các khu vực, và zombie thì luôn bị thu hút bởi tiếng ồn và sự hoạt động. Hãy chủ động tấn công tiêu diệt các bầy zombie trước khi chúng tiến đến nhà bạn, hoặc tập trung vào việc củng cố hệ thống phòng thủ chống lại các cuộc tấn công hàng loạt của xác sống. Mọi lựa chọn và mọi hành động đều quan trọng trong thế giới giả lập tiến hóa không ngừng này.",
  "Helped %3$s take out an Armored zombie. They said thanks with some supply stockpiles. -%1$s": "Đã giúp %3$s tiêu diệt một con zombie Bọc Thép (Armored zombie). Họ cảm ơn bằng một ít hàng dự trữ. -%1$s",
  "The crud's contagious.": "Căn bệnh này có tính truyền nhiễm đấy.",
  "Man, this is some bullshit. Risking three guys just to go out and find one dumb asshole who got himself lost?": "Trời ạ, đúng là trò nhảm nhí. Liều mạng ba người chỉ để ra ngoài tìm một thằng ngu ngốc tự đi lạc sao?",
  "The rats and bugs just ate a bunch of our food!": "Lũ chuột và bọ vừa ăn mất một đống thức ăn của chúng ta!",
  "It's from the New International No Bullshit Version.": "Trích từ Kinh Thánh Phiên bản Quốc tế Mới Đéo Giỡn Mặt.",
  "Necessity, the mother of invention.": "Cái khó ló cái khôn.",
  "Good shooting! Hey Mickey, you taking notes?": "Bắn hay lắm! Này Mickey, chú có đang ghi chép lại không đấy?",
  "Just need a couple minutes.": "Chỉ cần vài phút thôi.",
  "-20% Max Stamina": "-20% Thể Lực Tối Đa",
  "Missing": "Mất Tích",
  "That's a relief.": "Thật nhẹ nhõm.",
  "Somebody could use some time away from base. C'mon.": "Có vài người cần chút thời gian ra khỏi căn cứ cho khuây khỏa. Đi nào.",
  "Zeds in sight, stay frosty.": "Zeds trong tầm nhìn, giữ cái đầu lạnh nhé.",
  "I told Quentin the truth about Becca. He deserved to know.": "Tôi đã nói cho Quentin biết sự thật về Becca. Anh ta xứng đáng được biết.",
  "Lily will warn you if someone's attitude is cause for concern.": "Lily sẽ cảnh báo bạn nếu thái độ của ai đó trở nên đáng lo ngại.",
  "Hmm… I think I see a pattern to their movements.": "Hừm... Tôi nghĩ là tôi nhìn ra quy luật di chuyển của bọn chúng rồi.",
  "An AK 47 and a shotgun had a baby.": "Một đứa con lai giữa AK 47 và shotgun.",
  "UPGRADED: Medical Lab": "ĐÃ NÂNG CẤP: Phòng Thí Nghiệm Y Tế"
};

const file = 'output/languages/chunks/btxt_chunk_105.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_105.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk105[r.sourceText]) {
    r.translatedText = chunk105[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 105 successfully!');
