const fs = require('fs');
const chunk116 = {
  "Porter": "Porter",
  "There's something unnatural about this so-called Black Fever. No medicines seem to help. - %1$s": "Có điều gì đó không bình thường về cái gọi là Cơn Sốt Đen (Black Fever) này. Có vẻ như không loại thuốc nào có tác dụng cả. - %1$s",
  "Ask about Material Caches": "Hỏi về các Nơi Giấu Vật Liệu (Material Caches)",
  "Let's rock this shit!": "Quẩy lên nào bọn khốn!",
  "The biggest problem we've got right now is food spoilage, right?": "Vấn đề lớn nhất của chúng ta hiện nay là thức ăn bị hỏng, đúng không?",
  "We got one of those extra-large zeds on the loose, and it's a real threat.": "Chúng ta có một con zed cỡ lớn đang lởn vởn ngoài kia, và nó là một mối đe dọa thực sự đấy.",
  "%d Zombies Killed (Roadkill Doesn't Count)": "%d Zombie Đã Bị Tiêu Diệt (Tông Xe Không Tính)",
  "Details": "Chi tiết",
  "Yeah, I got you a pony. But then it tried to eat me, so I shot it in the head.": "Ừ, tôi có mang về cho cậu một con ngựa con đấy. Nhưng rồi nó cố ăn thịt tôi, nên tôi đã bắn vỡ sọ nó rồi.",
  "Watch the rear for zombies.": "Chú ý phía sau coi chừng zombie.",
  "Accelerate": "Tăng Tốc",
  "Might want to take a detour.": "Có lẽ nên đi đường vòng.",
  "Sounds like they're having some trouble with infestations in Marshall.": "Có vẻ như họ đang gặp rắc rối với các Ổ dịch (Infestations) ở Marshall.",
  "No, I will not \"lay off the doom and gloom.\" I'm just being a realist. -%1$s": "Không, tôi sẽ không \"bớt bi quan đi đâu.\" Tôi chỉ đang thực tế thôi. -%1$s",
  "Army Activity": "Hoạt Động Của Quân Đội",
  "I told you jerks to give me a gun!": "Tôi đã bảo mấy gã ngốc các cậu đưa súng cho tôi cơ mà!",
  "ATTITUDE: Panic": "THÁI ĐỘ: Hoảng Loạn",
  "Janet": "Janet",
  "+13%": "+13%",
  "Area's secure, no zeds here.": "Khu vực đã an toàn, không có zed ở đây.",
  "Needs help.": "Cần giúp đỡ.",
  "Haugen": "Haugen",
  "His name is Ed.": "Anh ấy tên là Ed.",
  "Bonus XP from Eagle-Eyed!": "Thêm XP nhờ đặc điểm Mắt Tinh Như Cú (Eagle-Eyed)!",
  "Ken": "Ken",
  "Has anybody seen %1$s? They haven't checked in since they headed out on that trade run... oops. I wasn't supposed to mention that. - %2$s": "Có ai thấy %1$s đâu không? Họ chưa báo cáo lại kể từ khi lên đường đi giao dịch... ôi. Đáng nhẽ tôi không nên nhắc tới chuyện đó. - %2$s",
  "Is everybody sick or what? Our med supply is pitiful.": "Tất cả mọi người đều ốm hay sao vậy? Nguồn cung cấp thuốc men của chúng ta thật thảm hại.",
  "A little help back here!": "Phụ một tay ở phía sau coi!",
  "How many other people you think would go out there and risk their necks to rescue somebody in trouble?": "Cậu nghĩ còn bao nhiêu người khác sẵn sàng ra ngoài kia và mạo hiểm mạng sống để cứu một ai đó đang gặp rắc rối chứ?",
  "\"and he shall wipe away every tear from their eyes; and death shall be no more; neither shall there be mourning, nor crying, nor pain, any more the first things are passed away.\"": "\"Ngài sẽ lau ráo mọi giọt lệ trên mắt họ; và sự chết sẽ không còn nữa; cũng sẽ chẳng còn than khóc, kêu la, hay đau đớn nữa, vì những điều trước kia đã qua đi.\"",
  "The effects on the local ecosystem could be unprecedented.": "Những tác động đến hệ sinh thái địa phương có thể là chưa từng có.",
  "He had one objective good to go, and a whole stack of leads.": "Anh ta đã có một mục tiêu sẵn sàng, và cả một mớ manh mối.",
  "104 STORY Benjamin Winston": "104 STORY Benjamin Winston",
  "Oh yeah, motherfuckers!": "Ồ yeah, bọn khốn khiếp!",
  "Winston": "Winston",
  "Use Item": "Sử Dụng Vật Phẩm",
  "Check the barricades on the left!": "Kiểm tra các rào chắn ở bên trái đi!",
  "Look for the \"Medical Advice\" option in your radio.": "Tìm tùy chọn \"Tư vấn Y tế\" (Medical Advice) trên radio của bạn.",
  "%1$s has been acting really weird lately. Like, \"contemplating suicide\" weird. Somebody better do something. - %2$s": "Gần đây %1$s cư xử rất lạ. Kiểu lạ như \"đang tính chuyện tự tử\" vậy. Tốt nhất là ai đó nên làm gì đi. - %2$s",
  "Until we get a good storeroom, this stuff's gonna keep walking off.": "Trừ khi chúng ta có một phòng chứa đồ tử tế, nếu không mớ đồ này sẽ tiếp tục không cánh mà bay.",
  "Resolution 1600x900": "Độ phân giải 1600x900",
  "SMG: PDS": "Súng tiểu liên: PDS",
  "42 VIP Thomas Horn": "42 VIP Thomas Horn",
  "But it’s good to know ... if it ever gets too hot around here, or if the food runs out for good ... we know we’ve got a way out. Thank you for that.": "Nhưng thật tốt khi biết rằng... nếu tình hình ở đây trở nên quá căng thẳng, hay thức ăn hoàn toàn cạn kiệt... chúng ta biết rằng mình có một lối thoát. Cảm ơn cậu vì điều đó.",
  "+16%": "+16%",
  "Sadie": "Sadie",
  "The Phoenix": "Phượng Hoàng (The Phoenix)",
  "Bingo.": "Chuẩn luôn.",
  "Fishing before dawn.": "Câu cá trước bình minh.",
  "Need an Ops Center!": "Cần một Trung Tâm Tác Chiến (Ops Center)!",
  "Brayden": "Brayden",
  "Wouldn't have been so bad if we had some advance warning. We've got to get some watchtowers set up.": "Mọi chuyện đã không tệ đến vậy nếu chúng ta có chút cảnh báo trước. Chúng ta phải dựng vài cái tháp canh lên thôi.",
  "Standard, off the lot neo-muscle. Good acceleration, handling and speed. Red was the cheapest. Two seats.": "Một chiếc neo-muscle tiêu chuẩn. Khả năng tăng tốc, khả năng xử lý và tốc độ tốt. Màu đỏ là rẻ nhất. Xe hai chỗ.",
  "All right, well, if you'll excuse me, I've got to go inventory the kitchen. Again.": "Được rồi, nếu các cậu không phiền, tôi phải đi kiểm kê nhà bếp đây. Lần nữa.",
  "We're all friends here, of course, but the Judge is a mighty busy lady. You need anything, you come see me first.": "Tất cả chúng ta đều là bạn ở đây, tất nhiên rồi, nhưng Thẩm phán là một quý bà vô cùng bận rộn. Cậu cần gì thì hãy đến gặp tôi trước.",
  "I'll get right on that!": "Tôi sẽ làm ngay đây!",
  "Everywhere You Look": "Nhìn Đâu Cũng Thấy",
  "Anyways, I was finally gonna fly over there and visit him, see if maybe London was the kind of place I could live.": "Dù sao thì, cuối cùng tôi cũng định bay qua đó thăm anh ấy, xem thử London có phải là nơi tôi có thể sống được hay không.",
  "There's plenty of room on the landing pad, Black Friday. Be ready for another extraction when we have the intel. Highroad out.": "Còn nhiều chỗ trên bãi đáp, Black Friday. Hãy sẵn sàng cho một cuộc rút lui khác khi chúng ta có thông tin tình báo. Highroad kết thúc liên lạc.",
  "Man, I can't even remember the last time I had a decent night's sleep. We need to build a bunkhouse, now.": "Anh bạn, tôi thậm chí còn không nhớ lần cuối cùng mình có một giấc ngủ đàng hoàng là khi nào nữa. Chúng ta cần xây một Nhà Tập Thể (Bunkhouse), ngay bây giờ.",
  "No zombies there.": "Không có con zombie nào ở đó cả.",
  "I think I have a plan for building a kitchen. Having one clear, clean place to prepare our food will go a long way.": "Tôi nghĩ tôi có một kế hoạch để xây dựng một nhà bếp. Có một nơi rõ ràng, sạch sẽ để chuẩn bị thức ăn sẽ rất hữu ích về lâu dài.",
  "17 GENERIC Terry Larwin": "17 GENERIC Terry Larwin",
  "Quentin's about as big-hearted and generous as they come. If it were up to him, he'd hand out all the food in the store to anybody who needed it; that's just what people do in a crisis, right?": "Quentin là một người vô cùng nhân hậu và hào phóng. Nếu tùy anh ấy quyết định, anh ấy sẽ phát hết thức ăn trong cửa hàng cho bất cứ ai cần; đó là những gì mọi người làm trong khủng hoảng mà, đúng không?",
  "Shit. What about bread?": "Chết tiệt. Vậy còn bánh mì thì sao?",
  "Good enough, I can work with this.": "Đủ tốt rồi, tôi có thể làm việc với thứ này.",
  "Ed won't survive forever.": "Ed sẽ không thể sống sót mãi được đâu.",
  "Ol' Andy Pimms": "Ông già Andy Pimms",
  "We need more weapons here.": "Chúng ta cần thêm vũ khí ở đây.",
  "I always get along with my commanding officers. But for some reason, the other grunts don't seem to like me very much. Guess I'm just officer material.": "Tôi luôn hòa đồng với các sĩ quan chỉ huy của mình. Nhưng vì một lý do nào đó, những tên lính quèn khác có vẻ không thích tôi lắm. Đoán là do tôi sinh ra để làm sĩ quan.",
  "Hey, come on, you can still turn this around.": "Này, thôi nào, cậu vẫn có thể xoay chuyển tình thế mà.",
  "Gun Specialization": "Độ Thành Thạo Súng",
  "We were coming out of this field. We stopped to get our bearings, and one of 'em came out of nowhere. Must have been hiding in the bushes or something.": "Chúng tôi vừa ra khỏi cánh đồng này. Chúng tôi dừng lại để định hướng, và một con trong số đó từ đâu lao ra. Chắc hẳn nó đã trốn trong bụi rậm hay gì đó.",
  "Escort a high-value asset back to base.": "Hộ tống một Mục Tiêu Giá Trị Cao (Asset) về căn cứ.",
  "We could use a hand clearing an infestation.": "Chúng tôi có thể cần người phụ giúp dọn dẹp một Ổ dịch (Infestation).",
  "Take care.": "Bảo trọng.",
  "This latrine is a toxic disaster area. Send someone in with a hazmat suit ASAP.": "Cái nhà vệ sinh (latrine) này là một khu vực thảm họa độc hại. Cử ai đó mặc đồ bảo hộ (hazmat) vào dọn NGAY LẬP TỨC.",
  "What is it, Quentin?": "Có chuyện gì vậy, Quentin?",
  "Help! Anybody? Please help me!": "Cứu với! Có ai không? Làm ơn cứu tôi với!",
  "He practically papered our house with ... oh, crap, you don't want me. You want his notes.": "Ông ấy gần như dùng giấy để dán kín nhà chúng tôi với... ồ, khỉ thật, cô không cần tôi. Cô muốn những ghi chép của ông ấy.",
  "Upgrade to Munitions Shop": "Nâng Cấp Lên Cửa Hàng Đạn Dược (Munitions Shop)",
  "Mechanic": "Thợ Cơ Khí",
  "Alright, be ready in a minute.": "Được rồi, sẽ sẵn sàng trong một phút nữa.",
  "We're losing assets!": "Chúng ta đang đánh mất các tài sản quan trọng!",
  "We need a little extra to get this thing done.": "Chúng ta cần thêm một chút đồ để hoàn thành việc này.",
  "SICK: Gravely Ill": "BỆNH: Ốm Rất Nặng",
  "Konig": "Konig",
  "SURVIVAL TACTICS: Slaughter": "CHIẾN THUẬT SINH TỒN: Tàn Sát",
  "Hicks": "Hicks",
  "Ah, yeah, this takes me back. The open road, wind in your hair... of course, when I was younger I usually had a stacked blonde sitting next to me, but hey.": "Ah, ừ, điều này làm tôi nhớ lại quá khứ. Con đường rộng mở, gió lùa qua mái tóc... tất nhiên, hồi tôi còn trẻ, tôi thường có một em tóc vàng ngực bự ngồi cạnh cơ, nhưng thôi kệ.",
  "Had to take some meds from the stores. Twisted my ankle pretty bad out there. Sure you don't mind. - %1$s": "Tôi đã phải lấy vài viên thuốc từ kho. Bị trật mắt cá chân khá nặng ngoài đó. Chắc mọi người không phiền đâu nhỉ. - %1$s",
  "So what about you two? What are you doing up here, romantic getaway?": "Vậy còn hai người thì sao? Các cậu làm gì ở trên này vậy, đi nghỉ dưỡng lãng mạn à?",
  "We don't have time!": "Chúng ta không có thời gian đâu!",
  "Another one of our neighbors is gone. No survivors.": "Lại thêm một người hàng xóm nữa ra đi. Không có người sống sót.",
  "Just a walk in the park, baby!": "Chỉ là một buổi đi dạo trong công viên thôi cưng!",
  "Food eaten.": "Thức ăn đã được tiêu thụ.",
  "Rejoin the other survivors.": "Hội quân với những người sống sót khác.",
  "Tamm": "Tamm",
  "Heh. It's funny. Up until two weeks ago, that was the most exciting thing that ever happened to me.": "Heh. Thật nực cười. Cho đến tận hai tuần trước, đó là điều thú vị nhất từng xảy ra với tôi.",
  "You might want to go check out that Army camp. No telling how long they'll be there.": "Cậu có lẽ nên đi kiểm tra doanh trại Quân đội đó. Không biết họ sẽ ở đó bao lâu đâu."
};

const file = 'output/languages/chunks/btxt_chunk_116.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_116.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk116[r.sourceText]) {
    r.translatedText = chunk116[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 116 successfully!');
