const fs = require('fs');
const chunk110 = {
  "We're just sitting tight. We're ready when you are.": "Chúng tôi đang chờ đây. Chúng tôi đã sẵn sàng khi nào cậu sẵn sàng.",
  "Come on, up you get. Time for you to go home.": "Thôi nào, đứng dậy đi. Đến lúc cô phải về nhà rồi.",
  "I can't really put weight on it.": "Tôi không thể dồn trọng lượng lên nó được.",
  "That inbound medivac cannot wait.": "Chuyến trực thăng cứu thương đang đến không thể chờ đợi được đâu.",
  "Gates": "Cổng",
  "EXPIRED: Search and Rescue": "ĐÃ HẾT HẠN: Tìm Kiếm và Cứu Hộ",
  "Hey! HEY! What’s going on? Speak to me! Come back, please! Don’t leave me alone.": "Này! NÀY! Có chuyện gì vậy? Nói gì đi chứ! Xin hãy quay lại! Đừng bỏ tôi lại một mình.",
  "Regular Exercise": "Tập Thể Dục Thường Xuyên",
  "That'll do us for today.": "Thế là đủ cho hôm nay rồi.",
  "That feral could be a problem.": "Con feral đó có thể là một rắc rối đấy.",
  "Jonson": "Jonson",
  "Pistol: F45 Tactical": "Súng lục: F45 Tactical",
  "We were en route to the LZ ... then a huge zombie went and smashed our vehicle. The corporal is down. I've got ... half of him here. The radio half.": "Chúng tôi đang trên đường tới Điểm đáp (LZ)... thì một con zombie khổng lồ tiến đến và đập nát xe của chúng tôi. Hạ sĩ đã hy sinh. Tôi có... một nửa thi thể của anh ấy ở đây. Nửa mang theo bộ đàm.",
  "Greyhound Two defended themselves without us.": "Greyhound Two đã tự phòng vệ mà không cần chúng ta.",
  "Jaded": "Chán Nản",
  "Stacy": "Stacy",
  "Decreases the rate at which you lose Stamina in combat.": "Giảm tốc độ tiêu hao Thể lực (Stamina) trong chiến đấu.",
  "+30": "+30",
  "I've been looking at these old ham radio manuals.": "Tôi đang xem mấy cuốn sách hướng dẫn sử dụng radio nghiệp dư cũ này.",
  "This place is a death trap!": "Nơi này là một cái bẫy chết người!",
  "We should be more quiet, okay?": "Chúng ta nên giữ im lặng hơn, hiểu không?",
  "We've got next to nothing left for building projects. We're going to need more really soon.": "Chúng ta gần như không còn gì cho các dự án xây dựng. Chúng ta sẽ cần thêm rất sớm thôi.",
  "Since the outbreak, he has been tasked with maintaining some semblance of order in Trumbull County. Has access to an artillery site in the mountains nearby.": "Kể từ khi dịch bệnh bùng phát, ông ta đã được giao nhiệm vụ duy trì một phần trật tự ở Hạt Trumbull. Có quyền truy cập vào một bãi pháo binh ở dãy núi gần đó.",
  "This is bullshit! We're just trying to survive out here, you can't kill us for that!": "Thật nhảm nhí! Chúng tôi chỉ đang cố gắng sống sót ngoài này, các người không thể giết chúng tôi vì điều đó!",
  "All right! Diplomacy's over, bitches!": "Được rồi! Hết màn ngoại giao rồi, lũ khốn!",
  "Hint Duration": "Thời Gian Hiện Gợi Ý",
  "You might want to swing by and check this out.": "Cậu có thể muốn ghé qua và kiểm tra thứ này đấy.",
  "Dominguez": "Dominguez",
  "Could use a little help getting out of here.": "Cần một chút giúp đỡ để thoát khỏi đây.",
  "Samuel": "Samuel",
  "Things are getting pretty hairy out there.": "Mọi thứ ngoài đó đang trở nên khá rùng rợn đấy.",
  "We can try preserving food here.": "Chúng ta có thể thử bảo quản thức ăn ở đây.",
  "Set Up Latrine": "Thiết Lập Nhà Vệ Sinh (Latrine)",
  "What's going on in the world, Lil?": "Chuyện gì đang xảy ra trên thế giới vậy, Lil?",
  "Icelandic Coast Guard sinks Danish refugee vessel approaching shore.\r\nAll passengers lost.": "Lực lượng Tuần duyên Iceland đánh chìm tàu tị nạn của Đan Mạch đang tiến vào bờ.\r\nTất cả hành khách đều thiệt mạng.",
  "Hey, if you're in a hurry, let me know.": "Này, nếu cậu đang vội thì cứ nói cho tôi biết nhé.",
  "Tracy": "Tracy",
  "Forge": "Lò Rèn",
  "LOG: Greyhound Two": "NHẬT KÝ: Greyhound Two",
  "HOME DEFENSE: Horde Destroyed": "BẢO VỆ NHÀ: Đã Tiêu Diệt Bầy Horde",
  "Ask about Food Caches": "Hỏi về các Kho Cất Giấu Thức Ăn",
  "Currently MIA.": "Hiện đang Mất tích (MIA).",
  "We're not going to open up until it's clear.": "Chúng tôi sẽ không mở cửa cho đến khi khu vực an toàn.",
  "Failed to protect %1$s.": "Thất bại trong việc bảo vệ %1$s.",
  "He needs a doctor.": "Anh ấy cần một bác sĩ.",
  "Oh, quit your whining already. We were all thinking it. I just had the balls to say it. (Can be Insensitive.)": "Ồ, bớt cằn nhằn đi. Tất cả chúng ta đều nghĩ thế. Tôi chỉ là có gan nói ra thôi. (Có thể là Vô Tâm - Insensitive.)",
  "Collected 150 Resources at Breakdown Level 4 or Higher.": "Thu thập được 150 Tài Nguyên ở độ khó Breakdown Cấp 4 hoặc cao hơn.",
  "First Wave": "Đợt Đầu Tiên",
  "Relax, we got this one.": "Bình tĩnh đi, chúng tôi lo vụ này được.",
  "Nicknamed \"The right arm of the Free World\".": "Được mệnh danh là \"Cánh tay phải của Thế giới Tự do\".",
  "Well, the good news is the wound hasn't become necrotic. I'll keep an eye on him until the fever breaks, but I think your friend is gonna make it.": "Chà, tin tốt là vết thương không bị hoại tử. Tôi sẽ để mắt đến cậu ấy cho đến khi hạ sốt, nhưng tôi nghĩ bạn của cô sẽ qua khỏi thôi.",
  "I ain't gonna let you get me killed. So move your ass now!": "Tôi sẽ không để anh làm tôi chết lây đâu. Nên vác cái mông đi ngay đi!",
  "Had yourself quite a hurt, didn't you?": "Bị thương khá nặng phải không?",
  "Earn 500 Fame. (Breakdown Level 1 or Higher)": "Kiếm được 500 Danh Tiếng (Fame). (Ở độ khó Breakdown Cấp 1 hoặc cao hơn)",
  "There's another freak.": "Lại một con quái vật (freak) khác kìa.",
  "NOTE: Making the Rounds": "GHI CHÚ: Đi Tuần Tra",
  "Sup?": "Có chuyện gì thế?",
  "Start a Scenario at Breakdown Level 3.": "Bắt đầu một Kịch bản ở độ khó Breakdown Cấp 3.",
  "Loved Literature": "Yêu Thích Văn Học",
  "So... Alan, huh?": "Vậy... Alan sao?",
  "As long as you can pull your weight, you're welcome with us.": "Miễn là cậu làm tròn trách nhiệm của mình, cậu luôn được chào đón ở chỗ chúng tôi.",
  "EXTRACTED: Julene Horn": "ĐÃ RÚT LUI: Julene Horn",
  "Highroad, this is Black Friday. Extraction in progress. We'll see you shortly. This squad could use a break.": "Highroad, đây là Black Friday. Việc rút lui đang tiến hành. Chúng ta sẽ sớm gặp lại. Tiểu đội này cần được nghỉ ngơi đôi chút.",
  "Maddie": "Maddie",
  "Gimme a few more minutes?": "Cho tôi thêm vài phút được không?",
  "Leaderboards are not available while not signed in.": "Bảng xếp hạng không khả dụng khi chưa đăng nhập.",
  "Vienna Cho's gonna go off about this one.": "Vienna Cho sẽ nổi điên về vụ này cho xem.",
  "Fuck this shit, I'm gone!": "Kệ mẹ đống cứt này, tao chuồn đây!",
  "Feel the Burn": "Cảm Nhận Sức Nóng",
  "Huh? Oh, yeah, I'm fine. Just... y'know. Worried in general.": "Hả? Ồ, ừ, tôi ổn. Chỉ là... cậu biết đấy. Lo lắng đủ thứ.",
  "Sound Settings": "Cài Đặt Âm Thanh",
  "The Grange": "The Grange",
  "Nothing like pulling the trigger and seeing a whole pack of zombies fall down.": "Không gì tuyệt bằng việc bóp cò và nhìn cả một bầy zombie gục ngã.",
  "Got anything good?": "Có thứ gì hay ho không?",
  "Controller Invert X-Axis": "Đảo ngược Trục X của Tay cầm",
  "So do you think Cleo knows we're here? And she's sending these things to us on purpose?": "Vậy anh có nghĩ Cleo biết chúng ta đang ở đây không? Và cô ta cố tình gửi những thứ này cho chúng ta?",
  "Negative emotions lower Stamina and can lead to trouble in the community.": "Những cảm xúc tiêu cực sẽ làm giảm Thể lực (Stamina) và có thể dẫn đến rắc rối trong cộng đồng.",
  "Might be some trouble on the right.": "Có thể có chút rắc rối ở bên phải.",
  "Let's not bust our arms pattin' our own backs here.": "Khoan hãy tự đắc vội.",
  "Standby to standby, Sergeant.": "Chuẩn bị chờ lệnh, Trung sĩ.",
  "Need a Storage Facility": "Cần Một Kho Chứa (Storage Facility)",
  "Made it. Gonna look around now.": "Đến nơi rồi. Giờ sẽ nhìn quanh một chút.",
  "Really? Yeah, I'd appreciate that. Let's go.": "Thật sao? Ừ, tôi rất cảm kích. Đi thôi.",
  "I'm sorry, Eli. Goodbye.": "Tôi xin lỗi, Eli. Tạm biệt.",
  "Commanding Officer": "Sĩ Quan Chỉ Huy",
  "Hell, now I'm just happy if a can of creamed corn's only been expired a week.": "Chết tiệt, bây giờ tôi đã thấy hạnh phúc lắm rồi nếu một hộp ngô kem chỉ mới hết hạn một tuần.",
  "Okay, let me think.": "Được rồi, để tôi suy nghĩ đã.",
  "Jesus Christ, we just can't catch a break, you know? Everything seems to be going wrong.": "Lạy Chúa, chúng ta không thể nào nghỉ ngơi được, cậu hiểu không? Mọi thứ dường như đều đang diễn ra tồi tệ.",
  "I mean when it comes to long-term survival.": "Ý tôi là khi nói đến vấn đề sinh tồn lâu dài.",
  "Small game scope included at no charge!": "Đi kèm ống ngắm thú nhỏ miễn phí!",
  "%3$s is a little banged up, but it's better than the alternative. -%1$s": "%3$s hơi te tua một chút, nhưng vẫn tốt hơn là phải chịu kết cục tồi tệ kia. -%1$s",
  "You got a map? Give it here, I'll mark the spot.": "Cậu có bản đồ không? Đưa đây, tôi sẽ đánh dấu vị trí đó.",
  "UPGRADED: Refrigerated Storage": "ĐÃ NÂNG CẤP: Kho Lạnh (Refrigerated Storage)",
  "Destroy the Juggernaut": "Tiêu Diệt Juggernaut",
  "Cans": "Lon rỗng",
  "You just like hearing this baby purr, don't you?": "Cậu chỉ thích nghe cỗ máy này gầm gừ thôi phải không?",
  "Glad you stopped by. Fact is, we're never gonna last on our own. Not like you folks have.": "Rất vui vì cậu đã ghé qua. Sự thật là, chúng tôi sẽ không bao giờ tồn tại được nếu chỉ có một mình. Không như các cậu.",
  "Took the brunt of the abuse.": "Hứng chịu phần lớn đòn tấn công.",
  "No. No. What I said was \"this will cover the interest.\" You still owe us the principal, right?": "Không. Không. Những gì tôi nói là \"số này sẽ trả cho phần lãi.\" Cậu vẫn nợ chúng tôi tiền gốc, đúng chứ?",
  "Never Been Sick": "Chưa Bao Giờ Bị Ốm"
};

const file = 'output/languages/chunks/btxt_chunk_110.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_110.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk110[r.sourceText]) {
    r.translatedText = chunk110[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 110 successfully!');
