const fs = require('fs');
const chunk133 = {
  "Evade attacks as they come in.": "Né đòn khi chúng lao tới.",
  "If we put a little more work into our infirmary, we might be able to actually get ahead of it. Preventative medicine and all that.": "Nếu chúng ta đầu tư thêm một chút vào bệnh xá của mình, chúng ta có thể thực sự đi trước một bước. Y tế dự phòng và những thứ đại loại thế.",
  "Can I help?": "Tôi có thể giúp đéo?",
  "Survivor's Guilt": "Mặc Cảm Của Người Sống Sót",
  "She was supposed to be gathering supplies from here. Maybe she's still around.": "Đáng lẽ cô ấy phải đang thu thập nhu yếu phẩm ở đây. Có thể cô ấy vẫn còn quanh quẩn quanh đây.",
  "11 GENERIC Tessa Wyeth": "11 GENERIC Tessa Wyeth",
  "Oh, for fuck's sake!": "Oh, mẹ kiếp!",
  "Choose Action": "Chọn Hành Động",
  "The good stuff.": "Đồ xịn đây.",
  "Poor bastard. Well, let's see if he's got a wallet on him or something.": "Tên khốn tội nghiệp. Chà, xem thử trên người hắn có ví hay thứ gì đó không.",
  "We couldn't protect her.": "Chúng ta đã đéo thể bảo vệ cô ấy.",
  "Time to get moving, I'd say.": "Đã đến lúc phải di chuyển rồi, tôi cho là vậy.",
  "Halverson": "Halverson",
  "Oh, right. Yeah, of course, I mean, obviously.": "Ồ, đúng rồi. Vâng, tất nhiên, ý tôi là, rõ ràng rồi.",
  "Yeah, well, people are scared. It only makes sense.": "Phải, chà, mọi người đều sợ hãi. Điều đó cũng hợp lý thôi.",
  "Zombie Horde Attacking Home!": "Bầy Horde Đang Tấn Công Căn Cứ!",
  "We're getting a lot of good use out of the workspace, but if we put a little more time and effort into it, we could start doing some basic automotive repair.": "Chúng ta đang tận dụng rất tốt xưởng chế tạo, nhưng nếu bỏ thêm chút thời gian và công sức vào đó, chúng ta có thể bắt đầu thực hiện một số công việc sửa chữa ô tô cơ bản.",
  "Come on, I saw a truck just up the road. I don't think you should be walking.": "Đi nào, tôi thấy một chiếc xe tải ở ngay phía trước đường. Tôi đéo nghĩ cậu nên đi bộ đâu.",
  "There's been way too much of that lately. Come on.": "Gần đây có quá nhiều chuyện như vậy rồi. Đi thôi.",
  "Wonder if my bros made it. (Decent cook.)": "Tự hỏi liệu những người anh em của tôi có qua khỏi không. (Người nấu ăn khá ổn.)",
  "Bloater Exterminated": "Bloater Đã Bị Tiêu Diệt",
  "Oh, shit!": "Ôi, chết tiệt!",
  "Great. I'm on my way.": "Tuyệt. Tôi đang trên đường tới.",
  "Black Fever?": "Sốt Đen (Black Fever) ư?",
  "Oscar": "Oscar",
  "Upgrade to Ammunition Shop": "Nâng Cấp Lên Cửa Hàng Đạn Dược (Ammunition Shop)",
  "I've got things under control in here. You just get out there and keep them off my back.": "Tôi đã kiểm soát được tình hình ở trong này rồi. Cậu cứ ra ngoài đó và giữ cho chúng tránh xa tôi ra.",
  "This place looks nice and defensible. Long as we don't run out of supplies, we should be okay.": "Nơi này trông khá ổn và dễ phòng thủ. Chừng nào chúng ta chưa hết sạch nhu yếu phẩm, thì chúng ta sẽ ổn thôi.",
  "You can't ask me to do this!": "Cậu đéo thể yêu cầu tôi làm điều này!",
  "We may have something here for the pain, but I'm more concerned about this fever. Could be a sign of infection.": "Chúng ta có thể có thứ gì đó ở đây để giảm đau, nhưng tôi lo lắng hơn về cơn sốt này. Có thể là dấu hiệu của nhiễm trùng.",
  "Created some .45 ammunition.": "Đã chế tạo một ít đạn .45.",
  "Probably ought to lock me up somewhere. I don't want to turn in the middle of the base and start eating people.": "Chắc là nên nhốt tôi ở đâu đó. Tôi đéo muốn bị biến đổi ngay giữa căn cứ và bắt đầu ăn thịt mọi người đâu.",
  "MORALE ISSUE: Anger": "VẤN ĐỀ TINH THẦN: Tức Giận",
  "NOTE: Safe and Sound": "GHI CHÚ: Bình Yên Vô Sự",
  "Electricity at last!": "Cuối cùng cũng có điện!",
  "Has worked at the local drugstore for 30 years.": "Đã làm việc tại hiệu thuốc địa phương được 30 năm.",
  "Never felt comfortable around guns and violence.": "Chưa bao giờ cảm thấy thoải mái với súng đạn và bạo lực.",
  "SMG: Mini Uzi 22": "Tiểu liên: Mini Uzi 22",
  "Watch out, zeds on the right.": "Cẩn thận, có zed ở bên phải.",
  "Mickey and Job will meet you there.": "Mickey và Job sẽ gặp cậu ở đó.",
  "Tired": "Mệt Mỏi",
  "Quick and efficient. That was great.": "Nhanh gọn lẹ. Tuyệt lắm.",
  "That was intense! Gonna be riding this high for a while. Go team! - %1$s": "Thật căng thẳng! Cảm giác hưng phấn này sẽ còn kéo dài một lúc nữa đây. Tiến lên nào đội! - %1$s",
  "Coming home.": "Đang về nhà.",
  "You seen Job around?": "Cậu có thấy Job quanh đây đéo?",
  "Blunt Weapon": "Vũ Khí Cùn",
  "Coordinating things at home.": "Điều phối công việc ở nhà.",
  "Erik": "Erik",
  "Laila": "Laila",
  "I think it's one of these.": "Tôi nghĩ nó là một trong những thứ này.",
  "Clear Infestation": "Dọn Dẹp Ổ Dịch",
  "DANGER: Extremely Low Morale": "NGUY HIỂM: Tinh Thần Cực Kỳ Thấp",
  "Artillery strike, my position, now now now!": "Pháo binh kích nổ, ngay vị trí của tôi, bây giờ, bây giờ, ngay bây giờ!",
  "Donut Shop": "Cửa Hàng Bánh Donut",
  "That's it. I see our target.": "Nó đây rồi. Tôi thấy mục tiêu của chúng ta rồi.",
  "Hates the Military": "Ghét Quân Đội",
  "We've added a new name to the roster.": "Chúng ta vừa thêm một cái tên mới vào danh sách.",
  "%1$s committed suicide. I guess we all saw it coming, but nobody did anything to stop it. There was no note. - Lily": "%1$s đã tự sát. Tôi đoán tất cả chúng ta đều thấy trước điều đó, nhưng đéo ai làm gì để ngăn chặn nó cả. Đéo có bức thư tuyệt mệnh nào để lại. - Lily",
  "Make .50 BMG Ammo": "Chế Tạo Đạn .50 BMG",
  "Sacrifice.": "Hy sinh.",
  "Vogel": "Vogel",
  "I've got somebody here.": "Tôi đang có người ở đây.",
  "Well, I guess you're not a total dumbass.": "Chà, tôi đoán cậu đéo hoàn toàn là một thằng ngu.",
  "I think he might be delirious.": "Tôi nghĩ ông ấy có thể đang mê sảng.",
  "Jesus. This is like walking through a war zone. - %1$s": "Chúa ơi. Chuyện này giống như đi dạo qua một vùng chiến sự vậy. - %1$s",
  "Ah, negative Charlie Six, hold position.": "Ah, từ chối Charlie Six, giữ nguyên vị trí.",
  "COMPLETED: Friendly Survivors": "HOÀN THÀNH: Những Người Sống Sót Thân Thiện",
  "Didn't blow up.": "Đéo bị nổ tung.",
  "Just get me back to base to talk to my handler, all right? We'll clear this whole thing right the hell up.": "Chỉ cần đưa tôi trở lại căn cứ để nói chuyện với người quản lý của tôi, được chứ? Chúng ta sẽ làm sáng tỏ toàn bộ chuyện chết tiệt này.",
  "Barn": "Nhà Kho (Barn)",
  "Well, that sucks. Guess we walk from here.": "Chà, tệ thật đấy. Có lẽ chúng ta phải đi bộ từ đây thôi.",
  "Points": "Điểm",
  "Well, by your leave boss, can I pretty please continue my operation?": "Chà, nếu sếp cho phép, tôi có thể xin tiếp tục ca phẫu thuật của mình được đéo?",
  "Time to pound the pavement.": "Đã đến lúc phải lê bước trên đường rồi.",
  "Let's just focus on not getting eaten for now.": "Bây giờ hãy chỉ tập trung vào việc đéo bị ăn thịt đi.",
  "Artillery Marker": "Dấu Chỉ Điểm Pháo Binh",
  "There's a cell tower behind the Swine & Bovine. From up there you should be able to get a good look at the town.": "Có một tháp phát sóng di động phía sau quán Swine & Bovine. Từ trên đó cậu sẽ có cái nhìn bao quát về thị trấn.",
  "Can you make it down to Spencer's Mill? Some of us are holed up at the church.": "Cậu có thể đến Spencer's Mill đéo? Một số người trong chúng tôi đang trốn ở nhà thờ.",
  "64 GENERIC Gene Evans": "64 GENERIC Gene Evans",
  "TIP: If you relocate, you will abandon your current home.": "MẸO: Nếu bạn chuyển chỗ, bạn sẽ từ bỏ căn cứ hiện tại của mình.",
  "+200%": "+200%",
  "It's getting worse out there.": "Mọi chuyện ngoài đó đang tồi tệ đi.",
  "Don't worry about it. We'll just... borrow a car before we head home.": "Đừng lo về việc đó. Chúng ta sẽ chỉ... mượn một chiếc xe trước khi về nhà thôi.",
  "You guys need a hand?": "Mấy người có cần giúp một tay đéo?",
  "You could say that. It's…": "Có thể nói là vậy. Nó…",
  "SURVIVAL TACTICS: Daily Influence": "CHIẾN THUẬT SINH TỒN: Điểm Ảnh Hưởng (Influence) Hàng Ngày",
  "Requires FUNCTIONING JUDICIAL SYSTEM.": "Yêu cầu HỆ THỐNG TƯ PHÁP HOẠT ĐỘNG (FUNCTIONING JUDICIAL SYSTEM).",
  "I told you that guy was dead.": "Tôi đã bảo với cậu là gã đó đã chết rồi mà.",
  "Get out of there!": "Ra khỏi đó đi!",
  "A martial arts fighting stick.": "Một cây gậy võ thuật chiến đấu.",
  "Jerk": "Đồ Tồi",
  "Stirring up trouble.": "Gây rắc rối.",
  "22 MIL Spc Kenny Anders": "22 MIL Chuyên viên Kenny Anders",
  "I suppose it's possible …": "Tôi cho rằng điều đó là có thể...",
  "Requires: %1$d Materials": "Yêu cầu: %1$d Vật liệu",
  "Zombie Infestation": "Ổ Dịch Zombie",
  "A little trouble focusing. (Improves wits slowly.)": "Gặp chút khó khăn trong việc tập trung. (Cải thiện trí tuệ từ từ.)",
  "Okay, yeah, let's go.": "Được rồi, phải, đi thôi.",
  "Black Friday, we sent you in to get scientists, not random civilians.": "Black Friday, chúng tôi cử các anh vào để mang các nhà khoa học về, đéo phải là dân thường ngẫu nhiên.",
  "We managed to clear out a few of the nearby areas. It'll take them a bit longer to build up to siege levels now.": "Chúng ta đã dọn dẹp được một vài khu vực lân cận. Sẽ mất thêm một chút thời gian nữa để chúng có thể tập hợp đủ lực lượng để vây hãm."
};

const file = 'output/languages/chunks/btxt_chunk_133.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_133.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk133[r.sourceText]) {
    r.translatedText = chunk133[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 133 successfully!');
