const fs = require('fs');
const chunk204 = {
  "Gah! Jeez, where the hell'd you come from? Nearly gave me a heart attack.": "Gah! Lạy chúa (Jeez), cậu chui ra từ cái xó xỉnh đéo nào (where the hell) vậy hả? Cậu đã gần như (Nearly) khiến cho tôi bị lên cơn đau tim (heart attack) đấy.",
  "I'd appreciate some backup, if you're not busy.": "Tôi thực sự sẽ vô cùng cảm kích (appreciate) nếu như có thêm được một vài sự hỗ trợ chi viện (backup), đương nhiên là nếu như hiện tại cậu đéo quá bận rộn (busy).",
  "Sorry.": "Thành thật xin lỗi (Sorry).",
  "Guerrero": "Guerrero",
  "The trick is to squeeze the trigger, not jerk it.": "Bí quyết (trick) ở đây chính là phải bóp cò súng một cách cực kỳ đều tay (squeeze), chứ đéo phải là giật mạnh (jerk) nó.",
  "Fassbinder": "Fassbinder",
  "I don't know what to say. Not sure I would have survived out here on my own.": "Tôi thực sự đéo biết (don't know) nên nói cái đéo gì vào lúc này nữa. Đéo dám chắc chắn (Not sure) rằng liệu tôi có thể tự mình sống sót (survived) nổi ở ngoài này khi chỉ có một thân một mình (on my own) đéo nữa.",
  "We need assistance on this construction.": "Chúng tôi hiện đang rất cần phải có được sự hỗ trợ (assistance) để tiếp tục tiến hành xây dựng công trình (construction) này.",
  "If you can shoot a gun or swing a nightstick, yeah.": "Nếu như cậu hoàn toàn có thể tự mình bắn được một khẩu súng (gun) hoặc là vung vẩy được một cái dùi cui (nightstick), yeah.",
  "Death and destruction.": "Cái chết (Death) và sự hủy diệt (destruction).",
  "One of the many rentals available from Sprang Van Rental.": "Một trong số rất nhiều những chiếc xe ô tô chuyên dụng dùng để cho thuê (rentals) hiện đang có sẵn (available) từ Dịch Vụ Cho Thuê Xe Tải Sprang Van Rental.",
  "The Tragedy": "Sự Phục Thù Báo Oán (The Tragedy)",
  "Lily wants me to go climb a cell tower in town and see if I can see any place to find medicine. - %1$s": "Lily hiện đang muốn tôi đi trèo lên trên một cái tháp viễn thông (cell tower) ở trong khu vực thị trấn và đồng thời phải cẩn thận quan sát xem liệu tôi có thể tìm thấy (see) được bất kỳ một cái nơi đéo nào có thể thu thập được một chút thuốc men (medicine) hay đéo. - %1$s",
  "MISSION: Trade Opportunity (Food)": "NHIỆM VỤ (MISSION): Cơ Hội Để Giao Dịch Trao Đổi (Trade Opportunity) (Lương Thực Food)",
  "Dr. Thomas Horn is a researcher at the Danforth Institute for Progress. It sounds like some crackpot political think-tank, but the brass seems to think Dr. Horn's work could lead to some kind of cure. At this point, with entire cities in chaos, I'm willing to hope for just about anything.": "Tiến Sĩ Thomas Horn hiện đang là một nhà nghiên cứu (researcher) thuộc Học Viện Vì Sự Tiến Bộ Danforth Institute for Progress. Nghe có vẻ hoàn toàn giống hệt như là một cái tổ chức nghiên cứu chính trị (political think-tank) vô cùng điên rồ lập dị (crackpot) đéo nào đó, thế nhưng các quan chức cấp cao (brass) dường như lại luôn tin tưởng rằng chính những công trình nghiên cứu (work) của Tiến Sĩ Horn hoàn toàn có thể giúp dẫn đến (lead) một phương thuốc chữa trị (cure) hữu hiệu đéo nào đó. Ở trong cái thời điểm thảm khốc (At this point) hiện tại, với việc toàn bộ tất cả mọi thành phố đều đã rơi vào tình trạng hỗn loạn (chaos) cùng cực, tôi hoàn toàn sẵn sàng đặt niềm hy vọng (hope) vào bất cứ một cái thứ đéo gì.",
  "Not getting enough food.": "Hiện đang đéo được cung cấp đủ khẩu phần lương thực thức ăn (enough food).",
  "I think the Wilkersons are still waiting for you down at that trade meet.": "Tôi nghĩ rằng cái lũ nhà Wilkersons hiện tại vẫn đang đứng chờ đợi cậu ở bên dưới cái địa điểm giao dịch trao đổi (trade meet) đó đấy.",
  "DISCOVERED: The Courthouse": "ĐÃ KHÁM PHÁ RA (DISCOVERED): Khu Vực Tòa Án (The Courthouse)",
  "Roth": "Roth",
  "If I'd ever gotten my big break, I wouldn't have been here when everything went to hell. (Knows how to strike a pose.)": "Nếu như tôi đã từng có được cơ hội đổi đời (big break) của riêng mình, thì chắc chắn tôi sẽ đéo bao giờ (wouldn't) phải đứng ở ngay tại cái nơi này khi mà mọi thứ xung quanh đều đã hoàn toàn sụp đổ biến thành địa ngục (went to hell). (Rất am hiểu tường tận về các cách để tạo dáng strike a pose chụp ảnh.)",
  "Ready to move.": "Đã hoàn toàn sẵn sàng (Ready) để tiếp tục di chuyển (move).",
  "The RV has two flat tires, but one of them might be salvageable. It's going to take some work to get them all roadworthy ... (RV FACILITY)": "Chiếc xe RV hiện tại đang có tận hai cái lốp đã bị xịt hơi xẹp lép (flat tires), nhưng ít nhất thì một trong số chúng có vẻ như vẫn còn có thể cứu vãn (salvageable) được đôi chút. Chắc chắn sẽ phải tốn kém thêm một ít công sức (work) sửa chữa để có thể khiến cho toàn bộ bọn chúng có thể hoạt động lưu thông tốt ở trên đường bộ (roadworthy) trở lại... (CƠ SỞ RV FACILITY)",
  "Girard": "Girard",
  "Kaiser": "Kaiser",
  "32 GENERIC Sam Wenderly": "32 CHUNG (GENERIC) Sam Wenderly",
  "And then should I standby some more?": "Và sau đó thì liệu tôi có nên tiếp tục đứng chờ đợi chờ (standby) thêm một lúc lâu nữa hay đéo?",
  "Heads up, zeds on your six!": "Hãy mau cẩn thận (Heads up), bọn zeds đang tiến đến từ hướng sáu giờ (on your six) của cậu kìa!",
  "Requires MARTINI LUNCH.": "Yêu cầu (Requires) cần phải có CHUYẾN ĂN TRƯA CÙNG VỚI RƯỢU MARTINI (MARTINI LUNCH).",
  "Need a LEGIT WORKSHOP": "Cần phải có một KHU XƯỞNG LÀM VIỆC CHÍNH THỨC (LEGIT WORKSHOP)",
  "145 STORY Sam Hoffman": "145 CỐT TRUYỆN (STORY) Sam Hoffman",
  "I've waited my whole life for this moment. My katana is sharp, my .50 caliber is fully loaded, and my trench coat is freshly dry-cleaned. Time to kill some zombies.": "Tôi đã phải chờ đợi ở trong suốt cả phần đời (whole life) của mình chỉ để được trải nghiệm cái khoảnh khắc (moment) đáng nhớ này. Thanh kiếm katana của tôi đã được mài dũa vô cùng vô cùng sắc bén (sharp), khẩu súng bắn tỉa nòng cỡ .50 caliber của tôi cũng đã được nạp đạn đầy đủ (fully loaded), và chiếc áo khoác măng tô (trench coat) của tôi cũng vừa mới được giặt khô sạch sẽ (freshly dry-cleaned). Đã đến lúc phải đi tàn sát (kill) một lũ zombies cmnr.",
  "Yeah, okay.": "Yeah, okay.",
  "Cancel": "Hủy Bỏ (Cancel)",
  "Hailey": "Hailey",
  "Zombies on our six. Stay alert.": "Có bọn Zombies đang kéo đến từ hướng sáu giờ (on our six). Hãy luôn giữ vững sự tỉnh táo cảnh giác cao độ (Stay alert) nhé.",
  "We can't ignore that.": "Chúng ta hoàn toàn đéo thể nào có thể dễ dàng phớt lờ làm ngơ (ignore) trước cái điều đó được.",
  "Regaining Ground": "Giành Lại (Regaining) Được Phần Lãnh Thổ Khu Vực (Ground)",
  "Jacob's right. It might be time to start looking elsewhere.": "Jacob đã hoàn toàn nói đúng. Có lẽ bây giờ đã đến lúc chúng ta cần phải bắt đầu (start) đi tìm kiếm ở những khu vực địa điểm khác (elsewhere) rồi đấy.",
  "Help Sasquatch hunt a Bloater": "Trợ Giúp Cho Sasquatch đi săn lùng (hunt) một con Bloater",
  "Rifle: SKS": "Súng Trường (Rifle): SKS",
  "A workshop to focus on creating ammunition.": "Một khu vực xưởng làm việc (workshop) luôn chú trọng tập trung (focus) tối đa vào việc tiến hành sản xuất và chế tạo ra các loại đạn dược vũ khí (ammunition).",
  "Our outpost took out an incoming horde. - %1$s": "Khu vực tiền đồn (outpost) của chúng ta vừa mới tiêu diệt toàn bộ (took out) một bầy đàn zombie (horde) đang ùn ùn kéo đến. - %1$s",
  "Excuse me? Virus?": "Xin thứ lỗi cho (Excuse me)? Chủng loại Vi-rút (Virus) đéo nào cơ?",
  "There's a good storage space here. Just need to clear out all the chaos and we can start using it.": "Hiện đang có một khoảng không gian (space) trống trải dùng để làm nhà kho lưu trữ (storage) đồ đạc cực kỳ tuyệt vời ở ngay tại cái khu vực này. Chỉ việc dọn dẹp sạch sẽ (clear out) đi tất cả mọi cái đống hỗn độn (chaos) và chúng ta sẽ hoàn toàn có thể bắt đầu tiến hành sử dụng (using) nó ngay lập tức.",
  "You have a new Home! Press D-pad [xi_dpad_up] to open your Journal and view your Stockpiles and Possessions on the Assets page.": "Bạn vừa mới sở hữu được một Khu Vực Căn Cứ Ngôi Nhà (Home) hoàn toàn mới! Hãy nhấn cụm phím điều hướng (D-pad) [xi_dpad_up] để có thể mở Cuốn Sổ Nhật Ký (Journal) của bạn lên và tiến hành quan sát thông tin chi tiết về các Kho Hàng Dự Trữ (Stockpiles) cũng như là các loại Tài Sản Sở Hữu (Possessions) đang nằm ở trong mục trang Tài Sản (Assets).",
  "Overbearing.": "Một người độc đoán và vô cùng hách dịch (Overbearing).",
  "Would you like to proceed?": "Bạn có chắc chắn muốn được tiếp tục tiến hành thực hiện (proceed) hay đéo?",
  "Just keep them off me a little longer.": "Chỉ việc cố gắng xua đuổi cản bước (keep them off) bọn chúng tránh xa khỏi tôi ra thêm một khoảng thời gian ngắn (a little longer) nữa đéo.",
  "Shit! Looks like trouble.": "Chết tiệt thật (Shit)! Trông có vẻ như đang có rắc rối (trouble) lớn ập đến cmnr.",
  "Sullivan": "Sullivan",
  "Shove": "Xô Đẩy Mạnh (Shove)",
  "A stroll through the zombie apocalypse": "Cùng nhau đi dạo bộ (A stroll) thư giãn thong thả băng qua (through) ngày tận thế zombie (zombie apocalypse)",
  "Timothy Hall died during our attempt to rescue him. I can't help but think that there might have been something else I could have done. I'll report it to Connors.": "Timothy Hall đã phải đánh đổi bằng cả mạng sống của mình (died) ngay trong lúc chúng tôi đang vô cùng nỗ lực (attempt) cố gắng để tiến hành giải cứu (rescue) cho anh ấy. Tôi hoàn toàn đéo thể nào (can't help) có thể ngừng suy nghĩ về cái việc rằng đáng lẽ ra đã có thể có một cái thứ đéo gì đó khác (something else) mà tôi đã có thể dễ dàng làm được. Tôi chắc chắn sẽ báo cáo lại toàn bộ (report) cái sự việc thảm khốc này cho Connors được biết.",
  "Doctor Horn was a research scientist whose work might have been able to help us fight this outbreak. Now he's dead.": "Bác Sĩ Horn đã từng là một nhà khoa học nghiên cứu (research scientist) mà những công trình nghiên cứu (work) của ông ta chắc chắn đã có thể dễ dàng giúp đỡ (help) được cho chúng ta rất nhiều ở trong công cuộc chiến đấu (fight) chống lại (fight) cái thảm họa đại dịch bùng phát (outbreak) chết tiệt này. Giờ đây thì ông ta đã chết cmnr (dead).",
  "Are you crazy? We can't go back out there! Those things'll eat us alive!": "Cậu có bị điên (crazy) đéo hả? Chúng ta tuyệt đối đéo thể nào (can't) có thể quay trở lại cái nơi khốn khiếp ở ngoài đó đéo đâu! Những cái thứ quái thai tởm lợm (things) đó chắc chắn sẽ nhai nuốt và ăn thịt chúng ta (eat us) một cách sống sờ sờ (alive) mất!",
  "Pistol: G 31": "Súng Lục (Pistol): G 31",
  "These aren't smart bombs; we can't put shells through windows.": "Bọn chúng hoàn toàn đéo phải là những quả bom thông minh (smart bombs) có thể dễ dàng định hướng đéo đâu; chúng ta đéo thể nào có thể tự do ném thẳng (put) những vỏ đạn pháo (shells) đó xuyên qua những khung cửa sổ (windows) được đâu.",
  "RUMOR: Neighbor Dead": "TIN ĐỒN (RUMOR): Một Người Hàng Xóm (Neighbor) Nào Đó Đã Chết (Dead)",
  "You know what they say about butterflies and bees, right?": "Cậu có biết rõ cái câu mà người ta vẫn thường hay hay nói về những loài bướm (butterflies) và những con ong (bees) đéo, đúng đéo?",
  "Polanco": "Polanco",
  "Me? Don't be silly, I'm perfectly fine. No, I don't know why %2$s said they heard me sobbing last night. Maybe it was somebody else? - %1$s": "Tôi á ư (Me)? Thôi đừng có nói mấy lời quá ngốc nghếch (silly) như thế chứ, tôi vẫn hoàn toàn cực kỳ khỏe mạnh (perfectly fine). Đéo, tôi hoàn toàn đéo thể nào hiểu được lý do tại sao %2$s lại dám nói rằng họ đã tình cờ nghe thấy tiếng tôi khóc nức nở (sobbing) vào đêm ngày hôm qua (last night). Có lẽ là do một ai đó khác (somebody else) chăng? - %1$s",
  "Hopefully it's just a cold and not something worse. We should look into upgrading our medical facilities.": "Rất hy vọng (Hopefully) rằng đó chỉ là một căn bệnh cảm lạnh (cold) thông thường chứ đéo phải là một thứ đéo gì đó tồi tệ hơn (worse). Chúng ta nên bắt đầu tìm cách (look into) nâng cấp (upgrading) toàn bộ các cơ sở (facilities) trang thiết bị y tế (medical) của chúng ta ngay thôi.",
  "Dr. Horn has provided us with materials that may help to reconstruct her ex-husband's research.\r\nRescued with %1$s, a colleague at University Medical.": "Bác Sĩ Horn đã cung cấp (provided) cho chúng ta rất nhiều những nguồn tài liệu (materials) vô cùng quý giá mà chắc chắn có thể sẽ giúp ích được rất nhiều trong việc phục dựng (reconstruct) lại toàn bộ công trình nghiên cứu (research) của người chồng cũ (ex-husband) của cô ấy.\r\nĐã được giải cứu (Rescued) thành công cùng với %1$s, một người đồng nghiệp (colleague) đang làm việc tại Trường Đại Học Y Khoa (University Medical).",
  "Now that you have a Field Workshop, you can repair damaged weapons at any Supply Locker.": "Bởi vì bây giờ bạn đã sở hữu một Khu Vực Xưởng Làm Việc Dã Chiến (Field Workshop), nên bạn hoàn toàn có thể tự mình sửa chữa (repair) các loại vũ khí bị hư hỏng (damaged) tại bất kỳ một chiếc Tủ Đồ Tiếp Tế (Supply Locker) nào.",
  "Kilo was killed.": "Kilo đã bị giết chết (killed) cmnr.",
  "HUNGRY: Malnourished": "ĐANG VÔ CÙNG ĐÓI BỤNG (HUNGRY): Tình Trạng Bị Suy Dinh Dưỡng Thiếu Chất Trầm Trọng (Malnourished)",
  "Local administrator for the Human Future Fund. May have received documents from Thomas Horn. Seems to think she should be arrested.": "Một nhà quản lý hành chính (administrator) địa phương chuyên làm việc cho cái Quỹ Tài Trợ Tương Lai Của Nhân Loại (Human Future Fund). Có vẻ như là đã từng nhận được (received) một vài bộ tài liệu (documents) tuyệt mật từ Thomas Horn. Dường như luôn suy nghĩ cho rằng bản thân mình đáng lẽ ra đã nên bị bắt giữ (arrested).",
  "67 RAD Col Gregory Peel": "67 NHÀ ĐÀI PHÁT THANH TRUYỀN HÌNH ĐỊA PHƯƠNG (RAD) Đại Tá (Col) Gregory Peel",
  "Price": "Price",
  "Kill 100 Zombies with Blades. (Breakdown Level 2 or Higher)": "Tiến hành Tiêu Diệt Hạ Gục (Kill) Lên Đến 100 Con Zombies bằng cách sử dụng các loại vũ khí sắc bén (Blades). (Cấp Độ Breakdown Level 2 hoặc là Cao Hơn Higher)",
  "43 VIP Julene Horn": "43 NHÂN VẬT QUAN TRỌNG (VIP) Julene Horn",
  "Insufficient materials": "Đéo có đủ các nguyên liệu vật tư (Insufficient materials)",
  "COMPLETED: Under Attack": "ĐÃ HOÀN THÀNH (COMPLETED): Đang Bị Tấn Công (Under Attack)",
  "Tammy": "Tammy",
  "Man, I'd like to see zed fuck with us now. They're all, \"Raaaaarrrr, eat your brains!\" and I'm all like \"POW! Now there's a bullet in your face, bitch!\"": "Ông anh ạ, hiện tại tôi cực kỳ mong muốn (like to see) lũ zed khốn nạn chết tiệt đó dám mò đến để gây rắc rối (fuck với us) với chúng ta đấy. Tất cả bọn chúng sẽ đều như kiểu, \"Raaaaarrrr, ta sẽ ăn tươi nuốt sống bộ não não (brains) của mi!\" và tôi thì lại hoàn toàn như kiểu \"POW! Nhận lấy một viên đạn (bullet) găm thẳng vào giữa cái bản mặt (face) tởm lợm của mày đi này, con chó đẻ (bitch)!\"",
  "Depression": "Sự Trầm Cảm (Depression) U Sầu Cực Độ",
  "TIP: Surveying adds buildings and other points of interest to your map.": "MẸO (TIP): Việc đi khảo sát đo đạc (Surveying) liên tục sẽ giúp bạn dễ dàng bổ sung (adds) thêm được rất nhiều những tòa nhà (buildings) và các địa điểm vô cùng thú vị đáng chú ý (points of interest) khác trực tiếp vào bản đồ (map) của bạn.",
  "Plenty of food? So, you know how long all this is going to last, huh? We got enough food for a month? Sure. A year? Maybe. Two years? Ten? Don't talk to me about \"plenty of food.\"": "Dư thừa (Plenty) lương thực thức ăn (food) ư? Thế hóa ra, cậu biết rất rõ rằng toàn bộ tất cả mọi chuyện sẽ còn kéo dài (last) thêm trong bao lâu nữa cơ đấy, huh? Rằng chúng đang có đủ thức ăn để có thể sống sót cho đến hết một tháng ư? Đương nhiên (Sure). Một năm ư? Có lẽ là vậy (Maybe). Hai năm ư? Hay là Mười năm ư? Thế nên đừng bao giờ mở mồm ra để nói (Don't talk) với tôi về cái thứ gọi là \"lương thực thức ăn (food) dư thừa (plenty)\" đéo nhé.",
  "Zed gets to go hungry tonight.": "Lũ Zed chắc chắn sẽ lại phải chịu cảnh nhịn đói (hungry) vào đêm nay rồi.",
  "Jordan": "Jordan",
  "That's right, Mickey. So why don't we put our friend here to work?": "Hoàn toàn chính xác đấy (That's right), Mickey. Vậy thì tại sao (why don't) chúng ta đéo tiến hành giao việc (put) cho người bạn (friend) của chúng ta ở ngay đây để cậu ta có thể tự mình chứng minh nhỉ?",
  "Heads-up, everyone. We've got a horde coming in again.": "Cẩn thận coi chừng (Heads-up), mọi người. Hiện đang có thêm một bầy đàn zombie (horde) chuẩn bị kéo tới (coming in) nữa rồi kìa.",
  "Hole in my fucking rucksack.": "Có một cái lỗ thủng (Hole) rất to ở ngay trên cái chiếc balo (rucksack) khốn khiếp chết tiệt (fucking) của tôi cmnr.",
  "You need to wait a bit before doing this again.": "Bạn rất cần phải chờ đợi (wait) thêm một chút thời gian nữa (a bit) trước khi (before) có thể tiến hành thực hiện lại cái hành động chết tiệt này (doing this again) thêm một lần nữa.",
  "Greenhouse available for construction.": "Khu Nhà Kính (Greenhouse) hiện đã sẵn sàng (available) để có thể được tiến hành xây dựng (construction).",
  "Alan's doing much better.": "Tình trạng hiện tại của Alan đang dần trở nên tốt hơn (better) rất nhiều cmnr.",
  "Firefighter's Universal Tool": "Công Cụ Dụng Cụ Đa Năng Hoàn Vũ (Universal Tool) Của Lính Cứu Hỏa (Firefighter)",
  "Someone would have been sick by now without it.": "Chắc chắn là đã có một người nào đó bị đổ bệnh nặng (sick) ngay từ lúc nãy (by now) cmnr nếu như đéo có nó.",
  "COMPLETED: An Elevated Perspective": "ĐÃ HOÀN THÀNH (COMPLETED): Một Góc Nhìn (Perspective) Vô Cùng Cao Cả Tuyệt Vời (Elevated)",
  "Uses some insane chemistry to generate a box of incendiary shotgun ammunition. For Incendiary Shotguns ONLY.": "Tiến hành sử dụng (Uses) một vài loại phản ứng hóa học (chemistry) vô cùng điên rồ và cực kỳ nguy hiểm (insane) để có thể tạo ra (generate) được một hộp đạn chứa toàn đạn cháy (incendiary ammunition) chuyên dụng dành riêng cho súng shotgun. CHỈ (ONLY) được sử dụng dành riêng cho các loại Súng Shotgun Chuyên Bắn Đạn Cháy (Incendiary Shotguns).",
  "Never misses a chance to get in a shot at somebody.": "Chưa bao giờ (Never) chịu đánh mất đi một cơ hội (chance) nào chỉ để được giơ súng lên ngắm bắn thẳng vào đầu (get in a shot) của một kẻ đéo nào đó (somebody).",
  "Deep Lacerations": "Những Vết Rách Cắt Sâu (Deep Lacerations)",
  "Wow, really? Wow, that's... Thank you.": "Wow, cậu nói thật (really) đéo vậy? Wow, thứ đó quả thật là... Vô cùng cảm ơn (Thank you) cậu nhé.",
  "Hold up here. Looks like trouble ahead.": "Hãy khoan (Hold up) hẵng tiến tới chỗ đó. Trông có vẻ như đang có rắc rối (trouble) lớn ở phía trước (ahead) đấy.",
  "START MISSION. You'll be given half the goods after you provide an escort.": "BẮT ĐẦU (START) LÀM NHIỆM VỤ (MISSION). Bạn sẽ được chia phần cho (given) một nửa (half) số lượng hàng hóa (goods) ngay sau khi (after) bạn đồng ý cung cấp (provide) một sự hộ tống bảo vệ an toàn (escort).",
  "Aw, shit! Gimme a hand?": "Aw, chết tiệt thật (shit)! Có thể giúp tôi một tay (Gimme a hand) được đéo?",
  "Hey, come with me, okay? You need to get out of your own head for a little while.": "Này, hãy đi theo (come with) tôi, okay? Cậu đang rất cần phải được thoát ra khỏi (get out) cái mớ suy nghĩ chết tiệt ở trong chính cái đầu (head) của mình một lát (little while) đấy.",
  "Door Attack": "Tấn Công Xông Thẳng Vào Cửa (Door Attack)",
  "MEDICINE RESOURCE. Just the essentials.": "TÀI NGUYÊN (RESOURCE) THUỐC MEN Y TẾ (MEDICINE). Chỉ hoàn toàn là những thứ thuốc vô cùng thiết yếu (essentials) mà thôi.",
  "Panic": "Tình Trạng Hoảng Loạn Cùng Cực (Panic)"
};

const file = 'output/languages/chunks/btxt_chunk_204.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_204.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk204[r.sourceText]) {
    r.translatedText = chunk204[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 204 successfully!');
