const fs = require('fs');
const chunk182 = {
  "Ito": "Ito",
  "You were saying?": "Cậu vừa nói gì cơ?",
  "Knows a lot about construction.": "Hiểu biết rất nhiều về lĩnh vực xây dựng (construction).",
  "One of those psychos tried to bite me, but yeah. Yeah. I'm fine.": "Một trong những thằng điên đó đã cố cắn tôi, nhưng đúng thế. Ừ. Tôi đéo sao.",
  "The pilot dropped off some extra fuel that he scavenged from HQ. Should help us hold out for a bit longer.": "Phi công đã thả xuống thêm một ít nhiên liệu mà anh ta thu thập được từ Trụ sở (HQ). Chắc là sẽ giúp chúng ta cầm cự được thêm một khoảng thời gian nữa.",
  "Wrench": "Cờ Lê (Wrench)",
  "Nobody wants to be the first to say it, but things are not going well around here. - %1$s": "Đéo ai muốn trở thành người đầu tiên nói ra điều này cả, nhưng mọi chuyện ở quanh đây đang diễn biến đéo được tốt cho lắm. - %1$s",
  "I just heard about something interesting.": "Tôi vừa mới nghe được một chuyện khá thú vị.",
  "Clean facilities for the disposal of human waste.": "Cơ sở vật chất sạch sẽ dùng cho việc xử lý chất thải của con người.",
  "I used to pass that place on my way to school all the time. It seems nice.": "Tôi từng thường xuyên đi ngang qua chỗ đó trên đường đến trường. Trông nó có vẻ khá là đẹp.",
  "This thing... black fever I guess they're calling it? It's bad. I mean, it's really bad.": "Cái thứ này... black fever (sốt đen) tôi đoán là bọn họ đang gọi nó như vậy? Nó rất tệ. Ý tôi là, nó thực sự rất tồi tệ.",
  "This isn't good.": "Chuyện này đéo tốt chút nào.",
  "Kiss my ass, Alan! Lily needs these meds.": "Hôn mông tôi đi (Kiss my ass), Alan! Lily cần những viên thuốc này.",
  "Shoulda been on a flight to visit my folks, but my mom, she's got this medical marijuana prescription, right?": "Đáng lẽ ra tôi phải lên một chuyến bay để đến thăm bố mẹ, nhưng mẹ tôi, bà ấy có cái đơn thuốc cần dùng cần sa y tế (medical marijuana) này, hiểu đéo?",
  "Manage your Home via your Journal. Here you can see the status of all your community members, including their Vitality, Stamina, inventory, skills, current condition, and interesting character traits. Earning the friendship of other survivors unlocks the ability to play as them. Help ensure your long-term survival by scavenging supplies, rescuing more survivors to join your community, and building facilities that enable you to create your own resources. Every base has a unique combination of built-in facilities as well as space to build your own. Feeling cramped? Need room to grow? Seek out new locations that offer the protection and space your community needs to expand. Keep an eye on your stockpiles as the strength of your supplies directly impacts your community's morale. Low morale paves the way to negative consequences.": "Quản lý Căn Cứ (Home) của bạn thông qua Nhật Ký (Journal). Tại đây, bạn có thể xem trạng thái của tất cả các thành viên trong cộng đồng của mình, bao gồm Sinh Lực (Vitality), Thể Lực (Stamina), đồ đạc trong kho, kỹ năng (skills), tình trạng sức khỏe hiện tại, và các đặc điểm tính cách thú vị của họ. Đạt được tình bạn của những người sống sót khác sẽ mở khóa khả năng để điều khiển họ. Giúp đảm bảo khả năng sinh tồn lâu dài của bạn bằng cách thu thập đồ tiếp tế, giải cứu thêm nhiều người sống sót khác gia nhập vào cộng đồng, và xây dựng các cơ sở tiện ích cho phép bạn tạo ra các nguồn tài nguyên của riêng mình. Mỗi căn cứ đều có một sự kết hợp độc đáo của các cơ sở vật chất được xây dựng sẵn cũng như không gian để tự bạn xây thêm. Cảm thấy chật chội? Cần thêm không gian để phát triển? Hãy tìm kiếm những địa điểm mới có thể cung cấp sự bảo vệ và không gian cần thiết để cộng đồng của bạn mở rộng. Hãy chú ý đến kho dự trữ của bạn vì lượng đồ tiếp tế (supplies) sẽ trực tiếp ảnh hưởng đến tinh thần (morale) của cộng đồng. Tinh thần xuống thấp sẽ dọn đường cho những hậu quả tiêu cực.",
  "Incendiary Barrage (Use Mortar Marker)": "Đợt Pháo Kích Đạn Cháy (Incendiary Barrage - Sử dụng Thiết Bị Chỉ Thị Mục Tiêu Mortar Marker)",
  "Outstanding success!": "Thành công ngoài sự mong đợi (Outstanding)!",
  "ASSET PROFILE: Michele Martin": "HỒ SƠ TÀI SẢN MỤC TIÊU (ASSET PROFILE): Michele Martin",
  "Heads up. Zombie-fuckin-central there.": "Chú ý nào. Cả một trung tâm đẫm lũ zombie khốn khiếp ở đằng kia kìa.",
  "Heavy Weapons": "Vũ Khí Hạng Nặng (Heavy Weapons)",
  "MISSION: An Elevated Perspective": "NHIỆM VỤ: Một Góc Nhìn Từ Trên Cao (An Elevated Perspective)",
  "Well, go ahead. Lead the way.": "Chà, cứ tự nhiên đi. Dẫn đường đi nào.",
  "So good...": "Thật tuyệt vời...",
  "We've almost got more trade offers than we can deal with.": "Chúng ta gần như đã nhận được nhiều lời đề nghị giao dịch (trade offers) hơn mức mà chúng ta có thể giải quyết được.",
  "DECLINE MISSION. Prevent the trade from happening. This'll cost you some Influence.": "TỪ CHỐI NHIỆM VỤ. Ngăn chặn cuộc giao dịch (trade) diễn ra. Việc này sẽ làm tiêu tốn của bạn một lượng Điểm Ảnh Hưởng (Influence).",
  "It's nice to see medical treatment work out. Everyone's breathing a sigh of relief. - %1$s": "Thật tuyệt khi thấy việc điều trị y tế (medical treatment) đang phát huy tác dụng. Mọi người đều đang thở phào nhẹ nhõm. - %1$s",
  "I'm gonna see if I can't get a high-level view of things.": "Tôi sẽ đi xem thử liệu mình có thể có được một cái nhìn bao quát về mọi thứ từ trên cao hay đéo.",
  "Maybe slow down a bit so we don't draw the zeds?": "Có lẽ nên chậm lại một chút để chúng ta đéo thu hút sự chú ý của bọn zeds chứ?",
  "Jacob? Jacob, come in.": "Jacob? Jacob, nghe rõ trả lời (come in).",
  "Zombies Killed": "Số Zombies Bị Tiêu Diệt",
  "WORK FOR HIRE": "CÔNG VIỆC LÀM THUÊ (WORK FOR HIRE)",
  "Batter up, bitches!": "Vung gậy lên nào, mấy con chó đẻ!",
  "Fall back, fall back!": "Rút lui, rút lui ngay!",
  "And who the hell put you in charge?": "Và ai là kẻ chết dẫm đã giao cho cậu quyền chỉ huy cơ chứ?",
  "All right, it's close. Remember, blades only. We need this kill to be clean.": "Được rồi, nó đang đến gần rồi. Hãy nhớ lấy, chỉ sử dụng vũ khí dạng lưỡi cắt (blades) thôi. Chúng Phần tử này tiêu diệt gọn gàng mục tiêu này (clean kill).",
  "Evolutionary step in pump action shotguns.": "Một bước tiến hóa vượt bậc trong dòng súng shotgun nạp đạn kiểu bơm (pump action).",
  "Aisha": "Aisha",
  "SURVIVAL TACTICS: Ammo Storage": "CHIẾN THUẬT SINH TỒN (TACTICS): Dự Trữ Đạn Dược (Ammo Storage)",
  "Medicine supplies dwindling.": "Nguồn cung cấp thuốc men (medicine) đang dần bị cạn kiệt.",
  "We have a new commanding officer. Hopefully, they'll do a better job of staying alive than the last one. Check the Ops Center to see what the Major is capable of.": "Chúng ta đã có một vị sĩ quan chỉ huy mới. Hy vọng rằng, họ sẽ làm tốt công việc giữ cho bản thân sống sót hơn người tiền nhiệm. Hãy kiểm tra Trung Tâm Tác Chiến (Ops Center) để xem vị Thiếu Tá này có khả năng làm được những gì.",
  "I know we wanted to make some improvements, but we're missing a few things.": "Tôi biết là chúng ta đang muốn thực hiện một số cải tiến (improvements), nhưng chúng ta lại đang bị thiếu một vài thứ.",
  "31 GENERIC Mike Rassle": "31 CHUNG (GENERIC) Mike Rassle",
  "All right, that's it. Everything else is either missing or with Doctor Horn.": "Được rồi, thế là xong. Tất cả mọi thứ khác đều đã bị mất tích hoặc là đang nằm trong tay Bác sĩ Horn.",
  "We could use some backup if you can make it home.": "Chúng tôi có thể cần thêm chi viện nếu như cậu có thể về đến nhà an toàn.",
  "Choose When to Leave the Valley": "Tùy Chọn Thời Điểm Rời Khỏi Thung Lũng",
  "Swartz": "Swartz",
  "Research Hospital": "Bệnh Viện Nghiên Cứu (Research Hospital)",
  "Magnuson": "Magnuson",
  "New bullpup from Israel. Compact, accurate and reliable.": "Một mẫu súng bullpup mới đến từ Israel. Nhỏ gọn, chính xác và đáng tin cậy.",
  "Call in a favor to get a team of mercenaries to cover you from a nearby rooftop.": "Sử dụng một đặc quyền (favor) để triệu tập một đội lính đánh thuê bắn yểm trợ cho bạn từ một sân thượng gần đó.",
  "I'm not moving until I'm convinced it's safe to go.": "Tôi sẽ đéo di chuyển cho đến khi nào tôi hoàn toàn bị thuyết phục rằng việc đi lại đã an toàn.",
  "Castillo": "Castillo",
  "THE WALL": "BỨC TƯỜNG (THE WALL)",
  "Doghouse to Greyhound One. Julene Horn is dead due to your utter incompetence.": "Doghouse gọi Greyhound One. Julene Horn đã chết là do sự kém cỏi hoàn toàn của các anh.",
  "Found a small stash of %s": "Đã tìm thấy một kho chứa nhỏ của %s",
  "Bunch of dumbasses. What the hell'd they think was gonna happen?": "Đúng là một đám ngu xuẩn. Bọn họ đã nghĩ cái quái gì sẽ xảy ra cơ chứ?",
  "Takes years of experience or a good botanical education to really understand plants like this. It's not something you pick up in a day or two.": "Đòi hỏi phải có nhiều năm kinh nghiệm hoặc một nền tảng giáo dục tốt về thực vật học mới có thể thực sự hiểu được các loại cây trồng như thế này. Đó đéo phải là thứ mà cậu có thể học lỏm được chỉ trong một hay hai ngày đâu.",
  "She was supposed to be gathering supplies from here. Maybe she's still inside.": "Đáng lý ra cô ấy phải đang thu thập đồ tiếp tế từ chỗ này. Có thể là cô ấy vẫn còn ở bên trong.",
  "What did those soldiers want, anyways?": "Dù sao thì những người lính đó đang muốn gì vậy?",
  "You got zeds, dead ahead!": "Cậu có bọn zeds kìa, ngay phía trước mặt!",
  "With so many cars in one place, it's no surprise that someone'd take one out for a ride.": "Với quá nhiều xe ô tô ở cùng một chỗ như vậy, cũng đéo có gì đáng ngạc nhiên khi có ai đó lấy ra một chiếc để lái đi dạo.",
  "Search for the Armored Zombies": "Tìm kiếm bọn Armored Zombies",
  "Marcus": "Marcus",
  "Yeah. I heard a few of their goons hit up the gas station outside town, found a couple survivors holed up there.": "Ừ. Tôi nghe nói một vài tên tay sai của chúng đã tấn công vào trạm xăng (gas station) ở ngoại ô thị trấn, phát hiện ra có một vài người sống sót đang ẩn náu ở đó.",
  "Hey, let's not get caught up in pointing fingers, right?": "Này, chúng ta đừng có bị cuốn vào cái trò chỉ trích đổ lỗi cho nhau, được đéo?",
  "PERSONAL SKILL. If you play your cards right, you may get hired to write the skill-description blurbs for an awesome video game.": "KỸ NĂNG CÁ NHÂN (PERSONAL SKILL). Nếu bạn biết nắm bắt cơ hội, có thể bạn sẽ được thuê để viết những dòng mô tả kỹ năng cho một trò chơi điện tử cực kỳ tuyệt vời.",
  "10 MIL Cpt Brett Lovegreen": "10 QUÂN ĐỘI (MIL) Đại Úy Brett Lovegreen",
  "[hissed through gritted teeth] How 'bout you slow the fuck down?!": "[rít lên qua kẽ răng] Hay là cậu chạy chậm lại cái đéo đi được đéo?!",
  "Aw dammit!": "Aw chết tiệt!",
  "Well, that's a passel of zeds we don't gotta worry about any more! - %1$s": "Chà, đó là một mớ bọn zeds mà chúng ta đéo cần phải bận tâm đến nữa rồi! - %1$s",
  "I need more than painkillers.": "Tôi cần nhiều thứ hơn là thuốc giảm đau (painkillers).",
  "Long as you don't start trouble, you're welcome to trade here.": "Miễn là cậu đéo gây ra rắc rối, cậu được chào đón đến giao dịch (trade) ở đây.",
  "Something's been bothering me, and I can't quite shake it.": "Có điều gì đó luôn khiến tôi băn khoăn, và tôi đéo thể nào rũ bỏ được nó.",
  "Now THAT I can use.": "Bây giờ thì TÔI có thể sử dụng được ĐIỀU ĐÓ rồi.",
  "Moving Company": "Công Ty Chuyển Nhà (Moving Company)",
  "Well, now that you mention it...": "Chà, bây giờ khi cậu nhắc đến chuyện đó...",
  "I don't know what I was thinking, going out there without backup. I guess I've always bitten off more than I could chew.": "Tôi đéo biết lúc đó mình đang nghĩ cái đéo gì nữa, khi ra ngoài đó mà đéo có ai hỗ trợ. Tôi đoán là tôi đã luôn ôm đồm quá nhiều việc mà bản thân đéo thể kham nổi (bitten off more than I could chew).",
  "Black Friday, we have a supply drop en route to your LZ.": "Black Friday, chúng tôi đang có một chuyến hàng tiếp tế (supply drop) đang trên đường (en route) đến bãi đáp LZ của anh.",
  "I'll come along. What the hell, they'd do the same for me right?": "Tôi sẽ đi cùng. Có cái đéo gì đâu, bọn họ cũng sẽ làm điều tương tự cho tôi thôi đúng đéo?",
  "Ice Axe": "Rìu Phá Băng (Ice Axe)",
  "You did good. I know things are looking pretty bleak, but just try to remember, everybody's here for you.": "Cậu đã làm rất tốt. Tôi biết mọi chuyện đang có vẻ khá là ảm đạm, nhưng hãy cố gắng nhớ rằng, mọi người đều ở đây vì cậu.",
  "Watch behind us.": "Hãy để mắt phía sau lưng chúng ta.",
  "Friend and confidant to Major Hawkes since Afghanistan.": "Bạn bè và đồng thời là tri kỷ (confidant) của Thiếu Tá Hawkes kể từ thời còn ở chiến trường Afghanistan.",
  "This is ALREADY an OUTPOST.": "Nơi này ĐÃ LÀ một TIỀN ĐỒN (OUTPOST).",
  "SURVIVAL TACTICS: Medicine Storage": "CHIẾN THUẬT SINH TỒN (TACTICS): Dự Trữ Thuốc Men (Medicine Storage)",
  "Fairgrounds Snack Shop": "Cửa Hàng Đồ Ăn Nhẹ Tại Khu Hội Chợ",
  "I think I caught something. It's that Cleo person again, but a lot fainter. Listen.": "Tôi nghĩ là tôi vừa bắt được thứ gì đó. Lại là cái người tên Cleo đó, nhưng tín hiệu mờ nhạt hơn rất nhiều. Hãy nghe thử xem.",
  "Brown": "Brown",
  "Creates a couple of improvised box mines. Small chance of mishaps.": "Chế tạo ra vài quả mìn hộp (box mines) tự chế. Có một tỷ lệ nhỏ xảy ra sự cố ngoài ý muốn (mishaps).",
  "The times, they are a-changing.": "Thời thế, chúng đang thay đổi.",
  "We're not out of the woods yet, bud!": "Chúng ta vẫn chưa thoát khỏi nguy hiểm đâu (out of the woods), anh bạn!",
  "Madison has developed an exhaustive ... one might say carnal ... knowledge of Doctor Horn and his work.": "Madison đã phát triển một sự am hiểu toàn diện ... có thể nói là rất sâu sắc (carnal) ... về Bác sĩ Horn và những công trình nghiên cứu của ông ấy.",
  "Turning out to be less of a screw-up.": "Hóa ra lại đéo phải là một kẻ ăn hại đái nát (screw-up) cho lắm.",
  "Improvised Painkiller": "Thuốc Giảm Đau Tự Chế (Improvised Painkiller)",
  "Time to confront the Wilkersons.": "Đã đến lúc phải đối mặt với nhà Wilkersons.",
  "Not while we got zeds nearby.": "Đéo phải trong lúc chúng ta có bọn zeds ở gần đây.",
  "Help destroy some armored zombies?": "Giúp đỡ tiêu diệt một vài con zombie bọc giáp (armored zombies) chứ?",
  "Reach Breakdown Level 6.": "Đạt Cấp Độ Sụp Đổ (Breakdown Level) 6.",
  "CHECKING IN": "ĐANG ĐĂNG KÝ XÁC NHẬN (CHECKING IN)",
  "Jason": "Jason"
};

const file = 'output/languages/chunks/btxt_chunk_182.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_182.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk182[r.sourceText]) {
    r.translatedText = chunk182[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 182 successfully!');
