const fs = require('fs');
const chunk193 = {
  "Jeez-us! You going for the record?": "Chúa ơi! Cậu đang định thiết lập kỷ lục đấy à?",
  "Voight": "Voight",
  "What about me, Alan? Do I need to start sleeping with one eye open?": "Vậy còn tôi thì sao, Alan? Có phải tôi cũng cần bắt đầu tập ngủ mở một mắt giống như vậy đéo?",
  "INCIDENT: Army Zed Encounter": "SỰ CỐ (INCIDENT): Đụng Độ Lính Quân Đội (Army) Zed",
  "Guess not.": "Đoán là đéo phải.",
  "Uh, not really.": "Uh, cũng đéo hẳn là như vậy.",
  "I'm in a fucking hurry because this is a waste of my damn time.": "Tôi đang vội vãi lồn ra đây bởi vì điều này đang làm lãng phí thời gian chết tiệt của tôi.",
  "Xbox Live": "Xbox Live",
  "%1$s found their way home, but from what I'm hearing, it was a rough trip. - %2$s": "%1$s đã tìm được đường để quay trở về nhà, nhưng theo như những gì mà tôi được nghe kể lại, thì đó là một chuyến hành trình vô cùng gian nan. - %2$s",
  "Anime Knowledge": "Kiến Thức Về Anime (Anime Knowledge)",
  "Gregory": "Gregory",
  "The RV has two flat tires, but one of them might be salvageable. It's going to take some work to get them all roadworthy ...": "Chiếc xe RV đang bị xịt mất hai cái lốp, nhưng có vẻ như một trong số chúng có thể tận dụng lại được. Sẽ phải tốn một chút công sức để có thể làm cho tất cả chúng hoạt động trở lại bình thường và sẵn sàng lăn bánh trên đường ...",
  "Troops at Fairgrounds FOB report civilian contact.\r\nRefugees from Marshall may have entered Fairfield Quarantine Zone.": "Lực lượng đóng quân tại căn cứ tiền phương Fairgrounds (Fairgrounds FOB) vừa báo cáo lại về việc đã có những cuộc đụng độ với dân thường (civilian).\r\nNhững người dân tị nạn (Refugees) đến từ Marshall có thể đã xâm nhập vào bên trong khu vực Vùng Cách Ly Fairfield (Fairfield Quarantine Zone).",
  "Well, I guess we could always move back in.": "Chà, tôi đoán là chúng ta luôn có thể di chuyển quay trở lại vào bên trong.",
  "Come on, everybody back on the horse!": "Thôi nào, tất cả mọi người hãy mau quay trở lại trên lưng ngựa đi!",
  "Hope he's not expecting to find any new patients up there.": "Hy vọng rằng ông ấy đéo kỳ vọng vào việc sẽ có thể tìm thấy bất cứ một bệnh nhân mới nào ở trên đó.",
  "You tryin' to get everybody killed? Give some room!": "Mày đang cố gắng tìm cách để giết chết tất cả mọi người ở đây đấy à? Tránh đường ra một chút coi!",
  "Teresa": "Teresa",
  "Pipe Bender": "Kìm Uốn Ống Nước (Pipe Bender)",
  "Put that one in the books.": "Hãy ghi chép lại điều đó vào trong những cuốn sách đi.",
  "Met up with Sam and Alan, but things didn't go all that well. - %1$s": "Tôi đã gặp được Sam và Alan, nhưng mọi chuyện đã đéo diễn ra tốt đẹp cho lắm. - %1$s",
  "Now that's some fucked-up shit!": "Giờ thì đó đúng là một mớ hỗn độn chết tiệt!",
  "Powerful round used the world over. Includes the entirety of the thirty-caliber family of rifle ammunition. Used by battle rifles and long-range rifles.": "Loại đạn mạnh mẽ được sử dụng phổ biến trên toàn thế giới. Bao gồm toàn bộ các loại đạn súng trường thuộc dòng cỡ nòng 30. Thường được sử dụng cho các loại súng trường chiến đấu và súng trường tầm xa.",
  "Practiced Martial Arts": "Từng Tập Luyện Võ Thuật (Martial Arts)",
  "Canned Goods": "Đồ Hộp (Canned Goods)",
  "Don't give up hope!": "Đừng bao giờ từ bỏ niềm hy vọng!",
  "Isabel": "Isabel",
  "Shit, these guys look messed up too!": "Chết tiệt thật, mấy gã này trông cũng rối rắm vãi cả đái!",
  "I got no fucking clue.": "Tôi đéo có bất cứ một manh mối chết tiệt nào cả.",
  "Course I'm ready, just waitin' on you!": "Tất nhiên là tôi đã sẵn sàng cmnr, tôi chỉ đang chờ đợi cậu mà thôi!",
  "Anderson": "Anderson",
  "Roger that, Black Friday. I'll let the governor know. Highroad out.": "Đã rõ thưa ngài, Black Friday. Tôi sẽ báo cáo lại sự việc này cho ngài thống đốc (governor) được biết. Highroad hết.",
  "I think I'm running out of gas.": "Tôi nghĩ là mình đang sắp sửa cạn kiệt nguồn nhiên liệu (gas) cmnr.",
  "It Was Just a Police Action": "Đó Chỉ Là Một Cuộc Hành Động Của Phía Cảnh Sát (Police) Mà Thôi",
  "Uh, help? Help would be good.": "Uh, cứu với? Cứu tôi với tôi đang cần được giúp đỡ.",
  "Standard NATO battle rifle caliber, includes the .223 caliber family of rounds as well.": "Cỡ nòng súng trường chiến đấu tiêu chuẩn của khối NATO, bao gồm cả các loại đạn thuộc dòng cỡ nòng .223.",
  "Knew you couldn't resist this beauty.": "Biết ngay là cậu sẽ đéo thể nào cưỡng lại được trước sức hấp dẫn của vẻ đẹp này mà.",
  "Sergeant Tan.": "Trung Sĩ (Sergeant) Tan.",
  "I'll call in to establish an outpost here. Nice work, Private.": "Tôi sẽ gọi điện thoại để thiết lập một khu tiền đồn (outpost) ở nơi này. Làm tốt lắm, Binh Nhì (Private).",
  "I'm not a machine. You gotta give me some time to rest.": "Tôi đéo phải là một cái máy. Cậu phải cho tôi có chút thời gian để nghỉ ngơi đi chứ.",
  "Swing by if you like.": "Hãy ghé qua đây nếu như cậu muốn.",
  "Locked and loaded.": "Đã nạp đạn và sẵn sàng khai hỏa.",
  "Okay, on second thought, that's a very dumb idea.": "Okay, nghĩ lại thì, đó quả là một ý tưởng vô cùng ngu ngốc.",
  "Please, nobody ever keeps anything useful in the closet. It's all about the sock drawer.": "Làm ơn đi, đéo có ai lại đi cất giấu bất cứ thứ gì hữu ích ở trong tủ quần áo (closet) cả. Tất cả những thứ đó đều được cất ở trong ngăn kéo đựng tất (sock drawer).",
  "Maybe you should think about heading home and getting some rest.": "Có lẽ cậu nên nghĩ đến việc đi về nhà và kiếm một chỗ để nghỉ ngơi đi.",
  "Man, he's just been such a downer lately, you know? What the hell is his deal?": "Trời ạ, dạo gần đây anh ta cứ tỏ ra là một kẻ vô cùng chán nản, cậu biết đéo? Anh ta đang gặp phải cái vấn đề quái quỷ gì vậy?",
  "Good supply of FUEL in their location.": "Nguồn cung cấp NHIÊN LIỆU (FUEL) rất tốt ở vị trí của bọn họ.",
  "Where'd you learn all this radio stuff, anyways?": "Dù sao thì, cậu đã học được tất cả những thứ liên quan đến đài phát thanh radio này ở đâu thế?",
  "I'm gonna check this one.": "Tôi sẽ tiến hành kiểm tra cái này.",
  "Invite a community member to follow you 10 times.": "Tiến hành Mời (Invite) một thành viên ở trong cộng đồng (community member) đi theo bạn 10 lần.",
  "Hoof angels forty, ten mikes.": "Hoof angels 40, 10 mikes.",
  "37 MIL Pvt Sam Pearce": "37 QUÂN ĐỘI (MIL) Binh Nhì (Pvt) Sam Pearce",
  "Listeners out there, any suggestions?": "Có vị thính giả (Listeners) nào ở ngoài kia có bất cứ một đề xuất gì hay ho đéo?",
  "Cost": "Chi Phí (Cost)",
  "Nearly all zeds behave in a primal, aggressive way, but FERAL ZEDS take it to another level.": "Gần như tất cả bọn zeds đều có cách cư xử theo một bản năng vô cùng nguyên thủy và cực kỳ hung hãn, nhưng bọn FERAL ZEDS lại nâng điều đó lên một tầm cao mới.",
  "Just gimme a few minutes.": "Chỉ cần cho tôi thêm một vài phút nữa thôi.",
  "I'm gonna wreck it!": "Tôi sẽ phá nát nó!",
  "Powerful mid-range workhorse for pistols, some revolvers and rifles.": "Loại đạn tầm trung cực kỳ mạnh mẽ dành cho các loại súng lục (pistols), một số loại súng lục ổ quay (revolvers) và súng trường (rifles).",
  "Safely in the air with Brock.": "Đang an toàn ở trên bầu trời cùng với Brock.",
  "Lauren": "Lauren",
  "We lost a barricade!": "Chúng ta vừa bị mất đi một cái chướng ngại vật (barricade) cmnr!",
  "Baton": "Dùi Cui (Baton)",
  "Whatever's causing the Black Fever, it's spreading fast.": "Bất kể thứ đéo gì đang là nguyên nhân gây ra căn bệnh Sốt Đen (Black Fever) này, thì nó hiện đang lây lan rất nhanh.",
  "Posit one one tango mike papa two five alpha zero five quebec. [message end tone]": "Posit one one tango mike papa two five alpha zero five quebec. [âm báo kết thúc tin nhắn]",
  "Old-School Muscle w/Style": "Chiếc Xe Cơ Bắp (Muscle) Cổ Điển Với Phong Cách Hiện Đại",
  "If we can't keep our outposts in shape, this situation WILL get worse.": "Nếu như chúng ta đéo thể giữ cho những tiền đồn (outposts) của mình ở trong trạng thái hoạt động tốt nhất, thì tình hình này SẼ CÒN trở nên tồi tệ hơn rất nhiều đấy.",
  "Delay your decision. Quentin probably won't wait forever.": "Trì hoãn (Delay) quyết định của bạn. Quentin có lẽ sẽ đéo thể nào chờ đợi mãi mãi được đâu.",
  "Taking a look around now.": "Hiện tại tôi đang tiến hành quan sát xung quanh.",
  "Why don't you come inside? Least we can do is feed you.": "Tại sao cậu lại đéo đi vào bên trong nhỉ? Ít nhất thì chúng tôi cũng có thể cung cấp cho cậu một bữa ăn cơ mà.",
  "Can't do that with zeds right outside.": "Đéo thể làm được điều đó khi mà bọn zeds đang đứng ngay ở phía bên ngoài kia.",
  "Eventually, you'll find fatigue building up. A snack will give you a temporary energy boost, but to really fight fatigue you should think about stepping away and resting for a day. You can also radio home and talk to Pastor Will. He has a way of inspiring people to keep going. - %1$s": "Cuối cùng, cậu sẽ nhận ra rằng sự mệt mỏi (fatigue) đang dần được tích tụ lại. Một bữa ăn nhẹ (snack) sẽ mang lại cho cậu một sự thúc đẩy năng lượng tạm thời, nhưng để có thể thực sự chống lại được sự mệt mỏi, cậu nên suy nghĩ đến việc tránh xa khỏi mọi chuyện và dành thời gian nghỉ ngơi thư giãn trong một ngày. Cậu cũng có thể liên lạc qua radio về nhà và trò chuyện cùng với Mục sư (Pastor) Will. Ông ấy có một cách riêng để có thể truyền cảm hứng giúp cho mọi người tiếp tục tiến bước về phía trước. - %1$s",
  "Use the mouse to look around.": "Sử dụng chuột (mouse) để có thể quan sát xung quanh.",
  "Semi-pro fighter with more losses than teeth.": "Một võ sĩ bán chuyên nghiệp có số lần thất bại còn nhiều hơn cả số lượng răng đang có ở trong mồm.",
  "Bianca": "Bianca",
  "Fix Up Refrigerated Storage Room": "Sửa Chữa Lại Khu Vực Phòng Lưu Trữ Bằng Tủ Lạnh (Refrigerated Storage Room)",
  "When we don't have enough food for everyone, people go hungry. - %1$s": "Khi chúng ta đéo có đủ lượng thức ăn (food) để cung cấp cho tất cả mọi người, mọi người sẽ bị đói khát. - %1$s",
  "Oh, uh... hey. Hey there.": "Oh, uh... này. Chào đằng ấy.",
  "No can do.": "Đéo thể nào làm được chuyện đó đâu.",
  "There's a huge wine cellar or something here, and I'm not leaving till I find it.": "Có một cái hầm chứa rượu vang khổng lồ hoặc một thứ đéo gì đó tương tự như thế ở nơi này, và tôi sẽ đéo rời đi cho đến khi nào tôi tìm thấy nó.",
  "I guess this all looks pretty grim, huh?": "Tôi đoán là tất cả những điều này trông có vẻ khá là u ám (grim), hả?",
  "COMPLETED: Ridge Cabins": "ĐÃ HOÀN THÀNH (COMPLETED): Khu Nhà Gỗ Trên Sườn Núi (Ridge Cabins)",
  "Biodiesel": "Nhiên Liệu Sinh Học Biodiesel",
  "Jesus, is this place being run by a pack of idiots? What the hell are they thinking?": "Chúa ơi, có phải cái nơi này đang được điều hành bởi một lũ ngu ngốc đéo? Bọn họ đang nghĩ cái quái quỷ gì vậy?",
  "Watch your right.": "Hãy chú ý quan sát cẩn thận ở phía bên phải của cậu kìa.",
  "Salas": "Salas",
  "Army personnel, this is Black Friday.": "Lực lượng quân đội (Army), đây là Black Friday.",
  "Thanks for being honest, though.": "Dù sao thì cũng cảm ơn cậu vì đã luôn thành thật.",
  "MISSION: Friendly Survivors": "NHIỆM VỤ (MISSION): Những Người Sống Sót Thân Thiện (Friendly Survivors)",
  "Kitchen": "Nhà Bếp (Kitchen)",
  "Just prepping dinner for tonight.": "Chỉ đang chuẩn bị cho bữa ăn tối vào tối ngày hôm nay thôi mà.",
  "Not really.": "Cũng đéo hẳn là như vậy.",
  "Screamer, it's close.": "Có một con Screamer, nó đang ở rất gần đây.",
  "Looks like a good spot for an outpost.": "Trông có vẻ như đây là một vị trí rất thích hợp để có thể thiết lập một cái tiền đồn (outpost) đấy.",
  "Umm... we might have a problem here.": "Umm... có thể là chúng ta đang gặp phải một rắc rối ở đây đấy.",
  "Whisks": "Dụng Cụ Đánh Trứng (Whisks)",
  "Prepare the RV (Home Menu)": "Chuẩn bị chiếc xe RV (Menu Trang Chủ Home Menu)",
  "Gatlin": "Gatlin",
  "Best Playthrough (Breakdown)": "Màn Chơi Tốt Nhất (Breakdown)",
  "Francis": "Francis",
  "Grayson": "Grayson"
};

const file = 'output/languages/chunks/btxt_chunk_193.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_193.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk193[r.sourceText]) {
    r.translatedText = chunk193[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 193 successfully!');
