const fs = require('fs');
const chunk159 = {
  "Wyatt": "Wyatt",
  "That's nothing. I caught him earlier, staring at his pistol like it was his long-lost best friend.": "Chuyện đó đéo nhằm nhò gì. Trước đó tôi bắt gặp anh ta đang nhìn chằm chằm vào khẩu súng lục của mình cứ như thể nó là người bạn thân thất lạc từ lâu của anh ta vậy.",
  "Oh man, oh man, oh man! This is so screwed up!": "Ôi bạn ơi, ôi bạn ơi, ôi bạn ơi! Chuyện này đúng là nát bét rồi!",
  "Desperately Need Food": "Đang Rất Cần Thức Ăn (Desperately Need Food)",
  "Damn. We were doing pretty good there up until the end.": "Chết tiệt. Chúng ta đã làm khá tốt cho đến tận phút cuối.",
  "You're going to burn yourself out if you don't come home and rest a little.": "Cậu sẽ tự vắt kiệt sức mình mất nếu đéo về nhà và nghỉ ngơi một chút.",
  "Essentially a 40mm revolver.": "Về cơ bản là một khẩu súng lục ổ quay 40mm.",
  "New toys!": "Đồ chơi mới kìa!",
  "I honestly don't know how long we can keep it together here.": "Thành thật mà nói, tôi đéo biết chúng ta có thể cầm cự được ở đây bao lâu nữa.",
  "Seems like a screamer issue.": "Có vẻ như đây là vấn đề do đám screamer gây ra.",
  "Well, look at you. Aren't you curious?": "Chà, nhìn cậu kìa. Cậu đéo tò mò sao?",
  "8 GENERIC Sarah Jordan": "8 CHUNG (GENERIC) Sarah Jordan",
  "You just run along and get us what you owe, and we won't have a problem. You hear me?": "Mày cứ việc chạy đi và mang về cho bọn tao những gì mày nợ, và chúng ta sẽ đéo có vấn đề gì. Mày nghe rõ đéo?",
  "Reckless actions, like setting an ally on fire, affect TRUST and ATTITUDE of those around you.": "Những hành động thiếu suy nghĩ, như việc châm lửa đốt một người đồng minh, sẽ ảnh hưởng đến NIỀM TIN (TRUST) và THÁI ĐỘ (ATTITUDE) của những người xung quanh bạn.",
  "Castellaw": "Castellaw",
  "Ruiz": "Ruiz",
  "You shoulda seen %2$s, man! Dumped, like, three whole clips into one of those big boys. I didn't think that thing would ever go down! It's epic! - %1$s": "Anh bạn, lẽ ra cậu nên nhìn thấy %2$s! Cậu ta đã xả, kiểu như, ba băng đạn trọn vẹn vào một trong những gã to xác đó. Tôi đã nghĩ cái thứ đó sẽ đéo bao giờ gục ngã! Thật là hoành tráng! - %1$s",
  "Strain 854b shows a remarkable resistance to traditional antibiotic countermeasures. Estimated probability of successful containment: 13.48%": "Chủng 854b cho thấy khả năng kháng cự đáng kinh ngạc đối với các biện pháp đối phó bằng thuốc kháng sinh truyền thống. Xác suất ngăn chặn thành công ước tính: 13.48%",
  "Built Like a Horse": "Khỏe Như Một Con Ngựa",
  "Press desired key": "Nhấn phím mong muốn",
  "JOURNAL: The Ranger Station": "NHẬT KÝ (JOURNAL): Trạm Kiểm Lâm (The Ranger Station)",
  "Your Honor.": "Kính thưa quý tòa.",
  "He might have known, but he didn't care. As far as Eli was concerned, he was immortal.": "Có thể anh ta biết, nhưng anh ta đéo quan tâm. Theo như những gì Eli nghĩ, thì anh ta là kẻ bất tử.",
  "Chambers": "Chambers",
  "I need a rest!": "Tôi cần được nghỉ ngơi!",
  "We're going to survive this.": "Chúng ta sẽ sống sót qua chuyện này.",
  "We need some help finding one of our own.": "Chúng tôi cần sự giúp đỡ để tìm kiếm một người của mình.",
  "Just point the way.": "Chỉ đường đi.",
  "Maybe next time try NOT to attract every zed in the county?": "Có lẽ lần sau hãy cố gắng ĐÉO thu hút tất cả bọn zed trong quận được đéo?",
  "Combat Sounds": "Âm Thanh Chiến Đấu",
  "I guess this is it, huh?": "Tôi đoán thế là hết, hả?",
  "Might want to send somebody with military experience. I dunno, maybe they'd respond better.": "Có lẽ nên cử ai đó có kinh nghiệm quân sự. Tôi đéo biết nữa, có thể họ sẽ phản hồi tốt hơn.",
  "Goddammit! We got enough trouble without bringing in another freeloader to use up all our medicine!": "Chết tiệt! Chúng ta đã có đủ rắc rối rồi mà đéo cần phải rước thêm một kẻ ăn bám rước vào để ngốn hết thuốc men của chúng ta nữa!",
  "Killed 100 zombies with Drone Strikes.": "Đã tiêu diệt 100 con zombie bằng các Cuộc Không Kích Từ Drone (Drone Strikes).",
  "I'd say you're doing better than you think.": "Tôi dám nói rằng cậu đang làm tốt hơn những gì cậu nghĩ đấy.",
  "She always had a good head on her shoulders. If she was in trouble, she would've tried to get inside, fortify someplace till we came looking.": "Cô ấy luôn có một cái đầu nhạy bén. Nếu cô ấy gặp rắc rối, cô ấy hẳn đã cố gắng chui vào bên trong, cố thủ ở một nơi nào đó cho đến khi chúng ta đến tìm.",
  "I've always loved taking things apart and putting them back together. Dig into the guts, ya know?": "Tôi luôn thích tháo tung mọi thứ ra và lắp ráp chúng lại với nhau. Đào sâu vào tận cốt lõi bên trong, cậu biết đéo?",
  "Additional Vitality and Stamina bonuses for everyone. (High likelihood of needing special ingredients.) REQUIRES GOOD COOK.": "Bổ sung các phần thưởng về Sinh Lực (Vitality) và Thể Lực (Stamina) cho mọi người. (Khả năng cao là cần đến các nguyên liệu đặc biệt.) YÊU CẦU ĐẦU BẾP GIỎI.",
  "Oh, and without my handler, I'm gonna need access to your intel.": "Ồ, và vì đéo có người hướng dẫn, tôi sẽ cần quyền truy cập vào thông tin tình báo của các anh.",
  "No, I like it. It's got a certain devil-may-care panache.": "Đéo, tôi thích nó đấy chứ. Nó có một kiểu phớt lờ đời đầy ngang tàng.",
  "I think we're going to have a fight on our hands here.": "Tôi nghĩ là chúng ta sắp có một trận chiến ra trò ở đây rồi.",
  "Are you trying to draw them to us?": "Anh đang cố thu hút chúng về phía chúng ta đấy à?",
  "Mickey wanted me to reach out; let you know we appreciate having you as a neighbor. - %1$s": "Mickey muốn tôi liên lạc; để cậu biết rằng chúng tôi rất trân trọng việc có cậu làm hàng xóm. - %1$s",
  "Local administrator for the Human Future Fund. May have received documents from Thomas Horn.": "Quản trị viên địa phương cho Quỹ Tương Lai Nhân Loại (Human Future Fund). Có thể đã nhận được tài liệu từ Thomas Horn.",
  "In command of this entire operation, and of base Black Friday.": "Người chỉ huy toàn bộ chiến dịch này, và của căn cứ Black Friday.",
  "Nice job giving away our position with that gunfire.": "Làm tốt lắm trong việc để lộ vị trí của chúng ta bằng tiếng súng đó.",
  "I don't know about you, but I'm keeping a couple of bullets back. Just in case.": "Tôi đéo biết cậu thì sao, nhưng tôi sẽ giữ lại một vài viên đạn. Đề phòng trường hợp bất trắc.",
  "Trade 1 Case of Ammunition for 5 Daily Rations of Food.": "Trao đổi 1 Thùng Đạn Dược (Case of Ammunition) lấy 5 Khẩu Phần Thức Ăn Hàng Ngày (Daily Rations of Food).",
  "Upgrade to Legit Workshop": "Nâng cấp lên Xưởng Chuẩn (Legit Workshop)",
  "Y'know, I hear Marshall's real nice this time of year. Cool, roomy, friendly... did I mention roomy?": "Cậu biết đéo, tôi nghe nói Marshall rất tuyệt vào thời điểm này trong năm. Mát mẻ, rộng rãi, thân thiện... tôi đã nhắc đến chữ rộng rãi chưa nhỉ?",
  "Went through the intensive training in marksmanship and decision-making that defines a qualified sniper.": "Đã trải qua quá trình huấn luyện cường độ cao về khả năng thiện xạ và ra quyết định, những yếu tố tạo nên một lính bắn tỉa đủ tiêu chuẩn.",
  "We can fit a few people and supplies on the RV. It’ll be tight, but we can manage.": "Chúng ta có thể nhét một vài người và nhu yếu phẩm lên chiếc RV. Sẽ chật chội đấy, nhưng chúng ta có thể xoay xở được.",
  "Peacemaker": "Người Kiến Tạo Hòa Bình (Peacemaker)",
  "Kirchheim": "Kirchheim",
  "Oh hell yeah!": "Ôi chết tiệt đúng vậy!",
  "This better be the last of them.": "Tốt nhất đây nên là những kẻ cuối cùng.",
  "Wow, this place looks secure. I still can't believe that you found me.": "Wow, nơi này trông có vẻ an toàn đấy. Tôi vẫn đéo thể tin được là cậu đã tìm thấy tôi.",
  "But the more dangerous the situation, the more likely it will result in injury or death.": "Nhưng tình hình càng nguy hiểm, thì càng có nhiều khả năng dẫn đến chấn thương hoặc tử vong.",
  "Now they've got armor? That's not fucking fair!": "Giờ chúng còn có cả giáp nữa sao? Thật đéo công bằng chút nào!",
  "Baiko? Baiko! Have you seen my dog? He's got to be around here... somewhere.": "Baiko? Baiko! Cậu có thấy con chó của tôi đéo? Nó phải ở quanh đây... đâu đó.",
  "Eat for a temporary stamina boost.": "Ăn để tăng cường thể lực (stamina) tạm thời.",
  "Julene Horn safely extracted": "Julene Horn đã được chiết xuất an toàn",
  "Dane": "Dane",
  "EYES IN THE SKY: Survey Complete": "NHỮNG ĐÔI MẮT TRÊN BẦU TRỜI (EYES IN THE SKY): Hoàn Tất Khảo Sát",
  "Leaderboards": "Bảng Xếp Hạng (Leaderboards)",
  "Tauscher": "Tauscher",
  "High quality hardwood oar.": "Mái chèo bằng gỗ cứng chất lượng cao.",
  "Seems like we're getting a reputation. Some neighboring survivors asked if they could come get some firearms training from us. There's 3 cases of ammo in it for us. - %1$s": "Có vẻ như danh tiếng của chúng ta đang vang xa. Một số người sống sót ở khu vực lân cận đã hỏi xem họ có thể đến để được chúng ta huấn luyện sử dụng súng đéo. Sẽ có 3 thùng đạn dành cho chúng ta từ việc đó. - %1$s",
  "HOME: Missing Persons Dead": "NHÀ (HOME): Những Người Mất Tích Đã Chết",
  "Pack up your things, pack up your families, and get as far away from this city as you can.": "Gói ghém đồ đạc, đưa gia đình của các bạn, và chạy trốn khỏi thành phố này càng xa càng tốt.",
  "I'll need time to consider that.": "Tôi sẽ cần thời gian để xem xét chuyện đó.",
  "Way too tired to lug that thing around.": "Quá mệt để có thể lôi cái thứ đó đi vòng quanh.",
  "One of our scouts encountered a Bloater while out on patrol. We took it down to buyt ourselves some time before the next siege ... but we suffered a loss in the process.": "Một trong những trinh sát của chúng tôi đã chạm trán với một con Bloater khi đang đi tuần tra. Chúng tôi đã hạ gục nó để câu giờ cho bản thân trước cuộc vây hãm tiếp theo... nhưng chúng tôi đã phải gánh chịu tổn thất trong quá trình đó.",
  "I'm terribly sorry, but the rest of my flock requires attention as well.": "Tôi thực sự xin lỗi, nhưng những con chiên còn lại trong bầy của tôi cũng cần được quan tâm.",
  "A long-time Cold Warrior, this rifle was often used in a sniper role. Sadly, this one has no scope.": "Một Chiến binh Lạnh lùng (Cold Warrior) lâu đời, khẩu súng trường này thường được sử dụng trong vai trò bắn tỉa. Đáng buồn thay, khẩu này lại đéo có ống ngắm.",
  "White": "White",
  "That's unnecessary.": "Điều đó là đéo cần thiết.",
  "Well, the shoulder looks to be healing nicely, but I'm concerned about that head.": "Chà, phần vai có vẻ đang lành lại rất tốt, nhưng tôi khá lo lắng về cái đầu đó.",
  "Look, when I thought this was all going to pass ... I sort of looted some stuff from the grocery store.": "Nghe này, khi tôi nghĩ rằng mọi chuyện rồi sẽ qua đi... tôi kiểu như đã hôi của một vài thứ từ cửa hàng tạp hóa.",
  "Press [ul_radio_menu] to use your Radio.": "Nhấn [ul_radio_menu] để sử dụng Bộ Đàm (Radio) của bạn.",
  "Lead the way.": "Dẫn đường đi.",
  "Load up the RV": "Chất đồ lên chiếc RV",
  "Tactics: Search and Rescue": "Chiến thuật: Tìm kiếm và Cứu nạn (Search and Rescue)",
  "Breaking Down": "Sự Đổ Vỡ",
  "Spare us the inspirational speeches. We all know how bad it is out there, and pretty words ain't gonna make it better. -%1$s": "Bớt mấy lời diễn văn truyền cảm hứng đi. Tất cả chúng ta đều biết ngoài kia tồi tệ đến mức nào, và những lời nói hoa mỹ cũng đéo làm cho mọi chuyện khá hơn đâu. -%1$s",
  "New actions available.": "Đã có các hành động mới.",
  "Complete All Research Projects. (Breakdown Level 1 or Higher)": "Hoàn thành Tất Cả Các Dự Án Nghiên Cứu. (Chế độ Breakdown Cấp độ 1 trở lên)",
  "This game supports an autosave feature. When you see this icon please do not turn off your console or remove the storage device.": "Trò chơi này hỗ trợ tính năng tự động lưu (autosave). Khi bạn thấy biểu tượng này, vui lòng không tắt máy chơi game hoặc tháo thiết bị lưu trữ.",
  "Safe Zone (%dm)": "Khu Vực An Toàn (%dm)",
  "Jacob Ritter": "Jacob Ritter",
  "Can you believe it? All this time, she was lying to me. To all of us.": "Cậu có tin được đéo? Suốt thời gian qua, cô ta đã nói dối tôi. Nói dối tất cả chúng ta.",
  "1 MIL Sgt Kilohana Young": "1 QUÂN ĐỘI (MIL) Trung Sĩ (Sgt) Kilohana Young",
  "Yeah, sure, man. I can do that.": "Ừ, chắc chắn rồi, anh bạn. Tôi có thể làm được.",
  "Play DLC": "Chơi bản mở rộng (DLC)",
  "The Cop": "Viên Cảnh Sát (The Cop)",
  "Safely in the air with Shira.": "Đang an toàn trên không trung cùng với Shira.",
  "%1$s is not happy.": "%1$s đang đéo vui.",
  "Shark Hoodie Guy": "Gã Mặc Áo Khoác Trùm Đầu Có Hình Cá Mập",
  "Investigate Artillery Site": "Điều tra Khu Vực Pháo Binh (Artillery Site)",
  "Danforth is a disaster, and we could use you someplace that still has a future.": "Danforth là một thảm họa, và chúng tôi có thể cần anh ở một nơi nào đó vẫn còn tương lai."
};

const file = 'output/languages/chunks/btxt_chunk_159.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_159.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk159[r.sourceText]) {
    r.translatedText = chunk159[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 159 successfully!');
