const fs = require('fs');
const chunk137 = {
  "If you are cut off, radio in and we'll provide assistance.": "Nếu cậu bị cắt đứt liên lạc, hãy gọi radio và chúng tôi sẽ hỗ trợ.",
  "Can call in support from off-map artillery when a part of the community.": "Có thể gọi hỗ trợ pháo binh từ ngoài bản đồ khi là một phần của cộng đồng.",
  "House": "Nhà",
  "Erin": "Erin",
  "They may have supplies to share.": "Họ có thể có nhu yếu phẩm để chia sẻ.",
  "Don't... please.": "Đừng... làm ơn.",
  "If they don't get help, those people could die.": "Nếu đéo được giúp đỡ, những người đó có thể sẽ chết.",
  "Finally, a sanitary place to cut people.": "Cuối cùng cũng có một nơi sạch sẽ để mổ xẻ người ta.",
  "Your dad. What was he like?": "Bố cậu. Ông ấy là người như thế nào?",
  "Move Forward": "Tiến Về Phía Trước",
  "Yeah, you can say that again.": "Chuẩn đéo cần chỉnh.",
  "Doherty": "Doherty",
  "Surgery Tools": "Dụng Cụ Phẫu Thuật",
  "I financed my first car on online poker winnings. (Wits Bonus)": "Tôi đã mua chiếc xe hơi đầu tiên bằng tiền thắng bài poker trực tuyến. (Thưởng Nhanh Trí)",
  "Hold [ul_aim] to aim a firearm, then press [ul_shoot] to fire. Hold down [ul_shoot] to fire automatic weapons. While aiming, press [aim.reload] to reload.": "Giữ phím [Ngắm bắn] (ul_aim) để ngắm súng, sau đó nhấn phím [Bắn] (ul_shoot) để bắn. Giữ chặt [Bắn] để bắn súng tự động. Trong khi đang ngắm, nhấn phím [Nạp đạn] (aim.reload) để nạp đạn.",
  "Black Friday, you've got another one incoming. Watch the skies. Highroad out.": "Black Friday, các anh lại có một đợt tiếp viện nữa đang đến đấy. Hãy chú ý trên bầu trời. Highroad hết.",
  "LOG: Disarming the Nuke": "NHẬT KÝ: Vô Hiệu Hóa Bom Hạt Nhân (Nuke)",
  "Expand the safe area around your home using a Watchtower.": "Mở rộng khu vực an toàn quanh nhà bạn bằng một Tháp Canh (Watchtower).",
  "See ya.": "Gặp lại sau nhé.",
  "We're clear, but if you're lonely I could start shoutin'.": "Chúng ta an toàn rồi, nhưng nếu cậu thấy cô đơn thì tôi có thể bắt đầu hét lên đấy.",
  "Could snap at any time.": "Có thể nổi điên bất cứ lúc nào.",
  "Meade": "Meade",
  "How about you help us clear out this infestation?": "Cậu giúp chúng tôi dọn sạch cái ổ dịch này thì sao?",
  "Gamer Country": "Thế Giới Của Game Thủ (Gamer Country)",
  "Let's go find 'em, then.": "Vậy thì đi tìm họ thôi.",
  "No room for %s on the RV.": "Đéo còn chỗ cho %s trên xe RV.",
  "No. It really doesn't, does it?": "Đéo. Nó thực sự đéo phải vậy, đúng đéo?",
  "Oh no. I'm so sorry.": "Ôi đéo. Tôi rất tiếc.",
  "Shira, we've got your father, and we're getting you out of here. Come on.": "Shira, chúng tôi đã đưa bố cô đi rồi, và chúng tôi sẽ đưa cô ra khỏi đây. Nhanh lên.",
  "Heading out now.": "Đang xuất phát đây.",
  "Make Flame Fougasse": "Chế Tạo Mìn Lửa (Flame Fougasse)",
  "START MISSION. Earn 3 Cases of Ammo with a simple (?) delivery mission.": "BẮT ĐẦU NHIỆM VỤ. Kiếm 3 Thùng Đạn bằng một nhiệm vụ giao hàng đơn giản (?).",
  "%1$s isn't going anywhere.": "%1$s sẽ đéo đi đâu cả.",
  "You throw a guy out on his ass for a case of the sniffles? What kind of an Army are you running?": "Anh ném cổ một người ra ngoài chỉ vì mấy triệu chứng sụt sịt mũi thôi sao? Các anh đang điều hành cái kiểu Quân Đội chó đẻ gì vậy?",
  "de la Cueva": "de la Cueva",
  "Increased mobility and control when using large machine guns.": "Tăng độ cơ động và kiểm soát khi sử dụng súng máy hạng nặng.",
  "The government? You don't get it. It's been total chaos.": "Chính phủ à? Cậu đéo hiểu rồi. Mọi thứ đã trở thành một mớ hỗn độn hoàn toàn.",
  "You'd think in a situation like this, empathy for your fellow man would be one of the first things to go. Glad to see that's not the case.": "Cậu sẽ nghĩ rằng trong một tình huống như thế này, sự đồng cảm với đồng loại sẽ là một trong những thứ biến mất đầu tiên. Thật mừng khi thấy mọi chuyện đéo phải vậy.",
  "A freaking foot, that's what! Yeah. Somebody dumped a body right behind my restaurant.": "Một cái cẳng chân chó đẻ chứ cái đéo gì nữa! Phải. Có kẻ nào đó đã vứt một cái xác chết ngay đằng sau nhà hàng của tôi.",
  "Repair RV Engine": "Sửa Động Cơ Xe RV",
  "You lost too many assets.": "Mấy người đã tổn thất quá nhiều lực lượng rồi.",
  "The walls aren't stopping them!": "Những bức tường đéo thể ngăn được chúng!",
  "SMG: MP7A1": "Súng tiểu liên: MP7A1",
  "Lay IFF mines that will blow up the zombies, but deactivate in the presence of friendlies.": "Rải các loại mìn nhận diện phe phái (IFF), chúng sẽ nổ tung lũ zombie, nhưng tự động vô hiệu hóa khi có đồng minh ở gần.",
  "You ever see a head explode like that?": "Cậu đã bao giờ thấy một cái đầu nổ tung như vậy chưa?",
  "I'll look and see what we got.": "Tôi sẽ xem thử chúng ta có những gì.",
  "I'm whipped. Need to catch my breath before I can do anything else.": "Tôi kiệt sức rồi. Cần phải lấy lại hơi trước khi tôi có thể làm bất cứ việc gì khác.",
  "Thanks!": "Cảm ơn!",
  "Maybe we should go the other way, huh?": "Có lẽ chúng ta nên đi đường khác, hả?",
  "Find Carl": "Tìm Carl",
  "Let's have a look around.": "Hãy nhìn quanh một vòng xem sao.",
  "You boys didn't have a bullet to your name.": "Các cậu đéo có lấy một viên đạn giắt lưng.",
  "You know, when they open on some innocuous scene of a guy jogging in the park or a couple arguing about directions and suddenly they find a dead body?": "Cậu biết đéo, kiểu như khi họ mở đầu bằng một cảnh quay vô thưởng vô phạt về một gã đang chạy bộ trong công viên, hoặc một cặp đôi đang cãi nhau về việc đi nhầm đường, và đột nhiên họ phát hiện ra một xác chết ấy?",
  "Greyhound One, this is Black Friday. I'm having trouble raising Doghouse on the radio.": "Greyhound One, đây là Black Friday. Tôi đang gặp khó khăn khi liên lạc với Doghouse qua vô tuyến.",
  "Well, that was pretty awesome. - %1$s": "Chà, chuyện đó thực sự rất tuyệt. - %1$s",
  "Wall Repairs": "Sửa Chữa Tường Vây",
  "Is Alan out there with you?": "Alan có ở ngoài đó với cậu đéo?",
  "Supply Lines: Nothing Found": "Tuyến Đường Tiếp Tế: Đéo Tìm Thấy Gì",
  "Outpost - PMC Reinforcements": "Tiền Đồn - Lính Đánh Thuê (PMC) Viện Trợ",
  "It's not rocket science: you want to improve your Revolver Specialization, you've got to dust off the old six-shooter and kill some zeds.": "Đéo phải là khoa học tên lửa gì đâu: cậu muốn cải thiện Chuyên Môn Súng Lục Ổ Xoay, cậu phải phủi bụi khẩu súng sáu viên cũ kỹ đó và đi giết vài con zed.",
  "You think anybody else up here survived?": "Cậu nghĩ còn ai khác trên này sống sót đéo?",
  "Retrieve Intel": "Thu Thập Thông Tin Tình Báo",
  "Macon": "Macon",
  "Grows soybeans and corn.": "Trồng đậu nành và ngô.",
  "Just need a little fuel and some generators, and I'm your new best friend. (Handy with tools.)": "Chỉ cần một ít nhiên liệu và vài cái máy phát điện, và tôi sẽ là người bạn thân mới của các cậu. (Khéo tay với máy móc.)",
  "Trevor": "Trevor",
  "We just received a request for assistance on a supply run. Transmitting coordinates now.": "Chúng tôi vừa nhận được yêu cầu hỗ trợ trong một chuyến đi chạy tiếp tế. Đang gửi tọa độ đây.",
  "I follow a rigorous daily routine that keeps my body in prime condition, and makes it easier to adapt to new threats. (Advanced Cardio, Faster Combat Skills)": "Tôi tuân theo một thói quen hàng ngày nghiêm ngặt giúp cơ thể luôn ở trạng thái sung mãn nhất, và dễ dàng thích nghi với các mối đe dọa mới. (Thể Lực Tiên Tiến, Tăng Nhanh Kỹ Năng Chiến Đấu)",
  "Uses the .50 AE pistol round, a show stopper.": "Sử dụng đạn súng lục .50 AE, một công cụ chấm dứt mọi cuộc chơi.",
  "What else is new?": "Có gì mới đéo?",
  "I got something you might want to see here. Meet me as soon as you can, I could use some backup.": "Tôi có thứ này cậu có thể muốn xem ở đây. Đến gặp tôi càng sớm càng tốt, tôi đang cần chút chi viện.",
  "HOME: Fight at Home": "CĂN CỨ: Chiến Đấu Tại Nhà",
  "Ben": "Ben",
  "Setting up traps ftw.": "Cài bẫy sẽ giành chiến thắng (ftw).",
  "HOME: Loss of Hope": "CĂN CỨ: Mất Hy Vọng",
  "We're pretty sure that isn't his real name. But we're afraid to say anything. You never know when he might be standing behind you.": "Chúng tôi khá chắc đó đéo phải là tên thật của hắn. Nhưng chúng tôi sợ đéo dám nói gì. Cậu sẽ đéo bao giờ biết được lúc nào thì hắn đang đứng ngay sau lưng mình đâu.",
  "Can call in drone recon support.": "Có thể gọi máy bay đéo người lái (drone) trinh sát hỗ trợ.",
  "Best part, though? No piece of shit local cops showing up blabbing about \"drunk and disorderly\" and \"restraining order\" bullshit.": "Tuy nhiên, phần tuyệt vời nhất là gì đéo? Đó là đéo có bọn cớm địa phương khốn nạn nào xuất hiện và lải nhải mấy thứ nhảm nhí về việc \"say xỉn gây rối trật tự\" và \"lệnh cấm tới gần\" nữa.",
  "9mm Ammunition": "Đạn 9mm",
  "Yeah, no, I'm fine. Least I will be when my hands stop shaking. - %1$s": "Phải, đéo, tôi ổn. Ít nhất là tôi sẽ ổn khi tay tôi ngừng run bần bật thế này. - %1$s",
  "Glad to hear it.": "Thật mừng khi nghe điều đó.",
  "So what now? Head back to the station, or go check the lake cabins?": "Vậy giờ sao? Quay lại đồn cảnh sát, hay đến kiểm tra mấy căn nhà gỗ ven hồ?",
  "Doc, I'm a fuckin' wreck out here. Can ya help?": "Bác sĩ, tôi đang tơi tả như một bãi rác khốn kiếp ở ngoài này đây. Ông có thể giúp tôi đéo?",
  "Hard hitting SMG, meant to replace the MP5.": "Súng tiểu liên (SMG) hỏa lực mạnh, được thiết kế để thay thế MP5.",
  "Lykins": "Lykins",
  "Better'n biscuits on a Sunday morning.": "Còn ngon hơn cả bánh bích quy vào sáng Chủ Nhật.",
  "Special counter that lets you bodyslam enemies.": "Đòn phản công đặc biệt cho phép bạn vật ngã kẻ thù bằng cơ thể (bodyslam).",
  "And now I'm out of food.": "Và bây giờ tôi đã hết sạch thức ăn.",
  "We don't have the materials to fortify that place.": "Chúng ta đéo có vật liệu để gia cố nơi đó đâu.",
  "Scratch this one off the list.": "Gạch tên cái này khỏi danh sách đi.",
  "Provided you're willing to obey the law and contribute to society, you're welcome to join us here.": "Chỉ cần các bạn sẵn sàng tuân thủ luật pháp và đóng góp cho xã hội, các bạn luôn được chào đón gia nhập với chúng tôi ở đây.",
  "I see something. Looks like an infestation.": "Tôi thấy cái gì đó. Có vẻ như là một ổ dịch.",
  "We've got some doctors here at base who had to abandon their samples and equipment when they evacuated.": "Chúng ta có một vài bác sĩ ở căn cứ đã phải bỏ lại các mẫu vật và thiết bị của họ khi họ sơ tán.",
  "Found some ammo.": "Tìm thấy chút đạn.",
  "She was dead the moment the outbreak started, wasn't she? We all were.": "Cô ấy đã chết ngay từ khoảnh khắc đợt bùng phát bắt đầu rồi, đúng đéo? Tất cả chúng ta đều thế.",
  "Tactics": "Chiến Thuật",
  "The standard in most U.S. military branches since 1985.": "Trang bị tiêu chuẩn ở hầu hết các nhánh quân đội Hoa Kỳ kể từ năm 1985.",
  "HOME: Recovery Failed": "CĂN CỨ: Phục Hồi Thất Bại",
  "Let's get out while we can.": "Chuồn thôi khi mà chúng ta còn có thể.",
  "Studied Kickboxing": "Đã Từng Học Kickboxing"
};

const file = 'output/languages/chunks/btxt_chunk_137.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_137.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk137[r.sourceText]) {
    r.translatedText = chunk137[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 137 successfully!');
