const fs = require('fs');
const chunk114 = {
  "Sorry, I'm out.": "Xin lỗi, tôi bỏ cuộc.",
  "Extras": "Tính Năng Phụ",
  "Having a dedicated work area would let us repair weapons, do light vehicle repairs, and make some useful items.": "Có một khu vực làm việc chuyên dụng sẽ giúp chúng ta sửa chữa vũ khí, sửa chữa xe cộ hạng nhẹ và chế tạo một số vật dụng hữu ích.",
  "After scouting a building, you can use the radio to call in other community members to loot the place.": "Sau khi trinh sát một tòa nhà, bạn có thể dùng radio để gọi các thành viên khác trong cộng đồng đến dọn sạch nơi đó.",
  "Strange Voice": "Giọng Nói Lạ",
  "I'd appreciate the help getting me home.": "Tôi sẽ rất cảm kích nếu được giúp đỡ để về nhà.",
  "Hold up.": "Khoan đã.",
  "A wild and crazy guy.": "Một gã hoang dã và điên rồ.",
  "What is this, an action movie? This is C-4 we're talking about here, you can light it on fire and it won't go off. It only detonates if you hit it with an electrical current.": "Đây là cái gì, phim hành động chắc? Đây là C-4 chúng ta đang nói đến đấy, cậu có thể châm lửa đốt nó và nó sẽ không phát nổ đâu. Nó chỉ kích nổ nếu cậu đánh lửa nó bằng một dòng điện.",
  "Duke": "Duke",
  "Complete 3 Surveys. (Breakdown Level 2 or Higher)": "Hoàn thành 3 lần Khảo sát (Surveys). (Độ khó Breakdown Cấp 2 hoặc cao hơn)",
  "Officer Parsons, please take the prisoner into custody.": "Sĩ quan Parsons, vui lòng đưa tù nhân vào phòng giam.",
  "Having people on the walls is great, but if we had a watchtower it'd be easier to coordinate our defenses.": "Có người đứng canh trên tường thành thì tuyệt, nhưng nếu có một tháp canh thì sẽ dễ dàng điều phối phòng thủ hơn.",
  "Well, then, I guess we better find some pills for you two, huh?": "Chà, vậy thì tôi đoán chúng ta nên đi tìm chút thuốc cho hai người, nhỉ?",
  "The outbreak condition in Chicago has worsened to CRITICAL.\r\nORD is compromised; all official personnel are being evacuated via MDW.": "Tình trạng bùng phát dịch bệnh ở Chicago đã trở nên NGUY KỊCH.\r\nSân bay ORD đã thất thủ; toàn bộ nhân viên chính phủ đang được sơ tán qua sân bay MDW.",
  "Yeah? Why not?": "Vậy sao? Sao lại không chứ?",
  "Some extra medicine": "Một ít thuốc men bổ sung",
  "If your friend doesn't look too dicey, we'll let you in.": "Nếu bạn của cậu trông không có vẻ gì là nguy hiểm, chúng tôi sẽ cho các cậu vào.",
  "More Outposts": "Thêm Tiền Đồn",
  "I hear we spotted a feral not far away. Wouldn't want to get jumped by one of those.": "Tôi nghe nói chúng ta vừa phát hiện một con feral không xa đây. Chẳng ai muốn bị một con như thế vồ lấy đâu.",
  "Come on. I'll lead the way.": "Đi nào. Tôi sẽ dẫn đường.",
  "Aaaaand…. bang!": "Vàààà…. bùm!",
  "Special Attack": "Đòn Tấn Công Đặc Biệt",
  "Resolution 480p": "Độ phân giải 480p",
  "%1$s noticed some improper food handling. Someone could have easily gotten sick if we'd tried to cook and serve that.": "%1$s đã phát hiện ra việc xử lý thực phẩm không đúng cách. Ai đó rất dễ bị ngộ độc nếu chúng ta cố gắng nấu và dọn món đó.",
  "DECLINED: Unwelcome Guest": "TỪ CHỐI: Vị Khách Không Mời",
  "I'm getting close to an infestation.": "Tôi đang tiến gần đến một Ổ dịch (Infestation).",
  "A place to grow fresh food. A thriving crop!": "Một nơi để trồng thực phẩm tươi sạch. Một vụ mùa bội thu!",
  "The zeds are inside the perimeter!": "Lũ zed đã lọt vào trong vành đai!",
  "I... I don't think I can.": "Tôi... tôi không nghĩ mình có thể.",
  "This is just like a book I read. Well, like ten or twelve books I read.": "Chuyện này y hệt như một cuốn sách tôi đã đọc. Chà, giống như mười hay mười hai cuốn tôi từng đọc ấy.",
  "HURT: Mauled": "BỊ THƯƠNG: Bị cào cấu",
  "My callers need to be rescued. I'm not going to keep broadcasting if I'm not doing any good.": "Những người gọi cho tôi cần được giải cứu. Tôi sẽ không tiếp tục phát sóng nếu tôi không làm được việc gì có ích.",
  "Moral Objections": "Sự Phản Đối Đạo Đức",
  "We're gonna need to do something about that soon.": "Chúng ta sẽ cần phải làm gì đó về chuyện này sớm thôi.",
  "Then a quick word of advice. Pick your friends carefully, while you still have the luxury.": "Vậy thì xin có một lời khuyên chân thành. Hãy chọn bạn mà chơi cẩn thận vào, khi cậu vẫn còn đặc ân đó.",
  "Now we gotta throw out all this food because vermin got into it!": "Giờ thì chúng ta phải vứt hết đống thức ăn này vì lũ sâu bọ đã chui vào rồi!",
  "Shelby": "Shelby",
  "Yeah...I guess so.": "Ừ... tôi đoán vậy.",
  "Posit one one lima november nine nine juliett six one oscar. [message end tone]": "Tọa độ 1-1-Lima-November-9-9-Juliett-6-1-Oscar. [tiếng bíp kết thúc tin nhắn]",
  "Rank": "Cấp bậc",
  "When you deviate from orders, people die. Highroad out.": "Khi cậu làm trái lệnh, sẽ có người chết. Highroad kết thúc liên lạc.",
  "Spend INFLUENCE for extra supplies or to influence others.": "Tiêu tốn ẢNH HƯỞNG (INFLUENCE) để lấy thêm đồ tiếp tế hoặc tạo ảnh hưởng đến người khác.",
  "Spot zombies for the Army's artillery.": "Đánh dấu mục tiêu zombie cho pháo binh của Quân đội.",
  "Is this guy for real?": "Gã này đùa à?",
  "Yeah, why do you think I'm trying so hard to get the gate open?": "Chứ còn sao, cậu nghĩ tại sao tôi lại cố gắng mở cái cổng này chứ?",
  "Revolver: Anvil Hammer": "Súng lục ổ quay: Anvil Hammer",
  "So...whaddya think?": "Vậy... cậu nghĩ sao?",
  "Our resource stockpiles were running a little low so I went out to find what we needed. Mission accomplished. - %1$s.": "Kho dự trữ tài nguyên của chúng ta đang hơi cạn, nên tôi đã ra ngoài để tìm những thứ chúng ta cần. Nhiệm vụ hoàn thành. - %1$s.",
  "Advice: Upgrade to Bunkhouse": "Lời Khuyên: Nâng Cấp Lên Nhà Tập Thể (Bunkhouse)",
  "Finish it off!": "Kết liễu nó đi!",
  "Pistol: P 07 Duty": "Súng lục: P 07 Duty",
  "Surprised he hasn't French-kissed a shotgun yet.": "Ngạc nhiên là anh ta chưa hôn kiểu Pháp với một khẩu shotgun đấy.",
  "This is Highroad Actual. Greyhound One, switch to encrypted channel one-five, so we can speak freely.": "Đây là Highroad Actual. Greyhound One, chuyển sang kênh mã hóa một-năm, để chúng ta có thể nói chuyện thoải mái.",
  "The RV's gas tank is empty. We're going to have to fill her up if we want to make it out of here.": "Bình xăng chiếc RV đã cạn sạch. Chúng ta sẽ phải đổ đầy nó nếu muốn thoát khỏi đây.",
  "I'm taking you fuckers with me!": "Tao sẽ kéo theo lũ khốn chúng mày!",
  "Case of Military Ammunition": "Hòm Đạn Quân Sự",
  "Jenny": "Jenny",
  "Kathryn": "Kathryn",
  "Maybe we ought to send somebody out there. Might be able to help each other out.": "Có lẽ chúng ta nên cử ai đó ra ngoài kia. Có thể sẽ giúp đỡ lẫn nhau được đấy.",
  "No ma'am, I wouldn't call it safe yet.": "Không thưa cô, tôi sẽ không gọi nó là an toàn đâu.",
  "Reduces the chances of suicides.": "Giảm nguy cơ tự sát.",
  "We are leaving NOW.": "Chúng ta đi NGAY BÂY GIỜ.",
  "Level 4": "Cấp 4",
  "A commercial failure made famous in the movies.": "Một thất bại về mặt thương mại lại trở nên nổi tiếng trên phim ảnh.",
  "Nail Puller": "Xà beng nhổ đinh (Nail Puller)",
  "Man, this is getting to be just like Christmas. - %1$s": "Trời ạ, việc này bắt đầu giống như Giáng sinh rồi đấy. - %1$s",
  "Wants an escort to the exchange site.": "Muốn có người hộ tống đến địa điểm giao dịch.",
  "Right?": "Phải không?",
  "I always figured I'd die somewhere exotic.": "Tôi luôn nghĩ mình sẽ chết ở một nơi nào đó kỳ lạ.",
  "Will never ask \"you want fries with that?\" again.": "Sẽ không bao giờ hỏi \"quý khách có muốn thêm khoai tây chiên không?\" nữa.",
  "Find the Feral Zombie": "Tìm Con Feral Zombie",
  "Look sharp.": "Tập trung chú ý vào.",
  "Gotta cut that part out. Don't be a baby about it, it's just a knife.": "Phải cắt phần đó đi thôi. Đừng có tỏ ra yếu đuối thế, chỉ là một con dao thôi mà.",
  "Dammit, I've searched this place from top to bottom, and it's not here!": "Khỉ thật, tôi đã lục soát chỗ này từ trên xuống dưới rồi, và nó không có ở đây!",
  "We'd better do something. I've seen them leap walls like they were nothing. - %1$s.": "Tốt hơn là chúng ta nên làm gì đó. Tôi đã thấy bọn chúng nhảy qua những bức tường như không có gì cản trở. - %1$s.",
  "What, firecrackers? Yeah... yeah that should work nicely.": "Gì cơ, pháo nổ (firecrackers) sao? Ừ... ừ cách đó chắc sẽ hiệu quả đấy.",
  "MISSION: Army Activity": "NHIỆM VỤ: Hoạt Động Của Quân Đội",
  "Lily wants to show me around the church. I guess that's a good move. - %1$s": "Lily muốn dẫn tôi đi xem quanh nhà thờ. Tôi đoán đó là một ý hay. - %1$s",
  "Pistol: D 1911": "Súng lục: D 1911",
  "HISTORY: Coward and Thief": "LỊCH SỬ BẢN THÂN: Kẻ Hèn Nhát Và Trộm Cắp",
  "%2$s snores. You all know it. Not a one of you wouldn't do the same thing. - %1$s": "%2$s ngáy to quá. Tất cả các cậu đều biết chuyện đó. Bất kỳ ai trong số các cậu cũng sẽ làm vậy thôi. - %1$s",
  "Oof... thanks... I really needed that. Don't worry, I feel much better now. - %1$s": "Oof... cảm ơn... Tôi thực sự rất cần điều đó. Đừng lo, giờ tôi cảm thấy tốt hơn nhiều rồi. - %1$s",
  "Somewhere to sleep.": "Một chỗ nào đó để ngủ.",
  "Guess that's all there is to see.": "Đoán là chỉ có vậy thôi.",
  "Michele Martin died during our attempt to rescue her. Anything she might have been able to explain to us is lost. I'll have to explain this to General Connors once the helo takes off without her.": "Michele Martin đã chết trong nỗ lực giải cứu của chúng tôi. Bất cứ điều gì cô ấy có thể giải thích cho chúng tôi giờ đã mất. Tôi sẽ phải giải thích chuyện này với Tướng Connors khi trực thăng cất cánh mà không có cô ấy.",
  "Ellie": "Ellie",
  "Vehicle Gate is down, zeds are inside!": "Cửa Xe đã bị phá, lũ zed đã vào trong!",
  "You didn't think we were gonna leave you out here, did you?": "Cậu không nghĩ là chúng tôi sẽ bỏ mặc cậu ngoài này đấy chứ?",
  "%+d Community Fame": "%+d Danh Tiếng Cộng Đồng (Community Fame)",
  "Need Tools Expert.": "Cần Một Chuyên Gia Về Công Cụ.",
  "Yeah, you're a regular goddamn hero.": "Phải rồi, cậu đúng là một anh hùng khốn kiếp luôn đấy.",
  "Henry": "Henry",
  "DECLINED: Nervous Survivor": "TỪ CHỐI: Người Sống Sót Hay Căng Thẳng",
  "MISSION: Fear Itself": "NHIỆM VỤ: Nỗi Sợ Hãi",
  "Whistling Box Mines available for construction.": "Mìn Hộp Phát Âm Thanh (Whistling Box Mines) đã sẵn sàng để chế tạo.",
  "Went through more materials than usual reinforcing the wall.": "Đã sử dụng nhiều vật liệu hơn bình thường để gia cố bức tường.",
  "We'll keep you apprised. Highroad out.": "Chúng tôi sẽ báo cáo tình hình cho cô. Highroad kết thúc liên lạc.",
  "ATTITUDE: Nervous": "THÁI ĐỘ: Hay Căng Thẳng",
  "Well, we'll see how Qentin deals with it now.... - %1$s": "Chà, chúng ta hãy xem Quentin giải quyết chuyện này thế nào bây giờ.... - %1$s"
};

const file = 'output/languages/chunks/btxt_chunk_114.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_114.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk114[r.sourceText]) {
    r.translatedText = chunk114[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 114 successfully!');
