const fs = require('fs');
const chunk142 = {
  "Sorry about that. Had to deal with a little problem. I'm all ears.": "Xin lỗi về chuyện đó. Vừa phải giải quyết một vấn đề nhỏ. Tôi đang lắng nghe đây.",
  "Import Save": "Nhập File Lưu Trữ (Import Save)",
  "Trait Discovered: Storyteller": "Phát Hiện Đặc Điểm: Người Kể Chuyện",
  "No apocalypse is complete without one.": "Đéo có ngày tận thế nào là trọn vẹn nếu đéo có một cái này.",
  "Ray Santos": "Ray Santos",
  "Chase": "Chase",
  "Like they say, chance favors the prepared mind, and mine is prepared.": "Như người ta nói, cơ hội ưu ái những cái đầu đã được chuẩn bị, và tôi thì đã chuẩn bị sẵn sàng rồi.",
  "Hey look ... what's going to happen to my grades? Am I going to have to repeat this semester, or what?": "Này nghe xem... chuyện gì sẽ xảy ra với điểm số của tôi đây? Tôi sẽ phải học lại học kỳ này, hay gì?",
  "Extra firepower when you need it.": "Bổ sung thêm hỏa lực khi cậu cần.",
  "People": "Con Người",
  "At this rate I'm gonna lose half this shit before we get home!": "Cứ đà này tôi sẽ làm mất một nửa cái đống chết tiệt này trước khi chúng ta về đến nhà mất!",
  "Listen, I know you're upset, but I could really use a hand with this.": "Nghe này, tôi biết cậu đang buồn bực, nhưng tôi thực sự có thể cần một tay giúp đỡ cho việc này.",
  "Explusion always lowers your community reputation.": "Việc trục xuất luôn làm giảm danh tiếng cộng đồng của bạn.",
  "I see one.": "Tôi thấy một con.",
  "Quit trying to freeload!": "Bỏ ngay cái thói ăn bám đó đi!",
  "Getting a little cramped in here, don't you think?": "Ở trong này bắt đầu hơi chật chội rồi, cậu đéo nghĩ vậy sao?",
  "+100% construction rate. REQUIRES TOOLS EXPERT.": "+100% Tốc độ xây dựng. YÊU CẦU CHUYÊN GIA MÁY MÓC (TOOLS EXPERT).",
  "They fucked with the wrong person, huh?": "Bọn chúng đã đụng nhầm người rồi, phải đéo?",
  "This is MY LZ, bitches!": "Đây là Khu Vực Hạ Cánh (LZ) CỦA TAO, lũ khốn!",
  "Jeffrey": "Jeffrey",
  "We need medicine here anyway. You can't be sick, you understand?": "Dù sao thì chúng ta cũng cần thuốc ở đây. Cậu đéo được phép ốm, cậu hiểu đéo?",
  "One more. Better make it last.": "Còn một cái nữa. Tốt hơn là hãy để dành xài được lâu vào.",
  "I know we're all on edge, but you seem especially off.": "Tôi biết tất cả chúng ta đều đang căng thẳng, nhưng cậu có vẻ đặc biệt bất ổn.",
  "I just got a distress call from our neighbors.": "Tôi vừa nhận được một cuộc gọi cầu cứu từ những người hàng xóm của chúng ta.",
  "Thought he was gonna pop me one back there.": "Cứ tưởng ông ta sẽ cho tôi một đấm ngay lúc đó chứ.",
  "So what else did you find out? Do you know where the Army went?": "Vậy anh đã phát hiện ra điều gì khác nữa? Anh có biết Quân đội đã đi đâu đéo?",
  "ASSET PROFILE: Dr. Dan Bogatz": "HỒ SƠ TÀI SẢN (ASSET PROFILE): Bác sĩ Dan Bogatz",
  "Shotgun: A12 Custom": "Súng shotgun: A12 Custom",
  "Valeria": "Valeria",
  "Next Point of Interest": "Điểm Đáng Chú Ý Tiếp Theo",
  "%s can't accompany you right now. (%s)": "%s đéo thể đi cùng bạn ngay lúc này. (%s)",
  "Come on, it'll be fun! Take out some of your aggression. Blow off steam. Trust me, this baby can take it.": "Thôi nào, sẽ vui lắm đấy! Giải tỏa bớt cơn giận của cậu đi. Xả stress đi nào. Tin tôi đi, em bé này có thể chịu đựng được mà.",
  "I don't know how long they'll be gone, but I can tell you where to look.": "Tôi đéo biết họ sẽ đi trong bao lâu, nhưng tôi có thể chỉ cho cậu biết nơi để tìm.",
  "To keep every soldier in top physical form.": "Để giữ cho mọi binh lính luôn ở trạng thái thể chất tốt nhất.",
  "103 STORY Aaron Felder": "103 STORY Aaron Felder",
  "Died": "Đã Chết",
  "Let's get this over with.": "Hãy giải quyết xong chuyện này thôi.",
  "Oh no... I'm gonna have to tell Jacob.": "Ôi đéo... Tôi sẽ phải nói với Jacob chuyện này.",
  "I think we should clear out some space specifically for medical treatment.": "Tôi nghĩ chúng ta nên dọn dẹp một không gian dành riêng cho việc điều trị y tế.",
  "I mean, as loud as this thing is, we'll have every zed from here to Danforth on us.": "Ý tôi là, với cái thứ to mồm này, chúng ta sẽ kéo mọi con zed từ đây đến Danforth nhào vào chúng ta mất.",
  "I'm headed back with the goods.": "Tôi đang quay về với số hàng hóa đây.",
  "Enables full vehicle repair.": "Cho phép sửa chữa phương tiện hoàn toàn.",
  "Your helivac will touch down soon.": "Trực thăng di tản của các anh sẽ sớm hạ cánh.",
  "Good. Nothing serious then.": "Tốt. Vậy là đéo có gì nghiêm trọng.",
  "Don't worry, Mom, I'll be home by curfew.": "Đừng lo, Mẹ, con sẽ về nhà trước giờ giới nghiêm.",
  "Bagged any big ones lately?": "Dạo này có săn được con nào bự chảng đéo?",
  "All right, we were saying?": "Được rồi, chúng ta đang nói đến đâu nhỉ?",
  "I haven't had a new caller in a while. I don't even know if you can hear me.": "Lâu rồi tôi đéo có người gọi mới nào. Tôi thậm chí đéo biết cậu có thể nghe thấy tôi hay đéo.",
  "Oh, the one that's completely full of zeds. Perfect.": "Ồ, cái nơi mà chứa đầy đặc lũ zed đó á. Hoàn hảo.",
  "Ah, the damn generator's on the fritz again. You know, I think I'll actually be glad when the fresh food's gone and we can turn these refrigerators off.": "À, cái máy phát điện chết tiệt lại dở chứng nữa rồi. Cậu biết đấy, tôi nghĩ mình thực sự sẽ thấy vui vẻ hơn khi đồ ăn tươi hết sạch và chúng ta có thể tắt mấy cái tủ lạnh này đi.",
  "Well, that just about oughta do it.": "Chà, như vậy là đủ rồi đấy.",
  "We've packed everyone up and moved back into the Church of the Ascension. - %1$s": "Chúng tôi đã đóng gói đồ đạc cho mọi người và chuyển về Nhà thờ Thăng Thiên (Church of the Ascension). - %1$s",
  "70 GENERIC Adam Robertson": "70 GENERIC Adam Robertson",
  "Specializes in Mexican/Indian fusion cuisine.": "Chuyên về ẩm thực kết hợp (fusion) Mexico/Ấn Độ.",
  "Help Ray with a delivery.": "Giúp Ray trong một chuyến giao hàng.",
  "Head to the survey point.": "Đi đến điểm quan sát (survey point).",
  "There are NO USABLE ITEMS in your inventory.": "KHÔNG CÓ VẬT PHẨM NÀO CÓ THỂ SỬ DỤNG ĐƯỢC (NO USABLE ITEMS) trong hành trang của bạn.",
  "63 GENERIC Janet Weiss": "63 GENERIC Janet Weiss",
  "Bout time you showed up. Let's get this show on the road. You're the newbie, so you get to bust in the window.": "Cũng đến lúc cậu xuất hiện rồi. Hãy bắt đầu cuộc vui nào. Cậu là lính mới, nên cậu sẽ nhận phần đập vỡ cửa sổ.",
  "What? Wait, of course he is. Who isn't dead right now.": "Cái gì? Khoan đã, tất nhiên là ổng chết rồi. Giờ thì ai mà chẳng chết cơ chứ.",
  "BUILT: Barracks": "ĐÃ XÂY DỰNG: Doanh Trại",
  "Black Friday, we just observed an explosion in your area. Looks like a air-to-surface missile, but ... we can't identify the source.": "Black Friday, chúng tôi vừa quan sát thấy một vụ nổ trong khu vực của các anh. Trông giống như một tên lửa đạn đạo không đối đất, nhưng ... chúng tôi đéo thể xác định được nguồn gốc.",
  "Bonus XP from Firearms Training!": "Nhận XP Thưởng từ việc Huấn Luyện Súng Cầm Tay!",
  "Assault Rifle: AK47 Custom": "Súng trường tấn công: AK47 Custom",
  "Oh, do you see that?": "Ồ, cậu có thấy cái đó đéo?",
  "Just happy to be alive.": "Chỉ thấy hạnh phúc vì vẫn còn sống.",
  "This ain't as easy as it looks!": "Trò này đéo dễ như cậu tưởng đâu!",
  "Jess": "Jess",
  "Having a tough time? How about you and me take a walk?": "Gặp khó khăn hả? Hay là cậu và tôi cùng đi dạo một chút nhỉ?",
  "Metal Oar": "Mái Chèo Kim Loại (Metal Oar)",
  "Has that classic cowboy flavor.": "Mang đậm phong cách cao bồi cổ điển.",
  "Junk": "Rác Rưởi",
  "Resource Report": "Báo Cáo Tài Nguyên",
  "Those things are toxic. - %1$s": "Những thứ đó rất độc hại. - %1$s",
  "Thanks. I feel a lot more confident now.": "Cảm ơn. Bây giờ tôi cảm thấy tự tin hơn nhiều rồi.",
  "You keep this up and I'm gonna have a total girl-boner for you.": "Cậu cứ tiếp tục thế này là tôi sẽ có một cơn nứng (girl-boner) hoàn toàn dành cho cậu đấy.",
  "Advice: Upgrade to Machine Shop": "Lời Khuyên: Nâng Cấp Lên Xưởng Cơ Khí (Machine Shop)",
  "Send a runner, willya?": "Cử một người chạy việc (runner) tới đây, được chứ?",
  "Come find me now!": "Đến tìm tôi ngay!",
  "Come on. I'll give you the nickel tour.": "Đi nào. Tôi sẽ dẫn cậu đi tham quan qua loa.",
  "A top-notch workshop with a wide variety of tools and equipment.": "Một xưởng làm việc đỉnh cao với đa dạng các loại công cụ và thiết bị.",
  "Is that an infestation?": "Đó có phải là một ổ dịch đéo?",
  "Concerned that this problem persists.": "Lo ngại rằng vấn đề này vẫn còn tiếp diễn.",
  "Why does he call everybody \"Boss?\"": "Tại sao hắn lại gọi mọi người là \"Sếp\" chứ?",
  "Hiatt": "Hiatt",
  "Did you hear that? I heard it! No more broadcasts!": "Cậu có nghe thấy đéo? Tôi đã nghe thấy! Đéo còn sóng phát thanh nào nữa!",
  "Is it wrong to think this is better than my shitty old job?": "Liệu có sai đéo khi nghĩ rằng cái này còn tốt hơn cả công việc cũ chết dẫm của tôi?",
  "Build Library": "Xây Dựng Thư Viện",
  "That... that's a lot of zombies.": "Đó... đó là một bầy zombie khổng lồ.",
  "I'm not mad. I'm just disappointed.": "Tôi đéo điên. Tôi chỉ cảm thấy thất vọng thôi.",
  "Coffey": "Coffey",
  "Wanna have some fun? Like shooting zed in a barrel.": "Muốn vui vẻ chút đéo? Dễ như bắn zed trong thùng phuy vậy.",
  "Crush the skull, cleave the brain, sever the head. Keep at it and in no time you'll be a Self-Defense expert.": "Nghiền nát hộp sọ, chẻ đôi bộ não, chặt đứt cái đầu. Hãy cứ luyện tập tiếp đi và chẳng mấy chốc cậu sẽ trở thành một chuyên gia Tự Vệ (Self-Defense) cho xem.",
  "Kill 100 Zombies with FIRE. (Breakdown Level 2 or Higher)": "Tiêu diệt 100 Zombie bằng LỬA. (Breakdown Cấp độ 2 trở lên)",
  "Gotcha, you son of a bitch!": "Bắt được mày rồi, đồ chó đẻ!",
  "Move your ass, soldier!": "Di chuyển cái mông đi, người lính!",
  "Rubbing Alcohol": "Cồn Xoa Bóp",
  "Better go help Doc Hanson, we can't afford to lose his expertise. -%1$s": "Tốt hơn là nên đi giúp Bác sĩ Hanson đi, chúng ta đéo thể để mất chuyên môn của ông ấy được. -%1$s",
  "Gotta slow down and aim.": "Phải chậm lại và ngắm bắn.",
  "Potential Home Base": "Căn Cứ Tiềm Năng"
};

const file = 'output/languages/chunks/btxt_chunk_142.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_142.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk142[r.sourceText]) {
    r.translatedText = chunk142[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 142 successfully!');
