const fs = require('fs');
const chunk186 = {
  "The only thing that's ever gonna change is when the last of us finally die and there's nothing left on the planet but the zombies. - %1$s": "Điều duy nhất có thể thay đổi cục diện này đó là khi người cuối cùng trong số chúng ta phải chết và sẽ đéo còn lại thứ gì trên hành tinh này ngoài bọn zombies. - %1$s",
  "Just calm down. We'll find him.": "Cứ bình tĩnh lại đi. Chúng ta sẽ tìm thấy anh ta thôi.",
  "Doc, I could use some medical advice here.": "Bác sĩ (Doc), tôi có thể cần đến một vài lời khuyên y tế (medical advice) ở đây đấy.",
  "Shit, we got a zombie horde!": "Chết tiệt, chúng ta đụng độ phải một bầy zombie (horde) rồi!",
  "You sure you want to split up?": "Cậu có chắc là cậu muốn chia nhau ra đéo?",
  "Womack": "Womack",
  "As a kid, I used to wonder what was inside a squirrel.": "Khi còn là một đứa trẻ, tôi đã từng tự hỏi bên trong cơ thể của một con sóc (squirrel) có chứa những gì.",
  "Some pretty scary shit going on out here, huh?": "Có vài chuyện khốn khiếp khá là đáng sợ đang xảy ra ở ngoài này đấy, đúng đéo?",
  "Slow down, tough guy, this ain't no action movie.": "Chậm lại đi, anh bạn cứng rắn à, đây đéo phải là một bộ phim hành động (action movie) đâu.",
  "JOURNAL: Hangovers and Halibut": "NHẬT KÝ (JOURNAL): Những Cơn Say Xỉn (Hangovers) Và Cá Bơn (Halibut)",
  "Where's my goddamn backup?!": "Lực lượng chi viện chết tiệt của tôi đang ở đâu cmnr?!",
  "Random Character": "Nhân vật ngẫu nhiên (Random Character)",
  "Office": "Văn Phòng Của Trưởng Khu (Office)",
  "They let about six of them loose on us. You don't really know how fast a dog can be till it's going for your throat.": "Bọn chúng đã thả khoảng sáu con trong số đó xông về phía chúng tôi. Cậu sẽ đéo bao giờ thực sự biết được một con chó có thể nhanh đến mức nào cho đến khi nó lao thẳng vào cổ họng của cậu.",
  "Are you finished?": "Cậu đã nói xong chưa?",
  "Hey, newsflash dipshit. If we didn't make so much noise, we wouldn't draw so much attention.": "Này, bản tin khẩn cấp dành cho thằng đần (dipshit) nhé. Nếu chúng ta đéo tạo ra quá nhiều tiếng ồn, thì chúng ta sẽ đéo thu hút nhiều sự chú ý đến thế đâu.",
  "Tense. People are starting to get antsy what with the crowding and all.": "Đang rất Căng Thẳng (Tense). Mọi người đang bắt đầu trở nên bồn chồn lo lắng với sự đông đúc và tất cả mọi chuyện.",
  "I don't know. What do you think?": "Tôi đéo biết. Cậu nghĩ sao?",
  "COMPLETED: The Vet Clinic": "ĐÃ HOÀN THÀNH: Phòng Khám Thú Y (The Vet Clinic)",
  "Even I wouldn't touch that.": "Ngay cả bản thân tôi cũng sẽ đéo đụng vào thứ đó đâu.",
  "We can't let these things fester. How about helping us clear out an infestation?": "Chúng ta đéo thể để cho những thứ rác rưởi này thối rữa (fester) ở đây được. Cậu giúp chúng tôi dọn dẹp sạch sẽ một Ổ Dịch (infestation) được đéo?",
  "Eden": "Eden",
  "Yes! I cracked the signal! Let's see what people are saying.": "Đúng rồi! Tôi đã bẻ khóa được tín hiệu (cracked the signal) cmnr! Hãy cùng xem thử mọi người đang bàn tán về chuyện gì nào.",
  "We'd better start gathering supplies now.": "Tốt hơn hết là chúng ta nên bắt đầu thu thập thêm đồ tiếp tế (supplies) ngay từ bây giờ.",
  "Who else wants some of this?": "Còn kẻ đéo nào muốn nếm thử mùi vị của cái thứ này nữa đéo?",
  "Made it to the top. Gonna look around now.": "Đã lên được tới đỉnh cmnr. Bây giờ tôi sẽ quan sát xung quanh xem thế nào.",
  "Grab it!": "Lấy nó đi!",
  "CLEANED: Latrine": "ĐÃ DỌN DẸP SẠCH SẼ: Nhà Vệ Sinh Công Cộng (Latrine)",
  "We're not done back here!": "Chúng ta vẫn chưa xong việc ở chỗ này đâu!",
  "Just out of high school, with all the coach's training still fresh on the brain. (Fitness Expert)": "Chỉ vừa mới tốt nghiệp trường trung học (high school), với tất cả những bài huấn luyện của huấn luyện viên vẫn còn in hằn in sâu trong tâm trí. (Chuyên Gia Thể Hình - Fitness Expert)",
  "Local boy who moved off to the big city, but still comes back to visit every year.": "Một chàng trai địa phương đã chuyển đến sống ở thành phố lớn, nhưng vẫn quay trở lại nơi này để thăm viếng vào mỗi năm.",
  "Time to grab the good stuff!": "Đã đến lúc để nhặt lấy những món đồ tốt rồi!",
  "Is there anything I can help with?": "Tôi có thể giúp ích được gì đéo?",
  "Well… we got one option, at least. Might be more out there if you look around.": "Chà… ít nhất thì chúng ta cũng có được một sự lựa chọn. Có thể sẽ còn có nhiều hơn ở ngoài đó nếu cậu chịu khó tìm kiếm xung quanh.",
  "Jesus. I'm on my way.": "Chúa ơi. Tôi đang đến ngay đây.",
  "We got something really special you should check out. (It's a goddamn M60E4!) - Mickey Wilkerson": "Chúng tôi có một thứ vô cùng đặc biệt mà cậu nên đến xem thử đấy. (Đó là một khẩu súng M60E4 chết tiệt!) - Mickey Wilkerson",
  "Rescue The Missing": "Giải Cứu Những Người Bị Mất Tích",
  "Followed the News": "Đã Từng Theo Dõi Các Bản Tin Tức (News)",
  "Goddamn roof's leaking.": "Cái mái nhà khốn kiếp này đang bị dột cmnr.",
  "I let him down.": "Tôi đã khiến anh ta phải thất vọng rồi.",
  "Lead the Way": "Dẫn Đường",
  "Now every time we lose somebody, all I can think is \"God, I hope I don't have to shoot them in the head.\"": "Giờ đây mỗi khi chúng ta mất đi một người nào đó, tất cả những gì tôi có thể nghĩ đến chỉ là \"Chúa ơi, tôi hy vọng là mình sẽ đéo phải bắn vào đầu bọn họ.\"",
  "Showed %3$s and their people some survival tips. They were happy to trade some supplies for the information. -%1$s": "Đã chỉ cho %3$s và nhóm người của bọn họ một vài mẹo để sinh tồn. Bọn họ rất sẵn lòng trao đổi một số đồ tiếp tế để lấy những thông tin đó. -%1$s",
  "Ugh, you smell that?": "Ugh, cậu có ngửi thấy cái mùi đó đéo?",
  "There are a lotta hungry mouths out there, human and... otherwise. Lotta hungry mouths.": "Có rất nhiều cái miệng đang đói khát ở ngoài kia, con người và... những thứ khác. Rất nhiều những cái miệng đang đói khát.",
  "I brought some more food.": "Tôi đã mang về thêm một ít thức ăn (food).",
  "We nailed it.": "Chúng ta đã làm được điều đó cmnr.",
  "Yeah, yeah, I know, setting zombies on fire is fun, but come on. There's other ways to put them down.": "Ừ, ừ, tôi biết, thiêu rụi bọn zombies bằng lửa (fire) rất là vui, nhưng thôi nào. Vẫn còn có những cách khác để hạ gục bọn chúng mà.",
  "Allows you to prepare Feasts in your Kitchen.": "Cho phép bạn chuẩn bị các Bữa Tiệc Lớn (Feasts) trong cơ sở Nhà Bếp (Kitchen) của mình.",
  "I'm a surgeon, I didn't have time to listen to Tom's obsessive theories.": "Tôi là một bác sĩ phẫu thuật (surgeon), tôi đéo có thời gian để lắng nghe những giả thuyết ám ảnh của Tom đâu.",
  "Dude, I know we don't have an infirmary here, but do you have to change those nasty-ass bandages in public? Some of us are trying to eat! -%1$s": "Anh bạn, tôi biết chúng ta đéo có bệnh xá (infirmary) ở đây, nhưng cậu có nhất thiết phải thay những cái băng gạc bẩn thỉu rác rưởi đó ở nơi công cộng đéo? Vài người trong số chúng tôi đang cố gắng để ăn đấy! -%1$s",
  "If it weren't for bad luck …": "Nếu như đéo phải là do quá xui xẻo (bad luck) …",
  "Hey, come on, you can turn this around.": "Này, thôi nào, cậu có thể lật ngược tình thế (turn this around) được mà.",
  "A BRAND NEW CAR!": "MỘT CHIẾC XE Ô TÔ HOÀN TOÀN MỚI!",
  "Stay back! We will open fire!": "Lùi lại đi! Chúng tôi sẽ nổ súng đấy!",
  "DISCOVERED: Desperate Survivors": "ĐÃ KHÁM PHÁ (DISCOVERED): Những Người Sống Sót Tuyệt Vọng",
  "Well, let's get it finished, quick. Last thing I want is to see you get bored.": "Chà, hãy giải quyết xong chuyện này, nhanh lên nào. Điều cuối cùng mà tôi muốn là phải nhìn thấy bộ dạng buồn chán của cậu đấy.",
  "Mk2 Grenade": "Lựu Đạn Mk2 (Grenade)",
  "COMPLETED: Home Sweet Home": "ĐÃ HOÀN THÀNH: Ngôi Nhà Thân Yêu (Home Sweet Home)",
  "We're all scared. That's no excuse to not do your damn job.": "Tất cả chúng ta đều đang rất sợ hãi. Đó đéo phải là một lý do để cậu đéo làm cái công việc chết tiệt của mình.",
  "Call in a favor to bring in a squad of mercenaries to back you up in a pinch.": "Yêu cầu một sự giúp đỡ (favor) để đưa đến một đội lính đánh thuê (mercenaries) nhằm hỗ trợ chi viện cho bạn trong những tình huống nguy cấp.",
  "Crisis Averted": "Cuộc Khủng Hoảng Đã Bị Ngăn Chặn (Crisis Averted)",
  "Our head count's coming up short. Can you help us look?": "Số lượng người của chúng tôi đang bị thiếu hụt đi một chút. Cậu có thể giúp chúng tôi đi tìm bọn họ đéo?",
  "Clear.": "Khu vực đã an toàn.",
  "We have more MEDICINE than we'll be able to store. - %1$s": "Chúng ta có quá nhiều THUỐC MEN (MEDICINE) hơn cả mức mà chúng ta có khả năng lưu trữ. - %1$s",
  "Refills some brass to generate a few magazines' worth of 5.56mm ammunition.": "Nạp lại một số lượng vỏ đạn đồng (brass) để chế tạo ra lượng đạn dược 5.56mm tương đương với vài băng đạn.",
  "MISSION: The Armory": "NHIỆM VỤ (MISSION): Kho Vũ Khí (The Armory)",
  "I guess we'll just have to get you back alive, then, huh?": "Tôi đoán là chúng tôi sẽ phải đưa cậu trở về trong tình trạng còn sống sót, đúng vậy đéo hả?",
  "Must be a problem with the detonator.": "Chắc là có vấn đề đéo gì đó với cái kíp nổ (detonator) rồi.",
  "Adds a weapons-training course to keep soldiers' proficiency with firearms up to par.": "Bổ sung thêm một khóa huấn luyện về vũ khí (weapons-training) để luôn giữ cho mức độ thông thạo súng ống của binh lính đạt đúng tiêu chuẩn.",
  "Ah, this is silly, she's probably just a recording. But thank you.": "Ah, chuyện này thật ngớ ngẩn, cô ấy có lẽ chỉ là một đoạn băng ghi âm (recording) mà thôi. Nhưng vẫn xin cảm ơn.",
  "So much for your barricades, boy! Let's smoke these assholes!": "Mấy cái rào chắn của tụi mày chỉ đến thế mà thôi, nhóc con! Hãy cùng xử lý bọn khốn này nào!",
  "No, Sergeant. No way.": "Đéo, thưa Trung Sĩ. Đéo đời nào.",
  "Nieminen": "Nieminen",
  "Survivors rescued.": "Những người sống sót (Survivors) đã được giải cứu.",
  "Yup, let's get folks moved over here.": "Yup, hãy đưa những người khác chuyển đến đây nào.",
  "Yeah. Or...": "Ừ. Hoặc là...",
  "Mariah": "Mariah",
  "Literature": "Môn Văn Học (Literature)",
  "It seems we are to suffer as many plagues as Egypt.": "Có vẻ như chúng ta đang phải gánh chịu nhiều tai ương đại dịch (plagues) giống như ở Ai Cập vậy.",
  "RAY SANTOS. Delivers a random car near you.": "RAY SANTOS. Giao đến một chiếc xe ô tô (car) ngẫu nhiên ở khu vực gần bạn.",
  "+50": "+50",
  "We could really hold out here for a while; just need enough people to guard the walls. - %1$s": "Chúng ta thực sự có thể bám trụ (hold out) ở nơi này trong một khoảng thời gian; chỉ cần có đủ số người để đứng canh gác cho những bức tường. - %1$s",
  "Wait ... you're here to rescue her? Who is she?": "Khoan đã ... cậu đến đây để giải cứu cô ấy sao? Cô ấy là ai vậy?",
  "Rashida": "Rashida",
  "Hey, cute girl with the phone! We're here to rescue you!": "Này, cô gái dễ thương đang cầm chiếc điện thoại kia! Chúng tôi đến đây để giải cứu cô đây!",
  "Hey, we actually pulled that one off!": "Này, chúng ta thực sự đã vượt qua được chuyện đó rồi!",
  "Who's going to clear my LZ?": "Kẻ đéo nào sẽ dọn dẹp sạch sẽ bãi đáp LZ cho tao đây hả?",
  "Yeah, we could use more hands.": "Ừ, chúng ta có thể sẽ cần thêm người giúp một tay đấy.",
  "Let's not get too cocky.": "Đừng có tỏ ra quá kiêu ngạo huênh hoang (cocky).",
  "Move it out, right now!": "Hãy di chuyển ra ngoài đi, ngay bây giờ!",
  "Rifle: SKS Survivor": "Súng Trường (Rifle): SKS Survivor",
  "I guess I'll just wait until your worshipfulness is ready, then.": "Tôi đoán là tôi sẽ phải chờ đợi cho đến khi sự tôn sùng (worshipfulness) của cậu đã sẵn sàng, vậy nhé.",
  "Run over 250 zombies.": "Cán chết 250 bọn zombies.",
  "Come on! Come on!": "Nhanh lên nào! Lại đây nào!",
  "MATERIALS are needed for construction and to keep our home secure.": "VẬT LIỆU XÂY DỰNG (MATERIALS) rất cần thiết cho các công trình xây dựng (construction) và để giữ cho ngôi nhà của chúng ta luôn được an toàn tuyệt đối.",
  "A few extra MREs": "Thêm một vài phần khẩu phần ăn quân sự MRE",
  "You cannot switch to someone who is DEAD.": "Bạn đéo thể chuyển sang (switch) một nhân vật đã CHẾT cmnr (DEAD).",
  "No Storage Device": "Đéo Có Thiết Bị Lưu Trữ Nào Cả",
  "Very heavy, precise artillery strikes.": "Những cuộc không kích pháo binh (artillery strikes) rất nặng nề và chính xác."
};

const file = 'output/languages/chunks/btxt_chunk_186.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_186.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk186[r.sourceText]) {
    r.translatedText = chunk186[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 186 successfully!');
