const fs = require('fs');
const chunk185 = {
  "You guys want to shut up before you pull even more zeds down on us?": "Mấy người có muốn ngậm mồm lại trước khi kéo thêm nhiều bọn zeds đến chỗ chúng ta nữa hay đéo hả?",
  "[reassuring] Yeah, be home soon.": "[trấn an] Ừ, sẽ về nhà sớm thôi.",
  "Cuts down gunshot noise. Decent construction; this one should last 30 shots, give or take.": "Giảm bớt tiếng ồn của súng khi bắn. Cấu tạo khá ổn; cái này sẽ dùng được trong khoảng 30 phát súng, ít hoặc nhiều hơn một chút.",
  "Dammit, get it together!": "Chết tiệt, lấy lại tinh thần đi nào!",
  "We got a Screamer, and close by.": "Chúng ta có một con Screamer, và nó đang ở rất gần đây.",
  "130 HERO Carl Parsons": "130 NGƯỜI HÙNG (HERO) Carl Parsons",
  "I tried to tell %1$s not to go for that trade mission, but would they listen? - %2$s": "Tôi đã cố gắng nói với %1$s là đéo nên đi thực hiện cái nhiệm vụ giao thương (trade mission) đó, nhưng bọn họ có thèm nghe đéo? - %2$s",
  "We're gonna have to leave the valley, aren't we? I mean we can't keep drinking this.": "Chúng ta sẽ phải rời khỏi thung lũng (valley), đúng đéo? Ý tôi là chúng ta đéo thể nào cứ tiếp tục uống cái thứ nước này được.",
  "Christ, man, what I wouldn't give for some electric lighting. Maybe a hot shower. We ought to hook up a generator.": "Lạy Chúa, anh bạn, tôi đéo biết mình sẽ phải đánh đổi những thứ gì để có được ánh sáng của đèn điện (electric lighting). Có thể là một vòi sen tắm nước nóng. Chúng ta nên kết nối với một cái máy phát điện (generator).",
  "We're lucky we've got so many building materials.": "Chúng ta thật may mắn vì đã có được rất nhiều vật liệu xây dựng (building materials).",
  "Outposts": "Các Tiền Đồn (Outposts)",
  "I'd rather have a bottle in front of me than a frontal lobotomy. (Improves wits slowly.)": "Tôi thà có một cái chai ở ngay trước mặt mình còn hơn là bị phẫu thuật thùy trán. (Giúp cải thiện sự nhạy bén wits từ từ.)",
  "SURVIVAL TACTICS: Injury Recovery": "CHIẾN THUẬT SINH TỒN (TACTICS): Phục Hồi Chấn Thương (Injury Recovery)",
  "Deliver the Goods": "Giao Hàng",
  "How about some backup?": "Một chút chi viện thì sao nhỉ?",
  "Earn 25 Headshot Streaks. (5 Headshots in a Row - Breakdown Level 4 or Higher)": "Đạt được Chuỗi 25 Phát Bắn Trúng Đầu (Headshot). (5 Headshots Liên Tiếp - Cấp Độ Sụp Đổ Breakdown Level từ 4 trở lên)",
  "You get him home safe, and drinks are on me when you get back.": "Cậu hãy đưa cậu ta về nhà an toàn đi, chầu nhậu này sẽ do tôi mời (drinks are on me) khi cậu quay trở lại.",
  "You feel like taking a little stroll? One of our supply runners is overdue by almost a day.": "Cậu có muốn đi dạo một chút đéo? Một trong những người chạy tiếp tế (supply runners) của chúng ta đã đi quá thời hạn mất gần một ngày rồi.",
  "Now I'm not so sure.": "Bây giờ thì tôi đéo còn chắc chắn cho lắm.",
  "142 NPC Soldier": "142 NPC Binh Lính (Soldier)",
  "Dr. Hall was able to provide us with biological samples he obtained from human cadavers just prior to the outbreak. He saw suspicious behavior in their blood, but failed to report his findings to anyone besides Dr. Horn.": "Bác sĩ Hall đã có thể cung cấp cho chúng ta các mẫu vật sinh học (biological samples) mà ông ấy thu thập được từ những xác chết của con người ngay trước khi dịch bệnh bùng phát. Ông ấy đã nhìn thấy những biểu hiện đáng ngờ trong máu của bọn họ, nhưng lại đéo báo cáo những phát hiện của mình cho bất kỳ ai khác ngoại trừ Bác sĩ Horn.",
  "Did you see me out there today? I don't mean to brag, but let me just put it this way: There was one point, I'm just looking at this pile of zeds and realizing I actually impressed myself. And that isn't easy. -%1$s.": "Mọi người có nhìn thấy tôi ngoài đó ngày hôm nay đéo? Tôi đéo có ý khoe khoang (brag) đâu, nhưng để tôi nói theo cách này nhé: Đã có một lúc, tôi chỉ nhìn chằm chằm vào cái đống xác zeds này và nhận ra rằng bản thân mình đã thực sự gây ấn tượng với chính mình. Và điều đó đéo hề dễ dàng chút nào. -%1$s.",
  "Briana": "Briana",
  "Be sure you're ready to kill the Juggernaut with a melee weapon.": "Hãy chắc chắn rằng bạn đã sẵn sàng để tiêu diệt con Juggernaut bằng một món vũ khí cận chiến (melee weapon).",
  "General": "Chung (General)",
  "Look, you need to follow me, right now!": "Nghe này, cậu cần phải đi theo tôi, ngay bây giờ!",
  "We’re going to have to fix the tires on the RV. Maybe even replace them.": "Chúng ta sẽ phải sửa lại những chiếc lốp xe trên chiếc RV này. Có thể thậm chí còn phải thay thế chúng.",
  "Have you considered the lessons in the Book of Matthew? Matthew says--": "Các cậu đã từng suy ngẫm về những bài học trong Sách Phúc Âm Matthew chưa? Matthew nói rằng--",
  "Cannibal Family Picnic": "Chuyến Dã Ngoại Của Gia Đình Ăn Thịt Người",
  "PERSONAL SKILL. What's your poison? TexMex? Sushi? Indian/Guatemalan fusion? Or maybe just the perfect cheeseburger?": "KỸ NĂNG CÁ NHÂN (PERSONAL SKILL). Độc tố của bạn là gì? TexMex? Sushi? Ẩm thực kết hợp giữa Ấn Độ và Guatemala? Hay có thể chỉ là một chiếc bánh mì kẹp phô mai (cheeseburger) hoàn hảo?",
  "A bunch of them are talking about some new disease that's been hitting their people.": "Một nhóm người trong số bọn họ đang bàn tán về một căn bệnh mới đang tấn công mọi người.",
  "Go ahead.": "Tiếp tục đi.",
  "A piece of metal lodged in the body as a result of an explosion or zombie attack. (Health penalty)": "Một mảnh kim loại bị găm vào trong cơ thể do hậu quả của một vụ nổ hoặc một cuộc tấn công của zombie. (Phạt điểm Sinh Lực Health)",
  "Are we ready to move?": "Chúng ta đã sẵn sàng để di chuyển chưa?",
  "I can't do this right now.": "Tôi đéo thể làm chuyện này ngay bây giờ được.",
  "East Gate Breached": "Cổng Phía Đông (East Gate) Đã Bị Phá Vỡ",
  "Thought %1$s was a goner out there, but I guess it looked worse than it was. We patched it up with a little medicine, should be fine in no time. -%2$s": "Cứ tưởng %1$s chắc chắn đã tiêu tùng cmnr ở ngoài kia, nhưng tôi đoán là tình trạng của nó trông có vẻ tệ hơn so với thực tế. Chúng tôi đã băng bó cho nó bằng một ít thuốc (medicine), chắc là sẽ ổn ngay thôi. -%2$s",
  "Well folks, the line has gone dead. Our caller is gone.": "Chà các bạn à, đường dây đã bị ngắt. Người gọi của chúng ta đã biến mất.",
  "Shit, the zombies are welcome to that place. The rats'll probably eat them.": "Chết tiệt, bọn zombies được chào đón đến cái nơi đó đấy. Lũ chuột (rats) có lẽ sẽ ăn thịt luôn bọn chúng cho xem.",
  "Zombie apocalypse? Whatever. Try raising five kids.": "Ngày tận thế zombie (Zombie apocalypse) á? Sao cũng được. Cứ thử nuôi nấng năm đứa trẻ con đi rồi biết.",
  "Way to go! People will be psyched to hear about this.": "Tuyệt lắm (Way to go)! Mọi người sẽ cực kỳ phấn khích (psyched) khi nghe được chuyện này cho xem.",
  "There's a good library here. Just need to clear out all the chaos and we can start using it.": "Có một thư viện (library) khá tốt ở đây. Chỉ cần dọn dẹp sạch sẽ mọi mớ hỗn độn (chaos) là chúng ta đã có thể bắt đầu sử dụng nó được rồi.",
  "Come with me. You need to get out of your head for a little while.": "Đi với tôi. Cậu cần phải thoát khỏi những suy nghĩ trong đầu mình một chút.",
  "We got armored zeds!": "Chúng ta có bọn armored zeds kìa!",
  "Sure. Now, you decide that doesn't sit right with you, the door's right there. Now you just remember what's on the other side of it.": "Chắc chắn rồi. Bây giờ, nếu cậu cảm thấy đéo đồng tình với chuyện đó (doesn't sit right with you), thì cánh cửa đang ở ngay đằng kia kìa. Giờ thì cậu chỉ cần nhớ những gì đang chờ đợi ở phía bên kia cánh cửa thôi.",
  "Dr. Nancy": "Bác sĩ Nancy",
  "Alright. Have a safe trip back.": "Được rồi. Đi đường bình an nhé (safe trip).",
  "Ehh, that's nothing.": "Ehh, cũng đéo có gì to tát cả.",
  "Codeine": "Codein",
  "Not now.": "Đéo phải bây giờ.",
  "Little busy here.": "Hơi bận một chút rồi.",
  "\"%1$s\" has stalled.": "\"%1$s\" đã bị đình trệ (stalled).",
  "Y'know, it takes a lot of construction materials to keep a base in good shape.": "Cậu biết đấy, cần phải có rất nhiều vật liệu xây dựng (construction materials) thì mới có thể giữ cho một căn cứ (base) luôn ở trong tình trạng tốt được.",
  "This... this is my fault. If I'd been there to help them, maybe....": "Chuyện này... chuyện này là lỗi của tôi. Nếu tôi ở đó để giúp đỡ bọn họ, có lẽ....",
  "SET UP: Bedroom": "THIẾT LẬP: Phòng Ngủ",
  "Allows upgrade of Workshop to Munitions Shop.": "Cho phép nâng cấp Xưởng Chế Tạo (Workshop) lên thành Xưởng Đạn Dược (Munitions Shop).",
  "Bonus XP from Combat Training!": "Thưởng Điểm XP từ việc Huấn Luyện Chiến Đấu (Combat Training)!",
  "We've taken down a few.": "Chúng ta đã hạ gục được một vài tên rồi.",
  "Michele Martin is on the way to the capital.": "Michele Martin đang trên đường (on the way) tới thủ đô.",
  "Kill your friend.": "Tiêu diệt người bạn của cậu đi.",
  "But it looks like it's also made donations to projects in Iran, China, Venezuela ... and the deeper we look, the shadier it gets.": "Nhưng có vẻ như nó cũng đã từng quyên góp (donations) cho các dự án ở Iran, Trung Quốc, Venezuela ... và càng tìm hiểu sâu hơn, mọi chuyện lại càng trở nên mờ ám hơn (shadier).",
  "Somebody shoot something!": "Ai đó hãy bắn cái con khốn đó đi!",
  "That's not gonna work.": "Làm như vậy đéo có tác dụng gì đâu.",
  "When zombies learn to drive, then I'll worry.": "Khi nào bọn zombies học được cách lái xe (drive), thì lúc đó tôi mới phải lo lắng.",
  "Yeah. Ain't far now.": "Ừ. Bây giờ thì đéo còn xa nữa đâu.",
  "Bag's almost full.": "Túi đã gần đầy rồi.",
  "Woah, she's got a temper on her, huh?": "Woah, cô ấy có tính khí khá là nóng nảy (temper) đấy nhỉ?",
  "Examining Site": "Đang Khảo Sát Địa Điểm (Examining Site)",
  "Vehicle Delivery": "Giao Hàng Xe Cộ (Vehicle Delivery)",
  "37 GENERIC Mike Daroca": "37 CHUNG (GENERIC) Mike Daroca",
  "I'll set it off.": "Tôi sẽ kích nổ (set it off) nó.",
  "Listen to Sheriff Parsons": "Hãy lắng nghe Cảnh Sát Trưởng (Sheriff) Parsons",
  "All the fight's gone out of %1$s.": "Mọi ý chí chiến đấu đều đã rời bỏ %1$s.",
  "Zombies do not show up on your minimap from this difficulty level onwards.": "Bọn Zombies sẽ đéo còn hiển thị trên bản đồ nhỏ (minimap) của bạn kể từ cấp độ khó này trở đi.",
  "It's not as good as the professional one--only lasts a couple dozen shots.": "Nó đéo thể tốt bằng loại chuyên dụng được--chỉ có thể chịu đựng được tối đa trong khoảng vài chục phát súng thôi.",
  "And besides... I wasn't alone.": "Và hơn nữa... tôi đéo hề đơn độc một mình.",
  "The trusty Saturday Night Special. Just as handy on Sundays.": "Khẩu súng đáng tin cậy Saturday Night Special (Bữa Tối Thứ Bảy Đặc Biệt). Vẫn tiện dụng y như trong những ngày Chủ Nhật.",
  "Gave away 5 FOOD.": "Đã cho đi 5 THỨC ĂN (FOOD).",
  "Luke": "Luke",
  "Refills some brass to generate several magazines' worth of 9mm ammunition.": "Nạp lại một số lượng vỏ đạn đồng (brass) để chế tạo ra lượng đạn dược 9mm tương đương với vài băng đạn.",
  "So what if I didn't have a job? Like it matters now anyways.": "Vậy nếu tôi đéo có một công việc (job) thì sao nào? Dù sao thì bây giờ chuyện đó cũng có quan trọng đéo gì đâu chứ.",
  "Scared people make bad decisions. We need to fix that.": "Những người đang bị hoảng sợ thường đưa ra những quyết định tồi tệ. Chúng ta cần phải sửa chữa chuyện đó.",
  "Trade Opportunity (Fuel)": "Cơ Hội Giao Thương Mua Bán (Nhiên Liệu - Fuel)",
  "If we don't find more construction materials, we're all gonna be campin' soon.": "Nếu chúng ta đéo tìm được thêm vật liệu xây dựng (construction materials), tất cả chúng ta sẽ sớm phải đi cắm trại (campin') cmnl đấy.",
  "This one's all hands on deck. You better get home ASAP.": "Nhiệm vụ lần này cần đến sự chung tay giúp sức của tất cả mọi người (all hands on deck). Tốt hơn hết là cậu nên quay trở về nhà CÀNG SỚM CÀNG TỐT (ASAP).",
  "Carew": "Carew",
  "Looks like we're zed-free.": "Trông có vẻ như chúng ta đã thoát khỏi bọn zed cmnr.",
  "We could turn this stuff into weapons easy.": "Chúng ta có thể dễ dàng biến thứ này thành vũ khí đấy.",
  "I'm not a machine. You gotta give me time to rest.": "Tôi đéo phải là một cỗ máy (machine). Cậu phải cho tôi thời gian để được nghỉ ngơi (rest) chứ.",
  "That's what I'm talking about. Let's make this town glow.": "Đó chính là điều mà tôi đang nói đến đấy. Hãy làm cho cái thị trấn này rực sáng lên (glow) nào.",
  "Get Dr. Horn to the LZ": "Đưa Bác sĩ Horn đến bãi đáp LZ",
  "Word around town is you're making quite a splash for yourself, my friend.": "Mọi người xung quanh thị trấn đang bàn tán rằng cậu đang tạo ra được tiếng vang (splash) khá lớn cho bản thân mình đấy, anh bạn của tôi.",
  "So that's a no.": "Vậy là đéo (no).",
  "Perimeter is down! Everybody fall back!": "Vành đai phòng thủ (Perimeter) đã bị phá vỡ! Tất cả mọi người mau rút lui!",
  "If you want to check it out, it's on your map.": "Nếu cậu muốn đi kiểm tra thử, vị trí của nó đã được đánh dấu trên bản đồ (map) của cậu rồi đấy.",
  "Civilian refugee.": "Người tị nạn dân sự (Civilian refugee).",
  "We can now manufacture our own ammunition.": "Bây giờ chúng ta đã có thể tự chế tạo ra đạn dược (ammunition) cho riêng mình.",
  "Dean": "Dean",
  "Like we don't have enough problems? Now some asshole is stealing our shit!": "Cứ như thể là chúng ta đéo có đủ các rắc rối hay sao ý? Bây giờ lại có tên khốn nào đó đang đi ăn trộm đồ của chúng ta!",
  "Yes ma'am! Right away ma'am!": "Rõ thưa bà! Sẽ làm ngay thưa bà!"
};

const file = 'output/languages/chunks/btxt_chunk_185.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_185.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk185[r.sourceText]) {
    r.translatedText = chunk185[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 185 successfully!');
