const fs = require('fs');
const chunk157 = {
  "Loves nothing more than the thrill of catching a killer wave. (Cardio Bonus)": "Đéo có gì anh ấy yêu thích hơn là cảm giác hồi hộp khi bắt được một con sóng tử thần. (Thưởng Thể lực - Cardio Bonus)",
  "The Events page keeps a log of things that happen to you as you play, including new mission opportunities, results of previous missions, community events, skill upgrades, and global events that impact you and your fellow survivors in Danforth.\r\nUse the mouse to select an event to show more details such as the people involved, and the associated rewards and bonuses.": "Trang Sự Kiện (Events) lưu giữ nhật ký về những điều xảy ra với bạn khi bạn chơi, bao gồm các cơ hội nhiệm vụ mới, kết quả của các nhiệm vụ trước đó, sự kiện cộng đồng, nâng cấp kỹ năng, và các sự kiện toàn cầu có ảnh hưởng đến bạn và những người sống sót khác ở Danforth.\r\nSử dụng chuột để chọn một sự kiện để xem thêm thông tin chi tiết như những người liên quan, cùng các phần thưởng và tiền thưởng đi kèm.",
  "Shit. Glad you've got a steady hand.": "Chết tiệt. Thật mừng vì cậu có một đôi tay vững vàng.",
  "So I guess you're my \"commanding officer\" now.": "Vậy tôi đoán bây giờ cậu là \"sĩ quan chỉ huy\" của tôi rồi.",
  "Our defenses managed to hold. Things could have been a lot worse. - %1$s": "Hệ thống phòng thủ của chúng ta đã chống đỡ thành công. Mọi chuyện đáng lẽ đã có thể tồi tệ hơn rất nhiều. - %1$s",
  "Help Sam find Andy Pimms?": "Giúp Sam tìm Andy Pimms đéo?",
  "Kilo is scavenging for supplies. Help him out?": "Kilo đang đi nhặt mót nhu yếu phẩm. Giúp anh ấy một tay chứ?",
  "We went out to try and rescue %1$s, but they died before we could get home. Not looking forward to reporting this to HQ.": "Chúng tôi đã ra ngoài để cố gắng giải cứu %1$s, nhưng họ đã chết trước khi chúng tôi có thể về đến nhà. Đéo mong đợi việc phải báo cáo chuyện này với Trụ Sở Chính (HQ) chút nào.",
  "I dunno, there's just something satisfying about building.": "Tôi đéo biết nữa, chỉ là có điều gì đó rất thỏa mãn trong việc xây dựng.",
  "Believe it. And get moving. The zeds always come back.": "Hãy tin vào điều đó đi. Và di chuyển đi. Bọn zed luôn quay trở lại.",
  "Let's start looking, then. What, you didn't think I was going to let you go out there alone, did you?": "Vậy thì bắt đầu tìm kiếm thôi. Sao, cậu đéo nghĩ là tôi sẽ để cậu đi ra ngoài đó một mình đấy chứ?",
  "We really need a good, clean latrine.": "Chúng ta thực sự cần một cái nhà xí sạch sẽ và tươm tất.",
  "Bryce": "Bryce",
  "Werner": "Werner",
  "Nobody's perfect.": "Đéo có ai hoàn hảo cả.",
  "It sounded like it was pretty important to you. I figured it was the least I could do.": "Nghe có vẻ như nó khá quan trọng với cậu. Tôi nghĩ đó là điều ít nhất tôi có thể làm.",
  "You don't look so good.": "Trông cậu đéo được khỏe lắm đâu.",
  "The fuck are you waiting for?": "Cậu còn chờ cái đéo gì nữa?",
  "Confirmed, we are zed-free here.": "Đã xác nhận, ở đây chúng tôi đéo có mống zed nào cả.",
  "I'd rather fight them here. At least here we've got choke points.": "Tôi thà đánh nhau với chúng ở đây còn hơn. Ít nhất ở đây chúng ta có các điểm thắt cổ chai.",
  "You ought to rest up when you get home.": "Cậu nên nghỉ ngơi cho khỏe khi về đến nhà.",
  "No one came to help. Had to get the hell out of there.": "Đéo có ai đến giúp cả. Đành phải vắt chân lên cổ mà cút khỏi đó thôi.",
  "Attention Marshall citizens. Trumbull County Sheriff's deputies are currently engaged in operations to clear the dead infestations in town. Please remain indoors and out of the line of fire until operations are concluded.": "Sự chú ý của công dân Marshall. Các phó cảnh sát trưởng Quận Trumbull hiện đang tham gia vào các hoạt động truy quét các ổ dịch người chết trong thị trấn. Xin hãy ở yên trong nhà và tránh khỏi làn đạn cho đến khi các hoạt động kết thúc.",
  "We depend on our radio to maintain contact with the brass, and with each other. We can also use it to reach out to other units stranded in the city.": "Chúng ta dựa vào bộ đàm để duy trì liên lạc với cấp trên, và với nhau. Chúng ta cũng có thể sử dụng nó để liên lạc với các đơn vị khác đang bị mắc kẹt trong thành phố.",
  "I guess maybe one of them survived. Whole time though, Job? He never looks up from his fuckin' book. Kept reading out loud from it. I dunno, something by Julius Caesar or somebody.": "Tôi đoán có lẽ một trong số họ đã sống sót. Cơ mà suốt ngần ấy thời gian, Job thì sao? Ông ta đéo bao giờ ngẩng đầu lên khỏi cuốn sách chết tiệt của mình. Cứ đọc to từ trong đó. Tôi đéo biết nữa, thứ gì đó của Julius Caesar hay ai đó.",
  "I'm not proud of what I did. I was just trying to survive.": "Tôi đéo tự hào về những gì mình đã làm đâu. Tôi chỉ đang cố gắng sống sót thôi.",
  "Leave me, sir. I'll hold 'em off.": "Bỏ tôi lại đi, thưa ngài. Tôi sẽ cầm chân chúng.",
  "Research Whistling Box Mine": "Nghiên Cứu Mìn Hộp Huýt Sáo (Whistling Box Mine)",
  "We could probably beef up our defenses. Just to be safe.": "Có lẽ chúng ta nên tăng cường hệ thống phòng thủ. Để cho an toàn.",
  "Spotted a horde.": "Đã phát hiện một bầy horde.",
  "Let's start by boarding up these here windows. There should be some scrap lumber in here that'll serve.": "Hãy bắt đầu bằng việc đóng ván lên những cái cửa sổ này đi. Chắc là sẽ có một ít gỗ vụn ở trong này có thể dùng được đấy.",
  "Who sent you to get me? Was it Holkins? That friggin' guy... you can tell him I'm not leaving until I'm done searching this place.": "Ai đã cử cậu đến đón tôi? Có phải Holkins đéo? Cái tên khốn khiếp đó... cậu có thể nói với hắn là tôi sẽ đéo rời đi cho đến khi tôi tìm kiếm xong chỗ này.",
  "Yeah, wow. That was awesome.": "Chà, wow. Quá là tuyệt vời luôn.",
  "Ask me, we shouldn't have stopped. Should have driven right the hell out of this valley. Headed for the city, maybe.": "Hỏi tôi thì, chúng ta đéo nên dừng lại. Lẽ ra nên lái xe cút thẳng ra khỏi cái thung lũng này. Có lẽ là hướng về phía thành phố.",
  "Palmer": "Palmer",
  "Shaw": "Shaw",
  "Just glad to help.": "Chỉ là rất vui vì được giúp đỡ thôi.",
  "You have any idea how long I've wanted to do that? Dreamed about it? Planned it? Felt good, too.": "Cậu có biết tôi đã muốn làm điều đó bao lâu rồi đéo? Đã mơ về nó? Lên kế hoạch cho nó? Cảm giác cũng khá tuyệt đấy.",
  "TIP: Press [ul_journal_menu] and then [ui_lb] to view your HOME BASE.": "MẸO: Nhấn [ul_journal_menu] và sau đó là [ui_lb] để xem CĂN CỨ CHÍNH (HOME BASE) của bạn.",
  "Trait Discovered: Self-Sufficient": "Đã Khám Phá Đặc Điểm: Tự Lập (Self-Sufficient)",
  "Doghouse to Greyhound One, did you think I sent you in there to fuck around?": "Nhà Chó (Doghouse) gọi Greyhound Một, các anh có nghĩ là tôi cử các anh vào đó để làm trò con bò đéo?",
  "Her mother died of cancer when she was ten. Her faith got her through it. She is committed to making a difference in this world before she sees the next.": "Mẹ cô ấy mất vì bệnh ung thư khi cô ấy mới mười tuổi. Đức tin đã giúp cô ấy vượt qua. Cô ấy cam kết sẽ tạo ra sự khác biệt trong thế giới này trước khi sang thế giới bên kia.",
  "Course, that ain't no excuse for bein' a fuckin' crybaby about it.": "Tất nhiên, đó đéo phải là cái cớ để trở thành một đứa khóc nhè khốn kiếp vì chuyện đó.",
  "Paid under the table for covert paramilitary work. Knows her way around an AK-47.": "Được trả tiền ngầm cho các công việc bán quân sự bí mật. Biết cách sử dụng thành thạo khẩu AK-47.",
  "Stop wasting bullets! Slow down and aim.": "Đừng lãng phí đạn nữa! Chậm lại và nhắm cho kỹ đi.",
  "Hangers": "Móc Treo Quần Áo",
  "Wits Improved!": "Đã Cải Thiện Trí Tuệ (Wits)!",
  "All lined up and ready.": "Tất cả đã xếp hàng và sẵn sàng.",
  "No surprise. That loser Lily invited couldn't hang with the big boys. Sam and I took care of business, though. - %1$s": "Đéo có gì ngạc nhiên. Cái tên thất bại mà Lily mời đến đéo thể đú đởn được với những tay chơi thứ thiệt. Dù sao thì Sam và tôi đã giải quyết xong công việc rồi. - %1$s",
  "Winkelman": "Winkelman",
  "Are we ready to go find us another Screamer?": "Chúng ta đã sẵn sàng đi tìm cho mình một con Screamer khác chưa?",
  "Help!": "Cứu với!",
  "You want this stuff? Keep them off us.": "Các người muốn thứ này sao? Vậy thì hãy cản chúng lại giúp chúng tôi đi.",
  "Black Friday, this is Highroad Actual.": "Black Friday, đây là Highroad Actual.",
  "Washington": "Washington",
  "Hits the bottle a little too hard.": "Nhậu nhẹt hơi quá đà.",
  "UPGRADED: Sat-Comms": "ĐÃ NÂNG CẤP: Vệ Tinh Viễn Thông (Sat-Comms)",
  "Change View": "Thay Đổi Góc Nhìn",
  "DECLINED: Sweet Ride": "ĐÃ TỪ CHỐI: Chiếc Xe Tuyệt Vời",
  "The runners are trouble!": "Bọn chạy bộ đó là cả một rắc rối đấy!",
  "Hey, babe.": "Chào cưng.",
  "Zombies. Dumber than hammered owl shit.": "Bọn zombie. Ngu hơn cả cứt cú bị đập bẹp.",
  "Investigate the signs of survivor activity.": "Điều tra các dấu hiệu hoạt động của người sống sót.",
  "Clear out the Artillery Site": "Dọn dẹp Khu Vực Pháo Binh (Artillery Site)",
  "The Commanding Officer determines which set of tactics and bonuses are available here. Currently, this unit is functioning without a Commanding Officer.": "Sĩ quan Chỉ huy sẽ quyết định bộ chiến thuật và phần thưởng nào có sẵn ở đây. Hiện tại, đơn vị này đang hoạt động mà đéo có Sĩ quan Chỉ huy.",
  "MISSION: Scene of the Crime": "NHIỆM VỤ: Hiện Trường Vụ Án",
  "What a mess. This is going to take a while.": "Thật là một mớ hỗn độn. Sẽ mất một lúc đây.",
  "Who buys this crap, anyway?": "Mà ai lại đi mua cái thứ rác rưởi này cơ chứ?",
  "Help a soldier bring in a big haul of supplies.": "Giúp một người lính mang về một đống lớn nhu yếu phẩm.",
  "I'm already loaded down here.": "Tôi đã gánh đủ đồ ở đây rồi.",
  "Private Vincent, you think the end of the world needs wise-asses or soldiers?": "Binh nhì Vincent, cậu nghĩ ngày tận thế cần những tên khôn lỏi hay những người lính?",
  "I don't like either choice. Give me some time to think about this.": "Tôi đéo thích lựa chọn nào cả. Cho tôi thêm chút thời gian để suy nghĩ về việc này.",
  "If you've heard from Karen, let me know!": "Nếu cậu nghe được tin tức gì từ Karen, hãy báo cho tôi biết nhé!",
  "What you in the market for?": "Cậu đang muốn tìm mua thứ gì vậy?",
  "That's it for me.": "Thế là đủ với tôi rồi.",
  "Parent": "Phụ Huynh",
  "Iturbide": "Iturbide",
  "Just a bit more.": "Thêm chút xíu nữa thôi.",
  "Abby": "Abby",
  "I bet they can hear us from a mile away.": "Tôi cá là chúng có thể nghe thấy chúng ta từ cách xa hàng dặm.",
  "Nice shootin', Tex!": "Bắn hay lắm, anh bạn (Tex)!",
  "Complete 50 missions or activities with the same character.": "Hoàn thành 50 nhiệm vụ hoặc hoạt động với cùng một nhân vật.",
  "Buzzball Bat": "Gậy Đánh Bóng Chày Buzzball",
  "I hear ya.": "Tôi nghe cậu rồi.",
  "Mind your left.": "Cẩn thận bên trái kìa.",
  "Aw, man, who invited you?": "Ôi, anh bạn, ai đã mời cậu đến vậy?",
  "BLAZE OF GLORY: %1$s": "ÁNH HÀO QUANG RỰC RỠ (BLAZE OF GLORY): %1$s",
  "Don't these things ever quit?": "Mấy thứ này đéo bao giờ bỏ cuộc sao?",
  "Survived another day": "Sống sót thêm một ngày nữa",
  "Requires Edged Weapons Level 4": "Yêu cầu Kỹ năng Vũ Khí Sắc Nhọn (Edged Weapons) Cấp 4",
  "Dr. Bogatz had been run off the road by zombies, but we've managed to get him safely back to the LZ. Now let's try and keep him alive until the helo gets here.": "Tiến sĩ Bogatz đã bị lũ zombie dồn ra khỏi đường, nhưng chúng tôi đã cố gắng đưa ông ấy về Khu Vực Hạ Cánh (LZ) an toàn. Bây giờ hãy cố gắng giữ cho ông ấy sống sót cho đến khi trực thăng đến đây.",
  "Jesus!": "Chúa ơi!",
  "I need some medical advice.": "Tôi cần một vài lời khuyên về y tế.",
  "A place to meet and eat.": "Một nơi để gặp mặt và ăn uống.",
  "Loves the great outdoors.": "Yêu thiên nhiên rộng lớn.",
  "Loves to live off the land, leaving the modern world behind. Knows how to get by on very little, and enjoy it. (Wits Bonus)": "Thích sống dựa vào thiên nhiên, bỏ lại thế giới hiện đại phía sau. Biết cách xoay xở với những thứ cực kỳ ít ỏi, và tận hưởng điều đó. (Thưởng Trí Tuệ - Wits Bonus)",
  "Send a runner to my position.": "Cử một người đưa tin (runner) đến vị trí của tôi đi.",
  "Shit. Well, what'd you expect?": "Chết tiệt. Chà, cậu mong đợi điều gì cơ chứ?",
  "We'll be there soon.": "Chúng tôi sẽ có mặt ở đó sớm thôi.",
  "Improvised Explosive": "Chất Nổ Tự Chế (Improvised Explosive)"
};

const file = 'output/languages/chunks/btxt_chunk_157.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_157.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk157[r.sourceText]) {
    r.translatedText = chunk157[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 157 successfully!');
