const fs = require('fs');
const chunk136 = {
  "Here's what you asked for.": "Đây là thứ cậu yêu cầu.",
  "<Heavy sigh.>": "<Thở dài thườn thượt.>",
  "Wait one.": "Đợi chút.",
  "Holy crap. I can't believe we survived that.": "Chúa ơi. Tôi đéo thể tin được là chúng ta đã sống sót qua vụ đó.",
  "Used to train race horses.": "Từng huấn luyện ngựa đua.",
  "Fuck! They're inside!": "Chết tiệt! Chúng ở bên trong!",
  "Wounded Scout": "Trinh Sát Bị Thương",
  "Dear Anthony, We waited as long as we could. Your father isn't willing to stay any longer. I suppose he's right. We can't risk everyone else. I hope you find this note and that you come find us. We didn't want to leave without you. We love you. Be safe.": "Anthony yêu quý, Chúng ta đã đợi lâu nhất có thể. Bố con đéo muốn ở lại thêm nữa. Mẹ cho là ông ấy đúng. Chúng ta đéo thể gây nguy hiểm cho những người khác. Mẹ hy vọng con sẽ tìm thấy mảnh giấy này và đến tìm chúng ta. Chúng ta đéo muốn rời đi mà đéo có con. Bố mẹ yêu con. Bảo trọng nhé.",
  "Debug4": "Debug4",
  "Mayonnaise": "Sốt Mayonnaise",
  "I'm done here.": "Tôi xong việc ở đây rồi.",
  "Put Andy Pimms to Rest": "Đưa Tiễn Andy Pimms Lần Cuối",
  "INCIDENT: SWAT Zombie Encounter": "SỰ CỐ: Chạm Trán Zombie SWAT",
  "We're all ready to go. Just waiting on you.": "Chúng tôi đều đã sẵn sàng xuất phát. Chỉ chờ cậu thôi đấy.",
  "Madisyn": "Madisyn",
  "I'll be back.": "Tôi sẽ quay lại.",
  "We are all the Lord's hands. Now let's use those hands to gather these supplies. What's mine is yours, my friend.": "Tất cả chúng ta đều là đôi bàn tay của Chúa. Giờ thì hãy dùng đôi bàn tay đó để thu thập những nhu yếu phẩm này. Của tôi cũng là của cậu, bạn của tôi.",
  "We can't afford to keep spending that much ammo to defend ourselves.": "Chúng ta đéo thể tiếp tục tiêu tốn ngần ấy đạn dược chỉ để tự vệ được.",
  "Fancy Machete": "Machete Xịn Xò",
  "We don't have enough soldiers left to go on risky scavenging missions.": "Chúng ta đéo còn đủ lính để thực hiện những nhiệm vụ nhặt đồ (scavenging) đầy rủi ro nữa.",
  "Vienna Cho to Greyhound One ... These stupid call signs. Anyway, come talk to me. Right now.": "Vienna Cho gọi Greyhound One ... Mấy cái biệt danh gọi vô tuyến ngu xuẩn này. Dù sao thì, đến nói chuyện với tôi đi. Ngay bây giờ.",
  "Thanks for coming with me, but... you mind waiting here? I want to say goodbye privately.": "Cảm ơn vì đã đi cùng tôi, nhưng... cậu có phiền đứng đợi ở đây không? Tôi muốn nói lời từ biệt một cách riêng tư.",
  "Eliza": "Eliza",
  "Disinfectant": "Thuốc Sát Trùng",
  "I don't really need this now.": "Tôi thực sự đéo cần cái này lúc này.",
  "These things last a while past the expiration date, but not forever. -%1$s": "Những thứ này có thể dùng được một thời gian sau ngày hết hạn, nhưng đéo phải là mãi mãi đâu. -%1$s",
  "Want: %s": "Cần: %s",
  "Okay, I think that's about all there is to find here.": "Được rồi, tôi nghĩ đó là tất cả những gì có thể tìm thấy ở đây.",
  "You must earn 100% trust before BEFRIENDING someone.": "Bạn phải đạt được 100% độ tin cậy trước khi KẾT BẠN (BEFRIENDING) với ai đó.",
  "RESCUED: Dr. Dan Bogatz": "ĐÃ CỨU: Bác sĩ Dan Bogatz",
  "The ammo locker's looking pretty empty.": "Tủ đạn trông khá là trống trơn rồi đấy.",
  "Sommelier": "Chuyên gia nếm rượu (Sommelier)",
  "In the meantime, I'm going to go look around some more.": "Trong lúc đó, tôi sẽ đi dạo quanh xem sao.",
  "It's coming for you!": "Nó đang nhắm vào cậu kìa!",
  "ATTITUDE: Brusque": "THÁI ĐỘ: Thô Lỗ",
  "Know what would make this a lot easier? If we had some medicine. Hell, I'd settle for some allergy pills at this point.": "Biết điều gì sẽ làm mọi chuyện dễ dàng hơn đéo? Nếu chúng ta có chút thuốc men. Chết tiệt, lúc này thì một vài viên thuốc chống dị ứng tôi cũng đéo chê đâu.",
  "Use this after your MAXIMUM VITALITY has been reduced.": "Sử dụng vật phẩm này sau khi SINH LỰC TỐI ĐA (MAXIMUM VITALITY) của bạn bị giảm sút.",
  "114 DEBUG": "114 DEBUG",
  "You mind if we keep that rescue between us? I got a rep to maintain.": "Cậu có phiền đéo nếu chúng ta giữ bí mật về vụ giải cứu này? Tôi còn có danh tiếng phải giữ gìn nữa chứ.",
  "What else is there to say? %2$s is a raging prick. I'm not sorry. - %1$s": "Còn gì để nói nữa đéo? %2$s là một thằng khốn cuồng nộ. Tôi đéo thấy tiếc đâu. - %1$s",
  "Showed those sons of bitches what's what.": "Cho mấy thằng chó đẻ đó biết thế nào là lễ độ.",
  "Popcorn machine, candy, curtains in front of the TV... he even made me get a ticket.": "Máy làm bắp rang, kẹo, rèm che trước tivi... ông ấy thậm chí còn bắt tôi mua vé.",
  "Madison Grant is on the way to the capital.": "Madison Grant đang trên đường đến thủ đô.",
  "Moving On ...": "Tiếp Tục Bước Đi...",
  "Routine Maintenance": "Bảo Trì Định Kỳ",
  "Michaela": "Michaela",
  "Sweet ass custom restore on this old american classic.": "Bản phục chế độ chế cực chất cho chiếc xe cổ điển của Mỹ này.",
  "LESSON 2": "BÀI HỌC 2",
  "Thanks. We owe you big-time.": "Cảm ơn. Chúng tôi nợ cậu một ân tình lớn đấy.",
  "SURVIVAL TACTICS: Real Time": "CHIẾN THUẬT SINH TỒN: Thời Gian Thực",
  "Now, does it still burn when you piss?": "Giờ thì, lúc đi đái có còn thấy buốt đéo?",
  "I see an infestation of zeds down there.": "Tôi thấy một ổ zed dưới đó.",
  "XP penalty from ????": "Hình phạt kinh nghiệm (XP) từ ????",
  "Remap %s": "Gán lại phím %s",
  "Edwards": "Edwards",
  "Something bad happened out at the Barrett place. Reports are still coming in, but... it sounds like the Wilkersons are dead.": "Có chuyện tồi tệ đã xảy ra ở chỗ nhà Barrett. Các báo cáo vẫn đang được gửi về, nhưng... nghe có vẻ như nhà Wilkerson đã chết hết rồi.",
  "You need to get home right now.": "Cậu cần phải về nhà ngay bây giờ.",
  "It's down, finish it!": "Nó gục rồi, kết liễu nó đi!",
  "Thin the Herd: SNAFU": "Giảm Dân Số: Tình Hình Hỗn Loạn (SNAFU)",
  "Eyes right, people.": "Nhìn sang phải đi, mọi người.",
  "I guess that's lucky for me, then.": "Tôi đoán thế là may mắn cho tôi rồi.",
  "I think this may be the first day in a while that I'm not sure it's gonna be my last.": "Tôi nghĩ đây có thể là ngày đầu tiên sau một thời gian dài mà tôi đéo chắc nó sẽ là ngày cuối cùng của mình.",
  "Well, I've got some ideas for a food storeroom that should cut down on that.": "Chà, tôi có vài ý tưởng cho một phòng chứa thức ăn có thể giúp giảm thiểu chuyện đó.",
  "Driving": "Lái Xe",
  "And you wouldn't know anything about it, would you?": "Và cậu thì đéo biết gì về chuyện đó, đúng đéo?",
  "Well, seems maybe I underestimated you.": "Chà, có vẻ như tôi đã đánh giá thấp cậu.",
  "Well, I wouldn't want you to be bored.": "Chà, tôi đéo muốn cậu phải nhàm chán đâu.",
  "Posit one one lima november nine nine charlie six one romeo. [message end tone]": "Tọa độ một một lima november chín chín charlie sáu một romeo. [âm thanh kết thúc tin nhắn]",
  "Invite a community member to follow you.": "Mời một thành viên cộng đồng đi theo bạn.",
  "Oh my God... come on! We've got to move!": "Ôi Chúa ơi... nhanh lên! Chúng ta phải di chuyển thôi!",
  "We need to keep SOME of these cars functional.": "Chúng ta cần phải giữ cho MỘT SỐ chiếc xe này còn hoạt động được.",
  "Home Away From Home": "Ngôi Nhà Thứ Hai",
  "You sure you don't need me to stick around?": "Cậu chắc là đéo cần tôi nán lại chứ?",
  "Pastor William Contacted": "Đã Liên Lạc Với Mục sư William",
  "Rice": "Gạo",
  "You're the army, for crying out loud!": "Mấy người là quân đội đấy, thật tình!",
  "Don't get yourself killed, okay?": "Đừng có để mình bị giết đấy, được chứ?",
  "Rader": "Rader",
  "Nice shooting, Tex!": "Bắn khá lắm, anh chàng cao bồi (Tex)!",
  "Boyles": "Boyles",
  "Assign Person": "Chỉ Định Người",
  "All I know is the chickenshit bastard better not panic when he's watching my back.": "Tất cả những gì tôi biết là thằng hèn nhát đó tốt nhất đừng có hoảng sợ khi hắn đang làm nhiệm vụ bọc hậu cho tôi.",
  "Agree": "Đồng ý",
  "... but when somebody gets on the radio, suddenly you're here to save us!": "... nhưng khi có ai đó lên đài phát thanh (radio), đột nhiên mấy người lại xuất hiện ở đây để cứu chúng tôi!",
  "Research Box Mine": "Nghiên Cứu Mìn Dạng Hộp (Box Mine)",
  "Survived the apocalypse ... so far.": "Đã sống sót qua tận thế ... cho đến lúc này.",
  "Aw man, it's locked.": "Trời ạ, nó bị khóa rồi.",
  "Delay your decision. What could possibly happen in the meantime?": "Trì hoãn quyết định của bạn. Chuyện tồi tệ gì có thể xảy ra trong lúc chờ đợi cơ chứ?",
  "We think we've found one of Doctor Horn's former colleagues. We'll send you the location.": "Chúng tôi nghĩ mình đã tìm thấy một trong những đồng nghiệp cũ của Bác sĩ Horn. Chúng tôi sẽ gửi tọa độ cho cậu.",
  "Let me spell it out. I'm infected. One of those things bit me. I'm a dead man. You're wasting your time.": "Để tôi nói thẳng nhé. Tôi đã bị nhiễm bệnh. Một trong những thứ đó đã cắn tôi. Tôi là một thằng sắp chết rồi. Cậu đang lãng phí thời gian của mình đấy.",
  "Sherwood": "Sherwood",
  "Mohrhaus": "Mohrhaus",
  "Keep an eye on that feral zombie.": "Để mắt đến con feral zombie đó nhé.",
  "...Yay?": "...Hoan hô?",
  "Really people? A candy dish full of pushpins? I'm sure they're super-useful and all, but some of us are coming back from supply runs tired and hungry and just want a mouthful of delicious candy, not tetanus of the mouth. - %1$s": "Nghiêm túc chứ mọi người? Một đĩa kẹo đầy những cái ghim bấm? Tôi chắc chắn là chúng cực kỳ hữu ích và đại loại thế, nhưng một số người trong chúng ta vừa trở về sau các chuyến chạy tiếp tế, vừa mệt mỏi vừa đói khát và chỉ muốn một ngụm kẹo ngon lành, chứ đéo phải bệnh uốn ván ở miệng đâu. - %1$s",
  "Hand me that map, and I'll show you where to look.": "Đưa tôi cái bản đồ đó, và tôi sẽ chỉ cho cậu biết cần tìm ở đâu.",
  "Shooting Platform option added temporarily.": "Tùy chọn Bục Bắn Súng (Shooting Platform) đã được thêm vào tạm thời.",
  "Thanks for the company. I'll make sure this all gets to the right place.": "Cảm ơn vì đã đi cùng. Tôi sẽ đảm bảo mọi thứ này được đưa đến đúng nơi.",
  "One of the most popular .22 cal. rifles.": "Một trong những khẩu súng trường cỡ nòng .22 phổ biến nhất.",
  "Halmer": "Halmer"
};

const file = 'output/languages/chunks/btxt_chunk_136.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_136.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk136[r.sourceText]) {
    r.translatedText = chunk136[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 136 successfully!');
