const fs = require('fs');
const chunk130 = {
  "What the hell is that?": "Cái quái gì thế kia?",
  "Bullying": "Bắt nạt",
  "Okay, I'm getting close now.": "Được rồi, tôi đang đến gần đây.",
  "That's it.": "Chính nó.",
  "Refugee": "Người Tị Nạn",
  "Black Friday, glad to hear you've been resupplied.": "Black Friday, rất vui khi nghe tin các bạn đã được tiếp tế.",
  "With the right expertise, we can really up our game with improvised weapons and distractions.": "Với chuyên môn phù hợp, chúng ta có thể thực sự nâng tầm cuộc chơi với những vũ khí và mồi nhử tự chế.",
  "Good sightlines up there.": "Tầm nhìn tốt ở trên đó đấy.",
  "Emote 4": "Biểu cảm 4",
  "Jesus. This is getting ridiculous. I'll bet you Judge Lawton's not going hungry.": "Chúa ơi. Chuyện này đang trở nên nực cười thật đấy. Tôi cá với cậu là Thẩm phán Lawton đéo bao giờ phải chịu đói đâu.",
  "%1$s encountered a Juggernaut while out on patrol. We took it down together and bought ourselves some time before the next siege.": "%1$s đã đụng độ một con Juggernaut khi đang đi tuần tra. Chúng tôi đã cùng nhau hạ gục nó và câu thêm được chút thời gian trước cuộc vây hãm tiếp theo.",
  "I'm calling that one done.": "Tôi xem như vụ này đã xong.",
  "I had this one little black dress she borrowed every time she went out on a first date. I didn't have the heart to tell her it just wasn't working for her.": "Tôi có một chiếc váy đen nhỏ mà cô ấy mượn mỗi khi đi hẹn hò lần đầu. Tôi đéo nỡ nói với cô ấy rằng nó đéo hợp với cô ấy chút nào.",
  "Extreme Couponing": "Săn Mã Giảm Giá Cực Đoan",
  "Hey, army! You really had me going there.": "Này, anh lính! Anh thực sự đã làm tôi tin sái cổ đấy.",
  "Sorry buddy, you're on your own. Good luck, though.": "Xin lỗi nhé anh bạn, cậu phải tự lo thân thôi. Dù sao thì cũng chúc may mắn.",
  "I appreciate you coming to get me, but I really need to find this. You think you can come with me while I look for it?": "Tôi rất biết ơn vì cậu đã đến đón tôi, nhưng tôi thực sự cần tìm thứ này. Cậu nghĩ cậu có thể đi cùng tôi trong lúc tôi tìm nó không?",
  "I've got this one.": "Để vụ này cho tôi.",
  "50 VIP Michele Martin": "50 VIP Michele Martin",
  "For God's sake, I just kept a few cans of tuna so my wife could eat!": "Vì Chúa, tôi chỉ giữ lại vài hộp cá ngừ để vợ tôi có cái mà ăn thôi!",
  "For now. Highroad out.": "Tạm thời là vậy. Highroad kết thúc.",
  "Scratch that off the wish list.": "Gạch cái đó khỏi danh sách điều ước đi.",
  "Probably not a bad idea to switch up your weapons every once in a while.": "Thỉnh thoảng đổi vũ khí cũng đéo phải là một ý kiến tồi đâu.",
  "Something very bad is happening": "Một chuyện gì đó rất tồi tệ đang xảy ra",
  "Really gives you a sense of the big picture, you know? Go ahead, have a look. Take it in.": "Thực sự mang lại cho cậu một cái nhìn toàn cảnh, cậu hiểu chứ? Cứ tự nhiên đi, hãy nhìn thử xem. Ngắm nghía nó đi.",
  "Rifle: 464 Brushgun": "Súng trường: 464 Brushgun",
  "Baker": "Baker",
  "Foreman": "Quản Đốc",
  "Headed off to join the other Wilkersons.": "Đã lên đường gia nhập cùng những người nhà Wilkerson khác.",
  "Ranger Gunderson - We apologize, but despite your repeated requests we cannot authorize the purchase of any .50 caliber hunting rifles for the ranger station. We would like to remind you that bears have not been seen on Mt. Tanner in over forty years, and moreover large-caliber rifles are not a recommended means of dealing with rogue bears.": "Kiểm lâm Gunderson - Chúng tôi xin lỗi, nhưng bất chấp những yêu cầu lặp đi lặp lại của anh, chúng tôi không thể cấp phép mua bất kỳ khẩu súng trường săn bắn cỡ nòng .50 nào cho trạm kiểm lâm. Chúng tôi muốn nhắc nhở anh rằng gấu đã không xuất hiện trên Núi Tanner trong hơn 40 năm qua, và hơn nữa súng trường cỡ nòng lớn không phải là phương tiện được khuyến nghị để đối phó với những con gấu hung dữ.",
  "Trait Discovered: Game Breaker": "Phát Hiện Đặc Trưng: Phá Vỡ Cuộc Chơi (Game Breaker)",
  "Doghouse Actual": "Chỉ huy Doghouse",
  "Futility": "Sự Vô Ích",
  "And since you apparently can't figure it out for yourself, we are better armed, armored, and equipped than a bunch of drunk hillbillies with hunting rifles.": "Và vì dường như các người đéo thể tự nhận ra điều đó, nên để tôi nói cho mà biết, chúng tôi được vũ trang, bọc thép và trang bị tốt hơn một đám nhà quê say xỉn cầm súng trường săn bắn đấy.",
  "You're with us now, soldier. Fall in and let's get moving.": "Cậu theo chúng tôi bây giờ, người lính. Vào vị trí và chúng ta cùng di chuyển nào.",
  "Hell yeah, let's go track 'em down!": "Hell yeah, hãy đi truy lùng bọn chúng nào!",
  "TIP: Hold [sprint] to sprint. Press [jump] to jump and climb.": "MẸO: Giữ [sprint] để chạy nước rút. Nhấn [jump] để nhảy và leo trèo.",
  "SitRep: International Travel": "Báo Cáo Tình Hình: Du Lịch Quốc Tế",
  "This may be our one chance. We've gotta get on this.": "Đây có thể là cơ hội duy nhất của chúng ta. Chúng bản phải nắm lấy nó.",
  "Come on, I'll show you where I'm staying.": "Đi nào, tôi sẽ chỉ cho cậu nơi tôi đang ở.",
  "Need Building Materials": "Cần Vật Liệu Xây Dựng",
  "Cheer": "Cổ vũ",
  "It ain't wise to cross me.": "Trở mặt với tôi đéo phải là hành động khôn ngoan đâu.",
  "So, look. I really appreciate you dragging me out here for this little heart-to-heart, but....": "Vậy, nghe này. Tôi thực sự biết ơn cậu vì đã kéo tôi ra đây để có buổi nói chuyện chân tình này, nhưng....",
  "Audrey": "Audrey",
  "We have food, water, and shelter, and we're willing to share.": "Chúng tôi có thức ăn, nước uống và nơi trú ẩn, và chúng tôi sẵn lòng chia sẻ.",
  "Unh... I ain't gonna last long leaking like a busted radiator.": "Unh... Tôi đéo thể trụ được lâu nếu cứ rỉ máu như một cái bộ tản nhiệt bị vỡ thế này đâu.",
  "Need enough BEDS for everyone or they won't be rested.": "Cần đủ GIƯỜNG cho tất cả mọi người, nếu không họ sẽ đéo được nghỉ ngơi đầy đủ.",
  "Send in backup!": "Gửi viện binh đến đây!",
  "Carpenter": "Thợ Mộc",
  "The man loves cars.": "Anh chàng này rất yêu xe hơi.",
  "+10": "+10",
  "Challenges": "Thử Thách",
  "Based on this information, and for your own safety, I'm declaring a lockdown, effective immediately and until further notice.": "Dựa trên thông tin này, và vì sự an toàn của chính các bạn, tôi tuyên bố phong tỏa, có hiệu lực ngay lập tức và cho đến khi có thông báo mới.",
  "Ritter": "Ritter",
  "We've got zeds attacking the east gate!": "Có bọn zed đang tấn công cổng phía đông!",
  "Tactics: Supply Lines": "Chiến Thuật: Tuyến Đường Tiếp Tế",
  "James": "James",
  "It's like every body they brought in last week had this ... infection that wasn't an infection.": "Cứ như thể mọi cái xác mà họ mang về tuần trước đều bị... nhiễm trùng, nhưng đéo hẳn là nhiễm trùng.",
  "Bastards aren't opening the gates, meanwhile my boys are sitting out here like a goddamn mobile brain buffet. So no, everything's pretty much not okay.": "Lũ khốn đéo chịu mở cổng, trong khi những người anh em của tôi đang ngồi chầu hực ngoài này như một bữa tiệc não sống di động chó chết vậy. Thế nên đéo, mọi thứ đéo ổn chút nào cả.",
  "FOUND NOTHING": "ĐÉO TÌM THẤY GÌ",
  "What's the situation out there?": "Tình hình ngoài đó thế nào rồi?",
  "%1$dm": "%1$dm",
  "Kaelyn": "Kaelyn",
  "%1$s is pretty obnoxious.": "%1$s khá là đáng ghét.",
  "Soap Opera Trivia": "Kiến Thức Về Phim Truyền Hình (Soap Opera)",
  "Medicine's been one of the more popular things to loot since all this started, but you can still find it if you know where to look.": "Thuốc men là một trong những thứ bị cướp bóc nhiều nhất kể từ khi chuyện này bắt đầu, nhưng cậu vẫn có thể tìm thấy chúng nếu biết phải tìm ở đâu.",
  "So why did that doctor shoot himself in the head?": "Vậy tại sao vị bác sĩ đó lại tự bắn vào đầu mình?",
  "Take a breath while you can.": "Tranh thủ nghỉ ngơi khi còn có thể đi.",
  "I thought we might use this time to chat about what's on your mind.": "Tôi nghĩ chúng ta có thể dùng khoảng thời gian này để trò chuyện về những gì cậu đang suy nghĩ trong đầu.",
  "Lily's trying to pick up the pieces.": "Lily đang cố gắng thu nhặt lại những mảnh vụn vỡ.",
  "REFUSE SOLDIER. Do not recruit this soldier to your unit.": "TỪ CHỐI NGƯỜI LÍNH. Đừng chiêu mộ người lính này vào đơn vị của bạn.",
  "Numbs the pain, but won't help serious wounds. Typical over-the-counter stuff.": "Làm tê liệt cơn đau, nhưng đéo giúp ích gì cho những vết thương nghiêm trọng. Những loại thuốc không kê đơn điển hình.",
  "You lost all your officers.": "Anh đã mất toàn bộ sĩ quan của mình.",
  "Hey. Losing that RV was kind of rough. For a while there, I felt really secure, you know? Like no matter what happened, we could always just MOVE. Nothing could touch us.": "Này. Mất chiếc RV đó đúng là thảm họa. Trong một lúc, tôi thực sự cảm thấy an toàn, cậu biết không? Kiểu như dù có chuyện gì xảy ra, chúng ta luôn có thể DI CHUYỂN. Đéo có gì có thể chạm vào chúng ta cả.",
  "Make 9mm Ammo": "Chế Tạo Đạn 9mm",
  "Roman": "Roman",
  "Revolver: Anvil": "Súng lục rulo: Anvil",
  "Sorry you wasted a trip. I'm not going back.": "Xin lỗi vì cậu đã phí công lặn lội đến đây. Tôi đéo quay lại đâu.",
  "Your orders are to bring in documents only. Is that clear?": "Lệnh của anh là chỉ mang tài liệu vào thôi. Rõ chưa?",
  "Collins": "Collins",
  "Damn, I shoulda told that guy to haul my ass to a city.": "Mẹ kiếp, lẽ ra tôi nên bảo gã đó đưa cái mạng tôi đến một thành phố.",
  "Cool. This isn't over, though.": "Tuyệt. Dù vậy, chuyện này vẫn chưa kết thúc đâu.",
  "Sounds like the folks at the grange could use some help with their defenses. - %1$s": "Có vẻ như những người ở nông trang có thể cần sự giúp đỡ để phòng thủ. - %1$s",
  "Hurry! Please!": "Nhanh lên! Làm ơn!",
  "Since the zombie apocalypse, Judge Lawton has been the front-runner in maintaining some semblance of society amongst the survivors.": "Kể từ khi thảm họa zombie nổ ra, Thẩm phán Lawton đã trở thành người đi đầu trong việc duy trì một số biểu hiện của xã hội giữa những người sống sót.",
  "Tell you one thing: I'd be welcome in any community. With these things roaming around, everyone could use a drink. (Can cook.)": "Nói cho cậu biết một điều: Tôi sẽ được chào đón ở bất kỳ cộng đồng nào. Với những thứ này đi lang thang khắp nơi, ai mà đéo cần một ly rượu cơ chứ. (Biết nấu ăn.)",
  "Damn, I'm tired.": "Mẹ kiếp, tôi mệt vãi.",
  "Event: Deadly Disagreement": "Sự kiện: Bất Đồng Chết Người",
  "Sgt. Branson": "Trung sĩ Branson",
  "Paul": "Paul",
  "Restores max Stamina a little. Fresh from our med lab. Heisenberg would be proud.": "Phục hồi Thể Lực tối đa một chút. Mới ra lò từ phòng thí nghiệm y tế của chúng ta. Heisenberg hẳn sẽ rất tự hào.",
  "Etiquette": "Phép Tắc Ứng Xử (Etiquette)",
  "Hello?": "Xin chào?",
  "Breach at Vehicle Ops! Zeds are flanking us!": "Bị chọc thủng ở khu vực Vận Hành Xe! Lũ zed đang bọc hậu chúng ta!",
  "Locked": "Đã Khóa",
  "Bug": "Bọ (Bug)",
  "Overclock": "Ép Xung (Overclock)",
  "We're going to get through this. Now come on.": "Chúng ta sẽ vượt qua chuyện này. Đi nào.",
  "We've been actively sniping zombies, giving us a larger safe area around our home.": "Chúng tôi đã tích cực bắn tỉa bọn zombie, giúp mở rộng khu vực an toàn xung quanh nhà của mình."
};

const file = 'output/languages/chunks/btxt_chunk_130.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_130.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk130[r.sourceText]) {
    r.translatedText = chunk130[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 130 successfully!');
