const fs = require('fs');
const chunk113 = {
  "%1$s was out gathering supplies for the community. I offered to provide an escort home, but things went to shit. I failed. - %2$s": "%1$s đã ra ngoài thu thập nhu yếu phẩm cho cộng đồng. Tôi đã đề nghị hộ tống cô ấy về nhà, nhưng mọi chuyện đã đổ bể. Tôi đã thất bại. - %2$s",
  "Spin Kick": "Cú Đá Xoay (Spin Kick)",
  "Copy that, Black Friday. We've got a workstation set up for her, with everything we could salvage from Horn's research.": "Rõ rồi, Black Friday. Chúng tôi đã thiết lập một trạm làm việc cho cô ấy, với tất cả những gì chúng tôi có thể cứu vãn từ nghiên cứu của Horn.",
  "Keep them off the barricades!": "Giữ chúng tránh xa các rào chắn!",
  "I don't see anything of interest.": "Tôi không thấy bất cứ điều gì thú vị cả.",
  "Never leave a man behind. That's us, motherfuckers.": "Không bao giờ bỏ lại đồng đội phía sau. Đó là chúng ta, những thằng khốn kiếp.",
  "Rifle: L41A1": "Súng trường: L41A1",
  "What do you mean, \"lowest bidder?\"": "Ý anh là sao, \"người trả giá thấp nhất\"?",
  "Stranded Soldier": "Người Lính Mắc Kẹt",
  "Call for Scavengers": "Gọi Người Thu Thập",
  "Roger that, we're inbound.": "Đã rõ, chúng tôi đang trên đường tới.",
  "Need a MUNITIONS SHOP": "Cần một CỬA HÀNG ĐẠN DƯỢC (MUNITIONS SHOP)",
  "Can't say for sure, but I think it's one of those thugs the Wilkersons hired.": "Không thể nói chắc chắn, nhưng tôi nghĩ đó là một trong những tên côn đồ mà nhà Wilkerson đã thuê.",
  "Hey, would I lie to my favorite little sister in the world?": "Này, anh lại đi nói dối cô em gái yêu quý nhất trên đời của anh sao?",
  "49 GENERIC Eddie Francis": "49 GENERIC Eddie Francis",
  "A few more outposts would give us more of a safety net.": "Thêm vài tiền đồn (outpost) nữa sẽ mang lại cho chúng ta thêm mạng lưới an toàn.",
  "Seems like more of those things out there lately. You notice that?": "Gần đây có vẻ như lũ quái vật đó xuất hiện nhiều hơn. Cậu có chú ý điều đó không?",
  "Supply's running low on that.": "Nguồn cung cấp thứ đó đang cạn kiệt.",
  "Well unless somebody walks up to the bomb, rips the electrical leads out of the detonator and jams them into the charge by hand, yeah.": "Chà, trừ khi có ai đó bước tới chỗ quả bom, giật tung các dây điện khỏi ngòi nổ và tự tay nhét chúng vào khối thuốc nổ, thì đúng vậy.",
  "Finally, some military intelligence.": "Cuối cùng, cũng có chút thông tin tình báo quân sự.",
  "We need you back here!": "Chúng tôi cần cậu quay lại đây!",
  "Maybe we can lose 'em here?": "Có lẽ chúng ta có thể cắt đuôi bọn chúng ở đây chăng?",
  "Better take that feral down first.": "Tốt hơn là hạ gục con feral đó trước đi.",
  "Suppose that's half the reason he left.": "Cho rằng đó là một nửa lý do khiến anh ấy rời đi.",
  "Grocery store pharmacies, corner drugstores... heck, you'd be amazed what people have in their bathroom medicine cabinets these days.": "Các hiệu thuốc ở cửa hàng tạp hóa, các hiệu thuốc ở góc phố... chết tiệt, cậu sẽ ngạc nhiên với những gì người ta có trong tủ thuốc phòng tắm thời nay đấy.",
  "I dunno, man. Whole situation's pretty messed up.": "Tôi không biết nữa, anh bạn. Toàn bộ tình huống này khá tồi tệ.",
  "The Sheriff? Yeah, he went out about an hour ago. He said he was gonna hunt down this feral bastard that's been stalking our patrols.": "Cảnh sát trưởng ư? Ừ, ông ấy đã ra ngoài khoảng một giờ trước. Ông ấy nói sẽ truy lùng con chó đẻ feral đang rình rập các đội tuần tra của chúng ta.",
  "Uh, Lily said you guys aren't actually building anything right now.": "Ờ, Lily nói các cậu hiện tại không thực sự xây dựng bất cứ thứ gì.",
  "Finally. Maybe now I can have a bunk to myself. - %1$s": "Cuối cùng thì. Có lẽ bây giờ tôi có thể có một chiếc giường cho riêng mình rồi. - %1$s",
  "There's an ugly one.": "Có một con quái thai kìa.",
  "I'm continuing to hear stories of flu outbreaks. Having a good stockpile of medicine and decent medical facilities is all we can do. -%1$s.": "Tôi tiếp tục nghe thấy những câu chuyện về dịch cúm bùng phát. Có một kho dự trữ thuốc tốt và các cơ sở y tế kha khá là tất cả những gì chúng ta có thể làm. -%1$s.",
  "This is where I would go to hide. If I hadn't ... you know ... hidden in that other place.": "Đây là nơi tôi sẽ đến để trốn. Nếu tôi không... cậu biết đấy... trốn ở một nơi khác.",
  "Besieged": "Bị Bao Vây",
  "Zombie hordes don't form instantaneously. If we can clear a few out, we'll make things safer for a little while. - %1$s": "Bầy zombie không hình thành ngay lập tức. Nếu chúng ta có thể dọn dẹp vài bầy, mọi thứ sẽ an toàn hơn trong một thời gian ngắn. - %1$s",
  "Perry": "Perry",
  "Come with me, or stay here and die, your call!": "Đi cùng tôi, hoặc ở lại đây và chết, tùy cậu quyết định!",
  "I'm taking you with me!": "Tao sẽ kéo mày đi cùng!",
  "Mouse Sensitivity": "Độ Nhạy Chuột",
  "Curses like a sailor, especially when talking to sailors.": "Chửi rủa như một thủy thủ, đặc biệt là khi nói chuyện với các thủy thủ.",
  "In the meantime, I'm going to look around some more.": "Trong lúc đó, tôi sẽ nhìn quanh một chút.",
  "Perimeter's breached!": "Vành đai đã bị chọc thủng!",
  "Hey, Carl, how are things?": "Này, Carl, mọi chuyện thế nào rồi?",
  "Power Level": "Mức Năng Lượng",
  "The entire internet is full of symptoms that I TOTALLY HAVE. (Minus Health)": "Toàn bộ internet chứa đầy những triệu chứng mà TÔI HOÀN TOÀN MẮC PHẢI. (Giảm Máu - Health)",
  "Killed a zombie silently": "Đã giết một con zombie trong im lặng",
  "Stack of Construction Materials": "Đống Vật Liệu Xây Dựng",
  "Yeah, whatever.": "Ừ, sao cũng được.",
  "SMG: MPX": "Súng tiểu liên: MPX",
  "Press": "Nhấn",
  "This bag's really fuckin' heavy, so how 'bout a thank you?": "Cái túi này nặng vãi lờ ra, vậy một lời cảm ơn thì sao nhỉ?",
  "Madison Grant died during our rescue attempt. She was so young, and seemed like she still had a lot to offer the world. I wish I could go back and ... somehow do things differently.": "Madison Grant đã chết trong nỗ lực giải cứu của chúng tôi. Cô ấy còn quá trẻ, và có vẻ như vẫn còn nhiều điều để cống hiến cho thế giới này. Tôi ước mình có thể quay lại và... bằng cách nào đó làm mọi chuyện khác đi.",
  "Hello, Sam. I didn't see you at service last Sunday.": "Xin chào, Sam. Tôi không thấy cậu đến buổi lễ vào Chủ nhật tuần trước.",
  "Behold, the demons shall cast some of you into prison, that ye may be tried; and ye shall have tribulation ten days": "Này đây, lũ ác quỷ sẽ tống một số người trong các người vào ngục, để các người bị thử thách; và các người sẽ phải chịu khốn khổ trong mười ngày",
  "A high quality antique headhunting axe.": "Một chiếc rìu săn đầu người cổ chất lượng cao.",
  "Yi": "Yi",
  "Double Vision": "Thị lực Đôi",
  "Are you army guys confused or what?": "Mấy người bên quân đội các anh bị nhầm lẫn hay sao vậy?",
  "Fire in the hole!": "Lựu đạn nổ!",
  "Supply Run Complete": "Chuyến Đi Lấy Đồ Hoàn Thành",
  "Talk about the living situation.": "Nói về tình hình sinh sống.",
  "We need more ammo, or we're gonna be fighting off the next attack with sticks and rocks.": "Chúng ta cần thêm đạn, nếu không chúng ta sẽ phải chống lại cuộc tấn công tiếp theo bằng gậy gộc và gạch đá đấy.",
  "Winard": "Winard",
  "Climb up and scout for danger.": "Leo lên và trinh sát các mối nguy hiểm.",
  "Look to the left.": "Nhìn sang bên trái.",
  "I think our defenses are okay, but I'm not sure I want to put them to the test.": "Tôi nghĩ hệ thống phòng thủ của chúng ta vẫn ổn, nhưng tôi không chắc mình muốn đem chúng ra thử nghiệm đâu.",
  "Crawford": "Crawford",
  "Our ammo reserves are dwindling.": "Kho dự trữ đạn của chúng ta đang cạn dần.",
  "You think one outpost is gonna save us? Dream on.": "Cậu nghĩ một cái tiền đồn (outpost) sẽ cứu được chúng ta sao? Tiếp tục mơ đi.",
  "Zed Hunt (Juggernaut)": "Săn Zed (Juggernaut)",
  "Wired for War": "Sẵn Sàng Chiến Đấu",
  "Torres": "Torres",
  "I'm loaded up. See you back at base.": "Tôi đã lấy đủ đồ rồi. Hẹn gặp lại ở căn cứ.",
  "Talking Doll": "Búp Bê Biết Nói",
  "Coming home now.": "Đang về nhà đây.",
  "21 GENERIC Alice Miller": "21 GENERIC Alice Miller",
  "Janiya": "Janiya",
  "Shut up shut up shut up!": "Im đi im đi im đi!",
  "Tessa": "Tessa",
  "Yeah, I'm pulling the trigger on this outpost.": "Ừ, tôi sẽ thiết lập cái tiền đồn này.",
  "Area Emptied": "Khu Vực Đã Trống Trơn",
  "Yes.": "Có.",
  "We're going to get through this.": "Chúng ta sẽ vượt qua chuyện này.",
  "Hey... you all right?": "Này... cậu không sao chứ?",
  "Poppin' more pills ain't gonna help.": "Uống thêm thuốc cũng không giúp ích được gì đâu.",
  "Brockworth \"Brock\" Brockway is on the way to the capital. (That's what I've decided his name was. He only introduced himself as Brock.)": "Brockworth \"Brock\" Brockway đang trên đường đến thủ đô. (Đó là cái tên tôi quyết định đặt cho anh ta. Anh ta chỉ giới thiệu bản thân là Brock.)",
  "These guys pick on you in high school or something?": "Bọn này hay bắt nạt cậu hồi trung học hay sao vậy?",
  "You have everything?": "Cậu có mọi thứ rồi chứ?",
  "Good for building, repairing, and reloading our weapons.": "Tốt cho việc xây dựng, sửa chữa và nạp lại vũ khí của chúng ta.",
  "Can be called in to advise on field medicine when a part of the community.": "Có thể được gọi đến để tư vấn về y tế dã chiến khi trở thành một phần của cộng đồng.",
  "Why don't you go skydiving? Without a chute?": "Sao cậu không đi nhảy dù đi? Mà không cần dù ấy?",
  "Hopefully this means some more supplies. Either way, we should check things out.": "Hy vọng điều này có nghĩa là có thêm nhu yếu phẩm. Dù sao thì chúng ta cũng nên kiểm tra xem sao.",
  "This stays closed until the zombies are cleared out.": "Cửa này sẽ vẫn đóng cho đến khi lũ zombie bị dọn sạch.",
  "Trait Discovered: People are Strange": "Phát Hiện Đặc Điểm: Mọi người thật kỳ lạ",
  "The outbreak condition in Houston has worsened to SERIOUS. \r\nGalveston Bay is now blockaded by U.S. Navy to manage the refugee situation.": "Tình trạng bùng phát dịch bệnh ở Houston đã trở nên NGHIÊM TRỌNG. \r\nVịnh Galveston hiện đang bị Hải quân Hoa Kỳ phong tỏa để quản lý tình hình người tị nạn.",
  "I'm not sure what's going on.": "Tôi không chắc chuyện gì đang xảy ra.",
  "Hold [sprint] and press [ul_melee_attack] to launch a slow, focused attack guaranteed to decapitate the target.": "Giữ [sprint] và nhấn [ul_melee_attack] để tung ra một đòn tấn công chậm, tập trung đảm bảo sẽ chặt đầu mục tiêu.",
  "I'm looking for someone.": "Tôi đang tìm một người.",
  "The current Threat Level (displayed below the mini-map) indicates how soon your base will be hit by a siege -- a major zombie attack. This threat builds up over time as zombies escape the city, and then an incoming helicopter from HQ will draw them straight to your base. This means that when you rescue a High Value Target or a Civilian, they will need to survive a siege before they can be airlifted to safety. Whenever a siege is inbound, get back to your base quickly to help defend it, or people are likely to die.": "Mức Độ Đe Dọa (Threat Level) hiện tại (hiển thị bên dưới bản đồ nhỏ) cho biết thời gian căn cứ của bạn sẽ bị vây hãm -- một cuộc tấn công lớn của zombie. Mối đe dọa này tăng dần theo thời gian khi zombie thoát khỏi thành phố, và sau đó một chiếc trực thăng đến từ Trụ sở sẽ thu hút chúng tiến thẳng tới căn cứ của bạn. Điều này có nghĩa là khi bạn giải cứu một Mục Tiêu Giá Trị Cao (HVT) hoặc một Thường dân, họ sẽ cần phải sống sót qua một cuộc vây hãm trước khi có thể được trực thăng đưa đến nơi an toàn. Bất cứ khi nào có cuộc vây hãm sắp tới, hãy nhanh chóng trở về căn cứ để giúp bảo vệ nó, nếu không mọi người rất dễ bị mất mạng.",
  "Good news I've been working on figuring out these Army broadcasts.": "Tin tốt đây, tôi đang cố gắng tìm hiểu những chương trình phát sóng này của Quân đội.",
  "Let's get some barricades up on those windows.": "Hãy dựng thêm vài rào chắn trên những cửa sổ đó đi."
};

const file = 'output/languages/chunks/btxt_chunk_113.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_113.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk113[r.sourceText]) {
    r.translatedText = chunk113[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 113 successfully!');
