const fs = require('fs');
const chunk183 = {
  "Did our friends out there get killed yet, or what?": "Những người bạn ngoài kia của chúng ta đã bị giết hết cmnr chưa, hay sao rồi?",
  "I think we got 'em all.": "Tôi nghĩ là chúng ta đã tiêu diệt được hết bọn chúng rồi.",
  "Headed to the Vet Clinic.": "Đang đi tới Phòng Khám Thú Y (Vet Clinic).",
  "Coordinating everything by radio.": "Điều phối mọi thứ thông qua bộ đàm vô tuyến (radio).",
  "We're picking up another message from Cleo, but it's not like the others. Stand by.": "Chúng tôi đang bắt được một tin nhắn khác từ Cleo, nhưng nó đéo giống những tin nhắn trước đó. Xin hãy giữ máy (Stand by).",
  "Needs Someone": "Đang Cần Người (Needs Someone)",
  "Artillery, right here, now now now!": "Pháo Binh (Artillery), bắn vào ngay chỗ này, ngay bây giờ ngay bây giờ!",
  "Screen Resolution": "Độ Phân Giải Màn Hình (Screen Resolution)",
  "Search The Supply Drop": "Tìm Kiếm Trong Thùng Hàng Tiếp Tế (Supply Drop)",
  "Uh, no offense.": "Uh, đéo có ý xúc phạm đâu nhé.",
  "Locked? Please. Stand back and let the big boys work.": "Bị khóa á? Làm ơn đi. Tránh ra sau và để cho những người đàn ông trưởng thành làm việc nào.",
  "You saved me back there. I won't forget it.": "Cậu đã cứu mạng tôi ở đằng kia. Tôi sẽ đéo bao giờ quên chuyện này đâu.",
  "Braggart": "Kẻ Thích Khoe Khoang (Braggart)",
  "Weird. Okay, I'll check it out. If they've got a helicopter, maybe they can get us the hell out of here.": "Kỳ lạ thật. Được rồi, tôi sẽ đi kiểm tra xem sao. Nếu như bọn họ có máy bay trực thăng (helicopter), có thể bọn họ sẽ đưa chúng ta thoát khỏi cái chốn địa ngục này.",
  "Wrapped my car around a tree. Didn't hurt anybody else, thank God, but three weeks in traction really made me think about the direction I was going.": "Tông chiếc xe ô tô của tôi vào một cái cây. Ơn Chúa là đã đéo làm tổn thương bất cứ ai khác, nhưng ba tuần phải nằm bó bột kéo giãn (traction) thực sự đã khiến cho tôi phải suy nghĩ lại về hướng đi mà mình đang chọn.",
  "Vince has always been a wiseass. I think he joined the Army because he'd burned so many bridges at home. But he's also a fighter, a survivor, and a clever bastard. I think he might be the kind of soldier this apocalypse needs.": "Vince luôn luôn là một gã khôn lỏi. Tôi nghĩ anh ta đã tham gia Quân Đội (Army) bởi vì anh ta đã cắt đứt quá nhiều mối quan hệ (burned so many bridges) ở quê nhà. Nhưng anh ta cũng là một chiến binh, một người biết cách sinh tồn, và là một tên khốn thông minh. Tôi nghĩ có thể anh ta chính là kiểu binh lính mà cái thời kỳ tận thế (apocalypse) này đang cần đến.",
  "Escort \"Sasquatch\" back to base": "Hộ tống \"Sasquatch\" quay trở về căn cứ",
  "The Hero": "Người Hùng (The Hero)",
  "I'm sorry, that's just the way it is.": "Tôi rất tiếc, nhưng đó là cách mà thế giới này vận hành.",
  "I think an outpost here would be good.": "Tôi nghĩ xây dựng một cái tiền đồn (outpost) ở đây sẽ rất tốt đấy.",
  "You're right, that's an issue.": "Cậu nói đúng, đó là một vấn đề rắc rối đấy.",
  "Cash is no longer a factor in the post-apocalyptic zombie world. The new currency is supplies and deeds that earn you Influence. Influence plays a large role in getting what you want, whether it be ammo from your own community's supply locker or borrowing some meds from your neighbors. Earning Influence is pretty straightforward: Get Shit Done.": "Tiền mặt đéo còn là một yếu tố quan trọng trong thế giới hậu tận thế zombie nữa. Loại tiền tệ mới chính là đồ tiếp tế (supplies) và những hành động mang về cho bạn Ảnh Hưởng (Influence). Ảnh Hưởng đóng một vai trò lớn trong việc giúp bạn có được những gì mình muốn, cho dù đó là đạn dược từ trong chính Tủ Đựng Đồ Tiếp Tế (Supply Locker) của cộng đồng mình, hay mượn một vài viên thuốc từ những người hàng xóm. Việc kiếm Điểm Ảnh Hưởng khá là đơn giản: Hãy Hoàn Thành Tốt Công Việc (Get Shit Done).",
  "Prevents explosives mishaps. REQUIRES CHEMISTRY EXPERT.": "Ngăn ngừa các sự cố tai nạn về thuốc nổ. YÊU CẦU CÓ CHUYÊN GIA HÓA HỌC (CHEMISTRY EXPERT).",
  "And look, we don't even know if my samples have anything to do with the outbreak, right?": "Và nhìn xem, chúng ta thậm chí còn đéo biết liệu những mẫu vật của tôi có liên quan gì đến sự bùng phát dịch bệnh hay đéo cơ mà, đúng đéo?",
  "Just shut your fuckin' trap for a second, willya?": "Cứ ngậm cái mồm khốn khiếp của cậu lại một giây thôi, được chứ hả?",
  "Have you seen the radio equipment here? Pretty swanky.": "Cô đã nhìn thấy các thiết bị liên lạc vô tuyến (radio equipment) ở đây chưa? Khá là xịn xò đấy.",
  "MEDICINE is essential for resisting disease and speeding recovery.": "THUỐC MEN (MEDICINE) là thứ vô cùng cần thiết để chống lại bệnh tật và tăng tốc độ phục hồi.",
  "Chu": "Chu",
  "Doghouse - Artillery Barrage": "Doghouse - Pháo Kích (Artillery Barrage)",
  "But if we can get to those guns ... maybe we can even the odds a bit.": "Nhưng nếu như chúng ta có thể lấy được những khẩu súng đó ... có lẽ chúng ta sẽ có thể cân bằng lại tỷ lệ thắng lợi một chút.",
  "Hello? Watchtower? Hey, will you assholes stop jerking off and open the damn gates?": "Xin chào? Có ai trên Tháp Canh đéo? Này, mấy thằng khốn các cậu có chịu dừng cái trò sóc lọ lại và mở cái cổng chết tiệt này ra đéo hả?",
  "Huh, interesting.": "Huh, thú vị đấy.",
  "The brass thought you might know something about his research. Something that could help us?": "Cấp trên (brass) nghĩ rằng cậu có thể biết được điều gì đó về nghiên cứu của ông ta. Chuyện gì đó có thể giúp ích được cho chúng tôi?",
  "You can also switch off and rest at home to recover stamina.": "Bạn cũng có thể chuyển sang nhân vật khác (switch) và cho họ nghỉ ngơi ở nhà để phục hồi Thể Lực (stamina).",
  "We need help clearing out an infestation!": "Chúng tôi cần giúp đỡ để dọn dẹp sạch sẽ một Ổ Dịch (infestation)!",
  "Brookstone": "Brookstone",
  "Nothing here. We're wasting our time.": "Đéo có gì ở đây cả. Chúng ta chỉ đang lãng phí thời gian của mình thôi.",
  "Sports Drink": "Nước Uống Thể Thao (Sports Drink)",
  "Keep an eye out to the left.": "Hãy chú ý quan sát cẩn thận ở phía bên trái.",
  "Seems pretty shell-shocked. Hope he doesn't do something crazy.": "Trông có vẻ khá là chấn động tâm lý (shell-shocked) đấy. Hy vọng là cậu ta đéo làm ra điều gì điên rồ.",
  "Brian": "Brian",
  "Graff": "Graff",
  "I've seen enough combat to know when someone's getting close to their breaking point.": "Tôi đã nhìn thấy đủ các trận chiến để biết được khi nào thì một người đang tiến gần đến giới hạn chịu đựng (breaking point) của họ.",
  "TIP: Click [crouch] to turn your flashlight on or off.": "MẸO: Nhấn phím [crouch] để bật hoặc tắt đèn pin của bạn.",
  "Balsamic Vinegar": "Giấm Balsamic (Balsamic Vinegar)",
  "108 HERO Evan Woodrow": "108 NGƯỜI HÙNG (HERO) Evan Woodrow",
  "You want to go home?": "Cậu muốn về nhà sao?",
  "Shit, bottle's empty. I gotta run.": "Chết tiệt, cái bình cạn không cmnr. Tôi phải chạy thôi.",
  "Okay, but I get first dibs on bedrooms.": "Được thôi, nhưng tôi được quyền ưu tiên chọn phòng ngủ (bedrooms) trước nhé.",
  "Look, I don't know what you're trying to accomplish, but I've had enough of this.": "Nghe này, tôi đéo biết là cậu đang cố gắng hoàn thành cái chuyện đéo gì, nhưng tôi đã chịu đựng đủ cái đống rác rưởi này rồi đấy.",
  "Afa": "Afa",
  "I think we can set up a few surprises for the zeds.": "Tôi nghĩ chúng ta có thể thiết lập một vài bất ngờ dành cho bọn zeds.",
  "Just what we need.": "Chính xác là thứ mà chúng ta đang cần đây rồi.",
  "Once zeds overrun a building, they'll continue to occupy it unless we clear them out.": "Một khi bọn zeds đã tràn vào xâm chiếm (overrun) một tòa nhà, bọn chúng sẽ tiếp tục chiếm đóng ở đó trừ phi chúng ta dọn dẹp sạch sẽ bọn chúng.",
  "I can't say I'm totally relaxed, but when I see %1$s running around, talking like nothing's wrong, it makes me think maybe things aren't quite as bad as I thought. - %2$s": "Tôi đéo thể nói rằng mình hoàn toàn thoải mái được, nhưng khi tôi nhìn thấy %1$s chạy lăng xăng quanh đây, nói chuyện cứ như đéo có chuyện gì xảy ra, nó khiến cho tôi nghĩ rằng có lẽ mọi thứ đéo đến mức quá tồi tệ như tôi đã nghĩ. - %2$s",
  "Sato": "Sato",
  "141 STORY Lily Ritter": "141 CỐT TRUYỆN (STORY) Lily Ritter",
  "Okay, that's about it. I'll stay in touch on the radio and talk you through everything.": "Được rồi, thế là xong. Tôi sẽ giữ liên lạc trên sóng radio và hướng dẫn cho cậu vượt qua mọi chuyện.",
  "I'm lucky they didn't hear that.": "Tôi thật may mắn vì bọn chúng đã đéo nghe thấy tiếng động đó.",
  "Game Menu": "Menu Trò Chơi (Game Menu)",
  "Colton!": "Colton!",
  "Hey... Do you... do you think you could do me a favor while you're out there?": "Này... Cậu có... cậu có nghĩ rằng cậu có thể giúp tôi một việc trong khi cậu đang ở ngoài đó được đéo?",
  "ATTITUDE: Wigged Out": "THÁI ĐỘ: Sợ Hãi Cực Độ (Wigged Out)",
  "117 STORY SWAT Officer": "117 CỐT TRUYỆN Sĩ Quan Đặc Nhiệm SWAT (SWAT Officer)",
  "There was a seat open, sir. We filled it.": "Có một chỗ ngồi còn trống, thưa ngài. Nên chúng tôi đã lấp đầy nó.",
  "Progress: %d/%d": "Tiến độ (Progress): %d/%d",
  "MORALE ISSUE: Overbearing Personality": "VẤN ĐỀ VỀ TINH THẦN (MORALE ISSUE): Tính Cách Độc Đoán (Overbearing Personality)",
  "Simon": "Simon",
  "A workshop focused on construction and car repair.": "Một xưởng chế tạo (workshop) tập trung vào công việc xây dựng và sửa chữa xe ô tô.",
  "You stay the fuck away from %2$s, %1$s. Next time it won't just be an argument.": "Mày hãy tránh xa cái thân xác khốn khiếp của mày khỏi %2$s đi, %1$s. Lần tới sẽ đéo chỉ là một cuộc tranh cãi đâu.",
  "Christ, that's loud.": "Lạy Chúa, to mồm quá đấy.",
  "Black Friday, this is Highroad Actual. Give me your officer in charge.": "Black Friday, đây là Highroad Actual. Nối máy cho tôi với sĩ quan chỉ huy của anh.",
  "+25": "+25",
  "+85%": "+85%",
  "Christ, what a bunch of junk. I'll bring it anyway.": "Lạy Chúa, đúng là một đống rác rưởi mà. Dù sao thì tôi cũng sẽ mang theo nó.",
  "Heads up the church in Spencer's Mill. Good at building up our spirits, even in the darkest of times.": "Quản lý nhà thờ ở thị trấn Spencer's Mill. Rất giỏi trong việc xây dựng và củng cố tinh thần cho chúng ta, ngay cả trong những thời khắc tăm tối nhất.",
  "Hmmm.": "Hmmm.",
  "Damn right I would have!": "Đúng cmnr tôi đã làm vậy đấy!",
  "Leave Trumbull Valley.": "Rời Khỏi Thung Lũng Trumbull.",
  "Thanks, that kinda helped.": "Cảm ơn nhé, nó phần nào cũng đã giúp ích cho tôi.",
  "We are all the Lord's hands. Now use those hands to gather these supplies. What's mine is yours, my friend.": "Tất cả chúng ta đều là những đôi bàn tay của Chúa. Bây giờ hãy sử dụng những đôi bàn tay đó để thu thập số đồ tiếp tế này đi. Những gì của tôi cũng là của cậu, bạn của tôi.",
  "Valoaga": "Valoaga",
  "Letting them get a little close, don't you think?": "Để cho bọn chúng tiến đến hơi gần quá rồi đấy, cậu đéo nghĩ vậy sao?",
  "Come on. You're carrying this.": "Đi nào. Cậu sẽ phải mang vác cái thứ này đấy.",
  "It's all about staying calm under pressure. I reload my guns a lot faster now. (Weapon Specialization available)": "Tất cả chỉ là việc giữ bình tĩnh trước những áp lực (pressure). Bây giờ tôi nạp đạn cho súng của mình nhanh hơn rất nhiều rồi. (Có thể chọn Chuyên Môn Vũ Khí - Weapon Specialization)",
  "Easy. Easy there.": "Bình tĩnh nào. Bình tĩnh lại đi.",
  "Well check out that vicious little fucker!": "Chà xem con chó đẻ nhỏ bé hung hãn đó kìa!",
  "131 HERO Cpt. Diane Montressor": "131 NGƯỜI HÙNG (HERO) Đại Úy Diane Montressor",
  "Come on, people, we're gonna get through this, trust me.": "Thôi nào mọi người, chúng ta sẽ vượt qua được chuyện này thôi, hãy tin tưởng tôi.",
  "Hurry up. We're not alone out here.": "Nhanh lên nào. Chúng ta đéo hề đơn độc ở ngoài này đâu.",
  "Gonna need something big to take that one down.": "Sẽ cần đến thứ gì đó lớn hơn để có thể hạ gục được con đó đấy.",
  "We just lost one!": "Chúng ta vừa mất đi một người!",
  "I've got this. Don't worry.": "Tôi lo được chuyện này mà. Đừng lo lắng.",
  "Bryant": "Bryant",
  "All your friends are dead!": "Tất cả bạn bè của cậu đều đã chết hết cmnr!",
  "McReady Farmhouse": "Khu Nông Trại Của Gia Đình McReady",
  "TIP: Hold [sprint] + [xi_use] while sneaking to kill a zombie instantly": "MẸO: Giữ phím [sprint] + [xi_use] trong khi đang lén lút (sneaking) để tiêu diệt một con zombie ngay lập tức",
  "+Exhaustion For Runners": "+Mức Độ Kiệt Sức Đối Với Á Quân (Runners)",
  "SURVIVAL TACTICS: Illness Recovery": "CHIẾN THUẬT SINH TỒN (TACTICS): Quá Trình Hồi Phục Bệnh (Illness Recovery)",
  "Kill 100 Zombies with Blunt Weapons. (Breakdown Level 1 or Higher)": "Tiêu diệt 100 Zombies bằng Vũ Khí Cùn (Blunt Weapons). (Cấp Độ Sụp Đổ Breakdown Level từ 1 trở lên)"
};

const file = 'output/languages/chunks/btxt_chunk_183.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_183.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk183[r.sourceText]) {
    r.translatedText = chunk183[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 183 successfully!');
