const fs = require('fs');
const chunk198 = {
  "Always wanted to quit her job, but definitely not like this.": "Cô ấy vẫn luôn mong muốn có thể từ bỏ đi cái công việc hiện tại của mình, nhưng chắc chắn đéo phải là theo cái cách tồi tệ như thế này.",
  "God, my first place was a shithole. I loved it.": "Chúa ơi, cái chỗ ở đầu tiên của tôi đúng là một cái hố phân (shithole) thảm hại. Nhưng tôi thực sự rất thích nó.",
  "23 GENERIC Virginia Dalhgren": "23 CHUNG (GENERIC) Virginia Dalhgren",
  "Hey, I appreciate it. Too bad I'm, uh, out of ammo, or I'd totally come with you. Totally.": "Này, tôi thực sự rất cảm kích vì điều đó. Chỉ hơi tiếc là tôi đã, uh, xài hết sạch sành sanh đạn dược cmnr, nếu đéo thì tôi hoàn toàn có thể đi cùng với cậu. Chắc chắn là như vậy rồi.",
  "It's been a pleasure doing business with you.": "Thực sự rất hân hạnh vì đã được cùng hợp tác làm ăn với cậu.",
  "Funeral Director": "Người Chuyên Đứng Ra Quản Lý Các Dịch Vụ Tang Lễ (Funeral Director)",
  "We could put just about anything here as long as we put a tent over it.": "Chúng ta có thể đặt gần như bất cứ một thứ đéo gì ở đây miễn là chúng ta có dựng lên một cái túp lều (tent) để che chắn cho nó.",
  "Crusty?": "Kẻ Cộc Cằn Khó Tính (Crusty)?",
  "Need to harden this position.": "Chúng ta cần phải củng cố và thắt chặt hệ thống phòng ngự ở khu vực này.",
  "Winsor": "Winsor",
  "Stay sharp, we got a feral!": "Hãy luôn giữ sự tỉnh táo, chúng ta vừa phát hiện ra một con feral!",
  "Here come the zeds.": "Lũ zeds đang kéo đến đây rồi.",
  "Okay, care to elaborate on that?": "Okay, vậy cậu có phiền đéo nếu như giải thích rõ ràng hơn một chút về chuyện đó?",
  "Let's clear these bastards out. You coming?": "Hãy cùng nhau dọn dẹp sạch sẽ lũ khốn nạn (bastards) này đi. Cậu có muốn đi cùng với chúng tôi đéo?",
  "Like hell. You know what you have to do.": "Giống như dưới địa ngục vậy. Cậu biết rõ là cậu cần phải làm những gì mà.",
  "NOTE: I Still Can't Believe It": "TỜ GHI CHÚ (NOTE): Cho Đến Tận Bây Giờ Tôi Vẫn Đéo Thể Nào Tin Được Chuyện Đó",
  "Increased Outpost Capacity": "Đã Gia Tăng Sức Chứa Cho Tiền Đồn (Outpost)",
  "Training Mats": "Những Tấm Thảm Tập Luyện (Training Mats)",
  "I can't go on on foot.": "Tôi đéo thể nào tiếp tục đi bộ được nữa đâu.",
  "Can you help us clear out an infestation?": "Cậu có thể giúp đỡ chúng tôi dọn dẹp sạch sẽ một cái ổ dịch (infestation) đéo?",
  "Zheng": "Zheng",
  "They seem to like noise. They'll come check out anything loud they hear.": "Bọn chúng dường như rất thích những tiếng ồn (noise). Bọn chúng sẽ tìm đến để kiểm tra bất kỳ một thứ đéo gì có âm thanh phát ra đủ lớn mà bọn chúng có thể nghe thấy được.",
  "Helps firefighters gain some leverage.": "Giúp cho những người lính cứu hỏa có thêm một vài lợi thế (leverage) để cạy mở mọi thứ.",
  "Build": "Xây Dựng (Build)",
  "Not only does it help everybody, it's got to be easier than hoping we get lucky with our scavenging, right?": "Nó đéo chỉ giúp đỡ cho tất cả mọi người, mà nó chắc chắn sẽ dễ dàng hơn rất nhiều so với việc chỉ biết ngồi hy vọng rằng chúng ta sẽ gặp may mắn ở trong những chuyến đi thu nhặt đồ nhặt phế liệu (scavenging), có đúng đéo?",
  "Okay, you two, break it up.": "Okay, hai người các cậu, hãy mau dừng lại giải tán đi.",
  "Time to check this out.": "Đã đến lúc để đi kiểm tra nơi này rồi.",
  "No can do, ma'am. We're shorthanded enough without leaving soldiers to die.": "Chúng tôi đéo thể nào làm được điều đó, thưa cô. Hiện tại chúng tôi đang cực kỳ thiếu hụt nhân sự đéo thể nào để cho những người lính (soldiers) của mình phải đi vào chỗ chết được.",
  "ATTITUDE: Pathetic": "THÁI ĐỘ (ATTITUDE): Thật Là Thảm Hại (Pathetic)",
  "Whenever there is a job to do, you can absolutely rely on me to be somewhere else. (Reduced Stamina)": "Bất cứ khi nào có một công việc nào đó cần phải được hoàn thành, bạn hoàn toàn có thể tin tưởng rằng tôi chắc chắn sẽ lảng vảng ở một cái nơi đéo nào đó khác chứ đéo phải ở đây. (Bị Suy Giảm Lượng Thể Lực Stamina)",
  "Supplies are here.": "Nguồn vật tư đồ tiếp tế (Supplies) đều đang nằm ở đây.",
  "Oh, don't worry 'bout me, I got this shit!": "Oh, đừng có quá lo lắng cho tôi, tôi hoàn toàn có thể tự mình xử lý được cái đống cứt này!",
  "Let's make sure everyone is armed!": "Hãy đảm bảo rằng tất cả mọi người đều đã được trang bị vũ khí đầy đủ!",
  "You're a lifesaver. I did not want to go back out there.": "Cậu đúng là một ân nhân cứu mạng (lifesaver) đấy. Tôi đéo hề muốn phải tiếp tục quay trở ra ngoài đó một chút đéo nào đâu.",
  "You really ought to pop some painkillers.": "Cậu thực sự rất nên cắn thêm một vài viên thuốc giảm đau (painkillers) vào đi.",
  "Langley": "Langley",
  "Okay, head on in. I've got more business to take care of.": "Okay, hãy đi thẳng vào bên trong đi. Tôi đang có rất nhiều việc cần phải giải quyết đấy.",
  "I think the stress is getting to him.": "Tôi nghĩ rằng sự căng thẳng (stress) áp lực tột độ đó đang dần bắt đầu ảnh hưởng trực tiếp đến cậu ấy cmnr.",
  "Fuller": "Fuller",
  "Some folks could use a few pointers on how to kick zed butt. -%2$s": "Một số người thực sự rất cần đến một vài lời chỉ dẫn chi tiết về cái cách làm thế nào để có thể đá đít (kick butt) được bọn zeds. -%2$s",
  "COMPLETED: Tanner Lake": "ĐÃ HOÀN THÀNH XUẤT SẮC (COMPLETED): Tanner Lake",
  "Yeah, we got the baddest motherfuckers in the whole valley right here!": "Yeah, chúng ta đang có được những kẻ nguy hiểm (baddest motherfuckers) bậc nhất ở trong toàn bộ cái thung lũng chết tiệt này đang tập trung lại ngay tại đây!",
  "About as big-hearted and generous as they come. If it were up to him, he'd hand out all the food in the store to anybody who needed it; that's just what people do in a crisis, right?": "Anh ấy được biết đến là một người có trái tim vô cùng nhân hậu và cực kỳ hào phóng (generous). Nếu như được phép tự mình quyết định mọi chuyện, anh ấy có lẽ sẽ đéo ngần ngại mang toàn bộ số lượng thức ăn (food) hiện đang có ở bên trong cửa hàng để đem đi phân phát cho bất kỳ một người nào đang thực sự cần đến nó; đó chính xác là những gì mà mọi người thường hay làm ở trong một cuộc khủng hoảng (crisis), có đúng đéo?",
  "One one tango mike papa two five charlie zero five romeo.": "One one tango mike papa two five charlie zero five romeo.",
  "Shit, she said she was a dental hygienist. Who makes that up as a career?": "Chết tiệt thật, cô ấy từng nói rằng cô ấy là một chuyên viên vệ sinh nha khoa (dental hygienist). Có một kẻ điên rồ đéo nào lại đi bịa đặt về cái công việc (career) kỳ lạ đó cơ chứ?",
  "Need a tools expert.": "Đang Cần Có Một Chuyên Gia Về Các Loại Công Cụ (Tools Expert).",
  "Shadow": "Shadow",
  "So... we've got a visitor. One of Job Wilkerson's guys.": "Vậy... chúng ta vừa mới có một vị khách (visitor) ghé thăm. Một trong những tên thuộc hạ của Job Wilkerson.",
  "40 GENERIC Becky Silverstone": "40 CHUNG (GENERIC) Becky Silverstone",
  "Provides new item creation options.": "Cung Cấp thêm nhiều tùy chọn chế tạo vật phẩm mới.",
  "Max out a community member's Cardio skill.": "Đạt đến mức giới hạn tối đa (Max out) đối với kỹ năng Sức Khỏe Tim Mạch (Cardio) của một thành viên nào đó ở trong cộng đồng.",
  "A high fever and a lot of pus resulting from a zombie bite. (Health and Stamina penalty)": "Một cơn sốt cao (high fever) cực kỳ khủng khiếp đi kèm với rất nhiều dịch mủ (pus) chảy ra sau khi bị một con zombie cắn trúng. (Hình phạt làm suy giảm đi Lượng Máu Health và Thể Lực Stamina)",
  "Look ... I'm not ... my ex-wife, she's still in the city. She's a medical doctor. You save her, she'll save a lot more.": "Nghe đây... Tôi đéo phải là... người vợ cũ của tôi, cô ấy hiện tại vẫn đang ở bên trong thành phố. Cô ấy là một bác sĩ y khoa (medical doctor). Nếu như cậu chịu cứu sống cô ấy, cô ấy chắc chắn sẽ cứu được thêm rất nhiều sinh mạng khác nữa.",
  "<Nodding off>": "<Gật gà gật gù vì buồn ngủ Nodding off>",
  "ProgressScore": "Điểm Số Quá Trình (ProgressScore)",
  "They were always having trouble maintaining their defenses. I guess when the hordes came they couldn't hold them off.": "Bọn họ trước giờ vẫn luôn gặp phải rắc rối ở trong việc duy trì cái hệ thống phòng thủ (defenses) của mình. Tôi đoán là khi những bầy hordes kéo đến bọn họ đã đéo thể nào cản bước được bọn chúng.",
  "Savea": "Savea",
  "KILLED: Madison Grant": "BỊ GIẾT CHẾT (KILLED): Madison Grant",
  "Ready to move out.": "Đã chuẩn bị sẵn sàng để có thể di chuyển ra ngoài.",
  "Brockfully in the air.": "Brock đang ở trong không khí.",
  "Anything else is a waste of time. I can lock onto a zombie's head from farther away now.": "Bất cứ một thứ đéo gì khác cũng chỉ là sự lãng phí thời gian mà thôi. Hiện tại tôi đã có thể khóa chặt mục tiêu vào thẳng phần đầu của một con zombie từ một khoảng cách vô cùng xa.",
  "None, this is a separate opportunity.": "Đéo có, đây là một cơ hội (opportunity) hoàn toàn riêng biệt.",
  "Pistol: Mi.Le .45": "Súng Lục (Pistol): Mi.Le .45",
  "Good news--we're not alone out here.": "Tin tốt đây--chúng ta đéo chỉ có một mình ở ngoài này đâu.",
  "Space on the RV is limited. I need to talk to everybody, and decide who's coming and who's staying behind. (NEW DIALOGUE OPTIONS)": "Không gian trống rỗng ở trên chiếc xe RV hiện đang rất giới hạn. Tôi cần phải nói chuyện trực tiếp với tất cả mọi người, và sau đó tự mình đưa ra quyết định xem ai sẽ là người được đi cùng và ai sẽ là kẻ phải tiếp tục ở lại nơi này. (NHỮNG TÙY CHỌN HỘI THOẠI MỚI NEW DIALOGUE OPTIONS ĐÃ XUẤT HIỆN)",
  "Sanitary Facilities": "Các Khu Vực Cơ Sở Vệ Sinh (Sanitary Facilities)",
  "On RV": "Ở Trên Chiếc Xe RV",
  "Find Quentin": "Tìm Kiếm (Find) Quentin",
  "I could sure use a pep talk right about now.": "Ngay lúc này tôi thực sự rất cần có được một vài lời động viên (pep talk) để khích lệ tinh thần đấy.",
  "A Gifted Leader leads from the front lines, getting into the thick of it with their people and encouraging others to be their best.": "Một Người Lãnh Đạo Tài Ba (Gifted Leader) luôn biết cách đứng ra dẫn dắt mọi người ngay từ ngoài tiền tuyến, tự mình dấn thân vào những nơi khó khăn khốc liệt nhất cùng với những người đồng đội của bọn họ và liên tục khích lệ (encouraging) những người khác cố gắng thể hiện được những tố chất tốt nhất của bản thân.",
  "Greyhound One, I show that you're at the LZ. Finally.": "Greyhound One, hệ thống của tôi đang hiển thị rằng các người hiện đang ở tại khu vực bãi đáp (LZ) cmnr. Cuối cùng thì cũng đã đến nơi.",
  "I mean, would it have killed us to do a little more cardio?": "Ý tôi là, liệu việc luyện tập thêm một chút về cái sức khỏe tim mạch (cardio) chết tiệt này có thể giết chết được chúng ta hay đéo chứ?",
  "38 GENERIC Danica Coleman": "38 CHUNG (GENERIC) Danica Coleman",
  "That last attack... well... look, you need to know about %1$s.": "Cuộc tấn công tồi tệ cuối cùng đó... chà... nghe đây, cậu cần phải biết rõ hơn về %1$s.",
  "58 GENERIC Andy Diller": "58 CHUNG (GENERIC) Andy Diller",
  "There's somebody here to see you.": "Đang có một người ở đây muốn được gặp cậu đấy.",
  "Hana": "Hana",
  "Whisper": "Lời Thì Thầm (Whisper)",
  "On the way back to base, Ms. Martin shoved most of the intel you retrieved from her office out the door of the helicopter.": "Ở trên đường quay trở về căn cứ, Cô Martin đã thẳng tay ném hầu hết tất cả những thông tin tình báo (intel) quan trọng mà cậu vừa mới vất vả thu thập được từ văn phòng của cô ấy ra ngoài cửa của chiếc máy bay trực thăng.",
  "COMMUNITY: Encouragement": "CỘNG ĐỒNG (COMMUNITY): Lời Động Viên Khích Lệ Tinh Thần (Encouragement)",
  "Umm... I just wanted to say, well... I like you.": "Umm... Tôi chỉ muốn nói rằng, chà... tôi có tình cảm với cậu.",
  "Just think of it as payback for that time that you \"volunteered\" us for the running of the bulls in Pamplona.": "Hãy cứ coi chuyện đó như là một sự đền đáp cho cái lần mà cậu đã \"tình nguyện\" đăng ký cho chúng ta tham gia vào lễ hội chạy đua với bò tót (running of the bulls) chết tiệt ở Pamplona đi nhé.",
  "Change of scenery'll do you good.": "Việc thay đổi lại khung cảnh xung quanh sẽ rất tốt cho tâm trạng của cậu đấy.",
  "Finance": "Lĩnh Vực Tài Chính (Finance)",
  "SURVIVAL TACTICS: Personal Skills": "CÁC CHIẾN THUẬT SINH TỒN (SURVIVAL TACTICS): Các Kỹ Năng Cá Nhân (Personal Skills)",
  "Gary": "Gary",
  "Tina": "Tina",
  "We're almost finished, keep it up!": "Chúng ta sắp hoàn thành xong công việc rồi, hãy tiếp tục cố gắng phát huy nhé!",
  "Boom, baby!": "Boom, cưng ơi!",
  "INSENSITIVE people have their drawbacks.": "Những người VÔ CẢM (INSENSITIVE) thường mắc phải những hạn chế yếu điểm (drawbacks) riêng của bản thân mình.",
  "Away from home": "Đang Rời Xa Căn Cứ Mái Ấm (home)",
  "Just what we needed!": "Chính xác là những gì mà chúng ta đang cần!",
  "Are you sure you wish to delete this save?": "Bạn có thực sự chắc chắn là bạn muốn xóa (delete) bỏ cái file save lưu trữ dữ liệu này đéo?",
  "You remember those people at the grange? Quentin and Becca and the rest?": "Cậu có còn nhớ những con người khốn khổ ở khu trang trại (grange) đéo? Quentin và Becca cùng với tất cả những người còn lại đó?",
  "Lily, how much time do I have to take care of this?": "Lily, tôi sẽ có khoảng bao nhiêu thời gian rảnh rỗi để có thể giải quyết được chuyện này đây?",
  "Vivian": "Vivian",
  "Charlene": "Charlene",
  "We've got no room for the weak here.": "Chúng tôi đéo còn đủ chỗ trống để có thể chứa chấp thêm cho những kẻ hèn nhát yếu đuối ở đây đâu.",
  "Low Morale causes your community members to act out.": "Chỉ Số Tinh Thần (Morale) Xuống Quá Thấp sẽ khiến cho các thành viên ở trong cộng đồng của bạn bắt đầu có những hành vi vô cùng mất kiểm soát.",
  "The .500 S&W round, used for shock and awe.": "Loại đạn .500 S&W, thường được sử dụng để tạo ra sự chấn động (shock) cũng như gieo rắc nên nỗi kinh hoàng tột độ."
};

const file = 'output/languages/chunks/btxt_chunk_198.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_198.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk198[r.sourceText]) {
    r.translatedText = chunk198[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 198 successfully!');
