const fs = require('fs');
const chunk127 = {
  "Upgrade to Bunkhouse": "Nâng Cấp lên Nhà Ngủ Tập Thể (Bunkhouse)",
  "Here they come on the left flank!": "Bọn chúng đến từ sườn bên trái kìa!",
  "Maybe I'll go out to the infirmary. And just lie there by myself, seeing as how nobody's working it.": "Có lẽ tôi sẽ ra ngoài bệnh xá. Và chỉ nằm đó một mình thôi, xem xét việc đéo có ai làm việc ở đó cả.",
  "We've finally got our orders": "Cuối cùng thì chúng ta cũng có mệnh lệnh rồi",
  "+30 Food, Ammo, Medicine, Fuel, and Materials capacity.": "Tăng sức chứa Thức ăn, Đạn dược, Thuốc men, Nhiên liệu, và Vật liệu thêm 30.",
  "Catch you later.": "Gặp cậu sau nhé.",
  "Don't give me shit for liking cooking shows. My grandma raised me on Julia Child, OK? (Good cook.)": "Đừng có mỉa mai tôi vì thích xem các chương trình nấu ăn. Bà tôi đã nuôi tôi lớn bằng mấy chương trình của Julia Child đấy, rõ chưa? (Là một đầu bếp giỏi.)",
  "Well, you're human after all.": "Chà, rốt cuộc thì cậu cũng chỉ là con người thôi.",
  "What's the sitch?": "Tình hình sao rồi?",
  "I'll just drop this in the stockpile.": "Tôi sẽ ném cái này vào kho dự trữ.",
  "18 GENERIC Dr. Nancy Paxton": "18 GENERIC Tiến sĩ Nancy Paxton",
  "Let me look around a bit more.": "Để tôi nhìn quanh thêm một chút.",
  "Let's rock and roll, brother!": "Chiến thôi, người anh em!",
  "Marshall": "Marshall",
  "Plastic Sheeting": "Tấm Nhựa Bọc",
  "+45": "+45",
  "Collects energy from the sun during the day, and charges batteries to use at night.": "Thu thập năng lượng từ mặt trời vào ban ngày, và sạc pin để sử dụng vào ban đêm.",
  "I think so. Let's move folks over now.": "Tôi cũng nghĩ vậy. Hãy chuyển mọi người qua đó ngay bây giờ.",
  "Wakizashi": "Kiếm ngắn Wakizashi",
  "RV: Refueling Complete": "Xe RV: Đã Đổ Đầy Nhiên Liệu",
  "Jesus, watch the doors!": "Chúa ơi, canh chừng các cánh cửa đi!",
  "Creates some improvised painkillers.": "Chế tạo một vài viên thuốc giảm đau tự chế.",
  "I'm not alone in here.": "Tôi đéo ở một mình trong này.",
  "It's another beautiful day.": "Lại là một ngày đẹp trời khác.",
  "We go to work.": "Chúng ta bắt đầu làm việc thôi.",
  "Now really isn't a good time, sorry.": "Bây giờ thực sự đéo phải lúc thích hợp đâu, xin lỗi nhé.",
  "Me and a couple guys from my unit came up here to do some deer hunting.": "Tôi và vài anh bạn trong đơn vị lên đây để đi săn hươu.",
  "Didn't survive a hurricane in Louisiana to be killed by this shit. Laughs in the face of disaster, because what else can you do?": "Đéo phải sống sót qua một trận cuồng phong ở Louisiana để rồi bị giết bởi cái mớ chết tiệt này. Cười vào mặt thảm họa, vì cậu còn có thể làm gì khác nữa chứ?",
  "We were foolish to ever think you could be trusted. - Your reluctant neighbor, %1$s": "Chúng tôi đã quá ngu ngốc khi nghĩ rằng có thể tin tưởng các người. - Người hàng xóm bất đắc dĩ của các người, %1$s",
  "Christmas dinner comes early this year.": "Bữa tối Giáng Sinh năm nay đến sớm thật đấy.",
  "My dad got me my first ham radio set when I was 12. I guess I kinda got hooked.": "Bố đã mua cho tôi bộ đài phát thanh vô tuyến nghiệp dư đầu tiên khi tôi 12 tuổi. Tôi đoán là tôi đã bị nghiện món đó.",
  "So what exactly are these laws?": "Vậy chính xác thì những luật lệ đó là gì?",
  "You know it. Our people get shit done. Nobody here's afraid to mix it up with zed.": "Biết rồi đấy. Người của chúng ta đéo nói suông mà luôn làm nên chuyện. Ở đây đéo có ai sợ phải đụng độ với lũ zed cả.",
  "The Gardener": "Người Làm Vườn",
  "Sure it bucks like a donkey with a bee under its saddle, but it's just so satisfying!": "Đồng ý là nó giật tung người như một con lừa bị ong đốt dưới yên, nhưng như thế mới đã chứ!",
  "We will?": "Chúng ta sẽ làm vậy sao?",
  "This is gonna take a while. Hope you're ready for company.": "Chuyện này sẽ mất một lúc đây. Hy vọng cậu đã sẵn sàng cho một vài người bạn đồng hành.",
  "We should collect some more medicine.": "Chúng ta nên đi kiếm thêm chút thuốc men.",
  "CLEO Wrecker": "Cứu Hộ CLEO",
  "Dammit.": "Chết tiệt.",
  "What's the point of even trying against something like that?": "Cố gắng chống lại một thứ như thế thì có ý nghĩa đéo gì cơ chứ?",
  "Yeah. Let's get this shit over with.": "Phải. Hãy kết thúc cái đống cứt này đi.",
  "Okay, look. Before all this started, I was... I had problems, okay?": "Được rồi, nghe này. Trước khi tất cả chuyện này bắt đầu, tôi đã... tôi đã có những vấn đề riêng, okay?",
  "Bat": "Gậy bóng chày",
  "Caution is key--now I'm less likely to break stuff when I search.": "Cẩn thận là trên hết--giờ thì tôi ít có khả năng làm vỡ đồ đạc hơn khi tôi lục soát.",
  "Nice place.": "Nơi này đẹp đấy.",
  "TIP: Press [drop] to drop rucksacks.": "MẸO: Nhấn [drop] để thả ba lô xuống.",
  "For the last time, asshole, nobody's going to help you rescue your action figure collection! We got enough problems already. -%1$s": "Nói lần cuối nhé, thằng khốn, đéo có ai rảnh rỗi đi giúp cậu giải cứu cái bộ sưu tập mô hình hành động của cậu đâu! Chúng ta đã có quá đủ rắc rối rồi. -%1$s",
  "I'm up. I'll take a look around.": "Tôi dậy rồi. Tôi sẽ đi quan sát xung quanh.",
  "Hell with this. Y'all want to risk your asses for his dumb fuck pal, knock yourselves out.": "Chết tiệt. Các người muốn liều mạng vì cái thằng bạn ngu đần vãi lồn của cậu ta thì cứ tự nhiên.",
  "Highroad Actual": "Chỉ huy Highroad",
  "They're all over me!": "Chúng đang bu lấy tôi!",
  "Bout time somebody showed up to rescue my ass!": "Đến lúc phải có ai đó xuất hiện và cứu cái mạng già này của tôi rồi chứ!",
  "Rifle: M14 Talon DMR": "Súng trường: M14 Talon DMR",
  "Skaggs": "Skaggs",
  "A special attack that hits everything in a large area in front of you.": "Một đòn tấn công đặc biệt đánh trúng mọi thứ trong một khu vực rộng lớn ngay phía trước bạn.",
  "Seriously, though, rule number one: All the food stays in here, and it stays sealed.": "Nghiêm túc đấy, quy tắc số một: Tất cả thức ăn phải để ở trong này, và nó phải được niêm phong kín.",
  "No more painkillers.": "Không còn thuốc giảm đau nữa.",
  "I think we can hide here.": "Tôi nghĩ chúng ta có thể trốn ở đây.",
  "It might sound corny, but I've been encouraging people to share stories about where they're from. Turns out people have a lot more in common than they might think. - %1$s": "Nghe có vẻ sến súa, nhưng tôi đã và đang khuyến khích mọi người chia sẻ những câu chuyện về nguồn cội của họ. Hóa ra mọi người có nhiều điểm chung hơn họ tưởng. - %1$s",
  "How so?": "Ý cậu là sao?",
  "Not one perimeter breach.": "Không có một vụ chọc thủng vành đai nào cả.",
  "Awesome! Now that we've established an outpost, we can really start pushing the zombies back and reclaiming the valley.": "Tuyệt vời! Bây giờ khi đã thiết lập được một tiền đồn, chúng ta có thể thực sự bắt đầu đẩy lùi bọn zombie và giành lại thung lũng.",
  "Keep moving! You can feel bad on your own time.": "Tiếp tục di chuyển đi! Cậu có thể dành thời gian để cảm thấy tồi tệ sau.",
  "Escobar": "Escobar",
  "That's some nice work.": "Làm tốt lắm.",
  "Don't know what for, but I figure if anybody can track 'em down, it'd be you.": "Đéo biết để làm gì, nhưng tôi cho rằng nếu có ai có thể truy lùng được bọn chúng, thì người đó chính là cậu.",
  "He's not well, son, and he's gonna be worse if I have to keep tending to these interruptions.": "Ông ấy không khỏe đâu, chàng trai, và ông ấy sẽ trở nên tồi tệ hơn nếu tôi phải tiếp tục giải quyết mấy vụ làm phiền này.",
  "Hey, don't be a stranger.": "Này, đừng có làm người dưng nhé.",
  "You know how it sucks when your hatchet breaks right in the middle of splatting zombies?": "Cậu biết cái cảm giác tồi tệ thế nào khi cái rìu của cậu bị gãy làm đôi ngay lúc đang chẻ sọ bọn zombie không?",
  "Preston": "Preston",
  "I met Eli, the youngest Wilkerson brother, when I rescued Jacob.": "Tôi đã gặp Eli, cậu em út nhà Wilkerson, khi tôi giải cứu Jacob.",
  "From Home": "Từ Căn Cứ",
  "Y'know, I used to think that *I* was a good shot.": "Cậu biết không, tôi từng nghĩ rằng *TÔI* là một tay súng thiện xạ đấy.",
  "Hours spent organizing events and debating with the opposition can hone arguing skills to a razor-sharp edge.": "Hàng giờ dành để tổ chức các sự kiện và tranh luận với phe đối lập có thể rèn luyện các kỹ năng tranh luận trở nên sắc bén.",
  "Insulation": "Vật Liệu Cách Nhiệt",
  "Watch your ammo and try to reload when it's safe.": "Hãy chú ý đến lượng đạn của bạn và cố gắng nạp đạn khi an toàn.",
  "Geez, that thing coulda exploded in my hand! The hell is wrong with people? - %1$s": "Trời ạ, thứ đó có thể đã phát nổ ngay trên tay tôi! Cái đéo gì đang xảy ra với những con người này vậy? - %1$s",
  "Okay, but I can't wait around forever.": "Được rồi, nhưng tôi đéo thể chờ đợi mãi được đâu.",
  "20 MIL Cpl Amy Prince": "20 MIL Hạ sĩ Amy Prince",
  "Allows you to repair and unjam weapons at the Supply Locker.": "Cho phép bạn sửa chữa và thông nòng vũ khí tại Tủ Đồ (Supply Locker).",
  "Oh... the expiration date said \"2010,\" not \"2018.\" - %1$s": "Oh... hạn sử dụng ghi là \"2010,\" đéo phải \"2018.\" - %1$s",
  "That's a good place to put your anger.": "Đó là một chỗ tốt để trút cơn giận của cậu đấy.",
  "I don't want to just give up, but...": "Tôi không muốn cứ thế mà bỏ cuộc đâu, nhưng...",
  "They're still out there.": "Bọn chúng vẫn đang ở ngoài kia.",
  "If you're not too busy, I could use a hand on this trade run.": "Nếu cậu không quá bận, tôi rất cần sự giúp đỡ trong chuyến giao thương này.",
  "Sit tight, we'll be there soon.": "Ngồi yên đó, chúng tôi sẽ đến đó ngay.",
  "Volpe": "Volpe",
  "Rifle: Arctic Warrior": "Súng trường: Arctic Warrior",
  "Hey look, you didn't hear this from me, but you need to be extra careful next time you go out.": "Này nghe đây, cậu chưa hề nghe điều này từ tôi đâu, nhưng cậu cần phải cẩn thận hơn vào lần đi ra ngoài tiếp theo đấy.",
  "Wanker.": "Đồ khốn nạn.",
  "I just need to get home and I'll be okay.": "Tôi chỉ cần về đến nhà là tôi sẽ ổn thôi.",
  "Dammit! This is taking longer than I thought.": "Chết tiệt! Chuyện này mất nhiều thời gian hơn tôi tưởng.",
  "Orc Sword": "Thanh Kiếm Của Orc",
  "Provides food daily": "Cung cấp thức ăn hàng ngày",
  "-%d Hour(s)": "-%d Giờ",
  "Resources: ????": "Tài Nguyên: ????",
  "Lucy": "Lucy",
  "Let's clear them out.": "Hãy dọn dẹp sạch bọn chúng đi.",
  "Great. I think we'll all benefit from this trade.": "Tuyệt. Tôi nghĩ tất cả chúng ta đều sẽ được hưởng lợi từ vụ giao dịch này."
};

const file = 'output/languages/chunks/btxt_chunk_127.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_127.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk127[r.sourceText]) {
    r.translatedText = chunk127[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 127 successfully!');
