const fs = require('fs');
const chunk163 = {
  "A few zeds down, a few billion more to go.": "Hạ được vài con zeds, còn vài tỷ con nữa phải lo.",
  "Give Quentin Some Space": "Cho Quentin Chút Không Gian Riêng",
  "Here, listen.": "Đây, nghe này.",
  "No longer tired.": "Đéo còn thấy mệt mỏi nữa.",
  "REPORT: Civilian in Distress": "BÁO CÁO: Dân thường Đang Gặp Nguy Hiểm",
  "Secretive": "Kín Đáo",
  "Ah great. Now we got screamers.": "À tuyệt quá cơ. Giờ chúng ta lại có thêm screamers nữa chứ.",
  "Gunderson": "Gunderson",
  "Whichever one of you dicks thought it would be funny to replace my tomato juice with sriracha sauce: vengeance is coming. Oh yes. You will suffer. - %1$s": "Thằng khốn nào trong số các cậu nghĩ rằng việc tráo nước ép cà chua của tôi bằng tương ớt sriracha là buồn cười: sự trả thù đang đến đấy. Ồ đúng vậy. Cậu sẽ phải đau khổ. - %1$s",
  "Kayla": "Kayla",
  "Somebody ought to step up to man the infirmary. Not doing us a lot of good otherwise.": "Ai đó nên bước ra để quản lý bệnh xá đi. Đéo thì nó cũng đéo mang lại nhiều lợi ích cho chúng ta đâu.",
  "Eliminate Stragglers": "Tiêu Diệt Những Kẻ Tụt Hậu",
  "We're about done. Thank you, by the way. I couldn't have done it without you.": "Chúng ta sắp xong rồi. Nhân tiện, cảm ơn nhé. Tôi đã đéo thể hoàn thành việc này nếu đéo có cậu.",
  "Welding Equipment": "Thiết Bị Hàn",
  "We're trying to save civilization here, soldier. Not just civilians. Highroad out.": "Chúng ta đang cố gắng cứu lấy cả một nền văn minh đấy, người lính à. Đéo chỉ là thường dân đâu. Highroad xin ngừng liên lạc.",
  "Do it! Target my position, danger close!": "Làm đi! Mục tiêu là vị trí của tôi, nguy hiểm cận kề!",
  "Firearms Training": "Huấn luyện Bắn súng",
  "Reduced Sickness Recovery chance.": "Giảm cơ hội Phục hồi Bệnh tật.",
  "Covering fire on demand.": "Cung cấp hỏa lực yểm trợ theo yêu cầu.",
  "How's everybody doing?": "Mọi người dạo này thế nào rồi?",
  "134 NPC Lily Ritter": "134 NPC Lily Ritter",
  "Help with a \"delivery.\"": "Giúp thực hiện một chuyến \"giao hàng.\"",
  "Black Friday, Highroad Actual. We found another group of skilled personnel who got stranded trying to escape the city.": "Black Friday, đây là Highroad Actual. Chúng tôi đã tìm thấy một nhóm nhân sự lành nghề khác bị mắc kẹt khi đang cố gắng trốn thoát khỏi thành phố.",
  "Or... Wait, wait... Maybe… was I supposed to take a left back there? Shit. Do you mind watching my back while I check this?": "Hoặc... Khoan, khoan đã... Có lẽ... đáng lẽ ra tôi nên rẽ trái ở chỗ kia? Chết tiệt. Cậu có phiền canh chừng phía sau cho tôi trong khi tôi kiểm tra thứ này đéo?",
  "Sims": "Sims",
  "That ain't fuckin' happenin'.": "Chuyện đéo đó sẽ đéo bao giờ xảy ra đâu.",
  "Press [ul_radio_menu] to use the radio.": "Nhấn [ul_radio_menu] để sử dụng radio.",
  "Told Quentin": "Đã Kể Với Quentin",
  "How's it going?": "Mọi chuyện thế nào rồi?",
  "Topsoil": "Đất mặt (Topsoil)",
  "Dunno.": "Đéo biết nữa.",
  "It's empty! Go find stuff.": "Nó trống rỗng rồi! Hãy đi tìm đồ đi.",
  "Eats Anything": "Ăn Tạp (Eats Anything)",
  "Anything but a headshot, and you're wasting my time.": "Bất cứ thứ gì đéo phải là một cú headshot, và cậu đang làm lãng phí thời gian của tôi đấy.",
  "May be a danger to the community.": "Có thể là một mối nguy hiểm cho cộng đồng.",
  "You don't have to do this. We can-": "Cậu đéo cần phải làm vậy đâu. Chúng ta có thể-",
  "This game supports an autosave feature. When you see this icon please do not turn off your pc or remove the storage device.": "Trò chơi này hỗ trợ tính năng tự động lưu (autosave). Khi bạn nhìn thấy biểu tượng này, vui lòng đéo tắt PC hoặc tháo thiết bị lưu trữ.",
  "Wow. Thanks.": "Wow. Cảm ơn nhé.",
  "Trouble is, the Army blocked it off when they left. Probably trying to stop whatever this is from spreading.": "Vấn đề là, Quân đội đã chặn nó lại khi họ rời đi. Chắc là đang cố gắng ngăn chặn thứ này lây lan.",
  "Revolver: River Snake": "Súng Lục Ổ Quay: River Snake",
  "Get clear! I got these guys!": "Tránh ra! Để những gã này cho tôi!",
  "Hurt": "Bị thương",
  "Missed my chance to help out %1$s. Maybe next time. - %2$s.": "Đã bỏ lỡ cơ hội giúp đỡ %1$s. Có lẽ để lần sau vậy. - %2$s.",
  "Mouth Guards": "Miếng Bảo Vệ Răng (Mouth Guards)",
  "Assault Rifle: 416D": "Súng Trường Tấn Công: 416D",
  "Well, hell, can't ask for much more than that. See you all next time.": "Chà, chết tiệt, đéo thể đòi hỏi gì hơn được nữa. Hẹn gặp lại mọi người vào lần sau.",
  "I'm seriously getting sick of this rationing bullshit.": "Tôi đang thực sự phát ngán với cái trò khẩu phần ăn vớ vẩn này rồi đấy.",
  "Listen, I know there's some food here somewhere, I just... gotta find it. Please. It's for my brother.": "Nghe này, tôi biết có một ít thức ăn ở đâu đó quanh đây, tôi chỉ cần... tìm ra nó. Làm ơn. Là cho anh trai tôi.",
  "Technically speaking, I'm still leading a company--callsign: Greyhound--but with casualties and desertions it's barely above platoon strength.": "Nói đúng ra thì, tôi vẫn đang lãnh đạo một đại đội--hồ sơ định danh: Greyhound--nhưng với số người thương vong và đào ngũ, quy mô hiện tại chỉ nhỉnh hơn quân số của một trung đội.",
  "Bitch all you want, you know I'm right! None of you had the stones to do what had to be done.": "Muốn chửi bới sao thì tùy, cậu biết là tôi đúng mà! Đéo một ai trong số các người có gan để làm những gì cần phải làm cả.",
  "I really don't know about this guy. He says he's out here looking for his brother, and he's willing to trade his expertise with explosives for a place to stay. But I'm not sure I'm on board with a guy carrying a pack full of pipe bombs ...": "Tôi thực sự đéo biết rõ về gã này. Hắn nói hắn ra ngoài này để tìm anh trai mình, và hắn sẵn sàng trao đổi chuyên môn về chất nổ của mình để lấy một nơi trú ẩn. Nhưng tôi đéo chắc là mình đồng ý với việc chứa chấp một gã mang theo một balo đầy mìn ống...",
  "My body is ready. (Advanced Cardio and Fighting.)": "Cơ thể tôi đã sẵn sàng. (Kỹ năng Tim mạch và Chiến đấu nâng cao.)",
  "When we have freak sightings, we need to be more proactive about dealing with them. - %1$s": "Khi chúng ta phát hiện ra lũ dị dạng (freak), chúng ta cần chủ động hơn trong việc giải quyết chúng. - %1$s",
  "HOME: Epidemic": "NHÀ (HOME): Bệnh Dịch (Epidemic)",
  "Ain't like I got anything better to do while I'm drinking.": "Tôi cũng đéo có việc gì tốt hơn để làm trong lúc nhậu nhẹt cả.",
  "ADVICE: Build a Sleeping Area": "LỜI KHUYÊN (ADVICE): Xây Một Khu Vực Ngủ (Sleeping Area)",
  "Next time, kill the Juggernaut with a melee weapon.": "Lần sau, hãy giết con Juggernaut bằng một vũ khí cận chiến.",
  "You did good. I know things were looking pretty bleak to you, but just try and remember, everybody's here for you.": "Cậu làm tốt lắm. Tôi biết mọi chuyện có vẻ khá ảm đạm đối với cậu, nhưng hãy cố gắng nhớ rằng, mọi người đều ở đây vì cậu.",
  "Well that one's got extra padding.": "Chà, con đó có thêm lớp đệm (padding) rồi.",
  "If you was so embarrassed about your condition, maybe you shouldn't have been fraternizing with women of low moral character.": "Nếu anh cảm thấy quá xấu hổ về tình trạng của mình, thì lẽ ra anh đéo nên đi dan díu với những người phụ nữ có tư cách đạo đức thấp hèn.",
  "Okay, I'll be here a little longer.": "Được rồi, tôi sẽ ở lại đây thêm một chút nữa.",
  "That's a whole lotta nothin'.": "Đó là một đống đồ vô dụng.",
  "Plates": "Những Cái Đĩa (Plates)",
  "So stop standing there staring at me and put one through my head, huh?": "Vậy nên hãy ngừng đứng đó nhìn chằm chằm vào tôi và tặng cho tôi một viên đạn xuyên qua đầu đi, hả?",
  "Former car thief on parole, trying to go straight.": "Cựu trộm xe đang được hưởng án treo, đang cố gắng hoàn lương.",
  "SET UP: Warehouse Machine Shop": "THIẾT LẬP: Xưởng Cơ Khí Của Kho Hàng (Warehouse Machine Shop)",
  "This firearm won't take a suppressor.": "Khẩu súng này đéo thể lắp được nòng giảm thanh.",
  "Roll": "Lăn qua (Roll)",
  "They'd like to join us.": "Họ muốn gia nhập với chúng ta.",
  "Moreno": "Moreno",
  "Hmm. Probably not.": "Hmm. Có lẽ là đéo.",
  "Refills some brass to generate several magazines' worth of 5.56mm ammunition.": "Nạp lại một ít vỏ đạn (brass) để tạo ra vài băng đạn 5.56mm.",
  "Ah, dammit!": "Ah, chết tiệt!",
  "I keep hearing it, every few minutes.": "Tôi cứ nghe thấy nó, vài phút một lần.",
  "Andy Pimms": "Andy Pimms",
  "Heavy, reliable, durable.": "Nặng, đáng tin cậy, bền bỉ.",
  "Someone has to do the thankless job of mucking out the latrine. Otherwise, we all risk getting seriously ill.": "Ai đó phải làm cái công việc vô ơn là dọn dẹp nhà xí thôi. Đéo thì tất cả chúng ta đều có nguy cơ bị ốm nặng.",
  "She seemed pretty proud of herself afterward, like she'd just committed the crime of the century.": "Cô ta có vẻ khá tự hào về bản thân sau đó, cứ như thể cô ta vừa thực hiện được một vụ tội phạm thế kỷ vậy.",
  "You're human after all.": "Dù sao thì cậu cũng là con người mà.",
  "I'm interested.": "Tôi có hứng thú đấy.",
  "<Burp!>": "<Ợ!>",
  "Not sure how much longer I can hang on!": "Đéo chắc tôi có thể trụ được bao lâu nữa đâu!",
  "Hunt down a Juggernaut zombie.": "Săn lùng một con zombie Juggernaut.",
  "Alison": "Alison",
  "Hello? Can you hear me?": "Xin chào? Cậu có nghe thấy tôi đéo?",
  "Those heads were poppin' like melons!": "Những cái đầu đó nổ tung như dưa hấu vậy!",
  "This is the place.": "Chính là nơi này.",
  "The outbreak condition in Dallas has worsened to CRITICAL.\r\n All flights from DFW are suspended until further notice.": "Tình trạng bùng phát dịch bệnh ở Dallas đã trở nên TỒI TỆ (CRITICAL).\r\n Tất cả các chuyến bay từ DFW đều bị đình chỉ cho đến khi có thông báo mới.",
  "Created some shotgun ammunition.": "Đã chế tạo một ít đạn súng shotgun.",
  "Fuckin' screamers. Ain't so tough without their little zombie buddies around, am I right?": "Lũ screamers khốn kiếp. Chẳng còn mạnh mẽ gì mấy nếu đéo có những người bạn zombie nhỏ bé xung quanh, tôi nói đúng đéo?",
  "Makes the surrounding area a lot more dangerous.": "Làm cho khu vực xung quanh trở nên nguy hiểm hơn rất nhiều.",
  "You give people hope. I admire that.": "Cậu mang lại hy vọng cho mọi người. Tôi ngưỡng mộ điều đó.",
  "You let me worry about that.": "Cứ để tôi lo chuyện đó.",
  "So, do you always do shit that's that dangerous, or was this just a special occasion for you?": "Vậy, cậu lúc nào cũng làm những chuyện nguy hiểm đến chết người như thế này, hay đây chỉ là một dịp đặc biệt đối với cậu?",
  "REFUSE REFUGEE. Leave them to their fate.": "TỪ CHỐI NGƯỜI TỊ NẠN. Mặc kệ số phận của họ.",
  "I'm gettin' fucked up over here!": "Tôi đang bị dần cho nhừ tử ở bên này!",
  "Hey, I just realized that now I'll probably NEVER get to visit Jurassic Junction.": "Này, tôi chợt nhận ra rằng bây giờ tôi có lẽ sẽ ĐÉO BAO GIỜ được đến thăm Giao lộ Kỷ Jura (Jurassic Junction) nữa.",
  "Ran over 250 zombies.": "Cán qua 250 con zombies.",
  "Let's start looking, then. What, you didn't think I was just going to let you go out there alone, did you?": "Vậy thì hãy bắt đầu tìm kiếm thôi. Sao nào, cậu đéo nghĩ là tôi sẽ để cậu ra ngoài đó một mình đấy chứ, hả?",
  "Well, it still sits ugly with me.": "Chà, chuyện đó vẫn khiến tôi thấy chướng tai gai mắt."
};

const file = 'output/languages/chunks/btxt_chunk_163.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_163.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk163[r.sourceText]) {
    r.translatedText = chunk163[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 163 successfully!');
