const fs = require('fs');
const chunk109 = {
  "I thought maybe you were going to turn this thing around. Start making a positive difference for the people of Danforth.": "Tôi đã nghĩ có lẽ cậu sẽ xoay chuyển tình thế này. Bắt đầu tạo ra một sự thay đổi tích cực cho người dân Danforth.",
  "Why don't you tell us your situation?": "Sao anh không cho chúng tôi biết tình hình của anh?",
  "Gabe": "Gabe",
  "Baling Wire": "Dây Thép Buộc (Baling Wire)",
  "Oh shit. Oh shit oh SHIT!": "Ôi chết tiệt. Ôi chết tiệt, CHẾT TIỆT!",
  "Failure": "Thất bại",
  "Yeah, they're coming! Looks like we got a few minutes, though.": "Đúng, chúng đang đến! Nhưng có vẻ như chúng ta còn vài phút nữa.",
  "Resolution 1280x720": "Độ phân giải 1280x720",
  "PERSONAL SKILL. Man, that new solid-state drive I had on order is never gonna get here now....": "KỸ NĂNG CÁ NHÂN. Trời ạ, cái ổ cứng SSD mới mà tôi đã đặt hàng bây giờ sẽ không bao giờ được giao tới nữa....",
  "SMG: MP5K": "Tiểu liên (SMG): MP5K",
  "It's done.": "Xong rồi.",
  "Honorably discharged for a bum knee.": "Giải ngũ danh dự vì chấn thương đầu gối.",
  "Watch your left!": "Cẩn thận bên trái!",
  "How about somebody out there get off your lazy ass and lend a hand?": "Sao không có ai ngoài đó nhấc cái mông lười biếng lên và giúp một tay nhỉ?",
  "Duly noted.": "Đã ghi nhận.",
  "A lot of people used to say he was crooked, but nobody ever proved anything.": "Nhiều người từng nói ông ta là kẻ lươn lẹo, nhưng chưa ai chứng minh được điều gì.",
  "Enzo": "Enzo",
  "Oh... was I not supposed to eat all that? Sorry, nobody showed me the ration schedule. - %1$s": "Ồ... tôi không được phép ăn hết chỗ đó sao? Xin lỗi, không ai cho tôi xem lịch phân phối khẩu phần ăn cả. - %1$s",
  "Oh yeah, prepare to be impressed.": "Ồ yeah, chuẩn bị để được ấn tượng đi.",
  "At least the bullet didn't hit any vital organs. That accident could have been a lot worse.": "Ít nhất viên đạn đã không trúng bất kỳ cơ quan nội tạng quan trọng nào. Tai nạn đó đã có thể tồi tệ hơn rất nhiều.",
  "Numbs the pain, but won't help serious wounds. Typical over-the-counter stuff. Come on, everybody knows what aspirin is.": "Làm tê liệt cơn đau, nhưng không giúp ích gì cho các vết thương nghiêm trọng. Một loại thuốc không kê đơn điển hình. Thôi nào, ai mà chẳng biết aspirin là gì.",
  "Green": "Màu Xanh Lá",
  "You can meet with them and see if it's worth our while.": "Cậu có thể gặp họ và xem liệu nó có bõ công chúng ta không.",
  "Don't worry, I'll be back out there as soon as I can. Sucking chest wounds aren't gonna keep me down.": "Đừng lo, tôi sẽ trở lại ngoài đó ngay khi có thể. Một vết thương hở ở ngực không thể hạ gục được tôi đâu.",
  "Callsign Sasquatch. High speed, low drag. Loves freak hunts.": "Biệt danh Sasquatch. Tốc độ cao, lực cản thấp. Rất thích đi săn quái vật.",
  "We're gonna need more construction materials soon, or this place is gonna start falling down around our ears.": "Chúng ta sẽ sớm cần thêm vật liệu xây dựng, nếu không nơi này sẽ bắt đầu sụp đổ ngay trên đầu chúng ta mất.",
  "The zeds told me they didn't need this.": "Lũ zed bảo tôi rằng chúng không cần cái này.",
  "ARMY GUNNERS. Gives you an artillery marker. Toss the item to call in an artillery strike.": "PHÁO BINH QUÂN ĐỘI. Cung cấp cho bạn một pháo sáng đánh dấu tọa độ pháo binh. Ném vật phẩm này để gọi một cuộc pháo kích.",
  "+175%": "+175%",
  "Woah shit shit shit shit shit!": "Á đù, chết tiệt chết tiệt chết tiệt!",
  "The way I see it, this whole thing is just another bad time, and I just know my daddy and granddaddy are looking down at me right now, saying \"Raymundo, you've got to do the right thing.\"": "Theo cách tôi thấy, toàn bộ chuyện này chỉ là một khoảng thời gian tồi tệ khác, và tôi biết cha và ông nội đang nhìn xuống tôi ngay lúc này, và nói rằng \"Raymundo, con phải làm điều đúng đắn.\"",
  "FRIENDLY SURVIVORS": "NHỮNG NGƯỜI SỐNG SÓT THÂN THIỆN",
  "If you think this thing \"just happened,\" you're fooling yourself. Someone knows what caused this, someone is BEHIND this. Don't believe me? Then riddle me this: why did the Army start ferrying people in two days BEFORE the first confirmed attacks?": "Nếu cậu nghĩ chuyện này \"chỉ tình cờ xảy ra\", thì cậu đang tự lừa dối mình đấy. Ai đó biết nguyên nhân gây ra chuyện này, ai đó đứng ĐẰNG SAU chuyện này. Không tin tôi ư? Vậy thì giải thích cho tôi điều này: tại sao Quân đội lại bắt đầu sơ tán người dân trước hai ngày KHI các cuộc tấn công đầu tiên được xác nhận?",
  "DECLINE MISSION. Lily may still have a little something to say to you.": "TỪ CHỐI NHIỆM VỤ. Lily có thể vẫn còn vài điều muốn nói với bạn.",
  "What's wrong, you get bored toward the end?": "Sao vậy, về cuối cậu thấy chán rồi à?",
  "Uses fuel to provide electricity.": "Sử dụng nhiên liệu (fuel) để cung cấp điện.",
  "Sergeant Eldridge's next target is a Bloater. We're looking for a zombie that's swollen with toxic gas ... and we have to take it down with a headshot.": "Mục tiêu tiếp theo của Trung sĩ Eldridge là một con Bloater. Chúng ta đang tìm kiếm một con zombie sưng phù chứa đầy khí độc... và chúng ta phải hạ gục nó bằng một phát bắn tỉa (headshot).",
  "I'm just going to pretend I didn't see you violating curfew.": "Tôi sẽ giả vờ như không thấy cậu vi phạm lệnh giới nghiêm.",
  "Doc Hanson ran into trouble. I wasn't able to help. - %1$s": "Bác sĩ Hanson gặp rắc rối. Tôi không thể giúp được gì. - %1$s",
  "Good thing I'm almost home, this is getting heavy.": "May mà tôi sắp về đến nhà, thứ này bắt đầu nặng rồi đấy.",
  "Aiden": "Aiden",
  "%1$s has lost track of the Feral. We missed a chance to bring down the zombie population and delay the next siege.": "%1$s đã mất dấu con Feral. Chúng ta đã bỏ lỡ cơ hội làm giảm số lượng zombie và trì hoãn đợt vây hãm tiếp theo.",
  "Your map should have the location.": "Bản đồ của bạn hẳn đã hiển thị vị trí.",
  "Yeah, shoulda known that was feelin' too easy.": "Ừ, đáng lẽ phải biết là chuyện này có vẻ quá dễ dàng.",
  "I don't know. Maybe it's some kind of messed up super-virus. Maybe it's radiation from outer space, or black magic or... or the Wrath of almighty frickin' God.": "Tôi không biết. Có thể là một loại siêu virus tồi tệ nào đó. Có thể là bức xạ từ ngoài không gian, hoặc ma thuật đen hay... hay là Cơn thịnh nộ của đấng Toàn Năng chết tiệt.",
  "Medicine": "Thuốc Men",
  "Bite me.": "Cắn tao đi.",
  "Pete": "Pete",
  "We're extracting a lot of scientists. Isn't anyone else trying to escape?": "Chúng ta đang giải cứu rất nhiều nhà khoa học. Không có ai khác đang cố gắng trốn thoát sao?",
  "NM-": "NM-",
  "See you in a sec.": "Hẹn gặp lại trong chốc lát.",
  "I guess R&R is over, huh?": "Tôi đoán thời gian nghỉ ngơi phục hồi (R&R) kết thúc rồi hả?",
  "Winkler": "Winkler",
  "Well, I guess we can stop worrying about philosophical differences about how to run the community. - %1$s": "Chà, tôi đoán chúng ta không cần phải lo lắng về những khác biệt triết lý trong cách điều hành cộng đồng nữa. - %1$s",
  "You're right, it's not. We've built a home here, and you just want to abandon it because things are getting tough!": "Cô nói đúng, không phải vậy. Chúng ta đã xây dựng một mái nhà ở đây, và cô chỉ muốn từ bỏ nó vì mọi chuyện đang trở nên khó khăn ư!",
  "Requires Shooting Level 3": "Yêu Cầu Kỹ Năng Bắn Súng Cấp 3",
  "%d Stealth Kills": "%d Lần Hạ Gục Lén Lút",
  "Maybe that's a good thing, right? Maybe it means this is almost over?": "Có thể đó là một điều tốt, phải không? Có thể nó có nghĩa là chuyện này sắp kết thúc rồi?",
  "Combat Endurance": "Độ Bền Bỉ Trong Chiến Đấu",
  "How about some of that SWAT support?": "Còn sự hỗ trợ từ đội SWAT thì sao?",
  "Yes": "Có",
  "Stay sharp. This isn't over.": "Giữ tỉnh táo nhé. Vẫn chưa xong đâu.",
  "Let's go get some zed-killin' practice.": "Hãy đi luyện tập kỹ năng giết zed chút nào.",
  "Don't worry about looking for %1$s; just got word from their people they made it home safe. - %2$s": "Đừng bận tâm tìm kiếm %1$s nữa; vừa nhận được tin báo từ người của họ rằng họ đã về nhà an toàn. - %2$s",
  "Push them back on the right!": "Đẩy lùi chúng ở bên phải!",
  "I don't care if you think it scares the zombies away, %2$s, next time you start yodeling at two in the morning I'm going to strangle you! - %1$s": "Tôi không quan tâm nếu cậu nghĩ điều đó sẽ làm lũ zombie sợ bỏ chạy, %2$s, lần tới nếu cậu bắt đầu hát yodel vào lúc hai giờ sáng, tôi sẽ bóp cổ cậu đấy! - %1$s",
  "EXPIRED: Sasquatch": "ĐÃ HẾT HẠN: Sasquatch",
  "Looks like we \"lost\" a few things.": "Có vẻ như chúng ta đã \"mất\" một vài thứ.",
  "Spencer's Mill Church": "Nhà Thờ Spencer's Mill",
  "I have new orders for our search teams. Locate stranded army personnel and bring them back to base.": "Tôi có mệnh lệnh mới cho các đội tìm kiếm của chúng ta. Xác định vị trí các quân nhân bị mắc kẹt và đưa họ về căn cứ.",
  "Artillery is operational, sir. We can start lighting up the zeds any time you want.": "Pháo binh đã sẵn sàng hoạt động, thưa ngài. Chúng ta có thể bắt đầu nã pháo vào lũ zed bất cứ lúc nào ngài muốn.",
  "Your car's ready.": "Xe của cậu đã sẵn sàng.",
  "Listeners, I just saw our last caller fly off in a helicopter. These army guys are the real deal.": "Thưa quý thính giả, tôi vừa thấy vị khách gọi đến cuối cùng của chúng ta bay đi bằng trực thăng. Mấy anh lính này là hàng xịn đấy.",
  "Shit, what's the rush? Take your time!": "Chết tiệt, có gì mà phải vội? Cứ từ từ thôi!",
  "Snake": "Snake",
  "SURVIVAL TACTICS: Library": "CHIẾN THUẬT SINH TỒN: Thư Viện",
  "Ali": "Ali",
  "Balaam angels forty, ten mikes.": "Balaam đội hình bốn không, khoảng cách mười mét. (Balaam angels forty, ten mikes.)",
  "Ah, just what we need.": "Chà, đúng thứ chúng ta cần.",
  "Yeah. Yeah, you can count on it.": "Vâng. Vâng, anh có thể tin tưởng vào điều đó.",
  "Comic book nerd who insists on being called \"Lex.\" No one listens.": "Tên mọt truyện tranh cứ khăng khăng đòi được gọi là \"Lex.\" Chẳng ai thèm nghe.",
  "2x4 Nails": "Đinh 2x4",
  "Search for the Juggernaut": "Tìm kiếm con Juggernaut",
  "So...which direction are you leaning?": "Vậy... cô đang nghiêng về hướng nào?",
  "Sounds like a bad situation out there.": "Nghe có vẻ là một tình huống tồi tệ ở ngoài đó.",
  "People don't need to see that!": "Mọi người không cần phải thấy cảnh đó!",
  "How about a little artillery support?": "Một chút hỗ trợ từ pháo binh thì sao?",
  "Refills some brass to generate several magazines' worth of .22-caliber ammunition.": "Tái chế vỏ đạn (brass) để tạo ra vài băng đạn cỡ .22.",
  "Mayday, mayday! Is anyone reading?": "Mayday, mayday! Có ai nghe rõ không?",
  "Black Friday to Highroad. No joy on extracting Timothy Hall, but he found us some samples in his lab.": "Black Friday gọi Highroad. Không thể giải cứu Timothy Hall, nhưng anh ta đã tìm cho chúng ta một số mẫu vật trong phòng thí nghiệm của anh ta.",
  "Having a community member with a medical background improves Recovery Chance.": "Việc có một thành viên cộng đồng có kiến thức nền tảng y tế sẽ cải thiện Cơ hội Phục hồi (Recovery Chance).",
  "Just do exactly what I say. You'll be fine.": "Chỉ cần làm chính xác những gì tôi nói. Cậu sẽ ổn thôi.",
  "Gunfire just pisses 'em off.": "Tiếng súng chỉ làm chúng thêm tức giận thôi.",
  "I don't have a gun.": "Tôi không có súng.",
  "Your community cannot support any more outposts.": "Cộng đồng của bạn không thể hỗ trợ thêm Tiền đồn (Outpost) nào nữa.",
  "Yeah... pretty sure cheese isn't supposed to smell like gym socks. Unless it's French. Which this isn't.": "Ừ... khá chắc là pho mát không có mùi như bít tất tập gym đâu. Trừ khi đó là pho mát Pháp. Mà cái này thì không phải.",
  "I'm coming to you from the army outpost where that old strip mall used to be.": "Tôi đang gọi cho các bạn từ tiền đồn của quân đội, nơi từng là khu trung tâm thương mại cũ.",
  "Words of Encouragement": "Những Lời Động Viên",
  "Friendly... right.": "Thân thiện... phải rồi.",
  "Unfazed by the lack of a microwave.": "Không hề bận tâm đến việc thiếu một cái lò vi sóng."
};

const file = 'output/languages/chunks/btxt_chunk_109.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_109.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk109[r.sourceText]) {
    r.translatedText = chunk109[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 109 successfully!');
