const fs = require('fs');
const chunk150 = {
  "Since you can't seem to dodge, mind if I call dibs on your stuff?": "Vì có vẻ như cậu đéo biết né, nên có phiền đéo nếu tôi xí trước đồ của cậu?",
  "This whole fucking world is dead. Doghouse out.": "Cái thế giới chết tiệt này tàn cmnr. Doghouse chấm dứt.",
  "Order at DZ": "Lệnh tại Khu vực thả dù (DZ)",
  "Zeds are inside!": "Lũ Zed đang ở bên trong!",
  "Oh, thank God.": "Ồ, tạ ơn Chúa.",
  "Willie": "Willie",
  "+20 Sense of Superiority; -50 Trust": "+20 Cảm giác thượng đẳng; -50 Niềm tin",
  "So... Now you know. Who I used to be.": "Vậy là... Giờ thì cậu đã biết. Tôi từng là ai.",
  "5.56mm Ammunition": "Đạn 5.56mm",
  "I dunno. Maybe.": "Tôi đéo biết. Có thể.",
  "A sturdy police baton.": "Một chiếc dùi cui cảnh sát chắc chắn.",
  "Well... until the mold in the walls put me in the hospital for a month.": "Chà... cho đến khi đống nấm mốc trên tường tống tôi vào viện trong suốt một tháng.",
  "I sure could use a pep talk right now.": "Tôi chắc chắn có thể cần một vài lời động viên ngay lúc này đấy.",
  "<Weak coughing>": "<Ho yếu ớt>",
  "Bingo. That's exactly what we need.": "Chuẩn luôn. Đó chính xác là những gì chúng ta cần.",
  "Things look pretty bleak, huh?": "Mọi thứ trông có vẻ khá ảm đạm nhỉ?",
  "Thought that's what I said.": "Tưởng đó là những gì tôi đã nói chứ.",
  "What do you think?": "Cậu nghĩ sao?",
  "Automatically repair body, engine, and tire damage. Replace lost bumpers and doors.": "Tự động sửa chữa các hỏng hóc ở thân xe, động cơ và lốp xe. Thay thế các cản xe và cửa xe bị mất.",
  "You've lost contact with HQ! You no longer have access to radio options or supply drops.": "Bạn đã mất liên lạc với Trụ sở chính (HQ)! Bạn đéo còn quyền truy cập vào các tùy chọn radio hay đồ tiếp tế được thả xuống nữa.",
  "Resolution 800x600": "Độ Phân Giải 800x600",
  "How's things?": "Mọi chuyện sao rồi?",
  "Course, it was on the ground floor and it had floor-to-ceiling windows in the living room, so, y'know... zombie death trap.": "Tất nhiên, nó nằm ở tầng trệt và có cửa sổ sát trần trong phòng khách, nên, cậu biết đấy... một cái bẫy tử thần đầy zombie.",
  "You wanna talk about it?": "Cậu có muốn nói về chuyện đó đéo?",
  "Ebberts": "Ebberts",
  "Guess the zeds can't slow you down.": "Có vẻ lũ zed đéo thể làm chậm bước chân của cậu được.",
  "Shared her story.": "Đã chia sẻ câu chuyện của cô ấy.",
  "(Alicia Hawkes)": "(Alicia Hawkes)",
  "%1$s Needs: %2$s": "%1$s Đang Cần: %2$s",
  "Where's Doc Hanson? We need to get going.": "Bác sĩ Hanson đâu rồi? Chúng ta cần phải đi ngay.",
  "Vitaly": "Vitaly",
  "Fucking dogs.": "Lũ chó đẻ.",
  "Your current character is very tired. Use the Journal [ul_journal_menu] to switch to a different character.": "Nhân vật hiện tại của bạn đang rất mệt mỏi. Sử dụng Nhật ký (Journal) [ul_journal_menu] để chuyển sang một nhân vật khác.",
  "Leave the rest. We gotta go now.": "Bỏ lại những thứ còn lại đi. Chúng ta phải đi ngay bây giờ.",
  "Got that little present ready for you. Come on out and meet me when you've got the time.": "Tôi đã chuẩn bị sẵn món quà nhỏ đó cho cậu rồi. Ra ngoài này gặp tôi khi nào cậu có thời gian nhé.",
  "Yeah! Keep it up.": "Tuyệt! Cứ giữ phong độ đó nhé.",
  "Nice one!": "Làm tốt lắm!",
  "The people at the courthouse... they're all dead.": "Những người ở tòa án... họ chết cả rồi.",
  "How could you do that?": "Sao cậu có thể làm như vậy được chứ?",
  "Hmm... let's hold off on the move for now.": "Hmm... hãy hoãn việc di chuyển lại lúc này đã.",
  "Growing": "Đang Phát Triển",
  "Be advised, we've set up an outpost at the LZ. The call sign is Black Friday. We're on the radio 24-7.": "Xin thông báo, chúng tôi đã thiết lập một tiền đồn tại khu vực hạ cánh (LZ). Tên gọi là Black Friday. Chúng tôi luôn túc trực trên radio 24/7.",
  "Found a stash of medications. -%1$s": "Tìm thấy một kho cất giấu thuốc men. -%1$s",
  "Listen to me! I don't have long, I can feel the change coming on.": "Nghe tôi này! Tôi đéo còn nhiều thời gian đâu, tôi có thể cảm nhận được sự biến đổi đang ập đến rồi.",
  "There's only one way out if you don't have air support. The pass back by the fairground--it links up with the main highway after about ten miles.": "Chỉ có một lối thoát duy nhất nếu cậu đéo có không quân yểm trợ. Con đường đèo vòng qua khu hội chợ--nó nối với đường cao tốc chính sau khoảng mười dặm.",
  "Waypoint": "Điểm Đánh Dấu (Waypoint)",
  "Black Friday, this is Greyhound One.": "Black Friday, đây là Greyhound Một (Greyhound One).",
  "Studied Boxing": "Từng Luyện Tập Quyền Anh (Boxing)",
  "Vienna Cho thinks she can do it.": "Vienna Cho nghĩ cô ấy có thể làm được.",
  "How the hell are we supposed to protect ourselves now? We're almost out of ammo!": "Thế quái nào chúng ta có thể tự bảo vệ mình bây giờ? Chúng ta gần như cạn kiệt đạn dược rồi!",
  "Delivery made.": "Quá trình giao hàng hoàn tất.",
  "Help Sasquatch hunt a Feral": "Giúp Sasquatch săn một con Feral",
  "The zombie population in the city has reached a tipping point. They're spilling out in droves now, and with all the noisy business at the base, we're are really attractive target.": "Dân số zombie trong thành phố đã đạt đến điểm bùng phát rồi. Bây giờ bọn chúng đang tràn ra từng bầy, và với tất cả những hoạt động ồn ào ở căn cứ, chúng ta thực sự là một mục tiêu rất hấp dẫn.",
  "119 HERO Becca Collins": "119 ANH HÙNG (HERO) Becca Collins",
  "Contact contact contact!": "Phát hiện mục tiêu, phát hiện mục tiêu!",
  "Max stamina is full. Stimulants temporarily recover some of your max stamina.": "Mức Thể Lực (Stamina) tối đa đã đầy. Thuốc kích thích sẽ tạm thời phục hồi một phần mức Thể Lực tối đa của bạn.",
  "Clean Suit": "Bộ Đồ Sạch Sẽ",
  "Wonder what that is?": "Đéo biết thứ đó là cái quái gì nhỉ?",
  "The detonator's shot, or else the receiver is. Bottom line, there's no way to blow this thing from a safe distance.": "Ngòi nổ bị hỏng rồi, hoặc nếu đéo thì là do bộ thu tín hiệu. Nói tóm lại, đéo có cách nào để kích nổ thứ này từ một khoảng cách an toàn đâu.",
  "Architect": "Kiến Trúc Sư",
  "TIP: Outposts create a small SAFE AREA and can be visited to RESUPPLY.": "MẸO: Tiền đồn (Outposts) tạo ra một KHU VỰC AN TOÀN (SAFE AREA) nhỏ và có thể được ghé thăm để TIẾP TẾ (RESUPPLY).",
  "92 GENERIC Charlene Norville": "92 CHUNG (GENERIC) Charlene Norville",
  "Take it easy.": "Bình tĩnh nào.",
  "Howdy.": "Chào đằng ấy.",
  "Hope he'll survive another day.": "Hy vọng anh ấy sẽ sống sót thêm được một ngày nữa.",
  "SitRep: North Korea": "Báo Cáo Tình Hình (SitRep): Triều Tiên",
  "Emote 2": "Biểu Cảm 2",
  "Investigate the source of the gunshots.": "Điều tra nguồn gốc của những tiếng súng.",
  "Gilbert": "Gilbert",
  "All the benefits of an Infirmary, plus the ability to create Stimulants. REQUIRES LIBRARY.": "Tất cả các lợi ích của Bệnh xá (Infirmary), cộng thêm khả năng chế tạo Thuốc Kích Thích (Stimulants). YÊU CẦU THƯ VIỆN (LIBRARY).",
  "Find Missing Survivors": "Tìm Những Người Sống Sót Bị Mất Tích",
  "Job says he doesn't know anything about raids. Yeah, right. - %1$s": "Job nói rằng hắn ta đéo biết bất cứ thứ gì về các cuộc đột kích. Phải rồi, cứ cho là vậy đi. - %1$s",
  "He was dropping out of school, you see. His father and I tried to talk some sense into him.": "Thằng bé định bỏ học, cậu hiểu chứ. Bố nó và tôi đã cố gắng nói lý lẽ để nó nhận ra vấn đề.",
  "Ethan": "Ethan",
  "Doctor, I need a bit of medical advice.": "Bác sĩ, tôi cần một chút lời khuyên về mặt y tế.",
  "So let me tell you, I am super glad to know that you're still alive.": "Vậy để tôi nói cho cậu nghe, tôi cực kỳ mừng khi biết rằng cậu vẫn còn sống đấy.",
  "Matthew says \"stop whining about how tired you are, sack up, and do the job.\" That about cover it?": "Matthew nói rằng \"bớt rên rỉ về việc cậu mệt mỏi thế nào đi, nhấc mông lên, và hoàn thành công việc đi.\" Thế đã đủ bao quát vấn đề chưa?",
  "Thinks he's hard.": "Nghĩ mình là thằng cứng cựa.",
  "You bet.": "Cậu đoán đúng rồi đấy.",
  "Game Breaker": "Kẻ Phá Đảo (Game Breaker)",
  "Okay. Let's go find 'em.": "Được rồi. Hãy đi tìm bọn họ thôi.",
  "Ron": "Ron",
  "We ought to make a supply run.": "Chúng ta nên thực hiện một chuyến nhặt mót.",
  "Taking things from the supply locker costs Influence.": "Lấy đồ vật từ tủ đồ tiếp tế (supply locker) sẽ tiêu tốn Ảnh Hưởng (Influence).",
  "Guns": "Súng Ống (Guns)",
  "Okay, people, we seriously need to figure out how we're going to improve our defenses.": "Được rồi, mọi người, chúng ta thực sự cần phải tìm ra cách để cải thiện khả năng phòng thủ của mình.",
  "That's gonna bring trouble.": "Thứ đó sẽ mang lại rắc rối đây.",
  "That's enough, Sergeant. We're moving on.": "Đủ rồi đấy, Trung sĩ. Chúng ta phải đi tiếp thôi.",
  "I called Doctor Horn, but even he couldn't make any sense of it. I sent him home with some samples to test.": "Tôi đã gọi cho Bác sĩ Horn, nhưng ngay cả ông ấy cũng đéo hiểu nổi chuyện này. Tôi đã cử ông ấy về nhà cùng với vài mẫu vật để xét nghiệm.",
  "Just keeping a rational perspective. Can't afford to get attached to nobody.": "Chỉ là giữ một góc nhìn lý trí thôi. Đéo thể cho phép bản thân gắn bó với bất kỳ ai cả.",
  "If you want quicker Reflexes, you've got to take the fight up close and personal.": "Nếu cậu muốn có Phản xạ (Reflexes) nhanh nhạy hơn, cậu phải tham gia vào những trận chiến giáp lá cà sát sườn thôi.",
  "Sup, Bro! Beer Pong, anyone?": "Chào ông anh! Chơi ném bóng bàn vào cốc bia (Beer Pong) đéo?",
  "Get to the Mt. Tanner Ranger Station.": "Đi đến Trạm Kiểm Lâm (Ranger Station) ở Núi Tanner.",
  "Better make a note of it. We'll have to clear it out before it spreads.": "Tốt hơn là nên ghi chú lại. Chúng ta sẽ phải dọn dẹp sạch sẽ nơi này trước khi nó lây lan ra ngoài.",
  "Hey, hey, you want a horde all up in your shit?": "Này, này, cậu có muốn một bầy horde xông vào xé xác cậu đéo?",
  "SWAT Team Inbound": "Đội Đặc Nhiệm SWAT Đang Kéo Đến",
  "Shhh, that's a Screamer.": "Suỵt, đó là một con Screamer.",
  "I didn't invite those people.": "Tôi đéo hề mời những người đó đến.",
  "Gonna be a good day to kill zeds.": "Sẽ là một ngày tuyệt vời để tàn sát lũ zed đây.",
  "Don't give up yet!": "Đừng bỏ cuộc vội!"
};

const file = 'output/languages/chunks/btxt_chunk_150.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_150.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk150[r.sourceText]) {
    r.translatedText = chunk150[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 150 successfully!');
