const fs = require('fs');

const map = {
  // Chunk 7
  "Rifle: 700 Huntsman": "Súng Trường (Rifle): 700 Huntsman",
  "A classic scoped hunting rifle.": "Súng trường săn bắn kinh điển có gắn ống ngắm.",
  "Rifle: Sidekick": "Súng Trường (Rifle): Sidekick",
  "Has that classic cowboy flavor.": "Đậm đà hương vị cao bồi miền viễn Tây.",
  "Rifle: 10/22": "Súng Trường (Rifle): 10/22",
  "One of the most popular .22 cal. rifles.": "Một trong những khẩu súng trường .22 cal phổ biến nhất.",
  "Rifle: 700 Huntsman Camo": "Súng Trường (Rifle): 700 Huntsman Camo",
  "Composite stock and iron sights.": "Báng súng bằng composite và đầu ngắm cơ khí điểm ruồi.",
  "Rifle: 597 Varmint": "Súng Trường (Rifle): 597 Varmint",
  "Small game scope included at no charge!": "Được tặng kèm ống ngắm săn thú nhỏ mà chẳng tốn xu nào!",
  "Rifle: 750 Forester": "Súng Trường (Rifle): 750 Forester",
  "When hunting big game, bring enough rifle.": "Đã đi săn thú lớn thì phải vác theo khẩu súng cho ra hồn.",
  "Rifle: 983 Squirrel": "Súng Trường (Rifle): 983 Squirrel",
  "Durable with reliable bolt action.": "Cơ chế lên đạn phát một cực kỳ bền bỉ và đáng tin cậy.",
  "Rifle: Bolt Scout": "Súng Trường (Rifle): Bolt Scout",
  "Rugged exterior, measured precision.": "Ngoại hình xù xì, nhưng bắn thì chuẩn không cần chỉnh.",
  "Rifle: Dog Leg": "Súng Trường (Rifle): Dog Leg",
  "A favorite in north-central Florida. ": "Món đồ yêu thích ở khu vực trung-bắc Florida.",
  "Rifle: M1 Garand": "Súng Trường (Rifle): M1 Garand",
  "Stood the test of a world war, highly collectible.": "Đã vượt qua phép thử của Chiến tranh Thế giới, giá trị sưu tầm cực cao.",
  "Rifle: M107 CQ": "Súng Trường (Rifle): M107 CQ",
  "Fires the .50 BMG. For anti-materiel missions.": "Bắn đạn .50 BMG. Được dùng cho các nhiệm vụ công phá khí tài.",
  "Rifle: Mini 14": "Súng Trường (Rifle): Mini 14",
  "1980's TV made this very recognizable.": "Lên TV suốt từ thập niên 1980 nên ai cũng nhận ra mặt.",
  "Rifle: SOCOM II ETR": "Súng Trường (Rifle): SOCOM II ETR",
  "One version of the ever-evolving M14.": "Một phiên bản cải tiến liên tục của dòng M14.",
  "Rifle: Model 70": "Súng Trường (Rifle): Model 70",
  "Pre-1964 models are very valuable. Scoped.": "Mấy đời trước 1964 là vô giá. Có gắn ống ngắm.",
  "Rifle: Ranch King": "Súng Trường (Rifle): Ranch King",
  "A classic western rifle. (replica)": "Súng trường kinh điển của miền Viễn Tây. (Bản sao chép)",
  "Rifle: SKS": "Súng Trường (Rifle): SKS",
  "The AK 47's older sister. Bayonet removed.": "Bà chị già của AK 47. Đã tháo lưỡi lê.",
  "Rifle: Mk. 15": "Súng Trường (Rifle): Mk. 15",
  "Long range service provider. Scoped.": "Chuyên gia giao hàng tận nơi tầm xa. Có gắn ống ngắm.",
  "Rifle: Monag 90/31": "Súng Trường (Rifle): Monag 90/31",
  "Produced in the millions from 1891 to 1965.": "Được sản xuất hàng triệu khẩu từ năm 1891 đến 1965.",
  "Shotgun: Hooker": "Súng Shotgun: Hooker",
  "Short pump, not legal. Don't try this at home.": "Súng cưa nòng, phạm pháp đấy. Đừng có thử cái này ở nhà.",
  "Shotgun: Warrior Police": "Súng Shotgun: Warrior Police",
  "Standard police shotgun in Trumbull County.": "Súng shotgun tiêu chuẩn của cảnh sát Hạt Trumbull.",
  "Shotgun: Model 870 X": "Súng Shotgun: Model 870 X",
  "The best selling shotgun in history.": "Khẩu Shotgun bán chạy nhất trong lịch sử.",
  "Shotgun: Model 1100": "Súng Shotgun: Model 1100",
  "Popular autoloader. Loved by shooting enthusiasts.": "Dòng súng tự nạp đạn phổ thông. Rất được những người đam mê súng săn yêu thích.",
  "Shotgun: Model 1100 Malone": "Súng Shotgun: Model 1100 Malone",
  "Cut down version of the 1100.": "Phiên bản cưa ngắn của khẩu 1100.",
  "Shotgun: Model 1100 Tactical": "Súng Shotgun: Model 1100 Tactical",
  "Model 1100 for police and military use.": "Bản 1100 dành riêng cho cảnh sát và quân đội.",
  "Shotgun: 1300 Hunter": "Súng Shotgun: 1300 Hunter",
  "Standard pump action hunting Shotgun.": "Súng shotgun bơm đạn tiêu chuẩn dùng để đi săn.",
  "Shotgun: 1300 Defender": "Súng Shotgun: 1300 Defender",
  "A pump shotgun says \"Private Property\".": "Khẩu súng lên đạn kiểu bơm, dùng để cảnh cáo \"Khu vực Tư nhân\".",
  "Shotgun: 1300 Hunter SP": "Súng Shotgun: 1300 Hunter SP",
  "Camouflaged pump hunting shotgun.": "Súng shotgun đi săn được sơn rằn ri.",
  "Shotgun: A-Series Mod. 1 ": "Súng Shotgun: A-Series Mod. 1",
  "Evolutionary step in pump action shotguns.": "Một bước tiến hóa mới của dòng shotgun bơm đạn.",
  "Shotgun: M1014": "Súng Shotgun: M1014",
  "A reliable military shotgun.": "Súng shotgun chuẩn quân sự siêu ổn định.",
  "Shotgun: Model 870 T": "Súng Shotgun: Model 870 T",
  "Tactical version of the 870.": "Bản chiến thuật của dòng 870.",
  "Shotgun: Warrior": "Súng Shotgun: Warrior",
  "Upgraded police shotgun.": "Shotgun bản nâng cấp của cảnh sát.",
  "Shotgun: Russian 12K": "Súng Shotgun: Russian 12K",
  "An AK 47 and a shotgun had a baby.": "Cứ như AK 47 và súng shotgun vừa đẻ ra đứa con lai vậy.",
  "Shotgun: A12": "Súng Shotgun: A12",
  "Civilian version. Popular in video games.": "Phiên bản dân sự. Cực kỳ quen mặt trong các trò chơi điện tử.",
  "Shotgun: Warden": "Súng Shotgun: Warden",
  "Low profile, slim but brutal.": "Mỏng nhẹ, thầm lặng mà tàn bạo dã man.",
  "LMG: M249 SAW": "Súng Máy (LMG): M249 SAW",
  "A workhorse for 20 years. Close to retirement.": "Cày cuốc suốt 20 năm ròng rã. Sắp tới tuổi về hưu rồi.",
  "Machine Gun": "Súng Máy (Machine Gun)",
  "LMG: M27 IAR": "Súng Máy (LMG): M27 IAR",
  "The new kid on the block.": "Tay mơ mới nổi trên giang hồ.",
  "LMG: M60E4": "Súng Máy (LMG): M60E4",
  "A lighter variant of the venerable heavy hitter.": "Một biến thể nhẹ hơn của tay đấm hạng nặng khét tiếng.",
  "Grenade Launcher: GL 06 Riot": "Súng Phóng Lựu: GL 06 Riot",
  "Crowd dispersal in a 40mm package.": "Giải tán đám đông nằm gọn trong cái nòng 40mm.",
  "Grenade Launcher": "Súng Phóng Lựu",
  "Grenade Launcher: GL M32": "Súng Phóng Lựu: GL M32",
  "Essentially a 40mm revolver.": "Hiểu đơn giản là một khẩu súng rulo phiên bản 40mm.",
  "Assault Rifle: Mk. 17 Mod. 0": "Súng Trường Tấn Công: Mk. 17 Mod. 0",
  "A battle rifle for the next generation, using the 7.62mm round.": "Súng trường chiến đấu của thế hệ tương lai, sử dụng đạn 7.62mm.",
  "Assault Rifle: FAL": "Súng Trường Tấn Công: FAL",
  "Nicknamed \"The right arm of the Free World\".": "Được mệnh danh là \"Cánh tay phải của Thế giới Tự do\".",
  "Assault Rifle: L85A1": "Súng Trường Tấn Công: L85A1",
  "British Armed Forces' standard issue since 1987.": "Vũ khí tiêu chuẩn của Lực lượng Vũ trang Anh kể từ năm 1987.",
  "Assault Rifle: RFB": "Súng Trường Tấn Công: RFB",
  "An aggressive bullpup carbine, perfect for CQB.": "Dòng súng carbine thiết kế bullpup cực kỳ hung hãn, sinh ra để cận chiến (CQB).",
  "Assault Rifle: G36": "Súng Trường Tấn Công: G36",
  "Modular and versatile, this rifle enjoys worldwide popularity.": "Dễ tháo lắp và đa năng, khẩu súng trường này vô cùng thịnh hành trên toàn thế giới.",
  "Pistol: PP 22": "Súng Lục (Pistol): PP 22",
  "Small-caliber version of the famous spy's gun.": "Phiên bản cỡ nòng nhỏ của khẩu súng điệp viên trứ danh.",
  "Pistol: 84 Wildcat": "Súng Lục (Pistol): 84 Wildcat",
  "This .380 ACP firearm has been modified for 9mm.": "Khẩu súng đạn .380 ACP này đã được cải tiến để bắn đạn 9mm.",
  "Pistol: Fifty-Seven": "Súng Lục (Pistol): Fifty-Seven",
  "A 5.7mm conversion to .22 caliber. Still very lethal to zombies.": "Chuyển đổi từ nòng 5.7mm sang đạn .22 caliber. Vẫn cực kỳ nguy hiểm với đám xác sống.",
  "Pistol: Hi-Power": "Súng Lục (Pistol): Hi-Power",
  "Always a favorite in the 9mm class.": "Luôn là sự lựa chọn số một trong dòng súng 9mm.",
  "Pistol: G 31": "Súng Lục (Pistol): G 31",
  "Full frame, using the .357 Sig round.": "Thiết kế Full frame, sử dụng đạn .357 Sig.",

  // Chunk 8
  "Pistol: G 32": "Súng Lục (Pistol): G 32",
  "Compact, scoped \"G\" line that fires the .357 Sig round.": "Dòng \"G\" nhỏ gọn, có gắn ống ngắm và sử dụng đạn .357 Sig.",
  "Pistol: G 33": "Súng Lục (Pistol): G 33",
  "Sub-compact using .357 Sig caliber.": "Bản thu nhỏ (Sub-compact) xài đạn .357 Sig.",
  "Pistol: P 226 Sg": "Súng Lục (Pistol): P 226 Sg",
  "Special edition P226 with custom finish, uses  the .357 Sig round.": "Bản đặc biệt P226 được gia công cực mượt, bắn đạn .357 Sig.",
  "Pistol: Automag": "Súng Lục (Pistol): Automag",
  "A commercial failure made famous in the movies.": "Một thất bại về mặt thương mại nhưng lại vụt sáng trong phim ảnh.",
  "Pistol: P229-40": "Súng Lục (Pistol): P229-40",
  "P229 beavertail in .40 cal.": "P229 với phần đuôi beavertail, dùng đạn .40 cal.",
  "Pistol: Mi.Le .45": "Súng Lục (Pistol): Mi.Le .45",
  "Now in minty fresh .45 caliber! Thumb safety included!": "Giờ đây đã có mặt với phiên bản .45 caliber mát mẻ! Tích hợp chốt an toàn ở ngón cái!",
  "LMG: RPK": "Súng Máy (LMG): RPK",
  "Russian light support weapon, based on the AK chassis.": "Vũ khí yểm trợ hạng nhẹ của Nga, phát triển dựa trên bộ khung súng AK.",
  "LMG: M1918A2": "Súng Máy (LMG): M1918A2",
  "Light support weapon with serious combat history. ": "Súng yểm trợ hạng nhẹ gắn liền với một bề dày lịch sử chiến tranh đẫm máu.",
  "Revolver: SP 101": "Súng Rulo (Revolver): SP 101",
  "A very popular modern small frame .357 revolver.": "Một khẩu rulo đạn .357 khung nhỏ kiểu dáng hiện đại cực kỳ thịnh hành.",
  "Revolver: Anvil Hammer": "Súng Rulo (Revolver): Anvil Hammer",
  "Long barrel custom revolver using the .500 S&W round.": "Khẩu rulo nòng dài độ chế xài đạn .500 S&W.",
  "Revolver: Mark VI": "Súng Rulo (Revolver): Mark VI",
  "Historic Commonwealth sevice revolver, inscribed \"Lt. Pears\".": "Khẩu súng rulo lịch sử của Khối Thịnh vượng chung, có khắc chữ \"Lt. Pears\".",
  "Rifle: Eli": "Súng Trường (Rifle): Eli",
  "A custom M107 created to avenge Eli Wilkerson.": "Khẩu M107 được độ lại để trả thù cho Eli Wilkerson.",
  "Rifle: .45 Justice": "Súng Trường (Rifle): .45 Justice",
  "A scoped revolver-rifle hybrid in .45 caliber.": "Một biến thể lai giữa súng trường và rulo, có gắn ống ngắm, xài đạn .45 cal.",
  "Rifle: RC 40": "Súng Trường (Rifle): RC 40",
  "Made for Police to use the same .40 cal round as a sidearm.": "Được chế tạo để cảnh sát dùng chung đạn .40 cal với súng lục phụ.",
  "Rifle: L41A1": "Súng Trường (Rifle): L41A1",
  "\\\"cadet\\\" training version of the L85 rifles.": "Phiên bản súng L85 huấn luyện \"tân binh\" xài đạn .22 caliber.",
  "Rifle: Lenfield No.4 MkI": "Súng Trường (Rifle): Lenfield No.4 MkI",
  "A British Army mainstay for most of the last century.": "Xương sống của Lục quân Anh trong gần suốt thế kỷ trước.",
  "Rifle: 464 Brushgun": "Súng Trường (Rifle): 464 Brushgun",
  "Very rugged, reliable lever action chambered in .357 caliber.": "Khẩu súng trường nạp đạn bằng đòn bẩy thô ráp, siêu bền, xài đạn .357 caliber.",
  "Shotgun: TS 15": "Súng Shotgun: TS 15",
  "Turkish competitor to the Mod SG.": "Đối thủ Thổ Nhĩ Kỳ của dòng Mod SG.",
  "Shotgun: 590 SP": "Súng Shotgun: 590 SP",
  "Rugged, special-purpose shotgun with a heat shield.": "Súng shotgun đặc nhiệm siêu ngầu được bọc lớp chống nhiệt.",
  "Shotgun: Coachgun": "Súng Shotgun: Coachgun",
  "Modern replica of a western double barrel shotgun.": "Bản sao hiện đại của súng shotgun nòng đôi miền Viễn Tây.",
  "Shotgun: Doubleshort": "Súng Shotgun: Doubleshort",
  "Severely shortened double barrel shotgun. Illegal everywhere.": "Shotgun nòng đôi cưa cụt ngủn. Mang ra đường là vô tù ngay.",
  "Shotgun: A12 Custom": "Súng Shotgun: A12 Custom",
  "Heavily customized, drum fed, nicknamed \"Bonesaw\".": "Độ chế cực gắt, xài băng đạn tròn, có biệt danh là \"Cưa Xương\".",
  "Shotgun: 1897": "Súng Shotgun: 1897",
  "The \"Trench Gun\" or M97. Still fires, but showing some wear.": "\"Súng Chiến Hào\" hay M97. Vẫn nã đạn tốt dù ngoại hình có hơi tàn phai.",
  "SMG: UMP Pro": "Súng Tiểu Liên (SMG): UMP Pro",
  "Pimp my UMP! Camo paint, front post and an optic added.": "Con UMP độ kiểng! Phủ sơn rằn ri, thêm báng trước và cả ống ngắm.",
  "SMG: M3": "Súng Tiểu Liên (SMG): M3",
  "Inexpensive, full auto only WWII SMG. ": "Tiểu liên Thế chiến II chỉ có chế độ bắn tự động, được cái rẻ rề.",
  "SMG: MPX": "Súng Tiểu Liên (SMG): MPX",
  "Civilian legal carbine in .357 (Sig) caliber.": "Súng carbine dân sự hợp pháp sử dụng đạn .357 (Sig).",
  "Assault Rifle: 556S": "Súng Trường Tấn Công: 556S",
  "Very reliable with RDSS sight system.": "Cực kỳ đáng tin cậy với hệ thống kính ngắm RDSS.",
  "Assault Rifle: 556S SWAT": "Súng Trường Tấn Công: 556S SWAT",
  "Tactical police rifle made in Switzerland.": "Súng trường chiến thuật của cảnh sát sản xuất tại Thụy Sĩ.",
  "Assault Rifle: AK 74": "Súng Trường Tấn Công: AK 74",
  "Russian reliability that chambers NATO rounds.": "Sự bền bỉ của người Nga khi sử dụng đạn chuẩn NATO.",
  "Assault Rifle: G3": "Súng Trường Tấn Công: G3",
  "A popular battle rifle worldwide for over 50 years. ": "Súng trường chiến đấu đình đám toàn thế giới hơn 50 năm nay.",
  "Assault Rifle: G36C": "Súng Trường Tấn Công: G36C",
  "The \"C\" stands for \"Compact\", the shorter brother to the G36.": "Chữ \"C\" nghĩa là \"Compact\" (Thu Gọn), đứa em trai nòng ngắn của khẩu G36.",
  "Assault Rifle: Gal SAR": "Súng Trường Tấn Công: Gal SAR",
  "Based on the AK design, this is a battle tested and reliable weapon.": "Được làm dựa trên thiết kế của AK, đây là một thứ vũ khí đáng tin cậy và đã rèn dũa qua biết bao trận mạc.",
  "Assault Rifle: 552 Commando": "Súng Trường Tấn Công: 552 Commando",
  "Very short rifle, good for indoors but can be hard to tame.": "Súng trường cực ngắn, thích hợp dọn dẹp trong nhà nhưng súng khá giật nên khó thuần phục.",
  "Assault Rifle: 552 CS": "Súng Trường Tấn Công: 552 CS",
  "The CS has a longer barrel for stability and scope.": "Bản CS có nòng súng dài hơn để dễ điều khiển và có gắn ống ngắm.",
  "Assault Rifle: Tar 21 Overwatch": "Súng Trường Tấn Công: Tar 21 Overwatch",
  "A new bullpup battle rifle, fitted with an optic for high visibility at range.": "Một khẩu súng trường bullpup tân tiến, trang bị ống ngắm giúp tăng cường tầm nhìn.",
  "Assault Rifle: Tar 21": "Súng Trường Tấn Công: Tar 21",
  "New bullpup from Israel. Compact, accurate and reliable.": "Súng bullpup thế hệ mới của Israel. Nhỏ gọn, chính xác và siêu bền.",
  "Assault Rifle: Vz. 58 P": "Súng Trường Tấn Công: Vz. 58 P",
  "Designed and built in Czechoslovakia until the mid 1980s.": "Được thiết kế và chế tạo tại Tiệp Khắc cho đến giữa thập niên 1980.",
  "Assault Rifle: XM8": "Súng Trường Tấn Công: XM8",
  "This next-generation rifle has an integrated optics package.": "Khẩu súng trường thế hệ mới được tích hợp sẵn gói phụ kiện ngắm bắn.",
  "Pistol: F45": "Súng Lục (Pistol): F45",
  "A lightweight, polymer .45 caliber pistol made for the civilian market.": "Khẩu súng lục đạn .45 caliber siêu nhẹ, bọc polyme dành cho thị trường dân sự.",
  "Pistol: F45 Tactical": "Súng Lục (Pistol): F45 Tactical",
  "A military and police oriented version of the F45, match barrel and optic.": "Phiên bản F45 được chế tạo riêng cho cảnh sát và quân đội, tối ưu nòng súng và có kèm ống ngắm.",
  "Pistol: P 07 Duty": "Súng Lục (Pistol): P 07 Duty",
  "Light weight polymer, accurate and reliable. Enough said.": "Khung polyme siêu nhẹ, ngắm là trúng và bắn không bao giờ kẹt. Chỉ cần nói thế thôi.",
  "Pistol: P 07 Tactical Duty": "Súng Lục (Pistol): P 07 Tactical Duty",
  "Groomed for combat and comes with a threaded barrel.": "Được sinh ra để chiến đấu và đi kèm với nòng tiện ren để gắn giảm thanh.",
  "Pistol: P.08": "Súng Lục (Pistol): P.08",
  "An accurate and iconic collector's firearm. Be sure to keep it clean!": "Một khẩu súng đầy tính biểu tượng và độ chính xác cao để sưu tầm. Nhớ phải giữ nó sạch sẽ đấy!",
  "Pistol: P 38 Stobaugh": "Súng Lục (Pistol): P 38 Stobaugh",
  "A special collector's item. Captured in WW II by a special G.I.": "Món đồ siêu hiếm để sưu tầm. Bị một lính thủy quân lục chiến đặc biệt tịch thu trong Thế chiến II.",
  "Revolver: Model 986": "Súng Rulo (Revolver): Model 986",
  "9mm revolvers made in the US are rare, now you have one!": "Súng rulo 9mm mà được sản xuất tại Mỹ là siêu hiếm đấy, giờ bạn đã có một cây rồi!",
  "Rifle: 464 Custom 22": "Súng Trường (Rifle): 464 Custom 22",
  "Factory tacti-cool .22 varmint gun, with optic. In case the squirrels attack!": "Súng săn thú nhỏ .22 được độ bao ngầu từ xưởng, gắn sẵn ống ngắm. Đề phòng mấy con sóc nó phản công!",
  "Rifle: Model 1903": "Súng Trường (Rifle): Model 1903",
  "A venerable combat rifle used by the US military over a period of 70 years.": "Khẩu súng trường chiến đấu đáng kính của Quân đội Hoa Kỳ đã chinh chiến hơn 70 năm.",
  "Rifle: Arctic Warrior": "Súng Trường (Rifle): Arctic Warrior",
  "Pinpoint accuracy at long range, this rifle is a huge success in military units.": "Độ chính xác tuyệt đối ở khoảng cách xa, khẩu súng này là một kiệt tác thành công vang dội của các đơn vị quân đội.",
  "Rifle: M1 Carbine": "Súng Trường (Rifle): M1 Carbine",
  "A veteran of many wars, this rifle can be found all over the world.": "Là cựu binh đã trải qua biết bao cuộc chiến, khẩu súng này giờ đây có mặt ở khắp nơi trên thế giới.",
  "Rifle: M14 Talon DMR": "Súng Trường (Rifle): M14 Talon DMR",
  "The pinnacle of precision M14 evolution to date. this version is custom to the Red Talon group.": "Đỉnh cao của sự phát triển vũ khí M14 chính xác cho đến ngày nay. Phiên bản này được độ riêng cho nhóm Đặc nhiệm Red Talon."
};

function applyTranslations(chunkPath, mapData) {
  if (!fs.existsSync(chunkPath)) return;
  const chunk = JSON.parse(fs.readFileSync(chunkPath, 'utf8'));
  for (const r of chunk.replacements) {
    if (mapData[r.sourceText]) {
      r.translatedText = mapData[r.sourceText];
    }
  }
  fs.mkdirSync('output/languages/bmd_chunks', { recursive: true });
  fs.writeFileSync(chunkPath.replace('input/languages/', 'output/languages/'), JSON.stringify(chunk, null, 2), 'utf8');
}

applyTranslations('input/languages/bmd_chunks/bmd_chunk_7.json', map);
applyTranslations('input/languages/bmd_chunks/bmd_chunk_8.json', map);

console.log('Translated BMD Chunk 7 and 8 successfully!');
