const fs = require('fs');
const chunk179 = {
  "We'd all be better off if we knew what was out there.": "Tất cả chúng ta sẽ tốt hơn rất nhiều nếu chúng ta biết được có những gì ở ngoài kia.",
  "Eduardo": "Eduardo",
  "March": "March",
  "When I say headshot, you know I mean shoot it in the head, right? Time to go look for another one.": "Khi tôi nói bắn vào đầu (headshot), cậu biết ý tôi là bắn thẳng vào đầu nó, đúng đéo? Đã đến lúc phải đi tìm một con khác rồi.",
  "How fearful your community is.": "Cộng đồng của cậu mới sợ hãi làm sao.",
  "You get around the valley a fair bit. Feel like making a delivery for me? I'll pay, of course.": "Cậu đi loanh quanh khắp cái thung lũng này cũng khá nhiều đấy. Có muốn thực hiện một chuyến giao hàng cho tôi đéo? Tất nhiên là tôi sẽ trả công đàng hoàng.",
  "We'll open up after the zombies are gone.": "Chúng tôi sẽ mở cửa đón tiếp sau khi bọn zombies đã biến mất.",
  "Suppose so.": "Chắc là vậy.",
  "Medications Expired": "Thuốc Men Đã Hết Hạn (Medications Expired)",
  "Assault Rifle: AK47 Grenade Launcher": "Súng Trường Tấn Công (Assault Rifle): AK47 Grenade Launcher",
  "Too many fucking newbies around here. We gotta get us a training facility.": "Có quá nhiều những kẻ mới đến (newbies) chết tiệt xung quanh đây. Chúng ta phải tìm cho mình một cơ sở huấn luyện (training facility) thôi.",
  "Done scouting. Nothing major to report.": "Đã trinh sát xong. Đéo có gì hệ trọng để báo cáo cả.",
  "Hey, what's going on?": "Này, chuyện quái gì đang xảy ra vậy?",
  "Aces, baby! Aces.": "Tuyệt đỉnh, cưng à! Đỉnh của chóp.",
  "81 GENERIC Harold Atede": "81 CHUNG (GENERIC) Harold Atede",
  "One of them big fat zeds just moved into town, and we're on the menu.": "Một trong những con zeds béo ú to lớn đó vừa mới di chuyển vào thị trấn, và chúng ta đang nằm trên thực đơn của nó đấy.",
  "Gutierrez": "Gutierrez",
  "What's up?": "Có chuyện gì thế?",
  "Watch for EYES IN THE SKY missions for the Army.": "Hãy chú ý đến các nhiệm vụ CON MẮT TRÊN BẦU TRỜI (EYES IN THE SKY) dành cho Quân Đội.",
  "Ariel": "Ariel",
  "SEARCH COMPLETE: Facility Need": "ĐÃ TÌM KIẾM XONG: Nhu Cầu Cơ Sở Vật Chất (Facility Need)",
  "Ah, fuck it, I'll come too. The more the merrier, I guess.": "Ah, mặc kệ nó đi, tôi cũng sẽ đến. Càng đông càng vui, tôi đoán vậy.",
  "Steel Wool": "Bùi Nhùi Thép (Steel Wool)",
  "I need a runner, ASAP.": "Tôi cần một người chạy việc (runner), càng sớm càng tốt (ASAP).",
  "Can't hardly walk with this leg. Fucking bullshit.": "Gần như đéo thể đi lại được với cái chân này. Đúng là tào lao nhảm nhí chết tiệt.",
  "What do you suppose that was about?": "Cậu cho rằng chuyện đó là về vấn đề gì?",
  "Hey! Come on up--just enjoying the view.": "Này! Lên đây đi--chỉ là đang tận hưởng cảnh đẹp thôi mà.",
  "Hold on, I'm almost there!": "Chờ chút, tôi sắp đến nơi rồi!",
  "Find out what's happening at the bridge.": "Tìm hiểu xem chuyện quái gì đang xảy ra ở cây cầu.",
  "That ain't gonna fuckin' fit on this gun.": "Cái thứ đó sẽ đéo thể nào lắp vừa vặn khốn kiếp lên khẩu súng này được đâu.",
  "Scratch one freak.": "Gạch tên một con quái thai (freak) đi.",
  "Cpt": "Đại Úy (Cpt)",
  "144 STORY Ed Jones": "144 CỐT TRUYỆN (STORY) Ed Jones",
  "Hey, lay on the horn there--that'll draw them out into the road.": "Này, hãy bấm còi ở đằng kia đi--điều đó sẽ thu hút bọn chúng ra ngoài đường đấy.",
  "Requires WEEKLY AD CIRCULARS.": "Yêu cầu TỜ RƠI QUẢNG CÁO HÀNG TUẦN (WEEKLY AD CIRCULARS).",
  "Get out there, and see if you can bring them back alive.": "Hãy ra ngoài đó, và xem liệu cậu có thể đưa họ trở về sống sót được đéo.",
  "Protect the Doctor": "Bảo Vệ Bác Sĩ",
  "Guess that's one of the perks of having all the guys with guns working for you. I'm telling you, if it wasn't for the girls, I think I'd take my chances on my own.": "Đoán rằng đó là một trong những đặc quyền khi có tất cả những gã được trang bị súng ống làm việc cho mình. Tôi nói cho cậu biết nhé, nếu đéo phải vì những cô gái ở đây, tôi nghĩ rằng tôi đã tự mình nắm lấy cơ hội rồi.",
  "Eccentric historian, best known for his collection of antique dictionaries.": "Nhà sử học lập dị, được biết đến nhiều nhất với bộ sưu tập những cuốn từ điển cổ của ông ta.",
  "Y'know, some recon wouldn't be a bad idea.": "Cậu biết đấy, một vài cuộc trinh sát thám thính (recon) sẽ đéo phải là một ý tưởng tồi đâu.",
  "Gained +2 Ammo.": "Nhận được +2 Đạn Dược (Ammo).",
  "See that? Black mold.": "Thấy cái đó đéo? Nấm mốc đen đấy.",
  "Well, as it says in Revelation, \"Fear none of those things which thou shalt suffer": "Chà, như đã nói trong sách Khải Huyền, \"Đừng sợ những điều mà ngươi sẽ phải chịu đựng",
  "Steward": "Steward",
  "Great! Try not to fuck it up this time!": "Tuyệt vời! Lần này hãy cố gắng đừng có làm hỏng chuyện khốn kiếp (fuck it up) đấy!",
  "What's in those samples?": "Có cái gì trong những mẫu vật đó vậy?",
  "Thanks, that really helped.": "Cảm ơn, điều đó thực sự đã giúp ích rất nhiều đấy.",
  "50% chance to resolve relationship issues.": "Có 50% cơ hội giải quyết các vấn đề liên quan đến các mối quan hệ (relationship issues).",
  "Hermann": "Hermann",
  "Rifles": "Súng Trường (Rifles)",
  "Only one way out....": "Chỉ có một lối thoát duy nhất....",
  "Leon": "Leon",
  "Didn't think we'd make it that time.": "Đã từng đéo nghĩ rằng chúng ta sẽ vượt qua được lúc đó.",
  "But we have to at least consider the possibility that we are it, and the survival of our species depends on us.": "Nhưng ít nhất chúng ta cũng phải xem xét đến khả năng rằng chúng ta chính là những người đó, và sự sinh tồn của giống loài chúng ta phụ thuộc cả vào chúng ta.",
  "TIP: Attach a suppressor to muffle your gunshots.": "MẸO (TIP): Lắp thêm một ống giảm thanh (suppressor) để bóp nghẹt tiếng súng của cậu.",
  "Utility Skill": "Kỹ Năng Đa Dụng (Utility Skill)",
  "Isn't that suicide?": "Đó đéo phải là tự sát sao?",
  "Killed a zombie with your car": "Đã tông chết một con zombie bằng xe ô tô của cậu",
  "Rifle: SVT-40": "Súng Trường (Rifle): SVT-40",
  "Now, I'm not saying they've ever murdered anyone in cold blood...": "Bây giờ, tôi đéo nói rằng bọn họ đã từng sát hại bất cứ ai một cách máu lạnh...",
  "%2$s has failed to recover from illness.": "%2$s đã thất bại trong việc phục hồi khỏi căn bệnh.",
  "Copy that, Black Friday. Highroad out.": "Rõ rồi, Black Friday. Highroad hết (out).",
  "SUV with Bubbles!": "Chiếc Xe SUV với Bong Bóng (Bubbles)!",
  "Thick Skull, Small Brain": "Hộp Sọ Dày, Não Nhỏ",
  "I can only tell you what I believe the Lord told me--that you were chosen for this, and that He supports you and wants you to succeed.": "Tôi chỉ có thể nói cho cô biết những gì tôi tin rằng Chúa đã nói với tôi--rằng cô đã được lựa chọn cho sứ mệnh này, và rằng Người ủng hộ cô cũng như muốn cô thành công.",
  "I'm just lucky to be alive.": "Tôi chỉ là đang may mắn được sống sót mà thôi.",
  "6 GENERIC B.W. Wilson": "6 CHUNG (GENERIC) B.W. Wilson",
  "You seem troubled. Is everything all right?": "Trông cậu có vẻ đang gặp rắc rối thì phải. Mọi chuyện vẫn ổn chứ?",
  "Sexting": "Nhắn Tin Gợi Dục (Sexting)",
  "Our scout spotted a zed in armor. This won't be easy to drop.": "Trinh sát (scout) của chúng ta đã phát hiện ra một con zed mặc áo giáp. Sẽ đéo dễ dàng để có thể hạ gục con này đâu.",
  "Are we done here?": "Chúng ta đã làm xong việc ở đây chưa?",
  "You wanna dance?": "Mày muốn nhảy một điệu đéo?",
  "Works extra shifts as a paramedic in the inner city, patching bullet holes. Ready at a moment's notice to be called back into service.": "Làm thêm ca với tư cách là một nhân viên y tế (paramedic) ở trong khu vực trung tâm thành phố, khâu vá những lỗ đạn. Luôn sẵn sàng chờ lệnh để được triệu tập quay trở lại phục vụ quân ngũ bất cứ lúc nào.",
  "Okay, I think we're good.": "Được rồi, tôi nghĩ chúng ta ổn rồi đấy.",
  "Umm... little help?": "Umm... có thể giúp tôi một tay được đéo?",
  "Found a stash of ammunition in the back of a pickup truck. -%1$s": "Đã tìm thấy một kho đạn dược (ammunition) được cất giấu ở phía sau một chiếc xe bán tải (pickup). -%1$s",
  "Let's get started.": "Hãy bắt đầu thôi nào.",
  "We're going to broaden our search. Grant was last seen alive, but her current status and location are unknown.": "Chúng ta sẽ mở rộng phạm vi tìm kiếm. Lần cuối cùng người ta nhìn thấy Grant thì cô ấy vẫn còn sống, nhưng tình trạng và vị trí hiện tại của cô ấy thì vẫn chưa được rõ.",
  "Alex": "Alex",
  "Greatly reduced Vitality and Stamina. Bed rest is advised. Small chance of recovery every 24 hours.": "Sinh Lực (Vitality) và Thể Lực (Stamina) bị giảm sút nghiêm trọng. Khuyên bạn nên nghỉ ngơi trên giường. Có một tỷ lệ nhỏ để phục hồi sau mỗi 24 giờ.",
  "We've received a package of general supplies to get us through the next little while.": "Chúng ta đã nhận được một gói hàng chứa các nhu yếu phẩm (supplies) chung để giúp chúng ta vượt qua một khoảng thời gian sắp tới.",
  "Shiitake Mushrooms": "Nấm Hương (Shiitake Mushrooms)",
  "Antique American Civil War replica.": "Một bản sao vũ khí cổ điển thời Nội Chiến Hoa Kỳ.",
  "Could be worse...you still got me around, right?": "Mọi chuyện đã có thể tồi tệ hơn... cậu vẫn còn có tôi ở bên cạnh, đúng đéo?",
  "I'm leaving this note for my family and friends. If that's not you, put this note down before the poison in the ink seeps into your skin and kills you. If it is you, don't worry, the poison thing was a bluff. I'm going across the river to find out what those Army pigs know. If I'm not back by Thursday, assume I've been compromised by government mind-lasers and you should shoot me on sight.": "Tôi để lại mảnh giấy ghi chú này cho gia đình và bạn bè của tôi. Nếu bạn đéo phải là họ, hãy đặt mảnh giấy ghi chú này xuống trước khi chất độc trong mực ngấm vào da và giết chết bạn. Nếu đó là bạn, đừng lo lắng, chuyện về chất độc chỉ là một trò lừa bịp thôi. Tôi sẽ đi qua bờ sông bên kia để tìm hiểu xem đám lợn Quân Đội đó biết được những gì. Nếu đến Thứ Năm mà tôi đéo trở lại, hãy cứ cho rằng tôi đã bị thỏa hiệp bởi các tia laser kiểm soát tâm trí của chính phủ và bạn nên bắn tôi ngay khi nhìn thấy.",
  "Trust Me, I'm an Expert": "Hãy Tin Tôi Đi, Tôi Là Một Chuyên Gia Mà",
  "135 STORY Doc Hanson": "135 CỐT TRUYỆN (STORY) Doc Hanson",
  "I think that's all I needed to do for now.": "Tôi nghĩ đó là tất cả những gì tôi cần phải làm trong lúc này rồi.",
  "Special Forces combat rifle. Has a pairing of optics.": "Súng trường chiến đấu của Lực Lượng Đặc Nhiệm (Special Forces). Có gắn kèm theo một bộ ống ngắm quang học.",
  "Secure the Area": "Đảm Bảo An Toàn Cho Khu Vực Này",
  "Goddamn I'm tired of having to make the hard choice. We won't forget you, %3$s. -%1$s": "Mẹ kiếp tôi đã quá mệt mỏi với việc luôn phải đưa ra sự lựa chọn khó khăn này rồi. Chúng tôi sẽ đéo bao giờ quên cậu đâu, %3$s. -%1$s",
  "Now that's the way to work off some anger.": "Đó chính là cách giải tỏa bớt cơn giận đấy.",
  "Something doesn't feel right about this one.... - %1$s": "Có điều gì đó đéo ổn về chuyện này.... - %1$s",
  "Shit. Shit! I'm ready!": "Chết tiệt. Chết tiệt! Tôi đã sẵn sàng rồi!",
  "The M110 Semi-Automatic Sniper System, due to replace the M24 system.": "Hệ thống Súng Bắn Tỉa Bán Tự Động (Semi-Automatic Sniper) M110, dự kiến sẽ thay thế cho hệ thống M24.",
  "Donaldson": "Donaldson",
  "Harris": "Harris",
  "Welcome to the Kirkman Residence": "Chào mừng đến với Khu Dân Cư Kirkman",
  "Number Seven angels forty, ten mikes.": "Number Seven thiên thần bốn mươi, mười mikes.",
  "Man, if you weren't here, we'd have been fucked.": "Trời ạ, nếu cậu đéo có mặt ở đây, chắc chắn là bọn tôi đã chết chắc cmnr."
};

const file = 'output/languages/chunks/btxt_chunk_179.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_179.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk179[r.sourceText]) {
    r.translatedText = chunk179[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 179 successfully!');
