const fs = require('fs');
const chunk144 = {
  "I encountered a new group of survivors. They're barely hanging on. - %1$s": "Tôi vừa chạm trán một nhóm người sống sót mới. Họ đang phải chật vật để cầm cự. - %1$s",
  "Zoom": "Phóng To",
  "Ask any hunter and they'll tell you: you're not going to improve your Rifle Specialization unless you start bagging trophies with one.": "Hỏi bất kỳ thợ săn nào và họ sẽ nói cho cậu biết: cậu sẽ đéo thể cải thiện được Chuyên Môn Súng Trường (Rifle Specialization) trừ khi cậu bắt đầu thu thập chiến lợi phẩm bằng nó.",
  "With the medicine situation being what it is, I guess I get to just tough it out.": "Với tình hình thuốc men hiện tại, tôi đoán mình chỉ đành phải cắn răng chịu đựng thôi.",
  "Survive": "Sống Sót",
  "Hot Plate": "Bếp Điện",
  "This attitude of yours won't cut it.": "Cái thái độ này của cậu đéo giải quyết được gì đâu.",
  "Ma'am, I have to ask you to turn around and walk the other way. This operation is classified.": "Thưa cô, tôi yêu cầu cô quay đầu lại và đi hướng khác. Hoạt động này là tuyệt mật.",
  "One of our scouts encountered a Juggernaut while out on patrol. We took it down to buyt ourselves some time before the next siege ... but we suffered a loss in the process.": "Một trong những trinh sát viên của chúng ta đã chạm trán một con Juggernaut khi đang đi tuần tra. Chúng ta đã hạ gục nó để câu thêm chút thời gian trước đợt công thành tiếp theo ... nhưng chúng ta cũng đã chịu tổn thất trong quá trình đó.",
  "I had this crazy streak of headshots just now. I must be getting better at shooting. - %1$s": "Tôi vừa có một chuỗi headshot điên rồ này. Chắc hẳn kỹ năng bắn súng của tôi đang tốt lên rồi. - %1$s",
  "Timothy Hall is headed out": "Timothy Hall đang đi ra ngoài",
  "Huh. No wonder Becca wanted to keep her past hidden. - %1$s": "Hừm. Thảo nào Becca lại muốn giấu nhẹm quá khứ của cô ta đi. - %1$s",
  "Where were we?": "Chúng ta đang nói tới đâu rồi nhỉ?",
  "Rich Friend": "Bạn Giàu",
  "I'm locked and loaded, let's move.": "Tôi đã lên nòng và sẵn sàng rồi, di chuyển thôi.",
  "MATERIALS RESOURCE. Construction materials that were never sold.": "NGUỒN VẬT LIỆU. Những vật liệu xây dựng (Construction materials) chưa bao giờ được bán đi.",
  "Gain Trust to gain Friends.": "Đạt được Sự Tin Tưởng (Trust) để có thêm Bạn Bè (Friends).",
  "Carly": "Carly",
  "Influence Costs Increased": "Chi Phí Ảnh Hưởng (Influence) Tăng",
  "A must-have when gardening near zombies.": "Một thứ bắt buộc phải có khi làm vườn gần bọn zombie.",
  "Oh, yes sir. Why don't I inventory all the bullshit around here while I wait?": "Ồ, rõ thưa ngài. Tại sao tôi lại đéo kiểm kê đống rác rưởi chết tiệt quanh đây trong lúc chờ đợi cơ chứ?",
  "SCRAPPED: Trouble at the Courthouse": "ĐÃ HỦY: Rắc rối ở Tòa Án (Courthouse)",
  "Hey, hey. At least the bullet didn't hit a major artery, huh? There's something. You know, that accident could have been a lot worse.": "Này, này. Ít nhất thì viên đạn cũng đéo trúng động mạch chủ, phải đéo? Cứ cho là vậy đi. Cậu biết đấy, tai nạn đó đáng lẽ ra còn có thể tồi tệ hơn nhiều.",
  "I'll carry the stuff and do the talking. I just want to have an extra gun on hand in case things go bad.": "Tôi sẽ mang vác đồ và phụ trách nói chuyện. Tôi chỉ muốn có thêm một khẩu súng dự phòng đề phòng mọi việc trở nên tồi tệ thôi.",
  "Video Games": "Trò Chơi Điện Tử",
  "Hey, you got a little on you.": "Này, cậu bị dính một ít lên người kìa.",
  "So, how about it?": "Vậy, ý cậu sao?",
  "Yeah? Gotta say I am surprised to see you standing around with your thumb up your ass while civilians are dying all around you.": "Thế à? Phải nói là tôi rất ngạc nhiên khi thấy ngài cứ đứng đực ra đó với ngón tay chọc vào lỗ đít trong khi dân thường đang chết như ngả rạ xung quanh ngài đấy.",
  "A folding, semi-auto survival rifle. Accurate but not meant for heavy use.": "Một khẩu súng trường sinh tồn bán tự động, có thể gấp gọn. Chính xác nhưng đéo dành cho việc sử dụng với cường độ cao.",
  "Stack of Food": "Chồng Thức Ăn (Food)",
  "There's an RV in the valley that might be able to get us out of here ...": "Có một chiếc xe RV ở dưới thung lũng có thể sẽ đưa chúng ta ra khỏi đây được đấy ...",
  "What I want you to do is head to the cell tower on the north side of town and find a way up. Tell us if the coast is clear. Be our eyes in the sky.": "Điều tôi muốn cậu làm là đi tới trạm thu phát sóng ở phía bắc thị trấn và tìm đường trèo lên đó. Hãy báo cho chúng tôi biết liệu bề mặt có an toàn đéo. Hãy làm đôi mắt trên bầu trời của chúng tôi.",
  "Rafael": "Rafael",
  "Okay. I think I'm ready to head home now.": "Được rồi. Tôi nghĩ bây giờ tôi đã sẵn sàng để về nhà rồi.",
  "(s)": "(s)",
  "Cover me!": "Yểm trợ cho tôi!",
  "Lotsa weird noises.": "Rất nhiều tiếng ồn kỳ quái.",
  "Great. So we're stuck up here playing cannibal family picnic until somebody bothers to come looking for us?": "Tuyệt. Vậy ra chúng ta bị kẹt trên này, chơi trò dã ngoại của gia đình ăn thịt người cho đến khi có ai đó chịu cất công đi tìm chúng ta sao?",
  "We need to keep it together, no matter how bad it looks.": "Chúng ta cần phải giữ bình tĩnh, cho dù tình hình có tồi tệ đến mức nào đi chăng nữa.",
  "Sweet Ride": "Chiếc Xe Xịn Xò",
  "Major Hawkes? I know it's irregular, but ... I'd like to stay on and help out your unit, if I can.": "Thiếu tá Hawkes? Tôi biết việc này là bất thường, nhưng ... Tôi muốn ở lại và giúp đỡ đơn vị của ngài, nếu tôi có thể.",
  "Additional Vitality bonus for everyone.": "Thêm phần thưởng Sinh Lực cho mọi người.",
  "You can't just hang around in that mood. Follow me.": "Cậu đéo thể cứ loanh quanh với cái tâm trạng ủ rũ đó được đâu. Theo tôi.",
  "Munitions": "Đạn Dược",
  "You know, before I even hit Basic Training, my father taught me to fight ... with one of these.": "Cậu biết đéo, trước khi tôi bước vào Khóa Huấn luyện Cơ bản, cha tôi đã dạy tôi cách chiến đấu ... với một trong những thứ này.",
  "That's what happens when we don't have a clean place to prepare our food. We need a kitchen.": "Đó là những gì sẽ xảy ra khi chúng ta đéo có một nơi sạch sẽ để sơ chế thức ăn. Chúng ta cần một nhà bếp.",
  "Those people in Spencer's Mill are still in major debt to the Wilkersons. Just a reminder.": "Những người ở Spencer's Mill vẫn còn nợ nhà Wilkersons một khoản lớn đấy. Chỉ nhắc nhở thế thôi.",
  "A riot baton with some bolts added.": "Một chiếc dùi cui chống bạo động được gắn thêm vài cái bu-lông.",
  "TIP: Press [execute] to finish off a downed foe.": "MẸO: Nhấn [execute] để kết liễu một kẻ thù đã gục ngã.",
  "I won't forget this, you know.": "Tôi sẽ đéo quên chuyện này đâu, cậu biết đấy.",
  "Rusty nails are an added bonus.": "Những chiếc đinh gỉ là một phần thưởng đi kèm đấy.",
  "Those might be survivors.": "Đó có thể là những người sống sót.",
  "Home": "Căn Cứ",
  "Knows the truth now.": "Bây giờ đã biết sự thật rồi.",
  "Killed a zombie with explosives": "Giết một con zombie bằng thuốc nổ",
  "Oh, my fellow survivors, did you think I'd left you? Never fear, Vienna Cho is here for all your post-apocalyptic concerns.": "Ồ, những người bạn sống sót của tôi, các bạn nghĩ tôi đã bỏ rơi các bạn sao? Đừng sợ, Vienna Cho đã có mặt ở đây để giải quyết tất cả các vấn đề hậu tận thế của các bạn.",
  "%1$s got %2$s sick.": "%1$s đã làm cho %2$s bị ốm.",
  "I would trust Kilo with my life.": "Tôi sẵn sàng giao phó mạng sống của mình cho Kilo.",
  "Enables partial vehicle repair.": "Cho phép sửa chữa phương tiện một phần.",
  "We could always use more help around here... and they'll probably appreciate a safe place to stay.": "Chúng ta luôn cần thêm sự giúp đỡ quanh đây... và có lẽ họ sẽ trân trọng một nơi an toàn để ở lại.",
  "1 Outpost - Drone Recon": "1 Tiền Đồn - Trinh Sát Bằng Drone",
  "A reliable military shotgun. INCENDIARY.": "Một khẩu súng shotgun quân dụng đáng tin cậy. ĐẠN CHÁY (INCENDIARY).",
  "Okay now.": "Bây giờ thì ổn rồi.",
  "You can't seriously be asking me to do this.": "Cậu đéo thể nghiêm túc yêu cầu tôi làm việc này được.",
  "You stay where you are, Sergeant, and I will get to you in due time.": "Trung sĩ, hãy ở yên vị trí đó, và tôi sẽ đến chỗ cậu vào thời điểm thích hợp.",
  "Fitness Regimen started!": "Chế độ Rèn luyện thể lực (Fitness Regimen) đã bắt đầu!",
  "Outpost - Incendiary Barrage": "Tiền Đồn - Oanh Tạc Đạn Cháy (Incendiary Barrage)",
  "Yvonne": "Yvonne",
  "Gotta catch my breath.": "Phải lấy lại hơi đã.",
  "Profiteer": "Kẻ Đầu Cơ",
  "Sofia": "Sofia",
  "Somebody has to be the responsible one.": "Phải có ai đó đứng ra chịu trách nhiệm chứ.",
  "um, duh!": "ừ, đương nhiên rồi!",
  "Not just yet.": "Vẫn chưa phải lúc này.",
  "Dan Bogatz may have been on the outs with Thomas Horn, but he should be able to continue Horn's research into whatever's going on here.": "Dan Bogatz có thể đã bất hòa với Thomas Horn, nhưng ông ấy hẳn là có thể tiếp tục công trình nghiên cứu của Horn về bất cứ chuyện khốn kiếp gì đang xảy ra ở đây.",
  "I've got stuff scattered all over the place. Give me a second to put it all together?": "Tôi để đồ đạc vương vãi khắp nơi. Cho tôi một giây để thu dọn lại mọi thứ được đéo?",
  "Only one way out and it's walled off. Options are limited, get through it or die. -%1$s": "Chỉ có một lối thoát duy nhất và nó đã bị bịt kín. Lựa chọn rất hạn hẹp, vượt qua nó hoặc là chết. -%1$s",
  "Approach a container and press [xi_use] to search it.": "Tiếp cận một hộp chứa đồ và nhấn [xi_use] để lục lọi nó.",
  "We'd like to join you, if you're up for it.": "Chúng tôi muốn gia nhập cùng với các bạn, nếu các bạn đồng ý.",
  "That's … that's awful. No excuse, sir.": "Điều đó … thật tồi tệ. Đéo có lời bào chữa nào, thưa ngài.",
  "Vito": "Vito",
  "Keep your eyes peeled for infestations.": "Hãy căng mắt ra mà tìm kiếm những ổ dịch (infestations).",
  "Your equipped gun uses a different kind of ammunition.": "Khẩu súng cậu đang trang bị sử dụng một loại đạn khác.",
  "Bailey, he... well, by the time we got the dogs off him, there wasn't much left to tell he was human.": "Bailey, anh ta... ừ thì, khi chúng tôi gỡ được lũ chó ra khỏi người anh ta, đéo còn lại bao nhiêu phần để có thể nhận ra anh ta từng là con người nữa.",
  "Black Friday, we've got another possible contact via aerial recon.": "Black Friday, chúng tôi vừa bắt được một mục tiêu (contact) khả nghi khác thông qua trinh sát trên không.",
  "I should return home.": "Tôi nên quay về nhà thôi.",
  "Okay, but you need to follow my directions exactly.": "Được, nhưng các cậu cần phải làm theo chính xác những chỉ dẫn của tôi.",
  "Used to get through church by filling notebooks with memorized sports statistics. They're all still in a closet at home. (Quick Wits)": "Từng phải vượt qua những buổi lễ nhà thờ bằng cách lấp đầy các cuốn sổ bằng những số liệu thống kê thể thao được ghi nhớ. Tất cả chúng vẫn còn nằm trong tủ quần áo ở nhà. (Phản Ứng Nhanh)",
  "Everybody's feeling a lot better after that dinner.": "Mọi người đang cảm thấy khá hơn rất nhiều sau bữa tối đó.",
  "Hawkes": "Hawkes",
  "Casings": "Vỏ Đạn",
  "Now don't go spending that all in one place!": "Này, đừng có đi tiêu xài hết sạch ở một chỗ đấy nhé!",
  "I don't have much, but I'll fight alongside you.": "Tôi đéo có nhiều đồ đạc, nhưng tôi sẽ sát cánh chiến đấu cùng cậu.",
  "Boiler Kettle": "Ấm Siêu Tốc (Boiler Kettle)",
  "Gandolfi": "Gandolfi",
  "Drove a big rig on the Danforth/Chicago route.": "Từng lái một chiếc xe tải hạng nặng trên tuyến đường Danforth/Chicago.",
  "20 GENERIC Dr. Nancy Paxton": "20 GENERIC Bác sĩ Nancy Paxton",
  "We're all stressed, okay? But we can't afford to be at each other's throats. So start playing nice, or you're out on your ass.": "Tất cả chúng ta đều đang căng thẳng, ok? Nhưng chúng ta đéo thể để bản thân cắn xé lẫn nhau được. Vì vậy hãy bắt đầu cư xử cho tử tế đi, nếu đéo cậu sẽ bị đá đít ra khỏi đây đấy.",
  "Damn straight! Chin up, soldier.": "Quá chuẩn! Ngẩng cao đầu lên, người lính.",
  "Dammit, just when I thought we had a chance.": "Chết tiệt, ngay lúc tôi tưởng rằng chúng ta có cơ hội."
};

const file = 'output/languages/chunks/btxt_chunk_144.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_144.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk144[r.sourceText]) {
    r.translatedText = chunk144[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 144 successfully!');
