const fs = require('fs');
const chunk126 = {
  "Heads up, survivors. Looks like it's getting pretty bad out there.": "Chú ý nào, những người sống sót. Có vẻ như tình hình ngoài kia đang trở nên khá tệ đấy.",
  "We could make the things we need to fight zombies instead of having to scavenge for everything.": "Chúng ta có thể tự chế tạo những thứ mình cần để chiến đấu với zombie thay vì lúc nào cũng phải đi nhặt mót mọi thứ.",
  "Nobody deserves to be in debt to the Wilkersons. - %1$s": "Đéo ai đáng bị mang nợ bọn nhà Wilkerson cả. - %1$s",
  "Ranger station?": "Trạm kiểm lâm?",
  "Long range service provider. Scoped.": "Nhà cung cấp dịch vụ tầm xa. Có ống ngắm.",
  "--------": "--------",
  "Psst! On the left.": "Suỵt! Bên trái kìa.",
  "I'm trapped. Please, if you're heading out of town, bring me along.": "Tôi bị mắc kẹt rồi. Làm ơn, nếu mọi người chuẩn bị rời khỏi thị trấn, cho tôi đi cùng với.",
  "I didn't sign up for that.": "Tôi đéo đăng ký tham gia chuyện đó đâu.",
  "Scavenging Speed": "Tốc Độ Nhặt Mót",
  "Kline": "Kline",
  "Wow, that is not a normal zombie.": "Chà, đó đéo phải là một con zombie bình thường đâu.",
  "Sir, we've set up a watchtower where you can see the whole perimeter.": "Thưa sếp, chúng tôi đã thiết lập một tháp canh nơi ngài có thể quan sát toàn bộ vành đai.",
  "That facility is just what we needed.": "Cơ sở đó chính xác là những gì chúng ta cần.",
  "No more free cars for me.": "Đéo còn những chiếc xe miễn phí cho tôi nữa rồi.",
  "Building something just feels like...progress.": "Xây dựng một cái gì đó có cảm giác giống như... một sự tiến bộ vậy.",
  "Rescued Maya.": "Đã cứu Maya.",
  "Veronica": "Veronica",
  "So next time you get into an argument, try using your words.": "Vậy nên lần tới nếu có xảy ra cãi vã, hãy cố gắng dùng lời nói để giải quyết.",
  "LOG: Barely Survived": "NHẬT KÝ: Sống Sót Trong Gang Tấc",
  "Training Area": "Khu Huấn Luyện (Training Area)",
  "My hero.": "Người hùng của em.",
  "Thanks. I'm ready to go.": "Cảm ơn. Tôi sẵn sàng đi rồi.",
  "Not your fault. I just hope things there aren't as bad as they are here.": "Không phải lỗi của cậu. Tôi chỉ hy vọng mọi chuyện ở đó không tồi tệ như ở đây.",
  "Just stand by while I unfuck this problem you created.": "Cứ đứng đó mà xem tôi giải quyết cái mớ bòng bong do cậu gây ra đi.",
  "Sorry, not interested.": "Xin lỗi, tôi đéo hứng thú.",
  "Potatoes": "Khoai tây",
  "I'm afraid we need to look after our own first.": "Tôi e là chúng ta cần phải tự lo cho bản thân mình trước đã.",
  "I mean, is this what we're risking a hideous, painful death for? Living on scraps in the ashes of civilization? - %1$s": "Ý tôi là, đây là lý do chúng ta mạo hiểm để đánh đổi lấy một cái chết đau đớn và gớm ghiếc sao? Sống bằng những mảnh vụn nhặt nhạnh được trong đống tro tàn của nền văn minh à? - %1$s",
  "Deja": "Deja",
  "Goddammit.": "Mẹ kiếp.",
  "Move your feet, I ain't carryin' you.": "Lết cái chân lên đi, tôi đéo cõng cậu đâu.",
  "Here, help me move this against the wall. We need to clear a space for the wounded.": "Đây, giúp tôi đẩy cái này sát vào tường. Chúng ta cần dọn một chỗ trống cho những người bị thương.",
  "Well, that's good. Here. Managed to scrounge you some immunosuppressants. Should moderate the worst of your symptoms.": "Chà, thế là tốt rồi. Đây. Mới kiếm được cho cậu một ít thuốc ức chế miễn dịch. Nó sẽ làm giảm bớt những triệu chứng tồi tệ nhất của cậu.",
  "I... what? Okay... wow. Wasn't expecting that.": "Tôi... cái gì cơ? Được rồi... chà. Đéo ngờ đến chuyện đó luôn.",
  "That would be a huge help.": "Đó sẽ là một sự giúp đỡ to lớn đấy.",
  "I hear you. Sometimes you just gotta have faith that things will work out, y'know?": "Tôi nghe cậu. Đôi khi cậu chỉ cần có niềm tin rằng mọi chuyện rồi sẽ ổn, hiểu chứ?",
  "Use the \"Preserve Food\" action at the Storage facility.": "Sử dụng hành động \"Bảo quản Thức ăn\" (Preserve Food) tại cơ sở Lưu Trữ (Storage).",
  "Mm-hmm.": "Mm-hmm.",
  "LOG: Sasquatch Sighting": "NHẬT KÝ: Nhìn Thấy Sasquatch",
  "Munitions Drop": "Hòm Tiếp Tế Đạn Dược",
  "Schulden": "Schulden",
  "Minimart": "Cửa hàng Tiện lợi",
  "Ammunition": "Đạn Dược",
  "Mcneal": "Mcneal",
  "What, you think I wouldn't help my fellow man unless it was court ordered?": "Gì chứ, cậu nghĩ tôi sẽ đéo giúp đỡ đồng loại của mình trừ khi có lệnh của tòa án à?",
  "North Gate Breached": "Cổng Phía Bắc Bị Chọc Thủng",
  "I know things look pretty grim, but what's the alternative? Strike out on your own?": "Tôi biết mọi chuyện trông khá là bi thảm, nhưng còn cách nào khác không? Tự mình ra ngoài kia mà sống à?",
  "We went out to try and rescue %1$s, but they died before we could get home.": "Chúng tôi đã ra ngoài để cố gắng giải cứu %1$s, nhưng họ đã chết trước khi chúng tôi có thể về đến nhà.",
  "How you doin'?": "Dạo này sao rồi?",
  "Forceps": "Kẹp phẫu thuật",
  "Need to be on foot for this one.": "Cần phải đi bộ để thực hiện việc này.",
  "Well, I kinda took that guy's walkie-talkie. Maybe we can raise somebody on that?": "Chà, tôi đã lấy trộm cái bộ đàm của gã đó. Có lẽ chúng ta có thể liên lạc với ai đó qua cái này chăng?",
  "68 GENERIC Janet Weiss": "68 GENERIC Janet Weiss",
  "Hellchild": "Hellchild",
  "Sounds like we have a bloater in the area. Gotta take it out.": "Nghe có vẻ như có một con bloater trong khu vực. Phải hạ gục nó thôi.",
  "Meeting new allies has earned you Fame.": "Gặp gỡ những đồng minh mới đã giúp bạn kiếm được Điểm Danh Tiếng (Fame).",
  "TIP: Press [jump] repeatedly to get up.": "MẸO: Nhấn [jump] liên tục để đứng dậy.",
  "Am I supposed to just take this abuse day after day?": "Tôi có phải chịu đựng sự hành hạ này hết ngày này qua ngày khác không hả?",
  "Uh, we, we need to get out of here.": "Uh, chúng ta, chúng ta cần phải rời khỏi đây.",
  "Ok, I'll run this home.": "Được rồi, tôi sẽ chạy mang cái này về nhà.",
  "I think I found my vantage point.": "Tôi nghĩ là tôi đã tìm thấy một điểm quan sát tốt rồi.",
  "Goddammit, they're coming from the rear, too!": "Mẹ kiếp, chúng đang đến từ phía sau nữa kìa!",
  "Puzzle angels forty, ten mikes.": "Puzzle đang bay ở độ cao 40 nghìn feet, dự kiến tới trong 10 phút nữa.",
  "Doesn't Drink or Smoke": "Không Uống Rượu hay Hút Thuốc",
  "MISSION SCRAPPED: Trade": "HỦY BỎ NHIỆM VỤ: Giao Thương",
  "Play matchmaker for Quentin and Becca.": "Làm ông mai bà mối cho Quentin và Becca.",
  "Mmmm, guarana. (Removes penalties to your maximum stamina)": "Mmmm, hạt guarana. (Loại bỏ các hình phạt đối với thể lực tối đa của bạn)",
  "Materials, tools, and fuel.": "Vật liệu, công cụ, và nhiên liệu.",
  "TIP: You can now switch off between Maya and Marcus.": "MẸO: Bây giờ bạn có thể chuyển đổi giữa Maya và Marcus.",
  "You might want to go check on... whatever's going on down by the bridges.": "Có lẽ cậu nên đi kiểm tra xem... chuyện quái gì đang xảy ra dưới mấy cây cầu kia.",
  "SET UP: Refrigerated Storage": "THIẾT LẬP: Kho Lưu Trữ Lạnh",
  "Well, don't take too long. My fingers are getting itchy.": "Chà, đừng có mất quá nhiều thời gian nhé. Ngón tay của tôi đang ngứa ngáy rồi đây.",
  "So, yeah, we both drank more than we probably should, and there's this couch in the manager's office, and... yeah.": "Vậy nên, ừ thì, cả hai chúng tôi đều đã uống nhiều hơn mức bình thường, và có một chiếc ghế dài trong văn phòng quản lý, và... vâng.",
  "I want an outpost on this location.": "Tôi muốn có một tiền đồn ở vị trí này.",
  "I'd say things are going reasonably well.": "Tôi có thể nói rằng mọi chuyện đang diễn ra khá suôn sẻ.",
  "Scheideler": "Scheideler",
  "EXPIRED: Exterminate a Bloater": "HẾT HẠN: Tiêu Diệt một Bloater",
  "Stranded Refugee": "Người Tị Nạn Bị Mắc Kẹt",
  "Think you could help me out here?": "Nghĩ cậu có thể giúp tôi một tay ở đây không?",
  "Bad Tidings": "Tin Xấu",
  "Zombies to the left. Don't think they spotted us yet.": "Có zombie ở bên trái. Tôi nghĩ chúng vẫn chưa phát hiện ra chúng ta đâu.",
  "Some more materials": "Thêm một ít Vật liệu",
  "Girl's got the common sense God gave a tree stump. You're worse than your brother.": "Cô gái à, trí khôn của cô chắc chỉ bằng cái gốc cây mất. Cô còn tệ hơn cả anh trai mình nữa.",
  "Shotgun: Model 1100": "Súng shotgun: Model 1100",
  "Infestation destroyed.": "Ổ dịch đã bị tiêu diệt.",
  "You can carry more weight in your pack before becoming encumbered.": "Bạn có thể mang nhiều trọng lượng hơn trong ba lô của mình trước khi bị rơi vào trạng thái quá tải (encumbered).",
  "A low-slung bag for the efficient packer.": "Một chiếc túi đeo thấp dành cho những người đóng gói đồ đạc hiệu quả.",
  "We're on it.": "Chúng tôi đang xử lý.",
  "We found a run-down RV on the outskirts of town.": "Chúng tôi tìm thấy một chiếc xe RV tồi tàn ở ngoại ô thị trấn.",
  "Assault Rifle: ACR": "Súng trường tấn công: ACR",
  "-%d Minute(s)": "-%d Phút",
  "Okay.": "Được rồi.",
  "Because at the rate you're going, I'd say you're halfway there.": "Bởi vì với cái tốc độ này của cậu, tôi có thể nói là cậu đã đi được nửa đoạn đường xuống mồ rồi đấy.",
  "What's the situation at home?": "Tình hình ở nhà thế nào rồi?",
  "Unconfirmed reports of one or more large explosions between Danforth and Trumbull Valley.\r\nNo scouting resources available to investigate at this time.": "Có những báo cáo chưa được xác nhận về một hoặc nhiều vụ nổ lớn nằm giữa Danforth và Thung lũng Trumbull.\r\nHiện tại không có nguồn lực trinh sát nào để điều tra vào thời điểm này.",
  "Wish I had, friend, but whatever they're up to, they aren't telling me anything about it.": "Ước gì tôi có thông tin, ông bạn ạ, nhưng bất kể chúng đang âm mưu trò gì, chúng cũng đéo hé răng nửa lời với tôi.",
  "TRIGGER NUKE": "KÍCH NỔ HẠT NHÂN",
  "Set up a space for the base's Commanding Officer, devoted to research and planning.": "Thiết lập một không gian dành cho Sĩ Quan Chỉ Huy (Commanding Officer) của căn cứ, chuyên dùng để nghiên cứu và lên kế hoạch.",
  "Michael": "Michael"
};

const file = 'output/languages/chunks/btxt_chunk_126.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_126.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk126[r.sourceText]) {
    r.translatedText = chunk126[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 126 successfully!');
