const fs = require('fs');
const chunk195 = {
  "Neighbors": "Những Người Hàng Xóm (Neighbors)",
  "All y'all okay for now? Good. I'm gonna go pass out for a little while.": "Tất cả các cậu hiện tại đều vẫn đang ổn cả chứ? Tốt rồi. Tôi sẽ đi kiếm một chỗ nào đó để ngất đi một lát đây.",
  "Well, fuck me. Nice knowin' you, I guess.": "Chà, đệt mẹ tôi. Thật vui vì đã được quen biết với cậu, tôi đoán vậy.",
  "Oooh, brainwave! Check this out": "Oooh, ý tưởng táo bạo (brainwave) vãi đái! Hãy xem thử cái này đi",
  "This place is full of zeds, and we need help clearing 'em out.": "Nơi này hiện đang chứa đầy lũ zeds, và chúng tôi đang rất cần có người giúp đỡ dọn dẹp sạch sẽ bọn chúng.",
  "I'll find an elevated position for sniping.": "Tôi sẽ đi tìm một vị trí thuận lợi ở trên cao để thực hiện việc bắn tỉa (sniping).",
  "Be thou faithful unto death, and I will give thee a crown of life.\"": "Ngươi hãy giữ lòng trung tín cho đến chết, và Ta sẽ ban cho ngươi triều thiên của sự sống.\"",
  "Nothing to see.": "Đéo có gì để xem ở đây cả.",
  "Ugh....": "Ugh....",
  "How many of these things are there?": "Rốt cuộc thì đang có bao nhiêu thứ này ở ngoài kia vậy?",
  "MISSION: The Wall": "NHIỆM VỤ (MISSION): Bức Tường (The Wall)",
  "Too close that time.": "Lần này là quá sát sao luôn đấy.",
  "This time, we're getting up close and personal. Bring a good blade with you. None of that golf club bullshit.": "Lần này, chúng ta sẽ phải tiếp cận và đối mặt trực tiếp với bọn chúng. Hãy nhớ mang theo một thanh kiếm (blade) thật tốt. Đéo có sử dụng mấy cây gậy đánh golf chết tiệt đó đâu đấy nhé.",
  "FOOD RESOURCE. It looks edible enough.": "NGUỒN THỨC ĂN (FOOD RESOURCE). Trông nó có vẻ vẫn còn đủ an toàn để có thể ăn được.",
  "We have an urgent request for backup. I'm sending the coordinates.": "Chúng tôi hiện đang có một yêu cầu rất khẩn cấp cần được hỗ trợ. Tôi đang tiến hành gửi tọa độ vị trí (coordinates) đây.",
  "I mean, signal reception's always been bad here, we're basically in a giant bowl, but we should have heard something by now.": "Ý tôi là, khả năng thu thập tín hiệu (signal) ở nơi này trước giờ vẫn luôn rất kém, về cơ bản là chúng ta đang nằm ở bên trong một cái bát khổng lồ, nhưng đáng lẽ ra chúng ta cũng phải nghe ngóng được một vài tin tức đéo nào đó rồi chứ.",
  "Deep knee bends are not my friend. Shallow ones either. (Crouching is tiring.)": "Việc phải uốn cong đầu gối xuống đéo phải là người bạn của tôi. Những người có chiều cao khiêm tốn cũng vậy. (Hành động Ngồi Xổm Crouching rất là mệt mỏi.)",
  "Finally something I need.": "Cuối cùng thì cũng đã tìm thấy thứ mà tôi đang rất cần.",
  "Trade Opportunity (Materials)": "Cơ Hội Để Có Thể Giao Dịch (Trade Opportunity) (Vật Liệu Materials)",
  "We got zeds in tow.": "Chúng ta đã dẫn dụ được lũ zeds đi theo sau lưng mình cmnr.",
  "Hey hey hey. Look, if you want this stuff you need to keep them off us.": "Này này này. Nghe đây, nếu như cậu muốn có được thứ này, cậu sẽ cần phải giữ cho bọn chúng tránh xa khỏi chúng tôi.",
  "Shit. Zombies heard the car, better move quick.": "Chết tiệt thật. Lũ zombies đã nghe thấy tiếng động cơ của chiếc xe ô tô, tốt hơn hết là hãy di chuyển thật nhanh vào.",
  "Damn, you come out of that without a scratch?": "Chết tiệt thật, cậu đã sống sót bước ra khỏi đống hỗn độn đó mà đéo hề bị một vết xước nào luôn sao?",
  "Right now, we need to clean out this office. Can you help us find what we need?": "Ngay bây giờ, chúng ta cần phải dọn dẹp sạch sẽ cái văn phòng (office) này. Cậu có thể giúp đỡ chúng tôi tìm kiếm những thứ mà chúng tôi đang cần đéo?",
  "Danforth isn't lost yet, sir.": "Danforth vẫn chưa hoàn toàn bị thất thủ đâu, thưa ngài.",
  "STRANGER IN TROUBLE": "NGƯỜI LẠ (STRANGER) ĐANG GẶP RẮC RỐI",
  "Okay, I'm getting started. Keep the zombies off my back if you can.": "Okay, tôi bắt đầu làm đây. Hãy cố gắng giữ cho lũ zombies đéo thể tấn công được tôi từ phía sau lưng nếu như cậu có thể nhé.",
  "Mcginnis": "Mcginnis",
  "Aim / Scout": "Ngắm Bắn (Aim) / Do Thám (Scout)",
  "Well, then I guess I didn't see you out here.": "Chà, vậy thì tôi đoán là tôi đã đéo hề nhìn thấy hai người ở ngoài này.",
  "The group's too small for anybody to be high-maintenance.": "Nhóm của chúng ta hiện đang quá nhỏ bé để có thể chứa chấp thêm bất kỳ một kẻ đéo nào đòi hỏi sự bảo trì cao (high-maintenance) được nữa đâu.",
  "Hostiles inbound!": "Những kẻ địch thù địch đang lao tới!",
  "8 MIL Cpl B.W. Wilson": "8 QUÂN ĐỘI (MIL) Hạ Sĩ (Cpl) B.W. Wilson",
  "You're more accurate when you're standing still.": "Cậu sẽ bắn chuẩn xác (accurate) hơn rất nhiều khi cậu đứng yên một chỗ.",
  "Field Medic": "Bác Sĩ Quân Y Dã Chiến (Field Medic)",
  "Nobody was dying of a disease. These were accident victims, homicides, heart attacks.": "Đéo có ai phải chết vì một căn bệnh truyền nhiễm (disease) nào cả. Đây đều là những nạn nhân của các vụ tai nạn, các vụ án mạng, hoặc là bị nhồi máu cơ tim (heart attacks).",
  "Mya": "Mya",
  "Just about halfway there.": "Chỉ mới đi được khoảng một nửa chặng đường thôi.",
  "Let's not tell Eldridge.": "Chúng ta đừng nói chuyện này cho Eldridge biết nhé.",
  "This place is full of zeds, and we need help clearing it out.": "Nơi này hiện đang chứa đầy lũ zeds, và chúng tôi đang rất cần có người giúp đỡ để dọn dẹp sạch sẽ nó.",
  "Michele Martin is safe": "Michele Martin hiện đã được an toàn",
  "Ashlyn": "Ashlyn",
  "Research Biodiesel": "Nghiên Cứu Về Nhiên Liệu Sinh Học Biodiesel",
  "Construction Materials": "Các Vật Liệu Xây Dựng (Construction Materials)",
  "It might be a good idea if you trained some of the rest of us.": "Đó có thể sẽ là một ý tưởng rất tuyệt vời nếu như cậu chịu huấn luyện lại cho một số người còn lại trong nhóm của chúng ta đấy.",
  "I found a food supply.": "Tôi đã tìm thấy được một nguồn cung cấp thức ăn (food supply).",
  "Playthrough Score": "Điểm Số Của Lần Chơi Hiện Tại (Playthrough Score)",
  "Wray": "Wray",
  "Never mind.": "Đừng bận tâm về điều đó nữa.",
  "Create a New Profile": "Tạo Mới Một Hồ Sơ (Profile)",
  "Pile of Scrap": "Một Đống Phế Liệu (Scrap)",
  "Rusty Pipe": "Ống Nước Bị Rỉ Sét (Rusty Pipe)",
  "I hear Ray's got you doing favors for him now.": "Tôi nghe nói bây giờ Ray đã bắt cậu phải thực hiện một số yêu cầu của ông ta thì phải.",
  "133 HERO Andy Pimms": "133 ANH HÙNG (HERO) Andy Pimms",
  "Mmmm-hmmm.": "Mmmm-hmmm.",
  "Running one over might not be the best idea either.": "Việc đâm xe trực tiếp vào một trong số bọn chúng có thể cũng đéo phải là một ý tưởng hay ho đéo đâu.",
  "I kept telling her, \"Ma, it's Marshall, not Detroit,\" but she wouldn't listen.": "Tôi đã liên tục nói với bà ấy rằng, \"Mẹ à, đây là Marshall, chứ đéo phải là Detroit đâu,\" nhưng bà ấy đéo thèm lắng nghe.",
  "You cannot switch to someone who is INJURED.": "Bạn đéo thể nào chuyển đổi sang điều khiển một người nào đó đang BỊ THƯƠNG (INJURED).",
  "Shit! We lost a barricade!": "Chết tiệt thật! Chúng ta vừa bị mất đi một cái chướng ngại vật (barricade) cmnr!",
  "EXPIRED: Ally in Trouble": "ĐÃ HẾT HẠN (EXPIRED): Đồng Minh (Ally) Đang Gặp Rắc Rối",
  "THREAT LEVEL HIGH": "MỨC ĐỘ NGUY HIỂM ĐANG Ở MỨC RẤT CAO (HIGH)",
  "Posit one one lima november nine nine india six one oscar. [message end tone]": "Posit one one lima november nine nine india six one oscar. [âm báo kết thúc tin nhắn]",
  "Y'know, some of us are actually trying here. You wanna help?": "Cậu biết đéo, một số người trong chúng tôi đang thực sự rất nỗ lực cố gắng ở đây đấy. Cậu có muốn giúp đỡ đéo?",
  "Got you now!": "Đã tóm được mày rồi!",
  "You already own everything here!": "Hiện tại cậu đã sở hữu tất cả mọi thứ có ở nơi này rồi!",
  "DELAY. Hopefully nothing bad will happen while you decide.": "TRÌ HOÃN (DELAY). Hy vọng rằng sẽ đéo có bất kỳ chuyện tồi tệ nào xảy ra trong lúc bạn đang cân nhắc để đưa ra quyết định.",
  "Time to move, now!": "Đã đến lúc phải di chuyển, ngay bây giờ!",
  "I've been better. Haven't been able to take my meds for a while. The weakness is getting worse.": "Tôi đã từng cảm thấy tốt hơn như thế này rất nhiều. Lâu rồi tôi đéo thể nào uống được các loại thuốc điều trị bệnh của mình nữa. Sự suy nhược (weakness) đang ngày càng trở nên tồi tệ hơn cmnr.",
  "They were fine just a minute ago!": "Bọn họ vẫn còn hoàn toàn ổn cơ mà chỉ mới một phút trước thôi!",
  "So wait. We saved somebody's life, and now we're the bad guys?": "Vậy chờ đã đéo nào. Chúng ta đã cố gắng cứu sống mạng của một người nào đó, và giờ đây chúng ta lại bị coi là những kẻ xấu xa ư?",
  "Steel Pipe Bomb": "Bom Ống Thép (Steel Pipe Bomb)",
  "Pause": "Tạm Dừng (Pause)",
  "Damned if the boys weren't gonna win the pennant this year. (Sports trivia whiz.)": "Chết tiệt thật nếu như những chàng trai đó đéo thể giành được chức vô địch (pennant) trong năm nay. (Chuyên Gia Thể Thao Sports trivia whiz.)",
  "Really? So then what happened between us? Was that real, or were you just having a relapse?": "Thật ư? Vậy thì chính xác những gì đã xảy ra giữa chúng ta là sao? Chuyện đó có phải là sự thật đéo, hay cậu chỉ đang bị tái phát lại bệnh cũ (relapse) mà thôi?",
  "It's not like we have enough fuel to be wasting it like that!": "Đéo phải là hiện tại chúng ta đang có đủ số lượng nhiên liệu (fuel) dư thừa để cho cậu có thể lãng phí chúng một cách vô tội vạ như vậy đâu!",
  "Check six, people!": "Chú ý vị trí 6 giờ kìa, mọi người!",
  "Heads up the church in Spencer's Mill.": "Hãy chú ý đến khu nhà thờ (church) nằm ở Spencer's Mill.",
  "Toss out the gas can!": "Hãy quăng ngay cái can đựng xăng (gas can) đó ra ngoài đi!",
  "6 seconds": "6 giây",
  "Let's clear some zeds and find out.": "Hãy cùng nhau dọn dẹp sạch sẽ lũ zeds và sau đó tìm hiểu xem mọi chuyện là thế nào.",
  "Helped %3$s on a supply run. Provided a safe escort home. - %1$s": "Đã hỗ trợ thành công %3$s trong lúc đang chạy đi thu thập đồ tiếp tế (supply run). Đã cung cấp một sự hộ tống (escort) an toàn trở về nhà. - %1$s",
  "Used to just be a hobby. But out here? Could come in handy.": "Trước đây nó chỉ từng là một sở thích cá nhân mà thôi. Nhưng khi ở ngoài này ư? Nó hoàn toàn có thể trở nên vô cùng hữu ích đấy.",
  "You trading?": "Cậu có muốn tiến hành trao đổi giao dịch (trading) đéo?",
  "Pistol: M11": "Súng Lục (Pistol): M11",
  "Advice: Establish More Outposts": "Lời Khuyên (Advice): Hãy Thiết Lập Thêm Nhiều Các Tiền Đồn (Outposts) Mới",
  "No. It makes perfect sense.": "Đéo đâu. Chuyện đó hoàn toàn có ý nghĩa đấy chứ.",
  "%1$dd; %2$dhr": "%1$d ngày; %2$d giờ",
  "I think Dad would have liked that. Come on, we better get moving.": "Tôi nghĩ là Bố tôi chắc chắn cũng sẽ rất thích điều đó đấy. Thôi nào, tốt hơn hết là chúng ta nên nhanh chóng di chuyển đi thôi.",
  "It's too late to run. We have to stand and fight.": "Đã quá muộn để có thể bỏ chạy cmnr. Chúng ta phải kiên cường đứng lại và chiến đấu thôi.",
  "Hey. Thanks, by the way. You laid it on the line for us. We won't forget that.": "Này. Dù sao thì, cũng xin cảm ơn cậu rất nhiều. Cậu đã đặt tính mạng của bản thân mình vào vòng nguy hiểm vì chúng tôi. Chúng tôi sẽ đéo bao giờ quên đi ân huệ đó đâu.",
  "Old Head Trauma": "Chấn Thương Vùng Đầu Cũ (Old Head Trauma)",
  "The Scholar": "Học Giả (The Scholar)",
  "We could use some help here!": "Chúng tôi thực sự rất cần có người giúp đỡ ở đây!",
  "l think we got this one well in hand.": "Tôi nghĩ là chúng ta đã hoàn toàn nắm chắc phần thắng trong tay đối với chuyện này rồi.",
  "Book on Home Improvement": "Cuốn Sách Nói Về Các Mẹo Cải Tạo Ngôi Nhà (Home Improvement)",
  "Roger that. Maybe one thing will go right today. Doghouse out.": "Đã rõ. Có lẽ sẽ có một điều gì đó diễn ra một cách suôn sẻ trong ngày hôm nay. Doghouse xin hết.",
  "We can't last out here by ourselves. Could we join your group?": "Chúng tôi đéo thể nào tự mình cầm cự được ở ngoài này nữa rồi. Liệu chúng tôi có thể xin gia nhập vào nhóm của cậu được đéo?",
  "Well. We just sort of stayed here after that.": "Chà. Chúng tôi chỉ là đã lựa chọn tiếp tục ở lại nơi này sau khi chuyện đó xảy ra mà thôi.",
  "I don't want to talk about it.": "Tôi đéo muốn phải tiếp tục bàn luận về chuyện đó nữa đâu.",
  "Vinegar": "Giấm (Vinegar)"
};

const file = 'output/languages/chunks/btxt_chunk_195.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_195.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk195[r.sourceText]) {
    r.translatedText = chunk195[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 195 successfully!');
