const fs = require('fs');
const chunk143 = {
  "HOME: Flu Outbreak": "CĂN CỨ: Bùng Phát Cúm",
  "It'd been almost a month. Not a peep from him, and I was coming back from work and I...": "Đã gần một tháng rồi. Đéo có một tiếng động nào từ ông ấy, và khi tôi đi làm về thì tôi...",
  "Eva": "Eva",
  "94 GENERIC Angela Farrell": "94 GENERIC Angela Farrell",
  "Solid Wood Oar": "Mái Chèo Gỗ Đặc",
  "They were carrying supplies and equipment that we need if we want to find a cure.": "Họ đang mang theo nhu yếu phẩm và trang thiết bị mà chúng ta cần nếu chúng ta muốn tìm ra phương thuốc chữa bệnh.",
  "TIP: Press [sprint] + [xi_use] to finish off a downed foe.": "MẸO: Nhấn [sprint] + [xi_use] để kết liễu một kẻ thù đã gục ngã.",
  "Spencer": "Spencer",
  "Good thing we had ammo.": "May mà chúng ta có đạn.",
  "We should be safe for a while now.": "Bây giờ chúng ta sẽ được an toàn trong một thời gian.",
  "Keep them off me, this is going to take a while.": "Giữ chúng tránh xa tôi ra, chuyện này sẽ mất một lúc đấy.",
  "27 GENERIC Tommy Luther": "27 GENERIC Tommy Luther",
  "Negative. We've been coming out there too much lately as it is.": "Từ chối. Gần đây chúng ta đã ra ngoài đó quá nhiều rồi.",
  "Yeah, sure, come by if you're not too fucking busy.": "Ừ, chắc rồi, ghé qua đi nếu cậu đéo quá bận rộn chết tiệt.",
  "Field Promotion": "Thăng Cấp Chiến Trường (Field Promotion)",
  "Distract zombies to complete an objective.": "Đánh lạc hướng lũ zombie để hoàn thành một mục tiêu.",
  "The Bureaucrat": "Kẻ Quan Liêu (The Bureaucrat)",
  "We're gonna have to start using something weaker to make our firebombs.": "Chúng ta sẽ phải bắt đầu sử dụng thứ gì đó yếu hơn để chế tạo bom lửa (firebombs).",
  "Any one of them might mean a million lives saved or lost.": "Bất kỳ thứ nào trong số đó đều có thể đồng nghĩa với việc hàng triệu mạng sống được cứu hoặc bị cướp đi.",
  "It's for the best.": "Đó là vì điều tốt nhất.",
  "Last time anybody saw her, she was hanging out here. Probably the best place to start looking.": "Lần cuối cùng có người nhìn thấy cô ta là lúc cô ta đang quanh quẩn ở đây. Có lẽ đây là nơi tốt nhất để bắt đầu tìm kiếm.",
  "Go ahead, caller.": "Nói đi, người gọi.",
  "Well that was a bust.": "Chà, đúng là xôi hỏng bỏng đéo.",
  "Asthma Attacks": "Cơn Hen Suyễn",
  "Met a man in debt to the Wilkersons. I thought about helping, but we can't spare the ammo. - %1$s": "Gặp một người đang mắc nợ nhà Wilkersons. Tôi đã định giúp, nhưng chúng ta đéo thể lãng phí đạn dược được. - %1$s",
  "THERE'S NO PLACE LIKE IT": "ĐÉO CÓ NƠI NÀO GIỐNG NƠI NÀY (THERE'S NO PLACE LIKE IT)",
  "There they are.": "Chúng kia rồi.",
  "We did. I'm just here to get you on a helicopter.": "Chúng tôi có làm. Tôi chỉ đến đây để đưa cô lên trực thăng thôi.",
  "Irreconcilable Differences": "Những Sự Bất Đồng Khó Giải Quyết",
  "My father took teaching jobs all over the world when I was young. I've had to learn to adapt to whatever comes my way. (Increased Wits)": "Cha tôi đã nhận những công việc giảng dạy trên khắp thế giới khi tôi còn nhỏ. Tôi đã phải học cách thích nghi với bất cứ điều gì xảy đến với mình. (Tăng Trí tuệ)",
  "Shitshitshitshitshit!": "Chết tiệt, chết tiệt, chết tiệt, chết tiệt!",
  "Find a hiding spot.": "Tìm một chỗ trốn.",
  "Let's get you some medical attention.": "Hãy để cậu được chăm sóc y tế.",
  "Don't…don't worry about it, huh? Let's get you to safety.": "Đừng… đừng bận tâm về chuyện đó, nhé? Để tôi đưa cậu đến nơi an toàn đã.",
  "You ain't seen me push somebody yet.": "Cậu vẫn chưa thấy tôi đẩy (push) ai bao giờ đâu.",
  "XP penalty from Absent-Minded.": "Trừ XP do Đãng trí (Absent-Minded).",
  "I honestly thought she was gonna hit me right in the face there.": "Thành thật mà nói, tôi cứ tưởng cô ấy sẽ đánh thẳng vào mặt tôi ngay lúc đó chứ.",
  "Alyssa": "Alyssa",
  "You think we're clear?": "Cậu nghĩ chúng ta đã an toàn (clear) chưa?",
  "We're running pretty low on fuel. Might want to look for more before it becomes a problem.": "Chúng ta sắp cạn nhiên liệu rồi. Có lẽ nên đi tìm thêm trước khi nó trở thành một vấn đề lớn.",
  "Yeah …": "Ừ …",
  "Zombies in the LZ": "Zombie ở Khu Vực Hạ Cánh (LZ)",
  "The opportunity has passed.": "Cơ hội đã vuột mất.",
  "Cinderblocks": "Khối Xỉ Than (Cinderblocks)",
  "Farkas": "Farkas",
  "I was trying to give %1$s a dignified end. I failed. - %2$s": "Tôi đã cố gắng cho %1$s một cái chết đàng hoàng. Tôi đã thất bại. - %2$s",
  "%d Soldiers Rescued": "Đã Giải Cứu %d Binh Sĩ",
  "HOME: No Infirmary": "CĂN CỨ: Không Có Trạm Xá (Infirmary)",
  "Oh! You really came! I ... I just ... oh, my gosh. Thank you.": "Ồ! Cậu thực sự đã đến! Tôi ... tôi chỉ ... ôi, lạy chúa. Cảm ơn cậu.",
  "Now me and my brother, we done pretty well for ourselves in all this. Other folks see that, and, well....": "Giờ thì tôi và anh trai tôi, chúng tôi đã làm khá tốt phần việc của mình trong tất cả những chuyện này. Những người khác cũng thấy điều đó, và, ừ thì....",
  "DECLINE MISSION. Try to talk them out of meeting with the Wilkersons.": "TỪ CHỐI NHIỆM VỤ. Cố gắng thuyết phục họ đừng gặp gỡ bọn Wilkersons.",
  "A 4.6mm converted to 9mm. Optic included.": "Một khẩu 4.6mm được chuyển đổi sang 9mm. Bao gồm cả ống ngắm quang học.",
  "Lily needs special medication or she will die.": "Lily cần loại thuốc đặc biệt nếu đéo cô ấy sẽ chết.",
  "Contact South!": "Mục tiêu (Contact) ở phía Nam!",
  "What, and just leave them here? To be food for those...": "Cái gì, và cứ thế bỏ mặc họ ở đây sao? Để làm thức ăn cho lũ...",
  "Andres": "Andres",
  "Master the use of Revolvers.": "Nắm vững cách sử dụng Súng lục ổ xoay (Revolvers).",
  "How's Ed doing?": "Ed dạo này thế nào rồi?",
  "Abraham": "Abraham",
  "Well, that's a big fat clusterfuck.": "Chà, đúng là một đống rắc rối siêu to khổng lồ (clusterfuck).",
  "Hank": "Hank",
  "Find a way to get along, or the next conversation won't be so friendly.": "Tìm cách mà hòa thuận với nhau đi, nếu đéo cuộc trò chuyện tiếp theo sẽ đéo thân thiện thế này đâu.",
  "We have no more leads on Doctor Horn's associates.": "Chúng ta đéo còn manh mối nào về các cộng sự của Bác sĩ Horn nữa.",
  "PERSONAL SKILL. If there's a deal, I'll find it.": "KỸ NĂNG CÁ NHÂN. Nếu có bất kỳ kèo thơm nào, tôi sẽ tìm ra nó.",
  "Christ, what I wouldn't give for some electric lighting. Maybe a hot shower. We ought to hook up a generator.": "Chúa ơi, tôi có thể đánh đổi mọi thứ để có được chút ánh sáng đèn điện. Hoặc có thể là một vòi sen nước nóng. Chúng ta phải kết nối một máy phát điện mới được.",
  "Thanks for the ride.": "Cảm ơn vì đã cho đi nhờ.",
  "Jensen": "Jensen",
  "We pay all those taxes, and yet all they can afford to send us is a single chopper.": "Chúng ta đóng đủ thứ thuế, vậy mà tất cả những gì bọn họ có thể gửi cho chúng ta chỉ là một chiếc trực thăng chết tiệt.",
  "Model 1100 for police and military use.": "Model 1100 dành cho cảnh sát và quân đội.",
  "It's okay to be freaked out. It just means you're human.": "Cảm thấy sợ hãi cũng đéo sao cả. Điều đó chỉ chứng tỏ cậu là con người thôi.",
  "Brackets": "Chân Đế (Brackets)",
  "I think I'm okay now. Thanks.": "Tôi nghĩ bây giờ tôi ổn rồi. Cảm ơn nhé.",
  "Rifle: 464 Custom 22": "Súng trường: 464 Custom 22",
  "Here's the thing. People can't take constant yelling and abuse.": "Vấn đề là thế này. Mọi người đéo thể chịu đựng được việc liên tục bị la mắng và chửi rủa đâu.",
  "20 Max Vitality and +10 Max Stamina for everyone.": "Cộng 20 Sinh Lực tối đa và +10 Thể Lực tối đa cho mọi người.",
  "%s >= %d": "%s >= %d",
  "This area is a bust.": "Khu vực này hỏng bét rồi.",
  "Medication Aide": "Phụ Tá Y Tế",
  "Guess that temper's working for you, huh?": "Đoán là cái tính nóng nảy đó cũng có ích cho cậu nhỉ?",
  "Load": "Tải",
  "Running Shoes": "Giày Chạy Bộ",
  "71 VIP Narinda Heston": "71 VIP Narinda Heston",
  "All personnel, the last helivac is inbound. Rally at the evac point. You do not want to stay here. Let's go!": "Tất cả nhân sự, trực thăng di tản cuối cùng đang đến. Tập trung tại điểm sơ tán. Các anh sẽ đéo muốn ở lại đây đâu. Đi thôi!",
  "Gotta Enjoy the Little Things": "Phải Biết Tận Hưởng Những Điều Nhỏ Bé Nhất",
  "Shit, half our stock ends up going bad before we can use it. We need a storeroom.": "Chết tiệt, một nửa kho dự trữ của chúng ta bị hỏng trước khi kịp sử dụng. Chúng ta cần một nhà kho (storeroom).",
  "You know what I was known for? My specialty before the... thing?": "Cậu có biết tôi từng nổi tiếng vì điều gì đéo? Chuyên môn của tôi trước cái... thảm họa này ấy?",
  "Help Kilo get some supplies back to base.": "Giúp Kilo mang một ít nhu yếu phẩm về căn cứ.",
  "A new bullpup battle rifle, fitted with an optic for high visibility at range.": "Một khẩu súng trường chiến đấu bullpup mới, được trang bị ống ngắm quang học giúp tăng cường tầm nhìn ở cự ly xa.",
  "Speakers - Mono": "Loa - Đơn âm (Mono)",
  "The painkillers also seem to have taken effect.": "Thuốc giảm đau có vẻ cũng đã phát huy tác dụng rồi.",
  "Stay alert, zeds behind us.": "Cảnh giác nhé, có zed ở đằng sau chúng ta đấy.",
  "Are you kidding me? I was ready before it was cool, man.": "Cậu đùa tôi à? Tôi đã sẵn sàng từ trước khi việc này trở nên ngầu cơ, bạn hiền.",
  "You wanna get out of this mess alive? I suggest you send me a fucking extraction!": "Mấy người muốn thoát khỏi mớ hỗn độn này mà vẫn còn sống đéo? Tôi khuyên mấy người nên gửi cho tôi một đội cứu hộ chết tiệt đi!",
  "49 GENERIC Gilbert Wingate": "49 GENERIC Gilbert Wingate",
  "Danforth County medical examiner. Recently in contact with Thomas Horn.": "Bác sĩ pháp y của Quận Danforth. Gần đây có liên lạc với Thomas Horn.",
  "Is it me, or are people really slow to trust us lately?": "Do tôi, hay là dạo này mọi người thực sự rất chậm trễ trong việc tin tưởng chúng ta?",
  "Oh, shit. We're screwed. We're screwed.": "Ôi, chết tiệt. Chúng ta tiêu rồi. Chúng ta chết chắc rồi.",
  "ADVICE: Upgrade to Munitions Shop": "LỜI KHUYÊN: Nâng Cấp Lên Xưởng Đạn Dược (Munitions Shop)",
  "30 MIL Sgt Nikki Gallagher": "30 MIL Sgt Nikki Gallagher",
  "I'm begging you. Put me out of my misery, ok? It'll be worse for everybody if you don't.": "Tôi cầu xin cậu đấy. Hãy giải thoát cho tôi khỏi sự đau đớn này, được đéo? Mọi chuyện sẽ tồi tệ hơn cho tất cả mọi người nếu cậu đéo làm vậy."
};

const file = 'output/languages/chunks/btxt_chunk_143.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_143.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk143[r.sourceText]) {
    r.translatedText = chunk143[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 143 successfully!');
