const fs = require('fs');
const chunk153 = {
  "New Base! Take some time to explore. Open the Journal to build and upgrade your facilities.": "Căn Cứ Mới! Dành chút thời gian để khám phá nhé. Mở Nhật ký (Journal) để xây dựng và nâng cấp các cơ sở vật chất của bạn.",
  "REWARD. A collection of heavy tools used by fire and rescue services, delivered directly to your Supply Locker.": "PHẦN THƯỞNG. Một bộ công cụ hạng nặng được sử dụng bởi các dịch vụ cứu hỏa và cứu hộ, được giao trực tiếp vào Tủ Đồ Tiếp Tế (Supply Locker) của bạn.",
  "Ready for what, exactly?": "Sẵn sàng cho chuyện gì, chính xác là vậy?",
  "Derek": "Derek",
  "Might be, yeah.": "Có lẽ vậy, ừ.",
  "Need assistance!": "Cần hỗ trợ!",
  "Sir, we're sending you her husband's notes. Reams of them. It's the best we could do.": "Thưa ngài, chúng tôi đang gửi cho ngài những ghi chép của chồng cô ấy. Cả một đống lớn. Đó là những gì tốt nhất mà chúng tôi có thể làm.",
  "Somehow I'll make it the rest of the way without you.": "Bằng cách nào đó tôi sẽ đi nốt phần đời còn lại đéo có cô.",
  "Now, you might ask yourself, \"Where's my army? Where's my airlift?\"": "Giờ thì, mấy người có thể tự hỏi, \"Quân đội của tôi đâu? Lực lượng không vận của tôi đâu?\"",
  "Doghouse is out of commission. But if you've got sat-comms, you can reach Highroad, out near the state capital.": "Doghouse đã ngừng hoạt động. Nhưng nếu cậu có thiết bị liên lạc vệ tinh (sat-comms), cậu có thể liên lạc với Highroad, ở gần thủ phủ của bang.",
  "It started, what, 12, 13 days ago? At first it was just weird stories on the news.": "Nó bắt đầu từ khi nào nhỉ, 12, 13 ngày trước sao? Lúc đầu đó chỉ là những câu chuyện kỳ lạ trên bản tin.",
  "Oh, right. 'Cause, like, I am, like, literally starving!": "Ồ, phải rồi. Vì, kiểu như, tôi đang, chết đói theo đúng nghĩa đen luôn rồi đây này!",
  "I should save this til I need an energy boost.": "Tôi nên cất thứ này cho đến khi cần tăng cường năng lượng.",
  "Uh... shit. Make that a lot of zombies harassing our guys.": "Uh... cứt thật. Có vẻ như là có rất nhiều zombie đang quấy nhiễu người của chúng ta.",
  "Sir, he'll need a medic when he arrives. But he's got his daughter with him. I think she'll get him through it.": "Thưa ngài, ông ấy sẽ cần một bác sĩ khi đến nơi. Nhưng ông ấy có con gái đi cùng. Tôi nghĩ cô bé sẽ giúp ông ấy vượt qua được chuyện này.",
  "I'm looking for one of our people.": "Tôi đang tìm một người của chúng ta.",
  "Teach %3$s a trick or two.": "Dạy cho %3$s một hai ngón đòn.",
  "I think we can set up some surprises for the zeds.": "Tôi nghĩ chúng ta có thể thiết lập vài bất ngờ nhỏ cho lũ zed.",
  "Just came to Trumbull Valley for a vacation.": "Chỉ đến Thung lũng Trumbull để nghỉ mát thôi.",
  "122 HERO Pastor William": "122 ANH HÙNG (HERO) Mục Sư William",
  "Are we done here? We're done here.": "Chúng ta xong việc ở đây chưa? Xong rồi đấy.",
  "Oh no...": "Ôi đéo...",
  "I think we can take out the worst threat.": "Tôi nghĩ chúng ta có thể loại trừ mối đe dọa tồi tệ nhất.",
  "Load off my mind.": "Trút được gánh nặng trong lòng.",
  "The Mother": "Người Mẹ",
  "START MISSION. Hear what Alan has to say.": "BẮT ĐẦU NHIỆM VỤ. Lắng nghe những gì Alan muốn nói.",
  "Shootist": "Xạ Thủ (Shootist)",
  "ADVICE: Build an Infirmary": "LỜI KHUYÊN: Hãy Xây Dựng Một Bệnh Xá (Infirmary)",
  "Nah. Let her cool down. She'll come around eventually.": "Đéo. Cứ để cô ấy bình tĩnh lại đã. Cuối cùng thì cô ấy cũng sẽ nguôi ngoai thôi.",
  "Thank you for getting me out of there. I thought I was dead.": "Cảm ơn vì đã đưa tôi ra khỏi đó. Tôi đã tưởng mình tiêu cmnr.",
  "So what do you say?": "Vậy cậu tính sao?",
  "I'm just looking out for number #1. You got a problem with that? (Improved wits.)": "Tôi chỉ lo cho bản thân mình thôi. Cậu có vấn đề gì với điều đó đéo? (Cải thiện trí tuệ - wits.)",
  "Liked to Sew": "Từng Thích May Vá",
  "This ain't going to be quick.": "Chuyện này đéo nhanh đâu.",
  "Down boy!": "Nằm xuống, cún cưng!",
  "DANGER: Feral Sighting": "NGUY HIỂM: Phát hiện Feral",
  "Laine": "Laine",
  "Trust Gain Rate Increased!": "Tốc Độ Tăng Niềm Tin Được Tăng Lên!",
  "Things actually seem pretty calm out there for once.": "Lần hiếm hoi mọi thứ ngoài kia dường như lại khá yên tĩnh.",
  "One of those creepy, fast bastards was spotted. We need to end this fucker now! -%2$s": "Một trong những thằng khốn nhanh nhẹn, rùng rợn đó vừa bị phát hiện. Chúng ta cần phải kết liễu cái thằng chó này ngay lập tức! -%2$s",
  "Bradley": "Bradley",
  "They're not here. We are. And we gotta think about what comes next.": "Họ đéo có ở đây. Chúng ta thì có. Và chúng ta phải nghĩ xem chuyện gì sẽ xảy ra tiếp theo.",
  "113 HERO Lincoln Voss": "113 ANH HÙNG (HERO) Lincoln Voss",
  "Genesis": "Genesis",
  "Well, thank you very much for the info. Guess I've got a decision to make.": "Chà, cảm ơn rất nhiều vì thông tin. Đoán là tôi phải đưa ra quyết định rồi.",
  "+10 Max Vitality for everyone. 15% Recovery Chance from injury/illness each day.": "Tăng 10 Sinh lực Tối đa (Max Vitality) cho mọi người. 15% Cơ hội Hồi phục chấn thương/bệnh tật mỗi ngày.",
  "I'm in trouble!": "Tôi đang gặp rắc rối!",
  "Just get us inside.": "Chỉ cần đưa chúng tôi vào trong thôi.",
  "I need some SWAT support here!": "Tôi cần một số hỗ trợ từ lực lượng SWAT ở đây!",
  "Back off. I don't have time for this shit.": "Lùi lại đi. Tôi đéo có thời gian cho cái mớ rác rưởi này đâu.",
  "Damn, you were kickin' ass and takin' names!": "Chết tiệt, cậu vừa đấm cho bọn chúng sấp mặt và cho bọn chúng biết tay đấy!",
  "Luther": "Luther",
  "Hey, thanks. I owe you one.": "Này, cảm ơn nhé. Tôi nợ cậu một lần.",
  "Dear Diary, HOLY SHIT IT WORKED! When Skyler said he found a ritual that could bend the dead to our black wills and finally take revenge on assholes like Ricky Valdez I kinda thought he was full of shit, but IT WORKED! It's all over the news, the dead are rising from the grave to eat the flesh of the living! BRB, I'm going to try out my sweet zombie-controlling powers!": "Nhật ký thân mến, CÁI ĐỊT MẸ NÓ HOẠT ĐỘNG THẬT NÀY! Khi Skyler nói anh ấy tìm thấy một nghi thức có thể bẻ cong ý chí của người chết để phục tùng sự đen tối của bọn tôi và cuối cùng thì trả thù những thằng khốn như Ricky Valdez, tôi đã nghĩ anh ấy đang nói xạo lồn, nhưng NÓ HOẠT ĐỘNG THẬT ĐẤY! Chuyện đó tràn ngập trên các bản tin, những người chết đang đội mồ sống dậy để ăn thịt người sống! Chút nữa quay lại nhé (BRB), tôi sẽ đi thử nghiệm sức mạnh điều khiển zombie tuyệt vời của mình đây!",
  "Can we get the hell out of here and get eaten on the open road already?": "Chúng ta có thể nhanh chóng cút khỏi đây và để bị ăn thịt ở trên đường đéo?",
  "I've got to wonder if the strain of leadership is getting to Her Honor. I mean, hell, it'd get to anybody.": "Tôi phải tự hỏi liệu áp lực lãnh đạo có đang đổ lên đầu Thẩm phán hay đéo. Ý tôi là, chết tiệt, nó sẽ ảnh hưởng đến bất cứ ai.",
  "Football Star": "Ngôi Sao Bóng Bầu Dục",
  "You need me to walk you to the door?": "Cậu có cần tôi tiễn cậu ra cửa đéo?",
  "Studied the Occult": "Từng Nghiên Cứu Tâm Linh (Occult)",
  "Aspirin": "Aspirin",
  "DECLINE MISSION. Piss off the Wilkersons but avoid any more entanglements.": "TỪ CHỐI NHIỆM VỤ. Chọc giận nhà Wilkersons nhưng tránh được thêm những rắc rối.",
  "Kanabo": "Gậy Kanabo",
  "Camouflaged pump hunting shotgun.": "Súng săn (shotgun) bắn đạn ghém được ngụy trang.",
  "Newcomers": "Những Người Mới Đến (Newcomers)",
  "Assault Rifle: Vz. 58 P": "Súng Trường Tấn Công: Súng Vz. 58 P",
  "Rescued Doc": "Đã Giải Cứu Bác Sĩ",
  "Nah, I'm good.": "Đéo, tôi ổn.",
  "Small-caliber rounds for pistols, revolvers, rifles, and SMGs.": "Đạn cỡ nhỏ dùng cho súng lục, súng côn, súng trường và súng tiểu liên.",
  "Sorry, you're on your own.": "Xin lỗi, cậu phải tự lo liệu thôi.",
  "Juliana": "Juliana",
  "God, that thing fucking reeks!": "Chúa ơi, cái thứ chết tiệt đó hôi thối vãi lồn!",
  "Holy shit, don't shoot!": "Vãi lồn, đừng bắn!",
  "Kill one of each freak zombie type with your car.": "Giết mỗi loại zombie quái nhân (freak) một con bằng xe của bạn.",
  "LMG: L86 LSW": "Súng Máy Hạng Nhẹ (LMG): Súng Máy L86 LSW",
  "Black Friday, this is . Engaging large group of hostiles. -assistance immediately.": "Black Friday, đây là . Đang giao tranh với một nhóm lớn kẻ địch. -hỗ trợ ngay lập tức.",
  "Hey, nice work out there!": "Này, làm tốt lắm!",
  "Has something has gone wrong with the chain of command? Because I know the army has officially pulled out of Danforth.": "Có chuyện gì đéo ổn xảy ra với chuỗi chỉ huy sao? Bởi vì tôi biết quân đội đã chính thức rút khỏi Danforth rồi.",
  "Radio contact with St. Louis has been lost.\r\nReports of nuclear activity in the city are unconfirmed at this time.": "Đã mất liên lạc vô tuyến với St. Louis.\r\nCác báo cáo về hoạt động hạt nhân trong thành phố hiện vẫn chưa được xác nhận.",
  "It's surprisingly hard to cultivate patience and understanding when you're caroming from crisis to crisis.": "Sẽ rất khó khăn một cách đáng ngạc nhiên để rèn luyện sự kiên nhẫn và thấu hiểu khi bạn cứ phải chạy vạy từ cuộc khủng hoảng này sang cuộc khủng hoảng khác.",
  "I got him, Lily. We're on our way home.": "Tôi tìm thấy ông ấy rồi, Lily. Chúng tôi đang trên đường về nhà đây.",
  "Hey, I just got a report from some folks just outside Spencer's Mill.": "Này, tôi vừa nhận được báo cáo từ vài người ở ngay ngoại ô Spencer's Mill.",
  "Ryan": "Ryan",
  "Vienna Cho here. The station generator is running and the doors are blocked, so I can hold out for a while ...": "Vienna Cho đây. Máy phát điện của đài vẫn đang chạy và các cánh cửa đã bị chặn, nên tôi có thể trụ được một thời gian ...",
  "You have a new Home! Press [ul_journal_menu] to open your Journal and view your Stockpiles and Possessions on the Assets page.": "Bạn đã có Căn cứ Mới! Nhấn [ul_journal_menu] để mở Nhật ký của bạn và xem Kho dự trữ và Tài sản của bạn trên trang Tài sản (Assets).",
  "Choose Facility": "Chọn Cơ Sở Vật Chất (Facility)",
  "You done good.": "Cậu làm tốt lắm.",
  "Materials Drop": "Đợt Thả Vật Liệu (Materials)",
  "Like, why aren't they taking these people to a hospital or something?": "Kiểu như, tại sao họ đéo đưa những người này đến bệnh viện hay đại loại thế?",
  "Digging a latrine will make a huge difference to our sanitation problem.": "Đào một cái nhà xí (latrine) sẽ tạo ra sự khác biệt lớn đối với vấn đề vệ sinh của chúng ta.",
  "Memento": "Kỷ Vật",
  "News flash: if you get sick, we don't have the meds to help you.": "Bản tin đặc biệt đây: nếu cậu bị ốm, chúng ta đéo có thuốc để chữa cho cậu đâu.",
  "I... I think I'm going to be sick. You've never seen so much blood. - Lily": "Tôi... Tôi nghĩ tôi sắp phát ốm rồi. Cậu chưa bao giờ nhìn thấy nhiều máu đến thế đâu. - Lily",
  "Jodie Hastert": "Jodie Hastert",
  "Good stuff!": "Tuyệt vời!",
  "NUCLEAR EXPLOSION IMMINENT": "VỤ NỔ HẠT NHÂN SẮP XẢY RA",
  "Lots of zeds right behind me.": "Có rất nhiều zed đang bám sát tôi.",
  "And uh, speaking of pulling together... I wonder if you wouldn't be able to do me a favor?": "Và uh, nhân tiện nói về việc sát cánh cùng nhau... Tôi tự hỏi liệu cậu có thể giúp tôi một việc đéo?",
  "Seems like you never go for the quick kill.": "Có vẻ như cậu đéo bao giờ chọn cách kết liễu nhanh chóng cả.",
  "This looks like the sort of place that would make a good home.": "Nơi này có vẻ giống như một chỗ lý tưởng để làm nhà đấy.",
  "Black Friday, we're trying to determine whether this \"Cleo\" is specifically targeting our operation.": "Black Friday, chúng tôi đang cố gắng xác định xem liệu \"Cleo\" này có đang cố tình nhắm vào hoạt động của chúng ta hay đéo."
};

const file = 'output/languages/chunks/btxt_chunk_153.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_153.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk153[r.sourceText]) {
    r.translatedText = chunk153[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 153 successfully!');
