const fs = require('fs');
const chunk166 = {
  "Problem Solved": "Đã Giải Quyết Vấn Đề",
  "Andrews": "Andrews",
  "Teased in School": "Từng Bị Trêu Chọc Ở Trường",
  "2 GENERIC Sally Jo Harrison": "2 CHUNG (GENERIC) Sally Jo Harrison",
  "Negative on the relocation for now.": "Hiện tại thì đéo đồng ý việc di dời.",
  "People used to hide when they saw me coming. You believe that? Grown-ass men and women, hiding from Santa Claus.": "Người ta từng trốn đi khi thấy tôi đến. Cậu tin được đéo? Những gã đàn ông và phụ nữ trưởng thành cmnr, lại đi trốn Ông già Noel.",
  "He'd kill me if he knew I said this, but... I swear I saw tears in his eyes.": "Anh ấy sẽ giết tôi mất nếu biết tôi nói ra điều này, nhưng... tôi thề là tôi đã nhìn thấy những giọt nước mắt trong đôi mắt anh ấy.",
  "Kirkman Residence": "Khu Dân Cư Kirkman",
  "Veterinary Clinic": "Phòng Khám Thú Y",
  "Set Up Machine Shop": "Thiết Lập Xưởng Cơ Khí (Machine Shop)",
  "Lily's brother is in trouble. Maybe if I bail him out it'll earn us some points. -%1$s": "Anh trai của Lily đang gặp rắc rối. Có lẽ nếu tôi cứu anh ta ra, điều đó sẽ giúp chúng ta kiếm được chút điểm tín nhiệm. -%1$s",
  "Small Backpack": "Balo Nhỏ (Small Backpack)",
  "This isn't the time for a little casual reading.": "Đây đéo phải lúc cho việc đọc sách thư giãn đâu.",
  "New Radio Option Gained": "Đã Có Thêm Tùy Chọn Radio Mới",
  "New facility is coming on line, ma'am.": "Cơ sở mới (facility) sắp đi vào hoạt động rồi, thưa cô.",
  "Noane": "Noane",
  "Well, there's a lucky break.": "Chà, đúng là một cơ may.",
  "Fled from a horde. Now missing.": "Đã bỏ chạy khỏi một bầy horde. Bây giờ đang mất tích.",
  "My own kids left home years ago, and I guess now I think of everyone in town as my children.": "Những đứa con của tôi đã rời nhà từ nhiều năm trước, và tôi đoán bây giờ tôi coi mọi người trong thị trấn như những đứa con của mình.",
  "Military Stash": "Kho Dự Trữ Quân Sự (Military Stash)",
  "Yeah, and if we gotta deal with any zombie trout, you'll be the first motherfucker I call.": "Ừ, và nếu chúng ta phải đối phó với bất kỳ con cá hồi zombie nào, cậu sẽ là thằng khốn đầu tiên tôi gọi đấy.",
  "Requesting artillery support, on my mark.": "Yêu cầu pháo binh hỗ trợ, chuẩn bị bắn theo hiệu lệnh của tôi.",
  "Gotta go, gotta go now!": "Phải đi thôi, phải đi ngay bây giờ!",
  "Eat this!": "Ăn kẹo đồng đi!",
  "Let this be a lesson to those Wilkerson boys and anyone else who would prey on their fellow survivors": "Hãy coi đây là một bài học cho mấy gã nhà Wilkerson và bất cứ kẻ nào khác có ý định trục lợi từ những người sống sót đồng bào của mình",
  "Noobsauce. Total noobsauce.": "Gà mờ. Đúng là một lũ gà mờ.",
  "Suarez": "Suarez",
  "Civilians are getting restless. I don't like it.": "Dân thường đang bắt đầu bồn chồn rồi. Tôi đéo thích điều đó.",
  "Didn't murder unarmed civilians. That doesn't exactly make him a hero.": "Việc đéo sát hại dân thường tay đéo tấc sắt đéo thực sự khiến hắn trở thành một anh hùng đâu.",
  "Brew some coffee, to keep our scavengers awake and alert.": "Pha chút cà phê, để giữ cho những người đi nhặt rác (scavengers) của chúng ta tỉnh táo và cảnh giác.",
  "Posit one one lima november nine nine echo six one november. [message end tone]": "Xác định vị trí một một lima november chín chín echo sáu một november. [âm báo kết thúc tin nhắn]",
  "Succinctly put. Now, it's been a while since I've read my field survival manual, but I'm pretty sure dead guys rotting in your water supply is what's known as a bad thing.": "Nói ngắn gọn thế này. Đã lâu rồi tôi đéo đọc cẩm nang sinh tồn thực địa của mình, nhưng tôi khá chắc rằng việc có những xác chết thối rữa trong nguồn nước của cậu được coi là một điều đéo hề tốt đẹp chút nào.",
  "Remember when the army was still dropping emergency supplies?": "Còn nhớ khi quân đội vẫn thả hàng cứu trợ khẩn cấp (emergency supplies) đéo?",
  "Gun Shop": "Cửa Hàng Súng",
  "Incoming. Clear the area!": "Mục tiêu đang tới. Dọn dẹp khu vực!",
  "We've got a bit of a problem out there.": "Chúng ta có một chút vấn đề ở ngoài kia rồi.",
  "Numbs the pain, but won't help serious wounds. Typical over-the-counter stuff. Tastes like ass, but knocks out just about anything.": "Làm dịu cơn đau, nhưng sẽ đéo giúp ích gì cho những vết thương nghiêm trọng. Loại thuốc đéo kê đơn điển hình. Vị như cức, nhưng có thể đánh gục hầu hết mọi thứ.",
  "Not really. The occasional squabble over resources, and y'know, we saw some riots in the first couple of days.": "Đéo hẳn vậy. Thỉnh thoảng có vài trận cãi vã tranh giành tài nguyên, và cậu biết đấy, chúng ta đã chứng kiến một vài cuộc bạo động trong vài ngày đầu tiên.",
  "Even potential criminals deserve to live.": "Thậm chí cả những kẻ có khả năng trở thành tội phạm cũng xứng đáng được sống.",
  "That's what made Marshall great, and it's what made America great.": "Đó là những gì đã làm nên sự vĩ đại của Marshall, và là những gì đã làm nên sự vĩ đại của nước Mỹ.",
  "Well, looks like we're not evicted, yet. Keeping an eye on Alan though. -%1$s": "Chà, có vẻ như chúng ta vẫn chưa bị đuổi. Tuy nhiên, tôi vẫn đang để mắt tới Alan. -%1$s",
  "TRUST GAINED (Rescue)": "ĐÃ KIẾM ĐƯỢC ĐIỂM TÍN NHIỆM (TRUST GAINED) - (Giải Cứu)",
  "Then why on earth would you think I'm interested? I need brain tissue samples, and I need them yesterday!": "Vậy tại sao cậu lại nghĩ là tôi có hứng thú cơ chứ? Tôi cần các mẫu mô não, và tôi cần chúng từ hôm qua rồi!",
  "We're gonna need some food to stay alive out here.": "Chúng ta sẽ cần một ít thức ăn để tiếp tục sống sót ngoài này.",
  "That's all to see this time.": "Lần này chỉ có thế thôi.",
  "A meathead who's more concerned about the lack of football than he is about the zombies.": "Một thằng đần (meathead) lo lắng về việc thiếu các trận bóng đá hơn là lo sợ bọn zombies.",
  "Mona": "Mona",
  "I really just have no idea what to do right now.": "Tôi thực sự đéo biết phải làm cái quái gì bây giờ nữa.",
  "Anyways. Now's the time to get tough and get going. You can do it.": "Dù sao thì. Bây giờ là lúc phải trở nên cứng cỏi và tiếp tục bước đi. Cậu có thể làm được mà.",
  "[message looping tone] One one lima november nine nine india six one oscar.": "[âm báo tin nhắn lặp lại] Một một lima november chín chín india sáu một oscar.",
  "This right here? Why you should listen to me.": "Lý do ngay đây? Đó là tại sao các người nên lắng nghe tao.",
  "SitRep: Philadelphia": "Báo cáo Tình hình (SitRep): Philadelphia",
  "Start a Scenario at Breakdown Level 2.": "Bắt đầu một Kịch bản (Scenario) ở mức Breakdown Cấp độ 2.",
  "This way.": "Lối này.",
  "If you need to resupply before you head out check the locker.": "Nếu cậu cần tiếp tế trước khi lên đường, hãy kiểm tra tủ đồ (locker).",
  "Crisis averted.": "Cuộc khủng hoảng đã được ngăn chặn.",
  "Determined to survive.": "Quyết tâm sống sót.",
  "LOG: Doctor Horn Located": "NHẬT KÝ (LOG): Đã định vị được Tiến sĩ Horn",
  "Liked Gardening": "Thích Làm Vườn (Liked Gardening)",
  "Brewster": "Brewster",
  "Everyone is still sore from the last set.": "Mọi người vẫn còn đau nhức sau hiệp tập vừa rồi.",
  "Back/Pause": "Quay lại/Tạm dừng",
  "Hey look, I can load up whenever you want. We'll just get going.": "Này nghe đây, tôi có thể mang vác đồ đạc (load up) bất cứ khi nào cậu muốn. Chúng ta sẽ bắt đầu khởi hành thôi.",
  "Head into town.": "Tiến vào thị trấn.",
  "Anybody else notice how %1$s just seems to stay calm no matter what? Maybe it should worry me, but I actually find it kind of reassuring. - %2$s": "Có ai khác nhận ra rằng %1$s dường như luôn giữ bình tĩnh bất kể có chuyện gì xảy ra đéo? Có lẽ điều đó nên làm tôi lo lắng, nhưng thực ra tôi lại thấy khá yên tâm. - %2$s",
  "%1$s led the way.": "%1$s đã dẫn đường.",
  "Trait Discovered: Priorities": "Đã Khám Phá Được Đặc Điểm (Trait): Các Ưu Tiên (Priorities)",
  "Click in on [camera] to toggle zoom with scoped weapons.": "Nhấp vào [camera] để bật/tắt chế độ thu phóng (zoom) đối với các loại vũ khí có ống ngắm.",
  "Ew! No.": "Eo ôi! Đéo.",
  "I've got a lead on some supplies.": "Tôi có manh mối về một số nhu yếu phẩm (supplies).",
  "Target Snap Distance": "Khoảng cách ngắm tự động (Target Snap)",
  "Something just came in over the radio.": "Có tin gì đó vừa được báo qua radio.",
  "Dante": "Dante",
  "Ammo": "Đạn Dược (Ammo)",
  "Milo Eldridge": "Milo Eldridge",
  "The Commander": "Người Chỉ Huy",
  "The import process failed for some reason. You may be suffering connectivity issues, or the file itself may be corrupted.": "Quá trình nhập dữ liệu (import) đã thất bại vì một lý do nào đó. Bạn có thể đang gặp sự cố kết nối hoặc bản thân tập tin có thể đã bị hỏng.",
  "Microphone Stand": "Chân Đế Micro",
  "Looks like trouble heading our way.": "Có vẻ như rắc rối đang hướng về phía chúng ta.",
  "Shit, that feels great. Thanks, doc.": "Chết tiệt, cảm giác thật tuyệt. Cảm ơn, doc.",
  "Follows player around, even outside of missions.": "Theo sau người chơi đi khắp nơi, ngay cả khi đéo làm nhiệm vụ.",
  "EXTRACTED: Hadley Westen": "ĐÃ GIẢI CỨU (EXTRACTED): Hadley Westen",
  "Wolf Sword": "Thanh Kiếm Sói (Wolf Sword)",
  "There you go.": "Của cậu đây.",
  "SitRep: Local Update #1": "Báo cáo Tình hình (SitRep): Cập nhật Địa phương #1",
  "Controller Sensitivity": "Độ nhạy Tay cầm",
  "Whenever you’re ready, I’ll pack up the radio and go.": "Bất cứ khi nào cậu sẵn sàng, tôi sẽ thu dọn radio và rời đi.",
  "Hates this town and everyone in it. Posers.": "Căm ghét cái thị trấn này và mọi kẻ trong đó. Lũ làm màu.",
  "Boxes of Medications": "Những Hộp Thuốc (Medications)",
  "Madison Grant was Thomas Horn's graduate assistant and close confidante. If anyone can decipher the notes he left behind, it's her.": "Madison Grant từng là trợ lý cao học và là người bạn tâm giao thân thiết của Thomas Horn. Nếu có ai có thể giải mã được những ghi chép mà ông ấy để lại, thì đó chính là cô ấy.",
  "Pico": "Pico",
  "A package of lifesaving supplies, including food and medicine.": "Một gói nhu yếu phẩm cứu mạng, bao gồm thức ăn và thuốc men.",
  "Might want to start here. She always did love the place. I think her parents owned it.": "Có thể sẽ muốn bắt đầu từ đây. Cô ấy luôn yêu thích nơi này. Tôi nghĩ cha mẹ cô ấy là chủ sở hữu của nó.",
  "Graphics - Ultra Spec": "Đồ Họa (Graphics) - Thông số Siêu Cao (Ultra Spec)",
  "Zeds are inside the south gate!": "Bọn zeds đã vào được bên trong cổng phía nam rồi!",
  "Koppel": "Koppel",
  "That guy was just as tough as you'd fear... and faster than you'd expect. - %1$s": "Gã đó vừa mạnh mẽ như những gì cậu lo sợ... vừa nhanh nhẹn hơn những gì cậu có thể tưởng tượng đấy. - %1$s",
  "Part of the job description.": "Một phần của bản mô tả công việc thôi.",
  "RECOVERY: I'm back, baby!": "ĐÃ BÌNH PHỤC (RECOVERY): Tôi đã trở lại rồi đây, cưng ơi!",
  "The kind of leader that everyone loves to serve. Puts the needs of individuals first, and their own goals second.": "Một kiểu lãnh đạo mà mọi người đều yêu thích để phục vụ. Luôn đặt nhu cầu của các cá nhân lên hàng đầu, và mục tiêu của bản thân ở vị trí thứ hai."
};

const file = 'output/languages/chunks/btxt_chunk_166.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_166.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk166[r.sourceText]) {
    r.translatedText = chunk166[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 166 successfully!');
