const fs = require('fs');
const chunk175 = {
  "Black Friday, this whole operation is looking worse by the minute, and I'm almost ready to pull you out.": "Black Friday, toàn bộ chiến dịch này đang có vẻ tồi tệ đi theo từng phút, và tôi gần như đã sẵn sàng để rút các anh ra khỏi đây rồi.",
  "Zombies? Are you fucking kidding me?": "Zombies sao? Cậu đang đùa giỡn chết tiệt với tôi đấy à?",
  "Performed 50 Zombie Executions at Breakdown Level 3 or Higher.": "Đã thực hiện 50 Pha Hành Quyết (Executions) Zombies ở Breakdown Cấp Độ 3 hoặc Cao Hơn.",
  "So tell me about this nuke you've got. You going to blow us all up?": "Vậy hãy nói cho tôi nghe về cái vũ khí hạt nhân (nuke) mà các người đang có đi. Các người định thổi bay tất cả chúng tôi sao?",
  "Haven't seen much of the Army these days. Have you heard anything?": "Dạo này đéo thấy bóng dáng Quân Đội nhiều lắm. Cậu có nghe ngóng được tin tức gì đéo?",
  "Okay. Now we're going to go kill some zombies the old-fashioned way.": "Được rồi. Bây giờ chúng ta sẽ đi giết một vài con zombies theo cách truyền thống cũ (old-fashioned way).",
  "Use a firecracker to draw zombie attention to an area.": "Sử dụng một quả pháo nổ (firecracker) để thu hút sự chú ý của zombie đến một khu vực.",
  "I can hardly walk with this leg. Fucking bullshit.": "Tôi gần như đéo thể đi lại được với cái chân này. Đúng là tào lao nhảm nhí (bullshit) chết tiệt.",
  "Well, I'm not exactly seeing the light at the end of the tunnel, if that's what you mean.": "Chà, tôi cũng đéo hẳn là đang nhìn thấy ánh sáng le lói cuối đường hầm đâu, nếu đó là ý của cậu.",
  "46 GENERIC Keri Florence": "46 CHUNG (GENERIC) Keri Florence",
  "If you'd let me start training them I'd-": "Nếu cậu để tôi bắt đầu huấn luyện họ thì tôi đã-",
  "Hey, anybody seen Eldridge?": "Này, có ai nhìn thấy Eldridge đéo?",
  "And now we have zombies on our right.": "Và bây giờ chúng ta có bọn zombies ở bên phải.",
  "No problems to report, back soon.": "Đéo có vấn đề gì để báo cáo cả, sẽ quay lại sớm.",
  "Now's good for me, if you're ready.": "Bây giờ là lúc thích hợp với tôi, nếu cậu đã sẵn sàng.",
  "Almost. Just a second more.": "Gần xong rồi. Chỉ một giây nữa thôi.",
  "Survivors need 1 Material to maintain an Outpost. In exchange, they return with 3 of whichever resource the Outpost contains.": "Những người sống sót cần 1 Vật Liệu (Material) để duy trì một Tiền Đồn (Outpost). Đổi lại, họ sẽ mang về 3 đơn vị tài nguyên bất kỳ mà Tiền Đồn đó có chứa.",
  "I feel like we're going in circles trying to avoid the zeds.": "Tôi cảm thấy như chúng ta đang đi loanh quanh trong một vòng luẩn quẩn để cố gắng lẩn tránh lũ zeds vậy.",
  "Okay, now try to listen this time. We go forward on foot.": "Được rồi, bây giờ hãy cố gắng lắng nghe lần này nhé. Chúng ta sẽ tiến lên phía trước bằng cách đi bộ.",
  "Low Slice": "Cú Chém Thấp (Low Slice)",
  "Jesus. This is like a war zone.": "Chúa ơi. Nơi này trông giống hệt như một bãi chiến trường vậy.",
  "Rich": "Rich",
  "I don't want to name names or anything, but... we've got some out-of-shape people around here.": "Tôi đéo muốn chỉ đích danh hay ám chỉ bất cứ điều gì cả, nhưng... chúng ta đang có một vài người đéo đủ thể lực (out-of-shape) ở quanh đây đấy.",
  "Great. Now we got screamers.": "Tuyệt vời. Bây giờ chúng ta lại có thêm cả bọn screamers (những kẻ la hét).",
  "I hear you could use a little practice.": "Tôi nghe nói cậu có thể cần thực hành luyện tập thêm một chút đấy.",
  "If you're willing to help, we could wipe out this infestation.": "Nếu cậu sẵn lòng giúp đỡ, chúng ta có thể quét sạch cái ổ dịch (infestation) này.",
  "Head Home": "Hướng Về Nhà (Head Home)",
  "Paige": "Paige",
  "It's so fucking unfair! I am not going to die like this.": "Chuyện này thật quá đỗi chết tiệt đéo công bằng chút nào! Tôi sẽ đéo chết như thế này đâu.",
  "Powder Scale": "Cân Cân Thuốc Súng (Powder Scale)",
  "Thin the Herd: Excellent Work": "Tỉa Bớt Bầy Đàn (Thin the Herd): Làm Việc Rất Tốt (Excellent Work)",
  "I thought we might be able to use this.": "Tôi đã nghĩ rằng chúng ta có thể sẽ dùng được thứ này.",
  "You called the cavalry, and we're on the way.": "Cậu đã gọi kỵ binh tới, và chúng tôi đang trên đường đến đây.",
  "We ain't through the fuckin' woods yet, kids.": "Chúng ta vẫn chưa thoát khỏi khu rừng khốn kiếp này đâu, mấy đứa.",
  "Siege Bonus:": "Phần Thưởng Cố Thủ (Siege Bonus):",
  "Well, she married a machinist. Didn't like it when I became a cop instead.": "Chà, bà ấy đã kết hôn với một người thợ máy. Bà ấy đéo thích chút nào khi thay vào đó tôi lại trở thành một cảnh sát.",
  "You're mine, motherfucker.": "Mày là của tao, thằng khốn nạn.",
  "70 VIP Gus Burton": "70 VIP Gus Burton",
  "Le": "Le",
  "Am I the only one going a little stir crazy here?": "Tôi có phải là người duy nhất ở đây đang trở nên hơi điên cuồng vì bị nhốt quá lâu (stir crazy) đéo?",
  "Help Doc Hanson": "Giúp Đỡ Bác sĩ Hanson",
  "Well, that fucking sucked.": "Chà, chuyện đó đúng là tệ hại vãi cứt (sucked).",
  "I want artillery on my coordinates, right now!": "Tôi muốn pháo binh nã đạn vào tọa độ của tôi, ngay bây giờ!",
  "Over to the right.": "Chuyển sang bên phải.",
  "Stand back and let us handle this.": "Lùi lại đi và để chúng tôi lo liệu việc này.",
  "Brew some Army coffee, in case we run out of engine grease.": "Hãy pha một ít cà phê Quân Đội (Army coffee) đi, phòng trường hợp chúng ta hết sạch dầu nhớt bôi trơn động cơ.",
  "Mckinley": "Mckinley",
  "I went out to try and bring %1$s into the community, but they died before we could get home. We barely got to know each other, but it feels like a serious loss. - %2$s": "Tôi đã đi ra ngoài để cố gắng đưa %1$s gia nhập vào cộng đồng, nhưng họ đã chết trước khi chúng tôi có thể về đến nhà. Chúng tôi hầu như còn chưa kịp làm quen biết nhau, nhưng nó mang lại cảm giác như một sự mất mát nghiêm trọng vậy. - %2$s",
  "It looks like somebody was ripped to pieces inside the RV. Probably several somebodies. It smells like the inside of a Bloater.\r\n\r\nIt can't be safe to ride in a mess like that. We're going to have to clean and disinfect the whole thing.": "Có vẻ như có ai đó đã bị xé xác thành từng mảnh bên trong chiếc RV này. Có lẽ là vài người nào đó. Nó có mùi y như bên trong một con Bloater vậy.\r\n\r\nChắc chắn là sẽ đéo an toàn khi di chuyển trong một mớ hỗn độn như thế này. Chúng ta sẽ phải dọn dẹp sạch sẽ và khử trùng toàn bộ chiếc xe.",
  "Runs in the family. Jacob and Thomas are both AWOL, and this isn't the first time.": "Di truyền trong gia đình rồi (Runs in the family). Cả Jacob và Thomas đều đào ngũ (AWOL), và đây cũng đéo phải là lần đầu tiên.",
  "Meet Judge Lawton.": "Gặp gỡ Thẩm Phán Lawton.",
  "This should help out.": "Thứ này chắc chắn sẽ giúp ích được đấy.",
  "Disk Corrupt": "Đĩa Bị Lỗi Tham Nhũng (Disk Corrupt)",
  "We do our best, sir. Black Friday out.": "Chúng tôi đã cố gắng làm hết sức mình rồi, thưa ngài. Black Friday hết (out).",
  "Interesting? Oh yeah. Useful? Not a chance.": "Thú vị sao? Ồ có chứ. Hữu ích á? Đéo có cửa đâu.",
  "We'd gotten into this big fight. My son and I.": "Chúng tôi đã rơi vào một cuộc tranh cãi lớn. Con trai tôi và tôi.",
  "New items at the Courthouse supply locker.": "Có những món đồ mới ở trong tủ chứa nhu yếu phẩm (supply locker) của Tòa Án.",
  "Like the other day, I was searching over on the west side and ended up in Jerry Haskin's place.": "Giống như ngày hôm nọ, tôi đang lùng sục tìm kiếm ở phía tây và cuối cùng lại chui vào nhà của Jerry Haskin.",
  "Report came in on one of those bloated gasbags, we need to kill this one quick. Keep your distance. -%2$s": "Báo cáo vừa nhận được về một trong những cái túi khí phình to (bloated gasbags) đó, chúng ta cần phải tiêu diệt con này thật nhanh chóng. Hãy giữ khoảng cách của cậu. -%2$s",
  "Payment received from Ray, as promised. - %1$s": "Đã nhận được khoản thanh toán từ Ray, đúng như đã hứa. - %1$s",
  "Revolver: Mark VI": "Súng Lục Ổ Quay (Revolver): Mark VI",
  "Your community is NOT BUILDING anything right now.": "Cộng đồng của cậu hiện tại ĐÉO XÂY DỰNG bất cứ thứ gì cả.",
  "NOTE: Food Concerns": "GHI CHÚ (NOTE): Những Mối Quan Tâm Về Vấn Đề Thức Ăn",
  "You should be fine from here.": "Cậu sẽ ổn thôi từ lúc này trở đi.",
  "Gives %s.": "Cung Cấp %s.",
  "Saline Solution": "Dung Dịch Nước Muối (Saline Solution)",
  "New report from our scouts....": "Báo cáo mới từ những người lính trinh sát (scouts) của chúng ta....",
  "Maybe I'll go out to the infirmary. And just lie there by myself, seeing as nobody's working it.": "Có lẽ tôi sẽ đi ra bệnh xá (infirmary). Và cứ nằm lì ở đó một mình thôi, bởi vì có vẻ như đéo có ai làm việc ở đó cả.",
  "I'm just thinking that this parasite, or whatever, probably lives up in the brain.": "Tôi chỉ đang nghĩ rằng con ký sinh trùng này, hay bất cứ thứ quái quỷ gì, có lẽ sống trên não bộ.",
  "So, what does he want?": "Vậy, hắn ta muốn cái gì?",
  "Shellplates": "Tấm Vỏ Đạn (Shellplates)",
  "Ranked Match": "Trận Đấu Xếp Hạng (Ranked Match)",
  "Fullscreen": "Toàn Màn Hình (Fullscreen)",
  "Help clear an infestation.": "Giúp dọn dẹp sạch sẽ một ổ dịch (infestation).",
  "We've received a package of high-end weapons, plus a few extra mags and some suppressors.": "Chúng ta đã nhận được một kiện hàng chứa những vũ khí cao cấp (high-end weapons), cộng thêm một vài băng đạn dự phòng (mags) và một số ống giảm thanh (suppressors).",
  "Meeks": "Meeks",
  "RESOURCES are gathered and consumed when you are away for a short period of time.": "CÁC TÀI NGUYÊN (RESOURCES) được thu thập và tiêu thụ khi cậu đi vắng trong một khoảng thời gian ngắn.",
  "Aleksander": "Aleksander",
  "Now that's the kind of place we could really stretch out in.": "Chà, đó đúng là kiểu nơi mà chúng ta thực sự có thể thoải mái kéo giãn gân cốt (stretch out) nghỉ ngơi rồi đấy.",
  "I know things are shitty, but that's no excuse to take it out on us.": "Tôi biết mọi chuyện đang rất tồi tệ (shitty), nhưng đó đéo phải là cái cớ để cậu trút giận lên chúng tôi đâu.",
  "Clear. Repeat last.": "Đã rõ. Hãy lặp lại câu cuối.",
  "Uh, Lil? Might want to tell your guy to hurry up. Looks like I just got noticed.": "Ờm, Lil? Có lẽ cô sẽ muốn bảo anh chàng của cô hãy nhanh lên đấy. Có vẻ như tôi vừa mới bị phát hiện rồi.",
  "Well, I guess I better go find him. - %1$s": "Chà, tôi đoán tốt hơn là tôi nên đi tìm anh ta. - %1$s",
  "TRUST LOST (Friendly Fire)": "MẤT ĐI ĐỘ TIN TƯỞNG (Bắn Nhầm Đồng Đội - Friendly Fire)",
  "Got any cannon-cockers on the line?": "Có tay pháo thủ (cannon-cockers) nào đang trên đường dây đéo?",
  "The swelling's not going down. I think it's broken.": "Chỗ sưng đéo hề xẹp xuống chút nào. Tôi nghĩ là nó bị gãy rồi.",
  "This changes things.": "Điều này làm thay đổi mọi thứ.",
  "Okay. Let's start dismantling these barricades. If anybody's still watching, they oughta notice this in a hurry.": "Được rồi. Hãy bắt đầu tháo dỡ những rào chắn (barricades) này đi. Nếu có bất kỳ ai đó vẫn còn đang theo dõi, chắc chắn họ sẽ nhanh chóng để ý thấy chuyện này thôi.",
  "We can talk about that later, Doctor Horn. Right now, you're my priority.": "Chúng ta có thể nói về chuyện đó sau, Bác sĩ Horn. Còn ngay lúc này, ông là ưu tiên hàng đầu của tôi.",
  "Yeah. That's what I was afraid of.": "Ừ. Đó chính là những gì mà tôi đã lo sợ.",
  "I'll check and see what's here.": "Tôi sẽ đi kiểm tra và xem có những gì ở đây.",
  "Doctor Horn made several visits to a medical examiner named Timothy Hall, just in the past week.": "Bác sĩ Horn đã có vài chuyến viếng thăm tới một chuyên gia giám định y khoa tên là Timothy Hall, chỉ trong tuần qua.",
  "I can't even imagine how hard it must be out there. How frightened you must be.": "Tôi thậm chí còn đéo thể tưởng tượng nổi ngoài kia mọi chuyện sẽ khó khăn đến mức nào. Cậu hẳn là phải cảm thấy sợ hãi lắm.",
  "If I try to stand up, I get dizzy.": "Nếu tôi cố gắng đứng dậy, tôi sẽ bị chóng mặt.",
  "Lexie": "Lexie",
  "95 STORY Anson Hearst": "95 CỐT TRUYỆN (STORY) Anson Hearst",
  "Commandeer a Vehicle": "Trưng Dụng Lấy Đi Một Chiếc Phương Tiện (Vehicle)",
  "PASTOR WILLIAM. Restores your Maximum Stamina.": "MỤC SƯ (PASTOR) WILLIAM. Phục hồi Thể Lực (Stamina) Tối Đa của cậu.",
  "Hold [ul_aim] to aim. Pull [ul_shoot] to shoot.": "Giữ [ul_aim] để ngắm mục tiêu. Nhấn [ul_shoot] để bắn.",
  "The disk appears to be corrupt": "Đĩa có vẻ như đã bị hỏng lỗi (corrupt)"
};

const file = 'output/languages/chunks/btxt_chunk_175.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_175.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk175[r.sourceText]) {
    r.translatedText = chunk175[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 175 successfully!');
