const fs = require('fs');
const chunk167 = {
  "Before we can do that, though, we need to find a way to get some power.": "Tuy nhiên, trước khi làm được việc đó, chúng ta cần tìm cách kiếm một nguồn điện (power).",
  "... maybe you should check the size of your bank account.": "... có lẽ cậu nên kiểm tra số dư tài khoản ngân hàng của mình đi.",
  "So what are you going to do?": "Vậy cậu định làm gì?",
  "MISSION: Trade Opportunity (Materials)": "NHIỆM VỤ (MISSION): Cơ Hội Giao Thương (Trade Opportunity) - (Vật Liệu - Materials)",
  "Like the mighty crocodile, I'm very dangerous over short distances.": "Giống như con cá sấu dũng mãnh, tôi rất nguy hiểm ở cự ly ngắn.",
  "We need an infirmary. We can't keep cramming sick people in with the rest of us.": "Chúng ta cần một bệnh xá (infirmary). Chúng ta đéo thể cứ nhồi nhét người bệnh vào chung với những người còn lại được.",
  "Pistol: G 33": "Súng Lục: G 33",
  "Everything went to hell at the Vet Clinic. I think Alan still made it out with the medicine, but no one here's gonna trust me for a long time, I think. - %1$s": "Mọi thứ đã đổ bể ở Phòng Khám Thú Y. Tôi nghĩ Alan vẫn trốn thoát được với số thuốc men, nhưng tôi nghĩ sẽ đéo có ai ở đây tin tưởng tôi trong một thời gian dài nữa. - %1$s",
  "I'll just put these with the rest of the stuff.": "Tôi sẽ để đống này cùng với những đồ đạc còn lại.",
  "Nick": "Nick",
  "Caution is key--now I'm less likely to break stuff when I search. (Special Technique: Ninja)": "Sự cẩn trọng là chìa khóa--bây giờ tôi ít có khả năng làm hỏng đồ đạc khi tìm kiếm hơn. (Kỹ Năng Đặc Biệt: Nhẫn Giả - Ninja)",
  "In position now.": "Đã vào vị trí.",
  "Keep an eye out for zombies--I'll be as quiet as I can, but, well... hammer.": "Hãy để mắt đến bọn zombies--tôi sẽ cố gắng giữ im lặng nhất có thể, nhưng, ừ thì... tôi dùng búa mà.",
  "I'm sorry. I know I let you down, I know this is a coward's way out, but I just can't. I'll see you soon, Mama. - %1$s": "Con xin lỗi. Con biết con đã làm mẹ thất vọng, con biết đây là một lối thoát hèn nhát, nhưng con thực sự đéo thể tiếp tục được nữa. Hẹn sớm gặp lại mẹ, Mẹ à. - %1$s",
  "+150%": "+150%",
  "We really aren't ready for another attack.": "Chúng ta thực sự đéo sẵn sàng cho một cuộc tấn công nào khác đâu.",
  "We're going to clear that LZ, now!": "Chúng ta sẽ dọn dẹp bãi đáp (LZ) đó, ngay bây giờ!",
  "Exit Strategy": "Chiến Lược Rút Lui (Exit Strategy)",
  "I am SO sorry, %2$s. You have to know it was an accident. I would never, ever do anything like that intentionally. - %1$s": "Tôi THẬT SỰ xin lỗi, %2$s. Cậu phải biết đó chỉ là một tai nạn. Tôi sẽ đéo bao giờ, đéo bao giờ cố ý làm một chuyện như vậy đâu. - %1$s",
  "Good supply of AMMO in their location.": "Có nguồn cung cấp ĐẠN DƯỢC (AMMO) tốt ở vị trí của họ.",
  "American variant of the famous Swedish C. Gustav m/45.": "Biến thể của Mỹ từ khẩu súng C. Gustav m/45 nổi tiếng của Thụy Điển.",
  "That was pretty good.": "Làm khá tốt đấy.",
  "Altizer": "Altizer",
  "Black pen on the back of a granola bar box.": "Chữ viết bằng bút đen trên mặt sau của hộp bánh ngũ cốc.",
  "Invert Y-Axis": "Đảo ngược trục Y (Invert Y-Axis)",
  "Gonna have to drive.": "Sẽ phải lái xe thôi.",
  "Concerned about our lack of construction materials.": "Lo ngại về sự thiếu hụt Vật liệu xây dựng (construction materials) của chúng ta.",
  "RV: Engine Repaired": "Xe RV: Đã Sửa Động Cơ (Engine Repaired)",
  "Back from patrol.": "Đã trở về từ chuyến tuần tra.",
  "Refills some brass to generate several magazines' worth of .50 BMG ammunition.": "Nạp lại một ít vỏ đạn (brass) để tạo ra vài băng đạn cỡ .50 BMG.",
  "Debug1": "Gỡ lỗi 1 (Debug1)",
  "TIP: [xi_dpad_down] (D-pad) to talk to Pastor William again.": "MẸO (TIP): [xi_dpad_down] (D-pad) để nói chuyện lại với Mục sư William.",
  "You wanna talk about that?": "Cậu muốn nói chuyện về việc đó đéo?",
  "I was afraid of that. Better keep an eye on it.": "Tôi đã lo sợ về điều đó. Tốt hơn là nên để mắt tới nó.",
  "I know, exciting life, right? Hell, I barely knew how to get to the post office.": "Tôi biết, một cuộc sống thú vị, đúng đéo? Chết tiệt, tôi thậm chí còn hầu như đéo biết đường đến bưu điện nữa là.",
  "Doc Hanson is a miracle worker.": "Doc Hanson đúng là một người làm phép màu.",
  "%1$s got sick.": "%1$s đã bị ốm.",
  "A few extra mags": "Vài băng đạn dự phòng",
  "Spotted someplace interesting. Should be some useful stuff there.": "Đã phát hiện ra một nơi khá thú vị. Chắc chắn sẽ có vài món đồ hữu ích ở đó.",
  "Puente": "Puente",
  "Somebody take out that screamer!": "Ai đó hãy hạ gục con screamer kia đi!",
  "Search and Rescue: Nothing Yet": "Tìm Kiếm và Cứu Hộ (Search and Rescue): Chưa Có Gì (Nothing Yet)",
  "Watch the barricades!": "Coi chừng các rào chắn (barricades)!",
  "Get ready!": "Chuẩn bị sẵn sàng đi!",
  "Shotgun Specialization Improved!": "Kỹ Năng Chuyên Môn Súng Shotgun Đã Cải Thiện!",
  "Yeah, but can you imagine how many people we'd need to keep it secure?": "Ừ, nhưng cậu có thể tưởng tượng được chúng ta cần bao nhiêu người để giữ an ninh cho nơi này đéo?",
  "Saw things through at the courthouse.": "Đã giải quyết xong mọi việc ở tòa án.",
  "A caring leader pays attention to their subordinates, and is constantly training them to be smarter, more observant soldiers. All soldiers gain Wits at twice the rate.": "Một người chỉ huy quan tâm luôn để ý đến cấp dưới của mình và liên tục huấn luyện họ để trở thành những người lính thông minh hơn, tinh ý hơn. Tất cả binh lính đều tăng Trí Tuệ (Wits) nhanh gấp đôi.",
  "MISSION: A Helping Hand": "NHIỆM VỤ (MISSION): Một Bàn Tay Giúp Đỡ (A Helping Hand)",
  "Stamina Regeneration": "Tốc Độ Phục Hồi Thể Lực (Stamina Regeneration)",
  "Listen, nobody likes having to make this call. I mean, I feel sick to my stomach just thinking about it.": "Nghe này, đéo ai thích phải đưa ra quyết định này đâu. Ý tôi là, tôi cảm thấy buồn nôn đến thót tim chỉ vì nghĩ về điều đó.",
  "Dogmatic Faith": "Đức Tin Cực Đoan (Dogmatic Faith)",
  "Rifle: Mini 14": "Súng Trường: Mini 14",
  "Modestine angels forty, ten mikes.": "Modestine ở độ cao bốn mươi (nghìn foot), mười phút nữa (mikes) đến nơi.",
  "Pro Gamer": "Game Thủ Chuyên Nghiệp (Pro Gamer)",
  "You here to help?": "Cậu đến để giúp một tay hả?",
  "Case of Ammunition": "Hòm Đạn Dược (Ammunition)",
  "Advice: Build a Watchtower": "Lời Khuyên (Advice): Xây Một Tháp Canh (Watchtower)",
  "Cornwell": "Cornwell",
  "Man, they beat the shit out of him. Cops had to taze a couple of them just to pull them off, and Biker Steve, he's just grinning like an idiot the whole time.": "Trời ạ, chúng đánh hắn nhừ tử luôn. Cảnh sát đã phải dùng súng điện chích vài tên trong số đó mới kéo chúng ra được, và Biker Steve, hắn chỉ cười toét miệng như một thằng ngu trong suốt thời gian đó.",
  "Kathy": "Kathy",
  "Maddison": "Maddison",
  "Hey, not too bad.": "Này, đéo tệ lắm đâu.",
  "Guys, we've got maybe the last tub of spicy garlic hummus in the world in our kitchen. That's pretty awesome, right? I'd love it if everybody got to eat some, but if a certain someone keeps dipping their fingers in it, nobody's going to get to enjoy it. -%1$s": "Các cậu, chúng ta có lẽ đang sở hữu hũ hummus tỏi cay cuối cùng trên thế giới trong nhà bếp của mình đấy. Khá tuyệt vời phải đéo? Tôi rất muốn mọi người đều được thưởng thức, nhưng nếu một ai đó cứ liên tục thò ngón tay vào chấm mút, thì sẽ đéo còn ai có cơ hội thưởng thức nó nữa đâu. -%1$s",
  "You heard the colonel, we are free to engage!": "Các cậu nghe lời đại tá rồi đấy, chúng ta được phép tự do giao chiến!",
  "Broadsword": "Kiếm Bản Rộng (Broadsword)",
  "Ha ha! That never gets old, does it?": "Ha ha! Trò đó đéo bao giờ cũ đi, phải đéo?",
  "The more outposts we have in an area, the larger the safe space around them will be. - %1$s": "Càng có nhiều tiền đồn (outposts) trong một khu vực, vùng không gian an toàn xung quanh chúng sẽ càng rộng lớn hơn. - %1$s",
  "Uh... I came from the church. Pastor William sent me? I'm here to pick up the doc.": "Ờ... Tôi đến từ nhà thờ. Mục sư William cử tôi tới? Tôi đến đây để đón doc.",
  "Kilo (Kilohana Young) is now playable.": "Kilo (Kilohana Young) hiện có thể chơi được.",
  "All done!": "Xong xuôi tất cả!",
  "I know where we can go to fix that.": "Tôi biết chúng ta có thể đi đâu để sửa chữa món đó.",
  "Killed 5 Bloaters at Breakdown Level 2 or Higher.": "Đã giết 5 Bloaters ở mức Breakdown Cấp độ 2 hoặc cao hơn.",
  "Posit one one tango mike papa two five juliett zero five romeo. [message end tone]": "Xác định vị trí một một tango mike papa hai năm juliett không năm romeo. [âm báo kết thúc tin nhắn]",
  "The end of the world can bring out the worst in people ... but here in Danforth, the army showed us their best.": "Ngày tàn của thế giới có thể bộc lộ những mặt tồi tệ nhất của con người... nhưng ở Danforth này, quân đội đã cho chúng ta thấy những gì tốt đẹp nhất của họ.",
  "You're pretty banged up. You'd better head home and rest.": "Cậu bị bầm dập khá nhiều đấy. Tốt hơn là cậu nên về nhà và nghỉ ngơi đi.",
  "Very short rifle, good for indoors but can be hard to tame.": "Một khẩu súng trường rất ngắn, phù hợp cho cận chiến trong nhà nhưng có thể khó kiểm soát.",
  "That's nothing.": "Chuyện nhỏ thôi mà.",
  "It's a trifle more blunt than any translation I'm familiar with.": "Bản dịch này có vẻ thô lỗ hơn một chút so với bất kỳ bản dịch nào mà tôi quen thuộc.",
  "Black felt-tip pen on a cardboard box top.": "Chữ viết bằng bút dạ đen trên nắp hộp các tông.",
  "The fuck is a \"Sabine?\"": "Cái đéo gì là \"Sabine?\"",
  "Evictions?": "Những Cuộc Trục Xuất?",
  "OSHA Standards": "Các Tiêu Chuẩn của OSHA (Cục Quản Lý An Toàn & Sức Khỏe Nghề Nghiệp)",
  "Reggie": "Reggie",
  "Walk with Sgt. Tan": "Đi dạo cùng Trung sĩ Tan",
  "Okay, I'll round up everybody that's available.": "Được rồi, tôi sẽ tập hợp tất cả những người đang rảnh rỗi lại.",
  "%1$s is a little insensitive.": "%1$s có một chút vô tâm.",
  "Pistol: Carrier 1911": "Súng Lục: Carrier 1911",
  "Oh. You know. Stuff.": "Ồ. Cậu biết đấy. Vài thứ linh tinh.",
  "I don't think that was the last of them.": "Tôi đéo nghĩ đó là đợt cuối cùng của chúng đâu.",
  "Start by climbing the designated Survey location.": "Bắt đầu bằng cách trèo lên Vị trí Khảo sát (Survey) đã được chỉ định.",
  "Like, back in college, I was in a car accident. I was stupid, trying to drive home after a frat party, lost control and swerved off the road.": "Chẳng hạn như, hồi còn học đại học, tôi bị tai nạn xe hơi. Tôi đã quá ngu ngốc khi cố lái xe về nhà sau một bữa tiệc ở hội nam sinh, mất kiểm soát và lao ra khỏi đường.",
  "Now get ready to move. The noise is going to bring down every zed in a ten-mile radius.": "Bây giờ chuẩn bị di chuyển đi. Tiếng ồn sẽ kéo theo mọi con zed trong bán kính mười dặm tới đây đấy.",
  "There's a building we'll want to check out.": "Có một tòa nhà mà chúng ta sẽ muốn kiểm tra đấy.",
  "Seeds": "Hạt Giống (Seeds)",
  "No, it's... ugh! Look, we're barely hanging on here as it is. Medicine was some of the first stuff to run out. We don't have any to spare for your friend.": "Đéo, đó là... ugh! Nghe này, chúng ta đang cố gắng cầm cự ở đây đã là may lắm rồi. Thuốc men là một trong những thứ đầu tiên cạn kiệt. Chúng tôi đéo còn dư chút nào cho bạn của cậu đâu.",
  "Supply Run with Kilo": "Chuyến Chạy Đi Tìm Đồ (Supply Run) Cùng Với Kilo",
  "FACILITY UNLOCKED": "ĐÃ MỞ KHÓA CƠ SỞ (FACILITY)",
  "You know, if we're close to one of her people, we might be able to bring them in.": "Cậu biết đéo, nếu chúng ta ở gần một người của cô ấy, chúng ta có thể đưa họ vào.",
  "That was my goddamn pudding cup.": "Đó là cốc bánh pudding chết tiệt của tao cơ mà."
};

const file = 'output/languages/chunks/btxt_chunk_167.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_167.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk167[r.sourceText]) {
    r.translatedText = chunk167[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 167 successfully!');
