const fs = require('fs');
const chunk115 = {
  "SUPPLY RUN: Resources Acquired": "CHUYẾN ĐI LẤY ĐỒ: Đã Thu Thập Tài Nguyên",
  "Yeah, you know what would make this easier? Is if we had some medicine. Hell, I'd settle for some allergy pills at this point.": "Ừ, cậu biết điều gì sẽ làm mọi chuyện dễ dàng hơn không? Đó là nếu chúng ta có chút thuốc men. Chết tiệt, lúc này tôi thậm chí chấp nhận cả thuốc chống dị ứng.",
  "Destroys Facility": "Phá Hủy Cơ Sở (Facility)",
  "Your heroics have earned you Fame.": "Hành động anh hùng của bạn đã mang lại Danh tiếng (Fame).",
  "A Tragic Loss": "Một Mất Mát Bi Thảm",
  "What've you got for us today, Ray?": "Hôm nay anh mang đến cho chúng tôi thứ gì vậy, Ray?",
  "Just goes to show ya, survivors: Seize the day. You never know when it'll be your last.": "Chỉ để cho các bạn thấy thôi, những người sống sót ạ: Hãy nắm bắt lấy từng ngày. Bạn sẽ không bao giờ biết khi nào là ngày cuối cùng của mình đâu.",
  "Well, we had a little bit of a close call there, but we got the barricades down.": "Chà, chúng tôi vừa thoát chết trong gang tấc, nhưng chúng tôi đã dẹp xong mấy cái rào chắn rồi.",
  "Can we blast our way through?": "Chúng ta có thể dùng thuốc nổ mở đường qua không?",
  "It's like a little traffic pattern. Hordes keep forming there.": "Giống như một mô hình giao thông thu nhỏ vậy. Các bầy horde cứ liên tục hình thành ở đó.",
  "You may need to hurry.": "Bạn có thể cần phải nhanh lên.",
  "TIP: Press [vehicle.ul_melee_attack] repeatedly to knock an enemy off the car door.": "MẸO: Nhấn [vehicle.ul_melee_attack] liên tục để hất văng kẻ thù khỏi cửa xe.",
  "Good for fitness and combat training.": "Tốt cho việc rèn luyện thể lực và huấn luyện chiến đấu.",
  "Skydiving, base-jumping, mountain climbing... you name it, I tried it. Even swam with the sharks once.": "Nhảy dù, nhảy base-jumping, leo núi... cứ kể đi, tôi đã thử hết rồi. Thậm chí có lần tôi còn bơi cùng cá mập nữa cơ.",
  "You know, we could use some extra hands ourselves. Why don't you join us?": "Cậu biết đấy, bản thân chúng tôi cũng có thể cần thêm người phụ giúp. Tại sao cậu không tham gia cùng chúng tôi?",
  "Let's get to searching.": "Bắt đầu tìm kiếm thôi.",
  "Got him.": "Bắt được hắn rồi.",
  "Hey, you see that?": "Này, cậu thấy chứ?",
  "No. There used to be twelve of us.": "Không. Từng có mười hai người chúng tôi.",
  "Should only take a minute.": "Chỉ mất một phút thôi.",
  "Just... when the time comes, make it quick, okay? One in the head. Don't let me suffer.": "Chỉ là... khi thời khắc đó đến, hãy làm thật nhanh nhé? Một viên vào đầu. Đừng để tôi phải chịu đựng.",
  "Gotcha, bitch!": "Bắt được mày rồi, con chó đẻ!",
  "Eyes right.": "Nhìn sang phải.",
  "I figured, we need all we can get.": "Tôi nghĩ là, chúng ta cần tất cả những gì có thể lấy được.",
  "We have more MATERIALS than we'll be able to store. - %1$s": "Chúng ta có nhiều VẬT LIỆU (MATERIALS) hơn mức có thể lưu trữ. - %1$s",
  "Well, nothing useful here.": "Chà, chẳng có gì hữu ích ở đây cả.",
  "Keep your blade out. You want to be ready.": "Cầm sẵn vũ khí cận chiến đi. Cậu sẽ muốn ở tư thế sẵn sàng đấy.",
  "Headshots. It's gotta be headshots.": "Bắn vào đầu. Phải bắn vào đầu.",
  "That was close. I was about to put a bullet in my head.": "Chút xíu nữa là xong rồi. Tôi đã định tự cho mình một viên đạn vào đầu.",
  "CRISIS: Malnutrition (Need Food)": "KHỦNG HOẢNG: Suy Dinh Dưỡng (Cần Thức Ăn)",
  ".40-caliber Ammunition": "Đạn cỡ .40",
  "So, that's five first aid kits and three cans of gas for a pallet of canned food and some antibiotics. Right?": "Vậy là, năm bộ sơ cứu và ba can xăng đổi lấy một pallet thức ăn đóng hộp và vài loại thuốc kháng sinh. Đúng chứ?",
  "Uhh, whenever you're ready, buddy! Help!": "Ờ, bất cứ khi nào cậu sẵn sàng nhé, anh bạn! Cứu với!",
  "Surprised you remember that.": "Ngạc nhiên là cậu vẫn nhớ chuyện đó đấy.",
  "It'd mean we have to spend less time scrounging for food... plus eating fresh fruit and vegetables has to be better for us than the canned stuff.": "Điều đó có nghĩa là chúng ta sẽ tốn ít thời gian đi lùng sục thức ăn hơn... thêm vào đó, ăn trái cây và rau tươi chắc chắn tốt cho chúng ta hơn là đồ hộp.",
  "Reduces the chances of violent arguments.": "Giảm thiểu nguy cơ xảy ra tranh cãi bạo lực.",
  "I just got my hands on a gun and a sat phone. I'm not saying how.": "Tôi vừa kiếm được một khẩu súng và một chiếc điện thoại vệ tinh. Tôi sẽ không nói là làm cách nào đâu.",
  "Upgrade to Refrigerated Storage": "Nâng Cấp Lên Kho Lưu Trữ Lạnh (Refrigerated Storage)",
  "Eyes front, people.": "Mọi người, nhìn về phía trước.",
  "I say we get outta here before any more of 'em walk by.": "Tôi đề nghị chúng ta biến khỏi đây trước khi có thêm vài con quái thai nào nữa đi ngang qua.",
  "Pistols": "Súng lục",
  "Other people survived!": "Có người khác sống sót!",
  "You've been surviving out there? All this time? Damn....": "Cậu đã sống sót ngoài kia sao? Trong suốt thời gian qua á? Chết tiệt....",
  "She seem a little... twitchy to you?": "Cô ta có vẻ hơi... bồn chồn quá mức đối với cậu không?",
  "Worthless.": "Vô dụng.",
  "This is the heart of the base, where the CO plans missions, makes strategic decisions, and researches new tactics.": "Đây là trái tim của căn cứ, nơi Chỉ huy (CO) lên kế hoạch cho các nhiệm vụ, đưa ra quyết định chiến lược và nghiên cứu các chiến thuật mới.",
  "CRAnial Breacher by CLEO.": "Vũ khí đập sọ (CRAnial Breacher) từ CLEO.",
  "Zombie Sieges": "Cuộc Vây Hãm Của Zombie",
  "LOG: We're going in.": "NHẬT KÝ: Chúng tôi chuẩn bị vào.",
  "I don't know how much longer I can take this. You know I had to shoot Frank last week, after he turned, right?": "Tôi không biết mình có thể chịu đựng chuyện này bao lâu nữa. Cậu biết tôi đã phải bắn Frank vào tuần trước, sau khi anh ấy bị biến đổi, đúng không?",
  "It is okay to let people help, you know.": "Để mọi người giúp đỡ là chuyện bình thường mà, cậu biết đấy.",
  "Sure, sounds good.": "Chắc chắn rồi, nghe hay đấy.",
  "Nolan": "Nolan",
  "We should get started.": "Chúng ta nên bắt đầu thôi.",
  "Requires Fighting Level 4": "Yêu cầu Kỹ Năng Chiến Đấu (Fighting) Cấp 4",
  "Take Rucksack": "Lấy Ba Lô Trữ Đồ (Rucksack)",
  "Thanks for walking me home.": "Cảm ơn vì đã đưa tôi về nhà.",
  "Choose Save Slot": "Chọn Ô Lưu Trò Chơi (Save Slot)",
  "We're all scared, but that's no excuse to not do your damn job.": "Tất cả chúng ta đều sợ hãi, nhưng đó không phải là cái cớ để không làm cái công việc khốn khiếp của cậu.",
  "Mm hm. Good kid, though. I tried to get her cleaned up and off the streets, but it never took.": "Mm hm. Nhưng là một đứa trẻ tốt. Tôi đã cố gắng giúp con bé cai nghiện và rời khỏi đường phố, nhưng không bao giờ thành công.",
  "Have you heard anything I've said in the last minute?": "Cậu có nghe những gì tôi vừa nói trong một phút vừa qua không đấy?",
  "Oh, yeah, sure! Help yourself!": "Ồ, ừ, chắc chắn rồi! Cứ tự nhiên nhé!",
  "Why? Why did I think steak tartare was a good idea with two-week-old beef? - %1$s": "Tại sao? Tại sao tôi lại nghĩ món thịt bò sống tartare là một ý kiến hay với món thịt bò đã để hai tuần rồi cơ chứ? - %1$s",
  "Get a Vehicle": "Lấy Một Chiếc Xe",
  "I think we're under some unusual fucking circumstances.": "Tôi nghĩ là chúng ta đang ở trong một cái hoàn cảnh đéo bình thường chút nào.",
  "Hey, Ray! Good to see you!": "Chào, Ray! Rất vui được gặp anh!",
  "Katerina": "Katerina",
  "Look, my orders were just to bring back those documents. But ... I can't leave you here. Come on.": "Nghe này, lệnh của tôi chỉ là mang tập tài liệu đó về. Nhưng... tôi không thể bỏ cô lại đây được. Đi nào.",
  "Yes! Um ... around here. Somewhere. Sorry, this place is a mess. I'll gather up what I can.": "Có! Um... quanh đây thôi. Đâu đó. Xin lỗi, chỗ này hơi lộn xộn. Tôi sẽ gom những gì có thể.",
  "Zap-Cat": "Zap-Cat",
  "I had to pick up a lot of that slack. \"Jacob, I need you to be a man. Take care of your sister.\" Know what I mean?": "Tôi đã phải gánh vác rất nhiều phần trách nhiệm đó. \"Jacob, bố cần con phải ra dáng một người đàn ông. Chăm sóc em gái con nhé.\" Cậu hiểu ý tôi không?",
  "Food Preservation": "Bảo Quản Thực Phẩm",
  "Shit, who needs zoning laws and county commissioners and all that crap?": "Chết tiệt, ai cần mấy cái luật phân vùng hay mấy ủy viên quận và đống nhảm nhí đó chứ?",
  "Graduated Early": "Tốt Nghiệp Sớm",
  "Holy shit!": "Vãi cứt!",
  "Even dead, people still hate this sound. Brings the zombies running.": "Dù đã chết, người ta vẫn ghét âm thanh này. Nó gọi lũ zombie chạy tới.",
  "(Kelly Eldridge III)": "(Kelly Eldridge III)",
  "Give me a snare and I'll bring you every damn zombie in the county. (Improved Cardio.)": "Đưa tôi một cái bẫy và tôi sẽ mang về cho cậu mọi con zombie khốn kiếp trong quận này. (Đã Cải thiện Thể Lực - Cardio.)",
  "Started taking a bunch of samples and talking about \"infection vectors\" and a bunch of shit I didn't understand.": "Bắt đầu lấy một đống mẫu vật và lải nhải về \"các vật trung gian truyền nhiễm\" và một đống thứ chết tiệt khác mà tôi chả hiểu gì.",
  "Man, that was fucked up. So, these guys get it into their head they can start selling crank on the Wilkersons' turf, right?": "Anh bạn, chuyện đó thật tồi tệ. Bọn này nghĩ rằng chúng có thể bắt đầu bán ma túy trên địa bàn của bọn Wilkerson, đúng không?",
  "Herrera": "Herrera",
  "Ferrari": "Ferrari",
  "Someone needs a talking to.": "Ai đó cần được nói chuyện đàng hoàng.",
  "Clear!": "An toàn!",
  "Still feeling pretty energized, better save this.": "Vẫn cảm thấy khá tràn trề năng lượng, tốt hơn là nên cất món này đi.",
  "Update on the runners...": "Cập nhật về những người chạy việc...",
  "Command Center: Fuel Located": "Trung tâm Chỉ huy (Command Center): Đã Định Vị Được Nhiên Liệu",
  "Trait Discovered: Adrenaline Junkie": "Đặc Điểm Được Khám Phá: Kẻ Nghiện Cảm Giác Mạnh",
  "This is Vienna Cho, signing off.": "Đây là Vienna Cho, kết thúc phiên phát sóng.",
  "Unlocks the ability to create Chemical Incendiaries. REQUIRES A WEAPONS LAB and MEDICAL LAB.": "Mở khóa khả năng chế tạo Chất Cháy Hóa Học. YÊU CẦU có PHÒNG THÍ NGHIỆM VŨ KHÍ (WEAPONS LAB) và PHÒNG THÍ NGHIỆM Y TẾ (MEDICAL LAB).",
  "Never talks about life back home. Wants the past to remain in the past.": "Không bao giờ nhắc về cuộc sống ở quê nhà. Muốn quá khứ ngủ yên.",
  "Anybody got any good intel on what's going on around here?": "Có ai có thông tin tình báo gì hay ho về chuyện đang xảy ra quanh đây không?",
  "Also? Now we've got a good source of medicine.": "Còn nữa? Bây giờ chúng ta đã có một nguồn cung cấp thuốc men tốt.",
  "He got jumped on his way home from \"patrol.\" Barely managed to drag his stupid ass home.": "Anh ta bị tấn công trên đường về nhà sau khi đi \"tuần tra.\" Phải cố gắng lắm mới lết được cái mông ngu ngốc của mình về nhà.",
  "Pistol: P 226 Sg": "Súng lục: P 226 Sg",
  "SUPPLY RUN: Resources Found": "CHUYẾN ĐI LẤY ĐỒ: Đã Tìm Thấy Tài Nguyên",
  "Maybe later.": "Có lẽ để sau.",
  "A friend in trouble.": "Một người bạn đang gặp rắc rối.",
  "We've got a line on one of our missing people.": "Chúng ta đã có manh mối về một trong những người mất tích của mình.",
  "Improvised Weapon": "Vũ Khí Tự Chế"
};

const file = 'output/languages/chunks/btxt_chunk_115.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_115.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk115[r.sourceText]) {
    r.translatedText = chunk115[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 115 successfully!');
