const fs = require('fs');
const chunk178 = {
  "Igorot Axe": "Rìu Igorot (Axe)",
  "Found that cell tower. Right where you said it'd be. So, what am I looking for?": "Đã tìm thấy tháp truyền hình đó rồi. Nằm ngay đúng vị trí cậu đã nói. Vậy, tôi đang phải tìm kiếm cái gì đây?",
  "Trait Discovered: Survivor's Guilt": "Phát Hiện Đặc Điểm (Trait): Mặc Cảm Tội Lỗi Của Kẻ Sống Sót (Survivor's Guilt)",
  "Might want to swing wide, we got zombies to the left.": "Có lẽ chúng ta nên lượn vòng rộng ra chút, có bọn zombies ở phía bên trái kìa.",
  "Hey, everybody ... if you’re listening. We knew this day was coming. We can’t stay here. Not anymore.": "Này, mọi người ... nếu các người đang nghe. Chúng ta đều biết trước rằng ngày này sẽ đến mà. Chúng ta đéo thể ở lại đây được nữa. Đéo thể thêm nữa.",
  "PERSONAL SKILL. Who needs subtitles?": "KỸ NĂNG CÁ NHÂN (PERSONAL SKILL). Ai cần phụ đề cơ chứ?",
  "Outstanding.": "Xuất sắc (Outstanding).",
  "HISTORY: Expelled": "LỊCH SỬ (HISTORY): Bị Đuổi Học (Expelled)",
  "A practical leader is always exploring new options and is ready with a backup plan in any disaster. Bonus to research rates.": "Một nhà lãnh đạo thực tế luôn tìm tòi khám phá những lựa chọn mới và sẵn sàng có kế hoạch dự phòng trong mọi thảm họa. Tăng tốc độ nghiên cứu (research rates).",
  "No Save Game Detected": "Đéo Phát Hiện Dữ Liệu Lưu Game (Save Game)",
  "I remember this one time, when I was too sick to go to the movies for Becky Lindeman's birthday party, he turned our living room into an old-timey movie theater, just for me.": "Tôi nhớ có một lần này, khi tôi ốm quá đéo thể đến rạp chiếu phim để tham dự bữa tiệc sinh nhật của Becky Lindeman, anh ấy đã biến phòng khách của chúng tôi thành một rạp chiếu phim theo phong cách cổ điển, chỉ dành riêng cho tôi.",
  "Ran the church bake sale every year for 20 years.": "Đã điều hành buổi bán bánh nướng từ thiện của nhà thờ mỗi năm một lần trong suốt 20 năm.",
  "Hope everybody's up on their cardio, 'cause at this rate we're gonna be hoofing it everywhere.": "Hy vọng mọi người vẫn đang rèn luyện tốt bài tập tim mạch (cardio) của mình, bởi vì với tốc độ này thì chúng ta sẽ phải cuốc bộ đến mọi nơi mất.",
  "%1$s is sick from poor sanitation.": "%1$s đang bị bệnh do điều kiện vệ sinh tồi tệ.",
  "Radio Home": "Gọi Radio Về Căn Cứ",
  "Maybe we should go the other way.": "Có lẽ chúng ta nên đi con đường khác đi.",
  "Missing persons found dead.": "Những người mất tích đã được tìm thấy trong tình trạng đã chết.",
  "One of those psychos bit me, but... Yeah. Yeah I'm fine.": "Một trong những thằng điên đó đã cắn tôi, nhưng... Ừ. Ừ tôi đéo sao đâu.",
  "Got some zeds on the right there.": "Có vài con zeds ở bên phải kia kìa.",
  "Used to be a wild child in college, but confronting the outbreak has sparked a return to the faith of her youth. She meditates daily and commits herself to personal discipline and service to others.": "Từng là một cô nàng hoang dại ở thời đại học, nhưng việc đối mặt với đợt bùng phát dịch bệnh đã khơi dậy sự trở lại với đức tin thời trẻ của cô ấy. Cô ấy thiền định mỗi ngày và cam kết với bản thân phải có kỷ luật cá nhân và phục vụ vì người khác.",
  "There were living cells still kicking around in there. Not bacteria. Not cancer. Something else.": "Vẫn còn những tế bào sống (living cells) đang hoạt động vất vưởng trong đó. Đéo phải vi khuẩn. Đéo phải ung thư. Là một thứ gì đó khác.",
  "The Mercenary": "Kẻ Đánh Thuê (The Mercenary)",
  "It's okay to be freaked out. Just means you're human.": "Việc cảm thấy hoảng sợ tột độ là chuyện bình thường thôi. Điều đó chỉ chứng tỏ cậu vẫn còn là con người.",
  "Not here, it's too small.": "Đéo phải ở đây, chỗ này quá nhỏ.",
  "You're all right.": "Cậu đéo sao rồi.",
  "You couldn't know this would happen.": "Cậu đéo thể nào biết được chuyện này sẽ xảy ra đâu.",
  "What am I silencing, exactly?": "Chính xác thì tôi đang làm cho cái gì phải im lặng cơ chứ?",
  "Wheeler": "Wheeler",
  "Web Developer": "Lập Trình Viên Web (Web Developer)",
  "+20%": "+20%",
  "10 Daily Rations of Food for 2 Cases of Ammunition.": "10 Khẩu Phần Thức Ăn (Food) Hàng Ngày đổi lấy 2 Thùng Đạn Dược (Ammunition).",
  "Jake": "Jake",
  "Danforth is gone. It's time to regroup and move on to the next objective. Highroad out.": "Thành phố Danforth đã sụp đổ. Đã đến lúc phải tập hợp đội hình lại và chuyển sang mục tiêu tiếp theo. Highroad hết (out).",
  "56 GENERIC Bethany Olmstead": "56 CHUNG (GENERIC) Bethany Olmstead",
  "Jillian": "Jillian",
  "Assault Rifle: Mk. 17 Mod. 0": "Súng Trường Tấn Công (Assault Rifle): Mk. 17 Mod. 0",
  "Why won't you listen to me, when I've got all the answers?": "Tại sao cậu lại đéo chịu lắng nghe tôi, trong khi tôi đã có tất cả các câu trả lời chứ?",
  "I appreciate it. Really. I'll stay here in case they turn up.": "Tôi thực sự rất biết ơn điều đó. Thật đấy. Tôi sẽ ở lại đây phòng trường hợp bọn họ xuất hiện.",
  "Aw shit.": "Ôi vãi cứt.",
  "We're moving out now. We'll be there soon!": "Bọn tôi đang xuất phát ngay bây giờ đây. Chúng tôi sẽ đến đó sớm thôi!",
  "Will you please give it a rest? You're not Mom.": "Cậu làm ơn bỏ qua chuyện đó được đéo? Cậu đéo phải là Mẹ tôi đâu.",
  "All he had was a little bite!": "Tất cả những gì anh ấy bị chỉ là một vết cắn nhỏ thôi mà!",
  "Our comms officer was lost with Greyhound Two. We haven't been able to locate his satellite gear.": "Sĩ quan liên lạc (comms officer) của chúng ta đã mất tích cùng với đội Greyhound Two. Chúng tôi vẫn chưa thể xác định được vị trí của thiết bị vệ tinh của anh ta.",
  "When those zeds go down, you gotta make sure they STAY down.": "Khi bọn zeds đó gục ngã, cậu phải chắc chắn rằng chúng sẽ ĐÉO THỂ GƯỢNG DẬY được nữa.",
  "If we got rid of some freaks, things might be easier.": "Nếu chúng ta tiêu diệt được một vài bọn quái thai (freaks), mọi chuyện có thể sẽ dễ thở hơn.",
  "I've been helping Pastor Will with charity shit for years.": "Tôi đã phụ giúp Mục sư Will mấy cái trò từ thiện chó má đó trong suốt nhiều năm qua.",
  "Sykes": "Sykes",
  "I'm a little ... out of it right now.": "Hiện tại tôi đang có một chút ... đéo được tỉnh táo cho lắm.",
  "Scroll Up": "Cuộn Lên (Scroll Up)",
  "That's what yo momma said.": "Đó cũng chính là những gì mà mẹ mày đã nói đấy.",
  "All right. Stay close to the landing zone until your ride gets here. Cure this thing for us, all right?": "Được rồi. Hãy ở gần khu vực bãi đáp (landing zone) cho đến khi chuyến xe của cậu đến đây. Hãy chữa khỏi căn bệnh chết tiệt này cho chúng tôi, được đéo?",
  "Find out what Quentin wants.": "Tìm hiểu xem Quentin đang muốn điều gì.",
  "SURVIVAL TACTICS: Surveying": "CHIẾN THUẬT SINH TỒN (TACTICS): Quan Sát Khảo Sát (Surveying)",
  "We weren't able to keep Doctor Julene Horn alive long enough to get her onto a helicopter.": "Chúng ta đã đéo thể giữ cho Bác sĩ Julene Horn sống sót đủ lâu để đưa cô ấy lên một chiếc trực thăng.",
  "Slow and steady gets us not eaten. Don't make so much noise when you search.": "Chậm rãi và chắc chắn sẽ giúp chúng ta đéo bị ăn thịt. Đừng có tạo ra quá nhiều tiếng ồn khi cậu lục soát tìm đồ.",
  "CLEO Axe": "Rìu CLEO (Axe)",
  "Aim for the fucking head.": "Hãy nhắm thẳng vào cái đầu chết tiệt của bọn nó.",
  "Electrician": "Thợ Điện (Electrician)",
  "Just wanted to say, it's good to have you here. We appreciate everything you do for us. - %1$s": "Tôi chỉ muốn nói là, thật tốt khi có cậu ở đây. Chúng tôi rất trân trọng mọi thứ mà cậu đã làm cho chúng tôi. - %1$s",
  "Gate": "Cổng Khóa (Gate)",
  "Pipe Bomb": "Bom Ống Tự Chế (Pipe Bomb)",
  "Thank you, and God bless.": "Cảm ơn cậu, và cầu xin Chúa ban phước cho cậu.",
  "I think we've discovered a flaw in my plan, listeners.": "Thưa các thính giả, tôi nghĩ rằng chúng ta đã phát hiện ra một lỗ hổng trong kế hoạch của tôi rồi.",
  "I'm glad I know something useful. (Good with plants.)": "Tôi rất vui vì tôi biết một vài thứ hữu ích. (Có khiếu trồng trọt.)",
  "Alright, let's do this thing": "Được rồi, hãy làm cho xong việc này thôi",
  "Our community is growing.": "Cộng đồng của chúng ta đang ngày càng phát triển lớn mạnh.",
  "An outpost here could be pretty useful.": "Lập một tiền đồn (outpost) ở đây có thể sẽ khá là hữu ích đấy.",
  "I thought suicide bombers usually worked for the other guys.": "Tôi đã tưởng rằng những kẻ đánh bom liều chết (suicide bombers) thường làm việc cho những phe cánh bên kia cơ đấy.",
  "Samus": "Samus",
  "%1$s missing.": "%1$s đang bị mất tích.",
  "10 GENERIC Jess Cohen": "10 CHUNG (GENERIC) Jess Cohen",
  "Army Sighting": "Phát Hiện Quân Đội (Army Sighting)",
  "Nicely done!": "Làm tốt lắm!",
  "Created 5 Flame Fougasses.": "Đã chế tạo 5 Quả Mìn Lửa (Flame Fougasses).",
  "We were serious about wanting to join your group, you know.": "Chúng tôi rất nghiêm túc về việc muốn gia nhập nhóm của cậu đấy, cậu biết mà.",
  "Of course, before we can do any of that we need to build an infirmary. So there's that.": "Tất nhiên rồi, trước khi chúng ta có thể làm được bất cứ điều gì trong số đó, chúng ta cần phải xây dựng một bệnh xá (infirmary). Mọi chuyện là như vậy đấy.",
  "This whole communal living thing takes some getting used to.": "Cái kiểu sống chung trong cộng đồng tập thể này đòi hỏi phải có thời gian để thích nghi làm quen.",
  "Again? We're going to have riots at this rate.": "Lại nữa sao? Chúng ta sẽ có bạo loạn với cái đà này mất.",
  "Pinckard": "Pinckard",
  "That place might have some good shit.": "Nơi đó có thể có vài thứ đồ ngon nghẻ (good shit) đấy.",
  "We have to believe in each other. That's the only way this works. -%2$s.": "Chúng ta phải tin tưởng lẫn nhau. Đó là cách duy nhất để chuyện này có thể hoạt động được. -%2$s.",
  "Jackie": "Jackie",
  "Hughes": "Hughes",
  "We've got company here.": "Chúng ta có khách (company) đéo mời mà đến ở đây này.",
  "Rrrraaaaaaaagh!": "Rrrraaaaaaaagh!",
  "We'll be along in a little while. Just want to make sure we don't leave anything behind.": "Chúng tôi sẽ đi dọc theo đó trong một chốc lát. Chỉ muốn đảm bảo rằng chúng ta sẽ đéo bỏ sót lại bất cứ thứ gì ở phía sau.",
  "COMPLETED: A Discreet Request": "ĐÃ HOÀN THÀNH: Một Lời Yêu Cầu Kín Đáo (Discreet Request)",
  "I don't have authorization for that.": "Tôi đéo có thẩm quyền (authorization) để làm việc đó.",
  "Homemade Suppressor": "Ống Giảm Thanh Tự Chế (Homemade Suppressor)",
  "Just checking in. How are things looking, Lily?": "Chỉ là kiểm tra tình hình chút thôi. Mọi chuyện trông có vẻ ổn đéo, Lily?",
  "NEW ZOMBIE TYPE: Juggernaut": "LOẠI ZOMBIE MỚI: Juggernaut",
  "Quite a crowd here.": "Đông nghẹt cả người ở đây nhỉ.",
  "Come on, motherfucker!": "Nhào vô đi, thằng khốn nạn!",
  "But now he's doing this whole lost puppy thing, following me around and acting like we're married or whatever.": "Nhưng bây giờ anh ta đang làm cái trò như một con cún con lạc lõng vậy, cứ đi theo tôi khắp nơi và hành động như thể chúng tôi đã kết hôn hay gì đó đại loại vậy.",
  "Everybody get to the walls - we've got a horde incoming.": "Mọi người mau vào vị trí ở các bức tường rào - chúng ta có một bầy (horde) zombie đang kéo đến.",
  "Don't worry, we're on the way.": "Đừng lo, chúng tôi đang trên đường tới đây.",
  "Nothing's broken, though. With a little bed rest, I should be fine in a day or so.": "Mặc dù vậy, cũng đéo có xương nào bị gãy cả. Chỉ cần nằm nghỉ ngơi trên giường một chút, tôi sẽ ổn thôi trong vòng một ngày hay chừng đó.",
  "Greyhound One to Doghouse, we're at the objective. The helo is a wreck. No visual on the asset.": "Greyhound One gọi Doghouse, chúng tôi đã đến mục tiêu (objective). Chiếc trực thăng là một đống đổ nát. Đéo nhìn thấy mục tiêu tài sản (asset) đâu cả.",
  "Fitzgerald": "Fitzgerald",
  "Sophie": "Sophie"
};

const file = 'output/languages/chunks/btxt_chunk_178.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_178.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk178[r.sourceText]) {
    r.translatedText = chunk178[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 178 successfully!');
