const fs = require('fs');
const chunk208 = {
  "Long as we got the guns, the complainers won't try anything.": "Chỉ cần (Long as) chúng ta vẫn còn được trang bị đầy đủ súng ống (guns), thì cái đám người hay than vãn phàn nàn (complainers) đó sẽ đéo dám cả gan làm liều thử giở trò (try) đéo nào cả đâu.",
  "We need to build up the expertise it will take to replace our gas generator with a solar array.": "Chúng ta hiện đang rất cần phải thu thập trau dồi (build up) được một lượng kiến thức chuyên môn (expertise) nhất định dùng để thay thế (replace) hoàn toàn cho cái chiếc máy phát điện chạy bằng khí gas (gas generator) của chúng ta thành một hệ thống mảng năng lượng mặt trời (solar array).",
  "Alexandra": "Alexandra",
  "Option 3": "Tùy Chọn Quyết Định (Option) Thứ 3",
  "When we reached the LZ, we found it under attack by waves of zeds. Greyhound Two was holding out, but they weren't going to make it on their own.": "Vào đúng lúc chúng tôi di chuyển đến (reached) được khu vực bãi đáp (LZ), thì chúng tôi lại tình cờ phát hiện (found) ra rằng nó hiện đang bị tấn công (under attack) dồn dập bởi từng đợt sóng (waves) zeds. Lực lượng Greyhound Two lúc đó vẫn đang cố gắng cầm cự bám trụ (holding out), nhưng chắc chắn là bọn họ sẽ đéo thể nào có thể tự mình xoay sở sống sót (make it) được khi chỉ có một thân một mình (on their own) như vậy đâu.",
  "Don't make me have to cut a zed.": "Đừng có để cho tôi phải bắt buộc đâm chém rạch nát (cut) một con zed đéo nào nữa đấy.",
  "Ahh, dammit.": "Ahh, mẹ kiếp (dammit).",
  "We don't have everything we need.": "Chúng ta hiện tại đéo (don't) có đủ toàn bộ tất cả mọi thứ (everything) mà chúng ta đang vô cùng cần thiết (need).",
  "Amateur photographer who sells the occasional shot to small magazines.": "Một thợ chụp ảnh nghiệp dư (Amateur photographer) chuyên đi rao bán lại (sells) những bức ảnh (shot) được chụp một cách vô tình ngẫu nhiên (occasional) cho các tòa soạn tạp chí (magazines) quy mô nhỏ.",
  "A zed's not much of a threat one-on-one, but taking a bunch out in close quarters takes skill. - %1$s": "Một con zed duy nhất thực sự hoàn toàn đéo (not much) phải là một mối đe dọa (threat) quá lớn khi phải đối mặt một chọi một (one-on-one), thế nhưng cái việc phải tiến hành dọn dẹp tiêu diệt (taking out) cả một đám đông (bunch) khi phải giáp lá cà trong phạm vi hẹp (close quarters) thì lại luôn đòi hỏi (takes) rất nhiều kỹ năng (skill). - %1$s",
  "COMPLETED: A Helping Hand": "ĐÃ HOÀN THÀNH (COMPLETED): Một Bàn Tay (Hand) Chìa Ra Để Giúp Đỡ (Helping)",
  "Range Finder": "Một Chiếc Máy Đo Khoảng Cách (Range Finder)",
  "But you still give a holler if you want me to shoot some corpsified motherfuckers for you. My aim's better when I drink.": "Thế nhưng cậu vẫn hoàn toàn có thể tự nhiên rống to gọi lớn (holler) nếu như cậu đang muốn tôi giúp (want me) bắn nát sọ (shoot) cái đám xác chết chó đẻ khốn nạn (corpsified motherfuckers) đó thay cho cậu. Khả năng ngắm bắn (aim's) của tôi sẽ trở nên chuẩn xác hơn rất nhiều (better) mỗi khi mà tôi được uống rượu (drink).",
  ".22 caliber": "nòng cỡ .22 caliber",
  "SURVIVAL TACTICS: Clearing Infestations": "NHỮNG CHIẾN THUẬT (TACTICS) DÙNG ĐỂ SINH TỒN SỐNG SÓT (SURVIVAL): Tiến Hành Càn Quét Dọn Dẹp (Clearing) Các Khu Vực Ổ Dịch (Infestations)",
  "Got some good stuff here, headin' home.": "Hiện đã thu thập (Got) được một vài món đồ đạc vô cùng tuyệt vời (good stuff) ở ngay tại đây, đang trên đường chuẩn bị đi quay trở về căn cứ (home).",
  "More like a concerned citizen.": "Giống hệt như (More like) là một người công dân (citizen) đang tỏ ra vô cùng lo ngại (concerned) vậy.",
  "If anyone finds my mother, tell her I'm sorry. I wasn't strong enough. %1$s": "Nếu như có bất kỳ một ai (anyone) vô tình tìm thấy (finds) người mẹ ruột (mother) của tôi, thì xin hãy nói (tell) lại với bà ấy rằng con vô cùng thành thật xin lỗi (sorry). Chỉ là do con đã đéo thể nào (wasn't) đủ mạnh mẽ kiên cường (strong enough). %1$s",
  "Hesse": "Hesse",
  "HOME STATUS": "BẢNG THÔNG TIN TRẠNG THÁI (STATUS) CỦA CĂN CỨ (HOME)",
  "Gill": "Gill",
  "Gotta take out some zeds first.": "Cần phải nhanh chóng xử lý dọn dẹp tiêu diệt (take out) một vài con zeds chết tiệt trước (first) đã.",
  "EXPEL FROM COMMUNITY. Or at least try to.": "TRỤC XUẤT (EXPEL) HOÀN TOÀN RA KHỎI CỘNG ĐỒNG CĂN CỨ (COMMUNITY). Hoặc chí ít (at least) là cũng nên thử làm như vậy (try to).",
  "Not signed in": "Đéo thể đăng nhập (Not signed in)",
  "Howdy, miss Lily. How you feeling today?": "Xin chào (Howdy), cô Lily. Hôm nay (today) tâm trạng của cô đang cảm thấy (feeling) như thế nào (How) rồi?",
  "We need somebody who actually knows their shit running the infirmary.": "Chúng ta hiện đang vô cùng cần (need) một ai đó (somebody) thực sự cực kỳ am hiểu (knows) sâu sắc về tất cả những cái thứ cứt đái tồi tệ (shit) này để có thể điều hành quản lý (running) được một khu vực trạm y tế (infirmary) chuẩn chỉ.",
  "Battllori": "Battllori",
  "I mean, how bad does shit have to be for somebody to just say \"you know what? Screw you guys, I'll take my chances alone in the zombie-infested wilderness?\"": "Ý của tôi (mean) là, rốt cuộc thì mọi cái thứ (shit) chết tiệt này sẽ còn phải trở nên tồi tệ (bad) đến nhường đéo nào (how) nữa thì mới có thể khiến cho một ai đó (somebody) phải thốt lên (say) rằng \"các người có biết điều (know) gì đéo? Mặc xác (Screw) cái lũ khốn kiếp (guys) nhà các người đấy, tôi chắc chắn sẽ tự mình đi đánh cược (take my chances) nắm lấy cơ hội sống sót khi phải ở ngoài một mình (alone) ngay giữa một vùng khu vực hoang dã (wilderness) đang bị lây nhiễm (infested) đầy rẫy bọn zombie tởm lợm này cơ chứ?\"",
  "Replace this gas guzzler with a modern solar array with battery backup.": "Tiến hành thay thế (Replace) cái cỗ máy vô cùng ngốn xăng (guzzler) rác rưởi này thành một hệ thống mảng thiết bị năng lượng mặt trời (solar array) vô cùng tối tân hiện đại (modern) đi kèm với (with) một hệ thống pin (battery) tích điện dự phòng (backup).",
  "All right, let's do this!": "Được rồi (All right), chúng ta hãy cùng nhau bắt tay vào làm việc (do this) thôi nào!",
  "Watch the left flank.": "Chú ý quan sát bảo vệ (Watch) cho phần cánh trái (left flank).",
  "There's nothing quite like cracking some skulls, huh?": "Sẽ đéo có (There's nothing) bất cứ một điều gì có thể sánh bằng (quite like) với cái cảm giác được đi đập vỡ (cracking) một vài cái hộp sọ (skulls) chết tiệt, đúng đéo (huh)?",
  "The Cleo beacon is up. Good luck.": "Cột tín hiệu (beacon) truyền tin của Cleo hiện tại đã được kích hoạt thiết lập thành công (up). Chúc cho các người gặp được nhiều điều may mắn (Good luck).",
  "We're going to have to clean and disinfect the whole thing.": "Chúng ta chắc chắn sẽ cần phải tiến hành lau dọn vệ sinh (clean) và tiêu độc khử trùng (disinfect) lại cho toàn bộ (whole) cái khu vực này đấy.",
  "All we have? The Army's camped just across the river.": "Tất cả những thứ (All) mà chúng ta đang sở hữu (have) ư? Lực lượng Quân Đội (Army) hiện tại đã tiến hành lập doanh trại (camped) đóng quân ở ngay phía bên kia con sông (across the river) rồi đấy.",
  "Everybody's dead!": "Tất cả mọi người (Everybody) đều đã hoàn toàn chết (dead) sạch cmnr!",
  "Hey, what happened to the guy the Wilkersons beat up?": "Này, cái chuyện đéo gì (what happened) đã xảy ra đối với cái gã (guy) đã bị cái gia đình Wilkersons đánh đập (beat up) tàn nhẫn vậy?",
  "Shit! They're coming through the kitchen!": "Chết tiệt thật (Shit)! Bọn chúng hiện đang xông thẳng qua (through) khu vực nhà bếp (kitchen) kìa!",
  "Turn On Generator": "Bật (Turn On) Máy Phát Điện (Generator) Lên",
  "Yeah, trade's done, I got the goods.": "Yeah, cuộc giao dịch (trade) cuối cùng cũng đã được hoàn thành (done), tôi hiện đã lấy được (got) đầy đủ số lượng hàng hóa (goods) yêu cầu rồi đây.",
  "Holy shit, is that one wearing a helmet?": "Địt mẹ khốn khiếp thật (Holy shit), có phải là cái con đó (that one) hiện đang được trang bị đội (wearing) cả một chiếc mũ bảo hiểm (helmet) đấy đéo?",
  "Wouldn't surprise me if this whole thing ends with all of us arrested for trespassing and grand larceny.": "Tôi chắc chắn sẽ đéo cảm thấy (Wouldn't) ngạc nhiên (surprise) một chút nào nếu như (if) toàn bộ tất cả mọi chuyện chết tiệt (whole thing) này đi đến hồi kết (ends) với việc toàn bộ tất cả chúng ta (all of us) đều sẽ bị bắt giữ giam cầm (arrested) vì cái tội cố tình xâm phạm (trespassing) trái phép và có âm mưu thực hiện hành vi trộm cắp tài sản sở hữu lớn (grand larceny).",
  "Home Improvement": "Hoàn Thiện Việc Cải Tạo Nâng Cấp Tái Thiết Lại (Improvement) Căn Cứ Ngôi Nhà (Home)",
  "Send a runner.": "Hãy mau gửi đi (Send) một người có khả năng chạy bộ cực nhanh (runner).",
  "Help you with something?": "Cần tôi hỗ trợ giúp đỡ (Help) cho cậu với một thứ gì đó (something) đéo?",
  "Autocrat": "Một Kẻ Luôn Thích Cầm Quyền Độc Đoán Độc Tài (Autocrat)",
  "Follow my lead!": "Hãy mau đi theo (Follow) sự chỉ dẫn (lead) của tôi!",
  "Maybe we ought to go, huh?": "Có lẽ (Maybe) chúng ta đáng lẽ ra (ought to) đã nên phải đi rời khỏi (go) cái nơi này ngay thôi, đúng đéo (huh)?",
  "Help Sasquatch hunt a Juggernaut": "Trợ Giúp (Help) Cho Sasquatch đi săn lùng (hunt) một con Juggernaut",
  "The Wilkersons": "Gia đình nhà Wilkersons",
  "We have zeds inside the east gate!": "Chúng ta hiện đang có một bầy zeds xuất hiện ở ngay bên trong (inside) khu vực cánh cổng phía đông (east gate) kìa!",
  "%s %s Is Missing!": "%s %s Hiện Tại Đã Hoàn Toàn Bị Mất Tích (Missing) Cmnr!",
  "We can talk our soldiers through advanced medical procedures over the radio, restoring their maximum vitality.": "Chúng ta hoàn toàn có thể sử dụng lời nói (talk) để trực tiếp hướng dẫn kỹ càng cho toàn bộ những người lính (soldiers) của chúng ta thông qua (through) một số quy trình thủ tục y tế (medical procedures) nâng cao (advanced) khi kết nối bộ đàm radio, qua đó sẽ giúp cho bọn họ có thể dễ dàng phục hồi (restoring) lại được hoàn toàn chỉ số sinh lực thể lực (vitality) một cách tối đa (maximum).",
  "Kill a member of your community to prevent them from turning.": "Tiến hành Giết chết (Kill) đi một người thành viên (member) ở trong khu vực cộng đồng (community) căn cứ của bạn để có thể ngăn chặn (prevent) cái việc bọn họ bị biến đổi (turning).",
  "You ready to try this shit again?": "Cậu đã thực sự sẵn sàng (ready) để có thể cùng nhau nếm thử (try) lại toàn bộ cái đống cứt đái (shit) chết tiệt này (again) thêm một lần nữa hay đéo?",
  "Pistol: Automag": "Súng Lục (Pistol): Automag",
  "RECRUITMENT MISSION": "NHIỆM VỤ (MISSION) CHIÊU MỘ TUYỂN DỤNG THÊM THÀNH VIÊN MỚI (RECRUITMENT)",
  "Montressor": "Montressor",
  "Check the Home tab in the Journal.": "Hãy tiến hành kiểm tra (Check) lại phần mục tab Căn Cứ (Home) ở trong bảng Cuốn Sổ Nhật Ký (Journal).",
  "Somebody just showed up asking for you.": "Vừa mới (just) có một kẻ đéo nào đó (Somebody) xuất hiện (showed up) và liên tục tìm kiếm hỏi thăm (asking) cậu đấy.",
  "DECLINED: A Discreet Request": "ĐÃ TỪ CHỐI (DECLINED): Một Yêu Cầu Đề Nghị (Request) Vô Cùng Thận Trọng Và Kín Đáo (Discreet)",
  "Not that we miss him MUCH ...": "Đéo phải (Not) là do chúng tôi cảm thấy nhớ (miss) anh ta đến một mức độ NHIỀU (MUCH) đến như thế đéo đâu...",
  "25 STORY Alice Miller": "25 CỐT TRUYỆN (STORY) Alice Miller",
  "I'm ready when you are.": "Tôi luôn luôn ở trong một tư thế sẵn sàng (ready) bất cứ khi nào (when) mà cậu yêu cầu.",
  "Rust": "Tình Trạng Rỉ Sét (Rust) Bám Bẩn Trầm Trọng",
  "Pills ain't gonna cut it anymore.": "Một vài viên thuốc (Pills) chết tiệt đó sẽ đéo (ain't) thể nào có thể tự giải quyết (cut it) triệt để được mọi vấn đề thêm được nữa (anymore) đâu.",
  "Hand Brake": "Hệ Thống Phanh Hãm (Brake) Cầm Tay (Hand)",
  "When they come, it's gonna be a lot of them. We need to set up defenses where we can. Alright?": "Khi (When) bọn chúng kéo đến (come), chắc chắn (gonna be) sẽ có một số lượng cực kỳ đông đúc khổng lồ (a lot). Chúng ta hiện đang rất cần phải tiến hành thiết lập (set up) ngay một mạng lưới hệ thống phòng thủ (defenses) bảo vệ ở mọi nơi (where) mà chúng ta có thể bao quát được. Cậu nghe rõ rồi chứ (Alright)?",
  "Left flank!": "Bên phía cánh trái (Left flank) kìa!",
  "Hey, let me stop you right there. This is not a rescue mission. The best thing you can do is go home, lock the doors, and shoot anyone paler than your average geek.": "Này, hãy để cho tôi giúp (let me) chặn đứng (stop) cậu lại ở ngay tại đó (right there). Đây hoàn toàn đéo (not) phải là một cái nhiệm vụ đi giải cứu (rescue) đéo nào đâu nhé. Một thứ cực kỳ tuyệt vời (best) nhất mà cậu có thể làm (do) ngay vào lúc này đó chính là lập tức quay trở về nhà (go home), khóa chặt (lock) lại toàn bộ mọi cánh cửa (doors), và bắn (shoot) thẳng vào đầu của bất kỳ một kẻ đéo nào (anyone) trông có vẻ nhợt nhạt trắng bệch (paler) hơn một gã ngốc nghếch (geek) trung bình (average).",
  "Bring the Survivors Home": "Tiến Hành Đưa Dẫn (Bring) Những Người Sống Sót (Survivors) Trở Về Lại Căn Cứ Ngôi Nhà (Home)",
  "Should we...?": "Liệu chúng ta (we) có nên (Should)...?",
  "Just stand by and don't let anyone else die. Doghouse out.": "Chỉ việc tiếp tục đứng chờ đợi (stand by) và đừng bao giờ để cho (don't let) có bất cứ một ai khác (anyone else) phải bỏ mạng (die) nữa. Căn cứ Doghouse kết thúc truyền tin (out).",
  "Hey, you willing to help us find somebody? One of ours is AWOL.": "Này, cậu có sẵn lòng (willing) đồng ý hỗ trợ giúp đỡ (help) cho chúng tôi đi tìm (find) một ai đó (somebody) đéo? Một (One) trong số những người lính của chúng tôi (ours) hiện tại đã hoàn toàn vắng mặt đéo có lý do phép tắc (AWOL) đéo nào cả.",
  "Hey, what if we get attacked? I totally need a gun, right?": "Này, điều đéo gì (what) sẽ xảy ra nếu như (if) chúng ta bất ngờ bị tấn công (attacked)? Tôi hoàn toàn (totally) đang rất cần phải có được một khẩu súng (gun), có đúng đéo (right)?",
  "So. We've had some pretty rough luck lately, huh?": "Vậy là (So). Chúng ta vừa mới gặp phải (had) một vài (some) vận rủi ro xui xẻo (luck) vô cùng tồi tệ thảm hại (rough) ở trong những khoảng thời gian dạo gần đây (lately) cmnr, đúng đéo (huh)?",
  "I've learned some tricks for making less noise when I search stuff.": "Tôi vừa mới học hỏi đúc rút (learned) được một vài thủ thuật (tricks) vô cùng hay ho giúp làm hạn chế đi (less) việc gây ra (making) những tiếng ồn (noise) chết người mỗi khi (when) tôi tiến hành việc đi lục lọi tìm kiếm (search) đồ đạc (stuff).",
  "Oh shit! Run!": "Oh chết tiệt (shit)! Chạy mau (Run)!",
  "I've seen some fucked-up shit, believe me. (Good in an infirmary)": "Tôi đã từng được tận mắt chứng kiến (seen) rất nhiều những thứ (some) thảm họa chết tiệt (fucked-up shit), hãy tin tưởng (believe) ở tôi đi. (Cực kỳ tài giỏi xuất sắc Good trong việc phục vụ ở bên trong khu vực trạm y tế infirmary)",
  "The fuck's that supposed to mean? I volunteered!": "Thế thì cái đó rốt cuộc là có cái ý nghĩa (mean) tởm lợm (fuck's) đéo gì hả? Rõ ràng là tôi đã tự mình tình nguyện (volunteered) xin được tham gia cơ mà!",
  "Rose": "Bông Hoa Hồng (Rose)",
  "Command Center: Medicine Located": "Khu Vực Trung Tâm (Center) Điều Hành Chỉ Huy (Command): Đã Xác Định Lên Định Vị (Located) Được Vị Trí Của Các Loại Nguồn Vật Tư Thuốc Men Y Tế (Medicine)",
  "Hey, I can help clear them out. I'm in the reserves. Trained at Fort Sam Houston.": "Này, tôi hoàn toàn có thể hỗ trợ giúp (help) dọn dẹp càn quét tiêu diệt sạch sẽ (clear out) bọn chúng. Tôi hiện đang là một người lính nằm ở trong hàng ngũ lực lượng dự bị (reserves). Đã từng được huấn luyện đào tạo bài bản (Trained) ở tại khu vực Pháo Đài Căn Cứ (Fort) Sam Houston.",
  "Yeah. Should keep us going for a while longer.": "Yeah. Thứ này chắc chắn sẽ có thể giúp duy trì (keep) cho chúng ta được sống sót bám trụ (going) thêm được trong một khoảng thời gian (while) dài hơn (longer) một chút.",
  "Executive VP for a major software developer. Had an expensive snowboarding habit.": "Đã từng là một Phó Chủ Tịch VP Điều Hành (Executive) chuyên cống hiến cho một tập đoàn nhà phát triển phần mềm (software developer) vô cùng to lớn (major). Có một thói quen (habit) vô cùng đắt đỏ tốn kém (expensive) là chơi bộ môn trượt ván trên nền tuyết (snowboarding).",
  "Bad luck there at the end. You okay?": "Một sự rủi ro xui xẻo (Bad luck) vô cùng tồi tệ lại bất ngờ xuất hiện ở ngay tại lúc cuối cùng (at the end). Cậu vẫn hoàn toàn ổn (okay) chứ?",
  "I've set up a trading opportunity, and I think it'll be quite beneficial.": "Tôi hiện tại vừa mới tiến hành thiết lập (set up) thành công một khu vực dùng để làm cơ hội giao dịch buôn bán trao đổi (trading opportunity), và tôi nghĩ (think) rằng nó chắc chắn sẽ trở nên (it'll be) vô cùng (quite) có lợi và hữu ích (beneficial).",
  "Help destroy a bloated zed.": "Tiến hành Trợ Giúp (Help) trong việc phá hủy tiêu diệt (destroy) một con zed mang thân hình mập mạp béo ú (bloated).",
  "Chemistry Expert: %s": "Chuyên Gia Trong Lĩnh Vực Phản Ứng Hóa Học (Chemistry Expert): %s",
  "Can't say that surprises me.": "Đéo thể nào có thể thốt lên (Can't say) được rằng cái điều đó lại khiến cho tôi cảm thấy ngạc nhiên (surprises) đéo đâu.",
  "Hollis": "Hollis",
  "TRUCK KEYS ACQUIRED.": "HIỆN ĐÃ CHÍNH THỨC THU THẬP TÌM THẤY LẤY ĐƯỢC (ACQUIRED) NHỮNG CHÌA KHÓA DÙNG ĐỂ KHỞI ĐỘNG (KEYS) CHO NHỮNG CHIẾC XE TẢI (TRUCK).",
  "Don't stand too close to one after taking it out. That gas is toxic.": "Tuyệt đối đừng (Don't) bao giờ được phép đứng (stand) ở vị trí quá (too) gần (close) với một cái xác nào đó ngay sau khi (after) vừa mới tiến hành tiêu diệt hạ gục (taking out) nó. Làn khí hơi (gas) đó vô cùng độc hại (toxic) đấy.",
  "Cleared some infestations but Marshall's Police are barely hanging on. -%1$s": "Hiện đã dọn dẹp càn quét tiêu diệt sạch sẽ (Cleared) được một vài (some) những ổ dịch tởm lợm (infestations) chết tiệt thế nhưng (but) Lực Lượng Cảnh Sát (Police) đóng quân ở tại thị trấn Marshall thì hiện tại cũng chỉ đang cố gắng cầm cự bám trụ (hanging on) một cách vô cùng mong manh yếu ớt (barely). -%1$s",
  "Soil Analysis Kit": "Một Bộ Dụng Cụ Phân Tích Mẫu Đất (Soil Analysis Kit)",
  "Damn. Lucky you came along.": "Mẹ kiếp (Damn). Thật may mắn (Lucky) vô cùng vì có cậu cùng đi theo (came along).",
  "If it needs a tune-up, you can bring it home. I'll make sure it gets fixed by tomorrow.": "Nếu như (If) nó thực sự đang rất cần (needs) phải có một cuộc tinh chỉnh (tune-up), cậu hoàn toàn có thể tự mình mang (bring) nó trở về căn cứ ngôi nhà (home) này. Tôi chắc chắn (make sure) sẽ khiến cho nó (gets) được sửa chữa thay thế bảo dưỡng hoàn tất (fixed) trước hạn của ngày mai (tomorrow).",
  "Callsign Sasquatch. High speed, low drag. May have just violated a Bloater.": "Mật Danh Gọi (Callsign) Sasquatch. Một cỗ máy với tốc độ (speed) cực cao (High), sức cản (drag) cực thấp (low). Có thể là vừa mới (just) đập nát xâm phạm hiếp dâm (violated) một con Bloater.",
  "Maybe I jumped the gun a little. Let's stay where we are.": "Có lẽ (Maybe) tôi vừa mới hơi hấp tấp cầm đèn chạy trước ô tô (jumped the gun) một chút. Chúng ta hãy cứ tiếp tục ở lại (stay) ngay tại cái vị trí (where) mà chúng ta đang đứng (we are) nhé.",
  "So I guess you're taking point, huh?": "Vậy là (So) tôi đoán (guess) rằng cậu chính là người chịu trách nhiệm tiên phong dẫn đường (taking point), đúng đéo (huh)?"
};

const file = 'output/languages/chunks/btxt_chunk_208.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_208.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk208[r.sourceText]) {
    r.translatedText = chunk208[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 208 successfully!');
