const fs = require('fs');
const chunk125 = {
  "I was just looking at our medical stockpiles, and we're running very low.": "Tôi vừa xem lại kho dự trữ y tế của chúng ta, và chúng ta đang thiếu hụt trầm trọng.",
  "Cabin": "Căn Nhà Gỗ",
  "No point in taking that.": "Đéo có lý do gì để lấy cái đó cả.",
  "Alcoholic": "Nghiện Rượu",
  "59 GENERIC Gene Evans": "59 GENERIC Gene Evans",
  "35 MIL Pvt Donald Steckler": "35 MIL Binh nhì Donald Steckler",
  "Speakers - Dolby 5,1": "Loa - Dolby 5.1",
  "Supply Lines: Medicine Found": "Đường Dây Tiếp Tế: Đã Tìm Thấy Thuốc Men",
  "We're here. Put as many fences as you can between yourself and the zeds. We'll try to keep you alive.": "Chúng tôi ở đây. Dựng càng nhiều hàng rào giữa cậu và lũ zed càng tốt. Chúng tôi sẽ cố gắng giữ cho cậu sống sót.",
  "No, no no no no, here's good, here's safe, out there, bad!": "Không, không không không không, ở đây tốt, ở đây an toàn, ngoài kia, nguy hiểm!",
  "Charles": "Charles",
  "I agree, but it's not that simple. We have orders, we can't just extract whoever we want.": "Tôi đồng ý, nhưng mọi chuyện đéo đơn giản như vậy. Chúng tôi có mệnh lệnh, chúng tôi đéo thể cứ thế sơ tán bất kỳ ai mình muốn.",
  "Civilian legal carbine in .357 (Sig) caliber.": "Súng carbine hợp pháp cho dân thường cỡ nòng .357 (Sig).",
  "You have 15 minutes remaining in your trial. Press [xi_start] to unlock the full game.": "Bạn còn 15 phút chơi thử. Nhấn [xi_start] để mở khóa toàn bộ trò chơi.",
  "That makes one more asset that this outbreak has brought down.": "Lại thêm một nhân tài nữa gục ngã vì thảm họa này.",
  "ASSET PROFILE: Dr. Thomas Horn": "HỒ SƠ NHÂN SỰ: Tiến sĩ Thomas Horn",
  "We don't get some more food soon, we're gonna start having riots.": "Nếu không sớm kiếm thêm thức ăn, chúng ta sẽ bắt đầu có bạo loạn đấy.",
  "Go to the Ranger Station": "Đến Trạm Kiểm Lâm",
  "<Coughing>": "<Ho>",
  "Full-size rifle round, SMG-size package.": "Đạn súng trường tiêu chuẩn, trong kích thước của súng tiểu liên.",
  "But they must have bailed in a big goddamn hurry to leave all this behind. Let's see if we can get a better look.": "Nhưng chúng hẳn đã phải chuồn trong sự vội vã vãi lồn mới để lại tất cả những thứ này. Hãy xem liệu chúng ta có thể nhìn rõ hơn không.",
  "I heard from a buddy of mine in Marshall the Army rolled up on them and seized all their guns.": "Tôi nghe từ một anh bạn ở Marshall rằng Quân Đội đã ập đến và tịch thu toàn bộ súng ống của họ.",
  "%.1f lbs": "%.1f lbs",
  "No. Even if I thought you could disarm a nuclear weapon, which I don't, I'm not going to risk the entire state for just one town.": "Không. Ngay cả khi tôi nghĩ cậu có thể vô hiệu hóa một vũ khí hạt nhân, mà tôi thì đéo nghĩ thế, tôi cũng sẽ đéo mạo hiểm toàn bộ tiểu bang chỉ vì một thị trấn.",
  "Assault Weapons": "Vũ Khí Tấn Công",
  "We're down to the stragglers now.": "Bây giờ chúng ta chỉ còn lại những kẻ đi lạc thôi.",
  "I almost turned onto the highway to go talk to him in person.": "Tôi suýt nữa đã lái xe ra đường cao tốc để đi nói chuyện trực tiếp với ông ta.",
  "It looks like work's going to be stalled a bit. - %1$s": "Có vẻ như công việc sẽ bị đình trệ một chút. - %1$s",
  "Good scavenging there.": "Nhặt mót được đấy.",
  "Adam came home with bites ... huge bites ... I don't know how he even made it home. His clothes were bright red. Within a few minutes, he had bled out on the living room floor.": "Adam về nhà với những vết cắn ... những vết cắn rất lớn ... Tôi không biết làm thế nào anh ấy có thể về được đến nhà. Quần áo anh đỏ thẫm. Chỉ trong vòng vài phút, anh ấy đã mất máu đến chết ngay trên sàn phòng khách.",
  "Other survivors want to join us.": "Những người sống sót khác muốn tham gia cùng chúng ta.",
  "79 GENERIC Lindsey Carruthers": "79 GENERIC Lindsey Carruthers",
  "Thank you, %1$s. You were a real life-saver back there. - %3$s": "Cảm ơn cậu, %1$s. Cậu thực sự là vị cứu tinh đấy. - %3$s",
  "Damn, you came out of that without a scratch?": "Mẹ kiếp, cậu thoát khỏi đó mà đéo trầy xước chút nào sao?",
  "There is a good kitchen here. Just need to clear out all the chaos and we can start using it as a mess.": "Ở đây có một nhà bếp khá tốt. Chỉ cần dọn dẹp đống lộn xộn này là chúng ta có thể sử dụng nó làm nhà ăn tập thể.",
  "Not worth my time.": "Đéo bõ phí thời gian của tôi.",
  "Check that out.": "Xem cái đó kìa.",
  "Okay, that's all we needed.": "Được rồi, đó là tất cả những gì chúng ta cần.",
  "I need eyes on that.": "Tôi cần có người để mắt tới việc đó.",
  "\"Ugh. Me Lurgh. Me make medicine with fire. Fire good magic. Fire keep saber-tooth tiger away.\" -The guy who made this batch of meds.": "\"Ugh. Ta là Lurgh. Ta chế thuốc bằng lửa. Lửa là phép thuật tốt. Lửa đuổi hổ răng kiếm đi.\" -Thằng cha đã chế ra mớ thuốc này.",
  "Wait 6 minutes for Eldridge to call in.": "Chờ 6 phút để Eldridge gọi điện báo cáo.",
  "%d Freaks Killed": "Đã giết %d Quái thai",
  "Bricks": "Gạch",
  "Sets zeds on fire. They don't seem to like it much. Watch it with this one--it's got a kick.": "Thiêu cháy bọn zed. Chúng có vẻ đéo thích điều đó cho lắm. Cẩn thận với món này--nó giật khá mạnh đấy.",
  "NM.": "NM.",
  "What the hell were you thinking, making noise so close?": "Cậu nghĩ cái quái gì vậy, làm ồn ở khoảng cách gần như thế sao?",
  "Kill 10 Screamers. (Breakdown Level 4 or Higher)": "Giết 10 Screamers. (Breakdown Cấp 4 Trở Lên)",
  "60 GENERIC Vince Meeks": "60 GENERIC Vince Meeks",
  "I think they want to eat us!": "Tôi nghĩ bọn chúng muốn ăn thịt chúng ta!",
  "Workshop": "Xưởng Chế Tạo",
  "I need more than just painkillers.": "Tôi cần nhiều hơn là chỉ vài viên thuốc giảm đau.",
  "Not zombies. Dead people. These folks never turned. No injuries on any of them but a single gunshot, right in the head.": "Không phải zombie. Những người đã chết. Những người này chưa bao giờ bị biến đổi. Không có vết thương nào trên người họ ngoại trừ một phát đạn duy nhất, bắn thẳng vào đầu.",
  "Let's scope this place out.": "Hãy do thám nơi này xem sao.",
  "Good deal.": "Giao kèo tốt đấy.",
  "Trumbull County bought these second hand off the Feds six years ago. They still have great speed and handling. Seats four (two uncomfortably).": "Hạt Trumbull đã mua lại đống xe cũ này từ Cục Liên bang sáu năm trước. Chúng vẫn có tốc độ và khả năng điều khiển tuyệt vời. Bốn chỗ ngồi (hai chỗ hơi chật chội).",
  "NOTE: You rock!": "GHI CHÚ: Cậu đỉnh vãi!",
  "Jeez, you okay? You're not looking so good.": "Trời ạ, cậu ổn chứ? Trông cậu không được khỏe lắm.",
  "Probably waiting to break my leg and steal my haul.": "Chắc là đang chờ để bẻ gãy chân tôi và cướp chiến lợi phẩm của tôi đây mà.",
  "Shotgun: Warden": "Súng Shotgun: Warden",
  "Couldn't risk going into a deathtrap.": "Không thể mạo hiểm bước vào một cái bẫy chết người được.",
  "Should save this til I need an energy boost.": "Nên giữ cái này cho đến khi tôi cần tăng cường năng lượng.",
  "We could check it out.": "Chúng ta có thể đi kiểm tra xem sao.",
  "I could really use someplace high to look around.": "Tôi thực sự cần một nơi nào đó cao ráo để quan sát xung quanh.",
  "Good. That's good. And everybody got those special presents I gave you?": "Tốt. Thế là tốt. Và mọi người đã nhận được những món quà đặc biệt mà tôi đưa chưa?",
  "Argument between Jacob and Lily.": "Cuộc cãi vã giữa Jacob và Lily.",
  "A P226 used by select U.S. military units.": "Một khẩu P226 được sử dụng bởi các đơn vị quân đội Hoa Kỳ tuyển chọn.",
  "I'm going home. I'll see you around.": "Tôi về nhà đây. Hẹn gặp lại sau.",
  "If you knock a zombie down, you need to finish it off.": "Nếu cậu đánh ngã một con zombie, cậu phải kết liễu nó luôn.",
  "Reinsert the storage device, or you may continue without saving and lose any progress made.": "Lắp lại thiết bị lưu trữ, hoặc bạn có thể tiếp tục mà không lưu và mất mọi tiến trình đã thực hiện.",
  "Found next to action figures. Replica.": "Được tìm thấy bên cạnh những mô hình hành động. Chỉ là hàng nhái.",
  "Refills some brass to generate a few magazines' worth of 7.62mm ammunition.": "Đổ đầy lại một số vỏ đạn để tạo ra vài băng đạn 7.62mm.",
  "I need some backup here!": "Tôi cần được tiếp viện ở đây!",
  "You can choose a gun specialization if you haven't already chosen a weapon specialization.": "Bạn có thể chọn một chuyên môn súng nếu bạn chưa chọn chuyên môn vũ khí cận chiến.",
  "Protects against spoilage and opens up new recipes.": "Bảo vệ thức ăn khỏi bị hỏng và mở ra các công thức nấu ăn mới.",
  "TIP: Press [ul_melee_attack] to attack.": "MẸO: Nhấn [ul_melee_attack] để tấn công.",
  "Yeeeeaaaaargh!": "Yeeeeaaaaargh!",
  "Seriously, that was freaking insane! How the hell'd you do that?": "Nghiêm túc đấy, thật sự là điên rồ vãi chưởng! Làm thế đéo nào mà cậu làm được như vậy?",
  "And yet you're out here, violating quarantine, unlawfully occupying people's homes. Great parenting.": "Và thế mà các người lại ở ngoài này, vi phạm lệnh cách ly, chiếm dụng nhà cửa của người khác một cách bất hợp pháp. Làm cha mẹ tuyệt thật đấy.",
  "Contact!": "Chạm trán!",
  "You're a real hero.": "Cậu đúng là một người hùng thực sự.",
  "As far as anybody around here knows, we're kinda nobodies.": "Theo như những gì mọi người quanh đây biết thì, chúng ta chỉ là những kẻ vô danh tiểu tốt.",
  "We don't know he was going to die, Alan!": "Chúng ta đéo biết là anh ấy sẽ chết, Alan!",
  "No Actions Available": "Không Có Hành Động Nào",
  "You got red on you.": "Cậu bị dính máu kìa.",
  "I mean, not that I don't appreciate you coming all this way to find me, but I paid Ray half my weekly food ration for the lead on this place.": "Ý tôi là, không phải tôi không đánh giá cao việc cậu lặn lội đến tận đây để tìm tôi, nhưng tôi đã trả cho Ray một nửa khẩu phần ăn hàng tuần của mình để lấy thông tin về nơi này.",
  "%1$s is contagious. Good thing we decided to keep the sick people in the infirmary. The last thing we need is for half the community to be out of commission.": "%1$s đang mắc bệnh truyền nhiễm. Thật may là chúng ta đã quyết định giữ những người bệnh ở trong bệnh xá. Điều tồi tệ nhất mà chúng ta không hề muốn lúc này là một nửa cộng đồng bị loại khỏi vòng chiến đấu.",
  "Very well. At this point, I'm inclined to trust your judgment.": "Rất tốt. Tại thời điểm này, tôi có xu hướng tin tưởng vào sự phán đoán của cậu.",
  "Let's see anybody ban these bad boys now!": "Hãy xem còn thằng đéo nào dám cấm những món đồ chơi này nữa không!",
  "Shit, you tryin' to get us killed out here?": "Chết tiệt, cậu đang cố giết chết chúng ta ở ngoài này đấy à?",
  "Dr. Thomas Horn doesn't look like he's in the best physical condition, but if his mind is still sharp, he could still help pull us out of this thing.": "Tiến sĩ Thomas Horn có vẻ không có thể trạng tốt nhất, nhưng nếu tâm trí ông ấy vẫn còn minh mẫn, ông ấy vẫn có thể giúp kéo chúng ta ra khỏi mớ hỗn độn này.",
  "Lead on, I'll watch your six.": "Dẫn đường đi, tôi sẽ bọc hậu cho.",
  "I appreciate it.": "Tôi rất cảm kích.",
  "Just follow me. And stay close, I'd rather you didn't get eaten.": "Cứ theo sát tôi. Và đừng có đi lung tung, tôi đéo muốn cậu bị ăn thịt đâu.",
  "Hope that place isn't looted yet.": "Hy vọng nơi đó vẫn chưa bị cuỗm sạch.",
  "Prevents sleep deprivation.": "Ngăn ngừa tình trạng thiếu ngủ.",
  "Meyer": "Meyer",
  "Taking things from their SUPPLY LOCKER will cost less INFLUENCE now.": "Lấy đồ từ TỦ ĐỒ (SUPPLY LOCKER) của họ bây giờ sẽ tốn ít ĐIỂM ẢNH HƯỞNG (INFLUENCE) hơn.",
  "Well, that's just fine. I've got a few more deals to make, but I'll let you know as soon as everything's taken care of.": "Chà, thế cũng tốt. Tôi còn vài giao kèo nữa phải thực hiện, nhưng tôi sẽ báo cho cậu ngay khi mọi thứ được giải quyết ổn thỏa.",
  "Note to self: deals with Job Wilkerson are bad news. - %1$s": "Ghi chú cho bản thân: giao dịch với Job Wilkerson là một tin đéo vui vẻ gì đâu. - %1$s",
  "We don't drive enough for FUEL to be a concern for cars, but we may want it for making firebombs.": "Chúng ta đéo lái xe đủ nhiều để coi NHIÊN LIỆU (FUEL) là mối bận tâm đối với ô tô, nhưng có thể chúng ta sẽ cần nó để chế tạo bom cháy."
};

const file = 'output/languages/chunks/btxt_chunk_125.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_125.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk125[r.sourceText]) {
    r.translatedText = chunk125[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 125 successfully!');
