const fs = require('fs');
const chunk151 = {
  "Sounds like I have a little time to explore. I should probably start looking for the things we'll need to survive. - %1$s": "Có vẻ như tôi có một chút thời gian để khám phá. Chắc tôi nên bắt đầu tìm kiếm những thứ chúng ta cần để sinh tồn. - %1$s",
  "C'mon. Let's go check on Eli.": "Thôi nào. Hãy đi kiểm tra tình hình của Eli.",
  "After one died, the others ran away. - %2$s": "Sau khi một người chết, những kẻ khác đã bỏ chạy. - %2$s",
  "Doc Hanson": "Bác sĩ Hanson",
  "Wouldn't mind some help getting past these assholes.": "Đéo phiền nếu có người giúp tôi vượt qua mấy thằng khốn này đâu.",
  "TIP: Hold [xi_use] to search for supplies or useful items.": "MẸO: Giữ [xi_use] để tìm kiếm nhu yếu phẩm hoặc các vật dụng hữu ích.",
  "Increasingly erratic in his behavior, but not a man to be trifled with.": "Hành vi ngày càng trở nên thất thường, nhưng đéo phải là một kẻ có thể dễ dàng chọc ngoáy.",
  "%d Sasquatch Hunts Completed": "%d Cuộc Săn Cùng Sasquatch Đã Hoàn Thành",
  "Trade 1 Case of Ammunition for 5 Barrels of Fuel.": "Trao đổi 1 Thùng Đạn Dược (Ammunition) lấy 5 Thùng Nhiên Liệu (Fuel).",
  "Lance": "Lance",
  "Coulda been worse.": "Mọi chuyện có thể đã tồi tệ hơn rồi.",
  "We're okay for a little while yet, but we're going to need more food soon.": "Chúng ta vẫn ổn trong một thời gian ngắn nữa, nhưng chúng ta sẽ sớm cần thêm thức ăn thôi.",
  "I'm sorry. I know what this must look like, but I swear I wouldn't leave if it wasn't important. I met some survivors who said they might've seen my sister over in Danforth. I've got to find a way across the river and see if it's really her. Best of luck to you all. - %1$s": "Tôi xin lỗi. Tôi biết chuyện này thoạt nhìn trông như thế nào, nhưng tôi thề là tôi sẽ đéo rời đi nếu nó đéo quan trọng. Tôi đã gặp một số người sống sót, họ nói rằng họ có thể đã nhìn thấy em gái tôi ở Danforth. Tôi phải tìm cách qua sông và xem đó có thực sự là con bé hay đéo. Chúc tất cả các cậu may mắn. - %1$s",
  "Scavenged food isn't gonna last forever. We need to start looking into planting before it gets too cold.": "Thức ăn nhặt mót được sẽ đéo tồn tại mãi mãi đâu. Chúng ta cần bắt đầu xem xét việc gieo trồng trước khi trời trở nên quá lạnh.",
  "How about a sitrep?": "Cho tôi một bản báo cáo tình hình (sitrep) được đéo?",
  "PAYMENT: Special Delivery": "THANH TOÁN: Chuyển Phát Đặc Biệt",
  "Guess this arm gives me some time to brush up on my domestic skills, huh?": "Chắc cái cánh tay này cho tôi chút thời gian để trau dồi lại các kỹ năng nội trợ của mình nhỉ?",
  "Those People": "Những Người Đó",
  "Fire Department": "Sở Cứu Hỏa",
  "I'm spoiling for a fight. How about you?": "Tôi đang rất thèm một trận đánh nhau đây. Cậu thì sao?",
  "I appreciate it. There's a water tower out back that has a good view of the campgrounds. Might be worth your while to climb up there and have a look around first.": "Tôi rất trân trọng điều đó. Có một tháp nước ở phía sau có tầm nhìn rất tốt bao quát khu cắm trại. Cậu nên leo lên đó và nhìn quanh một lượt trước thì hơn.",
  "Gamer Name": "Tên Game Thủ",
  "We opened our doors to feed some outsiders. It was an act of charity. - %1$s.": "Chúng ta đã mở rộng cánh cửa để nhường thức ăn cho một số người ngoài. Đó là một hành động từ thiện. - %1$s.",
  "We failed to extract Hadley Westen. Hopefully his father doesn't hold our screwup against the entire region ... we need his trucks to keep people supplied.": "Chúng ta đã đéo thể giải cứu được Hadley Westen. Hy vọng bố của hắn sẽ đéo vì sự thất bại của chúng ta mà trút giận lên toàn bộ khu vực này ... chúng ta cần xe tải của ông ta để tiếp tục cung cấp nhu yếu phẩm cho mọi người.",
  "Lawson": "Lawson",
  "136 NPC SWAT Officer": "136 NPC Sĩ Quan SWAT",
  "Good thing I'm almost home, cause this is getting heavy.": "Thật may là tôi gần về đến nhà rồi, vì cái này đang bắt đầu nặng lên rồi đây.",
  "It's looking pretty grim.": "Mọi thứ trông có vẻ khá tồi tệ đấy.",
  "Annual Fishing Trip": "Chuyến Đi Câu Cá Thường Niên",
  "Yeah okay... I guess so.": "Ừ được rồi... Tôi đoán vậy.",
  "This whole situation is pretty FUBAR, huh?": "Toàn bộ cái tình huống chết tiệt này đúng là thảm họa, nhỉ?",
  "Scavenged food isn't gonna last forever. We need to start thinking about planting before it gets too cold.": "Thức ăn nhặt mót được sẽ đéo thể kéo dài mãi mãi. Chúng ta cần bắt đầu suy nghĩ về việc gieo trồng trước khi trời trở nên quá lạnh.",
  "Places, people!": "Vào vị trí nào, mọi người!",
  "HISTORY: Got Separated": "LỊCH SỬ: Bị Chia Cắt",
  "Cruz": "Cruz",
  "How to Play": "Cách Chơi",
  "I mean, shit... leaving those people to die like that? Cold, man.": "Ý tôi là, chết tiệt... bỏ mặc những người đó chết như vậy sao? Lạnh lùng quá đấy, anh bạn.",
  "Okaaay.": "Đượccc rồiii.",
  "I got some good canned vegetables here. What'll you give me for them?": "Tôi có vài lon rau củ đóng hộp ngon nghẻ ở đây. Cậu sẽ trả tôi cái gì cho đống này?",
  "We can try sneaking around, but I'd just as soon destroy them now.": "Chúng ta có thể thử lén lút lẻn qua, nhưng tôi thà tiêu diệt chúng ngay bây giờ còn hơn.",
  "Rifle: Micro Dynamic Rifle Scoped": "Súng Trường (Rifle): Súng Trường Micro Dynamic Có Ống Ngắm",
  "FIND HELP": "TÌM KIẾM SỰ GIÚP ĐỠ",
  "ALLIES FLED": "ĐỒNG MINH ĐÃ BỎ CHẠY",
  "Well, I've got mine right here, and I'll share them with the first human being I see. Just come and get me out of here!": "Chà, tôi đang có phần của mình ở ngay đây, và tôi sẽ chia sẻ chúng với người đầu tiên mà tôi nhìn thấy. Làm ơn hãy đến và đưa tôi ra khỏi đây!",
  "You ready for this shit?": "Cậu đã sẵn sàng cho chuyện khốn nạn này chưa?",
  "No survivors.": "Đéo có người sống sót.",
  "Thank God. I was starting to worry this place was going to fall over.": "Tạ ơn Chúa. Tôi đã bắt đầu lo rằng nơi này sắp sụp đổ rồi.",
  "100 STORY Charlene Norville": "100 CỐT TRUYỆN (STORY) Charlene Norville",
  "Need a little nip? Can't say I blame you.": "Cần làm một ngụm đéo? Đéo thể trách cậu được.",
  "If I'm right, we could start growing some higher-yield crops.": "Nếu tôi đoán đúng, chúng ta có thể bắt đầu trồng một số loại cây cho năng suất cao hơn.",
  "Break Open": "Phá Cửa Mở",
  "You stay here, you're dead. Let's go!": "Cậu ở lại đây là cậu chết chắc. Đi thôi!",
  "Reach the LZ": "Đến Khu Vực Hạ Cánh (LZ)",
  "Pile": "Đống Rác (Pile)",
  "Hey, evade attacks as they come in.": "Này, hãy né tránh các đòn tấn công khi chúng lao đến.",
  "Liked to Travel": "Từng Thích Đi Du Lịch",
  "All I know is the chickenshit bitch better not panic when she's watching my back.": "Tất cả những gì tôi biết là cái con khốn nhát cáy đó tốt nhất là đéo nên hoảng loạn khi đang yểm trợ sau lưng tôi.",
  "Thicket": "Bụi Rậm (Thicket)",
  "Law Enforcement": "Thực Thi Pháp Luật",
  "Come on, Lil.": "Thôi nào, Lil.",
  "Grenade Launcher: GL 06 Riot": "Súng Phóng Lựu: Súng Phóng Lựu GL 06 Riot",
  "We're all scared. That's no excuse to not do your fucking job.": "Tất cả chúng ta đều sợ hãi. Đó đéo phải là lý do để cậu đéo làm cái công việc chết tiệt của mình.",
  "Never thought I'd be this hungry in my life.": "Chưa bao giờ tôi nghĩ mình lại đói đến nhường này trong đời.",
  "Get help from the Army.": "Nhận sự giúp đỡ từ Quân đội.",
  "Not yet. I got a whole list of freaks to get through first.": "Vẫn chưa. Tôi còn cả một danh sách lũ quái nhân cần phải giải quyết trước đã.",
  "Got an update on that siege for you--%1$s took care of it. - %2$s": "Cập nhật tình hình vụ bao vây cho cậu đây--%1$s đã giải quyết ổn thỏa rồi. - %2$s",
  "Willoughby": "Willoughby",
  "EXPIRED: Scavengers": "HẾT HẠN: Những Người Nhặt Mót (Scavengers)",
  "Now really isn't a good time. Sorry.": "Bây giờ thực sự đéo phải lúc thích hợp. Xin lỗi nhé.",
  "You know what I had for breakfast today? Half of a frozen hamburger patty. On a plate.": "Cậu biết hôm nay tôi đã ăn gì cho bữa sáng đéo? Một nửa miếng thịt kẹp hamburger đông lạnh. Đặt trên một cái đĩa.",
  "Circular Saw": "Máy Cưa Vòng (Circular Saw)",
  "Need a Strict or Organized Leader.": "Cần một Người Lãnh Đạo Nghiêm Khắc hoặc Có Tổ Chức.",
  "Threaded Pipe Caps": "Nắp Ống Có Ren",
  "Dammit, Becca! When were you going to tell me this?": "Khốn kiếp, Becca! Cô định bao giờ mới nói cho tôi biết chuyện này?",
  "How are you folks holding up?": "Mọi người vẫn trụ vững chứ?",
  "The world still has a purpose, and if we work together, we can still do great things.": "Thế giới này vẫn còn mục đích, và nếu chúng ta cùng nhau cố gắng, chúng ta vẫn có thể làm được những điều lớn lao.",
  "This area was a bust.": "Khu vực này đúng là một nỗi thất vọng.",
  "Benjamin": "Benjamin",
  "She's gone.": "Cô ấy đi rồi.",
  "Too sick.... Left me behind. Left all the sick ones behind.": "Ốm quá nặng.... Họ đã bỏ tôi lại phía sau. Bỏ lại tất cả những người bệnh tật ở lại phía sau.",
  "Get ready.": "Chuẩn bị sẵn sàng đi.",
  "Fuel reserves were looking iffy even before this shit.": "Dự trữ nhiên liệu (Fuel) trông đã khá bất ổn ngay cả trước khi cái đống chết tiệt này xảy ra rồi.",
  "Powell": "Powell",
  "Fuck!": "Chết tiệt!",
  "Veterinary Medical Supplies": "Vật Tư Y Tế Thú Y",
  "Uhh... Lily? I really hope you're at the radio, sis, 'cause I'm in a little trouble here.": "Uhh... Lily? Tôi thực sự hy vọng cô đang trực radio, cô em, vì tôi đang gặp một chút rắc rối ở đây.",
  "You need to harden those defenses, soldier, and keep these assets safe.": "Cậu cần phải củng cố các hệ thống phòng thủ đó đi, người lính, và giữ cho những tài sản này được an toàn.",
  "Zombie Hunt": "Cuộc Săn Zombie",
  "Old bastard's probably dead by now, but apparently I'm a sucker for winos with no teeth and bad gout, because here I am looking for him.": "Lão già khốn kiếp đó có lẽ đã chết ngắc rồi, nhưng rõ ràng tôi là một thằng ngu có hứng thú với những tên bợm rượu đéo còn răng và bị bệnh gút nặng, vì bây giờ tôi đang ở đây tìm kiếm ông ta.",
  "If you ever do something that incredibly stupid again, I will kill you. Okay?": "Nếu cậu còn làm cái trò ngu ngốc đéo thể tin nổi đó một lần nào nữa, tôi sẽ tự tay giết cậu. Rõ chưa?",
  "START MISSION. Go on a road trip with Jacob.": "BẮT ĐẦU NHIỆM VỤ. Đi dạo một vòng bằng ô tô với Jacob.",
  "Saved the day.": "Đã cứu rỗi cả một ngày.",
  "Good news, boss.": "Tin tốt đây, sếp.",
  "Sit tight, we're on the way.": "Cứ ngồi yên đó, chúng tôi đang trên đường tới.",
  "I've got your back.": "Tôi sẽ yểm trợ cậu.",
  "Click [xi_thumbr] to cycle between Mission Opportunities.": "Nhấn [xi_thumbr] để chuyển đổi giữa các Cơ Hội Nhiệm Vụ.",
  "As if that matters now.": "Cứ làm như điều đó có ý nghĩa vào lúc này vậy.",
  "Good news! %1$s found %3$s, and everybody made it home safe and sound. - %2$s": "Tin tốt đây! %1$s đã tìm thấy %3$s, và mọi người đã trở về nhà an toàn. - %2$s",
  "Prepare 12 Snacks. (Breakdown Level 1 or Higher)": "Chuẩn bị 12 Đồ Ăn Vặt (Snacks). (Breakdown Cấp 1 trở lên)",
  "Sara": "Sara"
};

const file = 'output/languages/chunks/btxt_chunk_151.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_151.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk151[r.sourceText]) {
    r.translatedText = chunk151[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 151 successfully!');
