const fs = require('fs');
const chunk107 = {
  "Collection of Do-It-Yourself Pamphlets": "Bộ Sưu Tập Tài Liệu Hướng Dẫn Tự Làm",
  "Know what would make this easier? If we had some medicine. Hell, I'd settle for some allergy pills at this point.": "Biết cái gì sẽ làm chuyện này dễ dàng hơn không? Nếu chúng ta có thuốc men. Chết tiệt, lúc này tôi thà có vài viên thuốc dị ứng còn hơn không.",
  "Later.": "Gặp lại sau.",
  "MISSION: The Vet Clinic": "NHIỆM VỤ: Phòng Khám Thú Y",
  "Now we can grow some food.": "Bây giờ chúng ta có thể trồng trọt chút thức ăn.",
  "Revolver: Model 986": "Súng rulo: Model 986",
  "Rescue High Value Assets": "Giải Cứu Những Người Quan Trọng (High Value Assets)",
  "Seems like we need to break open the armory.": "Có vẻ như chúng ta cần phải phá cửa kho vũ khí.",
  "Memorized Sports Stats": "Thuộc Lòng Số Liệu Thể Thao",
  "The long barrel on this 870 and custom parts make this a very accurate shotgun. Inscribed, \"Gungnir\".": "Nòng dài trên khẩu 870 này và các bộ phận tùy chỉnh khiến nó trở thành một khẩu shotgun rất chính xác. Có khắc chữ \"Gungnir\".",
  "The Judge": "Thẩm Phán",
  "Did I fire six shots, or just five?": "Tôi đã bắn sáu phát, hay chỉ mới năm?",
  "Rescue Madison Grant": "Giải Cứu Madison Grant",
  "ADVICE: Build Training Area": "LỜI KHUYÊN: Xây Dựng Khu Huấn Luyện",
  "Soldier": "Người lính",
  "I can't sneak past all these things.": "Tôi không thể lẻn qua được ngần ấy thứ này.",
  "Baumschlager": "Baumschlager",
  "Keep moving, zeds are on our tail.": "Tiếp tục di chuyển đi, bọn Zed đang bám đuôi chúng ta.",
  "Jesus.": "Chúa ơi.",
  "Yeah, okay. Sure.": "Ừ, được thôi. Chắc chắn rồi.",
  "This is good, right? I mean, it doesn't suck.": "Thế này là tốt, đúng không? Ý tôi là, nó không đến nỗi tệ.",
  "Big Guns": "Súng Hạng Nặng",
  "You just made all kinds of friends, didn't you?": "Cậu vừa kết bạn với đủ mọi thành phần, phải không?",
  "Not sure about that right now.": "Lúc này tôi không chắc về điều đó lắm.",
  "These things aren't too bright, are they?": "Mấy thứ này không được khôn ngoan cho lắm, nhỉ?",
  "Broker the Exchange?": "Làm Môi Giới Trao Đổi?",
  "Royell": "Royell",
  "I fuckin' hate Screamers.": "Tao ghét cay ghét đắng bọn Screamer.",
  "Jasmin": "Jasmin",
  "28 GENERIC Billy Kensenth": "28 GENERIC Billy Kensenth",
  "JOURNAL: The RV is dead.": "NHẬT KÝ: Chiếc xe RV đã hỏng.",
  "Multiple Breaches": "Nhiều Vị Trí Bị Chọc Thủng",
  "Can't help you right now, but don't worry, I haven't forgotten you.": "Tôi không thể giúp cậu lúc này, nhưng đừng lo, tôi chưa quên cậu đâu.",
  "ASSET PROFILE: Madison Grant": "HỒ SƠ NHÂN VẬT: Madison Grant",
  "OUTPOSTS provide a safe destination for missing friends.": "TIỀN ĐỒN (OUTPOST) cung cấp một điểm đến an toàn cho những người bạn bị mất tích.",
  "Make Snacks": "Làm Đồ Ăn Nhẹ (Snack)",
  "Unlocks a more powerful replacement for the shove attack ([xi_use]).": "Mở khóa một đòn thế mạnh mẽ hơn thay thế cho đòn đẩy lùi ([xi_use]).",
  "I am...in position.": "Tôi... đã vào vị trí.",
  "Hey, why don't you and I take a walk?": "Này, tại sao cậu và tôi không đi dạo một lát nhỉ?",
  "You can become Friends with many characters in the game after earning their full Trust. Your level of Trust with each character is represented by the green gauge. You can earn Trust with characters by helping them out on Missions and keeping the Community defended and well provisioned.\r\nWhen a character becomes your Friend you can play as that character by highlighting his or her portrait and pressing [ui_x] to \"Switch to...\"": "Bạn có thể trở thành Bạn Bè (Friend) với nhiều nhân vật trong game sau khi đạt được tối đa Niềm tin (Trust) từ họ. Mức độ Niềm tin của bạn với mỗi nhân vật được thể hiện bằng thanh màu xanh lá cây. Bạn có thể kiếm Niềm tin bằng cách giúp đỡ họ trong các Nhiệm Vụ và bảo vệ Cộng đồng cũng như cung cấp đủ nhu yếu phẩm.\r\nKhi một nhân vật trở thành Bạn của bạn, bạn có thể nhập vai nhân vật đó bằng cách chọn chân dung của họ và nhấn [ui_x] để \"Chuyển sang...\" (Switch to...)",
  "Leapfrog": "Nhảy Cóc",
  "That was good.": "Làm tốt lắm.",
  "Helped some folks with a supply run. -%1$s": "Đã giúp vài người trong một chuyến tìm kiếm nhu yếu phẩm. -%1$s",
  "I shouldn't.": "Tôi không nên.",
  "You know there ain't no civilians who can roll up on a horde and just clear it out for these people! It's us or nobody!": "Cậu biết thừa là không có thường dân nào có thể xông vào một bầy zombie và dọn sạch chúng cho những người này đâu! Chỉ có chúng ta hoặc không ai cả!",
  "Terry": "Terry",
  "We need to get folks trained up so that doesn't happen again.": "Chúng ta cần huấn luyện mọi người để chuyện đó không xảy ra nữa.",
  "Ana": "Ana",
  "New Facility! Upgrade your Workshop to an Ammunition Shop to allow you to craft the specific calibers you need from your Ammo resource.": "Cơ sở mới! Nâng cấp Xưởng (Workshop) của bạn thành Cửa Hàng Đạn Dược (Ammunition Shop) để cho phép bạn chế tạo các loại đạn cụ thể từ tài nguyên Đạn (Ammo).",
  "Rivera": "Rivera",
  "Yeah. Better keep an eye on her.": "Ừ. Tốt hơn là để mắt đến cô ta.",
  "%1$s left the community": "%1$s đã rời khỏi cộng đồng",
  "Nothing. Just, you know... bad luck with the army. Sorry.": "Không có gì. Chỉ là, cậu biết đấy... xui xẻo với quân đội. Xin lỗi.",
  "Want to come with? Do some trading?": "Muốn đi cùng không? Trao đổi chút đồ?",
  "You mean aside from being lost in the woods, attacked by psychopaths, and watching two of my best friends die?": "Ý anh là ngoài việc bị lạc trong rừng, bị tấn công bởi những kẻ tâm thần, và phải chứng kiến hai người bạn thân nhất của mình chết á?",
  "Not much on the radio to fill the time.": "Không có gì nhiều trên radio để giết thời gian cả.",
  "This next-generation rifle has an integrated optics package.": "Khẩu súng trường thế hệ mới này có tích hợp sẵn gói ống ngắm quang học.",
  "Oh my God oh my God oh my God oh my God....": "Lạy Chúa lạy Chúa lạy Chúa lạy Chúa....",
  "Little... closer...": "Gần... hơn chút nữa...",
  "Electrical Leads": "Dây Điện",
  "XP penalty from Dim Bulb.": "Bị trừ XP do đặc điểm Bóng Đèn Mờ (Dim Bulb).",
  "You've got to think about defense too. Can't just wade in like that.": "Cậu cũng phải nghĩ đến phòng thủ nữa chứ. Không thể cứ xông vào như thế được.",
  "I guess I'll just wait here then.": "Vậy chắc tôi sẽ đợi ở đây.",
  "(Brigadier General Henry Connors)": "(Chuẩn tướng Henry Connors)",
  "48 VIP Shira Bogatz": "48 VIP Shira Bogatz",
  "I was just thinking about a few of my buddies who were on leave when all this hit.": "Tôi chỉ đang nghĩ về vài người bạn chiến đấu đang nghỉ phép khi mọi chuyện xảy ra.",
  "Glad to see a few others made it this long.": "Rất vui khi thấy có người khác sống sót được lâu đến thế này.",
  "Burns": "Vết Bỏng",
  "You throw it. It goes boom. If you're lucky, not right in your face.": "Cậu ném nó. Nó nổ bùm. Nếu cậu may mắn, thì không phải là nổ ngay vào mặt cậu.",
  "Becca?! What's going on?": "Becca?! Có chuyện gì đang xảy ra vậy?",
  "Well, at least somebody's got our six.": "Chà, ít nhất cũng có người yểm trợ phía sau cho chúng ta.",
  "And the crowd goes wild!": "Và đám đông bắt đầu phát cuồng!",
  "JOURNAL: Safe Haven": "NHẬT KÝ: Nơi Trú Ẩn An Toàn",
  "147 STORY Maya Torres": "147 STORY Maya Torres",
  "Raymond": "Raymond",
  "FOOD RESOURCE. All foods that don't need to be refrigerated.": "TÀI NGUYÊN THỨC ĂN (FOOD). Bao gồm tất cả các loại thức ăn không cần bảo quản lạnh.",
  "When we picked up Sergeant Eldridge, he was down in that tunnel. He said he was hunting a screamer, but ... I'm starting to wonder if something else was going on.": "Khi chúng ta tìm thấy Trung sĩ Eldridge, anh ta đang ở dưới đường hầm đó. Anh ta nói mình đang săn một con screamer, nhưng... tôi bắt đầu tự hỏi liệu có chuyện gì khác đang xảy ra không.",
  "Old-School Muscle": "Sức Mạnh Cổ Điển",
  "Used to Rob Houses": "Từng Đi Ăn Trộm Nhà",
  "Y'know, that cheesy place down in the Valley, with the highway signs that you thought were so cool when you were a kid?": "Cậu biết cái nơi sến súa dưới Thung Lũng không, với mấy cái biển báo trên đường cao tốc mà cậu từng nghĩ là rất ngầu khi còn nhỏ ấy?",
  "Shaka, brah!": "Shaka, người anh em!",
  "We keep losin' outposts like that, shit's gonna get bad fast.": "Cứ mất tiền đồn kiểu đó hoài thì tình hình sẽ tồi tệ nhanh lắm đấy.",
  "Play Game": "Chơi Game",
  "CONTACT: Call for Scavengers": "LIÊN LẠC: Gọi người đi Thu Thập",
  "Received. Highroad out.": "Đã nhận. Highroad, hết.",
  "Wait until later to ask.": "Đợi lúc khác hãy hỏi.",
  "The rest of the ammo you're owed. That should clear up the debt.": "Số đạn còn lại mà chúng tôi nợ cậu. Thế là xong nợ nần nhé.",
  "We're all that's left of our unit. We could use some orders, sir.": "Chúng tôi là tất cả những gì còn sót lại của đơn vị. Chúng tôi cần nhận mệnh lệnh, thưa ngài.",
  "Cash": "Cash",
  "Spotted an unusual one.": "Phát hiện một con bất thường.",
  "Actually, we're pretty close.": "Thực ra thì, chúng ta khá gần đấy.",
  "Do you like fighting these big freaks? 'Cause you not following directions means we have to find another one.": "Cậu có thích đánh nhau với mấy con quái vật to xác này không? Bởi vì nếu cậu không nghe theo chỉ dẫn, chúng ta sẽ phải tìm một con khác đấy.",
  "Vince": "Vince",
  "SUPPLY RUN: Food Acquired": "TÌM NHU YẾU PHẨM: Đã Tìm Thấy Thức Ăn",
  "We're not going to make it without more ammunition.": "Chúng ta sẽ không thể vượt qua nếu không có thêm đạn dược.",
  "Petrol Bomb": "Bom Xăng",
  "Stay away! Just stay away!": "Tránh xa tôi ra! Tránh xa ra!",
  "Look, there's a helo about to touch down at your location. Gather everybody who's still alive, and put them on it.": "Nghe này, có một chiếc trực thăng sắp đáp xuống vị trí của cậu. Tập hợp tất cả những người còn sống và đưa họ lên đó.",
  "Sounds like the situation out there has changed.": "Có vẻ như tình hình ngoài kia đã thay đổi.",
  "Top Chef: %s": "Đầu Bếp Siêu Đẳng: %s"
};

const file = 'output/languages/chunks/btxt_chunk_107.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_107.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk107[r.sourceText]) {
    r.translatedText = chunk107[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 107 successfully!');
