const fs = require('fs');
const chunk118 = {
  "Our CO will provide benefits to the entire unit based on their individual leadership style.": "Chỉ huy (CO) của chúng ta sẽ mang lại các lợi ích cho toàn bộ đơn vị dựa trên phong cách lãnh đạo cá nhân của họ.",
  "That's one.": "Đó là một.",
  "COMPLETED: Anger Management": "ĐÃ HOÀN THÀNH: Kiềm Chế Cơn Giận",
  "New Storage facility action added temporarily.": "Hành động cho Cơ sở Lưu trữ (Storage) mới đã được thêm tạm thời.",
  "Saw some creepy dude hanging out by the public restrooms. He looked drunk. Maybe stoned. Stank too. Gross. I decided to hold it.": "Tôi thấy một gã đáng sợ lảng vảng gần nhà vệ sinh công cộng. Trông hắn như say xỉn. Hoặc có thể là phê thuốc. Lại còn hôi nữa chứ. Gớm ghiếc. Thế nên tôi quyết định nhịn luôn.",
  "I'm okay. The fatigue's getting worse, though.": "Tôi ổn. Dù vậy sự mệt mỏi ngày càng tệ hơn.",
  "Ugly Scar": "Vết Sẹo Xấu Xí",
  "RESCUED: Dr. Thomas Horn": "ĐÃ GIẢI CỨU: Tiến sĩ Thomas Horn",
  "Sheesh, she's got a temper on her, huh?": "Chà, cô ta nóng tính thật đấy nhỉ?",
  "Increases likelihood of penalties on opposing team.": "Tăng khả năng bị phạt cho đội đối phương.",
  "Did her part, despite adversity.": "Đã làm tốt phần việc của mình, bất chấp nghịch cảnh.",
  "A sanitary latrine is the key to a healthy base. Or so they tell us. We wouldn't know from experience.": "Một nhà vệ sinh sạch sẽ là chìa khóa cho một căn cứ khỏe mạnh. Hoặc là họ bảo chúng ta vậy. Chứ chúng ta thì làm đéo gì có kinh nghiệm.",
  "Whoa boy! Left side, left side!": "Ái chà chàng trai! Bên trái, bên trái!",
  "You think you scare me?": "Mày nghĩ mày dọa được tao chắc?",
  "You must resolve key conflicts before exiting.": "Bạn phải giải quyết các xung đột chính trước khi thoát.",
  "Go ahead, you're on the air.": "Nói đi, cậu đang trên sóng phát thanh đấy.",
  "Watch it, zeds at six o'clock.": "Coi chừng, có zed ở hướng sáu giờ (phía sau).",
  "Fire hot! use a poker.": "Lửa nóng lắm! Hãy dùng một cái que khều.",
  "Harlow": "Harlow",
  "Apparently, I didn't pull my weight. - %1$s": "Rõ ràng là tôi đã không làm tròn phần việc của mình. - %1$s",
  "Some weird rumors have been going around on the radio. People getting beaten up, robbed, stuff like that.": "Có vài tin đồn kỳ lạ đang lan truyền trên radio. Mọi người bị đánh đập, cướp bóc, những thứ đại loại thế.",
  "Right. Wouldn't want me to go and get something done.": "Phải rồi. Sẽ chẳng muốn tôi đi làm bất cứ việc gì có ích đâu.",
  "Go Out in a Blaze of Glory. (Breakdown Level 1 or Higher)": "Ra Đi Trong Ánh Hào Quang. (Cấp độ Breakdown 1 trở lên)",
  "United Nations refuses to lift international air travel ban.\r\nAmerican personnel stationed overseas still unable to return home.": "Liên Hiệp Quốc từ chối dỡ bỏ lệnh cấm di chuyển hàng không quốc tế.\r\nNhân viên Mỹ đóng quân ở nước ngoài vẫn chưa thể trở về nhà.",
  "Thank you for picking up the Prepper's Pack! Select this option to have a new SUV delivered near your home, and a new rifle and axe delivered to your supply locker.": "Cảm ơn bạn đã nhận Gói Người Chuẩn Bị (Prepper's Pack)! Chọn tùy chọn này để được giao một chiếc SUV mới gần nhà, cùng một khẩu súng trường và rìu mới vào tủ đồ của bạn.",
  "I don't know. Yeah. I guess zombie's as good a word as any.": "Tôi không biết nữa. Ừ. Tôi đoán từ zombie là từ mô tả đúng nhất rồi.",
  "She really cared, not just about surviving, but about doing the right thing.": "Cô ấy thực sự quan tâm, không chỉ là sống sót, mà là làm điều đúng đắn.",
  "Upgrade to Solar": "Nâng Cấp Lên Năng Lượng Mặt Trời (Solar)",
  "Terrance": "Terrance",
  "They're on the left!": "Chúng ở bên trái kìa!",
  "I wouldn't mind help getting past these assholes.": "Tôi không phiền nếu có người giúp vượt qua lũ khốn này đâu.",
  "Study regimen assigned!": "Chế độ học tập đã được chỉ định!",
  "Layla": "Layla",
  "Anyway, they ran out of room in their infirmary, so they started putting the sick anywhere they could find room. Including a certain warehouse.": "Dù sao thì, bệnh xá của họ hết chỗ, nên họ bắt đầu đặt người bệnh ở bất cứ nơi nào có thể. Bao gồm cả một cái nhà kho nọ.",
  "The very last piece of a secret weapon that'll kill all the zeds and return the world to normal.": "Mảnh ghép cuối cùng của một loại vũ khí bí mật sẽ giết chết tất cả đám zed và đưa thế giới trở lại bình thường.",
  "Her friends used to make fun of her annual trip to the Renaissance Faire. They're not laughing anymore.": "Bạn bè thường trêu chọc việc cô ấy đi Hội chợ Phục hưng hàng năm. Giờ thì họ không còn cười được nữa đâu.",
  "Here you go. Just in case.": "Của cậu đây. Phòng hờ thôi.",
  "Gas Powered": "Chạy bằng xăng",
  "Eriksen": "Eriksen",
  "That doesn't fuckin' suck.": "Chuyện đó đéo tệ chút nào đâu.",
  "SURVIVAL TACTICS: To the Pain": "CHIẾN THUẬT SINH TỒN: Cho Đến Khi Đau Đớn",
  "So. You were up on Mt. Tanner the day you found us.": "Vậy. Cậu đã ở trên Núi Tanner vào cái ngày cậu tìm thấy chúng tôi.",
  "Factory": "Nhà máy",
  "Besse": "Besse",
  "Medical Clinic": "Phòng Khám Y Tế",
  "Good call. Discretion is the better part of valor.": "Quyết định hay đấy. Cẩn trọng là phần tốt nhất của lòng dũng cảm mà.",
  "I need support here!": "Tôi cần hỗ trợ ở đây!",
  "Dammit! This place was supposed to have a closet full of first aid kits! I swear, if that son of a bitch lied to me, I....": "Chết tiệt! Đáng lẽ nơi này phải có một cái tủ chứa đầy hộp sơ cứu chứ! Tôi thề, nếu thằng chó đẻ đó lừa tôi, tôi sẽ....",
  "I'm not sure yet.": "Tôi vẫn chưa chắc chắn.",
  "Dead people are walking around now? There goes my business. (Counseling experience.)": "Giờ thì người chết đang đi lại lung tung sao? Công việc kinh doanh của tôi tiêu tùng rồi. (Có kinh nghiệm tư vấn.)",
  "Don't let them in!": "Đừng để chúng vào!",
  "START MISSION. Do what you said you were going to do.": "BẮT ĐẦU NHIỆM VỤ. Hãy làm những gì bạn nói bạn sẽ làm.",
  "Walton": "Walton",
  "I feel like somebody should say something, I just… God, what do you say in a situation like this?": "Tôi cảm thấy ai đó nên nói điều gì đó, tôi chỉ… Chúa ơi, cậu sẽ nói gì trong một tình huống như thế này chứ?",
  "Failed to extract our fellow soldiers.": "Thất bại trong việc giải cứu những người lính đồng đội của chúng ta.",
  "Reload": "Nạp đạn",
  "HOME: Outpost Arrival": "NHÀ: Đã Đến Tiền Đồn (Outpost)",
  "Hudson": "Hudson",
  "We had a little help.": "Chúng tôi đã có một chút trợ giúp.",
  "I hate to ask, but... help?": "Tôi rất ghét phải mở lời, nhưng... giúp tôi được không?",
  "I'll help. They could be in real trouble.": "Tôi sẽ giúp. Họ có thể đang thực sự gặp rắc rối.",
  "We need someone to step up and eliminate one of those hordes.": "Chúng ta cần ai đó đứng lên và tiêu diệt một trong những bầy horde đó.",
  "Stoffler": "Stoffler",
  "I've located some supplies.": "Tôi đã định vị được vài món đồ tiếp tế.",
  "Dammit! This place was supposed to have a closet full of first aid kits! If that son of a bitch lied to me....": "Chết tiệt! Đáng lẽ nơi này phải có một cái tủ chứa đầy hộp sơ cứu chứ! Nếu thằng chó đẻ đó mà lừa tôi....",
  "Thin the Herd: Marginal Success": "Thanh Trừng Bầy Đàn (Thin the Herd): Thành Công Vừa Phải",
  "That's it, we're leaving.": "Thế là đủ rồi, chúng ta đi thôi.",
  "Food Allergies": "Dị ứng thực phẩm",
  "I don't fuckin' need this NOW.": "Tao ĐÉO cần thứ này BÂY GIỜ.",
  "Maybe everyone else's been a little too sensitive lately.": "Có lẽ dạo gần đây mọi người hơi quá nhạy cảm.",
  "Utensils": "Đồ dùng nhà bếp",
  "Reward: %s %s": "Phần thưởng: %s %s",
  "If we don't get somebody with real experience in the infirmary, this shit's never gonna get better.": "Nếu chúng ta không tìm được ai đó có kinh nghiệm thực sự cho bệnh xá, tình trạng khốn kiếp này sẽ không bao giờ khá hơn được.",
  "Hey, I'm not greedy. You help me out and half of everything we get is yours.": "Này, tôi không tham lam đâu. Cậu giúp tôi và một nửa số chiến lợi phẩm thu được sẽ là của cậu.",
  "Hello? This thing on, or are you just ignoring our generous offer to risk life and limb for your country?": "Alo? Cái thứ này có đang bật không đấy, hay là các người đang cố lờ đi lời đề nghị hào phóng mạo hiểm tính mạng và tay chân vì đất nước của các người hả?",
  "%1$s has lost track of the Bloater. We missed a chance to bring down the zombie population and delay the next siege.": "%1$s đã mất dấu con Bloater. Chúng ta đã bỏ lỡ cơ hội làm giảm bớt số lượng zombie và trì hoãn cuộc bao vây tiếp theo.",
  "Kind": "Tốt bụng",
  "I got a thought, how 'bout somebody get off their ass and do some recon!": "Tôi có một ý này, sao không có ai đó nhấc mông lên và đi trinh sát chút đi nhỉ!",
  "That's what I'm looking for, soldier. Welcome home. Highroad out.": "Đó là những gì tôi đang tìm kiếm, người lính. Chào mừng về nhà. Highroad kết thúc liên lạc.",
  "My family's got deep roots in this town. My grandpa started with nothing but the deed to a few dozen acres of empty wilderness and spun it into a lumber empire that put all four of his kids through college.": "Gia đình tôi có gốc rễ lâu đời ở thị trấn này. Ông tôi bắt đầu từ hai bàn tay trắng với giấy chứng nhận vài chục mẫu đất hoang dã và biến nó thành một đế chế gỗ, đủ để nuôi cả bốn người con học xong đại học.",
  "51 GENERIC Bethany Olmstead": "51 GENERIC Bethany Olmstead",
  "Gain +3 AMMO to train survivors from another community with firearms.": "Nhận +3 ĐẠN DƯỢC (AMMO) để huấn luyện cách sử dụng súng cho những người sống sót từ một cộng đồng khác.",
  "SUPPLY RUN: Fuel Acquired": "CHUYẾN ĐI LẤY ĐỒ: Đã Lấy Được Nhiên Liệu",
  "Dammit, who built that shitty barricade!": "Chết tiệt, đứa nào đã dựng cái rào chắn khốn nạn đó lên vậy!",
  "Can somebody draw these fuckers away?": "Có ai dụ mấy con khốn này ra chỗ khác được không?",
  "I see something at three o'clock.": "Tôi thấy thứ gì đó ở hướng ba giờ.",
  "All right….": "Được rồi….",
  "Now don't judge me, all right? I've got useful stuff here... and I'll share it if you get me out of here.": "Bây giờ đừng phán xét tôi, được chứ? Tôi có vài thứ hữu ích ở đây... và tôi sẽ chia sẻ chúng nếu các người đưa tôi ra khỏi đây.",
  "You gotta help them! Please!": "Cậu phải giúp họ! Làm ơn!",
  "I don't know which end it's worse coming out of right now, but this really isn't pretty.": "Tôi không biết bên nào tồi tệ hơn khi chui ra lúc này, nhưng tình hình thực sự không ổn chút nào.",
  "Michele Martin is dead": "Michele Martin đã chết",
  "Black Friday, I need one of your people to catalog the supplies you've gathered from these \"Cleo\" drops, and report back.": "Black Friday, tôi cần một người của cậu phân loại các nhu yếu phẩm các cậu thu thập được từ những lần thả hàng \"Cleo\" này, và báo cáo lại.",
  "I'm gonna wreck your shit and look good doing it!": "Tao sẽ đập nát bét mày và trông thật ngầu khi làm điều đó!",
  "Maxed out a community member's Wits skill.": "Đã đạt tối đa kỹ năng Trí Tuệ (Wits) của một thành viên trong cộng đồng.",
  "Sorry for the interruption.": "Xin lỗi vì sự gián đoạn.",
  "Bonus Vitality": "Thưởng Sinh Lực (Vitality)",
  "You got this?": "Cậu lo được vụ này không?",
  "I think I just found more survivors.": "Tôi nghĩ là tôi vừa tìm thấy thêm vài người sống sót.",
  "Oscar-Mike.": "Oscar-Mike.",
  "They never get tired, but you don't have to pretend you don't. You need rest.": "Bọn chúng không bao giờ biết mệt, nhưng bạn không cần phải cố tỏ ra là mình cũng vậy đâu. Bạn cần phải nghỉ ngơi."
};

const file = 'output/languages/chunks/btxt_chunk_118.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_118.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk118[r.sourceText]) {
    r.translatedText = chunk118[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 118 successfully!');
