const fs = require('fs');
const chunk135 = {
  "I don't know, man. Doesn't make sense.": "Tôi đéo biết nữa, anh bạn. Đéo hợp lý chút nào.",
  "Faith": "Niềm tin",
  "Airtight Bags": "Túi Kín Khí",
  "Cover your six, Greyhound.": "Cẩn thận phía sau kìa, Greyhound.",
  "We've found Doctor Horn's crash site, and it's ugly. But until we find his body, we're holding out hope that he might have survived.": "Chúng tôi đã tìm thấy hiện trường vụ tai nạn của Bác sĩ Horn, và nó rất tồi tệ. Nhưng cho đến khi tìm thấy xác của ông ấy, chúng tôi vẫn nuôi hy vọng rằng ông ấy có thể đã sống sót.",
  "Little closer... little closer... fuck you!": "Gần thêm chút nữa... gần thêm chút nữa... đụ má mày!",
  "Listen, whatever the problem is, you need to knock that shit off. You're starting to freak out the others.": "Nghe này, bất kể vấn đề là gì, cậu cần phải dừng cái trò đó lại. Cậu đang bắt đầu làm người khác hoảng sợ rồi đấy.",
  "Need to head home and rest. Eating won't help.": "Cần phải về nhà và nghỉ ngơi. Ăn uống đéo giúp ích gì đâu.",
  "Wine should have a vintage. Clothing can be vintage. Antibiotics should not be vintage. -%1$s": "Rượu nên có tuổi đời. Quần áo có thể là đồ cổ. Thuốc kháng sinh đéo nên có tuổi đời. -%1$s",
  "116 STORY Jackson Hollis": "116 STORY Jackson Hollis",
  "My best friend growing up was this kid named Danny Morse. His family, they were fucking loaded--I think they owned a bunch of real estate or something.": "Bạn thân nhất thuở nhỏ của tôi là một thằng nhóc tên Danny Morse. Gia đình nó, bọn họ giàu nứt đố đổ vách--tôi nghĩ họ sở hữu một đống bất động sản hay đại loại thế.",
  "I can't carry everything, and I don't want it to go to waste.": "Tôi đéo thể mang theo tất cả mọi thứ được, và tôi cũng đéo muốn để nó lãng phí.",
  "Dude, I don't even know if I like you any more.": "Anh bạn, tôi thậm chí còn đéo biết mình có còn mến cậu nữa hay đéo.",
  "HOME: Wipeout": "CĂN CỨ: Xóa Sổ",
  "Spotted something interesting. There should be some useful stuff there.": "Phát hiện ra thứ gì đó thú vị. Chắc chắn sẽ có vài thứ hữu ích ở đó.",
  "I'm trying to avoid combat, but it's difficult.": "Tôi đang cố gắng tránh giao tranh, nhưng khó quá.",
  "Hell with that! We ain't got time for half-asses and lollygaggers. We need boys we can rely on.": "Chết tiệt với chuyện đó đi! Chúng ta đéo có thời gian cho những kẻ làm việc nửa vời và lười biếng đâu. Chúng ta cần những người anh em có thể tin tưởng được.",
  "I'm too exhausted, food won't cut it.": "Tôi quá kiệt sức rồi, thức ăn đéo giải quyết được đâu.",
  "Hey, it's not my fault! %2$s keeps trimming {[2:mn]his}{[2:f]her} toenails while I'm trying to eat. It's sick!": "Này, đéo phải lỗi của tôi! %2$s cứ cắt móng chân của {[2:mn]anh ấy}{[2:f]cô ấy} trong lúc tôi đang cố ăn. Thật tởm lợm!",
  "Oh, yes sir.": "Ồ, vâng thưa sếp.",
  "The straight dope from the Windy City": "Hàng chuẩn từ Thành phố lộng gió (Windy City)",
  "Hold on!": "Khoan đã!",
  "He's been really moody ever since Eli died. He won't talk to me about it.": "Anh ấy đã rất buồn rầu kể từ khi Eli chết. Anh ấy đéo chịu nói chuyện với tôi về điều đó.",
  "Look, the infirmary's no damn good if we don't have somebody to run it.": "Nghe này, bệnh xá sẽ vô dụng nếu đéo có ai quản lý nó.",
  "FAILED: Indefensible": "THẤT BẠI: Đéo thể phòng thủ",
  "It's not safe here! Too many zeds around.": "Ở đây đéo an toàn đâu! Có quá nhiều zed quanh đây.",
  "Experimental revolver style shotgun from CLEO.": "Shotgun kiểu ổ xoay thử nghiệm từ CLEO.",
  "SUPPLY RUN: Ammo Acquired": "CHẠY TIẾP TẾ: Đã Thu Thập Đạn Dược",
  "We've stopped receiving transmissions from the civilian that Vienna Cho directed us to. They are presumed dead. It hurts when you know you can't save everyone. I really hope we made the right call.": "Chúng tôi đã mất liên lạc với người dân mà Vienna Cho chỉ định cho chúng tôi. Họ được cho là đã chết. Thật đau đớn khi bạn biết mình đéo thể cứu tất cả mọi người. Tôi thực sự hy vọng chúng ta đã quyết định đúng.",
  "Mission?": "Nhiệm vụ à?",
  "Mueller": "Mueller",
  "What do you say? You'll get a cut of the deal, of course - provided it all goes according to plan.": "Cậu thấy sao? Cậu sẽ được chia phần trong thương vụ này, tất nhiên - miễn là mọi chuyện diễn ra theo đúng kế hoạch.",
  "Carlos": "Carlos",
  "Just acquired a stash of military style weapons and I feel like sharing. Benefits of being on my good side. - Mickey Wilkerson": "Vừa kiếm được một mẻ vũ khí quân dụng và tôi thấy muốn chia sẻ đây. Lợi ích khi đứng về phía tôi đấy. - Mickey Wilkerson",
  "REWARD. An attractively branded sportscar, delivered near your current location.": "PHẦN THƯỞNG. Một chiếc xe hơi thể thao mang thương hiệu hấp dẫn, được giao đến gần vị trí hiện tại của bạn.",
  "He always had a good head on his shoulders. If he was in trouble, he would've tried to get inside, fortify someplace till we came looking.": "Cậu ấy luôn rất tỉnh táo. Nếu gặp rắc rối, cậu ấy sẽ cố gắng lẻn vào trong, gia cố một nơi nào đó cho đến khi chúng ta đến tìm.",
  "New developments.": "Những diễn biến mới.",
  "Matthew": "Matthew",
  "Good for making and repairing stuff.": "Rất hữu ích để chế tạo và sửa chữa đồ đạc.",
  "Blessed is the Lord.": "Ngợi khen Đức Chúa Trời.",
  "Roger that, Black Friday, you've earned a rest. The next helo is yours. Highroad out.": "Rõ rồi, Black Friday, các anh đã xứng đáng được nghỉ ngơi. Chuyến trực thăng tiếp theo là của các anh. Highroad hết.",
  "Menard": "Menard",
  "Need me to come along?": "Cần tôi đi cùng đéo?",
  "Switch Camera": "Chuyển Đổi Góc Nhìn",
  "Save Created": "Đã Tạo Bản Lưu",
  "I think she's really depressed.": "Tôi nghĩ cô ấy thực sự đang trầm cảm.",
  "I will fuck you up!": "Tao sẽ đập mày nát nhừ!",
  "Let's have a look around here.": "Hãy xem quanh đây có gì nào.",
  "We appreciate everything you've done for us. - Your neighbor, %1$s": "Chúng tôi trân trọng mọi điều cậu đã làm cho chúng tôi. - Người hàng xóm của cậu, %1$s",
  "Outpost": "Tiền đồn",
  "I think we should experiment with a little noise discipline.": "Tôi nghĩ chúng荨ra nên thử nghiệm kỷ luật tiếng ồn một chút.",
  "Time to bail. Let's get the RV packed.": "Đến lúc chuồn rồi. Hãy thu dọn chiếc xe RV thôi.",
  "Adam": "Adam",
  "Find your problems, and fix them. Highroad out.": "Tìm ra vấn đề của các anh, và tự giải quyết chúng đi. Highroad hết.",
  "Fishing before dawn is awesome, except when you were up till three the night before. Where the hell does Ed put all that whiskey? - %1$s": "Câu cá trước bình minh rất tuyệt, ngoại trừ việc cậu phải thức đến tận ba giờ sáng đêm hôm trước. Ed giấu đống rượu whiskey đó ở cái xó xỉnh chó đẻ nào vậy? - %1$s",
  "Change Storage Location": "Thay Đổi Vị Trí Kho Lưu Trữ",
  "Foodie": "Người Sành Ăn",
  "Yeah. Just seems like we can't catch a break.": "Phải. Có vẻ như chúng ta đéo thể ngơi nghỉ chút nào.",
  "Get in there and help them!": "Vào đó và giúp họ đi!",
  "Got some stuff we could use as weapons here.": "Tôi có vài thứ chúng ta có thể dùng làm vũ khí ở đây.",
  "Zombies are about to overrun the base!": "Zombie sắp sửa tràn ngập căn cứ rồi!",
  "Nigel": "Nigel",
  "They're right on top of us!": "Chúng đang ở ngay trên đầu chúng ta!",
  "Sure is nice to see you round here.": "Thật vui khi thấy cậu quanh đây.",
  "Industrial Wrench": "Cờ Lê Công Nghiệp",
  "%1$s was out scouting. Make it home, but just barely. Had to burn some medicine on the wound. -%2$s": "%1$s đã ra ngoài thám thính. Về được đến nhà, nhưng chỉ vừa đủ mạng. Đã phải tốn một ít thuốc cho vết thương. -%2$s",
  "You're pulling us out, sir?": "Ngài định rút chúng tôi ra sao, thưa ngài?",
  "That should be enough scouting for now.": "Bấy nhiêu do thám là đủ cho lúc này rồi.",
  "We've got this covered.": "Chúng tôi đã lo liệu xong vụ này.",
  "Come on, let's clear this place out.": "Nào, hãy dọn sạch chỗ này đi.",
  "Army": "Quân Đội",
  "Oh yeah, there's a way easier approach for that.": "Ồ có chứ, có một cách tiếp cận dễ dàng hơn nhiều cho việc đó.",
  "Profile 4": "Hồ Sơ 4",
  "My luck I'll get infected and die....": "Số tôi nhọ nên sẽ bị nhiễm bệnh và chết thôi....",
  "But we can't stop fighting. If we give up, we're nothing. Less than nothing. Who's going to remember us if we roll over and die?": "Nhưng chúng ta đéo thể ngừng chiến đấu. Nếu bỏ cuộc, chúng ta sẽ chẳng là gì cả. Thậm chí còn tệ hơn cả đéo là gì. Ai sẽ nhớ đến chúng ta nếu chúng ta cứ thế lăn ra chết cơ chứ?",
  "Man, I hope not. We've got some survivors back at the ranger station that seem to know what's going on, but we didn't have time for orientation.": "Ông bạn, tôi hy vọng là đéo phải vậy. Chúng ta có vài người sống sót ở trạm kiểm lâm có vẻ biết chuyện gì đang xảy ra, nhưng chúng tôi đéo có thời gian để tìm hiểu.",
  "Almost home with a load of useful gear.": "Sắp về đến nhà với một đống đồ nghề hữu ích rồi.",
  "Kinda busy here. Can it wait?": "Ở đây đang hơi bận. Chuyện này đợi được đéo?",
  ".45 caliber royalty.": "Bậc vương giả của cỡ nòng .45.",
  "ATTITUDE: Supportive": "THÁI ĐỘ: Hỗ Trợ",
  "Oh shit oh shit oh shit oh shit!": "Ôi chết tiệt ôi chết tiệt ôi chết tiệt!",
  "%+d Community Fame (Social Network)": "%+d Danh Tiếng Cộng Đồng (Mạng Xã Hội)",
  "Sit tight, reinforcements are inbound.": "Giữ vị trí đi, viện binh đang đến.",
  "Make Chemical Incendiaries": "Chế Tạo Chất Cháy Hóa Học",
  "I think that made quite an... impression. Get it? Guys?": "Tôi nghĩ việc đó đã tạo được đôi chút... ấn tượng. Hiểu đéo? Mọi người?",
  "You have exceeded my expectations, and to you I say congratulations.": "Cậu đã vượt quá mong đợi của tôi, và tôi xin gửi lời chúc mừng đến cậu.",
  "Understood, sir. We'll keep searching unless otherwise directed.": "Đã rõ, thưa sếp. Chúng tôi sẽ tiếp tục tìm kiếm trừ khi có chỉ đạo khác.",
  "He's dead.": "Anh ấy chết rồi.",
  "We need to get a better sense of what's going on around us. A quick survey would do us a lot of good. -%2$s": "Chúng ta cần nắm rõ hơn về những gì đang diễn ra xung quanh mình. Một cuộc khảo sát nhanh sẽ mang lại rất nhiều lợi ích. -%2$s",
  "Oakley": "Oakley",
  "Altman": "Altman",
  "I'm getting worried about her. She's barely eating, she hardly says two words to anybody....": "Tôi bắt đầu thấy lo cho cô ấy. Cô ấy gần như đéo ăn uống gì, và cũng hiếm khi nói chuyện với ai....",
  "I know. I'm sorry I blew up at you.": "Tôi biết. Tôi xin lỗi vì đã nổi nóng với cậu.",
  "See what's out there.": "Xem ngoài kia có gì nào.",
  "Knee Injury": "Chấn Thương Đầu Gối",
  "Hadley Westen is away": "Hadley Westen đi vắng",
  "I'm sorry to hear that. Thanks for thinking about it.": "Tôi rất tiếc khi nghe điều đó. Dù sao cũng cảm ơn vì cậu đã nghĩ về nó.",
  "Nothing too onerous. You'll keep to the curfew, put any supplies you gather toward the community pool, and respect the rights and property of the others in the community.": "Đéo có gì quá nặng nề đâu. Cậu sẽ tuân thủ giờ giới nghiêm, đóng góp mọi nhu yếu phẩm cậu thu thập được vào quỹ chung của cộng đồng, và tôn trọng quyền lợi cũng như tài sản của những người khác trong cộng đồng.",
  "Yeah, kiss my ass.": "Vâng, hôn mông tao đi.",
  "Uh... I came from the church. Pastor William sent me? I'm here to pick up the doctor.": "Ơ... Tôi đến từ nhà thờ. Mục sư William cử tôi đến? Tôi đến đây để đón bác sĩ."
};

const file = 'output/languages/chunks/btxt_chunk_135.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_135.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk135[r.sourceText]) {
    r.translatedText = chunk135[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 135 successfully!');
