const fs = require('fs');
const chunk154 = {
  "Ready Freddy.": "Sẵn sàng nhé Freddy.",
  "I don't know.": "Tôi đéo biết.",
  "First thing I'm gonna do when this is all over? I'm gonna have a steak. Second thing I'm gonna do? Wipe my ass with real toilet paper. Third?": "Điều đầu tiên tôi định làm khi chuyện này kết thúc? Tôi sẽ ăn một miếng bít tết. Điều thứ hai tôi sẽ làm? Chùi đít bằng giấy vệ sinh thật. Thứ ba á?",
  "Ray.": "Ray.",
  "We could make something a little less rickety. REQUIRES WORKSHOP.": "Chúng ta có thể làm thứ gì đó bớt ọp ẹp hơn. YÊU CẦU XƯỞNG (WORKSHOP).",
  "Morey": "Morey",
  "Ammunition Shop": "Cửa Hàng Đạn Dược (Ammunition Shop)",
  "Can I get a runner?": "Tôi có thể có một người đưa tin (runner) đéo?",
  "I'm fine!": "Tôi ổn!",
  "Fuck, ain't we popular today.": "Đệt, hôm nay chúng ta đéo được hoan nghênh sao.",
  "That zombie hit me pretty hard. Can't seem to focus anymore. (Shooting XP penalty)": "Con zombie đó đánh tôi khá đau. Đéo thể tập trung được nữa. (Bị phạt Kinh nghiệm Bắn súng - Shooting XP)",
  "The zombies can't get in here?": "Lũ zombie đéo thể vào đây sao?",
  "Failed To Stop the Freak": "Đã Thất Bại Trong Việc Ngăn Chặn Freak",
  "Hmm?": "Hmm?",
  "Outpost %d: Traps Ready": "Tiền Đồn %d: Bẫy Đã Sẵn Sàng",
  "Best thing about this trip? No cell reception. No e-mail alerts from work, no \"the Meyers account needs to be audited by Monday morning\" texts, no RSS feeds. Just peace, quiet, and fresh fish. - %1$s": "Điều tuyệt vời nhất về chuyến đi này là gì? Đéo có sóng điện thoại. Đéo có email cảnh báo từ công ty, đéo có những tin nhắn kiểu \"tài khoản Meyers cần được kiểm toán trước sáng thứ Hai\", đéo có thông báo RSS. Chỉ có sự bình yên, tĩnh lặng và cá tươi. - %1$s",
  "Need a car out here.": "Cần một chiếc xe ngoài này.",
  "LZ Under Attack": "Khu Vực Hạ Cánh (LZ) Đang Bị Tấn Công",
  "Zombie Hordes move and become alerted as a group. Don't fight them if you don't have to.": "Bầy Zombie di chuyển và trở nên cảnh giác theo nhóm. Đừng đánh nhau với chúng nếu bạn đéo bắt buộc phải làm vậy.",
  "Flossie": "Flossie",
  "We've let the zeds overrun too much of valley. It's not safe. - %1$s": "Chúng ta đã để bọn zed tràn ngập quá nhiều trong thung lũng. Chỗ này đéo an toàn đâu. - %1$s",
  "THE OTHER DOCTOR": "VỊ BÁC SĨ KHÁC",
  "Serious Depression": "Trầm Cảm Nặng",
  "It's saying \"One, one, tango mike papa, two five delta ...\" Are these coordinates?": "Nó đang nói \"Một, một, tango mike papa, hai năm delta ...\" Đây có phải là tọa độ đéo?",
  "Assault Rifle: 552 CS": "Súng Trường Tấn Công: Súng 552 CS",
  "Command Center": "Trung Tâm Chỉ Huy (Command Center)",
  "Holy fucking shit!": "Cái định mệnh vãi lồn!",
  "1 Case of Ammunition for 5 Barrels of Fuel.": "1 Thùng Đạn Dược (Ammunition) đổi lấy 5 Thùng Nhiên Liệu (Fuel).",
  "Need a MEDICAL LAB": "Cần một PHÒNG THÍ NGHIỆM Y TẾ (MEDICAL LAB)",
  "Enjoy, motherfuckers!": "Thưởng thức đi, những thằng khốn!",
  "I'm telling you, we've got to start thinking long-term, and that means building some improvements into this place.": "Tôi đang nói cho cậu biết đấy, chúng ta phải bắt đầu suy nghĩ dài hạn, và điều đó có nghĩa là xây dựng một số thứ để cải tiến nơi này.",
  "Created 3 Homemade Painkillers": "Đã Chế Tạo Được 3 Liều Thuốc Giảm Đau Tự Chế (Homemade Painkillers)",
  "<Whew>": "<Phù>",
  "Damnation! We just lost a barricade!": "Khốn kiếp! Chúng ta vừa mất một rào chắn!",
  "Eyes front!": "Nhìn thẳng phía trước đi!",
  "So, I've been thinking about a lot of stuff lately, and something occurred to me.": "Tôi đã suy nghĩ về rất nhiều thứ gần đây, và tôi vừa nảy ra một ý.",
  "Major Hawkes just...well, she made me feel safe when she was around.": "Thiếu tá Hawkes chỉ là... chà, cô ấy khiến tôi cảm thấy an toàn khi cô ấy ở bên.",
  "Officially, of course, you're all still lawbreakers and squatters and you'll be arrested as soon as we have a jail to put you in.": "Chính thức thì, tất nhiên, tất cả các người vẫn là những kẻ phá luật và những kẻ chiếm đoạt nhà đất, và các người sẽ bị bắt ngay khi chúng tôi có một nhà tù để tống cổ các người vào.",
  "Hey, try not to shoot us in the back, okay?": "Này, cố gắng đừng bắn lén sau lưng chúng tôi, được đéo?",
  "Cortes": "Cortes",
  "Tango down.": "Mục tiêu (Tango) đã gục.",
  "Actor": "Diễn Viên",
  "Attention citizens We've had reports of armed civilians attempting to force our patrols to provide supplies.": "Chú ý hỡi các công dân. Chúng tôi đã nhận được báo cáo về việc thường dân vũ trang cố gắng ép buộc các đội tuần tra của chúng tôi cung cấp tiếp tế.",
  "Cutter": "Cutter",
  "Command Center: Survivors Located": "Trung Tâm Chỉ Huy: Đã Định Vị Được Người Sống Sót",
  "I heard we lost another patrol last night. Shit's getting bad.": "Tôi nghe nói chúng ta lại mất thêm một đội tuần tra đêm qua. Mọi chuyện đang trở nên tồi tệ.",
  "And you keep your eyes open for military assets lost in the field. We'll use anything you can find.": "Và hãy để mắt tới những tài sản quân sự bị thất lạc trên thực địa. Chúng ta sẽ sử dụng bất cứ thứ gì cậu có thể tìm thấy.",
  "Pick Up Rucksack": "Nhặt Ba Lô Lên",
  "Hey, I'm not sure what happened, but I think we got separated.": "Này, tôi đéo chắc chuyện gì đã xảy ra, nhưng tôi nghĩ chúng ta đã bị chia cắt.",
  "What if I find some more? Will that pay our rent?": "Nếu tôi tìm thấy thêm thì sao? Số đó có đủ để trả tiền thuê chỗ của chúng tôi đéo?",
  "Cases of Ammunition": "Thùng Đạn Dược (Ammunition)",
  "Cox": "Cox",
  "We're still hoping there's room for us at your place.": "Chúng tôi vẫn hy vọng có đủ chỗ cho chúng tôi ở chỗ của cậu.",
  "Mendoza": "Mendoza",
  "Phosphorous Triiodide": "Phốt Pho Tri-i-ốt (Phosphorous Triiodide)",
  "And in the junk drawer in his kitchen, I find these pictures that... well, trust me. I'll never look at the tailpipe of a '72 Falconer Hatchback the same way again.": "Và trong cái ngăn kéo chứa đồ lặt vặt trong bếp nhà ông ta, tôi tìm thấy những bức ảnh này... chà, tin tôi đi. Tôi sẽ đéo bao giờ có thể nhìn vào ống xả của một chiếc Falconer Hatchback đời '72 theo cùng một cách như trước nữa đâu.",
  "Yes, Alan. Pastor Will is still sick.": "Đúng thế, Alan. Mục sư Will vẫn đang ốm.",
  "Cause last time I checked, popping open a corpse didn't kill everybody in the room.": "Vì lần cuối tôi kiểm tra, việc mổ xẻ một cái xác chết đéo hề giết chết tất cả mọi người trong phòng.",
  "A pipe with a heavy fitting on the end.": "Một đường ống có đầu nối nặng ở đầu.",
  "Hey, and you assholes better build a statue of me!": "Này, và mấy thằng khốn chúng mày tốt nhất là nên xây một bức tượng của tao đấy!",
  "I see 'em!": "Tôi thấy chúng rồi!",
  "That's affirmative.": "Đã nhận rõ.",
  "Zed Hunt (Feral)": "Cuộc Săn Zed (Feral)",
  "Rifle: Model 70": "Súng Trường (Rifle): Súng Model 70",
  "Better do one more sweep, make sure everything's clear.": "Tốt hơn là nên quét qua một lần nữa, để chắc chắn rằng mọi thứ đã an toàn.",
  "My whole senior year of high school, she made me take these karate classes, so I'd be able to protect myself.": "Suốt năm cuối trung học, bà ấy bắt tôi học mấy lớp võ karate, để tôi có thể tự bảo vệ bản thân.",
  "Isabelle": "Isabelle",
  "%1$s is glad for the Latrine.": "%1$s rất vui vì có Nhà Xí (Latrine).",
  "COMPLETED: Zed Hunt (Armored)": "ĐÃ HOÀN THÀNH: Cuộc Săn Zed (Armored)",
  "Why would they do that?": "Tại sao họ lại làm vậy?",
  "Search for a Bloater": "Tìm Kiếm Một Con Bloater",
  "54 GENERIC Gilbert Wingate": "54 CHUNG (GENERIC) Gilbert Wingate",
  "Rifle: Eli": "Súng Trường (Rifle): Súng Eli",
  "Roaming Zombie Horde": "Bầy Zombie Đi Lang Thang",
  "No Melee Weapon": "Đéo Có Vũ Khí Cận Chiến",
  "Look For %s": "Tìm Kiếm %s",
  "Denial.": "Chối bỏ.",
  "Pistol: G 20": "Súng Lục (Pistol): Súng G 20",
  "All quiet here.": "Mọi thứ ở đây đều yên tĩnh.",
  "Keeps weeds at bay, named \"Barbra\".": "Dùng để diệt cỏ dại, được đặt tên là \"Barbra\".",
  "This character should never be given the Away status.": "Nhân vật này đéo bao giờ nên được cấp trạng thái Đi Vắng (Away).",
  "There you go. Don't say I never gave you anything.": "Của cậu đây. Đừng nói là tôi đéo bao giờ cho cậu cái gì nhé.",
  "Building Materials": "Vật Liệu Xây Dựng (Building Materials)",
  "We ain't clear yet.": "Chúng ta vẫn chưa an toàn đâu.",
  "If we keep pulling together like that, I've got a good feeling we'll get through this.": "Nếu chúng ta cứ tiếp tục kề vai sát cánh như vậy, tôi có linh cảm tốt rằng chúng ta sẽ vượt qua chuyện này.",
  "Castilla": "Castilla",
  "Buy in Bulk": "Mua Sỉ",
  "Kylie": "Kylie",
  "I know I can't order you to rest...so consider it a strong suggestion.": "Tôi biết tôi đéo thể ra lệnh cho cậu nghỉ ngơi... vậy nên hãy coi nó như một lời đề nghị mạnh mẽ.",
  "BLOOD TIES": "MÁU MỦ RUỘT THỊT",
  "Never realized how much food three people can go through in a week. When we found that Tartan Mart nobody had hit yet, we thought we'd taken enough for a month, but now it's a week later and the food's all gone and that Tartan Mart has been totally picked over... and now I don't know what to do.": "Tôi đéo bao giờ nhận ra ba người có thể tiêu thụ bao nhiêu thức ăn trong một tuần. Khi chúng tôi tìm thấy siêu thị Tartan Mart đó mà chưa có ai cướp phá, chúng tôi đã nghĩ rằng chúng tôi đã lấy đủ cho một tháng, nhưng giờ thì một tuần đã trôi qua và thức ăn đã hết sạch và cái Tartan Mart đó đã bị vét sạch bách... và bây giờ tôi đéo biết phải làm gì nữa.",
  "How many other people you think would go out there and risk their necks just to rescue somebody in trouble?": "Cậu nghĩ còn bao nhiêu người khác sẵn sàng ra ngoài đó và mạo hiểm mạng sống của mình chỉ để cứu một người đang gặp rắc rối?",
  "I've had just about enough of his bullshit.": "Tôi đã chịu đựng đủ mấy cái trò khốn nạn của hắn ta rồi.",
  "Hey, c'mon. Things'll turn around. Just have a little faith.": "Này, thôi nào. Mọi chuyện rồi sẽ khả quan hơn thôi. Cứ có chút niềm tin đi.",
  "Let's wait a bit on this one.": "Hãy chờ một chút đối với chuyện này đã.",
  "The youngest Wilkerson brother. A reckless hoodlum.": "Người em trai út nhà Wilkerson. Một tên du côn liều lĩnh.",
  "Hey, chin up. We'll figure out another way.": "Này, ngẩng cao đầu lên. Chúng ta sẽ tìm ra cách khác.",
  "I needed a little quiet time to get my head straight after all the shit that's been going down. Nothing weird about that. If you've got a problem with that, %1$s, how about you quit with the wisecracks and try saying so to my face? - %2$s": "Tôi cần một chút thời gian yên tĩnh để giữ cho đầu óc tỉnh táo sau tất cả những chuyện chết tiệt đã xảy ra. Đéo có gì kỳ lạ về điều đó cả. Nếu cậu có vấn đề gì với chuyện đó, %1$s, sao cậu đéo thôi cái trò nói móc xỉa và thử nói thẳng vào mặt tôi xem nào? - %2$s",
  "Jeez, I don't know. At first it just seemed like the place to go, y'know? End of the world and all that.": "Trời ạ, tôi đéo biết nữa. Lúc đầu nó có vẻ như là nơi đáng để đi, cậu biết đấy? Tận thế và tất cả những thứ đó.",
  "This won't do any good. I'm still fresh.": "Điều này sẽ đéo có tác dụng gì đâu. Tôi vẫn còn sung sức lắm."
};

const file = 'output/languages/chunks/btxt_chunk_154.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_154.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk154[r.sourceText]) {
    r.translatedText = chunk154[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 154 successfully!');
