const fs = require('fs');
const chunk148 = {
  "Don't worry about it, this one's on me. You can get me next time.": "Đừng bận tâm, vụ này để tôi lo. Cậu có thể trả ơn tôi vào lần sau.",
  "Pretty bad.": "Khá tệ đấy.",
  "Hey, I appreciate your concern. It means a lot to me.": "Này, tôi rất trân trọng sự quan tâm của cậu. Nó có ý nghĩa rất lớn đối với tôi.",
  "Atede": "Atede",
  "Oh, yes ma'am.": "Ồ, vâng thưa cô.",
  "15% chance of missing allies coming home safely on their own.": "15% cơ hội những đồng minh mất tích tự mình trở về nhà an toàn.",
  "Over there.": "Ở đằng kia kìa.",
  "Check on Eli": "Kiểm tra tình hình của Eli",
  "Refills some brass to generate several magazines' worth of 7.62mm ammunition.": "Nạp lại một ít vỏ đạn (brass) để chế tạo ra vài băng đạn 7.62mm.",
  "Set Up Cooking Area": "Thiết Lập Khu Vực Nấu Ăn",
  "Head to the Warehouse": "Đi đến Nhà Kho (Warehouse)",
  "Rifle: .45 Justice": "Súng Trường (Rifle): Súng Trường .45 Justice",
  "Warehouse": "Nhà Kho (Warehouse)",
  "Uh, yeah, that's great. I'm really excited for you.": "Ừ, phải, tuyệt đấy. Tôi thực sự rất hào hứng thay cho cậu.",
  "Hey. Whatcha doing?": "Này. Cậu đang làm gì thế?",
  "You coulda killed somebody!": "Cậu có thể đã giết ai đó rồi đấy!",
  "Played Golf": "Từng Chơi Golf",
  "Glad we got some real food. It was getting hard to stay alert. - %1$s": "Thật mừng vì chúng ta đã có thức ăn thực sự. Chứ việc giữ tỉnh táo đang ngày càng khó khăn rồi. - %1$s",
  "Karen Tolbert": "Karen Tolbert",
  "While aiming ([ul_aim]), press [firemode] to cycle rate of fire (automatic weapons only), or press [camera] to toggle zoom (scoped guns) or switch shoulder (non-scoped guns).": "Trong khi ngắm bắn ([ul_aim]), nhấn [firemode] để chuyển đổi chế độ bắn (chỉ dành cho vũ khí tự động), hoặc nhấn [camera] để bật/tắt phóng to (súng có ống ngắm) hoặc đổi vai (súng đéo có ống ngắm).",
  "Some folks said we'd never be finished, but check it out!": "Một số người nói rằng chúng ta sẽ đéo bao giờ hoàn thành được, nhưng hãy nhìn xem!",
  "Come on, we gotta at least check the place. Somebody might have survived.": "Thôi nào, ít nhất chúng ta cũng phải kiểm tra nơi này chứ. Có thể có ai đó đã sống sót.",
  "Before all this, I had a sweet setup.": "Trước khi tất cả chuyện này xảy ra, tôi đã có một cơ ngơi rất ngon lành.",
  "There's something about a well-maintained kitchen that makes everything feel almost normal.": "Có điều gì đó ở một căn bếp được bảo quản tốt khiến cho mọi thứ mang lại cảm giác gần như là bình thường.",
  "Damn. I was hoping things might not be as bad down there. Still... thanks.": "Chết tiệt. Tôi đã hy vọng mọi thứ có thể sẽ đéo quá tồi tệ ở dưới đó. Dù sao thì... cảm ơn nhé.",
  "Shh! This son of a bitch has killed four of my people in the last three days.": "Suỵt! Thằng chó đẻ này đã giết bốn người của tôi trong ba ngày qua rồi đấy.",
  "EXTRACTED: Dan Bogatz": "ĐÃ RÚT LUI: Dan Bogatz",
  "That'll have a great view.": "Chỗ đó sẽ có một tầm nhìn tuyệt vời đấy.",
  "Gain increased XP from shooting.": "Nhận được nhiều XP hơn từ việc bắn súng.",
  "Then I get to keep my town, and you won't be a mass murderer.": "Vậy thì tôi sẽ giữ được thị trấn của mình, và cậu sẽ đéo trở thành một kẻ giết người hàng loạt.",
  "Hey, c'mon. It'll turn around. Just have a little faith.": "Này, thôi nào. Mọi chuyện rồi sẽ xoay chuyển thôi. Chỉ cần có chút niềm tin đi.",
  "Gimme a fuckin' hand here!": "Phụ tôi một tay chết tiệt nào!",
  "Sergeant Eldridge's next target is a Feral. We're looking for a long-limbed blind zombie with a sickly tinge to its flesh. And we have to kill it with a sharp blade, to keep the samples intact.": "Mục tiêu tiếp theo của Trung sĩ Eldridge là một con Feral. Chúng ta đang tìm kiếm một con zombie mù lòa, chân tay dài lêu nghêu với làn da nhợt nhạt bệnh hoạn. Và chúng ta phải giết nó bằng một lưỡi dao sắc bén, để giữ nguyên vẹn các mẫu vật.",
  "I just found some supplies.": "Tôi vừa tìm thấy một số nhu yếu phẩm.",
  "Prevented the food poisoning.": "Đã ngăn chặn được ngộ độc thực phẩm.",
  "Dude. Seriously? Even I think you're a douche.": "Anh bạn. Thật luôn? Đến tôi cũng phải nghĩ cậu là một thằng khốn đấy.",
  "Torrisi": "Torrisi",
  "They say \"count your age not in years, but in friends.\" You, my friend, might as well be Methuselah.": "Người ta nói \"đừng đếm tuổi của bạn bằng số năm, mà hãy đếm bằng số lượng bạn bè.\" Vậy thì anh bạn ạ, cậu có khi phải già như Methuselah mất.",
  "A simple survival package. Just enough to keep us going.": "Một gói sinh tồn đơn giản. Chỉ vừa đủ để giữ cho chúng ta tiếp tục sống.",
  "Yeah, that was a close call with that horde.": "Phải, chúng ta đã thoát chết trong gang tấc với bầy horde đó.",
  "The RV's gas tank is filled to overflowing. Hope that'll be enough to get us somewhere useful.": "Bình xăng của chiếc xe RV đã được đổ đầy tràn rồi. Hy vọng thế là đủ để đưa chúng ta đến một nơi nào đó có ích.",
  "The Judge wants to talk to you. Get your ass down to the courthouse.": "Thẩm phán muốn nói chuyện với cậu. Vác cái mông của cậu xuống Tòa Án (Courthouse) đi.",
  "The pilot dropped off a box of medical supplies that he scavenged from HQ. Should help us hold out for a bit longer.": "Phi công đã thả xuống một hộp vật tư y tế mà anh ta nhặt mót được từ Trụ sở chính (HQ). Hẳn là sẽ giúp chúng ta cầm cự được thêm một thời gian nữa.",
  "Please go home. I don't want to shoot anybody today.": "Làm ơn hãy về nhà đi. Tôi đéo muốn phải bắn bất cứ ai trong ngày hôm nay đâu.",
  "The youngest Wilkerson brother. A reckless hoodlum with a bigass wrench.": "Đứa em út nhà Wilkerson. Một gã du côn liều lĩnh với một cái cờ-lê to tổ chảng.",
  "Marquez": "Marquez",
  "Gotta be more careful next time.": "Lần sau phải cẩn thận hơn mới được.",
  "Lone Soldier": "Người Lính Đơn Độc",
  "Sarah": "Sarah",
  "So I think I owe %2$s an apology. I thought everyone knew what I said things like 'punk ass bitch' and 'unbelievable crybaby' that was just good natured ribbing. I was wrong. - %1$s": "Vậy nên tôi nghĩ tôi nợ %2$s một lời xin lỗi. Tôi cứ tưởng mọi người đều biết những câu tôi nói kiểu như 'đồ chó đẻ nhãi ranh' hay 'đồ mít ướt đéo thể tin nổi' chỉ là những lời trêu đùa thiện ý thôi chứ. Tôi đã sai. - %1$s",
  "There's too many of them!": "Bọn chúng đông quá!",
  "You see what I did there?": "Cậu có thấy tôi vừa làm gì đéo?",
  "Nah, let's not.": "Đéo, chúng ta đừng làm thế.",
  "Kill a dying Community Member. (Breakdown Level 1 or Higher)": "Giết một Thành Viên Cộng Đồng đang hấp hối. (Breakdown Cấp 1 trở lên)",
  "HOME: Hunger Recovery": "CĂN CỨ: Phục Hồi Cơn Đói (Hunger Recovery)",
  "A sanitary latrine is the key to a healthy base.": "Một nhà xí hợp vệ sinh là chìa khóa cho một căn cứ khỏe mạnh.",
  "Margaret": "Margaret",
  "Sir, are you pulling us out? People still need help here.": "Thưa ngài, ngài định rút quân sao? Người dân ở đây vẫn cần được giúp đỡ.",
  "You realize these were people, right?": "Cậu nhận ra đây từng là con người, đúng đéo?",
  "Looks like a freak.": "Trông giống như một con quái nhân (freak).",
  "Improves Vitality and food safety.": "Cải thiện Sinh Lực (Vitality) và an toàn vệ sinh thực phẩm.",
  "Maybe you want to slow down? Be a little quieter?": "Có lẽ cậu muốn đi chậm lại một chút đéo? Cư xử im lặng hơn một chút?",
  "You have no space to carry that!": "Bạn đéo có chỗ để mang theo thứ đó!",
  "Aw, yeah, we're talking military-grade destruction here.": "Ồ, chuẩn rồi, chúng ta đang nói về mức độ hủy diệt cấp quân sự ở đây đấy.",
  "No gun; nothing to silence.": "Đéo có súng; đéo có thứ gì để lắp giảm thanh cả.",
  "New food storage options.": "Tùy chọn lưu trữ thức ăn mới.",
  "RV: New Facility": "Xe RV: Cơ sở vật chất mới",
  "Let's not scare our friends off already, Mickey. Everybody's here because they want to be.": "Đừng dọa những người bạn của chúng ta sợ chạy mất chứ, Mickey. Mọi người ở đây vì họ muốn thế mà.",
  "The RV has two flat tires.": "Chiếc RV có hai cái lốp bị xịt.",
  "The crops are almost fully grown.": "Hoa màu đã gần như phát triển hoàn thiện rồi.",
  "Fields": "Cánh Đồng",
  "That should last Becca a while. Also: TMI. Seriously. - %1$s": "Thứ đó chắc sẽ giúp Becca trụ được một thời gian. Vả lại: TMI (Thông tin quá đà). Nghiêm túc đấy. - %1$s",
  "Go Big or Go Home": "Chơi Lớn Hoặc Về Nhà (Go Big or Go Home)",
  "Hey c'mon, man, you got my back or what?": "Này thôi nào, anh bạn, cậu có yểm trợ cho tôi đéo đấy hả?",
  "Nah, I'm just fucking with you. No bullshit Hollywood ending for us.": "Đéo, tôi chỉ đùa với cậu chút thôi. Đéo có cái kết chết tiệt đậm chất Hollywood nào cho chúng ta đâu.",
  "About time you showed up. We've been needing those spare parts for a while now.": "Cũng đến lúc cậu xuất hiện rồi đấy. Chúng tôi đã cần những phụ tùng thay thế đó một thời gian rồi.",
  "Any bug these would treat has probably evolved an immunity already. -%1$s": "Bất kỳ mầm bệnh nào mà đống thuốc này có thể chữa được thì có lẽ đều đã tiến hóa để miễn dịch hết rồi. -%1$s",
  "Vienna Cho just relayed a message from a civilian in distress, and they may have supplies they can share. If we have the time, we might be able to rescue them.": "Vienna Cho vừa truyền đạt một tin nhắn từ một dân thường đang gặp nạn, và họ có thể có một số nhu yếu phẩm có thể chia sẻ. Nếu có thời gian, chúng ta có thể thử giải cứu họ.",
  "%1$s is sad.": "%1$s đang rất buồn.",
  "Meier": "Meier",
  "I don't have time for this.": "Tôi đéo có thời gian cho việc này đâu.",
  "Rescue %s %s": "Giải Cứu %s %s",
  "Highroad to Black Friday. Cleo beacon is active on the ground. Highroad out.": "Highroad gọi Black Friday. Tín hiệu Cleo đã được kích hoạt trên mặt đất. Highroad chấm dứt.",
  "Watch the birdie, motherfuckers!": "Nhìn vào con chim nhỏ nè, lũ khốn kiếp!",
  "Survivors at the church.": "Những người sống sót tại nhà thờ.",
  "McCoy": "McCoy",
  "MISSION: Runner in Trouble": "NHIỆM VỤ: Người Chạy Việc (Runner) Gặp Rắc Rối",
  "Bench Barbell": "Tạ Đòn Dài (Bench Barbell)",
  "Hey, I'm looking for Carl. Anybody seen him?": "Này, tôi đang tìm Carl. Có ai thấy ông ấy đéo?",
  "Guess the good stuff's gone.": "Chắc những món ngon nghẻ đã bốc hơi hết rồi.",
  "I don't think anyone's available.": "Tôi đéo nghĩ có ai đang rảnh rỗi đâu.",
  "REWARD. Several rucksacks' worth of Ammunition, delivered directly into your stockpile.": "PHẦN THƯỞNG. Một lượng Đạn Dược (Ammunition) tương đương với vài chiếc ba lô đầy, được giao trực tiếp vào kho dự trữ của bạn.",
  "Sounds like there's some commotion out there.": "Nghe như thể đang có một vụ hỗn loạn nào đó ở ngoài kia.",
  "The Wall": "Bức Tường",
  "Well, that wasn't too bad, was it?": "Chà, chuyện đó cũng đéo quá tồi tệ, phải đéo?",
  "SMG: Samurai PDW": "Tiểu Liên (SMG): Tiểu Liên Samurai PDW",
  "Family troubles.": "Những rắc rối gia đình.",
  "Tamara": "Tamara",
  "Must be a strong bug to get past our medical protocols. With our facilities I expect a speedy recovery. - Lily": "Chắc hẳn phải là một mầm bệnh rất mạnh mới có thể vượt qua được các quy trình y tế của chúng ta. Với các cơ sở vật chất của chúng ta, tôi hy vọng sẽ có một sự hồi phục nhanh chóng. - Lily",
  "Revolver: Blackbird": "Súng Côn (Revolver): Súng Côn Blackbird"
};

const file = 'output/languages/chunks/btxt_chunk_148.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_148.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk148[r.sourceText]) {
    r.translatedText = chunk148[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 148 successfully!');
