const fs = require('fs');
const chunk102 = {
  "That guy was dead. I swear to God, that guy, he was dead. How the hell does that happen?": "Gã đó đã chết. Tôi thề có Chúa, gã đó, hắn đã chết thật rồi. Làm thế quái nào chuyện đó lại xảy ra được chứ?",
  "All right, I'm going to set the charges.": "Được rồi, tôi sẽ đặt thuốc nổ.",
  "Hmmm… Eenie meanie miney mo....": "Hừm... Đếm xem ai chết nào....",
  "START MISSION. There probably isn't much in it for you other than earning some goodwill.": "BẮT ĐẦU NHIỆM VỤ. Chắc là cậu sẽ chẳng được lợi lộc gì nhiều ngoài việc kiếm chút thiện cảm đâu.",
  "A strict enforcer of the law whose reputation as a hanging judge has only added to her credibility as a leader in the aftermath of the outbreak.": "Một người thực thi pháp luật nghiêm khắc, nổi tiếng với biệt danh thẩm phán treo cổ, điều này lại càng làm tăng uy tín lãnh đạo của bà ta sau đại dịch.",
  "Loved Movies": "Đam Mê Phim Ảnh",
  "We have a base nearby. Let's get you on a helicopter.": "Chúng tôi có một căn cứ gần đây. Hãy đưa cậu lên trực thăng nào.",
  "Yeah, I think we just saw it.": "Ừ, tôi nghĩ chúng ta vừa nhìn thấy nó.",
  "Fuck with me and I'll kick your teeth in. (Improved Fighting and Cardio.)": "Gây sự với tao và tao sẽ đá gãy răng mày. (Cải thiện Chiến Đấu và Thể Lực.)",
  "Vienna Cho calls herself the Last Voice of Danforth. She's been using her radio station to relay information from refugees throughout the city ... when she isn't ripping us a new one. Now she realizes she can't survive on her own ... and she needs our help.": "Vienna Cho tự xưng là Tiếng Nói Cuối Cùng của Danforth. Cô ta vẫn dùng trạm phát thanh của mình để truyền tin cho những người tị nạn khắp thành phố... khi mà cô ta không chửi xéo chúng ta. Giờ thì cô ta nhận ra mình không thể tự sống sót... và cô ta cần sự giúp đỡ của chúng ta.",
  "Reliable and inexpensive, a classic.": "Đáng tin cậy và rẻ tiền, một món đồ cổ điển.",
  "This is the survival of humanity we're talking about. We have zero room for error.": "Chúng ta đang nói về sự sinh tồn của nhân loại. Chúng ta không có chỗ cho sai lầm.",
  "I could get used to this.": "Tôi có thể quen với chuyện này.",
  "Vitality will gradually recover while resting at home. It should take about 5 hours to get back to full Vitality.": "Sinh lực sẽ dần phục hồi khi nghỉ ngơi tại nhà. Mất khoảng 5 giờ để phục hồi hoàn toàn.",
  "Just a little bit closer...": "Chỉ một chút nữa thôi...",
  "Haylee": "Haylee",
  "You didn't call the CDC?": "Cậu không gọi cho CDC à?",
  "Don't you think we've got enough ways to get messed up without fighting amongst ourselves?": "Cậu không nghĩ là chúng ta đã có đủ rắc rối rồi, sao còn phải tự cắn xé lẫn nhau chứ?",
  "Kaasik": "Kaasik",
  "How about getting out of my face? How does that sound?": "Thế tránh xa tao ra thì sao? Nghe được không?",
  "Habe": "Habe",
  "Lot of money for a county commissioner.": "Một khoản tiền lớn cho chức ủy viên hạt đấy.",
  "I've been asking around, but no signs of Doc Hanson yet. - %1$s": "Tôi đã hỏi thăm xung quanh, nhưng vẫn chưa có tung tích gì của Bác sĩ Hanson. - %1$s",
  "Select storage device": "Chọn thiết bị lưu trữ",
  "You might wanna move your ass!": "Tốt nhất là nhấc mông lên và chạy đi!",
  "Silver felt-tip pen, cursive, on cream-colored diary paper, the \"O\" in gross has a smiley face in it.": "Bút dạ quang màu bạc, viết tay nét thảo trên giấy nhật ký màu kem, chữ \"O\" trong từ gross có vẽ thêm một khuôn mặt cười.",
  "We're still here why, exactly? Does everybody here have a death wish?": "Nói chính xác thì tại sao chúng ta vẫn ở đây? Chẳng lẽ mọi người ở đây đều muốn chết à?",
  "What happened to the guy the Wilkersons beat up?": "Gã bị anh em nhà Wilkerson đánh đập giờ ra sao rồi?",
  "We got a term for this in the Army. That term is FUBAR.": "Trong quân đội có một từ để chỉ việc này. Đó là nát bét (FUBAR).",
  "Yeah, I was afraid of that. We've got a horde on our hands.": "Ừ, tôi sợ là thế. Chúng ta đang phải đối mặt với một bầy Zombie.",
  "Everyone's okay.": "Mọi người đều ổn.",
  "COMPLETED: Stranger in Trouble": "ĐÃ HOÀN THÀNH: Người Lạ Gặp Nạn",
  "Get to Safety": "Chạy Trốn",
  "You're right. Start putting out calls to everyone we know. Tell them to get ready to move. We're all getting out of here.": "Cậu đúng. Bắt đầu gọi cho tất cả những người chúng ta biết. Bảo họ chuẩn bị di chuyển. Tất cả chúng ta sẽ rời khỏi đây.",
  "Now just hold still...": "Giờ thì ngồi yên nào...",
  "Yeah. Better keep an eye on him.": "Ừ. Tốt hơn hết là để mắt đến hắn.",
  "Damn, I ain't seen a beatdown like that in a long time!": "Chết tiệt, đã lâu rồi tao mới thấy một trận đòn nhừ tử thế này!",
  "Fuck, that wasn't half-bad!": "Mẹ kiếp, cũng không đến nỗi tệ!",
  "These expired years ago!": "Đống này đã hết hạn từ đời nào rồi!",
  "I got the fucker here.": "Tôi tóm được thằng khốn đó rồi.",
  "Nothing surprising about people letting you down.": "Chẳng có gì đáng ngạc nhiên khi con người ta làm cậu thất vọng.",
  "Finn": "Finn",
  "Weeks": "Weeks",
  "Feel like checking something out?": "Muốn đi kiểm tra thử xem sao không?",
  "Get a quick tour of the church?": "Đi tham quan nhà thờ một vòng nhé?",
  "Marquis": "Marquis",
  "Kaedria": "Kaedria",
  "I swear this'd probably blow over in a stiff wind, but it's nice to be building rather than just destroying all the time.": "Tôi thề là cái này có thể bay luôn nếu có gió to, nhưng dù sao xây dựng vẫn tốt hơn là cứ suốt ngày phá hoại.",
  "Trade 1 Case of Ammunition for 10 Pallets of Building Materials.": "Đổi 1 Thùng Đạn lấy 10 Pallet Vật Liệu Xây Dựng.",
  "Just about made it.": "Vừa kịp lúc.",
  "Functionally Illiterate": "Mù Chữ",
  "We've gotten a request for some help. Could go check it out.": "Chúng ta nhận được một yêu cầu giúp đỡ. Có thể tới đó kiểm tra xem.",
  "I need to do some housecleaning before this place is safe enough.": "Tôi cần phải dọn dẹp sạch sẽ nơi này trước khi nó đủ an toàn.",
  "Okay, I'm on my way.": "Được rồi, tôi đang tới.",
  "We should survey the area.": "Chúng ta nên khảo sát khu vực này.",
  "I hear you. Feel like talking about it?": "Tôi hiểu. Cậu có muốn nói về chuyện đó không?",
  "Go To The Church": "Tới Nhà Thờ",
  "Coker": "Coker",
  "99 GENERIC Quentin Barnes": "99 GENERIC Quentin Barnes",
  "I came out here to end it, but... God, I'm such a chickenshit.": "Tôi ra đây để kết liễu đời mình, nhưng... Chúa ơi, tôi đúng là một kẻ hèn nhát.",
  "COMPLETED: Survey Request": "ĐÃ HOÀN THÀNH: Yêu cầu Khảo sát",
  "Watch the right.": "Chú ý bên phải.",
  "Woah now--we don't know if whoever did this is still here.": "Khoan đã--chúng ta chưa biết kẻ nào làm chuyện này có còn ở đây hay không.",
  "I dunno, there's just something satisfying about building, you know?": "Tôi không biết nữa, việc xây dựng có gì đó rất thỏa mãn, cậu biết không?",
  "Deliver 6 rucksacks to your base in the back of a single vehicle.": "Giao 6 túi đồ (rucksack) về căn cứ chỉ bằng một chuyến xe.",
  "Damn good shot.": "Bắn hay lắm.",
  "The list of things that will kill you is longer than the list of things that won't. (Lower Health)": "Danh sách những thứ có thể giết chết mày còn dài hơn danh sách những thứ không thể. (Giảm Máu Tối Đa)",
  "Standard four-door commuter car. Fragile but agile. Space for four.": "Xe hơi 4 cửa tiêu chuẩn. Mỏng manh nhưng nhanh nhẹn. Chỗ cho 4 người.",
  "The Judge and the Sheriff are dead.": "Thẩm Phán và Cảnh Sát Trưởng đều đã chết.",
  "Your Scores": "Điểm Số Của Bạn",
  "Requires Shooting Level 4": "Yêu cầu Cấp độ Bắn Súng 4",
  "Fitness Guru": "Chuyên Gia Thể Hình",
  "She's been hiding from the authorities for years. Hiding from zombies shouldn't be a problem. Knows her way around an AK-47.": "Cô ta đã trốn tránh chính quyền nhiều năm rồi. Chạy trốn khỏi lũ zombie chắc cũng chẳng thành vấn đề. Rất thành thạo khẩu AK-47.",
  "Medical Advice": "Lời Khuyên Y Tế",
  "Building Supplies": "Vật Liệu Xây Dựng",
  "They're scratching at the damn gates over here. The sooner you get him in the air, the sooner we can all get the fuck out. Now GO.": "Bọn chúng đang cào cấu vào cái cổng chết tiệt ở đây. Cậu đưa hắn cất cánh càng sớm thì tất cả chúng ta càng nhanh chóng thoát khỏi đây. ĐI NGAY.",
  "Shit, at this rate I'd settle for a slingshot. Better luck finding ammo for it at least.": "Chết tiệt, cứ cái đà này thì tôi thà xài súng cao su còn hơn. Ít nhất còn có cơ may tìm được đạn cho nó.",
  "This location is tactically unsound.": "Vị trí này không khả thi về mặt chiến thuật.",
  "Extreme sports, indeed!": "Thể thao mạo hiểm thực thụ đấy!",
  "LOG: LZ is Secure": "NHẬT KÝ: Khu Vực Hạ Cánh (LZ) đã an toàn",
  "Emerson": "Emerson",
  "Placing explosive ordnance around the perimeter allows us to dramatically thin each oncoming horde before engaging them in CQB.": "Việc bố trí thuốc nổ quanh vành đai sẽ giúp chúng ta tiêu diệt bớt bầy đàn đang kéo tới trước khi tiến hành cận chiến.",
  "They're in a tough spot. Can you give them an escort?": "Họ đang ở tình thế khó khăn. Cậu có thể hộ tống họ không?",
  "Raven": "Raven",
  "Crowbar": "Xà Beng",
  "Requires Shooting Level 5": "Yêu cầu Cấp độ Bắn Súng 5",
  "Ofelia": "Ofelia",
  "87 GENERIC Harold Atede": "87 GENERIC Harold Atede",
  "The new group we brought in didn't last, but I'm glad we tried to help them. - %1$s": "Nhóm mới mà chúng ta đưa về không sống sót được lâu, nhưng tôi rất vui vì chúng ta đã cố gắng giúp họ. - %1$s",
  "Enclave %1$s (Trust %2$d)": "Khu Tị Nạn %1$s (Niềm tin %2$d)",
  "What's the latest news from home?": "Có tin tức gì mới ở nhà không?",
  "Works equally well on zombies and cod.": "Hiệu quả ngang nhau đối với cả zombie lẫn cá tuyết.",
  "Requires SUDOKU CHEAT SHEET.": "Yêu cầu TỜ BÍ KÍP SUDOKU.",
  "Practice Weapons": "Vũ Khí Luyện Tập",
  "Better take care of that feral.": "Tốt hơn là giải quyết luôn con Feral đó đi.",
  "Tiana": "Tiana",
  "Pops up to head height for optimal zombie killing.": "Bật lên ngang tầm đầu để tiêu diệt zombie tối ưu nhất.",
  "You want two halves of a phone book? I've got a lot lying around.": "Cậu muốn hai nửa cuốn danh bạ điện thoại không? Tôi có cả đống vứt lung tung ở đây.",
  "Hatchback": "Hatchback",
  "Johari": "Johari"
};

const file = 'output/languages/chunks/btxt_chunk_102.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_102.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk102[r.sourceText]) {
    r.translatedText = chunk102[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 102 successfully!');
