const fs = require('fs');
const chunk145 = {
  "Sniper Qualified": "Đạt Chuẩn Xạ Thủ Bắn Tỉa (Sniper Qualified)",
  "I hate those things.": "Tôi ghét mấy cái thứ đó.",
  "Has a gift, as promised.": "Có một món quà, như đã hứa.",
  "LOG: Tunnel Sasquatch": "NHẬT KÝ: Đường Hầm Sasquatch",
  "I can't do this one on foot.": "Tôi đéo thể làm việc này bằng cách đi bộ được.",
  "This right here! This is the person to watch!": "Chính là người này đây! Đây là người đáng để theo dõi!",
  "Why do I doubt you're helping this guy out of the goodness of your hearts, huh?": "Tại sao tôi lại nghi ngờ việc mấy người đang giúp anh chàng này xuất phát từ lòng tốt của mấy người nhỉ, hả?",
  "I dunno. Let's just take a look around, see if we can find a first aid kit. Maybe some food.": "Tôi đéo biết. Hãy cứ nhìn xung quanh xem liệu chúng ta có thể tìm thấy bộ sơ cứu nào đéo. Hoặc có thể là một ít đồ ăn.",
  "Zoe": "Zoe",
  "I mean, all this running, shooting, climbing, driving shit, it's exactly like playing on-line co-op with my buddies!": "Ý tôi là, tất cả những cái trò chạy nhảy, bắn súng, leo trèo, lái xe chết tiệt này, nó y hệt như đang chơi co-op trực tuyến với mấy thằng bạn tôi vậy!",
  "Schroder": "Schroder",
  "Saws": "Cưa (Saws)",
  "Thanks for coming to get me. I'm ready to leave now.": "Cảm ơn vì đã đến đón tôi. Tôi đã sẵn sàng để đi ngay bây giờ.",
  "If that's true ... I think we may have something in common after all.": "Nếu điều đó là thật ... Tôi nghĩ rốt cuộc thì chúng ta cũng có vài điểm chung đấy.",
  "Joshua": "Joshua",
  "Blow Up the Barrier?": "Cho nổ rào chắn đéo?",
  "+125%": "+125%",
  "One of those feral zombies has been lurking around here.": "Một trong những con feral zombie đó đang lảng vảng quanh đây.",
  "Trust me. I'll never look at the tailpipe of a '72 Falconer Hatchback the same way again.": "Tin tôi đi. Tôi sẽ đéo bao giờ nhìn vào cái ống xả của một chiếc Falconer Hatchback đời '72 theo cùng một cách như thế nữa đâu.",
  "Aw dammit.": "Ôi chết tiệt.",
  "Wait ... we have a tank?": "Chờ đã ... chúng ta có xe tăng sao?",
  "You broke the law, sir, and the people here need to know that breaking the law still has consequences. At least as long as I'm in charge.": "Ngài đã vi phạm luật, thưa ngài, và những người ở đây cần phải biết rằng việc phá vỡ luật lệ vẫn đi kèm với hậu quả. Ít nhất là chừng nào tôi còn nắm quyền.",
  "Uncle John used to take me and my cousins camping every summer. Taught us how to navigate with a compass, make fish hooks out of twigs, how to make a fire...": "Chú John từng đưa tôi và mấy đứa em họ đi cắm trại vào mỗi mùa hè. Chú dạy chúng tôi cách định vị bằng la bàn, làm lưỡi câu từ cành cây, cách nhóm lửa...",
  "Gamer PUID": "PUID Game Thủ (Gamer PUID)",
  "Gurubani": "Gurubani",
  "Need a good cook.": "Cần một đầu bếp giỏi.",
  "Jesus Christ!": "Lạy Chúa!",
  "Mickey and Job have some kind of deal going down, and they want me as a neutral observer. - %1$s": "Mickey và Job đang có một thỏa thuận nào đó, và họ muốn tôi làm một người quan sát trung lập. - %1$s",
  "Found some materials.": "Tìm thấy một ít vật liệu (materials).",
  "Lily has her father's watch back. I'm glad I could make a difference ... though I wish I'd been able to do more while he was still alive.": "Lily đã lấy lại được chiếc đồng hồ của cha cô ấy. Tôi rất vui vì mình có thể làm được điều gì đó ... mặc dù tôi ước mình đã có thể làm được nhiều hơn khi ông ấy vẫn còn sống.",
  "Help the Wilkersons resolve their differences.": "Giúp nhà Wilkersons giải quyết những sự bất đồng của họ.",
  "Scavengers Inbound": "Đội Nhặt Mót (Scavengers) Đang Đến",
  "No, this is a waste of time.": "Đéo, việc này đúng là lãng phí thời gian.",
  "While standing still, hold [sprint] + [cover] to automatically counter all incoming attacks.": "Trong khi đứng yên, giữ [sprint] + [cover] để tự động phản công lại tất cả các đòn tấn công đang lao tới.",
  "Bertolucci": "Bertolucci",
  "Waypoint (Survey)": "Điểm Đánh Dấu (Quan Sát)",
  "You're a cold-hearted son of a bitch, you know that?": "Cậu là một thằng chó đẻ máu lạnh, cậu biết điều đó đéo?",
  "For grenade launchers. Obviously.": "Dùng cho súng phóng lựu. Rõ ràng là vậy.",
  "Safe Haven": "Nơi Trú Ẩn An Toàn",
  "Just about lost 'em.": "Suýt chút nữa thì mất dấu chúng.",
  "Oh god don't let me die!": "Ôi lạy chúa, đừng để tôi chết!",
  "Classic Sedan": "Xe Sedan Cổ Điển",
  "Well you can blame that on everybody being at each others' throats. Not all those injuries are from zombies.": "Chà, cô có thể đổ lỗi cho việc mọi người đang cắn xé lẫn nhau đấy. Đéo phải tất cả những vết thương đó đều là do bọn zombie gây ra đâu.",
  "We don't know what's on the other side of that pass. We're going to need food, medicine, transportation... you know. The usual.": "Chúng ta đéo biết có thứ gì đang chờ ở phía bên kia hẻm núi đó đâu. Chúng ta sẽ cần thức ăn, thuốc men, phương tiện đi lại... cậu biết đấy. Vẫn như mọi khi.",
  "Well, that's just perfect.": "Chà, thế thì hoàn hảo quá rồi.",
  "START MISSION. Help out in exchange for their most plentiful resource.": "BẮT ĐẦU NHIỆM VỤ. Giúp đỡ để đổi lấy loại tài nguyên dồi dào nhất của họ.",
  "What are you doing in here?": "Cậu đang làm cái quái gì trong này vậy?",
  "Holiday Pie": "Bánh Nướng Ngày Lễ",
  "Killin' time!": "Giết thời gian!",
  "We have a juggernaut roaming out there, and we need to take it down ASAP.": "Chúng ta có một con juggernaut đang lảng vảng ngoài kia, và chúng ta cần phải hạ gục nó CÀNG SỚM CÀNG TỐT (ASAP).",
  "At least we're pretty well set for medical emergencies.": "Ít nhất thì chúng ta cũng được chuẩn bị khá tốt cho các trường hợp khẩn cấp về y tế.",
  "MISSION FAILED: Fear Itself": "NHIỆM VỤ THẤT BẠI: Nỗi Sợ Hãi Bản Năng (Fear Itself)",
  "Eric": "Eric",
  "Dubois": "Dubois",
  "Gavin": "Gavin",
  "I went to draw some ammo from our stores this morning. Guess what I found.": "Sáng nay tôi định đi lấy một ít đạn từ kho dự trữ của chúng ta. Đoán xem tôi đã tìm thấy gì.",
  "Let's get some barricades up on these windows.": "Hãy dựng rào chắn lên mấy cái cửa sổ này đi.",
  "Someone's Belongings": "Đồ Đạc Của Ai Đó",
  "I know y'all missed me, but I'll be comin' home soon.": "Tôi biết tất cả mọi người đều nhớ tôi, nhưng tôi sẽ về nhà sớm thôi.",
  "Nagle! Hernandez! Where the fuck are you guys?": "Nagle! Hernandez! Mấy cậu đang ở cái xó xỉnh chết tiệt nào vậy?",
  "The more infestations there are, the more dangerous the streets get.": "Càng có nhiều ổ dịch (infestations), đường phố càng trở nên nguy hiểm.",
  "Keep it quiet, will you?": "Giữ im lặng đi, được đéo?",
  "PERSONAL SKILL. Sure, it's nice having a good cook or somebody that can keep the peace around, but a good medic's worth their weight in ammo. You know it, I know it.": "KỸ NĂNG CÁ NHÂN. Đương nhiên, có một đầu bếp giỏi hay ai đó có khả năng giữ gìn hòa bình thì cũng tốt thôi, nhưng một người lính cứu thương giỏi thì đáng giá bằng cả đống đạn dược đấy. Cậu biết điều đó, tôi cũng biết điều đó.",
  "Come on. You? You're carrying this.": "Thôi nào. Cậu á? Cậu đang mang thứ này sao.",
  "Delivered the goods.": "Đã giao hàng.",
  "Missions won't stick around forever.": "Nhiệm vụ sẽ đéo tồn tại mãi mãi đâu.",
  "Kill The Zombies In The Building": "Tiêu Diệt Bọn Zombie Đang Ở Trong Tòa Nhà",
  "I think that woman was in charge--Captain Montressor or something. Not like she even looked at us.": "Tôi nghĩ người phụ nữ đó là người chịu trách nhiệm--Đại úy Montressor hay gì đó. Mà có vẻ cô ta còn đéo thèm nhìn chúng ta lấy một cái.",
  "It’s a long shot … but keep your eyes open, okay? If we have another chance like that, we should take it.": "Dù là hy vọng mong manh … nhưng hãy mở to mắt ra mà nhìn nhé, được đéo? Nếu chúng ta có một cơ hội khác như thế, chúng ta nên nắm lấy nó.",
  "Bauer": "Bauer",
  "Patriot Sedan Sport Series": "Dòng Thể Thao Patriot Sedan",
  "TIP: After exploring for a while, you will FATIGUE, lowering your available stamina.": "MẸO: Sau khi khám phá một thời gian, bạn sẽ bị MỆT MỎI (FATIGUE), làm giảm lượng thể lực khả dụng.",
  "We need to do something about those infestations.": "Chúng ta cần phải làm gì đó với những ổ dịch (infestations) kia.",
  "COMPLETED: Zombie Infestation": "ĐÃ HOÀN THÀNH: Ổ Dịch Zombie (Zombie Infestation)",
  "Rule #2": "Quy Tắc Số 2",
  "Fuel reserves were looking iffy even before this.": "Dự trữ nhiên liệu vốn đã trông đéo ổn chút nào từ trước chuyện này rồi.",
  "Kill a Screamer with fire.": "Tiêu diệt một con Screamer bằng lửa.",
  "One of the first responders to the Marshall food riots.": "Một trong những người ứng cứu đầu tiên cho các cuộc bạo loạn tranh giành thức ăn ở Marshall.",
  "Nah, Doc's good people. He can be a little... crusty sometimes though.": "Đéo, Bác sĩ là người tốt mà. Dù thi thoảng ông ấy có thể hơi... cộc cằn một chút.",
  "Listen, we're stuck up here on Mt. Tanner. My friend needs medical attention, can you help us?": "Nghe này, chúng tôi bị kẹt trên Núi Tanner. Bạn tôi cần được chăm sóc y tế, anh có thể giúp chúng tôi được đéo?",
  "-5 Friendship.": "-5 Tình Bạn (Friendship).",
  "SCAVENGING: Materials": "NHẶT MÓT (SCAVENGING): Vật liệu",
  "There's no point in any of this. (Suicide risk)": "Mọi thứ đéo còn ý nghĩa gì nữa. (Nguy cơ tự sát)",
  "Something to protect our perimeter. Having a watchtower increases the safe area around our home.": "Thứ gì đó để bảo vệ chu vi của chúng ta. Việc có một tháp canh (watchtower) sẽ làm tăng khu vực an toàn xung quanh nhà của chúng ta.",
  "Not a Rat": "Đéo Phải Kẻ Phản Bội (Not a Rat)",
  "I'll... I'll think about it.": "Tôi sẽ... Tôi sẽ suy nghĩ về chuyện đó.",
  "Looks like somebody's in trouble down there.": "Có vẻ như ai đó đang gặp rắc rối ở dưới đó.",
  "Cheap, chain-store blade.": "Loại lưỡi kiếm rẻ tiền, bán ở các cửa hàng chuỗi.",
  "Hey, are you expecting to find a dead body or anything? 'Cause I can wait outside.": "Này, cậu có đang mong sẽ tìm thấy một cái xác chết hay gì đó đéo? Vì tôi có thể đợi ở ngoài.",
  "No shit. Any chance we can just hole up here with the last of the tequila until this all blows over?": "Đéo đùa chứ. Liệu có cơ hội nào để chúng ta cứ trốn tịt ở đây với chỗ rượu tequila còn lại cho đến khi mọi chuyện trôi qua đéo?",
  "If this weren't the end of the world, I'd be feeling pretty good right now.": "Nếu đây đéo phải là ngày tận thế, tôi đã cảm thấy khá tuyệt vào lúc này rồi.",
  "Owes the Wilkersons some AMMO. Doesn't have it.": "Đang nợ bọn Wilkersons một ít ĐẠN (AMMO). Nhưng lại đéo có.",
  "Mess": "Mớ Hỗn Độn",
  "I can smell a bloater from a mile away, so trust me when I say there's one right around here.": "Tôi có thể ngửi thấy mùi của một con bloater từ cách xa một dặm cơ, nên hãy tin tôi khi tôi nói rằng có một con đang ở ngay quanh đây.",
  "Salutations!": "Xin chào (Salutations)!",
  "Coming Soon": "Sắp Ra Mắt",
  "Jill": "Jill",
  "Bachman": "Bachman",
  "Join up with us, and maybe we'll all get out alive.": "Gia nhập cùng với chúng tôi, và có lẽ tất cả chúng ta sẽ thoát ra khỏi đây sống sót.",
  "You coming? This is important.": "Cậu có tới đéo? Chuyện này rất quan trọng."
};

const file = 'output/languages/chunks/btxt_chunk_145.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_145.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk145[r.sourceText]) {
    r.translatedText = chunk145[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 145 successfully!');
