const fs = require('fs');
const chunk140 = {
  "I was unarmed for the first couple of days cuz I didn't want to ding up any of my bats. Had a game-used Babe Ruth, you know? (Sports Trivia whiz.)": "Tôi đã đéo mang vũ khí trong vài ngày đầu vì tôi đéo muốn làm hỏng bất kỳ cây gậy đánh bóng nào của mình. Tôi từng có một cây Babe Ruth đã qua sử dụng trong trận đấu, cậu biết đéo? (Chuyên Gia Câu Đố Thể Thao.)",
  "Worst. Vacation. Ever.": "Kỳ nghỉ. Tồi tệ. Nhất trần đời.",
  "SURVIVAL TACTICS: Noise Attracts Zeds": "CHIẾN THUẬT SINH TỒN: Tiếng Ồn Thu Hút Lũ Zed",
  "Nice going, boss!": "Làm tốt lắm, sếp!",
  "Ellis": "Ellis",
  "Reece": "Reece",
  "Maybe it's just me, but bringing people home safe feels like a bigger win than killing zombies. Like it's not a zero-sum game any more, you know?": "Có thể chỉ là do tôi, nhưng việc đưa mọi người về nhà an toàn mang lại cảm giác chiến thắng lớn hơn là việc giết zombie. Giống như nó đéo còn là một trò chơi có tổng bằng đéo (zero-sum) nữa, cậu biết chứ?",
  "Yeah? Well excuse me for being a little stressed out over the end of the world!": "Vậy sao? Chà, xin lỗi vì tôi đã hơi căng thẳng trước ngày tận thế nhé!",
  "When you work as a team, good things happen.": "Khi các bạn làm việc như một đội, những điều tốt đẹp sẽ đến.",
  "In Pace Requiescat": "Mong Người Yên Nghỉ (In Pace Requiescat)",
  "A great tool for apocalypse gardening.": "Một công cụ tuyệt vời cho việc làm vườn thời tận thế.",
  "Fitness Regimen": "Chế Độ Tập Luyện",
  "We'll get packed up and head to the base.": "Chúng tôi sẽ thu dọn đồ đạc và tiến về căn cứ.",
  "We've run into a bit of a snag.": "Chúng ta vừa vấp phải một chút trở ngại.",
  "It's damn good to see a friendly face.": "Thật cmn tốt khi được thấy một gương mặt thân thiện.",
  "Well. It sounds like there were no survivors.": "Chà. Nghe có vẻ như đéo có ai sống sót.",
  "Look, we're not going home until we find Jack, okay? So quit with the bitching already.": "Nghe này, chúng ta sẽ đéo về nhà cho đến khi tìm thấy Jack, được đéo? Vậy nên bớt cằn nhằn lại đi.",
  "So what happened anyway?": "Vậy rốt cuộc chuyện gì đã xảy ra?",
  "Thinks we're all in this together.": "Nghĩ rằng tất cả chúng ta đều ở chung trên một con thuyền.",
  "+66%": "+66%",
  "41 GENERIC Mike Daroca": "41 GENERIC Mike Daroca",
  "But when I sent out your calls for help, it was the army who answered.": "Nhưng khi tôi phát đi lời cầu cứu của cậu, chính quân đội là những người đã hồi đáp.",
  "We've got a Sergeant running the show now. Check out the Ops Center to see what they're capable of.": "Bây giờ chúng ta đã có một Trung sĩ điều hành mọi việc. Hãy kiểm tra Trung tâm Chỉ huy (Ops Center) để xem họ có khả năng gì.",
  "I've had just about enough of her bullshit.": "Tôi đã chịu đựng quá đủ cái thứ nhảm nhí của cô ta rồi.",
  "Good luck, folks. Maybe I'll see you in person. Or on the other side.": "Chúc may mắn, mọi người. Có thể tôi sẽ gặp trực tiếp các bạn. Hoặc là ở thế giới bên kia.",
  "Direct descendant of Ezekiel Marshall himself.": "Hậu duệ trực tiếp của chính Ezekiel Marshall.",
  "Fucking help me!": "Cứu tao với, chết tiệt!",
  "I think we can eliminate the worst threat.": "Tôi nghĩ chúng ta có thể loại bỏ được mối đe dọa tồi tệ nhất.",
  "Shotgun: Russian 12K": "Súng shotgun: Russian 12K",
  "I keep thinking about the last drive I made through town. The last one before, I mean.": "Tôi cứ nghĩ mãi về chuyến đi cuối cùng tôi lái xe qua thị trấn. Ý tôi là, chuyến đi cuối cùng trước khi mọi chuyện xảy ra.",
  "I've seen, like, three guys get bit by zeds, and none of them died.": "Tôi đã thấy, kiểu như, ba người bị lũ zed cắn, và đéo có ai trong số họ chết cả.",
  "We're going to need to go on a little scavenger hunt.": "Chúng ta sẽ cần phải tham gia vào một cuộc đi săn đồ nhỏ đấy.",
  "Rotholz": "Rotholz",
  "Killed one of each freak zombie type.": "Đã tiêu diệt mỗi loại freak zombie một con.",
  "Gel": "Gel",
  "Proceed": "Tiến hành",
  "We're gonna need more construction materials soon, or this place is gonna fall down around our ears.": "Chúng ta sẽ sớm cần thêm vật liệu xây dựng, nếu đéo nơi này sẽ sụp đổ ngay trên đầu chúng ta mất.",
  "MORALE ISSUE: Boastful Personality": "VẤN ĐỀ TINH THẦN: Tính Cách Khoe Khoang",
  "Control Increased!": "Khả Năng Kiểm Soát Được Tăng Cường!",
  "Yup. Gonna be a good season.": "Đúng vậy. Sẽ là một mùa màng bội thu đây.",
  "Doesn't take anything too seriously. Worrying only makes things worse.": "Đéo quá coi trọng bất cứ điều gì. Việc lo lắng chỉ làm mọi thứ tồi tệ hơn mà thôi.",
  "Based on the AK design, this is a battle tested and reliable weapon.": "Dựa trên thiết kế của AK, đây là một loại vũ khí đáng tin cậy và đã được kiểm chứng trong thực chiến.",
  "Rifle: Model 1903": "Súng trường: Model 1903",
  "Guess I've wasted enough of your time--let's get out of here.": "Tôi đoán mình đã làm lãng phí đủ thời gian của cậu rồi -- ra khỏi đây thôi.",
  "I knew I could rely on you. By all means, you drive. It's not too far.": "Tôi biết mình có thể dựa vào cậu mà. Bằng mọi giá, cậu lái xe đi. Đéo xa lắm đâu.",
  "Sir, we've located army personnel in need of assistance. Transmitting coordinates now.": "Thưa sếp, chúng tôi đã xác định được vị trí của quân nhân đang cần hỗ trợ. Đang truyền tải tọa độ ngay bây giờ.",
  "If there's any part of you that can understand me, I'm sorry.": "Nếu có phần nào trong cô còn có thể hiểu được tôi, thì tôi xin lỗi.",
  "But now I'm hearing about an outpost by the highway, where a few brave soldiers are sticking around to save whoever they can.": "Nhưng bây giờ tôi đang nghe nói về một tiền đồn gần đường cao tốc, nơi có một vài người lính dũng cảm đang bám trụ để cứu bất cứ ai mà họ có thể.",
  "I found some supplies.": "Tôi đã tìm thấy vài món nhu yếu phẩm.",
  "Nothing worse than trying to take a shot with an empty magazine.": "Đéo có gì tệ hơn việc cố bắn với một băng đạn trống rỗng.",
  "Nothing.": "Đéo có gì.",
  "Give that noisemaker a little more room next time!": "Lần sau nhớ chừa thêm chút khoảng trống cho cái thứ tạo tiếng ồn đó nhé!",
  "She finally had enough a few years back; took our son to live in the city. Said it would be a more enriching environment for him.": "Vài năm trước, cô ấy cuối cùng cũng đéo chịu đựng nổi nữa; đã đưa con trai chúng tôi đến sống ở thành phố. Bảo rằng đó sẽ là một môi trường phong phú hơn cho thằng bé.",
  "We're about done. Thank you, by the way. I couldn't have done this without you.": "Chúng ta sắp xong rồi. Nhân tiện, cảm ơn nhé. Tôi sẽ đéo thể làm được việc này nếu đéo có cậu.",
  "Killed 3 zombies with an exploding propane tank.": "Đã tiêu diệt 3 zombie bằng một bình gas phát nổ.",
  "We're gonna have to leave the valley, aren't we? We can't keep drinking this.": "Chúng ta sẽ phải rời khỏi thung lũng, phải đéo? Chúng ta đéo thể tiếp tục uống thứ này được.",
  "PERSONAL SKILL. Coffee's for closers only.": "KỸ NĂNG CÁ NHÂN. Cà phê chỉ dành cho người chốt hạ (closers).",
  "I still can't believe that fight escalated to shooting.": "Tôi vẫn đéo thể tin được cuộc cãi vã đó lại leo thang thành một vụ nổ súng.",
  "You got eyes on that shit behind us?": "Cậu có đang để mắt tới cái đống chết tiệt đằng sau chúng ta đéo?",
  "You're welcome.": "Đéo có chi.",
  "Build everything faster with electric power tools. (+100% Construction Speed)": "Xây dựng mọi thứ nhanh hơn bằng các công cụ điện. (+100% Tốc Độ Xây Dựng)",
  "FACILITIES UNLOCKED": "ĐÃ MỞ KHÓA CÁC CƠ SỞ VẬT CHẤT (FACILITIES)",
  "Fetch Doc Hanson.": "Đi tìm Bác sĩ Hanson.",
  "Defend the Survivors": "Bảo Vệ Những Người Sống Sót",
  "More of them? I'll be damned. We're gonna ding the fender at this rate.": "Lại thêm nữa à? Tôi sẽ chết tiệt mất. Chúng ta sẽ làm móp cái chắn bùn mất nếu cứ đà này.",
  "Needs help ASAP.": "Cần được giúp đỡ CÀNG SỚM CÀNG TỐT (ASAP).",
  "Megan": "Megan",
  "We couldn't protect Vienna in that tunnel, so she fled, leaving the nuke still armed. Most of us hope she's still alive somewhere.": "Chúng ta đã đéo thể bảo vệ Vienna trong đường hầm đó, thế nên cô ấy đã bỏ trốn, để lại quả bom hạt nhân vẫn đang trong trạng thái kích hoạt. Hầu hết chúng ta đều hy vọng cô ấy vẫn còn sống ở một nơi nào đó.",
  "Tiberius": "Tiberius",
  "It's really tearing into something in this pile of trash. So I yell at it to get lost before it takes a shit, and when it takes off, guess what I see?": "Nó thực sự đang xé toạc thứ gì đó trong đống rác này. Thế nên tôi quát nó cút đi trước khi nó ỉa bậy ra đó, và khi nó bỏ chạy, cậu đoán xem tôi đã thấy gì?",
  "Shit! Gotta get out of here!": "Chết tiệt! Phải chuồn khỏi đây thôi!",
  "Going to search nearby buildings.": "Đang đi lục soát các tòa nhà lân cận.",
  "Locate a Functional RV": "Tìm Một Chiếc RV Còn Hoạt Động",
  "Completely unflappable in the face of danger ... and completely unreasonable in social situations.": "Hoàn toàn đéo hề nao núng khi đối mặt với nguy hiểm ... và cũng hoàn toàn vô lý trong các tình huống giao tiếp xã hội.",
  "Crusty, huh?": "Gắt gỏng nhỉ?",
  "Hope you're geared up. We've got a few infestations to deal with.": "Hy vọng cậu đã trang bị đầy đủ. Chúng ta có một vài ổ dịch cần phải giải quyết đấy.",
  "Crazy Cat Person": "Người Yêu Mèo Cuồng Nhiệt",
  "Polycarbonate Sheets": "Các Tấm Polycarbonate",
  "Right, I'm sure there's some other world you gotta save right now.": "Phải rồi, tôi chắc là cậu đang bận đi giải cứu một thế giới nào khác ngay bây giờ.",
  "Rifle: Monag 90/31": "Súng trường: Monag 90/31",
  "I need a vehicle at my position": "Tôi cần một phương tiện ở vị trí của mình",
  "Not like any of us are gonna get out of this alive. Might as well just mix up a big old batch of cyanide punch and wait for the dark. - %1$s": "Làm gì có chuyện ai trong chúng ta thoát khỏi đây mà còn sống chứ. Thà cứ pha một mẻ xyanua lớn rồi chờ bóng tối buông xuống còn hơn. - %1$s",
  "Shotgun: CLEO Revo Shotgun": "Súng shotgun: CLEO Revo Shotgun",
  "Get these things out of here!": "Đưa mấy thứ này ra khỏi đây ngay!",
  "Not now. I'll let you know when I'm ready.": "Bây giờ đéo được. Tôi sẽ cho cậu biết khi tôi sẵn sàng.",
  "Almost ready to go. Just give me a few more seconds.": "Gần xong rồi. Chỉ cần cho tôi thêm vài giây nữa thôi.",
  "%1$s and %2$s wiped out a bunch of zombies before they became a threat. Cost us some ammo, but the morale boost's worth it! -%3$s": "%1$s và %2$s đã quét sạch một đám zombie trước khi chúng trở thành mối đe dọa. Dù tốn của chúng ta một ít đạn, nhưng cú huých tinh thần này hoàn toàn xứng đáng! -%3$s",
  "Delivered %1$s to %2$s": "Đã giao %1$s cho %2$s",
  "C'mon. We need to put up some barricades.": "Nào. Chúng ta cần dựng một số chướng ngại vật lên.",
  "Several Pints of Honey": "Vài Lít Mật Ong",
  "Lifesaving food and medical supplies to keep us going until the mission is complete.": "Lương thực và vật tư y tế cứu sinh để duy trì sự sống cho đến khi nhiệm vụ hoàn thành.",
  "LEVEL 4. Reloading a gun always looks so easy in the movies. Took me a while to get the hang of it. I'm so much more efficient now.": "CẤP 4. Việc nạp đạn luôn trông có vẻ rất dễ dàng trên phim ảnh. Đã mất một thời gian để tôi quen với nó. Bây giờ thì tôi đã làm hiệu quả hơn rất nhiều.",
  "No more food after that.": "Đéo còn thức ăn sau chuyện đó.",
  "Yeah, I think we could use a change in scenery.": "Phải, tôi nghĩ chúng ta có thể cần đổi gió một chút.",
  "Escort": "Hộ Tống",
  "Wonder what he needs? - %1$s": "Đéo biết anh ấy cần gì nhỉ? - %1$s",
  "We should set up some defenses.": "Chúng ta nên thiết lập một số tuyến phòng thủ.",
  "Thank you for this. We won't let you down.": "Cảm ơn vì điều này. Chúng tôi sẽ đéo làm cậu thất vọng đâu.",
  "Ask me again tomorrow, I'm beat.": "Ngày mai hãy hỏi tôi lại nhé, tôi đuối lắm rồi.",
  "We don't have enough ammo for everybody.": "Chúng ta đéo có đủ đạn cho tất cả mọi người đâu."
};

const file = 'output/languages/chunks/btxt_chunk_140.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_140.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk140[r.sourceText]) {
    r.translatedText = chunk140[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 140 successfully!');
