const fs = require('fs');
const chunk122 = {
  "These should help.": "Những thứ này sẽ giúp ích đấy.",
  "I need a situation report on base activities.": "Tôi cần một báo cáo tình hình về các hoạt động của căn cứ.",
  "It isn't too serious ... but it's a lot harder to swing a weapon with only one decent hand. (Melee XP penalty)": "Không quá nghiêm trọng ... nhưng sẽ khó khăn hơn rất nhiều khi vung vũ khí với chỉ một tay lành lặn. (Giảm XP Cận chiến)",
  "We need to hurry.": "Chúng ta cần phải khẩn trương.",
  "PERSONAL SKILL. No, no, no, I said an *Erlenmeyer* flask!": "KỸ NĂNG CÁ NHÂN. Không, không, không, tôi đã nói là một bình nón *Erlenmeyer* cơ mà!",
  "His ex owns a good chunk of his paycheck. He says he's caught up, but she would disagree.": "Vợ cũ của anh ta chiếm một phần lớn tiền lương của anh. Anh ta nói là đã trả đủ, nhưng cô ấy thì đéo nghĩ vậy.",
  "Dammit, I've searched this place from top to bottom. It's not here!": "Chết tiệt, tôi đã lục soát nơi này từ trên xuống dưới rồi. Nó không có ở đây!",
  "PMC Reinforcements": "Viện Binh PMC",
  "The Scion": "Người Thừa Kế (The Scion)",
  "TIP: Tap [cover] to defend.": "MẸO: Nhấn [cover] để phòng thủ.",
  "Could you?": "Cậu có thể không?",
  "Abe": "Abe",
  "I want this outpost running ASAP.": "Tôi muốn tiền đồn này hoạt động CÀNG SỚM CÀNG TỐT.",
  "You really know your stuff. Thanks.": "Cậu rất am hiểu về những thứ này. Cảm ơn nhé.",
  "It's going to get us the hell out of here.": "Nó sẽ đưa chúng ta cút khỏi cái chỗ quỷ quái này.",
  "Is it empty?": "Nó trống rỗng à?",
  "So tell me...how are you doing?": "Vậy nói tôi nghe xem... cậu dạo này thế nào?",
  "Okay, got everything we can.": "Được rồi, đã lấy mọi thứ có thể.",
  "You gonna aim that thing, or flail around like you're in a bad action movie?": "Cậu định nhắm bắn cái thứ đó, hay là vung vẩy lung tung như trong một bộ phim hành động rẻ tiền vậy?",
  "Blue felt-tip pen on white notepad. Three extra question marks.": "Bút dạ xanh trên sổ tay trắng. Thêm ba dấu chấm hỏi.",
  "Kitchen Timer": "Đồng Hồ Hẹn Giờ Bếp",
  "A well-stocked supply drop of army-issue munitions.": "Một hòm tiếp tế chứa đầy đủ đạn dược tiêu chuẩn quân đội.",
  "We are now dangerously low on ammo.": "Lượng đạn của chúng ta đang thấp ở mức báo động.",
  "Bloomberg": "Bloomberg",
  "Kitchen, bathroom, garage. The Holy Trinity of efficient scavenging.": "Nhà bếp, phòng tắm, nhà để xe. Bộ ba hoàn hảo của những chuyến đi nhặt mót hiệu quả.",
  "That guy is not right in the head. Trust me, we're better off without their \"protection.\"": "Gã đó có vấn đề về thần kinh. Tin tôi đi, chúng ta sẽ tốt hơn nếu không có sự \"bảo vệ\" của chúng.",
  "Killed a zombie with fire": "Đã thiêu chết một con zombie",
  "I'm out of ammo.": "Tôi hết đạn rồi.",
  "But uh, we should get moving. That fight's gonna draw more of them soon. See you around.": "Nhưng ừm, chúng ta nên đi thôi. Trận chiến đó sẽ sớm thu hút thêm nhiều bọn chúng đến. Hẹn gặp lại nhé.",
  "NO. Not our responsibility.": "KHÔNG. Không phải là trách nhiệm của chúng ta.",
  "Come help him out before it's too late.": "Đến giúp cậu ấy trước khi quá muộn đi.",
  "The Friend": "Người Bạn",
  "Let me put it in technical terms.": "Hãy để tôi giải thích bằng các thuật ngữ kỹ thuật.",
  "Them bridges have been empty for days now! The Army ain't even watching them, we get over the barricades and we can get all the guns we want!": "Mấy cây cầu đó đã vắng tanh mấy ngày nay rồi! Quân đội thậm chí còn không canh chừng ở đó, chúng ta vượt qua các rào chắn và có thể lấy tất cả súng ống mình muốn!",
  "ADVICE: Build an Outpost": "LỜI KHUYÊN: Xây dựng một Tiền đồn (Outpost)",
  "Lily, can our friends hold on a bit longer?": "Lily, những người bạn của chúng ta có thể cầm cự thêm chút nữa không?",
  "Looks like I'm here.": "Có vẻ như tôi đến nơi rồi.",
  "That fight tweaked my back something awful. I'm having a lot of trouble carrying my pack long distances. (Encumbrance penalty)": "Trận chiến đó đã làm lưng tôi bị vặn khủng khiếp. Tôi đang gặp rất nhiều khó khăn khi mang vác ba lô đi đường dài. (Phạt mang vác nặng)",
  "Uhh... it looked like it was all about to go bad. I swear. So I figured it was better for somebody to eat everything than to let it spoil. - %1$s": "Uhh... có vẻ như mọi thứ sắp hỏng hết rồi. Tôi thề đấy. Vì vậy tôi nghĩ thà để ai đó ăn hết mọi thứ còn hơn là để nó bị hỏng. - %1$s",
  "Still... it was pretty sweet.": "Dù sao... chuyện đó cũng khá ngọt ngào.",
  "Hmm, interesting.": "Hmm, thú vị đấy.",
  "Cole": "Cole",
  "I'm not making friends today.": "Hôm nay tôi đéo rảnh để kết bạn đâu.",
  "Recovered a backpack of gathered resources": "Đã thu hồi được một ba lô chứa tài nguyên thu thập",
  "Chronic Condition": "Tình Trạng Mãn Tính",
  "Nothing better than a homemade pie. Almost covers the smell of rotting death in the air.": "Không gì tuyệt hơn một chiếc bánh nướng tự làm. Gần như có thể át đi mùi tử thi thối rữa trong không khí.",
  "Crush the skull.": "Đập nát hộp sọ.",
  "One of ours is missing. Can you help?": "Một người của chúng ta đang bị mất tích. Cậu có thể giúp không?",
  "Makes a mean stroganoff.": "Làm món bò stroganoff rất tuyệt.",
  "An AR15 with some new furniture.": "Một khẩu AR15 với vài bộ phận ốp ngoài mới.",
  "Find the Survivors": "Tìm Những Người Sống Sót",
  "Same as usual.": "Vẫn như mọi khi.",
  "Gathered Supplies": "Vật tư Thu thập được",
  "All right, I'm in the area.": "Được rồi, tôi đang ở trong khu vực.",
  "Trait Discovered: \"Finding\" Supplies": "Đã Khám phá Đặc điểm: \"Tìm kiếm\" Vật tư",
  "%2$s disrespected me. I sure as shit wasn't going to let that go unanswered. - %1$s": "%2$s đã đéo tôn trọng tôi. Tôi đéo bao giờ để yên chuyện đó đâu. - %1$s",
  "Found %s!": "Đã tìm thấy %s!",
  "Basic Workshop": "Nhà Xưởng Cơ Bản",
  "Muller": "Muller",
  "Available Influence:": "Điểm Ảnh Hưởng Hiện Có:",
  "Come on, Lily, that's not fair.": "Thôi nào, Lily, thế thì không công bằng.",
  "Make it quick.": "Làm nhanh lên đi.",
  "Craig": "Craig",
  "Well, I think we can do better in the future.": "Chà, tôi nghĩ chúng ta có thể làm tốt hơn trong tương lai.",
  "He's going off on his own.": "Anh ấy đang tự ý rời đi một mình.",
  "Community Members": "Thành Viên Cộng Đồng",
  "You know? Some of you assholes ain't half bad.": "Biết không? Một vài tên khốn các người cũng không đến nỗi tệ lắm đâu.",
  "Westen": "Westen",
  "Stick with me, do what I say, and you'll be fine.": "Bám sát tôi, làm theo những gì tôi nói, và cậu sẽ ổn thôi.",
  "It's still out there.": "Nó vẫn còn ở ngoài kia.",
  "Saylor": "Saylor",
  "Times are tough, but a negative attitude doesn't help. Agreed?": "Thời điểm này đang rất khó khăn, nhưng một thái độ tiêu cực cũng đéo giúp ích gì đâu. Đồng ý không?",
  "Danforth is overrun with zeds. We have one chance to blow them up. If we wait, they'll spread all over the countryside.": "Danforth đã ngập tràn zed. Chúng ta có một cơ hội để cho nổ tung chúng. Nếu cứ chần chừ, chúng sẽ lan ra khắp các vùng nông thôn mất.",
  "Ortiz": "Ortiz",
  "Practiced Taxidermy": "Từng Thực Hành Nhồi Bông Động Vật",
  "Watch them barricades!": "Canh chừng mấy cái rào chắn đi!",
  "His daughter gives him hope": "Cô con gái đem lại hy vọng cho anh ấy",
  "Bergman": "Bergman",
  "Escaped Mt. Tanner and found the survivors at the church.": "Đã trốn thoát khỏi Núi Tanner và tìm thấy những người sống sót tại nhà thờ.",
  "Man, it is good to see that uniform. On somebody alive, I mean.": "Trời ạ, thật tốt khi thấy bộ đồng phục đó. Trên người một người còn sống, ý tôi là vậy.",
  "We're trying to get it set up, but we don't have everything we need.": "Chúng tôi đang cố gắng thiết lập nó, nhưng chúng tôi không có tất cả những thứ mình cần.",
  "Quiet, that's a Screamer.": "Im lặng, đó là một con Screamer.",
  "EXPIRED: Dr. Julene Horn": "ĐÃ QUA ĐỜI: Tiến sĩ Julene Horn",
  "COMMERCE: Food Preservation": "THƯƠNG MẠI: Bảo quản Thức ăn",
  "I'm not going to turn you away.": "Tôi sẽ không đuổi cậu đi đâu.",
  "Look out!": "Coi chừng!",
  "Practice makes perfect. Every character in the world has a unique set of skills and traits, some of which can impact combat effectiveness. Improve skills through use, then choose which specializations to unlock. Are you a stealth expert, able to sneak into any building? Or are you a one-shot zombie killing machine? Contextual Moves: Press [sprint] + [xi_use] for interactive moves such as pushing a zombie away or shoving it against a wall. Finishers: When an enemy is in a prone position, press [sprint] + [xi_use] to perform a finishing move.": "Có công mài sắt có ngày nên kim. Mọi nhân vật đều có một bộ kỹ năng và đặc điểm riêng, một số có thể ảnh hưởng đến hiệu quả chiến đấu. Cải thiện kỹ năng thông qua việc sử dụng, sau đó chọn chuyên môn để mở khóa. Bạn là chuyên gia hành động lén lút, có thể lẻn vào bất kỳ tòa nhà nào? Hay là cỗ máy giết zombie một-đòn-chết-luôn? Các Chiêu Tương Tác: Nhấn [sprint] + [xi_use] để đẩy zombie ra hoặc xô nó vào tường. Đòn Kết Liễu: Khi kẻ địch đang nằm sấp, nhấn [sprint] + [xi_use] để thực hiện đòn kết liễu.",
  "This is for you.": "Cái này là cho cậu.",
  "Gurubani added 4 Food, 4 Medicine, and 60 rounds of 7.62mm ammunition to our Supply Locker.": "Gurubani đã thêm 4 Thức ăn, 4 Thuốc men, và 60 viên đạn 7.62mm vào Tủ Đồ của chúng ta.",
  "Dan": "Dan",
  "Make .44 Ammo": "Chế tạo Đạn .44",
  "PERSONAL SKILL. People are inclined to listen to me and do what I say.": "KỸ NĂNG CÁ NHÂN. Mọi người có xu hướng lắng nghe tôi và làm theo những gì tôi nói.",
  "Homemade Painkiller": "Thuốc Giảm Đau Tự Chế",
  "I'll get an idea of what we have here while you plan our next move.": "Tôi sẽ nắm tình hình những thứ chúng ta có ở đây trong lúc cậu lên kế hoạch cho bước đi tiếp theo.",
  "Dramatically speeds up research projects.": "Đẩy nhanh đáng kể tiến độ các dự án nghiên cứu.",
  "A great idea ... should keep trying.": "Một ý tưởng tuyệt vời ... nên tiếp tục cố gắng.",
  "Looks empty, moving on.": "Trống không rồi, đi tiếp thôi.",
  "Let's hold off until we're more certain.": "Hãy khoan đã cho đến khi chúng ta chắc chắn hơn.",
  "I was just trying to tell Lily that we need to start looking for a new place to live.": "Tôi chỉ đang cố nói với Lily rằng chúng ta cần bắt đầu tìm một nơi ở mới.",
  "'Cause anything's better than sitting around here.": "Bởi vì làm gì cũng tốt hơn là ngồi ì ở đây."
};

const file = 'output/languages/chunks/btxt_chunk_122.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_122.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk122[r.sourceText]) {
    r.translatedText = chunk122[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 122 successfully!');
