const fs = require('fs');
const chunk181 = {
  "Build a facility.": "Xây dựng một cơ sở (facility).",
  "52 GENERIC Ricky Morrison": "52 CHUNG (GENERIC) Ricky Morrison",
  "At least we'll have plenty of room to grow.": "Ít nhất thì chúng ta cũng sẽ có nhiều không gian để phát triển.",
  "So yeah, we got some zed in armor not far from here. Ain't no problem.": "Đúng vậy, chúng ta có vài con zed mặc áo giáp ở cách đây đéo xa lắm. Đéo có vấn đề gì lớn đâu.",
  "This car better still be here when I get back.": "Tốt hơn hết là chiếc xe ô tô này vẫn còn ở đây khi tôi quay trở lại.",
  "This building is crawling with zombies. We could use some help clearing it.": "Tòa nhà này đang nhung nhúc đầy rẫy bọn zombies. Chúng tôi có thể cần một chút sự giúp đỡ để dọn dẹp sạch sẽ nó.",
  "Sepulveda": "Sepulveda",
  "Who sent you to get me? Was it Holkins? That friggin' guy... you can tell him I'm not leaving till I'm done searching this place.": "Ai đã cử cậu đến đón tôi vậy? Là Holkins phải đéo? Cái gã chết tiệt đó... cậu có thể nói với hắn ta rằng tôi sẽ đéo rời đi cho đến khi tôi tìm kiếm xong chỗ này đâu.",
  "Johansen": "Johansen",
  "Martial Artist": "Võ Sư (Martial Artist)",
  "%1$s has the flu. We knew it was going around, but didn't prepare. - %2$s": "%1$s đang bị cảm cúm. Chúng ta biết dịch bệnh đang lây lan, nhưng lại đéo hề chuẩn bị trước. - %2$s",
  "Look, truth is we're stretched pretty thin. Any help you could give us would be appreciated.": "Nghe này, sự thật là lực lượng của chúng tôi đang bị kéo giãn ra khá mỏng rồi. Bất cứ sự giúp đỡ nào mà cậu có thể dành cho chúng tôi đều sẽ được vô cùng trân trọng.",
  "I didn't like the look of 'em. Looked like %2$s was about to turn. I did what I had to. - %1$s": "Tôi đéo thích vẻ ngoài của bọn họ cho lắm. Trông có vẻ như %2$s đã chuẩn bị biến đổi (turn) cmnr. Tôi chỉ làm những gì mà tôi phải làm thôi. - %1$s",
  "Wish I could help, but I've got my own stuff to worry about.": "Tôi cũng ước gì mình có thể giúp, nhưng tôi còn có chuyện của riêng mình cần phải lo nữa.",
  "Haven't let us down... yet.": "Vẫn chưa làm cho chúng ta phải thất vọng... cho tới lúc này.",
  "Winner winner chicken dinner!": "Tuyệt vời ông mặt trời!",
  "We can export a copy of your current saved game to be loaded into State of Decay: Year-One Survival Edition on Xbox One.": "Chúng tôi có thể xuất (export) một bản sao từ dữ liệu lưu game hiện tại của bạn để tải nó vào tựa game State of Decay: Year-One Survival Edition trên hệ máy Xbox One.",
  "Okay, let's go. I've got all I can carry.": "Được rồi, đi thôi. Tôi đã lấy tất cả những gì tôi có thể mang theo được rồi.",
  "Our research project has run into some unexpected delays. - %1$s": "Dự án nghiên cứu (research project) của chúng ta đã gặp phải một số sự chậm trễ bất ngờ ngoài dự kiến. - %1$s",
  "Fine, go without me, it's your funeral.": "Được thôi, cứ đi đéo có tôi đi, đó sẽ là đám tang của cậu đấy.",
  "The beacon is down. Hope that means you're all right.": "Đèn hiệu báo động (beacon) đã tắt. Hy vọng điều đó có nghĩa là cậu đéo sao.",
  "Interested in combat training.": "Cảm thấy hứng thú với việc huấn luyện chiến đấu (combat training).",
  "EXTRACTED: Shira Bogatz": "ĐÃ CHIẾT XUẤT (EXTRACTED): Shira Bogatz",
  "An additional +10 Stamina for everyone. REQUIRES FITNESS EXPERT.": "Thêm +10 Thể Lực (Stamina) cho tất cả mọi người. YÊU CẦU CÓ CHUYÊN GIA THỂ HÌNH (FITNESS EXPERT).",
  "Intermittent civilian radio signals picked up from Trumbull Valley.\r\nCould be a provisional government asserting control of the situation.": "Thu nhận được các tín hiệu radio dân sự bị ngắt quãng phát ra từ Thung Lũng Trumbull.\r\nCó thể là một chính phủ lâm thời đang khẳng định quyền kiểm soát tình hình ở đó.",
  "Thank you. You're an answer to my prayer.": "Cảm ơn cậu. Cậu chính là câu trả lời cho lời cầu nguyện của tôi đấy.",
  "SCARED. I'm not sure we're gonna make it.": "SỢ HÃI. Tôi đéo chắc liệu chúng ta có thể vượt qua được chuyện này đéo.",
  "Yeah...": "Ừ...",
  "I need help.": "Tôi cần được giúp đỡ.",
  "You have new Events in your Journal! Press [ul_journal_menu] to open your Journal and review things that have happened to you on the Events page.": "Bạn có Sự Kiện (Events) mới trong Nhật Ký (Journal) của mình! Hãy nhấn [ul_journal_menu] để mở Nhật Ký lên và xem lại những chuyện đã xảy ra với bạn trong trang Sự Kiện.",
  "Jesus... no. No, I can't do this.": "Chúa ơi... đéo. Đéo, tôi đéo thể làm chuyện này đâu.",
  "Spoiler Delivery": "Vận Chuyển Cánh Gió Trực Thăng (Spoiler Delivery)",
  "Go get the explosives?": "Cậu sẽ đi lấy thuốc nổ chứ?",
  "Smith": "Smith",
  "Tomahawk": "Rìu Tomahawk",
  "%1$s left the community.": "%1$s đã rời khỏi cộng đồng.",
  "Good thing you found me when you did. Pretty sure somebody was following me.": "Thật tốt vì cậu đã tìm thấy tôi ngay lúc đó. Khá chắc chắn rằng đang có ai đó theo dõi tôi.",
  "I'd get better a lot quicker if we just had a damned infirmary.": "Tôi sẽ bình phục nhanh hơn rất nhiều nếu như chúng ta có một cái bệnh xá (infirmary) chết tiệt.",
  "They're all dead, so who cares?": "Tất cả bọn họ đều đã chết sạch rồi, nên ai thèm quan tâm cơ chứ?",
  "We've got some more rounds of 9mm ammunition.": "Chúng ta vừa có thêm vài băng đạn dược 9mm.",
  "These are not the kind of skills you acquire by amateur experimentation, and good luck finding an accredited university out there.": "Đây đéo phải là loại kỹ năng (skills) mà cậu có thể tự trang bị được thông qua những cuộc thử nghiệm nghiệp dư (amateur experimentation) đâu, và chúc may mắn tìm được một trường đại học được kiểm định ở ngoài kia đấy.",
  "This place is great! I'm gonna put the pool table here, the home theater over there, and the bar right over there!": "Nơi này thật tuyệt vời! Tôi sẽ đặt bàn bi-a (pool table) ở đây, rạp hát tại gia (home theater) ở đằng kia, và quầy bar ngay đằng kia!",
  "No sign of %1$s. Sounds like things got pretty hairy out there. - %2$s": "Đéo thấy bóng dáng của %1$s đâu cả. Nghe có vẻ như mọi chuyện đã trở nên khá là căng thẳng rùng rợn (hairy) ở ngoài đó rồi. - %2$s",
  "Maybe it's just me, listeners, but when I call for help, I do not want a bunch of jack-booted thugs to bust down my door and get me killed!": "Thưa các thính giả, có thể đó chỉ là do tôi nghĩ vậy thôi, nhưng khi tôi gọi điện cầu cứu, tôi đéo hề muốn một đám côn đồ lưu manh mang giày ống đến phá cửa nhà tôi và giết chết tôi đâu!",
  "Avoids Violence": "Né Tránh Bạo Lực (Violence)",
  "Suck it!": "Cút đi!",
  "Zombie Kill Score (Weekly)": "Điểm Tiêu Diệt Zombie (Hàng Tuần)",
  "\"Dodge this?\" Don't mind if I do!": "\"Né cái này đi á?\" Xin cứ tự nhiên, tôi đéo ngại đâu!",
  "We've secured the LZ, for now. But we've had reports that the zombies are coming out of the city in waves. It won't be long before the pressure builds again, and they attack. We need to fortify this position.": "Chúng ta đã bảo đảm an toàn cho bãi đáp LZ, tạm thời là vậy. Nhưng chúng tôi đã nhận được báo cáo rằng bọn zombies đang kéo ra khỏi thành phố theo từng đợt (waves). Sẽ đéo mất bao lâu nữa trước khi áp lực lại tăng lên, và bọn chúng sẽ tấn công. Chúng ta cần phải củng cố vị trí này ngay.",
  "Vehicle Delivered!": "ĐÃ GIAO XE CỘ (Vehicle)!",
  "I'll come along and help.": "Tôi sẽ đi cùng và giúp một tay.",
  "What are you doing here? You have to get out of here!": "Cậu đang làm gì ở đây vậy? Cậu phải thoát khỏi chỗ này ngay!",
  "Any questions, you come see me first.": "Có bất kỳ câu hỏi nào, cô cứ đến gặp tôi trước.",
  "Pie": "Bánh Nướng (Pie)",
  "The fuck's his problem?": "Hắn ta đang có vấn đề đéo gì vậy?",
  "Hey ... I have some supplies here.": "Này ... Tôi có mang theo một ít đồ tiếp tế (supplies) ở đây.",
  "SET UP: Church Kitchen": "THIẾT LẬP: Nhà Bếp Của Nhà Thờ",
  "67 GENERIC Ben Hanscomb": "67 CHUNG (GENERIC) Ben Hanscomb",
  "Rucks in Trucks": "Những chiếc Ba lô (Rucks) chất trên Xe tải",
  "Allows the preparation of feasts. (Need someone who really knows how to cook, though.)": "Cho phép chuẩn bị những bữa tiệc thịnh soạn (feasts). (Mặc dù vậy, vẫn cần một người thực sự biết nấu ăn.)",
  "Well, I haven't seen any crazies with guns. So I figure whoever's up there shooting must be normal. And in trouble.": "Chà, tôi vẫn chưa nhìn thấy bất kỳ kẻ điên nào mang theo súng cả. Vậy nên tôi cho rằng bất cứ ai đang ở trên đó xả súng thì đều phải là người bình thường. Và đang gặp rắc rối.",
  "We got this.": "Chúng ta xử lý được vụ này mà.",
  "Greed Is Good": "Lòng Tham Cũng Rất Tốt",
  "Postive emotions increase Stamina.": "Cảm xúc tích cực giúp tăng cường Thể Lực (Stamina).",
  "Common ground.": "Tiếng nói chung.",
  "Posit one one tango mike papa two five delta zero five sierra. [message end tone]": "Posit một một tango mike papa hai năm delta không năm sierra. [âm thanh báo hiệu kết thúc tin nhắn]",
  "Mario": "Mario",
  "Drying Racks": "Giá Phơi Khô (Drying Racks)",
  "Shayla": "Shayla",
  "Gonna need more painkillers.": "Sẽ cần thêm thuốc giảm đau (painkillers) đấy.",
  "Ahh look, you rolled out the red carpet for us.": "Ahh nhìn kìa, cậu đã trải thảm đỏ chào đón chúng tôi cơ đấy.",
  "Hey, who's interested in a little hunting practice?": "Này, có ai hứng thú với việc thực hành săn bắn một chút đéo?",
  "If I'm going to keep doing this, I'm going to need more ammo.": "Nếu tôi vẫn còn định tiếp tục làm việc này, tôi sẽ cần thêm đạn dược đấy.",
  "The Human Future Fund is an NGO that funnels money into a variety of sketchy research projects around the globe. Michele Martin is the local manager who would have had contact with Dr. Horn. We need to find out what she knew about his work.": "Quỹ Tương Lai Con Người (Human Future Fund) là một tổ chức phi chính phủ chuyên rót tiền tài trợ cho một loạt các dự án nghiên cứu mờ ám (sketchy) trên toàn cầu. Michele Martin là vị quản lý tại địa phương, người có khả năng đã từng liên hệ với Tiến sĩ Horn. Chúng ta cần tìm hiểu xem bà ta đã biết được những gì về công việc của ông ấy.",
  "Give Alan some space": "Hãy dành cho Alan một chút không gian riêng tư",
  "That's all for this place.": "Thế là hết đồ ở chỗ này rồi.",
  "We'll contribute to the group--no freeloaders here.": "Chúng tôi sẽ đóng góp cho nhóm--đéo có kẻ ăn bám (freeloaders) nào ở đây đâu.",
  "Corporal! Get these samples ready for transport back to base.": "Hạ sĩ! Hãy chuẩn bị sẵn sàng những mẫu vật này để vận chuyển về căn cứ.",
  "Revolver: Diplomat": "Súng Lục Ổ Quay (Revolver): Diplomat",
  "Looking for targets": "Đang tìm kiếm các mục tiêu",
  "Come on, you limp-dicked sons of hippies! Open this goddamn gate!": "Thôi nào, mấy thằng nhãi ranh ẻo lả nhu nhược! Mở cái cổng khốn kiếp này ra ngay!",
  "Our scouts spotted one of those rotted bastards wandering around. We need to take it out. Preferably from a long way off.": "Đội trinh sát (scouts) của chúng ta đã phát hiện ra một trong những tên khốn mục nát đó đang đi lang thang quanh đây. Chúng ta cần phải tiêu diệt nó. Tốt nhất là bắn tỉa từ đằng xa.",
  "-80% Max Stamina": "Giảm -80% Thể Lực Tối Đa (Max Stamina)",
  "Somebody back me up!": "Ai đó yểm trợ cho tôi với!",
  "Trade Opportunity (Food)": "Cơ Hội Giao Thương Mua Bán (Thức Ăn - Food)",
  "Stamina will gradually recover while resting at home. It should take about 1 hour to get back to full Stamina.": "Thể lực (Stamina) sẽ dần dần phục hồi trong khi nghỉ ngơi ở nhà. Sẽ mất khoảng 1 giờ đồng hồ để hồi phục lại mức Thể Lực tối đa.",
  "I don't know of any other supply operations in your area, so as far as I'm concerned, that crate is yours.": "Tôi đéo biết về bất kỳ hoạt động tiếp tế (supply operations) nào khác trong khu vực của cậu cả, vì vậy theo như tôi được biết, cái thùng tiếp tế đó là của cậu đấy.",
  "Kristina": "Kristina",
  "Reciprocating Saw": "Máy Cưa Kiếm (Reciprocating Saw)",
  "5 seconds": "5 giây (seconds)",
  "Missed that one.": "Bắn trượt phát đó rồi.",
  "I'd better let everyone know it's time to go.": "Tốt hơn là tôi nên báo cho mọi người biết đã đến lúc phải rời đi rồi.",
  "Stand still when you shoot!": "Đứng yên khi cậu đang bắn súng đi!",
  "Home on the Grange": "Ngôi Nhà Ở Nông Trại Grange",
  "Take": "Lấy đi (Take)",
  "Deliver Timothy Hall to Base": "Đưa Timothy Hall Trở Về Căn Cứ",
  "I think my number's just about up.": "Tôi nghĩ số mệnh của tôi đã đến lúc tận rồi.",
  "Swift": "Swift",
  "%2$s is my best buddy, though we sometimes have punch-ups. - %1$s": "%2$s là người bạn thân thiết nhất của tôi, mặc dù đôi khi chúng tôi có hơi xung đột đánh nhau một chút. - %1$s",
  "Rapid Reload": "Nạp Đạn Nhanh (Rapid Reload)"
};

const file = 'output/languages/chunks/btxt_chunk_181.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_181.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk181[r.sourceText]) {
    r.translatedText = chunk181[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 181 successfully!');
