const fs = require('fs');
const chunk187 = {
  "I'm ready, and I'm excited!": "Tôi đã sẵn sàng rồi, và tôi đang cảm thấy rất phấn khích!",
  "Some of us still fighting back here, y'know?!": "Vài người trong số chúng tôi vẫn còn đang chiến đấu ở lại đây đấy, cậu có biết đéo?!",
  "Erica": "Erica",
  "Ma'am, Doctor Horn is dead.": "Thưa bà, Bác sĩ Horn đã chết cmnr.",
  "The AN-M14 TH3 chemical incendiary. Pretty sure this one could melt through a truck engine.": "Hỗn hợp hóa chất gây cháy AN-M14 TH3. Khá chắc chắn rằng loại vũ khí này có thể làm tan chảy được cả một khối động cơ xe tải.",
  "Works out constantly; obsessed with getting huge. (Powerhouse, Bonus Stamina)": "Tập luyện thể hình liên tục; bị ám ảnh với việc sở hữu một thân hình to lớn. (Kỹ Năng Nền Tảng Powerhouse, Thưởng Thêm Thể Lực Bonus Stamina)",
  "Designed for police and military uses.": "Được thiết kế chuyên dụng dành cho các lực lượng cảnh sát và quân đội.",
  "Heads up, big zed incoming.": "Chú ý nào, có một con zed cỡ lớn đang tiến đến.",
  "Backstedt": "Backstedt",
  "Rock Climber": "Người Leo Núi (Rock Climber)",
  "Please go inside, and just ... don't do anything until the helicopter arrives.": "Làm ơn hãy đi vào bên trong, và chỉ cần ... đéo làm bất cứ điều gì cho đến khi máy bay trực thăng đến nơi.",
  "And the delivery guy never once tried to eat my face.": "Và cái gã giao hàng đó chưa từng một lần nào cố gắng ăn tươi nuốt sống khuôn mặt của tôi cả.",
  "This location is OCCUPIED by someone else.": "Địa điểm này ĐANG BỊ CHIẾM ĐÓNG (OCCUPIED) bởi một người khác.",
  "Played matchmaker for Quentin and Becca.": "Đã đóng vai trò người mai mối ghép đôi cho Quentin và Becca.",
  "My mama always said these things were the Devil's right hand.": "Mẹ tôi luôn nói rằng những thứ này chính là cánh tay phải đắc lực của Ác Quỷ.",
  "Apollo angels forty, ten mikes.": "Apollo angels forty, mười phút (ten mikes) nữa đến nơi.",
  "34 GENERIC Danica Coleman": "34 CHUNG (GENERIC) Danica Coleman",
  "Seeya around, okay?": "Gặp lại sau nhé (Seeya around), okay?",
  "Liked to Knit": "Từng Rất Thích Đan Len (Knit)",
  "Man, it's just not fair!": "Trời ạ, như vậy thật là đéo công bằng chút nào!",
  "COMMUNITY: Bonding": "CỘNG ĐỒNG (COMMUNITY): Gắn Kết Tình Cảm (Bonding)",
  "On": "Bật (On)",
  "Then the power died. No one ever sounded the all-clear.": "Rồi mạng lưới điện (power) bị mất. Chưa từng có ai phát ra thông báo an toàn (all-clear) cả.",
  "Zeds on our left.": "Bọn Zeds đang ở bên trái chúng ta.",
  "Good progress!": "Tiến độ rất tốt đấy!",
  "Whoa, easy... just trying to help.": "Whoa, bình tĩnh nào... chỉ đang cố gắng giúp đỡ thôi mà.",
  "Model 1100 for police and military use. INCENDIARY.": "Phiên bản Model 1100 chuyên dụng dành cho cảnh sát và quân đội. CÓ KHẢ NĂNG GÂY CHÁY (INCENDIARY).",
  "What the hell makes Lily so special, anyways? Don't ever see her risking her ass out there. -%1$s": "Rốt cuộc thì cái đéo gì đã khiến cho Lily trở nên quá đặc biệt vậy? Đéo bao giờ thấy cô ta dám liều cái mạng chó của mình ra ngoài kia cả. -%1$s",
  "Don't just stand there!": "Đừng có chỉ đứng trơ ra ở đó nữa!",
  "God works in mysterious ways.": "Chúa luôn hành động theo những cách vô cùng bí ẩn.",
  "Highroad Actual to Black Friday. The pilot tells me he's delivering another of your packages.": "Highroad Actual gọi Black Friday. Phi công vừa mới báo cáo với tôi là anh ta đang đi giao một kiện hàng (packages) khác của các anh.",
  "There's only so much I can do without fresh ingredients. (Great cook.)": "Tôi chỉ có thể làm được một vài món ăn nếu như đéo có các nguyên liệu tươi sống (fresh ingredients). (Là một người Đầu Bếp Tuyệt Vời Great cook.)",
  "You gonna be okay?": "Cậu sẽ ổn chứ?",
  "JOURNAL: Local Color": "NHẬT KÝ (JOURNAL): Bản Sắc Địa Phương (Local Color)",
  "Everybody gets matching tattoos to show community solidarity. (Increases Trust and Morale)": "Tất cả mọi người đều xăm những hình xăm giống nhau để thể hiện tinh thần đoàn kết trong cộng đồng. (Giúp gia tăng Độ Tin Cậy Trust và Tinh Thần Morale)",
  "Olivia": "Olivia",
  "Search this Location": "Tìm Kiếm Xung Quanh Địa Điểm Này",
  "Allows the creation of explosives, in addition to basic vehicle repairs.": "Cho phép chế tạo các loại vật liệu nổ (explosives), bên cạnh đó còn có khả năng sửa chữa xe cộ (vehicle repairs) cơ bản.",
  "Dear Anne": "Gửi Anne Thân Mến",
  "Cover me while I nail up some more boards!": "Hãy yểm trợ cho tôi trong khi tôi đóng thêm vài tấm ván gỗ này lên nào!",
  "Doesn't anybody bother to ask?": "Đéo có ai bận tâm đến việc hỏi han sao?",
  "Another day, another round of foraging. - %1$s": "Lại một ngày khác trôi qua, lại bắt đầu một vòng đi thu thập (foraging) đồ tiếp tế khác. - %1$s",
  "C'mon, you've met the Wilkersons. Do you really think they'd be okay with their little brother's boyfriend showing up to pay his respects? Yeah, I didn't think so.": "Thôi nào, cậu đã từng gặp gỡ với anh em nhà Wilkerson rồi mà. Cậu có thực sự nghĩ rằng bọn họ sẽ hoàn toàn thoải mái với việc bạn trai của cậu em út của họ xuất hiện để bày tỏ lòng thành kính hay đéo? Đúng vậy, tôi cũng đéo nghĩ như vậy đâu.",
  "Hernandez": "Hernandez",
  "Man, we are so screwed!": "Trời ạ, chúng ta tiêu tùng cmnr!",
  "Better get ready for company.": "Tốt hơn hết là nên chuẩn bị sẵn sàng để đón tiếp những vị khách đi.",
  "Tucker": "Tucker",
  "Here. Don't say I never did nothin' for you.": "Cầm lấy đi. Đừng có nói là tôi đéo bao giờ làm bất cứ điều gì cho cậu đấy nhé.",
  "You hardly rescued me once.": "Lúc nãy cậu suýt chút nữa là đéo thể giải cứu được cho tôi đấy nhé.",
  "Regroup at the Warehouse": "Tập Hợp Lại Tại Nhà Kho (Warehouse)",
  "We've gotten word that another group of survivors wants to trade some of their Ammunition for some of our Food. -%2$s": "Chúng ta vừa nhận được tin tức rằng có một nhóm người sống sót khác đang muốn dùng Đạn Dược (Ammunition) của bọn họ để trao đổi lấy một ít Thức Ăn (Food) của chúng ta. -%2$s",
  "Hey, I found some supplies here.": "Này, tôi đã tìm thấy một số đồ tiếp tế (supplies) ở đây.",
  "I'm looking for somebody.": "Tôi đang đi tìm kiếm một người.",
  "Guess it's time I headed home.": "Tôi đoán đã đến lúc tôi phải quay trở về nhà cmnr.",
  "Look, I appreciate what you're doing here, Your Honor, but-": "Nghe này, tôi rất trân trọng những gì ông đang làm ở đây, Thưa Ngài Thẩm Phán (Your Honor), nhưng-",
  "Gives us access to intel and direction from HQ.": "Cấp quyền cho chúng ta truy cập vào các thông tin tình báo (intel) và hướng dẫn từ Trụ Sở Chính (HQ).",
  "The cupboard's looking a little bare. Might want to keep an eye out for some food.": "Tủ đựng đồ trông có vẻ hơi trống rỗng (bare) rồi đấy. Có lẽ chúng ta sẽ muốn để mắt tìm kiếm thêm một số lượng thức ăn (food) đấy.",
  "Plumbing Pipe": "Ống Nước (Plumbing Pipe)",
  "You got that? They should be on your map.": "Cậu đã hiểu rõ rồi chứ? Vị trí của bọn họ đáng lẽ ra phải nằm ở trên bản đồ của cậu.",
  "You may want to keep an eye out for survivors.": "Bạn có thể sẽ muốn để mắt đến việc tìm kiếm những người còn sống sót (survivors) đấy.",
  "I don't think anybody here knows how to treat that.": "Tôi đéo nghĩ là có bất kỳ ai ở đây biết cách chữa trị thứ đó đâu.",
  "West": "Khu Vực Phía Tây (West)",
  "Safe is a relative term.": "An toàn (Safe) chỉ là một khái niệm mang tính chất tương đối mà thôi.",
  "Need Food": "Đang Cần Thức Ăn (Food)",
  "Build a STORAGE AREA to increase your STOCKPILE MAXIMUMS.": "Hãy xây dựng một KHU VỰC LƯU TRỮ (STORAGE AREA) để gia tăng SỐ LƯỢNG KHO DỰ TRỮ TỐI ĐA (STOCKPILE MAXIMUMS) của bạn.",
  "LOG: Missing Sasquatch": "NHẬT KÝ (LOG): Sasquatch Bị Mất Tích",
  "Hadley Westen is the reason the world needs soldiers. On his own, he wouldn't last a week.": "Sự tồn tại của Hadley Westen chính là lý do để giải thích cho việc tại sao thế giới này lại cần đến những người lính (soldiers). Nếu chỉ dựa vào sức lực của bản thân mình, anh ta sẽ đéo thể nào sống sót qua nổi một tuần.",
  "Talwar": "Kiếm Talwar",
  "Oh, my God. Oh my God.": "Oh, lạy Chúa tôi. Oh lạy Chúa tôi.",
  "Ghost town.": "Một thị trấn ma (Ghost town).",
  "SURVIVAL TACTICS: Juggernaut": "CHIẾN THUẬT SINH TỒN (TACTICS): Quái Vật Juggernaut",
  "Out on a supply run.": "Đang ra ngoài để thực hiện chuyến chạy thu thập tiếp tế (supply run).",
  "Zombie Kill Points (All Time)": "Số Điểm Tiêu Diệt Zombie (Mọi Lúc)",
  "The Wilkersons are bad news.": "Gia đình nhà Wilkerson chính là những kẻ tồi tệ luôn mang đến những rắc rối tồi tệ (bad news) đấy.",
  "Here. Next time bring more.": "Đây. Lần tới hãy mang đến nhiều hơn nhé.",
  "They're coming in through the back!": "Bọn chúng đang tiến vào từ phía sau kìa!",
  "It's funny what people think to take in the early days of a crisis.": "Thật nực cười khi nhìn thấy những thứ mà mọi người đã nghĩ đến việc phải mang theo trong những ngày đầu tiên của một cuộc khủng hoảng (crisis).",
  "I got nothing left.": "Tôi đéo còn lại thứ gì cả.",
  "Woah, what? No, no. You've got to be kidding me!": "Woah, cái đéo gì cơ? Đéo, đéo. Cậu đang đùa với tôi đấy à!",
  "Anyone who is GRAVELY ILL is in danger of dying instead of recovering.": "Bất kỳ người nào đang bị BỆNH NẶNG (GRAVELY ILL) sẽ có nguy cơ bị tử vong thay vì có thể phục hồi lại được.",
  "Well, isn't that cute? You brought friends.": "Chà, như vậy đéo phải là rất dễ thương sao? Cậu còn dẫn theo những người bạn của mình đến đây nữa à.",
  "Time for me to fall back.": "Đã đến lúc tôi phải rút lui về phía sau (fall back) cmnr.",
  "So, how is he?": "Vậy, anh ta cảm thấy thế nào rồi?",
  "This is a matter for the police, and they will deal with it.": "Chuyện này là vấn đề của bên cảnh sát (police), và bọn họ sẽ giải quyết nó.",
  "This fever... I know what it means. Just don't have the guts to do it myself.": "Cơn sốt này (fever)... Tôi biết nó có ý nghĩa gì. Chỉ là tôi đéo có đủ can đảm để có thể tự tay làm chuyện đó.",
  "Created 3 Snacks": "Đã chế tạo thành công 3 phần Đồ Ăn Vặt (Snacks)",
  "Running Out of Time": "Đang Sắp Cạn Kiệt Thời Gian (Running Out of Time)",
  "Still a few things to gather up here.": "Vẫn còn một vài thứ có thể thu thập được ở đây đấy.",
  "I've been here for a day and a half, with no food, no water, and no break from the zombies.": "Tôi đã bị mắc kẹt ở đây suốt một ngày rưỡi, đéo có một chút thức ăn nào, đéo có lấy một giọt nước, và cũng đéo có thời gian để nghỉ ngơi khỏi bọn zombies khốn kiếp.",
  "Shit, it's a big one. I'm seeing more than just screamers.": "Chết tiệt, đó là một con quái vật to lớn đấy. Tôi đang nhìn thấy nhiều thứ kinh khủng hơn chứ đéo chỉ có mỗi đám screamers đâu.",
  "Shane": "Shane",
  "Hypes": "Hypes",
  "Modern sporty sedan with patriotic flair. Four seats.": "Dòng xe sedan thể thao (sporty sedan) kiểu dáng hiện đại mang đậm phong cách yêu nước. Có bốn chỗ ngồi.",
  "Once you reach 100% TRUST you can become FRIENDS.": "Một khi bạn đạt được 100% ĐỘ TIN CẬY (TRUST), bạn có thể trở thành BẠN BÈ (FRIENDS) của bọn họ.",
  "Collecting cars appear to be one of Santos' big interests. If we stay on his good side, it looks like he can provide working vehicles for us. - %1$s": "Việc sưu tầm xe hơi có vẻ như là một trong những sở thích lớn nhất của Santos. Nếu như chúng ta tiếp tục giữ vững mối quan hệ tốt đẹp với hắn ta (stay on his good side), có vẻ như hắn sẽ có khả năng cung cấp những phương tiện di chuyển (vehicles) hoạt động tốt cho chúng ta. - %1$s",
  "Shit! It's one of those big bastards!": "Chết tiệt! Đó là một trong số những tên khốn to xác đó!",
  "Leandra": "Leandra",
  "Help me!": "Cứu tôi với!",
  "107 STORY Mercenary": "107 CỐT TRUYỆN Lính Đánh Thuê (Mercenary)",
  "If I was gonna shoot you, you'd be dead already.": "Nếu tôi mà định bắn cậu, thì cậu đã chết từ lâu cmnr."
};

const file = 'output/languages/chunks/btxt_chunk_187.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_187.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk187[r.sourceText]) {
    r.translatedText = chunk187[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 187 successfully!');
