const fs = require('fs');
const chunk132 = {
  "Great. No keys. Guess we're walking after all.": "Tuyệt. Đéo có chìa khóa. Tôi đoán rốt cuộc thì chúng ta vẫn phải đi bộ rồi.",
  "Colby": "Colby",
  "I'm not saying there's nothing to worry about, but there's no need to panic. We're doing pretty well, all things considered.": "Tôi đéo nói là đéo có gì phải lo, nhưng cũng đéo cần phải hoảng sợ. Xét cho cùng thì chúng ta đang làm khá tốt đấy chứ.",
  "Up ahead.": "Ở ngay phía trước.",
  "We're running low on food here. If anyone has any leads on unspoiled food stores, well, we'd really appreciate it.": "Chúng tôi đang cạn kiệt thức ăn ở đây. Nếu ai có manh mối nào về các cửa hàng thực phẩm chưa bị hỏng, thì chà, chúng tôi sẽ rất biết ơn đấy.",
  "You think it's an evac route?": "Cậu nghĩ đó là tuyến đường sơ tán sao?",
  "Dude, that was too close, too close!": "Anh bạn, chuyện đó suýt soát quá, quá suýt soát rồi đấy!",
  "Looks like we found the party!": "Có vẻ như chúng ta đã tìm thấy bữa tiệc rồi!",
  "-40% Max Vitality": "-40% Sinh lực tối đa",
  "Glutton": "Kẻ Phàm Ăn (Glutton)",
  "You ready to head out? I ain't waiting here forever.": "Cậu đã sẵn sàng lên đường chưa? Tôi đéo đợi ở đây mãi được đâu.",
  "Found some weapons.": "Tìm thấy một vài vũ khí.",
  "Scratch one infestation off the map.": "Gạch tên một ổ dịch khỏi bản đồ.",
  "I can carry the goods and make the exchange, but it'd be nice to have some backup.": "Tôi có thể mang hàng và thực hiện trao đổi, nhưng sẽ thật tốt nếu có người bọc hậu.",
  "Feral Sighted": "Đã Nhìn Thấy Feral",
  "Exit Game": "Thoát Game",
  "We've got problems at one of our outposts.": "Chúng ta đang gặp rắc rối ở một trong các tiền đồn của mình.",
  "We've got some more rounds of 7.62mm ammunition.": "Chúng ta có thêm một ít đạn 7.62mm.",
  "Come on then, you think you're hard enough!": "Ngon thì nhào vô, mày nghĩ mày đủ cứng sao!",
  "Beer Pong": "Bóng Bàn Bia (Beer Pong)",
  "Heavy, sturdy and all business.": "Nặng, chắc chắn và cực kỳ chuyên nghiệp.",
  "86 GENERIC Marcia Granderson": "86 GENERIC Marcia Granderson",
  "Let's hope she knows the science": "Hy vọng là cô ấy am hiểu về khoa học",
  "That's nothing. I caught him earlier, staring at a pistol like it was his long-lost best friend.": "Chưa là gì đâu. Lúc nãy tôi còn thấy anh ta nhìn chằm chằm vào một khẩu súng lục cứ như thể đó là người bạn thân thất lạc lâu năm của anh ta vậy.",
  "Hey, I appreciate the help. I know it's not easy.": "Này, tôi rất biết ơn sự giúp đỡ của cậu. Tôi biết chuyện này đéo hề dễ dàng.",
  "Too Many Hordes": "Quá Nhiều Bầy Horde",
  "We really don't.": "Chúng tôi thực sự đéo.",
  "Whiplash": "Hội chứng whiplash (Chấn thương cổ)",
  "Still can't wrap her head around what's going on.": "Vẫn đéo thể hiểu nổi chuyện chó đẻ gì đang xảy ra.",
  "This one's tough.": "Tên này khó nhằn đấy.",
  "I'm kinda messed up, Doc. What should I do?": "Tôi đang thấy khá là rối bời, Bác sĩ. Tôi nên làm gì đây?",
  "Shoot them in the head. Body shots will never kill them.": "Bắn vào đầu bọn chúng. Bắn vào người sẽ đéo bao giờ giết được chúng đâu.",
  "And that, my friends, is how we do that!": "Và đó, các bạn của tôi, là cách chúng ta giải quyết việc đó!",
  "Beats the hell out of me. They just showed up, dragged us out onto the street, and sent in those guys in hazmat suits.": "Có đánh chết tôi cũng đéo biết. Họ cứ thế xuất hiện, lôi chúng tôi ra đường, và cử những gã mặc đồ bảo hộ (hazmat) đó vào.",
  "Yes, ma'am.": "Vâng, thưa bà.",
  "Some dipshit gets lost, and we bail 'em out. Same old, same old.": "Vài tên khốn ngu ngốc đi lạc, và chúng ta phải đi cứu bọn chúng. Vẫn là cái bài cũ rích thôi.",
  "His faith has not wavered.": "Đức tin của anh ấy chưa bao giờ lung lay.",
  "Shit. I miss my old place.": "Chết tiệt. Tôi nhớ chỗ ở cũ của mình quá.",
  "That ought to be tall enough for a look around.": "Chỗ đó chắc đủ cao để nhìn quanh một vòng đấy.",
  "Yeah, damn right never mind. We're done, that's the final word.": "Phải, mẹ kiếp, quên đi. Chúng ta xong rồi, đó là lời cuối cùng.",
  "Hope nobody was planning on making firebombs any time soon.": "Hy vọng đéo có ai đang lên kế hoạch chế tạo bom lửa trong thời gian tới.",
  "It's a car. Wait, is that for me?": "Là một chiếc xe hơi. Khoan đã, nó dành cho tôi sao?",
  "Weathers": "Weathers",
  "Sales": "Bán hàng",
  "I'm outta here.": "Tôi chuồn khỏi đây đây.",
  "Damn. We were doing pretty well there up until the end.": "Mẹ kiếp. Chúng ta đã làm khá tốt ở đó cho đến tận phút cuối.",
  "Fortify the Farmhouse": "Gia Cố Nông Trại",
  "41 GENERIC Terrence Halverson": "41 GENERIC Terrence Halverson",
  "So when the helo drops you off at the capital, just try to lay low. We didn't exactly get permission to extract you.": "Vì vậy, khi trực thăng thả cậu xuống thủ đô, hãy cố gắng nằm vùng đi. Chúng tôi đéo thực sự được phép sơ tán cậu đâu.",
  "We don't have anybody free to make a run right now.": "Hiện tại chúng ta đéo có ai rảnh để thực hiện một chuyến chạy đi nhặt đồ (run) cả.",
  "Phosphorus": "Phốt pho",
  "I gotta get out of here!": "Tôi phải rời khỏi đây thôi!",
  "Good to see we're still finding useful stuff.": "Thật tốt khi thấy chúng ta vẫn đang tìm được những thứ hữu ích.",
  "Cassavettes": "Cassavettes",
  "%d Hordes Destroyed": "%d Bầy Horde Đã Bị Tiêu Diệt",
  "Fuel Drop": "Tiếp Tế Nhiên Liệu",
  "You know, don’t get me wrong, this place is really nice … but with all the zombies out there, I’m worried we might not be able to hold out here forever.": "Cậu biết đấy, đừng hiểu lầm tôi, nơi này thực sự rất tuyệt... nhưng với vô số zombie ngoài kia, tôi e rằng chúng ta đéo thể bám trụ ở đây mãi được.",
  "Increase protected range around the outpost.": "Tăng phạm vi bảo vệ xung quanh tiền đồn.",
  "What happened?": "Chuyện gì đã xảy ra vậy?",
  "Yeah, over here.": "Phải, ở đây này.",
  "We might have to start saving brass soon.": "Có lẽ chúng ta phải bắt đầu tiết kiệm vỏ đạn đồng (brass) sớm thôi.",
  "Shit, bulletproof zombies!": "Chết tiệt, zombie chống đạn!",
  "Clubbing zombies on the head is a surefire way to improve your Blunt Weapon Specialization.": "Nện vào đầu lũ zombie là một cách chắc chắn để cải thiện Chuyên Môn Vũ Khí Cùn của bạn.",
  "Stewart": "Stewart",
  "Heavy Weapon Specialization Improved!": "Chuyên Môn Vũ Khí Hạng Nặng Đã Cải Thiện!",
  "Elizabeth": "Elizabeth",
  "This gun can't take a suppressor.": "Khẩu súng này đéo thể lắp ống giảm thanh.",
  "Requires ART GALLERIES.": "Yêu cầu PHÒNG TRANH (ART GALLERIES).",
  "What? Never heard of comfort food? Don't you judge me. - %1$s": "Cái gì? Chưa từng nghe đến 'comfort food' (món ăn xoa dịu tinh thần) bao giờ sao? Đừng có mà phán xét tôi. - %1$s",
  "140 NPC Mercenary": "140 NPC Mercenary",
  "Damn, thanks for the save!": "Mẹ kiếp, cảm ơn vì đã cứu tôi!",
  "We're looking for a guy with long arms and legs, no eyes, and a weird color to the skin ...": "Chúng tôi đang tìm kiếm một gã với tay chân dài ngoằng, đéo có mắt, và màu da thì kỳ dị...",
  "I honestly don't think there's anybody left that's not hurt. Before long we're all gonna be screwed.": "Thành thật mà nói, tôi đéo nghĩ còn ai lành lặn cả. Chẳng bao lâu nữa tất cả chúng ta sẽ tiêu đời mất thôi.",
  "Now, how can I slack off when folks are pitching in like that?": "Giờ thì, làm sao tôi có thể lười biếng khi mọi người đều đang dốc sức như thế chứ?",
  "This is all we could find up on the ridge. No survivors, though.": "Đây là tất cả những gì chúng tôi có thể tìm thấy trên sườn núi. Dù vậy, đéo có ai sống sót.",
  "Fresh batch just came out of the barrels. You interested?": "Mẻ mới tinh vừa ra khỏi thùng. Cậu có hứng thú không?",
  "These days just about every place has security cameras, and a lot of those systems have battery backups in case the power fails.": "Thời buổi này, hầu như mọi nơi đều có camera an ninh, và rất nhiều hệ thống trong số đó có pin dự phòng phòng trường hợp mất điện.",
  "God, will somebody shut that thing up?": "Chúa ơi, ai đó làm ơn bắt cái thứ đó im đi có được đéo?",
  "Empty.": "Trống không.",
  "I know you're busy, but there are some things that could use your attention.": "Tôi biết cậu đang bận, nhưng có vài thứ cần cậu chú ý tới đấy.",
  "HOME: Bonding": "CĂN CỨ: Gắn Kết",
  "Yount": "Yount",
  "I've already done the calculations and I believe I will be the victor.": "Tôi đã tính toán xong xuôi rồi và tôi tin rằng mình sẽ là người chiến thắng.",
  "New Friend": "Bạn Mới",
  "So far, we've picked up only one other set of messages, from a small town further up the highway.": "Cho đến nay, chúng tôi chỉ bắt được một bộ tin nhắn khác, từ một thị trấn nhỏ xa hơn trên đường cao tốc.",
  "Fodor": "Fodor",
  "Find Sheriff Carl Parsons.": "Tìm Cảnh Sát Trưởng Carl Parsons.",
  "Local charity worker and activist.": "Nhân viên từ thiện và nhà hoạt động địa phương.",
  "Infestation? Meet 'scorched earth,' motherfuckers.": "Ổ dịch à? Nếm mùi 'tiêu thổ' (thiêu rụi mọi thứ) đi, những thằng khốn nạn.",
  "Stamina penalty.": "Hình phạt về Thể Lực.",
  "Exercise Area": "Khu Vực Tập Thể Dục",
  "You stay the fuck away from %1$s, %2$s. Next time it won't just be an argument.": "Mày tránh xa khỏi %1$s ra, %2$s. Lần tới đéo chỉ là một cuộc cãi vã đâu.",
  "Need something?": "Cần gì sao?",
  "He was unconscious for most of it. Only woke up a couple of times.": "Ông ấy đã bất tỉnh phần lớn thời gian. Chỉ tỉnh dậy được vài lần.",
  "Come on, no sense in dilly-dallying.": "Đi nào, dây dưa mãi cũng đéo ích gì đâu.",
  "So, what was that with you and Lily?": "Vậy, chuyện giữa cậu và Lily là sao?",
  "Okay, we really need to do something about all these infestations. The more infestations out there, the greater the danger. - %1$s": "Được rồi, chúng ta thực sự cần phải làm gì đó với tất cả các ổ dịch này. Càng có nhiều ổ dịch ngoài kia, mối nguy hiểm càng lớn. - %1$s",
  "I ever tell you I was one of those people in the cold open of a cop show?": "Tôi đã từng nói với cậu rằng tôi là một trong những người xuất hiện ở phân cảnh mở đầu lạnh gáy của một bộ phim cảnh sát chưa?",
  "Just the usual. Watch for screamers and kill any zombies you see.": "Chỉ là chuyện thường ngày thôi. Cảnh giác với bọn screamer và giết bất kỳ con zombie nào cậu thấy.",
  "Got them.": "Bắt được chúng rồi."
};

const file = 'output/languages/chunks/btxt_chunk_132.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_132.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk132[r.sourceText]) {
    r.translatedText = chunk132[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 132 successfully!');
