const fs = require('fs');
const chunk149 = {
  "Kill 5 Ferals. (Breakdown Level 3 or Higher)": "Tiêu diệt 5 con Feral. (Breakdown Cấp 3 trở lên)",
  "Exporting save game to cloud.": "Đang xuất (export) file save game lên đám mây (cloud).",
  "Sayers": "Sayers",
  "Scavenge and Move Out": "Thu Thập Nhu Yếu Phẩm và Di Chuyển",
  "Just doing our part to keep the streets safe. -%1$s": "Chỉ đang làm tròn bổn phận của chúng tôi để giữ cho đường phố được an toàn. -%1$s",
  "Check the left!": "Kiểm tra cánh trái!",
  "Little bit.": "Một chút thôi.",
  "Sitting around base isn't making the situation any better.": "Ngồi ỳ một chỗ trong căn cứ đéo làm cho tình hình khá hơn chút nào đâu.",
  "Maggie": "Maggie",
  "COMPLETED: Missing Survivor": "HOÀN THÀNH: Người Sống Sót Mất Tích",
  "Requires WAREHOUSE CLUB MEMBERSHIP.": "Yêu cầu THẺ THÀNH VIÊN CÂU LẠC BỘ NHÀ KHO (WAREHOUSE CLUB MEMBERSHIP).",
  "Attention all search teams, you are now on zed patrol until further notice.": "Chú ý tất cả các đội tìm kiếm, các cậu hiện đang làm nhiệm vụ tuần tra zed (zed patrol) cho đến khi có thông báo mới.",
  "Bonus XP for Crushing": "Thưởng XP cho Đòn Đập Nát (Crushing)",
  "I think we're okay.": "Tôi nghĩ chúng ta ổn rồi.",
  "They're saying I gotta kill it with fire this time. Preserve the internal structure of the brain or some shit.": "Họ nói lần này tôi phải giết nó bằng lửa. Để bảo tồn cấu trúc bên trong của bộ não hay cái đéo gì đó.",
  "Lake": "Lake",
  "Set Up Sleeping Area": "Thiết Lập Khu Vực Ngủ Nghỉ",
  "Here, let me do that.": "Đưa đây, để tôi làm chuyện đó cho.",
  "Oh. Okay, yeah, sure. I understand.": "Ồ. Được rồi, vâng, chắc chắn rồi. Tôi hiểu.",
  "A well-trained army engineer. Apparently, that means he is qualified to fill Hescos.": "Một kỹ sư quân đội được đào tạo bài bản. Rõ ràng, điều đó có nghĩa là anh ta đủ trình độ để lấp đầy những thùng Hesco.",
  "I think we just saw it.": "Tôi nghĩ chúng ta vừa mới nhìn thấy nó đấy.",
  "I mean it. We gotta stick together, right? I mean alone I would have been vulnerable but--we need people to watch our backs.": "Tôi nói thật đấy. Chúng ta phải gắn kết với nhau, đúng đéo? Ý tôi là nếu ở một mình tôi sẽ rất dễ bị tổn thương, nhưng--chúng ta cần người để yểm trợ sau lưng.",
  "I need a vehicle here ASAP.": "Tôi cần một chiếc xe ở đây ngay và luôn (ASAP).",
  "We're pretty short on weapons. I think some people are down to broken bottles.": "Chúng ta đang khá thiếu vũ khí. Tôi nghĩ một số người đã phải dùng đến những cái chai vỡ rồi.",
  "Got every imaginable shot while traveling in the Pacific. No disease is going to get by this immune system.": "Đã tiêm mọi loại vắc-xin có thể tưởng tượng được trong lúc đi du lịch ở Thái Bình Dương. Đéo có căn bệnh nào có thể lọt qua được hệ miễn dịch này đâu.",
  "I tried asking %1$s to leave for the good of the community. That didn't go over so well. - %2$s": "Tôi đã thử yêu cầu %1$s rời đi vì lợi ích của cả cộng đồng. Chuyện đó đéo suôn sẻ cho lắm. - %2$s",
  "Indefensible": "Đéo Thể Phòng Thủ Được",
  "More zeds incoming!": "Có thêm lũ zed đang kéo đến!",
  "Look... I'm living on borrowed time as it is. It's not like anyone's still making the meds I need, right?": "Nghe này... Dù sao thì tôi cũng đang sống bằng thời gian vay mượn rồi. Làm đéo gì còn ai đang sản xuất loại thuốc mà tôi cần nữa, đúng đéo?",
  "Delaney": "Delaney",
  "Mckenzie": "Mckenzie",
  "No, ma'am. It's like all of Hawaii went and fell off the map.": "Đéo, thưa cô. Cứ như thể toàn bộ Hawaii đã biến mất khỏi bản đồ vậy.",
  "Get ready to evacuate.": "Hãy chuẩn bị sẵn sàng để sơ tán.",
  "And then the dead started rising from the grave and eating people. Fuck it, I need a drink.": "Và rồi những kẻ đã chết bắt đầu đội mồ sống dậy và ăn thịt người. Mẹ kiếp, tôi cần một ly rượu.",
  "Death toll climbs in Delhi": "Số người chết gia tăng ở Delhi",
  "On our own we won't last, but we'd work hard if you let us join you.": "Nếu chỉ có một mình, chúng tôi sẽ đéo trụ nổi, nhưng chúng tôi sẽ làm việc chăm chỉ nếu các người cho phép chúng tôi gia nhập.",
  "<Sigh> Right. Sorry.": "<Thở dài> Đúng vậy. Xin lỗi nhé.",
  "Horticulture": "Làm Vườn",
  "Tag yourself in, brother!": "Vào việc đi, anh bạn!",
  "Shira": "Shira",
  "Aigner": "Aigner",
  "EXPIRED: Diversion Request": "HẾT HẠN: Yêu Cầu Đánh Lạc Hướng",
  "I encountered a new group of survivors. They're pretty guarded. - %1$s": "Tôi đã chạm mặt một nhóm người sống sót mới. Họ khá là cảnh giác. - %1$s",
  "TIP: The green icons represent mission opportunities.": "MẸO: Các biểu tượng màu xanh lá cây tượng trưng cho những cơ hội nhận nhiệm vụ.",
  "Katelyn": "Katelyn",
  "Isaiah": "Isaiah",
  "Questions Judge Lawton's policies.": "Đặt câu hỏi về các chính sách của Thẩm phán Lawton.",
  "Then how do we get out?": "Vậy thì làm sao để chúng ta thoát ra ngoài?",
  "Good Stockpiles": "Kho Dự Trữ Tốt",
  "I don't give a shit! I ain't never had to pay for it, and I ain't never had to take it that way neither!": "Bố đéo thèm quan tâm! Bố chưa bao giờ phải trả tiền cho nó, và bố cũng đéo bao giờ phải lấy nó theo cách đó cả!",
  "Seriously. Please.": "Nghiêm túc đấy. Làm ơn.",
  "SURVIVAL TACTICS: Materials Storage": "CHIẾN THUẬT SINH TỒN: Lưu trữ Vật liệu",
  "Advise us when you're ready for extraction.": "Báo cho chúng tôi khi ngài đã sẵn sàng để rút lui.",
  "Sounds like clearing out that infestation got pretty hairy. %1$s barely made it out with the team. - %2$s": "Nghe như thể việc dọn dẹp cái ổ dịch (infestation) đó đã trở nên khá nguy hiểm. %1$s và cả đội suýt chút nữa thì đéo thể thoát ra được. - %2$s",
  "When hunting big game, bring enough rifle.": "Khi săn thú lớn, hãy mang theo đủ hỏa lực súng trường.",
  "Goddammit, is it too much to ask for a little trigger discipline around here?": "Mẹ kiếp, đòi hỏi một chút kỷ luật khai hỏa (trigger discipline) ở quanh đây là quá đáng lắm sao?",
  "Business as usual for the Wilkersons. -%1$s": "Vẫn là công việc làm ăn thường ngày đối với nhà Wilkerson. -%1$s",
  "Yeah … I can tell you're impressed.": "Phải … Tôi có thể thấy cậu đang rất ấn tượng.",
  "I can load up any time if you want to get going.": "Tôi có thể chuẩn bị đồ đạc bất cứ lúc nào nếu cậu muốn đi luôn.",
  "Jack could have died out there. I couldn't risk that.": "Jack có thể đã chết ngoài đó rồi. Tôi đéo thể mạo hiểm như vậy được.",
  "I see someplace worth a scavenging run.": "Tôi thấy một nơi rất đáng để thực hiện một chuyến nhặt mót.",
  "You abandon the city when you think we're all going to die ...": "Ngài bỏ rơi thành phố khi ngài nghĩ rằng tất cả chúng tôi đều sẽ phải chết ...",
  "COMPLETED: Ranger Station": "HOÀN THÀNH: Trạm Kiểm Lâm (Ranger Station)",
  "I better move. You get him home safe.": "Tốt hơn là tôi nên di chuyển. Cậu hãy đưa anh ấy về nhà an toàn nhé.",
  "Swing from the hips!": "Đánh vung từ hông nào!",
  "This is Greyhound One. We've fortified our position at the LZ. New outpost uses callsign Black Friday.": "Đây là Greyhound Một (Greyhound One). Chúng tôi đã củng cố vị trí của mình tại Khu vực hạ cánh (LZ). Tiền đồn mới sử dụng tên gọi Black Friday.",
  "Shotgun: TS 15": "Súng Bơm (Shotgun): Súng Bơm TS 15",
  "Hey, don't get me wrong. I mean, the church is great, but we need to consider the long run.": "Này, đừng hiểu sai ý tôi. Ý tôi là, nhà thờ thì tuyệt đấy, nhưng chúng ta cần phải tính đến chặng đường dài phía trước.",
  "+40%": "+40%",
  "Hey, buddy!": "Này, anh bạn!",
  "Okay, let's get started.": "Được rồi, bắt đầu thôi.",
  "STATUS: Impatient": "TRẠNG THÁI: Thiếu kiên nhẫn",
  "I've always felt like I was specially blessed. When I was six, I fell off my daddy's boat.": "Tôi luôn cảm thấy như mình được đặc biệt phù hộ vậy. Hồi sáu tuổi, tôi bị ngã khỏi thuyền của bố.",
  "Please... I'll be fine, just let me go....": "Làm ơn... Tôi sẽ ổn thôi, cứ để tôi đi đi....",
  "We encountered a serious highway blockage on the way into Danforth, and on the other side ... zombies. Tons of them. We've survived our first encounter, but we've got a lot further to go before we can rest, much less find this VIP that Colonel Peel ordered us to exfil.": "Chúng tôi gặp phải một vụ tắc nghẽn đường cao tốc nghiêm trọng trên đường vào Danforth, và ở phía bên kia ... zombie. Hàng tá bọn chúng. Chúng tôi đã sống sót qua cuộc chạm trán đầu tiên, nhưng chúng tôi còn phải đi một chặng đường dài nữa trước khi có thể nghỉ ngơi, chứ đừng nói đến việc tìm thấy tay VIP mà Đại tá Peel đã ra lệnh cho chúng tôi giải cứu.",
  "Look! Somewhere to hide!": "Nhìn kìa! Có nơi để trốn!",
  "Hayley": "Hayley",
  "You know, the zeds that feature enhanced person-murdering capabilities?": "Cậu biết đấy, lũ zed được nâng cấp khả năng tàn sát con người ấy?",
  "We don't have enough bullets for everybody.": "Chúng ta đéo có đủ đạn cho tất cả mọi người đâu.",
  "All right. You better get back out there and keep them from getting in.": "Được rồi. Tốt nhất là cậu nên quay ra đó và cản đéo cho chúng vào.",
  "Work can continue": "Công việc có thể tiếp tục",
  "LOG: The Nuke is Disarmed": "NHẬT KÝ: Quả Bom Hạt Nhân Đã Bị Vô Hiệu Hóa",
  "I ... I'd appreciate that, ma'am.": "Tôi ... tôi rất trân trọng điều đó, thưa cô.",
  "Played Sudoku": "Từng Chơi Sudoku",
  "Or we go check on those gunshots we heard.": "Hoặc là chúng ta đi kiểm tra những tiếng súng mà chúng ta vừa nghe thấy.",
  "Lane": "Lane",
  "Targets": "Các Mục Tiêu",
  "So you lost the asset? Were my orders unclear in any way, soldier?": "Vậy là cậu đã đánh mất tài sản đó? Mệnh lệnh của tôi có chỗ nào đéo rõ ràng sao, người lính?",
  "Sergeant Kilohana Young. My friend. Killed in action.": "Trung sĩ Kilohana Young. Bạn của tôi. Đã hy sinh trong lúc làm nhiệm vụ.",
  "We can't take that risk.": "Chúng ta đéo thể mạo hiểm như vậy được.",
  "Creates a couple of homemade box mines. Small chance of mishaps.": "Chế tạo một vài quả Mìn Hộp (Box Mines) tự chế. Có một tỷ lệ nhỏ xảy ra sự cố.",
  "Just ... show me where you think she went.": "Chỉ cần ... chỉ cho tôi thấy nơi mà cậu nghĩ cô ấy đã đi.",
  "Approaching the target.": "Đang tiến lại gần mục tiêu.",
  "Incendiary Barrage": "Oanh Tạc Đạn Cháy (Incendiary Barrage)",
  "Billy": "Billy",
  "They came out of nowhere! <Gunshots> I can't hold them off by myself!": "Bọn chúng từ đâu chui ra đéo biết! <Tiếng súng> Tôi đéo thể một mình cầm cự với bọn chúng được!",
  "Hey, did you ever serve with Captain Montressor? Now, there was a commanding officer who could give you some fucking nightmares.": "Này, cậu đã bao giờ phục vụ dưới quyền Đại úy Montressor chưa? Đấy mới là một người sĩ quan chỉ huy có thể mang đến cho cậu những cơn ác mộng chết tiệt thực sự.",
  "Calabro": "Calabro",
  "Gonna see how things look from higher ground.": "Sẽ đi xem xét tình hình xung quanh từ trên cao.",
  "Yo.": "Dô."
};

const file = 'output/languages/chunks/btxt_chunk_149.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_149.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk149[r.sourceText]) {
    r.translatedText = chunk149[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 149 successfully!');
