const fs = require('fs');
const chunk192 = {
  "Survivors, we have a caller.": "Những người còn sống sót (Survivors) thân mến, chúng ta đang có một thính giả gọi đến đài.",
  "There you go. Try not to scratch the paint.": "Của cậu đây. Cố gắng đừng có làm xước đi lớp sơn của nó đấy nhé.",
  "I grew up on their compound. Learned all that hardcore survival shit as a kid.": "Tôi đã lớn lên ở bên trong khu nhà của bọn họ. Đã học được tất cả những thứ kỹ năng sinh tồn (survival) hardcore chết tiệt đó ngay từ khi chỉ còn là một đứa trẻ.",
  "Keep fighting!": "Hãy tiếp tục chiến đấu đi!",
  "Jimenez": "Jimenez",
  "Upgrade to Shooting Platform": "Nâng cấp lên thành Bệ Nâng Để Đứng Bắn Súng (Shooting Platform)",
  "Civility is awesome.": "Sự văn minh là một điều vô cùng tuyệt vời.",
  "Sumbitch hits like a bulldozer!": "Thằng khốn nạn Sumbitch này húc mạnh giống hệt như một chiếc xe ủi đất vậy!",
  "You think they just... left?": "Cậu nghĩ là bọn họ chỉ đơn giản là đã... rời đi thôi sao?",
  "Brad": "Brad",
  "We don't have enough guns for everyone.": "Chúng ta đéo có đủ súng ống để cung cấp cho tất cả mọi người.",
  "There just isn't enough to eat here. If this keeps up, I... I can't stick around. -%1$s.": "Hiện tại ở đây đang đéo có đủ thức ăn cho tất cả mọi người. Nếu như tình hình này cứ tiếp tục diễn ra, tôi... tôi đéo thể nào gắn bó thêm với cái nơi này được nữa. -%1$s.",
  "We are blessed today.": "Ngày hôm nay chúng ta đã được ban phước lành.",
  "Resolution 720p": "Độ Phân Giải (Resolution) 720p",
  "Missions": "Các Nhiệm Vụ (Missions)",
  "This is going to sound dumb, but I feel like this place is more of a home than anyplace I ever lived before.": "Điều này nghe có vẻ hơi ngu ngốc một chút, nhưng tôi cảm thấy cái nơi này giống như là một mái ấm thực sự hơn bất cứ nơi nào mà tôi đã từng sống trước đây.",
  "We need to be more careful. Watch for hordes.": "Chúng ta cần phải tỏ ra cẩn thận hơn nữa. Hãy coi chừng những bầy zombie hordes.",
  "Lexi": "Lexi",
  "And I gotta admit, knowing that we're not the only ones that made it? Feels pretty good.": "Và tôi phải thừa nhận một điều là, khi biết được rằng chúng ta đéo phải là những người duy nhất còn sống sót được cho đến tận bây giờ? Cảm giác đó thực sự rất tuyệt vời.",
  "SURVIVAL TACTICS: Screamer": "CHIẾN THUẬT SINH TỒN (SURVIVAL TACTICS): Screamer",
  "Given any thought to our offer yet?": "Cậu đã suy nghĩ xong về lời đề nghị của chúng tôi chưa?",
  "Revolver: CLEO Revo C": "Súng Lục Ổ Quay (Revolver): CLEO Revo C",
  "Landon": "Landon",
  "We have to try not to blame ourselves. We've had to make a lot of tough decisions lately. We can't save everyone.": "Chúng ta phải cố gắng đừng tự đổ lỗi cho bản thân mình. Gần đây chúng ta đã phải đưa ra quá nhiều những quyết định vô cùng khó khăn. Chúng ta đéo thể nào cứu được tất cả mọi người.",
  "We're at the east end of Spencer's Mill. If you've got a map, the church should be on it.": "Chúng tôi hiện đang ở khu vực đầu phía đông của Spencer's Mill. Nếu như các người có trong tay một tấm bản đồ (map), thì nhà thờ (church) đó đáng lẽ ra phải nằm ở trên đó.",
  "Do you know what it's like out there? No, uh-uh, we'd get killed in a second! I'll stay here.": "Cậu có biết ở ngoài kia trông như thế đéo nào đéo? Đéo, uh-uh, chúng ta sẽ bị giết chết chỉ trong vòng một tích tắc mà thôi! Tôi sẽ ở lại đây.",
  "Knockdown Chance Increased!": "Tỉ Lệ Đánh Ngã Kẻ Địch (Knockdown Chance) Đã Được Tăng Lên Cmnr!",
  "Jacob was left to his fate.": "Jacob đã bị bỏ mặc cho số phận quyết định.",
  "Never made it home.": "Đéo bao giờ có thể quay trở về nhà được nữa.",
  "<Crying>": "<Đang khóc nức nở Crying>",
  "Those damn zombies left me with this ugly scar, and now nothing will ever be the same. Hey! Stop staring at it! Fuck you! (Touchy)": "Lũ zombies chết tiệt đó đã để lại cho tôi cái vết sẹo vô cùng xấu xí này, và giờ đây mọi thứ sẽ đéo bao giờ có thể trở lại được như lúc trước. Này! Dừng ngay cái việc nhìn chằm chằm vào nó đi! Địt mẹ mày! (Rất Dễ Đụng Chạm Touchy)",
  "Don't forget you still need to go get Doc from the Barrett place.": "Đừng quên rằng cậu vẫn còn phải đi đón Doc trở về từ trang trại của nhà Barrett đấy nhé.",
  "73 GENERIC Jack Trant": "73 CHUNG (GENERIC) Jack Trant",
  "Heather": "Heather",
  "On a Mission": "Đang Thực Hiện Một Nhiệm Vụ (Mission)",
  "As many as we can spare.": "Nhiều nhất có thể trong khả năng của chúng tôi.",
  "I'm gonna need an answer from you.": "Tôi sẽ cần phải nhận được một câu trả lời từ phía cậu đấy.",
  "Dalton": "Dalton",
  "You ever hear of dodging? You're not gonna survive letting them pile on like that.": "Cậu đã bao giờ nghe nói về kỹ năng né tránh (dodging) chưa hả? Cậu sẽ đéo thể nào sống sót được nếu như cứ để cho bọn chúng xúm lại tấn công hội đồng mình như vậy đâu.",
  "A friend of mine's gone missing.": "Một người bạn của tôi đã bị mất tích cmnr.",
  "Jesus, Doc! Not in front of everybody!": "Chúa ơi, Doc! Xin đừng làm chuyện đó ngay trước mặt của tất cả mọi người!",
  "Don't worry, I'll cover you from higher ground.": "Đừng lo lắng, tôi sẽ yểm trợ (cover) cho cậu từ vị trí cao hơn.",
  "Keep going at this rate, and we'll be back to using the booze to make firebombs. And that's just sad.": "Nếu cứ tiếp tục với cái tốc độ như thế này, chẳng mấy chốc chúng ta sẽ lại phải quay trở về với cái thời kỳ sử dụng rượu (booze) để chế tạo ra bom lửa mất thôi. Và điều đó thì thực sự rất đáng buồn.",
  "Captain Moustache": "Đội Trưởng Moustache",
  "Did you find anything out?": "Cậu có tìm hiểu ra được điều gì đéo?",
  "Holmes": "Holmes",
  "You lishten to me, hear...I haven't *hic* touched a drop of that shtuff in...um...letsh shee... (Can be Insensitive.)": "Mày hãy lang nghe tao nói đây, nghe chửa... Tao đã đéo *nấc* đụng tới một giọt nào của cái thướt đó trong... um... để xemk nào... (Đôi khi có thể Vô Tâm Insensitive.)",
  "Overwrite": "Ghi Đè (Overwrite)",
  "I saw their last chopper disappear into the sky.": "Tôi đã nhìn thấy chiếc máy bay trực thăng cuối cùng của bọn họ từ từ biến mất vào trong bầu trời.",
  "Heads up gang! Scouts are reporting a horde heading our way.": "Mọi người hãy chú ý! Những lính do thám (Scouts) vừa mới báo cáo lại rằng đang có một bầy zombie horde tiến thẳng về phía của chúng ta.",
  "Food Poisoning": "Ngộ Độc Thực Phẩm (Food Poisoning)",
  "Bickering": "Đang Cãi Vã (Bickering)",
  "Maybe to you. Little killin' sounds just fine right about now.": "Có lẽ là đối với cậu thôi. Một chút chém giết nghe có vẻ rất ổn vào ngay lúc này đấy.",
  "Diaz": "Diaz",
  "Cars make a lot of noise. When driving, consider parking AWAY from your destination so you don't draw zeds to you.": "Những chiếc xe ô tô (Cars) sẽ gây ra rất nhiều tiếng ồn. Khi lái xe, hãy cân nhắc đến việc đỗ xe TRÁNH XA (AWAY) khỏi vị trí điểm đến của bạn để đéo thu hút bọn zeds lao về phía của bạn.",
  "Gained +5 Ammo.": "Nhận Được +5 Đạn Dược (Ammo).",
  "Owens": "Owens",
  "Now, about that target ...": "Bây giờ, nói về cái mục tiêu đó ...",
  "A must-have.": "Một thứ bắt buộc phải có (must-have).",
  "You do whatever it is you do. Unlawfully seize real estate, loot the town blind, whatever.": "Cậu muốn làm cái đéo gì thì tùy cậu. Chiếm đoạt bất động sản một cách bất hợp pháp, cướp bóc thị trấn một cách mù quáng, bất kể điều gì cũng được.",
  "It was ... kind of inevitable, sir. He ... isn't very smart. Wasn't. Black Friday out.": "Chuyện đó ... giống như là một điều đéo thể tránh khỏi được, thưa ngài. Anh ta ... đéo được thông minh cho lắm. Đã từng là như vậy. Black Friday xin hết.",
  "You're perilously close to being unwelcome here.": "Cậu đang ở ranh giới rất mong manh của sự nguy hiểm về việc sẽ đéo còn được chào đón ở nơi này nữa đấy.",
  "Damn. How'd you learn to shoot like that?": "Chết tiệt. Cậu đã học được cách bắn súng (shoot) như vậy ở đâu thế hả?",
  "Medical Skills": "Các Kỹ Năng Y Tế (Medical Skills)",
  "Best place to start is probably the Courthouse. - %1$s": "Nơi tốt nhất để bắt đầu tìm kiếm có lẽ là khu Tòa Án (Courthouse). - %1$s",
  "Westen as in Westen Food Services. Maybe you've seen their trucks around?": "Westen giống như trong tên của công ty Dịch vụ Thực phẩm Westen (Westen Food Services). Có lẽ là cậu cũng đã từng nhìn thấy những chiếc xe tải của bọn họ ở quanh đây rồi?",
  "Anyway, this crazy fuck, I swear all he did was get drunk and pick fights. Didn't matter where, didn't matter with who.": "Dù sao thì, cái thằng điên khốn nạn này, tôi thề là tất cả những gì hắn ta từng làm đó là uống rượu say khướt và kiếm cớ để đánh nhau. Đéo quan trọng là ở đâu, đéo quan trọng là với kẻ nào.",
  "Disaster Preparedness Kit": "Bộ Dụng Cụ Chuẩn Bị Cho Thảm Họa (Disaster Preparedness Kit)",
  "Last mag!": "Băng đạn cuối cùng rồi!",
  "Fuck, you're persistent.": "Chết tiệt thật, cậu đúng là một kẻ dai như đỉa (persistent).",
  "RECRUIT HERO. Escort this survivor to join your community.": "CHIÊU MỘ ANH HÙNG (RECRUIT HERO). Hộ tống (Escort) người sống sót này về để gia nhập vào cộng đồng của bạn.",
  "Wild": "Hoang Dã (Wild)",
  "Bring our new friends home.": "Hãy đưa những người bạn mới của chúng ta trở về nhà đi.",
  "With all due respect, sir, don't we need civilians? Especially if we're going to rebuild the world from scratch.": "Với tất cả sự tôn trọng, thưa ngài, đéo phải là chúng ta cũng cần đến những người dân thường (civilians) sao? Đặc biệt là nếu như chúng ta thực sự dự định sẽ tái thiết lại thế giới này từ hai bàn tay trắng.",
  "Honeycutt": "Honeycutt",
  "How long do you figure our stocks will last at this rate?": "Cậu nghĩ xem kho dự trữ của chúng ta sẽ có thể cầm cự được trong khoảng bao lâu nữa với cái tốc độ như thế này?",
  "There's gotta be an actual doctor we could get to run the infirmary, right?": "Chắc chắn là phải có một vị bác sĩ thực sự nào đó mà chúng ta có thể nhờ đến để điều hành cái bệnh xá (infirmary) này, có đúng đéo?",
  "So maybe we oughta go back and get their guns? For me and Marcus?": "Vậy có lẽ chúng ta nên quay trở lại đó và lấy những khẩu súng của bọn họ? Dành cho tôi và Marcus?",
  "Has been preparing for this her whole life. On her Xbox.": "Đã luôn chuẩn bị sẵn sàng cho những tình huống như thế này trong suốt toàn bộ cuộc đời của cô ấy. Ở trên chiếc máy chơi game Xbox của cô ấy.",
  "A very rare, iconic suppressed rifle from WWII. this working model was embellished as a gift.": "Một khẩu súng trường được gắn ống giảm thanh mang tính biểu tượng, cực kỳ quý hiếm từ thời kỳ Thế Chiến 2 (WWII). Mô hình hoạt động này đã được tô điểm để được sử dụng như là một món quà tặng.",
  "The Scientist": "Nhà Khoa Học (The Scientist)",
  "This isn't the Wild West. You want to trade with us, you'll keep your guns holstered and mind your manners.": "Đây đéo phải là khu vực Miền Tây Hoang Dã (Wild West) đâu. Nếu các người muốn tiến hành giao dịch (trade) với chúng tôi, các người sẽ phải cất gọn súng vào trong bao da và chú ý đến thái độ cư xử của bản thân mình đấy.",
  "You and me, boss? We're done.": "Ông và tôi, thưa ông chủ? Chúng ta coi như đã kết thúc tại đây cmnr.",
  "Farmhouse Kitchen": "Khu Nhà Bếp Của Trang Trại (Farmhouse Kitchen)",
  "Open the Journal [ul_journal_menu] and upgrade your Radio Post to Sat-Comms to reestablish contact with HQ.": "Hãy mở Cổ Nhật Ký (Journal) [ul_journal_menu] lên và tiến hành nâng cấp Trạm Phát Sóng Radio (Radio Post) của bạn lên thành Thiết Bị Liên Lạc Vệ Tinh (Sat-Comms) để có thể thiết lập lại được đường truyền liên lạc với Trụ Sở Chính (HQ).",
  "Saavedra": "Saavedra",
  "Anybody home?": "Có ai ở nhà đéo?",
  "And in other news, it turns out a bunch of our food just spoiled.": "Và trong một diễn biến khác, hóa ra là một đống lượng thức ăn (food) của chúng ta đã vừa bị thiu hỏng cmnr.",
  "Unlocks the ability to create Whistling Box Mines. REQUIRES A WEAPONS LAB.": "Mở khóa khả năng có thể chế tạo ra loại Mìn Hộp Có Tiếng Còi Hú (Whistling Box Mines). YÊU CẦU PHẢI CÓ MỘT PHÒNG THÍ NGHIỆM VŨ KHÍ (WEAPONS LAB).",
  "No, no, don't worry about it. We can manage just fine.": "Đéo, đéo, cậu đéo cần phải bận tâm về chuyện đó đâu. Chúng tôi có thể tự mình xoay sở ổn thỏa được mà.",
  "Only one more of that.": "Chỉ còn lại một cái duy nhất nữa của thứ đó thôi.",
  "These zeds really know how to hide a body.": "Lũ zeds này thực sự rất biết cách làm thế nào để có thể giấu đi một cái xác đấy.",
  "Nothing worth mentioning.": "Chẳng có gì đáng để đề cập đến cả.",
  "Come home when you have a chance.": "Hãy quay trở về nhà ngay khi cậu có cơ hội nhé.",
  "Goff": "Goff",
  "Strangers": "Những Người Lạ Mặt (Strangers)",
  "Don't you worry about it. We're happy to help.": "Cậu đéo cần phải bận tâm về chuyện đó đâu. Chúng tôi rất vui lòng khi có thể được giúp đỡ mà.",
  "Can you give me a hand?": "Cậu có thể giúp cho tôi một tay được đéo?",
  "Don't you think that's something you should ask her yourself?": "Cậu đéo nghĩ rằng đó là điều mà chính bản thân cậu nên trực tiếp hỏi cô ấy sao?",
  "Labels": "Nhãn Mác (Labels)"
};

const file = 'output/languages/chunks/btxt_chunk_192.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_192.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk192[r.sourceText]) {
    r.translatedText = chunk192[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 192 successfully!');
