const fs = require('fs');
const chunk188 = {
  "Oh yeah, better check that place out soon.": "Oh đúng rồi, tốt hơn hết là nên đến kiểm tra nơi đó sớm đi.",
  "PERSONAL SKILL. One does not use a dessert spoon to scoop up zombie brains.": "KỸ NĂNG CÁ NHÂN (PERSONAL SKILL). Đéo ai lại sử dụng một chiếc thìa ăn tráng miệng để múc bộ não của bọn zombies cả.",
  "Kilo, did you ... ever get through to your wife?": "Kilo, cậu đã ... từng liên lạc được với vợ của mình đéo?",
  "I've got plenty of energy already.": "Tôi đã có đủ mức năng lượng (energy) cmnr.",
  "Zombie horde spotted.": "Đã phát hiện thấy có một bầy zombie (horde).",
  "This looks like a good spot for an outpost.": "Nơi này có vẻ là một địa điểm lý tưởng để thiết lập một Tiền Đồn (outpost) đấy.",
  "The Cleo beacon is broadcasting now. More strings of numbers.": "Trạm phát tín hiệu Cleo hiện đang phát sóng. Lại có thêm một vài chuỗi số nữa.",
  "%3$s needs somebody to create a distraction for them. Got any noisemakers? -%2$s": "%3$s đang cần người để tạo ra sự phân tâm nhằm đánh lạc hướng cho bọn họ. Có thiết bị tạo tiếng ồn (noisemakers) đéo? -%2$s",
  "You in the Army?": "Cậu là người trong Quân Đội (Army) à?",
  "Sounds like the whole operation is AFU. We're gonna drive on. Do I have a volunteer to commandeer that vehicle?": "Nghe có vẻ như toàn bộ chiến dịch này đã bị AFU (hủy bỏ hoàn toàn) cmnr. Chúng ta sẽ tiếp tục lái xe. Có ai tình nguyện trưng dụng chiếc xe (vehicle) đéo đéo?",
  "Let me spell it out for you. You're a dick. And I'm awesome.": "Hãy để tôi nói thẳng ra cho cậu hiểu nhé. Cậu đúng là một thằng khốn nạn. Và tôi thật là tuyệt vời.",
  "Rusty Sedan": "Chiếc Xe Sedan Rỉ Sét (Rusty Sedan)",
  "My dad was up there that day. You know, my dad who's been missing ever since?": "Bố tôi đã ở trên đó vào ngày hôm đó. Mọi người có biết rằng, bố tôi đã bị mất tích kể từ đó đéo?",
  "Choose": "Chọn",
  "Hypochondriac": "Chứng Bệnh Hoang Tưởng (Hypochondriac)",
  "Eggleston": "Eggleston",
  "When this is all over, I should run for President!": "Khi mọi chuyện đã kết thúc, tôi nên ra tranh cử cho chức vụ Tổng Thống mới được!",
  "%d added to Supply Locker. (Poor food supply.)": "%d đã được thêm vào Tủ Khóa Tiếp Tế (Supply Locker). (Nguồn cung cấp thức ăn food quá nghèo nàn.)",
  "PhD in Pathophysiology. Senior fellow at the Danforth Institute for Progress. Possibly our last hope for survival.": "Tiến sĩ ngành Sinh lý bệnh học (Pathophysiology). Thành viên cấp cao tại Viện Tiến Bộ Danforth. Có thể ông ấy chính là hy vọng sống sót cuối cùng của chúng ta.",
  "Labor": "Lao Động (Labor)",
  "[message looping tone] One one tango mike papa two five foxtrot zero five oscar.": "[âm báo lặp tin nhắn] One one tango mike papa two five foxtrot zero five oscar.",
  "Jammed": "Bị Kẹt Đạn (Jammed)",
  "I've been saying, and saying it, and saying it forever. We need a kitchen. I'm sick and tired of eating cold processed meat all the time. It sucks.": "Tôi đã nói đi nói lại mãi rồi, và sẽ luôn lặp lại điều đó mãi mãi. Chúng bản cần có một cái nhà bếp (kitchen). Tôi đã quá phát ốm và mệt mỏi với việc lúc đéo nào cũng phải ăn cái món thịt nguội đóng hộp đéo khỉ này cmnr. Chuyện này thật tồi tệ vãi cả cứt.",
  "Aeschylus said that. And an envious man is a man who'll spread rumors about his neighbors.": "Aeschylus đã từng nói như vậy. Và một người đàn ông có tính đố kỵ là một người sẽ đi phát tán những tin đồn về những người hàng xóm của anh ta.",
  "Hope you're sitting down for this one.": "Hy vọng là cậu đã ngồi xuống để chuẩn bị nghe tin này.",
  "Oh, and all we have to do is let people die? Get off the radio, soldier.": "Oh, và tất cả những gì chúng ta có thể làm đó là cứ để cho mọi người phải chết sao? Hãy tắt ngay cái đài radio này đi, hỡi người lính.",
  "A place to make the things we need.": "Một nơi để chế tạo ra những thứ mà chúng ta đang rất cần.",
  "Already planted!": "Đã được trồng (planted) rồi!",
  "Might want to start here. He always did love the place. I think his parents owned it.": "Có lẽ nên bắt đầu tìm kiếm từ đây. Anh ta luôn luôn yêu thích cái nơi này. Tôi nghĩ bố mẹ của anh ta chính là chủ sở hữu của nó.",
  "Affiliate Value": "Giá Trị Thành Viên (Affiliate Value)",
  "Forgot about that. Good catch.": "Quên mất chuyện đó đi. Bắt tốt lắm.",
  "Dear Colin, I'm leaving you. I can't take the lies, or the paranoia, or the constant harping about government conspiracy. I'm going to stay with my mother up north. Don't try to find me. - Elsa. P.S. I took all your guns, your ammo, and your ridiculous MREs and I threw them in the river. Serves you right, you pig.": "Gửi Colin, em sẽ rời xa anh đây. Em đéo thể tiếp tục chịu đựng thêm những lời dối trá, hoặc sự hoang tưởng, hoặc những lời lải nhải không ngừng nghỉ về những thuyết âm mưu của chính phủ. Em sẽ chuyển đến sống cùng với mẹ em ở phía bắc. Đừng có cố gắng tìm kiếm em nữa. - Elsa. Tái bút (P.S). Em đã lấy đi tất cả những khẩu súng của anh, cả lượng đạn dược của anh, và những khẩu phần ăn quân sự MRE nực cười của anh nữa và em đã quăng tất cả mọi thứ xuống sông rồi. Đáng đời anh lắm, đồ con lợn thối tha.",
  "Supply Run": "Chạy Đi Thu Thập Tiếp Tế (Supply Run)",
  "Huh. Little plastic watch with cartoon fish on it. Perfect.": "Huh. Một chiếc đồng hồ đeo tay nhỏ bằng nhựa có hình ảnh chú cá hoạt hình trên đó. Hoàn hảo.",
  "The Home page is where you can view, build, and upgrade your Community's Facilities. Use the D-Pad to select a Facility Slot and press [xi_a] to get more information about the bonuses it provides and the actions available.\r\nAn Infirmary is critical when it comes to dealing with disease and injury; a Workshop is necessary to keep your gear in working order; a Latrine helps stave off disease, etc.": "Trang Chủ (Home page) là nơi bạn có thể xem xét, xây dựng (build), và nâng cấp (upgrade) các Cơ Sở Vật Chất (Facilities) cho Cộng Đồng của bạn. Sử dụng nút D-Pad để lựa chọn một Khu Vực Xây Dựng (Facility Slot) và ấn [xi_a] để biết thêm những thông tin chi tiết về các chỉ số phần thưởng bổ sung mà nó có thể mang lại cũng như những tính năng hiện có sẵn.\r\nMột Bệnh Xá (Infirmary) là một yếu tố cực kỳ quan trọng khi giải quyết các vấn đề liên quan đến bệnh tật (disease) và thương tích (injury); một Xưởng Chế Tạo (Workshop) là thứ rất cần thiết để duy trì cho các thiết bị của bạn luôn luôn ở trong tình trạng hoạt động tốt nhất; một Nhà Vệ Sinh Công Cộng (Latrine) sẽ giúp ngăn chặn sự lây lan của bệnh dịch, v.v.",
  "Barricade (Hold)": "Chặn Cửa Gỗ Barricade (Giữ Thao Tác)",
  "All I could do was hole up in an empty house and hope that they got bored.": "Tất cả những gì tôi có thể làm đó là cố gắng trốn chui trốn nhủi trong một ngôi nhà trống và hy vọng rằng bọn chúng sẽ cảm thấy nhàm chán và bỏ đi.",
  "Play as new user? You will return to the title screen without saving.": "Chơi như một người dùng mới (new user)? Bạn sẽ ngay lập tức được quay trở lại màn hình tiêu đề (title screen) mà đéo cần phải lưu game.",
  "Use the time between sieges to complete missions and build up your base.": "Hãy sử dụng khoảng thời gian trống ở giữa các cuộc bao vây (sieges) để hoàn thành các nhiệm vụ (missions) và xây dựng, củng cố thêm sức mạnh cho căn cứ (base) của bạn.",
  "Ask about Fuel Caches": "Hỏi thăm thông tin về Vị Trí Của Nhiên Liệu (Fuel)",
  "Investigate the Tunnel": "Điều Tra Khu Vực Đường Hầm (Tunnel)",
  "Wow, just let me say, you are awesome. Seriously.": "Wow, hãy cho phép tôi nói điều này, cậu thực sự rất tuyệt vời. Nghiêm túc đấy.",
  "The zeds ain't done yet!": "Bọn zeds vẫn chưa xong chuyện đâu!",
  "Why are we being so passive?": "Tại sao chúng ta lại có thể tỏ ra thụ động đến như vậy?",
  "A full-auto version of the G17 with a high capactiy magazine, calssified as an SMG.": "Đây là một phiên bản chế độ bắn hoàn toàn tự động (full-auto) của khẩu G17 cùng với một băng đạn có sức chứa lớn, được phân loại như là một khẩu súng tiểu liên (SMG).",
  "No longer Weak with Hunger. (-1 Daily Ration of Food)": "Đéo Còn Cảm Thấy Mệt Mỏi Khả Hạn Do Bị Đói Khát (Weak with Hunger). (-1 Khẩu Phần Ăn Food Hàng Ngày)",
  "Ranger Station": "Trạm Kiểm Lâm (Ranger Station)",
  "Yeah": "Yeah",
  "Brody": "Brody",
  "Last magazine. Better make it count.": "Băng đạn cuối cùng rồi. Tốt hơn hết là đừng có để phí phạm phát súng nào.",
  "You fuckin' done yet?": "Mày đã làm xong cái chuyện khốn khiếp đó chưa đéo?",
  "Sorry to take so long. Thanks for watching out for me.": "Xin lỗi vì tôi đã mất quá nhiều thời gian. Cảm ơn cậu vì đã để mắt trông chừng hộ cho tôi nhé.",
  "These things burn through clips like you wouldn't believe. So carry lots of clips.": "Những thứ này có thể bắn hết sạch băng đạn nhanh đến mức cậu đéo thể nào tin được đâu. Vì vậy hãy mang theo thật nhiều băng đạn dự trữ nhé.",
  "Bang, motherfucker!": "Bằng, chết mẹ mày đi thằng khốn!",
  "Gotta stop making so much noise.": "Phải dừng lại việc gây ra quá nhiều tiếng ồn cmnr.",
  "Approaching base now with a full rucksack": "Tôi hiện đang tiến lại gần khu vực căn cứ (base) cùng với một chiếc balo (rucksack) đã chứa đầy ắp đồ",
  "I... Thank you.": "Tôi... Xin cảm ơn cậu.",
  "Hey Lily, how's it going back at home?": "Này Lily, tình hình ở nhà hiện tại đang diễn ra thế nào rồi?",
  "CONTACT: Medical Advice": "LIÊN HỆ (CONTACT): Lời Khuyên Về Y Tế (Medical Advice)",
  "You've been a big help around here. Seems only fair we return the favor.": "Cậu đã giúp đỡ cho chúng tôi được rất nhiều việc ở nơi này rồi đấy. Có vẻ như chúng tôi cũng nên đền đáp lại ơn huệ này để cho công bằng chứ nhỉ.",
  "Great, another fuckup.": "Tuyệt vời vãi cả lồn, lại thêm một rắc rối khốn kiếp nữa.",
  "Robbie": "Robbie",
  "Ylvisaker": "Ylvisaker",
  "Now she needs our help.": "Bây giờ cô ấy đang cần đến sự giúp đỡ của chúng ta đấy.",
  "Neighbors Discovered": "Đã Tìm Thấy Những Người Hàng Xóm (Neighbors)",
  "Always good to have more troops on the line.": "Sẽ luôn luôn là một điều tốt nếu như chúng ta có thêm số lượng quân lính đồn trú ở trên tiền tuyến.",
  "Funny thing about people they don't much like to challenge their assumptions.": "Có một điều nực cười về con người đó là họ đéo thực sự thích thử thách những giả định của chính bản thân mình.",
  "Trapped in an infested site.": "Bị mắc kẹt ở bên trong một khu vực Ổ Dịch (infested site).",
  "We need more materials before we can even think about a project that big.": "Chúng ta sẽ cần phải thu thập thêm nhiều vật liệu xây dựng (materials) trước khi có thể nghĩ đến việc thực hiện một dự án (project) với quy mô lớn như vậy.",
  "We found a surviving soldier.": "Chúng tôi đã tìm thấy một người lính (soldier) còn sống sót.",
  "Lately I find myself coming out here more and more regular. Talking to her sets my mind at ease.": "Gần đây tôi nhận thấy bản thân mình thường xuyên phải ra ngoài này nhiều hơn. Việc được nói chuyện với cô ấy đã giúp cho tâm trí của tôi cảm thấy thoải mái đi được phần nào.",
  "I've got some bad news.": "Tôi có một vài tin xấu đây.",
  "I want to show people that this fucked-up world still has some beauty left. (Handy with Arts and Crafts.)": "Tôi muốn chứng minh cho mọi người thấy rằng cái thế giới đéo nát bét này vẫn còn sót lại đôi chút những điều tốt đẹp. (Là một người rất Khéo Léo Handy đối với các lĩnh vực thuộc bộ môn Nghệ Thuật Arts và Thủ Công Crafts.)",
  "Looks empty now.": "Bây giờ trông có vẻ rất trống rỗng (empty).",
  "Light support weapon with serious combat history.": "Vũ khí hỗ trợ hạng nhẹ (Light support weapon) mang đậm bề dày lịch sử chiến đấu.",
  "We've got zombies at the towers!": "Chúng ta đang bị bọn zombies tấn công tại khu vực những tòa tháp!",
  "If we added some more safety features to the workshop, we could start building some more sophisticated explosives.": "Nếu chúng ta nâng cấp thêm một số tính năng an toàn cho cơ sở nhà xưởng (workshop), chúng ta có thể bắt đầu sản xuất ra thêm một số những loại vật liệu nổ tinh vi và phức tạp hơn.",
  "Attracts attention.": "Thu hút rất nhiều sự chú ý.",
  "Diana": "Diana",
  "SitRep: Iceland": "Báo Cáo Tình Hình (SitRep): Quốc đảo Iceland",
  "Brenden": "Brenden",
  "We'll have better luck if you can keep them outside.": "Chúng ta sẽ may mắn hơn rất nhiều nếu như cậu có thể giữ cho bọn chúng ở phía bên ngoài đấy.",
  "Requires PHONE BANK.": "Yêu cầu phải có NGÂN HÀNG ĐIỆN THOẠI (PHONE BANK).",
  "I mean, hell, I hate going out there just to find food.": "Ý tôi là, chết tiệt thật, tôi rất ghét việc phải ra ngoài kia chỉ để đi tìm kiếm thức ăn (food) đấy.",
  "What does he want?": "Anh ta đang muốn đéo gì cơ?",
  "All I know is when my dad's insurance wouldn't cover my treatment Ray shows up at our place one night with an envelope full of cash.": "Tất cả những gì tôi biết đó là khi số tiền bảo hiểm của bố tôi đéo đủ để chi trả cho các khoản điều trị của tôi thì Ray đã xuất hiện ở nhà của chúng tôi vào một đêm muộn cùng với một phong bì chứa đầy tiền mặt.",
  "You're not gonna hurt me are you?": "Các người sẽ đéo làm hại tôi đâu, có đúng đéo?",
  "START MISSION. Kill this community member before it's too late.": "BẮT ĐẦU NHIỆM VỤ (START MISSION). Hãy giết chết ngay thành viên này của cộng đồng trước khi mọi chuyện trở nên quá muộn màng.",
  "So come on over and see what the Army's been hiding.": "Hãy đến đây và tận mắt xem thử Quân Đội đang cất giấu bí mật gì nào.",
  "Exterminate a Feral": "Tiêu Diệt Một Con Feral",
  "Runners In Trouble": "Người Chạy Đi Thu Thập Tiếp Tế (Runners) Đang Gặp Rắc Rối",
  "That's what neighbors are for.": "Đó chính là lý do vì sao chúng ta cần đến những người hàng xóm (neighbors).",
  "Deep core samples. Muscle, bone, brain tissue, all I can carry. We gotta know what makes him tick.": "Những mẫu lõi sâu. Các mô cơ, xương cốt, và mô não, tất cả những thứ mà tôi có thể mang theo. Chúng ta cần phải tìm hiểu chính xác xem đéo gì đã khiến cho hắn ta có những phản ứng đó.",
  "You could come stay with us if you want.": "Cậu có thể đến sống cùng với chúng tôi nếu như cậu muốn.",
  "Was trying to get a fresh start.": "Đang cố gắng để bắt đầu làm lại một cuộc đời mới.",
  "We keep growing at this rate, and by the time this blows over we'll be our own little mini-country.": "Chúng ta cứ tiếp tục phát triển với tốc độ như thế này, và cho đến lúc mọi chuyện đéo tồi tệ này kết thúc thì chúng ta sẽ có thể trở thành một đất nước thu nhỏ của riêng mình mất.",
  "AMMO is the primary trade currency and is key for survival.": "ĐẠN DƯỢC (AMMO) chính là loại tiền tệ trao đổi (currency) cơ bản và cũng là chiếc chìa khóa tối quan trọng để có thể sống sót sinh tồn (survival).",
  "Steady... find your bead... take your shot...": "Giữ vững tay súng nào... hãy ngắm bắn... bóp cò đi...",
  "Fatima": "Fatima",
  "Primers": "Thuốc Súng (Primers)"
};

const file = 'output/languages/chunks/btxt_chunk_188.json';
const c = JSON.parse(fs.readFileSync(fs.existsSync(file) ? file : 'input/languages/chunks/btxt_chunk_188.json', 'utf8'));
for(const r of c.replacements) {
  if(chunk188[r.sourceText]) {
    r.translatedText = chunk188[r.sourceText];
  }
}
fs.writeFileSync(file, JSON.stringify(c, null, 2), 'utf8');
console.log('Translated Chunk 188 successfully!');
